### ISSUE TITLE
[question] Can typedoc be used for JS projects that have TS typings?

### ISSUE THREAD

**Issue by papb** [TypeStrong/typedoc#1002]
First of all, sorry for asking a question in the issue tracker. I have checked the [contributing guidelines](https://github.com/TypeStrong/typedoc/blob/master/CONTRIBUTING.md) but I didn't see any mention to a preferred way to ask a question.

To the point: is it possible to use typedoc to generate documentation from a project which is not written in TypeScript but which provides typescript typings? In other words, is it possible to generate documentation from comments present in `*.d.ts` files only?

I am asking to see if typedoc would be an option for documenting [SequelizeJS](https://github.com/sequelize/sequelize).

**Comment by Gerrit0** [comment]
TypeDoc can document declaration files, so yes you could use it to generate documentation as you describe. You will probably need a combination of `--includeDeclarations` and `--exclude` to ignore anything in `node_modules`

**Comment by Gerrit0** [comment]
Closing as it appears this has been answered satisfactorily and is in the hands of the SequelizeJS maintainers.
