### ISSUE TITLE
Nested parameters description doesn't work with arrow functions

### ISSUE THREAD

**Issue by jiri-vyc** [TypeStrong/typedoc#1003]
- [ ] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
TypeDoc should generate description for nested "options" parameter. E.g. options.first, options.second and options.third in `options: { first: string, second: number, third: (a: number) => number }`

## Actual Behavior
Doesn't generate description for nested parameters. Only for the "options" object.

## Steps to reproduce the bug

Code to document:
```
class Bar {
    /**
     * Test method with object param
     * @param options Describing the options param
     * @param options.first A description of the first property of the options param
     */
    public fooArrow = (options: { first?: string, second: number, third: (a: number) => number }) => {

    }
}
```

Typedoc command:
`typedoc --out docs index.ts`

Typedoc.json:
```
{
    "mode": "modules",
    "out": "docs"
}
```

Should generate documentation with description of `option.first` nested parameter, instead generates only for `options`.

It works perfectly well with the function written normally, but arrow notation doesn't work. I.e.:
```
class Bar {
    /**
     * Test method with object param
     * @param options Describing the options param
     * @param options.first A description of the first property of the options param
     */
    public fooArrow (options: { first?: string, second: number, third: (a: number) => number })  {

    }
}
```

generates 

```
options: object
Describing the options param

Optional first?: undefined | string
A description of the first property of the options param
```

while

```
class Bar {
    /**
     * Test method with object param
     * @param options Describing the options param
     * @param options.first A description of the first property of the options param
     */
    public fooArrow = (options: { first?: string, second: number, third: (a: number) => number }) => {

    }
}
```

generates only

```
options: object
Describing the options param

Optional first?: undefined | string
```

Complete sample code to reproduce the bug and sample output documentation here: https://github.com/jiri-vyc/typedoc-test

(with comparison with standard and arrow function notation)

This is afaik not a duplicate of https://github.com/TypeStrong/typedoc/issues/987 nor https://github.com/TypeStrong/typedoc/issues/497

## Environment
  - Typedoc version: 0.14.2
  - Node.js version: v10.15.1
  - OS: Windows 10 Pro

**Comment by fc** [comment]
FYI, the repro ( `jiri-vyc/typedoc-test` ) is missing a `package.json`

**Comment by jiri-vyc** [comment]
@fc Added.

Also, I found an issue describing the same problem, including temporary workaround: https://github.com/TypeStrong/typedoc/issues/522, so this can be probably closed as duplicate.

**Comment by Gerrit0** [comment]
In 0.20, this appears to work as expected. The first codeblock generates this:

![image](https://user-images.githubusercontent.com/19329837/103257950-8014f300-4950-11eb-9f93-e193823595da.png)
