### ISSUE TITLE
Support for ES2017 as target

### ISSUE THREAD

**Issue by tvvignesh** [TypeStrong/typedoc#1004]
First of all, thanks for the great work you guys are doing with this project. I noticed in the API docs here: https://typedoc.org/api/ that there is no option for ES2017 as target - Currently Typedoc works for me in ES6 and I am moving to ES2017. 

Is there anything to be done from my end to make it work for ES2017 as well? 

Thanks.

**Comment by Gerrit0** [comment]
Just pass `--target ES2017`. The docs don't specify this clearly, but that option is just passed through to the TypeScript compiler, so any options for the compiler will also be accepted by TypeDoc.

**Comment by aciccarello** [comment]
Yeah, that typescript option should be available already. If you are having issues getting it to work, please reopen this issue and give some information to help us reproduce the problem.
