### ISSUE TITLE
Showcase different themes

### ISSUE THREAD

**Issue by resistdesign** [TypeStrong/typedoc#1005]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
I'm not sure what this outputs based on what I see at the website or this repo.

## Suggested Solution
It would be good to have an examples or showcase section on the website.

**Comment by resistdesign** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/c7485269-9eb6-4c88-ab79-859e3eff4c96-f6015c14-0ab2-4e71-a6b3-ba909b600d57-v1.png?transparent=1&palette=1&width=246)

**Comment by aciccarello** [comment]
Thanks for the feedback. Could you be a little more descriptive? We already have the [API docs](https://typedoc.org/api/). What different pieces would you like to see examples of?

**Comment by giannif** [comment]
@aciccarello is there a showcase of themes? I just found typedoc today, and am wondering if there are themes besides minimal and default that perhaps change the colors. I randomly tried two themes locally (`typedoc-clarity-theme`, `typedoc-twilio-theme`), but they didn't seem to do anything, so I'm confused. Would appreciate any guidance

**Comment by Gerrit0** [comment]
@giannif just installing the theme won't change anything, you need to pass the theme path with the `--theme` option to use themes.

**Comment by resistdesign** [comment]
@aciccarello Yeah, I thought there might be some themes and just was thinking there would be an example section like you might find on other sites for projects like this.

**Comment by giannif** [comment]
@Gerrit0 yeah, that's what I meant, using the `--theme` option does nothing with custom themes. I found this [theme](https://github.com/Horyus/typedoc-vortex-theme), which is a nice, obvious dark theme, and I see no changes. 

Using `minimal` works
```bash
typedoc --theme minimal --out docs/ ./src
```

These do nothing:
```bash
typedoc --theme ./node_modules/typedoc-thunder-theme/bin --out docs/ ./src
typedoc --theme ./node_modules/typedoc-twilio-theme/bin --out docs/ ./src
typedoc --theme ./node_modules/typedoc-clarity-theme/bin --out docs/ ./src
```

The output is always the same:
```
Using TypeScript 3.2.4 from /Users/MyProject/node_modules/typedoc/node_modules/typescript/lib
Rendering [========================================] 100%

Documentation generated at /Users/MyProject/docs

**Comment by Gerrit0** [comment]
I haven't looked at all the themes you linked, but the vortex theme has both a default and a minimal theme included in it. You can use it like this:

```bash
typedoc --theme ./node_modules/typedoc-vortex-theme/bin/default ./src
# or
typedoc --theme ./node_modules/typedoc-vortex-theme/bin/minimal ./src
```

The other themes likely have the same structure, so you need to append /minimal or /default.

**Comment by giannif** [comment]
@Gerrit0 whoa! yes that works. amazing!

Okay, so `vortex` does not throw an error with `/bin`, which threw me off there. 

`clarity` and `twilio` _only_ compile with `/bin`, but I can't tell if the theme was actually applied since there are no visual changes, or it works just like `vortex` does with `/bin` which is compiling successfully but not using the theme. 

Overall, a bit confusing

**Comment by aciccarello** [comment]
Could add this theme as well
https://github.com/pirix-gh/eledoc

**Comment by Gerrit0** [comment]
I've considered doing this a couple times, and ended up coming to the conclusion that this is not something I want to maintain. Adding this would mean that every time we do a release I have to manually confirm that the output of the themes in the showcase is valid (just because it ran doesn't mean that the output is *right*)
