### ISSUE TITLE
yarn install generates warning

### ISSUE THREAD

**Issue by fr0** [TypeStrong/typedoc#1010]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

No warnings.

## Actual Behavior

If your `package.json` contains a reference to typedoc:

```
warning typedoc > @types/handlebars@4.1.0: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.
```

## Steps to reproduce the bug

```
  "devDependencies": {
    "typedoc": "^0.14.2"
  },
```

## Environment
  - Typedoc version: 0.14.2
  - Node.js version: 11.12.0
  - OS: Mac OS 10.13.6

**Comment by aciccarello** [comment]
Thanks for the report. This could be fixed at the same time as #986

**Comment by fr0** [comment]
This was closed a month and a half ago, but I'm still seeing the issue.

**Comment by Gerrit0** [comment]
There hasn't been a release for over a month and a half.

**Comment by fr0** [comment]
That seems like a problem, can there be a new release soon?
