### ISSUE TITLE
How to document a anonymous function

### ISSUE THREAD

**Issue by ChTosar** [TypeStrong/typedoc#1013]
Is there no way to comment and document anonymous functions?

**Comment by Gerrit0** [comment]
By anonymous function, do you mean a function declaration assigned to a variable? #998 Or arrow functions in a class? #1003. If neither of these, what does the code look like you are trying to document?

**Comment by ChTosar** [comment]
In this case it is an arrow function to declare an entry point in the express router
`````
router.get('/', (req, res) => {

    /**
     * Some description
     * @param req Request object
     * @param res Response object
     */
`````

**Comment by aciccarello** [comment]
@ChTosar Since that is an expression and not a function declaration, it can't be documented.

To document that callback you would need to define it separately from the expression where it is registered.

```typescript

/**
 * Some description
 * @param req Request object
 * @param res Response object
 */
function callbackName (req, res) {
 // ...
}

router.get('/', callbackName);
```

**Comment by ChTosar** [comment]
I know but... that's not cool 😢

**Comment by Gerrit0** [comment]
I'm a bit confused as to why you would document that function in the first place. It's not exposed anywhere. What purpose would including it in your documentation serve?

**Comment by ChTosar** [comment]
Because there is the declaration of a petition and I want to document them.
But maybe i need something like swagger-jsdoc for this purpose

**Comment by aciccarello** [comment]
@ChTosar Yeah, TypeDoc is designed more for documenting source code. To document a REST API, something to generate swagger docs would likely be a better solution with more features you would like.
