### ISSUE TITLE
Support TypeScript 3.4

### ISSUE THREAD

**Issue by fr0** [TypeStrong/typedoc#1015]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

My app code uses `globalThis`, which is a new feature in TypeScript 3.4. Unfortunately, typedoc is using an old version of TS which doesn't know about it, and it breaks on my project.

```
Using TypeScript 3.2.4 from C:\ProgramData\Jenkins\workspace\atlas-dev-api\node_modules\typedoc\node_modules\typescript\lib
Error: C:/ProgramData/Jenkins/workspace/atlas-dev-api/src/step-identity.ts(12)
 Cannot find name 'globalThis'.
```

## Suggested Solution

Upgrade TypeDoc to use the latest version of TypeScript.

**Comment by just-boris** [comment]
The fix for this has already been merged ~2 weeks ago: https://github.com/TypeStrong/typedoc/pull/1014

We just need to ask maintainers about their plan to publish a release.

**Comment by nalply** [comment]
Const assertions seem not to work yet with the current version (0.15.0-0).

```text
Error: /some-path/some-file.ts(11)
 Cannot find name 'const'.
```

for source like this

```typescript
const composites = [ 'list', 'dir' ] as const
```

**Comment by fc** [comment]
I'm also affected by a 3.4 issue that is described here:
https://github.com/Microsoft/TypeScript/issues/30153

If someone really needs it (like me...) you can do the following:
```
git clone https://github.com/TypeStrong/typedoc.git
cd typedoc
npm install
```
Then, generate the docs:

**Comment by shihlinlu** [comment]
Thanks @fc for the workaround. Does anyone know when the maintainers will publish the release to support 3.4?

**Comment by crhistianramirez** [comment]
This should be closed. Resolved here:
https://github.com/TypeStrong/typedoc/issues/1068
