### ISSUE TITLE
--excludeNotExported excludes export equals

### ISSUE THREAD

**Issue by jerylvaz** [TypeStrong/typedoc#1023]
## Steps to reproduce the bug
src/a.js
```
/**
 * foo method.
 */
function foo (bar: string): string {
    return bar;
}

/** Some class */
class FooClass {
   constructor () {
      foo('bar');
   }
}

export = FooClass;
```
tsconfig.json
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "es2017",
    "esModuleInterop": true,
    "strict": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "inlineSourceMap": true
  },
  "include": [
    "src/**/*"
  ]
}
```

Command: ```typedoc --excludeNotExported --out ./doc```

FooClass is excluded even though it is exported.

## Environment
  - Typedoc version: 0.13.0
  - Node.js version: 8.10.0
  - OS: Ubuntu 18.04

**Comment by alber70g** [comment]
I have this issue as well.

This is especially annoying when writing functions with docs and exporting them at the end. E.g.:

```ts
/**
 * A bunch of docs about this function
 */
const someFunction = (param1: string) => {
  // some code
}

export const someSetOfFunctions = {
  someFunction, 
  // ... maybe more functions
}
```

**Comment by Gerrit0** [comment]
I believe that's a different issue, and would require restructuring the converter in order to fix...

#801 should fix the issue with `export =`, but I'm not sure if it will fix your problem.

**Comment by alber70g** [comment]
@Gerrit0 should I make a new issue for this?

**Comment by Gerrit0** [comment]
Yes please, I believe it's a different issue.

**Comment by alber70g** [comment]
@Gerrit0 I've made an issue: https://github.com/TypeStrong/typedoc/issues/1050
