### ISSUE TITLE
Schema for typedoc.json

### ISSUE THREAD

**Issue by bencooper222** [TypeStrong/typedoc#1026]
- [X ] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

VSCode doesn't build in Typedoc support the way it does for prettier and such. A simple $schema (https://json-schema.org/) for the the options would be awesome.
## Suggested Solution

Just a link to the schema on the website. I'd be willing to write up the schema if I get an indication that the PR would be merged in upon completion.

**Comment by Gerrit0** [comment]
:+1: this would be a great addition, and should resolve #962. I'm not very familiar with the json-schema project. Should the schema be included on the TypeDoc website, or is there a standard site where it should be hosted?

**Comment by bencooper222** [comment]
I know that VSCode at least pulls from here: http://schemastore.org/json/. 

[Source](http://schemastore.org/json/)

**Comment by Gerrit0** [comment]
That seems like an ideal solution for the most exposure. If I understood that page correctly, the submission should be to that repo, though it looks like it might be possible to generate the schema from the option declarations in the current source, which should probably live in this repo.

**Comment by bencooper222** [comment]
I'm trying to write the schema right now and I have 100% coverage of the itemized options from "out" onwards. I'm having two issues right now:

[ ] Can everything listed under `typedoc --help` (even if it doesn't have a section header) be part of the options file?
[ ] This isn't really an issue but "externalPattern" has two duplicate headers with "excludeExternals" separating them.

**Comment by Gerrit0** [comment]
The code to load from an option file is [here](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/readers/typedoc.ts#L89), it looks like yes, all options can be loaded.

There's also apparently the additional property `src` which may be either a string, or a string array, and is used to specify the `inputFiles`. This corresponds to passing a path on the command line without an attached argument. This isn't documented anywhere currently to the best of my knowledge, I just learned about it now.

**Comment by bencooper222** [comment]
Please take a look at my PR in the schemastore repo (directly above)! I believe I accurately reflected the available options but would greatly appear checking of work. Options appear in the same (i.e. alphabetical) order that they appear on the [site](https://typedoc.org/guides/arguments/).

**Comment by bencooper222** [comment]
Looking at the [catalog of schemas](https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json), some projects maintain the schema in their repo while others maintain it in the schemastore project's repository. I'm pretty impartial as to which happens as I think it's a decision for people who are more actively involved than I am. That said, there do seem to be tools to convert TS interfaces to JSON schemas: https://github.com/YousefED/typescript-json-schema

**Comment by Gerrit0** [comment]
That's good to know. It would be great to automatically generate the schema from the options declarations. I think there's almost enough information already included in the source, and adding the rest shouldn't be too difficult. I think that should be tracked in a different issue though, for now going with your PR is probably best, though I'd like to hear what @aciccarello thinks.

**Comment by aciccarello** [comment]
Yeah, I like the I idea of automatically generating the schema however that'd be a pretty low priority issue. 👍

**Comment by bencooper222** [comment]
I'll give it a shot

**Comment by bencooper222** [comment]
Can someone point me to the interface that defines the options for `typedoc.json`?

**Comment by Gerrit0** [comment]
There isn't one. Each option is declared by itself with the `@Option` decorator.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gerrit0** [comment]
Closing as the PR over at schemastore has been merged. Thanks again :)
