### ISSUE TITLE
Current handlebars dependency version is vulnerable to prototype pollution

### ISSUE THREAD

**Issue by vinaydasari** [TypeStrong/typedoc#1027]
Overview
Versions of handlebars prior to 4.0.14 are vulnerable to Prototype Pollution. Templates may alter an Objects' prototype, thus allowing an attacker to execute arbitrary code on the server.

Remediation
For handlebars 4.1.x upgrade to 4.1.2 or later. For handlebars 4.0.x upgrade to 4.0.14 or later.

https://www.npmjs.com/advisories/755

**Comment by Gerrit0** [comment]
This will be fixed in the next release, the fix has been merged to master in #1019
