### ISSUE TITLE
v0.14.2 uses marked with moderate vulnerability Regular Expression Denial of Service

### ISSUE THREAD

**Issue by VinceJones** [TypeStrong/typedoc#1031]
When running npm audit while using version 0.14.2 shows a vulnerability with the **marked** package. This is fixed in version >=0.6.2

**Vulnerability:**
Regular Expression Denial of Service
https://nodesecurity.io/advisories/812

**Comment by aciccarello** [comment]
Thanks for the report however I believe this is a duplicate of #1009. It should be fixed in the next release.
