### ISSUE TITLE
`toc` config option is confusing

### ISSUE THREAD

**Issue by jLouzado** [TypeStrong/typedoc#1040]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
- `toc` config option set to `false` should prevent the left-side `Table of Contents` from getting generated

![image](https://user-images.githubusercontent.com/2016685/58474021-b3394400-8167-11e9-8d06-5c76bcbb7bd6.png)

## Actual Behavior
- `toc` option set to true or false doesn't produce any difference in output

## Steps to reproduce the bug
- Reference config is here: https://github.com/action-land/action-land/blob/2271733aa8b1e32228b1525740252fe6a32aecdc/tsconfig.json
- Set `toc` to `false` and run `yarn typedoc` and there's no difference in output in `docs/index.html`

## Environment
  - Typedoc version: ^0.14.2
  - Node.js version: v10.13.0
  - OS: MacOS

**Comment by Gerrit0** [comment]
Question - where did you see that `toc` was a Boolean option? It is an array, which by default is filled with all root symbols. If you set it to a smaller array, it will limit the toc to those elements.

**Comment by jLouzado** [comment]
@Gerrit0 Thanks for pointing that out, I think that was just my assumption since usually documentation generators give you an option whether to generate a Table of Contents or not.

>  --toc: Specifies the top level table of contents.

Now that you mention it, the documentation makes sense but I think I misunderstood it initially

**Comment by aciccarello** [comment]
I've renamed this to re-purpose it as a documentation update issue.

- [ ] Make short description (in decorator) more clear
- [ ] Add documentation to website
- [ ] Update readme
