### ISSUE TITLE
Return type for accessors is missing under the `minimal` theme.

### ISSUE THREAD

**Issue by vitaly-t** [TypeStrong/typedoc#1043]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

Type returned by accessors must be provided, like it is shown under the `default` theme.

## Actual Behavior

No return type provided when using `minimal` theme.

## Steps to reproduce the bug

Declare any accessor:

```ts
    public get live(): boolean {
        return true;
    }
```

Only the name of accessor is emitted, but no return `boolean` type, unlike for regular properties.

![image](https://user-images.githubusercontent.com/5108906/58804226-414e7800-8609-11e9-8f1c-ee71ad4e7ed7.png)

## Environment
  - Typedoc version: 0.14.2
  - Node.js version: 12.3.1
  - OS: Windows 10

**Comment by aciccarello** [comment]
Thanks for the report! This must be an issue with the renderer or the theme. We have tests in the converter and it seems to be recording the return value correctly.

https://github.com/TypeStrong/typedoc/blob/f781b20dda3dfafd453cf540f58fcd8cf4473316/src/test/converter/getter-setter/specs.json#L44-L62

**Comment by vitaly-t** [comment]
@aciccarello You are right! Switching from the `minimal` theme to `default` one solved the problem, the accessor is shown there, although not how I expected:

![image](https://user-images.githubusercontent.com/5108906/58864088-0b160480-86ac-11e9-9e29-2c528779c5e9.png)

It is a little strange that it shows parenthesis for an accessor.

Anyway, this is strictly an issue with the `minimal` theme, so I'm changing the title accordingly.

**Comment by aciccarello** [comment]
Great! Thanks for checking that out. Should be an easy fix then. I'd also be okay with dropping the parenthesis for getters and setters.

**Comment by daevidpreis** [comment]
Fix for not showing accessor type
```
---
partials/member.hbs | 4 +++-
@@ -6,9 +6,11 @@
 
     {{#if signatures}}
         {{> member.signatures}}
+    {{else}}{{#if hasGetterOrSetter}}
+        {{> member.getterSetter}}
     {{else}}
         {{> member.declaration}}
-    {{/if}}
+    {{/if}}{{/if}}
 
     {{#unless isContainer}}
         {{#each groups}}
-- 
```

**Comment by Gerrit0** [comment]
Fixed in https://github.com/TypeStrong/typedoc-default-themes/pull/89. Will be released later today.
