### ISSUE TITLE
Error: <file>(line)  ',' expected.

### ISSUE THREAD

**Issue by telamonian** [TypeStrong/typedoc#1044]
I just ran into a bug very similar to the one described in #820 (see jupyterlab/jupyterlab#6471). However, it can't be the exact same thing since I'm already using `1.4.2`. Typedoc errors out on a line from a compiled declaration file `icon.d.ts`. Here's the command I used to run typedoc:

```
typedoc --options tdoptions.json --theme ../../typedoc-theme src
```

Here's the error message:

```
Using TypeScript 3.2.4 from /Users/tel/usr/venv/jup-test/git/jup-test/node_modules/typedoc/node_modules/typescript/lib
Error: /Users/tel/usr/venv/jup-test/git/jup-test/node_modules/@jupyterlab/ui-components/lib/icon/icon.d.ts(59)
 ',' expected.
Error: /Users/tel/usr/venv/jup-test/git/jup-test/node_modules/@jupyterlab/ui-components/lib/icon/icon.d.ts(59)
 ',' expected.
```

Here are the offending lines from `icon.d.ts`:

```
export declare namespace IconRegistry {
    interface IModel {
        name: string;
        className?: string;
        svg: string;
    }

    const defaultIcons: readonly IModel[];
}
```

If I comment out the `const defaultIcons: readonly IModel[];` line, then typedoc runs just fine.

My gut says that this issue may be fixed with the release of the current HEAD (or maybe just `1.5.0`) on npm. HEAD bumps the ts version to `3.4.x`, while the project I'm working on uses `3.5.1`, so it seems like there'd be less chance for weird compatibility issues.

**Comment by Gerrit0** [comment]
Your gut is correct, the `readonly T[]` syntax was introduced in 3.4. Previously, you had to use `ReadonlyArray<T>`

That said, I don't think we have a test for the new syntax, and I have no idea how it will render even if it converts correctly.

**Comment by telamonian** [comment]
That syntax is definitely the problem. In my original `.ts` file, `defaultIcons` was defined like this:

    export const defaultIcons = _defaultIcons;

If I add an explicit type declaration:

    export const defaultIcons: ReadonlyArray<IconRegistry.IModel> = _defaultIcons;

then the type in the compiled `icon.d.ts` changes as well:

    const defaultIcons: ReadonlyArray<IconRegistry.IModel>;

and the problems with typedoc disappear. So I guess this is a fine workaround until the release of a newer version of typedoc?

**Comment by Gerrit0** [comment]
Closing as v0.15.0 uses TS3.4
