### ISSUE TITLE
Support for @throws

### ISSUE THREAD

**Issue by userpixel** [TypeStrong/typedoc#1045]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

jsdocs has a [`@throws`](https://jsdoc.app/tags-throws.html) tag that is very useful since any function can `@return` or `@throw`. I don't see any reference to this tag in [supported tags](https://typedoc.org/guides/doccomments/) or the [tsdocs declaration reference](https://github.com/microsoft/tsdoc/blob/master/spec/code-snippets/DeclarationReferences.ts). Is this a feature that is intentionally avoided? In that case what is the preferred way to document the exceptions that a function throws? If not, is it on the roadmap?

**Comment by Gerrit0** [comment]
TypeDoc will render any tag you pass by default, even if we don't explicitly support it. https://github.com/TypeStrong/typedoc/issues/952#issuecomment-455668351

**Comment by userpixel** [comment]
Yes, I saw that in the rendered page (smart strategy) but I would really like how JSDocs gives them a special place in the output. To me, the `@throws` is as vital as `@returns` because they both specify what is the outcome of calling a function.

**Comment by Gerrit0** [comment]
Fair enough, that should be a fairly simple change to make in the theme, I don't think it would even require any changes to TypeDoc proper.

**Comment by aciccarello** [comment]
I think we should hold off until microsoft/tsdoc#171 is resolved since it can already be handled as a generic tag. My initial inclination is that it is not necessary.

**Comment by aciccarello** [comment]
Update: tsdoc is adding `@throws` as a standard block text tag.

**Comment by officialpiyush** [comment]
Waiting 👍

**Comment by MithileshHinge** [comment]
Need this 👍🏽

**Comment by sebsonjura** [comment]
waiting as well ;) can we haz it?
