### ISSUE TITLE
Symbol References across Files

### ISSUE THREAD

**Issue by mr-flannery** [TypeStrong/typedoc#1046]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

TypeDoc allows creating [symbol references](https://typedoc.org/guides/doccomments/#symbol-references). However, I have not found a way to create a symbol reference in file A to a function in file B.

## Suggested Solution

I could imagine something like a relative path syntax like this (assuming `A.ts` and `B.ts` are in the same directory): `[[./B->someFunction]]`.

Thanks, guys!

**Comment by aciccarello** [comment]
@mr-flannery This should be looked up automatically. Symbol references are not specific to one file. Are you unable to make the reference with just `[[someFunction]]`?

There are issues with distinguishing between symbols with the same name, however we are deferring to the ts-doc initiative to define a syntax for how to unambiguously make those references.

**Comment by Gerrit0** [comment]
Symbol references across files / scopes can be achieved by referencing the path to the symbol, unfortunately this isn't relative to the file, but follows the structure that TypeDoc converts with. So if you are using `--mode modules`, you'll want something like  `[["a".someFunction]]`
