### ISSUE TITLE
References are marked as external when the path includes a dot

### ISSUE THREAD

**Issue by tsvetomir** [TypeStrong/typedoc#1049]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
A dot (".") in the project path should have no effect on the generated documentation.

## Actual Behavior
References such as `classes.INameInterface` are treated as external when the project path contains a dot.

## Steps to reproduce the bug
1. Rename `examples/basic` to `examples/basic.dot`
1. Execute the `run` script in the folder
1. Observe that `INameInterface` is no longer an internal reference in `json.json` ([sample](https://github.com/tsvetomir/typedoc-dots-in-path/blob/dots-in-path/basic.dot/json.json#L6511-L6514)):

```json
{
  "type": {
    "type": "reference",
    "name": "classes.INameInterface"
   }
}
```

Normally it would be ([sample](https://github.com/tsvetomir/typedoc-dots-in-path/blob/master/basic/json.json#L6511-L6515)):
```json
{
  "type": {
    "type": "reference",
    "name": "INameInterface",
    "id": 19
   }
}
```

## Environment
  - Typedoc version: 0.15.0-0
  - Node.js version: v10.15.1
  - OS: OSX 10.14.5

**Comment by Gerrit0** [comment]
Huh, well that's unexpected, I'll have to find some time to look at the internal/external distinction to figure out what's going on someday..

Related: #927

**Comment by tsvetomir** [comment]
I've traced the issue to [lib/converter/types/alias.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/types/alias.ts#L36):

```ts
let symbolName = checker.getFullyQualifiedName(type.symbol).split('.');
if (!symbolName.length) {
    return false;
}
if (symbolName[0].substr(0, 1) === '"') {
    symbolName.shift();
}
```

Here the `symbolName` array would contain extra parts that will not be filtered by the last check above:
```ts
[ '"/private/tmp/typedoc/examples/basic',
  'dot/src/classes"',
  'INameInterface' ]
```

The path seems to be enclosed in quotes so we can remove with a Regex (yay, we have two problems now!):

```ts
const checker = context.checker;
const fqn = checker.getFullyQualifiedName(type.symbol);

let symbolName = fqn.replace(/"[^"]*"\./, '').split('.');
if (!symbolName.length) {
    return false;
}
```

Does this seem reasonable? I've submitted the patch in https://github.com/TypeStrong/typedoc/pull/1052 for review.
