### ISSUE TITLE
When exporting multiple functions in one object the docs aren't generated

### ISSUE THREAD

**Issue by alber70g** [TypeStrong/typedoc#1050]
When using `export const x = { ref1, ref2 };` the docs don't contain the `/** */` from the implementation of `ref1` and `ref2`. I'm using the flag `--excludeNotExported` to not export all private functions.

- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
When using the following construct, the docs that are generated **should** include the docs that come from the comments above the implementation of the function.

```
/**
 * A bunch of docs about this function
 */
const someFunction = (param1: string) => {
  // some code
}

export const someSetOfFunctions = {
  someFunction, 
  // ... maybe more functions
}
```

## Actual Behavior
It doesn't show the documentation when exporting through an object with a reference to the functions.

## Environment

```bash
$ npm list typedoc
ing-util-platform-lib@3.1.0

$ npm --versions
{ npm: '6.4.1',
  ares: '1.15.0',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.2',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.12',
  zlib: '1.2.11' }
```

**Comment by Gerrit0** [comment]
Thanks!

**Comment by miedmondson** [comment]
Similar experience with using `"excludeNotExported": true`:

```
export const isEven = (n: number) => n % 2 === 0
export const isOdd = (n: number) => !isEven(n)
```
...generates API documentation for the functions.

```
const isEven = (n: number) => n % 2 === 0
const isOdd = (n: number) => !isEven(n)

export {
  isEven,
  isOdd
}
```
...generates no API documentation.

**Comment by aciccarello** [comment]
I wonder if this is related to #801 and #1079

**Comment by Gerrit0** [comment]
#801 should fix this

**Comment by Gerrit0** [comment]
In 0.20, the OP's code results in:

![image](https://user-images.githubusercontent.com/19329837/103249804-2f8c9e00-492e-11eb-8755-ba76892c6d26.png)

Which isn't great... but is reasonable enough that I'm going to mark this as resolved.
