### ISSUE TITLE
Cannot document overloaded arrow functions

### ISSUE THREAD

**Issue by Lodin** [TypeStrong/typedoc#1055]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

Typedoc generates the following description as it does for the overloaded functions with `function` keyword.
![image](https://user-images.githubusercontent.com/8037479/59566117-331a4600-9064-11e9-8c23-778a026b7078.png)

## Actual Behavior

It generates nothing as if I provided no documentation.
![image](https://user-images.githubusercontent.com/8037479/59566093-d6b72680-9063-11e9-9580-15ec35b898ab.png)

## Steps to reproduce the bug

The code I'm trying to document is the following. 
```typescript
/**
 * Checks the property to have a value and throws a formatted error if the
 * property does not have it.
 *
 * @param decoratorName a name of the decorator the assertion applies to.
 *
 * @param markerName a name of the decorator the property should be marked with.
 *
 * @param [propertyName] a name of the property the assertion is applied to.
 * Omitting this parameter means that any property should be marked with the
 * marker decorator.
 *
 * @param property a value of the property.
 */
export const assertRequiredProperty: {
  (decoratorName: string, markerName: string, propertyName: string, property: unknown): void;
  (decoratorName: string, markerName: string, property: unknown): void;
} = (...args) => {
  // Function body
};
```
Command is the following:
```bash
$ typedoc --name "Corpuscule API" --mode modules --tsconfig ../tsconfig.json --ignoreCompilerErrors --excludeNotExported --excludePrivate --exclude "**/__tests__/**" --out ./api ../packages/utils
```
I'm working on the [following project](https://github.com/corpusculejs/corpuscule), the `typedoc` package executable will be placed in the `docs` directory under the root.
## Environment
  - Typedoc version: 0.14.2
  - Node.js version: 12.3.1
  - OS: Windows 10

**Comment by Gerrit0** [comment]
This works as expected in 0.20

![image](https://user-images.githubusercontent.com/19329837/103244688-0adafb00-491b-11eb-9dc7-4958a697d862.png)
