### ISSUE TITLE
Shelljs vunerability

### ISSUE THREAD

**Issue by SkeLLLa** [TypeStrong/typedoc#1056]
There's vunerability in shelljs dependency.
https://github.com/shelljs/shelljs/commit/7a9f8e5b7547132ea3f7e4fa47356a94d1156bb3

Actual behavior: 
Typedoc depends on vulnerable package

Expected behavior:
Typedoc doesn't depend on vulnerable package

**Comment by Gerrit0** [comment]
The master branch already uses the latest version, it was merged in with #1019.

I'll leave this open until a new version is published on `typedoc`.

**Comment by aciccarello** [comment]
[v0.15.0](https://github.com/TypeStrong/typedoc/releases/tag/v0.15.0) has been released! 🎉 

Thanks everyone for your patience.
