### ISSUE TITLE
@see {@link name} does not work consistently

### ISSUE THREAD

**Issue by AnyhowStep** [TypeStrong/typedoc#1057]
- [X] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Steps to reproduce the bug

```ts
/**
 *
 * [[meta]]
 *
 * [test]{@link meta}
 *
 * {@link meta}
 *
 *  @see {@link meta}
 *
 * @see {@link meta}
 */
const someVar : SomeType = someExpression;
```

The first `@see` has two space at the front.
The second `@see` has one space at the front.

## Expected Behavior

All five lines should produce a link to the variable `meta`.

## Actual Behavior

![image](https://user-images.githubusercontent.com/5655961/59939133-f912c080-9424-11e9-8497-e8b3f2b6004c.png)

Only the first four lines produce a link to the variable `meta`.

The 5th line (with one space at the front) fails to produce a link to the variable `meta`.

```
 * @see {@link meta}
```

## Environment
  - Typedoc version: `master` branch; dfb7207383bdd6a9b7e69271b18bb154b6fec7d9
  - Node.js version: `v11.12.0`
  - OS: Ubuntu 18.04

-----

I say it does not work consistently because **sometimes**, it works fine.
Other times, it does not.

And it varies from file-to-file. I cannot consistently get it to fail or succeed.

**Comment by Gerrit0** [comment]
In 0.21.1, this appears to do the right thing:

![image](https://user-images.githubusercontent.com/19329837/123529497-f307e800-d6ad-11eb-8eca-e9a2b35eeb85.png)
