### ISSUE TITLE
Ability to customize styles without creating a new theme

### ISSUE THREAD

**Issue by tusharmath** [TypeStrong/typedoc#1060]
## Problem
As a user of this library I would like to customize the styles using some external CSS.

## Suggested Solution

Inside `typedoc.json` add a property — `customCSS` where any file path for CSS can be added.

```json
{
  "customCSS": "../theme/style.css"
}
```

**Comment by ical10** [comment]
I was trying to move the menu bar from right to left, and this works. Just need to create `style.css` and define the css rules inside the class that we want to modify.
