### ISSUE TITLE
Can't get default value of generic

### ISSUE THREAD

**Issue by wulkanat** [TypeStrong/typedoc#1061]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

Typedoc lacks the ability to parse the default value of a generic. So for example in
```typescript
interface Foo<G, T = any> {
    foo: T;
    foo2: G;
}

interface Foo2 {
    a: Foo<number>; // T should be any now
}
```
Typedoc only recognizes the type of `G`, as we passed it in `Foo2`, but `T`'s type is apparently unknown (It still shows up, but without any type) to Typedoc.

A pretty easy workaround for me was to use `a: Foo<number, any>;` instead of `a: Foo<number>;`, however it still bothers me a lot as the occurence for us is in an external library and we heavily make use of tslint, which prohibits use of the `any` type, so the whole thing then looks more like
```typescript
interface Foo2 {
    // tslint:disable-next-line:no-any
    a: Foo<number, any>;
}
```
which is always something we try to avoid, plus it makes our code more error prone.

**Comment by Gerrit0** [comment]
I've confirmed that the `typeParameter` object in the JSON output is missing a default, this is definitely a bug. Generic support must have been added before TS2.3 when generics were allowed a default.
