### ISSUE TITLE
How can I combine the interface and class documentation?

### ISSUE THREAD

**Issue by SagnikPradhan** [TypeStrong/typedoc#1062]
If I have something like:
```ts
interface Properties {
	color?: string
	total?: number
}

class Something implements Properties {
	somethingElse: string
	Friends: string[]

	color = 'Blue'

	someFunctionThatAddsTotalProperty() {...}
}
```

Then in generated docs total property is not visible. Is there a way I can show that property too under the `Something` class instead of `Properties` interface?

**Comment by aciccarello** [comment]
Is this valid typescript? Wouldn't typescript complain that it doesn't know of a total property?

**Comment by Gerrit0** [comment]
It's valid since the `total` property is optional. I would expect the property to be included by default, mimicking how we present items from extended classes.

**Comment by aciccarello** [comment]
Ah, I didn't think that through. So it sounds like an issue with inheritance.

**Comment by Gerrit0** [comment]
So, turns out that this is expected behavior - `total` cannot be used within the `Properties` class without being declared there too. This is an error:

```ts
interface Properties {
	color?: string
	total?: number
}

class Something implements Properties {
	color = 'Blue'

	someFunctionThatAddsTotalProperty() {
		this.total = 1
	}
}
```
