### ISSUE TITLE
"--mode modules" option: Use the module name from package.json, not the local folder

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/typedoc#1064]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

The name of the folder where my project is located may be something like `foo+bar+baz`, where `baz` is the actual module name that I specify in package.json, and underwhich it is published on NPM.

In the generated documentation, I see the folder name, which is actually _not the module name_.

## Suggested Solution

I'd like for it to use the module name from the package.json, not the folder name.

For example, one package I have is called `infamous`, but it is located in a folder called `trusktr+infamous`, and so the output looks like this:

<img width="418" alt="Screen Shot 2019-07-04 at 6 36 50 PM" src="https://user-images.githubusercontent.com/297678/60692395-b4f2d780-9e8a-11e9-86f4-354a03de50e5.png">

**Comment by Gerrit0** [comment]
This seems like a reasonable change to me, it shouldn't be too difficult to do if you want to give updating it a shot.

**Comment by trusktr** [comment]
I'm not sure I'm ready to commit to changes yet. I'm still researching what may be the best way to document my code. I'm starting to think perhaps just having separate markdown files, and not using a doc generator, might be the easiest way for now.

Like what Three.js does with their [docs](https://github.com/mrdoob/three.js/tree/dev/docs/api), which have the same folder structure as the source code, but is all `.html` files instead of `.js` files (so `docs/en/core/WebGLRenderer.html` is documentation for `src/core/WebGLRenderer.js`.

**Comment by trusktr** [comment]
For example, what I have is code that looks like this:

```ts
import {Mixin, MixinResult} from 'lowclass' // a helper for making mixin classes

function SomeClassMixin<T extends Constructor>(Base: T) {
    const Parent = Sizeable.mixin(Constructor(Base))

    class SomeClass extends Parent {
        // ...
    }

    return SomeClass as MixinResult<typeof SomeClass, T>
}

export const SomeClass = Mixin(TransformableMixin)
export interface SomeClass extends InstanceType<typeof SomeClass> {}
```

and how it can be used is like this:

```ts
import {SomeClass} from './SomeClass'

class Foo {}

// extend it directly
class Bar extends SomeClass { ... }

// or use it as a mixin
class Baz extends SomeClass.mixin(Foo) {} 
```

and what I want to document is something like this:

```ts
import {Mixin, MixinResult} from 'lowclass' // a helper for making mixin classes

/**
 * @class SomeClass
 * @implements Sizeable
 */
function SomeClassMixin<T extends Constructor>(Base: T) {
    const Parent = Sizeable.mixin(Constructor(Base))

    class SomeClass extends Parent {
        /**
         * @method someMethod
         * @memberOf SomeClass
         */
        someMethod() {...}

        // ...
    }

    return SomeClass as MixinResult<typeof SomeClass, T>
}

export const SomeClass = Mixin(TransformableMixin)
export interface SomeClass extends InstanceType<typeof SomeClass> {}
```

Currently, all the typing around the mixin stuff is just making noise in the output. It's a pattern used across all the classes. If someone really wants to see what's going on, they can load the source in VS Code, or import it into their project and look at intellisense in VS Code.

But for documentation, I just want simplicity: they are just classes, with optional `.mixin` helpers to make them behave as class-factory mixins. I want to document them simply as classes, to keep docs simple.

**Comment by Gerrit0** [comment]
0.20 doesn't exactly do this, but I'm pretty sure it makes this unnecessary. In 0.20, TypeDoc expects to be given the path to an entry point. It will then ask the compiler API for exports and document that. You *can* provide more than one entry point, but I don't expect it to be common.

If more than one entry point is present, TypeDoc will use the shortest possible path to distinguish between files. If that still isn't enough `@module name` can be used to change the displayed module name.
