### ISSUE TITLE
Function overload

### ISSUE THREAD

**Issue by terrible-coder** [TypeStrong/typedoc#1072]
Does typedoc build the documentation for overloaded functions as well?
I tried typedoc with all the default settings and template. It worked fine in other cases but for overloaded functions, only the first overload signature was being documented and the others were ignored completely. Is there some special configuration I need to do to make that work or is that not supported yet?

**Comment by Gerrit0** [comment]
Moved from typedoc-default-themes as it is really easy to miss issues there. I'd thought we had turned off issues there...

Typedoc will document all overloads, but the documentation comment only applies to the overload it directly precedes. You can see an example of the generated html here: https://typedoc.org/api/classes/reflection.html#getchildbyname (click on each overload)

**Comment by terrible-coder** [comment]
Yes. I found that clicking on the different function signatures the different documentations for overloaded functions show up. Completely missed that. My bad. Sorry and thanks.
