### ISSUE TITLE
Vulnerability report: Dependency marked "^0.4.0" including Security Vulnerability and should be upgrade to version >0.6.2 

### ISSUE THREAD

**Issue by archerhbx** [TypeStrong/typedoc#1076]
### Dependency marked "^0.4.0" of typedoc@^0.14.2 including Security Vulnerability in WhiteSource check,  it should be upgrade to version >0.6.2.

- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

Description:
marked versions >0.3.14 and < 0.6.2 has Regular Expression Denial of Service vulnerability Email addresses may be evaluated in quadratic time, allowing attackers to potentially crash the node process due to resource exhaustion.

Fix:
Upgrade To Version 0.6.2
The reported vulnerability was not checked for vulnerability effectiveness and is suggested to be examined using Effective Usage Analysis.

typedoc@^0.14.2:
  version "0.14.2"
  resolved "https://registry.yarnpkg.com/typedoc/-/typedoc-0.14.2.tgz#769f457f4f9e4bdb8b5f3b177c86b6a31d8c3dc3"
  dependencies:
    "@types/fs-extra" "^5.0.3"
    "@types/handlebars" "^4.0.38"
    "@types/highlight.js" "^9.12.3"
    "@types/lodash" "^4.14.110"
    "@types/marked" "^0.4.0"
    "@types/minimatch" "3.0.3"
    "@types/shelljs" "^0.8.0"
    fs-extra "^7.0.0"
    handlebars "^4.0.6"
    highlight.js "^9.13.1"
    lodash "^4.17.10"
    **marked "^0.4.0"**
    minimatch "^3.0.0"
    progress "^2.0.0"
    shelljs "^0.8.2"
    typedoc-default-themes "^0.5.0"
    typescript "3.2.x"

## Environment
  - Typedoc version: 0.14.2
  - Node.js version: v10.15.3
  - OS:

**Comment by Gerrit0** [comment]
Closing in favor of #1009. This is fixed on master.
