### ISSUE TITLE
Documenting external types with TypeDoc

### ISSUE THREAD

**Issue by esmacik** [TypeStrong/typedoc#1081]
I have two files, file A and file B. File A uses a class from file B. My goal is to reference the TypeDoc output for a class used in file B in the TypeDoc output for file A. I can't seem to do this.

I know you can reference a symbol contained in the same file with TypeDoc with double brackets, like `[[Foo]]`, but this didn't work for an external type like this.

```typescript
/** Trying to reference [[FileB.InnerClass]] like this doesn't work. */
// This here is what I want to include
export type InnerClass = FileB.InnerClass;

// More code...
```

Is this a possible thing to achieve?

**Comment by aciccarello** [comment]
You should be able to reference the class with simply `[[InnerClass]]`. Does that not work?

**Comment by Gerrit0** [comment]
Referencing a type in another file requires using the full path to that name. Note that file names are wrapped in quotes (unless you use a plugin to rename them) so the link would have to be `[["FileB".InnerClass]]`

Please reopen if you are still having problems with links.
