### ISSUE TITLE
Prevent external inherited class properties from showing up

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/typedoc#1088]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

All my classes inherit from HTMLElement, because they are Custom Elements. This means that all the properties and methods inherited from HTMLElement appear in the documentation, which is what I don't want. I would rather tell the user something like "all classes extend from HTMLElement, please see MDN here.".

## Suggested Solution

A way to tell it not to include properties from inherited classes that are external (that are not in the files of the source).

**Comment by Gerrit0** [comment]
See #813
