### ISSUE TITLE
Rename "modules" to "namespaces"

### ISSUE THREAD

**Issue by sebastian-lenz** [TypeStrong/typedoc#109]
Starting with TypeScript 1.5 we have namespaces that will/should replace modules, see [here](https://github.com/Microsoft/TypeScript/pull/2923). I would like to rename the documentation output accordingly as I always struggled with the distinction between "modules" and "external modules".

| Old name | New name |
| --- | --- |
| Module | Namespace |
| External module | Module |

This would break existing urls and might interfere with other things but I think it's worth the trouble. Any opinions on this?

**Comment by indus** [comment]
:+1:

**Comment by bd82** [comment]
:+1:

**Comment by aciccarello** [comment]
I'd like this, but we don't have many links to our docs to break.

**Comment by jasongrout** [comment]
+1

**Comment by Chowarmaan** [comment]
:+1:

**Comment by aleung** [comment]
Please rename it. 
"External Module" is very confusing.

**Comment by MatthieuLebigre** [comment]
+1

**Comment by aciccarello** [comment]
This seems like low hanging fruit. The solution should have a way for projects to avoid breaking existing links. Text and URL changes could be completed as separate PRs

**Comment by Gerrit0** [comment]
This might be low hanging fruit to someone familiar with the codebase, but there's a lot of potential for breakage in unexpected places from what I've seen with some experimenting with this last week. If you want to give this a shot, feel free, but I wouldn't say it's the easiest issue wanting help.
