### ISSUE TITLE
Upgrade to Typescript 3.6

### ISSUE THREAD

**Issue by xaviergonz** [TypeStrong/typedoc#1092]
- [X] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
I have a project in TS3.6 that uses the new Generator type, which is not compilable under TS 3.5

## Suggested Solution
Upgrade dependency to TS3.6

**Comment by Neloreck** [comment]
Probably, it will be better to declare it as peerDependency (for package usage) and devDependency (for development).

 - Almost everyone who uses typedoc has typescript as global/development dependency
 - You will get tired of updating typescript every time

**Comment by simllll** [comment]
Also looking forward to the dependency update / or modification that you do not have to update it ;).

Thanks for the amazing project,
Simon

**Comment by Gerrit0** [comment]
PR welcome, it should be a quick fix - TypeScript isn't a peer dependency for us because we use internal APIs that could break on a minor version update.
