### ISSUE TITLE
Throw unnecessary errors in the tsx file

### ISSUE THREAD

**Issue by citrusjunoss** [TypeStrong/typedoc#1095]
- [ ] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

No errors are thrown in the react project
## Actual Behavior

errors are thrown in the react project
## Steps to reproduce the bug

line 187  in converter.js
`diagnostics = program.getSemanticDiagnostics().filter(isRelevantError);`

my project used tsx file, Some errors will be thrown in the above method. 
like below
`can only be default-imported using the 'esModuleInterop' flag`
`Cannot use JSX unless the '--jsx' flag is provided.`
` Module './Avatar' was resolved to 'E:/project/qzd-h5-lft/src/components/Base/Avatar/Avatar.tsx', but '--jsx' is not set.`

I guess this is a configuration issue with tsconfig, because the react project needs to set an option called` jsx : preserve`
## Environment
  - Typedoc version: 0.15.0
  - Node.js version: 12.10
  - OS: win 10
  - TS  version: 3.5.3
![image](https://user-images.githubusercontent.com/18432488/64951763-39ad9900-d8b1-11e9-97b0-1619a81f07ed.png)

**Comment by Gerrit0** [comment]
It sounds like TypeDoc doesn't know about your tsconfig.json file, how are you calling it?

**Comment by Gerrit0** [comment]
Closing for housekeeping, please reopen if you are still having issues.
