### ISSUE TITLE
how do I get the new parameters in v0.15.0?

### ISSUE THREAD

**Issue by zyziyun** [TypeStrong/typedoc#1097]
hello,
I want to add a plugin(such as: typedoc-plugin-sourcefile-url). The plugin add a declaration params. But in typedoc, I can not get value.
I debug code found a problem with the execution order.

![image](https://user-images.githubusercontent.com/26137817/65250849-d4fc7380-db28-11e9-83d9-8b600c69f7be.png)

![image](https://user-images.githubusercontent.com/26137817/65251253-95825700-db29-11e9-9ff2-fcf16d983c98.png)

![image](https://user-images.githubusercontent.com/26137817/65251503-01fd5600-db2a-11e9-805f-2daf4b3af126.png)

The first thing is find options' value. this time, don't have plugins param.
Then load plugin, re-execute function, but the first params is just setValue's params.

So how do I get extra parameters in plugin ? thank you~

**Comment by Gerrit0** [comment]
I believe this is caused by #875, and when that is fixed this should automatically be fixed. Unfortunately plugins right now aren't well documented & frankly I'm not sure anyone still working on the project understands how they were intended to interact with the rest of the application.

**Comment by Gerrit0** [comment]
This has been fixed, `application.options.getValue('name')` will correctly work for plugin options in v0.16.0.
