### ISSUE TITLE
Currying support

### ISSUE THREAD

**Issue by Freit02** [TypeStrong/typedoc#1098]
I just recently started using TypeDoc - mostly for documentation - but I am wondering if it just doesn't support currying or if I am implementing it incorrectly.

**I have the below file:**
```
/**
 * Helper File
 * @description Contains helper functions needed for multiple entities
 * @exports setParentData
 */

/** ignore this comment */
import React from "react";

/**
 * Takes in an array of props and runs the change function in props.
 * Used in the children where change is passed down from parent for state management.
 * Using currying to pass props, then field, then (e) change event for onchange in child.
 * @param {any} props
 * @param {string} field
 * @param {React.ChangeEvent} e
 */
export const setParentData = (props: any) => (field: string) => (
  e: React.ChangeEvent<any>
) => {
  props.change(field, e.currentTarget.value);
};
```

**and get this output:** 
![image](https://user-images.githubusercontent.com/36017906/65274719-03ab2780-daf2-11e9-8762-fa9c9fe5ae2f.png)

Thanks for any help in advance!

**Comment by Gerrit0** [comment]
The "Anonymous function" type certainly isn't ideal, we should support this pattern, and I thought we did... but apparently not. I don't think you did anything wrong.

**Comment by Herlevsen** [comment]
I just installed typedoc and experienced the same thing.

For example this function:
```ts
export const numberGreaterThan = (otherNum: number) => (num: number) => num > otherNum
```
got this signature:
```ts
numberGreaterThan(otherNum: number): (Anonymous function)
```

It's not just functions that returns functions though, it is higher order functions in general. Functions in parameters just becomes ``function``
Example:
```ts
validateField<T>(...tuples: Array<[function, string]>): (Anonymous function)
```

**Comment by Gerrit0** [comment]
In 0.20, the code in the OP renders as:

![image](https://user-images.githubusercontent.com/19329837/103161322-33d58180-479d-11eb-9941-c74260b5e999.png)

This still isn't exactly ideal, but the confusing non-indented tags is a theme issue, this issue has been resolved
