### ISSUE TITLE
ignore specific/custom jsDoc tags in d.ts generation

### ISSUE THREAD

**Issue by kmuthukumar23** [TypeStrong/typedoc#1099]
Hi Team,

I want to hide some JSDoc comments in d.ts generation. For clear precious, As i am defined and using some internal tags for my own. In my requirement, this tags are not expose in API which means these tags are should not generated in typings(d.ts) file generation. This is my exact requirement.  

- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

 The major problem is all internal purpose jsDocs Tags are exposed in user end.

## Suggested Solution

I need like following,

My actual source:

    /**
     * Some String.
     * @public
     * @customTag
     */

Here @customTag is internal tag

Actual generated typings for above:

    /**
     * Some String.
     * @public
     * @customTag
     */
     getRange(): Range;

As per my requirement, the internal Tags are should not generated in typings file like below.

    /**
     * Some String.
     * @public
     */
    getRange(): Range;

Is this possible? Please suggest me regarding this

**Comment by Gerrit0** [comment]
TypeDoc doesn't support declaration file generation, but .d.ts rollup/trimming is a stated goal of the [API Extractor](https://api-extractor.com/pages/overview/demo_rollup/) project. They might be able to help.
