### ISSUE TITLE
Security upgrade: handlebars dependency should be ^4.3.0

### ISSUE THREAD

**Issue by dbartholomae** [TypeStrong/typedoc#1101]
- [X] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
TypeDoc depends on handlebars ^4.1.2, which has the following security problem:
https://www.npmjs.com/advisories/1164

## Actual Behavior
TypeDoc should not depend on handlebars ^4.1.2, but ^4.3.0 to avoid this problem.

## Steps to reproduce the bug
Run npm audit or yarn audit on a project depending on Typedoc.

## Environment
  - Typedoc version: 0.15.0
  - Node.js version: 10.15.0
  - OS: Windows 10

**Comment by Gerrit0** [comment]
Fixed on master in 75aba843b5d283f02b9b75d223b61cd81e784ae7, leaving this open to track release.

**Comment by Gerrit0** [comment]
Fix released in v0.15.1
