### ISSUE TITLE
discoverNpmPlugins function breaks the generation

### ISSUE THREAD

**Issue by ethikz** [TypeStrong/typedoc#1102]
- [X] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

I expect it to resolve all files/paths and build documentation

## Actual Behavior

It fails to build the documentation and crashes.

The error showing in terminal is:
```
> angular-tour-of-heroes@1.0.0 docs ~/development/angular-tour-of-heroes
> typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/

fs.js:114
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir '~/node_modules/@babel-code-frame-7.0.0-beta.44.tgz'
    at Object.readdirSync (fs.js:790:3)
    at FS.readdirSync.forEach (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/utils/plugins.js:72:24)
    at Array.forEach (<anonymous>)
    at discoverModules (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/utils/plugins.js:69:38)
    at discover (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/utils/plugins.js:61:21)
    at PluginHost.discoverNpmPlugins (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/utils/plugins.js:54:9)
    at PluginHost.load (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/utils/plugins.js:16:46)
    at CliApplication.bootstrap (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/application.js:42:22)
    at CliApplication.bootstrap (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/cli.js:24:30)
    at new Application (~/development/angular-tour-of-heroes/node_modules/typedoc/dist/lib/application.js:31:14)
```

After some debugging, the breaking happens with this specific line `path = Path.resolve(Path.join(previous, '..'));`

It seems to get all `node_modules` in the local directory then it traverses up every directory until it gets to my home directory `node_modules` and then it breaks looking for that module for whatever reason.

When I comment that line out completely it works fine. Being that I am not 100% sure what this function does completely in the scheme of typedoc, I'm hesitant to submit a PR.

## Steps to reproduce the bug

- Create new angular app with angular-cli or you can clone/download the start at https://github.com/johnpapa/angular-tour-of-heroes.git
- Update all packages ( I use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) )
- `npm run build`
- `npm run docs`

**typedoc.js**
```
module.exports = {
  out: 'docs',
  includes: '/',
  exclude: [
    '**/*.spec.ts',
    '**/node_modules/**'
  ],
  mode: 'modules',
  theme: 'default',
  ignoreCompilerErrors: 'true',
  target: 'ES5',
  module: 'commonjs'
};
```

**package.json**
```
"scripts": {
  [...]
  "docs": "npm run typedoc -- --options typedoc.js ./src/",
  "typedoc": "typedoc",
}
```

## Environment
  - Typedoc version: 0.15.0
  - Node.js version: 10.16.0
  - OS: OSX 10.14.6

**Comment by Gerrit0** [comment]
Introduced with #736. We assumed that files under `node_modules` that start with `@` are folders used for npm's scoped packages, but this clearly isn't a safe assumption as you've found. Adding a check to ensure that it is a directory before trying to check its children should fix the issue.

That said, I recall some discussion somewhere (either in gitter or an issue, I can't seem to find it) about removing automatic plugin discovery since it makes load order considerably harder to follow and may include plugins you don't expect if one of your dependencies had them in their dependencies instead of devDependencies for some reason.

**Comment by ethikz** [comment]
@Gerrit0 Is there any movement or upate on this?

**Comment by Gerrit0** [comment]
I haven't had the time to get to it yet, I should be able to take a look this weekend

**Comment by ethikz** [comment]
@Gerrit0 No problem!  I just didn't want this to get lost in the ether.  I have solved the solution for now by just removing the global `node_modules` folder in the user directory.  Not sure what other issues this can and/or will pose.
