### ISSUE TITLE
Option to hide the legend?

### ISSUE THREAD

**Issue by ianstormtaylor** [TypeStrong/typedoc#1108]
Right now it doesn't seem like there's a way to hide the legend printed at the bottom of each page. For most small use cases the icons themselves are distinct enough, and the groupings are labelled with a header already, so the extra information overload isn't worth it. It would be nice to be able to hide.

**Comment by Gerrit0** [comment]
I'm kind of wary about including this in the main TypeDoc project, it would be really nice to be able to attach options to themes and let themes provide options for tweaks like this, but more work needs to be done on options before this is feasible.

That said, removing it locally isn't very difficult.

Create a theme directory with `partials` inside it, then create `footer.hbs` inside that `partials` directory. Grab as much, or as little, from [the original file](https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/partials/footer.hbs) as you like. Then tell TypeDoc to use your custom theme with `--theme path/to/theme/dir`
