### ISSUE TITLE
Tooltips when hovering over icons?

### ISSUE THREAD

**Issue by ianstormtaylor** [TypeStrong/typedoc#1109]
Related to https://github.com/TypeStrong/typedoc/issues/1108, I think it would be nice to get the legend entry name when you hover over an icon. That way you could hide the Legend for visual clutter, but readers can still opt-in to seeing what an icon represents in the rare cases they need to. (This might even make a better default.)

**Comment by Gerrit0** [comment]
I think this would require reworking how icons are displayed.. currently they are placed in the `::before` pseudo element of elements with the `tsd-kind-icon`. Ideally the displayed automatically on icons, we shouldn't need to add a `title` property on every single element...

I guess we *could* (ab)use the `::after` pseudo element for this, but it seems like there should be a better solution.

This would be a neat feature to have if it can be done without ugly hacks.
