### ISSUE TITLE
A method with 3 signatures and 1 body is generating a .json file that captures only 2 of them

### ISSUE THREAD

**Issue by JonathanFingold** [TypeStrong/typedoc#1122]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
All method signatures in the **.ts** file show up in the generated **.json** file.

## Actual Behavior
Only 2 of the 3 signatures for the `prompt` method are captured in the **.json** file.
See repo steps for details.

## Steps to reproduce the bug
1. Grab a copy of the microsoft/botbuilder-js repository. This [snapshot](https://github.com/microsoft/botbuilder-js/tree/65c6085588c5752fea6c0e5b2230a2a62592a1a9) should be close to the same version as what I ran the tool against.
1. From the root of your local copy, run **typeDoc**. This is the exact command I used:
   ```cmd
   typedoc --mode file --json \temp\typeDocs\botbuilder-dialogs.json libraries\botbuilder-dialogs\src --ignoreCompilerErrors --includeDeclarations --excludeExternals --excludePrivate --excludeNotExported
   ```
1. Compare the [signatures for the DialogContext.prompt method](https://github.com/microsoft/botbuilder-js/blob/ef4123ef3250d4eacabe21b0fd85448878d0bf60/libraries/botbuilder-dialogs/src/dialogContext.ts#L188-L230) to the generated output.
   - Included below are botbuilder-dialogs.json lines 9630-9811 for my output, edited down to the "good parts".
   - Note that typeDoc notices all 3 signature sources, but only generates 2 signature entries.

```json
				{
					"id": 178,
					"name": "prompt",
					"kind": 2048,
					"kindString": "Method",
					"flags": {
						"isPublic": true,
						"isExported": true
					},
					"signatures": [
						{
							"id": 179,
							"name": "prompt",
							"kind": 4096,
							"kindString": "Call signature",
							"flags": {},
							"comment": {
								"shortText": "Helper function to simplify formatting the options for calling a prompt dialog.",
								"tags": ...
							},
							"parameters": ...,
							"type": ...
						},
						{
							"id": 182,
							"name": "prompt",
							"kind": 4096,
							"kindString": "Call signature",
							"flags": {},
							"parameters": ...,
							"type": ...
						}
					],
					"sources": [
						{
							"fileName": "dialogContext.ts",
							"line": 206,
							"character": 23
						},
						{
							"fileName": "dialogContext.ts",
							"line": 207,
							"character": 23
						},
						{
							"fileName": "dialogContext.ts",
							"line": 208,
							"character": 23
						}
					]
				},
```

## Environment
  - Typedoc version: 3.5.3
  - Node.js version: v10.16.0
  - OS: Windows 10 Pro x64

**Comment by Gerrit0** [comment]
The implementation is not a signature that should be callable. Note 1/2, not 1/3 in this screenshot:

![image](https://user-images.githubusercontent.com/19329837/67625813-2bcc2b80-f800-11e9-8600-062cf0b830e0.png)

```ts
function overloaded(a: string): string
function overloaded(a: number): number
function overloaded(a: string | number) { return a; }
```
Note that the following code is an error, even though it matches the implementation signature.

```ts
function overloaded(a: string, b: true): string
function overloaded(a: number, b: false): number
function overloaded(a: string | number, b: boolean) { return a; }

const b: boolean = true
overloaded(1, b)
```

In this case, I'd argue that you shouldn't have overloads in the first place. You should _only_ have the implementation signature.

**Comment by JonathanFingold** [comment]
Thanks @Gerrit0 . I'll open an issue against the code base.
