### ISSUE TITLE
Do not completely wipe out the target directory

### ISSUE THREAD

**Issue by iherman** [TypeStrong/typedoc#1123]
- [ x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

At the moment, typedoc wipes out the the target directory when generating an update. This means it is not possible to put the documentation into a, say, github repository, because at every update the configuration files (e.g., `.git`) are removed.

## Suggested Solution

At the minimum, the script should not remove configuration files like `.git`, or similar. More generally, the user should be able to provide a file pattern(s) for files to be retained.

**Comment by Gerrit0** [comment]
Workaround: Put the generated output inside a dedicated folder in your git repo.

Workaround 2: Pass `--disableOutputCheck` and clean unchanged files yourself.

A problem with conditionally deleting files is that we don't know ahead of time what files will be generated. If we let the user tell us to retain a file, it still might be overwritten, leading to confusing behavior. If we don't overwrite retained files, the documentation will be incomplete and will likely contain broken links.

It seems reasonable to not delete `.git`, but I'm concerned that this retain list will grow...

**Comment by iherman** [comment]
@Gerrit0, thanks

> Workaround: Put the generated output inside a dedicated folder in your git repo.

That is what I started with but, to my surprise, github's pages cannot pick up a subdirectory on the repository as web site (it has to start from the top, somehow). I may have missed something, but that is actually how I hit the problem (setting up a separate repo for the documentation).

> Workaround 2: Pass --disableOutputCheck and clean unchanged files yourself

O.k. I think this is what I will do.

I understand and sympathize with your concerns...

Thanks again.

**Comment by iherman** [comment]
@Gerrit0 as far as I am concerned, you can close this issue if you prefer.

**Comment by iherman** [comment]
Actually... my original problem (generate a documentation on a github page) was not solved, but I am not sure why (although the files are correctly there, the ...github.io pages return a 404 for, e.g., the files in modules). There is a mystery somewhere else...

**Comment by Gerrit0** [comment]
GitHub pages ignores files with leading underscores, you can fix this by disabling Jekyll or tell it to include all files (like the [typedoc-site](https://github.com/TypeStrong/typedoc-site/blob/gh-pages/_config.yml#L21) repo does), you can disable it by adding a `.nojekyll` file to the root directory.

> That is what I started with but, to my surprise, github's pages cannot pick up a subdirectory on the repository as web site

You can tell it to use /docs in the repository settings, it isn't very configurable though.

I'll leave the issue open for now, @aciccarello might have a better idea for solving the issue than just ignoring it.
