### ISSUE TITLE
Modules with only non-exported constructs should not be exported either

### ISSUE THREAD

**Issue by alalonde** [TypeStrong/typedoc#1126]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
In a file with only `@internal` exports, the module corresponding to that file should not be exported either, and not show up in the "Globals" section.  Assuming `mode="modules"`

## Actual Behavior
The module is exported but empty.  There is a link to it in the "Globals" section.

## Steps to reproduce the bug
With this file `src/internal.ts`:
```
/**
 * @hidden
 */
export class Internal {
  ...
}
```

`typedoc --mode="modules" --excludeNotExported src/`

## Environment
  - Typedoc version: 0.15.0
  - Node.js version: 10.8
  - OS: Mac OS 10.12

**Comment by Gerrit0** [comment]
PR welcome, this should only require minor changes.
