### ISSUE TITLE
Was minimal theme "un-minimal'd" somewhere after 0.3.12?

### ISSUE THREAD

**Issue by KevinEady** [TypeStrong/typedoc#1128]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

We recently are upgrading our dependencies and came across a difference in artifact creation using the `minimal` theme from 0.3.12 to now. 

## Expected Behavior
- Minimal theme generates _one_ file

## Actual Behavior
- Minimal theme generates _multiple_ files

## Steps to reproduce the bug

```
> cat index.ts

export class MyClass {
    private member:number;
}
```

Using version 0.15.0:
```
> npm i typedoc@0.15.0 && \
  rm -rf /tmp/docs && \
  ./node_modules/.bin/typedoc --out /tmp/docs --theme minimal --mode file --module commonjs index.ts && \
  find /tmp/docs

...
/tmp/docs
/tmp/docs/index.html
/tmp/docs/classes
/tmp/docs/classes/myclass.html
/tmp/docs/assets
/tmp/docs/assets/css
/tmp/docs/assets/css/main.css
/tmp/docs/assets/images
/tmp/docs/assets/images/icons@2x.png
/tmp/docs/assets/images/widgets.png
/tmp/docs/assets/images/icons.png
/tmp/docs/assets/images/widgets@2x.png
/tmp/docs/assets/js
/tmp/docs/assets/js/main.js
/tmp/docs/assets/js/search.js
/tmp/docs/globals.html
```

Using version 0.3.12:
```
> npm i typedoc@0.3.12 && \
  rm -rf /tmp/docs && \
  ./node_modules/.bin/typedoc --out /tmp/docs --theme minimal --mode file --module commonjs index.ts && \
  find /tmp/docs

...
/tmp/docs
/tmp/docs/index.html
```

## Environment
  - Typedoc version: 0.3.12 -> 0.15.0
  - Node.js version: v12.11.0
  - OS: Mac OS X

**Comment by Gerrit0** [comment]
Huh, for as long as I've been around the minimal theme has created several files.  I'll have to do some serious digging to look into this.

**Comment by ZbigniewRA** [comment]
TypeDoc documentation says it should generate just one HTML file, with everything embedded, but it doesn't.
```
minimal - This theme is intended to be used with smaller projects.
It is ultra portable as it renders the entire documentation into one big html file
including all required assets like stylesheets or images.
Like the default theme, it supports filtering the displayed members by different criteria.
```

**Comment by dkocich** [comment]
I think this is still the issue - this happens to me in `typedoc@0.19.2` with `typescript@3.9.7` that `typedoc --theme minimal --out docs src` outputs tens of files
