### ISSUE TITLE
Support setting repository url for source links instead of always using git origin remote.

### ISSUE THREAD

**Issue by lukaswelinder** [TypeStrong/typedoc#1130]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

When generating documentation, the "defined in" links always point to the git origin remote, which becomes a pain when trying to update docs on an upstream repository.

## Suggested Solution

Allow user to define which git remote or url they wish to use for the repository.

**Comment by Gerrit0** [comment]
The [soucefile-link](https://www.npmjs.com/package/typedoc-plugin-sourcefile-link) plugin does a pretty good job of this already

**Comment by Gerrit0** [comment]
I've changed my mind ^

TypeDoc should support this natively. Users shouldn't need to install a plugin to update docs for an upstream repo.

**Comment by Gerrit0** [comment]
With 0.17.0-1 (beta) you can set the remote with `--gitRemote`
