### ISSUE TITLE
0.15.1 needs TypeScript 3.7.x and breaks with Protractor code

### ISSUE THREAD

**Issue by woppa684** [TypeStrong/typedoc#1134]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

I'm mainly creating this bug because it cost me a lot of time to find the culprit... I have in my package.json 
```
"typedoc": "^0.15.0"
```
so it automatically installed 0.15.1, which caused errors like
```
[15:56:03] node_modules/protractor/built/index.d.ts(4)
 Import declaration conflicts with local declaration of 'PluginConfig'.
[15:56:03] node_modules/protractor/built/index.d.ts(4)
 Import declaration conflicts with local declaration of 'ProtractorPlugin'.
```

## Expected Behavior
A patch release (going from 0.15.0 to 0.15.1) doesn't break existing code.

## Actual Behavior
The (automatic) update to version 0.15.1 requires TypeScript 3.7.x which breaks typedoc'ing code that uses Protractor because of this bug https://github.com/angular/protractor/issues/5348. 

## Steps to reproduce the bug
TypeDoc a project which depends on Protractor 5.4.2.

## Environment
  - TypeDoc version: 0.15.1
  - Node version: 10.15.3
  - OS: Windows 10

**Comment by Gerrit0** [comment]
Ouch, sorry about that. I released as 0.15.1 since I've been adding issues to the 0.16 milestone that weren't ready yet. Clearly I should have renamed that to 0.17 and released 0.15.1 as 0.16. I'll be sure to do this for future releases that upgrade the TS version.

**Comment by ravi005e** [comment]
issue still remains

**Comment by Gerrit0** [comment]
If you're running into this I recommend changing your targeted version to `"0.15.0"` so that npm doesn't automatically upgrade. I'm not going to overwrite versions to fix this.
