### ISSUE TITLE
header id conflicts

### ISSUE THREAD

**Issue by egoist** [TypeStrong/typedoc#1135]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

Sometimes the IDs in `README.md` are conflicted with the IDs generated from types.

## Suggested Solution

Maybe add prefix to the ID generated from types?

**Comment by Gerrit0** [comment]
I may be missing something, but when does this actually happen? At least in the default theme, it looks like we don't render anything with anchors but the readme on the page that displays it.

https://typedoc.org/api/

**Comment by egoist** [comment]
> it looks like we don't render anything with anchors but the readme on the page that displays it.

That's exactly what I mean (https://majo.egoist.sh):

![image](https://user-images.githubusercontent.com/8784712/68932788-46297180-07ce-11ea-9959-3f0e202a5f02.png)

These two things use the same ID, you may add a prefix to either one of them.

**Comment by Gerrit0** [comment]
Thanks, I didn't consider the minimal theme. PR welcome to add a prefix, I think it would be better to prefix the readme.

The whole anchor / url scheme needs reworking (two variables `Foo` and `foo` will have duplicate IDs), but that's a much larger task
