### ISSUE TITLE
<wbr> is inserted in the middle of html escaped characters

### ISSUE THREAD

**Issue by rinick** [TypeStrong/typedoc#1137]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
special character should be shown correctly
for example `&#x3D;`

## Actual Behavior
https://github.com/TypeStrong/typedoc/blob/5355abc164d5db8924698e2aef1190a081d0b659/src/lib/output/helpers/wbr.ts#L16

`&#x3D;` is converted to `&#x3<wbr>D;` 
## Steps to reproduce the bug
```javascript
interface Filter{
  "=": string;
}
```

## Environment
  - Typedoc version: 0.15.2
  - Node.js version: 12.8.0
  - OS: win10

**Comment by Gerrit0** [comment]
Well, the only character that can trigger this is `=`, so that's something at least.

https://github.com/wycats/handlebars.js/blob/25bae31578f95127720dd4dd911703101c8f7005/lib/handlebars/utils.js#L9

PR welcome, or I'll try to get to this Sunday, busy week here.

**Comment by Gerrit0** [comment]
Fix released in v0.15.3
