### ISSUE TITLE
Typedoc is inconsistent in excluding not exported symbols

### ISSUE THREAD

**Issue by mvlabat** [TypeStrong/typedoc#1141]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates
(Might be related to #596?)

I tried several combinations of organizing class exports and filtering them out in the docs, here's what I got:
```typescript
/**
 * Appears in the docs if "Only exported" is checked in the UI,
 * but doesn't if `excludeNotExported` is set to true in `typedocOptions`.
 */
class TestDefault1 {}

export default TestDefault1;
```

```typescript
/**
 * Appears in the docs for both "Only exported" in the UI and
 * `excludeNotExported` set to true in `typedocOptions`.
 */
export default class TestDefault2 {}
```

```typescript
/**
 * Won't appear in the docs as exported.
 */
class TestDefault3 {}

export { TestDefault3 as default };
```

I've set up a small repository to reproduce the issue:
https://github.com/mvlabat/typedoc-exported-issue

## Environment
  - Typedoc version: 0.15.0
  - Node.js version: v12.10.0
  - OS: macOS Catalina 10.15.1 (19B88)

**Comment by Gerrit0** [comment]
This is expected. We don't support export declarations yet. The work to support them is being tracked in #801

**Comment by mvlabat** [comment]
@Gerrit0, thank you for your response. I guess this issue can be closed then
