### ISSUE TITLE
@hidden annotation hides all documentation for overloads

### ISSUE THREAD

**Issue by fjcaetano** [TypeStrong/typedoc#1142]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

When using the `@hidden` annotation in an overload, only that overload's documentation should be hidden.

## Actual Behavior

The documentation for all overloads, including the implementation is hidden.

## Motivation

I have a method similar to `Promise.all` which I have implemented 10 overloads, supporting 10 different generic types. Since Typescript is able to import the documentation from the implementation, there's no need to document each single overload. At the same time, adding incremental overloads pollutes the Typedoc generated documentation, therefore, most of the overloads's documentation could be hidden.

## Steps to reproduce the bug

Run Typedoc in the following [playground link](http://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=41&pc=58#code/FAMwrgdgxgLglgewgAgLYE8BikoB4AqAjAHwAUwyyApiCFbAFzKkIA2AJgMowCGMVTANpEAugEpkAXmLIAbgjjtkAH2akJ0uQvZiANBWTsqAByoQj0OFQDOQ0frFN5i4KBzwkaLDgKFdyfAAmMgMaOkZmNi5efjs-AMDxKRlnJVVSdWStRT0DI1NzMygrW2RheKCRBydtVwB6ACoG5AABAAtFC2QGuuQ63oB5CFZ0ZBgO62QEWSoAJ1YEHnYAckn2BChJ6zaEMA5kACMqZA72CzdoDxQMbGhffyCHgGYQyjD6GCYWDm4+ATKiA9As8kppUio1BoUtpcpR8mYLMUbHEgSDqtl2K5wJdENdvHcACImBFFErUAAe-HMk1mVCWSBGyB4EHQghEr2otA+Xyiv1iyCJBURJShGIhGVFqVhhmJhUsyIFsuFNnRqXqTQozXGcEmOqZKCo5J4qGMrGO6ygYFQZhiuM1mtaxh4s2NnPCMACbWO71gyCgPFYrAOPCgAGsxghDt7yfQwPx2AA6B0tJ0u1AyoWkmye71c2CrDMk+XWJPdVowdCmVOuwVFpGTfBewty+vLMZgU3HCumfwAdw6UDayD13eOCBAYybzoA5labchaVAqHAZkp+2YHeNc+7h5MqLIA2A+HAINPhxO4B7trt9kcKbH46WehdYLivLc8LWW2TDVT2DS6XWYZRmZVl2XIN480+SIfhif4v2VaxJW0cVMjBGF9DhJUs1KBCcNVFCAG9kAAX1cG4cAyQRex4awABlFnYE9p38NolgAUVmWYEFmUEZEI4ASP8QQYFmMAqH8SAjBAE8qCUWjkE47jZghKSaFk9h-GWdA2AQZZxHqXojigBBrUmZkmS4nhRmsE8l0nMcZnmRjzNpZAQB45AnmQaczDmOAoDGSsbGACjoComj6MY5jWI4rieL45ABKEspRPEyTChkiA5KZSYlM81Q1KyuStJ0hZli0hMqv0sQgA)

## Environment
  - Typedoc version: `0.15.0`
  - Node.js version: `v10.17.0`
  - OS: `macOS 10.14.6`

**Comment by Gerrit0** [comment]
PR welcome, I'm kind of surprised this is how it works currently, I thought reflections were excluded based on their node comment...

**Comment by Gerrit0** [comment]
Fixed in v0.16.3 :) Thanks @socsieng!
