### ISSUE TITLE
Comment not added to function reflections

### ISSUE THREAD

**Issue by billylittlefield** [TypeStrong/typedoc#1144]
Thanks for the great project! I've been running into an issue with comments on function reflections - digging into the source code, I've found a few possible solutions, but I'm unsure if there's desired behavior or something else that I'm overlooking.

- [X] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
If I add Typedoc comments to a function, I expect the corresponding reflection to have a `comment` property containing this content. For instance:

```ts
/**
 * Some function I'd like to document
 * @foo bar
 */
function Baz(): boolean {
   return true;
}
```
I expect the reflection for "Baz" to contain a comment property containing `text`, `tags`, etc.

## Actual Behavior
What I actually see when generating the JSON docs for this is that the comment property does not exist on the function "Baz". It _does_ exist on the function's signature reflection, so I can still garner the information, but ideally I wouldn't have to reach into the signature to grab this information.

It's worth noting that this behavior isn't always the case. For example, if I define the function as a `const` variable like so:
```ts
/**
 * Some function I'd like to document
 * @foo bar
 */
const Baz = (): boolean => {
   return true;
}
```
the comment shows up as expected. I found this is because the reflection hits the `else` in [this code branch](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/plugins/CommentPlugin.ts#L178-L186), which explicitly defines `comment` on the reflection. This doesn't happen in the initial `if` branch, because typically `comment` is defined via the `EVENT_FUNCTION_IMPLEMENTATION` trigger. So, one workaround was to fork the CommentPlugin and explicitly define it in the `if` statement for functions & methods.

_Edit: I see now why this isn't a viable solution, because you could easily end up with duplicated comments. This could be handled in `onFunctionImplementation` to only add a comment if it doesn't have one, but I suppose that would break rolling up comments from signatures into the root function. For my use case, this may be enough._

Another use case where it properly sets `comment` is when I have type overloads on the function, ie:
```ts
function Baz(arg1: number): number;
function Baz(arg1: null): null;
/**
 * Some function I'd like to document
 * @foo bar
 */
function Baz(arg1: number | null): number | null {
   return number ? number * 2 : null;
}
```
The comment is properly added to "Baz" (as well as both of its signatures). This is because the `EVENT_FUNCTION_IMPLEMENTATION` gets fired on subsequent signature creation [here](https://github.com/TypeStrong/typedoc/blob/49602d913d9dc8588e03a404e0b5bd3651bd003b/src/lib/converter/nodes/function.ts#L40-L50). If there's only one signature, though, we don't define `comment`. This led me to a second potential workaround, which was to remove the `else` clause and always trigger `EVENT_FUNCTION_IMPLEMENTATION` instead of only triggering when a new signature isn't being created.

While it seems that there are possible fixes, I imagine there was some rationale for how the logic operates today, so I can't speak to the implications of these workarounds. Any input here would be great!

## Steps to reproduce the bug
This is reproduceable with the above snippets. Create a new repo with typedoc/typescript, create an `index.ts` with the "Baz" snippet from above, and run  `npx typedoc --json docs.json index.ts`.

## Environment
  - Typedoc version: 0.15.0
  - Node.js version: 8.15.0
  - OS: macOS Mojave

Cheers

**Comment by Gerrit0** [comment]
This is certainly undesirable behavior. Thanks for the detailed report!

I don't think it makes sense to trigger `EVENT_FUNCTION_IMPLEMENTATION` on every signature since a signature may not be the implementation signature. But it looks like we are incorrectly not firing `EVENT_FUNCTION_IMPLEMENTATION` when converting the first `Baz`. In that case, we do have the implementation, it just happens to also be a documented signature. I think fixing this should also fix this bug.

PR welcome if you'd like to give fixing that a shot, or I should have time to look more deeply into it next weekend.

**Comment by Gerrit0** [comment]
After more thought, and completely forgetting about this issue... I went the opposite direction. Functions can have multiple signatures, and in that case it's rather confusing as to what the wrapper "function" reflection should have as a comment. In 0.20, `EVENT_FUNCTION_IMPLEMENTATION` is gone and comments appear **only** on the signature.

**Comment by billylittlefield** [comment]
Ah interesting, that makes sense. In any case, thanks for fixing & following up! Cheers.
