### ISSUE TITLE
Question: How to generate uniquely named resource

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [TypeStrong/typedoc#1146]
Hi,

I am generating the application documentation I work on using typedoc. The generation is configured as "file" as we do not define modules.

The files themselves are stored into directory like so:
```
+ root
  + myComponent1
    - Component.ts
    + controller
      - App.controller.ts
      - SomethingElse.ts
  + myComponent2
    - Component.ts
    + controller
      - App.controller.ts
      - AnotherSomethingElse.ts
```

The issue is that during generation the second `Component.ts` overwrites the first one, as well as `App.controller.ts` is overwritten.
I would like to avoid renaming the resources for the only reason of generating documentation.
Is there a way to generate something with unique names, by default, or maybe using a plugin I don't know ?

Thanks.

**Comment by Gerrit0** [comment]
It sounds like you should be using the modules mode, not the file mode.

File mode should be used when your files actually aren't modules and are all globally scoped. In that case, `foo` defined in `myComponent1/Component.ts` would conflict (or merge) with `foo` defined in `myComponent2/Component.ts`

**Comment by GuillaumedesPommareSAP** [comment]
Thanks for your answer. Yes, this is quite obvious this is an issue here.
The other issue is that we are not defining modules, either.

But I will try again the module mode and check what I can adapt so that I generate non conflicting resources. Thanks for this confirmation !
