### ISSUE TITLE
Error jest/jest-extended conflict when generating document

### ISSUE THREAD

**Issue by rxliuli** [TypeStrong/typedoc#1147]
I get the following error when generating with typedoc

```sh
Using TypeScript 3.7.2 from E: \ Text \ rx-util \ node_modules \ typescript \ lib
Error: E: /Text/rx-util/node_modules/@types/jest/index.d.ts (728)
  All declarations of 'Matchers' must have identical type parameters.
Error: E: /Text/rx-util/node_modules/jest-extended/types/index.d.ts (4)
  All declarations of 'Matchers' must have identical type parameters.
```

GitHub repository: <https://github.com/rxliuli/rx-util>

## Steps to reproduce the bug

1. Install dependencies using `yarn`
2. Run `yarn docs` to generate documentation
3. Then the above error will appear. . .

> Running yarn jest alone will not report an error

## Environment

-Typedoc version: ^0.15.3
-Node.js version: v10.16.3
-OS: Win10

**Comment by Gerrit0** [comment]
TypeDoc checks for compiler errors before generating docs. Your package doesn't compile, so it is expected that it would not generate docs...

If you want TypeDoc to ignore compiler errors (with the risk of generating invalid documentation), you can pass `--ignoreCompilerErrors`

**Comment by rxliuli** [comment]
Thanks, but now there is another problem, I want to use it with [typedoc-neo-theme](https://www.npmjs.com/package/typedoc-neo-theme), but the generated docs document is Only the homepage can be accessed, all other pages are 404.

A closer look is because the files under the modules are generated starting with `_module_ *` and the links accessed from the index are in the form `/ modules / FetchLimiting.html`. Is there any way to solve it?

The command i used

```sh
typedoc --out docs src --ignoreCompilerErrors --theme ./node_modules/typedoc-neo-theme/bin/default --exclude src / ** / *. test.ts && cp CNAME docs / && cp readme.md docs / && cp .nojekyll docs /
```

GitHub repository: <https://github.com/rxliuli/rx-util>

**Comment by Gerrit0** [comment]
It looks like typedoc-neo-theme has a strict dependency on typedoc 0.15.0 ([link](https://github.com/google/typedoc-neo-theme/blob/master/package.json#L25)), possibly due to https://github.com/TypeStrong/typedoc/issues/1134, so there are two versions of TypeDoc being required.

You could try removing your local dependency on TypeDoc and calling the one indirectly included due to typedoc-neo-theme, or ask them to upgrade to the latest version.

**Comment by rxliuli** [comment]
我尝试删除了 `typedoc` 的依赖只保留 `typedoc-neo-theme`，但仍然存在这个问题，不知道发生了什么。。。感觉生成侧边栏的程序被莫名其妙修改了。。。
仔细观察了一下，最开始返回的 HTML 是正确的
![image](https://user-images.githubusercontent.com/24560368/70954668-1b6e5980-20a9-11ea-9a33-90187d709284.png)

但在 `main.js` 运行之后却发生了变化，吾辈不清楚发生了什么。。。
![image](https://user-images.githubusercontent.com/24560368/70954616-f11c9c00-20a8-11ea-8d31-94ebce8bd857.png)
![image](https://user-images.githubusercontent.com/24560368/70954702-3d67dc00-20a9-11ea-94de-24eb6ca65320.png)

但如果不使用 `typedoc-neo-theme` 的话链接就是正常的，看起来似乎是 `typedoc-neo-theme` 做了什么事情。。。
![image](https://user-images.githubusercontent.com/24560368/70954763-786a0f80-20a9-11ea-93d4-5b96a1eceba7.png)
