### ISSUE TITLE
question: Is it feasible/possible to generate JSON from disparate files vs a project

### ISSUE THREAD

**Issue by jquense** [TypeStrong/typedoc#1149]
👋 Howdy again. I'm working on a plugin for Gatsby (a static site builder) that has a fairly interesting data layer. without diving to much into it, the most straight forward integration approach would be to consume a stream of File nodes from gatsby and generate typedoc info incrementally. Naively this doesn't seem possible, b/c typedoc complains about referenced files not in the application file list. I was wondering if there was a way to incrementally build up a project and maybe also be able to have typedoc quietly stop for files that it doesn't see?

Sorry if that's a bit rambly happy to dig into the use-case a bit more if needed

**Comment by Gerrit0** [comment]
This isn't currently supported, but it is technically possible... The TypeScript compiler api accepts a `ts.CompilerHost` which controls access to the file system. We don't pass a host to `ts.createProgram` right now, but it seems reasonable to me to make it possible to do this.

https://github.com/TypeStrong/typedoc/blob/5704bf505f1b268c8b2241ecd4c9248a56ec7c0d/src/lib/converter/converter.ts#L279

---

The (much) harder problem is incremental builds. I talk about a few problems in #207
