### ISSUE TITLE
TypeDoc out of memory error in 0.15

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1150]
Hi @Gerrit0, I'm also getting the same error on my repo

https://github.com/pirix-gh/ts-toolbelt

`npm run build:docs`

This happens since my last update, where I made type distribution a default. So I suspect that typedoc tries to unfold types too much. I'd be nice if it could preserve the type "as it is" in the code.

_Originally posted by @pirix-gh in https://github.com/TypeStrong/typedoc/issues/835#issuecomment-568298478_

**Comment by Gerrit0** [comment]
This is happening because we call TypeScript's `typeToString` helper, with the no truncation flag. The `_Assign` type is recursive (against all of the TS's team recommendations, but ideally we shouldn't break on this), so we then go into an infinite loop expanding it.

https://github.com/pirix-gh/ts-toolbelt/blob/bd1c8914265d2206998348537dedbf9147fb1c50/src/Object/Assign.ts#L13-L20

**Comment by Gerrit0** [comment]
It looks like fixing this specific case just requires adding a new type converter for types with kind `IndexedAccessType`

**Comment by pirix-gh** [comment]
Well, believe it or not, those same types are powering ramda. They are recursive types that are crafted not to overflow, the docs *were generating* properly before I started forcing distribution.

In any case, it's my bad, I was distributing a type that ended in a redistribution loop. So this is not a bug, it's my mistake and typedoc is working correctly :tada:

**Comment by Gerrit0** [comment]
TypeDoc should still handle it correctly, so it is a bug I'd like to fix :) I have a fix for the JSON output, I just also need to verify that it works as expected when generating html.

The recursive types won't overflow - so long as they are passed a type. The issue here is TypeScript assumes they aren't recursive and can be fully expanded without a value.

**Comment by Gerrit0** [comment]
Fix has been merged, I should get a release out later today :)
