### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by sliepe** [TypeStrong/typedoc#1151]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

Don't throwing this error.

## Actual Behavior

Throws this error.

## Steps to reproduce the bug

typedoc --out docs [example.ts](https://gist.github.com/sliepe/4caa09231408c68a2306db32d2711fac)

## Environment
  - Typedoc version: 0.15.5
  - Node.js version: v12.9.1
  - OS: Windows 7

**Comment by Gerrit0** [comment]
Did this turn out to be a mistake?

**Comment by sliepe** [comment]
Yes, sorry for the late answer, i would also say, a mistake (a forgotten condition to prevent the error).
I have only fixed this, without deeper understanding where it comes from.

If the source contains errors, like in the example, then this fix is needed.
Therefor i have attached the example for reproduce. This happened also in other places, like linked here: https://github.com/TypeStrong/typedoc/pull/1152#issuecomment-568695076

**Comment by Gerrit0** [comment]
Ah, that makes sense. With #1184 we check for errors before trying to convert, so this will be fixed there too.
