### ISSUE TITLE
TypeDoc should export sufficient values to set options without importing internals

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1163]
Currently (0.16.1) TypeDoc doesn't export all the enums required to set options with type checking. `SourceFileMode` (and possibly other enums) are missing from the root level export.

All options should export sufficient types + values to be able to be set.

Also export `TypeDocAndTypeScriptOptions` + friends as they are missing.

**Comment by socsieng** [comment]
Is this also the reason for not being able to create custom options using the `@Option` decorator?

Custom options fail because they don't meet the following criterial: `function Option<K extends keyof TypeDocOptionMap>(option: { name: K } & KeyToDeclaration<K>)`

**Comment by Gerrit0** [comment]
The `@Option` decorator is more strictly typed since it was intended for internal use, I'd be open to a request to make the types more lax with an overload (like `addDeclaration`) so that external consumers can use it though.

Alternatively, maybe we should encourage plugin developers to add their options to the [`TypeDocOptionMap`](https://github.com/TypeStrong/typedoc/blob/7152031e89e68449e63cfa0140d89eb87a459d8f/src/lib/utils/options/declaration.ts#L37) via declaration merging and then the types on `addDeclaration` can be made more strict.

**Comment by Gerrit0** [comment]
Looking at this:

https://github.com/TypeStrong/typedoc/blob/7152031e89e68449e63cfa0140d89eb87a459d8f/src/lib/utils/options/declaration.ts#L42

This is wrong. I think it should be `{ file: SourceFileMode.File, modules: SourceFileMode.Modules }`

**Comment by socsieng** [comment]
> The `@Option` decorator is more strictly typed since it was intended for internal use, I'd be open to a request to make the types more lax with an overload (like `addDeclaration`) so that external consumers can use it though.

That explains https://github.com/TypeStrong/typedoc/issues/1165

+1 for making `@Option` available for use externally. I would prefer this option over declaration merging.

**Comment by Gerrit0** [comment]
Fixed in 0.16.2
