### ISSUE TITLE
Display external modules according to file hierarchy

### ISSUE THREAD

**Issue by 3nsoft** [TypeStrong/typedoc#117]
Notwithstanding #68 which may produce some deeper way of dealing with external modules, can we have the following little hack for now:
- split external module's name by respective separator of file name ( / or \ )
- treat name parts and their order to form a hierarchy of files (modules), just like module hierarchy is displayed now for internal modules (reuse GUI concepts here)
- put all external module (possibly many) tree(s) into "External Modules" root, or something like this, as Internal/External module worlds are de-facto different, and merging them into one (@ module tag?), probably, shall never be painless 

Today all modules are shovelled into Globals without any structure, although names like "lib/signing/fe25519" have all needed information in them, and, these modules are already labelled as being external.
Introduction of structure in display of external modules shall be those 90% of needed functionality.

**Comment by felixfbecker** [comment]
I would like to see some tree view
