### ISSUE TITLE
Plugins are no longer auto-loaded

### ISSUE THREAD

**Issue by alalonde** [TypeStrong/typedoc#1170]
I was working on updating my [plugin](https://github.com/convergencelabs/typedoc-plugin-custom-modules) for 0.16.2 and noticed that the tests were wholly failing.  

It appears that the `plugins` attribute in the `PluginHost` is initialized to an empty array, which causes this [check](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/plugins.ts#L29) to pass, meaning `discoverNpmPlugins` never gets called.

## Expected Behavior
Omitting the `--plugin` attribute will autoload any npm packages tagged `typedocplugin`

## Actual Behavior
npm plugins are never loaded

## Environment
  - Typedoc version: 0.16.2
  - Node.js version: 10.8
  - OS: macOS 10.15.2

**Comment by Gerrit0** [comment]
Thanks for the report! Should be a simple fix, will fix before 0.16.3 later today.
