### ISSUE TITLE
Fix circularity in dependency tree + add CI check for circularity

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1173]
According to madge, TypeDoc currently has 7 circular dependencies.

```
1) lib/converter/context.js > lib/converter/converter.js
2) lib/models/types/index.js > lib/models/types/array.js
3) lib/models/types/index.js > lib/models/types/indexed-access.js
4) lib/converter/index.js > lib/converter/nodes/index.js > lib/converter/nodes/enum.js
5) lib/converter/index.js > lib/converter/nodes/index.js > lib/converter/nodes/variable.js
6) lib/output/renderer.js > lib/output/plugins/index.js > lib/output/plugins/AssetsPlugin.js
7) lib/output/renderer.js > lib/output/themes/DefaultTheme.js > lib/output/theme.js > lib/output/utils/resources.js
```

#1172 was caused by adding another circular dependency that (unlike the existing 7) was not deferable, and thus caused an application crash when using the CLI. (I still don't really understand why it didn't crash the tests too)

This could have been prevented by a CI check that runs a check for circular dependencies and fails the build if any are detected.

- [x] Fix existing circular dependencies in TypeDoc
- [x] Add a check to CI so that introducing a circular dependency fails the build

**Comment by Gerrit0** [comment]
While doing this, it would be great to simplify the existing dependency tree. This is crazy large, it shouldn't need to be this big... seriously, it reminds me of the time I generated a dependency tree of literally everything installed on a linux box.

![deps](https://user-images.githubusercontent.com/19329837/72400394-4aa6d380-3706-11ea-9661-c3a617fdf261.png)

**Comment by Gerrit0** [comment]
TypeScript 3.8's type only imports / exports should also help with this - https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

**Comment by balthild** [comment]
The problem still exists in v0.28.4

```
(!) Circular dependencies
node_modules/typedoc/dist/lib/utils-common/index.js -> node_modules/typedoc/dist/lib/utils-common/index.js
node_modules/typedoc/dist/lib/models/index.js -> node_modules/typedoc/dist/lib/models/ProjectReflection.js -> node_modules/typedoc/dist/lib/serialization/index.js -> node_modules/typedoc/dist/lib/serialization/deserializer.js -> node_modules/typedoc/dist/lib/models/index.js
```

Occurs when only `typedoc/models` is imported.

**Comment by Gerrit0** [comment]
Weird, I couldn't get madge to report that second circularity...
