### ISSUE TITLE
@BindOption: Unable to resolve signature of property decorator when called as an expression.

### ISSUE THREAD

**Issue by socsieng** [TypeStrong/typedoc#1174]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

Unable to use `@BindOption` for custom option names

## Expected Behavior

Should be able to use `@BindOption` to bind custom options to class member.

## Actual Behavior

Unable to use `@BindOption` with custom option name.

This results in a TypeScript compilation error:

```
TS1240: Unable to resolve signature of property decorator when called as an expression.
```

It works with where the parameter is `keyof TypeDocOptionMap`.

## Steps to reproduce the bug

Sample code that will should result in the error

```ts
export class TestPlugin extends ConverterComponent {
  @BindOption('myParam') // fails - TS1240: Unable to resolve signature of property decorator when called as an expression.
  myParam!: string;

  @BindOption('name') // works with existing TypeDoc option name
  typedocParam!: string;
}
```

## Environment
  - Typedoc version: 0.16.4
  - Node.js version: 8.16.0
  - OS: macOS Catalina

**Comment by Gerrit0** [comment]
Well that's the weirdest TS type checking behavior I've seen in a long time... 

```ts
class Test {
    @Broken // Unable to resolve signature of property decorator when called as an expression. (1240)
    a!: unknown
    @Working
    b!: unknown
}

declare function Broken(obj: object): void
declare function Working(obj: object, key: PropertyKey): void
```
