### ISSUE TITLE
Should removing/hiding a reference remove type references as well?

### ISSUE THREAD

**Issue by socsieng** [TypeStrong/typedoc#1177]
For the given example:

```ts
/**
 * @hidden
 */
class HiddenClass {
}

class AvailableClass {
}

type Classes = HiddenClass | AvailableClass;

class OtherClass {
  hidden: HiddenClass;
  available: AvailableClass;
}
```

The following is effectively the output:

```ts
class AvailableClass {
}

type Classes = HiddenClass | AvailableClass;

class OtherClass {
  hidden: HiddenClass;
  available: AvailableClass;
}
```

The hidden class is removed but there are remaining references to it.

What is the desired behavior in the example above? Should it be as-is or should it remove or remap references? (e.g. replace the references with `unknown`)

Example:

```ts
class AvailableClass {
}

// remove type if in a list
type Classes = AvailableClass;
// alternatively, remap to unknown
// type Classes = unknown | AvailableClass;

class OtherClass {
  hidden: unknown;
  available: AvailableClass;
}
```

I would personally like to see something like:

- Remove the type reference if used in a list,
- Remap the reference to `unknown` if the resulting list is empty,
- Remap the reference to `unknown` if directly referenced

If you are happy with this, I can have a go at implementing it. What are your thoughts?

**Comment by Gerrit0** [comment]
This is tricky. Mapping types not included in the documentation to `unknown` poses a problem because `unknown` is the top type, `unknown | AvailableClass === unknown`. It also implies a less-strict contract when calling a function.

```ts
type Internal = { __internal: true }
declare function withInternal(arg: Internal): void
```

If this is mapped to 
```ts
declare function withInternal(arg: unknown): void
```

Then a user would expect to be able to pass whatever they like into the function... Which isn't right and will likely cause runtime errors.

---

Since TypeScript supports `@internal` for removing a symbol from the declaration file, I decided to take a look at what `tsc` does. It looks like it currently follows the same strategy that TypeDoc does, keeping the name when referenced in other locations but dropping the declaration.

```typescript
/** @internal */
type Internal = 1
type External = 2
export type Foo = Internal | External
```
When compiled with `--stripInternal` will result in

```typescript
declare type External = 2
export declare type Foo = Internal | External
```

**Comment by socsieng** [comment]
> This is tricky. Mapping types not included in the documentation to `unknown` poses a problem because `unknown` is the top type, `unknown | AvailableClass === unknown`. It also implies a less-strict contract when calling a function.

That's why I would prefer that in a union, the removed type be removed from the union (unless the resulting union is empty)

> If this is mapped to
> 
> ```ts
> declare function withInternal(arg: unknown): void
> ```
> 
> Then a user would expect to be able to pass whatever they like into the function... Which isn't right and will likely cause runtime errors.

I think this is semantically correct. As a consumer of the API, because the author hasn't included type information there isn't much choice but to resort to runtime.

What are your thoughts about specifying this behavior with an option?

**Comment by Gerrit0** [comment]
> As a consumer of the API, because the author hasn't included type information there isn't much choice but to resort to runtime.

Fair enough, I still think it provides some value in:

```ts
declare function createSomething(): ExternalConsumersMustNotTouchThis
declare function useSomething(something: ExternalConsumersMustNotTouchThis): void;
```

Including this behavior behind an option would probably be best, at least for an initial pass.
Having thought about this a bit more I think this might eventually be a good default, with `--preserveInternalNames` to keep the behavior TD currently has. I think I really need to look at some documentation with this turned on/off to really see the benefit though.

**Comment by socsieng** [comment]
I had a rough stab at what how an implementation would work.

For the given input:

```ts
/** @hidden */
class HiddenClass {
  a: string;
}

class AvailableClass extends HiddenClass {
  b: string;
}

type MyUnion1 = HiddenClass | AvailableClass;
type MyIntersection1 = HiddenClass & AvailableClass;

class OtherClass {
  hidden: HiddenClass;
  available: AvailableClass;
  doSomething1(): HiddenClass;
  doSomething2(): HiddenClass | undefined;
  doSomething3(param: HiddenClass): void;
  doSomething4(param: keyof HiddenClass): void;
  doSomething5<T extends keyof HiddenClass>(param: T): void;
}

type MyUnion2 = HiddenClass | AvailableClass | OtherClass;
type MyIntersection2 = HiddenClass & AvailableClass & OtherClass;
```

It results in something like this:

```ts
class AvailableClass { // removed from extends
  b: string;
}

type MyUnion1 = AvailableClass; // removed from unions
type MyIntersection1 = unknown & AvailableClass; // remapped in intersections

class OtherClass {
  hidden: unknown; // remapped for simple references
  available: AvailableClass;
  doSomething1(): unknown; 
  doSomething2(): unknown | undefined; // remapped from union return types
  doSomething3(param: unknown): void; // remapped for parameters
  doSomething4(param: keyof unknown): void; // remapped, but not sure it is the best solution
  doSomething5<T extends keyof unknown>(param: T): void; // remapped, but not sure it is the best solution
}

type MyUnion2 = AvailableClass | OtherClass;
type MyIntersection2 = unknown & AvailableClass & OtherClass;
```

What do you think?

**Comment by Gerrit0** [comment]
The union behavior is different in return types? `HiddenClass | undefined => unknown | undefined`

This kind of makes sense, just having `undefined` doesn't make sense... But this still seems wrong at a fundamental level to me. https://github.com/microsoft/rushstack/issues/1664 goes into a similar problem in api-extractor. I'm curious what the generated documentation there looks like.

@aciccarello if you happen to be around to see this, thoughts?

**Comment by socsieng** [comment]
> The union behavior is different in return types? `HiddenClass | undefined => unknown | undefined`

I figure that (at least in this scenario) with type aliases and parameters, a more constrained definition still satisfies the original definition at runtime, where `undefined` only return type does not satisfy the runtime behavior.

> This kind of makes sense, just having `undefined` doesn't make sense... But this still seems wrong at a fundamental level to me.

It seems wrong to me as well.  I'm not sure what the other alternatives are though.

**Comment by socsieng** [comment]
I'm writing a [plugin](https://github.com/socsieng/typedoc-plugin-typescript-declaration) that filters reflections based on the `@since` tag and renders the document as a `.d.ts` file so I might implement this as part of that plugin.

Happy to contribute back if you think it should be part of TypeDoc.

**Comment by Gerrit0** [comment]
Please let me know when you have an implementation, I want to at least see what it generates. I don't want to commit to merging it into TypeDoc proper due to the concerns above, but it is valuable work that might prompt a better solution.

**Comment by socsieng** [comment]
I've implemented it in: https://github.com/socsieng/typedoc-plugin-typescript-declaration/commit/11e3783d966711c9e04d21a096b393d6e1402e8a

A quick way to test it out is to run the following command at a typescript file with hidden types:

```
npx typedoc-plugin-typescript-declaration --remapUnresolvedTypes --out ~/temp/docs file.ts
```

Note that it should only remap types that were removed from the project. I should leave other unresolved types as is.

**Comment by socsieng** [comment]
> > The union behavior is different in return types? `HiddenClass | undefined => unknown | undefined`
> 
> I figure that (at least in this scenario) with type aliases and parameters, a more constrained definition still satisfies the original definition at runtime, where `undefined` only return type does not satisfy the runtime behavior.

Note that the implementation that I ended up going with for unions ended up being simpler, that is, remove unresolved types, unless resulting list results in a union of length 0, or 1 (where the only type is `undefined` or `null`),

- if the resulting union has 0 items, resulting type is `unknown`
- if the resulting union has 1 item which is `undefined`, or `null`, then replace the type with `unknown` instead of removing the type
- if the final union has 1 item, replace the union type with type of the first and only item
