### ISSUE TITLE
Object literal {} renders as __type

### ISSUE THREAD

**Issue by socsieng** [TypeStrong/typedoc#1179]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

Given the following input:

```ts
let test1: object;
let test2: {};
let test3: {
  option1: string,
  option2: number,
};
```

## Expected Behavior

```
test1: object
test2: {}
test3: { option1: string; option2: number }
```

## Actual Behavior

```
test1: object
test2: _type
test3: { option1: string; option2: number }
```

## Environment
  - Typedoc version: 0.16.6
  - Node.js version: 8.16.0
  - OS: macOS Catalina

**Comment by Gerrit0** [comment]
Fixed in typedoc-default-themes v0.7.2 and typedoc v0.16.7
