### ISSUE TITLE
Support for mapped types

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1181]
TypeDoc doesn't currently support generating documentation for mapped types.
```typescript
type NumberValues<T> = { [K in keyof T]: number }
```

Will result in generating docs for the apparent type:
```typescript
type NumberValues<T> = {}
```

---

This is a relatively easy change, it involves creating a new model, a converter, and a serializer and adding another case in [type.hbs](https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/partials/type.hbs) of the default themes to render the model correctly.

It should be possible to follow what I did in https://github.com/TypeStrong/typedoc/commit/0a61a00a69566d7935d79bafbdb5ef5734932a7d to do this.

**Comment by Gerrit0** [comment]
The commit e039eb8 has another example of adding a new converter, with the changes made to type the JSON output.

**Comment by phaux** [comment]
BTW it works if you declare it as an interface.
