### ISSUE TITLE
Overriden methods are treated as inherited

### ISSUE THREAD

**Issue by xshkut** [TypeStrong/typedoc#1191]
First of all, thank you for the project! I believe it has a great future.

The issue is next:
When overriding a method it is visible in docs only when "Inherited" checkbox is ON.
Seems like this is wrong behaviour. It would be correct if I still have my overriden methods visible, not messing them with other inherited methods.

For example, overriding events:

[_copy_] `export class SomeClass extends EventEmitter {} 
export interface SomeClass {
    /**@event */
    on(event: 'SomeEvent', handler: () => void): this
}`

![code](https://user-images.githubusercontent.com/59313986/73082024-55fdba00-3ed1-11ea-927e-d6efb7c25213.PNG)

**Toggling-off "Inherited"**
![not-inh](https://user-images.githubusercontent.com/59313986/73081685-ba6c4980-3ed0-11ea-9071-27e317209394.PNG)

**Toggling-on "Inherited"**
![inh](https://user-images.githubusercontent.com/59313986/73081762-de2f8f80-3ed0-11ea-8b2e-a8b40e91efdc.PNG)
![inh-c](https://user-images.githubusercontent.com/59313986/73081772-e25bad00-3ed0-11ea-8c20-c7145d0d6e35.PNG)

typescript version = 3.7.5
typedoc version = 0.16.8 (same with 0.17.0-3)

**Comment by Gerrit0** [comment]
Oh this is bad... Not only is it not inherited, we are copying the parent method so that it appears that the method is overloaded while using the "first overload" would actually cause a compiler error. Thanks for the report!

**Comment by Gerrit0** [comment]
This has been fixed in 0.20 (currently `typedoc@beta`), the overwritten method is removed.

![image](https://user-images.githubusercontent.com/19329837/100492738-49974e80-30ec-11eb-99e6-0c15935050d6.png)
