### ISSUE TITLE
default export along with named export makes commentary dublicate in --mode library

### ISSUE THREAD

**Issue by xshkut** [TypeStrong/typedoc#1197]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

When exporting SomeClass as `export default SomeClass` along with `export { SomeClass }` there is dublicate description of that class in generated docs. This behaviour appears for `--mode library`
For example:

```
/**Some description */
class SomeClass{ }

export { SomeClass}
export default SomeClass;
```

## Expected Behavior
![expected](https://user-images.githubusercontent.com/59313986/73557611-34b14680-445a-11ea-94bb-b2b3c7687222.PNG)

## Actual Behavior
![bug](https://user-images.githubusercontent.com/59313986/73557641-3ed34500-445a-11ea-830f-a6853d85d10e.PNG)

## Environment
  - Typedoc version: 0.17.0-3
  - Node.js version: 10.14.1
  - OS: Windows 10

**Comment by Gerrit0** [comment]
This works as expected in 0.20

![image](https://user-images.githubusercontent.com/19329837/103250323-8c895380-4930-11eb-94df-76257664e48e.png)

![image](https://user-images.githubusercontent.com/19329837/103250330-9448f800-4930-11eb-9ced-fceff7c9d8ee.png)
