### ISSUE TITLE
@type {Array.<object>} breaks class documentation generation

### ISSUE THREAD

**Issue by tva-TIS** [TypeStrong/typedoc#1198]
The Documentation of a class is incomplete when having  `@type {Array.<object>}` annotated to a property.  `@type {Array.<string>}` does not break, but renders as `@type{Array.}`. Type Annotations may not be needed for TypeDoc anymore but may still be existend from JsDoc usage. TypeDoc does not throw an error to the console.

No duplicate issues found.

## Expected Behavior

Typedoc should be able to handle the type annotation or at least continue with the other properties and methods.

## Actual Behavior

To generate a documentation for the type annotation.

## Steps to reproduce the bug

Have a property with annotation `@type {Array.<object>}` and generate TypeDoc documentation with any settings.

## Environment
  - Typedoc version: 0.16.8
  - TypeScript verison: 3.7.5
  - Node.js version: v10.16.3
  - OS: Windows 10, 64-bit

**Comment by Gerrit0** [comment]
This is definitely a problem, thanks for the report! We need to strip any tags that are just used to describe types.

**Comment by tva-TIS** [comment]
Just to clarify: I think it`s ok that the type annotations are included, but the major problem I see is that the documentation for the file is aborted (just ends at type annotation), if the annotation has a certain syntax.

**Comment by tva-TIS** [comment]
Automatic wripping of certain annotations would be cool however, maybe this would be possible with a whitelist: include all typescript annotations and those in the whitelist. Maybe list annotations that were found that dont match the whitelist.

**Comment by Gerrit0** [comment]
> documentation for the file is aborted

This isn't exactly what happens, we don't HTML-escape doc comments, so leaving `<object>` in the source creates a [`HTMLObjectElement`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object).

Conditionally escaping HTML content seems really error prone to me, so I'd rather just remove type annotations. (It should be redundant information in the first place, types should live as TS annotations, not comments)
