### ISSUE TITLE
categorizeByGroup=false seems broken

### ISSUE THREAD

**Issue by jonaskello** [TypeStrong/typedoc#1199]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

I would expect setting `categorizeByGroup=false` would lump all the different groups (types,functions,classes etc.) under a common category heading.

## Actual Behavior
Settting  `categorizeByGroup=false` ignores the `@category` tags and just creates output without any category headings. It does however create category headings if I set it to true or just leave the setting out.

## Steps to reproduce the bug

This repository has the described behavior:

https://github.com/typescript-tea/http

The config file says `categorizeByGroup: false` [here](https://github.com/typescript-tea/http/blob/5958a1736e0d0668929c19495c4ad5d1cb53d970/typedoc.js#L9). The output is [here](https://typescript-tea.github.io/http/modules/_http_.html). The source for one moudle with `@category` tags is [here](https://github.com/typescript-tea/http/blob/7c6c3f56267de652b7a802f7ce82178cb9c2fc1e/src/http.ts).

## Environment
  - Typedoc version: 0.17.0-3
  - Node.js version: v12.14.1
  - OS: Ubuntu 18.04 (via Windows WSL2)

**Comment by Gerrit0** [comment]
This does look like a bug, the PR that added this functionality seems to indicate that's how it should work. Thanks for the simple repro!

> **Group Categories** - https://github.com/TypeStrong/typedoc/pull/938#issue-242374499
Categories can now be used within groups or as lump categories. Lump categories mean if you have a method and property you want together, you can do so. The option --categorizeByGroup controls this. By default, reflections will be categorized by group (within properties, methods, etc).

**Comment by jonchardy** [comment]
See https://github.com/TypeStrong/typedoc-default-themes/pull/114. This appears to just be a theme issue.

**Comment by jonaskello** [comment]
Nice, thanks for fixing this! :-)

I guess it will make it into the next release?

**Comment by Gerrit0** [comment]
If you delete your lock file and reinstall, it should be picked up now :)
