### ISSUE TITLE
distinguish optional vs required in properties overview

### ISSUE THREAD

**Issue by slohr-agi** [TypeStrong/typedoc#1200]
We have a number of interfaces with a large number of optional properties, and a small number of required properties. It would be helpful if the generated API documentation styled optional and required properties differently in the properties overview section, to draw the reader's attention to the required properties.

If that is impractical, a middle ground would be to indicate optional vs required in the html of the properties overview section, so we could apply our own styling to reach the effect described above. It would also be acceptable to make either or both of these behaviors activate only if specifically requested by a build setting. I think this would be of enough general benefit, though, that including in the default output and styling would be preferable.

I haven't spotted any indication of typedoc parameters that I could use to activate this behavior currently, or any tickets indicating plans to add it.

Example...
export interface Foo {
  req: string,
  opt?: string,
}

Ends up with a properties overview section like...
<section class="tsd-panel tsd-index-panel">
  <div class="tsd-index-content">
    <section class="tsd-index-section ">
      <h3>Properties</h3>
      <ul class="tsd-index-list">
        <li class="tsd-kind-property tsd-parent-kind-interface"><a href="_nrm_map_util_.foo.html#opt" class="tsd-kind-icon">opt</a></li>
        <li class="tsd-kind-property tsd-parent-kind-interface"><a href="_nrm_map_util_.foo.html#req" class="tsd-kind-icon">req</a></li>
      </ul>
    </section>
  </div>
</section>

Notice that the "li" items for the two properties differ only by their name, with no indication of the different status related to one being optional. Unsurprisingly, there's  no style difference, as shown by this partial screen shot:
![image](https://user-images.githubusercontent.com/8573185/74174775-6c05bd00-4be9-11ea-8d5d-50568cb1ef84.png)

**Comment by Gerrit0** [comment]
This should be possible with a custom theme, haven't tested this, but it (or something very similar) should work:

1. Copy https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/partials/index.hbs to `<theme>/partials/index.hbs`
2. Change the anchor line to this:

```handlebars
<li class="{{cssClasses}}">
  <a href="{{relativeURL url}}" class="tsd-kind-icon">
    {{#if flags.isOptional }} {{! CHANGE ME !}}
        {{#if name}}{{{wbr name}}}{{else}}<em>{{{wbr kindString}}}</em>{{/if}}
    {{else}}
        {{#if name}}{{{wbr name}}}{{else}}<em>{{{wbr kindString}}}</em>{{/if}}
    {{/if}}
  </a>
</li>
```

I'd like to rebuild the default theme, it gets the job done, but isn't ideal in many ways...

**Comment by Gerrit0** [comment]
This can be done with a custom theme in 0.23 fairly easily, by overriding the `index` partial ([reference implementation](https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/default/partials/index.tsx)).

Properties can also be grouped with the [`@group`](https://typedoc.org/tags/group/) and [`@category`](https://typedoc.org/tags/category/) tags, which might be a good fit depending on the project.
