### ISSUE TITLE
Type declaration of an optional object is not rendered

### ISSUE THREAD

**Issue by omarmahili** [TypeStrong/typedoc#1202]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

Type declaration of an optional object should be rendered.

## Actual Behavior

Type declaration of an optional object is not rendered.

## Steps to reproduce the bug

Given this code:

```
/**
 * Lorem ipsum
 */
class Foo {
    /**
     * Lorem ipsum
     */
    public bar?: {
        /**
         * Lorem ipsum
         */
        foobar: string;
    };
}
```

It renders as:

![](https://user-images.githubusercontent.com/3227034/72569251-3efc0e00-38ba-11ea-8d35-5c70af5fe8be.png)

Shouldn't "**Type declaration**" be rendered below? Who looks at the documentation knows that **bar** can be an object with a **foobar** property, but doesn't know what it is about.

This happens with nested properties too, for example:

```
/**
 * Lorem ipsum
 */
class Foo {
    /**
     * Lorem ipsum
     */
    public bar: {
        /**
         * Lorem ipsum
         */
        foobar?: {
            /**
             * Lorem ipsum
             */
            baz: string;
        };
    };

    //...
}
```

Renders as:

![](https://user-images.githubusercontent.com/3227034/72570339-ebd78a80-38bc-11ea-91e0-a9653855ec60.png)

And **baz** is not documented.

## Environment
  - Typedoc version: 0.16.9
  - Node.js version: 13.5.0
  - OS: Windows

**Comment by Gerrit0** [comment]
This is somewhat expected since an optional type no longer just an object type - it is a union type with undefined and the object. That said, it seems reasonable to add a special case here for `undefined | object type` where the object type is expanded.

**Comment by VinSpee** [comment]
I can't tell… is this related? 

![image](https://user-images.githubusercontent.com/582828/74770429-3e102080-525a-11ea-8624-1919b03b1a3c.png)

typedef:

```
/**
 * @param red  Red channel gamma correction.
 * @param green  Green channel gamma correction.
 * @param blue  Blue channel gamma correction.
 */
type GammaOptions =
  | Partial<{
      red: number;
      green: number;
      blue: number;
    }>
  | number;

/**
 * @param sigma  Blur spread amount in pixels.
 * @param radius  Radial constraint of blur or zero if unconstrained. Should be at least 2x sigma if specified.
 */
type BlurOptions =
  | Partial<{
      sigma: number;
      radius: number;
    }>
  | number
  | boolean;

/*
 * @param radius  Number of pixels to which sharpening should be applied surrounding each target pixel.
 * @param sigma  Size of details to sharpen in pixels. (Pedantically: the standard deviation of the Gaussian.)
 * @param amount  Decimel percentage representing the strength of the sharpening in terms of the difference between the sharpened image and the original.
 * @param threshold  Decimal percentage representing a minimum amount of difference in a pixel vs surrounding colors before it's considered a sharpenable detail.
 */

type UnsharpOptions =
  | Partial<{
      radius: number;
      sigma: number;
      amount: number;
      threshold: number;
    }>
  | boolean;

/**
 * @param width  Target image width in pixels.
 * @param height  Target image height in pixels.
 * @param quality  Image quality as a percentage (0-100). Defaults to 82.
 * @param fit  Will zoom and crop the image for best fit into the target dimensions (width and height) if both are provided. Defaults to true.
 * @param defaults  Default options are excluded if set to false. Defaults to true.
 * @param align  If cropping occurs, the image can be aligned to the "top", "bottom", "left", "right", or "middle" of the crop frame.
 * @param crop  Image crop configuration.
 * @param blur  Image blur configuration (object) or blur spread amount in pixels (number).
 * @param gamma  Gamma correction, applied either to the whole image (number) or to individual color channels (object).
 * @param grayscale  Fully desaturates the image if truthy. Optionally you may also darken the image by specifying a decimal percentage value of less than 1.
 * @param unsharp  Applies an unsharp mask if true. Precise configurations can be specified in object form:
 * @param query  Additional query parameters to include in the Crushinator-optimized image URL.
 */
export type CrushConfig = Partial<{
  width: number;
  height: number;
  quality: number;
  fit: boolean;
  defaults?: boolean;
  align: 'top' | 'bottom' | 'left' | 'right' | 'middle';
  crop?: CropOptions;
  blur?: BlurOptions;
  gamma?: GammaOptions;
  grayscale: boolean | number;
  unsharp?: UnsharpOptions;
  query: Record<any, any>;
  'crop-afterResize': boolean;
  'crop-width': number;
  'crop-height': number;
  'crop-x': number;
  'crop-y': number;
}>;
```

I'd expect:

1. to see the name of the parameters
2. to see the type of the parameters

**Comment by Gerrit0** [comment]
Not at all related - you can't just use `@param` anywhere and expect it to be applied to properties of an object. This is *not* a supported pattern:

```ts
/** @param property description */
type Z = { property: string }
```

This *is* a supported pattern.

```ts
interface Z {
  /** description */
  property: string
}
```

This *may* work, but is not guaranteed to work. We don't have tests to validate this behavior (unless one is escaping me right now). Further, I'm not sure special casing an object literal type for type aliases is a good idea...

```ts
type Z = {
  /** description */
  property: string
}
```

This is *not* a supported pattern. We do not support documenting parts of types (with the exception of properties on object types)

```ts
type Z = string | /** docs for number */ number
```

**Comment by VinSpee** [comment]
thanks!

**Comment by Gerrit0** [comment]
In 0.20, the code in the OP renders as:

![image](https://user-images.githubusercontent.com/19329837/103250437-06b9d800-4931-11eb-9db1-bb8f1ab349e9.png)
