### ISSUE TITLE
Is there a way to rename interfaces in docs for Symbols References?

### ISSUE THREAD

**Issue by alexandercerutti** [TypeStrong/typedoc#1203]
Hey there,
I've tried to link in the Readme.md a symbol and I saw that I can set a link to a symbol:

``` bla bla bla [[Props]] bla bla bla ```
or
``` bla bla bla [[Props | ProjectProps]] bla bla bla ```

Sadly I have to leave "Props" named as is, but this name is confusing and I'm exposing this interface to the outside of the project as `ProjectProps`.

```typescript
export { Props as ProjectProps } from "..";
```

Also, what happens if I have two interfaces, from different parts of the project, that are named both "Props"?

___

I was thinking: is there a way, like comments, to rename an interface for docs only? If not, can this be included? (EDIT: found this https://github.com/TypeStrong/typedoc/issues/1201)

E.g. JSDoc through tag @alias

```typescript
/**
 * @alias ProjectProps
 */
export interface Props {
  ...
}
```

Result in docs would be something like this:

```
bla bla bla [[ProjectProps]] bla bla bla
```

will be like:

```
bla bla bla [[Props]] bla bla bla
```

Thank you very much.

P.s. I did not use Feature Request template because I'm not sure if this thing already exists or not.
If this becomes a Feature Request, If needed, I'll edit this post to the form.

**Comment by Gerrit0** [comment]
It sounds like you are building with `--mode file`.

File mode is intended for projects which do not use modules. (tsc compilation with `--module none`). It pretends that every file is global, so any declarations with the same name will be merged.

Unfortunately, many projects (TypeDoc included) use file mode because modules mode results in incredibly ugly output that reveals internal file paths. This is being remedied with library mode (#1184) but that isn't ready for a stable release yet (though you can try it out by installing `typedoc@next`)

With library mode, `Props` will be renamed to `ProjectProps` in the documentation if that is what it is exported as.

**Comment by alexandercerutti** [comment]
Thank you for your reply.

Yeah, I'm actually using file mode. I've tried module mode but it did not seem to be suitable for the project I'm on at work (which is composed of a lot of internal imports). I should retry because I don't remember that much which was the reason, but for sure not the one you said because I currently see the full path of each declaration, etc.

How does typedoc gets told to rename `Props` in `ProjectProps` in library mode? Starting from the main file?
Anyway, the support to `@alias` from JSDoc should be added IMHO.

**Comment by Gerrit0** [comment]
> How does typedoc gets told to rename Props in ProjectProps in library mode? Starting from the main file?

Library mode will look at what is actually exported from the given entry point(s) using TypeScript's APIs to get the exported name. If you use `typedoc --out docs src/index.ts`, then the output will resemble file mode with all entries not exported marked with `@hidden`, but all exported symbols will be given the name they are exported under. If more than one entry point (or a directory) is specified, the output will be similar to modules mode where each entry point gets a top level entry and then includes all exported content inside it.

This (mostly) works already, but causes some problems if symbols are exported under multiple names. I think I'm getting close to ironing out the kinks there, but it is taking a while.

> Anyway, the support to `@alias` from JSDoc should be added IMHO.

I'm loath to add support for `@alias`. TypeScript should know about all of the exports, and TypeDoc should be able to pick that information up from TypeScript. The `@alias` tag is a way to lie about how symbols are exported.

**Comment by alexandercerutti** [comment]
That's great to hear. So, I won't need anymore to use a lot of globs expressions to exclude files and folders that are getting included right now, isn't it?

About the `@alias`, yeah, sort of lie. Maybe it won't be needed anymore.

**Comment by Gerrit0** [comment]
Correct, I hope that library mode should make it possible to stop using the exclude/external options.

**Comment by alexandercerutti** [comment]
I found that `modules` mode right now is better for the project I'm on. I don't know why I didn't like it before.
Anyway, it is a bit mode "pathy" and it has not all the voices on the side (also with `toc` options)

**Comment by Gerrit0** [comment]
In 0.20 (currently `typedoc@beta`, TypeDoc asks TypeScript for the exported names, and uses those when generating documentation.
