### ISSUE TITLE
Mixins cause: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by zslayton** [TypeStrong/typedoc#1207]
I have [a Typescript codebase](https://github.com/amzn/ion-js/tree/zslayton-load-dom) that employs mixins.

* Example mixin: [DomValue](https://github.com/amzn/ion-js/blob/531cbd89b6fb584093931f2317b42c859e383d83/src/dom/DomValue.ts#L23)
* Example subclass: [dom.Integer](https://github.com/amzn/ion-js/blob/531cbd89b6fb584093931f2317b42c859e383d83/src/dom/Integer.ts#L10)

Running `typedoc` fails with the following stack trace:
```
Using TypeScript 3.7.5 from node_modules/typescript/lib
node_modules/typedoc/dist/lib/converter/nodes/class.js:65
                            && typeToInheritFrom.symbol.declarations.forEach((declaration) => {
                                                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at typesToInheritFrom.forEach (node_modules/typedoc/dist/lib/converter/nodes/class.js:65:70)
    at Array.forEach (<anonymous>)
    at context.withScope (node_modules/typedoc/dist/lib/converter/nodes/class.js:62:40)
    at Context.withScope (node_modules/typedoc/dist/lib/converter/context.js:101:9)
    at ClassConverter.convert (node_modules/typedoc/dist/lib/converter/nodes/class.js:33:17)
    at Converter.convertNode (node_modules/typedoc/dist/lib/converter/converter.js:116:53)
    at Context.inherit (node_modules/typedoc/dist/lib/converter/context.js:140:24)
    at typeToInheritFrom.symbol.typeToInheritFrom.symbol.declarations.forEach (node_modules/typedoc/dist/lib/converter/nodes/class.js:66:37)
    at Array.forEach (<anonymous>)
    at typesToInheritFrom.forEach (node_modules/typedoc/dist/lib/converter/nodes/class.js:65:70)
```

The issue is caused by [this code](https://github.com/TypeStrong/typedoc/blob/61a454285c19016ff59e20376e9faad809f8a8c6/src/lib/converter/nodes/class.ts#L72), reproduced here with slightly different formatting:

```javascript
typesToInheritFrom.forEach((typeToInheritFrom) => {
    typeToInheritFrom.symbol
    && typeToInheritFrom.symbol.declarations.forEach((declaration) => {
       context.inherit(declaration, baseType.typeArguments);
    });
});
```

If I change it to:

```javascript
typesToInheritFrom.forEach((typeToInheritFrom) => {
    typeToInheritFrom.symbol
    && typeToInheritFrom.symbol.declarations // <--- Make sure this is defined
    && typeToInheritFrom.symbol.declarations.forEach((declaration) => {
       context.inherit(declaration, baseType.typeArguments);
    });
});
```
then documentation is generated normally. I have not studied the code long enough to understand its intent, so I'm unsure if this change is the best approach.

This failure did not occur in my project until I started using mixins. Additionally, the code above was added in [a PR to introduce mixin support](https://github.com/TypeStrong/typedoc/commit/49602d913d9dc8588e03a404e0b5bd3651bd003b).

- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

Typedoc should finish generating documentation successfully.

## Actual Behavior

Typedoc throws an Error, preventing documentation from being generated and causing CI builds to fail.

## Steps to reproduce the bug

* [Example branch](https://github.com/amzn/ion-js/tree/zslayton-load-dom/src/dom) with failing code.
* Gruntfile.js [`typedoc` config](https://github.com/amzn/ion-js/blob/zslayton-load-dom/Gruntfile.js#L30-L34):
```javascript
typedoc: {
  build: {
    src: 'src/**/*'
  }
}
```

### Laptop
  - Typedoc version: 0.16.9
  - Node.js version: 11.13.0
  - OS: mac OS mojave

Here's a link to [the failing Travis CI Build](https://travis-ci.org/amzn/ion-js/builds/648541266?utm_source=github_status&utm_medium=notification), which runs on Node v8, v10, and v12 on Linux.

**Comment by Gerrit0** [comment]
This is really weird, my first instinct was that `typeToInheritFrom.symbol` was an internal definition that we used and TS's behavior didn't change, but it is defined in the TS declarations.

I really don't want to add checks for undefined when the TS declaration file claims it will never be defined, but maybe the TS types are just wrong here? Looking more deeply into it.

**Comment by Gerrit0** [comment]
I'm beginning to think this is a TS bug... I've tried to reduce it to a smaller example but haven't been able to. For now I'll just merge the PR with a note that this is really weird and needs further investigation.
