### ISSUE TITLE
Set meta description on each page

### ISSUE THREAD

**Issue by mbykovskyy** [TypeStrong/typedoc#1211]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
Moz site crawler complains about empty `description` meta tag.

From moz.com help page:

> Why it's an issue:
> Meta descriptions are a very important factor in improving click-through rates on SERPs. In the absence of a meta description, social media platforms and search engines will pull in the first matching text they find on page, which may not be interesting for users. If it's too long or doesn't relate to what the searcher is looking for, you may be missing a traffic-driving opportunity.

## Suggested Solution
Set `description` meta tag on each generated page, or allow it to be set manually.

**Comment by Gerrit0** [comment]
You can set it manually by creating a custom theme as described [here](https://github.com/TypeStrong/typedoc/issues/1212#issuecomment-589997923).

It seems like an easy improvement to change it in the default theme to:
```html
<meta name="description" content="Documentation for {{project.name}}">
```

Doing more than this (e.g. grabbing the first part of the module comment for each file) quickly gets more complicated than it seems worth handling. PR welcome for the simple solution!

**Comment by Gerrit0** [comment]
Improvement I described above has been implemented with https://github.com/TypeStrong/typedoc-default-themes/commit/a36b2eb06ceecaee11f184979998838f88fc4011

**Comment by jevonearth** [comment]
Hi, 

The change implented in a36b2eb makes the meta tag look like this:

`<meta name="description" content="Documentation for {{project.name}}">`

Which uses the global package name. What we would like is to have a description from the actual package. This could be taken, for example, from the `description` property in `package.json`. Would this be possible?

For example, if your `package.json` description looks like this:

`"description": "High-level functionality that builds upon the other packages in the Tezos Typescript Library Suite."`

Would render a meta tag like this:

`<meta name="description" content="High-level functionality that builds upon the other packages in the Tezos Typescript Library Suite">`

**Comment by Gerrit0** [comment]
Yeah, that's possible. I believe you could do that with `{{project.packageInfo.description}}`
