### ISSUE TITLE
Add an option to specify favicon path

### ISSUE THREAD

**Issue by JanMalch** [TypeStrong/typedoc#1212]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

You can't specify the path to a favicon, which means the browser can't find the favicon if the documentation is not hosted in the root path.

## Suggested Solution

Add an option to the set favicon path. Or maybe the base path, if that helps the browser find a favicon.

**Comment by Gerrit0** [comment]
Is your favicon not located at the root path? TypeDoc doesn't have any specific handling to tell the browser where it is (in the default theme at least)

You can set a favicon path by doing the following:

1. Create `<theme dir>/layouts/defaults.hbs`
1. Put https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/layouts/default.hbs into that file
1. Add a `<link rel="icon"` tag to the header that points to the correct path

**Comment by JanMalch** [comment]
Thanks, this works with the default theme, but when using the minimal theme's templates it doesn't seem to work. I guess that relates to https://github.com/TypeStrong/typedoc/issues/36?

**Comment by Gerrit0** [comment]
Ah, yes if you want to change the minimal template right now you'd have to copy the whole structure and also change the rendering setup. #36 would make this easier.

**Comment by JanMalch** [comment]
Okay thanks. I close this issue in favour of the other one.

**Comment by Drarig29** [comment]
I created a plugin to add a favicon (and date/time of generation) via an argument in the command line. It may be useful to someone later... 😀

https://www.npmjs.com/package/typedoc-plugin-extras

**Comment by willeastcott** [comment]
Hi @Gerrit0 - sorry to revisit this but `typedoc-plugin-extras` is not yet compatible with TypeDoc 0.26.x and I only use it for setting a favicon. What would be the 'up-to-date' way of setting a favicon when using the default template without using a plugin?

**Comment by Drarig29** [comment]
Hi @willeastcott! I'll let Gerrit answer for the plugin-less way to do it.

In the meantime, I just published a new version of `typedoc-plugin-extras` to support TypeDoc 0.26.x: [`v3.1.0`](https://github.com/Drarig29/typedoc-plugin-extras/releases/tag/v3.1.0)

**Comment by Gerrit0** [comment]
Without a plugin, there isn't a way to do it - that is one option that it might make sense to upstream from typedoc-plugin-extras, I suspect more people want a favicon than custom CSS, which is already in typedoc directly...

**Comment by willeastcott** [comment]
Yeah, I'd agree that it would be useful to see custom favicon support added to the core. I _was_ using custom CSS but only to handle the navigation links on mobile, but since 0.26.x fixed that, I don't need it any more! 🎉
