### ISSUE TITLE
Re-export TypeScript namespaces (or at least ones with enums)

### ISSUE THREAD

**Issue by KSXGitHub** [TypeStrong/typedoc#1213]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

`Application#bootstrap` requires some enum options. I cannot provide them unless I have access to TypeScript enum objects.

[Why is this a problem?](https://user-images.githubusercontent.com/11488886/75003887-f4af1380-549b-11ea-94aa-73b505b0c323.png)

I could have added TypeScript version that TypeDoc uses to my dependency list, but that means that:
* I have to check for which version TypeDoc uses every time I update TypeDoc.
* I cannot use TypeScript version I desired.

## Suggested Solution

Either:
  * Re-export typescript namespaces: `export * as ts from 'typescript'`
  * Re-export namespaces from typescript: `export { ScriptTarget, ModuleKind } from 'typescript'`

**Comment by Gerrit0** [comment]
In 0.17 this will be fixed by TypeScript moving to a peer dependency - #1184.

It seems reasonable to re-export the ts namespace until 0.17 is ready, PR welcome.

**Comment by KSXGitHub** [comment]
@Gerrit0 https://github.com/TypeStrong/typedoc/pull/1217
