### ISSUE TITLE
setter in declaration file gets any as return type iso void

### ISSUE THREAD

**Issue by PissedCapslock** [TypeStrong/typedoc#1215]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

When running Typedoc on the following declaration file, I expect that the setter has `void` as return type.

```
/**
 * The Foo class
 */
declare class Foo {
    private _bar;
    /**
     * The bar method
     * @return something
     */
    get bar(): string;
    /**
     * The setter for the bar method
     * @param bar
     */
    set bar(bar: string);
}
export { Foo };
```

## Actual Behavior

The generated documentation says that the setter has `any` as return type.

This is also visible in the json:

```
"setSignature": [                                        
	{                                                    
		"id": 5,                                         
		"name": "__set",                                 
		"kind": 1048576,                                 
		"kindString": "Set signature",                   
		"flags": {                                       
			"isExported": true                           
		},                                               
		"comment": {                                     
			"shortText": "The setter for the bar method",
			"returns": "something\n"                     
		},                                               
		"parameters": [                                  
			{                                            
				"id": 6,                                 
				"name": "bar",                           
				"kind": 32768,                           
				"kindString": "Parameter",               
				"flags": {                               
					"isExported": true                   
				},                                       
				"comment": {                             
					"shortText": "\n"                    
				},                                       
				"type": {                                
					"type": "intrinsic",                 
					"name": "string"                     
				}                                        
			}                                            
		],                                               
		"type": {                                        
			"type": "intrinsic",                         
			"name": "any"                                
		}                                                
	}                                                    
],
```

## Steps to reproduce the bug

Run Typedoc on the declaration file mentioned above using

```
typedoc --mode modules --out docs --includeDeclarations --excludeExternals Foo.d.ts
```
The setter will have `any` as return type.

Note that it works as expected when using a `.ts` file instead of the corresponding `.d.ts` file. Looking at the Typedoc code base, there are tests that cover the `.ts` scenario but none for the `.d.ts` case.

Not sure if this is a Typedoc issue or rather a problem with Typescript itself. My attempt at debugging this problem gave me the idea that the Typescript compiler returns a different return type for both cases.

## Environment
  - Typedoc version: typedoc@0.16.10
  - Node.js version: v12.11.1
  - OS: Ubuntu

**Comment by PissedCapslock** [comment]
You can work around this issue in the theme by hardcoding that setters have `void` as return type. Did this in https://github.com/PissedCapslock/typedoc-default-themes/commit/fa439d8dc8866fa2071c1aad8c53732ed1e1cf01

**Comment by Gerrit0** [comment]
This is really weird. I would have expected the return type in both cases to be `string`  since you can do this:

```ts
const foo = new Foo();
const bar: string = foo.bar = 'str';
```

Should setters even have return types? Hovering over the property in the playground shows `(property) Foo.bar: string`

**Comment by PissedCapslock** [comment]
No, Typescript gives an error when you try to define a return type for a setter.
That's why I felt confident in adjusting my custom theme to simply hardcode `void` as return type for setters.
