### ISSUE TITLE
Redundant `undefined` emitted for optional properties

### ISSUE THREAD

**Issue by vitaly-t** [TypeStrong/typedoc#1223]
I'm not sure whether this should be considered a bug or feature request, so I hope this format is ok.

---

For every optional parameter, this library emits redundant `undefined` type, along with `?`:

**Source:**

```
method(options?: { name?: string; timeout?: number });
```

**Output:**

```ts
method(options?: undefined | { name?: undefined | string; timeout?: undefined | number });
```

This looks odd. Why not produce the TypeScript native type? It would look more readable, without the extra `undefined` that makes documentation look too verbose, and less readable.

---

* TypeScript v3.8.3
* TypeDoc v0.16.11
* NodeJS v13.8.0

**Comment by vitaly-t** [comment]
I can see this was once suggested, in #1063, but then was closed without resolution.

**Comment by Gerrit0** [comment]
PR welcome if you want to give this a shot. This should just be a theme change - the type should still be represented internally as a union type since that is what it is.

**Comment by Gerrit0** [comment]
Version 0.20 (currently `typedoc@beta`) removes undefined from optional properties

![image](https://user-images.githubusercontent.com/19329837/100491624-5020c880-30e2-11eb-9e40-8a6fc7121a2d.png)
