### ISSUE TITLE
Remove tsdocs from documented const initialisers 

### ISSUE THREAD

**Issue by knoan** [TypeStrong/typedoc#1224]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Steps to reproduce the bug

Generate docs for the following snippet:

```typescript
export const Work={

	/**
	 * Lorem ipsum
	 */
	a: "one" as string,

	/**
	 * Sit amet
	 */
	b: 2 as number

} as const;
```

`tsconfig.json`

```json
{
	"typedocOptions": {
		"mode": "modules",
		"theme": "minimal",
		"out": "docs"
	}
}
```
## Expected Behavior

tsdocs not included in documented const initialiser, i.e.

```
Work: { a: string; b: number } = { a: "one", b: 2 } as const
```

## Actual Behavior

tsdocs included verbatim in documented const initialiser, i.e.

![Screenshot 2020-03-05 at 14 51 02](https://user-images.githubusercontent.com/6105462/75988682-3f944680-5ef2-11ea-8c2e-12ec6743da86.png)

## Environment

  - Typedoc version: 0.16.11
  - Node.js version: v11.10.0
  - OS: macOS 10.15.3

**Comment by Gerrit0** [comment]
This happens here:

https://github.com/TypeStrong/typedoc/blob/d18664d86e85726a725a33e045090cc971d08d65/src/lib/converter/convert-expression.ts#L19-L34

I think it should be possible to ask TS for a printer configured to remove comments and use that instead of getText. PR welcome if you'd like to give it a shot. I probably won't get to it for a while.

**Comment by Gerrit0** [comment]
0.20.1 renders this as:

![image](https://user-images.githubusercontent.com/19329837/103258334-cae33a80-4951-11eb-9430-fb158fe458c5.png)

In investigating other issues with the initializers, I decided that showing complex values was mostly not useful, so now only a few detected "simple" expressions are shown.
