### ISSUE TITLE
Reference to type of property

### ISSUE THREAD

**Issue by crowlKats** [TypeStrong/typedoc#1226]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
let's take this example:
```ts
export interface y {
	id: z["id"],
	hello: string,
	bar: boolean
}

export interface z {
	id: string,
	world: string,
	foo: any
}
```
when generating documentation for this code, this is the result for `y`: 
<img width="853" alt="Screenshot 2020-03-10 at 00 57 44" src="https://user-images.githubusercontent.com/13135287/76267207-46acb300-626a-11ea-9b81-181fbb1b5569.png">

## Suggested Solution
Either set the type of `y`'s `id` to be the value of `z["id"]` (so `string`), or make it a link to the `id` of the `z` interface.

**Comment by Gerrit0** [comment]
I think it would be best to create links in this case, pulling all the indexed access types in directly could cause problems.

There are a couple changes required here.

1. Fix indexed access types - apparently they aren't storing the ID of their object type if it is a reference (or maybe reference types are broken, not sure)
![image](https://user-images.githubusercontent.com/19329837/76707100-22aa0100-66b2-11ea-9781-dc44f0177808.png)
1. Update the themes so if the objectType of an indexed access type is a reference and the index type is a string literal, the string literal is linked to the member of the reference type of that name.
