### ISSUE TITLE
[Ask for Help] How can i hide all of `tsd-sources` DOM?

### ISSUE THREAD

**Issue by chudongvip** [TypeStrong/typedoc#1227]
![image](https://user-images.githubusercontent.com/31001856/76293148-8071ce00-62eb-11ea-8ab2-01060303216d.png)
I‘ve tried all the typeDoc Options, and none of the properties can hide this element(’className is tsd-sources‘)，So i wanna ask somebody help me.

**Comment by Gerrit0** [comment]
With 0.17, you will be able to pass `--disableSources` to remove this.

**Comment by chudongvip** [comment]
great! When will it be released?

**Comment by Gerrit0** [comment]
Hopefully this weekend.

**Comment by Gerrit0** [comment]
Fixed with 3dadcde3a4f4caec01e2676cacfb3149efef5183, release soon.
