### ISSUE TITLE
Remove path from right side naviation

### ISSUE THREAD

**Issue by FlippieCoetser** [TypeStrong/typedoc#123]
When generating the documentation the `path` and `module` are displayed as `path/module` in the right side navigation.

Is there a way to not show the `path` so that the right side navigation only show `module`?

**Comment by sebastian-lenz** [comment]
Hi, sorry, but currently you cannot do that. But the handling of modules will change in the near future there are already multiple issues discussing this. See #68, #98, #111 and #117. Both the first and and the last issue reminds me of your request.

**Comment by samvloeberghs** [comment]
any progress on this? I like typedoc a lot but this is uglyfing it :)

**Comment by nadhir-falta** [comment]
any news about this issue?

**Comment by Gerrit0** [comment]
This can be done using the [typedoc-plugin-external-module-name](https://github.com/christopherthielen/typedoc-plugin-external-module-name) plugin, still no built in way to do it. It could also be done by modifying the theme (I believe typedoc-neo-theme does this)
