### ISSUE TITLE
How to parse index.d.ts files?

### ISSUE THREAD

**Issue by LJNeon** [TypeStrong/typedoc#1231]
I want to generate JSON programmatically for a JS library that has typings, how would I go about doing that? When I try using the example code I just get
```js
{ id: 0, name: '', kind: 0, flags: {} }
```

**Comment by Gerrit0** [comment]
You need to pass --includeDeclarations, and will also probably want --excludeExternals

**Comment by LJNeon** [comment]
```js
app.bootstrap({
  mode: "library",
  logger: "none",
  target: "ES6",
  module: "CommonJS",
  out: "../docs",
  includeDeclarations: true,
  excludeNotExported: true
});
``` I thought I was already doing as much.

**Comment by Gerrit0** [comment]
Yep, that should do it - though I note you are using library mode. Do you have the `@next` version installed?
Try enabling logging and see if any errors are reported.

**Comment by LJNeon** [comment]
I'm not using the `@next` version, library mode was listed as an option and seemed to be the most fitting. Changing mode to module has no effect on the result. When I enable logging it seems to all be success messages.

**Comment by LJNeon** [comment]
```
Using TypeScript 3.8.3 from C:\Users\..\node_modules\typescript\lib

JSON written to C:\Users\..\site\data.json
```
This is the full logged output with folder paths shortened for privacy reasons.

**Comment by LJNeon** [comment]
So update to this, apparently the file path I put in doesn't exist, and it simply gives an empty output instead of erroring when that's the case. Might wanna do something there to make this problem a lot less confusing.

**Comment by LJNeon** [comment]
As the actual problem is rather different from the title I'm gonna close this and reopen a new issue.

**Comment by Gerrit0** [comment]
> I'm not using the @next version, library mode was listed as an option

Clearly I shouldn't have included in the docs with the WIP note not overly highlighted. Library mode only exists in `@next` so far and should have caused an error (though since you disabled logging you wouldn't see it) when you tried to use it. I've modified the website so it shouldn't be possible for others to miss that it is a WIP still.
