### ISSUE TITLE
Document easier way to use generated JSON

### ISSUE THREAD

**Issue by LJNeon** [TypeStrong/typedoc#1243]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

When you want to immediately use JSON after generating it (e.g. for a custom documentation builder) you have to write to and then read from a temporary file.
## Suggested Solution

This could be avoided with some option to just return the JSON, which is far simpler and less wasteful.

**Comment by Gerrit0** [comment]
If you are using it programmatically, why use the JSON at all? The `convert` method returns a [`ProjectReflection`](https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/reflections/project.ts#L19) which provides all of the information that the JSON does, along with helper methods.

If you still want the JSON itself, you can ask the serializer for it yourself.

```ts
const project = app.convert(['src/'])
if (project) {
    const json = app.serializer.projectToObject(project)
}
```

**Comment by LJNeon** [comment]
I'd suggest adding some mention of the ability to do this to the guide on the doc website, I had no idea this was possible.

**Comment by Gerrit0** [comment]
I was going to go add this to the site - and found it was already there. http://typedoc.org/guides/installation/#node-module
