### ISSUE TITLE
Backtick strings

### ISSUE THREAD

**Issue by arcanis** [TypeStrong/typedoc#1245]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

The following code fence should be a correct syntax:

![image](https://user-images.githubusercontent.com/1037931/77295354-17745800-6ce6-11ea-9c06-ee76ebc3304d.png)

Compare with the [original one](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-shell/README.md):

![image](https://user-images.githubusercontent.com/1037931/77295401-2fe47280-6ce6-11ea-87a2-d26af3488509.png)

## Actual Behavior

TypeDoc seems to be removing the backticks (probably because the markdown is interpreted after the syntax highlighting?), which breaks the output.

## Steps to reproduce the bug

- Online at: https://yarnpkg.com/api/modules/yarnpkg_shell.html

- Project at: https://github.com/yarnpkg/berry (run `yarn build:doc` to generate the doc in packages/gatsby/static)

**Comment by Gerrit0** [comment]
I suspect this may be an issue with your theme. I was unable to reproduce it by adding the same comment to the readme in https://github.com/TypeStrong/typedoc/tree/master/examples/basic.
