### ISSUE TITLE
Support for multiple tsconfig.json

### ISSUE THREAD

**Issue by HexMox** [TypeStrong/typedoc#1246]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

Hi, great jobs! I would like to build multiple folders with multiple tsconfig.json into one doc.

Currently I merged two tsconfig.json to build, But it goes some type errors.

```js
// tsconfig.web.js
{
  "compilerOptions": {
    "lib": ["esnext", "DOM"],
    // node_modules/@types/node is for node
    // src/types/globals.d.ts for web
    "typeRoots": ["node_modules/@types", "src/types"]
  },
  // ...
}
```

```
// src/types/globals.d.ts
// declare process for webpack DefinePlugin
declare const process: any;
```

and then
```
Using TypeScript 3.7.5 from /Users/moxhe/workspace/projects/core/src/edu_modules/ke-common/node_modules/typescript/lib
Error: /Users/xxx/globals.d.ts(14)
 Cannot redeclare block-scoped variable 'process'.
```

## Suggested Solution

Poor English, feel free to correct.

**Comment by Gerrit0** [comment]
This would be really tricky to implement. I don't plan on tackling it anytime soon. Personally I think separate packages should get separate documentation anyways.

**Comment by Gerrit0** [comment]
This isn't exactly the same thing - but it meets the same need. In 0.20 you can set up a tsconfig which uses project references to reference your other two tsconfig files. TypeDoc will then create two programs. There is no way currently for type references to reach across programs, but they can be bundled in the same docs. See #1414.
