### ISSUE TITLE
How to document something not representable in the source code?

### ISSUE THREAD

**Issue by LJNeon** [TypeStrong/typedoc#1254]
I'm trying to build documentation for a JS library with typings, as this would reduce maintenance compared to having to update both the typings and JSDoc comments. 

I have an abstract class which reads any string input and attempts to parse it into a specific type. The library comes with optional default implementation classes for common types, and I want to document them. However, due to the structure of the library, these classes are never actually exposed to the user and not in the typings (you use them by providing what is effectively a string ID). Having to document them elsewhere would be highly inconvenient, but I'm not sure how to get TypeDoc to include them when I can't export.

**Comment by Gerrit0** [comment]
> these classes are never actually exposed to the user and not in the typings

Then as far as external users are concerned, they need not be documented.

> you use them by providing what is effectively a string ID

It sounds like wherever you provide this ID you should document what each string will do. Users don't need to know about the implementation behind each string, just the effect.

**Comment by LJNeon** [comment]
> Then as far as external users are concerned, they need not be documented.

Not quite true, default implementations of a class are very relevant to external users.

> It sounds like wherever you provide this ID you should document what each string will do.

So instead of documenting a long list of implementations for a class on the page for that class, I should document it again in every single place that it's used? This seems disorganized and poorly designed.

> Users don't need to know about the implementation behind each string, just the effect.

All I want to document is the string ID, along with a single type associated with that particular implementation. I'd consider all of the above necessary information and part of "the effect" as you put it.

**Comment by Gerrit0** [comment]
Perhaps I'm not understanding the system you are working with, here's what I was imagining.

```ts
export interface Parser<T> {
  readonly type: string
  parse(value: string): T
}

class DefaultNumberParser implements Parser<number> {
  readonly type = 'number'
  parse(value) {
    return parseInt(value, 10)
  }
}

export type GetParserFromType<T, K> = T['type'] extends K ? T : never

export type DefaultParsers =
  | DefaultNumberParser

export class ParserContainer<T extends Parser<any>> {
  constructor(private parsers: T[]) {
    this.parsers.push(new DefaultNumberParser())
  }

  parse<K extends string>(data: string, type: K): GetParserFromType<T | DefaultParsers, K> {
    return this.parsers.find(p => p.type === type)?.parse(data)
  }
}
```

With this system, you just need to note that providing `'number'` as the `type` argument for `parse` will try to parse the data as a base 10 int... As a user of your library I couldn't care less whether there is a `DefaultNumberParser` class or a check within `parse` for `type === 'number'` which directly returns `parseInt(data, 10)`.

**Comment by LJNeon** [comment]
There's a large list of default implementations, and not all are types like `'number'` where the type is immediately obvious from the name, in fact some are very ambiguous. I'd rather have a long list of IDs and types they parse in the base class page, instead of in all the multiple locations they're being used.

**Comment by Gerrit0** [comment]
Why not include that information in the docs for the base class? Wherever it is being used you can just include ``see {@link BaseClassName} for how `type` is interpreted`` to tell people to look in your one location.

**Comment by LJNeon** [comment]
I guess I never thought about putting it in the same doc comment, I think that would work though.
