### ISSUE TITLE
@link to field with link text does not render as hyperlink

### ISSUE THREAD

**Issue by pluma** [TypeStrong/typedoc#1256]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

The implementation seems to be incomplete.

The following works as expected:

`{@link http://example.com | Something neat}`

As does this:

`{@link AcmeFactory.doStuff}`

But this does not:

`{@link AcmeFactory.doStuff | Link text here}`

It doesn't seem to be recognised at all and is output as-is.

This syntax is used in the playground: https://microsoft.github.io/tsdoc/

**Comment by Gerrit0** [comment]
TypeDoc doesn't yet support TSDoc - it existed for years before TSDoc did and has its own (inferior) system for parsing comments.

That said, this should be a relatively easy fix. It looks like the intent to support this was there, we just do it badly.  PR welcome. https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/plugins/MarkedLinksPlugin.ts#L147

**Comment by Gerrit0** [comment]
Fixed in 0.17.7 - 935e10a469a54282ee79911f1a82eddccef7739a

**Comment by pluma** [comment]
Not sure where this belongs but I just noticed VSCode seems to think the `|` (pipe) is part of the link text rather than part of the link syntax.

**Comment by Gerrit0** [comment]
Yea... that's a VSCode issue. I'm not sure what it uses for parsing comments, but it isn't TypeDoc.
