### ISSUE TITLE
Option to expand type aliases

### ISSUE THREAD

**Issue by moltar** [TypeStrong/typedoc#1258]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

I'm using a library to create types that hsa runtime checking: [io-ts](https://github.com/gcanti/io-ts)

Types are declared like so:

```ts
import * as t from 'io-ts'

const User = t.type({
  userId: t.number,
  name: t.string
})

export type User = t.TypeOf<typeof User>
```
Then in the docs, it shows the type as:

```
User = t.TypeOf<typeof User>
```

Which isn't helpful to the reader.

## Suggested Solution

I propose to have a flag that expands all of the aliases into a full type / interface.

E.g.

It would expand the type into:

```ts
type User = {
  userId: number
  name: string
}
```

**Comment by Gerrit0** [comment]
See also #1021

**Comment by maneetgoyal** [comment]
Have a similar requirement. Will be great to have a flag or a plugin (as suggested in #1021).

---

1. The source file looks like this:
```ts
export const RESTFontWeight = {
  Bold: "bold",
  Bolder: "bolder",
  Lighter: "lighter",
  Normal: "normal"
} as const;
export type RESTFontWeight = typeof RESTFontWeight[keyof typeof RESTFontWeight];
```

2. Generated docs for the exported `type` looks like:

![Screen Shot 2020-04-05 at 4 46 38 PM](https://user-images.githubusercontent.com/25290212/78513080-fd169180-775d-11ea-9400-65a91189b4ed.png)

3. On the other had, TypeScript intelisense for the `type` looks quite user-friendly:

<img width="1139" alt="Screen Shot 2020-04-05 at 4 49 53 PM" src="https://user-images.githubusercontent.com/25290212/78513006-84afd080-775d-11ea-8a92-3395e24ed49a.png">

4. If TypeDoc also emits a similar format, it will be quite useful for users reading the docs.

**Comment by maneetgoyal** [comment]
Hi @Gerrit0, in a similar example also noticed a possible bug:

Source Code:
```ts
export const MyObject =
  {
    myValue: "ddddd"
  } as const;
export type MyType = typeof MyObject.myValue;
```

TS Intelisense:

<img width="715" alt="Screen Shot 2020-04-05 at 10 32 08 PM" src="https://user-images.githubusercontent.com/25290212/78525908-4fbb7200-778d-11ea-8742-7a3536446cdd.png">

TypeDoc behavior:

![Screen Shot 2020-04-05 at 10 32 57 PM](https://user-images.githubusercontent.com/25290212/78525966-7a0d2f80-778d-11ea-850a-5868bf252cc9.png)

Issue:
The object `MyObject` is not present in the type-alias.

**Comment by Gerrit0** [comment]
> The object MyObject is not present in the type-alias.

Sounds like contradictory requests here ;) "resolve the type" vs "preserve the source representation"

Since we do generate a link to `myValue`, that will take you within `MyObject`, I'm not too worried about this... feel free to submit a PR if it bugs you.

**Comment by maneetgoyal** [comment]
> Sounds like contradictory requests here ;) "resolve the type" vs "preserve the source representation"

Yeah they are contradictory :) pointed out because I thought "preserve the source representation" should be consistent throughout.

> Since we do generate a link to myValue, that will take you within MyObject

Yeah, that would be quite acceptable too but it's not happening. It took me to the URL: `xyz.path.html#myobject.__type.myvalue` which doesn't seem to exist. If it takes us to `xyz/path.html#myobject` that would be acceptable too.

**Comment by Gerrit0** [comment]
Good to know about the broken links, I guess I should have expected that... Its kind of amazing how many links do work given the piecemeal way we build them up today.

**Comment by VanTanev** [comment]
I'm very much looking to do the same thing. Any guidance on how to approach this, including guidance on how to write a plugin for this is welcome.

**Comment by Gerrit0** [comment]
Doing this is rather tricky. I think the right solution would be to create a plugin which listens to `Converter.EVENT_CREATE_DECLARATION`, checks if it is a type alias, and if it is and is marked for expansion (with `@expand` or similar), uses the node to get a symbol. You can use `context.getSymbolAtLocation(node)` and then once you have the TS symbol, there is a `getProperties()` method that should give you the necessary properties.

I'm afraid I can't be more helpful here, its been a while since I looked at how this might be doable.

**Comment by VanTanev** [comment]
@Gerrit0 Thanks for the suggestion. I tried going down a similar road, but it indeed does get amazingly complex very quickly. The fact that I haven't worked with TS's compiler, or any compiler of similar magnitude not helping.

Ultimately, I went down another road, and found a much simpler way to get what I needed: 

I wrote a small utility to extract static types from `io-ts` definitions, and then combined it with prettier. The resulting type definitions can either be written to new .ts files for TypeDoc to parse, or be output directly to Markdown (what I end up doing)
https://gist.github.com/VanTanev/8a6ea41257eba917241cb026e5f52240

cc @moltar

**Comment by Gerrit0** [comment]
Far from perfect, but this gets the job done if you don't care about extra information that TypeDoc keeps about type info when rendering docs (enabling links, syntax highlighting)

```js
//@ts-check

// Supports: typedoc@0.20

const { Converter, ReflectionKind, TypeScript: ts } = require("typedoc");
const { UnknownType } = require("typedoc/dist/lib/models");

/** @param {import("typedoc").Application} param0 */
exports.load = function ({ application }) {
  const printer = ts.createPrinter();

  /** @type {Map<import("typedoc").DeclarationReflection, UnknownType>} */
  const typeOverrides = new Map();

  application.converter.on(
    Converter.EVENT_CREATE_DECLARATION,
    /**
     *
     * @param {import("typedoc/dist/lib/converter/context").Context} context
     * @param {import("typedoc").DeclarationReflection} reflection
     * @param {import("typescript").Node | undefined} node
     */
    (context, reflection, node) => {
      if (reflection.kind === ReflectionKind.TypeAlias && node) {
        if (reflection.comment && reflection.comment.hasTag("quickinfo")) {
          reflection.comment.removeTags("quickinfo");

          const type = context.checker.getTypeAtLocation(node);
          const typeNode = context.checker.typeToTypeNode(
            type,
            node.getSourceFile(),
            ts.NodeBuilderFlags.InTypeAlias
          );

          typeOverrides.set(
            reflection,
            new UnknownType(
              printer.printNode(
                ts.EmitHint.Unspecified,
                typeNode,
                node.getSourceFile()
              )
            )
          );
        }
      }
    }
  );

  application.converter.on(Converter.EVENT_RESOLVE_BEGIN, () => {
    for (const [refl, type] of typeOverrides) {
      refl.type = type;
    }
    typeOverrides.clear();
  });
};
```

Then, with this source:

```ts
export interface A {
	x: string
}

/** @quickInfo */
export type Mapped = {
	[K in keyof A & string as `${K}.${K}`]: A[K]
}
```

TypeDoc will produce:

![image](https://user-images.githubusercontent.com/19329837/103257151-4c849980-494d-11eb-83c2-295ce3e04ce3.png)

Replacing the call to create a new `UnknownType` with `context.converter.convertType(context, typeNode)` might work in some cases - but that code assumes it gets a real type node, and the one created with `typeToTypeNode` isn't one... so I wouldn't be surprised if it crashes in other cases.

**Comment by benjie** [comment]
@Gerrit0 Please could you supply a license for the above plugin? Thanks :pray:

**Comment by imtuanpham** [comment]
> 

@Gerrit0 the above plugin no longer works with TypeDoc 0.23.25. I looked into the source and `Converter.EVENT_CREATE_DECLARATION` listener now takes only `Context` and `DeclarationReflection` -- without the third param, `node`. Would you give me some pointers on how to fix this?

**Comment by Gerrit0** [comment]
For node, you'll need to get that from the symbol yourself now - `context.project.getSymbolFromReflection(refl)?.declarations?.[0]`

**Comment by imtuanpham** [comment]
Thanks @Gerrit0 for the pointer!

Below is the updated code that works with `typedoc` 0.23.25:

```
//@ts-check

// Supports: typedoc@0.23

const {
  Converter,
  ReflectionKind,
  TypeScript: ts,
  UnknownType,
} = require('typedoc');

/** @param {import("typedoc").Application} param0 */
exports.load = function ({ application }) {
  const printer = ts.createPrinter();

  /** @type {Map<import("typedoc").DeclarationReflection, UnknownType>} */
  const typeOverrides = new Map();

  application.converter.on(
    Converter.EVENT_CREATE_DECLARATION,
    /**
     *
     * @param {import("typedoc/dist/lib/converter/context").Context} context
     * @param {import("typedoc").DeclarationReflection} reflection
     */
    (context, reflection) => {
      const node =
        context.project.getSymbolFromReflection(reflection)?.declarations?.[0];

      if (reflection.kind === ReflectionKind.TypeAlias && node) {
        if (reflection.comment?.getTag('@quickinfo')) {
          reflection.comment.removeTags('@quickinfo');

          const type = context.checker.getTypeAtLocation(node);
          const typeNode = context.checker.typeToTypeNode(
            type,
            node.getSourceFile(),
            ts.NodeBuilderFlags.InTypeAlias,
          );

          typeOverrides.set(
            reflection,
            new UnknownType(
              printer.printNode(
                ts.EmitHint.Unspecified,
                typeNode,
                node.getSourceFile(),
              ),
            ),
          );
        }
      }
    },
  );

  application.converter.on(Converter.EVENT_RESOLVE_BEGIN, () => {
    for (const [refl, type] of typeOverrides) {
      refl.type = type;
    }
    typeOverrides.clear();
  });
};

```
