### ISSUE TITLE
Update website plugin list

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1259]
https://typedoc.org/guides/plugins/ lists a few TypeDoc plugins. There doesn't seem to be much rhyme or reason for how these were chosen, and some of them appear abandoned and don't work on the latest version of TypeDoc.

- [ ] Create GitHub action to automatically generate plugin list
- [ ] Make `--plugin` link to https://typedoc.org/guides/options/#plugin

**Comment by Gerrit0** [comment]
A couple of plugins to add that were mentioned in Gitter:
- UML class generation by @krisztianb - https://github.com/krisztianb/typedoc-umlclass
- Specify a favicon + include generation time in the footer by @Drarig29 - https://www.npmjs.com/package/typedoc-plugin-extras

**Comment by krisztianb** [comment]
I'd like to propose another useful plugin for the list: https://github.com/artifacthealth/typedoc-plantuml

**Comment by Gerrit0** [comment]
This one too https://github.com/mipatterson/typedoc-plugin-pages

**Comment by Gerrit0** [comment]
The plantuml plugin above has been abandoned, I think I'll just list https://github.com/krisztianb/typedoc-umlclass since it's still maintained.

**Comment by Gerrit0** [comment]
Reworked this a bit - it should be possible to use GitHub actions to query npm for a plugin list, then the site can just display plugins  with a release in the last 3? 6? months
