### ISSUE TITLE
Constructor property parameters are not documented when --excludeNotDocumented is on

### ISSUE THREAD

**Issue by judax** [TypeStrong/typedoc#1261]
## Search Terms
constructor parameter property documentation

## Problem
When using `--excludeNotDocumented`,  a class that declares properties in the constructor the properties do not seem to be documented correctly even with `@param`.

```
class X {
  /**
   * Instantiates X.
   * @param prop The property of X.
   */
  constructor(readonly prop: number) {
  }
}
```

**Comment by judax** [comment]
This is not a suggestion, but a bug. Sorry for the wrong labelling.

**Comment by Gerrit0** [comment]
@SamuraiJack you might be interested in this

**Comment by SamuraiJack** [comment]
Thanks for the report, I'll check soon

**Comment by SamuraiJack** [comment]
Can not reproduce this one. I'm testing with this class definition:

```ts
/**
 * Has docs
 */
export class BaseClass {
    /**
     * Has docs
     */
    some        : number
    // no docs
    protected kind: number;

    /**
     * Has docs
     */
    static instance: BaseClass;

    // no docs
    static instances: BaseClass[];

    /**
     * Has docs
     * @param name
     */
    constructor(readonly name: string){
    }
}
```
And the result is:
![image](https://user-images.githubusercontent.com/72431/79888021-825ba080-8404-11ea-8aa8-f52ba1225d94.png)

The constructor seems to be properly documented. 

Command line: 
```
node ../../bin/typedoc --includes inc/ --media media/ --target ES5 --json json.json --out doc/ src/ --excludeNotDocumented
```

@judax Any additional info?

**Comment by SamuraiJack** [comment]
@judax Perhaps you did not include the docs for the class itself? Then the whole class won't be included.

**Comment by judax** [comment]
It still does not work for me. Here is the code I am trying to document:

```
/** Represents a 2 float structure (i.e. a point in 2D). */
export class Float2 {
  /**
   * Constructs a 2 float structure instance.
   *
   * @param x The x component of the 2 float structure.
   * @param y The y component of the 2 float structure.
   */
  constructor(readonly x: number, readonly y: number) {}
}
```
Here are my command line options:

`typedoc --excludeNotDocumented --ignoreCompilerErrors --excludePrivate --excludeProtected --readme none --mode file --theme MY_DEFAULT_THEME_PATH`

**Comment by judax** [comment]
Ok, after some testing I found the issue: The class needs to have more members (or something else at least) to be able to document the properties correctly.

**Comment by SamuraiJack** [comment]
Ok, thanks for the info!

**Comment by mdornseif** [comment]
Seems to me related to #584. 

It also seems to me that there is no way to add Documentation to the auto-generated **Properties** (only the Parameters):

```
/** KvStore implements ...
*/
export class KvStore implements IKvStore {
  /** Generate a KvStore instance for a specific [[Datastore]] instance.
...
  @param datastore A [[Datastore]] instance. Can be freely accessed by the client. Be aware that using this inside [[runInTransaction]] ignores the transaction.
  @param projectId The `GCLOUD_PROJECT ID`. Used for Key generation during serialization.
  */
  constructor(readonly datastore: Datastore, readonly projectId?: string) {
    assertIsObject(datastore)
  }
  ```
![Generated Doc](http://f.foxel.org/Screen-Shot-2021-12-14-12-45-23.png)

**Comment by thopaw** [comment]
Is there an update on this issue?
I am struggling with this right now and I wonder if it is possible to have the docs on a constructor property in the generated HTML.


```
class A {
  constructor(
    /**
     * I want to see this comment in the documentation
     * /
     readonly property: string) {}
}

```
