### ISSUE TITLE
typedoc.json inputFiles property not working as expected

### ISSUE THREAD

**Issue by pchuong** [TypeStrong/typedoc#1263]
## Search terms
typedoc.json inputFiles

## Expected Behavior
When I specified the inputFiles option in the typedoc.json file to have an array (or single) of directories such as ["./src/foo/lib", "./src/bar/lib"]. It pickup all the files in the ./src file. I expect it to only search for files in the two lib folders.

## Actual Behavior

All files in the ./src folder are parsed and the generated doc contains files in other folder.

## Steps to reproduce the bug

typedoc.json
    {
        "mode": "modules",
        "out": "./docs",
        "inputFiles": ["./src/foo/lib", "./src/bar/lib"]
    }

Case #1: doesn't work
typedoc --options typedoc.json --tsconfig tsconfig.json

Case #2: work (with or without the inputFiles property in the typedoc.json file)
typedoc --options typedoc.json --tsconfig tsconfigjson "./src/foo/lib" "./src/bar/lib"

## Environment
- Typedoc version: 0.17.4
- TypeScript version: 3.8.3
- Node.js version: 12.16.1
- OS: Windows10

**Comment by Gerrit0** [comment]
Ah, good catch. Should be a really simple fix. The tsconfig reader should check if inputFiles is default before setting it.

**Comment by Gerrit0** [comment]
There's a fix for this in #1265, but it bumps the required Node version from 8.0 to 9.0 so can't be merged until 0.18 is ready (#1241).
