### ISSUE TITLE
TypeCode is not working with npx

### ISSUE THREAD

**Issue by paterninaisf** [TypeStrong/typedoc#1264]
Hi typecode team, amazing job you are doing with the library!

I tried `npx typecode --exclude **/node_modules/**  `  and `npx typecode --version` and i´m getting the following error

Look like is not in the npm register.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/typecode - Not found
npm ERR! 404
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I did that a couple of weeks ego and worked perfectly and right now not work. Any sugestion?

When I go to `https://registry.npmjs.org/typecode` throught the browser I getting `{"error":"Not found"}`

**Comment by Gerrit0** [comment]
This library is called `typedoc`, not `typecode`
