### ISSUE TITLE
Investigate browser tests for the theme

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1267]
Right now, the default theme is "tested" by just rendering everything in the examples/basic folder to HTML and diffing the changes.

This is... less than ideal. I know tools exist which can fire up a browser and interact with it. It would be nice to be able to use one of these to test the rendered code instead of storing a ridiculous amount of HTML in the repository.

Ideally it should test:

- [ ] A few complex types are displayed correctly
- [ ] Search works
- [ ] Visibility toggles (public/private/protected) work
- [ ] Overload toggles work (#1262)

**Comment by SamuraiJack** [comment]
I can start such test suite, using `siesta` - the testing tool we develop: https://www.bryntum.com/products/siesta/

Should be quite simple. However, the tool is currently proprietary, even though it is free. https://www.npmjs.com/package/siesta-lite

Please let me know what you think.

**Comment by Gerrit0** [comment]
That package looks really neat! However, there is one problem with it that I don't think I can accept.

> 2.3.1 No Compete. Licensee shall not use any part of the Software or Licensee’s knowledge of the
Software (or any information that Licensee learns as a result of Licensee’s use of the Software) to create a product categorized as a software development tool or software debugging tool. This includes any product or application with the same or substantially the same functionality as the Software including but not limited to unit testing tools, functional testing tools, logging tools, debugging tools and similar frameworks.

No compete is bad. I doubt I'll ever build my own tool like this, but I'm not willing to agree to a clause that says I won't just because I might have come up with some ideas because of exposure to this package, and I'm certainly not going to force anyone who wants to contribute to TypeDoc to also agree to this license.

I'd rather go with a package that has an open source license.

**Comment by SamuraiJack** [comment]
Understand. The next major release is going to be open source, however it will take a while till that.

**Comment by epinxteren** [comment]
You can take a look at https://www.cypress.io/ MIT licence

**Comment by Gerrit0** [comment]
We have this now (beta branch for now), it's not automatic, but it's still useful enough that I'm going to call this complete
