### ISSUE TITLE
Generated legend is missing items

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1270]
> I have the same problem. Enum and other types are missing. I am using mode "file".
\@johansten : have you found a solution to the problem?

_Originally posted by @mcmartincerny in https://github.com/TypeStrong/typedoc/issues/1136#issuecomment-614771721_

---

Pulling into a new issue to track.

**Comment by kaiyoma** [comment]
I'm seeing this issue regardless of mode. The legend is always empty.

**Comment by Gerrit0** [comment]
This can be reproduced still in 0.20 with a single exported function

```ts
export function foo(){}
```

The legend should have a function item, but is instead rendered empty.

**Comment by mnn** [comment]
I have updated from 0.17.7 to 0.20.20 and now I am missing half of classes. :disappointed: Not just in legend, links are broken and html files are gone.

[**before**](https://glcdn.githack.com/monnef/ts-opt/-/raw/v2.1.0/doc/modules/_opt_.html) vs [**after**](https://gl.githack.com/monnef/ts-opt/-/raw/5568600c27f8f15774d2ea91cb4b8f217464faad/doc/modules.html) (notice missing `Some` and `None`)

**Comment by Gerrit0** [comment]
That looks like expected behavior to me. TypeDoc 0.20 only documents your exports, and neither Some nor None are documented. If you really want to include those - take a look at #1484.

**Comment by mnn** [comment]
Regarding #1484, I don't use `--excludeExternals` nor have "Externals" unchecked. I have no intention of exporting those classes (it is supposed to be that way - a user should not be creating them directly). Those classes are in a same project, even same file, not a different package (library). I don't understand how that linked issue helps me.

I hope I don't have to downgrade (and possibly fork to fix TS version dependency) to continue using typedoc?

**Comment by Gerrit0** [comment]
Sorry about that! I typoed the issue number. I meant to link to https://github.com/TypeStrong/typedoc/issues/1474

**Comment by mnn** [comment]
@Gerrit0 Thank you, that plugin fixed the issue :slightly_smiling_face:.
