### ISSUE TITLE
How to hide references, generated by re-exports

### ISSUE THREAD

**Issue by samchon** [TypeStrong/typedoc#1271]
![image](https://user-images.githubusercontent.com/13158709/79690039-5967ce00-8293-11ea-8665-7fbe92b5959f.png)

As I'm using the `typedoc-plugin-external-module-name`, I don't need the "references" features, who are generated by re-exports. However, I can't find any option to exclude or hide the section. If there's an option for that, can you teach me how to use it? Otherwise, I want to request that feature.

**Comment by Gerrit0** [comment]
There is no way to exclude these currently, though you could write a plugin to do this fairly easily.

I don't really want to include a toggle for this, I expect with the upcoming library mode that these will drop to very few in each project and those that remain will be important.

Simple plugin to remove references (untested)

```ts
import { Application, Converter } from 'typedoc'
export function load({ application }: { application: Application }) {
  application.converter.on(Converter.EVENT_RESOLVE_BEGIN, context => {
    for (const reflection of context.project.getReflectionsByKind(ReflectionKind.Reference)) {
      context.project.removeReflection(reflection)
    }
  })
}
```

**Comment by samchon** [comment]
@Gerrit0 Thanks for reply. Your example code is working well.

**Comment by eyworldwide** [comment]
The code above is not working in typedoc@0.19.2.  I've written a package to fix it: https://www.npmjs.com/package/typedoc-plugin-remove-references
