### ISSUE TITLE
__namedParameters comments missing when excludeNotExported is set

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1274]
Opening a new issue to track:

---

I believe I'm seeing this bug again in 0.17.4, with the following JavaScript:
```
/**
 * FOO
 * @param {Object} __namedParameters various options
 * @param {Number} foo An interesting value
 * @param {Number} __namedParameters.bar Another value
 */
function demo({ foo=42, bar=43 } = {}) { }
module.exports = {demo};
```
[Here is a repository demonstrating the problem](https://github.com/phihag/typedoc-named-demo).

_Originally posted by @phihag in https://github.com/TypeStrong/typedoc/issues/1000#issuecomment-616232668_

**Comment by boredstiff** [comment]
I'm running into this issue as well, and I've jumped back through typedoc versions all the way back to the version that was called out in the parent ticket, v0.16 - same result in all of them. I'm attempting to comment the parameters on a React functional component, but while I can get the docstring to show up for the component itself, nothing shows up for the parameters.

```javascript
/**
 * My description that shows up
 * @param assetTypes  Hellooooooo
 * @param data
 * @param loading
 * @param error
 * @param disabled
 * @constructor
 */
const AssetSelector: React.FC<Props> = ({
  assetTypes,
```

The description does show up: 
![image](https://user-images.githubusercontent.com/3489076/80751632-0554b900-8adf-11ea-890f-d92473de3900.png)

But the parameter is completely empty:
![image](https://user-images.githubusercontent.com/3489076/80751681-1ac9e300-8adf-11ea-9a4a-b603f2bdfa4a.png)

**Comment by Gerrit0** [comment]
Version 0.20 (currently `typedoc@beta`) resolves this by... no longer supporting excludeNotExported (we only document exported members now). The following code:

```ts
/**
 * FOO
 * @param __namedParameters various options
 * @param foo An interesting value
 * @param __namedParameters.bar Another value
 */
export function demo({ foo=42, bar=43 }: { foo?: number, bar?: number } = {}) { }
```

Converts to:
![image](https://user-images.githubusercontent.com/19329837/100492110-937d3600-30e6-11eb-9cdb-ebca97c4d019.png)
