### ISSUE TITLE
Add an option to ignore element marked @internal

### ISSUE THREAD

**Issue by baanloh** [TypeStrong/typedoc#1283]
## Search Terms
tag internal ignore

## Problem
It will be usefull to add an option to automatically ignore every elements marked with `@internal`. For exemple, a internal method not need to be documented into a public doc, but must be documented into a internal doc (for collaborators).

## Suggested Solution
Add a option to typedoc.json:
```json
{
    "ignoreInternal": true
}
```
if set to true, consider `@internal` as `@ignore`

**Comment by Gerrit0** [comment]
You can already do this, if you pass TypeScript's `--stripInternal` option.
https://typedoc.org/guides/doccomments/#internal

**Comment by baanloh** [comment]
Thanks 👍 
But this option is not document here : https://typedoc.org/guides/options/

**Comment by Gerrit0** [comment]
Looks like it was missed since the option is pulled in from TypeScript's option declarations. I'll update momentarily :)
