### ISSUE TITLE
@param with the same name as function rendering as function comment

### ISSUE THREAD

**Issue by sfncook** [TypeStrong/typedoc#1286]
## Search terms
param rendering above

## Expected Behavior
Explanation of the parameter should be rendered below the bulleted parameter name.

## Actual Behavior
Most parameters are rendered correctly, but it seems like the first parameter has its description rendered above the bulleted parameter name.
![Screen Shot 2020-04-27 at 9 46 47 AM](https://user-images.githubusercontent.com/4008769/80398453-7e000f00-886c-11ea-8504-5db03b16ef97.png)
![Screen Shot 2020-04-27 at 9 47 12 AM](https://user-images.githubusercontent.com/4008769/80398458-7f313c00-886c-11ea-8200-dbe79142c5e1.png)

## Environment
- Typedoc version: v0.17.6
- TypeScript version: v3.8.3
- Node.js version: v13.7.0
- OS: Mac OSX v10.15.3

**Comment by sfncook** [comment]
Whoops, it's because the first parameter shares the same name as the function.  :)

**Comment by Gerrit0** [comment]
I'm going to reopen this - This is bad behavior even with your workaround :)

**Comment by Gerrit0** [comment]
This is fixed in 0.20

![image](https://user-images.githubusercontent.com/19329837/103253097-fe679a00-493c-11eb-8d9d-0e0f9246a61c.png)
