### ISSUE TITLE
“ENOENT: no such file or directory, open '…/docs/assets/css/main.css'”

### ISSUE THREAD

**Issue by Rouvo** [TypeStrong/typedoc#1287]
Hello there,

I am trying to use typedoc in order to automatically generate the documentation of a angular application.

Whenever I am running `npx typedoc --out docs app --exclude "**/*.{spec.ts}" --exclude node_modules --ignoreCompilerErrors` it's generating markdown files and the rendering finishes, but then it aborts with the error stated above, saying that `.../docs/assets/css/main.css` does not exist.

From my understanding, this main.css is part of the typedoc stack and should be moved to the assets folder upon running this command.

Am I misunderstanding this? What is the reason for the failure and how can I fix this?

Since it does not seem to be a bug, just wrong usage, I sticked to "other issue".

// edit:
I have played a little bit with it and the problem only seems to appear with the "default" theme:
```
$ typedoc --out docs app --theme default
Loaded plugin /home/name/work/stuff/src/main/webapp/node_modules/typedoc-plantuml
Loaded plugin /home/name/work/stuff/src/main/webapp/node_modules/typedoc-plugin-markdown

Using TypeScript 3.8.3 from /usr/local/lib/node_modules/typescript/lib
Rendering [========================================] 100%
fs.js:130
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/name/work/stuff/src/main/webapp/src/docs/assets/css/main.css'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:353:35)
    at Renderer.<anonymous> (/home/name/work/stuff/src/main/webapp/node_modules/typedoc-plantuml/lib/plugin.js:117:23)
    at triggerEvents (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:128:43)
    at triggerApi (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:110:13)
    at eventsApi (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:21:18)
    at Renderer.trigger (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:264:13)
    at Renderer.render (/usr/local/lib/node_modules/typedoc/dist/lib/output/renderer.js:39:18)
    at CliApplication.generateDocs (/usr/local/lib/node_modules/typedoc/dist/lib/application.js:100:23)
    at CliApplication.bootstrap (/usr/local/lib/node_modules/typedoc/dist/lib/cli.js:48:26) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/name/work/stuff/src/main/webapp/src/docs/assets/css/main.css'
}
```

`typedoc --out docs app --theme minimal` runs without problems.

Best regards

**Comment by Gerrit0** [comment]
This is an issue with typedoc-plantuml. That plugin assumes that the generated docs includes an `assets/images` directory, but it doesn't since typedoc-plugin-markdown doesn't create one.

It looks like that plugin has been abandoned, I know @krisztianb forked it recently, the bug might be fixed there.

**Comment by krisztianb** [comment]
No, its not fixed there either. Don't use my fork as I also abandoned it recently.

@Gerrit0 why do you think it has something to do with the images directory?

I know that the plugin is attaching some CSS to the `main.css` file. So the problem seems to be that the plugin assumes that there is such a CSS file while there isn't.

**Comment by Gerrit0** [comment]
> @Gerrit0 why do you think it has something to do with the images directory?

I was looking at the source when I replied rather than the original issue, it appeared to also add items to the images directory, assuming that it exists. Looks like you're right and this specific issue is related to the CSS file.
