### ISSUE TITLE
Specify source URL for non-GitHub projects

### ISSUE THREAD

**Issue by giladgray** [TypeStrong/typedoc#129]
Per #34, is it possible to specify the URL for non-GitHub projects? Looking to use this for internal code at our company which is not hosted on GitHub. Perhaps a `sourceUrl` option in the main options blob?

**Comment by sebastian-lenz** [comment]
Hi Gilad, sorry, this is a misunderstanding. TypeDoc only supports GitHub urls.

**Comment by ntrp** [comment]
It would be better to specify a url template so it would be possible to generate urls for a broader number of services.

**Comment by CalvinFernandez** [comment]
+1 would also like this

**Comment by gdelmas** [comment]
i had the same issue and created this plugin: https://github.com/gdelmas/typedoc-plugin-sourcefile-url

**Comment by Gerrit0** [comment]
Closing as this behavior can now be achieved through the [typedoc-plugin-sourcefile-url](https://www.npmjs.com/package/typedoc-plugin-sourcefile-url) plugin thanks to Gerard.

**Comment by iFwu** [comment]
The plugin seems to not work

**Comment by aciccarello** [comment]
@iFwu That is an issue tracked in gdelmas/typedoc-plugin-sourcefile-url#5
