### ISSUE TITLE
baseUrl does not affect module names

### ISSUE THREAD

**Issue by TheBrokenRail** [TypeStrong/typedoc#1294]
## Search terms
baseUrl, module, name, directory

## Folder Structure
```
src/
    a/
        a.ts
        b.ts
        c.ts
```

```baseUrl``` = ```src```

## Actual Behavior
Modules are displayed as:
```
a
b
c
```

## Expected Behavior
Using ```baseUrl```:
```
a/a
a/b
a/c
```

## Steps to reproduce the bug
Create similar file structure with ```baseUrl``` and run TypeDoc.

## Environment
- Typedoc version: Latest
- TypeScript version: Builtin To TypeDoc
- Node.js version: 10.19.0
- OS: Ubuntu 20.04

**Comment by Gerrit0** [comment]
> TypeScript version: Builtin To TypeDoc

This does not exist. TypeScript is a peer dependency and is no longer built in in the latest version.

I'm marking this as an enhancement as TypeDoc's current behavior is intended, but I think using `baseUrl` to determine names makes sense.
