### ISSUE TITLE
Symbol references are wrongly transformed to lowercase

### ISSUE THREAD

**Issue by ppoulard** [TypeStrong/typedoc#1295]
If you create 2 symbols e.g. `Whatever` and `WHATEVER` that you refer in the doc with  `[[Whatever]]` and `[[WHATEVER]]` they both lead to the same HTML anchor `#whatever` in lower case, which is wrong.

## Environment
- Typedoc version: 0.15.8
- TypeScript version: 3.8.3

**Comment by aztack** [comment]
Anchors in the TOC should preserve the cases of headings.

![image](https://user-images.githubusercontent.com/782871/83346105-3d545380-a34c-11ea-8fcc-cdc2ac6b477b.png)

[typedoc-markdown-theme/src/theme.ts](https://github.com/kimamula/typedoc-markdown-theme/blob/master/src/theme.ts) seems didn't transform symbols into lowercase.

**Comment by Gerrit0** [comment]
Closing in favor of #1585, which has a proposed solution
