### ISSUE TITLE
How do you make @link link to the type you want?

### ISSUE THREAD

**Issue by StoneT2000** [TypeStrong/typedoc#1297]
I have a file with an exported alias called `Tournament` and an exported class called `Tournament` in another file.

In another file I then do `... see {@link Tournament}` but it takes me to the alias called Tournament and not the class i wanted it to link to. Is there a way to resolve this and force the link to link to the right thing/

**Comment by Gerrit0** [comment]
I just created https://typedoc.org/guides/doccomments/ to document TypeDoc's link resolution process.

You can probably fix the link by using `"file-name-with-quotes".Tournament` as your link target.

If you are using `--mode file`, there is currently no way to disambiguate the links. Once we adopt TSDoc, you will be able to use `:type` to specify the type alias. See #1266, there's quite a bit of work to do before we get there unfortunately.
