### ISSUE TITLE
TypeDoc skipping generating markdown from class methods

### ISSUE THREAD

**Issue by michaelaflores** [TypeStrong/typedoc#1298]
## Search terms

missing docs, comments, skipped

## Expected Behavior

When adding a new method to a class, and a comment, the markdown generated for the class documentation should include the new method.

## Actual Behavior

TypeDoc skips this new declaration.

## Steps to reproduce the bug

Class method that documentation generation works correctly on, with the comment appearing in `output.json`:
```js
export default class MediaStreamState extends MobxEmitter<MediaStreamStateEventsMap> implements Disposable {
  /**
   * Dispose mediaStreamState.
   * @description Dispose mediaStream, close AudioContext, and terminate any autorunners.
   * @example <caption>Example usage of dispose.</caption>
   * mediaStreamState.dispose();
   * // Terminates mediaStream, close AudioContext, and terminate any autorunners.
   */
  @bind
  dispose(): void {
...
```

When I add this method, no new documentation is generated in `output.json`:
```js
  /**
export default class MediaStreamState extends MobxEmitter<MediaStreamStateEventsMap> implements Disposable {
   * here is a new test
   */
  private analyzerData: Uint8Array = new Uint8Array();
```

TSconfig.json:
```json
{
  "compilerOptions": {
    "assumeChangesOnlyAffectDirectDependencies": true,
    "importHelpers": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "CommonJS",
    "pretty": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "lib": [
      "dom",
      "dom.iterable",
      "es2015",
      "es2016",
      "es2017"
    ],
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowJs": true,
    "strict": true,
    "outDir": "build",
    "downlevelIteration": true,
    "plugins": [
      {
        "transform": "typescript-is/lib/transform-inline/transformer",
        "shortCircuit": false,
        "ignoreClasses": true,
        "ignoreMethods": true,
        "ignoreFunctions": true,
        "disallowSuperfluousObjectProperties": false
      }
    ],
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "isolatedModules": true
  },
  "typedocOptions": {
    "mode": "modules",
    "out": "docs",
    "inputFiles": ["./src/store/encoder/use-cases/mock-media-stream-state.ts"],
    "json": "styleguide-utils/typedoc/json/output-private.json",
    "ignoreCompilerErrors": "true",
    "theme": "minimal",
    "excludePrivate": false
  },
  "include": [
    "./typings/*.d.ts",
    "./src/**/*.tsx",
    "./src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "build"
  ]
}
```
## Environment
- Typedoc version: "^0.16.10"
- TypeScript version:"3.8.3"
- Node.js version: v12.16.1
- OS: macOS 10.15.4

**Comment by Gerrit0** [comment]
I can't seem to reproduce this. Here's what I tried:

1. `yarn init -y; yarn add tslib typescript@3.8.3 typedoc`
1. Copied `tsconfig.json` from OP
1. Copied the first code block into `.\src\store\encoder\use-cases\mock-media-stream-state.ts`
1. Ran `yarn typedoc`, this generated a file
1. Noticed that the provided code shouldn't compile, `const video` isn't valid in a class.
1. Turned off `ignoreCompilerErrors`, fixed compiler errors
1. Added the private property, ran `yarn typedoc`
1. Observed the new property was present in the JSON output.

```ts
interface Disposable {
}

class MobxEmitter<T> {
        videoState: null | string = null
        videoDevice?: any
}

interface MediaTrackConstraints {}
interface MediaStreamStateEventsMap {}

export default class MediaStreamState extends MobxEmitter<MediaStreamStateEventsMap> implements Disposable {
    #screenCapture: any

    /**
     * If videoDevices is null or is screenCapture is being used, set video to `false`.
     * Otherwise, begin building video constraints.
     */
    video: Partial<MediaTrackConstraints> | boolean =
            (this.videoDevice === null || this.videoDevice === this.#screenCapture) ? false : true

    /*
     * here is a new test
    */
        private analyzerData: Uint8Array = new Uint8Array();
}
```

---

`ignoreCompilerErrors` should *only* be used to make TypeDoc build faster, after you have confirmed that it can properly read your configuration and run without errors. The TypeScript compiler API can break if there are errors. I need to update the docs with a much more strongly worded warning against using this option.

**Comment by michaelaflores** [comment]
@Gerrit0 I posted a bad snippet, that was inside of the method that I intended to show here. That said, I will rerun without `ignoreCompilerErrors` set to `false` to see what additional info this provides. Thank you!

**Comment by michaelaflores** [comment]
@Gerrit0 I tried this with Tslib@^2.0.0, and was no longer able to reproduce the issue.
