### ISSUE TITLE
npx typedoc fails when TypeScript is not installed

### ISSUE THREAD

**Issue by ozum** [TypeStrong/typedoc#1299]
Hi,

`$ npx typedoc --version` throws `Cannot find module 'typescript'`.

whereas

`$ npx typedoc@0.16 --version` works. Probably because `typescript` moved to `peerDependencies`.

Best,

**Comment by ozum** [comment]
Possible solution may be https://github.com/chrisguttandin/angular-prerender/blob/master/src/functions/load-peer-dependencies.ts

**Comment by Gerrit0** [comment]
Do you have TS in your dev dependencies? I can't seem to reproduce this. I set up a package with only TypeScript in my dev dependencies, installed, then used `npx typedoc`. It worked correctly.

**Comment by ozum** [comment]
@Gerrit0, if TypeScript is in dev dependencies and project is installed via `npm install`, it works. However those conditions are not always met.

**Comment by Gerrit0** [comment]
> However those conditions are not always met.

Yes, if you don't install dependencies you can't use tools that depend on them... requiring that TypeDoc's dependencies are installed in order to use the tool seems reasonable to me.

**Comment by ozum** [comment]
I prefer commands do not depend anything in host environment, but it's a design decision, and I respect your thought. Nonetheless, with npm@7, peer deps will be installed by default. Thanks, I'm closing this issue.

**Comment by Gerrit0** [comment]
If npm handles this for us - I'm more than happy to take advantage of it, from the blog post it sounds like we shouldn't have to do anything to support this once npm@7 lands.

The switch to a peer dependency was made because of the arguments laid out in #1257
