### ISSUE TITLE
Support tsconfig.json

### ISSUE THREAD

**Issue by bryanforbes** [TypeStrong/typedoc#130]
Since projects can specify their compiler options and included files via `tsconfig.json`, it would be great if typedoc would support specifying generating documentation by passing it a `tsconfig.json`. I could see the following as the command-line invocation:

```
$ typedoc --mode modules --exclude **/tests/** --excludeNotExported --out docs tsconfig.json
```

In my mind, this would get the list of project files from `tsconfig.json`'s `files` property, apply the exclude pattern to those files, get the compiler options from the `compilerOptions` property, and then generate the docs.

**Comment by sebastian-lenz** [comment]
Hi Bryan, thank you for sharing this. I think this is a good idea, maybe we could even append the documentation parameters to <code>tsconfig.json</code> so they can be easily shared with others.

**Comment by robertbaker** [comment]
+1

**Comment by hourliert** [comment]
:+1:

**Comment by stepancar** [comment]
+1

**Comment by dabbank** [comment]
+1

**Comment by eggers** [comment]
:+1:

**Comment by joemcelroy** [comment]
:+1:

**Comment by listepo** [comment]
+1

**Comment by xstof** [comment]
+1

**Comment by meriturva** [comment]
+1

**Comment by dsebastien** [comment]
+1

**Comment by jpf200124** [comment]
+1

**Comment by readme42** [comment]
+1

**Comment by tforgione** [comment]
+1

Any news on this ?

**Comment by DanielJoyce** [comment]
Yeah, typedoc is pretty much worthless for me without this. Also ships with moldy old typescript version ( 1.6 ) and can't find how to get it to use different version.

**Comment by cfischer** [comment]
+1

**Comment by lholznagel** [comment]
Guys, please!
When you are intressted in this topic, please click on `Subscribe`.
If you want to to say that this is a nice feature just click on the smiley and press your reaction. Github added that for a reason. One of the reason is that the +1 is annoying for all that subscribed or watch a issue/repo.

Thanks!

**Comment by DaSchTour** [comment]
But reactions don't make me a participant and when watching a repo I want to me notified in a different way for certain topics.

**Comment by tht13** [comment]
Then click the subscribe button in the column on the right

**Comment by DaSchTour** [comment]
There is only an Unsubscribe Button.

**Comment by tforgione** [comment]
It's an `unsubscribe` button only because you're already subscribed...

**Comment by DaSchTour** [comment]
Yes and it was already an Unsubscribe when I entered this topic. But now I see it in my Participating block in my Notifications.

**Comment by TobiaszCudnik** [comment]
Seems like its supported now. With `typedoc --help` you get
>  --tsconfig                          Specify a js option file that should be loaded. If not specified TypeDoc will look for 'typedoc.js' in the current directory.

**Comment by blakeembrey** [comment]
Thanks @TobiaszCudnik 

Feel free to open a new issue if there's any problems that come up 😄
