### ISSUE TITLE
Syntax highlighting on typedoc.org

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1305]
Right now, there is no syntax highlighting on https://typedoc.org. This is especially annoying on the doc comments page - https://typedoc.org/guides/doccomments/

We should at least have syntax highlighting for TypeScript, but there might be other languages on the site that it should also be included for (none off the top of my head...)

**Comment by StoneT2000** [comment]
I'd suggest using https://github.com/googlearchive/code-prettify
It's been archived but still works really nicely, and you can define your own custom set of symbols to highlight with colors and what not

**Comment by sidthesloth92** [comment]
@Gerrit0 As the site is built using Jekyll, I would suggest using the inbuild highlighter for Jekyll. [Rouge](https://github.com/rouge-ruby/rouge). If it's okay I can create a PR.

**Comment by Gerrit0** [comment]
That would be great!

**Comment by sidthesloth92** [comment]
I've created the PR: https://github.com/TypeStrong/typedoc-site/pull/29. Let me know.

**Comment by Gerrit0** [comment]
Resolved by https://github.com/TypeStrong/typedoc-site/pull/29
