### ISSUE TITLE
Detect GitHub issue links in comments

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1311]
## Search Terms

github issue link

## Problem

It is fairly common to point readers to a GitHub issue in the doc comment for a class after describing a limitation. For example, here's a snippet from a comment I just wrote for `MethodReflection.overwrites`.

```ts
/**
 * This is a TypeScript design limitation. See Microsoft/TypeScript#22156. The default theme presents
 * methods as "overridden" instead of "overwritten", this is a compromise since most cases will not
 * intentionally overwrite methods. See GH#271.
 */
```

## Suggested Solution

Recognize and link the following patterns:
- `GH#\d+`
- `\w+/\w+#\d+`
- `#\d+`

**Comment by krisztianb** [comment]
Nice idea. I would make this a bit more customizable so that one can link to other "ticket systems" (eg. Jira) as well.

In Jira for instance you can have links like this https://jira.atlassian.com/browse/SRCTREE-4964 in which SRCTREE-4964 is the ID of the ticket.

So one could define:

1. A pattern to match link IDs: `SRCTREE-[\d]+`
2. A string with a placeholder for the matching ID: `https://jira.atlassian.com/browse/${TICKET_ID}`

What do you think?

**Comment by Gerrit0** [comment]
Right now TypeDoc doesn't have any builtin support for any other project management systems besides GitHub Enterprise (and I haven't used that so I'm not sure how well that's supported...)

It seems reasonable to try to support other systems... Jira is tricky since the `SRCTREE` key can be almost anything... Maybe this extra link detection functionality should be done via a specific links plugin (that maybe isn't enabled by default...)

**Comment by krisztianb** [comment]
Yes, I agree. This is a nice idea for a plugin.

**Comment by krisztianb** [comment]
I created a typedoc plugin called [typedoc-plugin-replace-in-comment](https://github.com/krisztianb/typedoc-plugin-replace-in-comment) for this task. I'm interested what you think about it.

**Comment by Gerrit0** [comment]
Looks like your repository is private ;)

**Comment by krisztianb** [comment]
Looks like I posted a wrong URL (missing S at the end). I updated it, please try again. 😄

**Comment by Gerrit0** [comment]
Looks pretty good! The one thing I would change is how options are handled. I would pull `value` out into its own private variable, and use declaration merging to avoid the need to cast + check to ensure that the option is configured correctly.

```ts
// plugin_options.ts

declare module "typedoc" {
  export interface TypeDocOptionMap {
    "replace-in-comments-config": string;
  }
}
```

**Comment by krisztianb** [comment]
Thanks for checking it out. Is there any other advantage using the declaration merging solution? I don't like that you have to repeat the name of the option when calling `getValue`.

**Comment by Gerrit0** [comment]
I don't find repetition to be a bad thing - so long as the compiler checks all instances but the first.

Another thing I thought of - you could change to taking a `ParameterType.Mixed`, which lets users specify their replacements in tsconfig.json > typedocOptions or typedoc.json without needing an extra file for your plugin.

**Comment by krisztianb** [comment]
Thanks. `ParameterType.Mixed`sounds like a good idea. I'll try that.
