### ISSUE TITLE
Merge type parameters when merging declarations

### ISSUE THREAD

**Issue by blutorange** [TypeStrong/typedoc#1314]
Not sure if this should be considered a bug, made this a feature request for now.

Creating the client-side documentation for PrimeFaces with tyepdoc worked great overall, but I noticed one issue: With certain libraries, it is common to write plugins and extend a core interface. For example, when writing a JQuery plugin, you write a declaration file that extends the `JQuery` interface with your additional methods.

When this interface contains a type parameter, they are not merged, resulting in duplicate type parameters in the output. See https://primefaces.github.io/primefaces/jsdocs/interfaces/jquery.typetotriggeredeventmap.html for a particular bad case with 32 type parameters instead of the expected 4.

## Search Terms

type parameters, generics, merging, declaration merging

## Problem

Typedoc merges the doc comments for multiple declarations of classes and interfaces, but does not merge type parameters. Basic example to reproduce:

```typescript
/**
 * An interface with a single generic parameters.
 */
interface E<A1> {
    foo: A1;
}

/**
 * Amend the interface E with additional properties.
 * @typeparam A1 Description for the type param.
 */
interface E<A1> {
    bar: A1;
}
```
This results in the following HTML output. The comments for the interface `E` are merged, but the type parameter `A1` appears twice.

![image](https://user-images.githubusercontent.com/2456413/82749765-62bcec80-9da3-11ea-814a-a48d3babe9ac.png)

## Suggested Solution

It would be great if type parameters could be merge the same way classes and interfaces are merged already. Comments could be concatenated.

One issue to consider is what constitutes the same type parameter. It could be either the type parameters's name or its position at which it appears. Typescript (usually?) seems to disallow type parameters with different names at the same position, so using the name would probably be safe. This avoids the problem of having to decide on a name when using its position instead.

**Comment by jose-pr** [comment]
I am also looking into this, found another issue from a few years back but not response/comment on it:
https://github.com/TypeStrong/typedoc/issues/618

**Comment by Gerrit0** [comment]
Yikes O.o that produces horrible output. This is definitely a bug. Library mode should avoid this by doing declaration merging in a sane way. PR welcome to fix it in the meantime.
