### ISSUE TITLE
TypeDoc CLI Doesn't Generate Default Theme Document

### ISSUE THREAD

**Issue by chrisalexander55** [TypeStrong/typedoc#1315]
#841  Search terms
CLI, arguments, args

## Expected Behavior
Should generate a default themed document.

## Actual Behavior
It produces nothing on the filesystem. Just outputs the following to console:

`TypeDoc 0.17.7
Using TypeScript 2.9.2 from /ds-web-components/node_modules/typescript/lib`

## Steps to reproduce the bug
typedoc.json
`{
  "name": "Prudential Web Components API Documentation",
  "includeVersion": true,
  "tsconfig": "./tsconfig.json",
  "mode": "file",
  "theme": "default",
  "inputFiles": ["./src", "./src/**"],
  "exclude": "**/*+(.d.ts|.spec|.e2e).ts",
  "includeDeclarations": false,
  "ignoreCompilerErrors": true,
  "out": "./dist/docs",
  "readme": "./README.md",
  "version": true
}`

tsconfig.json
`{
  "compilerOptions": {
    "rootDir": "src",
    "target": "es5",
    "lib": ["es6", "dom"],
    "typeRoots": ["node_modules/@types"],
    "rootDirs": ["src"],
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strict": false,
    "sourceMap": true,
    "baseUrl": ".",
    "declaration": true,
    "noImplicitAny": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["**/*.spec.ts"]
}`

CLI cmd:
`$ npx typedoc --options typedoc.json`

## Environment
- Typedoc version: 0.17.7
- TypeScript version: 2.9.2
- Node.js version: 10.15.3
- OS: OSX 10.14.6

**Comment by Gerrit0** [comment]
This is unactionable. You are running TypeDoc with an unsupported version of TS. I suggest either upgrading TS in your project, or using an older version of TypeDoc.

https://github.com/TypeStrong/typedoc/blob/9118a5ca611a040112554998b40976430396ae58/package.json#L34-L36
