### ISSUE TITLE
[Inquiry] Which Standard does The "Double Square Brackets" Link Meet?  

### ISSUE THREAD

**Issue by capraynor** [TypeStrong/typedoc#1317]
Hi, typedoc team
Thanks for your efforts.

We have a question about the link system in typedoc. 

We know that `{@link}` is a standard in tsdoc (https://github.com/microsoft/tsdoc). 

But which standard does `[[ClassName]]` meet? 
We searched a lot in google, and seems that this is only available in typedoc, correct? 

Thank you again for your awesome project
Raynor

**Comment by Gerrit0** [comment]
You're correct, this is a TypeDoc specific feature. TypeDoc existed ~4 years before TSDoc and thus does not very closely match the TSDoc standard.

**Comment by capraynor** [comment]
@Gerrit0  Thanks, got that.
