### ISSUE TITLE
is there any article to explain typedoc architecture，design idea or code flowing

### ISSUE THREAD

**Issue by yuzhidi** [TypeStrong/typedoc#1324]
Hi,
    I want to understand typedoc source code but it's not easy.
    is there any article to explain typedoc architecture，design idea or code flowing
Thx.

**Comment by Gerrit0** [comment]
There is https://typedoc.org/guides/development/, which is incomplete, and https://github.com/TypeStrong/typedoc/pull/914, which has some useful information (though it is certainly incomplete & becoming outdated)

I plan on updating the development guide on the website once library mode is complete.
