### ISSUE TITLE
Default Theme: allow to link directly to overloaded signatures - Currently there is no way to link to the nth overloaded definition of a function

### ISSUE THREAD

**Issue by JCMais** [TypeStrong/typedoc#1326]
## Search Terms
overloaded function method direct linking

## Problem
Currently, it's not possible to link directly to a specific overloaded method definition.

## Suggested Solution
Clicking on any method overload should change the current URL so that it can be linked directly:
![image](https://user-images.githubusercontent.com/1041647/86060548-4b74bd00-ba3b-11ea-8cf8-3c3ef09ced7c.png)

Sorry if this has been asked before, could not find another issue asking for this

**Comment by Gerrit0** [comment]
This is a good idea. I don't know if it is possible with the current themes + anchor generation, but would love to be proven wrong.
