### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by gz65555** [TypeStrong/typedoc#1329]
``` javascript
function createReferenceReflection(context, source, target) {
    if (!(context.scope instanceof models_1.ContainerReflection)) {
        throw new Error('Cannot add reference to a non-container');
    }
    if (target.declarations.some(d => context.isOutsideDocumentation(d.getSourceFile().fileName))) {
        return;
...
}
```

I don't know when will  be `target.declaration === undefined`. I have used `typedoc-plugin-lerna-packages` plugin. Would someone give me some information ?

## Environment
- Typedoc version: 0.16.11
- TypeScript version: 3.7.5
- Node.js version: v13.8.0
- OS: mac os catalina

**Comment by Gerrit0** [comment]
TypeScript's types are wrong about some nullable types. `symbol.declarations` is one of them.  We should be using `symbol.getDeclarations()` there instead and checking for null. I think it is correct to assume that if there are no declarations, the symbol is external.

**Comment by gz65555** [comment]
Sorry, I'm a newbie of typescript and typedoc. I still have some questions for your explain: 
- Are these code (`target.declarations.some..`) finding `.d.ts` files? 
- What does `symbol.getDeclarations()` do?

**Comment by Gerrit0** [comment]
`symbol.declarations` is refers to everywhere the symbol is defined. That might be in declaration files or source files.
`symbol.getDeclarations()` is just a getter which returns `symbol.declarations`, but is correctly typed to return `ts.Node[] | undefined`, while `symbol.declarations` is incorrectly typed to be type `ts.Node[]`. There's an open issue in the TS repo regarding this. https://github.com/microsoft/TypeScript/issues/24706

**Comment by lucastschmidt** [comment]
same here
