### ISSUE TITLE
Italic not working properly when markdown expression is followed by a comma sign

### ISSUE THREAD

**Issue by marcoliceti** [TypeStrong/typedoc#1331]
## Search terms

italic, markdown, underscore, comma

## Expected Behavior

Text between underscores should be rendered in italic.

## Actual Behavior

When the closing underscore is immediately followed by a comma, the text in the generated documentation is not rendered in italic and is surrounded by underscores, as in source markdown.

In other words, proper markdown parsing seems to be failing.

My workaround is to leave a space after the underscore, but the end result is not very nice.

## Steps to reproduce the bug

https://github.com/marcoliceti/typedoc-markdown

## Environment

- Typedoc version: 0.12.3
- TypeScript version: 3.9.5
- Node.js version: 10.15.3
- OS: Ubuntu 16.10

**Comment by Gerrit0** [comment]
Looks like this is a bug with Marked v1.0.0, upgrading the dependency should fix it. PR welcome :)

**Comment by marcoliceti** [comment]
Ok, I'll try to send the PR soon.

P.s. The issue is indeed caused by Marked v1.0.0 and is fixed in Marked v1.1.0, which is easy to reproduce with [their online demo](https://marked.js.org/demo).

**Comment by Gerrit0** [comment]
This was fixed with 14eb245 and released in 0.18.
