### ISSUE TITLE
Side navigation to support @category

### ISSUE THREAD

**Issue by y-nk** [TypeStrong/typedoc#1332]
## Search Terms
@category, sidebar, navigation

## Problem
When using @category, the main page is rightfully parsed and generated, but the sidebar isn't.

## Suggested Solution
Reusing the generated data tree from the main page and injecting it into the sidebar (with different styling) should be enough

**Comment by Gerrit0** [comment]
Closing in favor of #1532, which is a bit clearer about what this request is
