### ISSUE TITLE
How to understand TemplateDelegate template with PageEvent?

### ISSUE THREAD

**Issue by yuzhidi** [TypeStrong/typedoc#1334]
[renderer#rednerDocument](https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/renderer.ts#L137) call
```ts
        // Theme must be set as this is only called in render, and render ensures theme is set.
        page.template = page.template || this.theme!.resources.templates.getResource(page.templateName)!.getTemplate();
        page.contents = page.template(page, { allowProtoMethodsByDefault: true, allowProtoPropertiesByDefault: true });
```
page.template defination in [event.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/events.ts#L115)
```ts
    /**
     * The template that should be used to render this page.
     */
    template?: TemplateDelegate;
```
[handlebars](https://www.npmjs.com/package/handlebars) show Handlebars.template with simple json data
```ts
var source = "<p>Hello, my name is {{name}}. I am from {{hometown}}. I have " +
             "{{kids.length}} kids:</p>" +
             "<ul>{{#kids}}<li>{{name}} is {{age}}</li>{{/kids}}</ul>";
var template = Handlebars.compile(source):
var data = { "name": "Alan", "hometown": "Somewhere, TX",
             "kids": [{"name": "Jimmy", "age": "12"}, {"name": "Sally", "age": "4"}]};
var result = template(data);
```
How to understand page.template(page, ...), param page is PageEvent, so complex!

**Comment by Gerrit0** [comment]
As discussed somewhat in gitter, this is an unanswerable question. I agree that the current theming system is horrible, but don't really have any good way to propose how to understand it. Every time I look at it I learn something new about it.
