### ISSUE TITLE
Fix for #1330 is still unreleased.

### ISSUE THREAD

**Issue by sylvanaar** [TypeStrong/typedoc#1344]
The fix for issue #1330 is still unreleased.

It should really be released so the tool doesn't just crash when it is run with the error:

`RangeError: Maximum call stack size exceeded`

**Comment by Gerrit0** [comment]
Released in 0.18.0

**Comment by sylvanaar** [comment]
@Gerrit0 I guess I just followed a MS link and assumed that it was one of theirs - I should have looked more closely. I totally get it - I have large projects I do in my spare time too - and I hate when people don't appreciate that. Full throated apology!
