### ISSUE TITLE
Cannot find a way to generate html files

### ISSUE THREAD

**Issue by BenDevelopment** [TypeStrong/typedoc#1347]
Hi,

When i run `npx typedoc --options ../typedoc.json ./src`, all I got is a bunch of *.md files. What should I do with thoses files? Is there a way to generate *.html files instead? That I can host them in my web server?

Here is my `typedoc.json`:

```
{
	"out": "../doc-dist",
	"exclude": [
		"**/*.spec.ts"
	],
	"module": "commonjs",
	"theme": "default",
	"name": "My Doc",
	"hideGenerator": true,
	"excludeExternals": true
}
```

Thank you for your help.

Ben

**Comment by Gerrit0** [comment]
It sounds like you have typedoc-plugin-markdown installed. If you specify `"plugin": []` in your options file, it will disable automatic plugin loading & you should get html output.
