### ISSUE TITLE
Adding examples (@example) to the documentation

### ISSUE THREAD

**Issue by bali182** [TypeStrong/typedoc#135]
Thanks for the really great documentation tool! 

I was wondering, if there is any way to add examples directly into the doccoment? I noticed, that adding custom tags like `@whatever` shows up in the generated documentation, and if I use the triple quote markdown syntax, I get syntax highlighting. It also looks like, that `@example` is not treated as a special annotiation. But is the `@example` & markdown combo the standard way of adding API examples to your source? Is there a standard way at all?

**Comment by sebastian-lenz** [comment]
Hi Édes, nice to hear from you. TypeDoc currently has no explicit support for the <code>@example</code> tag, I've always preferred to include samples within the comment body itself using the markdown syntax for code blocks.

The "official" JSDoc implementation supports the <code>@example</code> tag, see [here](http://usejsdoc.org/tags-example.html). TypeDoc is not aiming at being fully aligned to JSDoc but maybe we should give the <code>@example</code> special treatment too.

**Comment by bali182** [comment]
Thanks for the quick response, Sebastian! I think, it would be a very nice extension of the existing functionality, if `@example` would be available :) If you consider adding it, let me know if I can help in any way!

**Comment by MartinSvarrer** [comment]
Just found this issue as I tried the same combination, expecting @example and code snippets to work together. Instead I just get a tag on top of my snippet, pushing my code.
![image](https://cloud.githubusercontent.com/assets/3289674/10310160/d70eab1c-6c40-11e5-9d92-587d7ee24f31.png)

**Comment by stepancar** [comment]
+1 need to:)

**Comment by tomlarkworthy** [comment]
I have tried triple markdown but the whitespace seems to get stripped? Some help on inserting code blocks would be greatly appreciated

**Comment by landonpoch** [comment]
I tried markdown syntax and it appears to work just fine.  In my mind this issue isn't that critical.  However, it might be nice to see the example tag show up above the examples that are included in the docs.

**Comment by jtraband** [comment]
Fenced code blocks do seems to have whitespace stripped.  ( per comment above).  This does make it difficult to include multiline examples in the docs.

**Comment by lharzenetter** [comment]
I would like to have this feature too 👍
For now i also tried the markdown syntax and the highlighting (preformatted also) works fine. However, i always have the three backticks ``` displayed also. Anyone a solution for that?

**Comment by amarzavery** [comment]
Update: I was able to preserve whitespaces/indentation. One needs to start the example with stars (*).

```typescript
   * . . . 
   * @example
   * ```typescript
   * 
   *const resourceGroupName = 'res9101';
   *const accountName = 'sto4445';
   *const parameters: StorageManagementModels.StorageAccountCreateParameters = {
   *  sku: {
   *    name: <StorageManagementModels.SkuName>'Standard_GRS'
   *  },
   *  kind: <StorageManagementModels.Kind>'Storage',
   *  location: 'eastus2euap',
   *  tags: {
   *    "key1": "value1",
   *    "key2": "value2"
   *  }
   * };
   *const storageAccount = await client.storageAccounts.create(resourceGroupName, accountName, parameters);
   * ``` 
   * @param {string} resourceGroupName The name of the resource group within the
   * user's subscription. The name is case insensitive.
   * . . .
```

### As you can see the indentation is preserved in the example.
![image](https://user-images.githubusercontent.com/4521223/32129441-0b5870fa-bb3c-11e7-9a08-5365e9e22856.png)

**Comment by Gerrit0** [comment]
With TypeDoc 0.23 (currently sitting on the beta branch, no release yet since I broke lots of things...), TypeDoc is much smarter about parsing comments, it will correctly handle indentation in code blocks, even without leading `*`s on each line.

Note: TypeDoc and JSDoc disagree about what an `@example` block contains. Both TypeDoc and TSDoc say that it contains regular text, like any other block, and may contain a code block. JSDoc says that the `@example` block *is implicitly* a code block.
