### ISSUE TITLE
Declaration Files CLI Crashing

### ISSUE THREAD

**Issue by BumpyBill** [TypeStrong/typedoc#1351]
## Search terms

- declaration files
- declaration files error
- declaration files CLI crash

## Expected Behavior
Generate documentation from .d.ts file

## Actual Behavior
crashes the CLI saying it cannot generate files in the directory "(project)/docs"

## Steps to reproduce the bug
in tsconfig: 
```json
  "typedocOptions": {
    "mode": "file",
    "out": "docs",
    "includeDeclarations": true
  }
```
have some declaration files in the "typings" directory
then in the terminal
```bash
typedoc typings
```
> The project is here if you want to see: https://github.com/BumpyBill/disca

## Environment
- Typedoc version: TypeDoc 0.18.0
- TypeScript version: 3.9.7 
- Node.js version: 14.2.0
- OS: Windows 64

**Comment by Gerrit0** [comment]
The repo you linked doesn't appear to have a `typings` directory... I tossed a basic `index.d.ts` file in there with the following and TypeDoc worked correctly.

```ts
export const x: 1
```

**Comment by BumpyBill** [comment]
I checked my gitignore, and for some reason, it was there! Thank you very much.
