### ISSUE TITLE
typedoc typings

### ISSUE THREAD

**Issue by BumpyBill** [TypeStrong/typedoc#1355]
## Search terms
- Typedoc Typings
- Typedoc Declaration File

## Expected Behavior
Generate docs from the cwd + typings

## Actual Behavior
generates docs from the typescript typings

## Steps to reproduce the bug

Have this be in you tsconfig:
```json
  "typedocOptions": {
    "mode": "modules",
    "out": "docs",
    "includeDeclarations": true
  }
```
and run
`typedoc typings`

## Environment
- Typedoc version: 0.18.0
- TypeScript version: 4.0.2
- Node.js version: 14.2.0
- OS: Windows 10 (x64)

**Comment by Gerrit0** [comment]
Huh? I don't understand your issue. There isn't enough here for me to understand what you did. `includeDeclarations` is a dangerous option though, if you set `excludeExternals` you might get the behavior you are expecting.
