### ISSUE TITLE
Add JSDocs style commenting to exported "types"

### ISSUE THREAD

**Issue by jplante** [TypeStrong/typedoc#1358]
Ideally it would be great if the TypeDocs JSON output could provide "type" spefici information about exported/declared types.

For example:
```
export type VectorAlias = 
  | Vector 
  | { direction: number, magnitude: number } 
  | [ direction: number, magnitude: number ]
;
```

Could become:
```
export type VectorAlias = 
 /**
  * description blah blah blah
  */   
  | Vector 

 /**
  * description blah blah blah
  */   
  | { direction: number, magnitude: number } 

 /**
  * description blah blah blah
  */   
  | [ direction: number, magnitude: number ]
;
```

**Comment by Gerrit0** [comment]
This is... tricky. Where does this end?

```ts
type Something =
  /** 1 */
  | A
  | { /** 2 */ b: 2 }
  | { c: /** 3 */ 3 }
  | { d: [/** 4 */ 4 | 5] }
```

**Comment by Gerrit0** [comment]
I'm going to go ahead and mark this as wontfix - I do plan on adding support for "union enums", but that's a very specific case. I haven't been able to figure out a nice way to generically handle comments *everywhere* https://github.com/microsoft/tsdoc/issues/164
