### ISSUE TITLE
Categories aren't parsed out of .d.ts files

### ISSUE THREAD

**Issue by LJNeon** [TypeStrong/typedoc#1359]
## Expected Behavior
`ProjectReflection.categories` should be properly populated with all categories used after conversion.

## Actual Behavior
`ProjectReflection.categories` is `undefined` even after conversion.

## Steps to reproduce the bug
Here's a [bare bones example](https://gist.github.com/LJNeon/0add87a4641ee249625c643850177c40).
No `tsconfig.json` or other configuration files are used.

## Environment
- Typedoc version: v0.18.0
- TypeScript version: v4.0.2
- Node.js version: v14.9.0
- OS: Same thing happens regardless of OS.

**Comment by Gerrit0** [comment]
Having looked at this a bit more, this is expected. Setting `mode` to `file` doesn't disable nesting members within declared modules. It only disables treating each file as a module. Your declaration file has `declare module "something"`, which creates a new module. Looking at `categories` for that module includes the expected category. Taking a look at the generated JSON reveals this.

```
 90             "categories": [
 91                 {
 92                     "title": "Alphabet",
 93                     "children": [
 94                         2
 95                     ]
 96                 }
 97             ],
```

**Comment by LJNeon** [comment]
Would there be a way to fix this module within a module setup?

**Comment by Gerrit0** [comment]
I'm not sure what you mean by that. Since you are using the JSON yourself, you can just grab the module you are interested in and only work with that. There is not any way currently to move reflections between modules.

**Comment by LJNeon** [comment]
Well it seems like currently, I have something like `libraryName.libraryName.ClassName` instead of just `libraryName.ClassName`. And that's what caused my confusion in this example.

**Comment by Gerrit0** [comment]
Wherever you are getting that name from likely builds it up by going up through the reflection tree until it gets to the project, also including that name; so the first libraryName is the project name, the second the module.

**Comment by LJNeon** [comment]
Would there be a way to treat the project AS the module instead of creating one within the project then?

**Comment by LJNeon** [comment]
Although at this point I've changed subjects entirely. This might be better suited for discord than a github issue.
