### ISSUE TITLE
make docs updating not always update the links despite no content change

### ISSUE THREAD

**Issue by StoneT2000** [TypeStrong/typedoc#1360]
## Search Terms

Doc external links
Code links
## Problem

Every time I rebuild the documentation, the links are completely different even though there is no actual content change. I see the only difference being the commit SHA? Is there a way for the code to use a link to the master branch instead?

**Comment by Gerrit0** [comment]
Sounds like you are after the `gitRevision` option - https://typedoc.org/guides/options/#gitrevision

**Comment by StoneT2000** [comment]
that works, thanks!
