### ISSUE TITLE
0.19.0 broke support for typescript 3.9.7

### ISSUE THREAD

**Issue by Dergash** [TypeStrong/typedoc#1362]
Recent upgrade to typescript `4.*.*` in 0.19.0 broke backward-compatibility for typescript 3.9.7 due to the unchecked usage of `ts.isNamedTupleMember` call: https://github.com/TypeStrong/typedoc/commit/e1364695db03f503ab38f2dd55ac6e1d77f2f60d#diff-b580b34740b3647ff5b29f4cb299a61aR77
which results in the following output when trying to generate documentation with TS 3.9.7:
```
C:\projects\tesler-ui\node_modules\typedoc\dist\lib\converter\types\tuple.js:44
        return ts.isNamedTupleMember(node);
                  ^

TypeError: ts.isNamedTupleMember is not a function
```

I believe the change was introduced due to https://github.com/TypeStrong/typedoc/issues/1357.

Investigating further I've also found that the 0.17.0 also broke support for typescript 3.7.3 (which is version used in create-react-app 
 typescript template) due to the unchecked usage of `ts.isIdentifierOrPrivateIdentifier`: https://github.com/TypeStrong/typedoc/commit/5d41a2e03a4cefa29ae84e7f9ef409d976d4ac56#diff-560fefcd039cbf06578d6f95c3e57753R413

[I've prepared a PR](https://github.com/TypeStrong/typedoc/pull/1361/files) to restore backward compatibility.

I've also found following issues warning about not following declared peer dependency: https://github.com/TypeStrong/typedoc/issues/1240, https://github.com/TypeStrong/typedoc/issues/1257, https://github.com/TypeStrong/typedoc/issues/979

Although I'll agree that backward compatibility might be not a requirement for `0.*.*` library and peer dependency are indeed warn you, broken typescript versions are pretty recent and the fix is pretty simple and non-invasive so it'll be nice to support those versions until typescript 4 stabilizes a bit so majority typedoc users may migrate to `4.*.*`

## Search terms
isNamedTupleMember, isIdentifierOrPrivateIdentifier, typescript 3
## Expected Behavior
typedoc is backward compatible for typescript versions 3.7.3 and 3.9.7

## Actual Behavior
`yarn typedoc` command results in the following output on the project with typescript 3.9.7:
```
Using TypeScript 3.9.7 from C:\projects\tesler-ui\node_modules\typescript\lib
C:\projects\tesler-ui\node_modules\typedoc\dist\lib\converter\types\tuple.js:44
        return ts.isNamedTupleMember(node);
                  ^

TypeError: ts.isNamedTupleMember is not a function
```

## Steps to reproduce the bug
I've prepared an example project to reproduce the bug:
https://github.com/Dergash/typedoc-tamed-tuples (master branch for 3.7.3 example, 3.9.7 branch for 3.9.7) 
Just clone it, yarn install, yarn typedoc and you'll receive the output

## Environment
- Typedoc version: 0.19.0, https://registry.yarnpkg.com/typedoc/-/typedoc-0.19.0.tgz#438ae5a8e631322e3fc21f6068f2729ff15b18b9
- TypeScript version:  3.9.7, 3.7.4
- Node.js version: v14.5.0
- OS: Windows 10 Pro 19041.450

**Comment by wsz7777** [comment]
I miss this problem too, when I can use it with no error?

**Comment by ibwei** [comment]
I got this problem too...

**Comment by Dergash** [comment]
@wsz7777  @ibwei 
I now believe that it is technically not a bug but a feature request as typescript 4.0.2 is properly declared as a peer dependency.

So if this backward compatibility feature will not be merged I think the following options are available for you:
1) Update typescript to 4.0.2 in your project to accommodate the peer dependency
2) Use typedoc 0.18.0 as a strict dependency in your file, which supports typescript >= 3.8.3:
your package.json:
```json
"devDependencies": {
     "typedoc": "0.18.0"
}
````
or just yarn add typedoc@0.18.0
3) I've published a forked version of 0.19.0 with related fix that you can use:
```
"devDependencies": {
     "typedoc": "@tesler-ui/typedoc"
}
```
or you could fork yourself and implement changes and fix yourself using linked PR as a reference.

**Comment by wsz7777** [comment]
thank you ,in my project  use typescript around packages with @4.x can solve this problem.
    
"typescript": "^4.0.2",
"jest": "^26.4.2",
"ts-jest": "^26.3.0",
"@types/jest": "^26.0.13",
"@typescript-eslint/eslint-plugin": "^4.0.1",
"@typescript-eslint/parser": "^4.0.1",

**Comment by ibwei** [comment]
> @wsz7777 @ibwei
> I now believe that it is technically not a bug but a feature request as typescript 4.0.2 is properly declared as a peer dependency.
> 
> So if this backward compatibility feature will not be merged I think the following options are available to you:
> 
> 1. Update typescript to 4.0.2 in your project to accommodate the peer dependency
> 2. Use typedoc 0.18.0 as a strict dependency in your file, which supports typescript >= 3.8.3:
>    your package.json:
> 
> ```json
> "devDependencies": {
>      "typedoc": "0.18.0"
> }
> ```
> 
> or just yarn add typedoc@0.18.0
> 3) I've published a forked version of 0.19.0 with related fix that you can use until you find possible to upgrade typescript:
> 
> ```
> "devDependencies": {
>      "@tesler-ui/typedoc": "0.19.0-typescript-3"
> }
> ```
> 
> or just
> 
> ```shell
> yarn remove typedoc
> yarn add @tesler-ui/typedoc
> ```
> 
> or you could fork yourself and implement changes and fix yourself using linked PR as a reference.

Thank you very much.I updated my typescript version follow your tips,then this problem hava solved.

**Comment by Gerrit0** [comment]
As discussed a bit in #1361, supporting old versions of TypeScript isn't really what I'd like to focus the time I have for this project on. `typedoc@0.19.1` reintroduces support for `typescript@3.9` thanks to @Dergash, and I think supporting one minor version older than the current version is feasible, so will try to do that... If you're still on an older version of TypeScript than that, upgrade!

**Comment by thekennysong** [comment]
As what others said I upgraded to "typescript": "^4.0.2" and it works great now. Thanks all!
