### ISSUE TITLE
How to track progress on library mode?

### ISSUE THREAD

**Issue by DanielSWolf** [TypeStrong/typedoc#1363]
At our company, we use the library mode TypeDoc used to have. Since library mode doesn't exist any more, we're stuck with the old version 0.17.0-3 of TypeDoc, so we don't get any of the new features and bug fixes added since then.

The epic #1266 says

> See (issue not yet created... next week) for a tracking thread for what's being done and still needs to be done for this to be complete.

I'd love to track the progress of this feature, but the tracking issue doesn't seem to exist. What's the best way for me to keep up to date on this topic?

**Comment by Gerrit0** [comment]
And here I thought I'd be safe to put that there for a week, I just put that there last Sunday! I will create the tracking issue this weekend. The most up to date checklist right now is https://github.com/TypeStrong/typedoc/pull/1184#issuecomment-650809143

**Comment by DanielSWolf** [comment]
I'm sorry, I didn't mean to rush you! I didn't realize that your comment about next week was a recent edit, or I would have waited!

In the mean time, thanks for sharing the comment!

**Comment by Gerrit0** [comment]
Not a problem at all! I hadn't updated that post in over a month before that, so I certainly didn't expect anyone to look at edit history :)

**Comment by Gerrit0** [comment]
Issue opened - #1364.
