### ISSUE TITLE
Re-exported symbols inside a namespace are ignored

### ISSUE THREAD

**Issue by hiranya911** [TypeStrong/typedoc#1366]
## Search terms
namespace, re-export

## Expected Behavior
List re-exported symbols as members of the namespace.

## Actual Behavior
Re-exported symbols are ignored.

## Steps to reproduce the bug

Run `tsdoc` against the following input:

```ts
// index.d.ts
interface Bar {
  prop: number;
}

declare namespace admin {
  export interface Foo {
    prop: string;
  }

  export { Bar }
}

export = admin;
```

Generated output only lists `Foo` for `admin`:

<img width="1255" alt="Screen Shot 2020-09-11 at 5 07 00 PM" src="https://user-images.githubusercontent.com/2375201/92982025-5394a400-f451-11ea-8bae-27f115355179.png">

Same happens when re-exporting symbols imported from another file:
```ts
import { auth } from './auth/index';

declare namespace admin {
  export { auth }
}
```

## Environment
- Typedoc version: v0.18.0
- TypeScript version: v3.9.6
- Node.js version: v10.22.0
- OS: Mac

**Comment by Gerrit0** [comment]
Fix published in v0.19.2
