### ISSUE TITLE
Render validated/predicated type instead of "unknown" for public library functions?

### ISSUE THREAD

**Issue by skddc** [TypeStrong/typedoc#1370]
A question for something I couldn't find out if it is possible. For our library, it would be great if users wouldn't see "unknown" as an argument type, but instead the actual type they're supposed to hand to the function.

Consider this example from our codebase, which we recently ported from JS/JSDoc to TS/TypeDoc, and which still declares the `number` type for the argument in the doc comment, as we haven't removed the types from JSDoc yet:

```typescript
  /**
   * Set the value of the sync interval when application is in the foreground
   *
   * @param {number} - Sync interval in milliseconds (between 1000 and 3600000)
   */
  setSyncInterval (interval: unknown): void {
    if (!isValidInterval(interval)) {
      throw interval + " is not a valid sync interval";
    }
    const oldValue = config.syncInterval;
    config.syncInterval = interval;
    this._emit('sync-interval-change', {oldValue: oldValue, newValue: interval});
  }
```

The function throws an error, based on the following validator function, which implements a predicate to narrow down the type:

```typescript
/**
* Check if interval is valid: numeric and between 1000ms and 3600000ms
*/
function isValidInterval(interval: unknown): interval is number {
  return (typeof interval === 'number' &&
          interval > 1000 &&
          interval < 3600000);
}
```

However, our output (rendered by [sphinx-js](https://github.com/mozilla/sphinx-js/) using the new release with TypeDoc support) shows the library user the defined argument type of "unknown":

![Screenshot of doc output](https://user-images.githubusercontent.com/843/94144160-17117100-fe71-11ea-9c33-e871bec03013.png)

Anyone has ideas for how to achieve using the correct type in the code (we can't know what the JS library user will hand to the function there), and yet rendering the expected type instead?

**Comment by Gerrit0** [comment]
There isn't any method for doing this, though a "display type" plugin is a neat idea. Is there some reason you didn't switch to `interval: number` immediately? TS will still let you do the `isValidInterval` check without errors.

**Comment by skddc** [comment]
Yeah, after thinking about it more, I came to the conclusion that using the number type immediately, and being careful about validating all incoming arguments from unknown sources, is probably the best solution. Thanks.
