### ISSUE TITLE
Why I am getting all this not found errors?

### ISSUE THREAD

**Issue by antoniogamiz** [TypeStrong/typedoc#1371]
I have published the generated docs to Github Pages but I cannot go to those files. I do not know if this is a bug with Github or with the URLs generated by typedoc.

- Github pages -> https://antoniogamiz.github.io/manga-api/
- Github pages branch -> https://github.com/antoniogamiz/manga-api/tree/gh-pages/

The thing is that the files I'm requesting are there, so maybe the URLs are not valid mm. Does anyone know anything?

**Comment by Gerrit0** [comment]
I suspect this is the same problem as in #149 / #620 - the url building is changing in 1.0, which will fix this without the need for those workarounds, but that's still a couple months out.

**Comment by antoniogamiz** [comment]
Adding `.nojekyll` has worked, so I will wait to 1.0, thanks :).
