### ISSUE TITLE
Running into a ENOENT: no such file or directory error while trying to generate docs

### ISSUE THREAD

**Issue by pastelsky** [TypeStrong/typedoc#1379]
## Search terms

ENOENT

## Expected Behavior

1. Install `typedoc` locally using yarn -

```
yarn add --dev typedoc
```
2. Have typescript installed in local `node_modules`.
3. Add a script to `package.json` — `typedoc --out docs`
4. Run `yarn docs`

Fails with —
```Using TypeScript 4.0.3 from /Users/skanodia/dev/package-build-stats/node_modules/typescript/lib
fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/Users/me/dev/my-package/node_modules/typedoc-default-themes/bin/default/assets'
    at Object.statSync (fs.js:856:3)

```
I don't see an `assets` folder when I cd into the directory

## Actual Behavior

No error

## Steps to reproduce the bug

Described above

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.0.3
-   Node.js version: 12.6.0
-   OS: Mac OS

**Comment by macrozone** [comment]
@pastelsky i have the same error. how did you solve it?
