### ISSUE TITLE
Support @deprecated, @alpha, and @beta TSDoc modifiers

### ISSUE THREAD

**Issue by alexkreidler** [TypeStrong/typedoc#1381]
#547 mentions that a goal of future TypeDoc versions is to be compliant with TSDoc.

[`@deprecated`](https://api-extractor.com/pages/tsdoc/tag_deprecated/) is a core TSDoc standard that is used by many tools, including IDEs like VSCode to indicate deprecation.

Although `@alpha` and `@beta` are "discretionary" modifiers, they are used by [API Extractor](https://api-extractor.com/pages/tsdoc/tag_alpha/) and many Microsoft APIs (e.g. rush, heft, etc), and I believe are quite useful.

I propose we either add a strikethough, "gray out" the name, or add an icon next to items that are marked deprecated.
I also propose we add icons/tags in the UI next to items that are marked `@alpha` and `@beta`.

These are likely less important than other core TSDoc features like `@link`ing, etc, so it may likely be implemented later.

Thanks for an awesome tool!

**Comment by Gerrit0** [comment]
Definitely planned - but probably won't happen this year... I'm planning on starting on TSDoc support come January though :)

**Comment by doberkofler** [comment]
Support for `@deprecated` would be most appreciated

**Comment by kamranayub** [comment]
Here is a commit you could reference where we support `@obsolete` (before deprecated was a thing), maybe for Hacktoberfest I could add this for `@deprecated`

https://github.com/excaliburjs/typedoc-default-themes/commit/8c824b8e5cc04afbc07e1d332da3cf19495451e5
