### ISSUE TITLE
ReferenceType.equals() returns incorrectly returns true when symbolFullyQualifiedName fields are different

### ISSUE THREAD

**Issue by socsieng** [TypeStrong/typedoc#1383]
## Search terms

ReferenceType, equals, symbolFullyQualifiedName

## Expected Behavior

`ReferenceType.equals()` should return false when `symbolFullyQualifiedName` isn't equal.

Example:

```ts
const type1 = new ReferenceType("Type1", "Type1");
const type2 = new ReferenceType("Type2", "Type2");

equal(type1.equals(type2), false); // should return false, but returns true instead
```

## Actual Behavior

`ReferenceType.equals()` returns true because `reflection` on both types are `undefined` and satisfies the `|| other.reflection === this.reflection` condition.

## Steps to reproduce the bug

```ts
const type1 = new ReferenceType("Type1", "Type1");
const type2 = new ReferenceType("Type2", "Type2");

equal(type1.equals(type2), false); // should return false, but returns true instead
```

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.0.3
-   Node.js version: v10.19.0
-   OS: macOS

**Comment by Gerrit0** [comment]
This one is probably going to be a wontfix - reference types are changing in 0.20 to use symbols instead of fully qualified names, so it won't apply anymore.

**Comment by socsieng** [comment]
Thanks for the quick response. I've actually already prepared a change with tests.

Let me know if you're interested and I can submit a PR (the test may/may not be useful going forward).

**Comment by Gerrit0** [comment]
Go ahead and submit it - There might need to be another 0.19 release before 0.20 comes, so it would be valuable there :)
