### ISSUE TITLE
Include a sample of TypeDoc output somewhere easy to find.

### ISSUE THREAD

**Issue by MicahZoltu** [TypeStrong/typedoc#1385]
## Search Terms
TypeDoc sample

## Problem
I was trying to *quickly* figure out what TypeDoc does exactly and was unable to easily locate just a sample of the output.

## Suggested Solution
Just link to a docs page that uses TypeDoc (ideally a sample project) and also link to the JSON output.  This would allow users trying to figure out if TypeDoc fits their needs to rapidly get that question answered.

**Comment by Gerrit0** [comment]
I haven't updated it in a long while, but http://typedoc.org/api/ has TypeDoc's output when run on itself.

I like the idea of the JSON output - will add that next time I update the docs (with 0.20 release)

**Comment by Gerrit0** [comment]
The site update tomorrow includes text that emphasizes that the /api directory is typedoc output, and adds /api/docs.json

**Comment by Gerrit0** [comment]
The out and json options now include links to the output when run on TypeDoc - https://typedoc.org/guides/options/#out

**Comment by ollydixon** [comment]
@MicahZoltu @Gerrit0  I'm still not sure what it actually does; I can't find any samples on the home website?

**Comment by Gerrit0** [comment]
https://typedoc.org/api/ is the result of running typedoc on typedoc

**Comment by ollydixon** [comment]
@Gerrit0 but I don't see any actual examples; I just see instructions; we've decided not to use the library it's unclear what it does. Hope this feedback helps. We decided to use https://apidocjs.com/ instead with a TS converter.

**Comment by MicahZoltu** [comment]
@ollydixon It generates a documentation site (HTML/CSS/JS) from a TypeScript codebase that includes typedoc compatible comments and TS type information.  If that statement clears things up for you, maybe there would be value in adding it to the top of the readme, after the first sentence?
