### ISSUE TITLE
Interface comments are ignored

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [TypeStrong/typedoc#1391]
Unfortunately, I found another issue trying to generate documentation for my project:

## Expected Behavior

When running typedocs over a class with interfaces in the constructor, I'd expect the comments to be displayed

## Actual Behavior

No comments are displayed

## Steps to reproduce the bug

Given:
```
interface Settings {
  /** some description */
  foo: string
}

class MyClass {
  constructor({ foo = 'bar' }: Settings) { ... }
}
```

The Typedocs output is

```
# constructor

    new MyClass(__namedParameters: { foo: string }): MyClass

     >   Defined in MyClass.ts:87

## Parameters
        __namedParameters: { foo: string }

           - foo: string
```

While the description is correctly displayed under the Settings Interface, in the Classes documentation it's not.
I'd either expect it to have the description from the interface taken over like:

```
- foo: string
some description
```

Or to have a reference to the interface something like this:

```
## Parameters
        __namedParameters: settings: Settings

 - settings: Settings
```

## Environment

-   Typedoc version: `"typedoc": "^0.19.2",`
-   TypeScript version: `"typescript": "^4.0.5"`

**Comment by Gerrit0** [comment]
I believe this is a problem with typedoc-plugin-markdown - The default themes will render this as follows, with a link to the settings interface:

![image](https://user-images.githubusercontent.com/19329837/97818292-edf9b280-1c5e-11eb-875f-feb96a00fa6e.png)

**Comment by ThibaultJanBeyer** [comment]
Somehow no, just using:

`typedoc --out docs/ts --mode modules src`

See:

<img width="345" alt="Screenshot 2020-11-02 at 00 37 00" src="https://user-images.githubusercontent.com/12467511/97818593-8fa2f300-1ca3-11eb-9d49-75e512bd18dd.png">
<img width="608" alt="Screenshot 2020-11-02 at 00 36 53" src="https://user-images.githubusercontent.com/12467511/97818594-90d42000-1ca3-11eb-9554-92af6c9b57c1.png">

**Comment by Gerrit0** [comment]
Oops... I checked on the 0.20 beta - this is another case of the bug linked in your other issue.

**Comment by ThibaultJanBeyer** [comment]
Ah! All right, any plans when 0.20 will be released? :D

**Comment by Gerrit0** [comment]
That highly depends on how many issues are discovered - The [current set](https://github.com/TypeStrong/typedoc/projects/5) of remaining things to do isn't that large, so I might be able to get it done in another couple of weeks. https://github.com/TypeStrong/typedoc/issues/1364 tracks what's being done.

That said, I am publishing betas, which will likely produce better output already than 0.19 (but might not work correctly with plugins - I'm almost certain I broke the markdown plugin since TypeDoc now supports more literal types than just string literals)

**Comment by ThibaultJanBeyer** [comment]
All right, I don't really understand what you mean by the plugins but looking forward to the changes. Where can I get the beta releases?
Will close this issue then since it's addressed in the new version already as you say :)

**Comment by Gerrit0** [comment]
By plugins I mean packages like typedoc-plugin-markdown that add extra features to TypeDoc.

You can get betas with `npm install typedoc@beta`

**Comment by ThibaultJanBeyer** [comment]
Thank you, will try it out!
