### ISSUE TITLE
Implicitly declared properties of interfaces aren't shown or inherited

### ISSUE THREAD

**Issue by 1s3k3b** [TypeStrong/typedoc#1392]
## Search terms

interface inheritance implicit declaration

## Expected Behavior

Implicitly declared properties of interfaces (eg. `interface U extends Omit<{ a: T; b: T; }, 'a'> {}`) should be documented, or at least have a way to be documented.
## Actual Behavior

These properties aren't shown anywhere, and to my knowledge, there's no other way to document them.
## Steps to reproduce the bug

Reproducible code:
```ts
interface T extends Omit<{ a: string; b: string }, 'a'> {}

// explicitly declared properties are documented, but this class implicitly inherits 'b' from the above declared interface, yet there is no way to document that to my knowledge
class T {
    /**
     * A string.
     */
    public c: string;
    constructor() {
        this.b = '';
        this.c = '';
    }
}
```
Dependencies: typedoc@0.19.2
tsconfig.json: default (generated by `tsc --init`)
Generation command: `tsdoc --out docs src`

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 3.9.2
-   Node.js version: v14.3.0
-   OS: Win 10

**Comment by Gerrit0** [comment]
![image](https://user-images.githubusercontent.com/19329837/100279572-0e4a2380-2f24-11eb-8dd5-77600b7df389.png)

v0.20.0-beta.9 fixes this :)
