### ISSUE TITLE
Handling class property with object literal type and default value 

### ISSUE THREAD

**Issue by csempesz** [TypeStrong/typedoc#1393]
## Search terms

property object literal missing sub-properties

## Expected Behavior

If I declare a class property inlining the type as an object literal with its own properties, typedoc should generate a "property" kind object with "reflection" type listing all the sub-properties as "children" of the type independent if the class property is initialized with a default value or not.

## Actual Behavior

If the class property has a default value (ie the property Node has an initializer), typedoc will generate children based on the default value. In other words, if I have 

class Props {
  propA?: {
     propA1?: number;
     propA2?: string;
  } = {propA1: 2}
}
typedoc will generate (output is json) an object for propA as "kindString": "Object literal" but "children" will only contain one "Variable" kind object, for propA1. There is no child object generated for propA2.
If however, I remove the default value assignment, the propA object will be of kind "Property" and the type will be of "reflection" type and "children" will list properly propA1 and propA2

## Steps to reproduce the bug
Copy and paste the below snippet into a ts file and run typedoc:
class Props{
  propWithNoDefault?: {
    fetchSize?: number;
    maxCount?: number;
    scroller?: Element | null;
  };
  
  propWithDefaults?: {
    y?: number;
    offsetY?: number;
  } = { y: 0 };
}

I have this section in my tsconfig:
"typedocOptions":{
    "mode": "file",
    "excludeExternals": true,
    "excludeNotExported": true,
    "excludePrivate": true
  }
## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.0.2
-   Node.js version: 10.19.0
-   OS: Windows 10

**Comment by csempesz** [comment]
Spelunking the src code a bit to understand what is going on it seems to me (without claiming that my understanding of the code path is deep enough) that the fix should concentrate on this block in src/lib/converter/node/varable.ts
`        context.withScope(variable, () => {
            if ('initializer' in node && node.initializer) {
                switch (node.initializer.kind) {
                    case ts.SyntaxKind.ArrowFunction:
                    case ts.SyntaxKind.FunctionExpression:
                        variable!.kind = scope.kind & ReflectionKind.ClassOrInterface ? ReflectionKind.Method : ReflectionKind.Function;
                        this.owner.convertNode(context, node.initializer);
                        break;
                    case ts.SyntaxKind.ObjectLiteralExpression:
                        if (!this.isSimpleObjectLiteral(<ts.ObjectLiteralExpression> node.initializer)) {
                            variable!.kind = ReflectionKind.ObjectLiteral;
                            variable!.type = new IntrinsicType('object');
                            this.owner.convertNode(context, node.initializer);
                        }
                        break;
                    default:
                        variable!.defaultValue = convertDefaultValue(node as ts.VariableDeclaration);
                }
            }

            if (variable!.kind === kind || variable!.kind === ReflectionKind.Event) {
                if (isBindingPattern) {
                    variable!.type = this.owner.convertType(context, node.name);
                } else {
                    variable!.type = this.owner.convertType(context, (node as ts.VariableDeclaration).type, context.getTypeAtLocation(node));
                }
            }
        });`

**Comment by Gerrit0** [comment]
This is fixed in typedoc@0.20.0-beta.11. I believe your initial assessment was correct, the old converter did bad things with trying to get types from non-type nodes...

![image](https://user-images.githubusercontent.com/19329837/100282200-6d119c00-2f28-11eb-8b7b-2156b91ee9de.png)

**Comment by csempesz** [comment]
Thanks for looking into this. I installed the latest beta (24) however it seems as if the "mode=modules" is not recognized anymore?
This is my typedoc options setting in tsconfig.json:
 "typedocOptions":{
    "mode": "modules",
    "excludePrivate": true,
    "excludeExternals": true
  },
I have a utility program that consumes the json output of typedoc and the utility is centered on "modules". Are "modules" still supported? If yes, what is the correct "mode" setting to get them working again?

**Comment by Gerrit0** [comment]
Version 0.20 removed the --mode option because:
1. `file` mode was a lie - it worked around the lack of a true library mode
2. `modules` mode is a specific case of library mode

You can get nearly identical results by just removing the `mode` option and giving TypeDoc the directory containing all your source files as the `entryPoints` option.

**Comment by csempesz** [comment]
I see and thanks for the prompt reply. I'm using the API from Node so here are my few lines of code that I've been using so far. With the latest changes, I get an **empty json** file though.
```
const app = new TypeDoc.Application();

    // TypeDoc will load tsconfig.json
    app.options.addReader(new TypeDoc.TSConfigReader());
    app.bootstrap({"tsconfig": "<path-to-tsconfig.json>"});

    const project = app.convert();
    if (project) {
        const outDir = grunt.template.process('<%= dirs.typedoc_out%>');
        const outFile = `${outDir}/typedoc.json`;
        // Generate JSON output
        app.generateJson(project, outFile);
    }
```
the typedoc config is pretty simple:
"typedocOptions":{
    "excludePrivate": true,
    "excludeExternals": true,
    "entryPoints":["<my-project-root-folder>"
    ],
    "exclude":"<my-project-root-folder>/**/*.ts"
  },

**Comment by Gerrit0** [comment]
app.generateJson returns a promise now - the process is likely exiting before the result is written to a file.

**Comment by csempesz** [comment]
Yep, that was it. I can generate now the json file however, the new code is producing a different output. Consider the following use-case (content of a file lets say mymodule.tsx):
```
import ..... from 'SomeBaseClass'
class Props {
  prop1: string,
  ...
}
type State = {
  active?: boolean;
  focus?: boolean;
};

type ActionDetail = {
  originalEvent: Event;
};
<...maybe some other types or interfaces...>
export class MyModule extends SomeBaseClass<Props, State>{
  constructor(props: Props{
  ...
  }
}
```
In v0.19 the json had MyModule, Props, State, ActionDetail, etc as children of the module defined by the file mymodule.tsx.
In 0.20 beta 24, the module will only have as children the class MyModule. Props, State, ActionDetail are gone.

**Comment by Gerrit0** [comment]
That's expected. TypeDoc now documents what you export - if you don't export it, it is an implementation detail.

**Comment by csempesz** [comment]
I finally upgraded to 0.20 ( I was using a forked 0.19 until now but I had to upgrade) and just run the sample code I provided in the original description but to my surprise, the default value for the "propWithDefaults" property is now "..." (three dots).
Attached is the json output of the result:
[typedoc.zip](https://github.com/TypeStrong/typedoc/files/6098473/typedoc.zip)

**Comment by Gerrit0** [comment]
Yeah... that change was made because of #1288. Including initializers which aren't "simple" produced extraordinarily bad results in some cases. I'm open to tweaking that definition. It's defined here: https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/convert-expression.ts

**Comment by csempesz** [comment]
Hi, thanks for the prompt reply. Looking at convert-expression.ts do you see a reason why would ts.SyntaxKind.ObjectLiteralExpression not be part of the switch case in convertExpression() for which the code would return the initializer expression?

**Comment by Gerrit0** [comment]
That would probably require more of a complicated definition than I want... if we allowed all object literals, something like this would be ugly:
```ts
const x = { a: true, /** docs */ b: 1, c: () => someCall() }
```

You can pretty easily override this anyways with a plugin:

```ts
const { Converter, TypeScript } = require("typedoc")

exports.load = function({ application }) {
        /** @type {Map<Reflection, string>} */
        const defaultValues = new Map();

        const printer = TypeScript.createPrinter({ removeComments: true, omitTrailingSemicolon: true });

        application.converter.on(Converter.EVENT_CREATE_DECLARATION, (_context, reflection, node) => {
                if (!node || !node.initializer) return;

                if (node.initializer.kind === TypeScript.SyntaxKind.ObjectLiteralExpression) {
                        // Unfortunately can't just set defaultValue right here, this happens before TD sets it.
                        defaultValues.set(reflection, printer.printNode(TypeScript.EmitHint.Expression, node.initializer, node.getSourceFile()));
                }
        });

        application.converter.on(Converter.EVENT_RESOLVE_BEGIN, () => {
                for (const [refl, init] of defaultValues) {
                        refl.defaultValue = init;
                }
                defaultValues.clear();
        });
}
```
