### ISSUE TITLE
Disable email address escaping with HTML character references

### ISSUE THREAD

**Issue by jens-duttke** [TypeStrong/typedoc#1395]
## Search Terms

Markedjs, Marked, email, mangle

## Problem

Autolinked email addresses in the generated files are escaped with HTML character references.
On every run of TypeDoc, the escape sequence is randomly generated.
The result is, that the generated HTML files differ from the previous version, even if the meaningful content doesn't change. A version management system detects that as change then.

## Suggested Solution

There should be a way to disable atleast the `mangle` option of Marked (see https://marked.js.org/using_advanced).

Even better, if all Marked options would be configurable in the `typedoc.json` like:
```
"markedOptions": {
  "mangle": false
}
```

**Comment by Gerrit0** [comment]
I like the idea of supporting all marked options through `markedOptions` - and also turning off mangle by default. TypeDoc's output should be deterministic.

This should be a relatively easy change:
- Add `markedOptions: unknown` to [`TypeDocOptionMap`](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/declaration.ts#L49)
- Add the option in [`addTypeDocOptions`](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/sources/typedoc.ts)
- Update [options.md](https://github.com/TypeStrong/typedoc-site/blob/gh-pages/_guides/options.md) to document the new option

**Comment by krisztianb** [comment]
I can do this next if nobody is already working on this.
