### ISSUE TITLE
Using @ignore now renders empty ignore block

### ISSUE THREAD

**Issue by tanepiper** [TypeStrong/typedoc#1396]
## Search terms

ignore, rendering

## Expected Behavior

In a barrel file for Typescript, using the @ignore tag should ignore the file completly

## Actual Behavior

In the rendered documentation an empty 'ignore' block is rendered

## Steps to reproduce the bug

Example Barrel: https://github.com/tanepiper/rxjs-primitives/blob/master/libs/rxjs/array/src/index.ts
Typedoc config: https://github.com/tanepiper/rxjs-primitives/blob/master/typedoc.json

Run typedoc, generate output to docs: https://tanepiper.github.io/rxjs-primitives/modules/array.html

<img width="1130" alt="Screenshot 2020-11-19 at 21 44 55" src="https://user-images.githubusercontent.com/376930/99722373-e0428a80-2ab0-11eb-893a-30870bbcafd7.png">

## Environment

-   Typedoc version: 0.19.2, typedoc-plugin-external-module-name: 4.0.3
-   TypeScript version: 4.05
-   Node.js version: 13.14.0
-   OS: OSX 10.15.7

**Comment by Gerrit0** [comment]
Fixed in 0.20.0-beta.11 (though likely not quite in the way you expect, library based docs changes what it means to "ignore" a reflection somewhat), looks like you may have found a workaround in the meantime - nice looking docs! I like it better than TypeDoc's default theme.
