### ISSUE TITLE
Typedoc not working with Typescript 4.1

### ISSUE THREAD

**Issue by tanepiper** [TypeStrong/typedoc#1397]
## Search terms

Typescript

## Expected Behavior

Upgrade to Typescript 4.1, run typedoc, get docs

## Actual Behavior

Upgrade to Typescript 4.1, run typedoc, 

`Error: Tried to set an option (pathsBasePath) that was not declared.`

## Steps to reproduce the bug

Update to Typescript 4.1
Run existing Typedoc configuration

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.1.2
-   Node.js version: 13.14.0
-   OS: OSX 10.15.7

**Comment by Gerrit0** [comment]
If you install `typedoc@beta`, which is being tracked in #1364, you will receive a warning about an unsupported version, but it seems to work properly.

Before updating the supported versions, I need to go through and add support for new TS features. Mapped types have received a major upgrade... will hopefully be able to get to it this weekend.

**Comment by Gerrit0** [comment]
Just released v0.20.0-beta.14, (`npm i typedoc@beta`) which has full support for TS 4.1. I don't plan on backporting support to v0.19, but if someone wants it, https://github.com/TypeStrong/typedoc/commit/a32c9766c486b4c66d6399353cd56801724851dd and https://github.com/TypeStrong/typedoc-default-themes/commit/08045f0991e8bec159fb64f4961c8a8063a1af20 + https://github.com/TypeStrong/typedoc-default-themes/commit/f70a9b125dd3d59d80ef49af431e436bec369aa6has the relevant changes, and I would accept + release a PR.

![image](https://user-images.githubusercontent.com/19329837/100311612-7c670880-2f6d-11eb-822a-745a4612e08f.png)

**Comment by tanepiper** [comment]
@Gerrit0 Thanks for your work on this!  Having a look at the two PRs, this one comes up as a 404? https://github.com/TypeStrong/typedoc-default-themes/commit/f70a9b125dd3d59d80ef49af431e436bec369aa6has

I'll look to add the migration to my custom theme

**Comment by Gerrit0** [comment]
Sorry about that! I missed a space, so there was an extra "has" at the end of the hash. https://github.com/TypeStrong/typedoc-default-themes/commit/f70a9b125dd3d59d80ef49af431e436bec369aa6
