### ISSUE TITLE
failed to handle multiple layers of Nested Function Parameters Destructure

### ISSUE THREAD

**Issue by TechQuery** [TypeStrong/typedoc#1401]
## Expected Behavior

```TypeScript
class View {
    handleTouchStart = ({ touches: [{ pageX: x, pageY: y }] }: TouchEvent) => {
        // do something...
    }
}
```

## Actual Behavior

> \node_modules\typedoc\dist\lib\converter\types\reference.js:22
>        return !!(type.flags & ts.TypeFlags.Object);
>                       ^
> TypeError: Cannot read property 'flags' of undefined
>     at ReferenceConverter.supportsNode (\node_modules\typedoc\dist\lib\converter\types\reference.js:22:24)
>     at Converter.convertType (\node_modules\typedoc\dist\lib\converter\converter.js:126:31)
>     at \node_modules\typedoc\dist\lib\converter\converter.js:142:36
>     at Array.forEach (<anonymous>)
>     at Converter.convertTypes (\node_modules\typedoc\dist\lib\converter\converter.js:141:29)
>     at BindingArrayConverter.convertNode (\node_modules\typedoc\dist\lib\converter\types\binding-array.js:18:34)
>     at Converter.convertType (\node_modules\typedoc\dist\lib\converter\converter.js:127:38)
>     at \node_modules\typedoc\dist\lib\converter\nodes\variable.js:99:48
>     at Context.withScope (\node_modules\typedoc\dist\lib\converter\context.js:109:9)      
>     at VariableConverter.convert (\node_modules\typedoc\dist\lib\converter\nodes\variable.js:78:17)

## Steps to reproduce the bug

If rewrite the code above to the below, everything is OK:

```diff
class View {
-    handleTouchStart = ({ touches: [{ pageX: x, pageY: y }] }: TouchEvent) => {
+    handleTouchStart = ({ touches: [touch] }: TouchEvent) => {
        // do something...
    }
}
```

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.1.2
-   Node.js version: 14.15.0
-   OS: Windows 10 (2004)

**Comment by Gerrit0** [comment]
This works correctly in typedoc@beta

![image](https://user-images.githubusercontent.com/19329837/100279158-3b4a0680-2f23-11eb-8e6d-ee17d5f39c31.png)

**Comment by TechQuery** [comment]
@Gerrit0 Same error at `0.20.1` for the code below:
![image](https://user-images.githubusercontent.com/19969570/103265707-2dd3e080-49e9-11eb-8e76-2a330a47fc03.png)

My configuration:
```JSON
{
    "typedocOptions": {
        "name": "BootCell",
        "excludeExternals": true,
        "readme": "./ReadMe.md",
        "out": "docs/"
    }
}
```
