### ISSUE TITLE
Broken @param tags on classes

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1402]
Thanks for your work on this @Gerrit0, it has been amazing.

I tried the new beta, and wanted to share some feedback, tought it might be useful to you.

The ex-library mode now works perfectly! There are no issues between module/classes.

There is only one issue I haven't been able to fix.

There is a class with a list of parameters, which apparently are in [correct JSDoc format](https://jsdoc.app/tags-param.html),

<img src="https://user-images.githubusercontent.com/7217420/99369222-73669f00-28bc-11eb-84ca-c98dca27d008.png" width="500" />

that aren't being shown in the class Typedoc page.

<img src="https://user-images.githubusercontent.com/7217420/99369525-d22c1880-28bc-11eb-959a-816fef5d1dee.png" width="800" />

Any of your input on this would be greatly appreciated, maybe I'm doing something wrong?

The PR with the beta is here https://github.com/pmndrs/cannon-es/pull/54

_Originally posted by @marcofugaro in https://github.com/TypeStrong/typedoc/issues/1364#issuecomment-728795449_

**Comment by Gerrit0** [comment]
Pulling this into its own issue to make it easier to track. There are a couple things here:

1. The `@param` tags don't really do anything... TypeDoc knows what properties your class is, and what types those properties are by asking TypeScript. It also knows that this is a class because TypeScript knows it is a class so `@class` isn't needed. The same goes for `@constructor`. All you really need for that class's comment is:

    ```ts
    /**
     * Base class for all body types.
     * @example
     *     const body = new Body({
     *         mass: 1
     *     });
     *     const shape = new Sphere(1);
     *     body.addShape(shape);
     *     world.addBody(body);
     */
    export class Body extends EventTarget {
    ```

2. TypeDoc's comment format isn't exactly JSDoc... or TSDoc... or anything. It's a custom thing, so what you find on other documentation systems might not always hold (though we're slowly getting closer to TSDoc)... with that in mind, right now TypeDoc will check `@param` tags on classes for type parameters, so if your class is generic you could use `@param` to describe those.

**Comment by marcofugaro** [comment]
> right now TypeDoc will check @param tags on classes for type parameters, so if your class is generic you could use @param to describe those.

Hmm true, I guess I could use the type `BodyOptions` to document the params:

<img src="https://user-images.githubusercontent.com/7217420/101191999-b6fe2e80-365a-11eb-9b89-1edebf76a15f.png" width="47%"  />

_`src/objects/Body.ts`_

<img src="https://user-images.githubusercontent.com/7217420/101193004-34766e80-365c-11eb-99b9-185401972298.png" width="47%" />

However it's in the `Type aliases` section of the homepage, it's not really useful there. Is there any way I can make it stay in the `Body` page, the page where it's exported from in the code?

Somethings like this, a `Types` section in the class page, right after index

![](https://user-images.githubusercontent.com/7217420/101192966-24f72580-365c-11eb-9ee3-604ca8989a7e.png)

How do I do this? I am trying to achieve a similar page structure to the old JSDoc documentation http://schteppe.github.io/cannon.js/docs/

**Comment by Gerrit0** [comment]
There's not really a good way to do that.. and I'm not sure what the architecture would look like for enabling it. If you inline a type, TypeDoc will too, because it trusts your judgement that it is simple enough to be described there. Once you create a name for a type though, it makes more sense to TypeDoc to point uses of that type to the dedicated documentation. So... you could do this, though I'd probably live with the extra click to see the interface.

```ts
export class Body {
  constructor(options: { allowSleep?: boolean ... })
```

If you go this route, you could then use this to avoid duplication:
```ts
export type BodyOptions = ConstructorParameters<typeof Body>[0]
```
