### ISSUE TITLE
Add New Option hiddenCategories

### ISSUE THREAD

**Issue by tobiasschweizer** [TypeStrong/typedoc#1407]
## Search Terms

Category, `@category`, hide, internal,

## Problem

I would like to have an additional option to hide certain categories.

There is an existing `typedoc` option `--stripInternal` based on the tag `@internal`. 
But this is not very flexible and it is actually based on a [TypeScript compiler option](https://www.typescriptlang.org/tsconfig#stripInternal) which causes declarations not to emit:

>  This is an internal compiler option; use at your own risk, because the compiler does not check that the result is valid.

## Suggested Solution

I suggest adding a new `typedoc` option `hiddenCategories` which takes a list of categories as an input and ignores those when building the docs. 

Without touching the source, different docs could be built for different purposes. For example, you could build docs that only cover classes that are directly used by your users, and more extensive docs for active maintainers of your project.

**Comment by Gerrit0** [comment]
This is a fairly simple change:
- In [utils/options/declaration.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/declaration.ts#L48) add the option to the `TypeDocOptionMap` interface
- In [utils/options/sources/typedoc.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/sources/typedoc.ts) declare the option
- In [converter/plugins/CategoryPlugin.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/plugins/CategoryPlugin.ts) check the option and use `project.removeReflection` to remove hidden reflections.

**Comment by tobiasschweizer** [comment]
@Gerrit0 Ok, I can give it a try. I will fork the repo and try to submit a PR. 
If I struggle, I will let you know.

**Comment by neto626roman** [comment]
> ## Search Terms
> Category, `@category`, hide, internal,
> 
> ## Problem
> I would like to have an additional option to hide certain categories.
> 
> There is an existing `typedoc` option `--stripInternal` based on the tag `@internal`.
> But this is not very flexible and it is actually based on a [TypeScript compiler option](https://www.typescriptlang.org/tsconfig#stripInternal) which causes declarations not to emit:
> 
> > This is an internal compiler option; use at your own risk, because the compiler does not check that the result is valid.
> 
> ## Suggested Solution
> I suggest adding a new `typedoc` option `hiddenCategories` which takes a list of categories as an input and ignores those when building the docs.
> 
> Without touching the source, different docs could be built for different purposes. For example, you could build docs that only cover classes that are directly used by your users, and more extensive docs for active maintainers of your project.I?IMPORT TO neto626roman@gmail.com

**Comment by tobiasschweizer** [comment]
I am not working on this anymore ...
