### ISSUE TITLE
prettier-plugin?

### ISSUE THREAD

**Issue by runarberg** [TypeStrong/typedoc#1409]
I recently stumbled upon a [prettier plugin for jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc) and I’m quite impressed. However there are some compatibility issues with typedoc. Most notable is the `@example` block does not use fences (fails at parsing) so the output examples won’t be displayed as code. If—on the other hand—you write your examples without the block, the plugin will ruin your indents.

I was wondering is there any effort into creating a prettier plugin for typedoc comments? (or—better yet—does one exist already)?

If not, is there an interest in creating one?

**Comment by Gerrit0** [comment]
As far as I know, there hasn't been any effort in creating something like this. I don't plan on working on anything like this - TypeDoc is also moving towards being (mostly) conformant to [TSDoc](https://github.com/microsoft/tsdoc), so any formatting attempt would likely be better spent there.
