### ISSUE TITLE
@param names are not rendered

### ISSUE THREAD

**Issue by mk010101** [TypeStrong/typedoc#1410]
## Search terms
@param hyphen

## Expected Behavior
The name of the param should be visible next to the 'param' field. The @param block is followed by a parameter name and then a hyphen.

## Actual Behavior
The generated document omits the actual param names and just lists the description.
<img width="385" alt="Screen Shot 2020-12-04 at 13 53 11" src="https://user-images.githubusercontent.com/24923195/101174027-3aa82300-363b-11eb-87de-10cb1b0fa033.png">

## Steps to reproduce the bug

```typescript
/**
 * @param side1 - First (face) side
 * @param side2 - Second side
 * @param dir - Direction of rotation. @default 'true'
 */
interface FlipOptions  {
    side1: HTMLElement;
    side2: HTMLElement;
    dir?: -1 | 1;
    singleDir?: boolean;
    vertical?: boolean;
    lockPointer?: boolean;
}
```

## Environment

-   Typedoc version: 0.20.0-beta.24
-   TypeScript version: 4.1.2
-   Node.js version: 12.7.0
-   OS: OSX

**Comment by Gerrit0** [comment]
This is due to the template partial for comment tags - it you to use `@param` tags for what they are meant to be used for, not for documenting properties. I'd accept a PR that rendered the name if present 

https://github.com/TypeStrong/typedoc-default-themes/blob/7754c7df1d9280da3e90e4b500737484f979245f/src/default/partials/comment.hbs#L14-L17

**Comment by mk010101** [comment]
This is the output of the same from https://microsoft.github.io/tsdoc 
<img width="942" alt="Screen Shot 2020-12-05 at 23 29 33" src="https://user-images.githubusercontent.com/24923195/101267567-f65b7680-3751-11eb-8fee-726afce47905.png">

As you can see, it works correctly.

**Comment by Gerrit0** [comment]
TSDoc != TypeDoc. TypeDoc doesn't currently conform to the TSDoc standard, though support for it is planned.

That demo is particularly misleading because it doesn't parse the source code - it only grabs a comment and then renders it. I suspect that if you ran that code through api-extractor, it would complain about your use of `@param`

**Comment by justinwilaby** [comment]
This defect also applies to the TypeScript binding syntax for member functions:
```ts
class MyClass {
/**
* Function that does stuff
* 
* @param param1 - The first param
* @param param2 - The second param
*/
protected boundFunction = (param1: string, param2: number): void {}
```
Is there another way to document this syntax?

**Comment by Gerrit0** [comment]
I'm not sure what you mean there. This seems to work as expected.

![image](https://user-images.githubusercontent.com/19329837/112414482-bf50a700-8ce7-11eb-9ed3-9f007e856370.png)

If you aren't seeing this, please open a new issue.

**Comment by cefn** [comment]
I encounter what I think is the same problem in the context of a function type definition. 

```typescript
/**
 * @param a The first number
 * @param b The second number
 */
export type MyFun = (a: number, b: number) => void;
```

...gets rendered like...
 
![image](https://user-images.githubusercontent.com/159819/121352197-83130700-c924-11eb-8e61-65d3488326e7.png)

Note the elements inlined in the comment which are marked `param` and have lost the `a` and `b` names.

I am invoking the build command with no arguments...

```
npx typedoc --watch --out docs ./src/index.ts 
```

**Comment by Gerrit0** [comment]
That's a different bug - #799.

**Comment by cefn** [comment]
Thanks for your attention @Gerrit0 I've subscribed to that one.

**Comment by Gerrit0** [comment]
v0.22.x, I'm not too happy with this... but if you are seeing param tags rendered, you are likely using them in an unsupported way in the first place, so will leave it at this.

![image](https://user-images.githubusercontent.com/19329837/132145408-94e0c71a-c54b-4d8d-94e1-237eb9dbdd9c.png)
