### ISSUE TITLE
How to create conditional codeblocks, or use variables inside codeblocks

### ISSUE THREAD

**Issue by hanastasov** [TypeStrong/typedoc#1418]
## Search terms

codeblocks conditionals variables

## Steps to reproduce the bug

1. Create a base class and two class extending it:

```
export class Person {
/**
 * How to place different examples here, so that Typedoc will generate a string uing the corresponding `htmlTag` property ?
 */
function doSomething(): string;
}
export class Parent extends Person {
  public htmlTag = "<parent>";
}
export class Child extends Person {
 public htmlTag ="<child>";
}
```

2. How to make Typedoc to generate a string using the corresponding `htmlTag` property, when documenting the `doSomething` ?
-->

**Comment by Gerrit0** [comment]
There's no built in way to do this... TypeDoc will take what you give it for comments.

You can override the comment fairly easily by simply duplicating the property/method declaration with a new comment. I'm not sure it makes sense for typedoc to do more than this.... you could write a plugin to do more, including this context-sensitive replacement, but as a builtin solution, it seems rather dangerous.
