### ISSUE TITLE
"Only exported" control doesn't seem to do anything

### ISSUE THREAD

**Issue by kaiyoma** [TypeStrong/typedoc#1419]
## Search terms

only exported exports

## Expected Behavior

The control should work.

## Actual Behavior

The control doesn't do anything.

## Steps to reproduce the bug

I have a pretty simple interface defined in my code (notice that it's not exported):

```
interface Foo {
  value: number;
  unit: string;
}
```

The interface appears in the docs, but if I check the "Only exported" checkbox at the top of the page, the interface doesn't disappear. In fact, all the non-exported types, code, and data are still present on the page. Does this checkbox do anything?

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.1.2
-   Node.js version: 14.15.0
-   OS: Windows 10, Linux

**Comment by Gerrit0** [comment]
If a file has no exports, then it is a global file, and *every* declaration within it is implicitly exported. This is consistent with TypeScript's behavior. If you add `export {}` to the file, and check the "Only Exported" box, the interface disappears as expected.

**Comment by kaiyoma** [comment]
Unfortunately that's not the case here. I have exports in this file. Everything appears in the final docs, exported items and non-exported items alike. Clicking the checkbox does nothing.

**Comment by Gerrit0** [comment]
I'll need a reproduction showing that - I can't reproduce based on the info you've given.

**Comment by kaiyoma** [comment]
This file is enough to do it for me:

```
interface Foo {
  value: number;
  unit: string;
}

export function bar(): string {
  return 'baz';
}
```

Enabling "Only exported" does not cause `Foo` to disappear from the docs.

**Comment by Gerrit0** [comment]
I can't seem to reproduce this - I copied it into a new file, ran `typedoc src/gh1419.ts`, and opened the file in a browser.. the checkbox works as expected. If I run with `--excludeNotExported`, the interface is completely omitted from the docs as expected.

**Comment by kaiyoma** [comment]
Ah, I think I found the culprit: setting `mode: 'file'` causes this to happen. If I switch to `mode: 'modules'` then the checkbox starts working.

**Comment by Gerrit0** [comment]
Ah, yeah... that would do it. "file" mode tells typedoc to treat your files as globals - even if they aren't. It's a horrible thing that's going away in 0.20 (releasing in ~2 weeks)

**Comment by kaiyoma** [comment]
Okay good to know! I think I've gotten slipped up by this "file" mode on other occasions too, so I'm happy to hear that things will be clearer with the new version.
