### ISSUE TITLE
Mode lib: include indirected used type

### ISSUE THREAD

**Issue by euberdeveloper** [TypeStrong/typedoc#1420]
## Search Terms

lib mode

## Problem

I have an `index.ts` of  a library with this code:

```ts
export * from '@/types';
export * from '@/utils/logger';
```

Then I have a `@/types/index.ts` with this code:

```ts
export { Palette } from './palette';
export { Options } from './options';
```

Then I have a `@/types/options/index.ts` with this code:

```ts
import { DeepPartial } from 'ts-essentials';
import { Palette } from '../palette';

/**
 * The internal options of the logger.
 */
export interface InternalOptions {
    /**
     * The color palette that specifies which colour to use for the various log types.
     */
    palette: Palette;
    /**
     * If the debug messages will be printed.
     */
    debug: boolean;
    /**
     * The scope of the logger, printed as {SCOPE} before the [TYPE] tag.
     */
    scope: string | null;
}

/**
 * The options of the logger.
 */
export type Options = DeepPartial<InternalOptions>;
```

You can see how I export the `Options` is exactly the `InternalOptions`, with the difference that every property is optional, ready ot be replaced with a default value if it misses. So when the user calls my exported function, he uses the `Options` type, then the function adds the default values that misses and obtains an `InternalOptions` used in all the rest of the code.

In my library I want to export only Options, because InternalOptions is used inside the library. The problem is that if I look in the generated site generated by typedoc, I see only:

![image](https://user-images.githubusercontent.com/33126163/102891216-17b0a800-445e-11eb-9cf5-8d0b0a3504b6.png)

Because InternalOptions is not exported. This way the user can not understand how the options is defined.

## Suggested Solution

There should be an option that if true makes typedoc consider the types that are not exported by a library but which the library types depends on, maybe marking them as "indirected" if not exported. In my case, InternalOptions should be defined even if not exported, so that a user can understand what `Options` is, maybe `InternalOptions` should also be marked as not exported or something to make the user understand that can not include it from the library.

**Comment by euberdeveloper** [comment]
I used the @next version of typedoc to run the docs generator

**Comment by Gerrit0** [comment]
This is a good idea, though potentially tricky to implement... it won't be in the initial 0.20 release, but it does seem like a natural extension of it.

**Comment by Gerrit0** [comment]
Thinking about this more... I'm not convinced this is a good idea.

1. The implementation is really tricky - we need to traverse all properties + types converted to see what's exported... then do that recursively until it doesn't discover anything new.
2. You should arguably be exporting everything else anyways. Users of your library shouldn't have to do `NonNullable<import("lib").Options["Palette"]>` to get the `Palette` type... TypeScript used to be much stricter about this, I kind of wish it still was.

**Comment by euberdeveloper** [comment]
The Palette is exported by index.ts, through @/types/index.ts. What I do not want to be exported is InternalOptions, because is the merge of the Options with the default ones that is used internally.

But I understand that it could be difficult to implement and that maybe it is not worth it because it could be useful only in rare cases

**Comment by Gerrit0** [comment]
I left this open for a while to see if I could come up with a good way of implementing this - and failed. The earlier assessment that necessary types should be exported still seems reasonable to me.
