### ISSUE TITLE
Missing documentation comment from curried exports

### ISSUE THREAD

**Issue by Pajn** [TypeStrong/typedoc#1421]
## Search terms

beta
missing documentation
missing doc comments

## Expected Behavior

With an export like this:

```ts
/**
 * Returns true if fn returns true for every item in the iterator
 *
 * Returns true if the iterator is empty
 *
 * ## Example
 * ```typescript
 * all(e => e > 1, [1, 2, 3]) // false
 * all(e => e > 0, [1, 2, 3]) // true
 * all(e => e > 1, [])        // true
 * ```
 */
export const all: {
  <T>(fn: (item: T) => boolean, iterator: IterableOrIterator<T>): boolean
  <T>(fn: (item: T) => boolean): (iterator: IterableOrIterator<T>) => boolean
} = curry2(function all<T>(
  fn: (item: T) => boolean,
  iterator: IterableOrIterator<T>,
): boolean {
  for (const item of asIterable(iterator)) {
    if (!fn(item)) {
      return false
    }
  }

  return true
})
```

typedoc should generate documentation that includes both the two signatures as well as the written documentation with the example.

## Actual Behavior

typedoc only generates documentation for the two signatures but the written documentation is missing.

## Environment

-   Typedoc version: 0.20.0-beta.27
-   TypeScript version: 4.1.3
-   Node.js version: 15.5.0
-   OS: Ubuntu 20.10

**Comment by Gerrit0** [comment]
Fixed in beta 29 - this was a tricky one...

![image](https://user-images.githubusercontent.com/19329837/103161020-5f566d00-4799-11eb-9b4a-ed71cfbc02e1.png)

**Comment by Pajn** [comment]
I tested version 0.20.0-beta.31 now. It works great. Thank you!
