### ISSUE TITLE
How to Merge namespace in difference Files?

### ISSUE THREAD

**Issue by arvinxx** [TypeStrong/typedoc#1424]
I have a files like this

![image](https://user-images.githubusercontent.com/28616219/103263869-ff9fd200-49e3-11eb-8299-624d2346b5d4.png)

All of them are start with 

```ts
declare namespace chromeExtension {
    // ...
}
```

when I use typedoc to generate docs, the result is below:

![image](https://user-images.githubusercontent.com/28616219/103263976-48f02180-49e4-11eb-927f-31529d2951a8.png)

![image](https://user-images.githubusercontent.com/28616219/103263942-2eb64380-49e4-11eb-84ea-eabd49fc216b.png)

How can I merge this namespace into one file ?

my typedoc version is 0.19.2 and use the `typedoc-plugin-external-module-map` plugin

**Comment by Gerrit0** [comment]
In 0.19, the way to do this is to use `--mode file`. In 0.20, I don't think there's a really good way to do this... you might be able to point tyepdoc at the index.d.ts file (assuming it `/// <reference />`s the other files)

**Comment by arvinxx** [comment]
> In 0.19, the way to do this is to use `--mode file`. In 0.20, I don't think there's a really good way to do this... you might be able to point typedoc at the index.d.ts file (assuming it `/// <reference />`s the other files)

Thanks, it work well! And I can use 0.19.2 by now. But I wonder in 0.20, is there anyway to handle this in some easy way? （I have the `/// <reference />` `index.d.ts` file）

**Comment by Gerrit0** [comment]
0.20.3 now works better with global files, you should be able to get good results with:

```bash
npx typedoc types/Manifest/index.d.ts
```

**Comment by arvinxx** [comment]
I update the typedoc version and try your command but failed.Is there something I has configured wrong?

my typedoc config file:

```js
const isProdSite = process.env.NODE_ENV === 'production';

module.exports = {
  name: 'umi-plugin-extensions',
  tsconfig: './tsconfig-typedoc.json',
  entryPoints: ['types/index.d.ts'],
  out: 'document/docs/api',
  exclude: ['**/node_modules/**'],
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  includeVersion: true,
  disableSources: true,
  readme: 'document/API.md',
  plugin: [
    'typedoc-plugin-markdown',
  ],
  hideBreadcrumbs: true,
  namedAnchors: true,
  hideProjectName: true,
  publicPath: isProdSite ? '/umi-plugin-extensions/api/' : '/api/',
};
```

**Comment by Gerrit0** [comment]
There have been some changes to the options API - https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0

typedoc-plugin-markdown will also need an update, 3.2.1 I believe

**Comment by arvinxx** [comment]
> There have been some changes to the option names - https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0
> 
> typedoc-plugin-markdown will also need an update, 3.2.1 I believe

yeah I have changed the config like entryPoints. And also update the markdown plugin version.

The Result I get is a modules.md files without modules I expect.

**Comment by arvinxx** [comment]
The types files are here https://github.com/arvinxx/umi-plugin-extensions/tree/master/types

**Comment by Gerrit0** [comment]
Ah, that's why, `///` references aren't really exports, so typedoc doesn't know to document their contents. If you add `declare namespace chromeManifest {}` (or equivalent for each namespace) in your entry point, then it will pick it up as a global declared in that file and document it.

**Comment by arvinxx** [comment]
a strange generate behavior, when use two entryPoints like below: 
```js
  entryPoints: [
    'types/chromeManifest/index.d.ts',
    'types/extensionsPlugin/index.d.ts',
  ],
```
the result is:
![image](https://user-images.githubusercontent.com/28616219/103330596-31c13a80-4a9d-11eb-90bb-42cbad3dd9b6.png)

Is there something wrong?

**Comment by Gerrit0** [comment]
Typedoc has special casing if there is only one entry point to avoid nesting the documentation within a module and directly including the module members within the project.

With two entry points, we can't do this since a user needs to be able to tell what module the exports are from... "global" modules aren't commonly used anymore.
