### ISSUE TITLE
Support for reading exports map to determine entrypoints

### ISSUE THREAD

**Issue by Vinnl** [TypeStrong/typedoc#1426]
## Search Terms

exports map, export map, package exports

## Problem

We're currently already listing all modules we export in the `exports` property in our package.json ([Node docs](https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_package_entry_points), [Webpack docs](https://webpack.js.org/guides/package-exports/)). It's great that [since v0.20.0](https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0), TypeDoc now allows you to just specify the entry points to your package, but that means we're keeping two lists of those entry points.

## Suggested Solution

Add an option to tell TypeDoc to look at the `exports` property in our package.json, and use the values in that object as the entry points. (And I suppose it could make sense to have it fall back to the `module` and then the `main` fields as well in case it's not present?)

**Comment by Gerrit0** [comment]
I want to wait on this until that field is out of "Experimental" stability for Node, seems like a good idea though!

**Comment by Gerrit0** [comment]
This is also tricky in that the "exports" likely don't match to exactly what we need to get... That map describes the output files, but typedoc really needs an equivalent one targeting the source directory containing TS. `outDir` could really mess with this...

**Comment by Vinnl** [comment]
Oh hmm, you're right... Duplication it is then, I'm afraid :/
