### ISSUE TITLE
Generating documentation to interfaces only

### ISSUE THREAD

**Issue by MatanBobi** [TypeStrong/typedoc#143]
Hey :)
Im trying to generate documentation to interfaces only and not to classes.
Is there an easy way to do this without going over each class and setting it as hidden?

Thanks alot for your great work

**Comment by sebastian-lenz** [comment]
Hi, nice to hear from you. With the current version of TypeDoc the easiest way would be by using a file pattern for exclusion (if your file structure allows that). Apart from that there is no filtering of the output available.

I've started working on the next version of TypeDoc and the way we are dealing with the models should change. Making them easier to manipulate we could add some kind of callback for you to filter the reflections. I'll keep this one in mind and give you a note if I find an easy solution to implement that one.
