### ISSUE TITLE
Typedoc 0.20.1: "Project" prefix on html output

### ISSUE THREAD

**Issue by euberdeveloper** [TypeStrong/typedoc#1431]
I think that the prefix "Project" should be overwritten by the option `--name`. In my case, if I put the option `--name mongoback`, I obtain:

![image](https://user-images.githubusercontent.com/33126163/103295141-a2ac1800-49f3-11eb-9ef4-7a6b85f6df4b.png)

But I would expect the "Project" prefix to be omitted. Maybe an additional option or something could be added.

**Comment by Gerrit0** [comment]
"Project" there is the kind of the node being printed - I agree it seems unnecessary. I'd be fine with adding some logic in the default theme to not print it if it is "Project"

https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/partials/header.hbs#L55
