### ISSUE TITLE
Markdown Code Highlight failed to parse Shell/Bash language

### ISSUE THREAD

**Issue by TechQuery** [TypeStrong/typedoc#1432]
## Expected Behavior

Parse **Shell/Bash** code blocks in Markdown with no error, like what `0.19.x` versions do.

## Actual Behavior

> Warning: Unsupported highlight language "shell" will not be highlighted
> Warning: Unsupported highlight language "bash" will not be highlighted
> Warning: Missing type converter for type: this
> Warning: Missing type converter for type: false

## Steps to reproduce the bug

- [`tsconfig.json`](https://github.com/EasyWebApp/BootCell/blob/aa089e9/tsconfig.json)
- [CI logs](https://github.com/EasyWebApp/BootCell/runs/1622391623#step:4:85)

## Environment

-   Typedoc version: 0.20.1
-   TypeScript version: 3.9.7
-   Node.js version: 14.15.0
-   OS: Windows 10 Pro 2004

**Comment by Gerrit0** [comment]
shell, sh, and bash will be mapped to the shellscript language in 0.20.2
true/false/this/null type converters - took me a while to see this... it's only a problem with old TS versions. Should also be fixed in 0.20.2.
