### ISSUE TITLE
excludeNotDocumented flag should work also on class properties/methods

### ISSUE THREAD

**Issue by marcofugaro** [TypeStrong/typedoc#1435]
## Search Terms

excludeNotDocumented class properties methods

## Problem

Currently, the `excludeNotDocumented` flags works only for source files. However it would be ideal if it would work also on class methods or properties. For example:

```js
/**
 * Example class
 */
export class Example {

  /**
   * Property that I want to document
   */
  property1: number

  property2: number 

}
```

I want `property1` to show up in Typedoc but not `property2`.

Usecase: `property2` needs to be public because I need to modify that property from within the library, but I don't want for that property to show up in the documentation.

## Suggested Solution

Make the flag `excludeNotDocumented` work for class properties/methods or expose a new flag.

**Comment by Gerrit0** [comment]
That's a bug - fixed in 0.20.4 now :)
