### ISSUE TITLE
Since v0.20: Type arguments are not used when extending a template class implementation

### ISSUE THREAD

**Issue by krisztianb** [TypeStrong/typedoc#1438]
## Search terms

template class, type arguments, type parameters, inheritance, extends

## Expected Behavior

When a class is extending a template class implementation (using type arguments) the type arguments should be used as types in the sub class.

## Actual Behavior

The sub class is rendered by TypeDoc with the type parameters instead of the type arguments. This was working fine back in version 0.19.2.

## Steps to reproduce the bug

Example module:

```typescript
export class TemplateTester<A, B = number> {
    public aaa: A;
    public bbb: B;
    public aOrb: A | B;
    public unionAB: string | A | Readonly<A | B>

    public BaseMethod(param1: A, param2: B): void {}
    public StaticMethodWithTypeParameters<A, B>(p1: A, p2: B): void {}
}

export class TemplateTesterSubClass2 extends TemplateTester<number> {
}
```

## Environment

-   Typedoc version: 0.20.5
-   TypeScript version: 4.1.3
-   Node.js version: 12.13.0
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Shoot... I thought I'd fixed this, I guess the fix only worked for methods. Fixed in 0.20.6, publishing shortly

**Comment by krisztianb** [comment]
Thanks for the quick fix. I'll check it out soon.

**Comment by krisztianb** [comment]
Looks better now. 👍  I still found a difference and created a new issue #1441 for it.
