### ISSUE TITLE
After migrating from 0.19.2 to 0.20.5 typedoc is throwing error 

### ISSUE THREAD

**Issue by hassanazharkhan** [TypeStrong/typedoc#1439]
Typedoc failed to generate documentation using 0.20.5 while it is working with 0.19.2

Error: 

![Screenshot 2021-01-01 at 9 01 33 AM](https://user-images.githubusercontent.com/57677979/103433255-23476000-4c10-11eb-9214-86b2549a6eb2.png)

## Environment

-   Typedoc version: 0.20.5
-   TypeScript version: 3.9.7
-   Node.js version: 14.5
-   OS: Mac/bigSur

**Comment by hassanazharkhan** [comment]
The same issue also exists in 0.20.6 which has just been tested

**Comment by Gerrit0** [comment]
I really wish I could reproduce it... fixing it isn't that difficult (0.20.7), but I played around for a while and wasn't able to get the issue to show up. Is there any chance you have seen this in an open source project that I could debug?

**Comment by Gerrit0** [comment]
Oh... I feel dumb now. The cause of this was the old TS version. `elements` was called `elementTypes` in 3.9.
I really need to set up a way for typedoc's tests to run on multiple TS versions to detect this sooner.
