### ISSUE TITLE
Using type declarations - Unable to locate entry point

### ISSUE THREAD

**Issue by benmccann** [TypeStrong/typedoc#1446]
## Description

I just sent a [PR to upgrade Chart.js to 0.20.9](https://github.com/chartjs/Chart.js/pull/8267)! :tada: 

Chart.js has been using JS Doc since the beginning, but more recently has added hand coded [type declarations](https://github.com/chartjs/Chart.js/tree/master/types). [You mentioned the other day that TypeDoc can use type declarations](https://github.com/TypeStrong/typedoc/issues/1266#issuecomment-751868964). I wanted to try this since I think it'd result in better typed docs (most of the types from the JS Doc end up as `any` and the type declarations are fairly fleshed out so should be better)

I set `"entryPoints": ["types/index.esm.d.ts"],` and got:
> Warning: Unable to locate entry point: types/index.esm.d.ts

I was wondering if you had any ideas if I might be doing something wrong

## Steps to reproduce

```
git clone https://github.com/benmccann/Chart.js
cd Chart.js
git checkout typedoc-upgrade
npm install
```

Change `typedocOptions` in `tsconfig.json` to:
```
  "typedocOptions": {
    "name": "Chart.js",
    "entryPoints": ["types/index.esm.d.ts"],
    "excludeExternals": true,
    "excludeNotExported": true,
    "includeVersion": true,
    "includes": "./types",
    "out": "./dist/docs/typedoc"
  },
```

Run `npx typedoc`

**Comment by Gerrit0** [comment]
It looks like these declaration files aren't included in the tsconfig's `include` option, making this change lets the docs generate:

```diff
diff --git a/tsconfig.json b/tsconfig.json
index c3f6ee1b..3da36225 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -12,7 +12,7 @@
   },
   "typedocOptions": {
     "name": "Chart.js",
-    "entryPoints": ["src/index.esm.js"],
+    "entryPoints": ["types/index.esm.d.ts"],
     "excludeExternals": true,
     "excludeNotExported": true,
     "includeVersion": true,
@@ -20,6 +20,7 @@
     "out": "./dist/docs/typedoc"
   },
   "include": [
-    "./src/**/*.js"
+    "./src/**/*.js",
+    "types"
   ]
 }
```

**Comment by benmccann** [comment]
Ah, thanks!!
