### ISSUE TITLE
0.20.10 Error: Tried to set an option (mode) that was not declared.

### ISSUE THREAD

**Issue by BryanHunt** [TypeStrong/typedoc#1447]
Renovate just updated several of my modules to typedoc 0.20.10 and they are all failing with:

Error: Tried to set an option (mode) that was not declared.

Reverting back to typedoc to 0.20.9 and the problem goes away.

**Comment by Gerrit0** [comment]
This is expected, these options were removed in 0.20, but prior to 0.20.10 the errors that they should have caused were not caught.

**Comment by krisztianb** [comment]
This is mentioned in the release notes here: https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0

> Removed options - mode, excludeNotExported, includeDeclarations, ignoreCompilerErrors, entryPoint

If I'm not mistaken then every documentation is now automatically generated in the new library mode.

**Comment by BryanHunt** [comment]
How do I not use mode when the only option I pass to typedoc is the src directory?

**Comment by Gerrit0** [comment]
The fix in 0.20.10 was for options declared in the tsconfig.json file, check for a `typedocOptions` key there

**Comment by BryanHunt** [comment]
Found it.  Thanks!
