### ISSUE TITLE
Is there any method to hide Index in interface files?

### ISSUE THREAD

**Issue by arvinxx** [TypeStrong/typedoc#1448]
A Case is here: [Case](https://arvinxx.github.io/umi-plugin-extensions/#/umi-plugin-extensions/api/interfaces/extensionsplugin-config)

In this case, I generate doc into markdown and the document framework dumi will generate document pages by markdown.

![image](https://user-images.githubusercontent.com/28616219/103485960-4010ad00-4e35-11eb-8383-d063c8e9cb76.png)

But by default typedoc will generate index.It will work well in most case. But in my case, it will be a noise because the dumi will show the toc direct by the header level.

So my question is there any way to hide this index in interface files?

**Comment by Gerrit0** [comment]
Given that you're using typedoc-plugin-markdown to create the markdown - this is probably a question for that plugin. The html generator doesn't have any flags to disable this, though a custom theme could disable it.

**Comment by Gerrit0** [comment]
Looks like you got an answer there
