### ISSUE TITLE
Extending a tuple with an optional member causes an error

### ISSUE THREAD

**Issue by eemeli** [TypeStrong/typedoc#1449]
## Search terms

tuple, optional, convertType

## Expected Behavior

Docs should be generated for valid code.

## Actual Behavior

Extending a tuple type that includes an optional member causes TypeDoc to exit with an unexpected error. This _might_ be related to #1439.

## Steps to reproduce the bug

Try to generate docs for this:

```ts
export function fails<T extends [foo: any, bar?: any]>(a: T): T {
  return a;
}
```

This causes an error `Cannot read property 'name' of undefined` to be thrown from here https://github.com/TypeStrong/typedoc/blob/0c3b1a0c4ea9168a0500ae13422f35935654df83/src/lib/converter/types.ts#L819
due to `elements` having a length that's one greater than the length of `namedMembers`.

Minimal reproduction: https://gist.github.com/eemeli/a860c474d8a8a221985aa3fc883baed0

## Environment

-   Typedoc version: 0.20.10
-   TypeScript version: 4.1.3
-   Node.js version: 14.9.0
-   OS: macOS Mojave 10.14.3

**Comment by Gerrit0** [comment]
Oh shoot.. this is another instance of #1408. TS does weird things with generic constraints. Fixed in 0.20.11
