### ISSUE TITLE
Private property shown as public method

### ISSUE THREAD

**Issue by arv** [TypeStrong/typedoc#1452]
## Search terms

private class property public method

## Expected Behavior

When generating docs it should not show private properties when `excludePrivate` is set to `true`.

## Actual Behavior

It fails to mark a private property as private. Instead it is listed as a public method

## Steps to reproduce the bug

Given code like this:

```ts
private _onStorage = (e: StorageEvent): void => {
```

https://github.com/arv/replicache-sdk-js/blob/147b0d932aa32f8066a9dcdeb78b601103e03ed6/src/replicache.ts#L223

On branch https://github.com/arv/replicache-sdk-js/tree/typedoc-0.20

You can repro this by running `npm run doc` and then `npx http-server docs` and checking out the generated documentation for the `default` export.

## Environment

-   Typedoc version: 0.20.11
-   TypeScript version: 4.1.3
-   Node.js version: v15.5.1
-   OS: macOS 11.1

**Comment by Gerrit0** [comment]
Fixed in 0.20.12, thanks for the report!
