### ISSUE TITLE
Typedoc produces incorrect documentation for equivalent type aliases

### ISSUE THREAD

**Issue by handerss-tibco** [TypeStrong/typedoc#1454]
Typedoc produces incorrect types in documentation when two type aliases are equivalent. 

**Example**

```
type Foo = string | number;
type Bar = string | number;

declare function bar(): Bar;
declare function foo(): Foo;
```

This source produces documentation where the return type of the function `foo` is `Bar`. I expected the return type to be `Foo`.

This issue is new in 0.20.

Here's a repo with a reproducible example and resulting docs:

https://github.com/handerss-tibco/typedoc-alias-issue

https://handerss-tibco.github.io/typedoc-alias-issue/modules.html#foo

**Comment by Gerrit0** [comment]
Thanks for the reproduction!

Unfortunately... this is unfixable in the generic case. Fixing this specific case isn't too bad (0.20.13), but we rely on the type checker for getting the type of symbols... and the type checker doesn't preserve this information. Types *may* have a single `aliasSymbol`, but which type gets this symbol, is determined by which alias is documented first...
