### ISSUE TITLE
VSCode intellisense while using typedoc

### ISSUE THREAD

**Issue by Artrix9095** [TypeStrong/typedoc#1458]
For some people trying to make a library natively in typescript, documentation is a must, and typedoc does it well. Typedoc is an excellent library and I'm looking forward to using it in my project. But I have 1 problem, As a former jsdoc user I enjoyed the Intellisense it provided inside vscode, it made it a lot easier, to quickly check read what something does, get descriptions for specific parameters, and check examples, all within my IDE. Having something similar inside typedoc would be amazing, especially if it was built into vscode like jsdoc.
But at least having an extension with snippets and syntax highlighting would be a good start, and then later making items like description, variable descriptions etc to it. I would be extremely happy if this was added.

**Comment by Gerrit0** [comment]
I'm curious - what would you want this to do that VSCode doesn't already do? The built in language support for jsdoc pretty much does all this, and the comments you've been using for jsdoc will (mostly) produce the same output for typedoc.

I don't see spending much time on this - my open source time is limited... and typedoc proper has plenty of issues to resolve still. Also, typedoc is slowly moving towards supporting the [tsdoc](https://tsdoc.org/) comment standard, so I suspect that effort in improving editor tooling would be better spent there.
