### ISSUE TITLE
BUG: Type Typo in Generated JSON

### ISSUE THREAD

**Issue by EisenbergEffect** [TypeStrong/typedoc#146]
Throughout the generated json we see this a lot: `"type": "instrinct"`. What is that? It seems like a typo. It would be great to see that fixed.

(PS - Aurelia.io is using TypeDoc on all it's libraries now..and we've also built a docs viewer on top of the TSDoc json format. :))

**Comment by sebastian-lenz** [comment]
Yes, this looks like a typo, should be <code>"intrinsic"</code> I guess. Sorry for my bad english.

**Comment by sebastian-lenz** [comment]
I'm unsure whether to fix that one in the current branch as it would break everyones code using the json export. v0.4 is in the making and I think it would be better to correct the typo with this new version.

**Comment by EisenbergEffect** [comment]
@sebastian-lenz Thanks for the update. Do you have any timeline on 0.4 or any feature roadmap on that. I'm just curios.
