### ISSUE TITLE
Question: How to set name of default export of a module?

### ISSUE THREAD

**Issue by renarsvilnis** [TypeStrong/typedoc#1460]
Hi,
sorry, couldn't find a better place to ask a question.

I have built a small npm that "export default" a class called `AppleSignIn`, in the generated docs the class is listed as "default" (which makes sense technically), but how can I instead rename it to `AppleSignIn` so it is clearer for readers what is that.

**Link to docs:** https://renarsvilnis.github.io/apple-sign-in-rest/classes/default.html
**Link to the source file:** https://github.com/renarsvilnis/apple-sign-in-rest/blob/master/src/AppleSignIn.ts
**Command I use to generate docs:**
```bash
npx typedoc --plugin none --theme minimal node_modules/typedoc-neo-theme/bin/default --out ./docs/ ./src/AppleSignIn.ts --readme none --gitRevision master
```

![image](https://user-images.githubusercontent.com/3515099/103878988-e8499e80-50df-11eb-87af-32d321bed8e7.png)

**Comment by Gerrit0** [comment]
Issues are great for questions - then other people can find them too!

There's no way to do this currently, and I don't really want to add one... using any other name is lying to your users. Default exports are bad! You could technically do this with a plugin...

A workaround that seems reasonable to me is to export a named export alongside the default export. TypeDoc will process exports in the same order as you declare them (mostly... works in this case), so the following will result in a class documented as `AppleSignIn` and a `default` export which is documented as an alias to that class.

```ts
class AppleSignIn {}
export { AppleSignIn }
export default AppleSignIn
```

<details><summary>If you really want to lie</summary>

```bash
npx typedoc --plugin ./rename-default.js src/index.ts
```

```js
exports.load = function({ application }) {
    application.converter.on("end", context => context.children.find(refl => refl.name === "default").name = "AppleSignIn");
};
```

</details>

**Comment by renarsvilnis** [comment]
@Gerrit0 Thanks for the help. Added export of the class and made the default one an alias, kept the default one for backward support.

```
export class AppleSignIn {}
export default AppleSignIn;
```

**Comment by JL102** [comment]
There's another way to do it, and it prevents the ugly name `default` from showing up on the page.

Example:
`src/control.ts`
```js
export default Control {}
```

`src/typedoc/control.ts`
```js
export {default as Control} from '../control';
```

and then you set `src/typedoc/control.ts` as your entry point.
