### ISSUE TITLE
Navigation menu stopped showing

### ISSUE THREAD

**Issue by vitaly-t** [TypeStrong/typedoc#1465]
Successfully upgraded to the very latest of everything:

* "typedoc": "0.20.14",
* "typescript": "4.1.3"

Now the navigation menu has disappeared from the generated documentation.

My `typedoc.json` file:

```json
{
  "name": "SUB-EVENTS v1.8",
  "readme": "README.md",
  "out": "docs",
  "theme": "minimal",
  "excludeExternals": true,
  "excludePrivate": true,
  "excludeNotDocumented": true,
  "disableOutputCheck": true,
  "exclude": [
    "./extras/**/*.ts",
    "./test/**/*.ts"
  ]
}
```

![image](https://user-images.githubusercontent.com/5108906/104393444-65d83900-553c-11eb-8cad-04c0a353e0b3.png)

P.S. It's a public library - [sub-events](https://github.com/vitaly-t/sub-events).

**Comment by Gerrit0** [comment]
Thanks for the repro! Not sure what went wrong here... will look into it Saturday at the lastest

**Comment by Gerrit0** [comment]
Looks like this was an issue with `excludeNotDocumented` - the check failed to resolve symbols before checking if they had documentation comments, so re-exports were seen as not documented.
