### ISSUE TITLE
Clicking on a search result does nothing

### ISSUE THREAD

**Issue by kaiyoma** [TypeStrong/typedoc#1466]
## Expected Behavior

Clicking on a search result should navigate to the appropriate page.

## Actual Behavior

Nothing happens. The search results close and no navigation is performed.

## Steps to reproduce the bug

Try it out on your own site: https://typedoc.org/api/

## Environment

-   Typedoc version: 0.20.13
-   TypeScript version: 4.1.3
-   Node.js version: 14.15.0
-   OS: Windows 10, Linux

**Comment by krisztianb** [comment]
I tired the following:

1. Click on the magnifier icon on top of the page to open up the search input field
2. Enter "Event"
3. First search result is "Event.prevenDefault"
4. Click on "Event.preventDefault"

Result:

I'm forwarded to the following page: https://typedoc.org/api/classes/event.html#preventdefault

Is this working for you differently?

**Comment by kaiyoma** [comment]
When I follow those steps, nothing happens. The search results close, but there's no navigation. I can repro this with any browser (Chrome, Edge, Firefox). I see this error popping up in the console periodically:

```
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by kaiyoma** [comment]
Here's a video showing the issue:

https://user-images.githubusercontent.com/10719780/104624479-7b3a8980-5648-11eb-8441-41e8e39d5c5d.mp4

**Comment by krisztianb** [comment]
Yes, I get the favicon 404 too. Unfortunately I can't reproduce this. If there is no error in the console, you might want to check out the "Network" tab and see if there are errors there.

**Comment by kaiyoma** [comment]
I don't see anything in the Network tab when clicking on a search result (and nothing in the console either). Should I see something?

**Comment by krisztianb** [comment]
Well, yes. When I click on the "Event.preventDefault" search result in the list, I get the following entry in the "Network" tab in Firefox:

Status: 304, Method: GET Host: typedoc.org File: event.html Initiator: document, Type: html

Just a wild guess: Maybe there is a caching issue? Have you tried emptying your browser cache? You can usually do this with the keyboard shortcut Ctrl + Shift + Del

**Comment by kaiyoma** [comment]
I've tried clearing the cache and it doesn't help. This problem shows up in incognito mode too.

**Comment by krisztianb** [comment]
Looking at the HTML and the search box each search result in the list is rendered as an `<a>` tag which directly links you to the right page. If you hover over the entries in the search result list, do you see the links being displayed in the status bar (bottom left corner of the window in Firefox)?

**Comment by kaiyoma** [comment]
Yes, I see the URL in the lower left corner, and it looks correct when I move the mouse cursor over the list of results. Is the code invoking `stopPropagation` or `preventDefault` on the click event?

**Comment by papb** [comment]
Hello, I have another guess, do you happen to be opening the file locally via `file:///some/path/to/that/file.html`?

If yes, can you please try with a local HTTP server instead? You can get one by `npm i -g http-server` and then `http-server -p 8888` for example.

**Comment by Gerrit0** [comment]
Well, talk about a confusing bug!

We don't call stopPropagation / preventDefault on a click - but there is another bit of suspicious code.

https://github.com/TypeStrong/typedoc-default-themes/blob/c34a61e990bc34a0d509880011e8b44da59b8d9f/src/default/assets/js/src/typedoc/components/Search.ts#L61-L64

I was able to reproduce this - sometimes... which is in favor of a race condition. I had most luck reproducing this on a touchscreen (for whatever reason...).

**Comment by kaiyoma** [comment]
> Hello, I have another guess, do you happen to be opening the file locally via `file:///some/path/to/that/file.html`?
> 
> If yes, can you please try with a local HTTP server instead? You can get one by `npm i -g http-server` and then `http-server -p 8888` for example.

No, I'm not opening the files locally. I'm using the deployed docs here: https://typedoc.org/api/

(I'm also testing with some doc pages that are deployed internally at my company.)

**Comment by Gerrit0** [comment]
I *believe* I've fixed this... https://typedoc.org/api/ has been updated. There are a couple other bugs I want to look at today before making a release

**Comment by kaiyoma** [comment]
> I _believe_ I've fixed this... https://typedoc.org/api/ has been updated. There are a couple other bugs I want to look at today before making a release

Oh nice, I believe it's fixed! I tested with all my browsers and incognito mode and now things appear to be working correctly.

**Comment by Gerrit0** [comment]
Awesome! That's great to hear. I'm working on publishing 0.20.15, which includes the fix right now.

**Comment by Gerrit0** [comment]
Publishing - https://github.com/TypeStrong/typedoc/actions/runs/490404791
