### ISSUE TITLE
stripInternal no longer recognized

### ISSUE THREAD

**Issue by dbartholomae** [TypeStrong/typedoc#1469]
## Search terms

stripInternal strip-internal

## Expected Behavior

Calling `typedoc` with `stripInternal` set in `typedoc.json` should build documentation.

## Actual Behavior

`Error: Tried to set an option (stripInternal) that was not declared.` and building fails

## Steps to reproduce the bug
You can see it in my open-source repo. Here's the config file:
https://github.com/dbartholomae/jsx-readme/blob/main/typedoc.json

This broke somewhere between 0.19.2 and 0.20.14.
With 0.19.2 the code worked:
https://github.com/dbartholomae/jsx-readme/runs/1713979422?check_suite_focus=true#step:11:6

But after updating to 0.20.14, it fails:
https://github.com/dbartholomae/jsx-readme/pull/62/checks?check_run_id=1713999146#step:11:6

## Environment

-   Typedoc version: 0.20.14
-   TypeScript version: 4.0.2
-   Node.js version: 12.20.1
-   OS: Ubuntu 18.04.5

**Comment by Gerrit0** [comment]
`stripInternal` is a TypeScript option (https://www.typescriptlang.org/tsconfig#stripInternal). In 0.20, TypeDoc dropped support for setting TypeScript options via TypeDoc config files.

However, given that it is marked as an internal option, it seems reasonable to me to add it as a TypeDoc option, and treat that option as on if either the compiler option or the TypeDoc option is on.

**Comment by dbartholomae** [comment]
Nice, I did not know that this is a TypeScript option. Will read up on it, from my side the issue could be closed then, but of course feel free to use it to track the idea to pass it through.

**Comment by Gerrit0** [comment]
0.20.15 includes `excludeInternal` (renamed to match the other exclude TypeDoc options). It will be set to true automatically if you set the TypeScript `stripInternal` option, or can be set explicitly.
