### ISSUE TITLE
Missing newlines in quick start shell script in Chrome 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [TypeStrong/typedoc#1471]
## Search terms

website quick start newline blank line code

## Expected Behavior

https://github.com/TypeStrong/typedoc-site/blob/aa53ab692a540a5f6bf375e1cdee79d0d1b7aafd/index.md includes blank lines between the commands to run.

## Actual Behavior

https://typedoc.org/#quick-start has lost those new lines.

## Steps to reproduce the bug

1. Visit typedoc.org
![Screenshot of missing blank lines in typedoc quick start](https://user-images.githubusercontent.com/3335181/104948104-c3301800-598a-11eb-8d07-d1d8bdb7e906.png)

## Environment

~N/A~ Edit: Brave (1.18.78; Chromium: 87.0.4280.141) and Chrome 87.0.4280.141 on Windows

**Comment by Gerrit0** [comment]
I can't seem to reproduce this... what browser are you using?

**Comment by JoshuaKGoldberg** [comment]
Brave and Chrome on Windows have this issue. Looks like Edge and Firefox do not.

**Comment by Gerrit0** [comment]
Very strange... Chrome is what I used to check. The lines are hard coded `<br>` tags, any chance you have a custom style enabled which prevents them from working?

https://github.com/TypeStrong/typedoc-site/blob/gh-pages/index.html#L61

**Comment by Gerrit0** [comment]
That looks like the br tags are missing entirely.. I can't reproduce this across several devices & browsers. Only thing that makes any kind of sense to me is a cached page (but afaik this was never that broken) or a user script removing them.

**Comment by JoshuaKGoldberg** [comment]
It's the weirdest thing -- this no longer repros for me either! I must have had a weird cache, or some behavior from messing with browser settings / extension locally. Sorry for the spam!

**Comment by Gerrit0** [comment]
Great to hear! Thanks for following up
