### ISSUE TITLE
Union arguments are unexpectedly expanded

### ISSUE THREAD

**Issue by arnog** [TypeStrong/typedoc#1472]
## Search terms

unions, arguments

```ts
type Union = "a" | "b";
class A {
 foo(a: Union) { /*...*/ }
}
```

## Expected Behavior

The reflections generated by Typedoc preserve the reference to the`Union` type: 
```ts
type Union = "a" | "b";
class A {
 foo(a: Union { /*...*/ }
}
```

## Actual Behavior

The reflections generated by Typedoc "expand" the union, and lose reference to the `Union` type: 
```ts
type Union = "a" | "b";
class A {
 foo(a: "a" | "b") { /*...*/ }
}
```

## Environment

-   Typedoc version: 0.20.16. This did not happen in 0.19.

In case that matters, I'm seeing this when using in the JSON output.

**Comment by Gerrit0** [comment]
This was caused by the switch in 0.20 to use the type checker more to get types - particularly to resolve method types with generic classes. I suspect TypeScript 4.2 will fix this - https://devblogs.microsoft.com/typescript/announcing-typescript-4-2-beta/#smarter-type-alias-preservation

**Comment by arnog** [comment]
Right, that makes sense...

**Comment by Gerrit0** [comment]
TypeScript 4.2 contained some changes which makes this specific case better. If you update your TS version, you should see that union types are better about preserving their names if they are aliased somewhere.
