### ISSUE TITLE
commonjs default export doesn't work

### ISSUE THREAD

**Issue by hugomrdias** [TypeStrong/typedoc#1476]
## Expected Behavior

commonjs default export could be merged with the named exports namespace and listed in the nav with some kinda of sign just to tell the users which are named and default. 

## Actual Behavior

commonjs default shows up has `export=` and any other types or exports are not resolved. Check example 1 below

## Steps to reproduce the bug

1. https://codesandbox.io/s/typedoc-test-w69ry?file=/src/index.js

2. https://codesandbox.io/s/typedoc-test-w69ry?file=/src/named.js

## Environment

-   Typedoc version: 0.20.16
-   TypeScript version: 4.1.3
-   Node.js version: 14
-   OS: all

**Comment by Gerrit0** [comment]
`module.exports =` isn't a default export. It's equivalent to TypeScripts `export =`.

Fixed with 4a539ddb3b17b53642b3981864ab3cd5a498d6fe

**Comment by Gerrit0** [comment]
Fix released in 0.20.17

**Comment by hugomrdias** [comment]
Thank you this is awesome!! Now I can change "export=" to whatever I want with a plug-in.
