### ISSUE TITLE
Twoslash plugin

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1479]
## Search Terms

twoslash, intellisense in docs

## Problem

The TypeScript site uses [`@typescript/twoslash`](https://www.npmjs.com/package/@typescript/twoslash) ([example](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#union-exhaustiveness-checking)), this makes it possible to display intellisense within the docs, which is potentially a really useful feature for some libraries.

## Suggested Solution

Implement a plugin which detects ` ```ts twoslash` and runs twoslash on the code block

**Comment by wojpawlik** [comment]
Why close?

**Comment by Gerrit0** [comment]
Because I don't have the time to do it - and keeping it open means that I see it every time I'm looking through issues for a newly opened bug.
