### ISSUE TITLE
Class Static methods seems broken

### ISSUE THREAD

**Issue by hugomrdias** [TypeStrong/typedoc#1481]
## Expected Behavior

Check the link below, static methods should output proper signatures, comments, etc.

## Actual Behavior
<img width="525" alt="Screenshot 2021-01-24 at 14 01 16" src="https://user-images.githubusercontent.com/314190/105632715-a2653800-5e4c-11eb-9891-8d751889867b.png">

Check the link below, only the ESM named export works properly.

## Steps to reproduce the bug

https://codesandbox.io/s/typedoc-test-w69ry?file=/src/index.js

## Environment

-   Typedoc version: 0.20.17
-   TypeScript version: 4.1.3
-   Node.js version: 14
-   OS: all

**Comment by Gerrit0** [comment]
Aww... this is going to be an annoying one to fix.

**Comment by Gerrit0** [comment]
Yep, as predicted... very annoying one. I really dislike how the compiler gives different results with JS files than TS files. Fixed in 0.20.18.

**Comment by hugomrdias** [comment]
Thank you
