### ISSUE TITLE
0.20.18 broke other kinds of commons js exports :/

### ISSUE THREAD

**Issue by hugomrdias** [TypeStrong/typedoc#1483]
## Expected Behavior

all exports should show up in the nav

## Actual Behavior

only the `module.exports` shows up in the nav

## Steps to reproduce the bug
I know you probably already tired of me : ) but the class static methods fix broke these types of exports

Check the repro both examples there are broken
https://codesandbox.io/s/typedoc-test-w69ry?file=/src/index.js

## Environment

-   Typedoc version: 0.20.18
-   TypeScript version: 4.1.3
-   Node.js version: 14
-   OS: all

**Comment by Gerrit0** [comment]
Ew.... JS is weird. :/ Why would anyone do this in an API designed in the past decade...

```js
// function + namespace export
function main() {}
main.export = () => {}

// class + static method
/** @class */
function main2() {}
main2.static = () => {}
```

Apparently TS lets you do this too, not forcing the use of a namespace... which is news to me. Going to be kind of tricky to fix... Saturday probably.
