### ISSUE TITLE
Props that are inherited from another component/library don't show up in the props table

### ISSUE THREAD

**Issue by kaiyoma** [TypeStrong/typedoc#1484]
## Expected Behavior

The inherited props should appear.

## Actual Behavior

The inherited props don't appear.

## Steps to reproduce the bug

For components that wrap other components - like a wrapper around a component from npm that adds some additional functionality - it's common to extend props. Here's an example of wrapping around `Col` from Ant Design:

```
import { ColProps } from 'antd/lib/col';

type ColSizeProps = Pick<ColProps, 'lg' | 'md' | 'sm' | 'xl' | 'xs' | 'xxl'>;

interface Props extends ColSizeProps, Pick<ColProps, 'onMouseEnter' | 'onMouseLeave'> {
  (extra props here)
}
```

In the props table in Storybook, only the extra props are appearing. The extended/inherited props are not showing up.

## Environment

-   Typedoc version: 0.20.16
-   TypeScript version: 4.1.3
-   Node.js version: 14.15.0
-   OS: Windows 10, Linux

**Comment by Dergash** [comment]
Helo kaiyoma! I was unable to reproduce this on 0.20.16 and 0.20.18: https://codesandbox.io/s/typedoc-test-forked-nh7fe?file=/src/index.ts

Could it be that you launch generation with [--excludeExternals](https://typedoc.org/guides/options/#excludeexternals) option? Or have `Externals` checkbox unchecked in API menu:

![extarnals2](https://user-images.githubusercontent.com/13132449/105918372-defb8400-6044-11eb-9975-ed20f925d38e.PNG)

With this checkbox checked properties seems to be inherited:

![externals1](https://user-images.githubusercontent.com/13132449/105918449-fdfa1600-6044-11eb-9dd1-36c8dbfceab6.PNG)

**Comment by kaiyoma** [comment]
Oh man, this is embarrassing, I filed this issue against the absolute wrong project. So sorry about that! typedoc is doing the right thing here. 😄
