### ISSUE TITLE
Using multiple plugins in tsconfig.json

### ISSUE THREAD

**Issue by Milo123459** [TypeStrong/typedoc#1487]
How do I use the exlcude param and multiple plugins in tsconfig.json? Really stuck.

**Comment by Gerrit0** [comment]
If your tsconfig has a `typedocOptions` plugin, TypeDoc will read options from that in same way as if you specified them in `typedoc.json`, for example:

```json
{
    "$schema": "http://json.schemastore.org/tsconfig",
    "compilerOptions": {
        "target": "ESNext"
    },
    "typedocOptions": {
        "plugin": ["typedoc-plugin-markdown", "./local_plugin.js"]
    }
}
```
