### ISSUE TITLE
Solutions to large diffspam due to changing commit-hash when using "Defined in:" links

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [TypeStrong/typedoc#1488]
## Search Terms

commit hash
github
permanent link
regenerate

## Problem

At the moment, *every time* the docs are regenerated, they pollute the diff with changes to every single page of docs, because of the changing commit-hash:

```diff
 docs/classes/automatonelement.html |  6 +++---
 docs/classes/automatonstack.html   |  6 +++---
 docs/classes/checkpoint.html       | 22 +++++++++++-----------
 docs/classes/expression.html       | 26 +++++++++++++-------------
 docs/classes/expressioncommon.html |  6 +++---
 docs/classes/expressioneval.html   | 18 +++++++++---------
 docs/classes/lexbuffer.html        |  6 +++---
 docs/classes/lexerror.html         |  2 +-
 docs/classes/locatedtoken.html     | 14 +++++++-------
 docs/classes/parseerror.html       |  2 +-
 docs/classes/position.html         |  8 ++++----
 docs/classes/script.html           |  2 +-
 docs/classes/token.html            |  6 +++---
 docs/globals.html                  | 42 +++++++++++++++++++++---------------------
 docs/interfaces/literal.html       |  4 ++--
 docs/interfaces/sub.html           |  4 ++--
 16 files changed, 87 insertions(+), 87 deletions(-)

diff --git i/docs/classes/automatonelement.html w/docs/classes/automatonelement.html
index 697eb6a..2460d5a 100644
--- i/docs/classes/automatonelement.html
+++ w/docs/classes/automatonelement.html
@@ -101,7 +101,7 @@
 <li class="tsd-description">
         <aside class="tsd-sources">
                 <ul>
-                        <li>Defined in <a href="https://github.com/ELLIOTTCABLE/excmd.js/blob/0e092e4/packages/excmd/src/excmd.ts#L1018">packages/excmd/src/excmd.ts:1018</a></li>
+                        <li>Defined in <a href="https://github.com/ELLIOTTCABLE/excmd.js/blob/371bdb1/packages/excmd/src/excmd.ts#L1018">packages/excmd/src/excmd.ts:1018</a></li>
                 </ul>
         </aside>
         <h4 class="tsd-returns-title">Returns <span class="tsd-signature-type">string</span></h4>
@@ -118,7 +118,7 @@
 <li class="tsd-description">
         <aside class="tsd-sources">
                 <ul>
-                        <li>Defined in <a href="https://github.com/ELLIOTTCABLE/excmd.js/blob/0e092e4/packages/excmd/src/excmd.ts#L1008">packages/excmd/src/excmd.ts:1008</a></li>
+                        <li>Defined in <a href="https://github.com/ELLIOTTCABLE/excmd.js/blob/371bdb1/packages/excmd/src/excmd.ts#L1008">packages/excmd/src/excmd.ts:1008</a></li>
                 </ul>
         </aside>
         <h4 class="tsd-returns-title">Returns <span class="tsd-signature-type">"Terminal"</span>
... and so on
```

This is especially problematic if the docs are autogenerated by some heuristic (intentionally) outside of developer control, such as updating them on every commit with [Husky](https://github.com/typicode/husky) and/or [lint-staged](https://github.com/okonet/lint-staged):

```js
// .lintstagedrc.js
module.exports = {

   // Typedoc
   '**/*.{ts,js,md}': ['typedoc ./src ; :'],

}
```

Basically, any attempt to automate doc-generation will result in a lot of diff-spam, if you want sourcefile URLs. That's no good!

(Note, this is separate to #808 — when you actually *do* want sourcefile URLs, you just want them without constant diffspam.)

## Solution

There's an easy, but suboptimal, solution; and a hard, optimal solution:

1. Add an option to revert #164: for some, smaller, projects, the prospect of linkrot may be less concerning than constant diffspam; and generating documentation that simply links to the HEAD branch (i.e. `master`, or whatever branch the documentation is being built on) might be way more friendly. Obviously, this is dangerous for exactly the reasons the fixes in #164 were desirable.

2. Re-parse the existing filename/line-number in preexisting output (or maintain a cache thereof), and only update the link/commit-hash *if the filename or line-number has also changed.* This yields a much lower chance of linkrot, and would prevent diffspam in the hundreds of docpages you *didn't* update when only tweaking one function, or similar.

Hope this report is helpful; and I, personally, would love 1. to be shipped as soon as possible, even though it's imperfect, given that I suspect 2. is a lot more development work. That said, your maintenance work is appreciated, no matter what; thank you from a fellow OSS maintainer for your thankless, tireless work on this project! <'3

**Comment by Gerrit0** [comment]
It sounds like what you want already exists :) [`--gitRevision`](https://typedoc.org/guides/options/#gitrevision) has been a thing since v0.6.0

TypeDoc's docs use this to link to the tag for the latest release instead of the blob

**Comment by ELLIOTTCABLE** [comment]
This is fantastic, @Gerrit0! That definitely satisfies point 1. — although perhaps leave the Issue open, as it's still a solution that's a lot more prone to linkrot than point 2.? Assuming anybody can ever find the time or motivation to implement it. ¯\_(ツ)_/¯

Thank you for pointing it out!

**Comment by Gerrit0** [comment]
I don't see ever implementing point 2. That's... horribly complicated, will produce different results depending on who runs the docs unless we automatically check out 2+ versions and rebuild the docs. Point 1 has been sufficient for a long time.

**Comment by Gerrit0** [comment]
I've given this some more thought, and have been unable to come up with any clean way of implementing option 2 that doesn't result in significant performance penalties and flaky results, so marking this as wontfix - option 1 is generally good enough.
