### ISSUE TITLE
Documentation not rendered for optional interface methods

### ISSUE THREAD

**Issue by jnordberg** [TypeStrong/typedoc#1490]
## Search terms

Optional method, function, interface declaration, missing, not working

## Expected Behavior

Should render the docstrings for optional methods in an interface

## Actual Behavior

Does not render

![Screen Shot 2021-01-31 at 13 30 12](https://user-images.githubusercontent.com/95886/106374648-83285680-63c8-11eb-90ab-43e046d95946.png)

## Steps to reproduce the bug

```ts
interface MyThing {
  /** This is documented. */
  doThing(): void
  /** This isn't. */
  doAnotherThing?(): void
}
```

## Environment

-   Typedoc version: 0.20.19
-   TypeScript version: 4.1.3
-   Node.js version: v15.4.0
-   OS: macOS 11

**Comment by Gerrit0** [comment]
Thanks for the reproduction! That was an easy fix at least... will be included in 0.20.20
