### ISSUE TITLE
[docs] supported tags list is unclear on file comment supported tags

### ISSUE THREAD

**Issue by pretentious7** [TypeStrong/typedoc#1492]
at https://typedoc.org/guides/doccomments/#supported-tags , I think the @module and @packageDocumentation tags should also be listed.

If this is acceptable, I can work on this. Do those two make the list of supported tags fully exhaustive? including all conditional tags?

**Comment by Gerrit0** [comment]
Wow... that page is even more out of date than I thought! It still talks about Highlight.JS, which was switched out for Shiki in 0.20.

Off the top of my head, that list is missing `@private`, `@protected`, and `@public`, which do what you'd expect (though are arguably a bad thing...) It should also mention that `@template` is a synonym for `@typeParam`

A PR fixing this would be great!

**Comment by Gerrit0** [comment]
... and of course the TS-in-JS tags! I had some other updates to do, so I went ahead and updated the site. https://typedoc.org/guides/doccomments/#%40packagedocumentation
