### ISSUE TITLE
Generated docs do not included re-exported namespaced members in 0.20.20

### ISSUE THREAD

**Issue by madtrick** [TypeStrong/typedoc#1493]
## Search terms

keywords: export, namespace, re-export

## Expected Behavior

```typescript
//module test/stubs.ts

export function makeStandarResponse () { ... }
export function makeResponseTimings () { ... }
...

//module src/client.ts

export * as stubs from '../test/stubs'
...
```
When running `typedoc src/client.ts` with version `0.20.19` the code above would yield:

(root of the api docs 👇 )

![image](https://user-images.githubusercontent.com/48772/106869639-7493b500-66d0-11eb-9650-2c6bddf3f294.png)

(inside the `stubs` namespace 👇 )

![image](https://user-images.githubusercontent.com/48772/106870267-30ed7b00-66d1-11eb-919c-9b69bb86ba7b.png)

## Actual Behavior

With version `0.20.20` and the same code, `typedoc` will generate a page without any exported member for the `stubs` namespace:

![image](https://user-images.githubusercontent.com/48772/106870031-e8ce5880-66d0-11eb-9e12-9b8c5d7e3a78.png)

## Steps to reproduce the bug

I use the same`typedoc.js` config in both cases:

```js
module.exports = {
  readme: 'none',
  excludeInternal: true
}
```

As mentioned, I run typedoc like so: `typedoc src/client.ts`

## Environment

-   Typedoc version:
```shell
typedoc --version

TypeDoc 0.20.20
Using TypeScript 4.1.3 from /Users/.../repos/work/http-client/node_modules/typescript/lib
```
-   Node.js version:
```shell
node --version
v14.15.1
```
-   OS: MacOs

**Comment by Sytten** [comment]
I don't even have the classes on the main page.

**Comment by Gerrit0** [comment]
Sorry about that! 0.20.21 fixes the repro in the OP.

**Comment by madtrick** [comment]
No worries. Thanks for the quick fix @Gerrit0
