### ISSUE TITLE
"Defined in" links not clickable when built on GitHub Actions

### ISSUE THREAD

**Issue by tpluscode** [TypeStrong/typedoc#1495]
Probably not a bug but something about how GH Actions checkout the repository.

What do I need to do to have clickable "Defined in" links? They work when built locally but typedoc on CI outputs only text

**Comment by Gerrit0** [comment]
TypeDoc figures out how to create source links by looking at the source location and the result of `git ls-files`. If you're getting "Defined in", but no link, that means that either:

1. The source code isn't in a git repo with an origin that TypeDoc understands
2. The files aren't tracked by the git repo.

TypeDoc's docs [are built](https://github.com/TypeStrong/typedoc-site/blob/master/.github/workflows/publish.yml#L30-L39) with GitHub Actions and [contain](https://typedoc.org/api/enums/reflectionkind.html#accessor) links, so it's definitely possible... how are you checking out your code?

**Comment by tpluscode** [comment]
I don't do anything fancy to check out. Only have the action [actions/setup-node@v2.1.2](https://github.com/hypermedia-app/shaperone/blob/master/.github/workflows/build.yml#L20)

**Comment by tpluscode** [comment]
Maybe I could alternatively pass the git detail to the CLI. All information should be available in the Actions context?

**Comment by Gerrit0** [comment]
That's... really weird. I just set up a very simple repo that uses basically the same setup as yours, and the links show up correctly:

https://github.com/Gerrit0/actions-test/blob/main/.github/workflows/build.yml
https://gerritbirkeland.com/actions-test/modules.html#test

**Comment by tpluscode** [comment]
Curious. I changed the build to directly call `yarn typedoc` from the workflow and it worked.

Somehow the "long way" of calling yarn + npm-run-all does not 🤔

**Comment by tpluscode** [comment]
Ah no, it's the Netlify action. I thought it only collected the build output but it actually runs the build again inside a container. Hence no git information.

Thanks for your help figuring this out

**Comment by dessalines** [comment]
This should be re-opened. I'm doing container builds of mine too, and we should be able to specify the git repo URL. Currently all the `defined in` don't have clickable links when doing builds in docker.
