### ISSUE TITLE
Accessors are not identified as an implementation of an interface property

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1497]
## Search terms

Inherit, inheritance, implementation, properties, computed properties, accessors

## Expected Behavior

Typedoc correctly identifies computed properties (accessors) as implementations of interface properties.

Example:

```ts
export interface Foo {
	/** Some documentation. */
	readonly bar: number;
	readonly barProp: number;
	barMethod(): number;
}
export class FooClass implements Foo {
	/** @inheritdoc */
	get bar(): number { return 4; }
	barProp = 9;
	barMethod(): number { return 42; }
}
```

All elements in `FooClass` should have a note saying that they implement some property of `Foo`.

## Actual Behavior

This:

<details>
<summary>Screenshot of the page of `FooClass`</summary>

![image](https://user-images.githubusercontent.com/20878432/107123287-fe907900-689c-11eb-990e-d14f363916d6.png)

</details>

`FooClass.bar` does not have a little note saying: "Implementation of Foo.bar". This is the case with and without `@inheritdoc`.

## Steps to reproduce the bug

[Minimal project](https://github.com/TypeStrong/typedoc/files/5937251/repo.zip).

## Environment

-   Typedoc version: 0.20.22
-   TypeScript version: 4.1.3
-   Node.js version: v14.15.4
-   OS: Win10 x64 Version 10.0.19042.746

**Comment by Gerrit0** [comment]
Looks like TypeDoc did correctly mark the accessor with `implementationOf`, but not the `getSignature` and/or `setSignature` property, so when rendering it wasn't picked up.
