### ISSUE TITLE
Exported elements missing

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1499]
## Search terms

namespace, missing export

## Expected Behavior

I have a project that exports a function like this:

```ts
export namespace nested {
  function bar(): number {
    return 4;
  }
}
```

I split this up into 3 files like this:

```
src/
  nested/
    bar.ts
    index.ts
  index.ts
```

```ts
// src/index.ts
export * as nested from "./nested/index";

// src/nested/index.ts
export * from "./bar";

// src/nested/bar.ts
export function bar(): number {
	return 4;
}
```

I expected that typedoc correctly detects the `nested` namespace and the `bar` function within it.

## Actual Behavior

Typedoc does not detect the `bar` function and thinks that `nested` is an empty namespace.

<details>

docs/modules.html

![image](https://user-images.githubusercontent.com/20878432/107126254-f9d4c080-68ae-11eb-928a-1a03d86bbfd1.png)

docs/modules/nested.html

![image](https://user-images.githubusercontent.com/20878432/107126256-01946500-68af-11eb-8735-18bf575527a4.png)

</details>

## Steps to reproduce the bug

[Minimal project](https://github.com/TypeStrong/typedoc/files/5937360/repo.zip).

## Environment

-   Typedoc version: 0.20.22
-   TypeScript version: 4.1.3
-   Node.js version: v14.15.4
-   OS: Win10 x64 Version 10.0.19042.746

**Comment by Gerrit0** [comment]
The namespace converter is the single most changed piece of code the past 3 weeks here... I keep half fixing it, and someone reports another bug 😅

**Comment by RunDevelopment** [comment]
Thank you for resolving this so quickly @Gerrit0!

**Comment by Gerrit0** [comment]
Glad to help :) You caught me on a day I had time and was working on TypeDoc anyways
