### ISSUE TITLE
The document generation using the third party plug-in is not successful

### ISSUE THREAD

**Issue by Clairegirl** [TypeStrong/typedoc#1501]
## Search terms

Typedoc-Webpack-Plugin
95% emitting unnamed compat pluginWarning: No compiler options set. This likely means that TypeDoc did not find your tsconfig.json. Generated documentation will probably be empty.
95% emitting unnamed compat pluginWarning: No compiler options set. This likely means that TypeDoc did not find your tsconfig.json. Generated documentation will probably be empty.
## Expected Behavior

Generate API documents
## Actual Behavior

![5FF5E30D-2185-4411-9D5B-D5CF9F0F110D](https://user-images.githubusercontent.com/15991200/107143083-fc4a1f80-696d-11eb-89b9-3866cbf01b56.png)

![642CEF51-BC0B-4b76-93B5-DF32AA334BE4](https://user-images.githubusercontent.com/15991200/107143090-0835e180-696e-11eb-947d-a6fd0f9126e4.png)

No API document was generated

## Environment

-   Typedoc version:0.20.23
-   TypeScript version: 3.9.7
-   Node.js version:12.16.1
-   OS:Windows10

**Comment by Gerrit0** [comment]
The webpack plugin isn't maintained here, and looking at the source, it hasn't been updated in years... I'm surprised it gets as close as it does.

I should probably go ahead and remove this plugin link from typedoc.org since it is broken. I recommend running typedoc separately with the CLI.
