### ISSUE TITLE
Can't figure out how to make a cross-module link

### ISSUE THREAD

**Issue by elashpear** [TypeStrong/typedoc#1505]
I have a class like so:
<img width="640" alt="Screen Shot 2021-02-08 at 3 34 30 PM" src="https://user-images.githubusercontent.com/47397266/107294889-29a4d500-6a23-11eb-8df3-52a8a65003e7.png">

I am trying to link to this class from another module inside this package. I can't get it to parse the link.

I checked https://typedoc.org/guides/link-resolution/, https://github.com/TypeStrong/typedoc/issues/1302, and https://github.com/TypeStrong/typedoc/issues/1297.

I have tried many combinations of the examples above and it never parses the link or logs any sort of warning. I thought that `{@link "state/persistence/SyncEngine".default}` would match your description above. I am trying to link to this concrete class as an example from the file that the interface it implements is defined in. The auto-generated link to the class appears in the list of implementing classes. I just can't make an inline link in my description of the interface.

I only have two ts files in the repo right now so I can't try it with any other files. Not sure if this is related, but `isolatedModules` is enabled in my `tsconfig` as that was recommended in the react native template I'm using.

I also can't figure out how to link to a type declared by a dependency. This is a library project but apparently "library mode" is now deprecated so I am hoping the new defaults will work.

**Comment by Gerrit0** [comment]
Do you have a project I could take a look at? I would expect that link to work from your description.

You can tell TypeDoc to tell you about broken links with `--listInvalidSymbolLinks`, which we should really default to true... but I haven't gotten around to making that one line change yet.

**Comment by elashpear** [comment]
Unfortunately it's proprietary code I can't share, but I'll try that option and see if it helps diagnose the issue. If i'm still having an issue I'll see if I can isolate a simplified repro case, although I expect this is a PEBKAC I can't figure out the fix yet. Thanks for the quick response!

**Comment by elashpear** [comment]
I was able to isolate a repro case here https://github.com/fadookie/tsdoc-linking-bug-repro

I can't get these absolute links to work at all. The relative links work but I can't figure out how to disambiguate symbols with the same name, or reference default exports.

**Comment by Gerrit0** [comment]
Thanks! I've sent a pull request with some fixed links. It looks like your issue is that you were trying to use a colon to separate parts of links instead of a period.

**Comment by fadookie** [comment]
Oh! Glad it was a simple error on my end. I will try this out soon.
