### ISSUE TITLE
Specify internals for projects with single file entry

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#151]
I have a project which uses ES6 imports to pull in files from a single entry point. When running typedoc,  only the entry point is shown as an internal in the sidebar. All other files are listed as externals. I know that there is the `externalPattern` option but this seems to only remove files from the internals list.

Is there a way to add files to the internals list without having them compiled separately?

**Comment by sebastian-lenz** [comment]
Hi Anthony, TypeDoc will treat all provided source files as being internal. If you want additional files to be listed as internal just pass them as source files. You can also specify an entire directory, all files inside that directory will be seen as "internal" files.
