### ISSUE TITLE
Process failing due to out of memory

### ISSUE THREAD

**Issue by bassochette** [TypeStrong/typedoc#1511]
## Search terms

out of memory

## Expected Behavior

Generate a beautiful documentation for my API client.

## Actual Behavior

Failing due to an out of memory error. 

<img width="1680" alt="Screenshot 2021-02-18 at 08 22 41" src="https://user-images.githubusercontent.com/935669/108320008-8a21d800-71c2-11eb-9406-480b5496d67a.png">

## Steps to reproduce the bug

typedoc.json config file:
```
{
  "entryPoints": ["src/main.ts"],
  "out": "docs"
}
```

[Repo I try to setup typedoc for](https://github.com/Webeleon/dev.to)

## Environment

-   Typedoc version: 0.20.25
-   TypeScript version: 4.1.15
-   Node.js version: 14.15.2
-   OS: Mac OSX 11.2.1 with an M1 chip

**Comment by Gerrit0** [comment]
This sounds a lot like https://github.com/TypeStrong/typedoc/issues/1491. Could you try upgrading to Node 15 and see if that fixes it?

**Comment by bassochette** [comment]
ran on node 15.9.0 without issues.

closing the issue, thanks for your help
