### ISSUE TITLE
Private static getters being displayed with `excludePrivates: true`

### ISSUE THREAD

**Issue by zajrik** [TypeStrong/typedoc#1516]
## Expected Behavior
I expected the private static getter to not be output in the documentation because I have `excludePrivates: true` in my config
![image](https://user-images.githubusercontent.com/10369802/108783518-3fda8700-7533-11eb-863f-4e19f327b7e4.png)

## Actual Behavior
The private static getter is being output in the documentation
![image](https://user-images.githubusercontent.com/10369802/108783530-436e0e00-7533-11eb-9577-9f0873c09db1.png)

## Steps to reproduce the bug
Generate documentation for the following code with `excludePrivates: true` in the config:
```ts
export class Test
{
	private static get _test(): string
	{
		return 'test';
	}

	public test(): string
	{
		return Test._test;
	}
}
```

## Environment

-   Typedoc version: 0.20.23
-   TypeScript version: 4.1.3
-   Node.js version: 14.15.3
-   OS: Ubuntu 20.04.2 LTS on Windows 10 x86_64

I'm just using `/** @internal */` as a workaround for the time being but hopefully this can be resolved. Thank you.

**Comment by Gerrit0** [comment]
I like easy bugs :) Just forgot to call the `setModifiers` function for accessors.

**Comment by zajrik** [comment]
Awesome! Thanks for the quick fix!
