### ISSUE TITLE
Changing the module names picked up by Typedoc

### ISSUE THREAD

**Issue by hiranya911** [TypeStrong/typedoc#1518]
# Summary

Is there a way to customize the module names Typedoc (0.20.x) assigns to each entry point?

# Details

I have a source tree that looks like this:
```
my-package/
  |__ index.ts
  |__ app/
  |      |__ index.ts
  |__ auth/
         |__ index.ts
```

If I run typedoc on each of my `index.ts` files as entry points, the generated `modules.html` file would list the following items:
* index
* app
* auth

Ideally I'd like them to be listed as:
* my-package
* my-package/app
* my-package/auth

Is this supported?

# Possible workaround

So far I've found the following workaround:
1. Copy `my-package` source tree into a new `temp` directory.
2. Add an empty `temp/index.ts` file.
3. Run typedoc on all entry points (including the one added in step 2 above)

Now the `modules.html` file lists the following entries:
* index (this is of course redundant)
* my-package
* my-package/app
* my-package/auth

This is pretty close to where I'd like to end up, but the extra steps and the redundant `index` entry in the output is a bit of a problem.

**Comment by Gerrit0** [comment]
Yes it is! You can use the `@module` tag to do this. In `index.ts`, include a comment at the top of the file that looks like this:

```ts
/**
 * General docs
 * @module my-package
 */
```

**Comment by hiranya911** [comment]
Brilliant! Exactly what I needed, and works like a charm.

I also retroactively found some docs about this feature at https://typedoc.org/guides/doccomments/#%40module. Thanks @Gerrit0 for the tip.
