### ISSUE TITLE
Utility functions are included in output, instead of their resolved final types

### ISSUE THREAD

**Issue by anzorb** [TypeStrong/typedoc#1519]
## Search terms

Maybe this is intended (or isn't implemented yet), but Utility type exports aren't being expanded in the output and instead show "Omit<>"...

```typescript
export interface TSmarterLabelOptions {
   color: string;
   text: string; 
};

export type TOptions = Omit<TGlobalOptions, 'text'>;

```

## Expected Behavior

I expect our clients to see the final result of the types involved in Utility functions:

<img width="811" alt="Screen Shot 2021-02-25 at 11 36 14 AM" src="https://user-images.githubusercontent.com/1194338/109185141-b35fdc80-775d-11eb-8d11-a9b9aca7071b.png">

## Actual Behavior

<img width="832" alt="Screen Shot 2021-02-25 at 11 28 51 AM" src="https://user-images.githubusercontent.com/1194338/109185174-be1a7180-775d-11eb-97d7-f22908ed8844.png">

This is especially problematic when re-exporting a type from another project and omitting a value (where we don't want them to know anything about the other project) and the end-users don't know what we're omitting from. This is actually how we use it:

```typescript
import type { TGlobalOptions } from '../../another_project_by_tsconfig_reference';

export type TOptions = Omit<TGlobalOptions, 'text'>;

```

## Environment

-   Typedoc version: 0.20.28
-   TypeScript version: 4.1.5
-   Node.js version: 12.18.4
-   OS: 10.15.7

**Comment by koskimas** [comment]
Some utility exports are really complex. I kind of hope my utility type won't get expanded in the docs 😉 

```ts
type ExtractTypeFromSelectArg<
  DB,
  TB extends keyof DB,
  S,
  A extends keyof any,
  R = RowType<DB, TB>
> = S extends `${infer SC}.${infer T}.${infer C} as ${infer RA}`
  ? RA extends A
    ? `${SC}.${T}` extends TB
      ? C extends keyof DB[`${SC}.${T}`]
        ? DB[`${SC}.${T}`][C]
        : never
      : never
    : never
  : S extends `${infer SC}.${infer T}.${infer C}`
  ? C extends A
    ? `${SC}.${T}` extends TB
      ? C extends keyof DB[`${SC}.${T}`]
        ? DB[`${SC}.${T}`][C]
        : never
      : never
    : never
  : S extends `${infer T}.${infer C} as ${infer RA}`
  ? RA extends A
    ? T extends TB
      ? C extends keyof DB[T]
        ? DB[T][C]
        : never
      : never
    : never
  : S extends `${infer T}.${infer C}`
  ? C extends A
    ? T extends TB
      ? C extends keyof DB[T]
        ? DB[T][C]
        : never
      : never
    : never
  : S extends A
  ? S extends keyof R
    ? R[S]
    : never
  : S extends AliasedRawBuilder<infer O, infer RA>
  ? RA extends A
    ? O
    : never
  : S extends (qb: any) => AliasedRawBuilder<infer O, infer RA>
  ? RA extends A
    ? O
    : never
  : S extends AliasedQueryBuilder<any, any, infer O, infer QA>
  ? QA extends A
    ? ValueType<O>
    : never
  : S extends (qb: any) => AliasedQueryBuilder<any, any, infer O, infer QA>
  ? QA extends A
    ? ValueType<O>
    : never
  : never
```

**Comment by anzorb** [comment]
I feel like the purpose of documentation isn't to show the inner workings, but to show how one would use a library/api, etc. Is this not the purpose of this project? Can this be opt in?

**Comment by Gerrit0** [comment]
This is a similar request to #1513.

I think this might make sense to do - with some limitations.

1. This should only happen if the type alias has no type parameters. This looks like an interface
    ```ts
   type Foo = Record<"a" | "b", string>
   ```
   This does not:
   ```ts
    type Bar<T> = T extends string ? T : never
    ```
2. This should only happen if the type is an object type.
   ```ts
   type Yes = { a: string }
   type No = { a: string } | { b: number }
   ```
3. This should still happen if the type is an intersection type
    ```ts
    type Yes = { a: string } & { b: number }
    ```
4. This should not happen for tuple types
   ```ts
    type No = [a: string, b: number]
    ```

Am I missing anything here? This won't catch the following, which it might be argued should be caught....
```ts
type Missed<T> = Record<"a" | "b", T>
```

cc: @thebestnom

**Comment by Gerrit0** [comment]
I'm not sure this is something that I necessarily want to put in the core library - but https://github.com/mxsdev/ts-expand-type exists now, the code in which should be usable to create a plugin... putting this here so I remember the next time I look at this with an eye to implementing.

**Comment by treykasada** [comment]
@Gerrit0 What are your thoughts on having the outputted types match those shown by the language service (in tooltips and such)?

It feels like that would make for a nice overall user experience, since users would know exactly what the doc typings would be just by looking at the tooltips in their IDE.
Ideally the implementation could even leverage some compiler/language service APIs to do the type resolution, although I'm not sure if such APIs exist.

**Comment by Gerrit0** [comment]
The language service is unfortunately terrible (at least last I looked at it... been a couple years) in terms of providing an API that can be used to correctly associate a displayed type name with the type that it actually represents. Because it just displays types to the user without go to definition, it will just stringify a type and then pass it through syntax highlighting... If that weren't the case, I think it'd be the way to go.

(Maybe this has improved now that semantic highlighting is a thing? Open to a PR resulting from an investigation!)

**Comment by Spencer17x** [comment]
Are there any good solutions now? I see that vscode and idea floating window prompt both support this, can you refer to the logic of this section?like this:
![image](https://user-images.githubusercontent.com/32794413/204241005-f67ecdd0-4bd2-48f8-ac29-f41898e163d0.png)

**Comment by Spencer17x** [comment]
Someone gave an answer to this issue: https://github.com/TypeStrong/typedoc/issues/2032. I have tested it and it can be used normally

**Comment by Gerrit0** [comment]
0.24.0-beta.6 includes support for this, with a slight design change. I realized that it doesn't necessarily always make sense to treat a type alias as an interface with eagerly resolved properties, and some people may prefer keeping the constructing type, (`Record<keyof Foo, string>` might be better for docs if Foo has a ton of properties)

Thus, resolving the type is now opt-in with the `@interface` tag. For convenience, `@prop` and `@property` are supported for specifying comments on the properties of the resulting type.

An example:

```ts
/**
 * Foo docs
 */
export type Foo = {
    /**
     * Foo.a docs
     */
    a: 123;
    /**
     * Foo.b docs
     */
    b: 456;
};

/**
 * Bar docs
 * @property a Bar.a docs
 * @interface
 */
export type Bar = {
    [K in keyof Foo]: string;
};
```

With this setup, `Bar` could be equivalently defined as:

```ts
/** Bar docs */
export interface Bar {
  /** Bar.a docs */
  a: 123,
  /** Foo.b docs
  b: 456,
}
```

Notice that `a`'s comment is overridden, but `b`s comment is still the one declared on the source type.
