### ISSUE TITLE
Force inclusion of type definition

### ISSUE THREAD

**Issue by mnlipp** [TypeStrong/typedoc#1520]
I have a type definition in my ts source:
```ts
/**
 * Represents...
 */
type Panel = {
  /** The id */
  id: string;
  label: string | Function;
  removeCallback: () => {}
};
```
I went through all options but I cannot find a way to make typedoc include this in the generated documentation. What am I missing?

**Comment by Gerrit0** [comment]
It sounds like you want https://www.npmjs.com/package/typedoc-plugin-not-exported. There's no builtin way to do this.

**Comment by mnlipp** [comment]
Thanks for the link. The plugin doesn't really help, because it only works if the source file is a direct input file. In my case, typedoc processes a different file that imports from the file with the type declaration.

Nevertheless, the discussion concerning the plugin made me understand why I should export the type, although the generated code is currently only used by "plain" JavaScript consumers. And of course, exporting the type fixes things.
