### ISSUE TITLE
Functions appear more than once if @category were annotated

### ISSUE THREAD

**Issue by JasonHK** [TypeStrong/typedoc#1522]
## Search terms

`@category`

## Expected Behavior

Functions should appear once only in the following cases:

```typescript
interface Callable
{
    (payload: number): string;
    (payload: string): number;
}

/**
 * @category Callable
 */
export declare const callable: Callable;
```

```typescript
/**
 * @category Callable
 */
export declare function callable(payload: number): string;

/**
 * @category Callable
 */
export declare function callable(payload: string): number;
```

## Actual Behavior

![2021-03-02_00001](https://user-images.githubusercontent.com/4410086/109596923-25676580-7b52-11eb-9d47-a781d2a3642d.png)
![2021-03-02_00002](https://user-images.githubusercontent.com/4410086/109597010-58115e00-7b52-11eb-9541-759811398d6b.png)

## Steps to reproduce the bug

Please refer to the code snippets above.

## Environment

-   Typedoc version: 0.20.28
-   TypeScript version: 4.1.5
-   Node.js version: 14.15.5
-   OS: Kubuntu 20.04

**Comment by Gerrit0** [comment]
Fixed in 0.20.30
