### ISSUE TITLE
Documentation for function variables was not inferred

### ISSUE THREAD

**Issue by JasonHK** [TypeStrong/typedoc#1523]
## Search terms

const, function

## Expected Behavior

Documentation for function variables should be inferred, i.e. the description, parameter descriptions etc. should be inherited.

```typescript
interface Callable
{
    /**
     * Convert a number to a string.
     * 
     * @param payload A number.
     */
    (payload: number): string;

    /**
     * Convert a string to a number.
     * 
     * @param payload A string.
     */
    (payload: string): number;
}

export declare const callable: Callable;
```

## Actual Behavior

![2021-03-02_00004](https://user-images.githubusercontent.com/4410086/109598678-b3445000-7b54-11eb-8827-86e79bea6779.png)
![2021-03-02_00003](https://user-images.githubusercontent.com/4410086/109598614-9019a080-7b54-11eb-9bee-b7775806ca26.png)

## Steps to reproduce the bug

Please refer to the code snippet above.

## Environment

-   Typedoc version: 0.20.28
-   TypeScript version: 4.1.5
-   Node.js version: 14.15.5
-   OS: Kubuntu 20.04

**Comment by Gerrit0** [comment]
This is a really tricky one.

We could technically achieve this by relying on `symbol.getDocumentationComment()` in order to retrieve the comments... but unfortunately this directly conflicts with some other goals, since then comments on elements using declaration merging would show up in both places:

```ts
/** NS docs */
namespace Foo {}
/** Function docs */
function Foo() {}
```

I also wonder... what's the right solution in a case like this?

```ts
/** Does this get ignored? What it if includes important info like @hidden? */
export const callable: Callable = ...
```

I should really write down somewhere what TypeDoc currently does for comments so that it's easier to propose refinements to what it does...

**Comment by JasonHK** [comment]
> This is a really tricky one.
> 
> We could technically achieve this by relying on `symbol.getDocumentationComment()` in order to retrieve the comments... but unfortunately this directly conflicts with some other goals, since then comments on elements using declaration merging would show up in both places:
> 
> ```ts
> /** NS docs */
> namespace Foo {}
> /** Function docs */
> function Foo() {}
> ```
> 
> I also wonder... what's the right solution in a case like this?
> 
> ```ts
> /** Does this get ignored? What it if includes important info like @hidden? */
> export const callable: Callable = ...
> ```
> 
> I should really write down somewhere what TypeDoc currently does for comments so that it's easier to propose refinements to what it does...

@Gerrit0 I think TypeDoc should at least inherit tags like `@template`, `@param`, `@returns` and `@throws`.

**Comment by Gerrit0** [comment]
Inheritance isn't the tricky part - we already do that for normal interface/class members. The tricky part is inherit from *where*? There is no `implements` clause here.

**Comment by Gerrit0** [comment]
![image](https://user-images.githubusercontent.com/19329837/175833880-2b4497c8-e1c6-451e-b324-917a900e1ece.png)

In 0.23, TypeDoc tries to get docs from the signature itself, and therefore picks these up.
