### ISSUE TITLE
Don't show superfluous undefined in optional properties

### ISSUE THREAD

**Issue by marcofugaro** [TypeStrong/typedoc#1525]
## Search terms

undefined optional parameter

## Actual Behavior

After upgrading Typedoc to the latest version (this happens on 0.20.6 and up), Typedoc is showing the `undefined` value also for parameters which are already marked as optional with `?`. This makes the parameters section much more clustered and difficult to read:

![image](https://user-images.githubusercontent.com/7217420/109959702-24683c80-7ce8-11eb-8ad6-0d5500c780bc.png)

## Expected Behavior

I would like an option to disable this behaviour, and make it look like it was originally (this is version 0.20.1):

![image](https://user-images.githubusercontent.com/7217420/109959217-78265600-7ce7-11eb-95eb-5903c1cc790e.png)

## Environment

-   Typedoc version: 0.20.6 and up

**Comment by Gerrit0** [comment]
This is behaving as expected for parameters but not for properties (note how `options` doesn't have a `| undefined`)

**Comment by Gerrit0** [comment]
Fixed in 0.20.30
