### ISSUE TITLE
How to prevent modules from being documented, while keeping their classes?

### ISSUE THREAD

**Issue by felipecrs** [TypeStrong/typedoc#1526]
In the past, `--mode files` had this effect. Now, I can't make this work, I tried to hide (with `@hidden`) all my modules, but that stop their classes from being documented as well.

I checked the 0.20 release notes for the `--mode` removal, but I couldn't find any help there also.

References #1470, which had no response.

**Comment by Gerrit0** [comment]
You're running TypeDoc with configuration like this:

```json
{
  "inputFiles": ["src"]
}
```

When you do this, TypeDoc will expand that directory into an array of entry points and then document each entry point's exports, resulting in documentation for all of your modules.

However, if you pass TypeDoc a single entry point, then it will only document what has been exported from that file, giving documentation for just those exports under your project. This is how [TypeDoc's config](https://github.com/TypeStrong/typedoc-site/blob/master/typedoc.json) is set up.

This is good enough for most usage, and is what you should use if you are generating docs for a library, but if you are documenting an application's classes without creating a single file that exports what you want to document, then you'll likely want to use [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules).

**Comment by felipecrs** [comment]
Thank you so much for the response, @Gerrit0. 

To make this easier, could you take a look into my project? I indeed use a folder as my `entryPoints`. However, my `src/index.ts` is pointless for a configuration perspective, so I want the documentation for all the other files (that's why I use `src` as my folder). Nonetheless, in my case, generating the modules documents is also pointless, as it's just a reference for my Classes, which actually contains meaningful information that I want documented.

https://github.com/felipecrs/megatar
https://gitpod.io/#https://github.com/felipecrs/megatar
https://felipecrs.com/megatar (currently generated with TypeDoc 0.19.0)

**Comment by felipecrs** [comment]
The plugin does exactly what I wanted, thank you so much!
