### ISSUE TITLE
v0.20 inheritedFrom property not set at declaration creation

### ISSUE THREAD

**Issue by jonchardy** [TypeStrong/typedoc#1527]
## Search terms

inheritedFrom, inherit, inheritance

## Expected Behavior

Typedoc v0.20 should properly set **Reflection.inheritedFrom** for inherited members prior to calling any EVENT_CREATE_DECLARATION listeners. This allows plugins to check inheritance prior to resolving.

## Actual Behavior

**Reflection.inheritedFrom** is not set for inherited members at the time of EVENT_CREATE_DECLARATION. This breaks https://github.com/jonchardy/typedoc-plugin-no-inherit.

## Steps to reproduce the bug

See https://github.com/jonchardy/typedoc-inheritedfrom-breaking.

## Environment

-   Typedoc version: 0.20.x
-   TypeScript version: 4.2.x
-   Node.js version: 14.15.5
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Awww... I knew it was too good to be true that that change hadn't broken anything.

**Comment by Gerrit0** [comment]
This is set during `EVENT_CREATE_DECLARATION` with a fairly high priority, so it should work... I hate all of the code I wrote to make it work though.
