### ISSUE TITLE
Regression: some types are misplaced or not displayed

### ISSUE THREAD

**Issue by marcofugaro** [TypeStrong/typedoc#1529]
## Search terms

types misplaced not displayed

## Actual Behavior

I have this code:

```js
export const BODY_TYPES = {
  DYNAMIC: 1,
  STATIC: 2,
  KINEMATIC: 4,
} as const

export type BodyType = typeof BODY_TYPES[keyof typeof BODY_TYPES]

export class Body  {
   /**
   * One of: `Body.DYNAMIC`, `Body.STATIC` and `Body.KINEMATIC`.
   */
  type: BodyType

  // ... 
  constructor(
    options: {
      /**
       * One of: `Body.DYNAMIC`, `Body.STATIC` and `Body.KINEMATIC`.
       */
      type?: BodyType
      
      // ...
    } = {}
  ) {

}

```

And the `options.type` is not showing the `BodyType`, but instead its literal value (happens from `v0.20.6`, possibly related to #1528).

![image](https://user-images.githubusercontent.com/7217420/110303882-38b77c80-7ffb-11eb-9864-098aff1dc9e5.png)
![image](https://user-images.githubusercontent.com/7217420/110303390-9eefcf80-7ffa-11eb-99e6-d0a60c13cd42.png)

While the class property, is showing totally a different type!! (happens from `v0.20.13`)

![image](https://user-images.githubusercontent.com/7217420/110303656-ec6c3c80-7ffa-11eb-8b40-bc1dbc336efe.png)

For context, the type `RayMode` is in totally another part of the application and corresponds to this:

```ts
export const RAY_MODES = {
  CLOSEST: 1,
  ANY: 2,
  ALL: 4,
} as const


export type RayMode = typeof RAY_MODES[keyof typeof RAY_MODES]
```

## Expected Behavior

This should be the correct behaviour as it is with `v0.20.5`:

![image](https://user-images.githubusercontent.com/7217420/110304125-803e0880-7ffb-11eb-8b8d-d6cf985b2612.png)

![image](https://user-images.githubusercontent.com/7217420/110304176-8cc26100-7ffb-11eb-8de7-586bccf912f4.png)

## Steps to reproduce the bug

I can link the repo where this happens if needed

## Environment

-   Typedoc version: v0.20.6 and up

**Comment by Gerrit0** [comment]
What TypeScript version are you using?

**Comment by marcofugaro** [comment]
4.0.5, but I'll try upgrading it and see if the issue persists!

**Comment by marcofugaro** [comment]
Updating typescript completely solves this issue, thanks!
