### ISSUE TITLE
Documentation for a module or including README.md for a folder...

### ISSUE THREAD

**Issue by electricessence** [TypeStrong/typedoc#153]
Seems logical to automatically include the README.md for a folder?  Or maybe not.
I'm having trouble configuring documentation for a module.

For a module that has an export default, how do I add docs?

**Comment by electricessence** [comment]
I want to add documentation like this.
https://github.com/electricessence/TypeScript.NET/blob/master/source/System.Linq/README.md

**Comment by sebastian-lenz** [comment]
Looks like a good idea to me, I would like to add this a new feature for the next version. Starting with TypeDoc 0.4 we will display the directory structure of modules in the documentation so it should be possible to pick up the readme files and display them.

**Comment by electricessence** [comment]
That could work.  So how do I document modules in the meantime?

**Comment by felixhayashi** [comment]
Hi, any progress on this one?

**Comment by Dzenly** [comment]
And how can I exclude this damn readme.md from my docs now. --exclude readme.md does not work (

**Comment by aciccarello** [comment]
@Dzenly You can create a stub readme with no content and use the `--readme filename.md` option to use the stub.

**Comment by Gerrit0** [comment]
Or you can use `--readme none` as specified in the help output.

**Comment by aciccarello** [comment]
Oh, yeah. I forgot about that option. That's prefered.

**Comment by Gerrit0** [comment]
Module documentation can be achieved as documented under `Files` on the site - https://typedoc.org/guides/doccomments/#files

```ts
/** @packageDocumentation
  * Module docs here
  */
```
