### ISSUE TITLE
OOM, even with Node 15

### ISSUE THREAD

**Issue by thejohnfreeman** [TypeStrong/typedoc#1536]
I'm trying to build documentation for the TypeScript compiler API. They don't seem to have any publicly available. I get an OOM, both with Node 14  and, after skimming #1511 and #1491, with Node 15.

## Steps to reproduce the bug

```shell
git clone https://github.com/microsoft/TypeScript.git typescript
cd typescript
npm install
# Building the compiler generates a few necessary source files.
npx gulp tsc
npm install typedoc --save-dev
npx typedoc src/compiler/ --tsconfig src/compiler/tsconfig.json
```

## Result

```text
<--- Last few GCs --->

[1824791:0x471d940]   120314 ms: Scavenge (reduce) 4058.7 (4141.6) -> 4058.3 (4141.6) MB, 5.3 / 0.0 ms  (average mu = 0.441, current mu = 0.316) allocation failure
[1824791:0x471d940]   120323 ms: Scavenge (reduce) 4059.1 (4141.6) -> 4058.7 (4142.1) MB, 5.2 / 0.0 ms  (average mu = 0.441, current mu = 0.316) allocation failure
[1824791:0x471d940]   120331 ms: Scavenge (reduce) 4059.6 (4142.1) -> 4059.2 (4142.6) MB, 5.3 / 0.0 ms  (average mu = 0.441, current mu = 0.316) allocation failure


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa7f490 node::Abort() [node]
 2: 0x9a5c4d node::FatalError(char const*, char const*) [node]
 3: 0xc6c2ae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xc6c627 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe360a5  [node]
 6: 0xe65633 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xe721e6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 8: 0xe5e30f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
 9: 0xe5e588 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
10: 0xe503a9 v8::internal::ItemParallelJob::Run() [node]
11: 0xe74170 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
12: 0xe749b3 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
13: 0xe74d75 v8::internal::MarkCompactCollector::Evacuate() [node]
14: 0xe874e1 v8::internal::MarkCompactCollector::CollectGarbage() [node]
15: 0xe433a8 v8::internal::Heap::MarkCompact() [node]
16: 0xe44d38 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
17: 0xe482dc v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
18: 0xe0c1fa v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
19: 0x1162fdb v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
20: 0x14fa139  [node]
Aborted (core dumped)
```

## Environment

-   Typedoc version: 0.20.30
-   TypeScript version: 4.2.3
-   Node.js version: 15.11.0
-   OS: Ubuntu 20.10
-   RAM available: 230 GB

**Comment by Gerrit0** [comment]
The OOMs in those issues were due to a bug in Node on M1 Macs, this is probably something different... but hard to tell since none of that stack trace is in TypeDoc code.

**Comment by Gerrit0** [comment]
This doesn't necessarily appear to be a memory leak - During conversion, we go up to only ~1.7 GB of ram, which then more than doubles when starting to render until Node dies... I gave Node 8 GB ram, and it jumped up to 6GB used for a bit when starting to render before going back down to 3.3GB for rendering the rest of the project.

There's definitely something weird going on with memory here, not sure what the issue is though.

**Comment by Gerrit0** [comment]
However, the generated docs are... useless. The generated search index is 360 MB, which my browser at least just flat can't handle.

**Comment by srknzl** [comment]
A similar thing happens to me on node 12. I am running typedoc in watch mode. For every change memory usage is increased about 50 megabytes. Is it a bug in node or typedoc?

<details>
<--- Last few GCs --->

[12078:0x3cbacb0]  3184399 ms: Mark-sweep 2031.7 (2051.8) -> 2030.5 (2051.3) MB, 637.7 / 0.0 ms  (average mu = 0.188, current mu = 0.242) allocation failure scavenge might not succeed
[12078:0x3cbacb0]  3184527 ms: Scavenge 2031.5 (2051.5) -> 2030.6 (2051.5) MB, 6.3 / 0.0 ms  (average mu = 0.188, current mu = 0.242) allocation failure 
[12078:0x3cbacb0]  3184541 ms: Scavenge 2031.6 (2051.5) -> 2030.7 (2052.0) MB, 5.8 / 0.0 ms  (average mu = 0.188, current mu = 0.242) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13c5b79]
Security context: 0x288f5a6008d1 <JSObject>
    1: getFlowTypeOfReference(aka getFlowTypeOfReference) [0x1fda1c11ffb9] [/home/serkan/forked/hazelcast-nodejs-client/node_modules/typescript/lib/typescript.js:~64166] [pc=0x25bc5db47568](this=0x1d1be78804b1 <undefined>,0x3967ff5e26e9 <IdentifierObject map = 0x390654ac9df9>,0x20981c374d31 <TypeObject map = 0x2ad0b7a67629>,0x20981c374d31 <TypeObject map = 0x2ad0...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20210503.111328.12078.0.001.json
Node.js report completed
 1: 0xa09830 node::Abort() [node]
 2: 0xa09c55 node::OnFatalError(char const*, char const*) [node]
 3: 0xb7d71e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb7da99 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd2a1f5  [node]
 6: 0xd2a886 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd37105 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd37fb5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd3aa6c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd0163b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x104300e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x13c5b79  [node]
Aborted (core dumped)

</details>

Attached the json report 
[report.20210503.111328.12078.0.001.log](https://github.com/TypeStrong/typedoc/files/6413646/report.20210503.111328.12078.0.001.log)

**Comment by Gerrit0** [comment]
That one is almost certainly a bug in TypeDoc, and one that should be relatively easy to track down as well! I suspect it's not the same root cause, however.

**Comment by Gerrit0** [comment]
This seems to have been resolved. Following the instructions in the OP with TypeDoc 0.22.5 works.

I slightly modified the generation command to make 0.22 behave as 0.20 would, and enable more verbose logging:

```
> npx typedoc .\src\compiler\ --tsconfig .\src\compiler\tsconfig.json --entryPointStrategy expand --logLevel Verbose
Debug: Using TypeScript 4.4.3 from C:/Users/gtbir/Documents/GitHub/typedoc/node_modules/typescript/lib
Debug: Converting with 1 programs 68 entry points
Debug: Finished getting entry points in 12042ms
Debug: Begin readme search at ./src
Debug: Refusing to recurse when converting type: readonly T[]
Debug: Refusing to recurse when converting type: readonly Comparator[]
Debug: Refusing to recurse when converting type: readonly Symbol[]
Debug: Refusing to recurse when converting type: readonly ProgramBuildInfoFileId[]
Debug: Finished conversion in 3231ms
Warning: ConcretePragmaSpecs, defined at src\compiler\types.ts:8570, is referenced by binder.ts.PragmaPseudoMap but not included in the documentation.
Warning: PerfLogger, defined at src\compiler\perfLogger.ts:2, is referenced by binder.ts.perfLogger but not included in the documentation.
Warning: tracingEnabled, defined at src\compiler\tracing.ts:9, is referenced by binder.ts.tracing but not included in the documentation.
Warning: PragmaArgumentSpecification, defined at src\compiler\types.ts:8480, is referenced by binder.ts.PragmaDefinition.args but not included in the documentation.
Warning: WatchFactory, defined at src\compiler\watch.ts:437, is referenced by binder.ts.createWatchFactory.createWatchFactory but not included in the documentation.
Warning: PackageJsonInfo, defined at src\compiler\moduleNameResolver.ts:1531, is referenced by binder.ts.getPackageJsonInfo.getPackageJsonInfo but not included in the documentation.
Warning: ScriptTargetFeatures, defined at src\compiler\utilities.ts:562, is referenced by binder.ts.getScriptTargetFeatures.getScriptTargetFeatures but not included in the documentation.
Warning: MapShimConstructor, defined at built\local\shims.d.ts:26, is referenced by binder.ts.ShimCollections.createMapShim.createMapShim but not included in the documentation.
Warning: SetShimConstructor, defined at built\local\shims.d.ts:40, is referenced by binder.ts.ShimCollections.createSetShim.createSetShim but not included in the documentation.
Warning: FileAndDirectoryExistence, defined at src\compiler\watchUtilities.ts:19, is referenced by binder.ts.CachedDirectoryStructureHost.addOrDeleteFileOrDirectory.addOrDeleteFileOrDirectory but not included in the documentation.
Warning: CachedResolvedModuleWithFailedLookupLocations, defined at src\compiler\resolutionCache.ts:45, is referenced by binder.ts.ResolutionCache.getResolvedModuleWithFailedLookupLocationsFromCache.getResolvedModuleWithFailedLookupLocationsFromCache but not included in the documentation.
Warning: Buffer, defined at src\compiler\sys.ts:1155, is referenced by binder.ts.System.bufferFrom.bufferFrom but not included in the documentation.
Warning: PragmaArgumentType, defined at src\compiler\types.ts:8564, is referenced by binder.ts.PragmaPseudoMap.__type.arguments but not included in the documentation.
Warning: CompilerHostLikeForCache, defined at src\compiler\program.ts:195, is referenced by binder.ts.changeCompilerHostLikeToUseCache.changeCompilerHostLikeToUseCache.host but not included in the documentation.
Warning: JsonConversionNotifier, defined at src\compiler\commandLineParser.ts:1892, is referenced by binder.ts.convertToObjectWorker.convertToObjectWorker.jsonConversionNotifier but not included in the documentation.
Warning: SourceFileImportsList, defined at src\compiler\program.ts:532, is referenced by binder.ts.getModeForResolutionAtIndex.getModeForResolutionAtIndex.file but not included in the documentation.
Warning: ModuleResolutionState, defined at src\compiler\moduleNameResolver.ts:99, is referenced by binder.ts.getPackageJsonInfo.getPackageJsonInfo.state but not included in the documentation.
Warning: CompilerHostLike, defined at src\compiler\program.ts:4025, is referenced by binder.ts.parseConfigHostFromCompilerHostLike.parseConfigHostFromCompilerHostLike.host but not included in the documentation.
Warning: PragmaDiagnosticReporter, defined at src\compiler\parser.ts:9314, is referenced by binder.ts.processPragmasIntoFields.processPragmasIntoFields.reportDiagnostic but not included in the documentation.
Warning: Mode, defined at src\compiler\tracing.ts:10, is referenced by binder.ts.startTracing.startTracing.tracingMode but not included in the documentation.
Warning: GetIteratorCallback, defined at built\local\shims.d.ts:1, is referenced by binder.ts.ShimCollections.createMapShim.createMapShim.getIterator but not included in the documentation.
Debug: Renderer: Loading highlighter took 519ms
Info: Documentation generated at ./docs
Debug: HTML rendering took 4417ms
```

The highest memory usage got up to was 700mb.
