### ISSUE TITLE
Cannot build documentation from a single self-contained file of declarations with no imports

### ISSUE THREAD

**Issue by thejohnfreeman** [TypeStrong/typedoc#1537]
On the heels of the issue I just created (#1536), I found a single (generated) declarations file that has much of what I need. I tried to build documentation from just that file, and TypeDoc failed to produce anything meaningful. Just a landing page with the content from the `README.md` in the same directory. No TypeScript content.

## Steps to reproduce the bug

```shell
git clone https://github.com/microsoft/TypeScript.git typescript
cd typescript
npm install
# Building the compiler generates a few necessary source files.
npx gulp tsc
npm install typedoc --save-dev
# The simple instructions on typedoc.org imply this should work.
# The file is entirely self-contained. It has no imports.
npx typedoc lib/typescriptServices.d.ts
```

## Environment

-   Typedoc version: 0.20.30
-   TypeScript version: 4.2.3
-   Node.js version: 15.11.0
-   OS: Ubuntu 20.10

**Comment by Gerrit0** [comment]
Please read the warning messages - they are important! TypeDoc told you this is what would happen.

```
Warning: No compiler options set. This likely means that TypeDoc did not find your tsconfig.json. Generated documentation will probably be empty.
Warning: Unable to locate entry point: C:/Users/gtbir/Documents/GitHub/TypeScript/lib/typescriptServices.d.ts
Rendering [========================================] 100%
Info: Documentation generated at C:\Users\gtbir\Documents\GitHub\TypeScript\docs
Done in 1.14s.
```

This is because TypeDoc 0.20+ requires a tsconfig file in order to properly set up a compiler. Even a trivial one works:

```json
{
  "files": ["lib/typescriptServices.d.ts"]
}
```

**Comment by thejohnfreeman** [comment]
Got it. I'll close with a usability suggestion: just temporarily generate a trivial tsconfig if none is found. Leave the warning, but try a sensible default.
