### ISSUE TITLE
Include custom Handlebars helpers

### ISSUE THREAD

**Issue by mikeloll** [TypeStrong/typedoc#154]
It would be convenient to be able to specify a js file on the command line which contains handlebars helpers.  Much like is included in the typedoc/src/td/output/plugins/MarkedPlugin.ts file on lines 90-95.

```
            Handlebars.registerHelper('markdown', function(arg:any) { return that.parseMarkdown(arg.fn(this), this); });
            Handlebars.registerHelper('compact',  function(arg:any) { return that.getCompact(arg.fn(this)); });
            Handlebars.registerHelper('relativeURL', (url:string) => this.getRelativeUrl(url));
            Handlebars.registerHelper('wbr', (str:string) => this.getWordBreaks(str));
            Handlebars.registerHelper('ifCond', function(v1, operator, v2, options) { return that.getIfCond(v1, operator, v2, options, this) });
            Handlebars.registerHelper('ifSignature', function(obj:any, arg:any) { return obj instanceof models.SignatureReflection ? arg.fn(this) : arg.inverse(this) });

```

This would allow for further customization of the themes.  I would be able to pass in my own helpers.

**Comment by sebastian-lenz** [comment]
Hi Mike, nice to hear from you. We have already changed this for the next version of TypeDoc. v0.4 will automatically load all helpers stored in the <code>/helpers/</code> directory of a theme.

**Comment by mikeloll** [comment]
Thanks, Sebastian!

**Comment by kamranayub** [comment]
Not accurate quite yet, just tested and this must not be implemented in 0.4.1.

**Comment by sclausen** [comment]
Unfortunately, this nifty detail is missing in the documentation on the website http://typedoc.org/guides/themes/#custom-themes, leading to confusion in at least two plugin projects:
[thepalebluedot/typedoc-md-theme](https://github.com/thepalebluedot/typedoc-md-theme) and [kimamula/typedoc-markdown-theme](https://github.com/kimamula/typedoc-markdown-theme)

**Comment by aciccarello** [comment]
@sclausen True. If anyone wants to take a crack at updating the docs you can submit a PR to [TypeStrong/typedoc-site](https://github.com/TypeStrong/typedoc-site)

**Comment by aciccarello** [comment]
See #846 for an alternate way of adding helpers in a plugin.

```typescript
this.application.renderer.theme.resources.deactivate();
this.application.renderer.theme.resources.helpers.addOrigin('custom-helper', `<path-to-my-custom-helper-function>`));
this.application.renderer.theme.resources.activate();
```

**Comment by PissedCapslock** [comment]
Added pointer in https://github.com/TypeStrong/typedoc-site/pull/23

**Comment by Gerrit0** [comment]
Resolved by TypeStrong/typedoc-site#23

**Comment by Aleksandyr** [comment]
@aciccarello I see that the suggested [comment](https://github.com/TypeStrong/typedoc/issues/154#issuecomment-436879216) above is no longer valid with the latest breaking changes.
Can you suggest how we can include a custom handlebars?

**Comment by Dayday10** [comment]
I need help my DNS is not right
