### ISSUE TITLE
Links like this [["path/filename".function_name]] stopped working after upgrading typedoc to version 0.20

### ISSUE THREAD

**Issue by ilyub** [TypeStrong/typedoc#1542]
## Search terms

symbolic link, typedoc 2.0

## Expected Behavior

The code [["path/filename".function_name]] should produce link in documentation.

## Actual Behavior

The code [["path/filename".function_name]] is displayed as plain text in documentation.

## Steps to reproduce the bug

Install old version of typedoc and generate documentation with --mode=modules option.
Then upgrade to typedoc 2.x.
You will get error saying that "mode" is unknown option.
After you remove --mode=modules it will work, but the links like this [["path/filename".function_name]] will be broken though they were working in previous typedoc versions.

So, new version breaks documentation that worked with previous versions.

## Environment

-   Typedoc version: 0.20.30
-   TypeScript version: 4.1.5
-   Node.js version: 14.13
-   OS: Windows 10

**Comment by Gerrit0** [comment]
This is expected behavior. TypeDoc's link resolution behavior hasn't changed. What's changed is that the module names changed so that they would more likely reflect the name used by people who import the module.

**Comment by ilyub** [comment]
I still don't understand what I should do if I have two files with the same function name.

Until recently I could use this: [["path/filename".function_name]]
But now this method does not work.

How should I link to the right function in the right file?

**Comment by ilyub** [comment]
I found that removing quotes solves the issue:
[["path/filename".function_name]]
->
[[path/filename.function_name]]
