### ISSUE TITLE
Document a simple .d.ts file with no export keyword

### ISSUE THREAD

**Issue by librehome** [TypeStrong/typedoc#1546]
## Expected Behavior

I would expect to see the generated document.

## Actual Behavior
But the output is empty.

Can anybody point me a direction? is it possible?

**Comment by krisztianb** [comment]
As far as I know only exports are documented. See: https://typedoc.org/guides/options/#entrypoints

**Comment by Gerrit0** [comment]
TypeDoc has some special casing for global files that makes most reasonable cases work.. and without more information here I'm not sure what you aren't seeing @librehome. The following:

```ts
const x: number
function y(): boolean
```

Will result in documentation for `x` and `y`

![image](https://user-images.githubusercontent.com/19329837/112408048-b1e1ef80-8cdc-11eb-8cb1-67b8a0a897b4.png)

**Comment by librehome** [comment]
Thanks. I've got it to work.
I had to copy the .d.ts file into a separate folder and generate doc only with that file so that other source filed won't pollute the result.
