### ISSUE TITLE
Maximum call stack exceeded when using recursive types

### ISSUE THREAD

**Issue by pyoor** [TypeStrong/typedoc#1547]
## Search terms

maximum call stack recursive

## Expected Behavior
Typedoc should be able to generate documentation for recursive types.

## Actual Behavior
Typedoc raises a maximum call stack error when attempting to generate documentation for recursive types.

## Steps to reproduce the bug
The following is a minimal example that can be used to reproduce this issue:
```typescript
export interface ThingA {
    type: "ThingA"
}

export interface ThingB {
    type: "ThingB"
}

type Things =
    ThingA
    | ThingB

type ValueOrArray<T> = T | Array<ValueOrArray<T>>

/**
 * Test.
 */
export class Test {
    /**
     * Log a thing.
     *
     * @param things - Array of things or a thing.
     */
    log_thing(things: ValueOrArray<Things>): void {
        console.log(things)
    }
}
```

## Environment

-   Typedoc version: 0.20.33
-   TypeScript version: 4.2.3
-   Node.js version: 14.16.0
-   OS: Ubuntu 20.04

**Comment by Gerrit0** [comment]
Thanks for the reproduction! I love single file repros :) This is a somewhat annoying one.. not sure why it's broken at first glance. I thought TS 4.2's check would let us resolve this, but apparently not since it has a type parameter...
