### ISSUE TITLE
Create an example on how to use typedoc within a Monorepo (lerna)

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [TypeStrong/typedoc#1548]
## Search Terms

lerna, monorepo, example

## Problem

I'm currently trying to create a documentation for my Monorepo that is built with lerna. Unfortunately, package relationships don't get resolved as you would expected. Additionally, the _typedoc-plugin-lerna-packages_ plugin does not seem to work anymore.

## Suggested Solution

Add an example on how to handle a situation like this. Maybe there are already options that I'm just not aware of.

**Comment by Gerrit0** [comment]
I'm definitely open to adding a page to the website that describes how this works and linking to an example project that uses this. I don't have any experience with Lerna though, so help creating a simple repo that I can experiment with to figure out the best way to use would be greatly appreciated

**Comment by efokschaner** [comment]
This might even be better framed as support for Yarn "workspaces" (https://classic.yarnpkg.com/en/docs/workspaces/). It defines a package.json extension (`workspaces`) for Lerna and other monorepo tooling to share the source of truth for the monorepo structure.

**Comment by carlocorradini** [comment]
This will be super useful! 🎉

**Comment by efokschaner** [comment]
I was playing around with implementing this today and found that the approach of crawling a package JSON tree is quite different to the support that typedoc currently has for following the tsconfig project references. Mainly the package jsons have no strict connection to things like the tsconfig and the source files that act as the TS entry points. I believe this is surmountable if we actually use the `main` property from the package jsons and require the js to have sourcemaps. The `main` property gives us the JS entry point, and the sourcemap can translate that to a TS entry point. We're still quite reliant on defaults/inference for finding tsconfigs however.

If I get this working, perhaps within a couple of weeks, I'll post a PR. Let me know if anyone has thoughts on this approach.

**Comment by vipulgupta2048** [comment]
Hello folks, I got a mono repo I am looking to document and thinking if this extension might help? https://www.npmjs.com/package/typedoc-plugin-monorepo I am trying this now, will probably make an example/page if it works.

**Comment by efokschaner** [comment]
@vipulgupta2048 let me know how that goes for you.

You may also be interested in trying my fork of typedoc that's currently feeding this PR: https://github.com/TypeStrong/typedoc/pull/1567

I'd be curious to know if it works for you. I'm not sure it supports the per-package readme's that the monorepo plugin supports.

**Comment by Gerrit0** [comment]
I think the instructions in the readme meet this now - 0.21.0 has --packages from #1567.

https://github.com/TypeStrong/typedoc#monorepos--workspaces
