### ISSUE TITLE
Module without exports and with "@module" not included

### ISSUE THREAD

**Issue by letmaik** [TypeStrong/typedoc#1549]
## Search terms

`@module` exports side effects

## Expected Behavior

If a module has a doc string at the top with `@module` it should be included even if it doesn't have any exports. This allows to document modules that are only imported for their side effects, like polyfills.

## Actual Behavior

The module is omitted in the docs.

## Steps to reproduce the bug

```ts
/**
 * This module has side-effects only.
 * 
 * @module
 */

(<any>globalThis).sideEffect = 42;
```

## Environment

-   Typedoc version: 0.20.33
-   TypeScript version: 4.2.3

**Comment by Gerrit0** [comment]
There's a couple things here.

1. A request to revert #1126, which with 0.20's behavior, I'm happy to do.
2. A bug, where TypeDoc doesn't pick up module comments from global files
