### ISSUE TITLE
Generete a new Theme

### ISSUE THREAD

**Issue by daniele-zurico** [TypeStrong/typedoc#155]
Hello all,
I'm trying to generate a new theme from default. I like everything the only thing that I would to do is in the tree menu display mi item in hierarchical mode.
This is how it display:

"heroes/component/hero-component"
"heroes/services/hero-service"
"heroes/services/mock-heroes"

This is how I would be displayed:

-heroes
  -component
    hero-component
  -service
    hero-service
    mock-heroes

I already created a new theme and found where I should change the code (default.hbs) :
<code>  
<nav class="tsd-navigation primary">
                <ul>
                   {{#each navigation.children}}
                        {{> navigation}}
                    {{/each}}
                </ul>
            </nav>
</code>
The problem is that I don't know how to change it. There's no documentation on that.

Is possible to have a little bit of support to introduce my code there?

Thanks,
Daniele

**Comment by sebastian-lenz** [comment]
Hi Daniele, nice to hear from you. The navigation structure is prepared by [NavigationPlugin](https://github.com/sebastian-lenz/typedoc/blob/master/src/td/output/plugins/NavigationPlugin.ts), the plugin creates a structure of [NavigationItem](https://github.com/sebastian-lenz/typedoc/blob/master/src/td/output/models/NavigationItem.ts) instances and updates their activity states for each page. There is a handlebars partial [navigation.hbs](https://github.com/sebastian-lenz/typedoc-default-themes/blob/master/src/default/partials/navigation.hbs) that will render the generated models by recursively including itself.

I guess the navigation items you've listed above are requirejs/amd modules? TypeDoc currently flattens the structure of file based modules and I don't think you can achieve the desired behaviour by making changes to the template. However we are working on a new version that will change this behaviour and individual folders should be represented as separate items within the navigation (and of course pages within the documentation) starting with TypeDoc v0.4.

**Comment by daniele-zurico** [comment]
Thanx for the reply Sebastian, I will try to use the branch 0.4 to see what it will generate. I'm just playing a little bit with angular 2.0 and stuff like that...so nothing for production;)

**Comment by sebastian-lenz** [comment]
I'm sorry that I have to disappoint you but the feature is not yet implemented. It's a planned feature but I'm currently low on time so it looks like I will take me some weeks till I can focus on this one. But I would be happy to keep you informed as soon as it lands.
