### ISSUE TITLE
io-ts types alias are inlined

### ISSUE THREAD

**Issue by antoine-morvan** [TypeStrong/typedoc#1550]
## A bit of context

I'm writing a front/back soft and I'm using io-ts to enforce runtime typing. I design this soft in 3 parts: 1) the shared datamodel; 2) the front (client); 3) the backend (server). The shared datamodel declares types using io-ts and export the Typescript static type for easy reuse (see https://github.com/gcanti/io-ts/blob/master/index.md#typescript-integration).

I'm using typedoc for other projects, but this is the first time I'm using "io-ts". I naturally generated the doc after implementing the first skeletons to discuss some ideas with my team, but was surprised when I discovered how th'e io-ts static types were displayed in the doc: they are fully inlined.

This is a bit of a hindrance for readability. The only solution that would work so far is to declare the ts static type manually, but that would add a bit of maintenance effort / technical debt as each type is duplicated (io-ts structure + ts static type).

I did search a bit, but did not find any solution nor comments saying this is not supported (or I did not understand them ^_^' )

More details below,
Best.

## Search terms

io-ts type alias inline

## Expected Behavior

I expect typedoc to not inline the type aliases when they are declared using io-ts `t.TypeOf<typeof IoTsStructuredType>`, and generate a link to the type declaration as it is for the other types.

## Actual Behavior

Typedoc actually inlines the type.

```typescript
/* src/model/users/User.ts */
export type UserIoTs = t.TypeOf<typeof UserType>;

export type UserManual = {
  userId: string;
  email: string;
} & {
  teams: string[];
};

/* src/client/ClientAPI.ts */
export class ClientAPI {
  public async listUsersIoTs(): Promise<UserIoTs[]> {
    return Promise.resolve([]);
  }
  public async listUsersManual(): Promise<UserManual[]> {
    return Promise.resolve([]);
  }
}
```
![image](https://user-images.githubusercontent.com/18552103/112321697-8ea14b00-8cb0-11eb-9420-6a3be936a752.png)

## Steps to reproduce the bug

I setup a small project to reproduce here : https://github.com/antoine-morvan/typedoc-io-ts-66c5a2ae6091

## Environment

-   Typedoc version: 0.20.33
-   TypeScript version: 4.1.5
-   Node.js version: 14.15.5
-   OS: Ubuntu 18.04.5 LTS 4.15.0-137-generic x86_64 GNU/Linux

**Comment by Gerrit0** [comment]
This is unfortunately a design limitation given how TypeDoc 0.20+ resolves types. In order to properly deal with generic classes and concrete classes inheriting from them, we have to ask the compiler for the return type of properties/methods on classes/interfaces. When we do this, TypeScript loses some information about the type. If you hover over the method, you'll see the expected type, but the type that TypeDoc gets back from the compiler is:

```ts
type Converted = ReturnType<ClientAPI['listUsersIoTs']>
// type Converted = Promise<({
//     userId: string;
//     email: string;
// } & {
//     teams: string[];
// })[]>
```

TypeScript (and therefore TypeDoc) will preserve the alias if you modify the type slightly:

```ts
export type UserIoTs = {} & t.TypeOf<typeof UserType>;
```

**Comment by antoine-morvan** [comment]
> TypeScript (and therefore TypeDoc) will preserve the alias if you modify the type slightly:
> 
> ```ts
> export type UserIoTs = {} & t.TypeOf<typeof UserType>;
> ```

 That's good enough for me. Thanks for the quick reply :)

**Comment by antoine-morvan** [comment]
> > TypeScript (and therefore TypeDoc) will preserve the alias if you modify the type slightly:
> > ```ts
> > export type UserIoTs = {} & t.TypeOf<typeof UserType>;
> > ```
> 
> That's good enough for me. Thanks for the quick reply :)

I spoke too fast: I tried prepending the type with `{} &` but the generated typedoc is still the same. 

![image](https://user-images.githubusercontent.com/18552103/112444286-299c3280-8d4e-11eb-9c63-bd6787ae6d4e.png)


(generated after : https://github.com/antoine-morvan/typedoc-io-ts-66c5a2ae6091/commit/cd7ac886e6ead245e57be03cbf29f31dffdff4b6)

**Comment by Gerrit0** [comment]
Huh - that's weird... It works if you upgrade TypeScript to 4.2

**Comment by antoine-morvan** [comment]
Indeed it works much better with typescript 4.2.3 & typedoc 0.20.34.

I still have the issue for 1 type only (deep combination of arrays of types ...). I will try to reproduce on the small project.

**Comment by antoine-morvan** [comment]
OK, done with a quite small type. Reusing the UserType from above, I declare the following io-ts type:
```
export const UserFriendsFavCompositionType = t.type({
  users: t.array(UserType),
  friends: t.array(t.string),
  favorites: t.array(t.string)
});

// see https://github.com/TypeStrong/typedoc/issues/1550
// eslint-disable-next-line @typescript-eslint/ban-types
export type UserFriendsFavComposition = {} & t.TypeOf<typeof UserFriendsFavCompositionType>;
```

The generating the doc still ends up with inlined type, but for this complex type only :
![image](https://user-images.githubusercontent.com/18552103/112982980-66f12d80-915d-11eb-862d-f59a70179cfc.png)

Sample available on the new branch https://github.com/antoine-morvan/typedoc-io-ts-66c5a2ae6091/tree/complexType

**Comment by Gerrit0** [comment]
This one's more annoying TypeDoc is failing somewhere in the conversion of this and bailing out with a request to TS to just give us the stringified type.

Unfortunately, even fixing this wouldn't fix the issue, since TypeScript doesn't want to preserve the alias (not sure why the intersection trick doesn't work here...)

Something you could try (which I'd argue results in likely better docs anyways) is using an interface instead of a type. TS will always preserve interface names, which makes this just work.

```ts
export interface UserFriendsFavComposition
  extends t.TypeOf<typeof UserFriendsFavCompositionType> {}
```

**Comment by antoine-morvan** [comment]
Indeed this works for all the types. Thanks for the tip :)
