### ISSUE TITLE
Optional search in descriptions

### ISSUE THREAD

**Issue by letmaik** [TypeStrong/typedoc#1553]
## Search Terms

search description

## Problem

The current search only works on type names. It would be nice if optionally the search would cover the description texts of types as well.

## Suggested Solution

Sphinx has a full-text search across all pages. I haven't looked in detail how they do it but I think the general technique is the same, just that the index is bigger.

**Comment by Gerrit0** [comment]
I'd be open to this, definitely needs to be optional since search indices can get really big with large projects.

**Comment by ronalddas** [comment]
It will be useful, dont have to keep on switching between notion and docs
