### ISSUE TITLE
Package scope ignored when resolving types

### ISSUE THREAD

**Issue by lobsterkatie** [TypeStrong/typedoc#1554]
## Expected Behavior

1. Typedoc correctly resolves types from both `react` and `@sentry/react` and doesn't confuse the two.
2. (I suspect this will happen if the first one happens) Typedoc is able to see properties and methods all the way up the prototype chain when a class in `@sentry/react` extends a class in `react`.

## Actual Behavior

1. Typedoc searches `@sentry/react` (one of the packages being documented) for types it should be finding in `react`, and doesn't find them.
2. Typedoc is unable to climb the prototype chain to see inherited properties and methods when a class in `@sentry/react` extends a class in `react`.

## Steps to reproduce the bug

I grant that this is far from minimal, but we're open source, so you actually can reproduce the behavior exactly.

1. Clone https://github.com/getsentry/sentry-javascript
2. Run `yarn`
3. `cd` into `packages/react` and run `yarn` again
4. `cd` back to the root level and run `yarn build` and then `make build-docs`

Though there are multiple problem spots, I'll draw your attention to one particular example where this is happening, namely in our `ErrorBoundary` class [here](https://github.com/getsentry/sentry-javascript/blob/a6f8dc26a4c7ae2146ae64995a2018c8578896a6/packages/react/src/errorboundary.tsx#L59).

In simplified form, we have
```
import * as React from 'react'

class ErrorBoundary extends React.Component { ... }
```

Which leads to `Property 'Component' does not exist on type 'typeof import("/Users/Katie/Documents/Sentry/sentry-javascript/packages/react/dist/index")'.`

Then we have
```
class ErrorBoundary extends React.Component {
  public componentDidCatch(error: Error, { componentStack }: React.ErrorInfo): void {...}
}
```

which leads to `Namespace '"/Users/Katie/Documents/Sentry/sentry-javascript/packages/react/dist/index"' has no exported member 'ErrorInfo'.`

Finally, we have 
```
  public componentDidCatch(error: Error, { componentStack }: React.ErrorInfo): void {
    const { beforeCapture, onError, showDialog, dialogOptions } = this.props;
  }
```

which leads to `Property 'props' does not exist on type 'ErrorBoundary'.`. This last one I think is just a side effect of the first one - we inherit from `React.Component`, but it can't find it, so it doesn't know that it provides the `props` property. You can solve this last problem by adding the following to the top of the class:

```
class ErrorBoundary extends React.Component {
  readonly props!: Readonly<ErrorBoundaryProps> & Readonly<{ children?: React.ReactNode }>;

  public setState<K extends keyof ErrorBoundaryState>(
    state:
      | ((
          prevState: Readonly<ErrorBoundaryState>,
          props: Readonly<ErrorBoundaryProps>,
        ) => Pick<ErrorBoundaryState, K> | ErrorBoundaryState | null)
      | (Pick<ErrorBoundaryState, K> | ErrorBoundaryState | null),
    callback?: () => void,
  ): void {
    super.setState(state, callback);
  }
}
```

but again, I suspect that's just treating the symptom rather than the cause.

This also affects third-party libraries, as when `hoist-non-react-statics` [tries to use `React.ComponentType`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/538483917491e9adedc58502103d642796fc7bae/types/hoist-non-react-statics/index.d.ts#L52), leading to `Namespace '"/Users/Katie/Documents/Sentry/sentry-javascript/packages/react/dist/index"' has no exported member 'ComponentType'.`

(The above problems also affect our `Vue` package, `@sentry/vue`.)

## Environment

-   Typedoc version: 0.18.0* 
-   TypeScript version: 3.7.5
-   Node.js version: 14.16.0
-   OS: OSX Catalina (10.15.7)

\* I also tried upgrading to 0.20.x, but could not for the life of me get it set up correctly - on that score I'll keep trying and ask separately if I need to. (Unless the upgrade is critical to solving the main issue here, I'm fine staying on 0.18.0 for the moment.)

**Comment by Gerrit0** [comment]
TypeDoc before 0.20 does a multitude of bad things with regard to setting up the compiler.. so it not too surprising that it can't do it here. If you can get tsc to compile with `tsc -p some.tsconfig.json` and point TypeDoc at the same tsconfig, it might work.

TypeDoc 0.18 doesn't support TypeScript older than 3.8.3. You will get a crash if you get past the compiler errors (0.18 has an `--ignoreCompilerErrors` flag, bad idea, but it exists...)

I spent about 45 minutes playing with it, but gave up. This repro is too big. If you upgrade to a version of TypeScript that 0.20 supports, I expect you'll have much better luck there. A naive attempt to do so reveals there are a ton of compiler errors...

**Comment by lobsterkatie** [comment]
@Gerrit0 - thanks for the reply, and for looking into it. Sounds like we'll need to upgrade, a least as a first debugging step. I'll give it another shot and let you know if continue to run into snags. FWIW, the code compiles just fine - under the TS 3.7.5 we use (so that our SDK remains compatible with more folks' apps) but also under TS 3.8.3 and TS 4.2.3. I'm not sure why it was showing up with compiler errors for you... 🤔

**Comment by Gerrit0** [comment]
I was compiling from the root directory like TypeDoc does - with `npx tsc -p tsconfig.json`

**Comment by Gerrit0** [comment]
Closing as this is unactionable without a smaller reproduction.

**Comment by lobsterkatie** [comment]
> I was compiling from the root directory like TypeDoc does - with `npx tsc -p tsconfig.json`

Sorry, missed this somehow. But ah, that probably explains it - our builds use tsconfig files which are extensions of the main one, so it wouldn't surprise me if compiling breaks without the extra config they provide. I haven't had a chance to dig back into this, but I'll let you know if and when I do. Thanks. 🙂
