### ISSUE TITLE
FR: Different output formats 

### ISSUE THREAD

**Issue by backnotprop** [TypeStrong/typedoc#1555]
## Search Terms

Output format, docx, pdf, word doc, output different file formats

## Problem

Most of us develop for a living, so documentation is key & in enterprise environments an HTML site doesn't cut it. 

## Suggested Solution

output docx files, pdf, even uml

**Comment by Gerrit0** [comment]
I don't plan to do anything like this in the main typedoc repo - In my very limited experience with Word APIs, it is a royal pain... and I'd like to spend the limited time I have here on HTML. There is a plugin, [typedoc-plugin-markdown](https://www.npmjs.com/package/typedoc-plugin-markdown) that you could use to generate markdown and throw that through some md -> pdf converter.
