### ISSUE TITLE
Update the examples folder with a real example

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1556]
The `examples/basic` folder might have originally contained an example, but has been used for UI tests for a really long time. Conflating these two things was a bad idea, since it means that the examples folder that ~80 people look at every week contains almost useless info.

**Comment by srmagura** [comment]
I could work on this if you want @Gerrit0.

What should the existing `examples` folder be renamed to? `testProjects`?

What would you like to see in the new example? I have a variety of already-commented code that I could pull from. Or I could write some new code just for this.

**Comment by Gerrit0** [comment]
That would be great! I'm not too particular about what to call the visual tests - it might actually be best to move it into src/test/renderer.

Ideally what I'd like to see in an example is something that shows how TypeDoc handles language constructs, so something with exported variables, classes, functions, overloaded functions, etc...

I'd also like to include features which people might not immediately think about, like a class `X extends Array<string>` which resolves the type parameters in inherited methods, and other special casing, like changing `as const` variables into enums with `@enum` (#1675), detecting variable-functions and displaying them as functions, exporting the same variable under an alternative name... probably other stuff I'm missing.

Once this is done, I'd really like to prominently link to both the example folder and generated documentation on the website.

**Comment by srmagura** [comment]
Thanks for the guidance 🙂. I will probably work on this this weekend.

- I think the `example` folder should have its own `package.json` and `tsconfig.json`. I was planning on adding React as a dependency of the example project so that I can show how to document a React component.
- Do you want the generated documentation to be committed or gitignored?

**Comment by Gerrit0** [comment]
Separate package/config - I agree. React sounds fine.

The generated output should be .gitignored, it will be published on typedoc-site, but I think rebuilding it like /api is done today is the right way to go about it.
