### ISSUE TITLE
Fail build on invalid symbol links 

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1568]
After renaming some functions, I noticed that the documentation website contained some broken links. E.g. `{@link Foo}` wasn't linked because `Foo` got renamed and instead, the website contained the literal text "{@ link Foo}".

I searched for an option to a) get all invalid symbols and b) a way to fail the build if it contains invalid symbols so this doesn't happen again.

The `--listInvalidSymbolLinks` was easy enough to find but is there any way to fail the build?

**Comment by Gerrit0** [comment]
Currently no, there's no way to fail a build if there are warnings. I'd be open to a new `treatWarningsAsErrors` (or possibly other name?) option

**Comment by RunDevelopment** [comment]
Thank you @Gerrit0!
