### ISSUE TITLE
[help/bug] typedoc does not generate documentation for parameter types

### ISSUE THREAD

**Issue by soanvig** [TypeStrong/typedoc#1569]
**Project**: https://github.com/soanvig/jsr/tree/v2

**typedoc version**: 0.20.35

**command**: `yarn typedoc ./src/JSR.ts`

**Problem**: 

Generating typedoc for https://github.com/soanvig/jsr/blob/v2/src/JSR.ts file generates documentation without parameter types **if** the type is `interface` or `type`.

I have generated documentation for that class. But I'm trying everything, and just cannot generate documentation, that will include types for constructor or method, that accepts callback (which is defined by `type`), as so:

![Screenshot_2021-04-13 JSR mm-jsr](https://user-images.githubusercontent.com/7525286/114615104-8d5ab100-9ca5-11eb-9c3c-cf3e26ed18c0.png)

![Screenshot_2021-04-13 JSR mm-jsr(1)](https://user-images.githubusercontent.com/7525286/114615134-977caf80-9ca5-11eb-81c5-46db2192546f.png)

As You see both interface Ctor and type `ValueChangeHandler` are not linked to anything (and `JSR` class is linked to itself as returned value from constructor).

**Comment by Gerrit0** [comment]
At a first glance this looks like expected behavior. `Ctor` isn't exported, so typedoc won't document it.

**Comment by christocracy** [comment]
I've recently upgraded to latest `typedoc` from a very old version.  I'm experiencing this as well.  None of the function param or return value symbols are linked.

![](https://dl.dropbox.com/s/0bvtlzepknx1qxb/Screen%20Shot%202021-04-14%20at%2010.18.53%20AM.png?dl=1)

In the above example, the interface `Location` *is* `export`ed.

```typescript
declare module "the-module-name" {
  export interface Location {
    .
    .
    .
  }
}
```

This `interface Location` exists in its own file, relative to the method `onLocation` in the screenshot above.

```typescript
/// <reference path="interfaces/Location.d.ts" />

declare module "the-module-name" {
  export default class TheClassName {
    static onLocation(success: (location:Location)=>void, failure?:(errorCode: LocationError) => void):void;
  }
}
```

**Comment by christocracy** [comment]
```
$ typedoc --version

TypeDoc 0.17.8

$ typedoc --out docs \
        --includeDeclarations \
        --excludeExternals \
        --listInvalidSymbolLinks \
```

**Comment by christocracy** [comment]
Hmm...seems I'm not using the latest typedoc (`0.20.35`) and latest no longer has support for `includeDeclarations`.

**Comment by christocracy** [comment]
Ok, I've figured out my issue after upgrading to `0.20.35` and implementing `tsconfig.json` as suggested in #1558.

**Comment by soanvig** [comment]
@Gerrit0 sorry, but this sounds ridiculous. I understand the idea, but this makes the usage unreasonable.

Even if I export my Ctor, it includes Config, which includes more stuff. It's like I have to export half of a project and interfaces now?

Gonna verify it, although I don't like the idea.

**Comment by soanvig** [comment]
@Gerrit0 
Thank You for Your help and time, I apprieciate this very much.

I've hit the same problem I hit last time, when I tried exporting Ctor.

I've exported Ctor, and yes, Ctor is documented, but the `ConfigAttrs` inside Ctor is not documented, despite being exported from `src/models/Config`

**Comment by Gerrit0** [comment]
It doesn't seem ridiculous to me to only document your public API surface.... why would anyone care about your implementation details who isn't looking at the implementation and therefore has the code right in front of them? TypeDoc 0.20+ documents your project according to the entry points of your package, not by traversing every random file and potentially picking up internal util modules.

That said, you aren't the only one resistant to exporting types. There's a plugin that forces typedoc to document everything. https://www.npmjs.com/package/typedoc-plugin-not-exported, alternatively, give TypeDoc the root directory of your project as an entry point and try https://www.npmjs.com/package/typedoc-plugin-merge-modules to merge all the modules into a super-module if you aren't documenting a library.

**Comment by soanvig** [comment]
Thanks for help anyway. Of course it makes sense to document API surface only. But if my "public" API has "private" dependency, then this should be pulled (as direct dependency, indirect should not be pulled). Nevertheless, I appreciate Your help :)

**Comment by soanvig** [comment]
But, as I said in my last post - everything was exported, and still the dependency was not pull, so...

**Comment by Gerrit0** [comment]
There's a difference between "exported" and "exported from an entry point", which it looks like you've figured out. The file that exports your public API is the way to go, that makes usage easy for your library consumers, and doc generation work well as well.

**Comment by soanvig** [comment]
I'm not sure if documentation is clear then, about this mechanism.

Maybe I'm the only one that had problems with that.

What do You think?

**Comment by Gerrit0** [comment]
That very well may be, those that followed the development of 0.20 all seemed to understand it, but I have seen a large number of people being confused by this.... I'm definitely open to suggestions/prs for how better to present this to reduce the confusion.
