### ISSUE TITLE
Do not include master README.md in typedoc docs folders

### ISSUE THREAD

**Issue by a-tylenda** [TypeStrong/typedoc#1570]
Hi, 
I am, not sure if this question has already popped. I searched through issues but I didn't find any answer. 
While creating typedoc documents from my `packages`folder my master `README.md` is copied into the folder where typedoc documents are generated. 

![image](https://user-images.githubusercontent.com/61054769/114708671-f258ea00-9d2b-11eb-947b-9d827d099cf6.png)

I don't want this README.md there. How do I exclude it? `exclude` option does not work:
```
    "typedocOptions": {
        "entryPoints": ["src/index.ts"],
        "out": "../../docs/model",
        "plugin": "typedoc-plugin-markdown",
        "exclude": "../../README.md"  
    }
```

**Comment by Gerrit0** [comment]
For HTML docs, the readme (https://typedoc.org/guides/options/#readme) option controls this. If that doesn't work, this is probably a question for the typedoc-plugin-markdown repo.

**Comment by rendunia** [comment]
Thank you for your answer. I tried this (https://typedoc.org/guides/options/#readme), unfortunately it doesn't work as well. I will ask typedoc-plugin-markdown repo. Thank you and have a lovely day!

**Comment by linonetwo** [comment]
"readme": "none",

This does not work

  "readme": "",

this cause 

[error] Provided README path, ./ could not be read.

**Comment by linonetwo** [comment]
Sorry, `  "readme": "none",` works.
