### ISSUE TITLE
Including non exported function in generated Documentation

### ISSUE THREAD

**Issue by DaliborBoldis** [TypeStrong/typedoc#1574]
I am facing an issue to include a non exported function to appear in the generated documentation. I am fairly new to TypeScript (and Typedoc as well) it still confuses me what works and what does not, and some online tutorials are no longer relevant.

`import HubRepository from '../../database/repositori...;`
`import HubGroupUserRepository from '../../database/repositori...;`

`/**`
 `* Raw handler to handle approving assets`
` * @param event`
 `* @returns Returns message to inform the user if an asset has been approved`
 `* @notExported`
` */`
 `const rawHandler = async (`
   `event: APIGatewayEvent<DefaultEvent>,`
`): Promise<APIGatewayResponse<AssetResponse | IdResponse>> => {`
    `const { sub: cognitoId } = event.requestContext.authorizer.claims; // Defines cognitoId > APIGatewayProxyCognitoAuthorizer`
`(name) - node_modules\@types\aws-lambda\trigger\api-gateway-proxy.d.ts`
    `const { hubId, assetId } = event.pathParameters;`
`...`

At the bottom of the file:

`export const handler = middy(rawHandler)`
    `.use(jsonBodyParser())`
`...`

In the generated documentation, only the "handler" variable appears, but I would like it to include the "rawHandler" variable as well. As you might notice, I already tried using "@notExported" with the additional plugin, but it still does not work.

Also, is there a possibility to include inline comments in the documentation?

Thank you!

**Comment by krisztianb** [comment]
By default TypeDoc only documents your external API and no internal (non exported) details.

But it should be possible to do so using a particular TypeDoc plugin: https://github.com/TypeStrong/typedoc/issues/1569#issuecomment-820067984

**Comment by soanvig** [comment]
I just created `api.ts` file with all exported types I want to have in my documentation.

**Comment by Gerrit0** [comment]
> Edit: Sorry, I just saw that you already tried that. Is the plugin loaded correctly? There should be an according message in the output of TypeDoc saying that the plugin is loaded.

This ^ I suspect the plugin isn't getting loaded as well.

> Also, is there a possibility to include inline comments in the documentation?

By inline comments do you mean the comments within your function body? If so, no. If you mean using `//` comments instead of `/*` comments for the function, that's being tracked under #1433.

**Comment by Gerrit0** [comment]
If you could point me towards a project that replicates the issue, there's a better chance I'll be able to help, right now I'm pretty much just guessing

**Comment by DaliborBoldis** [comment]
@Gerrit0 Unfortunately, this is a private project and I cannot make it publicly available. The main problem for me is that I am not even sure how to have you replicate the issue. The developers that we hired did not provide us with any documentation whatsoever, and it's now up to me to make the documentation from the available Back end code. Of course, there is no point to create it manually. Is there any way to have you (or someone else) join in a TeamViewer session so that you can investigate the issue?

**Comment by Gerrit0** [comment]
I don't do live support - don't have the time for it.

The way I'd create a repro is to create a new project that just contains the minimal dependencies to build docs (typescript + typedoc + typedoc-plugin-not-exported), your tsconfig.json and typedoc.json (if you have one) and a npm script that builds the documentation. As is, I don't see anything obvious that you're doing wrong, but often recreating the setup results in finding the issue

**Comment by Gerrit0** [comment]
Closing as unactionable
