### ISSUE TITLE
Subpaths with TypeDoc

### ISSUE THREAD

**Issue by IceeMC** [TypeStrong/typedoc#1575]
## Search Terms

HTTP Subpaths, assets

## Problem

Currently, if you were to go to `https://docs.my.site/<project>`
The HTML file would have `<link rel="stylesheet" href="assets/css/main.css">`
However, if I want to have that behind a proxy i.e nginx, I would need an option to make that element
`<link rel="stylesheet" href="/<project>/assets/css/main.css">` so that NGINX picks it up and routes it properly.

## Suggested Solution

Add an option to do so, `--subPath=/<project>`, or a config option

**Comment by Gerrit0** [comment]
I don't understand what you're asking for here... TypeDoc explicitly uses relative paths so that the generated docs will work if dropped into a subfolder (TypeDoc's docs are - https://typedoc.org/api/). If your proxy doesn't work with relative links, that's a configuration issue with your proxy.
