### ISSUE TITLE
Docs include types from excluded files

### ISSUE THREAD

**Issue by domoritz** [TypeStrong/typedoc#1578]
https://github.com/apache/arrow/blob/ca83a14e264d00c6b4b29560cc2816c6718f52e7/js/typedoc.js#L26 excludes `src/fb/*.ts` but the types from it still appear in the docs when built with `yarn doc`. 

<img width="1252" alt="Screen Shot 2021-04-25 at 20 55 21" src="https://user-images.githubusercontent.com/589034/116026949-8ff3c980-a608-11eb-99ab-7ad71ccba934.png">

I would expect them to not be in the docs. 

## Environment

-   Typedoc version: 0.20.35
-   TypeScript version: 4.0.2
-   Node.js version: 14
-   OS: macOS

**Comment by Gerrit0** [comment]
This is expected behavior:

> This option will **only** be used to filter entry points specified under directories. - [exclude docs](https://typedoc.org/guides/options/#exclude)

**Comment by Gerrit0** [comment]
There is a plugin that provides the type of filtering you're looking for: https://github.com/Gerrit0/typedoc-plugin-banish

**Comment by Gerrit0** [comment]
Thinking about this some more, it does seem reasonable to extend `exclude` to also work here. I'm open to treating this as a feature request. Needs to be a part of 0.21 though, breaking change.

**Comment by domoritz** [comment]
Thank you for the suggestions. I'll try them. And yea, it would be great to refine the exclude behavior in the next version.

**Comment by domoritz** [comment]
`typedoc-plugin-banish` does not seem to work

<img width="494" alt="Screen Shot 2021-04-26 at 15 19 30" src="https://user-images.githubusercontent.com/589034/116158019-ce3dc700-a6a2-11eb-88cb-1922f4d183c1.png">

<img width="1090" alt="Screen Shot 2021-04-26 at 15 20 00" src="https://user-images.githubusercontent.com/589034/116158069-deee3d00-a6a2-11eb-8806-d415c9a6e037.png">

**Comment by domoritz** [comment]
`externalPattern` does exactly what I want. I think it would make sense to make exclude work like externalPattern. 

<img width="530" alt="Screen Shot 2021-04-26 at 15 23 38" src="https://user-images.githubusercontent.com/589034/116158358-620f9300-a6a3-11eb-808c-976a9e9c5c29.png">
