### ISSUE TITLE
when have interface which inherit from multiple interfaces, we get only the first in result.

### ISSUE THREAD

**Issue by nisimjoseph** [TypeStrong/typedoc#1579]
## Search terms

multiple interfaces extends 

## Expected Behavior

the export doc need to show all the interfaces which the new interface derived from when using Partial<> for the interfaces.

## Actual Behavior

see all extends, it see only the first.

## Steps to reproduce the bug

1. add to file:
```ts
interface Shape extends Partial<BaseShape1>, Partial<BaseShape2> {}
```

2. run typedoc and you will see only the "BaseShape1" interface included in the doc.

## Environment

-   Typedoc version: 0.20.36
-   TypeScript version: 4.x
-   Node.js version: 14.16.x
-   OS: MAC

**Comment by krisztianb** [comment]
What is `BaseShape1`?

**Comment by Gerrit0** [comment]
This is a bug in [`ReferenceType.equals`](https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/types/reference.ts#L89). Currently it only checks the type name. It should also check that the type args are equal.

**Comment by krisztianb** [comment]
It doesn't check the name or am I mistaken? It checks if the references point to the same object.

**Comment by Gerrit0** [comment]
It effectively checks the name by checking the pointed-to symbol. The name might be different even if the symbol is the same due to import aliases.
