### ISSUE TITLE
Descriptions of overridden methods are missing.

### ISSUE THREAD

**Issue by donmccurdy** [TypeStrong/typedoc#1580]
## Search terms

inherit, inherited, override, overridden, missing documentation

## Expected Behavior

If a parent class declares a method that is overridden by child classes, the description provided with the parent method should be shown unless a child class provides its own description.

## Actual Behavior

If the child class does not provide a new method description when overriding a method, no method description is rendered in the docs.

## Steps to reproduce the bug

Given a simple project...

```ts
/** Class is documented. */
export class A {
    /** This method does a thing. */
    run(): void {
        console.log('A');
    }
}

/** Class is documented. */
export class B extends A {
    run(): void {
        super.run();
        console.log('B');
    }
}

/** Class is documented. */
export class C extends B {
    run(): void {
        super.run();
        console.log('C');
    }
}
```

... generate documentation with something like:

```
typedoc src/core.ts --out docs/ --excludeNotDocumented --theme minimal
```

The problem occurs whether `--excludeNotDocumented` is given or not, but the flag is helpful to my project so I thought I'd call it out as an additional case here: missing documentation on a child class does not prevent the method from appearing in the docs; only the description goes missing.

Despite the documenation on `A.run` above, inspecting `C.run` will show no description:

![Screen Shot 2021-05-02 at 10 21 56 PM](https://user-images.githubusercontent.com/1848368/116843466-df03a680-ab94-11eb-8a22-34303b2b2e5d.png)

## Environment

-   Typedoc version: 0.20.36
-   TypeScript version: 4.2.4
-   Node.js version: 14.14.0
-   OS: macOS Big Sur 11.3

**Comment by donmccurdy** [comment]
Forgot to mention — this case was working for me pre-0.20, I ran into the issue when attempting to upgrade.

**Comment by Gerrit0** [comment]
That's really weird... I could have sworn we had a test case for this one.

**Comment by donmccurdy** [comment]
Here's a stripped-down version of my project if it's helpful:

[DocsRepro.zip](https://github.com/TypeStrong/typedoc/files/6416410/DocsRepro.zip)

Methods that are inherited but not overridden are displayed just fine, it's just undocumented overrides that lose descriptions.

**Comment by donmccurdy** [comment]
Thanks @Gerrit0! Unfortunately the bugfix in https://github.com/TypeStrong/typedoc/commit/d5bb930c880e5a6fa0e2903fc4dec6edfc865333 appears to fix the simple A>B>C case provided above, but not another version of the problem in the same .ZIP file above. The class inheritance hierarchy is:

- Property
  - ExtensibleProperty
    - Camera

`Property.ts` defines a `copy(...)` method, and each subclass overrides it. The description of the method is shown for the first two, but not for Camera... I'm not sure why that would behave differently than the A>B>C example earlier.

**Comment by Gerrit0** [comment]
Aww shoot, I don't think I ever even downloaded the zip. I'll have to take another look

**Comment by Gerrit0** [comment]
Shoot. This is because of reflection ordering... The fix for this requires the implements plugin keeping track of inheritance so that it doesn't do child classes before parent classes.

```
Analyze inheritance B
Analyze inheritance C
Analyze inheritance Camera
Analyze inheritance ExtensionProperty
Analyze inheritance ExtensibleProperty
Analyze inheritance Property
Analyze inheritance Node
Analyze inheritance Scene
```
