### ISSUE TITLE
How to document functions imported inside class methods?

### ISSUE THREAD

**Issue by OmarOmeiri** [TypeStrong/typedoc#1581]
In this example I have a central class `class1.ts` that has three methods. The first has an imported static method from another class `./class2.ts`, the second has an imported plain function from `./func.ts` and the third returns a function. How can I reference these imported functions? Don't need to  display their whole comments, but just a small reference telling someone looking this class doc that these imported stuff is there. How would someone looking this class doc understand what is going on inside these methods?

the central class that imports everything:

`class1.ts`
```
/**
 * this is class1 module
 * @module Class1
 */

import class2 from './Class2';
import func from './func';

export class Class1 {
  /**
   * This is the crazy log method with imported static method
   * @param str
   */
  crazyMethod(str: string): void {
    /**
     * Even trying to comment this does not show in docs. {@link  Class2.logString}
     */
    class2.logString(str);
  }

  /**
   * This is the crazy log method with imported function
   * @param str
   */
  crazyMethodFunc(str: string): void {
    /**
     * Imported simple function {@link FunctionModule.logString}
     */
    func(str);
  }

  /**
   * This is the method that returns a function
   * @param str 
   * @returns 
   */
  methodWithLocalFunction(str: string): (a: number, b: string) => void {
    /**
     * This is the returned function
     */
    return function returnFunc(a: number, b: string): void {
      console.log(`${a}${b}`);
    };
  }
}
```

the class with the static method:

`class2.ts`

```
/**
 * This is Class2
 * @module Class2
 */
class class2 {
  /**
   * This is the logString static method
   * @param str
   */
  static logString(str: string): void {
    console.log(str);
  }
}

export default class2;
```

the plain exported function: 

`func.ts`

```
/**
 * This is the logString simple exported function
 * @param str
 */
const logString = (str: string): void => {
  console.log(str);
};

export default logString;
```

And this is the output from typedocs for `class1.ts`.

![TypeDocOutput](https://user-images.githubusercontent.com/46783176/116951530-7e40a080-ac5e-11eb-935a-a52ccb99e75d.png)

Am I missing something here? I'm sorry if this is a not valid issue, or this is how it is supposed to work, but I scoured the documentation, issues page and the examples. And solution not found.

**Comment by krisztianb** [comment]
The purpose of TypeDoc is to document the external API of your (library) code. Internal details are not documented. So if `class2` and the `logString` functions are not "visible" from the outside they won't get documented.

You could try this plugin: https://www.npmjs.com/package/typedoc-plugin-not-exported to include internal types into your documentation.

**Comment by Gerrit0** [comment]
krisztianb has the right idea here. TypeDoc isn't meant to be used to document every line of code, it is meant to be used to describe a module's API surface - what is exported. Comments within a function are notes for those maintaining the function, not a description of the API surface, and are therefore not included.

**Comment by OmarOmeiri** [comment]
Ok, thank you all for the time to respond. Already tried the not exported plugin. Although, I created a solution on my own. I used the typescript compiler to get my inner function names, parameters and return types and made a script that alters the html generated by TypeDoc. Now I can have the best of both worlds. Thanks anyway!

**Comment by akashdeepsharma1991** [comment]
@OmarOmeiri can you share that code here.. lots of ppl looking for a solution

**Comment by akashdeepsharma1991** [comment]
> Ok, thank you all for the time to respond. Already tried the not exported plugin. Although, I created a solution on my own. I used the typescript compiler to get my inner function names, parameters and return types and made a script that alters the html generated by TypeDoc. Now I can have the best of both worlds. Thanks anyway!

can u please share the code would be very helpful

**Comment by OmarOmeiri** [comment]
> > Ok, thank you all for the time to respond. Already tried the not exported plugin. Although, I created a solution on my own. I used the typescript compiler to get my inner function names, parameters and return types and made a script that alters the html generated by TypeDoc. Now I can have the best of both worlds. Thanks anyway!
> 
> can u please share the code would be very helpful

@akashdeepsharma1991 

Here you go!
This is the file that gets all methods inside a class.
```

import * as ts from 'typescript';
import * as fs from 'fs';

interface DocEntry {
  name?: string;
  fileName?: string;
  comment?: string;
  type?: string;
  constructors?: DocEntry[];
  parameters?: DocEntry[];
  returnType?: string;
  methods?: {
    name?: string,
    type?: string,
    comment?: string,
  }[]
}

/** Generate documentation for all classes in a set of .ts files */
function generateDocumentation(
  fileNames: string[],
  options: ts.CompilerOptions,
): void {
  // Build a program using the set of root file names in fileNames
  const program = ts.createProgram(fileNames, options);
  const checker = program.getTypeChecker();
  const output: DocEntry[] = [];

  // Visit every sourceFile in the program
  for (const file of fileNames) {
    const sourceFile = program.getSourceFile(file) as ts.SourceFile;
    if (!sourceFile.isDeclarationFile) {
      // Walk the tree to search for classes
      ts.forEachChild(sourceFile, visit);
    }
  }

  // print out the doc
  fs.writeFileSync('classes.json', JSON.stringify(output, undefined, 4));

  /** visit nodes finding exported classes */
  function visit(node: ts.Node) {
    if (ts.isClassDeclaration(node) && node.name) {
      // This is a top level class, get its symbol
      const symbol = checker.getSymbolAtLocation(node.name);
      // console.log(symbol);
      if (symbol) {
        const classDetails = serializeClass(symbol);
        const methodDetails = serializeMethods(symbol.exports);
        const details = classDetails;
        details.methods = methodDetails;
        output.push(details);
      }
    }
  }

  /** Serialize a class symbol information */
  function serializeClass(symbol: ts.Symbol) {
    const details = serializeClassSymbol(symbol);

    // Get the construct signatures
    const constructorType = checker.getTypeOfSymbolAtLocation(
      symbol,
      symbol.valueDeclaration!,
    );
    details.constructors = constructorType
      .getConstructSignatures()
      .map(serializeSignature);
    return details;
  }

  /** Serialize method symbol information */
  function serializeMethods(symbols: ts.SymbolTable | undefined) {
    const methodDetails: DocEntry['methods'] = [];
    if (symbols) {
      const symbolsArr: ts.Symbol[] = Array.from((symbols as Map<any, any>).values());
      symbolsArr.forEach((symbol) => {
        methodDetails.push(serializeMethodSymbol(symbol));
      });
    }
    return methodDetails;
  }

  /** Serialize a symbol into a json object */
  function serializeClassSymbol(symbol: ts.Symbol): DocEntry {
    return {
      name: symbol.getName(),
      comment: ts.displayPartsToString(symbol.getDocumentationComment(checker)),
      type: checker.typeToString(
        checker.getTypeOfSymbolAtLocation(symbol, symbol.valueDeclaration!),
      ),
    };
  }

  /** Serialize a symbol into a json object */
  function serializeMethodSymbol(symbol: ts.Symbol): {
    name: string,
    comment: string,
    type: string,
  } {
    return {
      name: symbol.getName(),
      comment: ts.displayPartsToString(symbol.getDocumentationComment(checker)),
      type: checker.typeToString(
        checker.getTypeOfSymbolAtLocation(symbol, symbol.valueDeclaration!),
      ),
    };
  }

  /** Serialize a signature (call or construct) */
  function serializeSignature(signature: ts.Signature) {
    return {
      parameters: signature.parameters.map(serializeClassSymbol),
      returnType: checker.typeToString(signature.getReturnType()),
      documentation: ts.displayPartsToString(signature.getDocumentationComment(checker)),
    };
  }
}

generateDocumentation(['INSERT FILENAMES HERE'], {
  target: ts.ScriptTarget.ES5,
  module: ts.ModuleKind.CommonJS,
});
```

But beware! I didn't put much work into it. The TS compiler API is a huge world and very poorly documented. You will probably have to make some mods. Check [this](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) out for reference.
