### ISSUE TITLE
Defines the output of marked parser

### ISSUE THREAD

**Issue by liorsharabi** [TypeStrong/typedoc#1582]
I want to customize some of Marked's markdown.
For example i wanna add a class that will wrap code markdowns.
i can see that Marked is giving the option to customize the parser by implementing "render" object and add it to the options:
[https://marked.js.org/using_pro]

but i cant see an option to do that by using typedoc
i think it would be great if we can use it throw typedoc 

maybe you can add a string in the Typedoc json file that refer to a js file that implement the render object.

**Comment by Gerrit0** [comment]
You can do this by using a .js config file and specifying markedOptions: https://typedoc.org/guides/options/#markedoptions
