### ISSUE TITLE
How to define an entry point for the nextjs application in the dev environment?

### ISSUE THREAD

**Issue by topheroes** [TypeStrong/typedoc#1584]
Hello,

Couldn't find the answer, sorry if it's a duplicate. What would be the entry point I need to specify in the typedoc config for the nextjs application?

Thank you in advance!

**Comment by Gerrit0** [comment]
I'm not familiar with the structure of nextjs... but TypeDoc will work with any project so long as you export what you want documented. From a quick google, it looks like an application framework, so you're likely building an app, not a library. I'd probably either use `src` as the entry point (in which case TypeDoc will expand all files under that) and possibly [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules) or export everything I want documented via re-exports in some file and use that as the entry point.
