### ISSUE TITLE
fix: Plugin Documentation

### ISSUE THREAD

**Issue by neozenith** [TypeStrong/typedoc#1586]
I would like to develop a plugin for TypeDoc.

I followed the below code snippet on the `v0.20.36` docs:
http://typedoc.org/guides/development/#plugins

```typescript
import { ParameterType, Converter } from "typedoc";

export function load(host: PluginHost) {
  const app: Application = host.application;

  app.options.addDeclaration({
    name: "plugin-option",
    help: "Displayed when --help is passed",
    type: ParameterType.String, // The default
    defaultValue: "", // The default
  });

  app.converter.on(Converter.EVENT_RESOLVE, (context: Context) => {
    if (app.options.getValue("plugin-option") === "something") {
      // ...
    }
  });
}
```

But then after some research looking at the TypeDoc source code and some real plugins in the wild, it seems the snippet should look like:

`index.ts`
```typescript
import { ParameterType, Converter } from "typedoc";
import { PluginHost } from "typedoc/dist/lib/utils/plugins"
import { MyPlugin } from "./plugin";

export function load(host: PluginHost) {
  const app: Application = host.application;

  app.options.addDeclaration({
    name: "my-plugin-option",
    help: "Displayed when --help is passed",
    type: ParameterType.String, // The default
    defaultValue: "", // The default
  });

  app.converter.addComponent(
    "my-plugin",
    new MyPlugin(app.converter)
  );
}
```

`plugin.ts`
```typescript
import { Component, ConverterComponent } from "typedoc/dist/lib/converter/components";
import { Context } from "typedoc/dist/lib/converter/context";
import { Reflection, ContainerReflection } from "typedoc/dist/lib/models";
import { Converter } from "typedoc";

@Component({ name: "my-plugin" })
export class MyPlugin extends ConverterComponent {
  /**
   * Create a new MyPlugin instance.
   */
  initialize() {
    this.listenTo(this.owner, {
      [Converter.EVENT_RESOLVE]: this.onResolve,
    });
  }

  /**
   * Triggered when the converter resolves a reflection.
   *
   * @param context  The context object describing the current state the converter is in.
   * @param reflection  The reflection that is currently resolved.
   */
  private onResolve(_context: Context, reflection: Reflection) {
    console.log(reflection);
    if (reflection instanceof ContainerReflection) {
      console.log(reflection);
    }
  }
}

```

Then you could instruct potential plugin authors to try to perform a plugin self-check by running the following:

```bash
npx typedoc --plugin . src/index.ts
```

It would seem the section https://github.com/TypeStrong/typedoc/tree/master/src/lib/converter/plugins is one of the more up to date areas in the library that implements Plugins. This could be a good additional link to add to the docs to direct potential plugin authors on where to read next.

----

Normally I would like to directly open the pull request to make the changes a no brainer for you to review and accept but I could not for the life of me find the source for the typedoc dot org website.

**Comment by krisztianb** [comment]
Actually I think that the docs are correct. Deriving from `ConverterComponent` is not best practice for implementing a plugin and only works if you solely need to listen to converter events.

Here is an example plugin I once created that shows how to register to all possible TypeDoc events: https://github.com/krisztianb/typedoc-plugin-base/blob/master/src/example_plugin.ts

**Comment by neozenith** [comment]
That example you linked is really helpful!!!

Here is a revised proposal example for the Plugin Authors snippet based on your base example.

`index.ts`
```typescript
import { PluginHost } from "typedoc/dist/lib/utils/plugins"
import { MyPlugin } from "./plugin";

export function load(host: PluginHost) {
    new MyPlugin().initialize(host.app);
}
```

`plugin.ts`
```typescript
import { Context } from "typedoc/dist/lib/converter/context";
import { Reflection } from "typedoc/dist/lib/models";
import { Converter, Application, ParameterType } from "typedoc";


export class MyPlugin {

  initialize(typedoc: Application) {
    // Add plugin options
    typedoc.options.addDeclaration({
        type: ParameterType.String
        name: "my-plugin-option",
        help: "[My Plugin Option] The helpful summary of how this option configures this plugin.",
    });

    // Add event listeners
    typedoc.converter.on(Converter.EVENT_RESOLVE, (context: Context, reflection: Reflection) => this.onResolve);
  }

  private onResolve(_context: Context, reflection: Reflection) {
    _context.logger.log(reflection);
  }
}
```

Then linking off to the more detailed example you have with all the events.

Any ideas where I can track down the documentation repo so I could open a draft PR against it?

**Comment by krisztianb** [comment]
That should be this repo: https://github.com/TypeStrong/typedoc-site

**Comment by neozenith** [comment]
Awesome! Thank you! I’ll open the pull request in the correct spot.
