### ISSUE TITLE
Generate documentation for function that is property of another function

### ISSUE THREAD

**Issue by ilyub** [TypeStrong/typedoc#1587]
## Search Terms

Generate documentation for function that is property of another function

## Problem

```typescript
namespace is {
  /**
   * Docs 1
   */
  export function string(value): value is string {}

  /**
   * Docs 2
   */
  export function not(...): ... {}

  /**
   * Docs 3
   */
  not.string = function <T>(value: T): value is Exclude<T, string> {}
}

is.string(value);
is.not.string(value);
```

The problem is that "is.not.string" is exported, but typedoc is not generating documentation for it.

## Suggested Solution

Generate documentation in a situation described above.

I.e. when some module exports function and this function has properties, these properties should be documented BECAUSE they are a part of the export.

**Comment by Gerrit0** [comment]
This is an annoying one. Outside of a namespace we detect this pattern correctly... but not inside a namespace, because TS does special things.

```ts
export namespace is {
    export function not(): void {} // symbol flags = 16

    not.string = function(): void {}
}


export function not(): void {} // symbol flags = 67110416

not.string = function () {};
```

**Comment by Gerrit0** [comment]
Workaround, explicitly make a namespace instead of relying on TypeScript's implicit namespace declaration:

```ts
export namespace is {
    export function not(): void {} // symbol flags = 16
    export namespace not {
        export function string(): void {}
    }
}
```

**Comment by Gerrit0** [comment]
After talking with @sandersn on Discord, I'm pretty sure this is a bug in TypeScript, not TypeDoc. I don't plan to add a workaround to TypeDoc proper to make this work.
