### ISSUE TITLE
Not all classes from .d.ts file are documented

### ISSUE THREAD

**Issue by rhuitl** [TypeStrong/typedoc#1588]
## Expected Behavior

It is expected that TypeDoc generates `someclass.html` because it is used in an exported interface.

## Actual Behavior

The file is only created when the `export {};` line is removed from the `.d.ts` file. I'm not sure why this line is in the file (it is generated by a tool called `dts-bundle-generator`) but it makes a difference for TypeDoc.

The file `someinterface.html` is always created.

I'm not sure if this is a bug or works as designed, because I don't know what `export {}` in a `.d.ts` file does. Therefore, this is either a request to clarify the behavior or a bug report :-)

## Steps to reproduce the bug

api.d.ts
```ts
export interface SomeInterface {
  field: SomeClass;
}
declare class SomeClass {
}

// With this line, the documentation for SomeClass is not created.
// Without this line, it is.
export {};
```

tsconfig.doc.json
```json
{
  "include": ["api.d.ts"]
}
```

package.json
```json
{
  "name": "typedoc-test",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "typedoc": "typedoc --out ./dist --excludeExternals --disableSources ./api.d.ts --tsconfig tsconfig.doc.json"
  },
  "devDependencies": {
    "typedoc": "0.20.36",
    "typescript": "~4.0.5"
  },
  "engines": {
    "node": ">=10.13.0",
    "npm": ">=6.1.0"
  },
  "paths": {
    "src": "src",
    "dist": "dist"
  }
}
```

## Environment

-   TypeDoc version: 0.20.36
-   TypeScript version: 4.0.5
-   Node.js version: 14.6.1
-   OS: macOS

**Comment by Gerrit0** [comment]
Yep, this is expected behavior. `SomeClass` is not exported, so it is *not* something you intentionally put in your public API, and will therefore not be documented by TypeDoc.
