### ISSUE TITLE
Add support for TypeScript 4.3

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1589]
## Search Terms

TypeScript 4.3

## Problem

npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"3.9.x || 4.0.x || 4.1.x || 4.2.x" from typedoc@0.20.36

## Suggested Solution

Support TypeScript 4.3

**Comment by simllll** [comment]
Right now it fails on my side with following error message:
```
Warning: You are running with an unsupported TypeScript version! TypeDoc supports 3.9, 4.0, 4.1, 4.2
lerna ERR! npm run generate:docs stderr:
TypeDoc exiting with unexpected error:
TypeError: Cannot read property 'kind' of undefined
    at Object.isDeclaration (/buddy/hokify-justin/hokify-justin/node_modules/typescript/lib/typescript.js:13449:18)
    at Object.isDeclarationName (/buddy/hokify-justin/hokify-justin/node_modules/typescript/lib/typescript.js:16414:75)
    at getTypeOfSymbolAtLocation (/buddy/hokify-justin/hokify-justin/node_modules/typescript/lib/typescript.js:66938:20)
    at Object.getTypeOfSymbolAtLocation (/buddy/hokify-justin/hokify-justin/node_modules/typescript/lib/typescript.js:45176:35)
    at Object.convertProperty (/buddy/hokify-justin/hokify-justin/node_modules/typedoc/dist/lib/converter/symbols.js:330:176)
    at convertSymbol (/buddy/hokify-justin/hokify-justin/node_modules/typedoc/dist/lib/converter/symbols.js:80:79)
    at convertSymbols (/buddy/hokify-justin/hokify-justin/node_modules/typedoc/dist/lib/converter/symbols.js:86:9)
    at Object.convertClassOrInterface (/buddy/hokify-justin/hokify-justin/node_modules/typedoc/dist/lib/converter/symbols.js:264:5)
    at Object.convertSymbol (/buddy/hokify-justin/hokify-justin/node_modules/typedoc/dist/lib/converter/symbols.js:80:79)
    at Converter.convertExports (/buddy/hokify-justin/hokify-justin/node_modules/typedoc/dist/lib/converter/converter.js:182:23)
```

let me know if I can help somehow!

Thanks

**Comment by chharvey** [comment]
Is there any particular reason why [this](https://github.com/TypeStrong/typedoc/blob/a446431a5233139b8d4daee08ea57fd6cabb9965/package.json#L36)
```json
"peerDependencies": {
  "typescript": "3.9.x || 4.0.x || 4.1.x || 4.2.x"
},
```
isn’t this?
```json
"peerDependencies": {
  "typescript": ">= 3.9"
},
```

**Comment by vladmandic** [comment]
> Right now it fails on my side with following error message:
> 
> ```
> Warning: You are running with an unsupported TypeScript version! TypeDoc supports 3.9, 4.0, 4.1, 4.2
> lerna ERR! npm run generate:docs stderr:
> TypeDoc exiting with unexpected error:
> TypeError: Cannot read property 'kind' of undefined

in function `isDeclaration(node)` somehow `node` param that is passed is `undefined`.  
no clue why, but definitely due to TS 4.3 change.

**Comment by Gerrit0** [comment]
This is probably going to be a weekend of June 5th fix - I likely won't have time before then :)

**Comment by krisztianb** [comment]
> 
> 
> Is there any particular reason why [this](https://github.com/TypeStrong/typedoc/blob/v0.20.36/package.json#L36)
> 
> ```json
> "peerDependencies": {
>   "typescript": "3.9.x || 4.0.x || 4.1.x || 4.2.x"
> },
> ```
> 
> isn’t this?
> 
> ```json
> "peerDependencies": {
>   "typescript": ">= 3.9"
> },
> ```

TypeScript updates often include breaking changes so it's not safe to simply state that TypeDoc supports every TS version.

**Comment by chharvey** [comment]
@Gerrit0  In the short term, could you make `typescript 4.2.x` a dependency, and then add `4.3.x` to the peer dependencies? That might let TypeDoc still use 4.2.x internally but let users install 4.3.x in their projects.

**Comment by Gerrit0** [comment]
@chharvey doing this would break quite a few users that still use old versions of TS, so I don't really want to do that. I'll consider it if I can't get around to fixing it this coming weekend.

**Comment by sindresorhus** [comment]
> TypeScript updates often include breaking changes so it's not safe to simply state that TypeDoc supports every TS version above 3.9.

I would personally take that risk rather than having the annoyance of having to wait for `typedoc` for every single minor version of TypeScript.

**Comment by krisztianb** [comment]
It's just a warning. You can take the risk. As you can see it won't work this time. 😄

**Comment by doberkofler** [comment]
I'm generally ok with the strict dependencies but maybe the actual need for the strict dependency could be relaxed. I don't know, how the interface between TypeDoc and TypeScript works but i believe that for example eslint abstracts aways the version specific details of language to be linted by using a dedicate abstraction layer.

**Comment by Nokel81** [comment]
> And code note actually says "This will probably break in a future TS version" - and I guess it did :(

Yeah... I just found that too, `{}` is not a valid `Node` (from TS POV) so I can understand why they didn't bother adding a check on `name.parent.kind` in the `ts.isDeclaration` function.

**Comment by Ayfri** [comment]
Hi, I'm needing this soon, how is it going ?

**Comment by Gerrit0** [comment]
432008c8dbda7ea8c6b9115f0302843593f54911

**Comment by nisimjoseph** [comment]
Beta working great! I moved to TS 4.3. thank you!

**Comment by bennycode** [comment]
Tested TypeDoc v0.21.0-beta.2 with TypeScript v4.3.2 in https://github.com/bennycode/coinbase-pro-node and it worked great. 👍

**Comment by doberkofler** [comment]
Tested version v0.21.0-beta.2 on a large project and worked perfectly. Thank you very much!

**Comment by Ayfri** [comment]
```ts
Error: source/src/sprites/Text.ts:17:18 - error TS2612: Property 'background' will overwrite the base property in 'Container'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

public override background: Sprite;
```
With https://github.com/Ayfri/PIXI-Extended.
Configuration here : https://github.com/Ayfri/PIXI-Extended/blob/docs/typedoc.json.

**Comment by krisztianb** [comment]
@Ayfri that's a compiler error you need to fix and not related to TypeDoc, is it?

**Comment by Ayfri** [comment]
No, my code is fine. It's just because `override` is a new keyword introduced by TS `4.3` and normally TS `4.2` says this, but in my project I use TS `4.3` and everything is fine. So I don't know 🤔

**Comment by krisztianb** [comment]
So the code builds fine, but creating the docs with TypeDoc fails. Is that right?

**Comment by Ayfri** [comment]
Exactly !

**Comment by krisztianb** [comment]
Could it be that TypeDoc for whatever reason is still using TS 4.2 to compile your project? Looking at your `package.json` TypeDoc is not installed locally with your project. How do you build the docs?

**Comment by Ayfri** [comment]
It's on the `docs` branch. I'm using a [GitHub action](https://github.com/Ayfri/PIXI-Extended/blob/master/.github/workflows/documentation.yml) to clone the `master` branch and generate the docs.

**Comment by krisztianb** [comment]
Oh, I see. I don't know then. Still looks like a compilation error to me. Maybe you should create a smaller repo to narrow down the issue.

**Comment by Ayfri** [comment]
Maybe it's because I'm using a plugin, here are the complete logs : 
```typescript
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run generate --scripts-prepend-node-path=auto

> pixi-extended-docs@1.0.0 generate
> typedoc --sourcefile-url-map mappings.json
Warning: C:\Users\Pierre\WebstormProjects\pixi\PIXI-utils\node_modules\typedoc-plugin-sourcefile-url uses a deprecated structure. Pl
ugins should export a "load" function to be called with the Application
    at Application.bootstrap (C:\Users\Pierre\WebstormProjects\pixi\PIXI-utils\node_modules\typedoc\dist\lib\application.js:156:17)
Info: Loaded plugin C:\Users\Pierre\WebstormProjects\pixi\PIXI-utils\node_modules\typedoc-plugin-sourcefile-url
Error: source/src/sprites/Text.ts:17:18 - error TS2612: Property 'background' will overwrite the base property in 'Container'. If th
is is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

17  public override background: Sprite;
                    ~~~~~~~~~~


Process finished with exit code 3
```

**Comment by krisztianb** [comment]
Can you temporarily disable or remove the plugin and try without it? Although I doubt that the plugin is the issue.

I think we should move this conversation to a new/separate issue.

**Comment by Ayfri** [comment]
It doesn't fix the issue :/

Maybe yes.

**Comment by ilyub** [comment]
Using typedoc 0.21.0-beta.2 with typedoc-plugin-markdown 3.9.0.
It works well.

Curious when 0.21.0 can be expected?
typedoc-plugin-markdown has peer dependency ">=0.20.0" and does not see 0.21.0-beta.2.

**Comment by Gerrit0** [comment]
I'm aiming to release it tonight, assuming I have enough time, if not tonight, it should be sometime this week, Friday at the latest.

**Comment by Gerrit0** [comment]
(Obviously didn't happen yesterday, or today... 4 things left on todo list - https://github.com/TypeStrong/typedoc/projects/8)

**Comment by krisztianb** [comment]
@Gerrit0 take your time. :+1:

**Comment by cefn** [comment]
[Depending on the beta](https://github.com/cefn/lauf/pull/107) works for [@lauf/store](https://www.npmjs.com/package/@lauf/store) and [@lauf/store-react](https://www.npmjs.com/package/@lauf/store) Thanks! 

Typedoc retiring support for EOL Node 10 has prompted me to tidy up my [test build matrix](https://github.com/cefn/lauf/pull/107/commits/f5707e5633a90dcc2b41cbbfb0b552327bb970b9)  too! 

Thanks for all your efforts.

**Comment by Gerrit0** [comment]
0.21.0 has been released!

**Comment by nisimjoseph** [comment]
Working great! Thank you!

**Comment by doberkofler** [comment]
Thank you!

**Comment by ilyub** [comment]
Thx. Great work 👍
