### ISSUE TITLE
Whats the right way to document only the things i want to document without using @hidden @private or @external?

### ISSUE THREAD

**Issue by alpatovdanila** [TypeStrong/typedoc#1594]
Hi!

I have medium-sized project written in TS with alot of types and tsdoc comments. Now i want to include in my docs only a few types. Unfortunately, i can't find anything in documentation about that. Only way i see mentioned in docs is marking types i don't want to see in docs with @hidden or @private tag. Sadly, that is not an option for me since project already has alot of types 99% of which are "private" or "external", so it would be very time-consuming to mark all of them with @private

**Comment by krisztianb** [comment]
Could you post your typedoc config and/or call?

Typedoc should only document things that are exported from your entry points.

**Comment by Gerrit0** [comment]
Yeah, the best way to limit what TypeDoc documents is to limit what you export - export your public API at that file, and then run `typedoc path/to/public/api.ts`

**Comment by alpatovdanila** [comment]
@krisztianb it is like that: 
`typedoc src --out docs`
Of course alot of my internal (private) types are exported and imported all over the project, and for now all of them are getting into docs

@Gerrit0 tried that, it works but not follow imports and does not document types imported and used in entrypoin, for example 
`
import { AppTheme } from 'application/theme'
import { AppConfig } from 'application/configuration'

export type AppLaunchOptions = {
  container: HTMLElement | null
  theme?: AppTheme
  config: AppConfig
}`

Only AppLaunchOptions get documented and i can't click on AppTheme or AppConfig in docs and see it. So it seems like i need to explicitly export all types i want to document, from my api.ts? That's almost as inconvinient as manually marking types as internal/external

**Comment by krisztianb** [comment]
What would be your expected behavior?

**Comment by alpatovdanila** [comment]
@krisztianb 
Something like that:

fileA
export type DontDocumentMe = ...

export type WillBeUsedInPublicApi = ...

fileB
import {WillBeUsedInPublicApi} from 'fileA'
export type PublicApi = {
   setting: WillBeUsedInPublicApi
}

typedoc fileB.ts

Now doing that i am getting PublicApi documented, but only on "first level", WillBeUsedInPublicApi is not documented. In the docs it says that setting is of type WillBeUsedInPublicApi but does not provide a way to expand WillBeUsedInPublicApi and see whats inside

**Comment by krisztianb** [comment]
Let's say `WillBeUsedInPublicApi` is clickable and it is a type that consists of multiple properties of different types. Would those property types also be clickable?

**Comment by alpatovdanila** [comment]
If they are not primitives then yes, just like it works now when i run typedoc on src directory - the types are linked together if neccessary

**Comment by krisztianb** [comment]
I think what you should probably do is what @Gerrit0 suggested. Your entry point needs to export everything that the user will potentially use (which includes types like `WillBeUsedInPublicApi`).

**Comment by alpatovdanila** [comment]
Thank you, i will try to do it that way
