### ISSUE TITLE
Cannot use `override` keyword

### ISSUE THREAD

**Issue by Ayfri** [TypeStrong/typedoc#1597]
```ts
Error: source/src/sprites/Text.ts:17:18 - error TS2612: Property 'background' will overwrite the base property in 'Container'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

public override background: Sprite;
```
With https://github.com/Ayfri/PIXI-Extended.
This is found in [this file](https://github.com/Ayfri/PIXI-Extended/blob/master/src/sprites/Text.ts).

Configuration here : https://github.com/Ayfri/PIXI-Extended/blob/docs/typedoc.json.

_Originally posted by @Ayfri in https://github.com/TypeStrong/typedoc/issues/1589#issuecomment-858291140_

**Comment by Ayfri** [comment]
Ok I've found a workaround, by adding `strict: true` in the `tsconfig` file, it fixes it.

**Comment by krisztianb** [comment]
Wow that is odd. Strict would mean an even stricter type checking.

**Comment by Ayfri** [comment]
Maybe the `override` keyword is only valid in stricter type checking ?

**Comment by Gerrit0** [comment]
TypeDoc is correctly providing the same error as TypeScript will if you run `tsc`. This seems to be working properly to me.

**Comment by krisztianb** [comment]
> Maybe the `override` keyword is only valid in stricter type checking ?

I don't think so. As far as I know `strict` is only a simpler way to activate several other options at once: https://www.typescriptlang.org/tsconfig#strict

**Comment by Ayfri** [comment]
Okay I'll try so !

**Comment by Ayfri** [comment]
Okay, I tested at all, and it seems that `strictNullChecks` makes it work with `override`!

**Comment by krisztianb** [comment]
That would make sense in the way that you override a property that becomes non-nullable. Still pretty strange imho.
