### ISSUE TITLE
Pin Marked to 2.0.x

### ISSUE THREAD

**Issue by Fleker** [TypeStrong/typedoc#1601]
## Search terms

Marked, Node 10

## Expected Behavior

I expect installing Typedoc in my project as a dependency, using Node 10, will work as expected.

## Actual Behavior

My CI system reports an error and breaks due to a [change in the Marked minimum version](https://github.com/markedjs/marked/issues/2111) from Node 8+ to Node 12+. As I am installing via Node 10, the build fails.

```
+ yarn
# ...
error marked@2.1.1: The engine "node" is incompatible with this module. Expected version ">= 12". Got "10.18.0"
error Found incompatible module.
```

A resolution to the issue would be pinning the Marked dependency to `~2.0.3` if and until Marked's `engines` field is returned to something `>= 10.18.0` or lower.

## Steps to reproduce the bug

* Start with an environment using Node 10 (nvm use 10.18.0)
* Create a project with a dependency of typedoc@^0.20.0 or marked@^2.00
* Run yarn

**Comment by Gerrit0** [comment]
Node 10 is dead. It's not supported anymore by Node. v0.21 removes it from TypeDoc's supported versions as well. If you want to submit a PR for 0.20, go ahead, but I'm likely not going to get around to this before 0.21, and I don't support versions older than latest due to time constraints.

**Comment by Fleker** [comment]
I will submit a PR for v0.20, as this issue breaks out project's build and I'd like that to be fixed promptly rather than go through a larger major release process.

**Comment by Fleker** [comment]
I appreciate your quick turnaround on this release.
