### ISSUE TITLE
I am unable to execute typedoc

### ISSUE THREAD

**Issue by czlowiek488** [TypeStrong/typedoc#1603]
## Expected Behavior

It should build docs

## Actual Behavior

It is failing
![image](https://user-images.githubusercontent.com/34620109/122834722-63e68300-d2ef-11eb-8f81-e20e9eb362a8.png)

## Steps to reproduce the bug
command: `./node_modules/typedoc/bin/typedoc "./src/index.ts" --exclude "**/{node_modules/**/*,*.spec}.ts" --tsconfig "./tsconfig.json"`

packages: 
```
    "@czlowiek488/swagger-express-ts": "^1.0.4",
    "@google-cloud/firestore": "^4.12.0",
    "@google-cloud/pubsub": "^2.12.0",
    "@google-cloud/storage": "^5.8.5",
    "@tshio/awilix-resolver": "^1.0.2",
    "@tshio/command-bus": "^1.0.2",
    "@tshio/event-dispatcher": "^1.0.2",
    "@tshio/logger": "^1.0.4",
    "@tshio/query-bus": "^1.0.2",
    "@tshio/security-client": "0.0.19",
    "@xtrf/tms-messages": "^1.1.11",
    "apollo-server-express": "^2.11.0",
    "awilix": "^4.2.6",
    "celebrate": "^12.1.1",
    "class-transformer": "^0.2.3",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-async-errors": "^3.1.1",
    "faker": "^5.5.3",
    "firebase-admin": "^9.8.0",
    "graphql": "^15.0.0",
    "helmet": "^3.22.0",
    "http-status-codes": "^1.4.0",
    "jsonwebtoken": "^8.5.1",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "luxon": "^1.27.0",
    "pg": "^8.0.3",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "swagger-ui-dist": "^3.35.1",
    "ts-pipe-compose": "^0.2.1",
    "utility-types": "^3.10.0",
    "uuid": "^8.3.2",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@commitlint/cli": "^12.1.1",
    "@commitlint/config-conventional": "^12.1.1",
    "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/typescript": "^1.13.1",
    "@graphql-codegen/typescript-resolvers": "^1.13.1",
    "@types/chai": "^4.2.11",
    "@types/chai-as-promised": "^7.1.2",
    "@types/cors": "^2.8.6",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5",
    "@types/faker": "^5.5.6",
    "@types/helmet": "0.0.46",
    "@types/jsonwebtoken": "^8.3.9",
    "@types/lodash": "^4.14.170",
    "@types/luxon": "^1.27.0",
    "@types/mocha": "^7.0.2",
    "@types/node": "^13.13.4",
    "@types/sinon": "^10.0.2",
    "@types/supertest": "^2.0.8",
    "@types/uuid": "^7.0.3",
    "@typescript-eslint/eslint-plugin": "^2.30.0",
    "@typescript-eslint/parser": "^2.30.0",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "chalk": "^4.0.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-typescript": "^7.2.1",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-no-only-tests": "^2.4.0",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-unicorn": "^19.0.1",
    "husky": "^4.3.0",
    "lodash.kebabcase": "^4.1.1",
    "mocha": "^9.0.0",
    "nock": "^13.0.5",
    "nyc": "^15.1.0",
    "plop": "^2.6.0",
    "prettier": "^2.0.5",
    "sinon": "^11.1.1",
    "supertest": "^4.0.2",
    "typedoc": "^0.21.0",
    "typescript": "^4.3.4"
```
tsconfig
```
{
  "compilerOptions": {
    "target": "es2019",
    "types": ["node"],
    "module": "commonjs",
    "declaration": false,
    "strict": true,
    "allowSyntheticDefaultImports": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "sourceMap": false,
    "inlineSourceMap": true,
    "outDir": "build",
    "typeRoots": ["./node_modules/@types"],
    "resolveJsonModule": true
  },
  "include": [
    "src/**/*.ts",
    "config/**/*.ts",
    "tests/**/*.ts"
  ],
  "exclude": ["node_modules", "build/**"]
}

```

## Environment

-   Typedoc version: 0.21.0
-   TypeScript version: 4.3.4
-   Node.js version: 12.18.1
-   OS: WSL Ubuntu

**Comment by Gerrit0** [comment]
Have you tried adding esModuleInterop: true to your tsconfig as the error suggests?

**Comment by czlowiek488** [comment]
Yes, I did. But it does not change anything.

wt., 22 cze 2021, 03:56 użytkownik Gerrit Birkeland <
***@***.***> napisał:

**Comment by Gerrit0** [comment]
I'm going to need a repro to look at then (ideally one *without* 100 dependencies...), I don't have the time to try to create one from scratch for reported bugs

**Comment by czlowiek488** [comment]
@Gerrit0 
I prepared one minimal for you. Just hit `npm i` and `npm run typedoc` then you will see errors. Tested on node 12.22.1.
https://github.com/czlowiek488/typedoc-bug-report

Also I found another bug which happend when I dont have installed peer dependency (here graphql). You can check it if you pull this commit (execute the same way).
https://github.com/czlowiek488/typedoc-bug-report/commit/aab0b96aee5b42e6467405d2bbb9b5391437b9eb

**Comment by Gerrit0** [comment]
Oops, I forgot that `esModuleInterop` wasn't the only option that controlled imports - the `apollo-server-express` package uses `allowSyntheticDefaultImports`, which means that every package which depends on it is also effectively forced to turn that compiler option on. (This is why Definitely Typed [forbids](https://github.com/DefinitelyTyped/DefinitelyTyped#esmoduleinteropallowsyntheticdefaultimports) that option)

```diff
diff --git a/tsconfig.json b/tsconfig.json
index 8ecfccc..785b192 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -5,7 +5,7 @@
     "module": "commonjs",
     "declaration": false,
     "strict": true,
-    "allowSyntheticDefaultImports": false,
+    "allowSyntheticDefaultImports": true,
     "emitDecoratorMetadata": true,
     "experimentalDecorators": true,
     "strictPropertyInitialization": false,
```

With this change, the docs build. Without it, they don't. This matches TypeScript's behavior. If you compile with `tsc` you'll see the same result. If you move the `skipLibCheck` option from your build command to the tsconfig, TypeDoc will also run.

I tried checking out the other commit, and with the `allowSyntheticDefaultImports` change, TypeDoc seems to behave properly there as well. If you have type errors, it is expected that TypeDoc won't build.
