### ISSUE TITLE
entryPoint resolution change in 0.21.0

### ISSUE THREAD

**Issue by donmahallem** [TypeStrong/typedoc#1604]
## Search terms

Change in path resolution

## Expected Behavior

It should resolve the entryPoints from the current working dir and not from the config path

## Actual Behavior

Since 0.21.0 it resolves entryPoints from the directory the typedoc.json is located.

## Steps to reproduce the bug

My current pre 0.21.0 setup is a lerna monorepo.
Every subpackage, that does create docs does have a script like this `typedoc --options ../../typedoc.json`. In the root folder the typedoc.json like this:
```
{
    "entryPoints":["./src/index.ts"],
    "exclude": [
        "**/*.spec.ts"
    ],
    "out": "docs"
}
```

So running something along the lines `npx lerna run docs --scope=packagename` would create a docs folder within the package folder. With 0.21.0 the entryPoint resolution doesn't start from the current working directory but it appears from the typedoc.json file in the root directory.

## Environment

-   Typedoc version: 0.21.0
-   TypeScript version: 4.2
-   Node.js version: 14
-   OS: Windows

**Comment by donmahallem** [comment]
I tried to use a local typedoc.json file inside the subpackage which only content is an extends attribute to the root typedoc.json.

Looking at the handling of Path and [PathArray ](https://github.com/TypeStrong/typedoc/blob/bde0b6af7c7708c2cdb476981253ad3a14b815af/src/lib/utils/options/declaration.ts#L349) options it is clear that every entryPoint is resolved relative to the typedoc.json file it was declared in and not the root/source/working dir.

**Comment by Gerrit0** [comment]
This is working as expected, and is documented in the breaking changes for 0.21.

If you want to continue using something similar to your current setup, you could replace the typedoc.json in your projects with a typedoc.js that does:

```ts 
module.exports = require("../typedoc.json")
```
