### ISSUE TITLE
Generating docs for default export class/interface creates unhelpful hierarchy

### ISSUE THREAD

**Issue by slalum** [TypeStrong/typedoc#1605]
For example, I have the following interface:

export default interface Point {
    X : number;
    Y : number;
}

The doc that is being generated:

![image](https://user-images.githubusercontent.com/16664906/122921292-fb3cec00-d36a-11eb-825b-7b14e45bb32c.png)

and clicking on the default name I get this:
![image](https://user-images.githubusercontent.com/16664906/122921411-1f003200-d36b-11eb-805a-553f23c185e1.png)

Is this the correct behavior? Can I customize it?

**Comment by Gerrit0** [comment]
See https://github.com/TypeStrong/typedoc/issues/1521
