### ISSUE TITLE
--excludeNotDocumented should not create empty pages

### ISSUE THREAD

**Issue by Primajin** [TypeStrong/typedoc#1607]
## Search terms
excludeNotDocumented empty page

## Expected Behavior
When running `typedoc src --excludeNotDocumented` I expect folders that only include undocumented files to not create empty pages in typedoc

## Actual Behavior
Typedoc still creates a link / page for every folder, rendering a complete useless blank page

## Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/1742115/123096120-0e18f480-d42f-11eb-8952-e45f6654a366.png)

## Environment

-   Typedoc version: 0.21.0
-   TypeScript version: 4.3.4
-   Node.js version: v16.3.0
-   OS: Windows

**Comment by Gerrit0** [comment]
That's strange... I thought we had logic to check for that in the renderer. Should be an easy fix at least.

**Comment by Primajin** [comment]
I ran it together with another exclude pattern (to exlude files under the folder "mock-data") if that helps reproducing somehow.
