### ISSUE TITLE
readme configuration doesn't seem to be working

### ISSUE THREAD

**Issue by dregert** [TypeStrong/typedoc#1608]
## Search terms

'readme' key not working when specified in the configuration file (typedoc 0.21.0)

## Expected Behavior

Expected the "readme" configuration inside the options file to work.

## Actual Behavior

Specifying "readme: none" inside the typedoc.js file doesn't seem to be working, while the other configurations inside the same file seemed to be working fine. 
When specifying "--readme none" in the command line, that works as expected.

### command line
```
node_modules/typedoc/bin/typedoc --options etc/typedoc.js bar.ts
```

### typedoc.js
```javascript
module.exports = {
  name: 'My Project',
  out: '../build/typedoc',
  externalPattern: [
    '**/foo/**',
  ],
  excludeExternals: true,
  excludePrivate: true,
  excludeInternal: true,
  logger: 'console',
  readme: 'none',
};
```

## Environment

-   Typedoc version: 0.21.0
-   TypeScript version: 4.3.4
-   Node.js version: 12.16.2
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Shoot, yep. That's busted. Thanks for the bug report!

**Comment by dregert** [comment]
Already tested 0.21.2 and the problem is fixed! Thanks!
