### ISSUE TITLE
How to configure the default theme to generate only the index.html?

### ISSUE THREAD

**Issue by dregert** [TypeStrong/typedoc#1609]
In the 0.20.x version of typedoc, I was using the default theme (without any readme file) and that generated an index.html file with the whole documentation. Now, with typedoc 0.21.0, the same configuration generates an index.html file with an empty "Index" section and it also generates a modules.html with the exact same content that used to be in the index.html generated with 0.20.x. 
Is there a way to change this behavior? Or is this a bug?

Thanks,

**Comment by krisztianb** [comment]
I thought that you need to pass `none` for this config parameter to get what you are looking for: https://typedoc.org/guides/options/#readme

Have you tried that?

**Comment by dregert** [comment]
yeah, they are somewhat related. 
I'm setting it to ``none``  but that doesn't seem to be working.

**Comment by Gerrit0** [comment]
Yeah, this is a bug - same root cause as #1608
