### ISSUE TITLE
Highlight JS css

### ISSUE THREAD

**Issue by xabufr** [TypeStrong/typedoc#161]
It seems there is no highlistjs theme for some languages.
When I put doc:
    ```json
    {
        "width": 1024,
        "height": 1200
    }
    ```
I get:
![electron-bug1](https://cloud.githubusercontent.com/assets/2772755/11497331/963d586e-9818-11e5-8dce-b09956c9e829.png)
In fact there is no CSS rules defined for css class `lang-json`, and maybe other languages.

**Comment by sebastian-lenz** [comment]
Hi Thomas, thank you for your message. I'll update the style definitions, probably got out of sync after an update to highlight.js.

**Comment by aciccarello** [comment]
This looks like a case of missing styles in the default theme [_highlight.js.sass](https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/assets/css/vendors/_highlight.js.sass) file. Interestingly, the theme no longer contains language specific classes.

It would be nice to point directly to the [highlight.js vs theme](https://github.com/isagalaev/highlight.js/blob/master/src/styles/vs.css) but it would be hard to point to the `node_modules` location. We should at least leave a comment so the file is easier to find.
