### ISSUE TITLE
Generating JSON doesn't seem to generate anything.

### ISSUE THREAD

**Issue by zthun** [TypeStrong/typedoc#1610]
## Search terms

JSON

## Expected Behavior

When executing typedoc with a json output, the json file should output the full documentation.

## Actual Behavior

It looks like something changed in the latest version that broke legacy json generation in monorepos when generating the docs in each individual package.  Note that I have not converted my repository to use the new monorepo features yet.

```json
{
	"id": 0,
	"name": "@zthun/lint-janitor",
	"kind": 0,
	"kindString": "Project",
	"flags": {},
	"originalName": "",
	"sources": [
		{
			"fileName": "index.ts",
			"line": 1,
			"character": 0
		}
	]
}
```

This was working fine in version 0.20.36.

## Steps to reproduce the bug

```sh
git clone https://github.com/zthun/janitor.git
cd janitor
yarn install
yarn build
```

Look at the generated json at packages/lint-janitor/docs

The previous version generated the correct output:

```sh
git checkout fa4cfcdb8cd2f8856f2adf897d0a5aeaf2af813a
yarn install
yarn build
```

## Environment

-   Typedoc version: 0.21.0
-   TypeScript version: 4.3.4
-   Node.js version: 16.3.0
-   OS: MacOS BigSur 11.4

**Comment by Lhoerion** [comment]
It works fine, so I think it's related to Linux/MacOS path handling (needs further research).

**Comment by Gerrit0** [comment]
This is a weird one... I can repro with WSL. No idea what's going on yet though.

**Comment by Gerrit0** [comment]
Well, that was an interesting investigation. The behavior you are seeing is correct. The bug is actually that Windows "works". On Linux & Mac OS, TypeDoc correctly removes everything that would be included from an excluded file. The behavior of `exclude` changed in 0.21 to not only apply to entry point discovery, which is why the previous version didn't show this bug.

```js
module.exports = {
  out: 'docs/typedoc',
  json: 'docs/typedoc.json',
  exclude: ['src/index.ts'],        // <-- The culprit, remove this.
  excludePrivate: true,
  tsconfig: 'tsconfig.bin.json',
  entryPoints: ['src/index.ts']
};
```
