### ISSUE TITLE
Unable to generate typedoc (throws exception)

### ISSUE THREAD

**Issue by probal31** [TypeStrong/typedoc#1611]
Hello Team,

Not able to generate typedoc for my typescript webpack project.

Attaching the exception log and `package.json` & `tsconfig.json`
[config_and_log.zip](https://github.com/TypeStrong/typedoc/files/6708507/config_and_log.zip)

Can you please look into the issue and suggest what could be the possible reason for the same?

Thanks.

**Comment by Lhoerion** [comment]
Are you sure that you also want to document external types?
If that wasn't your intension, then take a look at [`excludeExternals`](https://typedoc.org/guides/options/#excludeexternals).

**Comment by probal31** [comment]
> 
> 
> Are you sure that you also want to document external types?
> If that wasn't your intention, then take a look at [`excludeExternals`](https://typedoc.org/guides/options/#excludeexternals).

I was testing in various ways. But right now the config is minimal. Please find it below.

```
"typedocOptions": {
    "entryPoints": ["src/index.ts"],
    "out": "docs"
}
```

Even then the exception is the same.

**Comment by Lhoerion** [comment]
After another look, why do you specify `externalPattern` by yourself? TypeDoc by default assumes this value `**/node_modules/**`, will it work without it?

**Comment by Lhoerion** [comment]
Did you include webpack types somewhere in your entry point?

**Comment by probal31** [comment]
> 
> 
> Did you include webpack types somewhere in your entry point?

No

**Comment by probal31** [comment]
Here is the entrypoint for reference.

```typescript
import EventEmitter from 'events';
import IVideoChatAPIParameters from './IVideoChatAPIParameters';

declare interface VideoChatAPI {
  // on(event: 'connected', listener: (name: string) => void): this;
  // on(event: 'disconnected', listener: (name: string) => void): this;
}

/**
 * VideoChatAPI is an API implementation for connecting to Jitsi video chat server
 */
class VideoChatAPI extends EventEmitter {
  /**
   * Initialize VideoChatAPI with parameters
   * @param options Jitsi server connection options
   */
  constructor(options: IVideoChatAPIParameters) {
    super();
  }

  /**
   * Join a jitsi room
   *
   * @param roomID  ID of room to join
   * @param name    Name of the user
   */
  public joinRoom(roomID: String, name: String): void {
    // TODO
  }
}

export default VideoChatAPI;
```

**Comment by Lhoerion** [comment]
Could you prepare small reproduction repo?

**Comment by probal31** [comment]
> 
> 
> Could you prepare small (minimal) reproduction repo?

Please find the repo.

HTTPS: https://gist.github.com/69e3b536fe953ec4d48d07f86f653f0c.git

SSH: git@gist.github.com:69e3b536fe953ec4d48d07f86f653f0c.git

**Comment by Lhoerion** [comment]
Seems that `@types/webpack@4.41.29` is outdated, you need to either manually update it or disable types in `tsconfig.json` via `types: []`

**Comment by probal31** [comment]
> 
> 
> It seems that `@types/webpack@4.41.29` is outdated, you need to either manually update it or disable types in `tsconfig.json` via `types: []`

Thank @Lhoerion for your valuable comments. Now the typedoc is getting generated.

Uninstalled the `@types/webpack` (this is not required it seems) and added `types: []` in the `tsconfig.json`

**Comment by Lhoerion** [comment]
@probal31 It seems that issue is not related to TypeDoc, so you can close it.
