### ISSUE TITLE
How do I doc WebWorker APIs?

### ISSUE THREAD

**Issue by XadillaX** [TypeStrong/typedoc#1613]
If I have a class to be documented like:

```typescript
class Foo extends TransformStream {}
```

How do I include the `TransformStream`, it's `readableStream`, it's `getReader()` and the whole chain in the document?

Now it seems only document `readableStream`. Methods in `readableStream` (e.g. `getReader()`) are not included.

**Comment by krisztianb** [comment]
TypeDoc only documents things that are exported through the entry points that you provide in your TypeDoc config. If you want to document types that are not visible through your API you will need to export those in one of your entry points or specify the file as an entry point itself.

**Comment by XadillaX** [comment]
Since `Foo`'s useful way is by using `foo.readableStream.getReader().xxx`, I think I should document `readableStream`'s APIs.

So you mean that I have to export `TransformStream`, `ReadableStream`, etc. manually in my `*.d.ts` file?

**Comment by krisztianb** [comment]
In order not to mess up your code with export statements that are only there for TypeDoc, I would suggest creating a separate file which only contains reexports of things you want to have documented and use that file as the entry point for TypeDoc.

**Comment by XadillaX** [comment]
Thanks.

**Comment by krisztianb** [comment]
You're welcome. If your issue is solved, please don't forget to close it. Thanks.
