### ISSUE TITLE
Typedoc generator should be accessable from API.

### ISSUE THREAD

**Issue by czlowiek488** [TypeStrong/typedoc#1614]
## Problem

I would like to genereate typedoc when express app is starting.
I dont see a way to do this without copyting and pasting whole typedoc bin file to my project files.

## Suggested Solution

1. Move content of `/bin/typedoc` to `/dist/execute.js`.
2. Wrap content in a function.
3. In `/bin/typedoc` execute this function with 0 arguments.

**Comment by Gerrit0** [comment]
So.. there's a problem with this. What the CLI does and what your server does should almost certainly not be the same.

1. bin/typedoc reads command line arguments - it likely shouldn't on your custom script.
2. bin/typedoc supports watching - it likely shouldn't in your custom script.

It really isn't that much code to set up TypeDoc in a more appropriate way for your usage.  The [example here](https://typedoc.org/guides/installation/#node-module) is likely sufficient.
