### ISSUE TITLE
Docs not consistently inherited

### ISSUE THREAD

**Issue by fb55** [TypeStrong/typedoc#1616]
First off, thanks for this library — we're using it for [cheerio.js.org](https://cheerio.js.org), to great effect. Now to the bug I've encountered while refactoring a part of Cheerio:

## Actual Behavior

Take this example:

```ts
function foo() {
  /**
   * Does things.
   *
   * @param a - A string.
   * @returns A string.
   */
  return (a: string) => a;
}

export const test = foo(); // No inherited docs.

export interface Test {
  test: ReturnType<typeof foo>; // Docs inherited.
}
```

TypeDoc produces inherited docs for the `test` property of the `Test` interface, but doesn't do this for `const test`.

Note that this behavior doesn't change when explicitly typing `const test`:

```ts
export const test: ReturnType<typeof foo> = foo(); // Still no inherited docs.
```

## Expected Behavior

TypeDoc should have `const test` inherit the docs from its value.

## Steps to reproduce the bug

Run TypeDoc on the snippet above.

## Environment

-   Typedoc version: 0.21.2
-   TypeScript version: 4.3.4
-   Node.js version: 16.4.0
-   OS: macOS 11.4 / Big Sur

**Comment by Gerrit0** [comment]
I was actually surprised that the interface picked this up at all... strange inconsistency.
