### ISSUE TITLE
How can I get documentation for extended class

### ISSUE THREAD

**Issue by slalum** [TypeStrong/typedoc#1618]
I have 3 packages:
1. common - with some definitions and classes.
2.  X - imports from common. (common is in package,json dependencies)
3.  Y - imports from common. (common is in package,json dependencies)

I want to generate documentation that will have all the hierarchy for all 3 packages together so I will be able to jump to the extended class doc from the class deriving it in X or Y.

How can I achieve this?

**Comment by krisztianb** [comment]
Please take a look at this issue: #1613
I think this is essentially the same "problem".

Maybe we should add a description of this somewhere in the README since this scenario seems to be popping up quite often.

**Comment by slalum** [comment]
I thought https://typedoc.org/guides/project-references/ might be the way to go but it doesn't work.
I also tried running the demo and it didn't generate any files.

**Comment by Gerrit0** [comment]
Since `--packages` doesn't support linking between packages (#1612), I think project references is likely the way to go here....

I would probably set up a fourth package, which references both `X` and `Y` and does something like this:

```ts
// src/common.ts
export * from "common"
// src/X.ts
export * from "X"
// src/Y.ts
export * from "Y"
```

```
npx typedoc src
```
