### ISSUE TITLE
Typescript 1.7 compiler support

### ISSUE THREAD

**Issue by lowkay** [TypeStrong/typedoc#162]
Howdy,

With the recent release of the typescript 1.7 compiler we have been looking to upgrade our typescript code base. However typedoc will not be able to process the source correctly as the 1.6 compiler doesn't understand the new features - 'this' typing, exponential operator and async/await,

What is the status of this project is it still being actively maintained? Is 1.7 support in the works?

Thanks, and great work so far!

**Comment by sebastian-lenz** [comment]
Hi, nice to hear from you. Support for TypeScript 1.7 will be available with TypeDoc 0.4. This is a free time project and I've been quite busy lately so I'm sorry for not being able to tell you when v0.4 will be ready.

**Comment by jasongrout** [comment]
FYI, I got typedoc to compile in 1.7.3 using this patch:

```patch
diff --git a/src/td/models/Reflection.ts b/src/td/models/Reflection.ts
index d86da8d..7977697 100644
--- a/src/td/models/Reflection.ts
+++ b/src/td/models/Reflection.ts
@@ -440,7 +440,7 @@ module td.models
                     alias = 'reflection-' + this.id;
                 }
 
-                var target = this as Reflection;
+                var target: Reflection = this;
                 while (target.parent && !(target.parent instanceof ProjectReflection) && !target.hasOwnDocument) {
                     target = target.parent;
                 }
```

However, it just generates blank templates, so something is still wrong.

**Comment by jasongrout** [comment]
I don't know much about the internals of typedoc -- do you have a pointer for files or classes that should be constructed with, say, the test data set, so I can try to see where things are going wrong?

**Comment by jasongrout** [comment]
I worked some more on this.  As in #122, I had to update the tsc.d.ts file, and remove the last line of it (`export = ts;`) to get it to compile.

As you can probably guess, then I got a handful of compilation warnings.  It seems that a lot of functions are different.

**Comment by gdi2290** [comment]
:+1:

**Comment by xstof** [comment]
I'm new to typedoc, would someone mind clarifying how to force typedoc to use the TS 1.7 compiler please?  "typedoc --version" shows me: "TypeDoc 0.3.12
Using TypeScript 1.6.2 from ...", while I would have expected it would use 1.7 in the latest npm package.

**Comment by ocombe** [comment]
There hasn't been a release with the support for typescript 1.7 yet. The last release is from "7 Oct 2015" and the typescript 1.7 support is only 1 month old

**Comment by xstof** [comment]
@ocombe - when I try installing from github using "https://github.com/sebastian-lenz/typedoc.git#53bb762" - it seems to depend on "typedoc-default-themes@0.4.0", which is not checked into the typedoc-default-themes repo.  Would love to see polymorphic "this" typing light up, as described here: http://blogs.msdn.com/b/typescript/archive/2015/11/30/announcing-typescript-1-7.aspx.  Today typedoc fails compiling on such code.

**Comment by ThaNarie** [comment]
I wanted to see what the state of the 1.7 version was, so I cloned and npm-linked the repo in my (very small test) project. For it to work I had to:
* change the dependancy for `typedoc-default-themes` to `^0.3.0`, as `0.4` doesn't seem to exist anywhere (not even on github)?
* remove `'lib'` from this line, because `ts.getDirectoryPath` already seems to include `'lib'`:
https://github.com/sebastian-lenz/typedoc/blob/53bb762ad208f2be266ece767f6204159ce71a0d/src/lib/converter/utils/compiler-host.ts#L59

Without the change you end up with this output (added extra log):
```
Using TypeScript 1.7.3 from /Volumes/Projects/Repos/typedoc/node_modules/typescript/lib
/Volumes/Projects/Repos/typedoc/node_modules/typescript/lib/lib/lib.d.ts
Error: Cannot find global type 'Array'.
...
```

**Comment by ThaNarie** [comment]
Additional note; In a previous commit the project structure has changed where `bin/typedoc` now references files from the `/lib` folder, instead of a compiled version from the `/bin` folder.

The `/lib` folder isn't listed in the `package.json` `"files"` section, so it won't be included when you install it from Github via the package.json.

When you add the folder (together with the changes above), it will install and run correctly.

**Comment by gdi2290** [comment]
typescript is on 1.8 now

**Comment by christopherthielen** [comment]
>  as 0.4 doesn't seem to exist anywhere (not even on github)?

0.4 is `master` now, as can be seen here https://github.com/sebastian-lenz?tab=activity
<img width="520" alt="screen shot 2016-01-31 at 12 41 36 pm" src="https://cloud.githubusercontent.com/assets/2053478/12704071/1b066642-c818-11e5-9360-b470d1078280.png">

**Comment by mm-devmonk** [comment]
@christopherthielen I was talking about `typedoc-default-themes`, not `typedoc` :)

**Comment by ThaNarie** [comment]
@christopherthielen I was talking about `typedoc-default-themes`, not `typedoc` :)

**Comment by christopherthielen** [comment]
aha. deleting my previous comment to reduce the noise

**Comment by jasongrout** [comment]
Well, 1.8 is still beta, not released.

**Comment by sampsyo** [comment]
1.8 is now final.

**Comment by Guria** [comment]
You can force use typescript installed in your project by running:
`rm -rf node_modules/typedoc/node_modules/typescript`

But don't sure if it will work without any issues :)

**Comment by s-panferov** [comment]
Just for info: I'm making another doc generator called [docscript](https://github.com/docscript/docscript) which uses another architecture. I don't think that it can be useful right now for production purposes, and a lot of work must be done before the first public release. But docscript aims to support the latest TS compiler and successfully builds docs even for 1.9 nightly compiler.

So maybe in the next few weeks all missing features will be implemented and it will be ready to use. If someone is interested to be early adopters — you're welcome.

**Comment by jeffbcross** [comment]
>The /lib folder isn't listed in the package.json "files" section, so it won't be included when you install it from Github via the package.json.

@ThaNarie it looks like the default grunt task generates the lib folder. So if you `npm install` typedoc from Github as a dependency, you'll also have to run Grunt inside the project.

**Comment by jeffbcross** [comment]
BTW I have a fork that works with 1.7.5 thanks to @ThaNarie which can be npm installed via `npm install jeffbcross/typedoc`. 

I tried upgrading to 1.8.9 but it generated empty docs, and I don't have time right now to figure out why :).

**Comment by jasongrout** [comment]
FYI, this also looks like a very promising way to do docs: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker

It uses an unstable, but at least public, API.

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/typedoc/pull/204.
