### ISSUE TITLE
Not able to document events using the `@event` tag

### ISSUE THREAD

**Issue by iShibi** [TypeStrong/typedoc#1621]
## Search terms
event, event tag

## Expected Behavior
```ts
/**
   * Emitted when client becomes ready for use
   * @event Client#ready
*/
this.emit('ready');
```
This is how I used to document events using `jsdoc`. I couldn't find how to use the `@event` tag in `typedoc` as the docs don't describe anything about it. So, I went with the above comment. It doesn't work tho. It should have created an `Events` heading in the `Client` page where all the events should have been listed.

## Actual Behavior
It doesn't render the documentataion for events that were written using the `@event` tag.

## Steps to reproduce the bug
1) Make a class that extends `EventEmitter`
2) Use `this.emit` inside a method so that it emits that event when the said method gets called.
3) Document the event like I have done above
4) Make sure you export the class from `index.ts`, which is the entry point for `typedoc`
5) Build the documentation
6) Go to the page of the class you created and look for the event **(Spoiler! you won't find it)**
7) Sob 😿

I removed the documentation for events from my `Client` class as it wasn't working but forgot to remove it from [here](https://github.com/twitterjs/twitter.js/blob/60466c36d518ecef21be0037c74e4e8fa6f37382/src/rest/RequestHandler.ts#L45) **(This is a WIP branch and haven't been merge yet, so make sure you don't search for stuff in the `main` branch)**. It's not a minimal repo but that's what I've been working on and all the details you have asked for is also available on that repo. Hope that helps.

## Environment

-   Typedoc version: 0.21.1
-   TypeScript version: 4.3.4
-   Node.js version: 14.15.1
-   OS: Windows 10

**Comment by Gerrit0** [comment]
TypeDoc uses the `@event` tag to change the kind of documentation that it is attached to. Today, TypeDoc only supports the `@event` tag for this use, which can produce docs [like this](https://typedoc.org/api/classes/converter.html) from code [like this](https://github.com/TypeStrong/typedoc/blob/v0.21.2/src/lib/converter/converter.ts#L64-L69). 

See also:
- [microsoft/tsdoc#30](https://github.com/microsoft/tsdoc/issues/30) - some discussion on standardizing this
- [a blog post](https://cancerberosgx.github.io/javascript-documentation-examples/examples/typedoc-tutorial-basic/docs/docco/src/index.html#events) showing a few ways `@event` can be used in TypeDoc

I definitely think there's some room for improvement here, but scanning through all comments in the source code is almost certainly not going to be the answer.

**Comment by kungfooman** [comment]
Is there still no way to support good-old JSDoc event's as they are used in `jsdoc`?
