### ISSUE TITLE
Documentation of property-style methods isn't inherited

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1624]
## Search terms

property, inherit

## Expected Behavior

The documentation of property-style methods in interfaces should be inherited in the same way that shorthand-syntax methods work.

```ts
export interface Bar {
	/** Some shorthand syntax doc. */
	bar(): number;
	/** Some property style doc. */
	baz: () => number;
}

export class Foo implements Bar {
	bar(): number {
		return 0;
	}
	baz(): number {
		return 0;
	}
}
```

## Actual Behavior

The documentation is attributed to the function type instead of the property and therefore not inherited.

This broke going from version v0.20.37 to v0.21.0.

<details>
<summary>Result in v0.20.37</summary>

Doc of `Bar`:

![image](https://user-images.githubusercontent.com/20878432/124954651-99d97600-e016-11eb-8c9f-13b316c736cd.png)

Doc of `Foo`:

![image](https://user-images.githubusercontent.com/20878432/124954681-a067ed80-e016-11eb-9ab6-dbe57108fec8.png)

</details>

<details>
<summary>Result in v0.21.0</summary>

Doc of `Bar`:

![image](https://user-images.githubusercontent.com/20878432/124954227-26cfff80-e016-11eb-9ad8-40cc4c57e994.png)

Doc of `Foo`:

![image](https://user-images.githubusercontent.com/20878432/124954122-0f911200-e016-11eb-9217-54777d96cc9d.png)

</details>

## Steps to reproduce the bug

[Here is a minimal repo](https://github.com/TypeStrong/typedoc/files/6785821/example.zip) reproducing the bug.

Just run `npm ci && npm run docs` to generate the `docs` folder.

## Environment

-   Typedoc version: v0.21.x
-   TypeScript version: 4.2.4
-   Node.js version: v14.15.4
-   OS: Win10

**Comment by Gerrit0** [comment]
I like your bugs :) Very helpful to have an tiny reproduction!
