### ISSUE TITLE
Support for non-tip LTS versions of node

### ISSUE THREAD

**Issue by betaorbust** [TypeStrong/typedoc#1628]
Currently, the `engines` setting in typedoc breaks yarn installs on all machines not running tip LTS. Is there a known hard requirement for 12.20, or could it be relaxed back to 12?

## Search terms
Node version, minimum version

## Expected Behavior
Allows installing on non-tip Node 12

## Actual Behavior
Yarn aborts at install because minimum version is not supported.
```
error typedoc@0.21.4: The engine "node" is incompatible with this module. Expected version ">= 12.20.0". Got "12.19.1"
error Found incompatible module.
```

![image](https://user-images.githubusercontent.com/921683/125696770-d04c4502-b7ac-4d41-ac71-8aee2e591a87.png)

## Steps to reproduce the bug
```sh
mkdir test && cd test && yarn init -y.  # Set up test package
nvm use 12.19                           # Use < 12.20
yarn add typescript typedoc --dev       # install 
```

## Environment

-   Typedoc version: Latest
-   TypeScript version: Latest
-   Node.js version: LTS<12.20
-   OS: Mac

**Comment by Gerrit0** [comment]
There was a requirement for it, in that part of TypeDoc used `node:` style imports when `@types/node` would suggest those imports over the older ones, I think they have all been removed now though... it could probably be relaxed. https://nodejs.org/api/esm.html#esm_node_imports.

**Comment by betaorbust** [comment]
Just went to make a PR and tested that it works (tests complete correctly) down to 12.10.0, but lower than that and there are test errors. I'll relax it back to there in the PR.

Would you like the testing matrix in ./github/workflows/ci.yml to change to 
```diff
name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
-                node: ["12", "14", "16"]
+                node: ["12.10", "12", "14", "16"]
        name: Node ${{ matrix.node }
```
to reflect the engine limitations (while still testing against lts tip), just `12.10`, or just `12`?

**Comment by betaorbust** [comment]
I believe the project can work lower than 12.10, but https://github.com/TypeStrong/typedoc/commit/5ffe73d734a8d276ae87e3b071ece7c6cca4f7a5 removed fs-extra in favor of `rmdir({recursive: true})` which only has support from 12.10.
https://github.com/TypeStrong/typedoc/blob/8ff7d32dc31dccd26b42d96ba4bebb5b430867f4/src/lib/utils/fs.ts#L145

Didn't know what your feelings were on reintroducing `fs-extra`, `del` or rolling your own for greater compatibility, but I'll put in the PR to pull it back to 12.10 for now.

**Comment by Gerrit0** [comment]
I'd rather not add more dependencies - as time goes on I've become more and more reluctant to add third party code to projects I maintain. There are some dependencies that it's definitely worth having (I wouldn't want to write `glob`!), but for trivial things like this, that is supported by recent versions of Node itself, dependencies are just bloat.

Node 12 itself is already heading towards EOL, I don't think it's worth it to spend time trying to support lower and lower versions when all support for node 12 is going to be dropped the day it hits EOL. If you're stuck on a older version of Node, you have my utmost sympathies, and encouragement to fight whatever process is keeping you from upgrading Node (If it's cyber approval... don't they realize that Node upgrades aren't just noise? [there are real issues](https://nodejs.org/en/blog/vulnerability/july-2021-security-releases/))
