### ISSUE TITLE
Support of code tags

### ISSUE THREAD

**Issue by benzid-wael** [TypeStrong/typedoc#163]
I think that it will be great if we can generate boxes from code tags. Maybe we can add decorators like: @todo, @fixme, etc.

I'm interesting on developing this feature, but unfortunately I didn't know from where to start. Did you have any reference for the typedoc execution life cycle ?

**Comment by aciccarello** [comment]
@benzid-wael Can you describe your idea any more? What would you write in your code and what would the output be?
