### ISSUE TITLE
TypeDoc documents in gh-page return '404 not found' except files in docs root

### ISSUE THREAD

**Issue by ApexCaptain** [TypeStrong/typedoc#1633]
## Search terms
typedoc, github page, 404, not found

## Question

Hi guys, I'm trying to create an api documnet of my node module and host it on gh-page using `TypeDoc`.

Honestly, I did it and succeeded it about a year ago. I faced a similar trouble back then however I've solved it by adding file named `.nojekyll` in `docs` root even withouth knowing what it is or how does it work. 

About a week ago, I was surprised to realize my document page is not working properly. Here's my docs directory pic.

![pic1](https://user-images.githubusercontent.com/39866332/125898958-934cdcc3-7eae-4db3-b2d3-6abf5475b47c.png)

`index.html` and `modules.html`, which are in `docs` root directory work beautifully at gh-page.
But, rest of'em, e.g., `classes`, `enums`, `interfaces` etc always return `404 Page Not Found`.

I have no idea how to fix this.
Plz, help me...

Here's my [Page Link](https://apexcaptain.github.io/Koconut/)

**Comment by Gerrit0** [comment]
This looks like a Windows vs Linux problem. File names are no longer lowecased, so the lowercase names in your git repo won't work. I recommend deleting your docs directory in one commit, then regenerating it in a second one.

**Comment by ApexCaptain** [comment]
Now I see... um, after I rendered documents inside a docker container, then it works. But, I do want to set the titles of html pages to be synchronized with href url paths, or in a nutshell make'em named as the original titles of TypeSscript files in windows env. Is it possible? Do I have to add some kind of extra attributes into typedoc.json?

**Comment by Gerrit0** [comment]
You can do it in Windows, but because Windows paths are generally case insensitive, you need to fully remove the path from your repository in one commit, then regenerate the docs folder in a second one.

**Comment by ApexCaptain** [comment]
Is that it? Oh, my goodness... it really does work! I've been wasting so much time searching for this... Thank you very much.

**Comment by donmccurdy** [comment]
Could this issue be flagged in the release notes to mention that URLs generated by TypeDoc will change? The current note... 

> Two members differing only by case produced broken links (f909281), closes #1585 ...

... does not make it obvious that _all_ URLs are affected, even if your project has no members differing only by case.

Ideally this would have been a 'major' semver change (or minor since Typedoc is <v1.0) from my perspective – not all webservers are case insensitive, so this can create broken links that are not backward-compatible.

**Comment by Gerrit0** [comment]
I've updated the release notes to point out this pitfall, if I had thought about it some more, it probably would have waited until 0.22... but it's too late for that now.

**Comment by aleksei-berezkin** [comment]
Thanks, was exactly my case. It would be nice to output a warning into the console when TypeDoc detects changed case of the generated HTML page, if it's possible.
