### ISSUE TITLE
Type alias of callback/function does not show in doc

### ISSUE THREAD

**Issue by hwsiew** [TypeStrong/typedoc#1636]
## Search terms
type alias, callback argument, function 

## Expected Behavior
Display type alias of a function in the doc

## Actual Behavior
It doesn't show.

## Steps to reproduce the bug
1. create a class
```typescript
// class.ts
/**
 * @param {*} a currently highest priority element
 * @param {*} b next element to compare
 * @returns {boolean};
 */
type CompareFunction = (a: any, b: any) => boolean

export default class PriorityQueue {
    constructor(compareFn?: CompareFunction){}
}
```
2. run `npx typedoc` to generate documents
3. Check the document
![image](https://user-images.githubusercontent.com/51040350/126105638-3cd1d604-381f-43ab-862f-bc6103d23121.png)
4. E.g. Argument of constructor does not show details of CompareFunction 

## Environment

-   Typedoc version: 0.21.4
-   TypeScript version: 4.3.5
-   Node.js version: 14.16.1
-   OS: Window

**Comment by Gerrit0** [comment]
This is expected behavior, TypeDoc only documents what you export, and `CompareFunction` is not exported.

```ts
/**
 * @param {*} a currently highest priority element
 * @param {*} b next element to compare
 * @returns {boolean};
 */
export type CompareFunction = (a: any, b: any) => boolean

export default class PriorityQueue {
    constructor(compareFn?: CompareFunction){}
}
```

Will result in `CompareFunction` being clickable to take you to the type alias documentation.

**Comment by hwsiew** [comment]
Thanks
