### ISSUE TITLE
Function property is mis-interpreted as method

### ISSUE THREAD

**Issue by hez2010** [TypeStrong/typedoc#1637]
## Search terms

Function property, method

## Expected Behavior

```ts
interface Foo {
    prop: () => void
}
```

This should be interpreted as a function property:
```json
"name": "prop",
"kind": 1024,
"kindString": "Property",
"flags": {},
...
```

## Actual Behavior

Instead, typedoc generates a method node for it:

```json
"name": "prop",
"kind": 2048,
"kindString": "Method",
"flags": {},
...
```

## Steps to reproduce the bug
test.ts:
```ts
interface Foo {
    prop: () => void
}
```

tsconfig.json:
```
{
    "compilerOptions": {
        "target": "es2020"
    }
}
```

```
typedoc test.ts --json result.json
```

## Environment

-   Typedoc version: 0.21.4
-   TypeScript version: 4.4
-   Node.js version: v14.17.0
-   OS: Windows 11

**Comment by Simek** [comment]
Refs #1624 (98331b5b1a0248753b98c895d1b2168c31e3cee7)

In current project I'm using TypeDoc raw data output. It looks like after the change mentioned above the React/React Native functional components props data has been stripped or moved. If I downgrade to `0.21.2` the output is correct again, but there are still comment data missing or misplaced in few cases. The only solution for me right now was a revert to latest version from `0.20` branch.

**Comment by Gerrit0** [comment]
> This should be interpreted as a function property:

From a code generation perspective that targets compiled languages, I can see your point here... however, I'm not sure that this behavior is something that should be reverted. TypeDoc has done the same thing for property-methods for a long time, its detection for these was just improved in a way that broke your use case.

```ts
class Foo {
  iAmMethod = (x: string) => parseInt(x)
}
```

> React/React Native functional components props data has been stripped or moved too.

I can't seem to reproduce this, open a new issue with a reproduction to keep different problems separate please.

**Comment by tsvetomir** [comment]
Just got bitten by this issue after an upgrade. Seems wrong for my particular use case too.

Now the same member will show as a method in the interface and as a property in the implementing class:

```ts
interface Foo {
    prop: () => void;

// "kindString": "Method"
}

class FooClass implements Foo {
    prop: () => void;

//  "kindString": "Property",
//  "implementationOf": {
//      "type": "reference",
//      "name": "Foo.prop"
//  }
}
```

**Comment by Gerrit0** [comment]
Hmm... that's actually a really good argument for not turning property-methods into methods in type space...

Once TS 4.7 releases, with explicit variance annotations, it won't be necessary to declare intended methods as properties in order to get the correct variance, which *should* make property-methods less frequent... if the comment plugin is updated so that it can properly inherit comments from property-methods, I think I'm okay with reverting this...
