### ISSUE TITLE
Error: error TS5055: Cannot write file '...' because it would overwrite input file.

### ISSUE THREAD

**Issue by balupton** [TypeStrong/typedoc#1639]
## Search terms

```
> typechecker@7.17.0 our:meta:docs:typedoc
> rm -Rf ./docs && typedoc --exclude '**/+(*test*|node_modules)' --excludeExternals --out ./docs ./source

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/async.js' because it would overwrite input file.

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/classes-compiled.js' because it would overwrite input file.

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/classes.js' because it would overwrite input file.

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/index.js' because it would overwrite input file.

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/map-empty.js' because it would overwrite input file.

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/map.js' because it would overwrite input file.

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/weakmap-empty.js' because it would overwrite input file.

Error: error TS5055: Cannot write file '/Users/balupton/Projects/auto-fixes/typechecker/test-fixtures/weakmap.js' because it would overwrite input file.
```

## Expected Behavior

those files to be ignored due to the `--exclude` pattern

## Actual Behavior

didn't work

## Steps to reproduce the bug

```
git clone https://github.com/bevry/typechecker.git
cd typechecker
npm install
npm run our:release:prepare
```

## Environment

-   Typedoc version: `0.21.4`
-   TypeScript version: `4.3.5`
-   Node.js version: `16.5.0`
-   OS: ` Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 x86_64` - m1 mac mini 11.5.1 (20G80)

**Comment by balupton** [comment]
Solved by adding `"exclude": ["test-fixtures", "node_modules", "source/test.ts"]` to tsconfig, and `// @ts-ignore` to the fixture files

**Comment by balupton** [comment]
actually, that causes my test file not to compile - so I don't know

**Comment by balupton** [comment]
Tried this too, but to no avail

```
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "maxNodeModuleJsDepth": 5,
    "moduleResolution": "Node",
    "strict": true,
    "target": "ES2019",
    "module": "ESNext"
  },
  "include": ["source"],
  "exclude": ["test-fixtures", "node_modules"],
  "typedocOptions": {
    "exclude": "**/+(*test*|node_modules)",
    "externalPattern": "test-fixtures/*",
    "excludeExternals": true,
    "excludeInternal": true,
    "excludeNotDocumented": true,
    "excludePrivate": true,
    "excludeProtected": true,
    "entryPoints": ["source/index.ts"],
    "out": "docs"
  }
}
```

giving up for now

**Comment by Gerrit0** [comment]
TypeDoc's behavior matches the behavior of `npx tsc`, which is expected.

Running `npx tsc --explainFiles` shows that your include pattern of "source" means that "source/test.ts" is included in the program, which means that all the files in test-fixtures are also included. If you change the include pattern to only include source/index.ts, TypeScript (and therefore TypeDoc) won't look at your test-fixtures directory.

Alternatively, set a output directory with `"outDir": "dist"` in your tsconfig and TypeScript will no longer have this error since it won't be trying to write JS files into the same directory they were discovered from.

**Comment by balupton** [comment]
So as we have multiple out dirs for different targets I should just set outDid to "/tmp" for typedoc?

**Comment by Gerrit0** [comment]
You could also put `"noEmit": true` in your tsconfig, which is maybe something typedoc should do unless --emit is specified...

**Comment by balupton** [comment]
> typedoc should do unless --emit is specified...

that would be great, as this is already the implied behaviour of it:

```
 --emit                    If set, TypeDoc will emit the TypeScript compilation result
```

**Comment by Gerrit0** [comment]
You put `outDir` in the wrong place - it lives within `compilerOptions`.. I think I will make typedoc behave as if noEmit is set unless --emit is specified.

**Comment by balupton** [comment]
> I think I will make typedoc behave as if noEmit is set unless --emit is specified.

Great, this works (editions are compiled, documentation is compiled) as a workaround:

```
{
  "compilerOptions": {
    "outDir": "/tmp",
    "allowJs": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "maxNodeModuleJsDepth": 5,
    "moduleResolution": "Node",
    "strict": true,
    "target": "ES2019",
    "module": "ESNext"
  },
  "include": ["source"]
}
```

> I think I will make typedoc behave as if noEmit is set unless --emit is specified.

That will be great, thank you.
