### ISSUE TITLE
Live server for theme development

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/typedoc#1640]
## Search Terms

theme

## Problem

For theme developers, it is slow to make theme changes, re-run typedoc and see the results

## Suggested Solution

A typedoc plugin which hosts a livereload webserver and watches the filesystem for theme changes
When theme source code changes on disc, re-load the theme (clear `require()` cache as necessary), re-render into memory, and refresh the webserver.

This plugin does not need to detect changes in the typescript being documented; it only checks for changes to the theme and re-renders the reflections it has already computed.

**Comment by Gerrit0** [comment]
This will be made much easier once we can render docs from JSON - then the watcher can set up typedoc itself.

I marked this with plugin-idea, but I think it would probably be more easily implemented as a wrapper around typedoc that does something similar to the script in bin.

**Comment by Gerrit0** [comment]
https://github.com/citkane/typedoc-hot-dev
