### ISSUE TITLE
Add dark/light theme toggle to default themes

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/typedoc#1641]
## Search Terms

theme

## Problem

These days, docsites often have a toggle to switch between light and dark themes, and they default to matching the OS's theme preference.

## Suggested Solution

Colors from here: https://github.com/rockerBOO/typedoc-default-themes-dark
Toggle UI via https://github.com/GoogleChromeLabs/dark-mode-toggle
And ask Futuristick to give it their frontend polish and make it pretty.

**Comment by Rami-Sabbagh** [comment]
I really like `TypeDoc` and using it for many of my projects, and it would be very cool to have a dark mode.
As my own libraries documentation websites kill me at night 😬

**Comment by furkanarabaci** [comment]
Yes please, would be awesome!

**Comment by Gerrit0** [comment]
Will be available through `typedoc@beta` shortly - just need to fix a few more issues.

![image](https://user-images.githubusercontent.com/19329837/132110535-9f69b5fb-a2dd-4dd2-aa77-bd32560a3888.png)

![image](https://user-images.githubusercontent.com/19329837/132110554-dfa8761e-d4ac-4cda-bdd8-0efda499e082.png)

![image](https://user-images.githubusercontent.com/19329837/132110561-391419ca-2e9a-4e1a-8a76-d4629e6e19ba.png)

**Comment by aaclayton** [comment]
Is there a way to suggest the default theme that should be used? Currently the default for new users is "OS", but if I wanted to have the default theme prefer dark by default, is it possible?

**Comment by Gerrit0** [comment]
https://github.com/TypeStrong/typedoc/issues/1840#issuecomment-1012736455

**Comment by aaclayton** [comment]
Thanks, this isn't *quite* what I'm looking for because I'm not wanting to force all users to have a specific theme, but rather to change the default for a user who has not yet selected a preference to be "Dark" (desired default) instead of "OS" (current default). I can play with this plugin idea and likely accomplish it via a similar approach, unless that alters your answer.

**Comment by Gerrit0** [comment]
Re-reading my linked post... that's kind of confusing, but your desired behavior is what that plugin does.
