### ISSUE TITLE
Error: Unknown option: --ignoreCompilerErrors

### ISSUE THREAD

**Issue by Thinking80s** [TypeStrong/typedoc#1643]
## Search terms

typedoc --out ~/Downloads/ --tsconfig ./tsconfig.json --entryPoints ./src/ --ignoreCompilerErrors 

![image](https://user-images.githubusercontent.com/338079/127733233-bf0a7201-c080-4e3f-88fb-9f452202bb51.png)

**Comment by krisztianb** [comment]
I guess you updated to a newer version of TypeDoc, right?

That option was removed in version 0.20: https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0

**Comment by ouya99** [comment]
@Gerrit0 I do not get my paths to work and receive a TS2307 on every single import. Yet my TS-compiler does not complain when building the project. is "typedoc --tsconfig tsconfig.json" the correct syntax?

**Comment by Gerrit0** [comment]
If you compile with `tsc`, then `typedoc path/to/entry.ts` should work. If you compile with a custom tsconfig file name, (e.g. `tsc --project custom.tsconfig.json`), then `typedoc --tsconfig custom.tsconfig.json` should work.

If TypeDoc is complaining in some case where plain `tsc` is not, that's probably a bug, and I'd love a reproduction
