### ISSUE TITLE
Global namespaces not included

### ISSUE THREAD

**Issue by y-nk** [TypeStrong/typedoc#1649]
## Search terms

global, namespace

## Question

I'm authoring a library, and so my main entrypoint is `index.ts`. Inside this file, I have a simple: `import './@types/index.ts'` which imports all my types at once. My `./@types/index.ts` also contains roughly `import ./myType.ts`.

My `./myType.ts` contains the blueprint:

```
export {}

declare global {
  namespace MyLib {
    type MyType = {
      prop1: string
    }
  }
}
```

The overall idea is that, anyone importing my library will do so from the entrypoint, which will include the @types, and declare the namespace globally ; the result being that the user can have the types globally exposed (for convenience) within the security of the namespace's name.

It works perfectly fine in vscode, but it seems not working at all for typedoc.

Do you have any idea how to fix this? Should i refactor my code for something more standard which could please typedoc?

Thanks.

**Comment by Gerrit0** [comment]
TypeDoc documents what you export, and new globals aren't exports. If you wanted TypeDoc to document a namespace `MyLib`, you could do this:

```ts
// import MyLib instead of const MyLib so that TypeScript includes both types and values.
export import MyLib = globalThis.MyLib

declare global {
  namespace MyLib {
    type MyType = {
      prop1: string
    }
  }
}
```

... but that means people would have to do
```ts
import { MyLib } from "mylib"
type Z = MyLib.MyType
```

if they didn't want to use globals, which is kind of annoying.

Personally, I'd drop the globals, but you could, with the price of duplication, have both.

```ts
export type MyType = {
    prop1: string;
};

import type * as _MyLib from "./foo";
declare global {
    namespace MyLib {
        type MyType = _MyLib.MyType;
    }
}
```
