### ISSUE TITLE
Classes don't use type information from interface?

### ISSUE THREAD

**Issue by HomenSimpsor** [TypeStrong/typedoc#165]
If an interface supplies type information, is the implementation required to repeat it?

Class:

![image](https://cloud.githubusercontent.com/assets/2061925/11801054/27d350b6-a2b0-11e5-84a5-7432c461c6fb.png)

![image](https://cloud.githubusercontent.com/assets/2061925/11801071/420d529c-a2b0-11e5-9979-890316290be9.png)

Interface:

![image](https://cloud.githubusercontent.com/assets/2061925/11801060/309b2e44-a2b0-11e5-9143-4f93e49706dc.png)

![image](https://cloud.githubusercontent.com/assets/2061925/11801084/5365a706-a2b0-11e5-8acb-dc1f9ff3d62a.png)

Additionally, the description isn't loaded in (just says `inheritdoc` as if there's nothing in the implementation to show).

If I keep all the types except the return value, the description shows again:

![image](https://cloud.githubusercontent.com/assets/2061925/11801124/d3e8aff4-a2b0-11e5-8866-b6ba04c6e253.png)

![image](https://cloud.githubusercontent.com/assets/2061925/11801136/f5cde472-a2b0-11e5-911e-ced6fe26f67d.png)

**Comment by mattflix** [comment]
Perhaps this issue would be more clearly named, "Add support the @inheritdoc tag, a la JSDoc".

**Comment by enepomnyaschih** [comment]
+1

I need this feature desperately as well. Important to mention that it is not only related to interface -> class inheritance, but also to interface -> interface and class -> class.

I haven't managed to implement this feature in my fork. It looks like TypePlugin doesn't resolve `overwrites` type for fields and methods very well, or does it after ImplementsPlugin processing. Only constructors are resolved properly.

**Comment by Gerrit0** [comment]
TypeDoc's behavior is consistent with TypeScript's, yes, the implementing class must repeat type information from the interface.

```ts
interface Interface {
  method(a: string, b: number): void
}

class Class implements Interface {
  method(a, b) {
    b.substring(1, 2) // but wait, a is the string! TS doesn't know since the parameters aren't typed.
  }
}
```
