### ISSUE TITLE
Function with properties shown as variable

### ISSUE THREAD

**Issue by y-nk** [TypeStrong/typedoc#1651]
## Search terms

Functions type property

## Expected Behavior

Functions should be listed as functions

## Steps to reproduce the bug

```
// will be seen as function in typedoc
const foo = () => {}

// will be seen as variable in typedoc
const bar = () => {}
bar.metadata = "baz"
```

## Environment

-   Typedoc version: latest
-   TypeScript version: latest

**Comment by Gerrit0** [comment]
This happens because it isn't caught as a special case in the converter

https://github.com/TypeStrong/typedoc/blob/9d84e2ef5f3321cb743f9befd3a92084b67dd244/src/lib/converter/symbols.ts#L771-L773

Fixing it would involve updating that to also create a namespace for any properties.

Workaround:
```ts
const bar = () => {}
namespace bar {
  export const metadata = "baz"
}
```

**Comment by Gerrit0** [comment]
Note: Should probably do this only if the extra properties are defined with a PropertyAccessExpression. It would make #1735 worse to do it in every case.

**Comment by nicholasio** [comment]
This is causing me trouble when working with React `defaultProps`. I don't want to create a separate namespace for my components just becase of `defaultProps` is there a way to disable generation of a particular namespace?

```jsx
export function ReactComponent({ children }) {
	return (
		<>
			{children}
		</>
	);
}

// this creates a "ReactComponent" namespace with a "defaultProps" object.
ReactComponent.defaultProps = {
	someProp: '',
};
```

**Comment by Dayday10** [comment]
?

**Comment by Gerrit0** [comment]
Apparently some TS version changed how symbol flags were set, because in TS 4.7.2, with no code changes, the following gets converted as a variable and a namespace.

```ts
const bar = () => {}
bar.metadata = "baz"
```

I'm going to go ahead and make the change to convert a variable as a function if it contains any call signatures... hopefully it doesn't make worse documentation in some edge case I'm not thinking of right now.

**Comment by y-nk** [comment]
@Gerrit0 thank you for the long-term follow-up this is highly appreciated. 🙏
