### ISSUE TITLE
Support a @group tag

### ISSUE THREAD

**Issue by milesj** [TypeStrong/typedoc#1652]
## Search Terms

group, @group

## Problem

It would be nice if `@group` is supported. I know there is `@category`, but that doesn't organize at the top-level, only within groups.

I mainly would like this feature so that React components and hooks can be organized into groups, instead of being in "Functions" or "Classes".

## Suggested Solution

N/A

**Comment by Gerrit0** [comment]
I suspect setting categorizeByGroup: false might let you do what you want with the category tag

**Comment by milesj** [comment]
While that technically works, it does put everything else in the "Other" category... which is kind of annoying.

**Comment by Gerrit0** [comment]
Makes sense 👍 this seems reasonable to me.
