### ISSUE TITLE
Exclude files from search

### ISSUE THREAD

**Issue by painor** [TypeStrong/typedoc#1655]
## Search Terms

Exclude search

## Problem

I have some auto generated things in my project that I want to have documentation HTML files for but I do not want them to show up in the search query. 

## Suggested Solution

Probably the easiest way to solve this is to add an excludeSearch option and use that to exclude the files in the JavascriptIndexPlug file.

**Comment by Gerrit0** [comment]
With the changes in v0.23.4, this can now be done pretty easily with a plugin, and given that it seems that the demand for this isn't very high, it seems like it will fit best there.

```ts
const td = require("typedoc")

/** @param {td.Application} app */
exports.load = function(app) {
  app.renderer.on(td.Renderer.EVENT_PREPARE_INDEX, filterIndex);
}

/** @param {td.IndexEvent} index */
function filterIndex(index) {
  for (let i = 0; i < index.searchResults.length; /* in loop */) {
    // update this as appropriate, index.searchResults[i].sources is probably good enough for a personal plugin.
    if (index.searchResults[i].name === "excludeMe") {
      index.removeResult(i);
    } else {
      i++
    }
  }
}
```
