### ISSUE TITLE
Typedoc not render properties for object

### ISSUE THREAD

**Issue by nameczz** [TypeStrong/typedoc#1656]
## Search terms
params, property

## Expected Behavior

Render all properties , when use interface alias.

I tried multiple ways, only this way successful. 

![image](https://user-images.githubusercontent.com/20559208/129473552-434a1dbf-2433-4cda-825d-d47a5fdf3504.png)
![image](https://user-images.githubusercontent.com/20559208/129473611-b984a3e6-f922-412e-92fa-60d8077dcd1c.png)

**But i need to use interface alias to define type...** 
Thanks for any suggestions.

## Actual Behavior
![image](https://user-images.githubusercontent.com/20559208/129473302-002f21f8-2510-4ba8-b304-af6cc2859019.png)

![image](https://user-images.githubusercontent.com/20559208/129473296-ace4a46a-89d3-4bb3-8726-1a50b8871f91.png)

![image](https://user-images.githubusercontent.com/20559208/129473328-d4b23e1e-5b89-405f-9c1c-47de243a5490.png)

![image](https://user-images.githubusercontent.com/20559208/129473331-2bd08aa0-3e68-4a84-badc-e203a76682f9.png)

## Steps to reproduce the bug

You can check: https://github.com/milvus-io/milvus-sdk-node
Branch: doc

## Environment

-   Typedoc version: ^0.20.35
-   TypeScript version: 4.2.4
-   Node.js version: v14.16
-   OS: 10.15.7

**Comment by Gerrit0** [comment]
Sorry, this slipped under my radar somehow.

This is expected behavior, TypeDoc doesn't display the members of a referenced type because they will likely have many properties that aren't relevant when a user is viewing the documentation, and clicking on the reference will take them to a page which fully describes the interface.

**Comment by nameczz** [comment]
OK. Thanks for your support!
