### ISSUE TITLE
Documenting directories?

### ISSUE THREAD

**Issue by rauschma** [TypeStrong/typedoc#1659]
## Search Terms

directory, folder, documentation

## Problem

Directories usually group related source code files. It’d be nice if there were a way to document those files _as a group_: “This directory contains various helper modules. […]”

## Suggested Solution

One option:

* If TypeDoc detects a file `directory-info.md` in a directory, it uses that file to document the directory.

**Comment by Gerrit0** [comment]
TypeDoc doesn't deal with directories at all... What would this give you that adding a module comment to index.ts in the directory doesn't?
