### ISSUE TITLE
typedoc does not handle shiki language aliases

### ISSUE THREAD

**Issue by StoneCypher** [TypeStrong/typedoc#1672]
## Expected Behavior

`typedoc` should understand language aliases.

Many languages in shiki have aliases.  At this time `typedoc` believes that these aliases are "fakes" and [manually handles the five](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/highlighter.ts#L8) for `typescript`-as-`ts`, `javascript`-as-`js`, and `shell`-as-[`sh`, `bash`, `zsh`] in creating the supported language list.

Shiki offers an `aliases` field which should be walked instead.  Many other aliases, such as `ruby`-as-`rb`, `python`-as-`py`, `jssm`-as-`fsl` and so on are being missed, and the ones being manually loaded become unnecessary.

## Actual Behavior

`typedoc` does not understand language aliases, except the five manually added to the list.

## Steps to reproduce the bug

Attempt to highlight the following two blocks.

```
\```ruby
puts "this will work";
\```
```

```
\```rb
puts "this will not work, but should";
\```
```

Note: that backslash shouldn't be there, I just don't know how to quote a triple tick in a fence block

PR incoming

## Environment

-   Typedoc version: 0.21.8
-   TypeScript version: irrelevant
-   Node.js version: irrelevant
-   OS: irrelevant

**Comment by Gerrit0** [comment]
So that's where those are defined! I figured they must be listed somewhere, but never ended up discovering where.
