### ISSUE TITLE
Generating documentation while using webpack 4 and ts-loader.

### ISSUE THREAD

**Issue by itsjamie** [TypeStrong/typedoc#1674]
## Search terms

webpack, ts-loader, yarn, workspace

## Expected Behavior

I expected that I could document a package in a Yarn workspace that had been bundled using webpack. The command would look something like: typedoc --packages ./packages/<name>

## Actual Behavior

The issue is that the detection logic doesn't pick up the original source file of the package.

```Entry point "/<snip>/build/webpack:/webpack/universalModuleDefinition" does not appear to be built by the tsconfig found at "/<snip>/tsconfig.json"```

## Steps to reproduce the bug

Run `yarn webpack --mode production`.
Output a `umd` bundle.
With the `devtool` setting: `source-map`
Using: `typedoc --packages ./packages/<name>`.

Types are generated using `tsc` directly, and output to a `lib-types` and a `d.ts` rollup is done using `api-extractor`.

Webpack:
- Entrypoint: "src/index.ts"
- Output: "build/index.js"

package.json:
- main: "build/index.js"
- typings: "build/index.d.ts"

Versions:
- webpack: ^4
- ts-loader: ^8

## Environment

-   Typedoc version: 0.21.9
-   TypeScript version: 4.2.4
-   Node.js version: v12.20.1
-   OS: OSX

**Comment by Gerrit0** [comment]
--packages mode needs to be able to determine where your entry point came from. Right now, it does that exclusively through sourcemaps. I think trying to figure out the original entry point from a bundler is out of scope for TypeDoc. There are too many bundlers, and *way* too many ways to configure them.

It seems reasonable to me to log a warning in this case and fall back to the typings field.

**Comment by itsjamie** [comment]
@Gerrit0, I added a PR, I took a slightly different approach, adding an escape hatch at the package.json level to allow a user to point at a `tsc` generated build structure for documentation.

This way you can always test just with `tsc` output.

**Comment by itsjamie** [comment]
> It seems reasonable to me to log a warning in this case and fall back to the typings field.

Related to this, because of the use of api-extractor even falling back to the typings field caused an issue. So, we could script a `sed` change of the package.json to achieve the same thing that the PR in #1677 does, but I figured it might well be a nice addition for you to push people towards the understanding that `typedoc` works on `tsc` output.
