### ISSUE TITLE
Support for `as const` enums

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1675]
## Search Terms

`as const`, enumerations

## Problem

Since TypeScript's `enum` is rather inconvenient to work with, some packages define their own enum-like objects, TypeDoc does this too.

https://github.com/TypeStrong/typedoc/blob/664e27cfe7b0a91ca3ea8b299f89ca265238fb8c/src/lib/utils/entry-point.ts#L15-L35

However, the generated documentation doesn't make it obvious that this value should be treated as an enumeration.

![image](https://user-images.githubusercontent.com/19329837/132142432-1546c005-b374-4703-ac05-1ec736629599.png)
![image](https://user-images.githubusercontent.com/19329837/132142452-e816e14e-1b6f-4614-9837-2fb868f5406a.png)

## Suggested Solution

Detect variables annotated with `@enum` with all readonly properties that are string literals, and convert them as an enumeration.

If there is also a type alias by the same name whose content is `typeof T[keyof typeof T]`, remove it from the documentation since enums are also types.

**Comment by Gerrit0** [comment]
I'm going to look at this again before releasing 0.23, should TypeDoc do this even if you don't tag the variable with `@enum`?

Vote: :+1: :-1:

**Comment by michkot** [comment]
@Gerrit0 Could this be extended for enum-object declarations?

eg. instead of 

> /** @enum */
> export const EntryPointStrategy = { 
>      /** 
>       * abcd
>       */ 
>      Resolve: "resolve", 
>  } as const; 

there is (in .d.ts ) just

> /** @enum */
> export const EntryPointStrategy: { 
>      /** 
>       * abcd
>       */ 
>      readonly Resolve: "resolve", 
>  }; 

there is even a "convenience variant":
> /** @enum */
> export const EntryPointStrategy: Readonly<{ 
>      /** 
>       * abcd
>       */ 
>      Resolve: "resolve", 
>  }>; 

I am happy to open new issue for this if this is doable!
