### ISSUE TITLE
Typedoc Behavior on Default Exports

### ISSUE THREAD

**Issue by furkanarabaci** [TypeStrong/typedoc#1676]
## Search terms
default export, export default

## Question

The following code which uses export default:
```
/** 
 * Some documentation
 */
export default class Table implements TableInitOptions {
  /** Web equivalent of CSS properties */
  styleTypes: Readonly<typeof Styles> = Styles;
  webView: WebView | WebViewBridge;
  tableOptions: TableOptions;
```
Generates the following documentation:
![image](https://user-images.githubusercontent.com/12798126/132291819-fbfa52fe-caa7-495f-9ac0-ad9e9d342ca9.png)

I can see the desired documentation output at the default section, but is it possible to move those outside of the default?

Since the syntax `export default Table` indicates that it will be used directly within the module, it shouldn't be defined as different variable. I suspect it takes `default` as named export?

**Comment by Gerrit0** [comment]
> I suspect it takes `default` as named export?

Yes, this is exactly what it does, because:

```ts
export default Foo // is equivalent to
export { Foo as default } // this
```

`export default` is just special syntax for creating a named export called `default`, and `import Def from "mod"` is special syntax for importing the named export called `default` (+ some special handling in Node's ESM implementation)

You could lift the contained reflections up to the top level with a plugin fairly easily (untested):

```ts
import { Application, Converter } from "typedoc"

export function load(app: Application) {
  app.converter.on(Converter.EVENT_RESOLVE_BEGIN, (context) => {
    // Some extra sanity checks would be good here.
    // context is of type Context, which typedoc <0.22 doesn't publicly export
    const project = context.project;
    const oldDefault = context.project.children.find(r => r.name === "default");
    for (const child of oldDefault.children) {
      project.children.push(child)
      child.parent = project;
    }
    oldDefault.children = undefined;
    project.removeReflection(oldDefault);
  });
}
```

**Comment by furkanarabaci** [comment]
> > I suspect it takes `default` as named export?
> 
> Yes, this is exactly what it does, because:
> 
> ```ts
> export default Foo // is equivalent to
> export { Foo as default } // this
> ```
> 
> `export default` is just special syntax for creating a named export called `default`, and `import Def from "mod"` is special syntax for importing the named export called `default` (+ some special handling in Node's ESM implementation)
> 
> You could lift the contained reflections up to the top level with a plugin fairly easily (untested):
> 
> ```ts
> import { Application, Converter } from "typedoc"
> 
> export function load(app: Application) {
>   app.converter.on(Converter.EVENT_RESOLVE_BEGIN, (context) => {
>     // Some extra sanity checks would be good here.
>     // context is of type Context, which typedoc <0.22 doesn't publicly export
>     const project = context.project;
>     const oldDefault = context.project.children.find(r => r.name === "default");
>     for (const child of oldDefault.children) {
>       project.children.push(child)
>       child.parent = project;
>     }
>     oldDefault.children = undefined;
>     project.removeReflection(oldDefault);
>   });
> }
> ```

Thank you for replying, I have bumped my version to beta, which uses `0.22.0-beta.10` right now. Now I also have theme switch 💯 

For the task at hand, I have tweaked on par with my liking:

- The module I am documenting has lots of submodules, so I used children of the children instead
- As far as I tested the process, this default not showing behavior only happens when the default export is class. It doesn't happen when the default export is Function or a variable, so I only did this fix to the class. I did that via using `kind: 128`.
- Sanity checks are done via ?. nullish operator :)

```
async function main() {
  const app = new Application();
  app.converter.on(Converter.EVENT_RESOLVE_BEGIN, (context) => {
    // context is of type Context, which typedoc <0.22 doesn't publicly export
    context.project?.children?.forEach(submodule => {
      const oldDefault = submodule?.children?.find((reflection) => reflection.name === "default" && reflection.kind === 128);
      oldDefault?.children?.forEach((child) => {
        submodule.children.push(child)
        child.parent = submodule;
      });
      if (oldDefault) {
        oldDefault.children = undefined;
        context.project.removeReflection(oldDefault);
      }
    });
  });
// rest of the typedoc generation code
}
```

I guess this can be implemented as a plugin or maybe included by default. So far, the approach you have showed up fixed my issue. Thank you 👍
