### ISSUE TITLE
how to get a signature from a json file.

### ISSUE THREAD

**Issue by Anna-MariiaPetryk** [TypeStrong/typedoc#1678]
## Search terms

signature TypeDoc JSON

## Question
Hello ! I generate json file with TypeDoc. And I want to get signature from json file like this.
![photo5314359856968349980](https://user-images.githubusercontent.com/89048004/132526632-88b42663-8b14-4416-93f3-7dc908ed59c5.jpg)
is that possible? Do you have a special function for that?

**Comment by Gerrit0** [comment]
There's code in #1662 to render a signature to a string that might work for you. TypeDoc's HTML rendering is a bit more complicated <https://github.com/TypeStrong/typedoc/blob/beta/src/lib/output/themes/default/partials/member.signature.title.tsx>

Right now we don't publish any utilities for working with the JSON. Eventually I want to make TypeDoc able to import it and turn it back into reflections, but there are higher priority things to work through first...
