### ISSUE TITLE
Automatically add .nojekyll file to support GitHub Pages

### ISSUE THREAD

**Issue by srmagura** [TypeStrong/typedoc#1680]
## Search Terms

GitHub Pages, nojekyll, 404 error, page not found

## Problem

A very common pitfall when serving TypeDoc documentation on GitHub Pages is getting 404 errors because of HTML file names that start with an underscore. Adding a `.nojekyll` file to your GitHub Pages root fixes this.

TypeDoc automatically clears your output folder, so your `.nojekyll` file will get removed. The best way to work around this is a custom `package.json` script that re-adds `.nojekyll` on every build:
```json
"scripts": {
    "typedoc": "typedoc && touch docs/.nojekyll"
}
```

## Suggested Solution

1. Update the TypeDoc documentation to state that a `.nojekyll` file is necessary for your documentation site to work on GitHub Pages.
2. Add a `githubPages` boolean config option that defaults to true. When `githubPages == true`, TypeDoc adds a `.nojekyll` file in the root of your output directory.

I can submit a PR if none of the maintainers are eager to work on this.

**Comment by Gerrit0** [comment]
Is this still necessary with TypeDoc 0.21+? Most of the underscores in file names in 0.20 and earlier were from module names that were wrapped with quotes. In 0.21+ we don't do that anymore, though I guess it could still show up if using scoped package names... it won't hurt anything, so sounds like a reasonable thing to include. A PR would be great!

**Comment by srmagura** [comment]
Ah, I'm using scoped package names which is why I still have files beginning with underscores.

Will work on this when I get the time!

**Comment by mctrafik** [comment]
For anyone finding this thread when using the typedoc-plugin-markdown, you have to set `githubPages false`.
