### ISSUE TITLE
--excludeExternals but keep custom defined interfaces

### ISSUE THREAD

**Issue by GiovanniCardamone** [TypeStrong/typedoc#1681]
## Search terms

excludeExternals

## Question

hello, i have a library that inject into javascript language my custom methods:

example:

```typescript
declare interface ArrayConstructor {
	isNotArray(arg: any): boolean
}

declare interface Array <T> {
	remove(t: T): void
}

// implementation

Array.isNotArray = function(arg: any) {
  return !Array.isArray(arg)
}

Array.prototype.remove = function <T>(this: Array<T>, element: T) {
	for (let i = 0; i < this.length; i++) {
		if (this[i] === element) {
			this.splice(i, 1)
			i--
		}
	}
}
```

now i want to generate documentation using typedoc,

and i want to suppress library methods (any provided by typescript/lib/lib.*.d.s) so i use  `--excludeExternals`

but in this way my methods are excluded as well.

there is a way to exclude standard methods and only generate mine?

Thanks!

**Comment by Gerrit0** [comment]
Currently, no. Whether or not a symbol is considered external is determined by whether or not any of its declarations are external. I can't recall right now why `some` rather than `every` behavior is important, but I know it is, since I saw false positives when implementing the warnings for missing exports in 0.22 recently when trying to use `every`.

https://github.com/TypeStrong/typedoc/blob/d943dc6b0f66974d41f55d0206664aaf09960e1f/src/lib/converter/converter.ts#L412-L426

If you are dead set on adding this to globals, I would still likely implement them as standard exported functions, then mention in the documentation comment that it is available on the appropriate global.

**Comment by GiovanniCardamone** [comment]
Yeah, i mean, i am currently implementing a lib that enhance JavaScript base types: https://github.com/GiovanniCardamone/polyfull and I'd like to use TypeDoc to document this one (but not the language itself)

Furthermore, I'd like to to use TypeDoc but for now I haven't found a way to documentare my declaration and ignore the one of the language

Thanks a lot!

**Comment by invariant** [comment]
I have the exact same issue. I'm not using TypeScript, just documenting a JS API. Upfrtunately a couple of my class names clash with typescript internal classes. If I includ externals, I get extra stuff added to my classes. If I exclude externals, my own classes disappear. Neither option is desired.

**Comment by Gerrit0** [comment]
TypeDoc gets what is visible from TypeScript, so your globals clashing with names isn't just a problem here, but will also be a problem when writing code. You should probably set `"noLib": true,` or adjust the lib option to not include those.

I'll admit that both of these use cases are pretty low priority for me - libraries which muck with globals are doing *bad things*, and it's much more important to produce good documentation for the vast majority of libraries which do not do this. As for JavaScriptCore, well... if it doesn't have modules, TypeDoc here is matching what TypeDoc is doing.

I would accept a PR which fixes this, but probably won't get to it any time soon.

**Comment by invariant** [comment]
> You should probably set "noLib": true, or adjust the lib option to not include those.

Aha! That pointed me directly to the solution. My big problem was a couple of my interface names clashing with some DOM object names (my environment has no DOM). By setting `"lib": [ "ES6" ]` I was able to exclude the DOM libraries from the project and, hey presto, no more clashes. Thanks!
