### ISSUE TITLE
Is there a way to add a prefix to the module pathnames?

### ISSUE THREAD

**Issue by richardkazuomiller** [TypeStrong/typedoc#1682]
## Search terms

typedoc export directory prefix

## Question

My project as a `src` directory for TypeScript which outputs to `lib` (pretty standard). When my package is imported, files other than `index.js` are imported like this:

`import {...} from '@my-workplace/my-package/lib/other-stuff/abc';`

My typedoc config looks like this

```json
{
  "entryPoints": [
    "src/index.ts",
    "src/other-stuff",
  ],
  "out": "build/typedoc",
  "exclude": [
    "src/**/__tests__/**/*",
    "src/**/__mocks__/**/*"
  ]
}
```

At the top of the Typedoc page, it says 

> @my-workplace/package-name / other-stuff/abc /
> # Module other-stuff/abc

However, I want it to say this

> @my-workplace/package-name / lib/other-stuff/abc /
> # Module lib/other-stuff/abc

with `lib/` at the beginning of the top line (the bottom line I could take or leave). I can't find anything in the configuration document that lets me set what path is displayed in the documentation, but is there anyway to do this?

**Comment by Gerrit0** [comment]
There isn't any option to add this on directly, unless you count `--name "@my-workplace/package-name/lib"`, but TypeDoc does let you override the names of modules individually with the [`@module`](https://typedoc.org/guides/doccomments/#%40module) tag, so you could put:

```ts
/**
 * @module lib/other-stuff/abc
 */
```

at the top of your entry point.

**Comment by richardkazuomiller** [comment]
@Gerrit0 Thanks for the quick reply and sorry for the delay on my end 🙏 

I see, I was hoping that I could put something on the page that the person reading the doc could just copy and paste to get the module imported. I just had the idea that it might be possible with a plugin or a custom theme, so I will take a look at the documentation for those.

**Comment by Gerrit0** [comment]
Another option that might work for you is to include that information in the module comment:

```
// other-stuff/abc.ts
/**
 * To import this module:
 * ```ts
 * import * as Abc from "@my-workplsace/other-stuff/lib/abc"
 * ```
 * @module
 */
```
