### ISSUE TITLE
OS theme when set to dark produces wrong syntax highlighting

### ISSUE THREAD

**Issue by rob893** [TypeStrong/typedoc#1683]
## Search terms

theme syntax highlighting

## Expected Behavior

Typedoc OS theme should use dark syntax highlighting when OS theme is set to dark (it should have same behavior as dark theme):
![image](https://user-images.githubusercontent.com/20483475/132919291-fe9968b3-205b-437e-8269-495fe721d7d4.png)

## Actual Behavior

When OS theme is set to dark, Typedoc when set to use OS theme, uses dark background correctly but light theme syntax highlighting (which seems bugged to as some text is not readable) instead of using the expected dark highlighting:
![image](https://user-images.githubusercontent.com/20483475/132919243-b74e224a-3be5-4520-92b0-2ff6bb1e16c7.png)

## Steps to reproduce the bug

1. Set OS theme to dark
2. Generate a typedoc using version 0.22.0 with default theme
3. Open generated doc and ensure theme is set to OS

## Environment

-   Typedoc version: 0.22.0
-   TypeScript version: 4.4.2
-   Node.js version: 14.17.1
-   OS: Windows

**Comment by Gerrit0** [comment]
If you update to 0.22.1, this should be fixed

**Comment by rob893** [comment]
Indeed it does! That was fast! Thanks!

Love the new update!
