### ISSUE TITLE
Dark theme tables render light text against a light background

### ISSUE THREAD

**Issue by jordansexton** [TypeStrong/typedoc#1684]
## Search terms

theme, dark, table, bug

## Expected Behavior

When using the dark theme, or OS theme is dark, tables should be rendered with a dark background so light text is legible.

## Actual Behavior

Dark:
<img width="774" alt="Screen Shot 2021-09-10 at 5 18 30 PM" src="https://user-images.githubusercontent.com/1173161/132923565-ed364521-e562-43dc-a5bd-fcdd7a146a69.png">

Light:
<img width="774" alt="Screen Shot 2021-09-10 at 5 19 00 PM" src="https://user-images.githubusercontent.com/1173161/132923569-bb23aba7-e6ed-4920-bd02-0719c0f843a0.png">

## Steps to reproduce the bug

Use a Markdown table with Typedoc 0.22 and the dark theme.

## Environment

-   Typedoc version: 0.22.1
-   TypeScript version: 4.4.3
-   Node.js version: 14.17.5
-   OS: Mac OS 11.5 Big Sur

**Comment by jordansexton** [comment]
Typedoc's own documentation @ https://typedoc.org/api/ is affected by a similar and related issue:

<img width="825" alt="Screen Shot 2021-09-10 at 5 25 05 PM" src="https://user-images.githubusercontent.com/1173161/132923905-7c06d565-25fc-4d00-afdc-f3cd9edb4351.png">

**Comment by Gerrit0** [comment]
Oh wow that's really bad, thanks for the report!

The codeblock issue is because TypeDoc's site was built with 0.22.0, if you do a refresh there now, it has since been rebuilt with 0.22.1, which fixed codeblocks.

**Comment by jordansexton** [comment]
Awesome, thanks!

**Comment by DanielRios549** [comment]
How to render a table like this? I see the docs and the help command but I can't figure out how to render a markdown table

**Comment by Gerrit0** [comment]
https://www.markdownguide.org/extended-syntax/#tables
