### ISSUE TITLE
Possible false warning "Warning: <symbol>, defined at <source>, is referenced by <symbol> but not included in the documentation" in 0.22.3

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1687]
## Search terms

warning

## Expected Behavior

No warnings should be shown

## Actual Behavior

A warnings was shown

## Steps to reproduce the bug

typedoc.json:
```json
{
	"entryPoints": [
		"./src/components",
		"./src/data",
		"./src/framework",
		"./src/global_types"
	],
	"entryPointStrategy": "expand",
	"out": "doc",
	"exclude": [
		"**/*.js",
		"node_modules"
	],
	"excludeExternals": true,
 	"hideGenerator": true,
	"readme": "none"
}
```

src/components/statuschange/index.ts:80:
```ts
// --> this is actually line 80, so there might be a problem with the line number
type baseOptionsType = { // --> line 81 with the private declaration of baseOptionsType
	type: statuschangeData.HeaderDataEnum,
	multiple: boolean,
	isDialogSelector?: string,
};

export type ceOptionsType = baseOptionsType & { // line 87 with the exported declaration of ceOptionsType
	type: statuschangeData.HeaderDataEnum.CE,
	ceID: Array<number>,
	matchCode: Array<string>,
};
```

shows the following warning:
```bash
Warning: baseOptionsType, defined at src/components/statuschange/index.ts:80, is referenced by components/statuschange.ceOptionsType but not included in the documentation.
```

## Environment

-   Typedoc version: 0.22.3
-   TypeScript version: 4.4.3
-   Node.js version: 16.9.1
-   OS: macOS 11.5.2

**Comment by Gerrit0** [comment]
This seems to be working as intended, the warning is saying that the generated documentation for `ceOptionsType` will be

```ts
type ceOptionsType = baseOptionsType & { ... }
```

But this is not very useful to your API consumers because they can't click on `baseOptionsType` in order to see what is being documented.

**Comment by doberkofler** [comment]
Thank you for your feedback, but i'm not sure i understand.
Is the 'baseOptionsType' type not documented because it is not exported?

**Comment by Gerrit0** [comment]
That's correct, TypeDoc hasn't documented non-exported symbols since 0.20. #1657 is the canonical issue about it

**Comment by doberkofler** [comment]
This brings me back to my original #1685 and on how to best deal with the new warnings in 0.22.2.
If not-exported symbols are no longer considered since TypeDoc 0.20, why do I only get the new warnings after upgrading from 0.21 to 0.22? Using the `intentionallyNotExported` settings (at least for my use case) is almost impossible given the large number (>1000) of warnings.
In my projects I try to only export what is absolutely needed and typically types consist of multiple base types and only the final type used in the API is actually exported and "visible" to the user of the API.
Is there maybe a way to either also consider the not-exported symbols visible in TypeDoc or to disable all warnings for symbols that have not been exported?

**Comment by Gerrit0** [comment]
> why do I only get the new warnings after upgrading from 0.21 to 0.22?

Because this warning didn't exist in 0.21.

> Is there maybe a way to either also consider the not-exported symbols visible in TypeDoc 

That's why I linked #1657, there's a plugin, `typedoc-plugin-missing-exports` which will do that.

> or to disable all warnings for symbols that have not been exported?

```jsonc
// typedoc.json
{
  "validation": {
    "notExported": false
  }
}
```

**Comment by doberkofler** [comment]
Thank you!
