### ISSUE TITLE
No emit option

### ISSUE THREAD

**Issue by bennycode** [TypeStrong/typedoc#1688]
I recently updated from typedoc v0.22.0 which broke a lot of things for me. That's why I would like to add typedoc tests to my CI pipeline. To create docs I am running `typedoc src/index.ts`. Is it possible to call typedoc with an option so that it runs but doesn't write (no emit) any file? Similar to the [noEmit option](https://www.typescriptlang.org/tsconfig#noEmit) of TypeScript?

**Comment by Gerrit0** [comment]
This sounds like a reasonable thing to add, particularly as more validation options are added to TypeDoc. Unfortunately we already use `emit` to control whether or not TypeDoc will ask tsc to emit, so we need another name... `noOutput`?... I'd really like a way to obviously distinguish between TS emit and TypeDoc emit.

I guess the `emit` option could be changed to a mapped option with the values:

```ts
const TypeDocEmit = {
  true: true, // Alias for both, for backwards compatibility until 0.23
  false: false, // Alias for docs, for backwards compatibility until 0.23
  both: "both", // Emit both documentation and JS
  docs: "docs", // Emit documentation, but not JS (default)
  none: "none", // Emit nothing, just convert and run validation
} as const;
```
