### ISSUE TITLE
Subscribe to PageEvent.END event with a plugin

### ISSUE THREAD

**Issue by Drarig29** [TypeStrong/typedoc#1690]
## Search terms

RendererComponent, PageEvent.END, event, component, exported, plugin

## Question

I have a TypeDoc plugin where I need to have access to the info (`url` and `content`) of each generated page.

In previous versions of TypeDoc, I subscribed to the `PageEvent.END` event by making a component which extends from `RendererComponent`. (cf. [this file](https://github.com/Drarig29/typedoc-plugin-extras/blob/a8d352aeef445d1688184a3202e5de6036d3bf43/src/plugin.ts))

Now with ESM, I cannot access the `RendererComponent` anymore, and apparently it's what you want (https://github.com/TypeStrong/typedoc/blob/d943dc6b0f66974d41f55d0206664aaf09960e1f/.config/typedoc.json#L3-L7).

I tried to remove my `app.renderer.addComponent()` call and replace it with an event callback by doing `app.renderer.on(PageEvent.END, () => {})`, but it doesn't work.

What is the new way of accessing to the "page" level of your API?

**Comment by Gerrit0** [comment]
`PageEvent` is exported, the "Component" architecture not being exported is because that is planned to be removed. Plugins should listen to events directly:

```ts
import { PageEvent, Application } from "typedoc"

export function load(app: Application) {
  // Or Renderer.EVENT_END_PAGE
  app.renderer.on(PageEvent.END, () => { ... });
}

**Comment by Drarig29** [comment]
Okay, it's weird I swear I tried that. It must be VS Code again... It's a bummer I need to "Reload window" that much.
