### ISSUE TITLE
TypeDoc does not accept directory path as input file

### ISSUE THREAD

**Issue by srmagura** [TypeStrong/typedoc#1692]
## Search terms

directory, input files

## Expected Behavior

According to the [options documentation](https://typedoc.org/guides/options/)

> TypeDoc also accepts directories as input files.

So if I have my TypeScript files in `src`, I should be able to run `typedoc src` to generate my documentation.

## Actual Behavior

`yarn typedoc src` results in:
```text
Warning: Unable to locate entry point: C:/Projects/OSS/typedoc-repro/src
Error: Unable to find any entry points. Make sure TypeDoc can find your tsconfig
```

### Repro 1
After merging PR #1691, `cd` into the `examples/basic` directory in the TypeDoc repository and run `run` / `run.bat`.

### Repro 2
I made a simple project to double-verify this issue. See https://github.com/srmagura/typedoc-directory-repro. Run `yarn install` then `yarn typedoc src`.

## Environment

-   Typedoc version: 0.22.3
-   TypeScript version: 4.4.3
-   Node.js version: 14.17.6
-   OS: Windows 10

BTW, happy to attempt a fix if you can provide some guidance.

**Comment by Gerrit0** [comment]
This is expected behavior if you don't have an `index` file under `src` and [`entryPointStrategy`](https://typedoc.org/guides/options/#entrypointstrategy) is set to `resolve`. It looks like I missed that section of the page when updating it for v0.22 yesterday, updated now!
