### ISSUE TITLE
Package.json exports restriction breaks external plugins

### ISSUE THREAD

**Issue by mf-pherlihy** [TypeStrong/typedoc#1696]
## Search Terms

- exports
- is not defined by "exports"
- Package subpath

## Problem

Prior to 0.22.0, you could import specific TypeDoc classes and functions that made plugin development simpler:

```typescript
import { MarkdownEvent } from 'typedoc/dist/lib/output/events';
import { getRawComment } from 'typedoc/dist/lib/converter/factories/comment';

this.app.listenTo(
  this.app.renderer,
  MarkdownEvent.PARSE,
  (event: MarkdownEvent) => someHandler(event),
  eventPriority
);
```

However, in the 0.22.0 release a change was made to `package.json` which no longer allows this: https://github.com/TypeStrong/typedoc/commit/4f33ff8fb498bfbb58130af6f21ddcfeca2c5f1b
```json
"exports": "./dist/index.js",
```

Leading to this error:

> Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/output/events' is not defined by "exports"

## Suggested Solution

Remove `exports` from package.json

OR

While tedious, we could add any files that might be useful to external plugins.

**Comment by FireAndIceFrog** [comment]
I am also getting this problem. I encountered it using typedoc as expected but it throws the same error you are getting.

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/converter' is not defined by "exports"`

A solution is to include my version of typedocs package.json to hold a converter reference

![image](https://user-images.githubusercontent.com/60675668/133151548-984d619d-2312-488c-8448-50bb5a2fb257.png)


Obviously this isn't good, so please escalate this issue

**Comment by SamJakob** [comment]
This change broke our CI (in the exact way reported by @FireAndIceFrog) so I've created a simple 'hot fix' for this until the plugins are updated (though they do look impressively well maintained so I'd imagine that'll probably happen fairly soon).

https://gist.github.com/SamJakob/6fd2f06cc38242557e5d2d50fbe7a157
This simply guides adding a 'post install' script to yarn that replaces package.json in `node_modules/typedoc/` with one that doesn't have the `exports` option present.

**(!)** Naturally, as the point of this change was to raise an alert if something wasn't exported, if you do intend to use my fix, I encourage you to report an issue you're having _before_ using this fix.

**Comment by Gerrit0** [comment]
Plugins should not be using either of those. Both are going to be completely removed from TypeDoc's codebase, probably in 0.23
