### ISSUE TITLE
Hamburger menu doesn't open on mobile

### ISSUE THREAD

**Issue by koskimas** [TypeStrong/typedoc#1699]
## Search terms

Hamburger menu, main menu, mobile phone, doesn't open

## Expected Behavior

When I open a site generated using typedoc on a mobile device, I expect the main menu to open from the hamburger button.

## Actual Behavior

The hamburger button does nothing.

## Steps to reproduce the bug

Open this site https://koskimas.github.io/kysely/index.html and resize the browse to mobile size so that you can see the hamburger button (the three-lines button). Tap the button.

## Environment

-   Typedoc version: 0.22.3
-   TypeScript version: 4.4.3
-   Node.js version: 16.2.0
-   OS: Macos

**Comment by koskimas** [comment]
This also happens on the typedoc's own API doc https://typedoc.org/api/index.html. This bug means there is no way to browse the documentation on mobile devices.

By the way, AWESOME job in general with this project! I really appreciate all the hard work you put into it ❤️

**Comment by Gerrit0** [comment]
That's definitely broken! I'm not entirely sure how that CSS was lost... I must have accidentally deleted it when getting rid of SASS.
