### ISSUE TITLE
How does exclude work ?

### ISSUE THREAD

**Issue by ocombe** [TypeStrong/typedoc#170]
Hello,
I use the command line: `typedoc --options typedoc.json --exclude *.spec.ts src/app/`

But it generates documentation for my file "src/app/app.spec.ts".
Shouldn't it be excluded ?

**Comment by enanox** [comment]
Hi, I'm on the same boat as @ocombe. 
Is the `--exclude` pattern a RegExp, or a pattern similar those used in Grunt/Gulp, such as `directory/**/*.ext`?

**Comment by EMarginy** [comment]
Hi, got the same problem with exclude trying this: ```typedoc --media modules/ --exclude modules/**/tests/*```

**Comment by dsebastien** [comment]
Same issue here. Also how to configure multiple exclusions?

**Comment by caseyhoward** [comment]
I'm having the exact same issue. I want to ignore spec files. "<pattern>" is not helpful at all without an example of what a "pattern" is.

**Comment by caseyhoward** [comment]
@ocombe I think the following should work:
```
typedoc --options typedoc.json --exclude **/*.spec.ts src/app/
```

typedoc uses [Minimatch](https://github.com/isaacs/minimatch) for globs. I believe *.spec.ts will only look for files in the current directory.

**Comment by hverlin** [comment]
Hi, you can use for example: ``"exclude": "**/*+(e2e|spec|index).ts"`` if you want to have multiple exclusions.

The syntax seems to be ``+(pattern-list)``.

**Comment by blakeembrey** [comment]
Seen here (https://github.com/TypeStrong/typedoc/blob/53bb762ad208f2be266ece767f6204159ce71a0d/src/lib/application.ts#L253), the pattern is a standard minimatch (glob) pattern in Node.js. The existing comments by @caseyhoward should work for you (make sure you quote so it's not automatically expanded by your shell).

**Comment by daotoad** [comment]
Changing the docs to say that patterns are "standard" minimatch patterns would be very helpful.

**Comment by blakeembrey** [comment]
You are welcome to submit a PR improving the docs.

**Comment by YouriT** [comment]
I know this has been closed but I think that what would be interesting to know in the docs is what is given to minimatch for testing.

If you pass the whole path to the file, the pattern will be different than if you are passing what comes after `path/to/typescript/project/`. From my understanding, you make a full resolution and give it to the minimatch pattern but correct me if I'm wrong.

**Comment by Zeioth** [comment]
Then there is no way to exclude an entire directory?

**Comment by YouriT** [comment]
@Zeioth yup you can via the pattern.
Example: my tree is like this:
```
| src
  - File1.ts
  - File2.ts
  | tests
    - Test1.ts
    - Test2.ts
```
To exclude the `tests` folder under `src` you would do: `typedoc src --out docs --mode modules --exclude \"**/tests/*.ts\"`

**Comment by assaf-cream** [comment]
I managed to exclude several folders,
The syntax was "**/{folder1,folder2}/*.ts"

HTH

**Comment by paynoattn** [comment]
For whatever reason this only worked for me when I escaped the path like so:
`typedoc --out ./docs ./src  --exclude \"**/*+(index|.spec|.e2e).ts\"`

**Comment by dupski** [comment]
Just to add some info to this, if you use typedoc with a javascript config file
(e.g. `typedoc --options ./typedoc.js ./src`), then you can set an array of exclude paths in the configuration:

`typedoc.js`:
```js
module.exports = {
    out: './docs/dist/api/',

    readme: 'none',
    includes: './',
    exclude: [
        '**/__tests__/**/*',
        '**/__test_utils__/**/*',
        '**/__fixtures__/**/*',
        '**/testsuite/**/*'
    ],

    mode: 'file',
    excludeExternals: true,
    excludeNotExported: true,
    excludePrivate: true
};
```

**Comment by carlos-algms** [comment]
This exclude is not working: 

```javascript
module.exports = {
  mode: 'file',
  out: 'dist/typedoc',
  theme: 'default',
  ignoreCompilerErrors: true,
  excludePrivate: true,
  excludeNotExported: 'true',
  excludeExternals: true,
  target: 'ES5',
  moduleResolution: 'node',
  preserveConstEnums: 'true',
  stripInternal: 'true',
  suppressExcessPropertyErrors: 'true',
  suppressImplicitAnyIndexErrors: 'true',
  module: 'commonjs',
  readme: 'README.md',
  exclude: [
    '**/*.spec.ts',
    '**/*.module.ts',
  ],
};
```

I don't want to render *.module.ts files because they just import and export things, they don't add nothing to the documentation. 

Why the exclude patter is not working?

**Comment by Hoten** [comment]
A lot of users in this thread are actually using shell globs.

I'm finding this to not work (shell does not expand the glob with single quotes): `--exclude '**/*.d.ts'`

Using the shell glob works: `--exclude **/*.d.ts`

If glob patterns are meant to work, it's broken.

**Comment by Hoten** [comment]
Thanks @aciccarello. Yeah, some of us are having issues with declaration files. #820 is the relevant issue.

**Comment by vipetrul** [comment]
It is also possible to specify multiple excludes in cli by specifying several exclude arguments:
`typedoc --out docs src --ignoreCompilerErrors --exclude **/*__*/** --exclude **/*.test.tsx`

**Comment by chetana286** [comment]
is it possible to display specific comments only using typedoc?
I dont want to document variables, functions, classes, just want to display specific comment. Is that possible using Typedoc

**Comment by SalahAdDin** [comment]
> This exclude is not working:
> 
> ```js
> module.exports = {
>   mode: 'file',
>   out: 'dist/typedoc',
>   theme: 'default',
>   ignoreCompilerErrors: true,
>   excludePrivate: true,
>   excludeNotExported: 'true',
>   excludeExternals: true,
>   target: 'ES5',
>   moduleResolution: 'node',
>   preserveConstEnums: 'true',
>   stripInternal: 'true',
>   suppressExcessPropertyErrors: 'true',
>   suppressImplicitAnyIndexErrors: 'true',
>   module: 'commonjs',
>   readme: 'README.md',
>   exclude: [
>     '**/*.spec.ts',
>     '**/*.module.ts',
>   ],
> };
> ```
> 
> I don't want to render *.module.ts files because they just import and export things, they don't add nothing to the documentation.
> 
> Why the exclude patter is not working?

It is not working at all.

**Comment by receptiryaki** [comment]
you can use it like this,

`"exclude": "**/+(yourFile.ts|yourAnotherFile.ts|yetAnotherFile.ts)"`

**Comment by peabnuts123** [comment]
Just in case anybody is running into the same issue as me, don't forget to move the `exclude` option inside `packageOptions` if you are using `packages` entrypoint strategy. This is working for me: 
```jsonc
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": [
    "src/core",
    "src/engine",
  ],
  /*
    @NOTE It is important that packages are built (using declarationMap: true)
    for typedoc to be able to pick up cross-package references
  */
  "entryPointStrategy": "packages",
  "packageOptions": {
    "entryPoints": [
      "src",
    ],
    "entryPointStrategy": "expand",
    "exclude": [
      "**/*.test.ts",
    ],
  },
  "out": "./docs",
}
```
