### ISSUE TITLE
Property notExported is not allowed, validation.invalidLink too

### ISSUE THREAD

**Issue by zhixinbao** [TypeStrong/typedoc#1700]
## Search terms

Property notExported is not allowed
Property invalidLink is not allowed

## Expected Behavior

In typedoc.json, I have `https://typedoc.org/schema.json` as `$schema` obviously.
When I typed "v" the VSCode editor suggests
```
"validation": {
    "notExported": true,
    "invalidLink": false
}
```

## Actual Behavior

But, we also have warnings on the `validation` properties, when mouse over we see the problem above.

## Suggested Solution

`validation` definition can be fixed by

```
"validation": {
    "description": "Specify which validation steps TypeDoc should perform on your generated documentation.",
    "properties": {
        "notExported": {
            "type": "boolean"
        },
        "invalidLink": {
            "type": "boolean"
        }
    },
    "additionalProperties": false,
    "default": {
        "notExported": true,
        "invalidLink": false
    }
}
```

**Comment by Gerrit0** [comment]
Thanks for the report!
