### ISSUE TITLE
Empty documentation is beeing generated

### ISSUE THREAD

**Issue by Khuzha** [TypeStrong/typedoc#1705]
## Search terms

empty documentation, modules, import

## Question

Hey guys! I'm getting an empty documentation when try to generate that.

But this is actual only for imported files. When I add e.g. any class to the file specified in entryPoints, I get documentation for that.

But for imported files I get nothing. 

I have such [typedoc.json](https://github.com/ASUDR/backend/blob/dev/typedoc.json):
```
{
  "entryPoints": ["src/app.ts"],
  "out": "docs",
  "includes": "src"
}
```

Full source code is [here](https://github.com/ASUDR/backend/tree/dev)

How can I solve this?

**Comment by Flaiers** [comment]
I wont say, maybe you go learning python, and didn't have more exceptions

**Comment by Khuzha** [comment]
I should use `entryPointStrategy` instead.
