### ISSUE TITLE
How can we know what are the supported options?

### ISSUE THREAD

**Issue by VictorQueiroz** [TypeStrong/typedoc#1713]
## Search terms

- compatibility
- supported typescript version
- previous package versions for maximumly supported typescript version

## Question

The title says it all. I'm surprised I could not find this information anywhere. Is everyone using the latest TypeScript versions? I'm still stuck in 3.8.3 due to performance issues in Visual Studio Code IntelliSense.

**Comment by Gerrit0** [comment]
It's listed in package.json, I'd accept a PR to typedoc-site which adds a table with this info.

Being stuck on old TS versions is pretty bad though. That version is getting close to being out of support even by definitely typed. 

https://github.com/TypeStrong/typedoc/blob/master/package.json#L31

**Comment by Gerrit0** [comment]
I've updated the site with a table. Unfortunately, before 0.19, we weren't good about listing what versions were actually supported, only listing the minimum version, so going back further than that would require manually testing versions... 0.18 should work for 3.8.4, but I'm not sure about other versions.
