### ISSUE TITLE
How to specify file in intentionallyNotExported?

### ISSUE THREAD

**Issue by ilyub** [TypeStrong/typedoc#1715]
## Search terms

intentionallyNotExported

## Question

Here is an example from documentation:
```ts
{
    "intentionallyNotExported": ["InternalClass", "OtherInternal"]
}
```

But what if I have "InternalClass" in several files and only want to make exception in one file?

**Comment by Gerrit0** [comment]
Currently, there's no way to do this, the assumption that names were globally unique was taken.

I'd be happy to accept a PR which introduces syntax to allow this though, perhaps `index.ts:Foo` optionally allowing specifying more of the path if necessary to be unambiguous, `lib/utility/index.ts:Foo`
