### ISSUE TITLE
Typedoc includes files from node_modules

### ISSUE THREAD

**Issue by fireflysemantics** [TypeStrong/typedoc#1718]
## Search terms

node_modules
typedoc
angular package format

## Question

I documented it here also:
https://stackoverflow.com/questions/69367904/running-typedoc-on-project-includes-files-from-node-modules

I [have this project](https://github.com/fireflysemantics/is) setup with typedoc and the npm script (`npm run d`) used to work:

```
"d": "typedoc --out doc --exclude **/*.spec.ts ./projects/fs-is/src/lib"
```

I upgraded the project to Angular 12 (It uses the Angular Package Format) and now when typedoc is run it includes files from `node_modules` and fails:

```
Error: node_modules/@types/eslint/index.d.ts:474:43 - error TS2694: Namespace '"/Users/oleersoy/Github/is/node_modules/@types/estree/index"' has no exported member 'ImportExpression'.

474         ImportExpression?: ((node: ESTree.ImportExpression & NodeParentExtension) => void) | undefined;             ~~~~~~~~~~~~~~~
```

Any ideas?

**Comment by Gerrit0** [comment]
You see that error because the eslint and estree (parser that eslint relies on) have mismatched versions. I'd recommend making the versions match if possible, or turning on `skipLibCheck`.

**Comment by fireflysemantics** [comment]
Oh coo.  I added `skipLIbCheck` and that fixed it.  Thanks!!
