### ISSUE TITLE
"Unable to find any entry points" with typedoc@0.22.4

### ISSUE THREAD

**Issue by TitaneBoy** [TypeStrong/typedoc#1719]
## Search terms

"Unable to find any entry points"
"Unable to locate entry point"

## Expected Behavior

Should not generate any error and should generate docs

## Actual Behavior

Since using typedoc@0.22.4, I'm having trouble to generate typescript documentation with typedoc. Previous version I've used (v.21.9) works fine and without any issues

Here is the typedoc.json file I'm using with typefoc, located at the root folder of my project

```
{
  "entryPoints": ["src"],
  "out": "docs/Web Server/",
  "readme": "README.md",
  "name": "Web Server Documentation",
  "tsconfig": "./tsconfig.json"
}
```
The tsconfig.json file is also located at the root of the project..

Calling typedoc with typedoc v0.21.9 works perfectly. But with the last one (v0.22.4), I can see the following

![image](https://user-images.githubusercontent.com/15614466/135297338-9cd9dce5-249a-4b91-b8a1-2f94175732b3.png)

## Steps to reproduce the bug

- Define and configure properly a typedoc.json file
- Define and configure properly a tsconfig.json
- Install the latest version of typedoc
- Run typedoc for your project

Here my tsconfig.json file:
tsconfig.json
```
{
    "extends": "./tsconfigprod.json",
    "compileOnSave": true,
    "compilerOptions": {
        "sourceMap": true
    }
}
```

Here's the tsconfigprod.json file
tsconfigprod.json
```
{
    "compilerOptions": {
        "noImplicitAny": true,
        "outDir": "./build",
        "target": "es2018",
        "alwaysStrict":true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noFallthroughCasesInSwitch":true,
        "noUnusedLocals":true,
        "noUnusedParameters":true,
        "pretty": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "module": "commonjs",
        "resolveJsonModule": true,
        "downlevelIteration": true
    },
    "include": [
        "./src/**/*"
    ]
    ,
    "exclude": [
        "./build",
        "node_modules"
    ]
}
```

In the package.json, I have the following script defined:

"docgen": "typedoc",

I'm running the script using the following command: "yarn docgen"

## Environment

-   Typedoc version: v0.22.4
-   TypeScript version: 4.4.3
-   Node.js version: v14.17.3
-   OS: Windows 10

**Comment by Gerrit0** [comment]
> Changed the default entryPointStrategy from expand to resolve.

From the 0.22.0 release notes

**Comment by TitaneBoy** [comment]
> From the 0.22.0 release notes

Oh..Wow...Sorry about that...Completely missed that part...Seems to work again..Thank you for your help

**Comment by pldilley** [comment]
@Gerrit0 It looks like the example given at https://github.com/TypeStrong/typedoc suggests people do `typedoc src/index.ts` but with this change that will likely fail for most people, and the error does not make it clear what's wrong.

I want to suggest updating the readme to remove "/index.ts"?
