### ISSUE TITLE
Default parameter value constant is parsed as ellipsis in docs

### ISSUE THREAD

**Issue by Sjeiti** [TypeStrong/typedoc#1730]
## Search terms

parameter, default, number constant, ellipsis

## Expected Behavior

TypeDoc should describe the parameters correctly even when they are constants.
For instance:
  "num: number = Number.MIN_SAFE_INTEGER"

## Actual Behavior

TypeDoc generates the following parameter description for a constant:
  "num: number = ..."

## Steps to reproduce the bug

```TypeScript
/**
 * A small number
 * @param {number} [num=Number.MIN_SAFE_INTEGER]
 */
export function smallNumber(num=Number.MIN_SAFE_INTEGER):number {
  return num
}
```

## Environment

-   Typedoc version: 0.22.5
-   TypeScript version: 4.4.3
-   Node.js version: 14.15.1
-   OS: Windows

**Comment by Gerrit0** [comment]
See also https://github.com/TypeStrong/typedoc/issues/1552. Initializers are kind of annoying... property access might be simple enough in general that typedoc can include it.
