### ISSUE TITLE
Make default theme icons monochrome, paint them in CSS

### ISSUE THREAD

**Issue by KillyMXI** [TypeStrong/typedoc#1732]
## Search Terms

Default theme, icon colors, custom CSS

## Problem

My code is 100% functions and type aliases. The purple used by the default theme is the most unnatural to human eyes and very poorly readable in dark theme.

I can't change icon colors to more readable ones without significant effort.

## Suggested Solution

Make default theme customization more code-friendly. Make icons to be colored via CSS so I could make it more ergonomic with custom CSS alone, by specifying few meaningful variables and not hacking around.

Preferably SVG icons, so they will appear sharp on any DPI screens.

----

*Edit: re-worded.*

**Comment by Gerrit0** [comment]
I've legitimately put off responding to this for 4 months since the antagonistic wording for a feature request for an open source project annoys me so much that I have difficulty responding to it with grace.

With 0.23, icons will be defined using a svg, which can be styled via css.

**Comment by KillyMXI** [comment]
I'm sorry.
I'm not trying to attack anyone.
I have a bad habit to paint my user experience reports like this. It doesn't work well, but I have ASD and always miss that.

**Comment by KillyMXI** [comment]
And thank you.
`typedoc` is indispensable tool.
I was so focused on expressing all the inconveniences I didn't think how to balance it with all the good that is there as well.
