### ISSUE TITLE
Unknown @-annotations are ignored for function type aliases

### ISSUE THREAD

**Issue by nex3** [TypeStrong/typedoc#1734]
## Expected Behavior

I would expect unknown @-annotations to show up in the documentation the way they do for other types, like so:

![image](https://user-images.githubusercontent.com/188/136474511-c2e14993-89e7-4286-9f25-c3dac125609d.png)

This is particularly useful for writing annotations that are meant to be compatible with TSDoc, like `@example`.

## Actual Behavior

If I write an unknown @-annotation on a type alias whose value is a function:

```ts
/**
 * @asdf Some example text
 */
export type Foo = (arg: string) => string;
```

It doesn't appear in the output:

![image](https://user-images.githubusercontent.com/188/136474639-699e6f09-c714-400d-8547-44840b156392.png)

## Steps to reproduce the bug

Just run `npx typedoc test.ts` on the above code.

## Environment

- Typedoc version: 0.22.4
- TypeScript version: 4.3.5
- Node.js version: 16.10.0
- OS: Linux

**Comment by Gerrit0** [comment]
Oops... that's an easy fix at least. Apparently I didn't realize that `Comment` always has the `tags` property, even if there are no tags.
