### ISSUE TITLE
Support emitting docs, types, and javascript

### ISSUE THREAD

**Issue by okikio** [TypeStrong/typedoc#1737]
## Search Terms

emit, docs, and types

## Problem

Right now I have a separate build script for types and typedoc docs, I would love it if I could merge them both into typedoc, without needing to create another build script. 

## Suggested Solution

Right now the [emit option](https://typedoc.org/guides/options/#emit) supports emitting `none`, `either`, or `both` js and docs, I think adding `types`, as another option would be pretty cool. I don't think any other documentation tool do this right now, but it would be awesome if typedoc became the first.

**Comment by Gerrit0** [comment]
If you have TypeScript configured with `declaration: true`, then `both` will also emit declaration files... am I missing what additional capability you're looking for?

**Comment by Gerrit0** [comment]
PR welcome :) https://github.com/TypeStrong/typedoc-site/blob/master/guides/options.md#emit
