### ISSUE TITLE
`intentionallyNotExported` does not support Windows path separators

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1738]
## Search terms

intentionallyNotExported, Windows

## Expected Behavior

When running TypeDoc, I got this warning:

```
PS C:\Users\micha\Git\refa> npx typedoc
Warning: NodeIdent, defined at src\ast\nodes.ts:64, is referenced by NoParent but not included in the documentation.
```

So copied the file path of the warning + the type name and used the `intentionallyNotExported` in my `typedoc.json` like this:

```json5
{
  // other options

  "validation": true,
  "intentionallyNotExported": [
    "src\\ast\\nodes.ts:NodeIdent"
  ]
}
```

## Actual Behavior

This does not work. Luckily, TypeDoc prints a very helpful but also confusing warning:

```
PS C:\Users\micha\Git\refa> npx typedoc
Warning: NodeIdent, defined at src\ast\nodes.ts:64, is referenced by NoParent but not included in the documentation.
Warning: The following symbols were marked as intentionally not exported, but were either not referenced in the documentation, or were exported:
        src\ast\nodes.ts:NodeIdent
```

However, using front slashes in the path works:

```json5
{
  // other options

  "validation": true,
  "intentionallyNotExported": [
    "src/ast/nodes.ts:NodeIdent"
  ]
}
```

(Removing the path and only using `"NodeIdent"` also works as expected.)

It seems like the symbol comparison of the `intentionallyNotExported` option uses Unix path separators internally and doesn't account for Windows path separators. 

The easiest fix for this might be to consistently use Unix path separators internally and to converts the paths from the `intentionallyNotExported` into Unix paths as well. This _could_ as simple as replacing all backslashes with frontslashes.

## Steps to reproduce the bug

[Here is a minimal example.](https://github.com/TypeStrong/typedoc/files/7353887/example.zip) Just install all deps (`npm ci`) and run `npx typedoc`. You'll see the following on Windows machines:

```
PS C:\Users\micha\Desktop\example> npx typedoc
Warning: NoParentImpl, defined at src\index.ts:4, is referenced by NoParent but not included in the documentation.
Warning: The following symbols were marked as intentionally not exported, but were either not referenced in the documentation, or were exported:
        src\index.ts:NoParentImpl
Info: Documentation generated at ./docs
```

## Environment

-   Typedoc version: 4.2.4
-   TypeScript version: 0.22.5
-   Node.js version: v16.11.1
-   OS: Win10

**Comment by Gerrit0** [comment]
Thanks! Yeah, it was not intentional to print paths in the warning with Windows slashes, everything should use `/` slashes, since they're much less of a pain to work with.
