### ISSUE TITLE
Warning states Object is defined and referenced, but not included in the documentation. Why?

### ISSUE THREAD

**Issue by KyleTryon** [TypeStrong/typedoc#1739]
I am receiving quite a few warnings of the same type describing that a component of my code is defined, and referenced within the code, but has not been included in the docs. I am not finding, however, why this is or what I am meant to do to resolve it.

Example of Error:

```shell
MyClassSchema, defined at src/lib/MyClass.ts:24, is referenced by MyClass.generate.generate but not included in the documentation
```
Notice here `generate` is written twice, I found this strange.

Here is the Interface that is being defined here:

```ts
/**
 * JSON Schema for the Persist command.
 */
export interface MyClassSchema extends CommandSchema {
  my_class: MyParameters;
}
```

And here is how it was referenced:

```ts
export class MyClass extends Command {
  parameters: MyClassParameters;
  constructor(parameters: MyClasstParameters) {
    super('my_class');
    this.parameters = parameters;
  }
  generate(): MyClassSchema {
    ...
  }
}
```

Now possibly why, and worthy of note, is that `MyClass` here is overwriting the definition of `generate()` which was defined in `Command`, this may be why we see `generate` twice, and possibly why it is not being exported? If that is the case, this may be a bug?

However, counter example to the immediate above comment: I am also experiencing this in an interface that is being used as a struct on a class.

```ts
export class X implements IntefaceY {
  ...
}
export interface InterfaceY {
  ...
}
```

This too is getting this error:

`Warning: IntefaceY, defined at src/lib/X.ts:121, is referenced by X but not included in the documentation.`

**Comment by timohausmann** [comment]
Aha, so by default only exports from the direct entrypoints are included, this clarifies things. Thank you.

**Comment by Gerrit0** [comment]
Yep, this is expected behavior. Users of your library will (unless you tell them otherwise) import `lib` not `lib/some/internal/path`, so TypeDoc warns that you aren't exporting the necessary types from what you designated as the entry point.

> Notice here generate is written twice, I found this strange.

This is an artifact of `getFullName`, which just walks up the reflection tree to the project root. `generate` has two members in that tree - one for the signature, and one for the member itself. It works this way so that overloads can be represented... A PR which changes that for reporting here would be accepted :)

**Comment by Gerrit0** [comment]
Looking at the declaration file - I'd say... yes, for how TypeDoc works today, it is correct to produce a warning here. It could certainly be argued that TypeDoc isn't handling "variable namespaces" optimally here, and should have a special case for this, though (should probably be a new issue, that lays out when variables should be treated as namespaces, and when they shouldn't)

**Comment by y-polonsk** [comment]
Thanks, it works.
