### ISSUE TITLE
MarkedLinksPlugin fails to resolve symbol reference when copying documentation

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1747]
## Search terms

MarkedLinksPlugin, comment, function, copy

## Expected Behavior

When referencing the method of an interface, the documentation of the method is copied without errors.

## Actual Behavior

```
> npx typedoc
Warning:
[MarkedLinksPlugin]: Found invalid symbol reference(s) in JSDocs, they will not render as links in the generated documentation.
  In example - v1.0.0: {@link stableOut}
```

![image](https://user-images.githubusercontent.com/20878432/138083377-40b2eb94-1675-49dd-910f-2d18d2da32eb.png)

## Steps to reproduce the bug

`index.ts`

```ts
/**
 * Some documentation for FAIterator.
 */
export interface FAIterator<S> {
	/**
	 * A link to {@link stableOut}.
	 */
	readonly getOut: (state: S) => Iterable<S>;
	/**
	 * Some documentation for stableOut.
	 */
	readonly stableOut?: boolean;
}

/**
 * Some docs for foo.
 */
export function foo<S>(
	getOut: FAIterator<S>["getOut"],
	stableOut = false
): void {
	throw new Error("Not implemented")
}
```

The problem is that I use `FAIterator<S>["getOut"]`. This will copy over its documentation along with a JSDoc reference to `FAIterator#stableOut`. However, it seems that the MarkedLinksPlugin tries to resolve the JSDoc reference after the doc has been copied and then resolves `{@link stableOut}` as the parameter `stableOut` for which it cannot create a link to. The parameter `stableOut` is necessary for this bug to occur.

[Here is a small example project.](https://github.com/TypeStrong/typedoc/files/7380701/example.zip)

## Environment

-   Typedoc version: 0.22.6
-   TypeScript version: 4.4.4
-   Node.js version: v16.11.1
-   OS: Win10 64 bit

**Comment by Gerrit0** [comment]
I think this is going to be a wontfix. Dealing with inherited methods and wanting them to properly link to the current class seems more likely to me than inheriting a comment that then fails to resolve. There's a workaround if you want to link to the interface itself - just specify a more fully qualified link, e.g. `FAIterator.stableOut`
