### ISSUE TITLE
Generating class diagrams

### ISSUE THREAD

**Issue by Auliyaa** [TypeStrong/typedoc#175]
Currently, class hierarchy is shown as plain text, It would be nice if there was an option available to include SVG class diagram inside a class' documentation.

In addition, having the possibility to generate a full class diagram over a project (that would be displayed inside the home page or in a specific section) would be another nice addition.

**Comment by FlippieCoetser** [comment]
YES, please! Will be super helpful!

**Comment by samchon** [comment]
First, I'm sorry to opposite some opinion. Of course, what I want to say is a subjective perspective, too.

I've used Doxygen for many years and of course, have used GraphViz to generate class diagrams automatically. However, quality of [full] class diagram automatically generated is not good. It's very hard to read and lines expressing relationship and connection are very complicate to comprehend.

Even the automatically generated full class diagram expanded to a project level, the diagram's readability can't be guaranteed. So I want to insist, if make a class diagram generator, it would be better to express class diagram with only with hierarchy and inheritance relationship.


In my case, I draw class and collaboration diagram for each module or package by my hand. At next, insert the diagrams to API document as image files and the auto-generated API document with auto-generated inheritance (not full, only prints object name) diagram.

http://samchonorg.wix.com/framework#!architecture-designs/c1lio
http://samchon.github.io/framework/api/cpp/annotated.html

Although I opposite to generate full class diagram, I do not opposite to generate a simple diagram. I am challenging to a open-source contest as a subject of UML. If I can be helpful, I want to try the function.

**Comment by Auliyaa** [comment]
I do agree with you to some extent.
However having this kind of feature as an option would allow all sorts of
small architectures to be rendered in a clear way inside the documentation
page.

Moreover, ther could be an option to generate one diagram per namespace /
module in order to ensure readability for larger code bases.


On Thu, Jan 14, 2016 at 7:28 AM, Jeongho Nam <notifications@github.com>
wrote:

> First, I'm sorry to opposite some opinion. Of course, what I want to say
> is a subjective perspective, too.
>
> I've used Doxygen for many years and of course, have used GraphViz to
> generate class diagrams automatically. However, quality of [full] class
> diagram automatically generated is not good. It's very hard to read and
> lines expressing relationship and connection are very complicate to
> comprehend.
>
> Even the automatically generated full class diagram expanded to a project
> level, the diagram's readability can't be guaranteed. So I want to insist,
> if make a class diagram generator, it would be better to express class
> diagram with only with hierarchy and inheritance relationship.
>
> In my case, I draw class and collaboration diagram for each module or
> package by my hand. At next, insert the diagrams to API document as image
> files and the auto-generated API document with auto-generated inheritance
> (not full, only prints object name) diagram.
>
> http://samchonorg.wix.com/framework#!architecture-designs/c1lio
> http://samchon.github.io/framework/api/cpp/annotated.html
>
> Although I opposite to generate full class diagram, I do not opposite to
> generate a simple diagram. I am challenging to a open-source contest as a
> subject of UML. If I can be helpful, I want to try the function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastian-lenz/typedoc/issues/175#issuecomment-171548092>
> .
>



-- 
Cordialement.

--
M: urushiraa@gmail.com

**Comment by Chowarmaan** [comment]
:+1:

**Comment by electricessence** [comment]
++

**Comment by aciccarello** [comment]
You might want to look at #68 which talks about class diagrams.

**Comment by 0815fox** [comment]
Last weekend I forked @meirgottlieb s typedoc-plantuml module and added automatical generation of uml class diagrams:

https://github.com/0815fox/typedoc-plantuml

![screenshot](https://cloud.githubusercontent.com/assets/8955528/16196205/667ddca0-36fd-11e6-9bed-c5cc6e6d1703.jpeg)

**Comment by samchon** [comment]
@0815fox Wow, it seems amazing. 
I had been drawing diagrams and inserted to API documents by my hand like such below:
  - http://samchon.github.io/stl/api/classes/std.treemap.html

I appreciate for your help.

![image](https://cloud.githubusercontent.com/assets/13158709/16215119/112edd24-379a-11e6-9e88-357bea84d291.png)

**Comment by 0815fox** [comment]
Credits to the uml tag features go to @meirgottlieb.

**Comment by nadhir-falta** [comment]
@0815fox Michael, how do I get to generate class diagrams automatically?

**Comment by 0815fox** [comment]
@nadhir-falta I wrote it just short time before / while they modified the interface of typedoc. I do not have time to adopt to their new interface. It stopped working with 0.5.0 of typedoc, I think.

**Comment by krisztianb** [comment]
@0815fox First of all, thank you for your work with typedoc-plantuml. I would really like to use it, as there seems to be no other solution for auto-generating documentation for a TypeScript project. Would it be difficult to adopt typedoc-plantuml to the latest typedoc?

**Comment by 0815fox** [comment]
Probably it is not too difficult, but I will not spend any time on this, as I don't have the time for it.

**Comment by Chowarmaan** [comment]
I switched and am using compodoc to do my docs for typescript. Angular team
uses it I believe.

**Comment by krisztianb** [comment]
@Chowarmaan Thanks for the information. Can you create UML class diagramms using compodoc? I can't find such a feature. It looks like that it can only generate a kind of module dependency graph.

**Comment by Chowarmaan** [comment]
That is all it is doing now.  Maybe add a feature request as it is s
actively developed.

**Comment by krisztianb** [comment]
I've just checked their Issues page and saw that there are already several requests for this (one using the plantuml approach). So I guess we have to wait.

**Comment by SlickNutter** [comment]
@Chowarmaan is compodoc also good for non-angular typescript projects?

**Comment by Chowarmaan** [comment]
I use it with Angular/Ionic and it works well.  I do not see why it would not work as it does take your tsconfig.json as a parameter, so it knows where the source is.  I have not tried it on other projects outside of Angular though myself.

**Comment by SlickNutter** [comment]
Ok, I'll give it a go one of these days. Thanks for the quick response! :)

**Comment by aciccarello** [comment]
Someone created a [plugin](https://www.npmjs.com/package/typedoc-plugin-mermaid) for creating [mermaid](https://github.com/knsv/mermaid) diagrams in doccomments using an `@mermaid` annotation.

```typescript
/**
 * Hoge is sample class for example of `typedoc-plugin-mermaid`.
 *
 * @mermaid Make TypeDoc easy to use with mermaid.js
 * graph TB
 *   mermaid.js --> TypeDoc;
 */
export class Hoge {
}
```

![typedoc generated documentation with diagram matching the above code snippet](https://raw.githubusercontent.com/kamiazya/typedoc-plugin-mermaid/c5e7d66f43dc82b3973564958372d2e0bb4fed0e/media/example.png)

**Comment by krisztianb** [comment]
@aciccarello Mermaid does not support class diagrams, does it?

**Comment by krisztianb** [comment]
I just wanted to update this thread. Both the **typedoc-plantuml** and **typedoc-plantuml-extended** packages form NPM are working with the latest 0.15.0 typedoc.

**typedoc-plantuml**: This is the original package created by Meir Gottlieb which enables you to insert UML diagrams into your comments using the `<uml>` tag and the PlantUML-Syntax inside of it.

**typedoc-plantuml-extended**: Someone uploaded the extensions of typedoc-plantuml developed by @0815fox to NPM and called it this way. It automatically creates class diagrams for your classes without having to insert any <uml> tags in your comments.
