### ISSUE TITLE
typedoc seems to never terminate when trying to document a very large definition file

### ISSUE THREAD

**Issue by xmo-odoo** [TypeStrong/typedoc#1755]
This is trying to build the documentation for https://github.com/octokit/openapi-types.ts, the "entry point" is rather large at 1.5MB, I added the following `tsconfig.json` at the root of the repository in order to enable typedoc:
```json
{
    "compilerOptions": {
        "strict": true
    },
    "typedocOptions": {
        "entryPoints": ["packages/openapi-types/types.d.ts"],
        "out": "docs",
        "readme": "none",
    }
}
```
Running typedoc with `--logLevel Verbose` prints the following:
```
Debug: Using TypeScript 4.4.4 from ./node_modules/typescript/lib
Debug: Converting with 1 programs 1 entry points
Debug: Finished getting entry points in 2656ms
Debug: Begin readme search at ./packages/openapi-types
Debug: Finished conversion in 11168ms
Debug: Renderer: Loading highlighter took 752ms
```
then it pegs a core and doesn't log anything anymore, I ended up killing the process after a bit more than an hour:

    4957.74s user 3.66s system 99% cpu 1:22:42.55 total

**Comment by Gerrit0** [comment]
Something's definitely very wrong here, conversion should take significantly longer than rendering in almost all cases (unless maybe there's a ridiculous number of code samples to highlight)
