### ISSUE TITLE
Feature request: Add option to lowercase output file names

### ISSUE THREAD

**Issue by iliubinskii** [TypeStrong/typedoc#1766]
## Search Terms

lowercase output file names

## Problem

Currently plugin keeps casing (e.g. Action.ts is converted to Action.html).
The problem is that Github pages convert this file to lowercase action.html.
As a result, links to Action.html become broken, because Github URLs are case sensitive.

## Suggested Solution

Add option to lowercase output file names

**Comment by KillyMXI** [comment]
Why is this closed?
I would prefer typedoc not to depend on system-wide git config.

This error looks really obscure, and of all things for me typedoc seems the most responsible for it.
The only thing changed was the version bump (0.20.37 to 0.22.8), and all of a sudden it generated bad filenames, when previously it was fine.
I could only attribute it to sloppy filename handling when switching to the new templates and everything.
