### ISSUE TITLE
`no-js` class is not removed when JS is enabled

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1768]
## Search terms

html, no-js, js

## Expected Behavior

The `no-js` is removed from the `html` element when JS is enabled.

## Actual Behavior

The `html` element always has `no-js` class.

![image](https://user-images.githubusercontent.com/20878432/139277483-592c31e6-381f-4fc9-8519-0381fa31baaf.png)

## Steps to reproduce the bug

Open any page generated by TypeDoc.

## Environment

-   Typedoc version: 0.22.7
-   TypeScript version: 4.4.2
-   Node.js version: 16.x
-   OS: Win10

**Comment by Gerrit0** [comment]
Is there any meaningful difference in having this rather than using the CSS behavior by default, and having JS override that?

I don't really like keeping things in TypeDoc that it doesn't use... particularly things that can't be easily tested.

**Comment by RunDevelopment** [comment]
> I don't really like keeping things in TypeDoc that it doesn't use... particularly things that can't be easily tested.

Good point. We just saw what happens when things aren't used :)

I'll make a PR removing `no-js`.
