### ISSUE TITLE
Website: Publish workflow will fail until new TypeDoc version released

### ISSUE THREAD

**Issue by srmagura** [TypeStrong/typedoc#1778]
(￣_￣|||)    I didn't consider that the publish workflow checks out the latest tag, not master, after cloning the TypeDoc repo. So the publish workflow is going to fail because it depends on my tweaks to the example's `typedoc.json`. I think we can just let it fail until the next time a release is published. Or I can put in a temporary fix. Thanks.

See https://github.com/srmagura/typedoc-site/runs/4060567189 for reference.

**Comment by Gerrit0** [comment]
I'll just let it fail a bit longer, probably going to publish a release today :)

**Comment by Gerrit0** [comment]
It works!
