### ISSUE TITLE
How to Setup Typedoc for NextJS Project

### ISSUE THREAD

**Issue by ardiansyaherwin** [TypeStrong/typedoc#1779]
## Search terms
Setup, NextJS

## Question
Hi, I was wondering how to create a proper setup for NextJS app. Here's what I got so far.

Project structure:
```
src
-- components
---- base
------ BaseComponent1
-------- index.tsx
------ BaseComponent2
-------- index.tsx
-- pages
---- _app.tsx
---- dashboard
------ home
-------- index.tsx
------ about
-------- index.tsx
------ contact
-------- index.tsx

```

TSConfig.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": "./src",
    "plugins": [
      { "name": "typescript-plugin-css-modules" }
    ]
  },
  "include": [
    "next-env.d.ts",
    "next.config.js",
    "src/**/*.module.css",
    "src/**/*.css",
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": [
    "node_modules",
    "dist",
    ".next"
  ]
}
```

Typedoc.json:
```
{
  "name": "Code Documentation",
  "entryPoints": ["src"],
  "entryPointStrategy": "Expand",
  "tsconfig": "./tsconfig.json",
  "out": "docs"
}
```

Using above configuration, the build ran successfully. 
However the output is not what I expected, as the sidebar is not displaying the projects hierarchy in nested layout.
<img width="432" alt="Screen Shot 2021-11-04 at 15 10 02" src="https://user-images.githubusercontent.com/2732220/140279076-7fc3fa89-42b2-40d6-a7b6-7319b0e789c9.png">

Any advice on how to make the sidebar showing nested hierarchy according to projects structure respectively?

**Comment by afkcodes** [comment]
hey @ardiansyaherwin did you find any answers?

**Comment by ardiansyaherwin** [comment]
> hey @ardiansyaherwin did you find any answers? 

Nope, just switched to storybook recently

**Comment by Gerrit0** [comment]
> Any advice on how to make the sidebar showing nested hierarchy according to projects structure respectively?

AFAIK, there's no support in any TypeDoc 0.22 theme for this, it should be relatively easy to create, however, even without changing the theme itself, you could inject a script with https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md#hooks-v0228, which could update the sidebar on load.
