### ISSUE TITLE
Directories with spaces not supported on Windows

### ISSUE THREAD

**Issue by marlowp** [TypeStrong/typedoc#178]
When running a grunt task with the following details for a project in a directory structure that contains spaces on Windows I receive the following error:

_Error:_
Running "typedoc:build" (typedoc) task
'C:\Users\marlow_p\Documents\Visual' is not recognized as an internal or external command,
operable program or batch file.
Warning: Task "typedoc:build" failed. Use --force to continue.

_GruntFile.js:_

```
  typedoc: {
      build: {
          options: {
              module: 'commonjs',
              target: 'es5',
              out: 'docs/',
              name: 'My project title'
          },
          src: 'src/**/*'
      }
  }
```

**Comment by cspotcode** [comment]
This looks like a bug in grunt-typedoc, not typedoc.  grunt-typedoc calls child_process.spawn() to invoke typedoc's CLI, and I'm guessing that's what is splitting your path on spaces.

If I'm correct, this should be fixed by TypeStrong/grunt-typedoc#9.
