### ISSUE TITLE
Single valued enum is parsed as a broken reference

### ISSUE THREAD

**Issue by gviligvili** [TypeStrong/typedoc#1780]
## Search terms
Enum, Single value enum, Broken reference

## Expected Behavior
Say I got this ts file, with an enum with only 1 value in it

```
export enum CoolEnum {
 FOO = 'FOO_VALUE', 
} 
 
export interface Response { 
  x:  CoolEnum
}
```
I would expected the output to be:
```
{
  "id": 5,
  "name": "x",
  "kind": 1024,
  "kindString": "Property",
  "type": {
    "type": "reference",
    "id": 1,
    "name": "CoolEnum" // The reference name is CoolEnum.
  }
  ...
}
```
 
## Actual Behavior
The output of is actually this: 
```
{
  "id": 4,
  "name": "x",
  "kind": 1024,
  "kindString": "Property",
  "type": {
    "type": "reference",
    "id": 2,
    "name": "FOO" // It doesn't point into CoolEnum, it points to the *name* of the single value in the enum, by *reference*.
  }
  ...
}
```

if you think about it, it's structure would look like this :
``` 
export enum CoolEnum {
   FOO = 'FOO_VALUE',
}
 
export interface Response {
   x: FOO // That's the single enum values name, it not CoolEnum
}
```

## Steps to reproduce the bug
This ts snippet is all you need, just use JSON as output.

## Environment

-   Typedoc version: 0.22.7
-   TypeScript version: 4.1.6
-   Node.js version: 14.15.4
-   OS: macOS 10.15.7

**Comment by Gerrit0** [comment]
Huh, well that's unexpected. I could argue it's not technically *wrong* to point to the single value, but it's certainly not the desired behavior... and the name ought to indicate that at least. I'd definitely rather have this use `CoolEnum` as the type.

**Comment by Gerrit0** [comment]
Having spent more time looking at this... TypeDoc appears to be doing the right thing, at least based on my assumption that `type.symbol` for a reference type... points at the referenced symbol. If I look at the symbol ID of the type reference, it does actually point to `FOO`, not to `CoolEnum`. I'm leaning towards this being a bug in TypeScript... maybe I don't understand how references are resolved, but symbols work for everything else... I've posted a query in the compiler API chat that some TS team members look at, so might know more in a couple days.

**Comment by gviligvili** [comment]
@Gerrit0  Thanks ! really appreciate it.

**Comment by Gerrit0** [comment]
Consensus there seemed to be that this was a bug in the compiler, I've filed https://github.com/microsoft/TypeScript/issues/46755. Will leave this open until that issue is appropriately labeled.

**Comment by Gerrit0** [comment]
Based on the feedback from the TS issue, I think I'll mark this as wontfix - if someone submits a PR to TypeScript to change this, it'll automatically be picked up here. Until then, this feels like a very minor edge case that it isn't worth adding hacks to TypeDoc to try to fix.
