### ISSUE TITLE
How to hide exports in certain folders?

### ISSUE THREAD

**Issue by 2A5F** [TypeStrong/typedoc#1782]

**Comment by Gerrit0** [comment]
https://typedoc.org/guides/options/#exclude

**Comment by 2A5F** [comment]
@Gerrit0  `--exclude` not work

```ts
//  index.ts
export * from './foo/index.ts'

// foo/index.ts
export * from './xxx.ts'
export * from './xxx.ts'
```

I tried
-  `--exclude foo`
-  `--exclude ./foo`
-  `--exclude foo/**/*.ts`
-  `--exclude ./foo/**/*.ts`

**Comment by Gerrit0** [comment]
If I remember right exclude filtering is given absolute paths, so you'd need `"**/foo/**/*.ts"`

**Comment by 2A5F** [comment]
@Gerrit0 same not work

**Comment by Gerrit0** [comment]
You'll need to provide a reproduction. It works for me. If you're providing that on the command line, your shell might be expanding it. You need to pass the globs to TypeDoc, the quotes in my previous post were important.

**Comment by 2A5F** [comment]
[test.zip](https://github.com/TypeStrong/typedoc/files/7533426/test.zip)
@Gerrit0

**Comment by 2A5F** [comment]
[test.zip](https://github.com/TypeStrong/typedoc/files/7533441/test.zip)
`npm run doc`

**Comment by Gerrit0** [comment]
`**/bar/**/*.ts` means "exclude all files in directories under bar", not "exclude all files under bar" for that setup, you need `**/bar/*.ts`, or now that I've looked at this more closely, the leading `**/` could be replaced with `src/` for `src/bar/*.ts`

I'd really recommend using a config file, especially with how many options you're configuring now... you can put options under `typedocOptions` in tsconfig.json if you don't want to add another file to your project

**Comment by 2A5F** [comment]
![image](https://user-images.githubusercontent.com/13982338/142849338-e08175b4-6bd2-4386-b7d0-7064dc9a2fda.png)
![image](https://user-images.githubusercontent.com/13982338/142849390-45728b83-242d-452f-a78c-24ba8ad06a3d.png)

I think --exclude is not suitable for this situation

**Comment by Gerrit0** [comment]
Are you on Windows? Powershell doesn't handle quotes the same way bash does (another good reason to use a configuration file). `--showConfig` might show that the quotes are being included in the option.

**Comment by 2A5F** [comment]
You are right, powershell outputs 
```
exclude: ["C:\\Path\\To\\'src\\bar\\*.ts'" ], 
```
😂
