### ISSUE TITLE
Custom Theme Support (0.22.x)

### ISSUE THREAD

**Issue by matteobruni** [TypeStrong/typedoc#1785]
## Search terms

custom themes

## Question

Hello,

I've created a custom theme in my repository (for now it's empty),

``` typescript
import { Application } from "typedoc";
import { TestTheme } from "./theme";

export function load(app: Application): void {
    app.renderer.defineTheme("tsparticles-docs", TestTheme);
}
```

but when I try to build the documentation the CLI can't find it.

This is the `tsconfig.file`

``` json
{
  "typedocOptions": {
    "gaID": "UA-161253125-1",
    "githubPages": true,
    "includes": "./markdown",
    "entryPoints": [
      "./src/"
    ],
    "entryPointStrategy": "expand",
    "name": "tsParticles",
    "includeVersion": true,
    "hideGenerator": true,
    "out": "./docs",
    "theme": "tsparticles-docs"
  }
}
```

I didn't find much in the website or in issues here. The `node_modules` folder contains the theme, and it's in the `package.json` `devDependencies`.

Am I missing something? [This](https://github.com/rigor789/typedoc-test-theme) was a sample custom theme I've started from.

**Comment by omar0404** [comment]
where did you define load function ?

**Comment by matteobruni** [comment]
> where did you define load function ?

The function is in the `index.ts` file

**Comment by omar0404** [comment]
how did you tell typedoc to excute your load function ?

**Comment by matteobruni** [comment]
> how did you tell typedoc to excute your load function ?

I really don't know. I think it's something wired inside typedoc itself. The documentation [here](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md) does the same.

**Comment by omar0404** [comment]
try to put in package.json in keywords property
```
  "keywords": [
    "typedoc",
    "plugin",
    "typedocplugin",
    "typedoc-plugin"
  ],
```

**Comment by matteobruni** [comment]
> try to put in `your-theme/package.json` in keywords property
> 
> ```
>   "keywords": [
>     "typedoc",
>     "plugin",
>     "typedocplugin",
>     "typedoc-plugin"
>   ],
> ```

This worked, thank you so much

**Comment by omar0404** [comment]
@matteobruni a question please is there anyway to customize a theme without creating npm package ?

**Comment by matteobruni** [comment]
> @matteobruni a question please is there anyway to customize a theme without creating npm package ?

I don't know, I had a folder in the previous version, but I've found only a custom theme with a package so I've created a private package in the monorepo.

**Comment by Gerrit0** [comment]
You don't need a npm package for a custom theme - but automatic plugin discovery only works for packages under node_modules. You can point TypeDoc to any JS file with a plugin that you'd like with the [plugin](https://typedoc.org/guides/options/#plugin) option.

**Comment by omar0404** [comment]
@Gerrit0  how can i make default theme is light ?

**Comment by Gerrit0** [comment]
The theme defaults to the user's choice, if that's dark mode, it seems rude to force light mode on them...

That said, you could do this with a plugin:

```tsx
import { Application, JSX } from "typedoc"

const script = `localStorage.setItem("tsd-theme", localStorage.getItem("tsd-theme") || "light")`;

export function load(app: Application) {
  app.renderer.hooks.on("head.end", () => <script><JSX.Raw html={script} /></script>);
}
```
