### ISSUE TITLE
per module readme location

### ISSUE THREAD

**Issue by farfromrefug** [TypeStrong/typedoc#1787]
## Search Terms

module readme per-module

## Problem

In my lib i have a global readme and per-module readme (lerna monorepo)
In typedoc i see my main readme but when i go into a module, i dont have the readme

## Suggested Solution

Would be good to be able to specify a md location to be used as the module readme. 
maybe something like this?
```js
/**
 * Material ActivityIndicator component
 * @module @nativescript-community/ui-material-activityindicator
 * @readme ../../packages/activityindicator/readme.md
 */
 ```

**Comment by Gerrit0** [comment]
Sounds a lot like #1658.

**Comment by farfromrefug** [comment]
@Gerrit0 yes i think it is the same thing. Is it doable or is it something you dont "want to / cant"  add?

**Comment by Gerrit0** [comment]
It's something I want to add, but haven't grouped under something I plan to do for the next minor release

**Comment by farfromrefug** [comment]
@Gerrit0 sure thanks. Good to have but no hurry.
Do you want me to close this as duplicate?

**Comment by Gerrit0** [comment]
I've gone ahead and done it, wanted to be sure I answered your questions before closing :)
