### ISSUE TITLE
Support namespace-like variables?

### ISSUE THREAD

**Issue by srmagura** [TypeStrong/typedoc#1789]
## Search Terms

Namespace, not included in the documentation

## Problem

The code

```ts
type Email = (value: string) => boolean;

export type Validators = {
  email: Email;
};
```

produces the warning

```text
Warning: Email, defined at src/index.ts:12, is referenced by Validators.__type.email but not included in the documentation.
```

and the documentation

![image](https://user-images.githubusercontent.com/801549/141233782-a3df7470-d5dd-444e-ac92-07914ebaf935.png)

## Suggested Solution

In my case, I want TypeDoc to treat the above code as

```ts
export type Validators = {
  email: (value: string) => boolean;
};
```

When TypeDoc sees that the unexported type `Email` is going to be referenced in the documentation, it could "replace" `Email` with `(value: string) => boolean`.  But what if it was an accident that the `Email` type wasn't exported, and now we've erased it from the documentation? 🤔

## Additional Context

This was discussed on #1739, see [my comment](https://github.com/TypeStrong/typedoc/issues/1739#issuecomment-950429431) and those that follow.

I have no idea if this is a common problem. This seems like a low priority issue to me.

**Comment by Gerrit0** [comment]
I didn't realize this the first time I read this since "namespace-like variables" meant something different to me, this is something you *could* do with a plugin but is not something I want to include in TypeDoc proper. #1823.
