### ISSUE TITLE
How to document a interface in a react component

### ISSUE THREAD

**Issue by afkcodes** [TypeStrong/typedoc#1790]
## Search terms
interface, typedoc, documentation 

## Question

I have a simple interface in my react component in my project which i need to document but it seems i am doing something wrong and it does not shows up in the docs.

```

interface ButtonProps { 
  /** color of the button */
  color: string; 
 /** height of the button */
  height: number; 
  width: number; 
  fontSize: number; 
  fontWeight: number; 
  hasOutline: boolean; 
  radius: number
 }
export const Button = ({ color, height, width, fontSize, fontWeight, hasOutline, radius }: ButtonProps) => {
  return <button>
    Hello
  </button>;
}

```

after running the docs command i am getting this warning :
```
ButtonProps, defined at src/components/Button.tsx:2, is referenced by components/Button.Button.Button.__namedParameters but not included in the documentation.
```
Please anyone tell me what am i doing wrong and how can i make it work, i need to show the props that are accepted by this component

**Comment by Gerrit0** [comment]
You haven't exported your interface, TypeDoc only documents what you export, because that's what your public API is:

```ts
export interface ButtonProps {
```

**Comment by afkcodes** [comment]
Thanks got it closing this issue now :)
