### ISSUE TITLE
Add support for TypeScript 4.5

### ISSUE THREAD

**Issue by vladmandic** [TypeStrong/typedoc#1798]
Now that **TypeScript** 4.5 is released, would be nice if **TSDoc** supported it 

It seems to work without issues (unlike some painful upgrades in the past), just throws a warning:

> You are running with an unsupported TypeScript version! TypeDoc supports 4.0, 4.1, 4.2, 4.3, 4.4

Environment: TSDoc 0.22.9 with TypeScript 4.5.2

**Comment by Gerrit0** [comment]
Should be able to get to this Tuesday at the latest :)

**Comment by rvilarl** [comment]
The change required is to add `|| 4.5.x` to the following line, is not it?

https://github.com/TypeStrong/typedoc/blob/2742e7f92a5e02d57ce0bf19983bd364638537d3/package.json#L31

We are using TypeDoc with TypeScript 4.5.2 starting with  4.5.0-beta in VexFlow without issues now since 22 days.
