### ISSUE TITLE
Add Math display support

### ISSUE THREAD

**Issue by basilgass** [TypeStrong/typedoc#1799]
## Search Terms

Math, KaTeX

## Problem

I wanted to add some math in the documentation, using for example KaTeX.

## Suggested Solution

Allow to load external script and style to automatically display math in any html page. Basically, I need to add this in the header of each page.

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css" integrity="sha384-R4558gYOUz8mP9YWpZJjofhk+zx0AS11p36HnD2ZKj/6JR5z27gSSULCNHIRReVs" crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js" integrity="sha384-z1fJDqw8ZApjGO3/unPWUPsIymfsJmyrDVWC8Tv/a1HeOtGmkwNd/7xUS0Xcnvsx" crossorigin="anonymous"></script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
```

I tried to understand how to use a custom theme, but I'm not sure it's possible like that...

**Comment by Gerrit0** [comment]
You can do this pretty easily with a plugin:

```ts
import { Application, JSX } from "typedoc"

export function load(app: Application) {
  app.renderer.hooks.on("head.end", () => {
    return <>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css" integrity="sha384-R4558gYOUz8mP9YWpZJjofhk+zx0AS11p36HnD2ZKj/6JR5z27gSSULCNHIRReVs" crossorigin="anonymous">
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js" integrity="sha384-z1fJDqw8ZApjGO3/unPWUPsIymfsJmyrDVWC8Tv/a1HeOtGmkwNd/7xUS0Xcnvsx" crossorigin="anonymous"></script>
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
      </>
   });
}
```

Or if you don't want to set up something to compile TS,

```js
const { JSX } = require("typedoc");

export function load(app) {
    app.renderer.hooks.on("head.end", () => {
        return JSX.createElement(JSX.Fragment, null,
            JSX.createElement("link", { rel: "stylesheet", href: "https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css", integrity: "sha384-R4558gYOUz8mP9YWpZJjofhk+zx0AS11p36HnD2ZKj/6JR5z27gSSULCNHIRReVs", crossorigin: "anonymous" },
                JSX.createElement("script", { defer: true, src: "https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js", integrity: "sha384-z1fJDqw8ZApjGO3/unPWUPsIymfsJmyrDVWC8Tv/a1HeOtGmkwNd/7xUS0Xcnvsx", crossorigin: "anonymous" }),
                JSX.createElement("script", { defer: true, src: "https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/auto-render.min.js", integrity: "sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR", crossorigin: "anonymous", onload: "renderMathInElement(document.body);" })),
            "}); }");
    });
}
```

This isn't something I want to add to every page by default -- an extra three requests that most projects don't need isn't great.

**Comment by basilgass** [comment]
Thanks for the code... and sorry for the delay :)

Unfortunatly, I can't make it work. Maybe I'm making it wrong...

1. I created a file name "typedoc.katex.js" and pasted the second code.
2. Ran the `typedoc` with these options in my `tsconfig.js` file:

```
"typedocOptions": {
    "entryPoints": [
      "src/maths/algebra/index.ts",
      "src/maths/geometry/index.ts",
      "src/maths/coefficients/index.ts",
      "src/maths/random/index.ts",
      "src/maths/numeric.ts",
      "src/maths/shutingyard.ts"
    ],
    "plugin": ["./typedoc.katex.js"],
    "out": "docs"
  },
```

I'm receiving this error code:
```
Error: The plugin C:\Users\basil\Documents\Mes Sites Webs\PI\typedoc.katex.js could not be loaded.
Error: C:\Users\basil\Documents\Mes Sites Webs\PI\typedoc.katex.js:3
export function load(app) {
^^^^^^
```

**Comment by Gerrit0** [comment]
```ts
// change
export function load(app) {
// to
exports.load = function (app) {
```

**Comment by basilgass** [comment]
Hi!

Thanks a lot ! It works like a charm !

Maybe one little question to make my life easier:

When writing math using katex (and any LaTeX word processor), you must surround the math with `\( <math commands> \)` or `\[ <math commands> \]`.

The special caracters to start math is either `\(` or `\[`. Unfortunately, it isn't detected correctly. I have to double backslah them, ie `\\(` and `\\[`. I encountered this problem once also with markdown... So, is there an easy way with typedoc to add `\(` and `\[` to a "white list" so it's not preprocessed (and also the data inside, because it uses a lot of backslash)

As I said, it's just to make my life easier and if there isn't an easy solution, I will double backslash my math command :)


Again, thanks for your time and your help !

**Comment by Gerrit0** [comment]
That's almost certainly a Marked issue, there might be an option for it, but I doubt it. TypeDoc doesn't do any extra processing for escapes there.

**Comment by stranskyjan** [comment]
Based on this issue and the discussion, I have created [typedoc-plugin-katex](https://www.npmjs.com/package/typedoc-plugin-katex)
