### ISSUE TITLE
Add a --cname option to create the CNAME file

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1803]
## Search Terms

CNAME GitHub pages

## Problem

The repro for Gerrit0/typedoc-plugin-missing-exports#4 has a a build script which copies a CNAME file so that GitHub Pages works properly. We should make this extra build step easier.

## Suggested Solution

Add an option `--cname`, which will result in TypeDoc creating a CNAME file with the contents of that option.

**Comment by matteobruni** [comment]
I've just seen this issue (and it refers to my project 🤣). I don't use this anymore since the `docs` folder is inside another website but it could be useful for someone else.

I think a `cname` string option could fit, that value will be written inside the CNAME file.
