### ISSUE TITLE
Some JSDoc tags prevent class docstrings from showing

### ISSUE THREAD

**Issue by ejuda** [TypeStrong/typedoc#1807]
## Search terms

tags, docstring, class, extends, jsdoc

## Expected Behavior

TypeDoc should be able to render docstrings no matter what JSDoc tags are present in them.

## Actual Behavior

Some tags (`@class`, `@extends`) prevent class documentation from showing.

For instance the documentation for these three classes will not render:

```ts
/**
 * @class NoDocs1
 *
 * This is another class.
 */
class NoDocs1 {}

/**
 * @extends BaseClass
 *
 * This is an other class.
 */
class NoDocs2 extends BaseClass {}

/**
 * @class NoDocs3
 * @extends BaseClass
 *
 * Some docs.
 */
class NoDocs3 extends BaseClass {}
```

<img width="608" alt="NoDocs1" src="https://user-images.githubusercontent.com/26031740/143568683-6a87edf4-aa76-43b1-ba37-0443b265d727.png">

However, adding a made-up tag afterwards restores the class documentation:

```ts
/**
 * @class WithDocs1
 * @madeupTag
 *
 * This is a different class.
 */
class WithDocs1 {}

/**
 * @class WithDocs2
 * @extends BaseClass
 * @anotherMadeupTag
 *
 * This is a different class.
 */
class WithDocs2 extends BaseClass {}
```

<img width="606" alt="WithDocs1" src="https://user-images.githubusercontent.com/26031740/143568654-6f611256-4b45-4e8f-9da9-b7c66ef02761.png">

I have only tested `@class` and `@extends` tags for this behavior, but it's possible that this also affects other tags (and nodes other than classes).

## Steps to reproduce the bug

1. Clone [the reproduction repository](https://github.com/ejuda/typedoc-tags-in-docstrings-repro).
2. `npm ci`
3. `npm run docs`
4. This will generate documentation in `docs` directory.

## Environment

-   Typedoc version: 0.22.10
-   TypeScript version: 4.5.2
-   Node.js version: 14.15.4
-   OS: Windows 10

**Comment by ejuda** [comment]
@Gerrit0 I think I know what the issue here is and I'd love to contribute - I'll submit a PR shortly. 😃

**Comment by Gerrit0** [comment]
With 0.23, if you want to treat some tags as modifier tags and not cause them to create a block, you can do this by adding them to the `modifierTags` array option https://typedoc.org/guides/options/#modifiertags
