### ISSUE TITLE
Maintainers Needed

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1812]
I'm looking for a break from TypeDoc - at least for a month or two, maybe indefinitely. Open source is meant to be fun, and I've realized that I'm not enjoying working on it right now. There are a few reasons for this, but the primary one is probably that I'm tired of trying to balance "make breaking changes to enable new capability" with "don't break the world".

If you're interested in helping out, feel free to reply. I will check back in a few days.

**Comment by katsanva** [comment]
Hello, @Gerrit0! I like ts and find the typedoc as a pretty valuable part of its ecosystem. I hope I can be handy with maintaining this one.

**Comment by Gerrit0** [comment]
Awesome, thank you both! Sure, I'd be up for a walkthrough on the architecture. I hang out in the TypeScript discord server a lot, if that works.

**Comment by canonic-epicure** [comment]
Good for you! Please enjoy your time.

Speaking of 
> "make breaking changes to enable new capability" with "don't break the world"
do you have any vision of the better architecture for the tool? Like, if you would be starting the TypeDoc from scratch, what would you change?

**Comment by matteobruni** [comment]
Hi @Gerrit0,

I'd like to help to this project since I use it a lot. Does a discord/slack server exist where we can ask for help for helping contributing this project? Like the architecture, some guidelines or anything helpful for new contributors?

**Comment by Zamiell** [comment]
@matteobruni Check out the #typedoc channel in the official TypeScript Discord server.

**Comment by Gerrit0** [comment]
Awesome, thanks Matteo! I've sent you an invite as well. Yeah, the TS discord is a good place for that.

> do you have any vision of the better architecture for the tool? Like, if you would be starting the TypeDoc from scratch, what would you change?

Hard to limit this to a small number of things, I've changed maybe half of the architecture I didn't like about TypeDoc... but I think TypeDoc, somewhat like Webpack, suffers from trying to cater to too many different use cases. Personally, I find documenting "internals" to be useless. I only care about the public API of a library (assuming a well written library...) but lots of people also want to document internals, and do this through several methods, whether it's documenting all files in a project instead of just the exports that `require("foo")` will give you, or using plugins to document every symbol in scope.

There's also several different use cases for documentation. TypeDoc was originally intended to be used to produce documentation by someone publishing a library... but what if the library author didn't do this? Some people find it useful to have HTML documentation for their own project, and how that should be organized is probably somewhat different than how a published module should be documented.

If I was starting from scratch I probably wouldn't build TypeDoc, I'd build like a quarter of it. The kind of tool I've wanted since I started doing development on Node again (ignoring TypeDoc, just in the past few weeks) is something that builds local reference docs for me from the source in node_modules from my dependencies in package.json, then all the documentation is in one place (at least for those packages which don't do weird things)

**Comment by canonic-epicure** [comment]
Thanks for comments. I was thinking recently, that TypeDoc could be split into 2 packages - first, that produces some kind of augmented AST, which remains pretty close to the original TS AST (backend), and 2nd will be "frontend" using the data from backend and providing UI.

But then I realized its pretty much how it is already with the Reflections tree. Do you think Reflections tree generation can be improved (or its already well-written and maintainable)?

**Comment by krisztianb** [comment]
@Gerrit0 thanks for all your work man. I was always astonished about how you kept this project alive all by yourself. Wish you all the best for the future.

**Comment by dragomirtitian** [comment]
@Gerrit0 Hi. I'd be interested in helping to maintain this project. I currently work for Bloomberg and we are actively using TypeDoc to document internal code. I have a decent amount of experience with compilers and AST manipulation as well as specific experience with the TypeScript compiler and the Typescript compiler API.

I would be interested in picking up some medium sized issues to get more familiar with the code base.

**Comment by Dayday10** [comment]
I would be grateful to have you welcome and Thank You

**Comment by Dayday10** [comment]
> @Gerrit0 Hi. I'd be interested in helping to maintain this project. I currently work for Bloomberg and we are actively using TypeDoc to document internal code. I have a decent amount of experience with compilers and AST manipulation as well as specific experience with the TypeScript compiler and the Typescript compiler API.
> 
> I would be interested in picking up some medium sized issues to get more familiar with the code base.

Please do and thank you

**Comment by Gerrit0** [comment]
@dragomirtitian that would be awesome! I've sent you an invite.

> But then I realized its pretty much how it is already with the Reflections tree. 

Yep, I've considered trying to break TypeDoc into smaller packages a few times, and always ended up deciding against it, mainly because conversion into reflections can be affected by comments, and so it isn't doesn't make sense to split up into parts when the parts aren't much use without each other.

> Do you think Reflections tree generation can be improved (or its already well-written and maintainable)?

If I was starting from scratch, I'd probably change it somewhat. It is sometimes convenient that every reflection is a `DeclarationReflection`, but it also means you can construct reflections which have no grounding in reality (an enum with signatures for example). I'm pretty happy with the type tree though.
