### ISSUE TITLE
Is paths variable of tsconfig supported?

### ISSUE THREAD

**Issue by rp3e11** [TypeStrong/typedoc#1813]
## Search terms

tsconfig paths

## Question
Hi,
I am trying to setup typedoc in an angular project where we use local libraries that are linked via the tsconfig path declarations
```json
{
..
  "compilerOptions": {
    ..
   "paths": {
      "@local/lib1": ["src/lib1/lib/public_api.ts"]
    }
  }
}
```
Whe in run typedoc, it throws errors of the form
```
 Cannot find module '@local/lib1' or its corresponding type declaration
```
I am wondering, whether that should basically work as well in typedoc? Has anybody experienced a similar issue?

**Comment by Gerrit0** [comment]
Yes, it should be supported. If you have multiple tsconfig files, TypeDoc might not be reading the right one, you can tell it which one to read with the `--tsconfig` option.

**Comment by rp3e11** [comment]
Thanks for the reply. It helped solving it.
