### ISSUE TITLE
how to config the typedoc.json when i want only one package useful and other not  in yarn workspaces project

### ISSUE THREAD

**Issue by jypblue** [TypeStrong/typedoc#1814]
## Question
i have a lerna + yarn workspace project that i want the package utils generate typedoc but ignore other packages, please tell me how to config ? the readme is useless, when i config like below: 
`  "typedocOptions": {
    "cleanOutputDir": true,
    "entryPoints": [
      "packages/utils"
    ],
    "entryPointStrategy": "packages",
    "exclude": ["**/test/**"],
    "excludeExternals": true,
    "excludePrivate": true,
    "hideGenerator": true,
    "name": "xxx",
    "out": "doc",
    "readme": "README.md",
    "plugin": []
  }`

i just it's useful in package utils, other packages useless

**Comment by jypblue** [comment]
typedoc version:0.22.10

**Comment by Gerrit0** [comment]
You could probably do this with the exclude option, TypeDoc won't create a module if all symbols within it are excluded

**Comment by jypblue** [comment]
> You could probably do this with the exclude option, TypeDoc won't create a module if all symbols within it are excluded

and if some functions import some npm packages; how can i config it igonre 3rd package ts check ?

**Comment by Gerrit0** [comment]
Sounds like you might want the [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) compiler option.

**Comment by jypblue** [comment]
> Sounds like you might want the [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) compiler option.

{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "allowJs": false,
    "checkJs": false,
    "declaration": true,
    "target": "es2019",
    "module": "esnext",
    "sourceMap": true,
    "experimentalDecorators": true,
    "jsx": "react-native",
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "strict": false,
    "skipLibCheck": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {}
  },
  "typedocOptions": {
    "entryPoints": ["src/index.ts"],
    "out": "doc",
    "name": "test",
    "hideGenerator": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "lib", "es", "**/__tests__/**", "tests"]
}

**Comment by Gerrit0** [comment]
Does `npx tsc --noEmit` give errors? TypeDoc should match that behavior.
