### ISSUE TITLE
Unable to get @link to work with nested methods and properties of class fields.

### ISSUE THREAD

**Issue by barca-reddit** [TypeStrong/typedoc#1815]
## Search terms

Link, Link Resolution

## Question

Hello. So I am trying to achieve something simple, but I don't have much experience with typedoc, tsdoc or jsdoc in general, so I thought I'd ask here.

Basically I have a class, and that class has a property (I think it's called public class field) which by itself can contain more nested properties and methods. I would like to create a `@link` pointing exactly to that method or property, rather than the root level property itself. Consider this simple example, and I am using Typedoc version `0.22.10`:

```typescript
/**
 * My simple database
 */
export class Db {
    /**
     * Database CRUD operations
     */
    operations = {
        create: (id: string) => {
            console.log('Creating', id);
        },
        read: (id: string) => {
            console.log('Reading', id);
        },
        update: (id: string) => {
            console.log('Updating', id);
        },
        delete: {
            one: (id: string) => { console.log('Deleting one item:', id) },
            many: (ids: string[]) => { console.log('Deleting items:', ids) }
        }
    }

    /**
     * Initializes the database and calls the following method:
     * 
     * These work:
     * 
     * {@link Db.operations} or [[Db.operations]]
     * 
     * But none of these do:
     * 
     * {@link Db.operations.delete} or [[Db.operations.delete]]
     * 
     * {@link Db.operations.delete.many} or [[Db.operations.delete.many]]
     */

    init() {
        this.operations.delete.many(['foo', 'bar', 'baz'])
    }
}

new Db().init();
```

Basically I want my links to point at `Db.operations.delete` and/or `Db.operations.delete.many`, however, this is what gets rendered instead:

![image](https://user-images.githubusercontent.com/35380464/144442571-ffdb7c7d-738e-4e31-b24f-596d71956f8e.png)

I have setup a `typedoc.json` with `validation.invalidLink` set to `true` and this is what it outputs:

```
Debug: Using TypeScript 4.5.2 from ./node_modules/typescript/lib
Info: Starting compilation in watch mode...
Debug: Begin readme search at ./
Info: Found 0 errors. Watching for file changes.
Debug: Renderer: Loading highlighter took 358ms
Warning: 
[MarkedLinksPlugin]: Found invalid symbol reference(s) in JSDocs, they will not render as links in the generated documentation.
  In Db: [[Db.operations.delete]]
  In Db: [[Db.operations.delete.many]]
  In Db: {@link Db.operations.delete}
  In Db: {@link Db.operations.delete.many}
Info: Documentation generated at ./docs
Debug: HTML rendering took 399ms
```

So my question is, how do I get this to work properly (if possible)?

---

I also have a short follow-up question. Is it possible to have nested methods appear in the sidebar of the generated documentation? For example, this is what gets rendered currently:

![image](https://user-images.githubusercontent.com/35380464/144441292-801a74a8-e880-438e-9939-9b9e221a6837.png)

As you can see, only the `operations` property/class field gets listed in there, and I am wondering if I can get the nested methods of that property listed there as well, or it can only go 1 level deep?

Cheers!

**Comment by huzaifahj** [comment]
@barca-reddit Also interested in your last point and have created a separate issue (see above). Can anyone answer this or provide a solution?

**Comment by Gerrit0** [comment]
You might be able to do this with `Db.operation.__type.create`... like I said in #1848 though, I find this deep nesting of methods to be a bad idea... 

The `__type` is because the `operations` reflection doesn't have children. It's a property whose `type` is a [`ReflectionType`](https://typedoc.org/api/classes/ReflectionType.html). The `ReflectionType` stores a `declaration` which is another reflection with the name `__type`.

I'm not certain that this link, even if it resolves, will actually result in a usable link, since I don't think children of object types are given ID's when rendering.
