### ISSUE TITLE
Fully reset Application object so that output is the same if input unchanged

### ISSUE THREAD

**Issue by jugglingcats** [TypeStrong/typedoc#1818]
## Search terms

Unique ids

## Question

Sorry if this has been asked/answered before. We are using typedoc to generate json from our sources and we're running it in a dynamic website plugin (vite) and watching for source changes. Each time we run typedoc in the same process we get different ids, and this is messing up caching!

Here is the code:
```
export default function loadTypedoc(entryPoint, tsconfig = "tsconfig.doc.json") {
    const app = new Application()
    app.options.addReader(new TypeDocReader())
    app.options.addReader(new TSConfigReader())

    app.bootstrap({
        entryPoints: [entryPoint],
        tsconfig
    })

    try {
        const project = app.convert()

        if (project) {
            return app.serializer.toObject(project)
        } else {
            console.log("No typedoc generated!")
            return {
                children: []
            }
        }
    } catch (error) {
        throw error
    }
}
```

When this function is called multiple times for the same input, the ids in the generated json are different, ie. the call is not idempotent for the same input. Obviously then if you take the md5 sum or similar of the output it is changing.

Is there a way to fully reset the `Application` object so that the ids are the same?

Thanks

**Comment by Gerrit0** [comment]
https://typedoc.org/api/modules.html#resetReflectionID

**Comment by jugglingcats** [comment]
Thank you 🙏
