### ISSUE TITLE
How to exclude excessive partial declarations?

### ISSUE THREAD

**Issue by vitaly-t** [TypeStrong/typedoc#1820]
How to take [this kind of declaration](https://github.com/vitaly-t/iter-ops/blob/main/src/pipe.ts), and produce documentation that looks better [than this](https://vitaly-t.github.io/iter-ops/modules.html#pipe)?

I've tried separating parts with `@ignore` / `@hidden`, but those do not work for partial declarations.

Just trying to make my API look civilized, and not as awkward. Any suggestion?

---

![image](https://user-images.githubusercontent.com/5108906/145660976-b58d187e-5678-4498-8e46-466d7836b037.png)

**Comment by Gerrit0** [comment]
You probably want the `@hidden` / `@ignore` tags - https://typedoc.org/guides/doccomments/#%40hidden-and-%40ignore

**Comment by vitaly-t** [comment]
@Gerrit0 I don't follow. I've said right from start - 

> I've tried separating parts with `@ignore` / `@hidden`, but those do not work for partial declarations.

And you're just sending me right back to it.

**Comment by Gerrit0** [comment]
Sorry, I didn't see that, was distracted by the massive screenshot - you can put comments on individual signatures.

```ts
/** @hidden */
function pipe(a);
/** @hidden */
function pipe(a, b);
/** @hidden */
function pipe(a, b, c);
/** @hidden */
function pipe(a, b, c, d);
/** will not be hidden */
function pipe(a, b, c, d);
function pipe(...args) {...}
```

**Comment by vitaly-t** [comment]
That worked. Thank you!
