### ISSUE TITLE
Watch mode doesn't work with typedoc-plugin-markdown

### ISSUE THREAD

**Issue by wilcoxmd** [TypeStrong/typedoc#1827]
## Search terms

watch mode, plugins, typedoc-plugin-markdown

## Expected Behavior

When in watch mode, saving a file should regenerate TypeDoc output while respecting any plugins that might transform that output.

## Actual Behavior

When using watch mode with [`typedoc-plugin-markdown`](https://github.com/tgreyuk/typedoc-plugin-markdown), watch mode regenerates HTML instead of markdown files after changes are saved, and deletes the initially output markdown files.

## Steps to reproduce the bug

See https://github.com/wilcoxmd/typedoc-watch-plugin-repro

## Environment

-   Typedoc version: 0.22.10
-   TypeScript version: 4.5.2
-   Node.js version: 16.13.0
-   OS: macOS Monterey (12.0.1)

**Comment by Gerrit0** [comment]
This looks like a bug in typedoc-plugin-markdown to me. Instead of adding markdown as a custom theme, it tries to overwrite the default theme (which is not intentionally supported) and doesn't do it consistently before each render, just once on plugin load.

**Comment by wilcoxmd** [comment]
> This looks like a bug in typedoc-plugin-markdown to me. Instead of adding markdown as a custom theme, it tries to overwrite the default theme (which is not intentionally supported) and doesn't do it consistently before each render, just once on plugin load.

Thanks for taking a look. I opened a [follow up issue in typedoc-plugin-markdown](https://github.com/tgreyuk/typedoc-plugin-markdown/issues/279).

**Comment by wilcoxmd** [comment]
The issue was resolved in `typdoc-plugin-markdown@3.11.9`. Thanks again for your help!
