### ISSUE TITLE
Documentation coverage badge

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [TypeStrong/typedoc#1829]
## Search Terms

documentation coverage badge

## Problem

No easy way to inspect documentation coverage.

## Suggested Solution

Generate a badge similar to the one generated by `esdoc` (https://github.com/esdoc/esdoc-plugins/blob/master/esdoc-coverage-plugin/src/Plugin.js).

**Comment by Gerrit0** [comment]
There's now a plugin that does this: [typedoc-plugin-coverage](https://www.npmjs.com/package/typedoc-plugin-coverage)

**Comment by make-github-pseudonymous-again** [comment]
Thank you @Gerrit0!
