### ISSUE TITLE
Not updated DocComments?

### ISSUE THREAD

**Issue by aleung** [TypeStrong/typedoc#183]
Is the DocComments page (http://typedoc.org/guides/doccomments/) up to date?

It lists only two tags `@param` and `@return` are understood. All other tags will be rendered as definition lists. However I found that more tags are handled when I read typedoc source code.

For example, `@inheritdoc` should be used to copy comments from interface to implementation.(#78)

What's more, in DocComments it said:

> TypeDoc automatically copies comments and tags of the function implementation to its signatures for you.

However I can't make it work. No doc comment of dynamic module neither. Am I missing any configuration or tag which is undocumented?

**Comment by aciccarello** [comment]
The DocComments page has not been updated. There are several tags that could be included such as `@hidden` (#364).

PRs are always welcome.
