### ISSUE TITLE
Add GitHub link and/or link to the project site (instead of the typedoc site), to the default theme?

### ISSUE THREAD

**Issue by okikio** [TypeStrong/typedoc#1830]
## Search Terms

Would it be possible to add a GitHub link and/or a link to the actual site (instead of the typedoc site), to the default theme?

## Problem

I find for typedoc sites, I get to the typedoc site, and would like to return back to the original site, or just go to the GitHub page for the current project, and am unable to, e.g. [barba.js.org/api](https://barba.js.org/api/) (there is no button or link to the original site for barbajs, it's not a major problem, but it throws me off a bit, and I feel I'm not the only one who finds it off putting)

## Suggested Solution

Add a GitHub button and/or a original site button to the navbar of the default typedoc theme.

**Comment by Gerrit0** [comment]
Seems like a reasonable request, I think the links in the header should really be user configurable - there isn't an easy way to guess what they should be, some people might want to link to the Slack/Gitter/Discord/whatever for support for example

**Comment by okikio** [comment]
It would also be cool if we could add a link that could link to the projects original webpage, I think adding support for common link types should be good enough, e.g. discord, slack, github, etc..., if the users needs more than that they probs could configure the theme themselves (it would be awesome if the docs gave some example code to make getting started with this specific task easier)

**Comment by KillyMXI** [comment]
This is a feature I am missing very much as well.

This can be implemented as an array in typedoc options, with items specifying links, text and maybe an icon asset (if the latter is complicated - I can live without it, no problem - just having the right links with plain title is 1000 times better than not having them at all. Rollup [documentation](https://rollupjs.org/guide/en/) is an example with plain text links).

The place where I expect to see the links is dedicated for some filters that has no use for me and I had to put some effort to hide with CSS.
I much prefer to see the links either in what's currently called `tsd-page-toolbar` or `tsd-page-title`.
I think current design of search and filter is unintuitive (search) and not very useful (filters). I'd think where to move and how to make them more useful instead.
