### ISSUE TITLE
Method Returns extremely long

### ISSUE THREAD

**Issue by ZackaryH8** [TypeStrong/typedoc#1831]
## Search Terms
Method, Long, Returns

## Problem
The method return types are extremely long if you have an interface and are accessing it using square bracket notation.

Example Interface: https://github.com/ZackaryH8/tfl-api-wrapper/blob/master/lib/interfaces/tfl.ts
Example Usage: https://github.com/ZackaryH8/tfl-api-wrapper/blob/2d0b5ec/lib/stopPoint.ts#L34

Generated Documentation:
![image](https://user-images.githubusercontent.com/40175773/147628149-bcb08dd6-2d4a-46b4-b8eb-b9724f099afa.png)

## Suggested Solution
Possibly be able to hide returns or omit them completely when the docs are generated

**Comment by Gerrit0** [comment]
You can do this with a plugin fairly easily:

```js
const { Converter, ReflectionKind, UnknownType } = require("typedoc")

exports.load = function(app) {
  app.converter.on(Converter.EVENT_CREATE_SIGNATURE, (ctx, sig) => {
    // Without this will replace constructor signatures, get/set signatures, index signatures
    if (sig.kind === ReflectionKind.CallSignature) {
      sig.type = new UnknownType("whatever you want to show up")
    }
  })
}
```

I don't think this is something that should be included in TypeDoc itself. TypeDoc's goal is to provide documentation which accurately matches what's available from a library. Omitting information isn't a great way to do that...

FWIW, your input is **extremely unfriendly** to tools which try to accurately represent types. TypeScript will eagerly evaluate indexed access types if possible, so the type which TypeDoc receives when documenting the function is the object literal, not the indexed access type. Your output for this function would be much better if each literal in that interface was its own interface.

**Comment by ZackaryH8** [comment]
> You can do this with a plugin fairly easily:
> 
> ```js
> // typedoc --plugin path/to/this/file.js
> const { Converter, ReflectionKind, UnknownType } = require("typedoc")
> 
> exports.load = function(app) {
>   app.converter.on(Converter.EVENT_CREATE_SIGNATURE, (ctx, sig) => {
>     // Without this will replace constructor signatures, get/set signatures, index signatures
>     if (sig.kind === ReflectionKind.CallSignature) {
>       sig.type = new UnknownType("whatever you want to show up")
>     }
>   })
> }
> ```
> 
> I don't think this is something that should be included in TypeDoc itself. TypeDoc's goal is to provide documentation which accurately matches what's available from a library. Omitting information isn't a great way to do that...
> 
> FWIW, your input is **extremely unfriendly** to tools which try to accurately represent types. TypeScript will eagerly evaluate indexed access types if possible, so the type which TypeDoc receives when documenting the function is the object literal, not the indexed access type. Your output for this function would be much better if each literal in that interface was its own interface.

The plugin works flawlessly, unfortunately I don't have control on how the types are made for this as they are auto-generated from a swagger specification. Thanks!
