### ISSUE TITLE
Build fails if output json file already exists

### ISSUE THREAD

**Issue by yuschick** [TypeStrong/typedoc#1833]
## Search terms

json, overwrite, build error

## Expected Behavior

I have my typedoc options in my tsconfig file. So when I run `typedoc` I expect those options to be used and a file to be created. If the output file already exists, I expect it to be overwritten with the latest docs.

## Actual Behavior

When I run `typedoc` the first time, it works. When I run `typedoc` a second time with the output file now already created, the build fails.
![image](https://user-images.githubusercontent.com/563226/147936833-77f252ef-8cbb-4f11-bc36-363d32d0c6bb.png)

## Steps to reproduce the bug

**tsconfig**
````
{
"compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "jsx": "react",
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "declarationDir": "types",
    "emitDeclarationOnly": true
  },
  "typedocOptions": {
    "entryPoints": ["./src"],
    "name": "Pixel",
    "json": "typedoc.json",
    "excludeExternals": true,
    "includeVersion": true
  }}
````

Run `typedoc` to create `typedoc.json`. This will work.

Run `typedoc` a second time to get the errors in the terminal.

If I delete `typedoc.json` and try again, it works.

## Environment

TypeDoc 0.22.10
Using TypeScript 4.5.4 from /opt/homebrew/lib/node_modules/typescript/lib
Node: v14.18.2
MacOS Monterey 12.0.1 (21A559) M1

**Comment by Gerrit0** [comment]
`typedoc.json` is the default options filename. This looks like it's working as intended to me. I'd recommend changing `"json": "typedoc.json"` to a different file name that doesn't conflict with the config file name, or putting it in a different directory.

**Comment by yuschick** [comment]
Thanks for being so quick. That looks like that was the problem. When I renamed my output to something else, like `docs.json` then it worked as expected.

Thank you :)
