### ISSUE TITLE
New release of typedoc compatible with newer typescript?

### ISSUE THREAD

**Issue by RuXxar** [TypeStrong/typedoc#184]
Will a new version of typedoc compatible with newer versions of typescript be released soon?
We're having an issue with parsing the imports in the files we're trying to generate docs for that gets solved when using the current repository version of typedoc.

**Comment by johnman** [comment]
I was just checking and it looks like github has 0.4. but not npm, is it possible to publish?

**Comment by ThaNarie** [comment]
see #162

**Comment by Guria** [comment]
You can force use typescript installed in your project by running: `rm -rf node_modules/typedoc/node_modules/typescript`

**Comment by blakeembrey** [comment]
Closing with https://github.com/TypeStrong/typedoc/pull/204.
