### ISSUE TITLE
How can I set light theme to be the default theme?

### ISSUE THREAD

**Issue by zenoslin** [TypeStrong/typedoc#1840]
## Search terms

light theme

## Question

I want to always show then light theme when I open the doc. Not follow OS theme.

**Comment by Gerrit0** [comment]
If you change the theme using the dropdown in the footer, TypeDoc will save your preference and use that in the future for that site. Note that "site" might not be what you expect. Firefox at least treats each directory as a new "site" so won't save it. #1707.

If you want to force this globally for everyone... ok... you can do it with a plugin. I'd recommend against this. Users can change to light mode if they want, but sites really ought to respect their OS preference by default.

```js
// typedoc --plugin path/to/this/file.js
const { JSX } = require("typedoc");

exports.load = function load(app) {
    app.renderer.hooks.on("head.begin", () => {
        return JSX.createElement("script", null,
          JSX.createElement(JSX.Raw, { html: "localStorage.setItem('tsd-theme', localStorage.getItem('tsd-theme') || 'light')" }));
    });
}
```

**Comment by zenoslin** [comment]
Thinks.
