### ISSUE TITLE
Migrating from 0.19 to 0.22.9

### ISSUE THREAD

**Issue by XavierBncCoupal** [TypeStrong/typedoc#1841]
I migrated from 0.19 to 0.22, the main difference I pick up is the use of the `entryPointStrategy` option. Since I wanted the behavior to be the same one, i used the `expand` option. 

I removed some of the option that was removed in some release :

 ```json
{
  "stripInternal": "true",
  "mode": "modules",
  "ignoreCompilerErrors": false,
  "preserveConstEnums": true,
}	
```

Also, i changed my typescript version from 3.9 to 4.3, since 0.22 use typescript 4.0 and up.

Now, with all those change, when i run `typedoc` I get this error :

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
`

It look like running `typedoc` take now a lot more memory and time. If I enter only half the `entrypoint`, it work. It still take more time than the older version, and for half of the entry point.

I am wondering what im doing wrong in my migration of version. Did one of the option removed was important? Im trying to find what exactly they were doing, and I can find it anywhere.

If you have any lead for me, I will gladly take them! 

Also, I upgraded `NODE_OPTIONS=--max_old_space_size=16384 `and it just took longer to crash.

Thank you in advance

**Comment by Gerrit0** [comment]
`stripInternal` *might* be important. That's a TypeScript option, the equivalent one for TypeDoc is [`excludeInternal`](https://typedoc.org/guides/options/#excludeinternal)

This could definitely be a bug, but it's hard to say without a reproduction to look at.
