### ISSUE TITLE
Links to values and type aliases with the same name point to type aliases only

### ISSUE THREAD

**Issue by glebbash** [TypeStrong/typedoc#1845]
## Search terms

type aliases same name values link anchor

## Expected Behavior

Having this example TypeDoc generates documentation for value and type.
```ts
// index.ts
export const Value = 2;
export type Value = 2;
```

And then it should generate links to them which are different.
For example: `/docs/modules.html#Value.value` and `/docs/modules.html#Value.type`

## Actual Behavior

TypeDoc generates the same link for both which is `/docs/modules.html#Value.value` and thus points only to type alias which appears first on the page.

## Steps to reproduce the bug

1. Paste the contents of example into file called `index.ts`.
2. Run
```bash
typedoc index.ts
```

## Environment

-   Typedoc version: 0.22.10
-   TypeScript version: 4.5.4
-   Node.js version: 16.13.0
-   OS: Ubuntu 20.04 in WSL2

**Comment by Gerrit0** [comment]
I thought I fixed this like a year ago... that's annoying.
