### ISSUE TITLE
Update Google Analytics script

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1846]
TypeDoc 0.22.10 uses a version of a google analytics script which is no longer recommended by Google. It should be updated to the latest version, and `gaSite` removed since it is no longer required.

**Comment by donalffons** [comment]
I found this ticket while I was having trouble with GA and typedoc.
GA is configured and GA requests are issued by my typedoc page (with `collect?v=1` in the request URL). But none of them show up in my GA dashboard. After following [the doc on custom themes](https://github.dev/TypeStrong/typedoc/blob/ea16a7b4885abd9ee3ee7ef28ded0e4293f1ee7c/internal-docs/custom-themes.md), I was able to integrate my own analytics function. In my case using firebase. With that everything works fine.

```tsx
analytics = () => (
      <script type="module">
        <JSX.Raw html={`
          import { initializeApp } from "https://www.gstatic.com/firebasejs/9.6.10/firebase-app.js";
          import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.6.10/firebase-analytics.js";
        
          const firebaseConfig = {
            apiKey: "AIabcdefghijkl",
            authDomain: "blablabla.firebaseapp.com",
            projectId: "bla",
            storageBucket: "blablabla.appspot.com",
            messagingSenderId: "1234567",
            appId: "6:128937198273:web:295387298347",
            measurementId: "G-LLK234LKJ"
          };
        
          const app = initializeApp(firebaseConfig);
          getAnalytics(app);
        `} />
      </script>
    )
```

PS: Typedoc is fantastic. Thanks for all your great work!
