### ISSUE TITLE
Show nested methods in the sidebar

### ISSUE THREAD

**Issue by huzaifahj** [TypeStrong/typedoc#1848]
Can this be done? References #1815 

### Example code

```
export class Db {
    operations = {
        create: (id: string) => {
            console.log('Creating', id);
        },
        read: (id: string) => {
            console.log('Reading', id);
        },
        update: (id: string) => {
            console.log('Updating', id);
        },
        delete: {
            one: (id: string) => { console.log('Deleting one item:', id) },
            many: (ids: string[]) => { console.log('Deleting items:', ids) }
        }
    }
}
````

### Actual behaviour

![image](https://user-images.githubusercontent.com/52999758/149661996-3344b176-3188-48c1-8f7f-280f2b62b60b.png)

### Desired behaviour

The methods under `operations` show up in the sidebar.

**Comment by Gerrit0** [comment]
It could be done by overwriting the custom `navigation` helper in a custom theme ([typedoc's implementation](https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/default/partials/navigation.tsx))

I'd argue that this "nested" methods thing isn't really a great design in the first place... I'm not sure that I'd want to do this in the default theme.

**Comment by huzaifahj** [comment]
@Gerrit0 Once you have more methods under `operations` it becomes **not** a great design to omit the option to nest methods. Just becomes a massive block of `<li>` bullet points.

I do agree it shouldn't be the default, but could it be an option?

**Comment by Gerrit0** [comment]
Once you have that many methods, I'd argue your class is too big and should be split up ;)

I don't want to include this as a builtin option, at least in the short term. It might be a feature request which [typedoc-theme-hierarchy](https://www.npmjs.com/package/typedoc-theme-hierarchy) would entertain though.
