### ISSUE TITLE
Add classes from src/lib/output/components to root export

### ISSUE THREAD

**Issue by ejuda** [TypeStrong/typedoc#1850]
## Search Terms

plugins, root export, component

## Problem

Without `Component`, `RendererComponent` and `ContextAwareRendererComponent` available it can be tricky to extend or modify capabilities introduced by some code in `src/lib/converter/plugins` and `src/lib/output/plugins` (e.g. any plugin wanting to modify Markdown could listen to `MarkdownEvent.PARSE`, but it would not get access to the project reflection from the event, which could be required to implement the desired functionality).

## Suggested Solution

Adding the above classes to the root export would make it easier to write certain plugins.

**Comment by Gerrit0** [comment]
The `Component` hierarchy is going to go away, as soon as I have a few days to work on TypeDoc without interruptions. It is definitely not something I want to expose.

**Comment by ejuda** [comment]
I see, thanks! After the `Component` hierarchy goes away, will it still be possible to change the functionalities currently provided by code in `src/lib/converter/plugins` and `src/lib/output/plugins`? For instance, if I want to modify how search works, I can currently use `app.renderer.removeComponent('javascript-index');` to remove the inbuilt functionality and then listen to a renderer event to provide my own search index.

**Comment by Gerrit0** [comment]
There will be some way to do something like that - I suspect the API will be rather different, however.

**Comment by ejuda** [comment]
I see, thanks for the explanation. Looking forward to seeing the new API!
