### ISSUE TITLE
Cannot use typedoc for create-react-app project

### ISSUE THREAD

**Issue by alex-clear** [TypeStrong/typedoc#1856]
Hey guys
I have app create with create-react-app script

After install typed doc with npm install typedoc --save-dev cannot move to next steps in your installation guide

1. typedoc command is not recognized by zsh command line so all commands I nave to run with npx prefix
2. npx typedoc --version provides type doc version and used tyoescript version in output
3. However, cannot move froward this step since npx typedoc src/index.tsx provides error as in provided SS

<img width="772" alt="Screen Shot 2022-01-26 at 14 47 25" src="https://user-images.githubusercontent.com/97834715/151165753-52001be8-32c7-4113-b70e-1ede337074df.png">

I have standard file system, so I have no idea why I have error above

<img width="245" alt="Screen Shot 2022-01-26 at 14 42 33" src="https://user-images.githubusercontent.com/97834715/151165098-5eb38160-f32f-44f4-b555-368959c3c869.png">

My only guess that you lib does not supports .tsx files as entry point, but for react app no other entry point exists

Will appreciate for some help

**Comment by Gerrit0** [comment]
1. This seems expected to me, the installation guide mentions that you have to use `npx` when mentioning the local installation. This is the same as all other local npm packages which provide a binary (e.g. eslint, tsc, prettier)

2. 👍

3. TypeDoc does support TSX files. It looks to me what's going wrong here is that it isn't seeing your tsconfig.json file for some reason. If you help it with `--tsconfig <path/to/tsconfig.json>` it should work. TypeDoc ought to be discovering the tsconfig in your current directory automatically... does that file not have read permissions by any chance?

**Comment by alexberdichevsky** [comment]
@Gerrit0 Thanks for fast answer

In documentation for typedoc you are not using npx before the command (only in some places)
<img width="727" alt="Screen Shot 2022-01-26 at 15 48 15" src="https://user-images.githubusercontent.com/97834715/151174795-d3e0e0bd-9f85-4fa0-99a4-7d01066f7ddf.png">

as for >  --tsconfig <path/to/tsconfig.json> I tried it, but no luck

As for permissions for tsconfig.json, IMO, the looks good


<img width="257" alt="Screen Shot 2022-01-26 at 15 45 29" src="https://user-images.githubusercontent.com/97834715/151175034-d5a969d7-a743-4710-bc00-6b8feebe8f0a.png">

**Comment by Dayday10** [comment]
Please fill me in

**Comment by Dayday10** [comment]
This Alexander or what ever the name is is not me don't know what he's
doing in my account but my name is Shannon Day and I own this email

**Comment by Dayday10** [comment]
Fix it

**Comment by Gerrit0** [comment]
> In documentation for typedoc you are not using npx before the command (only in some places)

Yeah... the docs assume some level of familiarity with how `PATH` works with npm packages. This isn't unique to TypeDoc. ESBuild is way bigger and does the same thing.

> as for > --tsconfig <path/to/tsconfig.json> I tried it, but no luck

Hmm... just to be safe, maybe try passing `--showConfig`? That should give you full paths without trying to prettify any of the paths for display. Any more than this I think I will need a reproduction repo to look at though... not much I can do with what you've shown.

---

@Dayday10 I'm not sure I understand you. Did you accidentally watch this repo?

**Comment by Gerrit0** [comment]
> Yes

You can unwatch it by going to https://github.com/TypeStrong/typedoc and clicking the "Unwatch" button at the top right
