### ISSUE TITLE
Get rid of "External module "index.d""

### ISSUE THREAD

**Issue by Guria** [TypeStrong/typedoc#186]
I have prepared an `index.d.ts` for my js library. Typedoc prepared a great doc based on it, but actual documentation is too deep:`module-name / globals / External module "index.d"`.

You can see example here: http://cerebral.github.io/cerebral-module-router/index.html

I have tried to use `entryPoint`option but have not luck with it.

**Comment by Stevenic** [comment]
I have the same issue. Everything that it generates for index.d.ts is great but wish I could get rid of all the global stuff. entryPoint doesn't work.
