### ISSUE TITLE
Can we use TypeDoc to document a `.d.ts` file generated by TypeScript?

### ISSUE THREAD

**Issue by motla** [TypeStrong/typedoc#1860]
Hello,

It seems we can't use TypeDoc to document a .d.ts file generated by TypeScript.

I would like:
`main.js` > **TypeScript** > `main.d.ts` > **TypeDoc** > `main.html`

(providing the .js file directly as the TypeDoc entry point doesn't work well: module.exports is considered as a property, and classes does not appear).

So I tried:
###### tsconfig.json
```json
{
  "files": ["main.js"],
  "compilerOptions": {
    "allowJs": true,
    "declaration": true,
    "emitDeclarationOnly": true
  },
  "typedocOptions": {
    "entryPoints": ["main.d.ts"],
    "out": "docs"
  }
}
```

TypeScript generates the `main.d.ts` properly. Then TypeDoc fails with `Unable to locate entry point`, which is normal because `main.d.ts` has not been included.

But if I add it in `files` or `include`, TypeScript fails with `Cannot write file 'main.d.ts' because it would overwrite input file.`

Can we work around this?

**Comment by Gerrit0** [comment]
I'd recommend making a tsconfig.docs.json and pointing typedoc at that instead with `--tsconfig`

**Comment by motla** [comment]
Indeed. Thanks a lot.

**Comment by aaclayton** [comment]
Sorry for being a bit dense here, but @motla could I trouble you to post an example of the working configuration? I tried to follow this same issue myself and was not successful.

**Comment by motla** [comment]
@aaclayton
If I remember correctly, you need to create two files:
- **tsconfig.json** to convert your javascript code to a .d.ts file
```json
{
  "files": ["main.js"],
  "compilerOptions": {
    "allowJs": true,
    "declaration": true,
    "emitDeclarationOnly": true
  }
}
```
(follow https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html)
- **tsconfig.docs.json** to convert your .d.ts file to HTML documentation
```json
{
  "files": ["main.d.ts"],
  "typedocOptions": {
    "entryPoints": ["main.d.ts"],
    "out": "docs"
  }
}
```
Then you call `typescript` to execute the first one and `typedoc --tsconfig tsconfig.docs.json` for the second one.
