### ISSUE TITLE
question: types and enums only exports?

### ISSUE THREAD

**Issue by RealShadowNova** [TypeStrong/typedoc#1861]
## Question

Does `typedoc` have any way of exporting types and enums with out accessing Node.js native packages (e.g. `process`)? I'm currently trying to use the exported interfaces and enums from `typedoc` in a `tsx` environment. Every time I import something like `ReflectionKind` I receive errors in the browser console saying `process is not defined`. This is a genuine aggravation because I'm only importing previously generated `json` api, but have no types for them because I cannot import them.

EDIT: I just realized `typedoc` exports `JSONOutput`, but still doesn't resolve my issue with enums.

**Comment by Gerrit0** [comment]
Currently not possible unless you have some really crazy smart tree shaker (I don't think any exist). TypeDoc wasn't intended to be run in a browser environment, so there is a *lot* of code which assumes it has access to Node globals.

I'm not opposed to creating a second export (`typedoc/???`) which only exports the bits of TypeDoc which are relevant when dealing with the JSON output. I think the only relevant enum is `ReflectionKind`, but in the short term, just grabbing the enum from [kind.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/reflections/kind.ts#L4) and including that in your project is pretty safe. Any changes to it will be mentioned in the release notes, and I don't predict any major changes to it in the near future (only possible one I'm tracking right now is removing `Event`)

**Comment by RealShadowNova** [comment]
> Currently not possible unless you have some really crazy smart tree shaker (I don't think any exist). TypeDoc wasn't intended to be run in a browser environment, so there is a _lot_ of code which assumes it has access to Node globals.
> 
> I'm not opposed to creating a second export (`typedoc/???`) which only exports the bits of TypeDoc which are relevant when dealing with the JSON output. I think the only relevant enum is `ReflectionKind`, but in the short term, just grabbing the enum from [kind.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/reflections/kind.ts#L4) and including that in your project is pretty safe. Any changes to it will be mentioned in the release notes, and I don't predict any major changes to it in the near future (only possible one I'm tracking right now is removing `Event`)

Yeah, I'm currently just using my own `ReflectionKind` enum I grabbed from the source code. It works fine for me, but wanted to make this an issue for anyone else that may run into this issue in the future. Thank you!

**Comment by stazz** [comment]
@Gerrit0 Any plans on adding the export entry to `kind.ts` into `package.json`'s `"exports"` field? Right now e.g. Vite gives the following error:

```
[plugin:vite:import-analysis] Missing "./dist/lib/models/reflections/kind" specifier in "typedoc" package
```

**Comment by Gerrit0** [comment]
Absolutely no plans for that, I want the flexibility of being able to move files around, or bundle TypeDoc's source code for release at some point.

I'm not completely opposed to making a browser/bundler-friendly entrypoint, but haven't needed it myself, so haven't stopped to consider what should be in it. Feel free to open a new issue with a proposal
