### ISSUE TITLE
Include comments in JSON output

### ISSUE THREAD

**Issue by benmccann** [TypeStrong/typedoc#1869]
## Search Terms

comments json

## Problem

I'm using the `--json` option to get JSON output. I'd then live to build a Svelte component to display the types for the SvelteKit docs. However, the comments for our types don't seem to be in the JSON output.

I see a documentation page about doc comments (https://typedoc.org/guides/doccomments/), so I would expect that Typedoc is doing something with them, but maybe it's only being included in the HTML output and not the JSON output?

## Suggested Solution

Parse the `.d.ts` files and include the comments in the output when `--json` option is used

**Comment by Gerrit0** [comment]
Any comments output in the HTML output should also be included in the JSON output - can you provide a reproduction?

**Comment by benmccann** [comment]
Sure. Here's a reproduction. Note that it requires `pnpm`
```
git clone git@github.com:benmccann/kit.git
cd kit
git checkout typedoc-json
cd packages/kit
pnpm install && pnpm build
pnpx typedoc
```
Open `../../documentation/types.json` and see that it doesn't have any of the comments that are in the `types` directory

**Comment by Gerrit0** [comment]
Seems to be working correctly to me... TypeDoc only documents what you export. (or if a global file, what's declared in that file). If I look at `SSRManifest`, I see the comment there, same for `Builder.createEntries`.

**Comment by benmccann** [comment]
Ah, I was comparing to another approach someone was trying on another branch and didn't realize they had edited the comments. Thank you for the investigation. Sorry for the false report
