### ISSUE TITLE
Generate pages corresponding to Markdown files in directories

### ISSUE THREAD

**Issue by DanielFlaum** [TypeStrong/typedoc#1870]
TypeDoc currently includes the content of `README.md` in the generated `index.html`. It would be useful if `README.md`s in subdirectories also caused corresponding pages to be generated. Doing so would add a way for directories themselves to be documented, creating a place to discuss project organization or other things that apply to more than a single file, as well as a place to document non-TypeScript files.

This should probably be labelled enhancement and plugin idea.

**Comment by Gerrit0** [comment]
This is something I'd like to include in TypeDoc itself, but will probably be a part of the guides work that's planned for 0.24, probably won't happen for a while...

**Comment by cadavre** [comment]
Another, maybe simpler way, would be to just list a docs files with their path and create static docs from it, in a separate menu. Just to wrap existing docs into code-generated one.

**Comment by johnameyer** [comment]
I see the Guides project board is now closed - do there happen to be plans for this idea now?

**Comment by Voo2** [comment]
I would go one step further and say that generally all md files should be taken into account.

### Suggested Solution
Similar to what [Compodoc](https://compodoc.app/) does, it would be extremely helpful if typedoc would consider md (Markdown) files that are in the same directory as the class and have the same filename. These MD files could be displayed in a tab from the displayed class or linked quite high up in the document.

### Example

- _startup-config.service.ts_
- _startup-config.service.md_ (this is the md file that belongs to the file above and should be integrated into its documentation)

**Comment by LeaVerou** [comment]
Another vote for this. We have a monorepo-like structure with components living in their own directories, with their own READMEs. It would be nice if those READMEs were also picked up by typedoc.

**Comment by Gerrit0** [comment]
Fixed with TypeDoc 0.26, which is releasing 2024/06/21
