### ISSUE TITLE
`--requiredToBeDocumented` options not validated correctly

### ISSUE THREAD

**Issue by williamkbentley** [TypeStrong/typedoc#1872]
## Search terms

require
docs
warning
requiredToBeDocumented

## Expected Behavior

Validate provided types array

## Actual Behavior

Incorrect error reported

## Steps to reproduce the bug

Attempt to run TypeDoc with `--validation.notDocumented` and `--requiredToBeDocumented Enum`

Results in:
`Error: 'Enum' is an invalid value for 'requiredToBeDocumented'. Must be one of: Project, Module, Namespace, Enum, EnumMember, Variable, Function, Class, Interface, Constructor, Property, Method, CallSignature, IndexSignature, ConstructorSignature, Parameter, TypeLiteral, TypeParameter, Accessor, GetSignature, SetSignature, ObjectLiteral, TypeAlias, Event, Reference`

See: #1819 
[src/lib/utils/options/sources/typedoc.ts](https://github.com/TypeStrong/typedoc/pull/1819/files#diff-bf26d4bebc95d47c1a456e4f75adef90af7c5860f38327f789bf8c16dc4aa632R357)

## Environment

-   Typedoc version: 0.22.12
-   TypeScript version: ~4.4.0
-   Node.js version: 14.15.4
-   OS: Win10

**Comment by Gerrit0** [comment]
D'oh, that's a problem...
