### ISSUE TITLE
Failure to correctly link sources when building on vercel

### ISSUE THREAD

**Issue by ThisIsMissEm** [TypeStrong/typedoc#1873]
## Search terms

vercel, source links, repository, git, markdown

## Expected Behavior

When building on my local machine and building on vercel, I expect that the documentation output will be consistent between both if both are built from the same source repository. As such, I expect the source links for methods and interfaces to work on vercel reliably (they do not)

## Actual Behavior

Source code links are not linked on vercel (and sometimes in docker containers too)

## Steps to reproduce the bug

You can see this over at: https://github.com/inrupt/solid-client-js/pull/1481/ and https://solid-client-js-git-feature-improve-docs-generation-inrupt.vercel.app/modules/acl_acl.html (note: the vercel link may break in the future after the PR is merged)

The issue comes from how Typedoc tries to infer where the "source" is, which is by trying to look at the git remotes:
- https://github.com/TypeStrong/typedoc/blob/1e0e38cf326e36645718efae15444458fb9e8486/src/lib/converter/plugins/SourceLinkPlugin.ts#L272-L276
- https://github.com/TypeStrong/typedoc/blob/1e0e38cf326e36645718efae15444458fb9e8486/src/lib/converter/plugins/SourceLinkPlugin.ts#L178-L184

On vercel, the two git operations seem to not return back a URL for the "origin" remote (and in testing, I wasn't able to get `git remote -v` to actually output anything to the build log).

## Environment

-   Typedoc version: 0.22.12 (with typedoc-plugin-markdown@^3.11.14)
-   TypeScript version: 4.5.5
-   Node.js version: 14.x
-   OS: Unknown (whatever vercel uses)

**Comment by ThisIsMissEm** [comment]
I think the solution which could work is to just allow for a `repositoryUrl` option and use that for the source code links, rather than relying on `git`

**Comment by Gerrit0** [comment]
Hmmm... does vercel have any git info (particularly files in repo)? I worry that supplying a repositoryUrl would make it easy to generate docs which have broken links pointing to files in the repository that don't exist.

**Comment by ThisIsMissEm** [comment]
> Hmmm... does vercel have any git info (particularly files in repo)? I worry that supplying a repositoryUrl would make it easy to generate docs which have broken links pointing to files in the repository that don't exist.

In testing, I tried adding a `git remote -v` to the build command, and got nothing back in the output from that. As for broken links, an option if using a`repositoryUrl` would be to make a request and check for 200 status — though that'd be quiet slow.

**Comment by Gerrit0** [comment]
Yeah, too slow, also making web requests is also not something I want to include in TypeDoc. Your data should never leave your system.

I think this use case is probably going to be best served by a custom plugin. I haven't been able to come up with a good generic solution that's suitable for inclusion in TypeDoc.

```js
const td = require("typedoc");
const { join } = require("path");

exports.load = function (app) {
    const repo = new FakeRepository(
        join(__dirname, "..").replace(/\\/g, "/"),
        "https://github.com/you/project",
        app.options.getValue("gitRevision")
    );

    app.converter.getComponent("source-link").repositories[repo.path.toLowerCase()] = repo;
};

class FakeRepository {
    constructor(path, repo, revision) {
        this.path = path;
        this.repo = repo;
        this.revision = revision || "master";
        this.type = td.RepositoryType.GitHub;
    }

    getURL(file) {
        return [this.repo, "blob", this.revision, file.substring(this.path.length + 1)].join("/");
    }
}
```

**Comment by Gerrit0** [comment]
Not that I've been able to come up with, I'm being really picky about false positives.

https://www.npmjs.com/package/nlfurniss-typedoc-plugin-sourcefile-url might be of interest.
