### ISSUE TITLE
Clearly indicate abstract classes

### ISSUE THREAD

**Issue by ejuda** [TypeStrong/typedoc#1874]
## Search Terms

abstract, class, constructor

## Problems

Consider the following class:

```ts
export abstract class SomeClass {
    abstract abstractProp: boolean;
    abstract abstractMethod(): void;
}
```
<ol>
<li>While TypeDoc does indicate which methods and properties are abstract:

![image](https://user-images.githubusercontent.com/26031740/155533024-623ec2d1-58d7-4b29-99bd-2a918faa5c61.png)

 it does not provide any indication on whether the class itself is abstract:

![image](https://user-images.githubusercontent.com/26031740/155533775-45a782dc-cfbe-49f2-8da0-5c1a5b1e52f1.png)

 This means that the users cannot easily establish whether the class they are looking at is abstract - they have to rely on abstract methods and properties being present.</li>

<li>Secondly, even if a constructor of an abstract class may be not explictly defined (as in the example above), TypeDoc will still add the constructor to the documentation page. While this is useful for concrete classes (indicating the class has a default constructor), it is potentially misleading for abstract classes, as they cannot be instantiated directly.</li>
</ol>

## Suggested Solutions

<ol>
<li>It would be easier to spot abstract classes if the _Abstract_ badge was present prominently near the class name, for example in the header:

![image](https://user-images.githubusercontent.com/26031740/155533840-46bedaf9-4e9f-478d-95d5-727147e44146.png)

<li>If the constructor of an abstract class has not been explicitly defined, TypeDoc should not add an empty constructor, to further emphasise that the class cannot be instantiated directly. If the constructor has been defined, it should be preserved, as it might e.g. be accompanied by a docstring.</li>
</ol>

**Comment by Gerrit0** [comment]
1. Is definitely a good idea, and something we should do.
2. I think is better suited for a plugin. Constructors and their parameters are still useful to know about if the user is inheriting from this class.

```js
const td = require("typedoc");

/** @param {td.Application} */
exports.load = function(app) {
  app.converter.on(td.Converter.EVENT_RESOLVE, (context, reflection) => {
    if (reflection.kindOf(td.ReflectionKind.Class) && reflection.flags.isAbstract) {
       const ctor = reflection.getChildByName("constructor")
      // could check reflection.sources to see if it is associated with any user written code
      if (ctor) context.project.removeReflection(ctor);
    }
  })
}
```
