### ISSUE TITLE
Support TypeScript 4.6

### ISSUE THREAD

**Issue by sstone1** [TypeStrong/typedoc#1877]
## Search Terms

typescript 4.6

## Problem

typescript 4.6 was released last night, but this module is not compatible with it as 4.6.x is not in the list of compatible versions:

```
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x || 4.5.x" from typedoc@0.22.12
```

## Suggested Solution

please add support for typescript 4.6!

**Comment by Gerrit0** [comment]
I should get to this this weekend :)

**Comment by Gerrit0** [comment]
Support released in [v0.22.13](https://github.com/TypeStrong/typedoc/releases/tag/v0.22.13), no changes were necessary on TypeDoc's part besides marking it as supported, so if you're stuck on an old version it should still work.

**Comment by Lazerbeak12345** [comment]
typedoc version 0.22.13 still gives the warning on typescript 4.6.0.

Package.json snippet:

```json
{
  ...
  "devDependencies": {
    ...
    "typedoc": "~0.22.13",
    ...
    "typescript": "<=4.6.0"
  },
  ...
}
```

Log message:
```txt
=============

WARNING: You are currently running a version of TypeScript which is not offici
ally supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.5

Please only submit bug reports when using the officially supported version.

=============
```

Also relevant:

```
🐟 ❯ yarn typedoc --version
yarn run v1.22.17
$ /.../node_modules/.bin/typedoc --version
Info: Loaded plugin typedoc-plugin-mdn-links

TypeDoc 0.22.13
Using TypeScript 4.5.5 from ./node_modules/typescript/lib

Done in 1.01s.
```

**Comment by Lazerbeak12345** [comment]
Nevermind - there were multiple packages with a similar error. You can ignore my previous post.
