### ISSUE TITLE
return type () => Type is rendered as two separate returns

### ISSUE THREAD

**Issue by Necroskillz** [TypeStrong/typedoc#188]
Doc:

```
/**
 * @returns returns doc
 */
export function fn(): () => Promise<any> {
}
```

Output:

![image](https://cloud.githubusercontent.com/assets/346477/12790607/6208c8cc-caa3-11e5-9564-ba7453cc2e45.png)

It's a bit confusing.

**Comment by Gerrit0** [comment]
While somewhat confusing at first, this is expected behavior. Newer versions render this in a way that at least makes it clear what's going on:

![image](https://user-images.githubusercontent.com/19329837/103249915-ae81d680-492e-11eb-87bd-5bdf9688722d.png)
