### ISSUE TITLE
Docstrings of enum-like object members are missing

### ISSUE THREAD

**Issue by ejuda** [TypeStrong/typedoc#1880]
## Search terms

enum, enum-like object

## Expected Behavior

Consider the following code:

```ts
// index.d.ts

/**
 * This enumeration defines some values.
 *
 * @enum
 */
export declare const SomeEnum: {
    /**
     * This is the auto property.
     */
    readonly AUTO: "auto";
    /**
     * This is the manual property.
     */
    readonly MANUAL: "manual";
};
```

Thanks to the PR closing issue [#1740](https://github.com/TypeStrong/typedoc/issues/1740), TypeDoc correctly recognises this object as an enum. Both the docstring of the enum-like object and the docstrings of its members should also be preserved.

## Actual Behavior

While the docstring of the enum-like object are preserved, those of its members are not:

![image](https://user-images.githubusercontent.com/26031740/157270468-5bedef00-b6b4-42c6-90fb-115b756438e5.png)

The docstrings for `AUTO` and `MANUAL` members (_This is the auto property_ and _This is the manual property_ respectively) are missing from the page.

## Steps to reproduce the bug

1. Clone [the reproduction repository](https://github.com/ejuda/typedoc-enum-params-repro).
2. `npm ci`
3. `npm run docs`
4. This will generate documentation into `docs` directory.

## Environment

-   Typedoc version: 0.22.13
-   TypeScript version: 4.6.2
-   Node.js version: 16.14.0
-   OS: Windows 10

**Comment by ejuda** [comment]
I think this has been mentioned in [a comment](https://github.com/TypeStrong/typedoc/issues/1740#issuecomment-998755307) on #1740, but I have not seen any issue with the follow-up on this.

**Comment by Gerrit0** [comment]
I *think* this should be an easy fix, just needs an update to https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/converter.ts#L183

**Comment by michkot** [comment]
Thanks a lot @ejuda, I ultimately didn't make the time to report it properly!
