### ISSUE TITLE
Random search results are showing when the query is empty

### ISSUE THREAD

**Issue by ychan167** [TypeStrong/typedoc#1881]
## Search terms
search, search results 

## Expected Behavior
When the search text is empty/ cleared, it is expected that there are no search results showing.

## Actual Behavior
There are random search results when the search text is empty.
![search_actual](https://user-images.githubusercontent.com/101419436/157914173-c3310ade-f32c-4d1d-8054-1dcf94fef48b.gif)

## Steps to reproduce the bug
1. Go to [example doc](https://typedoc.org/example/index.html)
2. Click search
3. Input some search text
4. Remove the search text

## Environment
- Typedoc version: 0.22.13
- TypeScript version: 4.6.2
- Node.js version: 14.18.0
- OS: Windows 10

**Comment by Gerrit0** [comment]
Resolved by #1882
