### ISSUE TITLE
Values of a typed const are not documented

### ISSUE THREAD

**Issue by kdorion** [TypeStrong/typedoc#1883]
## Search terms
variable, as const, typed

## Expected Behavior
I would expect to see values of a typed variable, just like you see values of an untyped one. 

## Actual Behavior
Values are not visible in the documentation nor available when using the JSON output. 

## Steps to reproduce the bug
https://codesandbox.io/s/typedoc-test-forked-pty3b6?file=/src/index.ts

FIRST const is displaying its values (prop: "first")
SECOND const is not displaying its values

This might be as intended but I couldn't find anything about it. 

## Environment

-   Typedoc version: 22.13
-   TypeScript version: 4.6.2
-   Node.js version: v14.18.1
-   OS: Mac, Linux, Any?

**Comment by Gerrit0** [comment]
This is working as expected. What TypeDoc is displaying is not the value, but the type. You can prove this with:

```ts
export const THIRD: { prop: "third" } = null as any
```

When you explicitly defined the type of the variable with another name, TypeDoc noticed this and will provide a link to the type. It doesn't "expand" the properties in every instance of the type, similarly to how if you hover over the variable, intellisense will display the declared type.

![image](https://user-images.githubusercontent.com/19329837/158502216-8153525f-bf88-4a85-b194-c89e69cf5dc3.png)

**Comment by kdorion** [comment]
Well that makes perfect sense and I should have realized that by myself. Sorry for bothering!

**Comment by kdorion** [comment]
Actually, is there any way I could have the values of a typed const in the JSON output?

**Comment by Gerrit0** [comment]
You could write a plugin to extract the information you care about:

```ts
const td = require('typedoc');

/** @type {td.Application} */
exports.load = function(app) {
  app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, (_context, reflection, node) => {
    if (!node) return;

    // node will be the ts.Node for the symbol. I recommend putting the code you want to mess with
    // into https://ts-ast-viewer.com/
    reflection.customStuff = node.getText();
  });

  // So that it shows up in JSON output
  app.serializer.addSerializer({
    serializeGroup(obj) { return obj instanceof td.Reflection },
    supports(obj) { return obj instanceof td.DeclarationReflection },
    toObject(refl, obj) {
      obj.customStuff = refl.customStuff;
      return obj;
    }
  });
}
