### ISSUE TITLE
It's weird, I got (projectReflection instanceof Reflection) === false?

### ISSUE THREAD

**Issue by shrinktofit** [TypeStrong/typedoc#1884]
## Search terms

serializer plugin

## Expected Behavior

`projectReflection instanceof Reflection` to be true.

## Actual Behavior

![image](https://user-images.githubusercontent.com/28807867/158509131-f9f8d614-44eb-4208-9a25-6e2107049753.png)

![image](https://user-images.githubusercontent.com/28807867/158509160-6508f235-bb7c-4e0e-a761-f6390426b9bc.png)

![image](https://user-images.githubusercontent.com/28807867/158509176-7b0620c9-b70a-4733-81af-e631dbc37f34.png)

## Environment

-   Typedoc version: latest
-   TypeScript version: 4.6
-   Node.js version: 16.8.0
-   OS: Windows

**Comment by Gerrit0** [comment]
This is unactionable without a reproduction. However, I suspect the root cause is that you have multiple installations of TypeDoc.
