### ISSUE TITLE
Typedoc filenames consists of path

### ISSUE THREAD

**Issue by kayshwetha** [TypeStrong/typedoc#1885]
typedoc used with typedoc-plugin-markdown plugin generates long file names with path. How can we exclude the path names and get only class names in output filenames?
I have used expand mode in entrypoint strategy.

**Comment by Gerrit0** [comment]
Paths are created according to the fully qualified name for files, there is a plugin, [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules) which might serve your use case

**Comment by kayshwetha** [comment]
Thanks @Gerrit0, it served my case close to what I was looking for. :)
