### ISSUE TITLE
Comments in re-export erases documentation

### ISSUE THREAD

**Issue by DavidPeicho** [TypeStrong/typedoc#1886]
## Search terms

missing, erase, comments

## Expected Behavior

Consider the following file:

**query.ts**
```ts
/*
 * This query is awesome!
 *
 * @category Query
 */
export class Query { }
```

**index.ts**

```ts

/**
 * This comment will erase the Query doc, ho snap! :(
 */

export * from './query.ts'
```

The documentation that will be generated for the `Query` class should be ` This query is awesome!`

## Actual Behavior

The documentation that appears is the one from the comment before the re-export: `This comment will erase the Query doc, ho snap! :(`

## Steps to reproduce the bug

It's easy to reproduce with the exact two same files I gave in the [Expected Behavior](#expected-behavior) section.

## Environment

-   Typedoc version: 0.22.13
-   TypeScript version: 4.6.2
-   Node.js version: 17.2.0
-   OS: Windows WSL

**Comment by DavidPeicho** [comment]
I am not 100% sure it's a bug, but it's something I discovered today. I agree I maybe shouldn't use those type of comments before my re-export, but it still seems to be an odd behavior to me?

**Comment by Gerrit0** [comment]
This is intentional, but apparently never got added to the docs, and only shows up in the change log if you know what to search for: https://github.com/TypeStrong/typedoc/issues/1504
