### ISSUE TITLE
excludeNotDocumented is not documented

### ISSUE THREAD

**Issue by Primajin** [TypeStrong/typedoc#1888]
## Search terms
excludeNotDocumented missing docs documentation

## Expected Behavior

excludeNotDocumented should be listed and explained as available option in https://typedoc.org/guides/options/#input-options

## Actual Behavior
excludeNotDocumented is not documented (I know this sounds very meta)

## Steps to reproduce the bug
Visit https://typedoc.org/guides/options/#input-options

![image](https://user-images.githubusercontent.com/1742115/158777563-ec4d358b-f6eb-41e9-8629-7092c28b1475.png)
![image](https://user-images.githubusercontent.com/1742115/158777748-7bcef033-f5a8-4e61-ba3c-db870d475018.png)

## Environment

n/a

**Comment by Gerrit0** [comment]
Also missing: `requiredToBeDocumented`

**Comment by Gerrit0** [comment]
https://typedoc.org/guides/options/#excludenotdocumented

https://typedoc.org/guides/options/#requiredtobedocumented
