### ISSUE TITLE
TypeDoc: Memory consumption on large declaration files

### ISSUE THREAD

**Issue by jvilk** [TypeStrong/typedoc#189]
I suspect I am the only person with this issue!

Background: I'm working on [a JVM in JavaScript](https://github.com/plasma-umass/doppio) which maps JVM objects to TypeScript objects. It generates [a very large declaration file including declarations for almost all classes in the Java Class Library.](https://gist.github.com/jvilk/727f7b09a42f1d6c35bf)

Using `--verbose`, TypeDoc seems to choke in the `Resolving...` phase. I let it run for over 10 minutes with and without the `verbose` flag before killing it. It seems to resolve only a handful of things every few seconds.

By passing the `--trace-gc` flag to Node, I could tell that TypeDoc is nearly filling Node.js's heap, which apparently has a fixed maximum size of ~1.4GB. TypeDoc is using 1.2GB.

If you want to reproduce this issue, do the following:
- [Clone and build DoppioJVM](https://github.com/plasma-umass/doppio). The instructions are on that page, and aren't too involved.
- Run the following typedoc command from the repo folder (add `--verbose` to see the issue firsthand):

```
typedoc --out docs/ --externalPattern node_modules --includeDeclarations --mode modules --module commonjs --target ES3 includes/JVMTypes.d.ts src/
```

What objects do you suspect are taking up so much heap space?

**Comment by anthonyjlmorel** [comment]
I would love to know the status of this as I am running into this too.

**Comment by Gerrit0** [comment]
Closing in favor of #835. TypeDoc can still use a lot of memory on large projects, but it does successfully process the TypeScript repo, which is (I believe) a comparably large project.
