### ISSUE TITLE
Using multiple entryPoints with entryPointStrategy set to "expand" fails to build if out folder exists.

### ISSUE THREAD

**Issue by dcallus** [TypeStrong/typedoc#1893]
## Search terms

There is currently no fool-proof way to use an entryPointStrategy of "expand" for multiple folders. It can be done, but if an output folder already exists, the build fails.

## Expected Behavior
If you use a typedoc.json file such as
{
    "entryPointStrategy": "expand",
    "entryPoints": ["./tests", "./utils"],
    "out": "docs",
}
I would expect this to build documentation from the two listed folders.

## Actual Behavior
It only works if an output folder does not exist. You must delete the folder before re-running otherwise there the build fails. Oddly, this happens even if the folder has been renamed. It must be deleting before re-running options command.

## Steps to reproduce the bug
1. use a typedoc.json file like this:
{
    "entryPointStrategy": "expand",
    "entryPoints": ["./tests", "./utils"],
    "out": "docs",
}
2. run: npx typedoc --options ./typedoc.json
3. run again: npx typedoc --options ./typedoc.json

## Environment
-   Typedoc version: 0.22.13
-   TypeScript version: 4.5.5
-   Node.js version: 16.13.0
-   OS: Windows 10 Pro

**Comment by Gerrit0** [comment]
I can't seem to reproduce this. I set up a project with the specified structure, and ran TypeDoc several times without ever deleting the output folder. It succeeded in generating documentation each time.

**Comment by dcallus** [comment]
> I can't seem to reproduce this. I set up a project with the specified structure, and ran TypeDoc several times without ever deleting the output folder. It succeeded in generating documentation each time.

I'll try and make a minimal repo as soon as I can :)

Thanks

**Comment by dcallus** [comment]
Okay. I recently realised typescript builds were also failing to build with the docs folder present. The issue is actually because I need to add the output "docs" folder to my excluded list in my tsconfig.json otherwise it tries to build from the js files in the docs folder (which are present in docs/assets due to plugins).

**Comment by Gerrit0** [comment]
Well, yep, that'll do it! Glad you got it figured out.
