### ISSUE TITLE
@callback descriptions are missing

### ISSUE THREAD

**Issue by jackens** [TypeStrong/typedoc#1896]
## Search terms

@callback

## Expected Behavior

@callback descriptions are not missing

## Actual Behavior

@callback descriptions are missing

## Steps to reproduce the bug

`package.json`:

```json
{
  "devDependencies": {
    "typedoc": "0.22.13",
    "typescript": "4.6.3"
  },
  "name": "issue",
  "type": "module"
}
```

`typedoc.json`:

```json
{
  "entryPointStrategy": "expand",
  "entryPoints": [
    "src"
  ],
  "out": "_doc",
  "readme": "none"
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "declaration": true
  },
  "include": [
    "src/**/*.js"
  ]
}
```

`src/file.js`:

```js
/**
 * Some module.
 *
 * @module
 */

/**
 * This description is not in the documentation!
 *
 * @callback Type1 This description is not in the documentation!
 *
 * @param {number} one This description is not in the documentation!
 * @param {number} two This description is not in the documentation!
 *
 * @returns {number} This description is not in the documentation!
 */

/**
 * @typedef {{(one: number, two: number) => number}} Type2
 *
 * Some type 2.
 */

export const answer = 42
```

## Environment

-   Typedoc version: conf. `package.json`
-   TypeScript version: conf. `package.json`
-   Node.js version: v14.17.4
-   OS: MacOS

**Comment by Gerrit0** [comment]
Oh JSDoc how I despise you... this one I'm probably going to put off looking at until 0.23 since comment discovery was completely reworked and it might already work there.

**Comment by Gerrit0** [comment]
Yep, works as expected in 0.23 with no changes necessary.

![image](https://user-images.githubusercontent.com/19329837/163679240-f9287bc1-96c0-4416-8407-58dcebeeddfb.png)
![image](https://user-images.githubusercontent.com/19329837/163679246-826b7697-2d82-4e3f-be8e-859bb6a21e40.png)

```ts
/**
 * Before tag
 * @callback Type1 On Tag
 * @param {number} one Param 1
 * @param {number} two Param 2
 * @returns {number} Ret
 */

/**
 * Before tag
 * @typedef {{(one: number, two: number) => number}} Type2
 *
 * Some type 2.
 */
```

Note that text before the tag is dropped - this is because TypeScript technically supports multiple `@typedef` and `@callback` tags in a single comment.
