### ISSUE TITLE
Cannot link local files/images via markdown image links

### ISSUE THREAD

**Issue by WHenderson** [TypeStrong/typedoc#1899]
## Search terms

Markdown, Local files, Relative path

## Expected Behavior

When encountering markdown such as

`![debounce](diagrams/debounce.drawio.svg)`

Typedoc should link the referenced file relative to the source of the markdown being parsed

## Actual Behavior

TypeDoc will insert the expected `<img>` tag, but does not adjust the href and does not include the linked file in the assets folder. This results in broken images.

## Steps to reproduce the bug

1. Create a typedoc project
2. Add an image to the project
3. Add a markdown image tag `![image name](local/image/reference)`
4. Compile with typedoc
5. Note that the image is broken

Having traced through the code, it would also be helpful if the `MarkdownEvent` was given context information such that extensions could understand what the given markdown relates to and what file it was sourced from.

**Comment by stuft2** [comment]
Ran into this today as well except I'm trying to link to other markdown files by their relative path.

**Comment by kwiniarski97** [comment]
Is there some workaround available? Only think I think of is to manually copy images to assets folder, don't know though if that's best way.

**Comment by Gerrit0** [comment]
Fixed with TypeDoc 0.26, which is releasing 2024/06/21
