### ISSUE TITLE
How to categorise functions as seperate modules

### ISSUE THREAD

**Issue by kayshwetha** [TypeStrong/typedoc#1900]
I have public functions which are used by classes directly. But these functions appear in the documentation, in the modules.md page which is the index page. How can I seperate all these functions to a seperate file? When I add @category the functions are categorized to the name I give, but are not seperated from index page.

**Comment by Gerrit0** [comment]
TypeDoc structures your documentation according to the structure of the project itself - if you give TypeDoc an entry point separate from your root index that exports all the functions, it will document what is exported from that entrypoint in its own module.

**Comment by kayshwetha** [comment]
But the functions lie in seperate files, and they are generated in the Index page. Ideally no documentation, should generate inside Index page isnt it?

**Comment by kayshwetha** [comment]
I wanted to add a category for functions and it should appear as a folder along with other categories. Would that be possible?

**Comment by Gerrit0** [comment]
The `@category` tag is not able to do what you're asking. It's a per-page categorization feature. In TypeDoc 0.23 (beta this weekend, probably), all members are pushed out into their own files, so they won't show up on the index page anymore except as links (might make this configurable).

Today, you can achieve this with something like this:

```ts
// functions.ts
export { someFn } from "./foo"
export { someOtherFn } from "./bar"

// classes.ts
export { someClass } from "./foo"
export { someOtherClass } from "./bar"
```

```bash
$ typedoc ./functions.ts ./classes.ts
```

**Comment by kayshwetha** [comment]
I tried the beta version 0.23 and the public functions still appear in the overview file which is - modules.md. I am using plugins 
typedoc-github-wiki-theme
typedoc-plugin-markdown
typedoc-plugin-merge-modules

Could you suggest something to fix this?

**Comment by Gerrit0** [comment]
The theme is what controls wherever or not different reflections get their own document. It looks like typedoc-plugin-markdown has an option that changes how that works:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/f5a82913f14181f3fa59e5012a105461e201ccd4/packages/typedoc-plugin-markdown/src/theme.ts#L339

**Comment by kayshwetha** [comment]
In that case function should have its own directory isn't it? But in my case, functions appear in the modules.md file. Is this a bug? Or is there a workaround? Could you let me know please.

**Comment by Gerrit0** [comment]
*an option* implies you have to turn it on. Without seeing your configuration, I can only presume you haven't turned it on.

**Comment by kayshwetha** [comment]
Below are the configurations I am using:

"typedocOptions": {
    "entryPoints": "./sampleprojects/sampleFolder/",
    "entryPointStrategy": "expand",
    "out": "doc",
    "excludePrivate": true,
    "disableSources": true,
    "hideBreadcrumbs": true,
    "name": "API Doc",
    "theme": "default",
    "readme": "./doc1/README.md",
    "categorizeByGroup": true,
    "mergeModulesRenameDefaults": true,
    "excludeExternals": true,
    "mergeModulesMergeMode": "project"
}

plugins used:
typedoc-github-wiki-theme
typedoc-plugin-markdown
typedoc-plugin-merge-modules

**Comment by Gerrit0** [comment]
Yep, looks like you didn't turn that option on. `"allReflectionsHaveOwnDocument": true`

**Comment by kayshwetha** [comment]
Thanks a lot @Gerrit0 ! :) That worked like magic, have been behind this for long.
