### ISSUE TITLE
Variables in separate export statement get doc of export statement, not doc of declaration

### ISSUE THREAD

**Issue by Josh-Cena** [TypeStrong/typedoc#1901]
## Search terms

export variable

## Steps to reproduce the bug

```ts
// constants.d.ts

/** A constant */
declare const constant1 = 1;
/** Another constant */
declare const constant2 = true;
/**
 * bar
 * @param a foo
 */
declare function foo(a: number): void;

/**
 * copyright
 */
export {
  constant1,
  constant2,
  foo,
};
```

```bash
yarn typedoc --entryPoints constants.d.ts
```

Generated doc:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/55398995/160727015-e22c1a53-13a9-4e3a-8209-cbb8b53b0206.png">

See also: https://github.com/facebook/docusaurus/pull/7060 and [deploy preview](https://deploy-preview-7060--docusaurus-2.netlify.app/docs/api-next/modules/docusaurus_utils_lib/#babel_config_file_name) for this bug in action.

## Expected Behavior

The function `foo` correctly gets the doc of declaration. Variables should behave the same.

## Actual Behavior

The variable constants get the doc of the export statement, which is a copyright header.

## Environment

-   Typedoc version: 0.22.13
-   TypeScript version: 4.6.3
-   Node.js version: 17.5.0
-   OS: MacOS 11.6

**Comment by Gerrit0** [comment]
Duplicate of #1886, this is working as intended. You could toss a `@module` tag in the copyright comment, or make it a non-JSDoc comment which would prevent it from being associated with the export declaration

**Comment by Josh-Cena** [comment]
I see, thanks!

**Comment by Josh-Cena** [comment]
Is there a particular reason why doc for functions don't get overridden by the export statement comment though?

**Comment by Gerrit0** [comment]
That looks like an oversight + bug to me, didn't see it the first time I looked at it

**Comment by Gerrit0** [comment]
... and fixing it is *really* annoying. I'm tempted to instead make export comments only do a thing for modules/namespaces...

**Comment by Gerrit0** [comment]
> I'm tempted to instead make export comments only do a thing for modules/namespaces...

Going to do this as a part of 0.23's breaking changes.
