### ISSUE TITLE
How to describe an object return properties 

### ISSUE THREAD

**Issue by removed-usr** [TypeStrong/typedoc#1902]
## Search terms
This question could be also asked as 
How to describe a complex object return
How to describe a return that's an object 
How to describe a return with properties

## Question
Basically, I generate an object, values are correlated, so I think this is the best way to return the information

This is the code I'm using, and then there's the output of the code. As you see, it shows the return names and types, but it doesn't display the description of the property

[I found this post that's a jsdocs equivalent, althought I tried to convert it to typescript-typedoc, it didn't work](https://stackoverflow.com/questions/28763257/jsdoc-return-object-structure)

```ts
/** @module Test */
/**
 * A test function
 * @param args.num - argument number
 * @param args.str - argument string
 * @param args.arr_of_num - argument of type number []
 * @return ret_object.num  - a number 
 * @return ret_object.str - a string
 * @return ret_object.arr_of_num - an array of strings
 */
export const test = (args: {num: number, str: string, arr_of_num: number[]}): {
  num: number; str: string; arr_of_num: number[]
} => {
  let ret_object = {
    num: args.num,
    str: args.str,
    arr_of_num: args.arr_of_num
  }
  return ret_object
}
```

[![image showing produced html][1]][1]

  [1]: https://i.stack.imgur.com/Rk4yq.png

**Comment by Gerrit0** [comment]
If your returned object is complex enough to need explanation, I would recommend making an interface or type for it, and declaring that the function returns that type:

```ts
export interface TestResult {
    /** a string */
    num: number;
    str: string;
    arr_of_num: number[]
}

export const test = (args: {}): TestResult => { ... }
```

If you declare the return type as an anonymous object type on the function, you can also include comments there, but this is ugly and I don't really recommend it.

```ts
export const test = (args: {}): { /** a number */ num: number } => {
  // ...
}
```
