### ISSUE TITLE
Unable to hide default export with @internal

### ISSUE THREAD

**Issue by glensc** [TypeStrong/typedoc#1903]
## Search terms

`@internal`, `excludeInternal`

## Expected Behavior

Marking `@internal` to default export should be omitted from documentation

## Actual Behavior

The default export is still included in output

<img width="213" alt="image" src="https://user-images.githubusercontent.com/199095/161205638-3439988c-3063-405c-9f66-083dde07653d.png">

## Steps to reproduce

```ts
// src/index.ts
/**
 * @deprecated Use Logger.create
 * @internal
 */
export default (options: LoggerOptions = {}) => {
  return LegacyLogger.create(options);
}
```

```
$ typedoc  --excludeInternal
```

## Environment

-   Typedoc version: 0.22.13
-   TypeScript version: 4.6.2
-   Node.js version: v14.19.1
-   OS: Irrelevant (macOS)

**Comment by Gerrit0** [comment]
Huh, this is specific to using a default exported arrow function. Regular functions work fine, arrow functions non-default exported are fine...
