### ISSUE TITLE
How to handle of [[TOC]] in markdown

### ISSUE THREAD

**Issue by glensc** [TypeStrong/typedoc#1904]
## Search terms

`toc`

## Question

I have README.md that contains `[[TOC]]` this is rendered by GitLab to Table Of Contents.

1. Is there way to replace `[[TOC]]` with empty a string?
2. is there any plugin to handle rendering of `[[TOC]]`?
3. do something else?

I'm not sure what to do with it, but currently, it's just ugly. Not important to render the `[[TOC]]`.

**Comment by Gerrit0** [comment]
You can do this today for comments with a plugin: https://www.npmjs.com/package/typedoc-plugin-replace-in-comments

I suspect that plugin not working in readme files was an oversight, it would be an easy fix.

**Comment by krisztianb** [comment]
Currently the plugin only replaces text in code comments. But it makes sense to replace also in other parts of the documentation without having to install another plugin just for that purpose. I'll keep you posted in the [other thread that Gerrit opened in the plugin's repo](https://github.com/krisztianb/typedoc-plugin-replace-in-comments/issues/2).

**Comment by krisztianb** [comment]
Just in case anybody finds this while having a similar problem.

The following plugin can be used to solve this: https://github.com/krisztianb/typedoc-plugin-replace-text
