### ISSUE TITLE
Add support to extra markdown files to output directory

### ISSUE THREAD

**Issue by glensc** [TypeStrong/typedoc#1906]
## Search Terms

`extra files`, `copy`, `media`, `markdown`.

## Problem

My readme contains a link to `CONTRIBUTING.md`:

```
## Links

- [Contributing guide](CONTRIBUTING.md)
```

I would like that `CONTRIBUTING.md` file also copied to documentation directory.

## Suggested Solution

First I thought that `--media=CONTRIBUTING.md` would be useful, but it needs to be rendered as .html as well, so not that simple...

**Comment by glensc** [comment]
Somewhat related:
- https://github.com/TypeStrong/typedoc/issues/1870

**Comment by Gerrit0** [comment]
Yeah, going to track this under #1870
