### ISSUE TITLE
`undefined` as module name and `export&#x3D;` as property name

### ISSUE THREAD

**Issue by jackens** [TypeStrong/typedoc#1907]
## Search terms

`module name`, `export name`, `undefined`, `export&#x3D;`

## Expected Behavior

The documented module has the correct name (instead of `undefined`).
The documented property has the correct name (instead of `export&#x3D;`).

## Actual Behavior

The documented module has an invalid name (`undefined`).
The documented property has an invalid name (`export&#x3D;`).

## Steps to reproduce the bug

`typedoc.json`:

```json
{
  "cleanOutputDir": true,
  "entryPointStrategy": "expand",
  "entryPoints": [
    "src"
  ],
  "hideLegend": true,
  "out": "_doc",
  "readme": "none"
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "outDir": "tmp",
    "target": "esnext"
  },
  "include": [
    "src/**/*.js"
  ]
}
```

`package.json`:

```json
{
  "dependencies": {
    "typedoc": "0.22.13",
    "typescript": "4.6.3"
  }
}
```

`src/file.js`

```js
/**
 * @module someModuleName
 */

/**
 * @name someName
 */
module.exports = { answer: 42 }
```

Executing

```sh
npm i
npx typedoc
```

generates a file `_doc/index.html` with module name `undefined` and property name `export&#x3D;`.

## Environment

-   Typedoc version: conf. `package.json`
-   TypeScript version: conf. `package.json`
-   Node.js version: v14.17.4
-   OS: MacOS

**Comment by Gerrit0** [comment]
> The documented module has the correct name (instead of undefined).

This happens because, for the package, TypeDoc takes the name from your package.json file, unless you override it with [`--name`](https://typedoc.org/guides/options/#name). TypeDoc should probably warn you about this if the name isn't set... With a single file, it seems reasonable to me to infer the name from the file, but we'd still run into issues with multiple files.

> The documented property has the correct name (instead of export&#x3D;).

TypeDoc does not support renaming reflections with `@name`. You could write a plugin to do this:

```js
// typedoc --plugin ./path/to/this/file.js
const td = require("typedoc");

exports.load = function (app) {
    app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, onDeclaration);
};

/**
 * @param {td.Context} _context
 * @param {td.Reflection} reflection
 */
function onDeclaration(_context, reflection) {
    const rename = reflection.comment?.getTag("name");
    if (rename) {
        reflection.name = rename.text.trim();
        reflection.comment.removeTags("name");
    }
}
```
