### ISSUE TITLE
Links broken due to camelcasing

### ISSUE THREAD

**Issue by truebden** [TypeStrong/typedoc#1909]
## Search terms

casing, links, camelcasing, filename, url

## Expected Behavior

When clicking on one of the types which is called for instance "ApiState" on the export list on the right side of the index.html, it opens the specific type. The link to the type should have the same casing as the type or being all lowercase as well es the html file which should be opened. They should have the same casing.

## Actual Behavior

Clicking on a link for a type which has for isntance a camelcased name like "ApiState", the link to the html file is also camelcased "../classes/ApiState.html". The actual html file is stored as "../classes/apistate.html". Therefore clicking on the link does not work (on windows filesystem it does as it is not case sensitive).

## Steps to reproduce the bug

Use version v0.22.13

1. Define a typescript class with a camelcased name. e.g. "ApiState".
2. Generate the documentation
3. Click on the link on the exports section on the right for the created class.

I updated from version v0.20.36. There all links where lowercase

## Environment

-   Typedoc version:  v0.22.13
-   TypeScript version: 3.1.6
-   Node.js version: v16.14.2
-   OS: linux

**Comment by Gerrit0** [comment]
https://github.com/TypeStrong/typedoc/issues/1633

**Comment by truebden** [comment]
@Gerrit0 looks like mine is a duplicate to that one. Thank you and sorry, I did not find it in the search 👍

**Comment by Gerrit0** [comment]
That's totally fine! It's way easier to find something when you already know it's there ;)
