### ISSUE TITLE
Issue ignoring files on an ionic 2 / angular 2 project

### ISSUE THREAD

**Issue by petercn** [TypeStrong/typedoc#191]
It may just be my ignorance over minimatch patterns but for the life of me I can't figure out the right pattern to get typedoc to ignore all the files in my node_modules directory. A typical ionic2 project has a node_modules directory at the root and it has it's main TS file at app/app.ts so the node_modules and app directory are siblings. I've tried exclude like so and with a million other patterns and nothing seems to work: typedoc --out gb-docs ./ --exclude **/node_modules/**/*.ts

I just want typedoc to crawl through my app folder so that I can document my own source code and none of the other dependencies in node_modules folder. Thanks so much to anyone who can help.

**Comment by petercn** [comment]
Note: My globstar asterisks around that node_modules directory above got converted into markdown via github so just ignore that and imagine that there are two asterisks on either side of that node_modules directory above

**Comment by harryjubb** [comment]
+1 for this. Struggling with an Angular 2 app, I don't want anything from node_modules to be documented, and a dependency in there is throwing an error preventing any documentation from being generated at all.

**Comment by norenma** [comment]
I have the same problem. I haven't yet found a solution, but --ignoreCompilerErrors at least generates the docs, but still complains about missing modules.

**Comment by jtc10005** [comment]
in the past 
`--exclude '**/node_modules/**'
`
has worked for me.
