### ISSUE TITLE
Bug: error parsing the result type which is an array of maps

### ISSUE THREAD

**Issue by jackens** [TypeStrong/typedoc#1913]
## Search terms

`type parsing`

## Expected Behavior

Result type which is an array of maps is correctly parsed

## Actual Behavior

Result type which is an array of maps is incorrectly parsed

## Steps to reproduce the bug

`typedoc.json`:

```json
{
  "cleanOutputDir": true,
  "entryPointStrategy": "expand",
  "entryPoints": [
    "src"
  ],
  "hideLegend": true,
  "out": "_doc",
  "readme": "none"
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "outDir": "tmp",
    "target": "esnext"
  },
  "include": [
    "src/**/*.js"
  ]
}
```

`package.json`:

```json
{
  "dependencies": {
    "typedoc": "0.22.14",
    "typescript": "4.6.3"
  }
}
```

`src/file.js`

```js
/**
 * @returns {[{ [key1: string]: number }, { [key2: string]: string }]}
 */
const fn = () => [{ a: 42 }, { b: '42' }]

module.exports = { fn }
```

Executing

```sh
npm i
npx typedoc
```

generates a file `_doc/index.html` that includes line:

```
Returns [{}, {}]
```

and the following bugged line:

```
, { [key2: string]: string }]}
```

## Environment

-   Typedoc version: conf. `package.json`
-   TypeScript version: conf. `package.json`
-   Node.js version: v14.17.4
-   OS: MacOS

**Comment by Gerrit0** [comment]
> Returns [{}, {}]

This is because the rendering for reflection types in type.tsx doesn't properly support index signatures. Should be a relatively straightforward fix, if annoying...

> , { [key2: string]: string }]}

This is because TypeDoc parses comments with regex today. I believe this should be fixed already in the branch for 0.23, but need to verify.
