### ISSUE TITLE
Missing Documentation for Exports Wrapped in Higher-Order Components

### ISSUE THREAD

**Issue by TomTheHuman** [TypeStrong/typedoc#1916]
## Search terms
higher-order, hoc, components, wrapper, context

## Question
TypeDoc does not seem to generate documentation for exports wrapped in higher-order components. Is this functionality supported with special configurations, or is there a different way I would need to export my modules to get them to generate docs?

## Example
Standard exports (generate docs fine):
`export default App;`

Wrapped exports (do not generate docs):
`export default withAuthReq(App);`

We use a lot of HOC's in our company code base and it appears only modules exported this way are missing from our TypeDoc generated docs. I've tried various plugins like typedoc-plugin-not-exported or typedoc-plugin-missing-exports but they either don't produce docs for the component in question, or make more of a mess than without.

**Comment by TomTheHuman** [comment]
For anyone else running into this issue, here's the fix/work-around (depending on how you see things).

You can `export` your class/function/variable upon declaration, and then `export default` the same thing wrapped in an HOC.

Example:
``` javascript
export function App() {
  return (
    <h1>Hello World!</h1>
  );
}

export default withHOC(App);
```

TypeDoc will see the first export and document it correctly, however your imports in other files will use the default.

**Comment by Gerrit0** [comment]
If no docs are generated at all, as in an empty module, this sounds like a bug to me...
