### ISSUE TITLE
GithubPages Build Fails (.nojekyll gets ignored)

### ISSUE THREAD

**Issue by snoweuph** [TypeStrong/typedoc#1921]
## Expected Behavior

That I can use the Builded site with GH Pages

## Actual Behavior
GH Pages is using Jekyll even though there is a .nojekyll the site building then fails because I don't have a style.scss in assets/css/

full run https://github.com/snoweuph/BotPrefab/runs/6048474153?check_suite_focus=true

## Steps to reproduce the bug
- building a page
- pushing it in the repo
- setting the docs folder as pages entry point

## Environment

-   Typedoc version: ^0.22.15
-   TypeScript version:^4.6.2
-   Node.js version: v16.14.2
-   OS: Linux Mint 20.3 x86_64

**Comment by snoweuph** [comment]
sry pressed return to early accedently

**Comment by Gerrit0** [comment]
This is a configuration problem. GitHub isn't looking at `src/docs/` for your site, but at `docs/`, which doesn't exist. `.nojekyll` only has an effect if it's at the root of your built site, so this isn't a valid configuration.

```
Run actions/jekyll-build-pages@v1
  with:
    source: ./docs
```

**Comment by snoweuph** [comment]
Ahh okay, I moved the docs from src/bot/docs to /docs and now it works, thanks :) sry for stealing your time
