### ISSUE TITLE
Can the rendered output contain more line breaks?

### ISSUE THREAD

**Issue by mrft** [TypeStrong/typedoc#1923]
## Search terms

line length, git

## Question

I don't know if this can be controlled with some configuration option somehow, but when I regenerate the docs for my project, I always end up having huge commits, because the first line of ./modules/index.html in my case contains over 13000 characters.
But the only part in that line that is actually different is
```
\<li>Defined in \<a href="https://github.com/mrft/itr8/blob/27bb704/src/types.ts#L28">types.ts:28\</a>
```

If it cannot be controlled by configuration, I guess this is a feature request to make sure that this part and the other highly dynamic parts will end up on a single line as much as possible. This would make git commits of the generated docs much easier to read and cleaner.

**Comment by Gerrit0** [comment]
This seems like a reasonable feature request to me, gzip ought to take care of any whitespace, so I'm fine just adding some more line breaks... experimentation needed to figure out the best way to do this I think.

**Comment by mrft** [comment]
**First of all:**
I upgraded typedoc and saw that this feature improved the readability of the git commits tremendously! Thanks for that.

**But:** (there is always a but...)
1 thing that struck my eye was this: if I change an @example that contains a code block, everything inside is still on a single line of html.

So for example:
```
 * @example
 * ```typescript
 * // some comment
 * // and the next comment line
```
gets translated into the following html
```
<h3>Example</h3><pre><code class="language-typescript"><span class="hl-3">// some comment</span><br/><span class="hl-3">// and the next comment line</span><br/>
```
instead of adding a newline after the \<br/> which would make more sense I think.
