### ISSUE TITLE
Squash properties of unexported parent types

### ISSUE THREAD

**Issue by ocket8888** [TypeStrong/typedoc#1925]
## Search Terms

- inherited
- inherit
- expand
- deep

## Problem
If I'm making a Typescript library, I may choose to do something like the following example
<details><summary>The example in question</summary>

My library:
```typescript
interface FooBase {
    id: number;
}

interface FooWithABar extends FooBase {
    barID: number;
    barName: string;
}

interface FooWithoutABar extends FooBase {
    barID: null;
    barName: null;
}

export type Foo = FooWithABar | FooWithoutABar;
```

Usage:
```typescript
import type { Foo } from "foo";

// Legal
let foo: Foo = {
    id: 1,
    barID: null,
    barName: null
};

// Legal
foo = {
    id: 2,
    barID: 1,
    barName: "foobar"
};

// Illegal
foo = {
    id: 3,
    barID: null,
    barName: "foobar"
};

// Illegal
foo = {
    id: 4,
    barID: 2,
    barName: null
};
```
See, I've forced the users to either make both `barID` and `barName` non-`null`, or both `null` - but never a mixture. However, the types that make up `Foo` aren't useful on their own and I intentionally don't export them to avoid confusion. I especially don't want to publish `FooBase`, since that's not a valid `Foo` and can't possibly be used in a valid context.

</details>

The particulars of the example aren't terribly important, but the point is that I have an exported type alias that is a union of unexported types. I'm doing that intentionally because those unexported types aren't useful or valid on their own. However, my Typedoc documentation has no information for the reader thereof about what properties these types have; it simply displays them as a union of opaque types.

## Suggested Solution
Instead of just throwing up its hands and making the underlying unions opaque, Typedoc should support an option to replace unexported types with their equivalent sources. Or to really take things too far, an option to expand types out until only primitives and those provided by the `tsconfig.json`'s `lib` remain. That seems much less useful to me, but possibly easier to implement.

<details><summary>The resulting documented type from the exported alias in the example above</summary>

```typescript
type Foo = { id: number; } & (
	{
		barID: number;
		barName: string;
	} |
	{
		barID: null;
		barName: null;
	}
);
```
</details>

Now, I could, of course, just create my types this way in the first place, but due to the complexity of some libraries, the underlying parts of these types wind up being extended or unioned elsewhere, so doing it through unions of unexported types cuts down on duplication and makes development much easier.

**Comment by Gerrit0** [comment]
See #1823, not going to implement this in TypeDoc proper, but it could be implemented by a plugin.
