### ISSUE TITLE
Allow use of minimatch pattern

### ISSUE THREAD

**Issue by trajano** [TypeStrong/typedoc#1926]
## Search Terms

Entrypoint minimatch

## Problem

At present I have to explicilty [list all the entry points](https://github.com/trajano/react-hooks/blob/5be38acc7769e858343c1a3a0e02d038dba4fb73/typedoc.json#L2-L11) for the modules. because if I use `expand` it will create modules like `xyz/default` when I only want `xyz`

## Suggested Solution

If entrypoints can be allowed to use a minimatch pattern like `./src/*` then the duplication can be avoided.

A more complex solution would be to use the entry point and with a new strategy `exports` to include the directly exported modules from [./src/index.ts](https://github.com/trajano/react-hooks/blob/master/src/index.ts)

**Comment by Gerrit0** [comment]
This seems reasonable to me to do for resolve/expand strategies. Needs to be in a non-patch bump since it's a breaking change.
