### ISSUE TITLE
React.forwardRef poses a challenge to TypeDoc

### ISSUE THREAD

**Issue by oravecz** [TypeStrong/typedoc#1933]
## Search terms

wrappers, react.forwardref, export

## Question

How do I properly document the parameters my React component will accept when the function I export wraps the component?

Here is a component that is easy to document.

```js
/**
 * My button.
 */
export function MyButton (props:MyButtonProps) {
  return (
    <button className="button">
      {props.children}
    </button>
  )
}
```

However, I don't think it is possible to properly (or similarly) document the same component when it is wrapped, as is necessary when forwarding a ref value.

```js
/**
 * ???
 */
export const FancyButton = React.forwardRef<HTMLButtonElement, MyButtonProps>((props, ref) => (
  <button ref={ref} className="FancyButton">
    {props.children}
  </button>
));
```

**Comment by Gerrit0** [comment]
![image](https://user-images.githubusercontent.com/19329837/171026879-38300067-3ac6-4390-8313-04270002d1a8.png)

... yeah, that's not great. Automatically generating good documentation for arbitrary type patterns (especially when they get **messy** like React's) is incredibly difficult.

I would recommend creating a plugin which recognizes patterns like this and rewrites the reflection to a type you can more easily write comments for. Here's an example for `forwardRef`. I have `@types/react: ^18.0.1`  and `typescript: 4.6.3` installed in the project I threw this together in.

With this plugin, you can use `@param props description` in the comment for `FancyButton` just like you can for `MyButton`

```js
// npx typedoc --plugin ./path/to/this/file.js ./entry.tsx
const td = require("typedoc");

/** @param {td.Application} app */
exports.load = function (app) {
    app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, handleDeclaration);
};

/**
 *
 * @param {td.Context} context
 * @param {td.DeclarationReflection} refl
 */
function handleDeclaration(context, refl) {
    // This is probably brittle and will need to change based on TS / React version
    if (refl.type instanceof td.ReferenceType && refl.type.qualifiedName === "React.ForwardRefExoticComponent") {
        const sig = new td.SignatureReflection("__call", td.ReflectionKind.CallSignature, refl);
        const props = new td.ParameterReflection("props", td.ReflectionKind.Parameter, sig);

        // Ick. Grab the props.
        props.type = refl.type.typeArguments?.[0].types[0];
        sig.parameters = [props];

        refl.signatures = [sig];
        refl.kind = td.ReflectionKind.Function;
        delete refl.defaultValue;
        delete refl.type;
    }
}
```
