### ISSUE TITLE
package.json exports support

### ISSUE THREAD

**Issue by nicholasio** [TypeStrong/typedoc#1934]
## Search Terms

multiple exports packages, node.js exports, package.json exports.  which allow this kind of  behavior

## Problem

I have a monorepo where some packages exposes multiple exports through package.json `exports` directive. 

```js
import { something } from '@vendor/my-package/react'`
import { somethingElse }  from '@vendor/my-package/next'
```

I noticed with the `package` entryPointStrategy it will only look for a single entry point. Is there a easy way typedoc could be extended via plugins to search for every exports and create a module for each?

Alternatively I'm open to workaround but I couldn't find a way to have each export be treated as a separate module. What I ended up doing was creating a separate entry point that contains all of the exports but doing that groups separate exports into the same module.

For context, those packages are built separately which is why I'm using the `packages` strategy.

**Comment by nicholasio** [comment]
I made some progress by creating doing this in the entry point I created for the docs

```js
/**
 * The default export of the `@10up/headless-core` package.
 *
 * ```tsx
 * import { PostsArchiveFetchStrategy } from "@10up/headless-core";
 * ```
 */
export * as core from './index';

/**
 * The react export
 *
 */
export * as react from './react';
```

Which does this 
![image](https://user-images.githubusercontent.com/6104632/169907636-d38ae41f-0aa8-4d2f-ab59-c144fa9826c1.png)


and this

![image](https://user-images.githubusercontent.com/6104632/169907659-71fd97cb-da4f-4829-af14-07417fa70a05.png)

The only thing I couldn't do was rename the core module so it doesn become "@10up/headless-core/core" in the docs. It looks like @module doesn't wokr when using packages mode?

**Comment by nicholasio** [comment]
I could not rename the "index" export (core) but If I don't rename the index export I lose the ability to document the namespace (not sure if that's expected).

**Comment by Gerrit0** [comment]
I'm going to track this in #1937 since it more fully describes how I'd like TypeDoc to work
