### ISSUE TITLE
Support for TypeScript 4.7

### ISSUE THREAD

**Issue by sile** [TypeStrong/typedoc#1935]
## Search terms

npm install error, typescript 4.7

## Expected Behavior

TypeDoc works well with TypeScript 4.7.

## Actual Behavior

`npm install` fails when both typedoc-0.22.15 and typescript-4.7.2 are specified.

## Steps to reproduce the bug

The following commands show the minimum package.json and the install error message:
```console
$ cat package.json
{
    "name": "foo",
    "version": "1.0.0",
    "dependencies": {
        "typedoc": "^0.22.15",
        "typescript": "^4.7.2"
    }
}

$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: typedoc-test@1.0.0
npm ERR! Found: typescript@4.7.2
npm ERR! node_modules/typescript
npm ERR!   typescript@"^4.7.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x || 4.5.x || 4.6.x" from typedoc@0.22.15
npm ERR! node_modules/typedoc
npm ERR!   typedoc@"^0.22.15" from the root project
```
## Environment

-   Typedoc version: 0.22.15
-   TypeScript version: 4.7.2
-   Node.js version: 16.13.0
-   OS: macOS

**Comment by felixapitzsch** [comment]
When I run `npm update --force`, I can upgrade to TypeScript 4.7.2. When i run Typedoc in this setup, I get more warnings, but the output looks good and I didn't run into actual problems with my code so far. Are there any known issues with Typedoc and TypeScript 4.7 or could it be added to the allowed version range?

If there are no specific known issues and it just needs testing, a package release with a respective tag would be nice.

**Comment by Gerrit0** [comment]
There are several things that need to be done to support the new TS version:

- [ ] Update globs which look for TS files to handle cts/mts
- [ ] Add support for exports/./import|require/types to packages mode (not required for initial release, #1934)
- [ ] Add tests for code using instantiation expressions (don't think there's code changes necessary here, but...)
- [ ] Add tests + support for extends constraints on infer type variables
- [ ] Add support for variance annotations on type parameters (should be displayed in docs)
