### ISSUE TITLE
Add lint rule to website repo

### ISSUE THREAD

**Issue by Zamiell** [TypeStrong/typedoc#1940]
It should appear on the list of options here: https://typedoc.org/guides/options/

**Comment by Zamiell** [comment]
Idea: make a lint rule to parse the options and warn when one of them isn't documented?

**Comment by Gerrit0** [comment]
It's going away with the next minor version, which removes the legend entirely since icons changed to just be letters, I think I'll just let this one lie

**Comment by Gerrit0** [comment]
Lint job is a neat idea, will result in CI always failing if a PR adds a new option...

**Comment by Zamiell** [comment]
> Lint job is a neat idea, will result in CI always failing if a PR adds a new option...

Well, I think it makes more sense to put the lint rule on the site repo, not this one. That way, it won't fail unless an option has been officially released.

**Comment by Gerrit0** [comment]
Ended up deciding the amount of effort to write this rule isn't worth the amount of time it would save me... PR welcome if someone wants to do it, but I don't care enough, lots of other stuff to work on.
