### ISSUE TITLE
Is it possible to add custom flags

### ISSUE THREAD

**Issue by alimoncul** [TypeStrong/typedoc#1941]
For example can I add custom flags next to this Protected? I have some OS specific functions that works only on 1 os. For example test() function only works on Android. I want to point out this in docs. Is this correct way?

![image](https://user-images.githubusercontent.com/15328038/170685226-1c82d9f8-1fa1-4a96-9c48-6ef97ddffe95.png)

**Comment by Gerrit0** [comment]
In the next minor (currently beta) version of TypeDoc, you could do this by adding a new modifier tag to the definitions, and then adding `@android` to the doc comment.

**Comment by alimoncul** [comment]
Do you mean like this? @Gerrit0 
![image](https://user-images.githubusercontent.com/15328038/170923554-03b65f8d-53ee-4ded-b533-3a0d0170538f.png)

**Comment by Gerrit0** [comment]
That's showing up because you haven't configured the comment parser, you need to set the `modifierTags` option to include everything inside it that you use today, and add `@android`, `@ios`, etc: https://github.com/TypeStrong/typedoc/blob/beta/src/lib/utils/options/sources/typedoc.ts#L355-L375

```json
{
  "modifierTags": ["@android", "@ios"]
}
```

**Comment by alimoncul** [comment]
Alright I built beta branch and android & ios tag went missing on html.

```js
  app.bootstrap({
    entryPoints: fileNames,
    sort: ['source-order', 'visibility'],
    excludePrivate: true,
    excludeNotDocumented: false,
    excludeInternal: true,
    pretty: true,
    categorizeByGroup: true,
    cleanOutputDir: true,
    emit: 'docs',
    includeVersion: true,
    modifierTags: ['@android', '@ios']
  });
  const project = app.convert();
  // Project may not have converted correctly
  if (project) {
    // Rendered docs
    return await app.generateDocs(project, OUTPUT_DIR);
  }
```

![image](https://user-images.githubusercontent.com/15328038/171027439-a1a93608-b3d0-419e-be02-ab2ca16ce447.png)

**Comment by Gerrit0** [comment]
Oops... it works properly on non-functions... apparently however I rendered flags doesn't work correctly for signatures...

**Comment by Gerrit0** [comment]
Fixed on beta branch:

![image](https://user-images.githubusercontent.com/19329837/172013734-2556c6f3-0772-4121-82d5-20036f14537e.png)

![image](https://user-images.githubusercontent.com/19329837/172013738-7ba1507d-1559-4451-abc5-0de0c584f77e.png)

**Comment by alimoncul** [comment]
Thank you!
