### ISSUE TITLE
Legend is not displayed for single entry point

### ISSUE THREAD

**Issue by stranskyjan** [TypeStrong/typedoc#1946]
## Search terms

- legend
- missing legend
- single entry point
- single output page

## Expected Behavior

Legend is displayed at the bottom of the page.

## Actual Behavior
For **single entry point**, **no legend is displayed**.

However, for **multiple entry points**, the legend **is displayed**.

I could not find any other clues and/or differences than the fact of single / multiple entry points..

I tried to play with `entryPointStrategy` option, but without success..

## Steps to reproduce the bug

Minimal repo: [here](https://github.com/stranskyjan/typedoc-bug-report-single-entry-point-missing-legend)

Steps to reproduce the problem:
- `git clone` the repo
- `cd` the repo directory
- `npm install`
- `npm run test`
- see `single-entry-point/out/index.html`
- see `multiple-entry-points/out/index.html`

## Environment

-   Typedoc version: 0.22.15
-   TypeScript version: 4.6.4
-   Node.js version: 16.15.0 LTS
-   OS: Ubuntu 22.04 LTS

**Comment by Gerrit0** [comment]
This is because a `ProjectReflection` is not a `DeclarationReflection`:

https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/plugins/LegendPlugin.ts#L309

PR welcome, though the legend is going away in 0.23 as icons are self explanatory there... might not be worth fixing.
