### ISSUE TITLE
Use typedoc as remote type

### ISSUE THREAD

**Issue by Kivylius** [TypeStrong/typedoc#1947]
## Search terms

typedoc, typescript, remote, micro frontends

## Question

I love typedoc and its generated docs, but is it possible to use the output of typedoc or even write some plugin to be able to use typedoc output as remote type (comment or import) e.g.

```js
/** typedoc:url website.com/typedoc/MyComponentType **/
const MyComponent = import('website.com/components/MyComponent');

- or -

import MyComponentType from  `website.com/typedoc/MyComponentType`;
const MyComponent: MyComponentType = import('website.com/components/MyComponent');
```

This pattern would allow remote types, when using patterns like micro frontend and there no direct importing of the different repos. This could also aid in the generation of better docs, where the type is remote, we could say something like:

```tsx
import MyComponentType from  `website.com/typedoc/MyComponentType`;
type Something {
   MyComponent: MyComponentType
}
```

Let me know if this is possible, if not maybe point me in the right direction.

**Comment by Gerrit0** [comment]
You're probably after `renderer.addUnknownSymbolResolver` - https://github.com/TypeStrong/typedoc/blob/master/internal-docs/third-party-symbols.md
