### ISSUE TITLE
Empty modules with only top-level docstring are not included

### ISSUE THREAD

**Issue by letmaik** [TypeStrong/typedoc#1948]
The change was introduced with https://github.com/TypeStrong/typedoc/issues/1607.
Previous to that, a module that a had a docstring with `@module` was included but now it is excluded.
The module is part of `"entryPoints"` in `typedoc.json`.

Being able to include those "empty" module is useful if they exist for their side-effects only, like polyfills.

To reproduce, here is the module that is not rendered:
https://github.com/microsoft/CCF/blob/b1cdae40ba927e45fe8178791fa6e509b3a09097/js/ccf-app/src/polyfill.ts

and the corresponding config:
https://github.com/microsoft/CCF/blob/b1cdae40ba927e45fe8178791fa6e509b3a09097/js/ccf-app/typedoc.json

Short of adding a dummy symbol, is there a way to tell typedoc to include such modules?

**Comment by Gerrit0** [comment]
Looking at that again, I don't much like the change... TypeDoc shouldn't ignore entry points because they're empty. The excludeNotDocumented use case should be handled by checking that a module is not documented and contains no children.
