### ISSUE TITLE
Any way to document files externally to the source code?

### ISSUE THREAD

**Issue by grofit** [TypeStrong/typedoc#195]
I doubt this is supported and I doubt it would be an easy ask if it is not already but I kinda get annoyed when I have to make all my files really verbose and hard to read when there are comments everywhere. I love the actual documentation provided but ideally I keep hoping there would be a document generator tool which kinda works outside of your source code class and just kinda runs on it.

So is there any way that I can apply documentation to a file content without having to embed it within the raw `*.ts` file? just as an example I would expect something like in an ideal world:

```
// some-class.ts
export class SomeClass
{
   public something: string;
}
```

```
// some-class.doc.ts
/**
   #SomeClass
   This class does something
*/

/**
   #something
   This variable contains a string which doesnt do much

   @example 
   someClassInstance.something = "blah";

*/
```

I have yet to find a documentation tool that works this way, and it baffles me why it is not supported as in a lot of cases you just want to keep your source code clean and succinct, but when you want to provide lots of nice examples, extra docs on how things can be used and how to best use certain things it starts to get pretty wordy and a simple POJO or SRP style class ends up becoming a pretty large file with all the nice docs.

**Comment by aciccarello** [comment]
Look at the [Content](https://github.com/TypeStrong/typedoc#content) options. You may be able to include a markdown file. I haven't used it myself but saw a [note](https://github.com/TypeStrong/typedoc/issues/247#issuecomment-229897044) about it in #247
