### ISSUE TITLE
The file does not contain a sourceMappingURL

### ISSUE THREAD

**Issue by jlarmstrongiv** [TypeStrong/typedoc#1952]
## Search terms

Error: The file does not contain a sourceMappingURL
Error: Could not determine TS entry point for package package.json

## Expected Behavior

I expect tsdoc to compile like it normally does after migrating to https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions

## Actual Behavior

In monorepo mode only, tsdoc fails to find the entry point

```
Error: The file /absolute/path/to/src/index.d.cts does not contain a sourceMappingURL
Error: Could not determine TS entry point for package /absolute/path/to/package.json
```

## Steps to reproduce the bug

Create a monorepo with a package with two files—index.cjs and index.d.cts (instead of index.d.ts)

Have the typedocMain point to the index.d.cts file

Use the monorepo mode `NODE_OPTIONS=--max_old_space_size="16384" npx typedoc --out "$monorepo_path/docs" --excludeExternals --entryPointStrategy packages 'packages/*'`

## Environment

-   Typedoc version: 0.22.17
-   TypeScript version: 4.7.4
-   Node.js version: v16.15.0
-   OS: both MacOS and Linux

**Comment by Gerrit0** [comment]
Make sure you have source maps turned on for your dependent projects. This is required for packages mode, but no other mode.

**Comment by Gerrit0** [comment]
Shoot. I missed a couple regexes.

**Comment by Gerrit0** [comment]
Not yet! It should by Wednesday though... would like to get at least a couple mote of the [TODOs](https://github.com/TypeStrong/typedoc/projects/11) done, aiming for a full release next weekend.
