### ISSUE TITLE
Allow customization of JavascriptIndexPlugin

### ISSUE THREAD

**Issue by GerkinDev** [TypeStrong/typedoc#1953]
## Search Terms

JavascriptIndexPlugin, search, weight, extension

## Problem

I'm writing a plugin that alters some custom reflections in the javascript index. It needs to modify weight of custom reflections (which was implemented in a very recent release) and format the reflection name with a special pattern. Since I wasn't able to alter how reflections are gathered, I had to override the plugin entierly, which complexifies my workflow in order to always stay up to date with Typedoc.

## Suggested Solution

Ideally, plugins should be able to alter what is iterated on here: https://github.com/TypeStrong/typedoc/blob/ba586967c1131d657843e3eea773ea95bb1f2c6c/src/lib/output/plugins/JavascriptIndexPlugin.ts#L50-L52
Maybe the `JavascriptIndexPlugin` could be converted to an event emitter we could hook events on.

**Comment by Gerrit0** [comment]
> It needs to modify weight of custom reflections

Can be achieved by setting `reflection.relevanceBoost` during `Converter.EVENT_RESOLVE` today

I'm okay with adding an event to `Renderer` for further modification of `rows` before building the index.

**Comment by GerkinDev** [comment]
Yesterday when I checked, this new option was still undocumented

**Comment by Gerrit0** [comment]
The `relevanceBoost` key? https://typedoc.org/api/classes/ContainerReflection.html#relevanceBoost

**Comment by GerkinDev** [comment]
Well, in the original post, when I said that "it was recently implemented", I was talking about typedoc. Indeed, I'm overriding the `JavascriptIndexPlugin`, and I've seen those changes related to this feature. So I can now drop it from my plugin.
But the user documentation at http://typedoc.org/guides/options/ does not mention this new setting, and the options map api doc at http://typedoc.org/api/interfaces/TypeDocOptionMap.html#searchCategoryBoosts does not comment how this option behave nor its exact type. I still have to look at the source code to understand it. But that's an entierly different issue.

**Comment by Gerrit0** [comment]
User docs - true, there's a branch fixing it that'll be merged soon. 

Options map API doc - true, and unless someone else puts a comment there, it won't. None of the other options discuss implementation details either as comments which aren't right next to the implementation are even more likely to become out of date than normal.

**Comment by GerkinDev** [comment]
Great! I'll test this in my next plugin version! Have an excellent weekend
