### ISSUE TITLE
Pretty html

### ISSUE THREAD

**Issue by rotu** [TypeStrong/typedoc#1957]
## Search Terms

HTML, Formatting, Pretty

## Problem

The HTML generated by typedoc is messy and lacks whitespace. This makes it annoying to diff.

## Suggested Solution

It would be nice if the `--pretty` command-line option (which currently only affects JSON output) also made the HTML friendlier with newlines and indentation.

**Comment by Gerrit0** [comment]
See #1923 - 0.23 improves this.
