### ISSUE TITLE
Feature: ignore a package in the --entryPointStrategy packages globs

### ISSUE THREAD

**Issue by jlarmstrongiv** [TypeStrong/typedoc#1959]
## Search Terms

Ignore a package in the --entryPointStrategy packages globs

## Problem

I have a package in my monorepo that is pure css and no typescript as well as packages that are not exported.  When running typedoc with --entryPointStrategy packages and globs, it may pick up packages I would prefer to ignore.

That way, I can hide the `warning Could not determine the entry point for "/Users/jlarmst/Desktop/monorepos/turbo-monorepo/packages/configs/typedoc/package.json". Package will be ignored.` and run typedoc with `--treatWarningsAsErrors `

## Suggested Solution

Use the `--exclude` flag to disallow certain packages via the typedoc cli.

**Comment by Gerrit0** [comment]
As far as options go - I think the `--exclude` option is still applicable here, it's used for filtering entry points with other strategies

**Comment by jlarmstrongiv** [comment]
@Gerrit0 Unfortunately, I don’t think the commit fixed this bug.  I am on version `v0.23.4`.  Could we re-open?

I am still receiving the warning:
```
warning Could not determine the entry point for "/absolute/path/to/package/package.json". Package will be ignored.
```
when using exclude:
```
--exclude "relative/path/to/package/**/*"
```

**Comment by Gerrit0** [comment]
For packages, you're excluding a package itself, not the files within it, so you should use `--exclude "relative/path/to/package/"`

**Comment by jlarmstrongiv** [comment]
That works 🎉 thank you @Gerrit0
