### ISSUE TITLE
Warning about unescaped closing brace repeats "in comment"

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1964]
## Search terms

"in comment"

> warning Unmatched closing brace in comment in comment at ./src/showcase.ts:60.

## Environment

-   Typedoc version: 0.23.1

**Comment by doberkofler** [comment]
Same warning in `@example` section resulting in thousands of warnings

**Comment by doberkofler** [comment]
> That sounds like a different issue to me. Please open an issue with an example of what you're giving typedoc.

I created #1966
