### ISSUE TITLE
warning Encountered an unescaped open brace without an inline tag in comment starting with version 0.23.0

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1966]
## Search terms

warning Encountered an unescaped open brace without an inline tag in comment

## Expected Behavior

the same as in 0.22.18

## Actual Behavior

a warning is shown

## Steps to reproduce the bug

warning Encountered an unescaped open brace without an inline tag in comment at ./src/framework/UiElement/private/UiElement.ts:288.
warning Unmatched closing brace in comment at ./src/framework/UiElement/private/UiElement.ts:288.

The line 288 is the first line in the following example:

```typescript
	/**
	 * Register a blur event handler.
	 *
	 * @param {eventCallbackType} handler - Callback function.
	 * @example
	 * element.onChange(element => {console.log(element.getValueString());});
	 */
	public onBlur(handler: eventCallbackType): void { // eslint-disable-line @typescript-eslint/no-unused-vars
		console.warn(this.getError('The "onBlur" method is not available for this element'));
	}
```

## Environment

-   Typedoc version: 0.23.2
-   TypeScript version: 4.7.4
-   Node.js version: 18.4.0
-   OS: maCOS 12.2

**Comment by Gerrit0** [comment]
Hmm, this is unfortunate. The warning is valid, but for compatibility with horrible JSDoc style example tags, it should probably be suppressed when first scanning through `@example` blocks in case they'll be treated as code.
