### ISSUE TITLE
How do I `@inheritDoc` from a getter in v0.23?

### ISSUE THREAD

**Issue by oliversalzburg** [TypeStrong/typedoc#1968]
## Search terms

@inheritDoc, getter, update

## Question

After updating to the latest version, my `@inheritDoc` usage causes warnings to be printed (and is ineffective). The project I'm working on is available on GitHub and a previously working usage is at <https://github.com/oliversalzburg/plantdb/tree/d36454b25dea8d5530e24e92634c6c0020de23e3/packages/libplantdb/source/LogEntry.ts#L83>

The warning for that line would be:
> warning LogEntrySerialized.__type.id tried to copy a comment from @plantdb/libplantdb with @inheritDoc, but the source has no associated comment.

So how do I copy from the getters now or how should I restructure the code layout to not have to repeat these comments?

**Comment by Gerrit0** [comment]
Shoot, this is an edge case that slipped through...

**Comment by Gerrit0** [comment]
In 0.23.3 TypeDoc will let you do this:

```ts
export class Foo {
    /** getter */
    get x() {
        return 1;
    }
    /** setter */
    set x(value: number) {
        throw new Error();
    }
}

export class Bar {
    /** {@inheritDoc Foo.x} */
    x = 1; // getter comment
    /** {@inheritDoc Foo.x:getter} */
    y = 2; // getter comment
    /** {@inheritDoc Foo.x:setter} */
    z = 3; // setter comment
}
```

**Comment by oliversalzburg** [comment]
Nice. I'll migrate once it's out and give it a go :)
