### ISSUE TITLE
Upgrade to v0.23 removes comments from re-exported methods

### ISSUE THREAD

**Issue by chmanie** [TypeStrong/typedoc#1969]
## Search terms

`exports`
comments

## Expected Behavior

I want TypeDoc to use the comments for where the file is defined as it was in version 0.22.x. Did I miss anything in the changelog? I couldn't find a change that would affect this.

## Actual Behavior

fileA.ts
```typescript
/** A comment for a method */
export function myMethod() { /* ... */ }
```

index.ts
```typescript
export { myMethod } from './fileA.ts';
```

The `A comment for a method` comment is not shown anymore in the docs.

## Steps to reproduce the bug

See the example above.

## Environment

-   Typedoc version: 0.23.2
-   TypeScript version: 4.7.4
-   Node.js version: 16.15.0
-   OS: Linux

**Comment by Gerrit0** [comment]
Nope, you didn't miss anything. This should still work. I'll take a look tonight.

**Comment by chmanie** [comment]
Thank you so much, I appreciate it. Another thing I noticed is also that the descriptions of the parameters are missing in these cases. Here's the diff: https://github.com/JoinColony/colonyJS/compare/maint/typedoc-update#diff-e191ebfb66965e8ccd82dfc805b47134b623a758c40d2f6cbd226e522238932fL163-L173

This PR also contains other changes but I tested this with plain typedoc (generating HTML) with the same results.

**Comment by Gerrit0** [comment]
I can't seem to reproduce the first issue, I set up https://github.com/TypeStrong/typedoc-repros/pull/5, and if you look at the [job output](https://github.com/TypeStrong/typedoc-repros/actions/runs/2580380026), the comment is contained in the output. 

![image](https://user-images.githubusercontent.com/19329837/176340939-698a44c1-b40e-44b6-a595-626377bb1011.png)


Unfortunately, diff links to a file/line don't actually take you to the file/line... which file?

**Comment by chmanie** [comment]
Thank you for looking into this! I'll try to come up with a more isolated example!

You can open the actual diff lines by clicking to load the README.md diff right at the top.

**Comment by Gerrit0** [comment]
Huh weird, parameters not showing up is unexpected, if you can narrow down a test case for that too that would be very helpful :)

**Comment by Gerrit0** [comment]
0.23.3 might fix your parameters not showing up -- there was a bug with discovering comments for variable-functions that might have caused that.

**Comment by chmanie** [comment]
Yep, this version fixes all my issues
