### ISSUE TITLE
intentionallyNotExported not working with symbols addressed in namespaces (. separated)

### ISSUE THREAD

**Issue by frank-weindel** [TypeStrong/typedoc#1972]
I encountered the following warning:

```
./src/animation/TransitionSettings.d.mts:5:2 - warning TransitionSettings.Literal is referenced by default.Element.SmoothLiteral but not included in the documentation.

5      export interface Literal {
```

I decided that this was intentional so I added the following to the `intentionallyNotExported` array:
```
"src/animation/TransitionSettings.d.mts:TransitionSettings.Literal"
```

`TransitionSettings` is a namespace (the file also exports a class with the same name)

Seems to be an issue with the `.`?

## Search terms

warning <Symbol> is referenced by <Symbol> but not included in the documentation.

## Expected Behavior

The warning goes away

## Actual Behavior

The warning remains And an additional new warning is generated:
```
warning The following symbols were marked as intentionally not exported, but were either not referenced in the documentation, or were exported:
	src/animation/TransitionSettings.d.mts:TransitionSettings.Literal
```

## Steps to reproduce the bug

See above

## Environment

-   Typedoc version: 0.23.2
-   TypeScript version: 4.7.4
-   Node.js version: 16.14.0
-   OS: MacOS 12.2.1

**Comment by Gerrit0** [comment]
Hmm, It looks like I forgot that type names are prefixed with namespace names if applicable when implementing that function. Easy fix at least!

**Comment by frank-weindel** [comment]
Thank you!
