### ISSUE TITLE
Namespace comments not included

### ISSUE THREAD

**Issue by ClintH** [TypeStrong/typedoc#1973]
## Search terms

Namespace comments are not included.

## Expected Behavior

In typedoc 0.22.15 I was using comments on `export` statements to give an overview of a namespace.

Example source: https://github.com/ClintH/ixfx/blob/main/src/index.ts#L39
And rendered output: https://clinth.github.io/ixfx/modules/Generators.html

## Actual Behavior

Since upgrading to 0.23.2, these overviews aren't visible. The pull request on the repro hopefully demonstrates the same behaviour.

I've also tried adding the overview comment with a @module tag to no avail. 

If an underlying behaviour has changed, is there another way to have some kind of preamble to a namespace/module?

Thanks :)

## Steps to reproduce the bug

https://github.com/TypeStrong/typedoc-repros/pull/6

## Environment

-   Typedoc version: latest
-   TypeScript version: latest
-   Node.js version: 17.3.1
-   OS: Windows

**Comment by Gerrit0** [comment]
Thanks for the awesome repro! Looks like I messed up here... properly handling comment discovery is hard.

**Comment by ClintH** [comment]
Great work! :)
