### ISSUE TITLE
How to reuse icons from the default theme?

### ISSUE THREAD

**Issue by DiFuks** [TypeStrong/typedoc#1978]
Hello! I am the author of the [typedoc-theme-hierarchy](https://github.com/DiFuks/typedoc-theme-hierarchy) library. I have a problem with icons
Prior to version 0.23.2, I simply set the css class tsd-kind-icon for links and subItem.cssClasses for list items:

```tsx
<li class={subItem.cssClasses}>
  <a
    class='tsd-kind-icon'
    href={urlTo(subItem)}
  >
    {subItem.name}
  </a>
</li>
```
And the icons appeared. But since version 0.23.2 icons in the default theme are set in a different way https://github.com/TypeStrong/typedoc/blob/56517ef39b90d612c56110d25375cc824feaf5d6/src/lib/output/themes/default/partials/icon.tsx#L49

I tried to import:

```ts
import { icons } from 'typedoc/dist/lib/output/themes/default/partials/icon';
```

And change the code to the following:

```tsx
<li>
    <a href={urlTo(subItem)}>
      {icons[subItem.kind]}
      {subItem.name}
    </a>
</li>
```

Now, when I try to run the `typedoc` command, I get the following error:

```
error The plugin typedoc-theme-hierarchy could not be loaded.
error Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/output/themes/default/partials/icon' is not defined by "exports" in /Users/difuks/PhpstormProjects/typedoc-test/node_modules/typedoc/package.json
```
As I understand it, this is due to the definition of the `exports` field in package.json 

https://github.com/TypeStrong/typedoc/blob/master/package.json#L7

 But I still could not correctly import the variable `icons`

**Comment by Gerrit0** [comment]
The icons really ought to be exposed, probably on `DefaultThemeRenderingContext`, no good way to use them in 0.23.4.

**Comment by DiFuks** [comment]
How can I reuse them now?  If I just copy the code from icon.tsx to my project, the cache doesn't work correctly.  If there are no icons in the main content of the page, then they are not displayed in the menu either.
When caching is removed, everything works correctly, but svg are duplicated
I can implement my own icon logic but would like to reuse yours

**Comment by Gerrit0** [comment]
You can upgrade to 0.23.5 now and use them via `context.icons` :)

**Comment by DiFuks** [comment]
Thanks for your help and promptnessю Everything works fine!
