### ISSUE TITLE
Support for @ignore?

### ISSUE THREAD

**Issue by grofit** [TypeStrong/typedoc#198]
I assume that the syntax typedoc uses is based off jsdoc, but I have noticed that it doesn't support all the common features, in this instance the `@ignore` option which should omit the related variable/class/property etc from the documentation.

**Comment by vukmandavid** [comment]
It would be very useful. I tried exclude files, but in my case typedoc can't generate doc because missing references.

**Comment by enepomnyaschih** [comment]
Did you try @hidden?

**Comment by grofit** [comment]
nope, will try that when I am back on the project. I find it odd though that in some areas it followed jsdoc and in others it just does its own thing.

**Comment by enepomnyaschih** [comment]
Yeah, I was lucky to find this feature in source code.

**Comment by aciccarello** [comment]
Using `@hidden` should cover this use case but I think adding an alias to `@ignore` to match jsdoc would make sense.

**Comment by curioussavage** [comment]
it would also be nice if `@hidden` were documented on typedoc.org

**Comment by aciccarello** [comment]
Reviewing this, I think it would be good to alias [JSDoc's `@ignore`](http://usejsdoc.org/tags-ignore.html) option to TypeDoc's `@hidden`. As far as I can tell they both do the same thing. The action steps needed are:

- [ ] Adding `@ignore` as an alias of `@hidden`
- [ ] Document both options
