### ISSUE TITLE
Only first warning is shown by TypeDoc

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1981]
## Search terms

warning Encountered an unescaped open brace without an inline tag
warning Unmatched closing brace

## Expected Behavior

All warnings should be show and not only the first one (related to #1979)

## Actual Behavior

When the following type of warnings is shown, only the first one is shown instead of all of them.
After the code has been changed to `@param data - The given contact values` typedoc must be run again to see the next warning.

./src/components/contacts/index.ts:95:40 - warning Encountered an unescaped open brace without an inline tag
95    	 * @param {contactData.dataType} [data={}] - The given contact values

./src/components/contacts/index.ts:95:41 - warning Unmatched closing brace
95    	 * @param {contactData.dataType} [data={}] - The given contact values

## Steps to reproduce the bug

```typescript
export class ContactManagement {
	/**
	 * Constructor for the Contact management object.
	 *
	 * @param {contactData.dataType} [data={}] - The given contact values <--- line 95
	 */
	public constructor(data: contactData.contactValueType = {}) {
        }
}
```

## Environment

-   Typedoc version: 0.23.5
-   TypeScript version: 4.7.4
-   Node.js version: 18.4.0
-   OS: maCOS 12.2

**Comment by Gerrit0** [comment]
Aww shoot, looks like this is fallout from nearly a year ago when I added logic to not report duplicate warnings... I didn't take into account warnings with a location attached.
