### ISSUE TITLE
Emit non-zero exit code when error occurs

### ISSUE THREAD

**Issue by ilyub** [TypeStrong/typedoc#1984]
## Search terms

exit code

## Expected Behavior

1. Emit non-zero exit code for errors
2. Emit non-zero exit code for warnings when "treatWarningsAsErrors" option is enabled

## Actual Behavior

I get zero exit code with 
  "Block and modifier tags will be ignored within the readme" warning 
  "... is referenced by ... but not included in the documentation" warning 

## Steps to reproduce the bug

Add "@xyz" to readme
Add "treatWarningsAsErrors" option
Check exit code

**Comment by Gerrit0** [comment]
I can't seem to reproduce this... I get a non-zero exit code as expected.

https://github.com/TypeStrong/typedoc-repros/runs/7206636732?check_suite_focus=true

**Comment by ilyub** [comment]
It turned out that it was my mistake.
I was using the following script in package.json that did not return exit code:
```
  "scripts": {
    "build-doc": "typedoc src & cpy docs-static/* docs"
  }
```
Replacing "&" with "&&" fixed it:
```
  "scripts": {
    "build-doc": "typedoc src && cpy docs-static/* docs"
  }
```
