### ISSUE TITLE
entrypoints paths expanded

### ISSUE THREAD

**Issue by capraynor** [TypeStrong/typedoc#1985]
## Search terms
ExpandPackages Expand Packages EntryPoints entry points entryPointStrategy=packages

## Question

I'm debugging to find out why typedoc cannot find my packages. 

Finally, in options, I've found a path expansion: 

![image](https://user-images.githubusercontent.com/3467515/177728581-30080e2c-3789-49ca-992f-97df4c2e03b2.png)

From this image, you can see the `packages/*` turns into `C:\\Test\\xxxxx`. 

This expansion finally leads to `expandPackages` method works not properly.: 

![image](https://user-images.githubusercontent.com/3467515/177731012-d7f84dcd-03c7-4f01-be40-ab9476a02099.png)

Our question is, is this expansion intended? 

Let me know if my usage is wrong. 

Thanks for your help! 
Raynor 

typedoc.json: 
```
{
    "$schema": "https://typedoc.org/schema.json",
    "entryPoints": [
        "packages/*"
      ],
    "out": "doc",
    "entryPointStrategy": "Packages",
    "excludePrivate": true,
    "excludeNotDocumented": true
}
```

**Comment by capraynor** [comment]
I think related issue is: 
https://github.com/TypeStrong/typedoc/issues/1971

I'll read this issue first and do some more investigation in issue library.

**Comment by Gerrit0** [comment]
Yes, this expansion is intended. The path is added to the start of your glob so that options set in a config file with paths have paths relative to that config file rather than the cwd unless specified on the command line.

There's an example setup that uses packages mode at https://github.com/TypeStrong/typedoc-repros/pull/12 with the same `packages/*` entry point.

Your shown config in the report here is rather confusing given what you've shown in debug because it sets entryPointStrategy to Expand, not Packages. I'm guessing you're overriding this?

**Comment by capraynor** [comment]
> Your shown config in the report here is rather confusing given what you've shown in debug because it sets entryPointStrategy to Expand, not Packages. I'm guessing you're overriding this?

Sorry for confusing. 

My original-issue config is: 

```
{
    "$schema": "https://typedoc.org/schema.json",
    "entryPoints": [
        "packages/*"
      ],
    "out": "doc",
    "entryPointStrategy": "Packages",
    "excludePrivate": true,
    "excludeNotDocumented": true
}
```

The question is modified.

**Comment by capraynor** [comment]
Thanks for your reply. 

I'll investigate if there are any mistake in my configuration. 

![image](https://user-images.githubusercontent.com/3467515/177905768-752c34c3-f8d3-4aac-822b-3325721b7d4e.png)

**Comment by capraynor** [comment]
@Gerrit0 Well, 

![image](https://user-images.githubusercontent.com/3467515/177911116-5b213c48-247f-496b-b197-dc65b2e6acf6.png)

Previously here was "Packages". 
You've modified it yesterday? 
![image](https://user-images.githubusercontent.com/3467515/177911220-48f81f9f-09e4-4e98-b16a-f01a9bc4dc13.png)

**Comment by Gerrit0** [comment]
Both `Packages` and `packages` will be recognized and have the same behavior, `packages` is technically the enum value and matches what you'll see in --showConfig and what's documented on the website, so the schema was updated to be consistent, #1983

**Comment by capraynor** [comment]
OK, got it.
