### ISSUE TITLE
Export settings from default theme separately

### ISSUE THREAD

**Issue by DiFuks** [TypeStrong/typedoc#1987]
Hello! Question related to [typedoc-theme-hierarchy](https://www.npmjs.com/package/typedoc-theme-hierarchy)

Prior to typedoc version 0.23, theme and visibility settings were outside the navigation. Now they are inside the navigation. My theme completely overrides it, but I don't have the ability to reuse settings from the default theme. Because typedoc does not export the settings component separately

Could you separate the settings into a separate exportable component?

**Comment by Gerrit0** [comment]
Seems like a reasonable request :+1:

**Comment by DiFuks** [comment]
Thanks!
