### ISSUE TITLE
Add "Edit on GitHub" button to docs pages

### ISSUE THREAD

**Issue by lorensr** [TypeStrong/typedoc#1988]
## Problem

When looking at pages like: 

https://typedoc.org/tags/defaultValue/

I don't know how to submit PRs to edit the content.

## Suggested Solution

Add an "Edit on GitHub" button on the bottom of each page.

**Comment by Gerrit0** [comment]
PR welcome! https://github.com/TypeStrong/typedoc-site/blob/master/tags/defaultValue.md is the file you were after.
