### ISSUE TITLE
Generation fails when switching from Resolve to Packages entryPointStrategy

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#1989]
I can confirm that this is affecting me as well.

[Minimum reproduction](https://github.com/citkane/typedoc-repros)
[Mr pull request](https://github.com/TypeStrong/typedoc-repros/pull/10)

**TypeDoc version**: 0.23.2

With `tsconfig.json` as the config location, and `entryPointStrategy` = `Resolve`, the documentation is created as expected (as in it builds correctly, but not in the desired structure).

When `entryPointStrategy`  = `Packages`, TypeDocs errors with:
```
error Unable to find any entry points. Make sure TypeDoc can find your tsconfig
```
#### tsconfig.json
```json
{
	"include": [
		"./packages/**/*.d.ts",
		"./packages/**/*"
	],
	"typedocOptions": {
		"entryPoints": [
			"./packages/users/src/mioUsers.ts",
			"./packages/tools/src/mioTools.ts"
		],
		"entryPointStrategy": "Packages",
		"plugin": [],
		"externalPattern": "**/node_modules/**",
		"excludeExternals": true,
		"out": "docs",
		"readme": "none"
	},
	"compilerOptions": {
            ...etc
	}
}
```

#### Root `package.json`
```json
{ 
 "name": "@mio/scaffold",
  "version": "0.0.0",
  "description": "The scaffold for mio microservice architecture",
  "main": "./src/mioScaffold.ts",
  "workspaces":[
    "packages/users",
    "packages/tools"
  ]
}
```
#### Typical package `package.json`
```json
{
  "name": "@mio/users",
  "main": "src/mioUsers",
  "typedocMain": "src/mioUsers"
}
```

I have tried a good few permutations without success, but am open to correction that I am not understanding the TypeDoc documentation, and that the problem is BSK :)

_Originally posted by @citkane in https://github.com/TypeStrong/typedoc/issues/1971#issuecomment-1177511075_

**Comment by Gerrit0** [comment]
@citkane there are two issues with your setup.

1. In packages mode, `entryPoints` should be paths to package directories, not actual files. The package.json in the provided packages will be used to determine what file is the entry point.
1. `typedocMain` may not omit an extension

I created https://github.com/TypeStrong/typedoc-repros/pull/11 based on your branch with these changes applied, and documentation generates successfully.

**Comment by Gerrit0** [comment]
I will mention though, that since you have a single tsconfig file, you probably don't want to use packages mode. With packages mode, TypeDoc will create a new `ts.Program` for every package, which isn't noticeable in this small repro, but could result in a huge slowdown for projects with many/large packages

**Comment by citkane** [comment]
Thanks for the help @Gerrit0. This is my first foray into TS, so thanks for your patience.

That all works, makes sense, and is wrapped up in the larger issue of the best way to set up a TS monorepo (outside the scope of TypeDocs). 

For the benefit of future readers, I found [this](https://github.com/Quramy/npm-ts-workspaces-example) TS monorepo example which was helpful in understanding some monorepo concepts.
