### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by KapuzenSohn** [TypeStrong/typedoc#199]
Hey, just wanted to ask if there is a chance that you add other persons to help you maintain this project?

The reason for this, like you see, is that you project is liked and wants to be used. I needed it for a project work and I had to change all Map, Promise from Angular and Ionic to any in order to compile the files. The outcome is awesome, so it would be nice if this project is more maintained.
I mean look at issues like #194 and #197, the people want to use it.

Also I think looking at #192 is not a bad thing.

Have a nice day ;)

**Comment by Guria** [comment]
@sebastian-lenz seems [not active on github about 4 month](https://github.com/sebastian-lenz?tab=contributions&from=2015-12-08). Unfortunately his profile doesn't have any contact information.
Maybe it is a time to start a fork under TypeStrong? 

cc @blakeembrey

**Comment by FlippieCoetser** [comment]
This is a very useful project! Thumbs up for doing a fork and get the latest typescript 1.8x working.

**Comment by Edward-Lombe** [comment]
@Guria @sebastian-lenz Seems to have made some comments about 10 days ago, but no contributions in the last four months.

**Comment by jasongrout** [comment]
CC also https://github.com/sebastian-lenz/typedoc/issues/162, where there is lots of discussion about updating to recent typescript releases.

**Comment by jasongrout** [comment]
One of the reasons typedoc is difficult to maintain is that it uses internal private typescript constants, etc. If you're thinking of a fork, this also looks like a very promising way to extract the typing/doc information: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker. It uses an unstable, but at least public and supported API. That should make maintenance across typescript releases much easier.

**Comment by KapuzenSohn** [comment]
I never really looked into the code. But thinking of it I wonder why it builds all files instead of just looking into all files and check for comments, classes, interfaces, ...
Maybe this is a easier way and also you are not bound to a typescript version. It can be that I oversee something and it is a must to compile the files.

**Comment by sebastian-lenz** [comment]
Hi everyone, I've left a comment regarding this topic in #192. I personally think it would be the best solution to move TypeDoc to TypeStrong.

**Comment by KapuzenSohn** [comment]
Very nice!
I think this can be closed.
