### ISSUE TITLE
Default to the package.json source field

### ISSUE THREAD

**Issue by jlarmstrongiv** [TypeStrong/typedoc#1991]
## Search Terms

Legacy typedoc entry point config (using "typedocMain" field) found for "". Please update to use "typedoc": { "entryPoint": "..." } instead. In future upgrade, "typedocMain" field will be ignored.

package.json source field

## Problem

Typedoc understandably needs to know where my source typescript files are.

## Suggested Solution

Use the defacto standard of the package.json.source field by default.  However, allow overriding the source field by using "typedoc": { "entryPoint": "..." }

The source field in the package.json points to the entry ts file and is used as a defacto standard.

Examples of the source field in the wild are:

- parcel 
  - docs https://parceljs.org/features/targets/#entries
  - > They can be specified on the CLI, or using the source field in package.json
- microbundle
  - readme https://github.com/developit/microbundle
  - > "source": "src/foo.js",             // your source code
- https://github.com/microsoft/TypeScript/issues/21423

**Comment by akphi** [comment]
I'm pretty sure if you don't specify either `typedocMain` or `typedoc.entryPoint`, we will resolve by `main` field

https://github.com/TypeStrong/typedoc/blob/5060fe23c9335f080e9ea16308c0c4f48c3f823c/src/lib/utils/package-manifest.ts#L243-L281

**Comment by jlarmstrongiv** [comment]
@akphi very interesting!  For me, the main field always refers to the compiled `dist/index.cjs`, rather than the typescript in the source field `src/index.ts`

**Comment by Gerrit0** [comment]
I'm somewhat wary of adding even more options for specifying source files without a very clear reason for making the already fairly complicated monorepo code even more so...

If your compiled source contains source maps, TypeDoc in packages mode will automatically resolve the compiled file back to the .ts file.

Another proposal for the use of the `typescript:main` key: https://github.com/microsoft/TypeScript/issues/12561

---

This `source` key doesn't seem very commonly used... I have a folder with the `1000-packages` dependency installed, which actually installs nearly 19,000 packages. Of these packages, a total of 23 use the `source` key.

**Comment by jlarmstrongiv** [comment]
@Gerrit0 alrighty, thank you for your consideration!
