### ISSUE TITLE
Private methods are always shown

### ISSUE THREAD

**Issue by DiFuks** [TypeStrong/typedoc#1992]
Private methods are always shown. Turning it off in settings doesn't work. This bug is reproduced even on the example page

https://typedoc.org/example/classes/Customer.html

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/12777199/177958951-f4d07fad-17df-40a3-8d6d-1e6640f66a25.png">

**Comment by Gerrit0** [comment]
😱 how did that happen!?

**Comment by DiFuks** [comment]
😅
