### ISSUE TITLE
re-open #111 (2015) every single class in project is NOT named `default`

### ISSUE THREAD

**Issue by dvtate** [TypeStrong/typedoc#1993]
## Search terms
This issue is previously defined as #111 `export default class Anything`.

## Expected Behavior

it should use name given to default exports instead of having multiple `default` identifiers. I do not care if it uses the name assigned to it in the `import` declaration or the name given in the `export default` binding (although the former makes most sense to me). 

It's very common in enterprise/OO codebases for each file to have a single `export default class UsefulName { ... }` however with typedoc literally everything will be called `default` and thus the generated documentation will be almost useless

## Actual Behavior

it uses multiple ambiguous `default` identifiers.

## Steps to reproduce the bug
self explanatory

## Environment
Note that I'm targeting esm and import statements end with `.js` because typescript is poorly designed, not sure if that's relevant
-   Typedoc version: 0.22.18
-   TypeScript version: 4.7.3
-   Node.js version: v18.3.0
-   OS: Linux archbook 5.18.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 16 Jun 2022 20:40:45 +0000 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/15305612/178129010-cbe0f379-612b-4e7d-9d45-146bbe81cb06.png)
![image](https://user-images.githubusercontent.com/15305612/178129017-b55335e2-a1f9-4135-a414-4cef6f6d93a3.png)

**Comment by Gerrit0** [comment]
https://www.npmjs.com/package/typedoc-plugin-rename-defaults

**Comment by Gerrit0** [comment]
The plugin above is the recommended way to handle this case. TypeDoc works by export names, for which `default` is the correct name.

**Comment by dvtate** [comment]
thanks!
