### ISSUE TITLE
bug: @link failing to resolve correctly linked interface (same with `[[]]` syntax in previous version)

### ISSUE THREAD

**Issue by tomfrenken** [TypeStrong/typedoc#1995]
## Search terms

@link [[]] failed to resolve

## Expected Behavior

In our monorepo we use use the following config to include one of our packages `http-client`:

```
{
  "extends": "./tsconfig.json",
  "include": [
    "./packages/http-client/**/*",
    "..."
  ],
  "exclude": ["**/*.spec.ts"],
  "references": [
    {
      "path": "./packages/http-client"
    },
    ...
  ],
  "typedocOptions": {
    "out": "docs/api/2.5.0",
    "entryPoints": [
      "packages/http-client/src/index.ts",
      "..."
    ],
    "...",
    "excludePrivate": true,
    "includes": "packages",
     "..."
  }
}

```

However, one of its interfaces can somehow not be linked, resulting in the following warning:
```
warning Failed to resolve {@link HttpResponse} in @sap-cloud-sdk/odata-common.DeleteRequestBuilderBase.executeRaw with declaration references. This link will break in v0.24.
```

the interface `HttpResponse` is exported and documented correctly, once in the index.ts of the http-client:
```
export {
  HttpResponse,
  ...
} from './http-client-types';
```

and again when it is defined:
```
/**
 * Represents an HTTP response, that contains response code, headers, payload and the original request.
 * This interface is compatible with AxiosResponse.
 */
export interface HttpResponse extends KnownHttpResponseFields {
  [otherKey: string]: any;
}
```

We would expect not to receive a warning here and it working correctly.

## Actual Behavior

We still receive the `failed to resolve` warning.

## Steps to reproduce the bug

The repository is open source, so you can simply clone it and run yarn doc.

Repo: https://github.com/SAP/cloud-sdk-js

Steps to reproduce: `yarn && yarn doc`

## Environment

-   Typedoc version: 0.23.7
-   TypeScript version: 4.7.4
-   Node.js version: 14.17.0
-   OS: latest macOS

**Comment by tomfrenken** [comment]
@Gerrit0 since you found the issue with #1986 super quick, can you think of anything causing the issue here too? 👀

**Comment by Gerrit0** [comment]
It sounds like you were relying on step 4 [described here](https://typedoc.org/guides/link-resolution/), which searches for names in a global list of all reflections.

Declaration references don't work like that. https://typedoc.org/guides/declaration-references/ describes how links are resolved. For that specific one, `{@link @sap-cloud-sdk/http-client!executeHttpRequest}` should do what you want
