### ISSUE TITLE
"Defined in" link for functions does not emit or render. Types and Variables work as expected.

### ISSUE THREAD

**Issue by citkane** [TypeStrong/typedoc#1996]
## Search terms
code link "Defined in" github

## Expected Behavior
The `Defined in` github link for functions should emit and render the same as variables, types, etc.

## Actual Behavior
The `Defined in` github link emits and renders for variables and types, but not for functions.

## Steps to reproduce the bug
[Minimal repo](https://github.com/citkane/yaf-scaffold)
[Pull Request](https://github.com/TypeStrong/typedoc-repros/pull/10)
[Example Doc Site](https://citkane.github.io/typedoc-repros/index.html)

## Environment

-   Typedoc version: 0.23.7
-   TypeScript version: 4.7.4
-   Node.js version: 16.16.0
-   OS: Ubuntu 22.04

**Comment by Gerrit0** [comment]
That's a weird one...

**Comment by citkane** [comment]
Strange indeed...

This appears to affect Typedoc's own demo documentation site as well:
- [function](https://typedoc.org/example/functions/sqrt.html): does not render
- [type](https://typedoc.org/example/types/SimpleTypeAlias.html): renders
- [variable](https://typedoc.org/example/variables/PI.html): renders

Are you closing this because it is expected behavior, or am I missing something else?

I am limiting the example to 'functions', 'types' and 'variables' to illustrate that some other things render, but 'functions' do not.  
I have not checked all other types for behavior.
