### ISSUE TITLE
URLs not working in {@link}

### ISSUE THREAD

**Issue by frank-weindel** [TypeStrong/typedoc#1998]
## Search terms

url link

## Expected Behavior

URLs in links to work like:
```
{@link http://www.google.com}
```

## Actual Behavior

Warning:
```
warning Failed to resolve {@link http://www.google.com} in MySymbol with declaration references. This link will break in v0.24.
```
## Steps to reproduce the bug

https://github.com/TypeStrong/typedoc-repros/pull/13

## Environment

-   Typedoc version: 0.23.7
-   TypeScript version: 4.7.3
-   Node.js version: v16.14.0
-   OS: macOS 12.2.1

**Comment by Gerrit0** [comment]
#1980
