### ISSUE TITLE
Generating docs for libs in NX Monorepo

### ISSUE THREAD

**Issue by phihochzwei** [TypeStrong/typedoc#2005]
## Search terms

NX, NRWL, Libraries, Monorepo

## Question

Hi there. I am trying to create a documentation for 2 Libs inside our NX Monorepo. Here´s how I tried it: 

1. Set typedoc.json to entryPointStrategy "packages"
2. Pointed the entryPoints to the respective folders "libs/store" and "libs/model"
3. Inside the respective package.json, I added the entry for "main" to "./src/index.ts"
4. Added `"typedoc": {
        "entryPoint": "./src/index.ts",
        "readmeFile": "./README.md",
        "displayName": "XXX"
    }` like described in the docs to the libs package.jsons

When I try to create the doc, I only receive the error

`Error: Entry point "C:\XXX\libs\model\src\index.ts" does not appear to be built by the tsconfig found at "C:/XXX/libs/model/tsconfig.json"`

Has anyone an idea what I am missing?

**Comment by Gerrit0** [comment]
That error means that `libs/model/tsconfig.json` specifies the `include` (or `files`) option such that the `libs/model/src/index.ts` file is not included in the program. If the file is included, this is probably a bug and I'll need a reproduction to try to fix it.

**Comment by phihochzwei** [comment]
Okay, after I added "srx/index.ts" to the "include" of the respective tsconfig.json´s it is creating the documentation.

However, now I am facing a different problem. I receive the "Warning"

`Warning: ModalDTO, defined at libs/model/src/lib/DTO/modal-dto.ts:47, is referenced by @deichmann/store.selectActiveModal but not included in the documentation.`  and if i check the generated documentation of the entry 'selectActiveModal' (located in 'libs/store') there is no link to the entry of 'ModalDTO' (located in 'libs/model')

Do you any clue on how to fix this?

**Comment by phihochzwei** [comment]
Okay, I keep an eye on the other issue. Thanks a lot so far
