### ISSUE TITLE
Empty modules with only top-level docstring are not included

### ISSUE THREAD

**Issue by eddyashton** [TypeStrong/typedoc#2007]
Re-opening #1948, as our empty module is still not documented after https://github.com/TypeStrong/typedoc/commit/7918fba658f92b8c585ae0c05add6cb645140d81.

After examining the proposed fix in v0.23 and our module, it looks like the difference is that your test case has an export, while our module has no exports. So this block does an early out:

```
        if (allExports.every((exp) => this.shouldIgnore(exp))) {
            this.owner.logger.verbose(`All members of ${entryName} are excluded, ignoring entry point.`);
            return;
        }
```

And sure enough we see that with verbose logging:

```
All members of polyfill are excluded, ignoring entry point.
```

An empty module with no exports, but a `@module` docstring, should be included, as it was before #1607.

**Comment by Gerrit0** [comment]
Hmmm.... this if was apparently added to fix the original bug with empty modules due to excludeNotDocumented. I guess it's probably okay to remove it...
