### ISSUE TITLE
Unminified version of JavaScript in minimal theme?

### ISSUE THREAD

**Issue by DavidKDeutsch** [TypeStrong/typedoc#201]
Is it possible to either acquire or generate an unminified version of the JavaScript that is embedded in the footer of index.html when using the minimal theme?

**Comment by sebastian-lenz** [comment]
Sure, you can find all theme sources right here:
https://github.com/sebastian-lenz/typedoc-default-themes

**Comment by blakeembrey** [comment]
Closing as answered.
