### ISSUE TITLE
Extra type parameter in output when documenting types with self-referential `extends` clauses

### ISSUE THREAD

**Issue by jmartinezmaes** [TypeStrong/typedoc#2013]
## Search terms

extra, duplicate, type, parameter, extends

## Expected Behavior

Given the interface

```ts
interface Foo<A> {
  foo(this: A, x: A): A
}
```

and the function

```ts
function foo<A extends Foo<A>>(x: A, y: A): A {
  return x.foo(y);
}
```

the documentation for the function `foo` should list a single type parameter `A extends Foo<A>`.

## Actual Behavior

The documentation for the function `foo` lists a single type parameter `A extends Foo<A, A>`.

## Steps to reproduce the bug

In an empty node project:

```bash
npm i -D typescript typedoc
npx tsc --init
echo "export interface Foo<A> { foo(this: A, that: A): A } export function foo<A extends Foo<A>>(x: A, y: A): A { return x.foo(y); }" > foo.ts
npx typedoc --out docs foo.ts
```

Then observe the generated documentation for the function `foo`:

![image](https://user-images.githubusercontent.com/37962558/180589801-a621feba-334c-4760-bcf7-0d9798d2032f.png)

## Environment

-   Typedoc version: 0.23.8
-   TypeScript version: 4.7.4
-   Node.js version: 16.16.0
-   OS: Windows 10

**Comment by Gerrit0** [comment]
oh right, `.typeParameters` sometimes lies... There's got to be a better way to get the real type parameters...

**Comment by Gerrit0** [comment]
Asked about this in the TS discord, hope to hear something from a team member next week: https://discord.com/channels/508357248330760243/640177429775777792/1000435413959331900

**Comment by jm4rtinez** [comment]
Hmm interesting. Thanks for the update, I'll follow along on Discord as well!

**Comment by Gerrit0** [comment]
It appears to be a bug in TS: https://github.com/microsoft/TypeScript/issues/50105

**Comment by Gerrit0** [comment]
Once https://github.com/microsoft/TypeScript/issues/50105 is resolved + released, upgrading TS will automatically pick this fix up on TypeDoc's side. Going to track over there instead.

**Comment by Gerrit0** [comment]
Eventual response from compiler team indicates that this is, in fact, a bug in TypeDoc.... asked for further clarification in the TS Discord.

**Comment by Gerrit0** [comment]
Sooooo... full circle, in TS 5.2.2, this works like I'd expect, which points back to this actually being a TS bug... I guess I'm just going to ignore this unless it comes back in another TS version?

**Comment by jmartinezmaes** [comment]
Interesting... I just experimented with TypeDoc 0.24.8 and TS 5.1.6 and the issue seems to have vanished as well.
