### ISSUE TITLE
JSX.Raw is not working well

### ISSUE THREAD

**Issue by matteobruni** [TypeStrong/typedoc#2014]
## Search terms

jsx raw empty

## Expected Behavior

Render the JSX.Raw tag as raw HTML text

## Actual Behavior

Render a JSX.Raw tag

## Steps to reproduce the bug

``` jsx
<style>
    {JSX.Raw({html:adsStyle})}
</style>
```

or

``` jsx
<style>
    <JSX.Raw html={adsStyle} />
</style>
```

[Code Reference](https://github.com/matteobruni/typedoc-carbon-ads-plugin/blob/0e43620302c13c5f7c8cd197d7aba8631e5c23cf/src/index.tsx#L82)

Both renders an empty `<style>` tag.

I'm currently using this:

``` jsx
<style>
        {adsStyle}
</style>
```

[Code Reference](https://github.com/matteobruni/typedoc-carbon-ads-plugin/blob/2d13286e2e969591c6ba946dee25034ee0605fcb/src/index.tsx#L18)

But it escapes some characters like quotes and single quotes, and it's a mess for font family names.

## Environment

-   Typedoc version: 0.23.9
-   TypeScript version: 4.7.4
-   Node.js version: 16.15.1
-   OS: macOS Ventura 13.0 (public beta, but I don't think this matters)

**Comment by Gerrit0** [comment]
The second method is how that's intended to be used:

https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/default/layouts/default.tsx#L30-L32

Do you receive the warning about multiple loads of TypeDoc? `JSX.Raw` is checked with reference equality, so if your theme is using a different TypeDoc installation, it won't work.

**Comment by matteobruni** [comment]
> The second method is how that's intended to be used:
> 
> https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/default/layouts/default.tsx#L30-L32
> 
> Do you receive the warning about multiple loads of TypeDoc? `JSX.Raw` is checked with reference equality, so if your theme is using a different TypeDoc installation, it won't work.

Yeah I got the warning but I don't know why, the warning is gone after a `yarn install`. Weird behavior but ok, not an issue.
