### ISSUE TITLE
Why is there a `<internal>` namespace for modules?

### ISSUE THREAD

**Issue by gamertike** [TypeStrong/typedoc#2018]
## Search terms

modules, monorepo, internal, <internal>, namespace

## Question

Why does my modules have a `<internal>` namespace?? It seems unnecessary because it only has docs for stuff already documented in other modules. 

![image](https://user-images.githubusercontent.com/84046635/181024093-d3b253eb-7ed0-4536-bb1b-3324e01ed001.png)

`typedoc.json`:
```json
{
	"$schema": "https://typedoc.org/schema.json",
	"name": "Guilded.TS",
	"entryPointStrategy": "packages",
	"entryPoints": ["packages/*"],
	"cleanOutputDir": true,
	"lightHighlightTheme": "github-light",
	"darkHighlightTheme": "github-dark",
	"excludeExternals": true,
	"excludeInternal": true,
	"excludePrivate": true,
	"media": "media",
	"out": "docs",
	"readme": "packages/guilded.ts/README.md",
	"tsconfig": "tsconfig.json",
	"hideGenerator": true,
	"cname": "guildedts.js.org"
}
```

Repo code if needed: https://github.com/guildedts/guilded.ts

**Comment by Gerrit0** [comment]
#1835 - cross package references aren't supported yet.
