### ISSUE TITLE
Documentation on constructor properties are not included in output

### ISSUE THREAD

**Issue by thopaw** [TypeStrong/typedoc#2019]
## Search terms

constructor properties

## Expected Behavior

Documented parameters within a constructor should also be documented in the output.

Is it possible to also use the doc added to the constructor property?

```
class A {
  constructor(
    /**
     * I want to see this comment in the documentation
     * /
     readonly property: string) {}
}
```

## Actual Behavior

The generated documentation does include the parameter `property` but does not include the documentation of the parameter.

I can add a doc to the constructor itself but I can not add the same options as documenting the property directly like

```
class A {
   /**
     * I want to see this comment in the documentation
     * /
  readonly property: string

}
```

## Steps to reproduce the bug

```
class A {
  constructor(
    /**
     * I want to see this comment in the documentation
     * /
     readonly property: string) {}
}
```

## Environment

```
> typedoc --version

TypeDoc 0.23.9
Using TypeScript 4.7.4 from ./node_modules/typescript/lib

> node --version
v16.14.0

```

-   OS: Ubuntu 20.04

**Comment by Gerrit0** [comment]
Seems reasonable to me :+1:
