### ISSUE TITLE
Custom theme added using defineTheme not getting recognized properly

### ISSUE THREAD

**Issue by Waryserpant122** [TypeStrong/typedoc#2025]
## Search terms
options theme custom

## Expected Behavior
When adding custom theme using 
```js
app.renderer.defineTheme(`custom`, SomeCustomTheme);
app.bootstrap({... , theme : "custom"})
```
The final output should render according to the theme

## Actual Behavior
Getting error
```
error The theme 'custom' is not defined. The available themes are: default, custom
```

## Environment
Typedoc version: 23.09
TypeScript version: 4.7.2
Node.js version: 16.13.0

**Comment by Gerrit0** [comment]
Can you set up a repro? This looks to me like `SomeCustomTheme` is undefined

**Comment by Waryserpant122** [comment]
Sorry for creating this issue. It was a mistake on my end. It was indeed ```SomeCustomTheme``` was undefined
