### ISSUE TITLE
@links not working in monorepo readmes

### ISSUE THREAD

**Issue by WHenderson** [TypeStrong/typedoc#2029]
## Expected Behavior

Links inside monorepo  readme files should resolve to typedoc links.

e.g.

`/packages/repo/README.md`
```
link to my function: {@link my_function}
```

Should generate page content similar to:

```
link to my function: <a href=".../functions/_my_repo.my_function.html">my_function</a>
```

## Actual Behavior

Omits the anchor tag, resulting in plain text with no link such as

```
link to my function: my_function
```

## Steps to reproduce the bug

1. [Create a mono-repo with a configured readme](https://typedoc.org/guides/monorepo/)
1. Add a `{@link my_function}`  to the readme, replacing `my_function` with a symbol name from your repo
1. Run typedoc and examine the output

## Environment

-   Typedoc version: 0.23.10
-   TypeScript version: 4.7.4
-   Node.js version: 16.13.2
-   OS: Windows

**Comment by Gerrit0** [comment]
Oops, introduced with https://github.com/TypeStrong/typedoc/commit/3830f9650ec7d2bc5e7b53bd28898f23fc6c5590. The LinkResolverPlugin no longer checks reflection.readme.
