### ISSUE TITLE
Package depends on typedoc-default-themes@0.4.0, which doesn't exist

### ISSUE THREAD

**Issue by WasabiFan** [TypeStrong/typedoc#203]
When I `npm install` from a clean clone of the TypeDoc repo, I get the following error:
```
Error: version not found: typedoc-default-themes@0.4.0
```

I can confirm that v0.4.0 does not exist on npm or even in the typedoc-default-themes repo. Additionally, a fair number of the tests fail when I modify the `package.json` to reference the newest publish release. @sebastian-lenz is it possible that this is a local version that you have that you forgot to push? Or am I misunderstanding something?

**Comment by enepomnyaschih** [comment]
+1

I've managed to build it successfully with 0.3.3, but TypeDoc displays the next errors in result (I don't know if it is related):

```
Error: Cannot find global type 'Array'.
Error: Cannot find global type 'Boolean'.
Error: Cannot find global type 'Function'.
Error: Cannot find global type 'IArguments'.
Error: Cannot find global type 'Number'.
Error: Cannot find global type 'Object'.
Error: Cannot find global type 'RegExp'.
Error: Cannot find global type 'String'.
```

**Comment by tht13** [comment]
See #204 for updates on this.
I believe the PR is resolving those global errors. They are also reverting to 0.3.4 for the theme and requesting access to the theme repo for maintenance on that as well.

**Comment by blakeembrey** [comment]
Closing as resolved. I've pushed the latest builds, and the latest themes.
