### ISSUE TITLE
@link within @param fails to resolve

### ISSUE THREAD

**Issue by frank-weindel** [TypeStrong/typedoc#2031]
## Search terms

link param 

## Expected Behavior

Linking (via `@link`) to a method by name from an `@param` of another method in the same class should work and not cause an error.

## Actual Behavior

This error is produced:
```
warning Failed to resolve {@link anotherMethod} in MyClass.aMethod.aParam with declaration references. This link will break in v0.24.
````

VSCode properly handles the link within the quick info UI

## Steps to reproduce the bug

Repro PR:
- TypeStrong/typedoc-repros#18

```ts
class MyClass {

  /**
   * Documentation for aMethod()
   *
   * This is OK: {@link anotherMethod}
   *
   * @param aParam But this produces an error: {@link anotherMethod}
   */
  aMethod(aParam: number) {

  }

  /**
   * Documentation for anotherMethod()
   */
  anotherMethod() {

  }
}
```

## Environment

-   Typedoc version: 0.23.10
-   TypeScript version: 4.7.3
-   Node.js version: v16.14.0
-   OS: macOS 12.2.1

**Comment by Gerrit0** [comment]
Thanks for the awesome bug report! Made fixing that really easy
