### ISSUE TITLE
TypeDoc has been loaded multiple times happening in a subfolder

### ISSUE THREAD

**Issue by matteobruni** [TypeStrong/typedoc#2034]
## Search terms

 TypeDoc has been loaded multiple times

## Expected Behavior

TypeDoc used in a subfolder should not load more than once like in the main folder

## Actual Behavior

If I run TypeDoc from a subfolder, I have the warning, in the root folder it works fine.

## Steps to reproduce the bug

I have a monorepo, and I installed TypeDoc in the root folder, because I'd like to have a single documentation for the whole repo, but it's not working for now (#1606).

Since the root TypeDoc can't generate the documentation, I still want to generate at least one project documentation, so I'm calling the root TypeDoc from a subfolder (direct subfolder, just one level) and I receive the warning.

[Main folder](https://github.com/matteobruni/tsparticles)
[Sub folder](https://github.com/matteobruni/tsparticles/tree/main/engine)

Only the main folder has TypeDoc installed (and the plugins), but only in the subfolder the warning is showing up.

## Environment

-   Typedoc version: 0.23.10
-   TypeScript version: 4.7.4
-   Node.js version: 16.15
-   OS: macOS 13

**Comment by Gerrit0** [comment]
Please create a smaller reproduction if possible - there is so much noise there to someone not familiar with the repo that the problem is easily lost in the noise. https://github.com/typestrong/typedoc-repros

**Comment by matteobruni** [comment]
Tried in another repository and all was ok.

Folder: ~/Projects/tests/test-typedoc-repro/

Tried again in my project and the issue was still there

Folder: ~/Projects/GitHub/tsparticles/

I activated verbose log level and I've seen that it was looking into ~/Projects/GitHub/typedoc (a fork of this repository), once this folder was deleted it worked on my project again.

I keep it open, maybe it's not intended to work this way, if you want to close this @Gerrit0, as you prefer, I don't think a lot of users will have a fork in their machine.

**Comment by Gerrit0** [comment]
Ah, sounds to me like you maybe have a `npm link`ed version. There's nothing wrong with TypeDoc - this warning is just informative that stuff like `instanceof` will be broken, and cause likely broken results. How modules are loaded is entirely up to your package manager. I'll update the warning in the next version to also print info about what was loaded.

If you delete your node_modules in both the root and project folder, then reinstall, I bet your tsparticles one will work too.

**Comment by DominicGBauer** [comment]
OMG I had this issue because of yarn workspaces dependency handling. Kept getting `TypeDoc has been loaded multiple times. This is commonly caused by plugins which have their own installation of TypeDoc` for all the packages that were being used.
