### ISSUE TITLE
What's the best way to document a dynamic set of default values for an `options`-style parameter?

### ISSUE THREAD

**Issue by gnidan** [TypeStrong/typedoc#2041]
## Search terms

default value options object

## Question

The main entrypoint for my library is a function that takes one big `options` argument with mostly optional properties. I keep the defaults in an object like so:
```typescript
export const defaultOptions = {
  // excludes required options
  a: 1,
  b: 2,
  /* ... */
}
```

and then I do this to fill in the options:
```typescript
export const generate = (options: Options) => {
  const {
    requiredProperty,
    a = defaultOptions.a,
    b = defaultOptions.b,
    /* ... */
  } = options;
```

I expected these values to show up in the documentation for `defaultOptions`, but here's what I get:

<img width="990" alt="Screen Shot 2022-08-26 at 9 43 44 PM" src="https://user-images.githubusercontent.com/151065/187009369-1d6365b4-545b-4240-903e-0c7e1633950d.png">

Is there any way for me to get these values to show up nicely?

Thanks!

**Comment by Gerrit0** [comment]
TypeDoc [tries to](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/convert-expression.ts#L20) display initializer values which are "simple" this is because some initializers (particularly stuff where people use `React.FC`) result in *awful* documentation if they are included.

If this doesn't apply for your project, you can fairly easily overwrite the default value with a plugin:

```sh
$ typedoc src/index.ts --plugin ./path/to/default-objects.js
```

```js
// @ts-check
const td = require("typedoc");

exports.load = function ({ application }) {
    /** @type {Map<td.DeclarationReflection, string>} */
    const defaultValues = new Map();

    const printer = td.TypeScript.createPrinter({ removeComments: true, omitTrailingSemicolon: true });

    application.converter.on(
        td.Converter.EVENT_CREATE_DECLARATION,
        /**
         *
         * @param {td.Context} context
         * @param {td.DeclarationReflection} reflection
         */
        (context, reflection) => {
            const symbol = context.project.getSymbolFromReflection(reflection);
            if (!symbol) return;

            const decl = symbol.getDeclarations()?.find(td.TypeScript.isVariableDeclaration);
            if (!decl || !decl.initializer) return;

            if (decl.initializer.kind === td.TypeScript.SyntaxKind.ObjectLiteralExpression) {
                // Unfortunately can't just set defaultValue right here, this happens before TD sets it.
                defaultValues.set(
                    reflection,
                    printer.printNode(td.TypeScript.EmitHint.Expression, decl.initializer, decl.getSourceFile())
                );
            }
        }
    );

    application.converter.on(td.Converter.EVENT_RESOLVE_BEGIN, () => {
        for (const [refl, init] of defaultValues) {
            refl.defaultValue = init;
        }
        defaultValues.clear();
    });
};
```

**Comment by gnidan** [comment]
Awesome, thank you @Gerrit0 for the pointer! I think this will work to get the dynamic value for those defaults as defined by the code.

Quick follow-up question: let's say I want to format Markdown instead of `defaultValue`. How would I do that? Like, I'm not keen to stuff a bunch of values into an unstructured object, since that won't display very nicely. Instead, I'd like to read those defaults inside a plugin and then craft the doc comment for the function to format those defaults automatically.

I'll continue playing around, but all these years of being a casual TypeDoc observer and I still can't figure out your arcane system of reflections 😭

**Comment by Gerrit0** [comment]
You'll want to modify/create [DeclarationReflection#comment](https://typedoc.org/api/classes/DeclarationReflection.html#comment). Adding a single `{ kind: "text", text: "<generated content>" }` to `reflection.comment.summary` is probably the way to go.
