### ISSUE TITLE
Callable variables use signature comment instead of variable comment

### ISSUE THREAD

**Issue by VorontsovMaxim** [TypeStrong/typedoc#2042]
## Search terms

Callable variable object property

## Expected Behavior

Written callable variable documentation should be included in the HTML output.

## Actual Behavior

Written callable variable documentation is not included in the HTML output.

## Steps to reproduce the bug

```typescript
const obj = {
    /** function-docs */
    fn(x: unknown) {}
}

/**
 * exported-docs
 * @param x param-docs
 */
export const bug = obj.fn;
```

Only _function-docs_ string is included in the HTML output, but not _exported-docs_ string, neither as _param-docs_ string.

But when you remove docs of function declaration _exported-docs_ and _param-docs_ appears in the HTML output.
```typescript
const obj = {
    fn(x: unknown) {}
}

/**
 * exported-docs
 * @param x param-docs
 */
export const bug = obj.fn;
```

Here's repro PR: https://github.com/TypeStrong/typedoc-repros/pull/20

## Environment

-   Typedoc version: 0.23.11
-   TypeScript version: 4.8.2
-   Node.js version: 16.17.0
-   OS: macOS 12.4

**Comment by Gerrit0** [comment]
Hmm... this is going to be an annoying one to fix, because fixing this could easily break other usages where pulling the comment from the signature is expected.

**Comment by VorontsovMaxim** [comment]
We haven't control over `obj` because it's autogenerated, but still want to document exported functions. So maybe there are some workarounds to get desired behaviour?

Also i just found one more similar problem with factory functions:
```typescript
function factory() {
    /** function-docs */
    function fn() {};

    return fn;
}

/** exported-docs */
export const bug = factory();
```
