### ISSUE TITLE
Search bar header off-centre on displays wider than 1990px (approx)

### ISSUE THREAD

**Issue by toebeann** [TypeStrong/typedoc#2046]
## Search terms

header, search bar, large displays, ultrawide, 1440p, 2K, 4K, off-centre, off-center

## Expected Behavior

typedoc seems to intend to have the header display centred on the page as below:
![image](https://user-images.githubusercontent.com/45315526/187439066-7387391e-6b95-4922-94eb-dbabd833e05c.png)
![image](https://user-images.githubusercontent.com/45315526/187441720-0db4cc25-5b85-4bed-bc73-174ab345dbe6.png)

## Actual Behavior

This is at a width of 3440px, but the header goes off-centre from a width of approx. 1990px and up:
![image](https://user-images.githubusercontent.com/45315526/187438856-07042b4a-4160-4bad-b471-9c8a75a17968.png)
![image](https://user-images.githubusercontent.com/45315526/187441853-655b4e47-6ffa-4211-b3f8-309f72ccc9fd.png)

## Steps to reproduce the bug

- Open the latest [typedoc example project](https://typedoc.org/example) on a display with a width greater than approx 1990px (e.g. 1440p, 4K, most ultrawide displays, etc.)
- Maximise browser window

Issue is prevalent in both Firefox and Chrome, haven't tested others.
Seems to only go off-centre around an approximate width of 1990px.

I understand you generally require a minimal typedoc install repo for this, however I have tested this on multiple of my repos using typedoc and it is happening on all, including [the typedoc example project](https://typedoc.org/example/).

## Environment

-   Typedoc version: 0.23.11
-   TypeScript version: 4.8.2
-   Node.js version: 16.16.0
-   OS: Windows 11 (10.0.22000 Build 22000)

**Comment by Gerrit0** [comment]
In this case a minimal repro could just point at https://typedoc.org/api/ and say zoom out ;)

**Comment by Gerrit0** [comment]
... just noticed I put the css on the wrong element

**Comment by Gerrit0** [comment]
c72c75ca9c03cf5206094f9b2e3774851eafe25a
