### ISSUE TITLE
DeprecationWarning: 'isIdentifierOrPrivateIdentifier' has been deprecated since v4.2.0. Use `isMemberName` instead.

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#2047]
## Search terms

DeprecationWarning, isIdentifierOrPrivateIdentifier deprecated

## Expected Behavior

No warning

## Actual Behavior

TypeDoc shows the following warning when running on TypeScript 4.8.2

## Environment

-   Typedoc version: 0.23.11
-   TypeScript version: 4.8.2
-   Node.js version: 18.8.0
-   OS: macOS 12.5.1

**Comment by Gerrit0** [comment]
Fixed by 877e1a74ee96fd2cc75de19a139b08eed37fbe80, just haven't made a release yet
