### ISSUE TITLE
Help generating docs from collection of nested index.d.ts and tsconfig.json files

### ISSUE THREAD

**Issue by fartinmartin** [TypeStrong/typedoc#2048]
## Search terms

Help generating docs from collection of nested `index.d.ts` and `tsconfig.json` files.

## Question

I am attempting to create TypeDoc documentation from the [`Types-for-Adobe`](https://github.com/aenhancers/Types-for-Adobe) repo.

I am able to successfully generate docs if I `cd` into specific sub-directories (see my [`ae-types` branch](https://github.com/fartinmartin/Types-for-Adobe/tree/ae-types/AfterEffects/18.0/docs)), but would ideally like to generate a single `./docs` folder at the root of the project. If possible, I would also like each entry point to be represented as a "module" in the menu of the generated docs website, rather than the single "types-for-adobe" that shows up in my example.

Also, I'd like to propose this change to the maintainers of the `Types-for-Adobe` repo and would therefore like to achieve this with minimal disruption of files/workflow. Is this possible? 

My current approach is to list each `index.d.ts` file as an `entryPoint` in a `typedoc.js` options file (seen in [my fork of the project](https://github.com/fartinmartin/Types-for-Adobe/tree/master)). But, this results in: 

```error Unable to find any entry points. Make sure TypeDoc can find your tsconfig```

How do I make sure TypeDoc can find each `index.d.ts` respective `tsconfig.json` files? I've tried switching `entryPointStrategy` to each of the options but have had no luck.

**Comment by Gerrit0** [comment]
TypeDoc supports `packages` as an entry point strategy for handling projects with multiple tsconfig files, but using that requires a package.json file for each dependent package. In this case, I'd probably recommend a script which generates them in each documented directory, and then cleans up after itself when complete.

https://github.com/fartinmartin/Types-for-Adobe/pull/1

**Comment by fartinmartin** [comment]
Awesome—thank you for taking a look! I will close for now and work on a script as you describe. I'll come back to comment my solution or re-open if necessary.

**Comment by fartinmartin** [comment]
Ha! Didn't see that you wrote [that script](https://github.com/fartinmartin/Types-for-Adobe/blob/f7884c4238795cb44753067be048d3b3eba62020/_bin/docs.sh) for me—thanks so much!
