### ISSUE TITLE
`@type {import('file').Type}` not supported, while typescript says it is the official way

### ISSUE THREAD

**Issue by hasezoey** [TypeStrong/typedoc#2050]
## Search Terms

typescript import type

## Problem

Currently typedoc errors for `{import('file').Type}` with:

```txt
[Error [TypeLexerSyntaxError]: Expected "!", "#", ".", ".<", "<", "=", "?", "[]", "|", "~", [ \t\r\n ], [a-zA-Z0-9_$] or end of input but "(" found.:
import('./index.js').CustomType
     ^]
```

while typescript offically says that it is the right way to import types

[Typescript 4.8 Changelog Example Code](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#types-cannot-be-imported-exported-in-javascript-files)

## Suggested Solution

Implement `import()` capability

---

Tested on typedoc `0.23.13`

**Comment by Gerrit0** [comment]
That error isn't coming from TypeDoc - are you sure TypeDoc is using the version of TS you think it is? Try running with --version

**Comment by hasezoey** [comment]
> That error isn't coming from TypeDoc - are you sure TypeDoc is using the version of TS you think it is? Try running with --version

```txt
TypeDoc 0.23.13
Using TypeScript 4.8.2 from ./node_modules/typescript/lib
```

**Comment by Gerrit0** [comment]
Seems to be working correctly for me, I'll need a reproduction.

https://github.com/TypeStrong/typedoc-repros/runs/8169270507?check_suite_focus=true - run says failure but you can see by the logs that it did complete type checking and conversion.

**Comment by hasezoey** [comment]
> Seems to be working correctly for me, I'll need a reproduction.

the project and branch are public at https://github.com/hasezoey/mongoose/tree/typedocRepro (not minimal though simple to show the changes / install)

instructions:
- clone and enter the repository
- run `npm install`
- run `npm run docs:generate` observe the error

The file that has the type is `lib/index.js` (almost at the end of the file) and the import is in `lib/schema.js` (at the end of the file)

**Comment by Gerrit0** [comment]
> skipErrorChecking:true

I do not investigate projects which have this turned on as mentioned in the bug report template. The compiler api isn't consistent if errors are present and this option is off.

**Comment by hasezoey** [comment]
> I do not investigate projects which have this turned on as mentioned in the bug report template. The compiler api isn't consistent if errors are present and this option is off.

sorry it seems i have ignored template comments out of habit, thanks for telling instead of just closing

thanks for pointing this out, though sadly i would not be able to use typedoc in that project without that option, because otherwise typescript would give out way too many errors (even with `strict: false`) and some of them would not even be fixable with the current conventions the projects has (or backwards breaking)

also, vscode uses the same typescript but does not error and the types still work, is there anything i can do in typedoc to do the same?

**Comment by Gerrit0** [comment]
Looked slightly more closely at what you're doing and... it doesn't make sense to me. Mongoose defines its types in types/index.d.ts, so you should be running on that instead of on the source code in lib. I checked out `master`, made the following changes, and ran `npx typedoc types/index.d.ts --out docs2`, which gave me output.

```diff
diff --git a/package.json b/package.json
index 391c2e7..3f998d4 100644
--- a/package.json
+++ b/package.json
@@ -62,6 +62,7 @@
     "stream-browserify": "3.0.0",
     "ts-benchmark": "^1.1.10",
     "tsd": "0.20.0",
+    "typedoc": "^0.23.14",
     "typescript": "4.7.4",
     "uuid": "8.3.2",
     "webpack": "5.74.0"
diff --git a/tsconfig.json b/tsconfig.json
index 10f087f..47c3481 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -5,5 +5,6 @@
     "paths": {
       "mongoose" : ["./types/index.d.ts"]
     }
-  }
+  },
+  "exclude": ["test"]
 }
```

**Comment by hasezoey** [comment]
> Looked slightly more closely at what you're doing and... it doesn't make sense to me. Mongoose defines its types in types/index.d.ts,

that is correct, though i was looking for a replacement for [`dox`](https://www.npmjs.com/package/dox) and though i could use typedoc (especially because it would allow referencing types from other files<sup>1</sup>) while the code is still in only-js form. i was looking for a replacement because other jsdoc parsers seem to not be updated anymore and are outdated (dependency wise) and the only "similar" package i could think of was typedoc, so i wanted to try that

see:
- [`website.js`](https://github.com/hasezoey/mongoose/blob/typedocRepro/scripts/website.js) (the script that starts generating the static files for the documentation and calls `api.js`)
- [`api.js`](https://github.com/hasezoey/mongoose/blob/typedocRepro/docs/source/api.js) (the script that generates documentation based on the source-code)

note: i was not using typedoc's built-in html-generation, because i wanted to keep the style the same as before (only replace which package looked through the code)

<sup>1</sup>: we currently also use intellisense to make the js code easier to use (inside the package itself while developing), and typedoc (being reliant on typescript) would bring it in line with what intellisense would be capable of while also having the documentation work (like not ignoring `typedef` and being able to use stuff like `import`)

**Comment by Gerrit0** [comment]
```diff
diff --git a/tsconfig.json b/tsconfig.json
index 10f087f..d6835eb 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -2,8 +2,10 @@
   "compilerOptions": {
     "strict": true,
     "strictNullChecks": true,
+    "allowJs": true,
     "paths": {
       "mongoose" : ["./types/index.d.ts"]
     }
-  }
+  },
+  "include": ["lib"]
 }
```

I made the following changes, which let `npx tsc --project tsconfig.json --noEmit` compile without errors. With these changes, `npx typedoc --tsconfig tsconfig.json --json out.json` worked as expected.

If `npx tsc --noEmit` exits with no errors, TypeDoc should also be able to parse as expected.
