### ISSUE TITLE
Whether `typedoc` can generate `Markdown` files according to the directory structure

### ISSUE THREAD

**Issue by He110te4m** [TypeStrong/typedoc#2058]
## Search terms

markdown, generate, directory structure

## Question

I'm writing Vue 3's Component Library, which has some hooks (the TS function) . The comments within the component are parsed by the AST and extracted into a Markdown file that is rendered by VitePress, which is generated according to the directory structure. However, when Typedoc is generated, it prints everything to a file. This is very difficult to process and display in a component library.

Whether `typedoc` can generate `Markdown` files according to the directory structure?

**Comment by Gerrit0** [comment]
TypeDoc itself can't generate markdown, though typedoc-plugin-markdown adds support for doing that. I haven't used it... whether this is possible is entirely up to that plugin. I'd try running with entryPointStrategy set to expand.
