### ISSUE TITLE
Automatic renaming of functions as `function-1.html`

### ISSUE THREAD

**Issue by wolfram77** [TypeStrong/typedoc#2059]
## Search terms

auto-rename, rename, symbol, function, dash, one.

## Question

I use typedoc to generate HTML documentation and link to them from README so i need to know the URLs for each symbol. This works for most functions, but not for some others.

Here is an example of the link i generate for `orderValidity` function:
```
https://nodef.github.io/ext ra-fyers/functions/orderValidity.html
```

But the HTML file is actually named as `orderValidity-1.html`:
```
https://nodef.github.io/extra-fyers/functions/orderValidity-1.html
```

My guess `typedoc` is doing this because there is also a type named `OrderValidity`. However this should not be an issue as types are stored on a different path from functions. Is there a way i can avoid HTML file renameing?

**Comment by futurGH** [comment]
Here's the responsible code & reasoning if you're curious. https://github.com/TypeStrong/typedoc/blob/e50cd273366977d1e06eac782806a5c6bc49f223/src/lib/models/reflections/abstract.ts#L416-L434

You might be able to pass in a custom theme that overrides [`DefaultTheme.getUrl`](https://github.com/TypeStrong/typedoc/blob/e4fbb1c63c242631da966b1bfbfbe16f6b997c5b/src/lib/output/themes/default/DefaultTheme.tsx#L170) to trim out the suffix. It is worth noting that these paths also have to exist as filenames on your system, so you'll want to think twice before making such a change if you might ever need TypeDoc's output to end up on a machine using one of the filesystems mentioned at the start of the above snippet.

**Comment by Gerrit0** [comment]
A built in way - nope, futurGH is absolutely correct. In this case, you're right, the default theme puts those files in different directories, but a theme could override this, so until that method moves to the theme (where it really belongs), it can't make assumptions about where different types are rendered to.

**Comment by wolfram77** [comment]
Thanks @futurGH for insight to code, and suggesting to override `DefaultTheme.getUrl`. I am currently trying it as follows, but it does not generate any file other than `index.html` and `modules.html`.

```typescript
import {Application, DefaultTheme, Reflection} from "typedoc";


// Modify the default theme.
class ExtraTypedocTheme extends DefaultTheme {
  // Remove url suffix (function-1.html → function.html).
  static getUrl(reflection: Reflection, relative?: Reflection, separator?: string): string {
    var url = DefaultTheme.getUrl(reflection, relative, separator);
    return url.replace(/\-\d+(\.\w+)?/, "$1");
  }
}


// Define the theme.
export function load(app: Application) {
  app.renderer.defineTheme("extra-typedoc-theme", ExtraTypedocTheme);
}
```

Could you point out what i am doing wrong here?
