### ISSUE TITLE
Excluding directory doesn't work

### ISSUE THREAD

**Issue by sweco-sevsma** [TypeStrong/typedoc#2060]
## Search terms

exlude error --exclude

## Expected Behavior

I expect to be able to put files and or directories in the "exclude" option in order to exclude these files and folders.

## Actual Behavior

Tries to run or create documentation over files in an excluded folder.

## Steps to reproduce the bug

1. Create an multi project angular workspace (https://angular.io/guide/file-structure)
2. Install typedoc to dev dependencies and add a typedoc.json in the root folder.
3. Generate an example project
4. Add code in a subfolder and add it to the exclude list
5.  Run typedoc

Config file I have:
```
{
    "out": "dist/docs",
    "theme": "default",
    "entryPointStrategy": "expand",
    "excludeInternal": true,
    "excludePrivate": true,
    "hideGenerator": true,
    "exclude": [
        "**/*.spec.ts",
        "**/node_modules",
        "node_modules",
        "myspecial-folder"
    ],
    "entryPoints": [
        "projects/comp-lib/src"
    ]
}
```` 

As an example here we use babylonjs and it's ion the excluded node_modules but it still gives errors with other files in other excluded paths. It doesn't really matter what I put in there. It doesn't matter if I use it via the command line or as an array in the config file. The result is the same.

![image](https://user-images.githubusercontent.com/111854276/191959345-bedfad80-3c86-40a8-a2c2-c0aab36e4cb4.png)

## Environment

-   Typedoc version: 0.23.15
-   TypeScript version: 4.8.2
-   Node.js version: 16.17.0
-   OS: Windows 10

**Comment by Gerrit0** [comment]
The `exclude` option is only used to remove files from consideration as entry points. Unlike TypeScript's exclude option, it cannot be used to exclude files from compilation. You may want to turn on TypeScript's [--skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) if you have compilation errors originating in @types packages. This is working as intended, as `npx tsc --noEmit` would have the same result.
