### ISSUE TITLE
Allow to specify a custom `tsconfig` in packages mode for monorepos

### ISSUE THREAD

**Issue by avchugaev** [TypeStrong/typedoc#2061]
## Search Terms

Monorepo, tsconfig, custom path

## Problem

When operating in monorepo mode (multiple packages), each package may contain several `tsconfig` files. 
For instance, Nx generates 3 `tsconfig` files per TypeScript project:

- `tsconfig.json` - base configuration, extends workspace's root `tsconfig`;
- `tsconfig.lib.json` - production code configuration, extends package's `tsconfig.json`;
- `tsconfig.spec.json` - tests configuration, extends package's `tsconfig.json`.

When one generates documentation for several packages, TypeDoc uses `tsconfig.json` instead of desired `tsconfig.lib.json` without ability to override the file name (or location).

## Suggested Solution

Allow to override package's `tsconfig` file name (location) via `package.json` settings:

```json
{
  "name": "@org/package-a",
  "typedoc": {
    "entryPoint": "./src/index.ts",
    "readmeFile": "./README.md",
    "tsconfig": "./tsconfig.lib.json"
  }
}
```

So that TypeDoc will be more monorepo-friendly and multi-config-friendly.

**Comment by Zinyon** [comment]
I have same problem on generating docs with nx projects.
hope this feature applies.

**Comment by avchugaev** [comment]
@Zinyon Hi! Just curious, do you publish the resulting API reference to GitHub pages?

**Comment by Zinyon** [comment]
@avchugaev Hi!, i'm considering it, but haven't tried yet.
have you tried?

**Comment by avchugaev** [comment]
> @avchugaev Hi!, i'm considering it, but haven't tried yet. have you tried?

Yep, I managed to generate docs for all libraries from Nx workspace and deploy them to GitHub pages.

- [Repository](https://github.com/monumentjs/workspace)
- [Deployed documentation](https://monumentjs.github.io/workspace)

But to achieve this, I had to rename `tsconfig*` files in every library so that TypeDoc resolved the right `tsconfig.json`. So it pushed me to override default configs generated and maintained by Nx.

**Comment by avchugaev** [comment]
@Gerrit0 I'd try to implement it, but I need help understanding the codebase and solution design.

**Comment by avchugaev** [comment]
@Gerrit0 thanks for the feature 🤝 Please check the site build - https://github.com/TypeStrong/typedoc-site/actions/runs/3230626041/jobs/5289289873

There's still a previous version of the docs on the website:
![Screenshot from 2022-10-12 15-01-16](https://user-images.githubusercontent.com/6230776/195337389-af12b760-21be-4f99-bab6-fc404fef1d8f.png)

**Comment by Gerrit0** [comment]
Huh, surprised that didn't give me an email about a failing build... thanks!
