### ISSUE TITLE
Using typedoc without specific entryPoint

### ISSUE THREAD

**Issue by JenniferFalkenstein** [TypeStrong/typedoc#2062]
## Search terms
entryPoint, without index, electron, electron-react-boilerplate, react

## Question
We use the [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) in our project, which looks something like this:
![Bildschirmfoto 2022-09-27 um 16 03 31](https://user-images.githubusercontent.com/80680536/192548264-2834dc27-da2e-40db-80ce-74420358b471.png)
Now, I don't know what I should take as an `entryPoint`, since `.tsx` files doesn't seem to be supported (according to [this PR here](https://github.com/TypeStrong/typedoc/issues/1856#issuecomment-1022200708)) but the [main.ts](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/src/main/main.ts) doesn't seem to be the correct entryPoint as well.
I also don't quite understand why we even need an entryPoint. Shouldn't typedoc go through all files and search for function-declarations, etc. to document? Could you explain it to me, so I understand the tool better? 🙂

**Comment by futurGH** [comment]
TypeDoc tries to document the exported API surface of a package, so by default it needs at least 1 entry point file to document all exports from. You might want to try setting `entryPointStrategy` to `expand` and passing 1 or more directories as entry points; that will recursively expand all directories in the provided entry point(s) and document every *exported* symbol in each file.
