### ISSUE TITLE
ESLint rules to enforce TypeDoc?

### ISSUE THREAD

**Issue by hangboss1761** [TypeStrong/typedoc#2063]
## Search terms

eslint plugin、eslint-plugin-typedoc

## Question
just like [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc)

**Comment by Gerrit0** [comment]
The plugin you linked looks like it can be used in TS projects... there's not really a reason for TypeDoc to duplicate work done there I think

**Comment by hangboss1761** [comment]
> The plugin you linked looks like it can be used in TS projects... there's not really a reason for TypeDoc to duplicate work done there I think

Thank you for the reply！ 

It looks like you said，these rules in eslint-plugin-jsdoc is enough for most scenarios:

```
rules: {
  'jsdoc/require-jsdoc': 2,
  'jsdoc/require-description': 2,
  'jsdoc/require-returns': 2,
  'jsdoc/require-returns-description': 2,
}
```
