### ISSUE TITLE
Private properties declared in constructor assignment are not documented

### ISSUE THREAD

**Issue by rhuitl** [TypeStrong/typedoc#2064]
## Search terms

constructor assignment, private property / field, not extracted

## Expected Behavior

Private properties declared in a constructor assignment should be documented just like protected and public ones.

## Actual Behavior

Private properties declared in a constructor assignment are not extracted.

## Steps to reproduce the bug

https://github.com/TypeStrong/typedoc-repros/pull/22

One out of the six declared properties is not documented:
![Bildschirmfoto 2022-09-28 um 15 38 26](https://user-images.githubusercontent.com/429519/192796084-3d9dd0c6-60ca-441d-95eb-ca2efc619099.png)

## Environment

-   Typedoc version: 0.23.15
-   TypeScript version: 4.8.4
-   Node.js version: v14.20.0
-   OS: MacOS

**Comment by Gerrit0** [comment]
O.o that's a weird one
