### ISSUE TITLE
Allow to configure common readmeFile when creating documentation from monorepo

### ISSUE THREAD

**Issue by Hi-Fi** [TypeStrong/typedoc#2065]
## Search Terms

readmeFile, documentation, README, packages, monorepo

## Problem

Currently documentation from module's main page in monorepo documetantion is left out unless explicitly defined in package.json with `readmeFile`. This feels a bit ugly solution, as readme file is quite often `README.md` (or anyway same in all modules inside monorepo.

## Suggested Solution

I think it would be nice to have either
- Automatic usage of README.md (maybe case insensitive way) from module directory; or
- Common flag to set file name, which is then used from each module's directory

**Comment by Gerrit0** [comment]
I don't love flags if there's a reasonable default - I like the idea of grabbing the readme.
