### ISSUE TITLE
namespace + value not working

### ISSUE THREAD

**Issue by unional** [TypeStrong/typedoc#2069]
## Search terms

namespace

## Expected Behavior

```ts
export namespace foo {
  export type Options = { a: number }
}

export function foo(options: foo.Options) {
}
```

This should both `namespace` and `function`.

## Actual Behavior

It generates `namespace` only.

## Steps to reproduce the bug

https://github.com/unional/typedoc-repros

## Environment

-   Typedoc version: 0.23.15
-   TypeScript version: 4.8.4
-   Node.js version: 16.16.0
-   OS: Windows

**Comment by FredLL-Avaiga** [comment]
I also have an issue with functions not being generated by 0.23.15 (they are generated by 0.23.14)

**Comment by Gerrit0** [comment]
I can't reproduce this. I ran typedoc on that input file, and the output documentation for both the function and the namespace.

![image](https://user-images.githubusercontent.com/19329837/194733586-cc1ee7c7-68bd-4d79-8e51-16a746bdfafa.png)

**Comment by unional** [comment]
I found out what is the issue.
![image](https://user-images.githubusercontent.com/3254987/194745350-37b7cf57-25dd-4b61-833d-2fc92badde46.png)

The issue is that the navigation on the right list the modules and namespaces in a tree, while the function and other stuff at the bottom.
So when I click on the `foo`, it goes to the namespace and does not show the function `foo`.

That might be ok for small repository.

In my actual project, it is a monorepo with many packages. So I didn't see the function at the bottom.

Here is the typedoc of that repo:

https://justland.github.io/just-web/modules.html


And here, you can see at the bottom there are both namespace `createApp` and function `createApp`
https://justland.github.io/just-web/modules/_just_web_app.html

![image](https://user-images.githubusercontent.com/3254987/194745502-53f6f20f-b239-4bee-bd5a-8405606c4d28.png)

However, on the navigation, that is much longer:
![image](https://user-images.githubusercontent.com/3254987/194745515-59f81494-6cf0-4827-a208-7a8e011ccdc0.png)

I have to scroll that to the bottom to see the functions:
![image](https://user-images.githubusercontent.com/3254987/194745531-65d496dd-ff67-4462-a8d8-fc8633f189ed.png)

**Comment by Gerrit0** [comment]
You could write a custom theme that just overwrites the navigation helpers in order to change this behavior, but it's working as intended today.
