### ISSUE TITLE
Allow reading package information also from lerna.json

### ISSUE THREAD

**Issue by Hi-Fi** [TypeStrong/typedoc#2071]
## Search Terms

lerna, monorepo, projen

## Problem

Currently using entrypoint strategy "packages" information about packages is expected to be found from package.json. When using Projen and Lerna with https://github.com/AminFazlMondo/Lerna-Projen information is only at Lerna's configuration, not on package.json.

## Suggested Solution

Allow getting the package information from `lerna.json`. I think no flag needed, but it would be checked if `package.json` doesn't contain the info (or merge those sources).

**Comment by Gerrit0** [comment]
This is probably going to be a wont-implement. TypeDoc supports passing the package directory (or glob) directly to it, only really supporting reading workspaces as a convenience method for people using standard tooling. Reading configuration meant for other tools means that TypeDoc has to be kept up to date with any format changes, makes figuring out where TypeDoc got its configuration from harder, and opens up a rabbit hole of "why didn't it read this tool specific config file?"

- Nx's nx.json
- pnpm's pnpm-workspace.yaml
- Rush Stack's rush.json
- ... other monorepo manager tools

**Comment by Hi-Fi** [comment]
@Gerrit0 Thank you, I agree with you that it'll easily open requests for many other ways.
