### ISSUE TITLE
is it possible to create docs from npm packages inside node_modules?

### ISSUE THREAD

**Issue by CaveMa** [TypeStrong/typedoc#2075]
is it possible to run typedoc on dependency modules inside of node_modules? So a directory structure like

```    
library-src/
           module1/
                  index.ts
                  src/otherfolders/other.ts   
           typedoc.json
           node_modules/
                  @mycompany/src/module2/
                  @mycompany/src/module3/
           tsconfig.ts
```

and i want docs to be created for @mycompany/src/module2/index.ts and @mycompany/src/module3/index.ts

**Comment by Gerrit0** [comment]
Yes, you can do this, you just need to specify those files as part of your entry points:

```json
{
  "entryPoints": ["node_modules/@mycompany/src/module2/index.ts", "node_modules/@mycompany/src/module3/index.ts"]
}
```

... assuming those files are a part of the include in your library-src's tsconfig.json. If they are not, and they have their own tsconfig.json files, you can try `--entryPointStrategy packages`, and pass the package directories as your entry points.

**Comment by boneskull** [comment]
I'm not the `packages` strategy works, since the glob implementation always ignores `node_modules`.

**Comment by boneskull** [comment]
Scratch that--it doesn't like symlinks
