### ISSUE TITLE
Npm Install Fail on 0.7.1 version and others

### ISSUE THREAD

**Issue by shsouza** [TypeStrong/typedoc#2076]
## Search terms

npm install typedoc 0.7.1

## Expected Behavior

Keep installing and running for legacy systems

## Actual Behavior

NPM Error:

`
npm ERR! Windows_NT 10.0.19043
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "typedoc@0.7.1"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path C:\test\node_modules\.staging\@types\glob-1ad6152d\package.json
npm ERR! code ENOTDIR
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! ENOENT: no such file or directory, open 'C:\test\node_modules\.staging\@types\glob-1ad6152d\package.json'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\test\npm-debug.log
`

## Steps to reproduce the bug

npm install typedoc@0.7.1

## Environment

-   Typedoc version: 0.7.1
-   TypeScript version: 2.3.4
-   Node.js version: 6.17.1
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Looks like your antivirus might have blocked a file temporarily. I'd try installing again.

**Comment by shsouza** [comment]
Hi @Gerrit0, you is right... we tried on multiple machines inside the company and the issue was reproducible.

But after you comment I tried on my personal notebook and the package installed successfully, so I think that can be an network issue on my company...

Regards
