### ISSUE TITLE
Add lowercase option

### ISSUE THREAD

**Issue by lorensr** [TypeStrong/typedoc#2077]
## Problem

I use Algolia for search, and it normalizes URLs by lowercasing (and it's not configurable). So an Algolia search result URL is lowercase, but Vercel is case-sensitive, so Vercel doesn't match the lowercase URL with the typedoc-generated `SentenceCase` file, and returns a 404.

## Suggested Solution

Add a `lowercase` output option that: 
- generates lowercase files
- changes links to lowercase

**Comment by Gerrit0** [comment]
This feels like an Algolia defect or configuration issue to me... Normalizing non-search fields isn't okay.

**Comment by lorensr** [comment]
Thanks for pointing that out! Looks like I was mistaken—Algolia's normalization applies to search fields put in the index and query strings, not URLs. I'm not sure why there were lowercase URLs in my index, but after updating to a newer version of Crawler code and reindexing, I have SentenceCase types in my search result URLs.

Feel free to close, unless the lowercase option would be helpful for other use cases.

**Comment by Gerrit0** [comment]
:+1: I do eventually want to make routing much more configurable, but that's effectively tracked under #1919, so will go ahead and close this.
