### ISSUE TITLE
When function return type is inferred, the displayed signature's return type is missing a type parameter

### ISSUE THREAD

**Issue by reify-thomas-smith** [TypeStrong/typedoc#2079]
## Search terms

Signature, return type, type parameter

## Expected Behavior

Signature should be `capitalize<T>(string: T): Capitalize<T>`

## Actual Behavior

Signature is `capitalize<T>(string: T): Capitalize`

## Steps to reproduce the bug

```ts
/**
 * Capitalize the first letter of a string.
 */
export function capitalize<T extends string>(string: T) {
  return (
    string === '' ? '' : string[0].toUpperCase() + string.slice(1)
  ) as Capitalize<T>;
}
```

The bug does not occur if you add an explicit return type annotation.

## Environment

-   Typedoc version: 0.23.17
-   TypeScript version: 4.7.4
-   Node.js version: 16.14.0
-   OS: macOS 12.6

**Comment by Gerrit0** [comment]
Deep in `typescript.js`...

```ts
if (type.flags & 268435456 /* TypeFlags.StringMapping */) {
    var typeNode = typeToTypeNodeHelper(type.type, context);
    return symbolToTypeNode(type.symbol, context, 788968 /* SymbolFlags.Type */, [typeNode]);
    //   override type arguments                                                 ^^^^^^^^^^
}
```

Thanks TS. You do it magically, so just don't bother filling out the `typeArguments` property for anyone using the compiler API :/
