### ISSUE TITLE
Why does `typedoc foo.ts` report Error: Unable to find any entry points

### ISSUE THREAD

**Issue by Gallaecio** [TypeStrong/typedoc#2080]
```
$ typedoc --version

TypeDoc 0.22.15
Using TypeScript 4.6.4 from /usr/lib/node_modules/typedoc/node_modules/typescript/lib

$ typedoc --help
Usage:
  typedoc path/to/entry.ts
…
$ echo "export class Foo {}" > foo.ts
$ typedoc foo.ts 
Warning: Unable to locate entry point: <working directory>/foo.ts
Error: Unable to find any entry points. Make sure TypeDoc can find your tsconfig
```

Why is this minimal example not working? Is `foo.ts` not a valid “entry point”?

**Comment by Gerrit0** [comment]
TypeDoc requires a tsconfig file that includes your entry point - tsc doesn't need one, but I haven't spent the time figuring out how to match its behavior for this case.

**Comment by Gallaecio** [comment]
Should it work if I specify the entry point with a command-line switch?

```
typedoc --entryPoints foo.ts foo.ts
```

Because, while it does not fail, it instead hangs indefinitely, it seems.
