### ISSUE TITLE
How do I declare events' callback parameters?

### ISSUE THREAD

**Issue by JL102** [TypeStrong/typedoc#2081]
## Search terms

event, event callback, parameters, classes

## Question
Hello,

I'm working on documentation for an application that has several dozen classes & objects/methods that are compiled from Delphi and are accessible in JS. Events for these native objects are handled in a very specific way, which differs from the standard JS method of `myObj.addEventListener(eventString, callback)` / `myObj.on(eventString, callback)`:

```js
app.listen(myObj, eventString, callback);
// example:
app.listen(player, 'playbackState', (newState) => {
    console.log(newState);
});
```

This is how I have my Delphi -> TS parser declaring events currently:

```ts
class Player {
    /**
      Event is called when state of the player is changed ... like playback is started etc.
      Possible states are 'unpause', 'play', 'stop', 'pause', 'trackChanged'.

      @event playbackState
      @param {string} newState new playback state
      */
    event_playbackState = 'app.listen(myObj, "playbackState", () => {})'

    /**
      Event is called when now playing list is somehow modified.

      @event nowPlayingModified
      */
    event_nowPlayingModified = 'app.listen(myObj, "nowPlayingModified", () => {})'
}
```

It's janky to describe a specific function call as a string, but at least it gets the point across.
The only problem is the `@param` fields. For events, it appears that parameter names (and types) are not preserved in the generated documentation:

![image](https://user-images.githubusercontent.com/11487870/197031946-75d9676d-0316-455d-90fd-6581f608684e.png)

This is manageable for events whose callbacks are provided  a _single_ parameter, but it becomes quite unwieldy for events whose callbacks are provided multiple parameters:

```ts
    /**
      Event is called when playlist is changed in some way, additional params can detect the change type and new/old values </br>
      Note: Introduced in 5.0.3

      @event playlistChange

      @param playlist changed Playlist
      @param changeType (possible values 'title', 'new_child', 'child_removed', 'parent' or undefined)
      @param newValue possible values are playlist object, string or undefined
      @param oldValue possible values are playlist object, string or undefined

      */
    event_playlistChange = 'app.listen(myObj, "playlistChange", () => {})'
```
![image](https://user-images.githubusercontent.com/11487870/197033167-7314389d-af71-4ae7-9e6f-8af8d75044dc.png)

Is there a way for me to declare the event's callback parameters in a way that outputs something similar to that of function declarations (i.e., a list of named and typed parameters)? (Preferably while ALSO declaring the event ID)

(P.S. Maybe you could make it such that if the JSdoc includes the pattern "@event <eventName>", it would automatically declare that as the event ID, instead of just spitting out <eventName> as if it was regular text?)

**Comment by Gerrit0** [comment]
I would probably describe this pattern with something like:

```ts
/**
 * May be listened to with `app.listen(player, "<method name>", <method>)`
 */
export interface PlayerEvents {
  playbackState(newState: string): void
  nowPlayingModified(): void
}
```

This has the advantage of also providing types, so I could do `const listener: PlayerEvents["playbackState"]`, and later pass that to the listen method. Your `app.listen` method could then also be typed with something like:

```ts
interface PlayerEvents {
  playbackState(newState: string): void
  nowPlayingModified(): void
}
interface Player { isPlayer: true }

interface TrackEvents {
    complete(): void;
}
interface Track { isTrack: true }

interface App {
    // could do this without overloads, but this keeps types pretty simple
    listen<K extends keyof PlayerEvents>(obj: Player, event: K, callback: PlayerEvents[K]): void
    listen<K extends keyof TrackEvents>(obj: Track, event: K, callback: TrackEvents[K]): void
}
```

**Comment by JL102** [comment]
@Gerrit0 Thanks for the reply.
Hmmmmm... I'm not really the biggest fan of this method because it doesn't let me list the events on the pages for Player and Track respectively.

Is there a way to somehow make Player extend PlayerEvents or something, so that the list of events appear in the right place?

**Comment by Gerrit0** [comment]
You *could* use declaration merging to do this:

```ts
interface Player extends PlayerEvents {}
class Player {...}
```

... but that has the disadvantage of those properties then showing up when you try to use `Player`.

Another option:

```ts
class Player {
    /** Note: Does not exist at runtime */
    declare static events: {
        playbackState(newState: string): void
        nowPlayingModified(): void
    }
}
```
