### ISSUE TITLE
Add possibility for plugins to modify unparsed markdown file content

### ISSUE THREAD

**Issue by krisztianb** [TypeStrong/typedoc#2083]
## Search Terms

markdown, event

## Problem

Currently `MarkedPlugin` is using an event `MarkedownEvent` that is [emitted whenever a markdown file has been parsed](https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/MarkedPlugin.ts#L142).

Plugins can subscribe to this event and modify the parsed markdown. [My plugin](https://github.com/krisztianb/typedoc-plugin-replace-text/issues/1) would need a possibility to also manipulate the unparsed markdown content.

## Suggested Solution

Add another event that is emitted before the markdown file is parsed and converted.

**Comment by Gerrit0** [comment]
Seems like a reasonable request to me :+1:

**Comment by Gerrit0** [comment]
Was going to implement this - and it's already possible!

```js
const td = require("typedoc");

/** @param {td.Application} app */
exports.load = function (app) {
  app.renderer.on(
    td.MarkdownEvent.PARSE,
    (event) => {
      event.parsedText = "# Added by plugin\n\n" + event.parsedText;
    },
    null,
    1000 // priority
  );
};
```

**Comment by krisztianb** [comment]
Great. I didn't notice that `priority` parameter. Will give it a shot and close this when I get it working.
