### ISSUE TITLE
Adding a link to the home page (index.html in the destination directory)

### ISSUE THREAD

**Issue by MPV65** [TypeStrong/typedoc#2085]
## Search terms
index.html "home page" link

## Question
How does one provide a link to the initial index page that the readme document is rendered on? After navigating away from this, the only way back is via the back button. I have tried adding in a "navigationLinks" field with the value "index.html" but this just gets made relative to module root, so only actually works on the home page.

**Comment by krisztianb** [comment]
Actually I think there is a bug in the renderer. The name of the project at the very top of the page should IMHO link to the `index.html` and not to the current page. At least this would be my expected behavior.

**Comment by Gerrit0** [comment]
Introduced with #2078, I didn't catch that `??` was used for a string option default when it should have been `||`
