### ISSUE TITLE
@inheritDoc doesn't work with types and interfaces

### ISSUE THREAD

**Issue by deviant310** [TypeStrong/typedoc#2087]
## Search terms

@inheritDoc, type, interface

## Expected Behavior

`/src/index.ts`
```
/** Foo type comment */
export type Foo = () => number;

export class Bar {
  /**
   * {@inheritDoc Foo:type}
   */
  x = 1;
}
```
Expect that property `x` of `Bar` class will have the comment from `Foo` type

## Actual Behavior

Got the message:
```
warning Bar.x tried to copy a comment from Foo with @inheritDoc, but the source has no associated comment.
```
and as a result
<img width="980" alt="image" src="https://user-images.githubusercontent.com/38217402/198684582-aa3afe1a-8df1-4da8-a153-4de32c7e5104.png">

## Steps to reproduce the bug

Run typedoc as usual via cli:
```
typedoc ./src/index.ts --out ./docs
```

## Environment

-   Typedoc version: 0.23.18
-   TypeScript version: 4.8.4
-   Node.js version: 18.0.0
-   OS: MacOS

**Comment by Gerrit0** [comment]
*sigh* I missed another function type edge case. Shouldn't be too bad to fix. Will get it this weekend.

**Comment by deviant310** [comment]
I see you've made some fixes, that's great! But it seems your updates doesn't come up with 0.23.19 version=((
Attached some screens
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/38217402/199319619-6def9e90-1482-4ea9-b071-856b3c87d931.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/38217402/199319757-9ee24dd8-a438-4130-9bc0-00c9ad5ba772.png">

**Comment by Gerrit0** [comment]
I didn't make a release Friday, thought I was going to get #2084 as well Saturday, turned out to be way more complicated than expected at first... 0.23.20 is being published now

**Comment by deviant310** [comment]
Got it now, thanks!
