### ISSUE TITLE
categorizing and prioritizing the methods, classes etc..

### ISSUE THREAD

**Issue by tlq** [TypeStrong/typedoc#209]
I m trying to prioritize the methods or classes in the typedoc. So far i couldnt find any helpfull solution. would it be possible to prioritize the methods, classes, interfaces etc.. I mean is it possible to change the  view structure without touching the library ?

**Comment by s-panferov** [comment]
Could you please provide some examples?

**Comment by tlq** [comment]
for classes simply putting all the important modules at the top of the document and unimportant modules at the bottom. I mean some kind of grouping the modules and methods. 
let me explain it with methods:

lets say i have 3 methods
`@priorty = 3
 fillDays() {
    for (let index = 1; index <= 31; index++) {
      this.days.push(index);
    }
  }
  @priorty = 1
  fillYears() {
    for (let index = this.yearToStart; index <= this.yearToEnd; index++) {
      this.years.push(index);
    }
  }
  @priorty = 2
  changeDate(_day:number, _month:number, _year:number) {
    this.buildDate(_day, _month, _year);
  }`
and i want to shown in the doc exactly in this order (fillYears, changeDate, fillDays) . so i can highlight the important methods and group them, and unimportant methods at the bottom of the class (like setters and getters etc..).

**Comment by aciccarello** [comment]
Partially related is #112
