### ISSUE TITLE
monorepo & entry points

### ISSUE THREAD

**Issue by fryorcraken** [TypeStrong/typedoc#2091]
## Search terms

monorepo, entrypoint, entrypoints, entry points, packages, exports map

## Question

Using a monorepo, my exports map is as follows:

```
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js"
    },
    "./lib/enr": {
      "types": "./dist/lib/enr/index.d.ts",
      "import": "./dist/lib/enr/index.js"
    },
    "./lib/peer_discovery_dns": {
      "types": "./dist/lib/peer_discovery_dns/index.d.ts",
      "import": "./dist/lib/peer_discovery_dns/index.js"
    },
}
```

AFAIK, the only valid way to set the `entryPoint` is with a string:

```
  "typedoc": {
    "entryPoint": "./src/index.ts"
  },
```

Due to #2090, it seems that I have to specify `entryPoint` as typedoc is not able to find the source files using typescript.

How do I convert my `exports` map to a single string in `typedoc.entryPoint`?

**Comment by Gerrit0** [comment]
Packages mode today doesn't support multiple entry points for a package - this is something I'm looking to rectify with 0.24, along with adding direct support for the `exports` field, which is tracked in #1937.
