### ISSUE TITLE
links to protected members do not work without first changing "Member Visibility"

### ISSUE THREAD

**Issue by bd82** [TypeStrong/typedoc#2092]
## Search terms

- Member Visibility
- Protected 

## Expected Behavior && Actual Behavior

Given a link to a protected member I would expect it to "just" work.
But if the "Member Visibility" has not been set with "protected" enabled.
The link will not work.

Note that by default protected members are hidden so links to protected/private members will
simply not work...

## Steps to reproduce the bug

- Open: https://chevrotain.io/documentation/10_4_0/classes/CstParser.html#canTokenTypeBeInsertedInRecovery
- Note that the link will open the "root" of the class and not the specific `canTokenTypeBeInsertedInRecovery` method.

- Open the settings menu in the top right corner.
- enable "Member Visibility" of protected members.
- close the browser tab
- Open the same link again: https://chevrotain.io/documentation/10_4_0/classes/CstParser.html#canTokenTypeBeInsertedInRecovery
- Now the link works as expected.

You can also reproduce this using the super simple repo which includes my settings and config.
- https://github.com/bd82/typedoc_no_protected 

## Environment

    "typedoc": "0.23.19",
    "typescript": "4.7.4",
-   Node.js version: 18.4.0
-   OS: Win11

**Comment by Gerrit0** [comment]
Bleh :/ this is going to be annoying to fix. The best fix is probably to take you where it should be, and show you a prompt that indicates it's hidden because of settings, ideally with something to click to make it show up...

**Comment by Gerrit0** [comment]
Temporary workaround: you can set visibilityFilters to default protected members to visible.

**Comment by bd82** [comment]
Thanks.
I applied the workaround, although it did seem like I had to clear cache / hard-reload in 
my browser for it to be applied.

**Comment by Gerrit0** [comment]
That filter preference is stored in localStorage
