### ISSUE TITLE
If a module only exports one element AND has no module doc raise it up

### ISSUE THREAD

**Issue by trajano** [TypeStrong/typedoc#2093]
## Search Terms

Single export module

## Problem

https://trajano.github.io/react-hooks/modules/useAsyncSetEffect.html gives an example.

Since I refactor useAsyncSetEffect.ts to only contain one relevant element namely `useAsyncSetEffect` I have to click on the function afterwards.

## Suggested Solution

If a module only exports one element AND has no module doc raise it up so there's no need to navigate on the tree.

-- or --

If a module only exports one element AND has no module doc copy the module doc from the element to the module.

**Comment by Gerrit0** [comment]
If you have a single export module... does it deserve to be in its own module at all? At least from a dx point of view, I'd much rather `import { useAsyncSetEffect } from "react-hooks"` than access some directory. If bundling, tree shaking should still take care of the unused modules...


You could do this with a plugin, I don't think this behavior makes sense for the majority of projects.

```bash
typedoc --plugin ./path/to/plugin.js
```

```ts
const td = require("typedoc");

/** @param {td.Application} app */
exports.load = function (app) {
  app.converter.on(
    td.Converter.EVENT_RESOLVE_BEGIN,
    /** @param {td.Context} context */ (context) => {
      const toMove = [];
      for (const mod of context.project.children) {
        if (mod.children.length === 1 && !mod.hasComment()) {
          toMove.push(mod.children[0]);
        }
      }

      for (const child of toMove) {
        child.parent.children = undefined;
        context.project.removeReflection(child.parent);
        context.project.children.push(child);
        child.parent = context.project;
      }
    }
  );
};
```

**Comment by trajano** [comment]
It's primarily the `index.ts` that may become a single node module.  Since I like to keep my test near the code but plopping the whole thing in index may make sense at one point of time but change later on.  Also looking through the IDE tabs you'd see index.ts over and over and over rather than the component.  So that's worse for DX.

Your solution looks interesting though.  I'll see if I can tweak it so it will detect `index.ts`

**Comment by Gerrit0** [comment]
If you gave TypeDoc that file as the entry point instead of a bunch of entry points - you'd get that flattening for free.

https://github.com/trajano/react-hooks/blob/5d172bbf1ad90d65b24286021b5e67bb006cfb3a/typedoc.json#L2-L11

**Comment by trajano** [comment]
Ah nice.  I think I did that before but I wanted "xyz" to have a special treatment and be a module on it's own.  But when I did

```
  "entryPoints": [
    "./src"
  ],
```

It lumps everything in the root.  And if I do

```
  "entryPoints": [
    "./src",
    "./src/xyz"
  ],
```
I only get Xyz

**Comment by Gerrit0** [comment]
The latter is a bug... [this function](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/entry-point.ts#L203-L209) is removing `"./src"`, likely because it's the same as the derived root directory.

You could make `Xyz` a namespace with a `export * as`, but the plugin is probably a better solution for your use case.

```diff
diff --git a/src/index.ts b/src/index.ts
index 7207af0..3317c7a 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -8,4 +8,4 @@ export * from "./useMounted";
 export * from "./usePolling";
 export * from "./useReplaceLogging";
 export * from "./useSubscription";
-export * from "./xyz";
+export * as Xyz from "./xyz";
diff --git a/typedoc.json b/typedoc.json
index 94552dd..ab00b00 100644
--- a/typedoc.json
+++ b/typedoc.json
@@ -1,15 +1,9 @@
 {
   "entryPoints": [
-    "./src/useAsyncSetEffect",
-    "./src/useClock",
-    "./src/useStates",
-    "./src/useMounted",
-    "./src/usePolling",
-    "./src/useReplaceLogging",
-    "./src/useSubscription",
-    "./src/xyz"
+    "./src"
   ],
```
