### ISSUE TITLE
I want to save filter settings in sessionStorage.

### ISSUE THREAD

**Issue by bivarcs** [TypeStrong/typedoc#2094]
## Search terms

store, localStorage, SessionStorage, cache, save, settings, config, user

## Question
Is it possible to change the save destination of filter settings to sessionStorage?
After the user haphazardly changes the filter checkbox and closes the settings toggle, some users may forget that they are filtering and will not be able to fully see the content of the document thereafter.
So I thought it would be better to store filter settings in sessionStorage instead of semi-permanent localStorage.

Thank you for your wonderful project.

**Comment by Gerrit0** [comment]
I think it would be better to improve the filtering display such that it's clear that some members are hidden. I reference typedoc's apis relatively frequently, and wouldn't want to reselect filters every time I visit it.

**Comment by bivarcs** [comment]
Thank you. I will consider customizing the theme.

**Comment by Gerrit0** [comment]
If you end up with something you like - please share! I think it would make the default theme better.
