### ISSUE TITLE
Divergent property names in `TypeKindMap` (`serialization/schema.d.ts`)

### ISSUE THREAD

**Issue by niekvb** [TypeStrong/typedoc#2100]
## Expected Behavior

Expected names of properties `template-literal` and `named-tuple-member` to be written in camelCase.

Or alternatively, `indexedAccess` and `typeOperator` to be written in snake_case.

## Actual Behavior

Two types of notations within the same object.

## Steps to reproduce the bug

- `npm i typedoc`.
- Check `dist/lib/serialization/schema.d.ts:82`.

## Environment

-   Typedoc version: `0.23.20`

**Comment by Gerrit0** [comment]
Yeah, an unfortunate side effect of multiple authors several years apart. I'd rather go the camel case direction, likely as a part of 0.24.

**Comment by niekvb** [comment]
Just (or not even) a minor issue, but it will cause breaking changes if fixed in a future version.
