### ISSUE TITLE
externalSymbolLinkMappings wildcard

### ISSUE THREAD

**Issue by mistic100** [TypeStrong/typedoc#2101]
## Search Terms

externalSymbolLinkMappings wildcard

## Problem

I have a library that heavily relies on three.js package. I import and expose ~20 different objects from `three`. It is not really important for me that the links for these types are accurate but at least I would like to point the [three.js documentation index](https://threejs.org/docs/).

## Suggested Solution

Allow `externalSymbolLinkMappings` to declare wildcard mapping, that would be used if no other mapping match.

```json
    "externalSymbolLinkMappings": {
      "@types/three": {
        "*": "https://threejs.org/docs/"
      },
      "three": {
        "*": "https://threejs.org/docs/"
      }
    }
```

It would also cover cases when an external library is a single long page.

**Comment by Gerrit0** [comment]
Seems like a reasonable request 👍
