### ISSUE TITLE
Link not working within and after <ul> or <ol> tags

### ISSUE THREAD

**Issue by chrisgdt** [TypeStrong/typedoc#2103]
## Search terms

Indent by itemize or enumerate, `<ol>` `<ul>` tags, link parsing into markdown and not HTML ref.

## Expected Behavior

Having {@link ...} tags working everywhere in the doc.

## Actual Behavior

Inside `<ol>` tag, no link is working, not even after `</ol>`. Everything is parsed into markdown so it's not working in the HTML code.

## Steps to reproduce the bug

Simply run `typedoc --out docs/ --tsconfig ./tsconfig.json ./test.ts` with :

<details>
  <summary>tsconfig.json</summary>

```javascript
{
  "include": [
    "test.ts"
  ]
}
```
</details>

<details>
  <summary>test.ts</summary>

```javascript
/**
 * Write my documentation with some enumerate.
 * Before, the link to {@link myFunction} is working and {@link https://www.google.com | url} too.
 * <ol>
 *   <li>But within `ol` or `ul` tags, it's not {@link myFunction | working}.</li>
 *   <li>Not even url like {@link https://www.google.com}.</li>
 * </ol>
 * After, it's not working anymore : {@link myFunction} ; {@link https://www.google.com | url}.
 */
function myFunction () {
  console.log("hello world!");
}
```
</details>

The result is:
![ss+(2022-11-14+at+02 25 10)](https://user-images.githubusercontent.com/61288881/201671571-abaee567-1ee6-4588-a7f8-65b20c45154d.png)

Notice that there is no warning *Failed to resolve link [...]*.

## Environment

-   Typedoc version: 0.23.21
-   TypeScript version: 4.8.4
-   Node.js version: 16.17.0 (not used)
-   OS: Windows version 10.0.19043 Build 19043

**Comment by Gerrit0** [comment]
TypeDoc resolved the link, but marked didn't render it, because markdown isn't allowed within block level html elements.

This function should be producing `<a>` tags instead of markdown links.

https://github.com/TypeStrong/typedoc/blob/8a3e195d3814b6cf54f036fa528ad3a804678d1a/src/lib/output/themes/lib.tsx#L137

**Comment by KlausMikhaelson** [comment]
Hey @chrisgdt is this issue still open to work on ? if yes than would love to work on it !

**Comment by chrisgdt** [comment]
@KlausMikhaelson Yes of course, I opened it today ! I currently don't have the time to dive into the code and try to PR it myself.

**Comment by Yasir761** [comment]
Can you assign me this issue, I would love to work on this.

**Comment by KlausMikhaelson** [comment]
Hey @Yasir761 I already asked him and rn working on it, there should be other issues open as well would really appreciate if you can check them out.
Thank you !

**Comment by Yasir761** [comment]
@KlausMikhaelson It's ok brother.
Thank you
