### ISSUE TITLE
The comment associated with the callable property should not be moved down to the signature

### ISSUE THREAD

**Issue by psmyrek** [TypeStrong/typedoc#2104]
## Search terms

Callable class property comment

## Expected Behavior

The comment associated in the source code with the callable property should be associated with that property.

## Actual Behavior

The comment associated in the source code with the callable property is moved down to the property signature.

## Steps to reproduce the bug

```ts
export class Foo {
    /**
     * Example description.
     */
    public foo: () => void;

    constructor() {
        this.foo = () => {};
    }
}
```

Actual output from TypeDoc 👇🏻 
Please note the _"Example description."_ comment is moved down to the signature.

```json
{
    "id": 1,
    "name": "foo",
    "kind": 1024,
    "kindString": "Property",
    "flags": {
        "isPublic": true
    },
    "sources": [],
    "type": {
        "type": "reflection",
        "declaration": {
            "id": 2,
            "name": "__type",
            "kind": 65536,
            "kindString": "Type literal",
            "flags": {},
            "sources": [],
            "signatures": [
                {
                    "id": 3,
                    "name": "__type",
                    "kind": 4096,
                    "kindString": "Call signature",
                    "flags": {},
                    "comment": {
                        "summary": [
                            {
                                "kind": "text",
                                "text": "Example description."
                            }
                        ]
                    },
                    "type": {
                        "type": "intrinsic",
                        "name": "void"
                    }
                }
            ]
        }
    }
}
```

Expected output from TypeDoc 👇🏻 
The _"Example description."_ comment is associated to the property.

```json
{
    "id": 1,
    "name": "foo",
    "kind": 1024,
    "kindString": "Property",
    "flags": {
        "isPublic": true
    },
    "comment": {
        "summary": [
            {
                "kind": "text",
                "text": "Example description."
            }
        ]
    },
    "sources": [],
    "type": {
        "type": "reflection",
        "declaration": {
            "id": 2,
            "name": "__type",
            "kind": 65536,
            "kindString": "Type literal",
            "flags": {},
            "sources": [],
            "signatures": [
                {
                    "id": 3,
                    "name": "__type",
                    "kind": 4096,
                    "kindString": "Call signature",
                    "flags": {},
                    "type": {
                        "type": "intrinsic",
                        "name": "void"
                    }
                }
            ]
        }
    }
}
```

## Environment

-   Typedoc version: 0.23.21
-   TypeScript version: 4.8.4
-   Node.js version: 18.11.0
-   OS: Windows 11 Pro 22H2

**Comment by Gerrit0** [comment]
This is working as designed today - if that comment contained `@param` tags, they ought to be associated with parameters of the type, so by extension, the comment belongs to the signature. What's your use case for needing the comment to not be associated with the signature?

**Comment by psmyrek** [comment]
Thank you for the quick reply.

It seems to me that the current implementation with moving comments deeper is inconsistent. Let's assume we have a slightly different definition of a callable property:

```ts
export class Foo {
    /**
     * Example description.
     */
    public foo: ( () => void ) | number;

    constructor() {
        this.foo = () => {};
    }
}
```

In this case the _Example description_ is not moved down, but it stays on the same level as the `foo` property in the generated output. Please note that the comment in the source code is assigned to the property, not its type. If someone needs to describe e.g. the parameters for a callable property, it is enough to create an interface:

```ts
/**
 * Description for interface.
 *
 * @param value Description for param.
 * @returns Description for return value.
 */
export interface IBar {
    ( value: number ): boolean;
}

export class Foo {
    /**
     * Example description.
     */
    public foo: ( () => void ) | number;

    /**
     * Another example description for property.
     */
    public bar: IBar;

    constructor() {
        this.foo = () => {};
        this.bar = value => !!value;
    }
}
```

What do you think?

**Comment by Gerrit0** [comment]
```ts
/** Note: Comment here is for the interface, *not* the signature */
export interface IBar {
    /** comment would have to be here */
    ( value: number ): boolean;
}
```

(Almost) nobody does this. The type equivalent is far more common:

```ts
/** @param value should work */
export type Bar = (value: number) => boolean
```

As for the comment on the property vs the property type... both of these comments are displayed in essentially the same place when rendering, at least with the default theme, and removing this behavior would break the ability to fully describe the signature without placing a comment awkwardly between the `:` and the type, or creating a type alias... I'm going to need a stronger argument than "it's inconsistent" to be convinced to break that behavior. It's somewhat annoying when programmatically messing with the output, but I think changing it would result in worse behavior for most projects.

The rule today is that if a reflection contains signatures (either directly, or immediately within a reflection type), its comment will be applied to the signature.
