### ISSUE TITLE
Interface vs Const with same name confusion

### ISSUE THREAD

**Issue by alexdonh** [TypeStrong/typedoc#2106]
## Search terms

same name interface const

## Question

Given the below code:

`index.ts`

```
import {Coin} from "./codec/cosmos/base/v1beta1/coin";

export type {Coin};

export function balance(address: string): Promise<Coin> {
  return Promise.resolve({
    amount: "",
    denom: ""
  })
}
```

`coin.ts`

```
export interface Coin {
  denom: string;
  amount: string;
}

export const Coin = {
  // some methods and props
};
```

On the `balance` function, how can I tell typedoc to link to the Interface and not the Const?

<img width="677" alt="image" src="https://user-images.githubusercontent.com/10590429/202367567-979943b5-2393-43dc-becc-8b4ef0c02464.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/10590429/202367629-1b5a786d-35fd-4069-adff-ffbe98fb7cd5.png">

Currently the `Coin` return type in `balance()` links to the Const object.

**Comment by Gerrit0** [comment]
This is a bug - typedoc today only tracks one symbol->reflection relationship today, so can't tell which one it ought to link to according to if the reference is in type or value space.
