### ISSUE TITLE
Trying to document function inside of callback (jQuery Ready)

### ISSUE THREAD

**Issue by DKapin** [TypeStrong/typedoc#2107]
## Search terms

When I attempt to document a function inside of a callback (specifically on DOMContentLoaded or jQuery ready events), the function isn't being documented inside of the docs on output. In the code below, function test2 is being loaded into the documentation but function testingDocs is not. I've been trying to search through the documentation and Googling in general, but I can't find if I'm doing something wrong. I'm new to typedoc so apologies if it's obvious. Can anyone help?

```


// Documentation works
  /**
   * Function that returns b plus a
   * 
   * @param a testing a number
   * @param b testing a number 2
   * @returns sum of both numbers
   */
   function test2(a, b) {
    return b + a;
  }


// Documentation doesn't work 
jQuery(function ($) {

/**
 * Function that returns a + b
 * @callback
 * @param a test
 * @param b test b
 */
  function testingDocs(a, b) {
    return a + b;
  }

// ...
})

// Documentation still doesn't work
document.addEventListener("DOMContentLoaded", function () {
  /**
   * Function that returns b plus a
   * 
   * @param a testing a number
   * @param b testing a number 2
   * @returns sum of both numbers
   */
   function test(a, b) {
    return b + a;
  }
}, false);

```

**Comment by Gerrit0** [comment]
This is working as expected - TypeDoc is really meant to be used to create documentation for modules intended to be consumed by other code, so it only documents module exports, not values which aren't visible to the module consumer.
