### ISSUE TITLE
Still get plugin output without --plugin switch

### ISSUE THREAD

**Issue by brownieboy** [TypeStrong/typedoc#2108]
## Search terms

plugin, cache
## Expected Behaviour

If no plugin is specified via the `--plugin` switch, then TypeDoc should produce HTML

## Actual Behaviour

If a plugin is installed then it continues to be used, even after the switch specifying it has been removed from the CLI command.  The plugin in my case is typedoc-plugin-markdown.

## Steps to reproduce the bug

1. run `typedoc ./src/index.tsx` - I get HTML docs output
2. run `typedoc ./src/index.tsx --plugin  typedoc-plugin-markdown` - I get Markdown docs output 
3. run `typedoc ./src/index.tsx` - I _still_ get Markdown docs output even though I did not specify a plugin

Two workarounds to get HTML docs restored:
- Uninstall the typedoc-plugin-markdown plugin, or...
- ...specify `none` for the plugin, e.g. `typedoc ./src/index.tsx --plugin none`

## Environment

-   Typedoc version: ^0.23.21
-   TypeScript version: ^4.8.4
-   Node.js version: 16.17.1
-   OS: Debian bookworm (on Chromebook)

**Comment by Gerrit0** [comment]
Working as documented.

https://typedoc.org/guides/options/#plugin

> Specifies the plugins that should be loaded. By default, all installed npm packages with one of the following in their keywords will be loaded.

**Comment by brownieboy** [comment]
Yeah, I missed that one.

Odd that you have specify the `--plugin` switch in order to turn plugins off, but that _is_ how it's documented.

Many thank for the response, @Gerrit0 .

Closing this one.

**Comment by Gerrit0** [comment]
I'm not entirely opposed to changing this - it'd be a breaking change, but traversing all your node modules to find plugins is something I never really liked...
