### ISSUE TITLE
How can I put Functions on top of the order?

### ISSUE THREAD

**Issue by inokawa** [TypeStrong/typedoc#2109]
Hi, at first, thank you for this nice project!

## Search terms

kind sort order

## Question

How can I put Functions on top of the order?

I'm trying to use typedoc in my own React library.
In recent typical React projects, Functions are commonly used than Classes.
So I want to display Functions before any other kinds.

I tried categoryOrder and sort option but had no luck.

**Comment by Gerrit0** [comment]
Not possible today without a custom plugin - the `kind` sort order uses a predefined list <https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/sort.ts>

Adding an option to be able to define this list wouldn't be terrible...

**Comment by Gerrit0** [comment]
Site is still building, but this is now possible with `kindSortOrder`

https://github.com/TypeStrong/typedoc-site/commit/e24b4cc4d6080459e1bce314d4b33864a3f536c9

**Comment by inokawa** [comment]
I tried it. Thank you so much!
