### ISSUE TITLE
Symbol type definition.

### ISSUE THREAD

**Issue by origin1tech** [TypeStrong/typedoc#211]
When defining a type of "symbol" typedoc complains that it "Cannot find 'Symbol'.

Example:

```
let mySymbol: symbol = Symbol('symbol');
```

Setting to any will of course allow the docs to build.

```
let mySymbol: any = Symbol('symbol');
```

if pointed in the right direction happy to work on the fix and then PR.

**Comment by blakeembrey** [comment]
Have you tried from `master`?

**Comment by origin1tech** [comment]
@blakeembrey that was quick :) no I haven't!  I'll try:

    $ npm install typedoc@master

**Comment by blakeembrey** [comment]
You might need to clone, `npm install && npm run build`, then `npm link` first.

**Comment by origin1tech** [comment]
@blakeembrey yup did I'm testing now and will post process for others in future in just about 5 min. testing...

**Comment by origin1tech** [comment]
BINGO! master branch works thx. Man I didn't want to change all those ha ha.

Here's the process for posterity's sake.

Clone the repo:
    $ git clone https://github.com/TypeStrong/typedoc.git

Change to the typedoc directory:
    $ cd typedoc

Run npm install and link so you can access in your terminal.
    $ npm install && npm link

enjoy!

Thanks to @blakeembrey for the amazingly quick response you just made a whole lot of guys happy here :) +1.
