### ISSUE TITLE
Typedoc keeps processing my README.md even though it's in the 'exclude' array.

### ISSUE THREAD

**Issue by BonesyWonesy** [TypeStrong/typedoc#2110]
## Question
Current typedoc options are as follows
`
  "typedocOptions": {
    "entryPoints": [
      "src"
    ],
    "entryPointStrategy": "expand",
    "exclude": [
      "**/*+(.test).ts",
      "README.md",
    ],
    "excludeExternals": true,
    "includeVersion": true,
    "out": "docs"
  },
`

Yet I'm still getting warnings like: "./README.md:377:18 - warning Encountered an unescaped open brace without an inline tag"

How do I get typedoc to stop analyzing my markdown files?

**Comment by Gerrit0** [comment]
`"readme": "none"` in your settings

**Comment by BonesyWonesy** [comment]
> `"readme": "none"` in your settings

Nice, yea that works for sure. Is there a way to include it, but not have it be processed? It's nice to have on the main landing page for the generated docs.

**Comment by Gerrit0** [comment]
No, in order to include it, TypeDoc needs to be able to parse it to look for `@link` tags to resolve.

**Comment by BonesyWonesy** [comment]
Thanks for the clarifications
