### ISSUE TITLE
Links to source files are not generated under Windows with older MSYS (mingw)

### ISSUE THREAD

**Issue by royaltm** [TypeStrong/typedoc#2113]
## Search terms

Links to source files are not generated under Windows under older mingw versions or non-standard configuration.

## Expected Behavior

Typedoc should generate source links.

## Actual Behavior

Typedoc does not generate source links because [here](https://github.com/TypeStrong/typedoc/blob/4c81b3d30974a9524a5b696dab5683af2824db6f/src/lib/converter/utils/repository.ts#L61) 
`fileName` does not match the files produced by `git -C {path} ls-files`.

For example:
* fileName is `"c:/Path/To/Repo"`
* paths in the `files` start with `"C:/Path/To/Repo"` because they are being run through `BasePath.normalize` and `fileName` is not.

## Steps to reproduce the bug

This is actually hard, because I can not pinpoint why my MSYS is converting the windows path with the small drive letter.

Get MSYS (mingw version 1) on Windows, try to generate docs to any repository, check if the source links are being generated.

There are probably some other MSYS configurations that produce the windows path with the small drive letter.

## Environment

-   Typedoc version: 0.23.21
-   TypeScript version: 4.9.4
-   Node.js version: 16.16.0
-   OS: Windows 10 + mingw

## How to fix

The bug can be fixed easily if you add:

```
fileName = BasePath.normalize(fileName);
```
before this [line here](https://github.com/TypeStrong/typedoc/blob/4c81b3d30974a9524a5b696dab5683af2824db6f/src/lib/converter/utils/repository.ts#L61)

If the possible fix wasn't this easy I would rather not bother filing this issue. However I think the purpose of adding `BasePath.normalize` was to address such issues under Windows. If the paths in `Repository#files` set are being normalized already, then paths that are being matched against the set should be normalized as well.

**Comment by Gerrit0** [comment]
Oh Windows, how I dislike you... seems like a pretty innocuous fix.

**Comment by royaltm** [comment]
Thank you!
