### ISSUE TITLE
`@throws` is ignoring built-in Errors?

### ISSUE THREAD

**Issue by half0wl** [TypeStrong/typedoc#2117]
## Search terms

missing, throws, `@throws`, exceptions, errors

## Expected Behavior

When annotating a function with `@throws $SOME_BUILTIN_ERROR`, the rendered documentation should show that error.

## Example of Actual Behavior / Reproduction

`TypeError` is missing from the "Throws" section. Given:
```typescript
class Foo {
  private readonly bar: string
  /**
   * Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
   * tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim.
   *
   * @param bar Sed ut perspiciatis unde omnis iste natus
   * @throws {TypeError} when `bar` is not a string
   */
  constructor(bar: string) {
    this.bar = bar
  }
}
```

It renders:

![ss 2022-12-10 at 2 58 01 PM](https://user-images.githubusercontent.com/24421625/206836682-89abcba9-3d84-413f-876d-66d91bd68e84.png)

Notice that `{TypeError}` is missing altogether in the rendered doc.

Using `{@link TypeError}` works:
```diff
@@ -5,7 +5,7 @@
    * tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim.
    *
    * @param bar Sed ut perspiciatis unde omnis iste natus
-   * @throws {TypeError} when `bar` is not a string
+   * @throws {@link TypeError} when `bar` is not a string
    */
   constructor(bar: string) {
     this.bar = bar
```

![ss 2022-12-10 at 2 59 38 PM](https://user-images.githubusercontent.com/24421625/206837286-da48aab3-9a58-409e-a153-58853e357eb4.png)

but it (expectedly) doesn't link to the error, and generates a warning:

```
warning Failed to resolve link to "TypeError" in comment for Foo.constructor.new Foo
```

## Environment

-   Typedoc version: `TypeDoc 0.23.21`
-   TypeScript version: `TypeScript 4.9.4`
-   Node.js version: `v18.8.0`
-   OS: `macOS 12.6 (build 21G115)`

All examples are built using `$ yarn run typedoc index.ts` with no additional config and the following `package.json` / `tsconfig.json` respectively:
```json
{
  "name": "foo",
  "version": "1.0.0",
  "devDependencies": {
    "@tsconfig/recommended": "^1.0.1",
    "typedoc": "^0.23.21",
    "typescript": "^4.9.3"
  }
}
```
```json
{
  "compilerOptions": {
    "target": "ES2015",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Recommended"
}
```

---

Please close this if this is not a bug! I'm unsure because I found https://github.com/TypeStrong/typedoc/issues/2000#issuecomment-1207213275 when digging around which seems to suggest this may be the expected behaviour (which implies that `@throws` only works for exported custom errors?)

**Comment by Gerrit0** [comment]
This is working as intended - The type annotation `{TypeError}` [not supported by TSDoc](https://tsdoc.org/pages/tags/throws/), with `{@link TypeError}` being recommended instead.

In order to work with JS projects, where `{type}` fields are required on `param`/`return`/etc tags to provide good intellisense, TypeDoc silently ignores `{type}` fields after tags.

**Comment by half0wl** [comment]
> This is working as intended - The type annotation `{TypeError}` [not supported by TSDoc](https://tsdoc.org/pages/tags/throws/), with `{@link TypeError}` being recommended instead.
> 
> In order to work with JS projects, where `{type}` fields are required on `param`/`return`/etc tags to provide good intellisense, TypeDoc silently ignores `{type}` fields after tags.

Makes sense. Thanks!
