### ISSUE TITLE
Is is possible to be informed of final documentation paths for a symbol in a plugin?

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2119]
I've got a few related modules that I'm documenting and I'm trying to link between them.  I control the format and publishing of the documentation of each module so it's all very predictable.  Docs are generated during a CI publish step and published to `gh-pages`.

I have followed the very useful docs on [third party symbols](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/third-party-symbols.md) and have configured an unknown symbol resolver which works well.

I had an idea that if module A uses some of the types from module B, module B could include URLs for the docs of those types in it's package.json which my unknown symbol resolver could read while generating the docs for module A.

So, in module A:

```ts
import { SomeType } from 'module-b'

export default function () {
  return new SomeType()
}
```

Then in module B's package.json what I'm trying to generate is something like:

```js
{
  // other stuff
  "typedocs": {
    "SomeType": "https://......SomeType.html"
  }
}
```

Then my plugin is something like (not really, it's a bit more complicated in reality):

```js
function load (Application) {
  Application.converter.addUnknownSymbolResolver((ref) => {
      const moduleName = ref.moduleSource
      const symbolName = ref.symbolReference.path[0].path
      const manifest = require(`${moduleName}/package.json`)

      return (manifest.typedocs ?? {})[symbolName]
  })
}
```

The URLs generated by typedoc are predictable based on the type, name and path of the export, so I think it could be guessed from the `DeclarationReflection`s in the project `Context` object, but is there a way to hook in to the template output to build a list of symbol -> doc path mappings?

Another approach, though fragile, might just be reading the file names of the generated HTML docs and deriving it all from there?

**Comment by Gerrit0** [comment]
There's no builtin way to do this today, would be nice to have though... Reflection urls are created just before `RendererEvent.BEGIN` is triggered, so you could listen to that

```ts
const { RendererEvent }  = require("typedoc")

exports.load = function(app) {
  app.renderer.on(RendererEvent.BEGIN, rendererEvent => {
    console.log(renderEvent.urls)
  });
}
```

**Comment by achingbrain** [comment]
Neat, thanks so much for the tip - I have this working now.

It's got two parts to it - the first is a [type indexer plugin](https://github.com/ipfs/aegir/blob/master/src/docs/type-indexer-plugin.cjs) that creates a file named `typedoc-urls.json` that has the mapping from symbol name to documentation URL, this is included in the tarball published to npm.

The second part is an [unknown symbol resolver plugin](https://github.com/ipfs/aegir/blob/master/src/docs/unknown-symbol-resolver-plugin.cjs) that attempts to load `typedoc-urls.json` from a dependency when the documentation cannot be resolved.

You can see it working [here](https://libp2p.github.io/js-libp2p-tcp/functions/tcp.html), the docs from [libp2p/js-libp2p-tcp](https://github.com/libp2p/js-libp2p-tcp) link through to the `Transport` type from [libp2p/js-libp2p-interfaces](https://github.com/libp2p/js-libp2p-interfaces).
