### ISSUE TITLE
Hiding all overloads also hides the main function

### ISSUE THREAD

**Issue by asportnoy** [TypeStrong/typedoc#2122]
## Search terms

`@hidden`, overload

## Expected Behavior

#1142 adds the ability to apply `@hidden` to only some overloads without hiding all of them. I'd expect that I can apply `@hidden` to all of the overloads except for the original function and still be able to see the original, non-overloaded function.

## Actual Behavior

Typedoc hides the function when all the overloads are hidden

## Steps to reproduce the bug

MRE: https://tsplay.dev/w1An8w
Notice how all overloads are marked with `@hidden`, but the original function is not. Typedoc hides this entire function from the docs, when I'd expect it to still show the combined method.

## Environment

-   Typedoc version: `0.23.22`
-   TypeScript version: `4.8.4`
-   Node.js version: `16.17.1`
-   OS: macOS Ventura

**Comment by Gerrit0** [comment]
I can't seem to reproduce this. I pasted your file into a basic project, ran typedoc, and got this output:

![image](https://user-images.githubusercontent.com/19329837/207218914-18136f68-6384-41ea-9a59-ae6f2565da28.png)

I suspect your code was actually:

```ts
/** @hidden */
function getSomething(all: true): string[];
/** @hidden */
function getSomething(all: false): string;

function getSomething(all: boolean): string | string[] {
 return []
}
```

This is different. When overloads are declared, the signature declared on the implementation is not visible outside of the function, and effectively does not exist (`getSomething(Math.random() > 0.5)` is a type error).  If you want the catch-all signature to be visible, you need to add it separately

```ts
/** @hidden */
function getSomething(all: true): string[];
/** @hidden */
function getSomething(all: false): string;
/** documented! */
function getSomething(all: boolean): string | string[];
function getSomething(all: boolean): string | string[] {
 return []
}
```

**Comment by asportnoy** [comment]
The declare isn't in my actual code, I just did it there so I wouldn't have to define the actual function for the example. Wasn't aware it would make a difference.

**Comment by asportnoy** [comment]
I think I tried adding the combined overload but it caused type errors. Will try again later and let you know.

**Comment by asportnoy** [comment]
Must've messed something up the first time, it works now. Thanks!
