### ISSUE TITLE
Property comments are not inherited (@inheritDoc)

### ISSUE THREAD

**Issue by takthetank** [TypeStrong/typedoc#2126]
## Search terms

Hi, I have a class that extends an abstract class and implements an interface. In the interface there are some properties that need implementation, but when implemented and use @inheritDoc, inherited comments are not displayed.

## Expected Behavior

When using @inheritDoc and specifying where to retrieve the comments from, comments should be retrieved.

## Actual Behavior

In `FooBarClass.barProp` comments, it outputs `{@inheritDoc BarInterface.barProp}` instead of the actual comment.

## Steps to reproduce the bug

```ts
export abstract class FooClass {
   /** Describes what this method does */
   public fooMethod(): void{
      // do stuff
   }
}

export interface BarInterface {
   /** Describes the property */
   barProp: string;
}

export class FooBarClass extends FooClass implements BarInterface{
    // comments not inherited
   /** {@inheritDoc BarInterface.barProp} */
   public barProp: string='';

   // comments inherited fine
   /** {@inheritDoc FooClass.fooMethod} */
   public fooMethod(): void {
      // do something first
      super.fooMethod();
   }
}
```

## Environment

-   Typedoc version: 0.23.23
-   TypeScript version: 4.8.4
-   Node.js version: 16.17.0
-   OS: Windows 10

**Comment by Gerrit0** [comment]
The tag is `@inheritDoc`, with a capital `D`. TypeDoc only recognizes the lower cased version for compatibility with JSDoc, and JSDoc doesn't specify this tag as an inline tag, so TypeDoc requires the camel cased spelling.

```
./src/gh2126.ts:15:7 - warning Encountered an unknown inline tag "@inheritdoc"

15      /** {@inheritdoc BarInterface.barProp} */

./src/gh2126.ts:19:7 - warning Encountered an unknown inline tag "@inheritdoc"

19      /** {@inheritdoc FooClass.fooMethod} */
```

**Comment by takthetank** [comment]
My bad, that's a typo, I corrected it now in the initial post. I'm having the issue with `inheritDoc`.

**Comment by Gerrit0** [comment]
In that case, I'm going to need a reproduction that shows the issue. The snippet you provided works correctly for me.

**Comment by takthetank** [comment]
Please have a look at this [repo](https://github.com/takthetank/typedoc-bug). Run in the root `yarn install && yarn build-prod:all`.  
The inherited comments in `SubModuleModel` don't work, you should see in the output the following:
![image](https://user-images.githubusercontent.com/6099270/209703028-af5eeb91-2bd0-4ed1-818a-9ef5d34c6f9a.png)

**Comment by Gerrit0** [comment]
This is working as intended, `IFoo` is in the `<internal>` module of the resulting documentation, so `{@inheritDoc IFoo.code}` isn't a valid reference. You'd have to tell TypeDoc that the reference is in that namespace.

```ts
/** {@inheritDoc "<internal>".IFoo.code} */
```

It's worth mentioning that you don't need a `@inheritDoc` comment in this case - TypeDoc will copy the comment from `IFoo.code` if you don't have a comment on `code` since it recognizes that the class implements `IFoo`, so the same documentation likely applies.

**Comment by takthetank** [comment]
I see, and what about the comments from the base class that comes from a different module? There is also an error.

**Comment by Gerrit0** [comment]
The same thing applies there - in the output documentation, the base class is also in `<internal>`

**Comment by takthetank** [comment]
Ok I tried it and works fine this way. Can I find more about this behavior in the docs? I searched before posting but didn't find anything related.

**Comment by Gerrit0** [comment]
https://typedoc.org/guides/declaration-references/ is the page you want - PR welcome if you think there's improvements to be made there :)

**Comment by takthetank** [comment]
Great, thank you for the explanation!
