### ISSUE TITLE
cannot use symlinked entry points with 'packages' strategy

### ISSUE THREAD

**Issue by boneskull** [TypeStrong/typedoc#2130]
## Search terms

symlink

## Expected Behavior

It should find the entry point in e.g., `node_modules/foo` when `foo` is a symlink to a package that contains a `tsconfig.json` and/or a `typedoc.entryPoint` in its `package.json`

## Actual Behavior

TypeDoc does not find the entry point.

## Steps to reproduce the bug

1. Create package `foo` w/ `typedoc.json` containing an entry point that is a symlinked package (e.g., via `npm link`).
2. Create a `tsconfig.json` and appropriate entry point in `foo`
3. Set `entryPointStrategy` to `packages`.
4. Run `typedoc --logLevel Verbose`; note that it only finds the entry point from `foo`.

## Environment

-   Typedoc version: 0.23.23
-   TypeScript version: 4.7.4
-   Node.js version: 18.12.1
-   OS: macOS

* * *

I would be willing to open a PR to address this, but I'm of the opinion that a battle-tested external library should probably be pulled in rather than add further complexity to the current implementation. What do you think?

**Comment by Gerrit0** [comment]
> I'm of the opinion that a battle-tested external library should probably be pulled in rather than add further complexity to the current implementation

We used to depend on `glob` - I got rid of it when it had an open CVE due to depending on an ancient version of minimatch. I tend towards avoiding third party libraries if it's a "small" amount of code, so I'd rather go with the patch to TypeDoc's glob at this point.

**Comment by boneskull** [comment]
My reasoning for using a 3p package is the test coverage and handling of edge cases, which I prioritize over often-of-dubious-impact CVEs.  Anyway, I can see it from both angles, so I'll just do what you prefer here.
