### ISSUE TITLE
typedoc does not always use the correct version of typescript

### ISSUE THREAD

**Issue by boneskull** [TypeStrong/typedoc#2131]
## Search Terms

typescript version path tsc node_modules

## Problem

When a TypeDoc working copy is symlinked into a different project (e.g. via `npm link`), TypeDoc cannot find `node_modules/typescript` relative to the to-be-documented project directory, and instead uses its own.  

This is a problem because the to-be-documented project may be incompatible with the version of TypeScript in `typedoc`'s dev deps (currently 4.9.4 as of this writing).

## Suggested Solution

I can think of three (3) options:

1. Do nothing and note somewhere that use of `typedoc` via `npm link` is not supported.
2. Change the resolution algorithm -- _if there is one_ -- to prefer resolution of `typescript` from `process.cwd()` or the package root dir, _then_ `typedoc`'s dir or whatever else it does.  I assume that something is happening here other than the bog-standard Node.js resolution algorithm, because TypeDoc emits a warning about it.
3. Add an option which allows a user to specify an explicit path to `typescript`, which should handle this use-case plus some to-be-determined ones.

This could be a feature, bug, or intended behavior, depending on how you squint at it.

**Comment by Gerrit0** [comment]
> Change the resolution algorithm -- if there is one

There isn't one. We just `require` TypeScript like any other node module. When linking, npm doesn't mess with the node_modules of the linked module, so you see this behavior.... it's not really "unsupported" just an artifact of npm...  

I assume you're talking about the warning regarding unsupported TypeScript versions, that's just a check based on TypeDoc's package.json + the exported version number of TypeScript. The verbose logging about what TS is being used is really just there as a debugging aid.
