### ISSUE TITLE
warning-like output when entry point is a JS file not always helpful

### ISSUE THREAD

**Issue by boneskull** [TypeStrong/typedoc#2132]
## Search Terms

suppress warning javascript entrypoint

## Problem

When _run with verbose logging_ and provided an entry point that is a source `.js` file, TypeDoc emits a message like the following (for each such entry point):

```
The file /path/to/some/script.js does not contain a sourceMappingURL
```

The majority of end-users will likely only encounter this message if they have provided an incorrect entry point, as their sources are likely `.ts` files.  For others, this message is confusing at best and misleading at worst.

## Suggested Solution

One of:

- Allow users to somehow specify that JS entry points are expected
- Suppress this message if `compilerOptions.allowJs` is `true` in `tsconfig.json`
- Do nothing, since this is verbose logging, after all

**Comment by Gerrit0** [comment]
The entirety of packages mode is being reworked as a part of 0.24, so this will end up going away as a part of that.

That said - verbose logging is primarily for TypeDoc developers. It isn't really intended for end users.
