### ISSUE TITLE
Missing block tags for classes static fields

### ISSUE THREAD

**Issue by Simek** [TypeStrong/typedoc#2135]
## Search terms

Hello, I'm in process of upgrading TypeDoc from latest `0.22` release to `0.23` in our codebase, and after resolving most of the breaking changes related to the comment content structure changes I have spotted that comments tags for the classes static, non-async fields are missing, but base comment text and return values are present in output JSON file.

No change to the package source has been made between TypeDoc version switch, when generating JSON files using `0.22` tags fields are present as expected, so it looks like a regression.

I have tried few other standard and custom tags, but it seems that all tags are omitted, when placed in the static class field description.

## Expected Behavior

Comments tags are extracted, if defined for any class member.

## Actual Behavior

`blockTags` field is missing for classes static fields.

## Steps to reproduce the bug

Problematic comment:
* https://github.com/expo/expo/blob/main/packages/expo-camera/src/Camera.tsx#L177-L189

Package TSConfig:
* https://github.com/expo/expo/blob/main/packages/expo-module-scripts/tsconfig.base.json

We are running TypeDoc programatically via `Application`:
* https://github.com/expo/expo/blob/main/tools/src/commands/GenerateDocsAPIData.ts#L99

### Output JSON
* 0.22 - https://raw.githubusercontent.com/expo/expo/main/docs/public/static/data/unversioned/expo-camera.json
* 0.23 - https://gist.githubusercontent.com/Simek/546d04365429e88898f715825e7004bd/raw/677c25a249625a0544f51b7df9ceb58c8731bf2f/expo-camera.json

Happy to provide more details, if needed.

## Environment

-   TypeDoc version: 0.23.23
-   TypeScript version: 4.9.4
-   Node.js version: 16.17.1
-   OS: macOS 12.6

**Comment by Gerrit0** [comment]
I'm going to have to ask for a reproduction that doesn't involve figuring out expo, too far from minimal. This seems to work in a very roughly cloned reproduction setup.

Code: https://github.com/TypeStrong/typedoc-repros/pull/24
Job: https://github.com/TypeStrong/typedoc-repros/actions/runs/3817737949/jobs/6494190729#step:4:41

**Comment by Simek** [comment]
Fully understandable, I was able to reproduce it in isolation using your repro branch as base, by copying part of the Camera code, now I just need to narrow down the repro and strip unneeded parts. Going to follow up with repo/branch link.

**Comment by Simek** [comment]
The bug seems to be different than I have initially assumed, the culprit for the missing tag is fact that the description defined for the `useCameraPermissions` hook is overwritten by the default one for `createPermissionsHook`. 

The quite minimal repro I was able to assemble is here:
* https://github.com/Simek/typedoc-repros/tree/gh2135

The source for the extracted description is here:
* https://github.com/expo/expo/blob/main/packages/expo-modules-core/src/PermissionsHook.ts#L73-L76

**Comment by Gerrit0** [comment]
Anything that depends on another module isn't minimal...

```ts
export class Camera {
  /** One */
  static useCameraPermissions = createPermissionHook();
}

/** Two */
export declare function createPermissionHook(): () => void;
```

**Comment by Gerrit0** [comment]
Ugh, this is another instance of functions being *special*... with an extra layer of indirection because of a reflection type.
