### ISSUE TITLE
typedoc not picking up comments in entry or my imported modules

### ISSUE THREAD

**Issue by vedtam** [TypeStrong/typedoc#2136]
## Search terms

ES6 import folders nested entry

## Problem

When running with the following config:

```
{
  "name": "NewsFeed",
  "entryPoints": ["./src/main.ts"],
  "out": "docs"
}
```

the generated documentation does not show any of the comments from the entry point or the imported modules:

![Screenshot 2023-01-02 at 18 35 50](https://user-images.githubusercontent.com/4981592/210258662-8fd4d1e2-f846-4ce6-9b50-c58dc8b7a9af.png)

This comment is in main.js:

![Screenshot 2023-01-02 at 18 49 34](https://user-images.githubusercontent.com/4981592/210259616-200c04c0-406b-4ead-8cf5-9e62d7b29b8f.png)

main.js also imports `scraper.js` which contains more comments: 

```
import * as scraper from "./services/scraper/scraper.js";
...
```
comment in scraper.js:

![Screenshot 2023-01-02 at 18 51 28](https://user-images.githubusercontent.com/4981592/210259790-68c6f54b-a184-4ae3-ac14-625a60b6d075.png)

I'm new to typedoc, please forgive me if my beginner question.

**Comment by Gerrit0** [comment]
TypeDoc is meant for documenting a library from the standpoint of the library's consumers. As such, it documents anything you *export* from your entry points. `test` isn't exported, so it won't be included, and `run` isn't re-exported from `src/main.ts`, so it isn't considered public and is therefore also not documented.

**Comment by vedtam** [comment]
@Gerrit0 thanks for the elaborate answer. I would like to document different parts of my project (for myself). I've discovered the option `entryPointStrategy` with this set to `expand` and by giving the root directory as an entry point it seems to get all individual files just right.
