### ISSUE TITLE
Unable to exclude node_modules

### ISSUE THREAD

**Issue by agiron123** [TypeStrong/typedoc#2137]
## Search terms

node_modules, exclude, typescript

## Question
I'm having trouble excluding node_modules from my typedoc generation. I have a Typescript/React library that I'm trying to run this on.

My typedoc.json is as follows:
```
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": ["./src/index.tsx"],
  "out": "doc",
  "externalPattern": "**/node_modules/**",
  "exclude": "**/node_modules/**"
}
```

and in my tsconfig.json I have skipLibCheck set:
```
{
  ...
  compilerOptions: {
    ...
    skipLibCheck: true
  }
}
```

Yet, when I run the docs command from my package.json I still see node_modules showing up in my terminal output. 

```
➜  common git:(ui-docstrings) ✗ npm run docs

> @aqueducthq/common@0.1.8 docs
> typedoc

warning You are running with an unsupported TypeScript version! If TypeDoc crashes, this is why. TypeDoc supports 4.6, 4.7, 4.8, 4.9
error TS5053: Option 'noEmit' cannot be specified with option 'incremental'.

node_modules/@mui/material/styles/experimental_extendTheme.d.ts:304:9 - error TS1110: Type expected.

304       ? `${keyof T}-${ConcatDeep<Split<V>>}`
            ~~~

node_modules/@mui/material/styles/experimental_extendTheme.d.ts:304:18 - error TS1005: '}' expected.

304       ? `${keyof T}-${ConcatDeep<Split<V>>}`
                     ~

node_modules/@mui/material/styles/experimental_extendTheme.d.ts:304:19 - error TS1128: Declaration or statement expected.

```

What am I missing here?

**Comment by Gerrit0** [comment]
skipLibCheck can only ignore non-syntax errors. You're running with a very old version of TypeScript, but trying to use newer versions of libraries that expect at least TS 4.1. There is no way for this to work without upgrading TypeScript.

Furthermore, TypeDoc's `exclude` option **only** applies to filtering out entry points -- https://typedoc.org/guides/options/#exclude
