### ISSUE TITLE
v0.23.24 | Unwanted color change in code block (index.html)

### ISSUE THREAD

**Issue by KillerJulian** [TypeStrong/typedoc#2139]
## Expected Behavior

![1](https://user-images.githubusercontent.com/36083682/211187741-be156956-3656-43ce-b757-4057b6ac1e9d.png)

## Actual Behavior

![2](https://user-images.githubusercontent.com/36083682/211187753-d75c77bc-9a29-48f8-a2e4-8bfa54992ed6.png)

## Summary

Since the update to version `0.23.24` the color (as seen on the pictures) in a code block of `README.md` has updated unintentionally.

## Environment

-   Typedoc version: `0.23.24`
-   TypeScript version: `4.9.4`
-   Node.js version: `16.13.0`

**Comment by Gerrit0** [comment]
This will be due to an upgraded Shiki version, what language are you using for highlighting?

**Comment by KillerJulian** [comment]
> [...] what language are you using for highlighting?

Do you mean:

```
```bash
npm i your-dependency
\```
```

*Igonize the one back slash*

**Comment by Gerrit0** [comment]
This is an issue with Shiki, it'll have to be fixed there. https://github.com/shikijs/shiki/issues/404

**Comment by Gerrit0** [comment]
If you don't want syntax highlighting use `text` as the language, it looks like this is likely intended update that just hasn't released in VSCode yet.

**Comment by KillerJulian** [comment]
Okay, thanks a lot. If it is an external update, can you close this issue.
