### ISSUE TITLE
Git version can't be started

### ISSUE THREAD

**Issue by DaSchTour** [TypeStrong/typedoc#214]
As there is still no 0.4.0 released on NPM and I have the feeling that this might take years I tried to install the git version through NPM. But sadly the repository is build in a way that doesn't allow to run the git version. Bin is referencing to ../lib which doesn't exist in the repo.
So I guess to get indepentend of releases if there will be any soon it would be nice to have a dist release in git that is startable so that it doesn't really so much on NPM.

**Comment by lholznagel** [comment]
Take a look at this https://github.com/TypeStrong/typedoc/issues/211#issuecomment-219260134.

**Comment by blakeembrey** [comment]
Thanks @lholznagel 👍 I'll be doing a release this weekend, now that I have credentials.
