### ISSUE TITLE
Typedoc is not following symlink correctly

### ISSUE THREAD

**Issue by Ethan-Arrowood** [TypeStrong/typedoc#2140]
## Search terms

symlink, pnpm, typescript

## Expected Behavior

I expect to see the link `node_modules/typescript/lib/lib.dom.d.ts:1578` produced

## Actual Behavior

I'm seeing `node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/lib.dom.d.ts:1578` produced.

## Steps to reproduce the bug

In a pnpm project.

Using a type definition like this: 

```ts
export interface ExtraResponseInit extends Omit<ResponseInit, 'headers'> {
  /**
   * These headers will be sent to the user response
   * along with the response headers from the origin.
   */
  headers?: HeadersInit;
  /**
   * Fields to rewrite for the upstream request.
   */
  request?: ModifiedRequest;
}
```

The resulting typedoc prints this:

```md
# Interface: ExtraResponseInit

## Hierarchy

- `Omit`<[`ResponseInit`](node_modules/typescript), `"headers"`\>

  ↳ **`ExtraResponseInit`**

## Table of contents

### Properties

- [headers](ExtraResponseInit.md#headers)
- [request](ExtraResponseInit.md#request)
- [status](ExtraResponseInit.md#status)
- [statusText](ExtraResponseInit.md#statustext)

## Properties

### headers

• `Optional` **headers**: `HeadersInit`

These headers will be sent to the user response
along with the response headers from the origin.

#### Defined in

[packages/edge/src/middleware-helpers.ts:31](https://github.com/vercel/vercel/blob/main/packages/edge/src/middleware-helpers.ts#L31)

---

### request

• `Optional` **request**: [`ModifiedRequest`](ModifiedRequest.md)

Fields to rewrite for the upstream request.

#### Defined in

[packages/edge/src/middleware-helpers.ts:35](https://github.com/vercel/vercel/blob/main/packages/edge/src/middleware-helpers.ts#L35)

---

### status

• `Optional` **status**: `number`

#### Inherited from

Omit.status

#### Defined in

node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/lib.dom.d.ts:1578

---

### statusText

• `Optional` **statusText**: `string`

#### Inherited from

Omit.statusText

#### Defined in

node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/lib.dom.d.ts:1579
```

I can't figure out how to fix the links so that they don't print the pnpm symlink piece. 

## Environment

-   Typedoc version: 0.23.24
-   TypeScript version: 4.7.4
-   Node.js version: 16
-   OS: mac

**Comment by Ethan-Arrowood** [comment]
From https://github.com/vercel/vercel/pull/9198

If you want to try running locally, clone repo, checkout `migrate/yarn-to-pnpm` branch, then run `pnpm install`, `cd package/edge`, `pnpm build:docs`

**Comment by Gerrit0** [comment]
The issue here isn't that TypeDoc isn't following the symlink, but that it *is* following the symlink, and that isn't under TypeDoc's control. The path we get from TypeScript's API has already had the symlink resolved... so there really isn't a good way for TypeDoc to do anything but what it's already doing.

I stuck a breakpoint in `symbols.ts/convertSymbol` for the `statusText` symbol:

> symbol.declarations[0].getSourceFile().fileName
'/home/gerrit/Desktop/td_tests/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/lib.dom.d.ts'

For your specific case, a plugin is probably good enough.

```bash
$ pnpm typedoc src/gh2410.ts --plugin ./plugins/gh2140.js
```


```ts
// @ts-check
// CC0

const td = require("typedoc");

/** @param {td.Application} app */
exports.load = function (app) {
  app.converter.on(
    td.Converter.EVENT_RESOLVE_BEGIN,
    /** @param {td.Context} context */
    (context) => {
      for (const refl of Object.values(context.project.reflections)) {
        for (const source of refl.sources || []) {
          source.fileName = source.fileName.replace(
            /^node_modules\/\.pnpm\/[^\/]+\//,
            ""
          );
        }
      }
    }
  );
};
```
