### ISSUE TITLE
Plugin API: How to change a declaration?

### ISSUE THREAD

**Issue by thislooksfun** [TypeStrong/typedoc#2142]
## Search terms

plugin, declaration, change, remove, update, unregister

## Question

I'm trying to make a plugin for typedoc to be able to document zod object types as if they were interfaces. For example, I want to treat the code

```ts
/** Some documentation! */
const SomeObject = z.object({
  /** Something */
  foo: z.string(),
});

/** More documentation! */
const OtherThing = SomeObject.extend({
  /** Other! */
  bar: z.number(),
});

export type SomeInterface = z.infer<typeof SomeObject>;
export type OtherInterface = z.infer<typeof OtherThing>;
```

As if it was written

```ts
/** Some documentation! */
export interface SomeInterface {
  /** Something */
  foo: string;
}

/** More documentation! */
export interface OtherInterface extends SomeInterface {
  /** Other! */
  bar: number,
}
```

Ideally I'd just use a typescript plugin for this, but those _still_ aren't properly supported, so instead I'm trying to do it with a combination of a typedoc plugin and a `.d.ts` codemod. For the typedoc plugin though I'm a bit lost. I can't find a good guide on how to make a plugin. I found `context.registerReflection()`, which looks like it will work to create the phantom interfaces, but how can I unregister the actual types? Or is there a better way of doing this?

**Comment by Gerrit0** [comment]
[project.removeReflection](https://typedoc.org/api/classes/ProjectReflection.html#removeReflection) is what you're looking for, there aren't really any guides on creating a plugin, just [other plugins](https://typedoc.org/guides/plugins/) to use as examples.

I think creating new reflections is probably the way to go with this, I'd recommend `context.createDeclarationReflection`, which *should* get comments correctly if you give it the symbol of the appropriate property you're creating.

**Comment by Gerrit0** [comment]
@thislooksfun since someone else asked for it, decided to give it half an hour or so, https://github.com/Gerrit0/typedoc-plugin-zod now exists, which doesn't *exactly* do what you asked, since it skips comments and leaves the inferred type as type aliases instead of interfaces, but...
