### ISSUE TITLE
What is compilerOptions for?

### ISSUE THREAD

**Issue by mikelehen** [TypeStrong/typedoc#2143]
The [docs](https://typedoc.org/guides/options/#compileroptions) say:

> compilerOptions
> Used to selectively override compiler options for generating documentation. Values set with this option will override options read from tsconfig.json.

And there is an example of overriding `strictNullChecks`.  But what does it mean to override strictNullChecks for typedoc? I wouldn't expect a documentation generator to be doing null checks, so I wouldn't expect that to have any effect.  In general I am curious why this option exists / when you would use it.  The docs / example are confusing to me as-is.

**Comment by Gerrit0** [comment]
#1891 - the original implementing PR has a use case. 

TypeDoc uses type information, so it runs the TS compiler. It can be useful to be able to configure it with different options  than are present in the tsconfig

**Comment by mikelehen** [comment]
Thanks for the explanation! Sorry for not acknowledging it earlier. I wanted to create a PR against the docs, but was super slow to do so.  Feel free to accept or reject as you see fit.
