### ISSUE TITLE
example output when building locally does not match what's on the site

### ISSUE THREAD

**Issue by trajano** [TypeStrong/typedoc#2144]
## Search terms

TypeDoc Example

## Expected Behavior

https://typedoc.org/example/index.html shows
![image](https://user-images.githubusercontent.com/110627/213444691-b648b9cc-4290-4be0-ab00-bb9acee57194.png)

I was actually trying to figure out how you got that text.

## Actual Behavior

Building locally shows

![image](https://user-images.githubusercontent.com/110627/213444752-ecfb9ea8-3c2e-4d37-a46a-168a0d16a5d4.png)

## Steps to reproduce the bug

from the file

1. Build TypeDoc: `npm install` and `npm run build` in the root directory.
2. `cd example`
3. `npm install` (the example has its own `package.json`)
4. Typecheck the example: `npm run tsc`
5. Build the docs: `npm run typedoc`

## Environment

-   Typedoc version: latest master
-   TypeScript version: 
-   Node.js version: 16.18.1
-   OS: Windows

**Comment by Gerrit0** [comment]
This is caused by the `name` option. I'm not sure why that's specified in the config file for the site rather than the base config...

https://github.com/TypeStrong/typedoc-site/blob/master/example.typedoc.json

**Comment by trajano** [comment]
OK I was looking at the `examples` folder.  But at least that helps.
