### ISSUE TITLE
Create a plugin with typescript

### ISSUE THREAD

**Issue by birvl97** [TypeStrong/typedoc#2146]
## Search terms

create a plugin with typescript

## Question

In docs I can see example written with typescript, but in reality it doesn't work for me 😢 Did I miss something?
However plugin written with js works fine, but it's a bit inconvenient to work without strict typing 🐝

**Comment by krisztianb** [comment]
Here is a pretty simple plugin written in TypeScript: https://github.com/krisztianb/typedoc-plugin-replace-text

I hope it helps you to get started.

**Comment by birvl97** [comment]
I've already figured out how I should do it. Btw thanks for trying to help 😃
