### ISSUE TITLE
Copy code to clipboard

### ISSUE THREAD

**Issue by remarkablemark** [TypeStrong/typedoc#2153]
## Problem

Would TypeDoc be open to adding a button inside of code blocks that can copy code to clipboard similar to [GitHub](https://github.com/) and [Docusaurus](https://docusaurus.io/)?

GitHub example:

<img width="438" alt="Screen Shot 2023-01-28 at 7 57 49 PM" src="https://user-images.githubusercontent.com/10594555/215298146-f20b18c3-567c-4614-98ca-dd2ba2dba1d9.png">

Docusaurus example:

<img width="478" alt="Screen Shot 2023-01-28 at 7 58 31 PM" src="https://user-images.githubusercontent.com/10594555/215298147-0a401008-031a-45bb-b680-c112d49f8219.png">

## Suggested Solution

I created a plugin [typedoc-plugin-copy-code-to-clipboard](https://github.com/remarkablemark/typedoc-plugin-copy-code-to-clipboard) (see [docs](https://b.remarkabl.org/typedoc-plugin-copy-code-to-clipboard)) but it would be nice if TypeDoc natively supported this.

## Search Terms

copy code block to clipboard

**Comment by ilg-ul** [comment]
That would be a nice feature to have.
