### ISSUE TITLE
Can't set schema in typedoc.json

### ISSUE THREAD

**Issue by AlexAegis** [TypeStrong/typedoc#2155]
`"typedoc": "^0.23.24"`

This `typedoc.json` isn't valid, but it should be:

```json
{
	"$$schema": "https://json.schemastore.org/typedoc.json"
}
```

When running `npx typedoc --entryPointStrategy packages .` I get

```sh
error Tried to set an option ($$schema) that was not declared.
```

While this isn't part of the actual options, it would be nice to make an exception for this to provide cross-editor hints for this file.

A workaround for VSCode `settings.json`

```json
{
	"json.schemas": [
		{
			"fileMatch": ["typedoc.json"],
			"url": "https://json.schemastore.org/typedoc.json"
		}
	]
}
```

**Comment by Gerrit0** [comment]
There is an exception - the property is `$schema`, not `$$schema`

**Comment by AlexAegis** [comment]
Sorry for the noise! My bad
