### ISSUE TITLE
Arrow functions not being included when `excludeNotDocumented` is true

### ISSUE THREAD

**Issue by jonathanchaffer** [TypeStrong/typedoc#2156]
## Search terms

arrow, function, const

## Expected Behavior

Arrow functions (like `const foo = () => {}`) should be documented correctly when `excludeNotDocumented` is true.

## Actual Behavior

They are being incorrectly excluded from the generated docs, even when they have JSDoc comments on them.

## Steps to reproduce the bug

See repro: https://github.com/jonathanchaffer/typedoc-repros

## Environment

-   Typedoc version: 0.23.24
-   TypeScript version: 4.9.4
-   Node.js version: 14.17.6
-   OS: macOS 13.0

**Comment by Gerrit0** [comment]
Thanks for the repro! I forgot to consider how signature comment inheritance worked there.
