### ISSUE TITLE
a CallbackLogger does not pass enough information to callback function

### ISSUE THREAD

**Issue by boneskull** [TypeStrong/typedoc#2158]
## Search Terms

logger callbacklogger custom addcontext

## Problem

When using a custom logger (a `CallbackLogger`), the callback is called with `[message:string, level: LogLevel]` and that's it.  `CallbackLogger` does not override `addContext`; its prototype contains `Logger.addContext()` which throws away the extra information.  This extra information is most certainly useful to someone using a custom logging function.

## Suggested Solution

`CallbackLogger.log()` should look like this (changes highlighted):

```ts
/**
 * Print a log message.
 *
 * @param message  The message itself.
 * @param level  The urgency of the log message.
 */
override log(message: string, level: LogLevel, ...args: [ts.Node?] | [number, MinimalSourceFile]) { // 👈
    super.log(message, level);
    this.callback(message, level, ...args); // 👈
}
```

**Comment by Gerrit0** [comment]
Seems reasonable, I think you may be the first person to have used the callback logger.

**Comment by boneskull** [comment]
Hmm, what I suggested was insufficient.  It looks like the `addContext` method is called, and the `string` result is then passed along to the `log` and `callback` methods.  So something more fundamental would need to change in the public API.  

The use-case here is programmatic usage of TypeDoc (not plugin implementation).

I'll see if I can find another workaround.

**Comment by Gerrit0** [comment]
I'm considering killing `CallbackLogger` entirely -- it's not *that* much more code to implement the `Logger` interface yourself, and just overwrite `application.logger` (also call [options.setLogger](https://typedoc.org/api/classes/Options.html#setLogger))

**Comment by Gerrit0** [comment]
When I went to go look at doing this as a part of the breaking changes in 0.24, apparently I'd already done it months ago and forgotten about it, marking this as wontfix
