### ISSUE TITLE
How I inserted a piece of js code into result of typedoc, so that I could try running the source code in the browser's console while watch typedoc.

### ISSUE THREAD

**Issue by EricaLi123** [TypeStrong/typedoc#2160]

**Comment by Gerrit0** [comment]
Sounds like you either want a custom theme, or a plugin which defines [a hook](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md#hooks-v0228) to add extra markup to an existing theme.

**Comment by EricaLi123** [comment]
> Sounds like you either want a custom theme, or a plugin which defines [a hook](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md#hooks-v0228) to add extra markup to an existing theme.

Thanks for your help. This is what I want
