### ISSUE TITLE
How to get a contributed theme listed on the typedoc website?

### ISSUE THREAD

**Issue by citkane** [TypeStrong/typedoc#2161]
## Search terms

typedoc theme listing

## Question
I have recently published a new [typedoc theme on npmjs.com](https://www.npmjs.com/package/typedoc-theme-yaf).  
The name follows the `typedoc-theme-*` pattern.

It has the `typedoc-theme` keyword, and shows on the [npmjs listing](https://www.npmjs.com/search?q=keywords:typedoc-theme). (Presently last page, last item)  
The `package.json` includes the dependency and peerdependency: `"typedoc": "^0.23"`.

It has been overnight (about 16hours), and the theme is not appearing on the [typedoc listing page](https://typedoc.org/guides/themes/).
Am I missing a trick here?

**Comment by Gerrit0** [comment]
The trick was waiting 3 more hours :) the site only rebuilds once per day. It's there now.

**Comment by citkane** [comment]
Thanks Gerrit :)
