### ISSUE TITLE
Enhancement for `excludeNotDocumented` option

### ISSUE THREAD

**Issue by andrey-kuznetsov-osome** [TypeStrong/typedoc#2162]
## Search Terms

`excludeNotDocumented`, `option`

## Problem

I have a codebase with large set of non documented functions, classes, e.t.c

1. If `excludeNotDocumented` = true I can see only documented classes, functions. But even if a whole class has documentation his properties, methods without docs are hidden.
2. `excludeNotDocumented` = false I can see all non-documented properties, methods from documented classes but at the same time I see a rest of non-documented functions, classes which I don't want to include.

## Suggested Solution

A mode when class, enum, interface, ... shows all it non documented members if it was documented on top level

**Comment by Gerrit0** [comment]
Hmm, this ideally should be configurable at a more granular level, where you can specify what kinds of reflections should be removed by excludeNotDocumented... `excludeNotDocumentedKinds` isn't a horrible name, having difficulty coming up with something better.
