### ISSUE TITLE
Is there a built-in way to rename an entire module (i.e. customize its name so that it's not just the filename)?

### ISSUE THREAD

**Issue by JL102** [TypeStrong/typedoc#2165]
## Search terms

rename, module, file, namespace

## Question
Hi,

I have a file `mminit.ts` which defines a bunch of variables on the Window object. The name `mminit` is quite cryptic, and I'd like to rename it something like `Window` or `DOMExtensions`. I have a comment with the tag `/** @module DOMExtensions */` at the top of the file, but it does nothing.

Is there a way to make the file show up in the documentation with a custom name other than `mminit`?
I could probably jury-rig it with a janky solution via a plugin, but I'd like to see if there's a built-in way first. I can't find anything in the documentation that seems to work, though.

**Comment by Gerrit0** [comment]
> I have a comment with the tag /** @module DOMExtensions */ at the top of the file, but it does nothing.

This is the way to go - is the comment the very first thing in the file, before any imports? It should do what you've described you want.

**Comment by JL102** [comment]
@Gerrit0 Apologies for missing your reply. It took me a while to get back to this.

I just checked putting `/** @module <module name> */` at the top of one of our project's ESM files and it did work, but unfortunately `mminit` is one of the few files which are actually global scope; and it looks like the `@module` trick doesn't work for globally scoped scripts. 

It is dawning on me now _why_ that is the case - since it being global scope by definition makes it not a module. That being said, it would still be helpful to rename all the scripts from that file, because having `mminit` in the list of modules in our api docs is extremely unclear. Is there a potential workaround?

**Comment by Gerrit0** [comment]
Hmm, yeah, global files are a problem. They don't get a symbol, so comment discovery doesn't find any comments for them. They're the only thing reflection like this... there's probably a not completely terrible way of discovering comments for "global modules"...

**Comment by Gerrit0** [comment]
I was right, that wasn't bad at all, 20 minutes, will be available in the next release :)

**Comment by JL102** [comment]
> I was right, that wasn't bad at all, 20 minutes, will be available in the next release :)

Sweet, thanks!
