### ISSUE TITLE
[Documentation] Application class no longer accepts options parameter

### ISSUE THREAD

**Issue by Mikkal24** [TypeStrong/typedoc#2166]
## Search terms

Application, documentation

## Expected Behavior

I expect the intellisense to not suggest a parameter when it is not accepted. 

## Actual Behavior

When utilizing the Application class the comments hint that it accepts an options argument in the constructor. 

## Steps to reproduce the bug

go to https://github.com/TypeStrong/typedoc/blob/v0.23.24/src/lib/application.ts#L115 

and notice that the @param note is incorrect

![image](https://user-images.githubusercontent.com/21202515/217937068-6dafc3d9-19de-4414-b3c5-3cc0c08e2c90.png)

## Environment

-   Typedoc version: 23.24
-   TypeScript version: N/A
-   Node.js version: N/A
-   OS: N/A

**Comment by Mikkal24** [comment]
I would tag it documentation if I could!

**Comment by Gerrit0** [comment]
Resolved by #2167
