### ISSUE TITLE
[Bug] unable to install dev dependency TypeStrong / fs-fixture-builder

### ISSUE THREAD

**Issue by Mikkal24** [TypeStrong/typedoc#2171]
## Search terms

fs-fixture-builder

## Expected Behavior

I expect to be able to install fs-fixture-builder so I can run tests before submitting a PR :)

## Actual Behavior

Typedoc does nothing wrong except when installing I get this error: 

![image](https://user-images.githubusercontent.com/21202515/219471057-2ec6638a-3ca1-4696-8398-b60506e318a5.png)

Even if the commit hash worked because the devs of fs-fixture-builder have their /dist folder in the .gitignore file I'm not even sure anything would pop up if we could install it lol.

## Steps to reproduce the bug

simply clone typedoc and try to run `npm install`

## Environment

-   Typedoc version: 0.23.25
-   TypeScript version: 4.9.5
-   Node.js version: 16.19.0
-   OS: Windows

**Comment by Mikkal24** [comment]
If you want to wait on resolving this I'm working on making a PR that adds fs-fixture-builder as a local dependency in the test folder and point it at that instead since that repo seems pretty broken. (I can't get either the src folder or dist folder when i npm install it) 

I figure this is an acceptable solution since typedoc is pointing at a specific commit anyways but, let me know if you disagree!

**Comment by Mikkal24** [comment]
> Why is the dev dependency not installing?

From my research I believe it is because  `fs-fixture-builder` only included the `/dist` folder when installing from npm (specifically on the commit that TypeDoc uses)

see `files` property on the package.json https://github.com/TypeStrong/fs-fixture-builder/blob/5a9486bc66f6e36988106685768396281f6cbc10/package.json

but, the `/dist` folder is also .gitignored https://github.com/TypeStrong/fs-fixture-builder/blob/5a9486bc66f6e36988106685768396281f6cbc10/.gitignore

I think it was intended that when it is installed the "prepare" script would run and generate the dist folder when the package as installed but, since the `/src` folder is not included under `files` in package.json we don't get it when we install it via npm. 

This _has_ been updated see https://github.com/TypeStrong/fs-fixture-builder/blob/main/package.json

But, I _still_ don't get either folder when installing even from the latest commit so NPM might be cacheing some rules or something. I'm not entirely sure. 

Either way, judging from the commit history, it seems like `fs-fixture-builder` has struggled with this way of distributing the code. So I'm thinking that putting a local version in TypeDoc would be a solution until that's figured out. And then you guys (or I idk I'm new here lol) can run the tests before approving PRs in the CI/CD pipeline.  

Sorry probably more than you asked for. 

Were you able to re-create the issue?

**Comment by Mikkal24** [comment]
i'm going to try cloning and installing on my linux laptop see if it makes a difference

**Comment by Mikkal24** [comment]
well I'm not so sure about that lol. 

it seemed to install correctly on my linux machine. Now I am thinking it's a networking issue on my end :/ 

going to close this for now

**Comment by tintinthong** [comment]
I experience this issue to

**Comment by tintinthong** [comment]
For those of you who have faced this issue, the main reason is that `prepare` script is not being run when `npm install` of github repo.

Here is the relating [issue](https://github.com/npm/cli/issues/2890) 
Here is the comment that [fix](https://github.com/npm/cli/issues/2890#issuecomment-1050345098). TLDR upgrade to npm@8.5.2 and above
