### ISSUE TITLE
How to correctly use multiple entrypoints with root entry?

### ISSUE THREAD

**Issue by zfy0701** [TypeStrong/typedoc#2173]
## Search terms

multiple entrypoints

## Question
My typedoc configs looks like this:
{
  "entryPoints": [
    "./src/index.ts",
    "./src/core/index.ts",
  ]
}

the generated doc then will give an entry called 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/1646270/219757411-cefc5d99-f3e3-4875-a95d-f53484a04888.png">

instead just putting them as root module, how to fix this?

**Comment by Gerrit0** [comment]
You can rename modules with the [`@module`](https://typedoc.org/tags/module/) tag. I suspect what you really want is a single entry point that looks like this though:

```ts
// api.ts
export * from "./index"
export * as core from "./core/index"
```

**Comment by zfy0701** [comment]
not exactly, I use multiple export for package.json, that why I have different modules so I could do 

import * from "my_package"
import * from "my_package/a"
import * from "my_package/b"

so I don't want a, b show as namespace. they need to be module

rename module doesn't work well
the best thing I can do for now is rename it as '.' and it will show like this:

![image](https://user-images.githubusercontent.com/1646270/223899379-f8e83366-4d43-4772-8004-6e3c64fd11ce.png)

but want I really want is just make them as root package
