### ISSUE TITLE
The entry point ./lib does not exist or is not included in the program for your provided tsconfig.

### ISSUE THREAD

**Issue by squarfiuz** [TypeStrong/typedoc#2177]
Hey! I've been trying to fix this error for a while (`"The entry point ./lib does not exist or is not included in the program for your provided tsconfig."`) but I couldn't find anything, do you have an idea 😁 ?

![image](https://user-images.githubusercontent.com/104249551/220373510-26e48275-16f5-4e84-ae50-8765e24b5f95.png)

**Comment by ryangibbsnc** [comment]
@squarfiuz what was the fix?

**Comment by Gerrit0** [comment]
Likely `--entryPointStrategy expand` if you intended to have TypeDoc  document every file under a folder rather than looking for `index.ts` inside the folder
