### ISSUE TITLE
undefined type is avoided in function param when it is used with an or operator

### ISSUE THREAD

**Issue by roggervalf** [TypeStrong/typedoc#2178]
## Search terms

undefined type, function parameters

## Expected Behavior

when a param in a function interface has this signature:

```ts
failed: (
    job: Job | undefined,
    error: Error,
    prev: string,
  ) => void;
```

job parameter should appear with both possibilities in our docs, (Job | undefined)
## Actual Behavior

undefined type is avoided when the documentation is generated. Only Job appears

## Steps to reproduce the bug

Add a param in a function with a similar signature as previous example.
## Environment

-   Typedoc version:0.23.25
-   TypeScript version:4.9.5
-   Node.js version:14.20.1
-   OS:Ubuntu

**Comment by Gerrit0** [comment]
You probably have strictNullChecks turned off - in which case `Job | undefined` is equivalent to `Job` according to the compiler. I can't reproduce this with strict turned on. https://github.com/TypeStrong/typedoc-repros/actions/runs/4266319079
