### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by illuxio** [TypeStrong/typedoc#218]
I would ask when the next release is planed, because I would love to use typedoc with typescript 1.8.

**Comment by aciccarello** [comment]
I know @blakeembrey got npm permissions but I'm not sure that he's had time to push the release to npm

Related: #204

**Comment by blakeembrey** [comment]
@illuxio I got permission a couple of weeks ago. Sadly I've been busy. I plan to do the release tomorrow now, I just need some time to make sure all the changes are accurate (especially when interacting with the default themes). Thanks for your patience 😄
