### ISSUE TITLE
Coalesce function **Returns** sections

### ISSUE THREAD

**Issue by ilg-ul** [TypeStrong/typedoc#2180]
## Search Terms

@returns

## Problem

Functions are rendered with two distinct sections, the first with the content of the `@returns` tag, and the second with the actual TS type.

![Screenshot 2023-02-22 at 17 28 37](https://user-images.githubusercontent.com/362732/220674221-abb19469-2d8c-48ce-815f-1f5e495f46be.png)

## Suggested Solution

Coalesce the two sections, and render the `@returns` content on the next line after the type.

This would also be more consistent with the way parameters are rendered (a bulleted list followed by a paragraph with the description).

**Comment by ilg-ul** [comment]
Any thoughts on this proposal?

**Comment by Gerrit0** [comment]
Labeled help wanted to indicate PRs will be gladly accepted, not something that I'm likely to have time to do anytime soon.

**Comment by ilg-ul** [comment]
Ok, I'll take a look and possibly prepare a PR.

**Comment by ilg-ul** [comment]
@futurGH, what do you think about this proposal, does it make any sense?

**Comment by futurGH** [comment]
Definitely makes sense, I'll see if I can take a stab at it before Gerrit0 gets to it 🙂

**Comment by ilg-ul** [comment]
Gerrit0 said he will not have time for it anytime soon; I'd be happy to contribute to the project, but I'm not familiar with the internals, and, until I'll get there, your PR will be long ago merged. ;-)

**Comment by ilg-ul** [comment]
@futurGH explained me that, with the current implementation, the `@returns` content is part of a composite with all comments, which are all rendered in a loop, and moving the `@returns` content after the return type would require filtering out in the current loop, and adding a second loop where only `@returns` is filtered in, which, I agree, is not exactly an elegant solution.

In this case probably the solution would be to parse `@returns` into a separate property, and render it separately after the return type. Such a change is not trivial (at least for my current skills), and I have no idea what the implications would be, so I let the project maintainers to suggest a solution.

**Comment by ilg-ul** [comment]
Wow! Looking forward to testing the new release.

Thank you!
