### ISSUE TITLE
Does it support multiple languages?

### ISSUE THREAD

**Issue by CasualMing** [TypeStrong/typedoc#2182]
## Question
Hi author, I would like to ask the following, will you consider adding multi-language configuration to the build configuration for the text description in the HTML after the build?

**Comment by Gerrit0** [comment]
There is a plugin which adds support for this. It's not something I plan on adding into typedoc itself, primarily since I'm not really working on it right now, just doing the minimum for maintenance. https://www.npmjs.com/package/typedoc-plugin-localization?activeTab=readme
