### ISSUE TITLE
TypeDoc generates blank documentation

### ISSUE THREAD

**Issue by FadhiliNjagi** [TypeStrong/typedoc#2185]
## Search terms

Express JS, Node JS, Blank Documentation

## Question
I'm trying to document my Express JS API using TypeDoc, but I get a rather empty documentation generated.
![image](https://user-images.githubusercontent.com/54543510/221230662-76ce9615-9377-4541-972f-cacf85625094.png)

This is my API file structure
![image](https://user-images.githubusercontent.com/54543510/221230378-808cb6da-ce4b-494d-8d2e-6752d5871a9d.png)

This is my tsconfig.json:
```json
 {
  "compilerOptions": {
    "target": "es5", 
    "module": "commonjs",
    "moduleResolution": "node", 
    "esModuleInterop": true, 
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "typedocOptions": {
    "entryPoints": ["server.ts"],
    "out": "docs"
  }
}

```

What am I doing wrong? All materials on the web point to adding the TypeDoc option `{"mode": "modules}`. But that's been deprecated. I would appreciate any guidance.

**Comment by Gerrit0** [comment]
TypeDoc is really meant to document libraries -- not applications. It only documents what you export from your entry points, so if you don't export anything from `server.ts`, there won't be anything to document from TypeDoc's point of view.

**Comment by FadhiliNjagi** [comment]
I exported my Express app instance in my server.ts and tweaked my `typedoc.json`. This way, I was able to get half-decent documentation.
```JSON
{
  "entryPoints": ["server.ts", "src/**/*.ts"],
  "out": "docs",
  "entryPointStrategy": "expand",
  "plugin": ["typedoc-theme-hierarchy"],
  "theme": "hierarchy",
  "name": "My Awesome API",
  "includeVersion": true,
  "exclude": ["**/node_modules/**/*.*", "**/dist/**/*.*"],
  "excludeExternals": true,
  "readme": "./README.md"
}
```
