### ISSUE TITLE
Typedoc storybook Add-on

### ISSUE THREAD

**Issue by sparkeplug** [TypeStrong/typedoc#2186]
## Search Terms

Storybook, Storybook Addon, Tsdoc, Typedoc

## Problem

Typedoc is a good tool to auto document a projects codebase. Whereas storybook is good in terms of documenting components and application in an interactive testbed application. What if we have best of both worlds ? Currently in storybook a developer has to create explicit "stories" and "MDX" files to document. But there is no way to use the same tool to also refer the available functions and types information aimed for developers.

I feel both tool should go hand in hand. If both converge a common documentation output can be generated targeting different teams in a project. Especially Dev's.

## Suggested Solution

A custom storybook ADD-ON called "typedoc-storybook-add-on". This tool should be able to inject the TYPEDOC generated documentation information in an MDX format into storybook through an addon.

**Comment by Gerrit0** [comment]
I think this is a neat idea, but it's definitely out of scope for this project, I don't have the time to maintain another tool.
