### ISSUE TITLE
Should typedoc-default-themes be an optional dependency?

### ISSUE THREAD

**Issue by zakhenry** [TypeStrong/typedoc#219]
In the case where a user provides their own theme, it is redundant to pull the (relatively large) typedoc-default-themes package. Rather it should be defined as an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies) so consumers that use their own theme don't download it.

**Comment by blakeembrey** [comment]
I don't think so. `optionalDependencies` are still installed, they are just allowed to fail on things like the build step. Also, I think the package should remain a seamless experience for all users. I'll see what I can do about shrinking the installation size.

**Comment by zakhenry** [comment]
True that they are installed anyway by default, but not if installed with `npm install --no-optional` (https://docs.npmjs.com/cli/install) which would be done in ci/cd etc where install performance is desireable

**Comment by blakeembrey** [comment]
Keeping it as a dependency. I don't see any compelling reason to change it since 99% of people will be using this.
