### ISSUE TITLE
Rendering of the navigation pane on iPad is shifted down

### ISSUE THREAD

**Issue by ilg-ul** [TypeStrong/typedoc#2191]
I noticed a small problem with rendering the generated site on an iPad: the navigation pane seems shifted down and the last link is not visible:

![IMG_0253](https://user-images.githubusercontent.com/362732/223152899-36f0acda-d1f5-4019-b1ea-1e47521b17ad.PNG)

When rendered with Safari on macOS, it is ok:

![Screenshot 2023-03-06 at 17 27 20](https://user-images.githubusercontent.com/362732/223154764-ae3f055c-8361-4b12-bf9c-b62961321ee0.png)

The [site](https://xpack.github.io/logger-ts/) was generated with 0.23.25.

**Comment by ilg-ul** [comment]
On iPhone it is also ok:

![IMG_2453](https://user-images.githubusercontent.com/362732/223161468-5d6fc9c9-5036-4f8d-823b-f1fafdeb7124.PNG)

**Comment by Gerrit0** [comment]
I don't have an iPad suitable for troubleshooting this - PR welcome

**Comment by ilg-ul** [comment]
I have the iPad, but I don't have a CSS knowledge suitable for troubleshooting this. :-(

If someone can suggest a fix, I can test it.

**Comment by ilg-ul** [comment]
Another question: are those spaces between Setting, Modules and the list really necessary?

**Comment by ilg-ul** [comment]
I just checked and the issue can be also reproduced using an iPad simulator. Just be sure you select a 4th or 5th generation iPad (9.7", 2048x1536) and landscape screen orientation. Interestingly enough, on larger iPads I could not reproduce the issue.

**Comment by futurGH** [comment]
It's because certain iPads have the precise display dimensions (a computed width of 1024px) that would cause this edge case. My PR should resolve the top margin as well as the large spacing. Thanks for pointing it out.

**Comment by ilg-ul** [comment]
> a computed width of 1024px

Does this also apply to a 9.7" screen with 2048x1536?

**Comment by futurGH** [comment]
Yeah. iOS devices, among others, have what's called a device pixel ratio. Although it has 2048 physical pixels across, that'd be illegible on a 9.7" display, so it presents browsers a width of 1024px and uses the pixels in between for stuff like finer font rendering; what Apple calls "retina".

**Comment by ilg-ul** [comment]
Thank you @futurGH for the explanation.

So, if you think that this fix also applies to my iPad, and there is no need to test anything now, I'll wait for the next release.
