### ISSUE TITLE
NPM latest tag is pointing at beta version

### ISSUE THREAD

**Issue by akphi** [TypeStrong/typedoc#2193]
Hi @Gerrit0,

Is it intentional that we're pointing the `latest` alias on NPM at `0.24.0-beta.2`? - https://www.npmjs.com/package/typedoc
Could we point `latest` to `0.23.6` and `beta` at `0.24.0-beta.2` instead, this confuses package upgrader tools like `Yarn interactive-tools`, etc.?

Thanks!

**Comment by Gerrit0** [comment]
Nope, that's a mistake! I'll fix as soon as I get home, thanks for the report

**Comment by Gerrit0** [comment]
Fixed!

**Comment by akphi** [comment]
@Gerrit0 Thanks so much for the fast response!
