### ISSUE TITLE
Default value for out option

### ISSUE THREAD

**Issue by DiFuks** [TypeStrong/typedoc#2195]
Hello! I am the author of the [typedoc-theme-hierarchy](https://github.com/DiFuks/typedoc-theme-hierarchy) library

When the "out" option is not specified, I can't figure out where to copy the custom css and js for my theme

https://github.com/DiFuks/typedoc-theme-hierarchy/issues/17

A possible solution is to return the default value, namely "docs" https://github.com/TypeStrong/typedoc/blob/c75f44f1153c0ae6a0e682dda5cf6a94267b24fc/bin/typedoc#L80

I can solve this problem by specifying "docs" as the default knowledge on my end. But this can break if the path to the generated folder changes on your end.

**Comment by Gerrit0** [comment]
The original reason it was done like this was so that TypeDoc could check if the json/docs options were set, and not generate docs if json was set, since there's an `isSet` method on options now, seems like a reasonable change.
