### ISSUE TITLE
Small inconsistency in rendering category names

### ISSUE THREAD

**Issue by ilg-ul** [TypeStrong/typedoc#2196]
## Search Terms

@category inconsistency

## Problem

I'm using the @category tag to group some accessors and methods, and in the index they are listed as `Accessors - {{ categoryName }}`, or `Methods - {{ categoryName }}`, while in the listing below the dash is gone and the order is reversed, with the category name shown first. In my case, this made naming the categories a bit more difficult, trying to match both formats.

![Screenshot 2023-03-09 at 12 18 59](https://user-images.githubusercontent.com/362732/223995634-33fc1aed-847c-424b-9c4b-d8ad1946e653.png)

![Screenshot 2023-03-09 at 12 19 19](https://user-images.githubusercontent.com/362732/223995678-07e8afff-7ac9-4662-85e5-b975b1a14b79.png)

## Suggested Solution

Use the same order as in the index, and the dash.

**Comment by Gerrit0** [comment]
That's weird, should be an easy fix

**Comment by ilg-ul** [comment]
The index names are rendered in `src/lib/output/themes/default/partials/index.tsx`:

```html
<h3 class="tsd-index-heading">{prependName ? `${prependName} - ${item.title}` : item.title}</h3>
```

The second location where the name is printed is less evident, apparently some objects are created, but I could not identify where the names are computed. :-(

Perhaps @futurGH can be of more help than I can.

**Comment by futurGH** [comment]
Just need to switch around the order here:
https://github.com/TypeStrong/typedoc/blob/c75f44f1153c0ae6a0e682dda5cf6a94267b24fc/src/lib/output/themes/default/partials/members.group.tsx#L12-L13

**Comment by ilg-ul** [comment]
Thank you for pointing the location. 

Time permitting, could you also add a PR for this? The `.tsx` syntax is new to me and I'd probably mess something. :-(

**Comment by futurGH** [comment]
Sure
