### ISSUE TITLE
Support @link

### ISSUE THREAD

**Issue by cfischer** [TypeStrong/typedoc#220]
Another useful tag which we could support is [`{@link}`](http://usejsdoc.org/tags-inline-link.html).

**Comment by aciccarello** [comment]
I know some markup is supported. The `[text](url)` syntax may already support URLs

**Comment by aciccarello** [comment]
There is discussion of `@link` on #79. There is commit mentioning that it was implemented but I haven't tried it. Using double square brackets `[[SymbolName]]` has been supported for a while.

**Comment by vhakulinen** [comment]
The `{@link}` seems to work with symbols (e.g. `{@link my_symbol}`).

**Comment by petrbela** [comment]
Linking directly to fields works, too (`{@link MyClass.myMethod}`)
