### ISSUE TITLE
Allow Typescript 5.0

### ISSUE THREAD

**Issue by nandi95** [TypeStrong/typedoc#2201]
## Search Terms
typescript 5.0

## Problem

Typescript 5.0 released but the peer dependencies do not allow v5 yet.

## Suggested Solution

Allow 5.0.x in the peer dependencies.

If also updating the package to v5 this is a relevant flag to the project [verbatimModuleSyntax](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#verbatimmodulesyntax) and it's connection to `isolatedModules`
An alternative option for imports could be to setup ts lint and use [@typescript-eslint/consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md)

I had a quick attempt at updating but ended up with 2 errors in tests
evals to false:
https://github.com/TypeStrong/typedoc/blob/d2057a111b6e69e45054a369551116c85fb2b8c7/src/test/issueTests.ts#L224 
I _suspect_ here it failes a deep equality check:
https://github.com/TypeStrong/typedoc/blob/d2057a111b6e69e45054a369551116c85fb2b8c7/src/test/converter2.test.ts#L61

**Comment by LoboMetalurgico** [comment]
Yes, please

**Comment by Gerrit0** [comment]
Will probably be Sunday, don't expect I'll have time before then

**Comment by Gerrit0** [comment]
Support released in 0.23.28

**Comment by skjnldsv** [comment]
:tada: :pray: :rocket:
