### ISSUE TITLE
Individual --exclude patterns per entryPoint possible?

### ISSUE THREAD

**Issue by opt12** [TypeStrong/typedoc#2208]
## Search terms

exclude, entryPoint, expand
## Question
Is it somehow possible to have an individual exclude pattern for each entry point specified in conjunction with the `entryPointStrategy "expand"`?

In our use case, we want to have a unified documentation for a bunch of different apps and libraries in a monorepo.
We achieve this by using the "typedoc-plugin-merge-modules" and the "typedoc-plugin-resolve-crossmodule-references". 

All in all this works out quite well.

Unfortunately, the usage of file-types differs from portion to portion in our code. So it would be helpful to have an individual exclude list per each specified `entryPoint`.

- Is this somehow achievable?

- Is it achievable to have different typedoc settings in different areas of the monorepo's sources? E. g. by placing different typedoc.json files in the root of each entry-point?

Thanks a lot!
Felix

**Comment by Gerrit0** [comment]
Nope, that's not possible for expand, implementing that would be a complete rework of how that entry point strategy is handled.

TypeDoc 0.24's packages mode (see #2197) provides the ability to have different configuration in each module, and should be a much better configuration setting for monorepos.

**Comment by opt12** [comment]
Ok, I'll give the 0.24 a try and see, whether this could serve our needs. Thanks for your incredible work.
