### ISSUE TITLE
bug: Collapsed "Index" table

### ISSUE THREAD

**Issue by KillerJulian** [TypeStrong/typedoc#2214]
## Actual Behavior

![Screenshot1](https://user-images.githubusercontent.com/36083682/227998196-9176d922-d3f1-441d-a401-fc578b08cbac.png)

The error occurs when the "Index" of the page is collapsed and the "Protected" check mark is removed. When you unfold the page again, no more content is displayed. After reloading the page in the collapsed state, everything is normal again. 

## Environment

-   Typedoc version: 0.23.28
-   TypeScript version: 5.0.2
-   Node.js version: v16.3.0

**Comment by Gerrit0** [comment]
I poked at fixing this a bit, but realized that getting it right would likely be more work than is worthwhile, when just getting rid of the animation makes sure it will never break. v0.24 will fix this.

**Comment by Gerrit0** [comment]
Fixed released in v0.24.0
