### ISSUE TITLE
Unable to resolve types from dependency

### ISSUE THREAD

**Issue by huangmin-ms** [TypeStrong/typedoc#2215]
## Question

Hi All,

 I am trying to generate json for package: [@azure/service-bus@7.8.1](https://www.npmjs.com/package/@azure/service-bus/v/7.8.1?activeTab=code) which depends on pacakge [long](https://www.npmjs.com/package/long).

```
import Long from 'long';

receiveDeferredMessages(sequenceNumbers: Long | Long[], options?: OperationOptionsBase): Promise<ServiceBusReceivedMessage[]>;
```
But in the output json file, `Long | Long[]` cannot be resolved (resolved as any). 

```
{
    "id": 610,
    "name": "sequenceNumbers",
    "kind": 32768,
    "kindString": "Parameter",
    "flags": {},
    "comment": {
        "summary": [
            {
                "kind": "text",
                "text": "The sequence number or an array of sequence numbers for the messages that need to be received."
            }
        ]
    },
    "type": {
        "type": "intrinsic",
        "name": "any"
    }
}

```

typedoc version: `^0.23.26`

In our tool, we will first install [@azure/service-bus@7.8.1](https://www.npmjs.com/package/@azure/service-bus/v/7.8.1?activeTab=code) to a temp folder and invoke typedoc with below code:

[@azure/service-bus@7.8.1](https://www.npmjs.com/package/@azure/service-bus/v/7.8.1?activeTab=code) install path: <temp_folder>\\node_modules\\@azure\\service-bus

[long](https://www.npmjs.com/package/long) install path: <temp_folder>\\node_modules\\long

```
const app = new Application();

    app.options.addReader(new TSConfigReader());

    const tsConfigPath = createTsConfig(); // please see tsConfig below

      app.bootstrap({
          tsconfig: tsConfigPath,
          logger: "none",
          compilerOptions: {
              strictNullChecks: true,
          }
      })

      const project = app.convert();

      return app.serializer.projectToObject(project) as any as Node;

```

```
{
    "typedocOptions": {
        "entryPointStrategy": "expand",
        "entryPoints": [
            "<temp_folder>\\node_modules\\@azure\\service-bus\\types\\latest\\service-bus.d.ts"
        ],
        "excludeInternal": true,
        "excludePrivate": true,
        "externalPattern": [
            "./node_modules/**"
        ],
        "excludeExternals": true,
        "skipErrorChecking": true,
        "name": "@azure/service-bus"
    }
}
```

Can you please help to let me know where I did wrong. Thanks in advance.

**Comment by Gerrit0** [comment]
> skipErrorChecking

If you turn that off, there might be useful errors, I suspect types can't be resolved for some reason.

**Comment by huangmin-ms** [comment]
> > skipErrorChecking
> 
> If you turn that off, there might be useful errors, I suspect types can't be resolved for some reason.

Sure, will try tomorrow.

**Comment by huangmin-ms** [comment]
> > skipErrorChecking
> 
> If you turn that off, there might be useful errors, I suspect types can't be resolved for some reason.

The error log said:
```
"Module '\"<temp_folder>\node_modules/long/index\"' can only be default-imported using the 'esModuleInterop' flag"
```
