### ISSUE TITLE
Add a way to flatten namespaces

### ISSUE THREAD

**Issue by ceymard-salesway-biogaran** [TypeStrong/typedoc#2216]
## Search Terms

flatten namespaces

## Problem

I have a library that exports quite a lot of symbols. Among them are a few namespaces, with a few symbol inside each. These exist mostly to keep the root namespace clean somewhat clean and to group items that are related for completion convenience.

Right now, when I generate the documentation, it creates a tree for the namespaces before the exported symbols, like so :

```
Modules
  - $bind
  - ... other similar modules
 
# and then, the exported symbols
  - [F] all
  - [C] the
  - [F] other
  - [V] stuff
  - ...
```

## Suggested Solution

What I would like would be the option to flatten namespaces and have something like that :

```
 - [F] $bind.string
 - [F] $bind.boolean
 - [F] $bind.contenteditable
 - ...
 - [F] all
 - [C] the
 - [F] other
 - [V] stuff
```

Maybe through the use of a configuration option like `--flattenNamespaces` ?

**Comment by Gerrit0** [comment]
There is a plugin which can do this: https://www.npmjs.com/package/typedoc-plugin-merge-modules

I think I want to keep this functionality in plugin space, allowing TypeDoc proper to focus on creating documentation which accurately matches your exports.
