### ISSUE TITLE
To Display only the typescript class names instead of entire file path in the generated document

### ISSUE THREAD

**Issue by bboycs** [TypeStrong/typedoc#2217]
![image](https://user-images.githubusercontent.com/13663798/228477363-5d2bd69c-1ad6-47e3-b404-485d719754fa.png)

Used to solved with configure with mode:"file". 
Now it seems not possible 

Kindly assist
thank you

**Comment by Gerrit0** [comment]
TypeDoc documents what you export - most libraries should just give typedoc their top level index.ts that exports everything. There's also typedoc-plugin-merge-modules

**Comment by bboycs** [comment]
> TypeDoc documents what you export - most libraries should just give typedoc their top level index.ts that exports everything. There's also typedoc-plugin-merge-modules

thanks
