### ISSUE TITLE
Smarter sidebar default scroll state

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2218]
## Search Terms

theme, scroll, scroll state, side bar, sidebar

## Problem

Since 0.23, every (non-class) function is its own page. This makes it harder to see the documentation of multiple functions quickly (e.g. to skim through what a library has to offer) since the sidebar does not remember its scroll state between navigations, so you have to scroll down to the correct spot each time.

Example: 
Here, I scrolled down to see `SomeType`.
![image](https://user-images.githubusercontent.com/20878432/228534889-2740c528-65ee-44e2-a7e7-389d814a7d40.png)

After clicking it, the sidebar scrolled back up.
![image](https://user-images.githubusercontent.com/20878432/228535013-b4ef4ac0-87a4-498a-9db3-cbd67b3d4d96.png)

## Suggested Solution

I can think of 2 ways to address this problem:

1. Don't change the scroll state of the sidebar if the sidebar's content doesn't change between navigations. 
    This is could be trivially implemented if something like React client-side routing were to be used. Of course, adding client-side routing would likely be non-trivial, but it would also have additional advantages (such as no page flickering during loads).

2. When loading the page, scroll the sidebar such that the current element is visible.
    This is similar to the behavior of IDEs like VSCode that scroll to the currently selected file in their file explorer.

**Comment by Gerrit0** [comment]
Client side rendering doesn't play nicely with static html pages aren't served from a webpage, which is a feature I'm loath to give up... 

I think the second solution would be a good change

**Comment by RunDevelopment** [comment]
Thank you @Gerrit0!
