### ISSUE TITLE
Eslint plugin

### ISSUE THREAD

**Issue by Diboby** [TypeStrong/typedoc#2221]
## Search Terms
Eslint plugin

## Problem
Have a eslint-plugin can help to define eslint rules which can be useful for :
- mandatoring, in a pipeline build, the typedoc documentation to test developers code.
-  checking for missing params in the documentation, etc.

## Suggested Solution
I suggest **eslint-plugin-typedoc** for the package name.
A similar tool exists for jsdoc : [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc)

**Comment by Gerrit0** [comment]
The JSDoc plugin you linked can be used in TypeScript files, and has rules which meet both of your requests, I'd recommend using it - not sure there is benefit to a typedoc specific plugin here.
