### ISSUE TITLE
Rendering of & as &amp; in TOC

### ISSUE THREAD

**Issue by ilg-ul** [TypeStrong/typedoc#2224]
## Search terms

TOC, ampersand

## Expected Behavior

Render ampersand in TOC as `&`.

## Actual Behavior

Ampersand in TOC is rendered as `&amp;`.

## Steps to reproduce the bug

![Screenshot 2023-04-09 at 09 00 58](https://user-images.githubusercontent.com/362732/230757385-0c7e3728-2f53-462b-9d19-d01cdfc8197d.png)

## Environment

-   Typedoc version: 0.24.1
-   TypeScript version: 4.9.5
-   Node.js version: 16.19.1
-   OS: macOS 12.6.3

**Comment by Gerrit0** [comment]
Shoot, I totally forgot that content would already be escaped... interesting dilemma here actually, since in-line elements probably should be stripped when generating the TOC. Ideally, I think getting the text from `.textContent` on the header should be shown, which is kind of annoying to get without DOM apis.

**Comment by krassowski** [comment]
We see something possibly related over at https://github.com/jupyterlab/jupyterlab/pull/14367 (sorry, I was not sure if you prefer new issues or comment here) - the link in the title is rendered as HTML:

<img width=300px src="https://user-images.githubusercontent.com/5832902/231571022-c60bca30-7e02-4f3b-bda7-fd0a2a799e3b.png">

The title in question is `# [JupyterLab](http://jupyterlab.github.io/jupyterlab/)` in markdown (and actually ideally we skip it as this is just the title).

**Comment by Gerrit0** [comment]
Yep, this is the same underlying issue

**Comment by Gerrit0** [comment]
Wow, that was a lesson in insanity! HTML entities are ***special***.

**Comment by ilg-ul** [comment]
I confirm, with v0.24.2 the TOC is rendered correctly in my projects.

Thank you!
