### ISSUE TITLE
Semantic colors don't work in type and function signatures

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2227]
## Search terms

semantic color type function signature

## Expected Behavior

TypeDoc shows the kind of type linked to in function signatures or elsewhere using color. `type`s are red, `interface`s are green, and `class`es are blue. This is a great feature.

![image](https://user-images.githubusercontent.com/20878432/230764913-19016dd0-5784-405b-8fbf-0fee440122ca.png)

## Actual Behavior

This feature only works on class and interface pages. It does not work on variable, type, and function pages.

![image](https://user-images.githubusercontent.com/20878432/230765027-f5b08e0b-6838-4296-b1bc-19ea4fbba83c.png)
![image](https://user-images.githubusercontent.com/20878432/230765132-7680ffc1-cf92-48ed-aa89-671c1707ad93.png)
![image](https://user-images.githubusercontent.com/20878432/230765157-cbc4299c-0d38-4988-bef5-f076a44e9960.png)
(`NodeFactory<T>` is an interface.)

## Steps to reproduce the bug

Sorry for the non-minimal reproduction repo:
1. Download https://github.com/RunDevelopment/refa
2. `npm ci`
3. `npm i -D typedoc@0.24.1`
4. `npm run build:docs`
5. See docs at `docs/index.html`

The current docs generated by 0.23.28, which has the same issue, can be found [here](https://rundevelopment.github.io/refa/docs/v0.11.0/index.html) ([`commonCharacter`](https://rundevelopment.github.io/refa/docs/v0.11.0/classes/CharSet.html#commonCharacter), [`Word`](https://rundevelopment.github.io/refa/docs/v0.11.0/types/Word.html), [`createCharSet`](https://rundevelopment.github.io/refa/docs/v0.11.0/functions/JS.createCharSet.html), [`nodeFactory`](https://rundevelopment.github.io/refa/docs/v0.11.0/variables/ENFA.nodeFactory.html)).

## Environment

-   Typedoc version: 0.24.1 (same issue in 0.23.x)
-   TypeScript version: 5.0.2
-   Node.js version: v16.13.0
-   OS: Win10

**Comment by Gerrit0** [comment]
Huh, that's odd. I thought this was implemented in a way that it'd always semantically highlight.

**Comment by RunDevelopment** [comment]
Thank you @Gerrit0!
