### ISSUE TITLE
private class properties (ECMAScript # properties) should not cause warning

### ISSUE THREAD

**Issue by benneq** [TypeStrong/typedoc#2232]
## Search terms

private, class, property, #, is referenced by, but not included in the documentation

## Expected Behavior

There should be no warning, because it doesn't affect the generated documentation

## Actual Behavior

I get this warning:
```
[warning] StackNode, defined in ./src/stack.ts, is referenced by Stack.#top but not included in the documentation.
```
StackNode isn't referenced anywhere else, because it's an implementation defail. 
And because Stack.#top isn't included in the generated tsdoc, there no way StackNode is needed.

## Steps to reproduce the bug

```
class StackNode<T> {
  next: StackNode<T> | undefined;
  constructor(public value: T) {}
}

/**
 * ...
 * @template T - ...
 */
export class Stack<T> {
  /**
   * ...
   */
  #top?: StackNode<T> | undefined;
}
```

## Environment

-   Typedoc version: 0.24.1
-   TypeScript version: 5.0.3
-   Node.js version: 18.12.1
-   OS: Windows 11 22H2

**Comment by Gerrit0** [comment]
You get this warning because `#top` *is* in the documentation. If you set `--excludePrivate` to prevent private members from appearing in the documentation, the warning will go away.

**Comment by benneq** [comment]
Ah! .. I had to enable the "Private" checkbox in the secret settings menu! 

Thanks for the fast response 😸 

![image](https://user-images.githubusercontent.com/1627305/230835962-3904b8a7-b169-40dd-87d0-bca8fd71cc4a.png)
