### ISSUE TITLE
Links for "Implementation of X.y" are missing sometimes

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2233]
## Search terms

Implementation of

## Expected Behavior

The "Implementation of X.y" section should always link to both `X` and `y`. 

![image](https://user-images.githubusercontent.com/20878432/230890198-90f3657b-843c-42a0-bd5e-d968ec2631c2.png)

## Actual Behavior

If `y` and the implementation of `y` are not the same *kind*, then there will be no link. 

Note: I have only tested with methods implementing a property, but I highly suspect that properties implementing a method will have the same issue. Another case that should be tested is accessors implementing methods.

In the following example, `isFinal` is declared as a property, but implemented as a method.

![image](https://user-images.githubusercontent.com/20878432/230890518-552ad6cf-8fd8-4d53-b38e-32fa28b40ed5.png)
![image](https://user-images.githubusercontent.com/20878432/230890621-f9af7f78-ffee-4a60-9fc2-02b4a1a17be5.png)

## Steps to reproduce the bug

1. Download https://github.com/RunDevelopment/refa
2. `npm ci`
3. `npm i -d typedoc@0.24.1`
4. `npm run build:docs`
5. Open `docs/index.html`

Or see the doc pages generated by 0.23.28: [`ENFA.Builder#isFinal`](https://rundevelopment.github.io/refa/docs/v0.11.0/classes/ENFA.Builder.html#isFinal) and [`FABuilder#isFinal`](https://rundevelopment.github.io/refa/docs/v0.11.0/interfaces/FABuilder.html#isFinal).

## Environment

-   Typedoc version: 0.24.1 (or 0.23.x)
-   TypeScript version: 5.0.2
-   Node.js version: 16.13.0
-   OS: Win10

## Additional context

It's import for typedoc to support both styles. Property style declarations in interfaces have slightly different semantics to method style declarations, so we sometimes must use property style to ensure correctness. For more info, see [TypeScript ESLint's `method-signature-style` rule](https://typescript-eslint.io/rules/method-signature-style).

**Comment by Gerrit0** [comment]
FABuilder - https://github.com/RunDevelopment/refa/blob/33a0c5ef2080290fc615320af40cc4a6cbfe6a07/src/fa-types.ts#L163
ENFA.Builder - https://github.com/RunDevelopment/refa/blob/33a0c5ef2080290fc615320af40cc4a6cbfe6a07/src/enfa.ts#L945

Saving links since I can't just click on the provided links to get the source
