### ISSUE TITLE
Documentation of all nested files of nested sub folders

### ISSUE THREAD

**Issue by foulong** [TypeStrong/typedoc#2235]
## Search terms

nested sub folder

## Expected Behavior

```
src/
   bin/
   controllers/
      api/
         file_one.ts
      engine/
         file_two.ts
   routes/
      api/
```

Explore all nested files of nested sub folders in "src" folder :
```bash
./node_modules/typedoc/bin/typedoc src/**/*.ts --out doc --skipErrorChecking
```

file_one.ts and file_two.ts files will be included in the generated documentation.

## Actual Behavior

Explore only files in "src" folder, not in nested sub folder of "src" folder :
```bash
./node_modules/typedoc/bin/typedoc src/**/*.ts --out doc --skipErrorChecking
```

file_one.ts and file_two.ts files aren't included in the generated documentation.

-----

Explore only files in sub folder of a first level of depth of "src" folder, not in nested sub folder of "src" folder

```bash
./node_modules/typedoc/bin/typedoc src/**/**/*.ts --out doc --skipErrorChecking
```

file_one.ts and file_two.ts files aren't included in the generated documentation.

## Steps to reproduce the bug

.

## Environment

-   Typedoc version: 0.23.25
-   TypeScript version: 4.9.5
-   Node.js version: 14.18.1
-   OS: Windows 11

Thx a lot in advance.

PS : for the moment, i use this workaround : 
```bash
./node_modules/typedoc/bin/typedoc src/*.ts src/*/*.ts src/*/*/*.ts src/*/*/*/*.ts src/*/*/*/*/*/*.ts --out doc --skipErrorChecking
```

**Comment by Gerrit0** [comment]
Based on what you said went wrong, I suspect your shell - not typedoc - is expanding the globs. If you run `./node_modules/typedoc/bin/typedoc "src/**/*.ts"` (with quotes), you'll prevent your shell from expanding the globs and pass them to TypeDoc to do the work.

Incidentally, in testing this to make sure it worked correctly, I found a bug with a single directory being passed to TypeDoc, so even if you'd have done this in 0.24.1, it wouldn't have worked properly!

**Comment by foulong** [comment]
Thx for your response.

It doesn't work. I have errors.


With single quote :
```bash
./node_modules/typedoc/bin/typedoc 'src/**/*.ts' --out doc --skipErrorChecking
TypeDoc exiting with unexpected error:
Error: ENOENT: no such file or directory, scandir 'E:/project01/src/**'
    at Object.readdirSync (fs.js:1047:3)
    at glob ......................
```

With double quotes :
```bash
./node_modules/typedoc/bin/typedoc "src/**/*.ts" --out doc --skipErrorChecking
TypeDoc exiting with unexpected error:
Error: ENOENT: no such file or directory, scandir 'E:/project01/src/**'
    at Object.readdirSync (fs.js:1047:3)
    at glob ......................
```

**Comment by Gerrit0** [comment]
Did you upgrade typedoc? Before 0.24.4 the expansion is broken

**Comment by foulong** [comment]
Hi @Gerrit0,

i upgrade to 0.24.5 version.
I have no longer errors (with single and double quotes).
But, it explores only files in "src" folder, not in nested sub folder of "src" folder (with single and double quotes).

For the moment, i must ever use my workaround.

**Comment by Gerrit0** [comment]
I'm going to have to ask for a reproduction, it seems to work correctly for me

**Comment by foulong** [comment]
```bash
$ ./node_modules/typedoc/bin/typedoc 'src/**/*.ts' --out ./doc --skipErrorChecking
[warning] NeatCsvComplement, defined in ./src/controllers/engine/_common.ts, is referenced by controllers/engine/_common.NeatCsvComplement but not included in the documentation.
[warning] ObjectCustomClass, defined in ./src/controllers/engine/_common.ts, is referenced by controllers/engine/_common.ObjectCustom but not included in the documentation.
[warning] Could not empty the output directory.
[info] Documentation generated at ./doc
```

The documentation is no longer generated in my output folder.
I see this problem because i delete content of my output foler ("doc").
And now, my output folder stays empty.
A warning talks about "[warning] Could not empty the output directory." but why ?

**Comment by Gerrit0** [comment]
I suspect permissions issues. If you manually delete the output directory, that might resolve it
