### ISSUE TITLE
new packages strategy breaks plugin

### ISSUE THREAD

**Issue by boneskull** [TypeStrong/typedoc#2236]
## Search Terms

legacy-packages
legacypackages

## Problem

I have a plugin that considers a multi-package project as a whole, basically.  It expects a couple specific packages to exist, and creates new reflections in other packages based on the reflections found in those required packages.  The new packages mode seems to run in isolation, so my plugin cannot make the connections.

I'm also receiving warnings about use of `typedoc.entryPoint` in `package.json` when run w/ `legacy-packages`, which mention it will be ignored--but I'm not aware of any alternative.  Because of this, TypeDoc complains that it cannot find entry points.  I would rather not require my users to know the specific entry point of the required package(s).

## Suggested Solution

Do not eliminate `legacy-packages` and/or support `typedoc.entryPoint` and/or suggest a workaround.

**Comment by Gerrit0** [comment]
Yes, the whole point of 0.24's packages mode is to run in isolation and then merge the project together when done, see #2197 for details on that.

Your plugin should probably be listening to [Application.EVENT_PROJECT_REVIVE](https://typedoc.org/api/classes/Application.html#EVENT_PROJECT_REVIVE). When that fires, it will be passed a ProjectReflection which contains everything.

In packages mode, TypeDoc effectively makes a completely separate run in each child package, so each of those packages should configure their `entryPoints` option as if docs were to be built for only that package. [Gerrit0/typedoc-packages-example](https://github.com/Gerrit0/typedoc-packages-example) has a setup using this.

> I'm also receiving warnings about use of `typedoc.entryPoint` in `package.json` when run w/ `legacy-packages`

That shouldn't happen... a minimal repro would be great.

**Comment by boneskull** [comment]
Thanks, I'll give this a try tomorrow and get that MCVE if it's still a problem.
