### ISSUE TITLE
Sort enums by source order

### ISSUE THREAD

**Issue by n0samu** [TypeStrong/typedoc#2237]
## Search Terms

enum, source order, sort order

## Problem

We use typedoc to generate documentation for our library's settings interface. It would be very helpful for us to have a way to sort enums in source order while still sorting interfaces alphabetically.
- [Here is our main interface](https://ruffle.rs/js-docs/master/interfaces/BaseLoadOptions.html). It makes sense to sort these options alphabetically.
- [Here is one of our related enums](https://ruffle.rs/js-docs/master/enums/LogLevel.html). We would like to sort enums like this one in source order. Log level has a logical ordering that is different from alphabetical order.

## Suggested Solution
- Specific solution: Add an `enum-source-order` sort option
- General solution: Allow separately specifying sort orders for each `kind`.

**Comment by Gerrit0** [comment]
Adding `enum-source-order` is pretty simple, and what I think I want to go for here

**Comment by n0samu** [comment]
Thanks so much for the quick resolution! 👍
