### ISSUE TITLE
Failed to find any packages in pnpm workspace

### ISSUE THREAD

**Issue by linonetwo** [TypeStrong/typedoc#2238]
## Search terms

pnpm monorepo workspace

## Expected Behavior

Generate a HTML website I guess.

## Actual Behavior

```
pnpm run build:doc

> memeloop-monorepo@ build:doc /Users/linonetwo/Desktop/repo/memeloop
> typedoc

[info] Converting project at ./
[error] Project at ./ has entryPointStrategy set to packages, but nested packages are not supported.
[info] Merging converted projects
[error] Failed to convert one or more packages, result will not be merged together.
 ELIFECYCLE  Command failed with exit code 3.
```

```
  "scripts": {
    "build:doc": "typedoc"
  },
```

## Steps to reproduce the bug

plugins/memeloop-plugin/typedoc.json

```
{
  "$schema": "https://typedoc.org/schema.json",
  "extends": ["../../typedoc.base.json"],
  "entryPoints": ["."]
}
```

typedoc.json

```
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": ["."],
  "out": "docs",
  "name": "Memeloop Docs",
  "entryPointStrategy": "packages",
  "includeVersion": true
}
```

typedoc.base.json
```
{
  "$schema": "https://typedoc.org/schema.json",
  "includeVersion": true
}
```

pnpm-workspace.yaml

```
packages:
  # core packages
  - 'packages/*'
  # plugins, each can be use as needed
  - 'plugins/*'
```

## Environment

-   Typedoc version: 0.24.1
-   TypeScript version: 5.0.4
-   Node.js version: 18
-   OS: Mac

**Comment by Gerrit0** [comment]
> plugins/memeloop-plugin/typedoc.json

This sets the entry point strategy to packages, which expects directories as entry points, but passes a TS file... so yes, that won't work. 

Packages mode expects one or more directories containing package.json to be provided as the entry points.

**Comment by linonetwo** [comment]
I don't understand, but change it to

```
{
  "extends": ["../../typedoc.json"],
  "entryPoints": ["."]
}
```

also has this error.

**Comment by linonetwo** [comment]
Where should I run the `pnpm exec typedoc`? At monorepo root or in a package like `plugins/memeloop-plugin`?

**Comment by linonetwo** [comment]
Update the issue description, I run `typedoc` in the project root, still not working.

**Comment by linonetwo** [comment]
SHould I change it to 

```
"entryPoints": ["packages/*", "plugins/*"]
```

to match pnpm-workspace.yaml

**Comment by linonetwo** [comment]
This works, I test it out. Maybe you should update the example repo.

But with new error.

**Comment by Gerrit0** [comment]
The [website](https://typedoc.org/options/input/#packages) says

> Expects all entry points to be directories to run TypeDoc within. After each entry point has been run through TypeDoc, the projects will be merged together and rendered to a single site.

I'm not sure how to make that clearer... packages mode is intended to be more of a build-orchestration mode than a directly generate docs mode. It's a convenient wrapper to let monorepos that don't need control over rebuilding some packages generate documentation for each package and then merge them together.

> Also will it faster to process plugins/memeloop-plugin/dist/index.d.ts instead of plugins/memeloop-plugin/src/index.ts ?

Generally, no, and the former won't work anyways unless you set up special tsconfig files for typedoc's use
