### ISSUE TITLE
"packages" strategy and config inheritance

### ISSUE THREAD

**Issue by mistic100** [TypeStrong/typedoc#2240]
Version 0.24.1

The documentation clearly states "Configuration specified in the root level project will not be copied to child projects."

My question is: why ? Why the input options like "excludePrivate" cannot be inherited from the root config and I have to create two separate root config files (like the demo repository). It is very confusing to have to split the common config between two files.

Thank you for your consideration/explanation.

**Comment by mistic100** [comment]
I found I can have a single root config as long as I reset `entryPointStrategy` to `resolve` in each package, so that could work.

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "extends": ["../../typedoc.json"],
  "entryPoints": [
    "src/index.ts"
  ],
  "entryPointStrategy": "resolve",
  "name": "plugin: Autorotate",
  "readme": "./.typedoc/README.md"
}
```

**Comment by Gerrit0** [comment]
I experimented with inheriting options, but unfortunately doing so meant that you could no longer run TypeDoc yourself, individually, in each package, and then merge them together with `--entryPointStrategy merge`, which made user-level debugging of configurations harder. It also made figuring out what options were set in each package more confusing.

I suspect most monorepos will use a setup similar to what you have

**Comment by mistic100** [comment]
Okay I didn't understand what was the purpose of the merge strategy.

Thank your for your answer.
