### ISSUE TITLE
V0.24.2 does not work

### ISSUE THREAD

**Issue by fabo-afpa** [TypeStrong/typedoc#2241]
## Search terms

entry points

## Expected Behavior

After an upgrade from 0.24.1 to 0.24.2 and no other change, I expect to run npx typedoc and see the magic happen.

## Actual Behavior

I've got this message: [error] Unable to find any entry points. Make sure TypeDoc can find your tsconfig.
Running with --logLevel Verbose tells me that my tsconfig.json is read.

## Steps to reproduce the bug

Just upgrade from 0.24.1 with an env where everything works and try to launch typedoc. 

## Environment

-   Typedoc version: 0.24.2
-   TypeScript version: 5.0.4
-   Node.js version: 16.18.0
-   OS: Win10 21h2

**Comment by Gerrit0** [comment]
TypeDoc's site rebuilt successfully with 0.24.2, and so did a couple other test sites, so this isn't a universal problem. Are you sure nothing changed in your config?

**Comment by hgabor** [comment]
I could also reproduce the issue, without any configuration files.
Windows 10, 64bit, node v18.16.0 (reproducible in msys2 bash and powershell too)

It's not a minimal repo (I'm teaching how to document TypeScript, NestJS projects), but it shouldn't take too long to install.

https://github.com/hgabor/ts-dokumentacio
Typedoc is ver. 0.24.1

Generate the docs with

```
$ npx typedoc --entryPointStrategy expand src
[info] Documentation generated at ./docs
```

Everything works as expected, docs are generated in the "docs" folder.

Now switch to the "latest" branch, the only difference is the typedoc version in package.json:

```
$ git checkout latest
$ npm install
$ npx typedoc --entryPointStrategy expand src
[error] Unable to find any entry points. Make sure TypeDoc can find your tsconfig
```

And after switching back to main, just to make sure

```
$ git checkout main
$ npm install
$ npx typedoc --entryPointStrategy expand src
[info] Documentation generated at ./docs
```

**Comment by Gerrit0** [comment]
Apparently I broke Windows. My Linux box is totally fine... time to figure out how to set up a windows box to test on
