### ISSUE TITLE
"Unable to find any entry points." since 0.24.2

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2243]
## Search terms

0.24.2

## Expected Behavior

Installing 0.24.2 should not break the build.

## Actual Behavior

```
PS C:\Users\micha\Git\refa> npx typedoc --treatWarningsAsErrors --logLevel 0
[debug] Reading tsconfig at ./tsconfig.json
[debug] Using TypeScript 5.0.2 from ./node_modules/typescript/lib
[error] Unable to find any entry points. Make sure TypeDoc can find your tsconfig
```

## Steps to reproduce the bug

1. Download https://github.com/RunDevelopment/refa 
    (make sure it's the latest commit: [ee63239e81494325acd3149ca2eadda74e76e6b2](https://github.com/RunDevelopment/refa/commit/ee63239e81494325acd3149ca2eadda74e76e6b2))
1. `npm ci`
1. Refa currently uses 0.24.1. Run `npx typedoc --treatWarningsAsErrors --logLevel 0` to verify that the build works.
1. `npm i -D typedoc@0.24.2`
1. Run `npx typedoc --treatWarningsAsErrors --logLevel 0` and get the above error.

## Environment

-   Typedoc version: 0.24.2
-   TypeScript version: 5.0.2
-   Node.js version: v16.11.1
-   OS: Win10

**Comment by Gerrit0** [comment]
Huh, apparently this is a Windows issue :/

**Comment by RunDevelopment** [comment]
It works with 0.24.3. Thank you for fixing it!

**Comment by tufcode** [comment]
Had the same issue, spent hours trying to figure out what was wrong with my config - updating to 0.24.4 fixed it.

**Comment by aszx-fyh** [comment]
I work with 0.24.4 ,had the same issue.
`npx typedoc src/index.ts --logLevel 1`

[warning] No tsconfig file found, this will prevent TypeDoc from finding your entry points.
[debug] Using TypeScript 5.0.4 from ./node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib
[debug] tsconfig appears to be a solution style tsconfig - creating programs for references
[warning] The entry point ./src/index.ts does not exist or is not included in the program for your provided tsconfig.
[error] Unable to find any entry points. Make sure TypeDoc can find your tsconfig

**Comment by aszx-fyh** [comment]
@RunDevelopment 
[Here is demo](https://github.com/aszx-fyh/typedoc.git).
When I added an empty tsconfig.json in the root directory, it worked.Do i have to  have a tsconfig.json?
os: win10
node: v19.8.1

**Comment by RunDevelopment** [comment]
> Do i have to have a tsconfig.json?

Yes, I would assume so. The TypeScript compiler has a lot of options that can change the meaning of TypeScript files (e.g. `strictNullChecks`). So typedoc can't fully know what your .ts files mean without a `tsconfig.json`.
