### ISSUE TITLE
Color contrast for parameter titles is too low in dark mode

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2244]
## Search terms

color contrast

## Expected Behavior

I expected parameter names to easily readable.

## Actual Behavior

![image](https://user-images.githubusercontent.com/20878432/232335919-83fd01cb-ef3c-4a61-b2b8-d0c6635897d1.png)

## Steps to reproduce the bug

Open any page with functions that have parameters.

## Environment

-   Typedoc version: 0.24.3
-   TypeScript version: 5.0.2
-   Node.js version: v16.11.1
-   OS: Win10

**Comment by Gerrit0** [comment]
.. Colors hurt me :(
