### ISSUE TITLE
Don't resolve types if the resolved type is intentionally not exported

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2246]
## Search Terms

type alias, resolve, not exported

## Problem

I have configured typedoc to not include non-exported types. I have a type called [`NoParent<T>`](https://github.com/RunDevelopment/refa/blob/ee63239e81494325acd3149ca2eadda74e76e6b2/src/ast/nodes.ts#L73) that is implemented using a few non-exported type. This is necessary, because these types are a pure implementation detail of `NoParent<T>` and may change. Unfortunately, typedoc resolved some `NoParent<T>` types to the non-exported types.

[Example](https://github.com/RunDevelopment/refa/blob/ee63239e81494325acd3149ca2eadda74e76e6b2/src/ast/visit.ts#L29):
```ts
export interface VisitNoParentAstHandler {
	onAlternationEnter?(node: NoParent<Alternation>): void;
	onAlternationLeave?(node: NoParent<Alternation>): void;
	onAssertionEnter?(node: NoParent<Assertion>): void;
	onAssertionLeave?(node: NoParent<Assertion>): void;
	onCharacterClassEnter?(node: NoParent<CharacterClass>): void;
	onCharacterClassLeave?(node: NoParent<CharacterClass>): void;
	onConcatenationEnter?(node: NoParent<Concatenation>): void;
	onConcatenationLeave?(node: NoParent<Concatenation>): void;
	onExpressionEnter?(node: NoParent<Expression>): void;
	onExpressionLeave?(node: NoParent<Expression>): void;
	onQuantifierEnter?(node: NoParent<Quantifier>): void;
	onQuantifierLeave?(node: NoParent<Quantifier>): void;
	onUnknownEnter?(node: NoParent<Unknown>): void;
	onUnknownLeave?(node: NoParent<Unknown>): void;
}
```

![image](https://user-images.githubusercontent.com/20878432/232336948-e963de2c-bfd4-409c-bab5-9c531d6a125a.png)

`NoParentNode` is one of my [intentionally non-exported types](https://github.com/RunDevelopment/refa/blob/ee63239e81494325acd3149ca2eadda74e76e6b2/typedoc.json#L20).

## Suggested Solution

Don't resolve (trivial) type aliases if the resolved type is intentionally non-exported.

**Comment by Gerrit0** [comment]
This is almost certainly going to be a design limitation, because what typedoc documents is the type it gets from typescript. If TS resolves the type, then typedoc doesn't know what it was originally

**Comment by RunDevelopment** [comment]
I wonder how VSCode still shows `NoParent<Alternative>`? I remember that the release notes of a TS version long ago mentioned that the TS language server got a lot smarter in how it handles type aliases. 

![image](https://user-images.githubusercontent.com/20878432/232342416-e5baed47-6d89-4933-91a0-7ba88120f19a.png)

Maybe we're lucky and there's an easy trick to get the same here too?

**Comment by Gerrit0** [comment]
TypeDoc is already using that trick unfortunately, VSCode still shows `NoParent` because it is using the type nodes rather than the actual type signature. TypeDoc uses the type for methods/properties instead of the type node to properly handle generic types without having to manually implement type parameter replacement

```ts
declare const x: VisitNoParentAstHandler
x.onAlternationEnter // <-- hover over that
```

I've considered a few times trying to always use type nodes and resolve type parameters manually, but it'd be super ugly and likely easily broken with more complicated types.

**Comment by RunDevelopment** [comment]
Argh, that's a shame. So it seems like this isn't possible right now. Well, it's not like this is a huge issue (for me). 

Should we close the issue? Maybe we could keep it open as a long-term goal, but if you don't see this happening in the foreseeable future, feel free to close this as won't fix.

**Comment by Gerrit0** [comment]
It's still a possibility, but a pretty low one at this point... I don't see spending the time to write a type parameter resolver anytime soon
