### ISSUE TITLE
Is semantic highlighting for classes, interfaces, etc. not a thing anymore?

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2247]
## Search terms

semantic highlighting

## Question

I recently opened #2227 because semantic highlighting (classes=blue, interfaces=green, types=red) didn't work on some pages. But in 0.24.3, all pages lack semantic highlighting. Everything is blue.

0.24.1
![image](https://user-images.githubusercontent.com/20878432/232338004-fbdb5c23-3c44-4ac3-9724-0a084f3be839.png)

0.24.3
![image](https://user-images.githubusercontent.com/20878432/232337968-7202a60c-aa26-4e40-9a1f-8490fedadfcf.png)

Is this intentional? If so, why was this feature removed?

**Comment by Gerrit0** [comment]
Not intentional, apparently the very last change I did to fix a circular dependency, a5eaa4c1b37aac853fc7608fb44157d23949dea7, broke it.
