### ISSUE TITLE
Are the .html extensions really necessary in URLs?

### ISSUE THREAD

**Issue by ilg-ul** [TypeStrong/typedoc#2250]
## Search terms

URL, html

## Question

I was wondering whether the use of explicit `.html` file extensions in the URLs generated by TypeDoc is of any special value, compared to the shorter folder type URLs.

For example the `Logger` class in one of my projects has the following URL:

```
https://xpack.github.io/logger-ts/classes/Logger.html
```

Personally I expected something like:

```
https://xpack.github.io/logger-ts/classes/Logger/
```

In my opinion, the second URL is generally preferred, as being easier to use as a link and (subjectively) looking nicer.

Is there any reason (that I'm missing) for using the `.html` URLs?

**Comment by RunDevelopment** [comment]
@Gerrit0 [mentioned before](https://github.com/TypeStrong/typedoc/issues/2218#issuecomment-1493167677) that they still want typedoc to support *not* using a web server. 

Right now, you just open any typedoc-generated HTML file locally (e.g. `file:///path/to/repo/docs/index.html`) and all links in it will work. But this will not work with `/Logger/`-type links, because the browser will just show this:
![image](https://user-images.githubusercontent.com/20878432/233041336-4e5e32c9-4fcd-46a8-ba1e-fd662e813499.png)

**Comment by Gerrit0** [comment]
Yep, exactly, *eventually* I want to do #2111, which will enable this, among other things, but haven't gotten around to doing it yet.

**Comment by ilg-ul** [comment]
Yeah, opening the site locally might be useful while initially working on the configuration, but all my other web projects come with a way to start a simple local browser, on a localhost port, and I never felt the need to open the site directly from the file system. I guess that it wouldn't be very difficult to add this functionality to `typedoc` too; or add a separate command for this.

It would be useful that a future version to generate sites without the .html extensions.

**Comment by Gerrit0** [comment]
Even if nobody else uses it, it's extremely useful to me, I'll frequently have several different projects/versions built locally when testing, it's nice to be able to just open up a built file rather than starting a temporary web server to check something for five minutes

**Comment by ilg-ul** [comment]
Did you add support for short URLs? Since I can't find details on how to configure it.

**Comment by ilg-ul** [comment]
Ok, I subscribed to #2111 to get updates when you address this issue.

**Comment by easyontop** [comment]
after typedoc use express to host it for * links and if it not found you can add a custom 404 page ig
