### ISSUE TITLE
Sorting by group 

### ISSUE THREAD

**Issue by mn-prp** [TypeStrong/typedoc#2251]
## Question

I am just getting started with typedoc, and I'm loving it so far. I particularly like the ability to define my own `@group` categories, but right now, I can't find a way to sort the major groups on a page. For example, `Type Aliases` are always appearing before my `Custom Group`. I tried changing the `categoryOrder` and the `sort`, but this did not seem to produce the desired results. Any guidance would be appreciated.

My goal is for my docs to look like this:

> **Custom Group** 
> `SomeType`
> **Another Custom Group**
> `AnotherType`
> **Type Aliases**
> `ThirdType`

**Comment by Gerrit0** [comment]
First time someone has asked for this, doesn't exist yet :)

**Comment by mn-prp** [comment]
Wow, thanks for such a quick turnaround on a feature request! 🎉
