### ISSUE TITLE
show default value of a function param in typedoc

### ISSUE THREAD

**Issue by vikyw89** [TypeStrong/typedoc#2253]
## Search terms

default value of a nested param, complex param

## Question
How can I show default value of a function param nested object ?

Here's my code

```jsx
/**
 * A custom hook for managing asynchronous data in an external store with synchronous state.
 *
 * @param selector - The selector for the asynchronous data.
 * @param config - Optional configuration options.
 */
export const useAsyncV = (
  selector: string,
  config: { initialState: { data: any; loading: boolean; error: boolean } } = {
    initialState: { data: null, loading: false, error: false },
  }
) => {
  // Get initial state from config
  const initialState = config.initialState;

  update(store, selector, (p: any) => {
    if (typeof p === "object") {
      if ("data" in p && "loading" in p && "error" in p) return p;
      return { ...p, ...initialState };
    }
    return initialState;
  });

  // Get the synchronous state object for the given selector
  const state = useSyncV(selector);

  // Return the synchronous state object
  return state;
};
```
![image](https://user-images.githubusercontent.com/112059651/233765358-92ce2966-f165-4da9-af3a-d14eef1ec6a3.png)

I want theresulting html to show my default param value  
```
{
    initialState: { data: null, loading: false, error: false }
}
``` 
Is there any way I can do that ?

**Comment by Gerrit0** [comment]
See https://github.com/TypeStrong/typedoc/issues/1393#issuecomment-793313396

**Comment by vikyw89** [comment]
Is there a documentation on how to use the plugin ? I'm kinda lost. I searched plugins, all i got is a config with string array as input.

**Comment by vikyw89** [comment]
![image](https://user-images.githubusercontent.com/112059651/233833438-6932efa9-bbe6-441c-b907-edb3f56efa3a.png)

I put the code inside plugin and call it, but doesn't seem to work. it outputed the same thing
