### ISSUE TITLE
Preventing typedoc from compiling root README.md

### ISSUE THREAD

**Issue by jtlapp** [TypeStrong/typedoc#2256]
## Search terms

readme, readme.md, markdown, compile, compiling

## Question

I am missing something basic. I cannot figure out how to keep typedoc from compiling my root level README.md and spitting out meaningless errors such as these:

```
./README.md:501:48 - [warning] Unmatched closing brace

501    | `parameterize<Params>(`<br/>`({ mapper, param }) =>`<br/>`new query)` | Returns a compiling query with a parameterized filter. Its argument is a factory method that returns a parameterized, compilable query. |

./README.md:527:220 - [warning] Encountered an unescaped open brace without an inline tag

527    | object | Object of fields, matching rows whose columns match the values of the object's properties. Non-array property values are compared by equality, while array properties match via `where ... in ...` expressions. `{}` matches all rows.

./README.md:527:221 - [warning] Unmatched closing brace

5
```

`--exclude` has no effect, but the docs say, "Unlike TypeScript's exclude option, it cannot be used to exclude files from compilation."

`--entryPoints` has no effect

Specifying the `./src` directory in the command line has no effect.

Why is it compiling anything in the root at all?

**Comment by Gerrit0** [comment]
It's not "compiling" it so much as parsing it, looking for `{@link}` tags to resolve. If you turn off the readme rendering with `--readme none`, typedoc wont parse it anymore.

**Comment by jtlapp** [comment]
That worked! Thank you so much!

**Comment by jtlapp** [comment]
Oops, forgot to close.
