### ISSUE TITLE
default value of function param not showing

### ISSUE THREAD

**Issue by vikyw89** [TypeStrong/typedoc#2257]
## Search terms

param default value not showing

## Question

this is continued from #2253 

I tried the solution using plugin, but didn't work

I'll try to rephrase my question again:

So I have this function:
```jsx
export const test = (param = {name:"test", number:"1"})=>{
} 
```

the right now output in html:

```jsx
Parameters
param:{name:string, number:string}=...
```
the output I want:

```jsx
Parameters
param:{name:string, number:string}={name:"test", number:"1"}
``

**Comment by vikyw89** [comment]
#1393 , similar to this case

**Comment by Gerrit0** [comment]
Ah yeah, that makes, version 0.23 (iirc) removed the `node` parameter from `EVENT_CREATE_DECLARATION`, so we have to grab it from the symbol.

```js
const { Converter, TypeScript } = require("typedoc");

exports.load = function ({ application }) {
    /** @type {Map<Reflection, string>} */
    const defaultValues = new Map();

    const printer = TypeScript.createPrinter({
        removeComments: true,
        omitTrailingSemicolon: true,
    });

    application.converter.on(
        Converter.EVENT_CREATE_DECLARATION,
        (_context, reflection) => {
            const node =
                reflection.project.getSymbolFromReflection(reflection)
                    ?.declarations?.[0];
            if (!node || !node.initializer) return;

            if (
                node.initializer.kind ===
                TypeScript.SyntaxKind.ObjectLiteralExpression
            ) {
                // Unfortunately can't just set defaultValue right here, this happens before TD sets it.
                defaultValues.set(
                    reflection,
                    printer.printNode(
                        TypeScript.EmitHint.Expression,
                        node.initializer,
                        node.getSourceFile()
                    )
                );
            }
        }
    );

    application.converter.on(Converter.EVENT_RESOLVE_BEGIN, () => {
        for (const [refl, init] of defaultValues) {
            refl.defaultValue = init;
        }
        defaultValues.clear();
    });
};

```

**Comment by vikyw89** [comment]
![image](https://user-images.githubusercontent.com/112059651/233884333-d899a09f-661b-4f0e-9426-59926f3cf893.png)
still the same, it doesn't show the default value. Instead it's showing the type twice
![image](https://user-images.githubusercontent.com/112059651/233884423-bd9e53e9-8e3f-427b-9192-16888057f9ed.png)
this is the result that i want (i edited it in browser)
![image](https://user-images.githubusercontent.com/112059651/233884560-26e2ffad-e637-4919-a17f-909b2a510fcc.png)

**Comment by Gerrit0** [comment]
I somehow missed that you were doing this for parameters, not properties/variables, sorry about that!

This doesn't do exactly what you pictured, but replaces the `...` that TypeDoc currently displays for the default value.

![image](https://user-images.githubusercontent.com/19329837/233888663-78222319-bc44-415b-a961-ec7729bc59b2.png)

```js
const { Converter, TypeScript } = require("typedoc");

exports.load = function ({ application }) {
    /** @type {Map<Reflection, string>} */
    const defaultValues = new Map();

    const printer = TypeScript.createPrinter({
        removeComments: true,
        omitTrailingSemicolon: true,
    });

    application.converter.on(
        Converter.EVENT_CREATE_DECLARATION,
        saveDefaultValues
    );
    application.converter.on(
        Converter.EVENT_CREATE_PARAMETER,
        saveDefaultValues
    );

    function saveDefaultValues(_context, reflection) {
        const node =
            reflection.project.getSymbolFromReflection(reflection)
                ?.declarations?.[0];
        if (!node || !node.initializer) return;

        if (
            node.initializer.kind ===
            TypeScript.SyntaxKind.ObjectLiteralExpression
        ) {
            // Unfortunately can't just set defaultValue right here, this happens before TD sets it.
            defaultValues.set(
                reflection,
                printer.printNode(
                    TypeScript.EmitHint.Expression,
                    node.initializer,
                    node.getSourceFile()
                )
            );
        }
    }

    application.converter.on(Converter.EVENT_RESOLVE_BEGIN, () => {
        for (const [refl, init] of defaultValues) {
            refl.defaultValue = init;
        }
        defaultValues.clear();
    });
};
```

**Comment by vikyw89** [comment]
works fine now ! thank you

**Comment by paulshryock** [comment]
I have the same issue where a function's default value is displayed as `...`.

```typescript
import { Console } from 'node:console'
import { stderr, stdout } from 'node:process'
import { Logger } from '../../Psr/Log/Logger.ts'

export class ConsoleLogger implements Logger {
    constructor(private console: Console = new Console({ stderr, stdout })) {}
}
```

<img width="387" alt="Screenshot 2023-05-16 at 7 52 00 AM" src="https://github.com/TypeStrong/typedoc/assets/7530507/024278a9-fffb-4ef7-bd57-fe5a702b04c5">

## What I've tried

I have tried using the example plugins [above](https://github.com/TypeStrong/typedoc/issues/2257#issuecomment-1519301081) and from [#1393](https://github.com/TypeStrong/typedoc/issues/1393#issuecomment-793313396). Both times, I stored the code in `./typedoc-plugin-default-values.ts` and ran like this:

```bash
./node_modules/.bin/typedoc --out dist/docs --plugin=./typedoc-plugin-default-values.ts src/index.ts
```

And I saw that the plugin was loaded:

```bash
[info] Loaded plugin /path/to/my/project/typedoc-plugin-default-value.ts
[info] Documentation generated at ./dist/docs
```

@Gerrit0, is there any chance this might be patched in a future version of TypeDoc, or is there a different plugin you would recommend in order for me to show default function parameter values that include `new` class instantiations?

**Comment by Gerrit0** [comment]
`new Console({ stderr, stdout })` isn't a `TypeScript.SyntaxKind.ObjectLiteralExpression`, which the above plugin looks for.

Tossing it into [ts-ast-viewer](https://ts-ast-viewer.com/#code/JYWwDg9gTgLgBAbzgYQgOwM4QDYFM4C+cAZlBCHAORoQAmuAXAMbpZ6UBQoksicGMelCgAafoIgBXeEVLkqNegzBkmuDBk7do8JABkIAc0O4ohEmQqUAdNYD0tuwAUMUOwcPujJqNZiaODlwADx54JmwAQw0UVhxcDx84bjwQXDR-OETTRA44fLgWTBgoSSYYaAAKFWAAN0iYfCK2RljMeLgAXjg0XAB3NpbKpAEhUXFaKRkASmnEAg4CIA), we can see that it is a `NewExpression`, you could update the if in the code above, or remove the if entirely to get all initializers, which results in:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/84aa01fe-f523-49b3-81a5-5fd9c4d863b8)

**Comment by paulshryock** [comment]
Thanks @Gerrit0! That's super helpful.
