### ISSUE TITLE
Error with spec.ts even excluding "spec.ts" files

### ISSUE THREAD

**Issue by CrisGuzmanS** [TypeStrong/typedoc#2261]
## Search terms

exclude, property does not exist, spec.ts

## Expected Behavior

i need to be able to exclude .spec.ts files

## Actual Behavior

a lot of these errors:
![image](https://user-images.githubusercontent.com/51240376/234362423-dc38bf4c-33c2-4460-9529-0fa4b5b0bf05.png)

## Steps to reproduce the bug

    1. my typedoc.json:    
![image](https://user-images.githubusercontent.com/51240376/234363324-7cadf326-b9f4-41db-a2b3-773250f2a5cc.png)

    2. i got this error:   
![image](https://user-images.githubusercontent.com/51240376/234363442-76484c76-23c0-4838-a080-989158e35143.png)

## Environment

-   Typedoc version: 0.22.18
-   TypeScript version: 4.5.5
-   Node.js version: 16.20.0
-   OS: Ubuntu/Linux 18.04

**Comment by Gerrit0** [comment]
TypeDoc's exclude option is only used for filtering entry points & exported members. It does not exclude files from compilation. If you want to do that, you'll have to use TypeScript's tsconfig exclude option.

You'll get the same errors if you run `npx tsc --noEmit`, typedoc is just faithfully reporting the same errors as TS compilation would.
