### ISSUE TITLE
Include root README in a monorepo

### ISSUE THREAD

**Issue by cprussin** [TypeStrong/typedoc#2263]
## Search terms

root, readme, monorepo, packages

## Question

Currently it looks like typedoc will disregard the root README when generating the documentation for a monorepo.  Is there any way to get typedoc to include the contents of the root README at the root of the docs site instead of disregarding it?

**Comment by Gerrit0** [comment]
That's not intentional... I thought I'd explicitly included code in the PackagePlugin to search for readme files in this case.

**Comment by cprussin** [comment]
ah @Gerrit0 this is probably something I did wrong, I rebuilt everything and updated my modules and it's showing up now... not sure what fixed things but probably I was unintentionally on an old version of typedoc....

anyhow I'll close this but will reopen if I see it behaving inconsistently.
