### ISSUE TITLE
Generate docs for README-only package

### ISSUE THREAD

**Issue by cprussin** [TypeStrong/typedoc#2264]
## Search terms

readme, packages

## Question

I have one package in my monorepo that just exports shared tsconfig.json files.  As such, that package doesn't have any entry points for typedoc to use.  However, I'd still like that package included in my documentation, with just the README rendered in the package's section of the docs (or maybe with the contents of the json files if possible).  It seems like right now, typedoc bails on any package that doesn't have entry points, but is there a way to tell typedoc to generate a README-only doc site (or include the json contents possibly)?

**Comment by Gerrit0** [comment]
Currently no on both counts. This is a pretty good argument for not bailing with no entry points though, at least for nested packages... it seems reasonable to downgrade that to a warning if entryPoints is not set, and allow it silently if it's set to an empty array.

Including json files is not something typedoc is designed to do at all. You could write a plugin to create a fake reflection type that does it, but that'd still depend on typedoc not bailing if there are no entry points.
