### ISSUE TITLE
@link parser should honour actual link text ignoring locally-resolved names

### ISSUE THREAD

**Issue by cefn** [TypeStrong/typedoc#2270]
## Search Terms

`@link` parser should allow `https://` links to appear with link text, even if words in the text match with e.g. class names in the codebase.

## Problem

In my comment-based documentation I have links like `{@link https://en.wikipedia.org/wiki/Immutable_object | Immutable Objects}`. 

Unfortunately this markdown appears like `Objects` and it links to an `Immutable` type that exists in my repo, rather than using the Wikipedia link and providing the link text `Immutable Objects` as expected. Omitting crucial words changes the fundamental meaning of sentences in the documentation.

```typescript
 * Flagging all state references as {@link Immutable} guides IDEs to treat these
 * as {@link https://en.wikipedia.org/wiki/Immutable_object | Immutable Objects}
 * to avoid programming errors.
```

![image](https://user-images.githubusercontent.com/159819/236072479-67998a15-cad2-4740-aefd-ddc23cc1b6e9.png)

## Suggested Solution

The presence of the URL should prevent further words from being interpreted as references to internal types.

**Comment by Gerrit0** [comment]
That's odd... Likely a bug.

**Comment by Gerrit0** [comment]
Are you able to share a project I can look at that reproduces this? I just added a test with https://github.com/TypeStrong/typedoc/commit/5d38df12def8e4fe94fde75fbbf31f9b7992ea1c, and it seems to work as you'd expect there.
