### ISSUE TITLE
`kindSortOrder` behavior changed from 0.24.5

### ISSUE THREAD

**Issue by inokawa** [TypeStrong/typedoc#2271]
## Search terms

groupOrder, kindSortOrder

## Question

I noticed kindSortOrder seems to be changed its behavior(not working?) from 0.24.5  so I downgraded typedoc in my repo.
https://github.com/inokawa/virtua/commit/a649be94d86728d241d96b71d968958912336402

Is there anyway to enable sort by kind as before? or should I use groupOrder or something else instead?
My `typedoc.json` is here.
```json
{
  "entryPoints": ["./src/index.ts"],
  "out": "docs",
  "name": "API",
  "plugin": ["typedoc-plugin-markdown"],
  "readme": "none",
  "sort": ["kind"],
  "kindSortOrder": ["Function", "Interface", "TypeAlias"],
  "githubPages": false,
  "entryDocument": "API.md",
  "hideBreadcrumbs": true
}
```

Thanks!

**Comment by Gerrit0** [comment]
If you want to control the ordering of groups on the page, yes `groupOrder` is the appropriate sort option. The `sort` order was always intended for sorting within groups/categories, and the fact that it affected group ordering previously was a lucky accident.

This actually made me take a second look at the implementation of categories, and I realized the sort option isn't being applied there, which is a bug that I'm somewhat surprised nobody has noticed, but not what you're running into
