### ISSUE TITLE
Documentation for JSON Output?

### ISSUE THREAD

**Issue by OfficialCRUGG** [TypeStrong/typedoc#2274]
## Search terms

JSON Output, kind Property, Documentation

## Question

Hey there, is there any Documentation for the JSON Output I can output from TypeDoc? For example, there's the `kind` property. I found out so far that 8 means Enum and 256 Interface, but where would I find a full list for example?

**Comment by Gerrit0** [comment]
It's described by the JSONOutput namespace - https://typedoc.org/api/modules/JSONOutput.html
