### ISSUE TITLE
Modules treeview links in packages mode output are not working

### ISSUE THREAD

**Issue by matteobruni** [TypeStrong/typedoc#2275]
## Search terms

packages, links, treeview

## Expected Behavior

The links in the modules treeview when in packages mode should be clickable instead of toggling the treeview section toggle. This behavior happens on Safari (macOS), using Chrome is working as expected.

## Actual Behavior

The links in the modules treeview when in packages mode are toggling the treeview section

## Steps to reproduce the bug

You can see this behavior [here](https://particles.js.org/docs/index.html)

- Click on the links in the left treeview, mainly they toggles their section instead of following the link as expected

## Environment

-   Typedoc version: 0.24.6
-   TypeScript version: 4.9.4 (`main` branch) and 5.0.4 (`v2` and `dev` branch)
-   Node.js version: 18.x
-   OS: macOS and Safari 16.4

**Comment by Gerrit0** [comment]
Ew, apparently safari doesn't follow the standard css properties for styling details elements either...
