### ISSUE TITLE
How to install plugins in my environment

### ISSUE THREAD

**Issue by Voo2** [TypeStrong/typedoc#2277]
## Question

I have a very special project structure (It's not possible to change this structure) and there I have problems to get typodoc plugins installed.

### Info

- Angular Project with NX
- I only want to document the lib modules

**Directory structure**
```
myProject
--apps
----myProject
------tsconfig.json
--libs
----ui
------common
--------typedoc.json
--------tsconfig.json
------desktop
--------typedoc.json
--------tsconfig.json
----platform
------common
--------typedoc.json
--------tsconfig.json
------access
--------typedoc.json
--------tsconfig.json
--typedoc.json
--typedoc.base.json
```

Content of **_myProject\typedoc.base.json_**
```
{
	"$schema": "https://typedoc.org/schema.json",
	"includeVersion": true
}
```

Content of **_myProject\typedoc.json_**
```
{
	"basePath": "./",
	"entryPoints": [
		"libs/platform/*",
		"libs/ui/*"
	],
	"name": "Documentation",
	"entryPointStrategy": "packages",
	"out": "./dist/typedoc",
	"plugin": [
		"typedoc-umlclass",
		"typedoc-plugin-coverage",
		"typedoc-plugin-replace-text"
	],
	"umlClassDiagram": {
		"type": "detailed",
		"location": "local",
		"format": "svg",
		"umlClassDiagramVerboseOutput": true
	},
	"replaceText": {
		"inCodeCommentText": true,
		"inCodeCommentTags": true,
		"inIncludedFiles": true,
		"replacements": [
			{
				"pattern": "King Kong",
				"flags": "gi",
				"replace": "[King Kong](https://github.com/king-kong)"
			}
		]
	}
}
```

Content of _**myProject\libs\platform\common\typedoc.json**_ (every typedoc.json in a nx-module looks the same)

```
{
	"extends": [
		"../../../typedoc.base.json"
	],
	"entryPoints": [
		"src/index.ts"
	]
}
```

### Problem Description
When I run the command `npx typedoc`, the documentation is generated successfully. However, no plug-ins are executed or implemented. I have listed 3 in the _typedoc.json_ as examples.

But the plugins are loaded, which is also displayed during execution. The config entries also seem to be pulled, because if I make a spelling mistake on purpose, this would lead directly to the termination of the generation.

```
[info] Loaded plugin typedoc-umlclass
[info] Loaded plugin typedoc-plugin-coverage
[info] Loaded plugin typedoc-plugin-replace-text
```

**Does anyone knows what the problem here is?** 

This was the only way I got typedoc working. If there is a better way, I am open to using it. I tried to do everything from the instructions, but everything else didn't work. If any info is needed, I'll be happy to provide it.

**Comment by Voo2** [comment]
I have tried "typedoc-plugin-extras" and it works. This means that all the previously mentioned plugins do not work in the way I expected. Why doesn't the plugin typedoc-plugin-replace-text replace the term "King Kong" that I wrote in a description of a class or why the plugin typedoc-plugin-coverage doesn't show any coverage?

**Comment by Voo2** [comment]
I have solved the problem and it was so clear in retrospect. Each NX module is considered separately and its tsconfig.json is used. I had only written the settings in the root tsconfig.json, which was wrong. I have to make the settings in tsconfig.base.json, then everything works.

Thanks for your help.

**Comment by Gerrit0** [comment]
Glad you found an answer! I'd expect the coverage plugin at least to work with configuration in the root config (it's a bug if it does not), the other plugins I don't maintain, but I suspect they ought to be able to work with configuration in the root config as well, and likely need an update to also listen to `Application.EVENT_REVIVE`
