### ISSUE TITLE
Inherited docs not overwritten

### ISSUE THREAD

**Issue by fb55** [TypeStrong/typedoc#2280]
## Search terms

inheritance, derived

## Expected Behavior

Exports should be able to override the docs of the type.

## Actual Behavior

See https://cheerio.js.org/docs/api/classes/Cheerio#next. The "defined in" references the type (https://github.com/cheeriojs/cheerio/blob/d57ba57/src/api/traversing.ts#L120), not the export (https://github.com/cheeriojs/cheerio/blob/d57ba57/src/api/traversing.ts#L365-L380). The export contains the actual docs for the type, which are now no longer shown on the website.

This is likely a regression from a recent release, as I do remember docs being as expected here.

## Steps to reproduce the bug

Let me know if the links above suffice — I can create an example project if needed.

## Environment

-   Typedoc version: 0.24.7
-   TypeScript version: 5.0.4
-   Node.js version: 20
-   OS: linux

**Comment by Gerrit0** [comment]
I suspect this is going to be because the defined in link relies on the *signature* declaration, not the variable declaration... in general the signature is the one you want so that overloads work properly.

I'm not seeing a good way to decide when to throw away the signature declaration off the top of my head... maybe if the function declarations don't match any of the signature declarations...

**Comment by Gerrit0** [comment]
I'm not entirely sure when this was fixed, but it appears to work properly on master today... I copied stuff into a single file to make it easy for me to run it:

```ts
type Cheerio<T> = any;
type AnyNode = any;
type AcceptedFilters<T> = any;

declare const filterArray: any;
declare const nextElementSibling: any;

/**
 * Creates a matcher, using a particular mapping function. Matchers provide a
 * function that finds elements using a generating function, supporting
 * filtering.
 *
 * @private
 * @param matchMap - Mapping function.
 * @returns - Function for wrapping generating functions.
 */
function _getMatcher<P>(matchMap: (fn: (elem: AnyNode) => P, elems: Cheerio<AnyNode>) => Element[]) {
    return function (fn: (elem: AnyNode) => P, ...postFns: ((elems: Element[]) => Element[])[]) {
        return function <T extends AnyNode>(this: Cheerio<T>, selector?: AcceptedFilters<Element>): Cheerio<Element> {
            let matched: Element[] = matchMap(fn, this);

            if (selector) {
                matched = filterArray(matched, selector, this.options.xmlMode, this._root?.[0]);
            }

            return this._make(
                // Post processing is only necessary if there is more than one element.
                this.length > 1 && matched.length > 1 ? postFns.reduce((elems, fn) => fn(elems), matched) : matched
            );
        };
    };
}

/** Matcher that adds at most one element for each entry in the input. */
const _singleMatcher = _getMatcher((fn: (elem: AnyNode) => Element | null, elems) => {
    const ret: Element[] = [];

    for (let i = 0; i < elems.length; i++) {
        const value = fn(elems[i]);
        if (value !== null) {
            ret.push(value);
        }
    }
    return ret;
});

/**
 * Gets the next sibling of each selected element, optionally filtered by a
 * selector.
 *
 * @category Traversing
 * @example
 *
 * ```js
 * $('.apple').next().hasClass('orange');
 * //=> true
 * ```
 * @param selector - If specified filter for sibling.
 * @returns The next nodes.
 * @see {@link https://api.jquery.com/next/}
 */
export const next = _singleMatcher((elem) => nextElementSibling(elem));
```

![image](https://github.com/TypeStrong/typedoc/assets/19329837/0ddd1e3a-9ed9-49b2-bacf-1d60fe75f1c4)
