### ISSUE TITLE
Customize the order of doc comment block tag rendering

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2285]
## Search Terms

`block tags` `@remarks` `@example` `@param`

## Problem

Currently there seems to be no way to force the "parameters" block to render above the "examples" block.  This is troublesome if the `@example` block is lengthy.

## Suggested Solution

Add an option to mandate the rendering order (top-to-bottom) of the existing block tag sections.  This could be represented by a simple string array.

**Comment by Gerrit0** [comment]
This is unimplementable given TypeDoc's current reflection architecture. Comments on parameters are not contained within the comment for the signature, but on each parameter.

That said, TypeDoc really should render the comment summary, then parameters + return type, then the remaining block tags, which would make this better.

**Comment by Oblarg** [comment]
If it's possible to change the default rendering order, why is it not possible to make that rendering order depend on some literal array in the global options?

**Comment by Gerrit0** [comment]
It's possible for everything *except* parameters + returns -- unless an incredible amount of hackery is done, the parameters and returns sections aren't kept in the same collection as the block tags.

**Comment by Gerrit0** [comment]
Changelog entry:

> -   When rendering functions/methods, TypeDoc will now render the comment summary above the parameters/return type,
    and any other block tags in the order they are defined in the comment, #2285.

![image](https://github.com/TypeStrong/typedoc/assets/19329837/7c64e32d-9164-4068-88b0-8f868822a941)

**Comment by ramitheeb** [comment]
@Gerrit0 anyway we can render examples above Parameters ?

**Comment by Gerrit0** [comment]
You could do it with a custom theme. There's no builtin support.

**Comment by Oblarg** [comment]
really glad to see this make it in - thanks!

**Comment by w10036w** [comment]
hi team, currently I am facing the annoying inconsistent order of the tags & type defs (see screenshots). any ideas? 
e.g. 
![image](https://github.com/user-attachments/assets/843ca8ba-11f3-41b8-9ab8-71a3c7361182)
![image](https://github.com/user-attachments/assets/2a267518-9cd2-4bf7-9ecf-ab6d4ea03e39)
