### ISSUE TITLE
Add options for code formatting in declarations

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2286]
## Problem

Code declarations (e.g. function and type literal definitions) are currently formatted as a single line.   Sometimes, these are somewhat lengthy and readability would be improved if they were formatted across multiple lines.

## Suggested Solution

There should be an option to preserve formatting from the source or else to apply a standard formatter like `Prettier` to code declarations.

**Comment by Gerrit0** [comment]
I'm unlikely to get to this anytime soon, sounds like a lot of pain -- formatting/frontend UI work isn't much fun to me. If you want to give it a shot, the relevant code is in https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/default/partials/type.tsx

**Comment by Oblarg** [comment]
I don't think it would necessarily be a pain, but it might involve a bit of a change-of-strategy.  Instead of recursively rendering to HTML, we could instead build a code string, run `Prettier` on it, and then display it as a code block.  This loses the contextual linking, but that's reproduced in the parameters and returns blocks below so I'm not sure if that's unacceptable.

**Comment by Gerrit0** [comment]
That might be something that some custom theme decides to do, but I don't think this is something I'm ever going to get to in the default theme.
