### ISSUE TITLE
How to ignore node_modules syntax analysis?

### ISSUE THREAD

**Issue by caochenlei** [TypeStrong/typedoc#2289]
## Question

How to ignore node_modules syntax analysis?

example:
```
"sources": [
      {
	      "fileName": "node_modules/typescript/lib/lib.es2015.core.d.ts",
	      "line": 86,
	      "character": 4
      }
]
```

**Comment by Gerrit0** [comment]
If you're looking to exclude members from the generated docs, you probably want `--excludeExternals` for this. If you want to remove the source info, you want `--disableSources`. If you want to ignore compiler errors coming from node_modules, TypeScript's `skipLibCheck` option is probably what you're after.
