### ISSUE TITLE
Documentation for one interface is not generated and produces 'does not have any documentation' warning

### ISSUE THREAD

**Issue by jstritch** [TypeStrong/typedoc#2290]
## Search terms

missing documentation

## Expected Behavior

When the documentation is present, it appears in the output and does not produce a warning.

## Actual Behavior

Some of the documentation is not generated and a warning is produced.

## Steps to reproduce the bug

Configure validation
```json
{
  "validation": {
    "notDocumented": true
  }
}
```

Declare and document the interface.
```typescript
/**
* ConsoleDataHandler defines the callback signature required to
* obtain data from a command's stdout or stderr streams as it executes.
* ConsoleDataHandler callbacks are specified by {@link ApiOptions.outHandler}
* and {@link ApiOptions.errHandler}.
*
* Uncaught Errors thrown by ConsoleDataHandler functions are
* logged to console.error by easy-git-annex.
* An application may override this behavior by
* catching and handling any error in the callback.
*
* The bind function may be used to pass `this` and other parameters.
* Refer to the
* [Function.prototype.bind() documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
* for additional information.
* @category API Options
*/
export interface ConsoleDataHandler {
  /**
   * @param data The recently generated console output.
   */
  (data: string): void;
}
```

1. clone https://github.com/jstritch/easy-git-annex.git
2. npm ci
3. npm run typedoc
4. observe the warning `[warning] ConsoleDataHandler, defined in ./src/interfaces/console-data-handler.ts, does not have any documentation.`
5. observe the part before the interface is omitted from the HTML but other parts are not. See attached screen shot. Other interfaces in the project are working as expected.

![Screenshot from 2023-05-27 12-26-38](https://github.com/TypeStrong/typedoc/assets/66251356/3bde48c8-9da4-4e28-9444-71228b3e7e2a)

## Environment

-   Typedoc version: 0.24.7
-   TypeScript version: 5.0.4
-   Node.js version: v20.2.0
-   OS: Linux, macOS, and Windows

**Comment by Gerrit0** [comment]
Ah, yep... signatures are tricky. Fairly easy fix at least.
