### ISSUE TITLE
Cannot assign to read only property 'options' of object '#<Object>'. Error is thrown by custom script using Application.bootstrapWithPlugins 

### ISSUE THREAD

**Issue by gkn1234** [TypeStrong/typedoc#2292]
## Search terms

API, bootstrapWithPlugins

## Expected Behavior

My custom script using typedoc API can not work after i updated the package version to latest(0.24.7).

Followed the changelog. I changed the previous `app.bootstrap` to `app.bootstrapWithPlugins`, but the script still works improperly.

```js
// ...other functions

async function main() {
  const app = new TypeDoc.Application();

  // If you want TypeDoc to load tsconfig.json
  app.options.addReader(new TypeDoc.TSConfigReader());

  const entries = await resolveEntries();

  app.bootstrapWithPlugins({
    // typedoc options here
    entryPoints: entries,
    tsconfig: apiPath('tsconfig.json'),
    plugin: ['typedoc-plugin-markdown'],
    allReflectionsHaveOwnDocument: true,
  });

  const project = app.convert();

  if (project) {
    const outputDir = path.join(__dirname, 'dist');

    // Rendered docs
    await app.generateDocs(project, outputDir);

    // Alternatively generate JSON output
    const jsonDir = path.join(outputDir, 'documentation.json');
    await app.generateJson(project, jsonDir);

    await resolveConfig(jsonDir);
  }
}

// eslint-disable-next-line no-console
main().catch(console.error);
```

The custom script should generate markdown production successfully.

## Actual Behavior

The script throws the error with no production.
```
[info] Loaded plugin typedoc-plugin-markdown

D:\myProjects\innersource-openx-vue\node_modules\.pnpm\typedoc@0.24.7_typescript@5.0.4\node_modules\typedoc\dist\lib\utils\options\options.js:107
                this._values[declaration.name] = (0, declaration_2.getDefaultValue)(declaration);
                                               ^

TypeError: Cannot assign to read only property 'options' of object '#<Object>'
ptions.js:107:48)
    at Application.bootstrap (D:\myProjects\innersource-openx-vue\node_modules\.pnpm\typedoc@0.24.7_typescript@5.0.4\node_modules\typedoc\dist\lib\application.js:109:22)
    at Application.bootstrapWithPlugins (D:\myProjects\innersource-openx-vue\node_modules\.pnpm\typedoc@0.24.7_typescript@5.0.4\node_modules\typedoc\dist\lib\application.js:103:14)

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.
```

## Steps to reproduce the bug

Minimal reproduction: https://stackblitz.com/edit/vitejs-vite-2r4fb9?file=doc.js

Run `pnpm run doc:script` or `node doc.js`.

## Environment
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 19.25 GB / 31.78 GB
  Binaries:
    Node: 18.16.0 - D:\devAPP\nodejs\node.EXE
    Yarn: 1.22.18 - D:\devAPP\nodejs\yarn.CMD
    npm: 9.5.1 - D:\devAPP\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.19041.1566 

```json
{
  "devDependencies": {
    "typedoc": "^0.24.7",
    "typedoc-plugin-markdown": "^3.15.3",
  }
}
```

**Comment by Gerrit0** [comment]
bootstrapWithPlugins Returns a promise, if you don't await that, it's no surprise to me that things break

**Comment by gkn1234** [comment]
> bootstrapWithPlugins Returns a promise, if you don't await that, it's no surprise to me that things break

@Gerrit0  Thanks, You remind me!

Sorry. I shouldn't be in such hurry to ignore the type defination.

I think it would be better if `bootstrapWithPlugins` can be shown in [Documentation#node-module](https://typedoc.org/guides/installation/#node-module).

**Comment by QiuShuiBai** [comment]
I have also encountered this problem. Is there a solution？
