### ISSUE TITLE
Support typescript 5.1.x

### ISSUE THREAD

**Issue by skjnldsv** [TypeStrong/typedoc#2296]
https://github.com/TypeStrong/typedoc/blob/6d92e84b8a366d443294330ac02dba225ea943ee/package.json#L33

https://github.com/microsoft/TypeScript/releases/tag/v5.1.3

**Comment by jacoobes** [comment]
Hey, does this also support the new syntax with `const` generics? 
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters
Im trying to build documentation on a personal project and the compiler fails to compile my project

**Comment by Gerrit0** [comment]
That's a TS 5.0 feature - so was supported even before 0.24.8, yes TypeDoc supports it. If you're getting compiler errors about it, make sure you have the TS version installed that you think you do, if you're still having issues, please open a new issue

**Comment by jacoobes** [comment]
Thanks, I’ll try again and report

Vào Th 6, 30 thg 6, 2023 lúc 3:42 CH Gerrit Birkeland <
***@***.***> đã viết:

**Comment by jacoobes** [comment]
> That's a TS 5.0 feature - so was supported even before 0.24.8, yes TypeDoc supports it. If you're getting compiler errors about it, make sure you have the TS version installed that you think you do, if you're still having issues, please open a new issue

Hey, everything works. I had to delete node modules and package lock and regenerate. Thanks for the help!
