### ISSUE TITLE
request: add `version` to referenced package types

### ISSUE THREAD

**Issue by RealShadowNova** [TypeStrong/typedoc#2299]
## Problem

I'd like to be able to use a referenced package type to refer to their proper documentation. I can simply search the latest version of the referenced package for the type qualified name or name, but then I run into issues where maybe the type referenced was different in another version. This creates problems for end-users trying to use documentation as it could lead to confusion.

## Suggested Solution

When parsing through a referenced package, have the relevant `package.json` available and pull the version from there.

I would make a PR for this feature but have never contributed to TypeDoc and wouldn't even know where to start.

This would be a great addition and I cannot wait to add it to my package, [typedoc-json-parser](https://github.com/RealShadowNova/typedoc-json-parser) if it is made available.

**Comment by Gerrit0** [comment]
I think this is a reasonable request... I guess it probably belongs on [ReflectionSymbolId](https://typedoc.org/api/classes/Models.ReflectionSymbolId.html), which is somewhat unfortunate... TypeDoc currently really has no support for multiple versions of packages... there's a part of me that wants TypeDoc to consider this when resolving links too...



> [typedoc-json-parser](https://github.com/RealShadowNova/typedoc-json-parser)

... huh.

```ts
import { Application } from "typedoc";
import json from "./docs.json";

const app = new Application();
app.bootstrap();
const project = app.deserializer.reviveProjects("Doc", [json]);
```

**Comment by Gerrit0** [comment]
Coming back to this 6 months later, it doesn't look like there has been any interest from anyone else -- which when it comes to significantly increasing the size of the generated json, is a fairly heavy weighting for me.

This information is still available to your plugin - you have the package name, so can go get the version yourself, so I think I'm going to mark this as a wontfix.
