### ISSUE TITLE
Does it support import statements?

### ISSUE THREAD

**Issue by Dart120** [TypeStrong/typedoc#2302]
I'm having trouble with typedoc recognizing a class that has import statements above it. When I remove the import statements, typedoc is able to see the class. Is this normal behavior?

**Comment by krisztianb** [comment]
Can you link to the repo or post your TypeDoc config and code file?

**Comment by Dart120** [comment]
This is the index.ts file I wanted to document
`import wifi from 'node-wifi'
import soapRequest from 'easy-soap-request'
import dgram from 'dgram'
import fetch from 'node-fetch'
import { XMLParser, XMLBuilder } from "fast-xml-parser"
import AlphaSyncTypes from "./Types"
import { Discovery } from './Discovery'
import { ContentDirectory } from './ContentDirectory'
import fs from 'fs'

/**
 * AlphaSync is a class responsible for discovering and interacting with Sony Alpha Camera's services.
 * It utilizes UPnP (Universal Plug and Play) to discover services and communicate with them.
 */
class AlphaSync {
   // Class Properties

  private discovery: Discovery
  private contentDirectory: ContentDirectory | undefined

  private readonly builder =  new XMLBuilder();
  /**
   * Class constructor.
   *
   * @param {string} APname - The name of the Access Point.
   * @param {string} APpassword - The password of the Access Point.
   */
    constructor (private readonly APname: string, private readonly APpassword: string) {
    this.discovery = new Discovery(APname,APpassword)
    
    
  }
  /**
   * discover_avaliable_service
   */
  public async discover_avaliable_services() {
    await this.discovery.discover_avaliable_services()
    if (this.discovery.contentDirectoryDetails){
      this.contentDirectory = new ContentDirectory(this.discovery.serverIP,this.discovery.serverPort,this.discovery.contentDirectoryDetails)
      console.log(this.contentDirectory.send_browse_request({
        ObjectID:0,
        BrowseFlag: "BrowseDirectChildren",
        Filter:"*",
        StartingIndex:0,
        RequestedCount:0,
        SortCriteria:""
}))
    }
    
  }

// TODO impl this using data in chrome
  /**
   * This method fetches a single image from the Digital Imaging service.
   */
public async get_single_image(): Promise<NodeJS.ReadableStream> {
  return new Promise<NodeJS.ReadableStream>(async (resolve, reject) => {
    if (this.discovery.digitalImagingDetails !== undefined){
      const url: string = this.discovery.construct_url(this.discovery.digitalImagingDetails?.SCPDURL)
      try{
        const digitalImagingDescXML: AlphaSyncTypes.DigitalImagingDescXML = await this.discovery.requestXML(url)
        const imageSizes: AlphaSyncTypes.SingleImageSizes[] = digitalImagingDescXML.scpd.X_DigitalImagingDeviceInfo.X_CurrentContent_URL.X_CurrentContent_URL_URL
        const targetURL = imageSizes[imageSizes.length - 1]['#text']
        const image: AlphaSyncTypes.ImageResponse =  await fetch(targetURL)
        resolve(image.body)
      } catch(error){
        reject(error)
      }
    } else {
      reject(new Error("Need to discover DigitalImagingService first"))
    }
    
  })
  
  
}


}
const as = new AlphaSync('DIRECT-qCE1:ILCE-6100', 'a-password')

as.discover_avaliable_services().then(() => as.get_single_image()).catch((error: Error) => { console.log(error) })

`

**Comment by Dart120** [comment]
This is the code I wanted to document

```
import wifi from 'node-wifi'
import soapRequest from 'easy-soap-request'
import dgram from 'dgram'
import fetch from 'node-fetch'
import { XMLParser, XMLBuilder } from "fast-xml-parser"
import AlphaSyncTypes from "./Types"
import { Discovery } from './Discovery'
import { ContentDirectory } from './ContentDirectory'
import fs from 'fs'

/**
 * AlphaSync is a class responsible for discovering and interacting with Sony Alpha Camera's services.
 * It utilizes UPnP (Universal Plug and Play) to discover services and communicate with them.
 */
class AlphaSync {
   // Class Properties

  private discovery: Discovery
  private contentDirectory: ContentDirectory | undefined

  private readonly builder =  new XMLBuilder();
  /**
   * Class constructor.
   *
   * @param {string} APname - The name of the Access Point.
   * @param {string} APpassword - The password of the Access Point.
   */
    constructor (private readonly APname: string, private readonly APpassword: string) {
    this.discovery = new Discovery(APname,APpassword)
    
    
  }
  /**
   * discover_avaliable_service
   */
  public async discover_avaliable_services() {
    await this.discovery.discover_avaliable_services()
    if (this.discovery.contentDirectoryDetails){
      this.contentDirectory = new ContentDirectory(this.discovery.serverIP,this.discovery.serverPort,this.discovery.contentDirectoryDetails)
      console.log(this.contentDirectory.send_browse_request({
        ObjectID:0,
        BrowseFlag: "BrowseDirectChildren",
        Filter:"*",
        StartingIndex:0,
        RequestedCount:0,
        SortCriteria:""
}))
    }
    
  }

// TODO impl this using data in chrome
  /**
   * This method fetches a single image from the Digital Imaging service.
   */
public async get_single_image(): Promise<NodeJS.ReadableStream> {
  return new Promise<NodeJS.ReadableStream>(async (resolve, reject) => {
    if (this.discovery.digitalImagingDetails !== undefined){
      const url: string = this.discovery.construct_url(this.discovery.digitalImagingDetails?.SCPDURL)
      try{
        const digitalImagingDescXML: AlphaSyncTypes.DigitalImagingDescXML = await this.discovery.requestXML(url)
        const imageSizes: AlphaSyncTypes.SingleImageSizes[] = digitalImagingDescXML.scpd.X_DigitalImagingDeviceInfo.X_CurrentContent_URL.X_CurrentContent_URL_URL
        const targetURL = imageSizes[imageSizes.length - 1]['#text']
        const image: AlphaSyncTypes.ImageResponse =  await fetch(targetURL)
        resolve(image.body)
      } catch(error){
        reject(error)
      }
    } else {
      reject(new Error("Need to discover DigitalImagingService first"))
    }
    
  })
  
  
}


}
const as = new AlphaSync('DIRECT-qCE1:ILCE-6100', 'a-password')

as.discover_avaliable_services().then(() => as.get_single_image()).catch((error: Error) => { console.log(error) })
```

The config file 

```
{
	"source": {
	  "include": ["src"],
	  "exclude": ["src/test"]
	},
	"plugins": ["plugins/markdown"],
	"opts": {
	  "recurse": true,
	  "destination": "./docs"
	},
	"typescript": {
	  "moduleRoot": "src",
	  "includeDeclarations": false,
	  "excludeNotExported": false,
	  "excludePrivate": false,
	  "excludeProtected": false,
	  "mode": "file",
	  "tsconfig": "./tsconfig.json"
	}
  }
```

**Comment by Dart120** [comment]
When i remove the import statements typedoc recognises the code but otherwise no

**Comment by Dart120** [comment]
Fixed it, needed to mark the class as exported
