### ISSUE TITLE
Is tsconfig.json required?

### ISSUE THREAD

**Issue by jcbhmr** [TypeStrong/typedoc#2304]
## Search terms

tsconfig required

## Question

I recently had some .d.ts files that I had a bunch of documentation in. This was all generated from native Rust bindings using https://napi.rs/

Basically:

```rs
use napi_derive::napi;
 
#[napi]
/// Compute it!
fn fibonacci(n: u32) -> u32 {
  match n {
    1 | 2 => 1,
    _ => fibonacci(n - 1) + fibonacci(n - 2),
  }
}
```

```ts
// GENERATED FILE
/** Compute it! */
export function fibonacci(n: number): number;
```

And I wanted to run `typedoc --entryPoints index.d.ts` and have it _just work_. No need to have a tsconfig.json file when I'm not even using JavaScript! 😂 It's all native codegen magic.

And... I couldn't.
![image](https://github.com/TypeStrong/typedoc/assets/61068799/a2aa3416-0d8f-4e2b-8775-536e40d642ac)

Is there a way to magically say "no i don't need a tsconfig, just give me docs" ?? sort of like how i can do `tsc file.ts` and it will _just work_ even with no tsconfig.json.

**Comment by jcbhmr** [comment]
A hack for anyone else to get around this is this:

```sh
echo '{}' >tsconfig.json && typedoc --entryPoints index.d.ts; rm tsconfig.json
```

**Comment by typhonrt** [comment]
Hi @Gerrit0. Thanks for all your work on TypeDoc along with other present and past maintainers!. 

Cool, glad this was asked as I'm coming from the ESM native side of things and generating `d.ts` files from ESM source and building docs, so kind of similar angle to the OP question. However, I don't mind building a CLI around TypeDoc for this use case using the programmatic API. A potential PR on my side would be to get the programmatic API to also accept an object for the `tsconfig` option that defines the `tsconfig.json` data. 

Something like this will then be possible:
```js
// Create a new TypeDoc application instance.
const app = new Application();

await app.bootstrapWithPlugins({
   // A few other options...
   
   tsconfig: { /* TSConfig data */ }    
});
```

Is there any general known timing on when `0.25` might ship? I suppose a change like this doesn't require a major version. I'll get right on this with a PR this week though as this would be rather handy on my end. 

And general heads up.. I do have really other neat TypeDoc related things I'll get in touch about / release / drop a note in a couple of weeks. So cool stuff incoming. :D

**Comment by Gerrit0** [comment]
You can already set tsconfig options ([`app.options.setCompilerOptions`](https://typedoc.org/api/classes/Options.html#setCompilerOptions))

0.25 has no planned release date yet, I've been very busy recently, so have barely even started on what I want to include with it.

**Comment by Gerrit0** [comment]
It looks like this can probably be done via `ts.parseCommandLine([])`, if someone wants to give a PR a shot.

**Comment by typhonrt** [comment]
Yeah.. You can use `ts.parseJsonConfigFileContent()`.  In another tool of mine I parse just compilerOptions as JSON w/ `ts.convertCompilerOptionsFromJson()`. I'll definitely take a look soonish. This is more for the next tool I'd like to build, so this potential PR is in the queue.
