### ISSUE TITLE
Should tree shaking work (eg. using vite / esbuild)?

### ISSUE THREAD

**Issue by jugglingcats** [TypeStrong/typedoc#2306]
## Search terms

tree shaking
vite
esbuild

## Question

Sorry this is very long winded but I want to provide a bit of context...!

We have written a vite plugin which runs typedoc via the API on our sources. In development mode this watches for changes and emits JSON and makes it available as a vite virtual import. This allows us to do:

```
import typedoc from "typedoc:@glowbuzzer/store"
// typedoc = [... generated typedoc ...]
```

We then render navigation and detailed docs using our own React components in our doc site.

The typedoc generation runs in node, both in dev mode and when doing the build. But of course the rendering happens in the browser. We're using the typedoc types in our React components, so we have some strong typing, for example:

![image](https://github.com/TypeStrong/typedoc/assets/526349/21678cea-0d69-405d-abaf-75b427939709)

So far so good. However, recently we started making use of `ReflectionKind`, and hit #2305.

It seems whenever the browser code goes beyond using _only the type information_ from the typedoc package, it bundles the whole of typedoc and its dependencies (which includes markdown, etc, etc)...

With type usage only:
```
$ vite build
vite v4.3.9 building for production...
✓ 21 modules transformed.
dist/index.html                  0.19 kB │ gzip:  0.15 kB
dist/assets/index-faacffb5.js  141.63 kB │ gzip: 45.62 kB
✓ built in 549ms
```

With (for example) `ReflectionKind.Class`:
```
$ vite build
vite v4.3.9 building for production...
✓ 472 modules transformed.
dist/index.html                    0.19 kB │ gzip:     0.15 kB
dist/assets/index-ec07b082.js  3,746.37 kB │ gzip: 1,074.82 kB
✓ built in 7.46s
```
😨 

Running `esbuild` gives similar results.

Perhaps this is expected behaviour. I'm not an expert on tree shaking, but thought I'd ask the question. Thanks for your consideration.

**Comment by Gerrit0** [comment]
I'd not expect it to work, typedoc wasn't designed to ever work in a browser environment
