### ISSUE TITLE
Namespaces/modules spanning files

### ISSUE THREAD

**Issue by jws305** [TypeStrong/typedoc#231]
I am attempting to document my Typescript code and I am having an issue with how the globals are being exported.  I use a folder structure where namespaces are defined in a folder hierarchy. My files structure looks like this:

myProject/moduleA.ts

```
namespace myProject.moduleA {
    export class ClassA { }
}
```

myProject/moduleB.ts

```
namespace myProject.moduleB {
    export class ClassB { }
}
```

The problem that i am having is that when the documentation is generated, the two modules do not know they are both children of my project.  The breadcrumb structure is `Globals / "moduleA" / myProject / moduleA` and I can only see the code that was defined in a single file.  The way I envision the documentation would be generated is:

```
Globals
  |-- myProject (module)
      |-- moduleA (module)
            |-- ClassA (class)
      |-- moduleB (module)
            |-- ClassB (class)
```

When I am viewing the `myProject` page, I want to see all of the sub-modules, regardless of the file they are defined in.  Is this possible with Typedoc?

**Comment by TrekkerUK** [comment]
Almost two years old, but I've had the same problem for ages and just stumbled across the answer so I thought I'd add it here for reference.

You need to set the mode to 'file'.

This is either `--mode file` on the command line or adding the option `mode: 'file'` if you're using Gulp or something similar.
