### ISSUE TITLE
Exclude node_modules definitions

### ISSUE THREAD

**Issue by lcaprini** [TypeStrong/typedoc#2311]
## Search terms

react, reduxjs, rtkquery, node_modules

## Question

In my react app I'm using @reduxjs/toolkit in order to fetch the data from API using the RTK Query hooks. That hooks are exported in this way

```typescript
import appCmsSlice from './cms-slice';

export const {
  /**
   * Query hook used to fetch the app menu
   * 
   * @group Query hooks
   * @param {string} menuUrl
   * @returns {MenuModel}
   */
  useFetchMenuQuery,
} = appCmsSlice;

```

but the compiled doc ignore my `param` and use the original @reduxjs/toolkit definition:

------

app-cms - v1.0.0 / useFetchMenuQuery
**Function useFetchMenuQuery**

_useFetchMenuQuery<R>(arg: string | typeof skipToken, options?: UseQuerySubscriptionOptions & UseQueryStateOptions<QueryDefinition<string, BaseQueryFn<AxiosRequestConfig<any>, unknown, unknown, {}, {}>, never, RPMenuModel<RPMenuType>, "app-cms">, R>): UseQueryHookResult<QueryDefinition<string, BaseQueryFn<AxiosRequestConfig<any>, unknown, unknown, {}, {}>, never, RPMenuModel<RPMenuType>, "app-cms">, R>_

Query hook used to fetch the app menu

**Type Parameters**

- R extends _Record<string, any> = UseQueryStateDefaultResult<QueryDefinition<string, BaseQueryFn<AxiosRequestConfig<any>, unknown, unknown, {}, {}>, never, RPMenuModel<RPMenuType>, "app-cms">>_

**Parameters**

- arg: _string | typeof skipToken_

- Optional options: _UseQuerySubscriptionOptions & UseQueryStateOptions<QueryDefinition<string, BaseQueryFn<AxiosRequestConfig<any>, unknown, unknown, {}, {}>, never, RPMenuModel<RPMenuType>, "app-cms">, R>_

**Returns** _UseQueryHookResult<QueryDefinition<string, BaseQueryFn<AxiosRequestConfig<any>, unknown, unknown, {}, {}>, never, RPMenuModel<RPMenuType>, "app-cms">, R>_

Defined in node_modules/@reduxjs/toolkit/dist/query/react/buildHooks.d.ts:40

------

There is a way to ignore the original definitions? My config is:

```json
{
  "entryPoints": ["src/index.ts"],
  "entryPointStrategy": "expand",
  "out": "docs",
  "plugin": ["typedoc-theme-hierarchy"],
  "tsconfig": "./tsconfig.json",
  "excludeExternals": true,
  "excludePrivate": true,
  "includeVersion": true,
  "cleanOutputDir": true,
  "readme": "none",
  "theme": "hierarchy",
  "logLevel": "Error"
}
```
Thanks.

--Luca

**Comment by Gerrit0** [comment]
TypeDoc prioritizes comments on signature declarations over comments on the "top level" function to correctly handle APIs created with factory functions. A simple workaround for this, which unfortunately requires repeating the name, is:

```ts
/** Your comment */
export const useFetchMenuQuery = appCmsSlice.useFetchMenuQuery
```

This works because it introduces a new variable binding rather than a reference to the original one, so TypeDoc's support for overriding comments via module exports kicks in.
