### ISSUE TITLE
Is it possible to add badges next to top-level items?

### ISSUE THREAD

**Issue by gallak-openfin** [TypeStrong/typedoc#2313]
## Search terms

badges

## Question

I'm looking at ElectronJS docs and they have badges next to some APIs or instance members. Here is an example ([link](https://www.electronjs.org/docs/latest/api/app#event-did-become-active-macos)) of a `macOS` badge added to a specific event:

<img width="413" alt="image" src="https://github.com/TypeStrong/typedoc/assets/115574877/7d313322-75e4-4c4b-9c74-aa8b75159dfb">

Is it possible to do this through TypeDoc natively? Or would it require a new plugin?

**Comment by Gerrit0** [comment]
Not quite on the level used by that site, but it is possible for top level items, #1941 has someone using `@ios`  and `@android` tags as an example

**Comment by gallak-openfin** [comment]
Great thanks, I'll try it out. Closing the issue.
