### ISSUE TITLE
Events are showing in the same line

### ISSUE THREAD

**Issue by HarelM** [TypeStrong/typedoc#2314]
## Search terms

Same line, event

## Expected Behavior

Events should be in separate lines

## Actual Behavior

Events are written one after the other

## Steps to reproduce the bug

The following is the comment of a class:
```js
/**
 * A `FullscreenControl` control contains a button for toggling the map in and out of fullscreen mode.
 * When [requestFullscreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen) is not supported, fullscreen is handled via CSS properties.
 * The map's `cooperativeGestures` option is temporarily disabled while the map
 * is in fullscreen mode, and is restored when the map exist fullscreen mode.
 * 
 * @group Controls
 * 
 * @example
 * // Adds a full screen control to the map
 * map.addControl(new maplibregl.FullscreenControl({container: document.querySelector('body')}));
 * 
 * @see [View a fullscreen map example](https://maplibre.org/maplibre-gl-js-docs/example/fullscreen/)
 * 
 * @event fullscreenstart - Fired when fullscreen mode has started
 * @event fullscreenend - Fired when fullscreen mode has ended
 *
 */
```
See the last line:
<img width="947" alt="image" src="https://github.com/TypeStrong/typedoc/assets/3269297/86f8d699-b045-47f2-8882-ece2d7f41a95">

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.1.3
-   Node.js version: 18.15
-   OS: macos

Other notes worth mentioning, this is my first attempt with this tool, I would like to use it with my maplibre-gl-js library.
Using the above TSDocs this class lands into the events category, I couldn't find a way to force it our of there as this is not an event class but a class that can fire these events.

When surfing to the index page when there are some categories, there is a missing ">" near the leaf of the module, let me know if you would like me to open a different issue about it:
<img width="947" alt="image" src="https://github.com/TypeStrong/typedoc/assets/3269297/7ad84ad4-1e45-4817-8522-10d2e9bacf78">

The see is right next to the exmaple code, some padding would be great there, I know I can alter the css, but I would like to touch it as little as possible.

I know this is nit picking, but I wanted to share my experience before I "get used to it".
Thanks for all the hard work around this amazing tool!

**Comment by Gerrit0** [comment]
This is working as intended, because [`@event`](https://typedoc.org/tags/event/) is a **modifier** tag (by default, can be overridden with the [modifierTags](https://typedoc.org/options/comments/#modifiertags) and [blockTags](https://typedoc.org/options/comments/#blocktags) options). Modifier tags do not create new sections, but instead are used to indicate something about the current reflection.

**Comment by HarelM** [comment]
That's fair, but why not break a line between the two events? In the tsdocs comment they are separated by a new line, but in the generated site they are not...
What am I missing?

**Comment by Gerrit0** [comment]
That's how markdown works - TypeDoc uses marked for rendering, and you can see in [their demo](https://marked.js.org/demo/?text=Test%0Anewline&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) that a single newline does not result in a new line.

You could set [`markedOptions.breaks`](https://typedoc.org/options/output/#markedoptions) to `true`, which would result in the output you're after

**Comment by HarelM** [comment]
Interesting, thanks!!
If there's a good place I can ask noob questions let me know, otherwise I'll continue here... 😀

**Comment by Gerrit0** [comment]
There is a #typedoc channel in the [TS discord](https://www.typescriptlang.org/community), this works too
