### ISSUE TITLE
Automated client generation

### ISSUE THREAD

**Issue by inktrap** [TypeStrong/typedoc#2315]
## Search Terms

automated generic client generation creation

## Problem

Could we automatically generate clients based on typedoc json output from modules/methods/params?
Swagger/OpenApi [does this](https://aevitas.medium.com/how-to-automatically-generate-clients-for-your-restful-api-fa34a6b408ff) for RESTful apis.

I [wondered](https://github.com/logseq/plugins/issues/11) if this could be done in a generic way, when I checked out the logseq plugin api docs

## Suggested Solution

Yes, tools that can generate clients exist and I have seen this hand-rolled for some python projects, however I don't know how the status in the js/typescript world is and if this is something this project would be interested in. Client code could also be generated for a variety of languages. I have not found anything similar in your issues/suggestions so I guess it has not come up yet?!

**Comment by Gerrit0** [comment]
This is definitely possible, there was some project that generated a C# interop for JS using typedoc's output at some point, no idea if it's still alive as I can't even remember what it was called.

that said, it's definitely outside of the scope of what will ever be included in typedoc itself. There are already good tools for REST/GraphQL apis as you noted

**Comment by inktrap** [comment]
If/When I have some results I'll mention them here so I would keep this open if you don't mind?
