### ISSUE TITLE
Theme.getUrls type annotation is misleading

### ISSUE THREAD

**Issue by nex3** [TypeStrong/typedoc#2318]
The type annotation for `Theme.getUrls()` is:

https://github.com/TypeStrong/typedoc/blob/d4098e8631feb74f21c99bf1225fcc5e55fbc96d/src/lib/output/theme.ts#L44

and `UrlMapping` is:

https://github.com/TypeStrong/typedoc/blob/d4098e8631feb74f21c99bf1225fcc5e55fbc96d/src/lib/output/models/UrlMapping.ts#L4

This implies that a theme can return a `UrlContext` with any `model` value. However, this condition:

https://github.com/TypeStrong/typedoc/blob/d4098e8631feb74f21c99bf1225fcc5e55fbc96d/src/lib/output/renderer.ts#L303-L307

throws an error if the `model` isn't specifically a `Reflection`. It seems like either `getUrls()` should specifically return a `UrlMapping<Reflection>`, or `Theme` should be made generic over the model type.

(My use-case here is adding a generated file to my theme that isn't based on a model at all, but rather on some side-loaded data, so I'd prefer the latter, but I can work around the former.)

**Comment by Gerrit0** [comment]
Work on #247 will eventually enable that ^ for now, fixed
