### ISSUE TITLE
Type is wrong

### ISSUE THREAD

**Issue by mishengqiang** [TypeStrong/typedoc#232]
<string> is lost.

![image](https://cloud.githubusercontent.com/assets/9413032/15990671/bbb35fa6-30cc-11e6-94b1-4fc1351b290a.png)

**Comment by aciccarello** [comment]
The `@type` is is handled in a generic way for any unrecognized `@___` jsdoc reference. The parser must be removing things in `<__>` for some reason. Possibly it thinks it is an html tag.

**Comment by Gerrit0** [comment]
Closing in favor of #1198. This is an escaping bug... The `<string>` is rendered in the page as an HTML tag. If it was `<object>` the page would totally break as noted in the linked issue.
