### ISSUE TITLE
Generic class-scoped arrow functions lack access to class-level type reflections

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2320]
When defining generic class functions whose lower bounds depend on class-level generics, the lower bound types will resolve/expand based on the value of those generics.  For example, consider this (very lengthy) string literal union:

![image](https://github.com/TypeStrong/typedoc/assets/23393863/ddb9baba-b0b9-4804-bed0-32fb461e8889)

However, if a similar function is defined with an arrow function, the lower bound does not expand and is instead broadened to just `string`:

![image](https://github.com/TypeStrong/typedoc/assets/23393863/06e032a1-8ce8-479c-8c26-f2db5e239277)

The type constraints are identical between these two functions; they differ only in that the former is a class method and the latter is an arrow function.

It would be really nice if the rendering were consistent here.

**Comment by Gerrit0** [comment]
Please provide a code snippet that can be used to reproduce this

**Comment by Oblarg** [comment]
```typescript
export type BaseUnionMember = {
    type: string;
}

export type UnionMember =
    {
        type: "one"
    } |
    {
        type: "two"
    }

export class GenericClass<Member extends BaseUnionMember> {
    public arrow = <MemberType extends Member['type']>(member: Extract<UnionMember, { type: MemberType}>) => {

    }

    public member<MemberType extends Member['type']>(member: Extract<UnionMember, { type: MemberType}>) {

    }
}

export class ResolvedSubclass extends GenericClass<UnionMember> {

}
```
