### ISSUE TITLE
Error 'Unable to find any entry points' with a monorepo

### ISSUE THREAD

**Issue by mjordang** [TypeStrong/typedoc#2321]
## Search terms

Error:Unable to find any entry points, when trying to generate the documentation when using the solution for monorepos proposed in your README (https://github.com/Gerrit0/typedoc-packages-example).

## Expected Behavior
Generate the documentation

## Actual Behavior

It is reporting this error:  'Unable to find any entry points'. with this warning before the error: 'The entry point ./ is not included in the program for your provided tsconfig. If you wanted to include files inside this directory, set --entryPointStrategy to expand or specify a glob'

## Steps to reproduce the bug
I'm working with a monorepo and I have upgraded the typedoc version to 0.24.7  and at that moment I began to have errors to generate the docs, checking the documentation I saw that in this version was introduced the 'legacy-pacakges' as an alternative resolution mode useful for monorepos, but, I saw, as well, that will be removed in 0.25 version, so, In order to  have a solution in advance, before the new release is done, I tried  the example  with the solution proposed in the README for monorepos, https://github.com/Gerrit0/typedoc-packages-example.
I created at project level the files tsconfig.base.json, tsconfig.json, typedoc.base.json and typedoc.json and in each package its own tsconfig.json and typedoc.json.
But it is not working and I am  having all the time the error : 'Unable to find any entry points.' and the warning: 'The entry point ./ is not included in the program for your provided tsconfig. If you wanted to include files inside this directory, set --entryPointStrategy to expand or specify a glob'

## Environment

-   Typedoc version:  ^0.24.7
-   TypeScript version: ^4.9.4
-   Node.js version: v18.13.0
-   OS: Mac

Could you help on this, please?, will the version 0.25 have the final solution for monorepos due that legacy-packages will be removed?.

Regards.

**Comment by Gerrit0** [comment]
The current packages mode is what I suspect will remain the final solution for monorepos. There's not enough information here for me to deduce what is happening, besides a potential suspicion that you tried to specify the entrypoints of your sub-packages with the typedoc.base.json rather than in each package. If you're able to point me towards a repo that matches your current setup, I can probably be more helpful.

**Comment by mjordang** [comment]
Hell, thanks, I can send you my tsconfig and typedoc files, content.

**Comment by mjordang** [comment]
Hello this is the structure of my project, folder: 
name
    |--folder_apps
        |-- folder_node
           |-- folder-project
              |-- src
                  |-- packages
                     |-- package1

This could be the issue?

**Comment by Gerrit0** [comment]
I don't use turbo, but it sounds like it runs typedoc in each package, while your the monrepo example (and therefore your setup) expects typedoc to be run at the root of the monorepo instead. You could use turbo to convert child packages to JSON, then use `--entryPointStrategy merge` on the generated JSON, but TypeDoc's packages mode is effectively doing that for you, so it seems like needless complication to me.
