### ISSUE TITLE
Generic parameters should be rendered in a different color than ordinary type aliases, and hyperlink to the parameter definition.

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2322]
Currently, generic parameters render in function/object documentation with the same formatting as links to type aliases (i.e. red-colored text), but are not links at all.  This can be confusing, especially in the case of a nontemplated member function of a templated class, where the parameter occurs without any obvious context to indicate that it is a generic parameter.

These should be links to the corresponding entry in the "type parameter" section (or just to the "type parameter" section itself if that's not easy/possible), and should render in a different color.

**Comment by Gerrit0** [comment]
Tricky part of doing this is the notExported warnings - requires a rework of how type parameters are handled.

need to consider how `infer X` is handled as it is, according to the compiler api, a type parameter.

**Comment by Oblarg** [comment]
My feeling is that `infer X` is a type parameter, just one whose value has been inferred based on another provided parameter, and that linking to the type parameter section would be sufficient (maybe not optimal; it'd be cool if we could have a separate "inferred" section eventually).
