### ISSUE TITLE
[warning] Could not empty the output directory.

### ISSUE THREAD

**Issue by puggan** [TypeStrong/typedoc#2323]
get the warning '[warning] Could not empty the output directory.'
unless the user running it have write-permission in the parent folder.

## Expected Behavior

typedoc should only need write-permission in the output directory.

## Actual Behavior

get warning unless i also give it write permission to the parent directory

## Steps to reproduce the bug

* sudo chown userA: build
* sudo chown userB: build/doc
* sudo -u userB npx typedoc --out build/doc

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 4.9.5
-   Node.js version: 16.20.0
-   OS: Ubuntu 23.04 lunar

**Comment by Gerrit0** [comment]
Typedoc does this by removing the output directory and recreating it, which is a single call to fs.rm.... I don't love the idea of having to manually loop over the directory to clean it up.
