### ISSUE TITLE
structurize library items in the left menu

### ISSUE THREAD

**Issue by FreePhoenix888** [TypeStrong/typedoc#2324]
## Search Terms
structurize symbols

## Problem
We have structurized view of library's exports on the main page
![image](https://github.com/TypeStrong/typedoc/assets/66206278/293c68fa-5512-4760-9db2-59c1b76e4b8a)
But do not have on the left menu
![image](https://github.com/TypeStrong/typedoc/assets/66206278/51d03a40-60f3-4778-a3cd-729e348635ab)
It would be more easier to navigate when items in left menu will be structurized too. If can be useful where library has a lot of exports

## Suggested Solution
Add this feature :) It will be nice if this feature will be switchable/customizable. Small libraries do not need it :)

**Comment by Gerrit0** [comment]
You can already do this by setting --navigation.includeGroups and/or --navigation.includeCategories

**Comment by Oblarg** [comment]
Could these sections be made collapsible on the pages themselves?  There's occasionally a lot of scrolling, and the navbar entries with the above options (blessedly) allows collapsing the sidebar categories.

**Comment by Gerrit0** [comment]
PR welcome

**Comment by FreePhoenix888** [comment]
> navigation

Where can I find this in documentation ? :) https://typedoc.org/guides/overview/

**Comment by Gerrit0** [comment]
https://typedoc.org/options/output/#navigation

**Comment by FreePhoenix888** [comment]
> https://typedoc.org/options/output/#navigation

Thank you very much! ❤️
