### ISSUE TITLE
How can I handle different versions in my documentation?

### ISSUE THREAD

**Issue by roggervalf** [TypeStrong/typedoc#2325]
## Search terms

Versioning

## Question

How can I add a side bar to point to different versions in my documentation? Is there any recommended way to do it or something similar?

**Comment by Gerrit0** [comment]
TypeDoc doesn't have anything built in to do this, though with 0.24's support for generating docs from the JSON output, you could generate JSON output for multiple versions, and render docs with both JSON files included

**Comment by roggervalf** [comment]
Thank you @Gerrit0 looks like this is what I was looking for, also for someone else interested on this, you have to use `--entryPointStrategy merge ./first.json ./second.json` in order to generate your documentation with more than one json file
