### ISSUE TITLE
Duplicate declarations in class hierarchy

### ISSUE THREAD

**Issue by JaylyDev** [TypeStrong/typedoc#2327]
## Search terms

hierarchy duplicate

## Expected Behavior

Duplicate declarations should not appear in hierarchy.

## Actual Behavior

![image](https://github.com/TypeStrong/typedoc/assets/65847850/e894232c-8de3-4c56-a54f-28e9826c02c2)

Duplicate declarations in class hierarchy appears when using entryPointStragetry "packages".

## Steps to reproduce the bug

This occurs in my repo [scriptapi-docs](https://github.com/JaylyDev/scriptapi-docs), but I attached [hierarchy-dupe.zip](https://github.com/TypeStrong/typedoc/files/11928585/hierarchy-dupe.zip) which includes a smaller reproduction.

Extract zip and run typedoc on the root of the zip directory, not the lib folder.

## Environment

-   Typedoc version: v0.24.8
-   TypeScript version: v5.0 and v5.1
-   Node.js version: v18.16.0
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Thanks for the very simple reproduction! It made tracking that down very easy.
