### ISSUE TITLE
Possibility to not merge the results in one unique doc folder

### ISSUE THREAD

**Issue by mjordang** [TypeStrong/typedoc#2328]
## Search terms

v0.24.

## Question
Hello, regarding the change in the version 0.24 "The packages entry point strategy will now run TypeDoc in each provided package directory and then merge the results together.", until now I was using an earlier version generating the documentation in each package directly(folder docs in each of them), so, in this new version, is there any way to avoid to do the merge and have the same behaviour as before? O always will work in this way and there is not possibility to  avoid it?. Because I can see that adding in the typedoc file in each package, this line "out": "docs", still generates the docs folder in the package, as before, but it also generates the docs folder at a higher level with the merge.
Perhaps to do it the way that was done before is to use legacy package, I'm right? that will be removed in the version 0.25.
It's only to confirm, to be sure of it and be able to argue it to my manager who is asking/insisting me, why we have to do it now in this way.
Regards.

**Comment by Gerrit0** [comment]
Your use case of running typedoc in several packages to produce separate sites is not the intended use case of the tool, and is better served by the various monorepo tools (npm, yarn, nx, etc.) which include support for running a command (in this case, typedoc) in each package.

I've updated https://github.com/Gerrit0/typedoc-packages-example with a `docs-all` script that shows one way to do this with npm workspaces, it should be easily adaptable to whatever monorepo tool you are using.

**Comment by mjordang** [comment]
Thanks for the answer.
