### ISSUE TITLE
Make page sections (including groups/categories) collapsible in the main page body

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2330]
When using the `navigation` categorization settings, the added sidebar elements are collapsible, which is super convenient for scrolling through large namespaces.  The corresponding sections in the main page body are not collapsible, however, so the convenience is lost in the documentation itself.

Page sections (including markdown sections, maybe?) should be collapsible to aid navigation in large namespaces.

**Comment by Gerrit0** [comment]
I'm not likely to get to this anytime soon, would be happy to look at a PR that implemented it though

**Comment by Gerrit0** [comment]
Fixed with 0.26, which is releasing 2024/06/21
