### ISSUE TITLE
@inheritDoc fails to find cross-package reference

### ISSUE THREAD

**Issue by lorem--ipsum** [TypeStrong/typedoc#2331]
## Search terms

cross-package inheritDoc monorepo reference

## Summary

[Here's a repo](https://github.com/lorem--ipsum/typedoc-packages-example) to replicate this bug, but basically in a mono repo, using `@link` from packageB to packageA works but using `@inheritDoc` yields the following warning:
```
[warning] Failed to find "@typedoc/bar!bar2" to inherit the comment from in the comment for foo2.foo2
```

Let me know if anything's unclear, and thanks for this great project :)

**Comment by Gerrit0** [comment]
I really need to get type checking for events merged in... such a small change!

**Comment by lorem--ipsum** [comment]
Thank you for the quick response :-)
