### ISSUE TITLE
Code Playgrounds

### ISSUE THREAD

**Issue by steve02081504** [TypeStrong/typedoc#2333]
## Search Terms

run code playground

## Problem

I saw mdn's docs which have some code examples where you can modify it and hit run and subsequently get the output!
![图片](https://github.com/TypeStrong/typedoc/assets/31927825/0ee8a4c8-b9f1-4ff4-98fd-bfa92aa83477)
And my project has dist that can be run in a browser, so I'd like to be able to have that in my doc as well, which is cool!

## Suggested Solution

I'm not sure how hard it would be to implement this functionality, as a user I think I'd just need to when using it:

- Provide some code to initialise global variables, e.g. importing a module
- Then provide sample code in the documentation of each class or method that the user can run, using special syntax.
- Optional code type: ts or js

**Comment by Gerrit0** [comment]
I think this is probably something I want to push to plugin space, what makes sense for examples will vary greatly by the library (some should run in the browser in-line in the page, some should probably point to a NodeJS playground like the node docs, some don't include "complete" runnable examples, so providing a run button is misleading)

**Comment by Gerrit0** [comment]
Closing this as I don't have time to work it, and it wouldn't be in typedoc itself, I think it's a good idea, but.. no time...
