### ISSUE TITLE
Typedoc does not respect the `extends` semantics of `tsconfig.json`

### ISSUE THREAD

**Issue by StevenEWright** [TypeStrong/typedoc#2334]
## Search terms

- tsconfig.json
- extends
- typedocOptions

## Expected Behavior

When looking for `typedocOptions` in `tsconfig.json` files, typedoc should respect the semantics of `tsconfig.json` by honoring the `extends` property per https://www.typescriptlang.org/tsconfig/extends.html

## Actual Behavior

Currently, in `src/lib/utils/tsconfig.ts`, there is no affordance for resolving the complete contents of `tsconfig.json` in the case where an `extends` property is present. 

## Steps to reproduce the bug

- Start with any project which currently works as expected with `typedoc` and specifies `typedocOptions` in a `tsconfig.json`.
- Copy the contents of the existing `tsconfig.json` to a new file (such as `tsconfig.base.json`)
- Replace the contents of the existing `tsconfig.json` with `{ 'extends': 'tsconfig.base.json' }`
- Observe that `typedoc` no longer respects the settings in the extended config.

## Environment

-   Typedoc version: `typedoc@0.24.7`
-   TypeScript version: `^5.0.0`
-   Node.js version: `16`
-   OS: `macOS`

**Comment by Ainias** [comment]
@Gerrit0 While the typedoc-options may now be working, the other tsconfig-options are not working. I have a base tsconfig with `paths`, which are not resolved if I specify the extending tsconfig. The `paths` are resolved if I specify the base tsconfig.
Should I open a new bug or should we reopen this bug?

**Comment by Gerrit0** [comment]
That's a different issue - and one that'll definitely need a reproduction, since I have test cases which shows that TypeDoc *does* inherit tsconfig options properly.

**Comment by Ainias** [comment]
You are correct. In my project I get an error, because the include is different and therefore it has no types for `.scss`-files and it cannot resolve those files. It has nothing to do with the  `paths`.
Sorry for the wrong bug.
