### ISSUE TITLE
Please provide a full CLI example usage of the "compilerOptions" option.

### ISSUE THREAD

**Issue by goldingdamien** [TypeStrong/typedoc#2337]
## Search terms

compilerOptions option CLI example.

## Question

"compilerOptions" is provided as a way, I assume, to override individual compiler options.
However, the documentation does not make it very clear, how to use it.
Does it take JSON? A path? A single property?
Please provide a full example using CLI.

Regards.

- https://typedoc.org/options/configuration/#compileroptions

**Comment by Gerrit0** [comment]
It cannot be specified on the command line, only via a config file

**Comment by goldingdamien** [comment]
Thank you.
Do you mean it is referring to using in tsconfig.json#typedocOptions.compilerOptions only, as mentioned in https://github.com/TypeStrong/typedoc/pull/1891 ?

**Comment by Gerrit0** [comment]
Either tsconfig.json, or typedoc.json, the example on the site assumes typedoc.json, but it looks like I forgot to make a comment about that, updated with https://github.com/TypeStrong/typedoc-site/commit/d3dd4065b5c17da23983ae38db15a550db910451
