### ISSUE TITLE
fullName in UrlMapping is different between monorepo and regular projects

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2338]
## Search terms

- fullName
- UrlMapping

## Steps to reproduce the bug

I have a simple plugin (I've omitted some error checking and property inspection):

```js
export function load (Application) {
  Application.renderer.on(RendererEvent.BEGIN, (event) => {
    for (const urlMapping of event.urls) {
      console.info(urlMapping.model.sources[0])
    }
  })
}
```

For a regular project I see `SourceReference`s like:

```
SourceReference {
  fileName: 'index.js',
  fullFileName: '/Users/alex/Documents/Workspaces/ipfs/aegir/test/fixtures/projects/an-esm-project/src/index.js',
  line: 17,
  character: 13,
  url: 'https://github.com/ipfs/aegir/blob/master/test/fixtures/projects/an-esm-project/src/index.js#L17'
}
```

For a monorepo project I see:

```
SourceReference {
  fileName: 'index.js',
  fullFileName: 'index.js',
  line: 6,
  character: 21,
  url: 'https://github.com/ipfs/aegir/blob/48cc141/test/fixtures/projects/a-monorepo/packages/a-workspace-project/src/index.js#L6'
}
```

## Expected Behavior

`fullFileName` should be an absolute path for monorepos and regular projects.

## Actual Behavior

`fullFileName` is only an absolute path for regular projects.

Also, the `SourceReference` url property has a branch name (`master`) for the regular project but a commit-ish (`48cc141`) for the monorepo project, I'm not sure which is correct.  Perhaps the commit-ish since the object at the end of the URL won't change over time?

## Environment

-   Typedoc version: `^0.24.8`
-   TypeScript version: `^5.1.6`
-   Node.js version: `v18.14.0`
-   OS: `Mac OS X 13.3.1`

**Comment by achingbrain** [comment]
Any ideas on this @Gerrit0? I'm having to perform all sorts of [workarounds](https://github.com/ipfs/aegir/blob/master/src/docs/type-indexer-plugin.js#L96-L129) for this.

**Comment by Gerrit0** [comment]
Relying on this property is a **bad idea**. The fact that there is a fullFileName there is an artifact of the implementation of the sources plugin, and it really shouldn't have been public to begin with. The `sources` object's existence is controlled by a user option, so I assert that any plugin behavior beyond rendering a link to the url which relies on it's existence is broken by definition.

What are you actually trying to do? There is almost certainly a better way to do it, and if there isn't, I'd much rather provide one than encourage the use of this property.

**Comment by achingbrain** [comment]
> What are you actually trying to do?

I maintain a large group of related TS repos across different GH orgs, all of which have generated documentation using typedoc.

The modules produced by these repos use the types from other repos - for example the [CID](https://multiformats.github.io/js-multiformats/classes/cid.CID.html) type from [multiformats/js-multiformats](https://github.com/multiformats/js-multiformats) is used as an argument type for the [Bitswap.want](https://ipfs.github.io/js-ipfs-bitswap/interfaces/Bitswap.html#want) method from [ipfs/js-ipfs-bitswap](https://github.com/ipfs/js-ipfs-bitswap)

What I'm trying to do is have the CID type referenced in the TypeDocs for `ipfs-bitswap` link to the TypeDocs for the relevant type exported from `multiformats`:

<img width="277" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/0fc0e03c-0787-4782-bb44-03bb6097c49e">

This way the user doesn't have to thrash around looking for docs, they can just click through and get on with things.

I use [aegir](https://github.com/ipfs/aegir) as the build tool for this, it basically just supplies tsc, typedoc etc with some shared configuration and plugins.

There are two steps to generating the cross-documentation type links:

1. The [type-indexer-plugin](https://github.com/ipfs/aegir/blob/master/src/docs/type-indexer-plugin.js)
      - This plugin creates a [typedoc-urls.json](https://unpkg.com/browse/multiformats@12.0.1/dist/typedoc-urls.json) file at a known location in the module tarball
      - `typedoc-urls.json` contains a mapping of exported type names to documentation URLs
      - This is built during every publish of (for example) `multiformats`
2. When building the docs of (for example) `ipfs-bitswap` the [unknown-symbol-resolver-plugin](https://github.com/ipfs/aegir/blob/master/src/docs/unknown-symbol-resolver-plugin.js) is used.
      - This plugin knows where to look up `typedoc-urls.json` from for a given module
      - Given a module name and a type name (e.g. "multiformats" and "CID"), it tries to resolve a documentation URL from `typedoc-urls.json` for that module & type name

The reason the full path to the file is needed is to locate the nearest `package.json` in order to know where to write the `typedoc-urls.json` file out (or not to if it was loaded from a dependency).

There are a few shortcomings, for example where a type is exported from two locations [it's not possible to differentiate between them](https://github.com/TypeStrong/typedoc/issues/2125) so you may not end up linking to the canonical source, but you will link to something.

It would be a lot simpler if the `UrlMapping` had more information about the type it is referencing - the module it was loaded from, the path on disk, the file name, the line in the source code, etc, and for unknown symbol resolvers, if the path that the symbol was loaded from within it's containing module could be supplied  - this would eliminate a lot of the guess work.

Or maybe this could just be a TypeDoc feature in the future somehow, it's remarkably useful to be able to click through to the documentation of another module.

Anyway if there's a better way to do this I'd love to simplify it all.

**Comment by Gerrit0** [comment]
From that description, I think the right solution is to track source locations yourself, TypeDoc doesn't need it, so just doesn't track it...

At rendering time, TypeDoc generally doesn't have the TS project in memory anymore, but during conversion it is available for use, so you can get this (and much more) information from the symbol associated with a reflection. To map this properly you'll need logic to save/restore IDs, since in packages mode TypeDoc serializes each project & throws away the original to avoid holding on to any TS memory. Incidentally this will also mean that these plugins will work properly if someone runs TypeDoc to produce json output, and then runs with the unknown symbol resolver plugin in a separate run.

```js
const td = require("typedoc");

const savedKinds =
    td.ReflectionKind.Interface |
    td.ReflectionKind.Function |
    td.ReflectionKind.TypeAlias |
    td.ReflectionKind.Variable |
    td.ReflectionKind.Class |
    td.ReflectionKind.Enum;

/** @param {td.Application} app */
exports.load = function (app) {
    app.converter.on(td.Converter.EVENT_RESOLVE, onResolve);

    app.serializer.addSerializer({
        priority: 0,
        supports(model) {
            return model instanceof td.ProjectReflection;
        },
        toObject(model, obj, _ser) {
            obj.reflectionSources = model.reflectionSources;
            return obj;
        },
    });

    app.deserializer.addDeserializer({
        priority: 0,
        supports(_model, obj) {
            return typeof obj.reflectionSources === "object";
        },
        fromObject(_model, obj) {
            app.deserializer.defer((project) => {
                project.reflectionSources ??= {};

                for (const [id, path] of Object.entries(obj.reflectionSources)) {
                    project.reflectionSources[app.deserializer.oldIdToNewId[id]] = path;
                }
            });
        },
    });

    app.renderer.on(td.Renderer.EVENT_BEGIN, onRenderBegin);
};

/**
 * @param {td.Context} context
 * @param {td.DeclarationReflection} decl
 */
function onResolve(context, decl) {
    if (!decl.kindOf(savedKinds)) return;
    const symbol = context.project.getSymbolFromReflection(decl);
    if (!symbol) return;

    const declarations = symbol.declarations;
    if (!declarations) return;

    context.project.reflectionSources ??= {};

    // Probably want to get the module name rather than just saving the full path here?
    // Might want to consider if you care about declaration merging across projects. There's no reason a reflection
    // can only be declared in one project.
    context.project.reflectionSources[decl.id] = declarations[0].getSourceFile().fileName;
}

/**
 * @param {td.RendererEvent} event
 */
function onRenderBegin(event) {
    for (const urlMapping of event.urls) {
        console.log(urlMapping.model.name, event.project.reflectionSources[urlMapping.model.id], urlMapping.url);
    }
}
```
