### ISSUE TITLE
Occasional SIGABRT crash

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2339]
## Search terms

- crash
- sigabrt

## Expected Behavior

Typedoc should not crash.

## Actual Behavior

Typedoc sometimes crashes.

## Steps to reproduce the bug

This happens occasionally - maybe one run in twenty on my local machine.  I realise the output isn't terribly helpful for pinpointing the crash, please let me know if there's something I can run that will provide more info.

The project this is being run in is [here](https://github.com/ipfs/aegir/tree/master/test/fixtures/projects/a-monorepo).

```
[info] Loaded plugin /Users/alex/Documents/Workspaces/ipfs/aegir/src/docs/typedoc-plugin.js
[info] Loaded plugin /Users/alex/Documents/Workspaces/ipfs/aegir/src/docs/unknown-symbol-resolver-plugin.js
[info] Loaded plugin /Users/alex/Documents/Workspaces/ipfs/aegir/src/docs/type-indexer-plugin.js
[info] Loaded plugin typedoc-plugin-mdn-links
[info] Loaded plugin typedoc-plugin-missing-exports
[info] Converting project at ./packages/a-workspace-project
[info] Converting project at ./packages/another-workspace-project
[info] Merging converted projects
Command was killed with SIGABRT (Aborted): typedoc . --entryPointStrategy packages --out .docs --hideGenerator --includeVersion --exclude **/node_modules/** --gitRevision master --plugin /Users/alex/Documents/Workspaces/ipfs/aegir/src/docs/typedoc-plugin.js --plugin /Users/alex/Documents/Workspaces/ipfs/aegir/src/docs/unknown-symbol-resolver-plugin.js --plugin /Users/alex/Documents/Workspaces/ipfs/aegir/src/docs/type-indexer-plugin.js --plugin typedoc-plugin-mdn-links --plugin typedoc-plugin-missing-exports
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
 ```

## Environment

-   Typedoc version: `^0.24.8`
-   TypeScript version: `^5.1.6`
-   Node.js version: `v18.14.0`
-   OS: `Mac OS X 13.3.1`

**Comment by Gerrit0** [comment]
I suspect one of the plugins is doing something back and keeping stuff in memory from a prior conversion rather than clearing everything out between package conversions, I thought I'd taken care of everything in typedoc-plugin-missing-exports, but maybe I missed a variable... mdn links shouldn't care, quick scan at your plugins make it look like they shouldn't care either.
