### ISSUE TITLE
How to get warnings, errors from generateDocs()?

### ISSUE THREAD

**Issue by cowwoc** [TypeStrong/typedoc#2340]
## Search terms

warnings, errors, exit code

## Question
I am using Typedoc's [node module](https://typedoc.org/guides/installation/#node-module) but I can't figure out how to retrieve any warnings, errors that are returned by the `generateDocs()` method.

**Comment by cowwoc** [comment]
For reference, I am seeing this output:

```
C:\Users\Gili\Documents\requirements.js\src\MapValidator.mts
  11:55  warning  tsdoc-reference-missing-identifier: Syntax error in declaration reference: expecting a member identifier  tsdoc/syntax

✖ 1 problem (0 errors, 1 warning)
```

but `app.logger.hasErrors()` and `app.logger.hasWarnings()` both return `false`

**Comment by cowwoc** [comment]
`app.validate(project)` sets warning and error logs as expected, so this problem seems to be specific to `generateDocs()`.

**Comment by Gerrit0** [comment]
That output is not from typedoc, I suspect it is from the TSDoc eslint plugin

**Comment by cowwoc** [comment]
Ah. Makes sense. Sorry for the false alarm.
