### ISSUE TITLE
explicitly documenting type properties no longer works in the same way that vscode typescript  LS does

### ISSUE THREAD

**Issue by acao** [TypeStrong/typedoc#2342]
the vscode typescript extension honors this approach

```ts
export type HoverOptions = {
  mode?: JSONMode;
  /**
   * Generate the text to display in the hover tooltip
   */
  getHoverTexts?: (data: FoundCursorData) => HoverTexts;
  /**
   * Generate the hover tooltip HTML
   */
  formatHover?: (data: HoverTexts) => HTMLElement;
  /**
   * Provide a custom parser for the document
   * @default {JSON.parse}
   */
  parser?: (text: string) => any;
};
```

![Screenshot from 2023-07-20 12-34-03](https://github.com/TypeStrong/typedoc/assets/1368727/cb16e090-450c-4334-9043-70cbcebbbcca)

however typedoc no longer does (it used to iirc?)

![image](https://github.com/TypeStrong/typedoc/assets/1368727/deea3879-52d1-4fef-a5b0-938c95a516fa)

I know it's not easy to support every approach to inline documentation, but shouldn't it be supported if the typescript language service supports it?

**Comment by Gerrit0** [comment]
Typedoc supports it - whatever markdown theme you are using does not. 

https://typedoc.org/api/types/ValidationOptions.html Is defined in the same way in typedoc's source code

**Comment by acao** [comment]
@Gerrit0 ahh ok! This makes sense. This is my first time using the markdown plugin. Sorry for the confusion, I will open a ticket over there.
