### ISSUE TITLE
Facing errors in new tyepdoc version

### ISSUE THREAD

**Issue by vigneshsivaji** [TypeStrong/typedoc#2343]
## Search terms

Older version of typedoc is working. But I want update it to latest. Now I have latest version of typedoc, gulp-typedoc and typescipt. Facing many errors like below:

error TS2322: Type 'Timeout' is not assignable to type 'number | boolean'.
error TS2339: Property 'msSaveBlob' does not exist on type 'Navigator'.
error TS2345: Argument of type 'DataManager & Record<"result", unknown>' is not assignable to parameter of type 'string'.
error TS2440: Import declaration conflicts with local declaration of 'ColumnModel'.
 error TS2365: Operator '>=' cannot be applied to types 'number' and 'string | number'.
error TS2532: Object is possibly 'undefined'.
error TS2300: Duplicate identifier 'Promise'.
 error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'
error TS2440: Import declaration conflicts with local declaration of 'PluginConfig'.
error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.

## Question
This is my typedoc file:

      'use strict';
      
      // Node JS global scope
      var gulp = global.gulp = global.gulp || require('gulp');
      global.config = global.config || require('../utils/common.js');
      var config = global.config.config();
      
      gulp.task('typedoc', async function (done) {
          var typedoc = require('gulp-typedoc');
          gulp.src(config.typedoc)
              .pipe(typedoc({

            // TypeScript options (see typescript docs) 
            module: 'amd',
            target: 'es5',
            moduleResolution: 'node',
            includeDeclarations: true,
            emitDecoratorMetadata: true,
            experimentalDecorators: true,

            // Output options (see typedoc docs) 
            out: './public/api',
            json: './public/api/file.json',

            // TypeDoc options (see typedoc docs) 
            name: 'Syncfusion TypeScript',
            ignoreCompilerErrors: true,
            version: true,
            theme: 'minimal',
            excludeExternals: true,
            excludeNotExported: true,
            stripInternal: true
        }))
        .on('end', function () {
            gulp.src('./readme/*.*')
                .pipe(gulp.dest('./public/api/readme'))
                .on('end', function () { done(); })
                .on('error', function (e) { done(e); });
        })
        .on('error', function (e) {
            done(e);
        });
  });

tsconfig file:

  {
    "compilerOptions": {
      "target": "es5",
      "module": "amd",
      "declaration": true,
      "removeComments": true,
      "noLib": false,
      "experimentalDecorators": true,
      "sourceMap": true,
      "pretty": true,
      "allowUnreachableCode": false,
      "allowUnusedLabels": false,
      "noImplicitAny": true,
      "noImplicitReturns": true,
      "noImplicitUseStrict": false,
      "noFallthroughCasesInSwitch": true,
      "allowJs": false,
      "forceConsistentCasingInFileNames": true,
      "moduleResolution": "node",
      "types": ["jasmine","jasmine-ajax","requirejs","chai","es6-promise"],
      "suppressImplicitAnyIndexErrors": true
    },
    "exclude": [
      "node_modules",
      "dist",
      "public",
      "coverage",
      "test-report",
      "typings/browser.d.ts",
      "typings/browser"    
    ],
    "compileOnSave": false
  }

**Comment by Gerrit0** [comment]
I do not support gulp-typedoc, are you able to reproduce without it?
