### ISSUE TITLE
Decorators support was removed, is there an alternative?

### ISSUE THREAD

**Issue by mkhodan** [TypeStrong/typedoc#2346]
## Question

We actively used decorators in type Reflection.decorators for our Angular documentation to display Inputs and Outputs. After updating typedoc I see that decorators were removed from this type and general support for them disappeared. Was there a reason for this change? Can I create a feature request to bring them back or maybe there's an alternative way to get decorators that I wasn't able to find?

**Comment by Gerrit0** [comment]
#2157 -- not planning on adding this back to TypeDoc, at least the main library. It was never used by TypeDoc's code, not really tested, and I didn't want to waste time on it with non-experimental decorators coming up, I have little enough time for this as it is.

You can add decorator information yourself with a plugin, something like this should get you started. I highly recommend https://ts-ast-viewer.com/ for figuring out what is available on the AST nodes

```bash
npx typedoc --plugin ./path/to/plugin.js --json docs.json
```

```js
const td = require("typedoc");
const ts = td.TypeScript;

/** @param {td.Application} app */
exports.load = function (app) {
    // Add decorator info to reflections
    // if you need parameters, you need app.converter.on(td.Converter.EVENT_CREATE_PARAMETER)
    app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, addDecoratorInfo);

    // Add decorator info to serialized json
    app.serializer.addSerializer({
        priority: 0,
        supports(item) {
            return item instanceof td.DeclarationReflection;
        },
        toObject(item, obj, _ser) {
            if (item.decorators) {
                obj.decorators = item.decorators;
            }
            return obj;
        },
    });
};

/**
 * @param {td.Context} context
 * @param {td.DeclarationReflection} decl
 */
function addDecoratorInfo(context, decl) {
    const symbol = context.project.getSymbolFromReflection(decl);
    if (!symbol) return;

    const declaration = symbol.valueDeclaration;
    if (!declaration) return;
    if (
        !ts.isPropertyDeclaration(declaration) &&
        !ts.isMethodDeclaration(declaration)
    ) {
        return;
    }

    const decorators = declaration.modifiers?.filter(ts.isDecorator);

    decl.decorators = decorators?.map((d) => ({
        expression: d.getText(),
    }));
}
```

**Comment by mkhodan** [comment]
Got it, thanks for details and plugin example!
