### ISSUE TITLE
typedoc getting a random README.md file as entry point document?

### ISSUE THREAD

**Issue by ololiuhqui** [TypeStrong/typedoc#2349]
## Search terms

path entrypoint entrydocument entrypointstrategy  readme.md

## Question

I've been wrapping my head around this for two days, and i don't really get what is happening here.

Whenever typedoc generates a new document, it creates a README.md file (name can be changed with the `entryDocument` option). But even though i specified a specific `entryPoints`, wheter it's a file or a folder, typedoc grabs a random README.md file that is positioned way upper in the folder structure and away from any specified entrypoint.

this is the folder structure:

[...][...][...]
├
├── 09-Data-Structures-Operators
│   ├── Coding challenge 1
│   │   ├── build
│   │   │   └── js
│   │   │       └── main.js
│   │   ├── docs
│   │   │   ├── assets
│   │   │   │   ├── highlight.css
│   │   │   │   ├── main.js
│   │   │   │   ├── search.js
│   │   │   │   └── style.css
│   │   │   ├── index.html
│   │   │   ├── modules.html
│   │   │   └── variables
│   │   │       └── a.html
│   │   ├── src
│   │   │   └── main.ts
│   │   └── tsconfig.json
[...][...][...]
└── README.md

This is my tsconfig.json

```json
{
{
  "compilerOptions": {
"target": "es2016"
"module": "commonjs"
"rootDir": "./src"
"outDir": "./build/js"
"noEmitOnError": true
"esModuleInterop": true
"forceConsistentCasingInFileNames": true
 "strict": true
"skipLibCheck": true
},

"typedocOptions": {
    "entryPoints": ["./src/main.ts"],
    "entryPointStrategy": "resolve",
    "name": "Coding challenge 1.ts"
  },

  "include": ["./src"]
}

```

The entryDocument file (README.md) i get is that README.md in the very root folder, outside of my current workspace and distant from my entryPoints, i don't really know what may be causing this behaviour.

Another weird thing is that all the content in main.ts actually get rendered into modules, it's just the entry document that's showing this weird behaviour.

**Things i tried:**
- changing the entryDocument name to something like: `"entryDocument": "Conding challenge 1.md"`
- different entry points strategies: `"entryPointStrategy": "resolve"`, `"entryPointStrategy": "expand"`
- changing the entryPoints to containing directory or to the file: `    "entryPoints": ["./src/main.ts"]`,  `"entryPoints": ["./src"]`

**Comment by Gerrit0** [comment]
This sounds like a question for the markdown plugin repo -- typedoc doesn't have an entryDocument option, and I have no idea how it works.

**Comment by ololiuhqui** [comment]
> This sounds like a question for the markdown plugin repo -- typedoc doesn't have an entryDocument option, and I have no idea how it works.

Even without the entryDocument option and without the typedoc markdown plugin active, the documentation gets rendered in HTML with exactly the same issue.

**Comment by Gerrit0** [comment]
Ah, that is working as intended. README discovery starts at the base directory of your entry points, and traverses up the tree looking for a readme. This is so that common project structures with everything in a `src` or `src/lib` folder (like typedoc) can still have their readme discovered. If you don't want typedoc to include a readme, then `--readme none` is available.
