### ISSUE TITLE
Code blocks without highlighting

### ISSUE THREAD

**Issue by honungsburk** [TypeStrong/typedoc#2351]
## Search Terms

code blocks, txt, highlighting, warning

## Problem

I want to create code blocks without highlighting and not get warning messages.

## Suggested Solution

You can create code blocks without highlighting using a language that doesn't exist.

Example

```txt
```txt
Here I can put stuff I want in a block, but it should not be highlighted.
`` `
```

(Note that I added an extra space, I didn't find a way to escape backticks)

However, this produces warnings since `txt` is not a recognized language.

Suggested solution: Add support for the `txt` extension.

**Comment by Gerrit0** [comment]
This is already supported with `text` as the language
