### ISSUE TITLE
`@interface` tag on discriminated union results in inappropriate broadening of some property types, omission of others

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2352]
Consider:

```typescript
type Foo = {
  key: 'foo'
  bar: 'bar1'
}

type Bar = {
  key: 'bar'
  bar: 'bar2'
  baz: any
}

/**
 * @interface
 */
type DiscriminatedUnion = Foo | Bar;
```

This renders as:

```typescript
{
  key: 'foo' | 'bar'
  bar: 'bar1 | 'bar2'
}
```

The type above is overly-broad with respect to the `key` and `bar` properties (their values are correlated), and omits the `baz` property entirely.

**Comment by Gerrit0** [comment]
The way `@interface` works is effectively to run your type through `{ [K in keyof T]: T[K] }` and convert that, TS interfaces don't support unions like this, and neither does `@interface`

**Comment by Oblarg** [comment]
I am aware that TS interface does not support these properties - but I think it's a bad behavior to just strip them/represent them wrongly without warning.  It'd be better to error here.
