### ISSUE TITLE
Sidebar links should not open in a new webpage

### ISSUE THREAD

**Issue by terryzfeng** [TypeStrong/typedoc#2353]
## Search terms

Sidebar

## Expected Behavior

Sidebar links should open in the same tab. Navigation links currently open in the same tab and it should be the same. 

## Actual Behavior

Sidebar links open in a new tab

## Steps to reproduce the bug

Create a sidebar link. Open the HTML link

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 4.9.3
-   Node.js version: 18.16.0
-   OS: Mac

**Comment by Gerrit0** [comment]
Seems reasonable, PR welcome
