### ISSUE TITLE
Avoid generating types from an external module using 'excludeExternals' with an exception for a particular module.

### ISSUE THREAD

**Issue by tarunsinghdev** [TypeStrong/typedoc#2354]
## Search terms
excludeExternals, externalPattern

## Question
I use `excludeExternals: true` property in my `typedoc.json` to exclude the  types resolved from the external modules. 

The above works, however I want to exclude all the external modules **except** "`@some_name`" module that resides in my `node_modules` folder, since I want `typedoc` resolve the type from that particular module.

Can you please let me know how we can achieve this?

**Comment by Gerrit0** [comment]
Assuming you're not using a pnpm or some weird-pathed package manager, you can achieve this with `"**/node_modules/!(@some_name|)/**"`

**Comment by tarunsinghdev** [comment]
Thank you, it worked!
