### ISSUE TITLE
Links created with `{@link }` are converted to lower case

### ISSUE THREAD

**Issue by posva** [TypeStrong/typedoc#2356]
## Search terms

This was reported before and I think even fixed:

- https://github.com/TypeStrong/typedoc/issues/1585
- https://github.com/TypeStrong/typedoc/commit/1056bc9fb3c9c499af056103dc58d279b4c6dbaf

## Expected Behavior

Links should preserve the case to avoid conflicts

## Actual Behavior

I think the `.toLowerCase()` was added at some point again but I couldn't really find which place needed the patch so I didn't open a PR 😓 

## Steps to reproduce the bug

Here is an example of the code creating a lower case link:

```ts
export function rtdbPlugin() {}

/**
 * @see {@link rtdbPlugin}.
 */
export const databasePlugin = rtdbPlugin
```

## Environment

-   Typedoc version: latest
-   TypeScript version: 5
-   Node.js version: 18

**Comment by Gerrit0** [comment]
This is working as expected for me, please make sure your node_modules folder is up to date.

**Comment by posva** [comment]
You are right, this was related to an markdown plugin and the need of an option `  preserveAnchorCasing: true` in such plugin
