### ISSUE TITLE
Render Github MathJax in Readme

### ISSUE THREAD

**Issue by santimirandarp** [TypeStrong/typedoc#2357]
## Search Terms

Readme, MathJax, Latex, Github

## Problem

Github renders MathJax, for example $\vec{x}\cdot\vec{x}$, from the code `$\vec{x}\cdot\vec{x}$`. 

However `README.md`s containing MathJax would display incorrectly in the Typedoc generated pages. It is displayed as text (as the code version above.)

One way is to use `typedoc --readme none ...` but this isn't a great option (i.e to ignore `readme.md` for API docs.).

----------------

Would it be possible to allow that projects displaying MathJax in the README.md would also display correctly in the typedoc-generated pages ?

**Comment by Gerrit0** [comment]
This seems like something that belongs in a plugin to me
