### ISSUE TITLE
Linking to documentation subsection from markdown

### ISSUE THREAD

**Issue by RebeccaStevens** [TypeStrong/typedoc#2361]
## Search terms

readme
markdown
link

## Question

How can I link to things in the generated docs from the markdown file that is used as the index/home page of the site?

For example, if I have a `function foo` that's documentation lives at `http://example.com/dev/functions/my_module.foo.html`, can I link to this in my markdown file with something equivalent to `{@link foo}` syntax that is used in JSDoc? Or do I have to use the full url?

**Comment by Gerrit0** [comment]
You can use exactly the same syntax, `{@link foo}` works there too. However, if what you are linking to is nested, you'll need to refer to the [declaration references](https://typedoc.org/guides/declaration-references/) documentation for how to target the appropriate reflection (mostly boils down to `{@link some.namespace.path.foo}` unless doing something special)
