### ISSUE TITLE
Grouping classes under the same index name 

### ISSUE THREAD

**Issue by HarryJSCave** [TypeStrong/typedoc#2362]
## Search terms

Grouping 
Category 

## Question
Hello,

I hope you're doing well. I'm writing to seek some assistance with an issue I encountered while using TypeDoc for generating documentation for my TypeScript project.

Issue Description:
I have been using TypeDoc to generate documentation for my project, and overall, it has been a fantastic tool. However, I'm facing a challenge with grouping and categorizing classes in the generated documentation. I've tried using the @category JSDoc tag, but it seems that the classes are not getting grouped under the specified category names.

Expected Behavior:
I expect to be able to group classes based on specified category names so that the generated documentation is well-organized and easier to navigate for users. Each class should appear under the appropriate category, as defined by the @category tag.

Current Behavior:
Currently, the classes are not being grouped under the specified category names. Instead, they seem to be placed under the same default category, making it challenging for users to find relevant classes easily.

It is possible that i using the @category tag completely wrong. I have also tried using the @group tag.

```ts
/**

@namespace DatabaseInit
@category Database
@group DatabaseInit
DatabaseInitColumn is responsible for initializing and managing the column name database.
Implements PouchDBInit interface with ColumnDBDocument as the generic type.
*/
export class DatabaseInitColumn implements PouchDBInit {
// static property instance of DatabaseInitColumn for Singleton pattern
private static instance: PouchDBInit;
private db: PouchDB.Database;

/**

The path to the database.
*/
static path: string;
/**

Creates an instance of DatabaseInitColumn.
@param {string} dbPath - The path to the database.
*/
constructor(dbPath: string) {
this.db = new PouchDB(dbPath);
PouchDB.plugin(PouchDBFind);
}
}
```
I would love some help resolving this issue :)

**Comment by Gerrit0** [comment]
You probably do not want to use both `@category` and `@group`, unless you are intentionally creating a two-level hierarchy.

If you want to mostly group reflections together by their native TS type, with some exceptions (like a special section for decorators), you should use `@group`.

If you want to group reflections together by a custom organization method regardless of their TS type, you should use `@category`, and probably set `--categorizeByGroup false` to make any application of `@category` override the default type based grouping.
