### ISSUE TITLE
@namespace creates duplicated namespace in doc

### ISSUE THREAD

**Issue by jpolo** [TypeStrong/typedoc#2364]
## Expected Behavior

Typedoc should generate one namespace entry

## Actual Behavior

Typedoc generates two entries

## Steps to reproduce the bug

```typescript
export namespace NS {
  export type T = string;
}
/**
 * @namespace
 */
export const NS = {
  property: 'blah',
};
```
=> namespace NS with only T in it
=> namespace NS with property in it

I also found a related bug
```typescript
export type NS  = { foo: string };

/**
 * @namespace
 */
export const NS = {
  property: 'blah',
};
```

=> This will create a Namespace named NS, with a foo property in it.
=> It seems @namespace is ignored

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.1.6
-   Node.js version: v18.17.1
-   OS: macOS

**Comment by Gerrit0** [comment]
Declaration merging is really annoying and full of weird edge cases...

The second example seems to be working as intended to me. TypeDoc creates a namespace + a type, as expected.

**Comment by jpolo** [comment]
> Declaration merging is really annoying and full of weird edge cases...
> 
> The second example seems to be working as intended to me. TypeDoc creates a namespace + a type, as expected.

It creates the type and the namespace but the content of the namespace is wrongly generated.

**Comment by Gerrit0** [comment]
Well, that's weird... I saw there was one property, didn't notice the name was wrong!
