### ISSUE TITLE
Warn when documenting non-existing @param

### ISSUE THREAD

**Issue by verhoevenv** [TypeStrong/typedoc#2368]
## Search Terms

warning, parameter, optional

## Problem

When a typo or mistake is made in naming a parameter, the documentation string after it will be silently dropped.

The original case I found this for was when erroneously adding a question mark to the name of an optional parameter:

```
/**
 * This is a function.
 * 
 * @param mandatory Some parameter documentation
 * @param optional? Parameter documentation missing
 */
function withOptional(mandatory: string, optional?: string) {
}
```

Next to this case it's probably also useful with typos, or after renaming a parameter and forgetting to change the documention.

`--validation.notDocumented` also doesn't produce warning for this case, but that is probably expected.

## Suggested Solution
Log a validation warning for parameters that couldn't be matched with the function signature.

If an option for this already exists in typedoc, I couldn't find it.

Linting tools can probably do this already. IntelliJ finds this and marks this as warning.

**Comment by Gerrit0** [comment]
This should happen even without any validation enabled, since it's obviously broken in this case.
