### ISSUE TITLE
How to configure `externalSymbolLinkMappings` for `@types/google-apps-script`?

### ISSUE THREAD

**Issue by sharky98** [TypeStrong/typedoc#2371]
## Search terms

gas, google apps script, @types/google-apps-script

## Question

Hello, I would like to configure `externalSymbolLinkMappings` for the [`@types/google-apps-script` ](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google-apps-script) package.

This package provides typing for Google Apps Script by using reference paths, declaring a `GoogleAppsScript` namespace with many sub-namespace that contains the interface, enum, etc. There is also some var declared that refer to specific main interface.

In my TypeScript code, I use it with the full namespace. I wanted to have links to Google Developers pages for each interface I am using. I thought of using `externalSymbolLinkMappings`, but based on my tentative, it does not seems to work. Any idea if it is possible to achieve my goal and how?

Thank you very much!

**Example code**

```typescript
export type WebAppsOutput = GoogleAppsScript.HTML.HtmlOutput | GoogleAppsScript.Content.TextOutput;
export type DoPost = (event: GoogleAppsScript.Events.DoPost) => WebAppsOutput;
```

**typedoc.json**

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "externalSymbolLinkMappings": {
    "GoogleAppsScript.HTML": {
      "HtmlOutput": "https://developers.google.com/apps-script/reference/html/html-output"
    },
    "GoogleAppsScript": {
      "HTML.HtmlOutput": "https://developers.google.com/apps-script/reference/html/html-output"
    },
    "HtmlOutput": {
      "": "https://developers.google.com/apps-script/reference/html/html-output"
    }
  }
}

```

**Comment by Gerrit0** [comment]
The keys in `externalSymbolLinkMappings` must be the package name, see https://typedoc.org/options/comments/#externalsymbollinkmappings


```jsonc
{
  "$schema": "https://typedoc.org/schema.json",
  "externalSymbolLinkMappings": {
    "@types/google-apps-script": {
      "GoogleAppsScript.HTML.HtmlOutput": "https://developers.google.com/apps-script/reference/html/html-output"
    }
  }
}

**Comment by sharky98** [comment]
Thanks, I'll try that on Monday. However the docs are not clear that it should be the package name. It is inferred from the examples. Maybe having inside the docs some kind of schema-like description would help?

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "externalSymbolLinkMappings": {
    "package-name": {
      "namespaced.symbol": "URI"
    }
  }
}
```
 And maybe add something like `externalSymbolLinkMappings: Record<string, Record<string, string>>` may help.

Regards!
