### ISSUE TITLE
"Delegate" type aliases render summary in wrong location

### ISSUE THREAD

**Issue by jonchardy** [TypeStrong/typedoc#2372]
## Search terms

Type Alias
Delegate
Handler

## Expected Behavior

The following type declaration should render with its comment just below the signature.
```ts
/**
 * The signature for a function acting as an event handler.
 */
export type EventHandler = ((e: Event) => void);
```

It should appear like this (without the `| null`, added to show expected output).

![image](https://github.com/TypeStrong/typedoc/assets/1202288/0c6f51ba-e745-438d-abd3-761fc480821e)

## Actual Behavior

Typedoc renders the description as part of the type declaration.

![image](https://github.com/TypeStrong/typedoc/assets/1202288/5433577d-c583-4f06-81bf-1129fb200c38)

## Steps to reproduce the bug

Repro here:
https://github.com/TypeStrong/typedoc-repros/pull/30

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.1.6
-   Node.js version: 18.13.0
-   OS: Windows 11

**Comment by Gerrit0** [comment]
This happens because `@param` tags in that comment should be attached to the function's parameters, so the entire comment is implicitly considered to belong to the function, which is a really unfortunate way of making that work...

**Comment by LennardF1989** [comment]
> This happens because `@param` tags in that comment should be attached to the function's parameters, so the entire comment is implicitly considered to belong to the function, which is a really unfortunate way of making that work...
So is this fixable? Is there a workaround, even if draconic?

**Comment by Gerrit0** [comment]
```ts
/**
 * The signature for a function acting as an event handler.
 */
export type EventHandler = ((e: Event) => void) & {};
```

is the same type, but is not detected as a function signature, so kinda sorta works...

This should be fixable, unfortunately signature comment handling is really convoluted, likely not a trivial change.
