### ISSUE TITLE
Understanding why exclude option never works, and entry point difficulty

### ISSUE THREAD

**Issue by viveleroi** [TypeStrong/typedoc#2376]
## Search terms

negate exclude

## Question

I am trying to understand entry points and exclusions. I assume "entry point" means an index.tsx file that is the root of our application, but we have dynamically loaded routes in a react app so a majority of the app is "linked" but even so, using that individual file produces docs output of nothing but our readme.

I tried uses a glob for entry points instead `"entryPoints": ["app/**/*.ts?(x)"],` which works, except I cannot get excludes to work despite trying a dozen different things.

I tried negating stuff in the glob in various ways, I tried adding stuff to the exclude array, yet nothing is ever excluded from the output.

For example:

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": ["app/**/*.ts?(x)"],
  "exclude": ["app/**/*(.spec|.stories).tsx"],
  "out": "docs"
}
```

The .spec.tsx and .stories.tsx files are still in the `docs` output. I've tried various glob patterns, listing them as separate array entries, etc. No changes.

Am I misunderstanding how this works?

**Comment by Gerrit0** [comment]
This doesn't work because I forgot to handle `--exclude` when adding support for globs in entry points, sorry about that!

**Comment by viveleroi** [comment]
Thanks! Please let me know if you can when this gets released.

**Comment by Gerrit0** [comment]
Should be later today, there are a couple issues I'd like to get fixed if I have time, but either way, planning on a release today
