### ISSUE TITLE
Bug: Frontmatter not removed in Markdown Readme

### ISSUE THREAD

**Issue by hrueger** [TypeStrong/typedoc#2381]
## Search terms

markdown, frontmatter, readme

## Expected Behavior

The markdown parser in typedoc (for readmes) removes any yaml frontmatter as it is just metadata and should not be displayed to the end-user.

## Actual Behavior

YAML frontmatter is converted to html and shown. Example:
```md
---
title: Vision
---

# SHIFTY - Vision

```
becomes
![grafik](https://github.com/TypeStrong/typedoc/assets/18656830/eafbe516-9e5e-4bec-a3c7-642f61c6c56e)

However, we should just see the headline and not `title: Vision`.

## Steps to reproduce the bug

1. Create a readme with YAML frontmatter (like above)
2. Build the docs
3. See the frontmatter contents in the generated docs

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.0.0
-   Node.js version: 18.17.1
-   OS: Windows & macOS

## Additional Info
Happy to fix that in a PR. Should be as simple as removing frontmatter via regex before passing it to `marked`. Maybe this should be a new config option?

**Comment by Gerrit0** [comment]
frontmatter isn't standard markdown, it is rendered by both GitHub & npm, which TypeDoc generally tries to replicate.

- https://github.com/Gerrit0/dummy
- https://www.npmjs.com/package/@gerrit0/dummy

I don't want to imply that TypeDoc supports frontmatter until (if ever) it does, which I think doing this by default would imply. A `stripYamlFrontmatter` option is probably fine...

**Comment by hrueger** [comment]
Hi @Gerrit0, thanks for the reply! I agree with that, I'll make a pr adding the `stripYamlFrontmatter` option soon.

**Comment by hrueger** [comment]
Thanks!
