### ISSUE TITLE
Duplicate tags on function parameters

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2385]
## Search terms

class, function, method, tag, optional, rest

## Expected Behavior

Function parameters have tags such as "Optional" and "Rest" that describe their function. These tags should only appear once

## Actual Behavior

The tags appear twice.

![image](https://github.com/TypeStrong/typedoc/assets/20878432/8fbe69c6-699f-4e7f-866c-c5dfc6f227e5)
![image](https://github.com/TypeStrong/typedoc/assets/20878432/61090f39-16fc-4f65-8975-19e78c00058b)
![image](https://github.com/TypeStrong/typedoc/assets/20878432/4ab46710-a990-4af1-938f-e459440d8205)

Obviously, this looks quite silly.

## Steps to reproduce the bug

This should be fairly easy to reproduce. I have a very basic typedoc setup ([`typedoc.json`](https://github.com/RunDevelopment/refa/blob/master/typedoc.json)). 

In case you need a project, use [refa](https://github.com/RunDevelopment/refa). Just install the latest typedoc version, and `npm run build:docs`, and you'll be able to reproduce the issue. The above screenshot are from `docs/interfaces/ReadonlyDFA.html#copy`, `docs/functions/transform.html`, and `docs/classes/CharSet.html#union`.

## Environment

-   Typedoc version: 0.25.0
-   TypeScript version: 5.0.1
-   Node.js version: v20.5.1
-   OS: Win 10

---

## Side note

I also noticed that function parameters with a default value do not have the "Optional" tag. Is that intentional?

![image](https://github.com/TypeStrong/typedoc/assets/20878432/e3caf118-b854-40e1-9617-d1ea7aeef383)

**Comment by Gerrit0** [comment]
Oops, introduced in https://github.com/TypeStrong/typedoc/commit/c75e011729f58ba64c43eb4af6a5d1c225fc6667
