### ISSUE TITLE
Typedoc not honoring compilerOptions: paths?

### ISSUE THREAD

**Issue by michaeltford** [TypeStrong/typedoc#2390]
I have a mono repo with a tsconfig.json that contains paths 

```
 "paths": {
      "@sheetxl/common/*": ["packages/common/src/*"],
      "@sheetxl/models/*": ["packages/models/src/*"],
}
```

With the follow typedocs.json
```
{
  "entryPoints": ["packages/*/src/index.ts"],
  "name": "SheetXL"
}
```

The docs are almost working but I would expect it to generate links that 
follow @sheetxl/common (or even just common) instead of common_src.

see
https://api.sheetxl.com/modules/common_src.html

Is there a workaround where I can redefine or alias these within typedocs?

**Comment by Gerrit0** [comment]
You're probably after the `@module` tag, which can be used to rename an entry point - https://typedoc.org/tags/module/

This is working as designed:
1. The file path is always a valid method of referring to the file.
2. Multiple paths entries may map to the same file, so typedoc would have to arbitrarily choose one in those cases.
3. Paths are terrible hacky things that don't represent how things work in any (non-bundled) runtime and should be avoided in favor of referencing projects as dependencies. Even npm today will symlink projects within node_modules if set up as a monorepo

**Comment by Gerrit0** [comment]
The case I'm describing is this:

```
 "paths": {
      "@sheetxl/common/*": ["packages/common/src/*"],
      "@sheetxl/also-common/*": ["packages/common/src/*"],
}
```

This is completely fine for paths, but means that a path within there could be "mapped" back to multiple path aliases.
