### ISSUE TITLE
how to exclude `.yarn/`?

### ISSUE THREAD

**Issue by ygnoh** [TypeStrong/typedoc#2391]
## Search terms

yarn, exclude

## Question

`typedoc` emits errors like:

```
.yarn/__virtual__/mini-css-extract-plugin-virtual-4e56ffed65/0/cache/mini-css-extract-plugin-npm-2.7.6-0014d24fe7-be6f7cefc6.zip/node_modules/mini-css-extract-plugin/types/index.d.ts:206:12 - error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

206   content: Buffer;
               ~~~~~~
```

It seems like codes in a library. I think the cause is that `.yarn` is being included. How can I exclude `.yarn/`?
I've tried `exclude: [".yarn"]`, `exclude: ["**/.yarn/**/*"]`, but it doesn't work.

**Comment by Gerrit0** [comment]
`exclude` does not filter compiler errors. If you ran `tsc` you would see the same error. You probably want to set `skipLibCheck` in your tsconfig.json

**Comment by ygnoh** [comment]
> `exclude` does not filter compiler errors. If you ran `tsc` you would see the same error. You probably want to set `skipLibCheck` in your tsconfig.json

You're right! 👍 Thank you Gerrit.
