### ISSUE TITLE
Allow custom rendering, using the existing traversal logic in the default theme?

### ISSUE THREAD

**Issue by NullVoxPopuli** [TypeStrong/typedoc#2392]
## Search Terms

react, jsx

## Problem

 I'm wanting to render typedoc JSON with live, interactively rendered code snippets from my JSDoc's comments -- this can be done an infinite number of ways, but I feel like typedoc is in a good place to handle the module/type/specifier/symbol lookup for everyone.

## Suggested Solution

Refactor out the JSX / React stuff to a "default renderer" so folks could opt to not use it at all (maybe even extracted to its own package, so if folks don't use React, they don't have to install it), and provide callback apis for rendering?

**Comment by Gerrit0** [comment]
A "callback style" renderer will likely never exist - there's no reason to maintain something like that for me as TypeDoc won't use it, and it isn't very clear how it should work in the general sense... TypeDoc does provide a general purpose [traverse](https://typedoc.org/api/classes/Models.Reflection.html#traverse) function on reflections, and a [visit](https://typedoc.org/api/classes/Models.Type.html#visit) function on types which may be helpful, however.

I have been looking recently at refactoring the theme structure in a way that would incidentally make it possible to use what I've called the `BaseTheme` to just provide a `render(x: Reflection): string` method and have the base theme take care of the directory structure creation. Not pushed anywhere yet, still working out some design issues locally

FYI: TypeDoc doesn't use React -- the JSX is just serialized to a HTML string, using [~180 lines of code](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/jsx.ts), it's not making any download appreciably larger
