### ISSUE TITLE
Ability to sort entry points

### ISSUE THREAD

**Issue by frank-weindel** [TypeStrong/typedoc#2393]
## Search Terms

entry point, sort, sorting

## Problem

I'm supplying a list of separate entry points (which map to different NPM package exports), and I'd like to make sure they appear in the generated docs in a certain order. One of the exports is the main export of the package, and I want that one at the top to emphasize that fact. The others are used in special circumstances only.

Currently the generated docs sort them in alphabetical order.

## Suggested Solution

Perhaps the order that you supply entry points in the `entryPoints` array should dictate the order they appear in the generated docs.

**Comment by Gerrit0** [comment]
Hmm... how does this play with people who specify wildcards as entry points? Glob expansion order isn't generally specified & depends on your OS. Currently, everything is sorted with the [--sort](https://typedoc.org/options/organization/#sort) option.

**Comment by frank-weindel** [comment]
Just some way to mandate/hardcode a certain order at any level of the nav would be great. If I come up with a good idea I'll post it here.

**Comment by Gerrit0** [comment]
I suppose a `--sortEntryPoints false` option meets the initial requirement. "at any level of the nav" is more complicated

**Comment by frank-weindel** [comment]
That would work!

**Comment by frank-weindel** [comment]
Thanks @Gerrit0!
