### ISSUE TITLE
How can I "collapse" / combine similar/repeated name paths to more of a foldable hierarchy?

### ISSUE THREAD

**Issue by GitMurf** [TypeStrong/typedoc#2395]
## Search Terms

hierarchy, nest, paths, repeat

## Problem

See screenshot below...

I understand there is a variety of opinion and complexities with the way the tool currently works (and that is fine) but I have been able to figure out a decent setup bringing in what I want but the root "namespace" (hierarchy level) is very repetitive and messy. I would just simply like a way to have these grouped/collapsable to a few more levels when the "path" is similar.

For example I have "main/libs/electron/*" repeated several times with their individual items within and each independently expand/collapsible. It takes up a ton of vertical space and is very hard for the eyes to scan it. Instead I would just simply like the following whenever the "path" (name) is the same, auto group/collapse with each/similar/part. For example:

```txt
Root
    main
        interfaces
            stuff...
        libs
            electron
                foo
                bar
                baz
    renderer
        stuff ...
    preload
        stuff ...
```

Here is the screenshot of how it currently shows:

![image](https://github.com/TypeStrong/typedoc/assets/64155612/e6a1af87-cce5-4308-a796-dc6676a21585)

## Suggested Solution

Sorry, my suggested solution is kind of in the problem statement above,. I tried the hierarchy theme but it was pretty sluggish and had many bugs to it. It was close-ish to the concept I am looking for but I just don't like all the other pieces it adds and the sluggishness and frankly doesn't look nearly as good as the default.

**Comment by GitMurf** [comment]
To clarify my request, the outcome/process TypeDoc takes to build and formulate the results can stay exactly as is... just when building out / rendering the HTML itself, have an option that allows you to group by "name" based on the "/" slash separators. So again, `main/libs/electron/types` would simply become `main > libs > electron > types` where each `>` represents a hierarchy/nesting/indent "level".

**Comment by Gerrit0** [comment]
I'm going to track this under #2388, which it looks like you already found, don't need a second issue for it :)

**Comment by GitMurf** [comment]
> I'm going to track this under #2388, which it looks like you already found, don't need a second issue for it :)

@Gerrit0 no problem, sounds good. I just wanted to document my specific use case and also make sure there wasn't something I was missing that would allow for this specific configuration with the navigation link nesting based off "/" slashes.
