### ISSUE TITLE
Referenced but not included in the documentation.

### ISSUE THREAD

**Issue by pinpong** [TypeStrong/typedoc#2396]
Hi,  i have the following issue and don't know how to solve it because i don't want export the Actions class.

```js

export abstract class Client {
    public readonly actions: Actions = new Actions(this);
}

export class LocalClient extends Client {}


export class BaseSystem {
  protected readonly client: Client;

  public constructor(client: Client) {
    this.client = client;
  }
}

export class Actions extends BaseSystem {}

```

`[warning] Actions, defined in ./src/systems/actions/index.ts, is referenced by LocalClient.actions but not included in the documentation.`

<img width="656" alt="Bildschirmfoto 2023-09-14 um 20 33 01" src="https://github.com/TypeStrong/typedoc/assets/1012532/eb8b4176-ba08-41ba-8291-6e458c2c8cfa">

See: https://github.com/TypeStrong/typedoc/blob/master/src/lib/validation/exports.ts#L87

This is how it looks like:

<img width="803" alt="Bildschirmfoto 2023-09-14 um 20 38 38" src="https://github.com/TypeStrong/typedoc/assets/1012532/995cee3d-29e5-425f-b249-7c29a147d415">

**Comment by Gerrit0** [comment]
You want either the intentionallyNotExported option, or typedoc-plugin-missing-exports

https://typedoc.org/options/validation/#intentionallynotexported

https://www.npmjs.com/package/typedoc-plugin-missing-exports

**Comment by pinpong** [comment]
This is what i was looking for, thx ;D
