### ISSUE TITLE
How to go to line for local source files?

### ISSUE THREAD

**Issue by crystalfp** [TypeStrong/typedoc#2398]
## Search terms
source, sourceLinkTemplate, local, disableGit

## Question
My sources lives in `./src` and the documentation is generated under `./doc/typedoc`. To link to the source files I added the option `--sourceLinkTemplate "../../../{path}` to typedoc. This works well, but obviously the source is always positioned at the beginning. Is there a way to use the `{line}` macro to position it at the correct line?
Thanks!
mario

**Comment by Gerrit0** [comment]
That's going to be up to whatever program (your browser?) is displaying that page, nothing that TypeDoc can do to control that... if you use VSCode, you might be able to use `--sourceLinkTemplate "vscode://file/../../../{path}:{line}"` per https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls

**Comment by crystalfp** [comment]
Thanks a lot @Gerrit0 ! Only a small correction. Relative paths seems are not working. Instead using 
`"vscode://file/D:/Project/{path}:{line}"` works perfectly.
