### ISSUE TITLE
Documentation coverage analysis

### ISSUE THREAD

**Issue by enanox** [TypeStrong/typedoc#240]
Hi, it would be completely awesome to include some kind of metrics or summary for documentation coverage, in a similar way as [this](https://esdoc.org/feature.html#documentation-coverage). 
I would do my best to create a pull request (but it would take me a while) with the idea if you find it useful, so please let me know!

**Comment by 0815fox** [comment]
What would be completeness for you? Every class has a comment block? Every method? You could however write a plugin which adds this feature, then every-1 can chose to use it or not.

E.g. I avoid writing documentation if the name of a method is clean (Like `getChildCount` returns the total count of childs in this instance).

**Comment by enanox** [comment]
Yes, surely it would be an opt-in, and in no way as a mandatory check.
The rule of thumb you mention is certainly the way to go with coding as a whole, even libraries for other languages such as Foundation or UIKit for Obj-C have been following this approach and it really pays off. 
However, in the context of very big applications or codebases that are spread and customized over various dev teams (think in a productization strategy), this is a necessity to avoid misuse, bad practices and such, since the former developers don't know by heart the whole codebase (and when time passes by, it's more and more difficult!) and we even could give a glimpse of how to use a class, widget, component, and so.

Hope this clearifies the intent, nonetheless, I agree with all you've said.

**Comment by justmoon** [comment]
Perhaps this should be a tslint feature, not a typedoc feature?

**Comment by enanox** [comment]
@justmoon yes, they added [here](https://github.com/palantir/tslint/pull/1644) the `completedDocs` rule to enforce the code style. Sorry for the delay on this, I'll close it.  🙏

**Comment by cjduncana** [comment]
Now that TSLint is [deprecated](https://github.com/palantir/tslint/issues/4534) and the `completed-docs` is not part of ESLint, will this project reconsider opening this issue?

**Comment by Gerrit0** [comment]
TypeDoc can do this today - apparently it slipped through the cracks and isn't documented in the website though. PR welcome to fix, or I'll be doing a review of all the options when revisiting the docs for 0.23, so should get it there. 

1. Turn on "validation.notDocumented" either with `"validation": { "notDocumented": true }` or `--validation.notDocumented`
2. Configure "requiredToBeDocumented" with the types you want documented ("Class", "Interface", etc.). Throw a bad value in there and TypeDoc will print out all the options when trying to run. Note: Some values are effectively aliases of others. `Accessor` is equivalent to providing `GetSignature` and `SetSignature`.

**Comment by cjduncana** [comment]
Excellent! 🙌🏻 Let me play around with it to gain a better understanding of how it works before I update the documentation.
