### ISSUE TITLE
declare module vs @module different output

### ISSUE THREAD

**Issue by lal12** [TypeStrong/typedoc#2401]
## Search terms

module, declare module, 

## Question

Before I a .d.ts file was only as a way to document a library/environment.

So each file looked like this:

```
/**
* @module foo:bar
* This module can be imported to do something
*/
export function doSomething(a: any): void;
```

This resulted in the comment above being included and the page being called `foo:bar`.
However know I want to use those .d.ts also as reference in Typescript, so I need to wrap the whole file into a `declare module`:
```
/**
* @module foo:bar
* This module can be imported to do something
*/
declare module 'foo:bar'{
export function doSomething(a: any): void;
}
```
 now however the page is title as (Module +) filename and the comment isn't included either.

How can I handle this?

**Comment by Gerrit0** [comment]
The `@module` tag currently doesn't work on `declare module`, though it really ought to

**Comment by saghul** [comment]
Thanks for fixing this!

**Comment by saghul** [comment]
Follow up question: will the module comments also be preserved?

**Comment by Gerrit0** [comment]
When a file only contains `declare module "foo"`, the comment on that will be used as the module comment
