### ISSUE TITLE
What're the options for the `requiredToBeDocumented` option?

### ISSUE THREAD

**Issue by electrovir** [TypeStrong/typedoc#2402]
## Search terms

- requiredToBeDocumented
- documentation
- reflection

## Question

I'm new to TypeDoc. I see that the `requiredToBeDocumented` option is documented here: https://typedoc.org/options/validation/#requiredtobedocumented. However, I do not see documentation for what values this option accepts or what they mean. So far I've determined the possible options by intentionally triggering this error message:

```
[error] 'X' is an invalid value for 'requiredToBeDocumented'. Must be one of: Project, Module, Namespace, Enum, EnumMember, Variable, Function, Class, Interface, Constructor, Property, Method, CallSignature, IndexSignature, ConstructorSignature, Parameter, TypeLiteral, TypeParameter, Accessor, GetSignature, SetSignature, TypeAlias, Reference
```

It seems weird to me that I have to provide an invalid value in order to even find out what the valid values are.

Even after discovering these values, I'm unsure what some of them mean. Obviously some are obvious, like `Function`, but others aren't (to me at least). For example, what is `CallSignature`? (I'm unsure of others as well, not just that one.)

**Comment by electrovir** [comment]
I've now found the possible values by browsing the API page: https://typedoc.org/api/interfaces/Configuration.TypeDocOptions.html#requiredToBeDocumented

Still haven't found any explanations though.

**Comment by Gerrit0** [comment]
The API page unfortunately looks like it's also including all of TypeDoc's shortcuts which are unions of two or more reflection kinds (that enum is made up of increasing powers of two to allow such usage)

You're absolutely right that the docs are lacking here, updating!

**Comment by Gerrit0** [comment]
How's this look? https://github.com/TypeStrong/typedoc-site/commit/c191ef566f0a88ba83afca55cf1d17064ce9b522

**Comment by electrovir** [comment]
Wow thanks, that looks awesome! The only option that I'm still wondering about is `Project`, what does that correspond to?

**Comment by Gerrit0** [comment]
The top level reflection in your documentation is the Project, guess I should make a note about that too 

There's only ever one, so it generally doesn't make sense to require it be documented (it also can only *be* documented if you have a single entry point)

**Comment by electrovir** [comment]
Cool, thanks! All my questions have been answered for this then! 🥳
