### ISSUE TITLE
How to merge multiple json using TypeDoc programmatically?

### ISSUE THREAD

**Issue by matteobruni** [TypeStrong/typedoc#2404]
## Search terms

json, merge, programmatically

## Question

Desired use case:

I have N projects creating TypeDoc JSON output files instead of the HTML ones. In another project I'd like to merge all of them in a single HTML output files, to have a single website for all these projects.

For the moment I'm building projects and docs manually with a Node.js script that checkouts all these repositories, builds them and call a single TypeDoc application programmatically to create a single output. (Script [here](https://github.com/tsparticles/website/blob/main/deploy.js))

It takes forever to do this, downloading only regenerated JSON files will improve build times for sure.

Is this possible?

**Comment by matteobruni** [comment]
> Why are you merging?

I splitted the monorepo in many repo, one per framework/library like Angular, React, Vue, but I’d like to keep the docs together

**Comment by Gerrit0** [comment]
There's a couple ways to do this. The simplest is probably to use TypeDoc's `merge` entry point strategy, and provide the JSON files you want to merge as the entry points.

```ts
const TypeDoc = require("typedoc");

async function main() {
    const app = await TypeDoc.Application.bootstrapWithPlugins({
        entryPoints: ["typedoc-output/*.json"],
        entryPointStrategy: TypeDoc.EntryPointStrategy.Merge
    });

    const project = await app.convert();

    if (project) {
        const outputDir = "docs";

        // Rendered docs
        await app.generateDocs(project, outputDir);
        // Alternatively generate JSON output
        await app.generateJson(project, outputDir + "/documentation.json");
    }
}

main().catch(console.error);
```

You could also use [`app.deserializer`](https://typedoc.org/api/classes/Deserializer.html) directly, but that won't be the same as TypeDoc's packages mode as it doesn't emit the Application.REVIVE event (which is used to do stuff like resolving cross-json links), so likely isn't what you want to do.
