### ISSUE TITLE
How to use @module (with sub-modules)?

### ISSUE THREAD

**Issue by Tobjoern** [TypeStrong/typedoc#2405]
## Question
I'm currently documenting an older project, which features a quite nested structure.
My idea is to declare nested modules, i.e. '/classes', '/classes/users', '/classes/users/resolvers', ...

To achieve this, I tried to use the '@module' tag and reproduce the example given in the [documentation](https://typedoc.org/tags/module/).
Here is a small excerpt of the code:
```
/**
 * This is the doc comment for thing1/functions.ts
 *
 * Specify this is a module comment and rename it to thing1:
 * @module thing1
 */
export * from "./thing1/functions";
```

From my understanding, this should create a module 'thing1', which holds everything, which is exported from the './thing/functions' TS file.
However, all the exported functions are simply added to the 'root' module, when looking at the generated ui.

I also created a reproduction here: https://github.com/Tobjoern/typedoc-module-repro

Since I'm new to the project, I most likely made some mistake in the setup.
My question is, how do I get the @module tag to work, and how can I most effectively display a deeply nested folder structure with typedoc?

Your help is highly appreciated.

**Comment by Gerrit0** [comment]
This is not what `@module` is for, it is only for renaming an entry point which TypeDoc gets wrong.

You probably want

```ts
/**
 * Doc
 */
export * as thing1 from "./thing1/functions"
```

**Comment by Tobjoern** [comment]
> This is not what `@module` is for, it is only for renaming an entry point which TypeDoc gets wrong.
> 
> You probably want
> 
> ```ts
> /**
>  * Doc
>  */
> export * as thing1 from "./thing1/functions"
> ```
Thanks for your help.
I adjusted the code in the way you described, but I still don't get the module 'thing1' to show up.

**Comment by Gerrit0** [comment]
![image](https://github.com/TypeStrong/typedoc/assets/19329837/e9fcea48-4b6a-4f2a-b3fc-4a9118f39b72)

Going to need more info than that then.. seems to create a namespace for me.

```diff
diff --git a/src/index.ts b/src/index.ts
index 4595237..0207a39 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -9,8 +9,5 @@ export * from "./internals";
 
 /**
  * This is the doc comment for thing1/functions.ts
- *
- * Specify this is a module comment and rename it to thing1:
- * @module thing1
  */
-export * from "./thing1/functions";
\ No newline at end of file
+export * as thing1 from "./thing1/functions";
```

Alternatively, specifying multiple entry points:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/eb6ea30d-1748-4d63-8c82-4b27e91b6e70)

```diff
diff --git a/src/index.ts b/src/index.ts
index 4595237..e4b7f59 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -7,10 +7,3 @@ export * from "./showcase";
 export * from "./reactComponents";
 export * from "./internals";
 
-/**
- * This is the doc comment for thing1/functions.ts
- *
- * Specify this is a module comment and rename it to thing1:
- * @module thing1
- */
-export * from "./thing1/functions";
\ No newline at end of file
diff --git a/src/thing1/functions.ts b/src/thing1/functions.ts
index 8296110..1d41dca 100644
--- a/src/thing1/functions.ts
+++ b/src/thing1/functions.ts
@@ -1,3 +1,5 @@
+/** @module thing1 */
+
 /**
  * Calculates the square root of a number.
  *
diff --git a/typedoc.json b/typedoc.json
index 184f569..16b38ec 100644
--- a/typedoc.json
+++ b/typedoc.json
@@ -2,7 +2,8 @@
     "$schema": "https://typedoc.org/schema.json",
     "name": "TypeDoc Example",
     "entryPoints": [
-        "./src"
+        "./src",
+	"./src/thing1/functions.ts"
     ],
     "sort": [
         "source-order"
@@ -23,4 +24,4 @@
     "sidebarLinks": {
         "API": "https://typedoc.org/api"
     },
-}
\ No newline at end of file
+}
```

**Comment by Tobjoern** [comment]
Thanks, using named exports like
`export * as thing1 from "./thing1/functions";`
or
`export * as subModule from './submodule/index'`

Fixed the issue for me.
