### ISSUE TITLE
front-end `Settings` checkbox never checked

### ISSUE THREAD

**Issue by hasezoey** [TypeStrong/typedoc#2408]
## Search terms

front-end
settings
checkbox

## Expected Behavior

I expect the checkboxes under `Settings` to display something different than when not checked

## Actual Behavior

Currently the settings checkboxes stay the same, regardless if active or not

## Steps to reproduce the bug

open some typedoc site (using 0.25.1) and try to use the settings

## Environment

-   Typedoc version: 0.25.1
-   TypeScript version: 5.0.4
-   Node.js version: 20.5.1
-   OS: Linux Manjaro 23.0.2

---

additional context:
this problem goes away when downgrading to 0.24.8

also when using darkreader (it is disabled for the above issues), those checkboxes (and some other svgs) are a problem, see https://github.com/darkreader/darkreader/issues/11786, the old website design worked fine (like 0.22)

**Comment by Gerrit0** [comment]
Oops..

Darkreader seems like it ought not even activate on TypeDoc's pages... by default, the theme natively respects the browser's color scheme preferences.

**Comment by hasezoey** [comment]
> Darkreader seems like it ought not even activate on TypeDoc's pages... by default, the theme natively respects the browser's color scheme preferences.

i have it active by default and used it when there was no theme settings, also i personally prefer black-gray-ish rather than blue-ish dark (at least on my screen), just wanted to mention it here, because the issue (at least visually) looked similar
