### ISSUE TITLE
Documenting Vue 3 components / Pinia stores

### ISSUE THREAD

**Issue by pkgw** [TypeStrong/typedoc#2409]
## Search terms

Vue, Pinia, components

## Question

I have a package that uses TypeScript and Vue 3. We define a component class using [Vue.defineComponent()](https://vuejs.org/api/general.html#definecomponent), which has a complex type signature but is basically returning a constructor for a class whose properties are defined by the function arguments.

Unfortunately, Typedoc interprets the resulting value as a variable with a type that, in my case, is unreadable:

https://docs.worldwidetelescope.org/webgl-reference/latest/apiref/engine-pinia/variables/WWTAwareComponent.html

Is there a way to get this to show up as a proper class instead? I wouldn't be surprised if a plugin was required, but I've searched around and nothing seems to be available. I'm willing to contemplate writing one, but if there's a different documentation system that would handle this case better, that might honestly be the better approach :-/

Would there perhaps be some way to define a type associated with `typeof WWTAwareComponent` that could express it as a documentable class? Or some other workaround?

Similarly we have a variable created via [pinia.defineStore()](https://pinia.vuejs.org/core-concepts/) that also fails badly:

https://docs.worldwidetelescope.org/webgl-reference/latest/apiref/engine-pinia/functions/engineStore.html

Here, there seems to be some type inference happening so that TypeDoc decides to categorize this variable as a function.

If it's useful, here's the source code: [WWTAwareComponent](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine-pinia/src/wwtaware.ts#L226), [engineStore](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine-pinia/src/store.ts#L460).

Thanks for any advice.

**Comment by Gerrit0** [comment]
```ts
export class WWTAwareComponent extends defineComponent({}) {}
``` 

May be better, though in general, highly dynamic code like this is nearly impossible to document in a reasonable way for all cases. A while ago I threw together a plugin which uses `{@displayType}` to tell TypeDoc what should be displayed as the type. #2273.

The [`@interface`](https://typedoc.org/tags/interface/) tag also exists, which tells TypeDoc to try to statically resolve all properties of a type, but it was intended for type aliases, not values, so won't work in this case... There's also [`@namespace`](https://typedoc.org/tags/namespace/), but the pinia store at least seems like it ought to actually be documented as a variable. I'm not opposed to adding a tag for this... `@resolve`?

**Comment by pkgw** [comment]
The `class ... extends...` approach seems to work shockingly well! If I could combine it with `@interface`, I think that would basically get me there, but I don't think I can because TypeScript cares about the difference between class methods and properties that are functions:

```
export interface WWTAwareComponent {
  startTour(): void; // just one sample function as a test
}
```

leads to

```
Class '[long unreadable stuff]' defines instance member property 'startTour', but extended class 'WWTAwareComponent' defines it as instance member function.
```

**Comment by Gerrit0** [comment]
I got nerd sniped... https://github.com/Gerrit0/typedoc-plugin-vue should make your docs a lot nicer without needing the `class extends defineComponent` workaround

**Comment by pkgw** [comment]
Incredible, thank you! With a little bit of futzing I was able to use your new plugin to get our docs back in order.
