### ISSUE TITLE
Fails to generate MD with plugin anymore

### ISSUE THREAD

**Issue by haf** [TypeStrong/typedoc#2410]
## Expected Behavior

The command should not crash.

## Actual Behavior

```
> typedoc --theme markdown --tsconfig tsconfig-typedoc.json --disableSources --out ./md-docs ./src

[error] The theme 'markdown' is not defined. The available themes are: default
[error] Documentation could not be generated due to the errors above.
```

## Steps to reproduce the bug

devDependencies:
```
    "typedoc": "^0.25.2",
    "typedoc-plugin-markdown": "^3.16.0",
    "typescript": "^5.2.2",
```

also under dependencies:

```
  "dependencies": {
    "@corp/sdk": "workspace:sdk"
  }

```

## Environment

-   Typedoc version: 0.25.2
-   TypeScript version: 5.2.2
-   Node.js version: 18.18
-   OS: macOS
-   package manager: pnpm 8

Using a monorepo. However, this project is self-contained an does not reference anything. But it means pnpm-workspace.yaml is a level below.

**Comment by Gerrit0** [comment]
This is working as intended. Typedoc no longer automatically loads plugins from node_modules as of 0.24. Release notes are a good thing. 

https://github.com/TypeStrong/typedoc/releases/tag/v0.24.0

**Comment by haf** [comment]
Yes, had I had infinite time, it would be good to read all release notes, but single dev teams rely on e.g. `--help`, which outputs like so:

```
❯ pnpx run typedoc -- --help
Packages: +4
++++
Progress: resolved 4, reused 4, downloaded 0, added 4, done
Watching /Users/h/dev/analytics/sdk-events and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
/Users/h/bin/store/v3/tmp/dlx-18612/node_modules/.pnpm/run@1.4.0/node_modules/run/run.js:127
        if (minimatch(file, pattern)) {
            ^

TypeError: minimatch is not a function
    at /Users/h/bin/store/v3/tmp/dlx-18612/node_modules/.pnpm/run@1.4.0/node_modules/run/run.js:127:13
    at Array.forEach (<anonymous>)
    at parseFolder (/Users/h/bin/store/v3/tmp/dlx-18612/node_modules/.pnpm/run@1.4.0/node_modules/run/run.js:113:9)
    at Object.<anonymous> (/Users/h/bin/store/v3/tmp/dlx-18612/node_modules/.pnpm/run@1.4.0/node_modules/run/run.js:63:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)

Node.js v18.18.0
```

And then I'd look at your docs, but they don't mention `--plugin`: https://github.com/TypeStrong/typedoc#arguments

Finally, your release notes don't mention the way that the plugin is referenced. Is it `markdown` or `typedoc-plugin-markdown`?

**Comment by haf** [comment]
The solution is

> typedoc --plugin typedoc-plugin-markdown --theme markdown --tsconfig tsconfig-typedoc.json --disableSources --out ./md-docs ./src

**Comment by Gerrit0** [comment]
`pnpx run` doesn't execute TypeDoc... that executes the `run` package. If you'd run `pnpx typedoc --help`, you'd have gotten the help message rather than gibberish from an entirely different project.

The arguments section in the readme isn't intended to be complete. TypeDoc has >75 CLI arguments, and most are not useful to everyone. There's a reason that section starts with:

> For a complete list of the command line arguments run typedoc --help or visit [our website](https://typedoc.org/options/).

The release notes don't mention individual plugins, there are [a lot of them](https://typedoc.org/guides/plugins/), and the behavior of `--plugin` wasn't changed.
