### ISSUE TITLE
Non-exported referenced types

### ISSUE THREAD

**Issue by Azario16** [TypeStrong/typedoc#2411]
@Gerrit0 Good afternoon

I agree with you that there is no point in describing variables that are not exported

But what about the interfaces that are exported and inside which there are parameters from the same directory and they are not exported but are used inside the exported interface

How will a person who opens the documentation understand what exactly needs to be put in the required parameter?

Example:

``` ts
export interface User {
    detail: Detail
}

interface Detail {
    name: string;
    age: number
}
```
![image](https://github.com/TypeStrong/typedoc/assets/61908140/f7efbc6f-27e2-45b8-b46d-0462b98bba72)

_Originally posted by @Azario16 in https://github.com/TypeStrong/typedoc/issues/1521#issuecomment-1752929305_

**Comment by Gerrit0** [comment]
`Detail` should be exported. By not exporting it, you're making your API distinctly worse by requiring that if I'm building up an object for your API iteratively I either have to extract the type myself:

```ts
const det: User["detail"] = { ... }

const user: User = { detail: det }
```

Or live without excess property checks while building that object up.

```ts
const det = {
  name: "x",
  age: 123,
  married: false
}

const x: User = { detail: det } // NO errors!
```

However, I've gotten sufficiently tired of arguing with people about this, so [typedoc-plugin-missing-exports](https://www.npmjs.com/package/typedoc-plugin-missing-exports) exists, and will automatically create documentation for non-exported "exports" and stick them in an `<internals>` namespace.

**Comment by Azario16** [comment]
Yes, you're right, it's really logical and makes sense.
Thanks for the answer and experience
