### ISSUE TITLE
how can i de-dupe .js and .d.ts in a JavaScript-based project?

### ISSUE THREAD

**Issue by jcbhmr** [TypeStrong/typedoc#2412]
## Search terms

javascript
declaration
dts
.d.ts

## Question

how can i make is so that this:
![image](https://github.com/TypeStrong/typedoc/assets/61068799/8919b286-9af1-43c2-ae82-24588a3a2ed3)

generates NOT this
![image](https://github.com/TypeStrong/typedoc/assets/61068799/24db3a14-2d44-4dfc-8c37-10098e7c1b26)

but instead this (excuse my mspaint lol)
![image](https://github.com/TypeStrong/typedoc/assets/61068799/c15c0bb0-a728-479d-91d8-f7bc146b77a0)

preferrable solution: if there's a .js file and a .d.ts file with the same-ish name, ignore the .js file

idk if there's a magic way to do this with `"exclude": [... magic]` or some fancy plugin? looking for help.

stackblitz thingie to see the problem live. https://stackblitz.com/edit/vitejs-vite-kzaymw

real world situation: writing code that **really really should** be in javascript (too complex to do `tsc && the-main-thing-that-uses-js`) and am using jsdoc. BUT there's no jsdoc equivalent (that i know of) to do `declare global { interface Object { myPrototypeMethod(): void } }` and so i made a .d.ts file... but now its picking up TWO files to document things and i dont want duplicates 😩

**Comment by jcbhmr** [comment]
after some post-clarity googling after i wrote my question down 👆 i found that this works:

```js
/** @ignore @module */
export function setupCounter(element) {
// ...
```
https://stackblitz.com/edit/vitejs-vite-vmmnen

https://jsdoc.app/tags-ignore.html
https://jsdoc.app/tags-module.html

note that just the `@ignore` DOESNT ignore the entire namespace and just ignores that specific function thing. somehow the magic `@module` makes it apply to the entire file? idk
```js
// this doesn't cut it.
/** @ignore */
export function setupCounter(element) {
// ...
```

itd be nice if there was a generalized solution (plugin or magic exclude idk), but i can live with this manual jsdoc `@ignore` solution 😊

**Comment by jcbhmr** [comment]
i tried it in my project and it worked! caveat: the `@ignore @module` comment MUST be the FIRST STATEMENT even before the `"use strict";` thing if you're using commonjs. but if you do that, it WORKS! 🤩

closing since i solved my own problem. 👍

**Comment by Gerrit0** [comment]
You've configured typedoc to read both files with the entry points in the tsconfig, so I think typedoc is behaving exactly as it ought to here..

I'd recommend either specifying what entry points you want explicitly, or potentially using a `typedoc.config.js` file where you can apply that logic yourself.

I recommend TypeDoc's documentation for tags over JSDoc's. They do not always mean the same thing. https://typedoc.org/guides/tags/, specifically https://typedoc.org/tags/module/

**Comment by jcbhmr** [comment]
> You've configured typedoc to read both files with the entry points in the tsconfig, so I think typedoc is behaving exactly as it ought to here..

i think it sorta depends on how closely you adhere to typescript behaviour. on one hand, yeah, per-file makes sense. on the other hand, typescript auto-resolves `import "./theFile.js"` to use types from `./theFile.d.ts` and appears to ignore the .js. intuition from cli tools (operate on files) vs tsc (does fancy resolution overload logic). idk which is better really; i do know that _i personally_ sorta expected tsc-like behaviour due to typedoc integrating so well with the tsconfig.json and other tsc tooling. 🤷‍♀️

> I'd recommend either specifying what entry points you want explicitly, or potentially using a typedoc.config.js file where you can apply that logic yourself.

```sh
$ find . -type f | wc -l
3873
```
yeah... i dont really want to put ~1000 files in my typedoc.json lol
the trick with typedoc.config.js seems like it might be a winner tho!

> I recommend TypeDoc's documentation for tags over JSDoc's. They do not always mean the same thing. [typedoc.org/guides/tags](https://typedoc.org/guides/tags/), specifically [typedoc.org/tags/module](https://typedoc.org/tags/module/)

👍
