### ISSUE TITLE
Missing comments on interface index signatures

### ISSUE THREAD

**Issue by adidahiya** [TypeStrong/typedoc#2414]
## Search terms

missing, omitted, comment, property, method, interface, signature

## Actual Behavior

I'm working on upgrading a library from typedoc 0.19 -> 0.25 and I'm noticing that comments on index signatures are being dropped:

```ts
export interface ObjectWithIndexSignature {
  /** Looking for this JSDoc comment in the output JSON. */
  [x: string]: any;
}
```

The reflection for the index signature both return `ref.hasComment() == false` and I no longer get the comment contents.

You can see my Jest snapshots which changed to flag this regression in my upgrade PR here: https://github.com/palantir/documentalist/pull/156#discussion_r1365897305

## Expected Behavior

I should get comments on index signatures like I previously did with typedoc v0.19

## Steps to reproduce the bug

See repro on my fork here: https://github.com/adidahiya/typedoc-repros/pull/1

## Environment

-   Typedoc version: 0.25.2
-   TypeScript version: 5.2.2
-   Node.js version: 18.18
-   OS: macOS

**Comment by Gerrit0** [comment]
Good find!

**Comment by adidahiya** [comment]
nice, thanks for the quick fix @Gerrit0!
