### ISSUE TITLE
Provide an option flag to allow opening source links in a new tab

### ISSUE THREAD

**Issue by JamesLMilner** [TypeStrong/typedoc#2415]
## Search Terms

CSP, new tab, tab links, GitHub pages

## Problem

At the moment all links to source code do not open in new tabs by default. There is no issue in this behaviour as it is expected, however if you are hosting your docs in an iframe in a page that has the [CSP policy `frame ancestors: none`](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#preventing-framing-attacks-clickjacking-cross-site-leaks) then the page will fail to load in the iframe. Sites such as GitHub Pages have this policy enabled, making it hard to host the docs on GitHub pages.

## Suggested Solution

It would be great if there was a flag to enable adding target="_blank" which opens the link in a new tab. Perhaps something like `sourceLinkNewTab` which defaults to true but is configurable to false. 

This would result in the generated HTML going from something like this:

```html
<li>Defined in <a href="https://github.com/JamesLMilner/terra-draw/blob/f640815/src/terra-draw.ts#L69">terra-draw.ts:69</a></li>
```

to this:

```
<li>Defined in <a href="https://github.com/JamesLMilner/terra-draw/blob/f640815/src/terra-draw.ts#L69" target="_blank" rel="noopener noreferrer">terra-draw.ts:69</a></li>
```

I feel like people hosting there docs on GitHub Pages is probably a common use case so this feels like it would be beneficial to others hopefully.

**Comment by Gerrit0** [comment]
> GitHub Pages is probably a common use case

Certainly! This is the first time I've heard of someone using an iframe though... *shudder*

I actually thought these links already opened in a new tab, I meant to do that for all external links...

**Comment by JamesLMilner** [comment]
Thanks for this! Really helpful
