### ISSUE TITLE
Where does typedoc get the module names from?

### ISSUE THREAD

**Issue by 0815fox** [TypeStrong/typedoc#242]
Maybe it's a stupit question...?

Looking at the typedoc documentation, I see it uses the modules mode. Where does it get the modules td, td.converter, td.models, td.output from?

I can nowhere find "td" in the sources as module name?

How does e.g. output become a module, while utils does not?

**Comment by MaPUILabs** [comment]
Yeah same for me. I dont really understand this. 
When I build the exemples doc (the one in exemples/self) I don't even have "the td.something" modules, it looks like every file is displayed as a module. 

I have the same problem on my personnal project. Is there any solution ?
![capture](https://cloud.githubusercontent.com/assets/18192843/17213074/ffc803a2-54d2-11e6-959a-82cb20847e34.PNG)

**Comment by aciccarello** [comment]
@MaPUILabs 
You are probably using "files" mode which considers each file a separate module.

> --mode <file|modules>
> Specifies the output mode the project is used to be compiled with.

@0815fox, I think that the typedoc.io site hasn't been updated in a while. You'll notice that there is no td/ directory as specified in the documentation links. That was changed when typedoc updated to 0.4.0

**Comment by lucaterribile** [comment]
I have similiar issue, each file is displayed as module, and documentations and modules are not group by namespace hierarchy.

Is there any solution?

Example: If I have 2 modules with namespace AA.BB.CC e AA.BB.DD, I would like navigate in documentation using namespace hierarchy:

AA
---BB
-----CC
-----DD

Thanks,
Luca
