### ISSUE TITLE
Target single tag for compilation

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2421]
## Search terms

- packageDocumentation
- readme

## Question

I document the entry point for a whole lot of modules (monorepo and single repo) with the `@packageDocumentation` tag in `/src/index.ts`.  The block looks something like:

```js
/**
 * @packageDocumentation
 *
 * This module is a $FOO, it's useful for $BAR.
 *
 * These links might add some context
 *
 * @see http://example.com/hello
 * @see http://example.com/world
 *
 * @example
 * 
 * Here's how you do $BAZ with it:
 * 
 * ```js
 * // some code here
 * ```
 */

// implementation code here
```

The package documentation is always declared in it's own comment block and always in `/src/index.ts`.

I'd really like to include this information in the README so people can see it on npm/github but not have keep the two things in sync manually.  I already auto-generate READMEs based on the properties of the current repo so this would be a case of generating the markdown (preferably) or HTML and adding it to the README template.

Is there a way to have a typedoc plugin that can intercept the output of specific tags or to do this programatically somehow?

**Comment by Gerrit0** [comment]
Plugins can modify comments:

```ts
// @ts-check
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, onCreateDeclaration);
}

/**
 * @param {td.Context} context
 * @param {td.DeclarationReflection} refl
 */
function onCreateDeclaration(context, refl) {
    const symbol = context.project.getSymbolFromReflection(refl);
    const decl = symbol?.getDeclarations()?.[0];
    if (!decl) return;

    if (refl.kindOf(td.ReflectionKind.Module)) {
        console.log("Created declaration for module", refl.getFullName(), "at", decl.getSourceFile().fileName);
        // create/update refl.comment
    }
}
```

**Comment by achingbrain** [comment]
That looks like a simpler solution than the one I came up with, but it doesn't seem to work for me.  Nothing seems to pass the `refl.kindOf(td.ReflectionKind.Module)` test in mono-repos or single-module repos.

I ended up [listening for `RendererEvent.END` events](https://github.com/ipfs/aegir/blob/master/src/docs/readme-updater-plugin.js#L24-L41) and looking at each `UrlMapping`, then detecting if it relates to either a `modules.html` file (for single-module repos) or if the model.name of the mapping corresponds to a module name in the mono-repo.

It does feel a bit hacky though, I'd prefer a simpler solution if one is possible.

**Comment by Gerrit0** [comment]
Oops, I completely forgot to consider projects with a single entry point. In that case, the root of the module will be the ProjectReflection.

```ts
// @ts-check
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, onCreateDeclaration);
    // The symbol won't be associated yet if listening to EVENT_BEGIN.
    app.converter.on(td.Converter.EVENT_END, onEnd);
}

/**
 * @param {td.Context} context
 */
function onEnd(context) {
    const symbol = context.project.getSymbolFromReflection(context.project);
    const decl = symbol?.getDeclarations()?.[0];
    if (!decl) return;

    console.log("Created project for module", context.project.getFullName(), "at", decl.getSourceFile().fileName);
}

/**
 * @param {td.Context} context
 * @param {td.DeclarationReflection} refl
 */
function onCreateDeclaration(context, refl) {
    const symbol = context.project.getSymbolFromReflection(refl);
    const decl = symbol?.getDeclarations()?.[0];
    if (!decl) return;

    if (refl.kindOf(td.ReflectionKind.Module)) {
        console.log("Created declaration for module", refl.getFullName(), "at", decl.getSourceFile().fileName);
        // create/update refl.comment
    }
}
```
