### ISSUE TITLE
Version number is always included in monorepo root?

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2423]
## Search terms

- monorepo
- includeVersion
- version

## Expected Behavior

In a monorepo, when `typedoc.json` in the root of the monorepo has:

```json
{
  "includeVersion": false
}
```

I would expect the version number not to be displayed.

## Actual Behavior

The version number is displayed:

<img width="1015" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/bd25be90-b2d9-458d-9732-8c3c9c95ceaa">

`"includeVersion": false` is respected for individual monorepo packages (via `typedoc.json` in each package folder), just not the monorepo root.

## Steps to reproduce the bug

Build docs for a monorepo with `"includeVersion": false` in the root `typedoc.json`

## Environment

-   Typedoc version: 0.25.2
-   TypeScript version: 5.2.2
-   Node.js version: 20.8.0
-   OS: Mac OS X 13.5.1

**Comment by achingbrain** [comment]
Experimenting a bit more, the version number is always included in non-monorepo projects too, even if you have `"includeVersion": false` in `typedoc.json`.  If you specify `--includeVersion false` on the CLI it works as expected, however and omits the version number in the generated docs.

This seems related to https://github.com/TypeStrong/typedoc/issues/2424 in that some options are recognised on the CLI but ignored in `typedoc.json`.

**Comment by Gerrit0** [comment]
I'm going to have to ask for a reproduction for this one, the example project I set up for packages mode when first developing the project has a setup that does exactly this, and works as expected, might be a good starting point for a minimal repro.

https://github.com/Gerrit0/typedoc-packages-example

**Comment by achingbrain** [comment]
Ah, sorry for opening this, it was user error.  I was passing a different `--includeVersion` arg to typedoc elsewhere.
