### ISSUE TITLE
Exclude monorepo package from config file

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2424]
## Search terms

- exclude
- monorepo
- package

## Expected Behavior

typedoc config should be consistent between `typedoc.json` and CLI arguments.

## Actual Behavior

Excluding a monorepo package works on the CLI:

```console
$ typedoc --exclude packages/undocumented-package
// packages/undocumented-package is not in the generated docs
```

If I configure the same thing via a `typedoc.json` in the root of the monorepo and just run `typedoc` (without the `--exclude`) it no longer excludes the package:

```json
{
  "exclude": [
    "packages/undocumented-package"
  ]
}
```

```console
$ typedoc
// packages/undocumented-package *is* in the generated docs
```

## Steps to reproduce the bug

See above.

## Environment

- Typedoc version: 0.25.2
- TypeScript version: 5.2.2
- Node.js version: 20.8.0
- OS: Mac OS X 13.5.1

**Comment by Gerrit0** [comment]
Going to have to ask for a reproduction here, this seems to work correctly for me. I made the following change to https://github.com/Gerrit0/typedoc-packages-example, and TypeDoc excludes `foo` exactly as expected.

```diff
diff --git a/typedoc.json b/typedoc.json
index 55d96f8..ef4407e 100644
--- a/typedoc.json
+++ b/typedoc.json
@@ -2,7 +2,8 @@
   "entryPoints": ["packages/*"],
   "name": "Packages Example",
   "entryPointStrategy": "packages",
-  "includeVersion": false
+  "includeVersion": false,
+  "exclude": ["packages/foo"]
 
   // Potentially useful for debugging
   // "logLevel": "Verbose"
```

**Comment by achingbrain** [comment]
Ah, sorry for opening this, it was user error.  I was passing a different `--exclude` tag to typedoc elsewhere.
