### ISSUE TITLE
How to get non-readme content onto a module home page.

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2429]
## Search terms

- module
- empty
- readme

## Question

I have a monorepo module with one entry point.  I don't want to show the README because there's a much better (more specific) `@packageDocumentation` block in the `/src/index.ts`.

```json
{
  "entryPoints": [
    "./src/index.ts"
  ],
  "readme": "none"
}
```

<img width="1302" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/a11a2c9d-87e1-46b7-a058-bd0bb6bab69f">

If I add another entry point the landing page for the module is now devoid of context:

```json
{
  "entryPoints": [
    "./src/index.ts",
    "./src/routes/index.ts"
  ],
  "readme": "none"
}
```

<img width="1243" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/11b31530-1970-403b-b4d8-7b584fda0c4c">

The module index shows the rendered `@packageDocumentation` block:

<img width="1313" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/c49aded3-ee5c-4a76-8fcf-845e52b17324">

----

Is it possible to have multiple entry points but still get some non-readme content onto the module landing page?

**Comment by Gerrit0** [comment]
Not possible today without a plugin which adds stuff to the `.readme` field, which is pretty easy to write, this one will copy the comment from your index module:

```bash
$ typedoc --plugin ./plugin.mjs
```

```ts
// @ts-check
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(td.Converter.EVENT_RESOLVE_END, copyIndexComments);
}

/**
 * @param {td.Context} context
 */
function copyIndexComments(context) {
    const modules = context.project.getReflectionsByKind(td.ReflectionKind.SomeModule);

    for (const mod of modules) {
        if (mod.name === "index" && mod.parent) {
            mod.parent.comment ||= mod.comment?.clone();
        }
    }
}
```

**Comment by achingbrain** [comment]
I guess the weird thing here is it creates inconsistent navigation (and pages) when there is more than one entry point.

E.g. the first module only has a single entry point so all exported symbols are children of the module name in the nav:

```ts
// single entry point, just the module root
import { createDelegatedRoutingV1HttpApiClient } from '@helia/delegated-routing-v1-http-api-client'
```

<img width="302" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/d2eafe4e-2036-4917-9d63-9cba67e34eb4">

The second module has two entry points the root and `/routes`, so a synthetic "index" navigation item is created:

```ts
// two entry points, the root and `/routes`
import { createDelegatedRoutingV1HttpApiServer } from '@helia/delegated-routing-v1-http-api-server'
import routes from '@helia/routing-v1-http-api-server/routes'
```

<img width="274" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/51eab1fe-7aa9-48ec-9da4-2acff5c7185b">

What I might find more intuitive is if only the `/routes` entry point was a submenu, something like:

<img width="325" alt="image" src="https://github.com/TypeStrong/typedoc/assets/665810/c67077af-8281-48ad-bbcd-c6fb6f8a60db">

This way selecting the module on the left could show the `@packageDocumentation` block in the `/src/index.ts` the same as with the single-entrypoint version?

**Comment by Gerrit0** [comment]
I like the idea for that if there is a module that'd be named "index"... unfortunately that'll need to wait for 0.26 since it'll break external links to people's documentation.

In the meantime, you can do this via a plugin:

```js
// @ts-check
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(td.Converter.EVENT_RESOLVE_BEGIN, moveIndexModuleToParent, undefined, 10000);
}

/**
 * @param {td.Context} context
 */
function moveIndexModuleToParent(context) {
    const modules = /** @type {td.DeclarationReflection[]} */ (
        context.project.getReflectionsByKind(td.ReflectionKind.Module)
    );

    for (const mod of modules) {
        const parent = /** @type {td.DeclarationReflection | td.ProjectReflection} */ (mod.parent);
        if (!parent) continue;

        if (mod.name !== "index") {
            if (context.project.getSymbolFromReflection(mod)) {
                mod.name = "/" + mod.name;
            }
            continue;
        }

        parent.comment = mod.comment;
        parent.children ||= [];

        for (const child of mod.children || []) {
            child.parent = mod.parent;
            parent.children.push(child);
        }

        context.project.removeReflection(mod);
    }
}
```
