### ISSUE TITLE
How to render README.md for each index?

### ISSUE THREAD

**Issue by LaiArturs** [TypeStrong/typedoc#2431]
## Search terms

README.md, index, 

## Question

I have a project with following structure:
```
.
├── package.json
├── src
│   ├── index.ts
│   ├── moduleA
│   │   ├── functionalityA.ts
│   │   ├── index.ts
│   │   └── README.md
│   ├── moduleB
│   │   ├── functionalityB.ts
│   │   ├── index.ts
│   │   └── README.md
│   └── README.md
└── typedoc.json
```

I would like `moduleA` and `moduleB` index to render corresponding README.md file.
I feel that this is something that could be supported, but I can't find a way for it to work.

This is what I get:
![image](https://github.com/TypeStrong/typedoc/assets/31618791/bdee93c7-8a8f-4acf-a971-c3020cfcf8b1)

This is the README.md file I hoped to see rendered:
```
$ cat src/moduleA/README.md 
# Module A README

This is the README for module A.
```

This is my `typedoc.json`:
```
{
    "entryPoints": [
        "./src/",
        "./src/moduleA/",
        "./src/moduleB/"
    ],
    "out": "docs/",
    "json": "docs/index.json"
}
```

I build docs with this cmd:
```
yarn typedoc --options typedoc.json
```

To be clear I would like all three README.md files to be included in generated documentation:
```
./src/moduleA/README.md
./src/README.md
./src/moduleB/README.md
```

**Comment by Gerrit0** [comment]
Currently not supported, unless each module was a separate package and packages mode was used to convert the project. #1870 tracks support for including arbitrary markdown files in the docs.

**Comment by LaiArturs** [comment]
This functionality can be achieved with plugin [@knodes/typedoc-plugin-pages](https://github.com/KnodesCommunity/typedoc-plugins). However, this plugin only supports TypeDoc version ^0.23.0.
