### ISSUE TITLE
Allow injection of HTML into output, primarily for Analytics

### ISSUE THREAD

**Issue by suzukieng** [TypeStrong/typedoc#2435]
## Search Terms

Analytics, customize HTML

## Problem

Typedoc allows supplying an ID for Google Analytics to insert tracking code:
https://typedoc.org/options/output/#gaid

While this is useful if you're using Google Analytics, it is not flexible enough to integrate other Analytics solutions like Plausible, which are more privacy-friendly and perhaps better suited for developer docs (no cookie banner needed).

## Suggested Solution

Allow specifying an HTML file whose content gets included in the <head> of the generated HTML.
This is similar to how other tools support Analytics code injection (e.g. Jetbrains Writerside)

**Comment by Gerrit0** [comment]
You can do this via hooks already -- https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md

**Comment by Gerrit0** [comment]
I don't have any plans to add text based templating back to typedoc -- it used to use handlebars for the themes, which was a nightmare due to lack of typechecking... even just for small injection points, I think hooks serve this use case better. If you really wanted this, you could write a plugin which uses hooks and reads user specified text files.

**Comment by suzukieng** [comment]
Thanks @Gerrit0, this pointed me in the right direction.

If anyone else find this useful, here's how to add an HTML snippet to head without referencing an existing plugin on NPM. In this case I'm adding a script tag for Plausible Analytics.

```HTML
<script defer data-domain="example.com" src="/js/script.js"></script>
```

First create a local plugin file and reference it in typedoc.json or via the --plugin CLI parameter:

```JSON
  "plugin": [
    "./typedoc-plausible.js"
  ]
```

In the plugin file, use JSX to create a script tag that will be added before closing the <head> section.

```JavaScript
import {JSX} from "typedoc";

export function load(app) {
    app.renderer.hooks.on("head.end", (ctx) => {
        return JSX.createElement("script", {
            defer: true,
            "data-domain": "yourdomain.com",
            src: "/js/script.js"
        });
    });
}
```
