### ISSUE TITLE
Comments formatting is not honored in the generated documentation

### ISSUE THREAD

**Issue by ericmorand** [TypeStrong/typedoc#2439]
## Search terms

comment formatting
formatting

May be related to https://github.com/TypeStrong/typedoc/issues/2286

## Expected Behavior

I'm working on a library that emulates the output buffering logic of PHP. To make things clear to the users of the library - and because PHP's documentation is lacking in that regard and output buffering is a very confusing matter even for seasoned PHP developers, I'm putting visual representation of the buffer alongside each method documentation.

Like this:

```ts
    /**
     * Flush (send) contents of the output buffer. The last buffer content is sent to next buffer
     *
     * In human terms, append the top-most buffer to the second-top-most buffer and empty the top-most buffer
     *
     * ┌─────────┐    ┌─────────┐
     * │   oof   │    │         │
     * ├─────────┤    ├─────────┤
     * │   bar   │ => │  baroof │
     * ├─────────┤    ├─────────┤
     * │   foo   │    │   foo   │ => true
     * └─────────┘    └─────────┘
     *
     */
    flush(): boolean;
```

I was expecting the comment to be rendered as-is in the documentation.

## Actual Behavior

I don't want to paster a screenshot here, so here is roughly what it looks like once generated:

```html
flush
flush(): boolean
Flush (send) contents of the output buffer. The last buffer content is sent to next buffer

In human terms, append the top-most buffer to the second-top-most buffer and empty the top-most buffer

┌─────────┐ ┌─────────┐ │ oof │ │ │ ├─────────┤ ├─────────┤ │ bar │ => │ baroof │ ├─────────┤ ├─────────┤ │ foo │ │ foo │ => true └─────────┘ └─────────┘

Returns boolean
Defined in [Projects/twing/src/lib/output-buffer.ts:94](https://gitlab.com/eric.morand/twing/-/blob/5eb56a80/src/lib/output-buffer.ts#L94)
```

Maybe I'm missing something - some output options or a different way to write the comments - but it looks like a bug to me - or a feature that TypeDoc doesn't support.

## Environment

-   Typedoc version: 0.25.3
-   TypeScript version: 5.2.2
-   Node.js version: 16.20
-   OS: Ubuntu 20.04

**Comment by Gerrit0** [comment]
TypeDoc is working as intended here, the comment isn't rendered as you wanted in VSCode either.

![image](https://github.com/TypeStrong/typedoc/assets/19329837/9054e6fb-40ec-49a2-b15e-518524af9a44)

TS comments are parsed as markdown by convention, so if you wanted to do something like this, you'd have to make it a code block, which will then be rendered verbatim by both tools:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/b8c712c0-b9a1-4d39-8398-cff6be7dbd6d)

**Comment by ericmorand** [comment]
That's amazing. Thank you so much.
