### ISSUE TITLE
"any | Promise<any>" defined in interface output incorrectly 

### ISSUE THREAD

**Issue by imtuanpham** [TypeStrong/typedoc#2442]
## Search terms

any | Promise<any>

## Expected Behavior

Returns `any | Promise<any>`

## Actual Behavior

Returns `any`

## Steps to reproduce the bug

Create an example interface as below

```
export interface SomeInterface {
  someProp: string;
  someCallback: (someParam: any) => any | Promise<any>;
}
```

The output API Doc looks like the following

![image](https://github.com/TypeStrong/typedoc/assets/35354761/37a4ea24-1c7a-4d7b-83b7-97828f84b65b)

Note that this issue applies to interface only. A type alias is output correctly -- as shown in the example below:

```
export type SomeType = {
  someProp: string;
  someCallback: (someParam: any) => any | Promise<any>;
};
```

![image](https://github.com/TypeStrong/typedoc/assets/35354761/325ddcbb-6efc-4ec6-9b64-0f6502d61924)

## Environment

-   Typedoc version: 0.25.3
-   TypeScript version: 4.8.4
-   Node.js version: 18.16.0
-   OS: MacOS

**Comment by Gerrit0** [comment]
`any | <any possible type>` is just `any` according to the type system. It "works" for type aliases because typedoc converts them with the type node rather than the type. Anywhere typedoc uses the type checker to get the type, it converts this as `any`. This is working as intended.
