### ISSUE TITLE
How to not make separate pages

### ISSUE THREAD

**Issue by sdragos1** [TypeStrong/typedoc#2443]
## Search terms

pages, build

## Question

I am currently trying out TypeDoc, testing plugins and themes. And I only have two plugins currently:
- typedoc-theme-hierarchy
- typedoc-plugin-extras

And I just wanted to know if there is a feature/plugin that could keep all the contents of a typescript file in a single page.

Ex: I have an array.ts file containing multiple functions, I want only one page with all the functions of that file

**Comment by Gerrit0** [comment]
This is controlled by the theme, I'm not aware of any page-per-file themes that exist today
