### ISSUE TITLE
tsconfig of packages ignored when using packages strategy on 0.22.0

### ISSUE THREAD

**Issue by JosefLitos** [TypeStrong/typedoc#2447]
## Search terms

config issues
packages strategy

## Question
I'm working with an old (`TS 4.3.1` → `TD 0.22.0`) codebase and need to generate docs for it, but when using `entryPointStrategy: packages` it seems the packages' individual config files aren't used by TD. I eventually managed to [replicate](https://github.com/JosefLitos/typedoc-packages-issue) the issue with the example packages repo.

The issue is:
```log
./$ npx typedoc --out /tmp/docs
> Warning: Could not determine the entry point for "/home/kepis/typedoc-packages-example/packages/bar/package.json". Package will be ignored.
> Warning: Could not determine the entry point for "/home/kepis/typedoc-packages-example/packages/foo/package.json". Package will be ignored.
> Error: Unable to find any entry points. Make sure TypeDoc can find your tsconfig

./packages/foo/$ npx typedoc --out /tmp/docs
> Warning: BarInt, defined at ../bar/src/index.ts:14, is referenced by foo.foo but not included in the documentation.
> Info: Documentation generated at /tmp/docs
```

So when run from the directory the modules are in, it works better.

I also noticed some other issue mentioning `includeDeclarations`, but I haven't found anything about that on the wiki nor did it work in this older version. I wanted to try that as I was also experiencing issues with declaration files:
```sh
./$ npx typedoc --out '/tmp/docs'
> Warning 'Pkg1Obj', defined at './packages/pkg1/dist/pkg1obj.d.ts:42', is referenced by 'Pkg2Obj' but not included in the documentation
> Warning 'Pkg2AnotherObj', defined at './packages/pkg2/src/resources/pkg2obj.ts:1', is referenced by 'Pkg2Obj' but not included in the documentation
```

I use `entryPointStrategy: expand, entryPoints: ['src']` in those packages. Should I still need to make the entryPoints some `minimatch` pattern to go to the resources directory?

Remember, the config is being ignored, it just went on some defaults and used the `main` attribute of the packages file, so the actual result with my config being applied could be a little different, though I ran into similar issues when testing directly in the individual package directories.

**Comment by Gerrit0** [comment]
Pre-0.24, packages mode was an entirely different implementation which didn't read configuration for each package in the standard way.

It instead tried to use the `main` field in your package.json to find the entry point (relying on source maps to turn that back into a .ts file) or a `typedocMain` key. I honestly don't remember much about how it worked, but I'm pretty sure it just completely didn't support generating docs with multiple entryPoints for packages.

**Comment by JosefLitos** [comment]
Ok, thank you. Could I find somewhere some more information about the `typedocMain` key?

**Comment by Gerrit0** [comment]
There was a passing mention in the readme back then, https://github.com/TypeStrong/typedoc/tree/v0.23.28#monorepos--workspaces and a page on an old version of the site https://web.archive.org/web/20230315112159/https://typedoc.org/guides/monorepo/

**Comment by JosefLitos** [comment]
I will take a look and see what I can do. Thank you for the quick response.
