### ISSUE TITLE
Add JSON view for interfaces

### ISSUE THREAD

**Issue by trevormil** [TypeStrong/typedoc#2449]
## Search Terms

JSON, type definition, interfaces

## Problem

At the top of each type page, there is a nice JSON view of all the properties for the type (see https://bitbadges.github.io/bitbadgesjs/packages/proto/docs/types/Coin.html). However, for interfaces, there is no such UI box.

## Suggested Solution

Would it be possible to also add this view to interface pages as well? It gives a really nice summary of what can be expected from the type all in one place.

**Comment by Gerrit0** [comment]
This is a really good idea, makes it easier to quickly scan for what you know ought to be there!

**Comment by trevormil** [comment]
Thanks! Just updated and this really makes a huge visual difference :)
