### ISSUE TITLE
Confusing error message: length has multiple declarations with a comment

### ISSUE THREAD

**Issue by cowwoc** [TypeStrong/typedoc#2450]
## Search terms
length has multiple declarations with a comment

## Question
When I run version 0.25.4 I get this output:

```
[info] Loaded plugin typedoc-plugin-missing-exports
[warning] length has multiple declarations with a comment. An arbitrary comment will be used.
[info] The comments for length are declared at:                                            
        ./node_modules/.pnpm/typescript@5.3.2/node_modules/typescript/lib/lib.es5.d.ts:1322
        ./node_modules/.pnpm/typescript@5.3.2/node_modules/typescript/lib/lib.es5.d.ts:516 
[info] The comments for length are declared at:
        ./node_modules/.pnpm/typescript@5.3.2/node_modules/typescript/lib/lib.es5.d.ts:1322
        ./node_modules/.pnpm/typescript@5.3.2/node_modules/typescript/lib/lib.es5.d.ts:516
[info] Documentation generated at ./target/apidocs
```

I don't understand why typedoc is generating docs from this directory given that my configuration file contains:

```
{
	"entryPoints": [
		"src/*.mts",
		"src/extension/*.mts"
	],
	"plugin": [
		"typedoc-plugin-missing-exports"
	],
	"excludePrivate": true,
	"includeVersion": true,
	"treatWarningsAsErrors": true,
	"treatValidationWarningsAsErrors": true
}
```

and `node_modules` does not show up under entryPoints.

Here is my `tsconfig.json` just in case:

```
{
	// Based on https://stackoverflow.com/a/61305579/14731, @tsconfig/node14/tsconfig.json and
	// https://iamturns.com/typescript-babel/
	"compilerOptions": {
		"preserveConstEnums": true,
		"allowSyntheticDefaultImports": true,
		"target": "ES2021",
		"lib": [
			"DOM",
			"ES2021"
		],
		"module": "Node16",
		"moduleResolution": "node16",
		// Fix importing of CommonJS/AMD/UMD modules
		"esModuleInterop": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"verbatimModuleSyntax": true,
		// Required by C8
		"sourceMap": true
	},
	"include": [
		"build.mts",
		"src/**/*.mts",
		"test/**/*.mts"
	],
	"exclude": [
		"node_modules",
		"target",
		"scripts",
		"./.eslintrc.mjs",
		"test/TestGlobalConfiguration.mts"
	],
	"typeRoots": [
		"node_modules/@types"
	],
	"declaration": true
}
```

Any ideas?

**Comment by cowwoc** [comment]
@Gerrit0 How can I find these references?

* Is there a way to output the file + position of each reference?
* Is the reference coming from a `{@link}` tag in the documentation? Or are we talking about links from somewhere else?

I tried diffing the output with `excludeExternals` enabled and disabled but I couldn't figure out where the problem is coming from.

**Comment by cowwoc** [comment]
I figured it out.

If I open index.html there is a checkbox on the top right corner that allows me to enable/disable showing "External" members. By toggling this on and off repeatedly I tracked down the following reference:

```
[N] ArrayVerifier
\-> [N] <internal>
  \-> [I] ConcatArray
  \-> [I] FlatArray
\-> [I] ArrayVerifier

```
I have no idea what `[N]` stands for. I couldn't find a legend nor any sort of documentation to explain what the different icon types mean. I assume that `[I]` stands for interface and `[N]` for module (which in practice contains all the elements inside a single file).

In any case, file `ArrayVerifier.mts` contains interface `ArrayVerifier` and that interface is declared as `interface ArrayVerifier<E> extends ExtensibleObjectVerifier<ArrayVerifier<E>, E[]>`

I have no idea where the module name `<internal>` is coming from. I don't seem to be specifying it anywhere.

In any case, it looks like the fact that `ArrayVerifier` is referencing `E[]` leads to`interface Array<T>` in `typescript@5.3.2/node_modules/typescript/lib/lib.es5.d.ts:1322` and that, in turn, points to a `length` field.

I've got the following questions:

1. Are the icons/symbols documented somewhere?
2. Is there a way to add a legend to the bottom of the page with minimal effort?
3. Where is the name `<internal>` coming from?

You're right that enabling `--excludeExternal` solves the problem (I don't want external references documented anyway).

**Comment by Gerrit0** [comment]
Good questions!

Icons - not documented anywhere besides implicitly in the icons.tsx file in typedoc... and that's just the implementation. The [N] should really be an [M], but typedoc shares namespace/module, probably because it predates ES modules and they just haven't been separated. I should really fix that at some point...

Legend - that should be pretty easy with a plugin, should maybe be a part of the default theme though.

`<internal>` is coming from typedoc-plugin-missing-exports. It's where it puts stuff that is referenced but not exported.

**Comment by cowwoc** [comment]
Thank you for the answers! :)

And yes, I agree that a legend should be part of the default theme.
