### ISSUE TITLE
interface uses @group, class that implements it remains ungrouped

### ISSUE THREAD

**Issue by RobMayer** [TypeStrong/typedoc#2459]
## Search terms

@group interface class inherit implements

## Question

I have an interface, like so

```typescript
export interface IThing<T> {

    /**
     * Does a thing
     * @param {string} key The key to check.
     * @returns {boolean} True if the key exists, false otherwise
     * @category Query
     */
    has(key: string): boolean;
 }
 ```
 
 and a class that implements it
```typescript

export class ActualThing<T> implements IThing<T> {
    //...

    has(key: string): boolean {
        //...
    }
```

at present the methods within the IThing are grouped, but methods within the ActualThing are not, though all the documentation details are. Is there a way to have the class typedoc get grouped according to the interface without having to duplicate all the doc details?

**Comment by Gerrit0** [comment]
Unfortunately not possible with the current implementation. I think both `@group` and `@category` should be inherited, and consider this a bug.
