### ISSUE TITLE
Is there a way to define a custom Kind?

### ISSUE THREAD

**Issue by RobMayer** [TypeStrong/typedoc#2460]
## Question

I'd like to be able to have Components and Hooks distinct from Functions in the sidebar. I already have them set up as a group, but is there any mechanism to have them utilize a different icon and kind title?

**Comment by RobMayer** [comment]
Closing, because I realized this is vastly outside the scope of typedoc and instead an adherence to TSdoc spec.

**Comment by Gerrit0** [comment]
There's an argument that typedoc ought to allow *something* like this, but there isn't currently a mechanism for it, and kinds are closely tied into how typedoc handles different reflections, so it'd have to be some other method

**Comment by RobMayer** [comment]
Yeah, as I'm starting to grok how it works (and forgive me for chiming in before that inflection point) I can see how Kinds is definitely not the place to do that. 
This *could* just be a theming concern? (I haven't dove into that yet).

**Comment by Gerrit0** [comment]
Questions in issues are a good place to learn :) It helps since they show up in search for others in the future too.
