### ISSUE TITLE
How to add @inheritDoc to @ types/lodash

### ISSUE THREAD

**Issue by aosnow** [TypeStrong/typedoc#2464]
## Search terms
inheritDoc, lodash, comment

## Question
The purpose is to add `@category` functionality to third-party libraries (such as lodash) for exporting, and to copy the original comments through `@inheritDoc`. However, it was found that no matter how SymbolReference was written, the goal could not be achieved. How should the parameters of `@inheritDoc` be set for similar requirements mentioned above.

```ts
export { sortBy as lodashSortBy } from "lodash";
```

What can currently be thought of is to rewrite it in the following way, but how should the `@inheritDoc` parameter be written correctly?
```ts
import _ from 'lodash';

/**
 * {@inheritDoc lodash!isArray}
 * @category Array
 */
export const isArray = _.isArray;
```
Always prompt the following error:
```[warning] Failed to find "lodash!" to inherit the comment from in the comment for isArray.isArray```

**Comment by Gerrit0** [comment]
`@inheritDoc` can only be used to inherit comments from other symbols included in the documentation, so this unfortunately isn't really possible.

With this goal, I'd probably approach it with a plugin that added a custom inheriting method which explicitly searched the lodash package.

**Comment by aosnow** [comment]
> `@inheritDoc` can only be used to inherit comments from other symbols included in the documentation, so this unfortunately isn't really possible.
> 
> With this goal, I'd probably approach it with a plugin that added a custom inheriting method which explicitly searched the lodash package.

Thank you. This solution may be more feasible currently.
