### ISSUE TITLE
Hangs indefinitely

### ISSUE THREAD

**Issue by JamesKyburz** [TypeStrong/typedoc#2468]
## Hangs indefinitely

The latest version of typedoc 0.25.5 fails to produce documentation for [sam-expand](https://github.com/starterstack/sam-expand/tree/main)

0.25.4 works fine.

## Expected Behavior
Documentation produced

## Actual Behavior
Without `--logLevel Verbose` nothing is logged to stdout and the process hangs, with verbose we get a lot of `Refusing to recurse when converting type:` errors.

Produce documentation
## Steps to reproduce the bug

```sh
git clone git@github.com:starterstack/sam-expand.git
npm install --ignore-scripts
npm run typedoc # this works
npm i typedoc@latest -D
npm run typedoc # this fails
```

## Environment

-   Typedoc version: 0.25.5
-   TypeScript version: 5.3.3
-   Node.js version: v20.10.0
-   OS: macOS 14.2.1

**Comment by Gerrit0** [comment]
That's strange, looks like it gets hung up during conversion, not during rendering in the spot I thought I might have introduced an infinite loop.. 

Simple fix: `--excludeExternals` -- there's something weird in ajv that's causing this.

**Comment by Gerrit0** [comment]
Caused by https://github.com/TypeStrong/typedoc/commit/a636bd5f4848cccb8b8d1928970c9079f88724a0, apparently we also need to check for `aliasSymbol` on the type before using the origin.
