### ISSUE TITLE
Inherited from/Defined in has no link

### ISSUE THREAD

**Issue by luu-alex** [TypeStrong/typedoc#2471]
Hi there! We have a monorepo and the inherited from/defined in is not populating properly, it points to a lib location instead of an src location. I saw there is already an issue for this https://github.com/TypeStrong/typedoc/issues/2416 but having declaration map on still does not help.
The best solution for me would to either have the `Inherited from` or `defined in` to be removed, is there a way to do this right now or would i need to create a plugin?
Another solution would be to have the Accessors tab to not generate, as this only happens under accessors.
Thanks
Heres the issue in the docs and a screenshot below: 
https://docs.web3js.org/libdocs/Contract#inherited-from
<img width="1019" alt="Screenshot 2024-01-02 at 5 39 33 PM" src="https://github.com/TypeStrong/typedoc/assets/29740020/15700cd3-09e7-432c-a534-d198966ee295">

## Environment

-   Typedoc version:
-   TypeScript version:
-   Node.js version:
-   OS:

**Comment by Gerrit0** [comment]
You can disable the sources section with [--disableSources](https://typedoc.org/options/input/#disablesources)

Inheritance sections would have to be disabled with a plugin

If you're able to set up a minimal reproduction, I can look at why the links aren't showing up -- from a very cursory glance, it looks like you aren't using packages mode, so all the types seem like they would be coming from the initial compilation anyways...
