### ISSUE TITLE
How can I get type parameter as plain text?

### ISSUE THREAD

**Issue by Mizugorou** [TypeStrong/typedoc#2472]
## Search terms

- type parameter as plain text
- destructed json

## Question
I'm trying to use typedoc to capture Typescript class APIs to json to write my own document. And here is my input Typescript API
```typescript
  public myFunction(params: K[]) {
     ...
  }
```
Look at type parameter. My expect result is just `K[]` but get confused structured json. Like below.
```
// json result
{
  "id": 12,
  "name": "keys",
  "variant": "param",
  "type": {
      "type": "array",
      "elementType": {
	      "type": "reference",
	      "target": -1,
	      "name": "K",
	      "refersToTypeParameter": true
      }
    }
}
```
Could you advise me to get only plain content of type parameter?

FYI: Sorry if my English skill isn't smoothy.

**Comment by Gerrit0** [comment]
For this you'd have to write a custom plugin to overwrite the type with a stringified version, here's an example of how to do that for parameters.

```console
$ npx typedoc src/gh2472.ts --plugin ./path/to/plugin.mjs
```

```ts
// @ts-check
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    /** @type {Map<td.ParameterReflection, td.SomeType>} */
    const replacements = new Map();

    app.converter.on(td.Converter.EVENT_CREATE_PARAMETER, replaceTypesWithStrings);

    app.converter.on(td.Converter.EVENT_RESOLVE_BEGIN, () => {
        for (const [param, type] of replacements) {
            param.type = type;
        }
        replacements.clear();
    });

    /**
     * @param {td.Context} context
     * @param {td.ParameterReflection} reflection
     * @param {td.TypeScript.Node?} node
     */
    function replaceTypesWithStrings(context, reflection, node) {
        const symbol = context.project.getSymbolFromReflection(reflection);
        if (!symbol) return;

        const type = context.checker.typeToString(context.checker.getTypeOfSymbol(symbol));
        replacements.set(reflection, new td.UnknownType(type));
    }
}
```

**Comment by Mizugorou** [comment]
Great one! Look like it need to do custom callback to each places.
Could I ask more? I want this results apply to all places such as 'return', not just parameter. Could you another guide me? Or have any more detail document for this?

```javascript
  // for example. I want to get results as K[] and T[]
  public myFunction(params: K[]): T[] {
     ...
     return 
  }
```

**Comment by Gerrit0** [comment]
You'll have to add listeners for the other `CREATE` events on the converter, and replace the type field on those too: https://typedoc.org/api/classes/Converter.html#EVENT_CREATE_DECLARATION is the big one, but there's also one for parameters and signatures
