### ISSUE TITLE
How to get typeParameters in >v0.25.5

### ISSUE THREAD

**Issue by nborko** [TypeStrong/typedoc#2474]
## Search terms

Since v0.25.5, the typeParameters of a DeclarationReference for a generic type is empty.

## Question

In v0.25.5 and above, when using a TypeVisitor, processing a reference for a generic type has an empty typeParameters list except for the most simple cases. What is the new API for processing typeParameters? I don't see anything in the Changelog mentioning this breaking change.

Thanks!

**Comment by nborko** [comment]
Upon further inspection, it doesn't appear that the type hierarchy is correct at all. For example, I have a type that refers to a generic type with an enum argument, and I end up with each of the enum members as a DeclarationReflection instead of the enumeration itself.

Unfortunately I have a somewhat complicated TypeVisitor, and I honestly don't know enough about the inner workings of the typedoc model to provide a minimal reproduction.

**Comment by Gerrit0** [comment]
0.25.5 includes an attempted fix for #2451, which has caused several strange issues with the type converter, it sounds to me like there's another issue with it
