### ISSUE TITLE
Inner types in a function-namespace are not documented

### ISSUE THREAD

**Issue by fasttime** [TypeStrong/typedoc#2476]
## Search terms

function, namespace

## Expected Behavior

I would expect TypeDoc v0.25.5/6 to behave like v0.25.4.

In the following code, both the function-namespace (`test`) and the inner type (`test.Options`) should be documented.

```ts
/**
 * Test function
 *
 * @param options Options for the function.
 */
declare function test(options?: test.Options): void;

declare namespace test
{
    /** Test options */
    interface Options
    {
        a: string;
        b: number;
    }
}

export { test };
```

## Actual Behavior

Only the function-namespace (`test`) is documented.

On the command line I see this warning:

```console
[warning] test.Options, defined in ./index.ts, is referenced by test.test.options but not included in the documentation.
```

I can work around this problem by adding a second `export` keyword directly on the namespace declaration (see below), but that should not be necessary.

```ts
/**
 * Test function
 *
 * @param options Options for the function.
 */
declare function test(options?: test.Options): void;

export declare namespace test // redundant export
{
    /** Test options */
    interface Options
    {
        a: string;
        b: number;
    }
}

export { test };
```

## Steps to reproduce the bug

Repro: https://stackblitz.com/edit/stackblitz-starters-qqddz8

## Environment

-   Typedoc version: 0.25.5 and 0.25.6
-   TypeScript version: 5.3.3
-   Node.js version: 20.10
-   OS: -

**Comment by Gerrit0** [comment]
Well, that's annoying, apparently the symbol flags for namespaces don't mean what I thought they did.. this case shouldn't be caught by the change for #2461.

**Comment by fasttime** [comment]
Thanks! The documentation for function-namespaces is working for me in v0.25.7. Now I'm experiencing another seemingly related problem. I'm going to open a separate issue.
