### ISSUE TITLE
marge same name's var and type as class?

### ISSUE THREAD

**Issue by steve02081504** [TypeStrong/typedoc#2479]
## Search Terms

marge as class

## Problem

For some ts syntax limitation I have to express a class with a variable and a type.
https://ukatech.github.io/jsstp-lib/doc/EN/types/ghost_events_queryer_t.html
https://ukatech.github.io/jsstp-lib/doc/EN/variables/ghost_events_queryer_t-1.html
Is it possible to merge them into a class in the generated document for easy reading?

## Suggested Solution

idk

**Comment by Gerrit0** [comment]
Hmm.. it seems somewhat reasonable to me to look for an `@class` in comments for variables, and interpret that type as a class.

**Comment by steve02081504** [comment]
> Hmm.. it seems somewhat reasonable to me to look for an `@class` in comments for variables, and interpret that type as a class.

I just thought it would be nice to have some way to merge the following pages into one - considering that they would have been just defining different parts of the same class
https://ukatech.github.io/jsstp-lib/doc/EN/types/ghost_events_queryer_t.html
https://ukatech.github.io/jsstp-lib/doc/EN/variables/ghost_events_queryer_t-1.html
https://ukatech.github.io/jsstp-lib/doc/EN/classes/_internal_.ghost_events_queryer_t_class_impl.html
https://ukatech.github.io/jsstp-lib/doc/EN/types/_internal_.ghost_events_queryer_t_call_signature.html
https://ukatech.github.io/jsstp-lib/doc/EN/types/_internal_.ghost_events_queryer_t_constructor.html
Of course, typedoc doesn't have to do this, it's just that ts itself doesn't allow types with call signatures to be defined, so I had to split the class this way.
If this is really difficult to implement, you can close this issue, I completely understand!
