### ISSUE TITLE
Add option to generate sitemap

### ISSUE THREAD

**Issue by PythonCoderAS** [TypeStrong/typedoc#2480]
## Search Terms

sitemap

## Problem

TypeDoc has no way to generate a sitemap.

## Suggested Solution

I wonder if TypeDoc could generate a sitemap for the generated output. It would probably require specifying the base path.

**Comment by karmaniverous** [comment]
I just published a sitemap plugin. Works great! https://github.com/karmaniverous/typedoc-plugin-sitemap
