### ISSUE TITLE
Sources are set for the ProjectReflection (maybe a feature and not a bug?)

### ISSUE THREAD

**Issue by krisztianb** [TypeStrong/typedoc#2481]
## Search terms

sources, SourceReference, SourcePlugin

## Expected Behavior

According to the documentation of TypeDoc only the following reflection types have a `sources` property:

* https://typedoc.org/api/classes/Models.DeclarationReflection.html
* https://typedoc.org/api/classes/Models.ReferenceReflection.html
* https://typedoc.org/api/classes/Models.SignatureReflection.html

## Actual Behavior

Sources array is set on the `ProjectReflection` instance.

I think the `sources` are added in the `onDeclaration` event of the `SourcePlugin` which is also called for the `ProjectReflection` and not just `DeclerationReflection` instances as the event handler is typed.

However I'm not sure if this behavior is actually an error or if the documentation is missing the property. In our scenario having the `sources` property on the `ProjectReflection` is actually wanted as it gives us access to the file where the `@packageDocumentation` tag is used - see example below.

## Steps to reproduce the bug

Run TypeDoc with the following options:

```js
/** @type { import('typedoc').TypeDocOptionMap */
module.exports = {
    entryPointStrategy: "expand",
    entryPoints: ["input/a.ts"],
    out: "output",
    tsconfig: "tsconfig.json"
};
```

Using the following input file `input/a.ts`:

```ts
/**
 * @packageDocumentation
 * README.MD
 */
export function a(): void {
  // empty
}
```

## Environment

-   Typedoc version: 0.25.7
-   TypeScript version: 5.3.3
-   Node.js version: 18.16.0
-   OS: Windows 10

**Comment by Gerrit0** [comment]
This is a bug - carryover from when comments were discovered by the create declaration event.

I fixed this on the beta branch a few months ago, just haven't finished the features I want for the next minor release.

Relying on the `sources` property to determine where a module is declared is not reliable. The user can pass `--disableSources` to remove that property, and the sources property also depends on the module having a symbol, while "global modules" (files that aren't modules and define a bunch of symbols in the global scope) do not have a symbol, so won't have a sources property.

**Comment by krisztianb** [comment]
Understood. Thanks for the explanation.
