### ISSUE TITLE
How to customize the footer?

### ISSUE THREAD

**Issue by tisonkun** [TypeStrong/typedoc#2482]
## Search Terms

customize footer

## Problem

In my scenarios I may need to customize the footer to include some trademark attributions like:

> DataStax, is a registered trademark of DataStax, Inc.. Apache, Apache Cassandra, Cassandra, Apache Pulsar, and Pulsar are either registered trademarks or trademarks of the Apache Software Foundation.

Currently, the footer is always "Generated using TypeDoc".

## Suggested Solution

I have no idea.

**Comment by Gerrit0** [comment]
Currently requires a custom theme which overrides the `footer` member on the context class: https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md
