### ISSUE TITLE
Destructured parameter in interface causes "not used" warning

### ISSUE THREAD

**Issue by pvditto** [TypeStrong/typedoc#2483]
## Search terms

interface `@param` destructured not used

## Expected Behavior

When I define an interface that has a method using a destructured parameter and individual fields are documented using `@param`, I expect no warning about the parameter not being used as long as it is used in implementations of the interface.

## Actual Behavior

Typedoc emits a warning `[warning] The signature TestInterface.method has an @param with name "options.field", which was not used.`

## Steps to reproduce the bug

- create `index.ts` with content below
- run `npx typedoc@0.25.7 index.ts`

```ts
type Options = {
    field: string
}

interface TestInterface {
    /**
     * @param options.field test field
     */
    method(options: Options): void
}

class TestClass implements TestInterface {
    method(options: Options) {
        console.log(options.field)
    }
}
```

## Environment

-   Typedoc version: 0.25.7
-   TypeScript version: -
-   Node.js version: 20.10.0
-   OS: -

**Comment by Gerrit0** [comment]
This is working as expected -- that description isn't used and won't be present in your documentation. There's an open issue, #2147, for changing that, but it needs design work.

**Comment by pvditto** [comment]
Oh, thank you for the clarification Gerrit. I'll close this and follow the linked issue instead.
