### ISSUE TITLE
Help with monorepo: Cannot find module

### ISSUE THREAD

**Issue by pawamoy** [TypeStrong/typedoc#2484]
## Search terms

monorepo packages cannot find module

## Question

I'm trying to generate JSON docs for the following monorepo: https://github.com/squidfunk/mono/.

Here's what I do:

```bash
git clone https://github.com/squidfunk/mono/ --depth=1
cd mono

npm install
npm install typedoc

echo '{"$schema": "https://typedoc.org/schema.json", "includeVersion": true}' > typedoc.base.json
for package in packages/*; do
  echo '{"extends": ["../../typedoc.base.json"], "entryPoints": ["src"], "entryPointStrategy": "expand"}' > $package/typedoc.json
done

npx typedoc --json docs.json --entryPointStrategy packages 'packages/*'
```

And the output is:

```console
[info] Converting project at ./packages/mono-chance
[info] Converting project at ./packages/mono-changelog
[warning] ChangelogOptions, defined in ./packages/mono-changelog/src/changelog/_/index.ts, is referenced by export=.export=.__type.conventionalChangelog but not included in the documentation.
[warning] ParserOptions, defined in ./packages/mono-changelog/src/changelog/parser/index.ts, is referenced by export=.export=.__type.parserOpts but not included in the documentation.
[warning] RecommendedBumpOptions, defined in ./packages/mono-changelog/src/commit/bump/index.ts, is referenced by export=.export=.__type.recommendedBumpOpts but not included in the documentation.
[warning] WriterOptions, defined in ./packages/mono-changelog/src/changelog/writer/index.ts, is referenced by export=.export=.__type.writerOpts but not included in the documentation.
[info] Converting project at ./packages/mono-commit-convention
[info] Converting project at ./packages/mono-commit-parser
[info] Converting project at ./packages/mono-esbuild
packages/mono-esbuild/src/build/plugin/optimize/index.ts:26:29 - error TS2307: Cannot find module '@squidfunk/mono-optimize' or its corresponding type declarations.

26 import { optimizePNG } from "@squidfunk/mono-optimize"
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/mono-esbuild/src/build/plugin/serve/index.ts:28:23 - error TS2307: Cannot find module '@squidfunk/mono-serve' or its corresponding type declarations.

28 import { serve } from "@squidfunk/mono-serve"
                         ~~~~~~~~~~~~~~~~~~~~~~~

packages/mono-esbuild/src/build/plugin/web/index.ts:28:30 - error TS2307: Cannot find module '@squidfunk/mono-optimize' or its corresponding type declarations.

28 import { optimizeHTML } from "@squidfunk/mono-optimize"
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~

[info] Converting project at ./packages/mono-jasmine
packages/mono-jasmine/src/_/index.ts:29:23 - error TS2307: Cannot find module '@squidfunk/mono-serve' or its corresponding type declarations.

29 import { watch } from "@squidfunk/mono-serve"
                         ~~~~~~~~~~~~~~~~~~~~~~~

[info] Converting project at ./packages/mono-karma
[warning] Options, defined in ./packages/mono-karma/src/execute/index.ts, is referenced by execute.execute.options but not included in the documentation.
[info] Converting project at ./packages/mono-optimize
[warning] Options, defined in ./packages/mono-optimize/src/optimize/image/index.ts, is referenced by optimizePNG.optimizePNG.options but not included in the documentation.
[info] Converting project at ./packages/mono-resolve
[info] Converting project at ./packages/mono-serve
[warning] Options, defined in ./packages/mono-serve/src/serve/_/index.ts, is referenced by serve.serve.options but not included in the documentation.
[info] Converting project at ./packages/mono-transform
[info] Merging converted projects
[error] Failed to convert one or more packages, result will not be merged together.
```

As you can see, TypeDoc fails to convert both the `mono-esbuild` and `mono-jasmine` packages, because they import things from other packages (`mono-optimize` and `mono-serve`).

How to solve this?

I tried adding "references" in the root `tsconfig.json` but it didn't change anything.

I'm a completely new to TypeScript and TypeDoc, so would appreciate any guidance here :bow:

**Comment by Gerrit0** [comment]
TypeDoc is failing to compile those packages because their dependencies haven't been built yet, and TypeDoc requires that all dependencies can be resolved at build time.

In this case, it looks like you can get everything to build by running:
```bash
npm run build --workspaces --if-present
```

several times. Once all the invocations of `tsc` in that command complete successfully, then your typedoc run will work. 

(FWIW, this monorepo isn't ideally set up, you should really be able to compile with TS's build mode once so you don't have to compile multiple times. [typedoc-packages-example](https://github.com/Gerrit0/typedoc-packages-example)) is how I'd set up a monorepo with TS)

**Comment by pawamoy** [comment]
Thank you very much for your help, I will try that and report back. I'm sure this will solve my issue so feel free to close right now, I'll do it later otherwise 😊

**Comment by typhonrt** [comment]
Hiya @pawamoy. I have recently released a very powerful CLI front-end for TypeDoc that has easy setup to generate docs for mono-repos called [typedoc-pkg](https://www.npmjs.com/package/@typhonjs-typedoc/typedoc-pkg). I have integrated it into a temporary fork of your mono-repo effort here: https://github.com/typhonjs-typedoc/mono

Super easy to generate docs across the whole set of packages and it correctly sets the module names to the export / package.json names. 

I had to add a `types` field to all of the package.json files. `typedoc-pkg` analyzes `package.json` to pick up the types by default. Then I simply added a single NPM script to run `typedoc-pkg` which you can see [here](https://github.com/typhonjs-typedoc/mono/blob/master/package.json#L27) 

Even better it's super simple to host the docs on GitHub, so check them out here:
https://typhonjs-typedoc.github.io/mono/

Take a look at the 4 commits I made and if you'd like I'd be glad to submit a PR.

**Comment by pawamoy** [comment]
Hey @typhonrt, that's super interesting, thanks for sharing! `typedoc-pkg` looks indeed easy to use. Now, can it generate JSON instead of HTML docs? I need JSON data because I render the HTML part myself, in Python :slightly_smiling_face: And no, indeed, I'm not the author of this project, I'm just using it to test my code!

**Comment by pawamoy** [comment]
@Gerrit0 I was indeed able to generate JSON docs after building each package. From the author, the actual command was `npx lerna run build` :smile:
