### ISSUE TITLE
Declaration reference with a meaning produces incorrect link text

### ISSUE THREAD

**Issue by lawrence-forooghian** [TypeStrong/typedoc#2485]
## Search terms

declaration reference, meaning, incorrect link text

## Expected Behavior

Consider a `@link` to a declaration reference with a [meaning](https://typedoc.org/guides/declaration-references/#meaning), e.g. the `{@link foo:var}` below.

```
/**
 * A thing that you should know about `foo` is that it’s called `foo`.
 */
export const foo = 123;

/**
 * Here I’m writing about `bar` but I really want to tell you about {@link foo:var}.
 */
export const bar = 456;
```

I expect it to produce an HTML `<a>` tag with link text `foo`.

## Actual Behavior

Later versions of Typedoc produce an HTML link tag whose text is the declaration reference’s meaning (e.g. `:var`).

## Steps to reproduce the bug

See https://github.com/TypeStrong/typedoc-repros/pull/37.

When using TypeDoc 0.25.7, the `{@link foo:var}` generates the following HTML:

```html
Here I’m writing about <code>bar</code> but I really want to tell you about <a href="foo.html" class="tsd-kind-variable">:var</a>.
```

When using TypeDoc 0.23.8 (with TypeScript 4.9.5) it generates the following HTML:

```html
Here I’m writing about <code>bar</code> but I really want to tell you about <a href="foo.html">foo</a>.
```

## Environment

-   Typedoc version: 0.25.7
-   TypeScript version: 5.3.3
-   Node.js version: 16
-   OS: Ubuntu

**Comment by Gerrit0** [comment]
This is working as intended, TypeDoc 0.24 added the [`--useTsLinkResolution`](https://typedoc.org/options/comments/#usetslinkresolution) option, which is on by default. When that option is set, TypeDoc will rely on TypeScript's comment parsing for both resolving links in comments and determining what should be displayed in the rendered HTML. If you turn that option off, links will be resolved like they were in 0.23.

This was added so that TypeDoc's output more closely matches what VSCode and other editors using TypeScript's language service to render text will display:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/de904e8a-0860-4a92-a3a9-3d9b9e6504d4)

**Comment by lawrence-forooghian** [comment]
Thanks your reply, @Gerrit0. Do you happen to have any information on how TypeScript performs this resolution? I'm a bit confused about why some of the functionality described in TypeDoc’s [declaration references documentation](https://typedoc.org/guides/declaration-references/#declaration-references) continues to work with `useTsLinkResolution` enabled. For example, specifying a module source, or linking to a declaration using its `{@label}` tag. I'd also like to understand if there's a replacement syntax for `:keyword` that I can use to satisfy the use case described in this issue.

**Comment by Gerrit0** [comment]
I believe the first paragraph on that page answers the first question:

> Note: If [--useTsLinkResolution](https://typedoc.org/options/comments/#usetslinkresolution) is turned on (the default) this page likely does not apply for your links. Declaration references are used only if that option is off **or TypeScript fails to resolve a link.**

TypeScript doesn't parse declaration references, so links which don't start with references to names in the current scope will be resolved with declaration references.

Unfortunately, this means that if you want to link to a specific kind, and leave that option on, you need to construct a link which TypeScript won't parse. The easiest way to do this is probably to make it a fully qualified link like `{@link !foo:var}` or `{@link module!foo:var}`

TypeScript doesn't have a way to link to a specific variable type for a symbol as its links are intended for use in an editor where links to an ambiguous symbol will show multiple results in a peek window. Personally, I avoid exporting variables which contain multiple kinds of values to avoid this issue.

---

How TypeScript performs resolution is *very roughly* based on [jsdoc's namepaths](https://jsdoc.app/about-namepaths)... but it wants the variable being linked to to be present in the file's current scope, it doesn't search globally, so this actually means that TypeScript just looks for names in the current scope for link resolution.

**Comment by lawrence-forooghian** [comment]
Thank you very much @Gerrit0! I'll close this issue.
