### ISSUE TITLE
Issue with the class hierarchy where the base class is from the web platform API

### ISSUE THREAD

**Issue by DmitrySharabin** [TypeStrong/typedoc#2486]
## Search terms

Class Hierarchy

## Question

First of all, thank you so much for this wonderful library! It helps us _a lot_ in documenting the API of [our library](https://madata.dev/). ❤️

We have a class in the library that extends the `EventTarget` class from the web platform API. That means that `EventTarget` is _not defined_ in our library.

```js
export default class Backend extends EventTarget {...}
```

<img width="735" alt="SCR-20240122-svky" src="https://github.com/TypeStrong/typedoc/assets/9166277/0196ff05-3e96-455d-94b9-38b9a475f429">

When I try to view the entire class hierarchy, I can't see any expected (backend) classes.

<img width="820" alt="SCR-20240122-svqh" src="https://github.com/TypeStrong/typedoc/assets/9166277/71b3b408-f2fc-4b99-904f-88e457f14b0f">

However, if I remove the `EventTarget` class, I can see the correct class hierarchy.

<img width="896" alt="SCR-20240122-svuu" src="https://github.com/TypeStrong/typedoc/assets/9166277/923ebaf8-a1b2-41de-8db1-b8c2f509391c">

I can't eliminate `EventTarget` for obvious reasons to get the desired class hierarchy. Is there a way to ask TypeDoc to ignore the classes defined in other places and generate the correct class hierarchy, e.g., by stopping on the classes it doesn't know? Or is there a way to “teach” TypeDoc to handle the `EventTarget` class (or any platform-specific class) correctly? Or is there anything I'm doing wrong?

If it might help, our project is written in vanilla JS. And here is our `typedoc.json` file.

```json
{
	"name": "Madata API",
	"compilerOptions": {
		"allowJs": true,
		"skipLibCheck": true,
	},
	"plugin": [
		"typedoc-plugin-merge-modules",
	],
	"mergeModulesRenameDefaults": true,
	"mergeModulesMergeMode": "module",
	"entryPoints": [
		"src/*.js",
		"backends/index.js",
		"formats/index.js",
	],
	"exclude": [
		"src/node-shims.js",
	],
	"excludeReferences": true,
	"navigation": {
		"includeCategories": true,
		"includeFolders": false,
	},
	"readme": "API.md",
	"out": "api",
	"customCss": "api.css",
}
```

I would be grateful for any help!

Regards,
Dmitry

**Comment by Gerrit0** [comment]
That's a bug, the "full hierarchy" page is supposed to ignore base classes in your docs which don't exist so those classes still appear

**Comment by DmitrySharabin** [comment]
Thank you, @Gerrit0, for clearing this out. Eagerly waiting for the fix. 🙏

**Comment by DmitrySharabin** [comment]
@Gerrit0 I'm sorry, but it looks like the issue isn't fixed yet. Moreover, I see `any` instead of the previously correct base class (`EventTarget`). And the correct hierarchy isn't built.

Before
---
<img width="735" alt="SCR-20240122-svky" src="https://github.com/TypeStrong/typedoc/assets/9166277/0196ff05-3e96-455d-94b9-38b9a475f429">

After
---
<img width="678" alt="SCR-20240210-qkbr" src="https://github.com/TypeStrong/typedoc/assets/9166277/3a91d4db-97ca-4b54-9b7d-6279df31b176">

Would you mind re-opening this issue, please?

**Comment by Gerrit0** [comment]
Going to need a reproduction, I can't infer where the problem is from that.

**Comment by DmitrySharabin** [comment]
> Going to need a reproduction, I can't infer where the problem is from that.

I would love to do it. Do you have any instructions on how to build a reproduction so that it's helpful? Will it be enough if I provide you a link on StackBlitz or something similar reproducing the bug?

**Comment by Gerrit0** [comment]
StackBlitz works, a repo I can clone and just `npm i` then `npm run docs` is great too

**Comment by DmitrySharabin** [comment]
I rechecked our docs and found out why the hierarchy wasn't correct. The problem was on our side — we had the outdated `package-lock.json` file. And our docs were generated with the old version of TypeDoc. Sorry about that!

Unfortunately, there is an issue with the wrong name of the base (not included in the documentation) class — now, it's called `any`.

<img width="400" alt="SCR-20240210-qkbr" src="https://github.com/TypeStrong/typedoc/assets/9166277/3a91d4db-97ca-4b54-9b7d-6279df31b176">

It would be nice to have this class's real name taken from the definition.

I hope this repo with the minimal reproduction helps: https://github.com/DmitrySharabin/typedoc-hierarchy-reproduction.

> a repo I can clone and just `npm i` then `npm run docs` is great too

Did it this 👆 way. 😄

**Comment by Gerrit0** [comment]
TypeDoc uses the type in order to figure out what `EventTarget` is. In a TS file `extends EventTarget` would be an error, because EventTarget isn't defined by either `npm install @types/node` or by including the DOM in your lib:

```diff
diff --git a/tsconfig.json b/tsconfig.json
index 2ae115a..0577b11 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -2,7 +2,7 @@
        "compilerOptions": {
                "allowJs": true,
                "skipLibCheck": true,
-               "lib": ["ESNext"],
+               "lib": ["ESNext", "DOM"],
                "outDir": "./dist"
        },
        "include": ["src"],
```

Undefined types appearing as "any" in the docs is a design limitation. I've considered ways to avoid it, but making those changes require hacks that I really don't want to introduce.

**Comment by DmitrySharabin** [comment]
> TypeDoc uses the type in order to figure out what `EventTarget` is. In a TS file `extends EventTarget` would be an error, because EventTarget isn't defined by either `npm install @types/node` or by including the DOM in your lib:

Fair.

> "lib": ["ESNext", "DOM"]

Thank you so much, @Gerrit0! The change you proposed fixes the issue I face. 🥳
