### ISSUE TITLE
Include documentation for non-exported `type`

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2488]
## Search terms

type, export, include

## Question

I have a type parameter that is not exported, which is referred to in an exported function like this. It should appear in the documentation, but it should not be exported.

```ts
type Color = 'red' | 'orange' | 'yellow';

export function favoriteColor(color: Color): void {
    console.log('Your favorite color is ' + color);
}
```

When I run `typedoc` I get the following warning.

```
[warning] Color, defined in ./src/tst.ts, is referenced by tst.favoriteColor.favoriteColor.color but not included in the documentation.
```

And as expected, `Color` is not documented (it is not a clickable link.)

![image](https://github.com/TypeStrong/typedoc/assets/24358775/f7708aab-b4ce-4d86-acd3-30a9bf1b4eea)

1. Is it possible to achieve this without exporting `Color`?
2. Are there any `@tags` I can use to say "hey Typedoc, document this!"?
3. If not, what are the best practices for this?

Thanks!

**Comment by nicfv** [comment]
Update: I did find this plugin, but it feels like there should be a way to achieve this directly in Typedoc without plugins.

https://github.com/tomchen/typedoc-plugin-not-exported

**Comment by Gerrit0** [comment]
1. Yes, via plugins.
2. No, in addition to the plugin you found, there is [typedoc-plugin-missing-exports](https://www.npmjs.com/package/typedoc-plugin-missing-exports), which doesn't require a tag, and will automatically include anything referenced.
3. The best practice for this is to export the type, potentially via a `package/internals` entry point to indicate it isn't part of semver if it's truly an implementation detail that's exported for completeness, but not intended to be stable.

The type is already accessible to your users. By not exporting it, you just make it more annoying for a user of your library to reference it:

```ts
type Color = Parameters<typeof import("lib")["favoriteColor"]>[0];
```

**Comment by nicfv** [comment]
Thank you for your answers. I didn't know that users still have access to the type via parameters anyway, so you're probably right that it should just be exported. I was actually doing this anyway for the documentation. So I guess I learned a good coding practice from using TypeDoc. Who knew?
