### ISSUE TITLE
Generate links to the source codes on GitHub Enterprise

### ISSUE THREAD

**Issue by kimamula** [TypeStrong/typedoc#249]
Currently TypeDoc can generate links to the source codes on GitHub only if they are on github.com.

https://github.com/TypeStrong/typedoc/blob/v0.4.4/src/lib/converter/plugins/GitHubPlugin.ts#L56
https://github.com/TypeStrong/typedoc/blob/v0.4.4/src/lib/converter/plugins/GitHubPlugin.ts#L109

It would be great if TypeDoc can also generate links to the source codes on GitHub Enterprise.

**Comment by aciccarello** [comment]
Would be covered by #129

**Comment by gdelmas** [comment]
i had the same issue and created a plugin [typedoc-plugin-sourcefile-url](https://github.com/gdelmas/typedoc-plugin-sourcefile-url)

the plugin allows to create custom URLs to source code files.

it can be simply installed with:

    npm install --save-dev typedoc-plugin-sourcefile-url
