### ISSUE TITLE
Grab entry points off of package.json/tsconfig.json

### ISSUE THREAD

**Issue by johnameyer** [TypeStrong/typedoc#2493]
## Search Terms

entryPointStrategy, packages, legacy-packages, monorepo, entrypoint, entry point

## Problem

When using monorepos - TypeDoc now requires configuration files to be present in each directory to specify the entry points.

This was not previously the behavior with the legacy packages variant that was deprecated and removed.

Specifying a configuration file in every package just to extend the root and specify entrypoints is additional configuration noise that would ideally not be included.

Ref: https://github.com/Gerrit0/typedoc-packages-example

## Suggested Solution

If a configuration file is not specified in a package, use the entrypoints from package.json or tsconfig.json instead.

**Comment by Gerrit0** [comment]
This is #1937
