### ISSUE TITLE
@group descriptions

### ISSUE THREAD

**Issue by paularmstrong** [TypeStrong/typedoc#2494]
## Search Terms

`@group`, `@category`

## Problem

When using `@group` a heading is generated, but there's no way to provide more context for the grouping. Just a heading doesn't give much to go on as to what the heading means.

## Suggested Solution

Ideally, a block comment that is unrelated to any export could include the `@group` tag and any summary information would be included in the output.

```
/**
 * @group Title… 
 * Summary
 */
```

**Comment by Gerrit0** [comment]
>  unrelated to any export

Really don't like that. The rules for what comments are used are already too complicated. I'd rather require that this be put on the group-containing reflection, and use a different tag like `@groupDescription`, should also support it for `@categoryDescription`

Seems like a useful feature :+1:

**Comment by paularmstrong** [comment]
`@groupDescription` sounds good to me. I don't have any strong preferences other than I would really like to provide more context in the generated documentation 😄

**Comment by paularmstrong** [comment]
Thank you @Gerrit0!
