### ISSUE TITLE
How do I "place a child in a group"?

### ISSUE THREAD

**Issue by fhaag** [TypeStrong/typedoc#2501]
## Search terms

groupDescription, group, output, warning

## Question

[Release 0.25.8](https://github.com/TypeStrong/typedoc/releases/tag/v0.25.8) adds support for a [`@groupDescription` tag](https://typedoc.org/tags/groupDescription/). As far as I understand from the release notes and the docs, it is meant to provide a description on a group that topics can be grouped into by means of the `@group` tag.

My project already contains various grouped topics. That is, on several types, I have added `@group` tag with the same group title, and the generated docs nicely group them in a separate foldable group of the specified title, apart from Classes/Interfaces/... .

Now, I have added a `@groupDescription` tag with the very same group title, and some lines of a description for the group. However, the description is not included in any of the generated output files, and Typedoc actually reports:
```
[warning] Comment for <my type X> includes @groupDescription for "<my group title>", but no child is placed in that group.
```
I have tried this with two different types `X`, once one that belongs to the group (i.e. having a `@group` tag with the same title itself), and another one that is unrelated (the module descriptor class in the same module), as the latter is what is implied by the docs. The result is the same in both cases.

**How do I place children in the group other than by adding the `@group` tag to them?**

**Comment by Gerrit0** [comment]
Adding `@group` to the child is the correct way to add children to the group. In this case, it sounds like you're adding `@group` to module exports, so you'd need to put the `@groupDescription` tag on the module itself, for example:

```ts
/**
 * @module
 * @groupDescription X
 * X desc
 */

/**
 * @group X
 */
export function x() {}
```
