### ISSUE TITLE
feat: sort unions

### ISSUE THREAD

**Issue by Zamiell** [TypeStrong/typedoc#2502]
## Expected Behavior

Typedoc produces a webpage like this:

![image](https://github.com/TypeStrong/typedoc/assets/5511220/de53dc1b-3169-4b82-9727-ff513fbaeb57)

This union  is bugged because it is in the wrong order (i.e. not sorted). This is because TypeDoc is just mirroring how TypeScript internally prints out the union.

Nathan Sanders explains that TypeScript does this internally because it builds the union data structure based on when the original types are first used. In other words, the type of `3` gets used first in the stdlib before the type of `1`, so then are printed out in the order that the types are first added to the set.

Nathan also suggests that in principle this could be fixed in the TypeScript repo upstream by adding all of the types `type A = 1; type B = 2;` and so on in the first file of the stdlib so that they all get created in memory in order.

But for now, I propose that TypeDoc automatically sorts unions of numbers.

## Steps to reproduce

Something like:

```ts
type Test = [1, 2, 3][number]
//   ^? - type Test = 1 | 2 | 3
```

(it works on twoslash but not on the playground because they use different stdlibs)

**Comment by Gerrit0** [comment]
More design needed before this can be implemented.

What happens if it isn't just numbers?
   - Strings (how are template literals sorted?)
   - Symbols
   - Nested objects
   - Tuples
   - Intersections
   - Functions

**Comment by Zamiell** [comment]
- to start with, i would only sort number literals, as it would be the least arbitrary/contentious sorting. (i think doing baby steps and iterating later is good!)
- i don't have strong opinions about the sorting algorithm for the other things you specified.
