### ISSUE TITLE
Is there a JavaScript API?

### ISSUE THREAD

**Issue by NullVoxPopuli** [TypeStrong/typedoc#2504]
## Search terms

javascript API

## Question

is there a javascript API, I was looking through the docs / prior issues, and I couldn't find anything.

thanks!

**Comment by RobbieTheWagner** [comment]
@NullVoxPopuli and I have been discussing this quite a bit. I would also love clarity on the public API. We had an old project manually invoking typedoc like this: https://github.com/ember-learn/ember-cli-addon-docs-typedoc/blob/master/lib/typedoc-worker.js#L43-L48

All the new APIs seem to require `entryPoints` though and we didn't have `entryPoints` before. I would love some clarity on what to do to make this work again ❤️

**Comment by NullVoxPopuli** [comment]
^^ also, my use case is that I'd like to abstract away more of the typedoc setup from my users (me),
I've spit-balled something like this as a wishful API, (tho, using entrypoints)

```
import { createUnplugin } from 'unplugin';

/**
 * Generates JSON from typedoc given a target path.
 *
 * May be used multiple times to generate multiple docs
 * for multiple libraries
 *
 * example:
 * ```js
 * import { typedoc, helpers } from 'kolay';
 *
 * typedoc.webpack({
 *   outFile: '/api-docs/ember-primitives.json
 *   entryPoints: [
 *     // utility of mine that would path.join(package root, + declarations + '**/*')
 *     helpers.pkgGlob(
 *       require.resolve('ember-primitives'),
 *        'declarations'
 *      )
 *   ]
 * })
 * ```
 */
export const typedoc = createUnplugin(
  (
    /**
     * options may contain a 'outFile' option
     */
    options
  ) => {
    let name = 'kolay::typedoc';

    return {
      name,
      /**
       * 1. generate typedoc config
       * 2. given the
       */
      async buildEnd() {
        const tsconfig = {
          extends: "@tsconfig/ember/tsconfig.json",
          compilerOptions: {
            baseUrl: './'
          },
          typedocOptions: {
            entryPoints: options.entryPoints,
          },
          include: options.entryPoints,
        };

        ///////////////////////////////////////////////////////
        // this is the API that I hope could exist
        ///////////////////////////////////////////////////////
        // invoke typedoc
        ///////////////////////////////////////////////////////
        await buildTypedoc({
          cwd: process.cwd(),
          tsconfig,
          compilerOptions: {
            noEmitOnError: false,
          },
          json: options.outFile,
          pretty: false,
          excludeInternal: false,
          skipErrorChecking: true,
          // https://github.com/tomchen/typedoc-plugin-not-exported
          plugin: ['@zameill/typedoc-plugin-not-exported'],
        });
      },
    };
  }
);
```

**Comment by Gerrit0** [comment]
That API mostly exists - https://typedoc.org/guides/installation/#node-module

It does not accept a tsconfig object, and I have no plans to add that, but you _could_ use TypeScript's API to read the tsconfig you're extending from, or point TypeDoc at the project's real tsconfig, then use [`app.options.setCompilerOptions`](https://typedoc.org/api/classes/Configuration.Options.html#setCompilerOptions) to override the files used by that config.

**Comment by NullVoxPopuli** [comment]
> or point TypeDoc at the project's real tsconfig

because of aforementioned pre-processing, I think I'll need to create a file in `tmp`, and point it there :thinking: thanksn!

**Comment by RobbieTheWagner** [comment]
@Gerrit0 thanks for the quick reply! Do you have any idea how I would restore the behavior of the earlier versions before `entryPoints` was required? I assume something internal in typedoc was reading tsconfig files and "magically" creating entryPoints behind the scenes, so I would love to know what it was doing, so I can replicate it.

**Comment by Gerrit0** [comment]
How old are we talking about? Pre-0.20 was a *completely* different conversion method that I can basically guarantee you don't want to replicate.

Even back then though, entry points were required. The option was called "include" then.

**Comment by RobbieTheWagner** [comment]
@Gerrit0 very old, 0.14.2. We don't seem to be passing `include` or `entryPoints` of any kind https://github.com/ember-learn/ember-cli-addon-docs-typedoc/blob/master/lib/typedoc-worker.js

**Comment by Gerrit0** [comment]
Huh, apparently I had just started contributing to typedoc around then... don't remember those early commits at all... faulty memory!

Looks like TypeDoc used to convert every file in the program not removed with `exclude`

https://github.com/TypeStrong/typedoc/blob/v0.14.2/src/lib/converter/converter.ts#L388-L392

Given your filter call to `Serializer.serialize`, you probably want to use `entryPointStrategy: "expand"` and give typedoc `entryPoints: ["."]`

**Comment by RobbieTheWagner** [comment]
Thank you @Gerrit0! Something like this?

```js
      const app = await Application.bootstrap({
        entryPoints: ['./**/*.ts'],
        entryPointStrategy: 'expand',
      });
      let { importPathForFile } = this;
      let docs = loadFromReflection(app.convert(), { importPathForFile });
      console.log(docs);
      ```

When I log out `docs` there, I get an empty modules array, it seems, but it does at least build. I was assuming we didn't need all this super manual stuff, but maybe I was wrong?

```js
      let program = this.watch.getProgram().getProgram();
      let context = new Context(
        converter,
        [],
        program.getTypeChecker(),
        program
      );

      converter.trigger(Converter.EVENT_BEGIN, context);
      converter.compile(context);
      converter.resolve(context);
      converter.trigger(Converter.EVENT_END, context);
      ```

**Comment by NullVoxPopuli** [comment]
How do you specify the current working directory? 

I have this code:
```
let resolvedEntries = await resolveFiles(typeInfo.dir, entries);
let absoluteResolved = resolvedEntries.map((entry) => join(typeInfo.dir, entry));

console.log({
  dir: typeInfo.dir,
  resolvedEntries,
});

const typedoc = await import('typedoc');

const typedocApp = await typedoc.Application.bootstrapWithPlugins({
  entryPoints: resolvedEntries,
  basePath: typeInfo.dir,
  cleanOutputDir: false,
  // includes: typeInfo.dir,
  pretty: false,
  excludeInternal: false,
  skipErrorChecking: true,
  plugin: ['@zamiell/typedoc-plugin-not-exported'],
});

const tmpTSConfigPath = '/tmp/test.json';
const tsConfig = {
  extends: '@tsconfig/ember/tsconfig.json',
  // include: [join(typeInfo.dir, '**')],
  // files: resolvedEntries,
  files: absoluteResolved,
  include: entries,
  compilerOptions: {
    baseUrl: typeInfo.dir,
    // rootDir: typeInfo.dir,
    noEmitOnError: false,
  },
};

await writeFile(tmpTSConfigPath, JSON.stringify(tsConfig, null, 2));

typedocApp.options.setCompilerOptions(
  [tmpTSConfigPath],
  {
    include: resolvedEntries,
    baseUrl: typeInfo.dir,
    noEmitOnError: false,
  },
  []
);

const project = await typedocApp.convert();

if (project) {
  await typedocApp.generateJson(project, dest);
}
```

which produces this output:
```
{
  dir: '/home/nvp/Development/NullVoxPopuli/kolay/node_modules/.pnpm/ember-primitives@0.11.3_@babel+core@7.23.9_@ember+test-helpers@3.3.0_@ember+test-waiters@3.1._jitdkbpeetyxmjwavxc63hrjma/node_modules/ember-primitives',
  resolvedEntries: [
    './declarations/index.d.ts',
    './declarations/components/one-time-password/index.d.ts',
    ✂️
    './declarations/components/layout/sticky-footer/index.d.ts'
  ]
}
[info] Loaded plugin @zamiell/typedoc-plugin-not-exported

ENOENT: no such file or directory, scandir '/home/nvp/Development/NullVoxPopuli/kolay/docs-app/declarations'
```

kolay/docs-app is my CWD, but I want typedoc to act as if the CWD was `/home/nvp/Development/NullVoxPopuli/kolay/node_modules/.pnpm/ember-primitives@0.11.3_@babel+core@7.23.9_@ember+test-helpers@3.3.0_@ember+test-waiters@3.1._jitdkbpeetyxmjwavxc63hrjma/node_modules/ember-primitives`


Now, if I change, `entryPoints` to absolute paths, 

I get this 
```
✂️ bunch of these warnings ✂️
[warning] The entry point /home/nvp/Development/NullVoxPopuli/kolay/node_modules/.pnpm/ember-primitives@0.11.3_@babel+core@7.23.9_@ember+test-helpers@3.3.0_@ember+test-waiters@3.1._jitdkbpeetyxmjwavxc63hrjma/node_modules/ember-primitives/declarations/components/layout/sticky-footer/index.d.ts is not referenced by the 'files' or 'include' option in your tsconfig.
[error] Unable to find any entry points. See previous warnings.
```

**Comment by NullVoxPopuli** [comment]
can `serializer` be made public? https://github.com/TypeStrong/typedoc/blob/de4d813005e8f5dc86a1f9e40b426858be3f8ec3/src/lib/application.ts#L100

I'm using it with unplugin to emit the json to the correct output directory:
```ts
const project = await typedocApp.convert();

if (project) {
  let data = typedocApp.serializer.projectToObject(project, typeInfo.dir);

  this.emitFile({
    type: 'asset',
    fileName: dest,
    source: JSON.stringify(data),
  });
}
```

**Comment by Gerrit0** [comment]
It already is public?

**Comment by NullVoxPopuli** [comment]
thanks!
