### ISSUE TITLE
How can I output the documentation as react components?

### ISSUE THREAD

**Issue by meftunca** [TypeStrong/typedoc#2506]
## Search terms
Providing output as React/jsx

## Question
How can I output the documentation as react components? 
I would like to spread the data sources into JSON files and use them in a way that uses less memory. Currently the total size of the documentation is 3GB. I can also support a higher quality documentation by adding additional features more easily. By making this structure accessible to everyone, we can build a highly interactive documentation system.

**Comment by Gerrit0** [comment]
I have no plans to add this to typedoc directly. You could write a custom output which does it though. Typedoc has a json output which you could post process to split it up into components...

**Comment by Ahmad-Akel** [comment]
I would take a look at[ typedoc-plugin-mark-react-functional-components ](https://www.npmjs.com/package/typedoc-plugin-mark-react-functional-components)
