### ISSUE TITLE
Duplicate comment in interfaces and types

### ISSUE THREAD

**Issue by Kartanovicius** [TypeStrong/typedoc#2509]
## Search terms

tsd-parameters
tsd-comment
duplicate comments
interface comments duplicate
types comments duplicate

## Expected Behavior

Interface and types should not duplicate comments 

## Actual Behavior

Duplicates comments in interface and types

Before 0.25.5
![image](https://github.com/TypeStrong/typedoc/assets/69004630/0d735b2c-abe8-4e1d-b3c4-b09a02e319f2)

After 0.25.5
![image](https://github.com/TypeStrong/typedoc/assets/69004630/9b091ac8-6e05-4a6f-9931-6f21b9eef076)

## Steps to reproduce the bug

Duplicates are appearing only in interfaces and types after typedoc upgrade to 0.25.5

UPDATE 2024-02-29
Created repository that can easily reproduce bug. https://github.com/Kartanovicius/test-rep

## Environment

-   Typedoc version: 0.25.5
-   TypeScript version: 5.3.3
-   Node.js version: 18
-   OS: Any

**Comment by Gerrit0** [comment]
Please provide a minimal reproduction. I can't run typedoc on Screenshots.

**Comment by Kartanovicius** [comment]
https://github.com/Kartanovicius/test-rep

**Comment by Gerrit0** [comment]
Caused by 03426c3ddb2f322aec703a3358795c6e9a1849de, I handled signature checking one level deep, but didn't correctly handle comments attached to a `type` property on a reflection.

More minimal:

```ts
export interface InterceptorMethodAPI {
    /**
     * Duplicated
     */
    callback: () => Promise<any>;
}
```
