### ISSUE TITLE
Generate other file type than html

### ISSUE THREAD

**Issue by MatthieuLebigre** [TypeStrong/typedoc#251]
Hi,
First thanks to your great works on this project !
I would like to use it to generate a doc in Markdown. I can do it thanks to the templates, but the file extension is still html, I have no way to change. I do it by renaming the files with a script, but it would be nice to be able to configure the output file extension.

**Comment by aciccarello** [comment]
@MatthieuLebigre This seems similar to #174 but it sounds like you got further than he did.

Reiterate, it sounds like this RFC is to allow templates to be outputted with different file types.

**Comment by jonaskello** [comment]
@MatthieuLebigre I'm also looking to create markdown output. Could you provide some info how you made it work?

**Comment by MatthieuLebigre** [comment]
Hi @jonaskello 
I'm using this theme: [https://www.npmjs.com/package/typedoc-markdown-theme]
Unfortunatly it's not working so well (file extension is still html, link between pages is broken, ...). With a few manual steps, I can generate a doc.
We plan on do something about that (contribute to Typedoc, or a better theme maybe), but for now it's on hold

**Comment by jonaskello** [comment]
@MatthieuLebigre Thanks for the info, I'll give it a try!

**Comment by Ledragon** [comment]
Hi everyone,
Not sure if this is still an active discussion, but if so, I might be interested as well. Being what I am, though, I started doing [something](https://github.com/Ledragon/TypeDocJsonToMd) on my side before searching the issues...

This is C# (.NET Core), and I am basically parsing the json output by TypeDoc to create markdown files. The result can be seen [here](https://github.com/Ledragon/ldd3/wiki). The whole wiki was generated from the json output file, except the Home page and sidebar.

**Comment by Gerrit0** [comment]
There is a markdown theme that demonstrates one way to generate `.md` files instead of `.html`, [typedoc-plugin-markdown](https://github.com/tgreyuk/typedoc-plugin-markdown). This plugin is advertised in the readme for future searchers to find.
