### ISSUE TITLE
How to include one dependency while using --excludeExternals?

### ISSUE THREAD

**Issue by rickymohk** [TypeStrong/typedoc#2513]
I am developing a typescript module. It depends on a core module also developed by me. It re-exports some types from the core module.

When using typedoc, the core module is being treated as external modules since it is one of the dependencies, hence the generated doc does not contain the doc written in the core module if I uses the --excludeExternals flag.

Is it possible to only include the core module, while still excluding other dependencies from typedoc?

**Comment by Gerrit0** [comment]
You want the excludePattern option - #2354

**Comment by rickymohk** [comment]
Thank you
