### ISSUE TITLE
How to include changelog.md in typedoc output?

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2516]
## Search terms

include, changelog, markdown, documentation

## Question

Is it possible to include the project's changelog within Typedoc's output? If it's not a builtin feature is there possibly a plugin out there that does this?

**Comment by Gerrit0** [comment]
Not currently supported, something I've wanted for a while but haven't gotten to implementing... including arbitrary markdown pages in the docs is really the last "big" feature that TypeDoc is missing IMO. This will be implemented at the same time as #247 / #1870

**Comment by nicfv** [comment]
@Gerrit0 thank you so much for your response and quick action on my other issues (#2514, #2515). I can confirm that I no longer detect those other bugs.

Follow up question here, generally asking the community: Are there any plugins that can include markdown files (e.g. changelog) in typedoc? I think that would solve this issue.

**Comment by Gerrit0** [comment]
There is a typedoc-plugin-pages, but that hasn't been updated for a couple major releases, and I believe last worked with 0.23 (or maybe even 0.22?)

**Comment by nicfv** [comment]
That's a shame. What do you recommend for this issue? Close in favor of #247? I saw that you added the v0.26 milestone to that issue, so I guess the course of action is to wait for the next minor release?

**Comment by Gerrit0** [comment]
GitHub's history there is kind of weird -- I suspect it won't be in the next minor release, but the one after that, as the next minor will probably be adding internationalization support, some necessary breaking changes, (and potentially having to make the step to ESM, since TypeScript is getting really close to removing the `importsNotUsedAsValues` option that I don't want to lose.

**Comment by xuhdev** [comment]
For now, maybe [typedoc page plugin](https://www.npmjs.com/package/@knodes/typedoc-plugin-pages?activeTab=readme) is a reasonable workaround.

**Comment by nicfv** [comment]
@Gerrit0 I see you closed this as completed. Was this implemented? I don't see any new releases.

**Comment by Gerrit0** [comment]
No, it hasn't been implemented, I'm treating this as a duplicate of #247 as the same capability will enable this.

**Comment by nicfv** [comment]
I'd recommend closing as duplicate rather than completed. It could be confusing otherwise.
