### ISSUE TITLE
Typescript 5.4 support

### ISSUE THREAD

**Issue by hildjj** [TypeStrong/typedoc#2517]
(copied from #2446)

## Search Terms

TypeScript 5.4

## Problem

[warning] You are running with an unsupported TypeScript version! If TypeDoc crashes, this is why. TypeDoc supports 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3

## Suggested Solution

Update to TypeScript 5.4, including peerDependencies, and re-test.

**Comment by Gerrit0** [comment]
Also needs a test for NoInfer - will probably be this weekend.

**Comment by nicfv** [comment]
I got this warning/error too.

Minimal reproduction:

Create an empty node project with this `package.json` and run `npm i`

```json
{
  "devDependencies": {
    "typedoc": "^0.25.11",
    "typescript": "^5.4.2"
  }
}
```
