### ISSUE TITLE
`entryPoints` custom names

### ISSUE THREAD

**Issue by reyafyi** [TypeStrong/typedoc#2525]
## Search Terms

custom names for entry points, exports map

## Problem

the problem is basically #1937 - the ability to outline the consumer apis in the docs, and not the internal library structure.

but since that issue seems dormant for some time already, i'd like to propose a (likely) much easier to implement solution

## Suggested Solution

instead of parsing `exports` map, `entryPoints` in config could accept an object instead, where the keys are the names of the resulting branches in the tree, and values are the typescript entrypoints they correspond to.

so assuming i have an `exports` map like this:

```ts
"exports": {
  ".": "./index.ts",
  "./foo": "./__internal__/foo.ts
},
```

i'd write this in my `typedoc.cjs`:

```js
entryPoints: {
  index: './index.ts',
  foo: './__internal__/foo.ts'
}
```

now this obviously wouldn't work for mixed export maps (where there are both wildcard exports and normal ones), since that would require having different entry point strategies for different entry points (is there a tracking issue for this to link?), but should still cover many cases

**Comment by Gerrit0** [comment]
You can already do this with the [`@module`](https://typedoc.org/tags/module/) tag, `__internal__/foo.ts` would look like this:

```ts
/**
 * @module foo
 */
... code for module
```
