### ISSUE TITLE
feat: render readthedocs flyout menu for default theme

### ISSUE THREAD

**Issue by jkowalleck** [TypeStrong/typedoc#2527]
## Search Terms

- readthedocs
- rtfd
- readthedocs-embed-flyout

## Problem

When rendering the docs and publishing them to https://readthedocs.com
I don't have usual "flyout menu" visible or it is rendered incorrectly.
 
read the details here: https://docs.readthedocs.io/en/stable/flyout-menu.html

dummy project:
- https://github.com/jkowalleck/testing_rtfd/tree/push-prerendered
- rendered as https://jkowalleck-testing-rtfd.readthedocs.io/en/push-prerendered/

## Suggested Solution

Add the needed functionality and styling to the default theme, so the readthedocs menu may be rendered.
Maybe hide the functionality behind an environment variable `READTHEDOCS` -- see https://docs.readthedocs.io/en/stable/reference/environment-variables.html#environment-variable-reference

**Comment by Gerrit0** [comment]
Per their docs, typedoc shouldn't have to do anything?

> without having to have the documentation theme integrate it directly.

From the "details" page you linked ^

The menu also appears to work correctly for me...

**Comment by jkowalleck** [comment]
The default theme is very well-thought and responsive.
When the "flyout" menu is rendered on top, it sometimes hides content, or behaves incorrectly.

If the default theme was shipping some CSS to move the "flyout" menu to a different place where it could not interfere with content, this would be great.

For example, the "flyout" menu could be moved to the left site, where the "table of content" is. Somewhere sticky on the bottom left, maybe the horizontal position of `#col-sidebar`.

**Comment by Gerrit0** [comment]
I think this is probably one of those things that would be better maintained as a plugin by people who actually use it. I don't use readthedocs, and really don't want to add features which require manual testing.

A plugin can use [hooks](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md#hooks-v0228) to inject things into the page
