### ISSUE TITLE
Option `sitemapBaseUrl` is not documented

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2530]
## Search terms

sitemapBaseUrl

## Expected Behavior

The option was introduced in [v0.25.8](https://typedoc.org/guides/changelog/#v0.25.8-(2024-02-09)).
The option should be documented at the [options page](https://typedoc.org/options/).

## Actual Behavior

The option is not documented.

**Comment by Gerrit0** [comment]
PR welcome
