### ISSUE TITLE
How to reference a method with a symbol name?

### ISSUE THREAD

**Issue by jameslan** [TypeStrong/typedoc#2531]
## Search terms
Symbol reference link

## Question
When a method's name is a symbol, `{@link [Symbol.XXX]}` will cause warning:

```
[warning] Failed to resolve link to "Example.[Symbol.XXX]" in comment for Example
```

Example:
```typescript
/**
 * Please call {@link Example.[Symbol.dispose]} when the object is no more used.
 */
class Example {
    [Symbol.dispose](): void {
    }
}
```

What is the correct syntax in this case?

**Comment by Gerrit0** [comment]
It's rather unfortunate, but this works...

```ts
/**
 * Please call {@link Example."[dispose]"} when the object is no more used.
 */
export class Example {
    [Symbol.dispose](): void {}
}
```

TypeScript doesn't support linking to computed names, so it won't work properly in VSCode. For TypeDoc's custom resolution, you need quotes around the brackets.

Since TypeDoc displays the symbol name as `[dispose]`, that's the name you need to target

**Comment by jameslan** [comment]
The generated webpage will have the double quotes, but it is a correct link.

There's a workaround: custom the link text, e.g.

```typescript
/**
 * {@link "[dispose]" | [dispose]}
 */
```
or
```typescript
/**
 * {@link "[dispose]" | [Symbol.dispose]}
 */
```

It's a bit redundant, but it works.

**Comment by Gerrit0** [comment]
That's controlled by the [`--preserveLinkText`](https://typedoc.org/options/comments/#preservelinktext) option
