### ISSUE TITLE
No footer in the default theme and renderhooks

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2532]
## Search Terms

footer, theme

## Problem

No footer in the default theme. This makes things like copyright notice, privacy notice (e.g., for [those who use Google analytics](https://support.google.com/analytics/answer/7318509?hl=en)), logo that commonly appear at the footer have no good place to go.

## Suggested Solution

Add a footer to the default theme and add `footer.{begin,end}` render hooks.

**Comment by xuhdev** [comment]
To clarify, when I say footer, I meant a footer that uses the `footer` tag. Currently, with the default theme, the "Generated by TypeDoc" text is not enclosed by a `footer` tag, and appending a footer tag using `body.end` render hooks would cause somewhat unnatural results.

**Comment by Gerrit0** [comment]
The "Generated by TypeDoc" probably ought to be in a footer tag
