### ISSUE TITLE
Does Accessor not support @readonly?

### ISSUE THREAD

**Issue by Mizugorou** [TypeStrong/typedoc#2534]
## Search terms

accessor, json

## Expected Behavior

The flag `IsReadonly` should be true when set @readonly at any accessors.

## Actual Behavior

Got `IsReadonly` = false when set @readonly at any accessors.

## Steps to reproduce the bug
1. Try convert ts to json.
2. Use any tsconfig.
3. TS contains class with accessor with @readnoly flag.
4. Found isReadonly capture incorrectly only at accessor. But method is fine.

### Reproduce link:
[codesandbox link - Convert Test.ts to output.json](https://codesandbox.io/p/devbox/typedoc-test-readonly-qth98n?file=%2Foutput.json)

## Environment

-   Typedoc version: 0.25.12
-   TypeScript version: 4.8.3
-   Node.js version: 20.9.0
-   OS: -

**Comment by Gerrit0** [comment]
This is behaving as intended. When placed on an accessor, `@readonly` instructs TypeDoc to remove any setters.

A getter without any setter is effectively readonly, so there isn't any point to preserving the flag as rendering `@readonly` in the docs is redundant.

**Comment by Mizugorou** [comment]
If so, how can I know in the process of JSON conversion that it's Getter without Setter. Is there the way to tell? Or I have to detect it myself after JSON conversion process.

**Comment by Gerrit0** [comment]
You can check `reflection.getSignature && !reflection.setSignature`
