### ISSUE TITLE
Github links go to previous commit

### ISSUE THREAD

**Issue by paul-uz** [TypeStrong/typedoc#2535]
When the docs are generated, the links to Github point to the previous commit, meaning they could easily be pointing to the wrong line.

**Comment by Gerrit0** [comment]
Are you making changes, then generating docs, and committing that? If so... how could TypeDoc work any other way? The commit you want to target _doesn't exist_ yet!

TypeDoc will use `HEAD` to determine the commit ish. You can change the targeted revision with [`--gitRevision`](https://typedoc.org/options/input/#gitrevision)

**Comment by paul-uz** [comment]
Yea I figured as much. I actually found the gitRevision config after posting this and decided to ultimately disable the source link.
