### ISSUE TITLE
Is it possible to generate output without either sidebar?

### ISSUE THREAD

**Issue by sporritt** [TypeStrong/typedoc#2537]
## Search terms

sidebar exclude

## Question

I can't see any references to this in the docs or in any plugins so I'm fairly sure I know the answer, but I'd like to know if it is possible to run Typedoc in such a way that it generates only the content in the center and leaves out the left and right sidebars. So if I had some class `Foo`, for instance, `classes/Foo.html` would just contain the class definition.

I'd use this to transclude API references into the main JsPlumb documentation - when discussing some class I'd like to drop its definition into the page in an iframe and not have any of the links to other parts of the docs. 

I know this can be done via `customCSS`. Just wondering if there's an option I've missed. Thanks.

**Comment by Gerrit0** [comment]
There isn't an option for this, you could make a custom theme which no-ops the navigation and/or pageSidebar methods in the render context:

- https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md
- https://typedoc.org/api/classes/DefaultThemeRenderContext.html#navigation
- https://typedoc.org/api/classes/DefaultThemeRenderContext.html#pageSidebar

**Comment by sporritt** [comment]
Thanks for the reply, much appreciated, and thanks for this very useful tool.

One aspect I neglected to mention is that I want to use the apidocs both in this "chromeless" format and also in the standard format, and after I posted this I came to the conclusion I don't want to bloat my repo with two versions of the docs, so for the sake of anyone who comes across this issue looking for a similar thing, I ended up doing this:

### Add a plugin that reads a query string param and perhaps sets an attribute on the document element

```javascript
const { JSX } = require("typedoc");

exports.load = function load(app) {
    app.renderer.hooks.on("head.begin", () => {
        return JSX.createElement("script", null,
            JSX.createElement(JSX.Raw, { 
                    html: `const urlParams = new URLSearchParams(window.location.search);
                           if (urlParams.get('sidebars') === 'false') { 
                            document.documentElement.setAttribute('data-sidebars', 'false'); 
                            }`
            }))
    });
}
```

### Add some CSS overrides to hide what I don't want

```css
html[data-sidebars='false'] .tsd-page-toolbar {
    display:none;
}

html[data-sidebars='false'] .col-sidebar {
    display:none;
}

html[data-sidebars='false'] .container-main {
    grid-template-columns: minmax(0, 100vw);
    grid-template-areas:
            "content";
}
```

NOTE: here I also hide the header (it's the `.tsd-page-toolbar` class).

### Run it like this

```bash
npx typedoc --plugin my-plugin.js --customCss my-css.css .....
```
