### ISSUE TITLE
When a function parameter has type `NoInfer<T>`, `T` is removed from the generated doc

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2539]
## Search terms

NoInfer, TypeScript 5.4

## Expected Behavior

When `NoInfer<T>` is used in a function parameter, `T` is retained in the document output of this function parameter. This is because `T` is still informational, indicating that the function parameter has type `T` -- it's just that `T` can't be inferred from this function parameter.

## Actual Behavior

`T` is removed from this function parameter in the doc.

## Steps to reproduce the bug

(The corresponding test does not check for `C`: https://github.com/TypeStrong/typedoc/blob/3398e98dce4de5d7c5a53f1f6c66e1af8aa28cc9/src/test/behavior.c2.test.ts#L1180)

1. Download the test file: https://github.com/TypeStrong/typedoc/blob/3398e98dce4de5d7c5a53f1f6c66e1af8aa28cc9/src/test/converter2/behavior/noInfer.ts

```ts
export function createStreetLight<C extends string>(
    colors: C[],
    defaultColor?: NoInfer<C>,
) {}

// @ts-expect-error
createStreetLight(["red", "yellow", "green"], "blue");
```

2. `npm install --save-dev typedoc`
3. `npx typedoc NoInfer.ts`
4. Observe that `C` is gone from the `defaultColor` parameter description

## Environment

-   Typedoc version: 0.25.12
-   TypeScript version: 5.4.3
-   Node.js version: 20.12.1
-   OS: Debian

**Comment by Gerrit0** [comment]
Huh, that's strange... I must not have been paying enough attention.
