### ISSUE TITLE
Using typedoc in vite will result in compilation failure

### ISSUE THREAD

**Issue by Jeggery** [TypeStrong/typedoc#2542]
## Search terms
vite

## Question
I initialized a vite project and then wrote a ts file in src. 
When I compile using typedoc, it will report：
**src/main.ts:3:17 - error TS2307: Cannot find module './App.vue' or its corresponding type declarations.**

**`tsconfig.json**
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"],
  "references": [{ "path": "./tsconfig.node.json" }]
}

**typedoc.json:**
{
  "entryPoints": ["src/engine/index.ts"],
  "out": "docs",
  "name": "Meta3DEngine API",
  "skipErrorChecking": false,
  "compilerOptions": {
    "skipLibCheck": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false
  },
  "exclude": ["src/**/*.vue", "README.md"]
}

**package.json:**
{
     "scripts": {
          "typedoc": "typedoc --options typedoc.json"
    }
}
`
Please take a look at my entryPoints, where the entry is src/engine/index. ts, but why does typedoc compile main. ts?
This is very confusing for me

**Comment by Gerrit0** [comment]
TypeDoc's entryPoints option doesn't control what is compiled. That is up to your tsconfig.json.

The entryPoints option just specifies the subset of files included by your tsconfig which typedoc should generate documentation for.

You'll have the same errors from TS if you run `tsc --noEmit`

**Comment by Jeggery** [comment]
I have found a way. I have created a new typedoc tsconfig.json with its contents
`{
  "compilerOptions": {
    "skipLibCheck": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false
  },
  "include": ["src/**/*.ts"],
  "exclude": ["src/main.ts"]
}
`
typedoc.json:
`
  "tsconfig": "typedoc-tsconfig.json"
`
I used another tsconfig, excluding src/main.ts and not using tsconfig in the root directory
