### ISSUE TITLE
Typedoc will automatically filter undefined and null types

### ISSUE THREAD

**Issue by Jeggery** [TypeStrong/typedoc#2543]
## Search terms

undefined | null

## Expected Behavior

Display null and undefined types

## Actual Behavior

Undefined and null are not displayed in the document

```ts
export class Engine {
  screenShot?: ScreenShot;
  private dom: HTMLElement | null;
  /**
   * value值
   */
  value: number | null | undefined;
  constructor(id: string) {
    let dom = document.getElementById(id);
    if (dom) {
      this.dom = dom;
      this.screenShot = new ScreenShot();
    } else {
      this.dom = null;
    }
  }
  getScreenShot() {
    return this.screenShot?.getScreenShot();
  }
  getDom(): string | null {
    if (this.dom) {
      return '888';
    } else {
      return null;
    }
  }
}

class ScreenShot {
  constructor() {}
  getScreenShot() {
    if (window.Blob) {
      return '222';
    } else {
      return undefined;
    }
  }
}
```

## Environment

-   Typedoc version: 0.25.13
-   TypeScript version: 5.4.2
-   Node.js version: v18.19.1
-   OS: windows

tsconfig.json
```json
{
"compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },

}

```

![image](https://github.com/TypeStrong/typedoc/assets/39072827/c232beb1-4630-4e7d-9200-1643e6980541)
![image](https://github.com/TypeStrong/typedoc/assets/39072827/6dc274f6-05b5-4737-b95a-f6a870127e46)

**Comment by Gerrit0** [comment]
Based on your comment on the other issue, that is not the tsconfig you are using, you're using one with `strict: false`. TypeDoc relies on TypeScript's API to get types, so if TS options are set up to ignore null/undefined, this is expected behavior.

**Comment by Jeggery** [comment]
> 根据您对另一问题的评论，这不是您正在使用的 tsconfig，您正在使用`strict: false`. TypeDoc 依赖于 TypeScript 的 API 来获取类型，因此如果 TS 选项设置为忽略 null/未定义，这是预期的行为。

Wow, "strict": False actually affects the output of typedoc. I see. Thank you, my problem has been resolved
