### ISSUE TITLE
Header is navbar on mobile is overriding itself

### ISSUE THREAD

**Issue by HarelM** [TypeStrong/typedoc#2547]
## Search terms

header, mobile, override
## Expected Behavior

Either use ellipsis or use two rows for the header in the mobile for long text

## Actual Behavior
Header is overriding itself:
![image](https://github.com/TypeStrong/typedoc/assets/3269297/1a1bc542-2afa-4c8d-8106-a3b964e0fe31)

## Steps to reproduce the bug

Write a long package name I guess...?
1. Clone: https://github.com/maplibre/ngx-maplibre-gl
2. Run: `npm ci && npm run docs`
3. open the docs (generated in dist/showcase/browser/API) and look at it using the chrome tool for mobile.  

## Environment

-   Typedoc version: 0.25.12
-   TypeScript version: 5.4.3
-   Node.js version: 20
-   OS: any

**Comment by Gerrit0** [comment]
Very unlikely that this will be fixed anytime soon unless someone else picks it up. I despise GUI work.

**Comment by HarelM** [comment]
I'll be happy to contribute, can you point me in the right direction?

**Comment by HarelM** [comment]
The part that gets overridden in the navigation links, I have proposed a solution in the link PR: 
- #2548
