### ISSUE TITLE
npm ERR! ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by maxvia37** [TypeStrong/typedoc#2549]
While installing TypeDoc by running "npm install typedoc --save-dev", I have the following error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-new-app@1.0.0
npm ERR! Found: typescript@4.5.5
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"~4.5.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"4.6.x || 4.7.x || 4.8.x || 4.9.x || 5.0.x || 5.1.x || 5.2.x || 5.3.x || 5.4.x" from typedoc@0.25.13
npm ERR! node_modules/typedoc
npm ERR!   dev typedoc@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

My current Typescript version ("tsc -v") is Version 5.3.3. In my package.json, devDependencies: "typescript": "~4.5.4".

**Comment by Gerrit0** [comment]
This is working as intended, you need to install a more recent typescript in your project to use typedoc.

**Comment by maxvia37** [comment]
> This is working as intended, you need to install a more recent typescript in your project to use typedoc.

I don't understand why. When I am typing "tsc -v" I have "Version  5.3.3. In my project I have "typescript": "~4.5.4" which means all versions above 4.5.4. Do I update the Thypescript by running "npm install typescript@latest --save-dev"? Thank you!

**Comment by nicfv** [comment]
I think `~` means to match the minor version, so `4.5.X`. You can fix it using `^4.5.4` or just changing the version number of Typescript to a newer version.
