### ISSUE TITLE
Add a page to typedoc.io for typedoc plugins

### ISSUE THREAD

**Issue by christopherthielen** [TypeStrong/typedoc#255]
Here's a plugin I created that allows you to override the "External Module" for each ES6 module (TS file):   https://github.com/christopherthielen/typedoc-plugin-external-module-name

**Comment by blakeembrey** [comment]
Added: https://github.com/TypeStrong/typedoc#plugins.

**Comment by DaSchTour** [comment]
Nice work. But is there a documentation for this?
@christopherthielen I tried to use your plugin. But all I get is a `Unknown option 'plugins.0'.`
How does ne option in typedoc look like? Is it supposed to work with gulp-typedoc? How are plugins loaded?

**Comment by christopherthielen** [comment]
@DaSchTour

> But is there a documentation for this?

Just the docs on the plugin project page: https://github.com/christopherthielen/typedoc-plugin-external-module-name

> How does ne option in typedoc look like?

No options should be necessary.   Typedoc discovers plugins and loads them automatically.  I learned how plugins are loaded only by reading the typedoc source and experimenting.  

This plugin is working for me in the ui-router project with typedoc 0.4.4 and typescript 1.8.10.  Using typedoc from the command line.

```
git clone https://github.com/angular-ui/ui-router.git && cd ui-router && npm i && ./scripts/docs.sh
```

output: 
```
Cloning into 'ui-router'...
remote: Counting objects: 10765, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 10765 (delta 16), reused 0 (delta 0), pack-reused 10720
Receiving objects: 100% (10765/10765), 7.89 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (7553/7553), done.
Checking connectivity... done.

... npm  output ...

Loaded plugin typedoc-plugin-external-module-name

Using TypeScript 1.8.10 from ~/projects/t/ui-router/node_modules/typescript/lib
Rendering [========================================] 100%

Documentation generated at ~/projects/t/ui-router/_doc
```

scripts/docs.sh contents: 

```
#!/bin/sh
SCRIPTDIR=`dirname $0`;
BASEDIR="$SCRIPTDIR/..";
$BASEDIR/node_modules/typedoc/bin/typedoc $* \
  --experimentalDecorators \
  --readme $BASEDIR/README.md \
  --name "UI-Router" \
  --theme $BASEDIR/typedoctheme \
  --mode modules \
  --module commonjs \
  --target es5 \
  --out $BASEDIR/_doc  \
  $BASEDIR/src $BASEDIR/typings/es6-shim/es6-shim.d.ts $BASEDIR/typings/angularjs/angular.d.ts
```

**Comment by DaSchTour** [comment]
Okay, well. Than it simply doesn't work with gulp-typedoc.
Just a line with "Typedoc recognizes plugins by itself" would clear things up. It's not that obvious.
