### ISSUE TITLE
Add docstring representation for inferred parameters

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2551]
## Search Terms

generic parameters
type parameters

## Problem

Inferred types (i.e. those following `infer` keyword) are colored as type parameters, but there is no way to document them.  It is sometimes necessary to provide explanation for inferred types, since they can feature directly in a typedef or in the return type of a documented function.

## Suggested Solution

A new section below "type parameters" should be added specifically for inferred types, with a corresponding docstring annotation (possibly `@inferredType` or just `@inferred`).

**Comment by Gerrit0** [comment]
I'm not sure this is a good idea.

Type parameters which are internal to the implementation of your type are exactly that. Internal implementation details.

So far as the users of the following types are concerned... these are equivalent. Whether a utility delegates to a helper or performs the work inline isn't relevant.

```ts
type GetParamsAndReturns<T extends (..._: any) => any> = { params: Parameters<T>; return: ReturnType<T> }
type GetParamsAndReturns<T extends (..._: any) => any> = T extends (..._: infer P) => infer R ? { params: P; return: R } : never
```

Further, these names are not necessarily unique, they're scoped to the conditional which introduces them, so documenting them as a part of the type alias feels very similar to documenting local variables within a function as part of that function's contract...

```ts
type Values<T> =
  T extends Array<infer U> ? U :
  T extends Map<string, infer U> ? U :
  never
```

You could do this with a custom plugin, but at this point I don't think it's something I want to include in TypeDoc itself.

**Comment by Oblarg** [comment]
An inferred type param isn't always an internal implementation detail, though - it can occur directly in the return type, and in those cases it's important for the user to know the bounds on what was inferred.

**Comment by Gerrit0** [comment]
From that description, it sounds like what you actually want is `@returns` (`@typeReturns`?) for type aliases, re-using `@typeParam` for it seems like a mixing of concerns with input/output and a recipe for more confusion

**Comment by Oblarg** [comment]
`@typeReturns` would be more accurate, yeah.

**Comment by Gerrit0** [comment]
I don't think this needs special handling in TypeDoc, unless I'm missing something...

```ts
/**
 * @typeReturns An object describing the parameters and return type of the function
 */
export type GetParamsAndReturns<T extends (..._: any) => any> = { params: Parameters<T>; return: ReturnType<T> }
```

Renders as:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/07aa2659-3cb7-48e6-b93d-a04c515fc2cf)

**Comment by Oblarg** [comment]
See the amended request - I still think there should be a bespoke section for inferred types that is formatted like the type parameter section and has similar hyperlinking behavior.  Describing the return type can sidestep the problem for functions, but I think it's far from optimal for highly-algebraic types, especially in internal developer-facing docs.  Consider:

```typescript
PropagatedEvent<SourceTopic, TargetTopic, Event>: Event extends infer E extends { 
        type: string; 
    }
    ? Omit<E, "type" | "topic"> & { 
            topic: TargetTopic; 
            type: PropagatedEventType<SourceTopic, E["type"]>; 
        }
    : never```

Here `E` is specifically a member of the union type `Event` - understanding this helps greatly in making sense of the type - but there's no natural place to document this in TypeDoc as-is.  Note that this isn't a function, it's a typedef, so there's no "returns" involved.  Since the inference behavior is part of the contract of the type, I feel that it should be represented.

**Comment by Gerrit0** [comment]
I think it is "far from optimal for highly-algebraic types" because many metaprogramming types like that suffers from lack of encapsulation where every "type-function" (aka typedef - it is a type which operates on a type and returns a type...) needs to be understood in order to use it. Personally, if writing documentation for types like this I'd make every effort to let users of the types **not** need to read the type, including myself in 6 months. A good example of this is `Awaited`.

Consider TypeScript's documentation for [`Awaited<T>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#awaitedtype)...

> This type is meant to model operations like `await` in `async` functions, or the `.then()` method on `Promise`s - specifically, the way that they recursively unwrap `Promise`s.
> ```ts
> type A = Awaited<Promise<string>>;
> //   ^? - string
> type B = Awaited<Promise<Promise<number>>>;
> //   ^? - number
> type C = Awaited<boolean | Promise<number>>;
> //   ^? - number | boolean
> ```

That's all you really need to know in order to use the type... it doesn't say anything about how the type works under the hood, because in almost every case, you don't care! It also includes a few examples to let potential users of the type quickly get an understanding of what the type does for them.

Then compare that to [the implementation](https://github.com/microsoft/TypeScript/blob/ebcb09d71a0838b4b9be974f9ef1e80fce8888af/src/lib/es5.d.ts#L1542-L1550)

```ts
type Awaited<T> =
    T extends null | undefined ? T : // special case for `null | undefined` when not in `--strictNullChecks` mode
        T extends object & { then(onfulfilled: infer F): any } ? // `await` only unwraps object types with a callable `then`. Non-object types are not unwrapped
            F extends ((value: infer V) => any) ? // if the argument to `then` is callable, extracts the argument
                Awaited<V> : // recursively unwrap the value
                never : // the argument to `then` was not callable
        T; // non-object or non-thenable
```

I think this approach, where inline comments are used for anyone who needs to peek behind the curtain, and a high level description + list of examples for most users is the best way to document complex types.

TypeDoc could try to provide more features around making explaining these types easier, but I doubt it will ever be able to provide a better experience to exploring such a type than your editor can...

**Comment by Oblarg** [comment]
The users already do not need to read the type - it has a high-level description, as do the types that rely on it, and the overall behavior of the type is understandable without parsing the entire definition.  But I like to offer as much as I reasonably can to a developer without forcing them to context-switch, and this is information that I'd like to include in our internal developer-facing builds of the API docs.

**Comment by Gerrit0** [comment]
> I think this approach, where inline comments are used for anyone who needs to peek behind the curtain, and a high level description + list of examples for most users is the best way to document complex types.

^ A couple months later, this still feels right to me... so, I think I'm going to push this to plugin land. With 0.26, TypeDoc adds a couple hooks around comments for plugins to add custom rendering. If someone publishes a plugin to do this, and that plugin gets a lot of use, I'll reconsider pulling it into TypeDoc.

For this code:

```ts
/**
 * The type values
 * @inferredType U the values within this container
 */
export type Values<T> = T extends Array<infer U> ? U : T extends Map<string, infer U> ? U : never;
```

The following plugin will render:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/1ea7e2da-7b15-4a4b-b850-05097fd25bf3)

```ts
// CC0
// @ts-check
import td from "../../typedoc2/dist/index.js";
const createElement = td.JSX.createElement;

const TAG = "@inferredType";

/** @param {td.Application} app */
export function load(app) {
    // Automatically add `@inferredType` to the list of allowed block tags if not present.
    app.on(td.Application.EVENT_BOOTSTRAP_END, () => {
        const tags = [...app.options.getValue("blockTags")];
        if (!tags.includes(TAG)) {
            tags.push(TAG);
        }
        app.options.setValue("blockTags", tags);
    });

    app.renderer.hooks.on("comment.beforeTags", (context, comment) => {
        /** @type {td.CommentTag[]} */
        const inferredTypes = comment.blockTags.filter((tag) => tag.tag === TAG);
        /** @type {td.JSX.Element[]} */
        const items = [];
        for (const tag of inferredTypes) {
            tag.skipRendering = true; // Tell TypeDoc not to render this tag

            if (tag.content[0].kind === "text") {
                let nameEnd = tag.content[0].text.search(/\s/);
                tag.name = tag.content[0].text.slice(0, nameEnd);
                tag.content[0].text = tag.content[0].text.slice(nameEnd).trimStart();
            }

            items.push(
                createElement("li", null, [
                    createElement("span", { class: "tsd-kind-type-parameter" }, tag.name),
                    createElement(td.JSX.Raw, { html: context.markdown(tag.content) }),
                ]),
            );
        }

        if (items.length) {
            return createElement("section", { class: "tsd-panel" }, [
                createElement("h4", null, "Inferred Types"),
                createElement("ul", { class: "tsd-type-parameter-list" }, items),
            ]);
        }
    });
}
```
