### ISSUE TITLE
Documented constructor type produces warning

### ISSUE THREAD

**Issue by jpikl-prgs** [TypeStrong/typedoc#2553]
## Search terms

notDocumented, constructor, warning

## Expected Behavior

Running typedoc for fully documented constructor types should not produce any warnings.

## Actual Behavior

The following warnings are produced:

```
[warning] Constructor.__type (ConstructorSignature), defined in ./index.ts, does not have any documentation.
[warning] TypedConstructor.__type (ConstructorSignature), defined in ./index.ts, does not have any documentation.
```

## Steps to reproduce the bug

**index.ts**

```ts
/**
 * Constructor.
 *
 * @param args - Constructor arguments.
 * @returns New instance.
 */
export type Constructor = new (...args: any[]) => object;

/**
 * Typed constructor.
 *
 * @typeParam T - Class type.
 * @param args - Constructor arguments.
 * @returns New instance.
 */
export type TypedConstructor<T> = new (...args: any[]) => T;
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

**typedoc.json**
```json
{
    "entryPoints": ["index.ts"],
    "validation": {
        "notDocumented": true
    }
}
```

## Environment

-   Typedoc version: 0.25.13
-   TypeScript version: 5.4.5
-   Node.js version: 20.10.0
-   OS: Linux

## Notes

The latest typedoc where it worked was `0.25.4`. The warnings started to appear after updating to `0.25.5` or higher,

**Comment by Gerrit0** [comment]
Signatures are the bane of my existence, there are entirely too many edge cases around them, so I always seem to miss at least one when touching that code...
