### ISSUE TITLE
Nested object parameter descriptions are not included in the output

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2555]
## Search terms

nested object

## Expected Behavior

Descriptions of nested object types should be generated in the output.

## Actual Behavior

Descriptions of nested object types are not generated in the output.

## Steps to reproduce the bug

1. Write the following file:

```ts
/**
 *
 * @param props - Component properties.
 * @param props.title - Title.
 * @param props.options - Options.
 * @param props.options.featureA - Turn on or off featureA.
 * @param props.options.featureB - Turn on or off featureB.
 */
function ComponentWithOptions({
  title,
  options,
}: {
  title: string;
  options: { featureA: boolean; featureB: boolean };
}) {}
```

2. Invoke `typedoc` on the file.
3. The output looks like the following:

![image](https://github.com/TypeStrong/typedoc/assets/325476/d0a1f17e-c86f-4dd7-8b83-d774d6438195)

Note the descriptions of `featureA` and `featureB` are completely missing.

## Environment

-   Typedoc version: 0.25.13
-   TypeScript version: 5.4.5
-   Node.js version: 20.12.2
-   OS: Debian

**Comment by Gerrit0** [comment]
This is controlled by https://github.com/TypeStrong/typedoc/blob/cf3dcd103a302f9e14cef00cf80a191b9c7b3219/src/lib/converter/plugins/CommentPlugin.ts#L644-L648

**Comment by pastelsky** [comment]
@Gerrit0 what is needed to be done here? I can try and give this a shot.

**Comment by Gerrit0** [comment]
The function that I linked to above is what's responsible for moving `@param` comments, it currently only does one level deep, so it needs to be updated to be recursive or some other way too handle dotted name paths that are more than one deep.

**Comment by Oblarg** [comment]
Sideways angle at this: if TypeDoc adds an `@expand` annotation, that could be used along with defining the type out-of-line to achieve effectively the same thing.

I feel like this feature could encourage poor practice - inline parameter typedefs are bulky and hard to consume.
