### ISSUE TITLE
Ensures select element has an accessible name.

### ISSUE THREAD

**Issue by msftedad** [TypeStrong/typedoc#2557]
**Test Environment:** 
OS: Windows 11
OS version: 23H2 ((OS Build 26052.1000)
Edge Version: 123.0.2380.1 (Official build) stable app, dev channel (64-bit)
Tool: AI for web/ windows
Typedoc version: v0.25.13
 
**Steps to Reproduce:**   
1. Open [TypeDoc - v0.25.13](https://typedoc.org/api/) in edge browser.
2. Run accessibility Insights tool and observe the issue.
 
**Actual result:**
Select element does not have an accessible name at the theme dropdown.

**Expected Result:**
Ensures select element has an accessible name.

![221470_main](https://github.com/TypeStrong/typedoc/assets/93735775/d33f4b40-33ba-4f02-b826-6f74d653cc32)
![221470](https://github.com/TypeStrong/typedoc/assets/93735775/30bb1530-2f27-48f1-a9d4-ce7562350528)
![fastpass](https://github.com/TypeStrong/typedoc/assets/93735775/f11384e6-7437-4577-aab2-9ec40b904d88)
![accessible name](https://github.com/TypeStrong/typedoc/assets/93735775/5823e672-2db1-4592-a37a-58e32eb60321)

**Comment by Gerrit0** [comment]
Fixed with TypeDoc 0.26, which is releasing 2024/06/21
