### ISSUE TITLE
Invite new contributors/maintainers?

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#256]
@sebastian-lenz has put together a great project here but unfortunately does not seem to have the time to continue working on this. @blakeembrey has helped move typedoc into the TypeStrong organization and done a great job answering questions and keeping the project alive with a few releases. However, he has many other projects that he is involved in and hasn't been able to learn the ins and outs of the typedoc source.

Is anyone able to take a bigger role in this project and would that be welcomed? Right now it feels like there is no one able to take charge of where things are headed?

**Comment by aciccarello** [comment]
@blakeembrey, I would like to be more involved in this project. My OS experience and available time is still limited so I do not think I would be a good maintainer but I would like to contribute. I'll do my best to follow up on and triage GH issues and PRs. I'd also like to contribute to a project code/style review when time allows.

**Comment by blakeembrey** [comment]
Any help on issues right now is certainly appreciated, especially for new feature implementations 😄

**Comment by emilianosantucci** [comment]
Currently `typedoc` is the only valid project to build docs in TypeScript.
Anyway in my opinion, when they started to think on it, them make an error: not consider to build it upon [jsdoc](https://github.com/jsdoc3/jsdoc). 
While two projects differ on target language, it have many common points and features.
Typedoc could take advantage on parsing rules of jsdoc and on community behind it (currently 72 contributors, not bad).

I would like to support this project but now I'm on startup a big project, I hope give you help in near future :)

**Comment by jiayihu** [comment]
I think setting a gitter chat (or even better Slack) could be very helpful for many reasons. I wish there were somebody to ask info when I started using Typedoc's internal API for a script of mine.

I don't have much free time, as probably anyone else, but I'd like to give some contributions to minor issues/changes. I believe it's currently the best project for doc generation in Typescript.

**Comment by aciccarello** [comment]
@jiayihu I'd be up for participating in a Slack channel. There is a big need for documentation updates though. There are features that are not well documented and the existing documentation has not been updated in a long time. I'd prefer we focus on that than having people repeatedly ask the same questions.

I also think that the readme should have some information encouraging people to make PRs since there isn't currently anyone who can devote a ton of time to the project right now.

**Comment by WasabiFan** [comment]
Side-note: If you're going to create somewhere to chat, use Gitter (not Slack). I use both and they're both great, but Slack is designed specifically for private teams while Gitter is the opposite (allowing both private and public). Unless you want to pay for a limited service, don't use Slack.

**Comment by jiayihu** [comment]
@aciccarello a chat is not exclusive with documentation and it's easy to set up. Could be helpful also for organization between collaborators.

**Comment by blakeembrey** [comment]
I just added https://github.com/TypeStrong/typedoc/pull/422 in case.

**Comment by aciccarello** [comment]
Hi @demurgos, some additional help would be greatly appreciated. Unfortunately I have not had the time to review PRs quickly enough to keep up with issues. Feel free to reach out to me on Twitter or gitter to discuss the best way to keep the project moving.

**Comment by aciccarello** [comment]
I'm adding @blink1073 to this thread as he has indicated that he would like to help too.

The main priority I see right now is getting typedoc up to speed with TypeScript updates. There are PRs open to update the dependency but there are a lot of related bugs for typescript features that TypeDoc does not support. I'm considering using a peer dependency on TypeScript to ease some of the pain for users with TypeScript compile errors but tsc often has breaking changes. It helps to have issues verified and duplicates identified in the comments. Creating and especially reviewing PRs is always great. I'll merge PRs if I believe others have thoroughly tested them.

I'd also like to see a couple architectural changes made to improve the contribution/learning/release process. These are probably a while down the road but would bring big wins.
- Pull in the theme projects as a monorepo to test together (#741)
- Improve documentation
- Use ts-node for running tests
- Support a library structure (with a public api of re-exports from a few files)

If someone has been active for a while and would like more access on the project I'd be happy to add you. I can't take the credit for the great work that went into this project and I can't keep up with bugs and features on my own so your help is appreciated.

**Comment by blink1073** [comment]
I think it is fair for a TypeDoc version to be tied to a particular minor release of TypeScript, since they do not follow semver the way a typical project normally would.  When they "fix" a bug in the compiler, it can cause code that compiled in the previous minor version to no longer compile.  I can dig up an example from the TypeScript issues where they've said this if need be.

I personally don't have time to contribute code to this code base, but would love to help with reviewing PRs and making releases so we don't fall out of sync with the current TypeScript compiler version.

**Comment by blink1073** [comment]
Ah, found the link: https://github.com/Microsoft/TypeScript/issues/14116#issuecomment-280410804
