### ISSUE TITLE
Document Coverage like ESDocs

### ISSUE THREAD

**Issue by jebarpg** [TypeStrong/typedoc#2566]
## Search Terms

Document Coverage 

## Problem

Not having a metric to show how much code has been documented as well as where documentation still might be needed.

## Suggested Solution

Take example from ESDocs and work their solution into TypeDocs

**Comment by jebarpg** [comment]
This is great for the first part of the feature request, but doesn't address the second part, which is showing where in your code you still need documentation. Unless the plugin has a flag I'm missing, but I only see options to output a statistic badge.

**Comment by Gerrit0** [comment]
That is built in to typedoc, `--validation.notDocumented` will make TypeDoc print out what hasn't been documented according to the `requiredToBeDocumented` option

**Comment by jebarpg** [comment]
O awesome! Thank you a ton!
