### ISSUE TITLE
<meta charSet="utf-8"/> The attribute name of [ charSet ] must be in lowercase.(attr-lowercase)

### ISSUE THREAD

**Issue by jebarpg** [TypeStrong/typedoc#2568]
## Search terms

`<meta charSet="utf-8"/>`

## Expected Behavior

in `index.html` this is how it should be formatted
`<meta charset="utf-8"/>`

## Actual Behavior

in `index.html` this is how it is currently formatted
`<meta charSet="utf-8"/>`

## Steps to reproduce the bug

npm typedoc

## Environment

-   Typedoc version: 0.25.13
-   TypeScript version: 5.4.5
-   Node.js version: v22.1.0
-   OS: Clear Linux

**Comment by Gerrit0** [comment]
Fixed with TypeDoc 0.26, which is releasing 2024/06/21
