### ISSUE TITLE
What is json option?

### ISSUE THREAD

**Issue by iveetoo** [TypeStrong/typedoc#257]
Hi, is there more information about the json option and the outputed json file? How can I use it to generate documentation?

**Comment by aciccarello** [comment]
I believe the json option allows you to serialize your parsed project documentation to a file. I think the idea is to use the parsed documentation in other tools.

**Comment by iveetoo** [comment]
Can you give me an example of such tool, that consumes json and produces documentation?

**Comment by aciccarello** [comment]
I'm not sure who's using it right now.

**Comment by FlippieCoetser** [comment]
We used the JSON output to create UML Diagrams in GenMyModel. Transpile the JSON output to  XMI 2.1 (UML Structured in XML format) and then import that into GenMyModel. Creating the transpiler was a pain due to the limited documentation but we succeeded. Thanks to @Gronke!

**Comment by sergiusignacius** [comment]
Is there a definition (e.g. d.ts declaration) that serves as a schema for the generated file? I'm interested in creating a tool in Typescript that consumes this output, but the generated JSON is a monster of a file.

**Comment by ericjim** [comment]
I would like the option of generating a JSON file that my app can consume. I would also like the ability to stop generating HTML file in this case.

**Comment by ssokolow** [comment]
@sergiusignacius While it's not perfect, I usually find [GenSON](https://github.com/wolverdude/GenSON/) helpful in situations like that.

**Comment by Tiberriver256** [comment]
@FlippieCoetser did you have your code for conversion from json to XMI out somewhere? That would be pretty useful.

**Comment by gronke** [comment]
@Tiberriver256 https://github.com/gronke/TypeDoc-GenMyModel-Transpiler

**Comment by FlippieCoetser** [comment]
@Tiberriver256 @gronke and I are just checking if any private info is contained in the code. Once done we will post the link to the code here. When we developed the transpiler typescript was still at an older level which means some of the new features are not covered. but at least you will be able to see the approach we took.

**Comment by FlippieCoetser** [comment]
@Tiberriver256 this is the repo for the code. https://github.com/gronke/TypeDoc-GenMyModel-Transpiler
@gronke will open source the code shortly.

**Comment by danbars** [comment]
@FlippieCoetser the link to the repo is broken. Did you open it?
Would also love to see it.
Thanks!

**Comment by FlippieCoetser** [comment]
@danbars @gronke will open the package. We removed all privacy info. so it is ready to go. A lot has changed since we last used the transpiler. but it might still give you a direction to work from.

**Comment by gronke** [comment]
@danbars @Tiberriver256 there you go: [gronke/TypeDoc-GenMyModel-Transpiler](https://github.com/gronke/TypeDoc-GenMyModel-Transpiler)

**Comment by Tiberriver256** [comment]
@FlippieCoetser @gronke Thanks guys!

**Comment by danbars** [comment]
Thank you @FlippieCoetser and @gronke
