### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by ben-polinsky** [TypeStrong/typedoc#2571]
Semantic versioning helps developers understand at a glance if a new version has breaking changes, allows us to easily apply hotfixes and security patches, and provides clarity for new releases. `0.x` releases are "for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable." [Semver](https://semver.org/#semantic-versioning-specification-semver).

TypeDoc seems stable. Has a 1.x release been considered?

**Comment by Gerrit0** [comment]
Yes, it's been considered. 5 years ago I thought I'd be making a 1.0 release in a couple of months. That obviously hasn't happened.

In practice, while *pieces* of TypeDoc, mainly the CLI interface with common options, and to a lesser extent the JS API, are very stable, other pieces are not... and what the "public API" is isn't well defined.

If TypeDoc didn't support plugins, some of which reach deep into what probably should be considered internals, but is effectively public, it'd have been 1.0 ages ago (and probably 3.0 today), if I'd gone to 1.0 back then, we'd be at least at 25.x today when considering plugins.

Currently what is done is that changes I know will be breaking wait for 0.x.0 releases, while changes which likely won't affect anyone (at least those only using public plugins, or no plugins) can be included in any release. I've been wary of going to 1.x as in my mind it promises more stability than I can guarantee with every piece of TypeDoc being effectively public.

**Comment by ben-polinsky** [comment]
Sure, I can understand that. But it does seem like people are using this in production and relying on the library's public APIs. Fair enough, just wanted to know if you had thought of it. Thanks.

**Comment by Gerrit0** [comment]
I'm certainly not ruling out a 1.0 sometime in the future, but I really need to figure out how to decide on what is public, and go through the 500+ "public-ish" things and properly mark them all first... not a very high priority to me.

**Comment by xuhdev** [comment]
Since TypeDoc doesn't use semver, could you make it clear in the doc?
