### ISSUE TITLE
Property 'withResolvers' does not exist on type 'PromiseConstructor'.

### ISSUE THREAD

**Issue by itancc** [TypeStrong/typedoc#2572]
## Question
Hello, could you tell me how to deal with this kind of problem? thanks

![image](https://github.com/TypeStrong/typedoc/assets/46319251/8eb70abe-cb46-40f9-a832-3bee4f28495b)

**Comment by Gerrit0** [comment]
That error is coming from typescript, and is caused by not having a recent enough ES version in your tsconfig.json's "lib" option

**Comment by itancc** [comment]
Thanks for replying, I actually have the latest version of typescript and "lib" is set to "ESNext". There are no errors in my project, this only happens when I do typedoc.

**Comment by itancc** [comment]
oh ,sorry! my fault.  I'll close this.
