### ISSUE TITLE
Is there a way to inline a type into a function? without creating another page for the type?

### ISSUE THREAD

**Issue by marcog83** [TypeStrong/typedoc#2575]
## Search terms
inline, function, type, merge, expand

## Question
I have a react `NovaProvider` and its pros `NovaProviderProps`. I'd like to display the NovaProviderProps expanded / inlined directly into the `NovaProvider` , without a separated page, because those props are used only by the provider.
is it possible? maybe some plugin? 
I can try to create one plugin if you can give me some hints about the steps to follow and where to hook.

Function Page
<img width="911" alt="image" src="https://github.com/TypeStrong/typedoc/assets/4071265/c1d20b61-1fc6-4d51-8f73-72cc3f10a291">

Interface Page
<img width="911" alt="image" src="https://github.com/TypeStrong/typedoc/assets/4071265/ab970dca-dc7c-4745-8eb0-856fba38ff1e">

**Comment by Gerrit0** [comment]
This would require a plugin, the way I'd approach it is to listen to [Converter.EVENT_CREATE_PARAMETER](https://typedoc.org/api/classes/Converter.html#EVENT_CREATE_PARAMETER) to collect parameters whose type needs to be overwritten (everything with the `refl.name === "props"`?) and then in a listener for [Converter.EVENT_RESOLVE_BEGIN](https://typedoc.org/api/classes/Converter.html#EVENT_RESOLVE_BEGIN), replace `refl.type` with a [ReflectionType](https://typedoc.org/api/classes/Models.ReflectionType.html) which describes that interface.

Notes:
- ReflectionType expects that the DeclarationReflection passed to its constructor is owned by it, not a reference to something somewhere else in the site. If you do that, it might mostly work, but will likely break some links
- The `DeclarationReflection` created must be passed to [ProjectReflection.registerReflection](https://typedoc.org/api/classes/Models.ProjectReflection.html#registerReflection) or links between reflections will break.
- The `DeclarationReflection`'s `kind` should be [ReflectionKind.TypeLiteral](https://typedoc.org/api/enums/Models.ReflectionKind-1.html#TypeLiteral)

**Comment by marcog83** [comment]
Great i'll give it a try, and let you know
Thanks for help
