### ISSUE TITLE
Generating documentation for a constructed class?

### ISSUE THREAD

**Issue by greggman** [TypeStrong/typedoc#2579]
## Search terms

`'inner'` found

* https://github.com/TypeStrong/typedoc/issues/2476
* https://github.com/TypeStrong/typedoc/issues/1581

## Question

I have code like this

```js
export function getSomeClassImpl<T extends ArgType>(TypeCtor: new(n: number) => T) {
  type Type = T;

  /**
   * SomeClass functions
   */
  class SomeClassImpl {
    /**
     * Negates someClass.
     * @param s - The source.
     * @param dst - type to hold result. If not passed a new one is created.
     * @returns -s.
     */
    static negate(s: ArgType, dst?: Type): Type {
      dst = dst || new TypeCtor(s.length);

      for (let i = 0; i < s.length; ++i) {
        dst[i] = -s[i];
      }

      return dst;
    }
  }

  return SomeClassImpl;
}
```

And I use that toe generate 3 versions of this class with different types

```js
import {getSomeClassImpl} from './someclass';

const someClassF32 = getSomeClassImpl(Float32Array);
const someClassF64 = getSomeClassImpl(Float64Array);
const someClassArray = getSomeClassImpl(Array);

export {
  someClassF32,
  someClassF64,
  someClassArray,
};
```

When I generate the docs I get this

```js
[warning] SomeClassImpl, defined in ./src/someclass.ts, is referenced by someClassArray but not included in the documentation.
```

Which then of course, like it says, is not included in the docs.

What I kind of don't get though is `someClassF32` etc are exported. Yet they aren't documented. Well, they just say 

```
someClassF32: typeof SomeClassImpl = ...
```

Further, typescript itself (or whatever VSCode uses to show intellisense) show docs 

<img width="893" alt="Screenshot 2024-05-25 at 10 49 03" src="https://github.com/TypeStrong/typedoc/assets/234804/9c08001f-dfb8-4b7e-9526-8503b6864fa5">

As those functions are part of the public API.

So it kind of feels like typedoc should also be generating docs. No?

**Comment by Gerrit0** [comment]
In an attempt to maintain some sanity when dealing with the compiler API, TypeDoc makes the assumption that it's reasonable to document variables *as variables* unless instructed otherwise or incredibly obvious that they should be something else (e.g. `const x = () => 1` is obviously intended to be a function)

```ts
const someClassF32 = getSomeClassImpl(Float32Array);
```

is not obviously a class looking at the nodes used to declare it, so TypeDoc doesn't document it as one. Either of the following will give you docs like what you want:

```ts
/** @class */
const someClassF32 = getSomeClassImpl(Float32Array);

class someClassF32 extends getSomeClassImpl(Float32Array) {}
```

**Comment by greggman** [comment]
Wow, such a quick response. Thank you so much and thank you for typedoc!
