### ISSUE TITLE
Feature request: display warning and error count like eslint.

### ISSUE THREAD

**Issue by bladerunner2020** [TypeStrong/typedoc#2581]
## Problem

TypeDoc doesn't show the number of warnings and errors (though it does calculate them!). If a project has a lot of warnings (as it is in our case), it would be very convenient to see the number of warnings to ensure that the count goes down over time and not up.

## Suggested Solution

I suggest displaying the warning and error count like ESLint does. Possible outputs:

- if there are only warnings: `[warning] Found 0, error(s), 70 warning(s). `
- if there are errors: `[error] Found 1, error(s), 70 warning(s).`

Considering that TypeDoc already counts errors and warnings, it should only take a couple of lines to add this feature.

I don't mind to make a PR.

**Comment by Gerrit0** [comment]
Seems like a reasonable request, go for it!

**Comment by Gerrit0** [comment]
Included in TypeDoc 0.26, which is releasing 2024/06/21
