### ISSUE TITLE
How to document each type in `export type Foo = 'foo1' | 'foo2'?

### ISSUE THREAD

**Issue by ibc** [TypeStrong/typedoc#2585]
## Question

Basically I need those 'foo1' and 'foo2'. being documented:

```ts
/**
 * Foo valid values.
 */
export type Foo =
	/**
	 * Doc of foo1.
	 */
	| 'foo1'
	/**
	 * Doc of foo2.
	 */
	| 'foo2';
```

However generated docs look like this (documentation about 'foo1' and 'foo2' is not parsed/included):

![CleanShot 2024-06-03 at 17 54 01@2x](https://github.com/TypeStrong/typedoc/assets/16191/8e3ad920-cef4-4e74-8a7b-726d0f488fe4)

I know that I could make it "work" by doing this complex thing:

```ts
/**
 * Doc of foo1.
 */
export type Foo1 = 'foo1';

/**
 * Doc of foo2.
 */
export type Foo2 = 'foo2';

/**
 * Foo valid values.
 */
export type Foo = Foo1 | Foo2;
```

It would produce this:

![CleanShot 2024-06-03 at 17 55 23@2x](https://github.com/TypeStrong/typedoc/assets/16191/6642dfcc-a65e-4048-a496-0d786f6cb230)
![CleanShot 2024-06-03 at 17 55 41@2x](https://github.com/TypeStrong/typedoc/assets/16191/73baa882-a8e4-45c7-b007-567b1f44820e)
![CleanShot 2024-06-03 at 17 55 49@2x](https://github.com/TypeStrong/typedoc/assets/16191/e483b64a-8410-4d3f-984a-1820c19b87e2)

But this is definitely too complex and definitely not desirable at all. Having to click on each type to see how a string looks is too much. Do I miss something?

**Comment by Oblarg** [comment]
You cannot; this is a tsdoc limitation.

https://github.com/microsoft/tsdoc/issues/164

**Comment by ibc** [comment]
Understood. Funny thing is that in that issue I found this comment :)

![CleanShot 2024-06-05 at 15 44 41@2x](https://github.com/TypeStrong/typedoc/assets/16191/cc14813f-bce4-4a55-8c2e-c82b0b108073)

https://github.com/microsoft/tsdoc/issues/164#issuecomment-692810066

**Comment by Gerrit0** [comment]
My recommendation for this today is to use [`@enum`](https://typedoc.org/tags/enum/) , and export an enum-object.

```ts
/**
 * This will be displayed as an enumeration.
 * @enum
 */
export const Foo = {
    /**
     * Doc comments may be included here.
     */
    foo1: "foo2",
    foo2: "foo2",
} as const;

// This will be hidden, but produces the same type as in the OP
export type Foo = typeof Foo[keyof typeof Foo];
```

I looked at supporting this in TypeDoc, but doing so requires an unfortunately large number of hacky assumptions, and essentially requires re-implementing (parts of) a lexer for TypeScript. Without [TypeScript support](https://github.com/microsoft/TypeScript/issues/38106) I find the `@enum` version is better for downstream consumers anyways.

**Comment by ibc** [comment]
Thanks. But not sure this trick will be useful because my real case is more complex. I would need to declare a const Foo like this:

```
const MyEvent = {
  /**
   * Doc of event "foo1" with clickable links
   * to AnotherType2 and AnotherType3.
   */
  "foo1": AnotherTypeA<[param1: AnotherType1, param2: AnotherType2]>
   // etc
} as const;
```

I am 99% sure that the `export type MyEvent` you suggested won't render clickable links to those AnotherTypeN types because an enum is supposed to have numbers of string as values and not complex types. I may be wrong. Will test it on next Monday.

Thanks a lot.

**Comment by Oblarg** [comment]
This is a really big missing feature in TypeScript/TSDoc.

So far my approach has been to ban inline type definitions in unions beyond a very rudimentary base complexity, and settle with requiring our users to click through to the component definition.  Together with enforcing that "primitive" object literal types be tagged with `@interface` (I do not use `interface` in code, typically, because tooltip renderers can't expand it), the result ends up pretty easy to follow:

![image](https://github.com/TypeStrong/typedoc/assets/23393863/7f62a98f-9981-46c9-9c46-6907d64a92d1)

Anything green is a single "primitive" event; anything in red is still structured/algebraic.

Huge credit to @Gerrit0; this is a lot better than it was a year ago, even with the current limitations.

**Comment by Gerrit0** [comment]
I spent a bit of time poking around in https://ts-ast-viewer, and it looks like supporting this (*specifically* for type alias unions) is slightly less messy than I remember... still not great, but it looks possible without an unacceptably large amount of hackery.

**Comment by Gerrit0** [comment]
... I didn't expect that to take ~4 hours to implement, but there were lots of rabbit holes. In 0.26.0-beta.3 (publishing sometime today)

```ts
/**
 * Represents a parsed piece of a comment.
 * @category Comments
 * @see {@link JSONOutput.CommentDisplayPart}
 */
export type CommentDisplayPart =
    /**
     * Represents a plain text portion of the comment, may contain markdown
     */
    | { kind: "text"; text: string }
    /**
     * Represents a code block separated out form the plain text entry so
     * that TypeDoc knows to skip it when parsing relative links and inline tags.
     **/
    | { kind: "code"; text: string }
    /**
     * Represents an inline tag like `{@link Foo}`
     */
    | InlineTagDisplayPart
    /**
     * Represents a reference to a path relative to where the comment resides.
     * This is used to detect and copy relative image links.
     */
    | RelativeLinkDisplayPart;
```

is now rendered as:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/2655a7b9-c5f2-424b-b051-8ecdeaafe3a8)

**Comment by ibc** [comment]
Yes, indeed I was already using a `type` with many `|` as a workaround for it, but looks a bit cumbersome:

```ts
/**
 * Events emitted by the {@link Notifier} class.
 */
export type NotifierEvents =
  | NotifierWaitingForJoinApprovalEvent
  | NotifierYouHaveBeenAuthorizedToJoinEvent
  | NotifierAttendeeHasJoinedEvent
  | NotifierAttendeeHasLeftEvent
  | NotifierAttendeeJoinRequestEvent
  | NotifierMediaDeviceErrorEvent
  | NotifierNoMediaDeviceEvent
  | NotifierAudioInputDeviceChangedEvent
  | NotifierAudioOutputDeviceChangedEvent
  | NotifierVideoInputDeviceChangedEvent
  | NotifierCameraFilterEvent
  | NotifierMicrophoneDisconnectedEvent
  | NotifierCameraDisconnectedEvent
  | NotifierRemoteMutedEvent;
```

![CleanShot 2024-06-10 at 10 48 01@2x](https://github.com/TypeStrong/typedoc/assets/16191/7f8883f0-6ae9-484e-830c-8feaf656febc)

Definitely I wanted to avoid this look and feel in which the user needs to click on every item to see its definition. Now I understand that this is not even supported by core `tsdoc` so will live with it.

Thanks a lot.

NOTE: Feel free to close this issue if you think that it doesn't make sense to keep it open.

**Comment by Oblarg** [comment]
@Gerrit0 thanks a ton for addressing this; it'll be super useful.

I use algebraic types a *lot*, and documenting them has been the hardest problem by far.  Tools like this matter.

**Comment by Gerrit0** [comment]
Fixed with 0.26, which is releasing 2024/06/21

**Comment by Oblarg** [comment]
@Gerrit0 you rule!  will immediately be bumping our version upon release.

**Comment by ibc** [comment]
Tested. This is amazing. Thanks!
