### ISSUE TITLE
Missing doc when returned field is not an object literal

### ISSUE THREAD

**Issue by xixixao** [TypeStrong/typedoc#2587]
## Search terms

return fields properties

## Expected Behavior

Input:

```ts
export function foo() {
  const x = {
    /**
     * This one is fine.
     */
    a: 1,
  };
  return {
    /**
     * This one is missing.
     */
    x,
  };
}
```

Output:

Includes both comments.

## Actual Behavior

The `This one is missing.` comment is not included.

But note that TypeScript has no problem generating a correct declaration file with the comment:

```ts
export declare function foo(): {
    /**
     * This one is missing.
     */
    x: {
        /**
         * This one is fine.
         */
        a: number;
    };
};
```

## Steps to reproduce the bug

As shown above.

## Environment

-   Typedoc version: 0.25.13
-   TypeScript version: 5.0.4
-   Node.js version: 18.17.0
-   OS: macOS

**Comment by Gerrit0** [comment]
I actually noticed + fixed this when investigating #2582, it's fixed in the latest beta
