### ISSUE TITLE
Keep enum/const name instead of displaying number or string as return type

### ISSUE THREAD

**Issue by ibc** [TypeStrong/typedoc#2588]
## Search Terms

const, enums

## Problem

Some enums/consts are displayed as `number` instead of the TS name they have. Example:

```ts
/**
 * Camera casual filters.
 *
 * @enum
 */
export const CameraCasualFilters = {
  NoFilter: 0,
  FilterFoo: 1,
  FilterBar: 2,
} as const;

/**
 * TS trick.
 * @hidden
 */
export type CameraCasualFilters = typeof CameraCasualFilters[keyof typeof CameraCasualFilters];

/**
 * Currently selected camera filter.
 */
get cameraFilter(): CameraCasualFilters {
  return this.filterId;
}
```

The generated Typedoc API looks like this:

![CleanShot 2024-06-11 at 11 45 36@2x](https://github.com/TypeStrong/typedoc/assets/16191/932c6dd6-d7db-4608-a080-698c8b86c5f4)

Why does it say that return type is `number` instead of `CameraCasualFilters`? That doesn't help at all.

## Suggested Solution

Honor type/enum names in return types of function despite they are just numbers or strings.

**Comment by Gerrit0** [comment]
TypeDoc gets the type to use from TypeScript's type checker, so if TypeScript says the type is just `number`, that's what TypeDoc will display.

You can make TypeDoc display the type you'd want by making the `CameraCasualFilters` a type which is in every way compatible with `number` but is distinct from it:

```ts
export type CameraCasualFilters = {} & (typeof CameraCasualFilters)[keyof typeof CameraCasualFilters];
```

The `{} &` triggers TypeScript's type alias preservation which will allow TypeDoc to pick up the name. Once you've done this, TypeDoc displays:

![image](https://github.com/TypeStrong/typedoc/assets/19329837/277f3f72-a418-43b8-8017-e74f9d994736)

Also a note: You don't need `@hidden` on the type alias, `@enum` will automatically cause the alias to not be converted

**Comment by ibc** [comment]
Wow, amazing!. Thanks a lot. Works perfectly.
