### ISSUE TITLE
`0.26 Beta`: Add `json5` to defaults in option declaration for `highlightLanguages` .

### ISSUE THREAD

**Issue by typhonrt** [TypeStrong/typedoc#2593]
`json5` was previously supported or enabled by default in TypeDoc `0.25.x`. 

With the TypeDoc 0.26 beta the new `highlightLanguages` option default does not include `json5`. I'd say a good candidate to add to the default as it is widely used and makes it easy to add comments to example JSON blocks. 

I have tested that simply adding "json5" to the `highlightLanguages`  provides default support.

Info on [JSON5](https://json5.org/). The [NPM package](https://www.npmjs.com/package/json5) has 70+MM weekly downloads, so is popular. This is compared to `jsonc` which is included in the default which has [~80k weekly downloads](https://www.npmjs.com/package/jsonc)

**Comment by Gerrit0** [comment]
It's absurd to me that json5 gets that many downloads... that parser has awful non-linear performance!

I consider TypeScript to be the canonical jsonc parser, with 51 million weekly downloads, but [jsonc-parser](https://www.npmjs.com/package/jsonc-parser) used by VSCode has a nice 17 million as well.

That said, it seems reasonable to load the json5 grammar by default, it's only an extra 3.87kb and one extra file, for something that's widely used.

**Comment by typhonrt** [comment]
That makes more sense re `jsonc-parser` as the main NPM package. And I agree JSON5 is not the best per se. I had several repos using it in markdown comment blocks though just to add comments in the blocks for documentation. Easy enough not to trip folks up upgrading TypeDoc.

**Comment by Gerrit0** [comment]
Added in v0.26.0-beta.4
