### ISSUE TITLE
Deprecate Google Analytics Integration

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#2600]
## Search Terms

gaId, privacy, gdpr, cookies

## Problem

TypeDoc supports specifying a `gaId` option. When set, this causes TypeDoc to include Google Analytics tracking code in the generated pages. This causes a problem for anyone attempting to comply with the [EU Cookie Law](https://www.termsfeed.com/blog/eu-cookies-directive/) as TypeDoc does **not** generate a cookie banner.

## Suggested Solution

Push the `gaId` option to an external plugin. I could generate a cookie banner within TypeDoc, but other plugins (like typedoc-clarity-plugin) also ought to cause this to be generated, so TypeDoc's check would have to be externally controlled.

**Comment by euberdeveloper** [comment]
Are you aware of any google analytics plugin? I would like to migrate

**Comment by Gerrit0** [comment]
I am not aware of any. Replacing the clarity code with google analytics from typedoc-plugin-clarity seems like an easy way to make one though: https://github.com/matteobruni/typedoc-plugins/blob/main/plugins/clarity/src/index.tsx

**Comment by Gerrit0** [comment]
One can be easily constructed from the code in 1b55285f18cae26ac1cb3c814b6c64ae9809bea9

```console
$ typedoc --plugin ./analytics.mjs
```

```js
// @ts-check
// Apache License 2.0 - https://github.com/TypeStrong/typedoc/blob/master/LICENSE
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.options.addDeclaration({
        name: "gaID",
        help: "Set the Google Analytics tracking ID and activate tracking code",
        type: td.ParameterType.String,
    });

    app.renderer.hooks.on("body.end", () => {
        const gaID = app.options.getValue("gaID");
        if (gaID) {
            const script = `
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '${gaID}');
`.trim();
            return td.JSX.createElement(td.JSX.Fragment, null, [
                td.JSX.createElement("script", {
                    async: true,
                    src: "https://www.googletagmanager.com/gtag/js?id=" + gaID,
                }),
                td.JSX.createElement("script", null, td.JSX.createElement(td.JSX.Raw, { html: script })),
            ]);
        }
        return td.JSX.createElement(td.JSX.Fragment, null);
    });
}
```

**Comment by euberdeveloper** [comment]
I think in the official docs website, `gaId ` is still specified as a possible option

**Comment by Gerrit0** [comment]
Fixed with https://github.com/TypeStrong/typedoc-site/commit/c43e28b27c595ba10ee9c8839ec705b2ffb42530, thanks

**Comment by euberdeveloper** [comment]
> One can be easily constructed from the code in [1b55285](https://github.com/TypeStrong/typedoc/commit/1b55285f18cae26ac1cb3c814b6c64ae9809bea9)
> 
> ```
> $ typedoc --plugin ./analytics.mjs
> ```
> 
> ```js
> // @ts-check
> // Apache License 2.0 - https://github.com/TypeStrong/typedoc/blob/master/LICENSE
> import td from "typedoc";
> 
> /** @param {td.Application} app */
> export function load(app) {
>     app.options.addDeclaration({
>         name: "gaID",
>         help: "Set the Google Analytics tracking ID and activate tracking code",
>         type: td.ParameterType.String,
>     });
> 
>     app.renderer.hooks.on("body.end", () => {
>         const gaID = app.options.getValue("gaID");
>         if (gaID) {
>             const script = `
> window.dataLayer = window.dataLayer || [];
> function gtag(){dataLayer.push(arguments);}
> gtag('js', new Date());
> gtag('config', '${gaID}');
> `.trim();
>             return td.JSX.createElement(td.JSX.Fragment, null, [
>                 td.JSX.createElement("script", {
>                     async: true,
>                     src: "https://www.googletagmanager.com/gtag/js?id=" + gaID,
>                 }),
>                 td.JSX.createElement("script", null, td.JSX.createElement(td.JSX.Raw, { html: script })),
>             ]);
>         }
>         return td.JSX.createElement(td.JSX.Fragment, null);
>     });
> }
> ```

Hello, this plugin has been done today, it can be found here: https://www.npmjs.com/package/typedoc-plugin-ga

Feedback would be nice, also, can it be added to typedoc's documentation, in the plugins' list?

**Comment by Gerrit0** [comment]
It will automatically be picked up when the site rebuilds tonight

**Comment by euberdeveloper** [comment]
It didn't appear

**Comment by Gerrit0** [comment]
Ah, that's because you don't have a peerDependency declared. Setting it to 0.26.x will make it show up.
