### ISSUE TITLE
Support `@author` tag

### ISSUE THREAD

**Issue by regseb** [TypeStrong/typedoc#2603]
## Search terms

`@author`

## Expected Behavior

TypeDoc supports [`@author`](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#author) tag.

## Actual Behavior

TypeDoc repport: `Encountered an unknown block tag @author`

### `package.json`

```json
{
  "name": "testcase",
  "version": "1.0.0",
  "dependencies": {
    "typedoc": "0.26.0",
    "typescript": "5.5.2"
  }
}
```

### `tsconfig.json`

```json
{
  "typedocOptions": {
    "entryPoints": ["index.ts"]
  }
}
```

### `index.ts`

```typescript
/**
 * @author Ian Awesome
 */
```

### Steps

1. `npm install`
2. `npx typedoc`

   ```
   ./index.ts:2:3 - [warning] Encountered an unknown block tag @author

   2     * @author Ian Awesome

   [info] Documentation generated at ./docs
   [warning] Found 0 errors and 1 warnings
   ```

## Environment

-   Typedoc version: 0.26.0
-   TypeScript version: 5.5.2
-   Node.js version: 20.14.0
-   OS: Ubuntu 22.04.4 LTS

**Comment by Gerrit0** [comment]
Since I suspect more people will run into similar issues, linking https://github.com/TypeStrong/typedoc/issues/2614#issuecomment-2187850425 here as well
