### ISSUE TITLE
Doesn't find anchor in README.md

### ISSUE THREAD

**Issue by regseb** [TypeStrong/typedoc#2604]
## Search terms

relative, path, anchor, markdown, README

## Expected Behavior

TypeDoc shouldn't report any problems for links in the README.md to a header also in the README.md.

## Actual Behavior

TypeDoc report: _The relative path #foo does not exist_

### `package.json`

```json
{
  "name": "testcase",
  "version": "1.0.0",
  "dependencies": {
    "typedoc": "0.26.0",
    "typescript": "5.5.2"
  }
}
```

### `README.md`

```markdown
[foo](#foo)

## foo

Bar.
```

### `tsconfig.json`

```json
{
  "typedocOptions": {
    "entryPoints": ["index.ts"]
  }
}
```

### `index.ts`

```typescript
// Unimportant.
```

### Steps

1. `npm install`
2. `npx typedoc`

   ```
   ./README.md:1:6 - [warning] The relative path #foo does not exist

   1    [foo](#foo)

   [info] Documentation generated at ./docs
   [warning] Found 0 errors and 1 warnings
   ```

## Environment

- Typedoc version: 0.26.0
- TypeScript version: 5.5.2
- Node.js version: 20.14.0
- OS: Ubuntu 22.04.4 LTS

**Comment by Gerrit0** [comment]
Ah, yeah that's a problem... I forgot about anchor links when looking for relative links.
