### ISSUE TITLE
The lines reported aren't the lines with errors

### ISSUE THREAD

**Issue by regseb** [TypeStrong/typedoc#2605]
## Search terms

line, code, block, markdown, README

## Expected Behavior

The error lines reported correspond to the lines where there are problems.

## Actual Behavior

Other lines are reported.

### `package.json`

```json
{
  "name": "testcase",
  "version": "1.0.0",
  "dependencies": {
    "typedoc": "0.26.0",
    "typescript": "5.5.2"
  }
}
```

### `README.md`

````markdown
foo
bar
baz
qux

```javascript
// Without this code block, the reported warning lines are good.
```

[quux](#quux)
[corge](#corge)
[grault](#grault)
````

### `tsconfig.json`

```json
{
  "typedocOptions": {
    "entryPoints": ["index.ts"]
  }
}
```

### `index.ts`

```typescript
// Unimportant.
```

### Steps

1. `npm install`
2. `npx typedoc`

   ```
   ./README.md:3:1 - [warning] The relative path #quux does not exist

   3    baz

   ./README.md:5:8 - [warning] The relative path #corge does not exist

   5    ```javascript

   ./README.md:6:10 - [warning] The relative path #grault does not exist

   6    // Without this code block, the reported warning lines are good.

   [info] Documentation generated at ./docs
   [warning] Found 0 errors and 3 warnings
   ```

## Environment

- Typedoc version: 0.26.0
- TypeScript version: 5.5.2
- Node.js version: 20.14.0
- OS: Ubuntu 22.04.4 LTS

**Comment by Gerrit0** [comment]
Wow, this has been wrong since I originally added reporting for positions in non-ts source files... 2 years ago.

The issue is in MinimalSourceFile.getLineAndCharacterOfPosition, where it incorrectly handles multiple consecutive newlines.

**Comment by Gerrit0** [comment]
... well, that was one of the things that was wrong. The code block was revealing another bug too!
