### ISSUE TITLE
Wrap customFooterHtml content with `<p class="tsd-generator">` by default

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2608]
## Search Terms

footer

## Problem

Currently, `customFooterHtml` by default wraps the content with `<p>`. This leads to styles unaligned with "Generated by TypeDoc":

![image](https://github.com/TypeStrong/typedoc/assets/325476/a80b1689-d544-4767-97fa-7f6be5e43622)

## Suggested Solution

By default, wrap `customFooterHtml` with `<p class="tsd-generator">` (or assign an alternative class name)

![image](https://github.com/TypeStrong/typedoc/assets/325476/18305f89-b591-4f5f-9673-f47bd25ab074)

**Comment by Gerrit0** [comment]
Shoot, I thought that's how it was set up... apparently I never actually looked at it in a browser.

**Comment by xuhdev** [comment]
Oddly I couldn't reproduce it on a different machine...
