### ISSUE TITLE
Consider adding `text` to the default `highlightLanguages` option

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2610]
## Search terms

syntax highlighting

## Expected Behavior

Since typedoc defaults code blocks to typescript, the [plain text syntax highlighter](https://shiki.style/languages#plain-text) should work out of the box.

## Actual Behavior

If not modifying `highlightLanguages`, typedoc would issue a warning:

```
[warning] Code block with language text will not be highlighted in comment for ... as it was not included in the highlightLanguages option
```

## Environment

-   Typedoc version: 0.26.1

## Additional Context

This is only a request, since a user can always add `text` to `highlightLanguages`. However, since `text` is so common, I request considering adding it as default.

**Comment by Gerrit0** [comment]
I agree, text should be included.

**Comment by TechQuery** [comment]
@Gerrit0 `yml` or `yaml` has the same issue.
