### ISSUE TITLE
Is it possible to suppress warnings from node_modules files?

### ISSUE THREAD

**Issue by crystalfp** [TypeStrong/typedoc#2611]
## Search terms

node_modules, warning

## Question
Running typedoc on my application generates plenty of warnings from modules under `node_modules` on which I have no control. For example:
```
./node_modules/@types/node/events.d.ts:512:11 - [warning] Encountered an unknown block tag @since

512             * @since v0.11.2

./node_modules/electron/electron.d.ts:3883:7 - [warning] Encountered an unknown block tag @platform

3883         * @platform win32,linux
```
These modules are not in the list of files passed to typedoc, but are indirectly loaded from input statements.
This huge list of warnings obscures genuine warnings from my code.
Thanks for your help!
mario

**Comment by Gerrit0** [comment]
Hmm.. that's a rather annoying problem. Currently no, I'm going to go add a `suppressCommentWarningsInDeclarationFiles` option right now though.

**Comment by crystalfp** [comment]
The new option works and helped a lot. Thanks!
