### ISSUE TITLE
How to put a mail address link in the comments?

### ISSUE THREAD

**Issue by crystalfp** [TypeStrong/typedoc#2613]
## Search terms

link,mail

## Question
Want to add the mail address of the author in the comment, but typedoc complains. The file header comment is:
```
/**
 * Creating/closing windows and setup communications to them
 * @packageDocumentation
 * @author [John Doe](mailto:jdoe\@example.com)
 */
```
And the error is:
```
./src/electron/modules/WindowsUtilities.ts:6:25 - [warning] The relative path mailto:jdoe@example.com does not exist
```
Tried also with `{@link mailto:jdoe\@example.com}` with the same result. Seems the only solution is to put the mail address as a normal string:
```
 * @author John Doe "jdoe\@example.com"
 ```
Any suggestion?
Thanks!
mario

**Comment by Gerrit0** [comment]
That's a bug, TypeDoc shouldn't be recognizing that as a relative link
