### ISSUE TITLE
Righthand sidebar should nest one level further to reflect page groups

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2616]
## Search Terms

navigation sidebar groups collapsible

## Problem

Page categories (e.g. methods, properties, accessors, etc) are not reflected on the right-hand "on this page" navbar.

## Suggested Solution

Page categories should be represented in the "on this page" navbar, with collapsible sub-categories matching the group divisions on the page.

**Comment by Gerrit0** [comment]
At first I thought it was kind of crazy to include dropdowns for portions of the table of contents... and then I implemented it, wow, how did I not do this when doing the TOC initially?! This is so much nicer!

**Comment by Oblarg** [comment]
Yeah, for large namespaces it's a total gamechanger.  Love the quick turnaround, and loving 0.26!  Keep up the awesome work, it makes my job way easier :)
