### ISSUE TITLE
TypeDoc generates an insanely large 16GB output on a pnpm monorepo with lots of packages

### ISSUE THREAD

**Issue by AlexAegis** [TypeStrong/typedoc#2617]
## Search terms

pnpm, monorepo, symlink

## Expected Behavior

To produce a small output

## Actual Behavior

The TypeDoc output is large, all inter-package dependencies are duplicated in the individual package output folders.

I don't remember this being a problem in earlier versions, I've been using `"entryPointStrategy": "packages"` for a while now. Also do note that while `"node_modules/**"` is not part of the "exclude" array, I did try it and made no difference.

![image](https://github.com/TypeStrong/typedoc/assets/16900547/53cc3205-8ba1-47ad-9e24-606b14ce86ac)

The `ncdu` output might give a better idea, each dependency and their dependencies are present in every `media` folder. Each of these dependencies are part of this repository.

## Steps to reproduce the bug

> Given the nature of the problem I can only provide a large repo as example

```sh
npm i -g pnpm
git clone -b typedoc https://github.com/AlexAegis/js-tooling
pnpm i
pnpm typedoc_
```

Then check the size of `.cache/typedoc`

## Environment

-   Typedoc version: 0.26.2
-   TypeScript version: 5.5.2
-   Node.js version: v20.14.0
-   OS: arch

**Comment by Gerrit0** [comment]
The cause of this is your readme:

```md
## config providers

These packages only contain configurations, that could be independently used

- [commitlint-config](packages/commitlint-config/)
- [eslint-config-core](packages/eslint-config-core/)
- [eslint-config-vitest](packages/eslint-config-vitest/)
- [lint-staged-config](packages/lint-staged-config/)
- [prettier-config](packages/prettier-config/)
- [remark-preset](packages/remark-preset/)
- [standard-version](packages/standard-version/)
- [stylelint-config](packages/stylelint-config/)
- [ts](packages/ts/)
- [turbowatch](packages/turbowatch/)
- [vite](packages/vite/)
- [vitest](packages/vitest/)
```

TypeDoc is seeing those relative links and deciding that they mean it ought to copy those directories to your documentation site. I didn't intend for relative link copying to include directories. With a patch to ignore directories, the generated site is back down to 2.1mb.
