### ISSUE TITLE
@description tag missing from default

### ISSUE THREAD

**Issue by Bugs5382** [TypeStrong/typedoc#2618]
## Search Terms

description,since,block

## Problem

Like `@since` (#2614), `@description` is a valid JSdoc tag. When properly used in an IDE it shows up like this:

From:

<img width="979" alt="image" src="https://github.com/TypeStrong/typedoc/assets/12115015/74f35864-0ebd-4cac-9d4e-2dcd8427eecf">

To:

<img width="745" alt="image" src="https://github.com/TypeStrong/typedoc/assets/12115015/e060eabe-7891-4f2b-bfb4-c133a711e0e4">

... in the rendered view indicating more description/expanding from the "title." It might have been removed as the default by accident.

## Suggested Solution

I am working on a PR.

**Comment by Gerrit0** [comment]
> If there's both a description at the beginning of a JSDoc comment and a description provided with the @description tag, the description specified with the @description will override the description at the beginning of the comment. - [JSDoc](https://jsdoc.app/tags-description)

This behavior is not respected by typedoc, and frankly it sounds like a terrible idea to me, which is why `@description` is not included in the list of default tags.

As your IDE obviously isn't following this behavior either, my question is - why is this tag useful over just including a paragraph break in the comment summary section?

```ts
/**
 * Some docs
 *
 * More docs that were previously under `@description
 */
```

**Comment by Bugs5382** [comment]
@Gerrit0 I see the “title” of the function/code as one thing and a more description about what it does in its own section.  While I can see this as a burden to add, JSDOC shows https://jsdoc.app/tags-description being a type. Though it notes that the tag overrides the rest of the comment.

The  https://jsdoc.app/tags-summary tag seems to be the “short” description and/or  summary of what the long stuff. Maybe switch this out for @summary ,,,,

**Comment by Gerrit0** [comment]
It sounds like what you want is provided by TypeDoc's [`@remarks`](https://typedoc.org/tags/remarks/) tag.

The `@summary` tag isn't a great fit either as typedoc renders the non-tagged content first.

**Comment by Bugs5382** [comment]
@Gerrit0 Remarks it is! 👍
