### ISSUE TITLE
Differentiate an Interface and an Enum element with the same name.

### ISSUE THREAD

**Issue by MaPUILabs** [TypeStrong/typedoc#262]
Hello,

I want to link an Interface in a methode definition like this : 

``` typescript
/**
   * Get an array of [[FooBar]]
   * @param id
   */
  public getSomeFooBar = (id : Id) : FooBar => {
    /*...*/
  };
```

The probleme is that I have an `Interface` named "FooBar", but also an `Enum` containing an element named "FooBar", so the link refers to the Enum and not the Interface.

Is there a way to manually specify that I want to refer to the Interface ?

**Comment by aciccarello** [comment]
I think this is a TypeScript issue and intentional.

**Comment by SamuraiJack** [comment]
Huh, this is still not resolved since 2016? I have exactly the same problem.

It is not reasonable to expect the "plain" `[[LinkTarget]]` scheme to work. Need to take into account name collisions.

**Comment by aciccarello** [comment]
How would you expect it to know which reflection to point to?

Microsoft is working on defining a specific format for doc comments that would have a much more robust (and complex) symbol reference syntax.

**Comment by SamuraiJack** [comment]
> How would you expect it to know which reflection to point to?

By using "much more robust (and complex) symbol reference syntax" of course. The first thing that comes into mind is something like: `[[interface:Name]]`. But then this is can be only a shortcut too, since there can be easily 2 interfaces with the same name. The full syntax could be: `[[filename.ts:interface:Name]]` (just an idea).

Any link to the Microsoft work?

**Comment by aciccarello** [comment]
Here it is: Microsoft/tsdoc#9

I think that TypeDoc should support the tsdoc syntax since it should be more standard (assuming it stabilizes) as opposed to making our own syntax.

**Comment by SamuraiJack** [comment]
Agree. Seems they haven't decided yet?
