### ISSUE TITLE
bug: @link is not working, but in other places refering the same function, it is working.

### ISSUE THREAD

**Issue by Bugs5382** [TypeStrong/typedoc#2620]
## Search terms

```@link```, inline, ```@default```, warning

## Expected Behavior

I expected these errors not to exist.

## Actual Behavior

```> node-hl7-client@2.3.1 typedoc
> typedoc

[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_4_MSH.msh_10
[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_5_MSH.msh_10
[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_5_1_MSH.msh_10
[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_6_MSH.msh_10
[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_7_MSH.msh_10
[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_7_1_MSH.msh_10
[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_8_MSH.msh_10
[info] Documentation generated at ./docs
[warning] Found 0 errors and 7 warnings

Process finished with exit code 0
```

## Steps to reproduce the bug

In the code: 

Function: https://github.com/Bugs5382/node-hl7-client/blob/dcc0f10324582f1632a25ad1614a264346db6988/src/utils/utils.ts#L170-L180

Working Line: https://github.com/Bugs5382/node-hl7-client/blob/dcc0f10324582f1632a25ad1614a264346db6988/src/specification/2.1.ts#L36
Working Line Output: https://bugs5382.github.io/node-hl7-client/interfaces/HL7.HL7_2_1_MSH.html#msh_10 - Shows a good link to the function in CORE namespace as well.

This line (https://github.com/Bugs5382/node-hl7-client/blob/dcc0f10324582f1632a25ad1614a264346db6988/src/specification/2.4.ts#L44) produces the error/warning:
```
[warning] Failed to resolve link to "randomString" in comment for HL7.HL7_2_4_MSH.msh_10
```

... yet I can not find any difference in the two lines of code. The actual output of the docs is here: https://bugs5382.github.io/node-hl7-client/interfaces/HL7.HL7_2_4_MSH.html#msh_10 showing no link.

So I got no clue since the spelling, format, design, etc., are the same in the other files

## Environment

-   Typedoc version: 0.26.3
-   TypeScript version: 5.5.2
-   Node.js version: v20.15.0
-   OS: MacOS 14.5 (23F79)

**Comment by Gerrit0** [comment]
This is happening because in one file, you have imported `randomString`, so TypeDoc notices that TypeScript has resolved the link already, and uses it.

In the other file, there is no import, so TypeScript can't resolve the link. This causes TypeDoc to fall back to using [declaration references](https://typedoc.org/guides/declaration-references/) to resolve the link.

Looking at your docs, it looks like `{@link CORE.randomString}` should work.

**Comment by Bugs5382** [comment]
*sigh*. Once again, you are right, @Gerrit0. So closing this issue. I had to refactor my code cause CORE.randomString was not resolving for my interfaces/types..
