### ISSUE TITLE
TSDoc @link cannot be written with # delimiter

### ISSUE THREAD

**Issue by yoursunny** [TypeStrong/typedoc#2621]
## Search terms

tsdoc, \@link, tsdoc-reference-missing-hash

## Expected Behavior

When a \@link tag is written with `#` delimiter between NPM scope and import path, TypeDoc should recognize this syntax.
[The `#` delimiter is suggested by TSDoc spec](https://tsdoc.org/pages/tags/link/), despite that it's [labeled as "not finalized"](https://github.com/microsoft/tsdoc/issues/9).

## Actual Behavior

TypeDoc rejects the `#` delimiter and requires it to be rewritten with `!` delimiter.
See build log: https://github.com/TypeStrong/typedoc-repros/actions/runs/9732291154/job/26857760496

```text
[warning] Failed to resolve link to "@typedoc/lib#LibInt" in comment for @typedoc/wrapping-lib.wrappingLibFunc. You may have wanted "@typedoc/lib!LibInt"
```

If I rewrite it with `!` as TypeDoc currently wants, eslint-plugin-tsdoc would trigger a tsdoc-reference-missing-hash warning, indicating that the TSDoc has an error.

## Steps to reproduce the bug

https://github.com/TypeStrong/typedoc-repros/pull/42

## Environment

-   TypeDoc version: 0.26.3
-   TypeScript version: 5.5.2
-   Node.js version: 20.15.0
-   OS: Ubuntu 22.04.4

**Comment by Gerrit0** [comment]
[TypeDoc implements](https://typedoc.org/guides/declaration-references/) the "new" version of [declaration references](https://tsdoc.org/pages/spec/overview/#declaration-references), not the old one. This decision was made because it is *far* closer to matching how TypeScript resolves links, and thus, far closer to how links will be resolved when someone looks at the comment in an editor like VSCode.

It looks like eslint-plugin-tsdoc uses the old link style... it probably deserves an issue to be updated/gain a flag.

**Comment by yoursunny** [comment]
https://github.com/microsoft/tsdoc/issues/202#issuecomment-2198762945

**Comment by blipk** [comment]
It's possible to use

```ts
import tsdoceslint from "eslint-plugin-tsdoc"

//...
            plugins : {
                // '@typescript-eslint': tseslint
                // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
                "tsdoc": tsdoceslint
            },
            rules : {
                "tsdoc/syntax": "warn",
            },
/// ...
```

This will give warnings when both running ESlint and in VSCode if using the ESLint plugin.

However if I want to disable a specific rules it's not possible, as `eslint-plugin-tsdoc` is expecting a value of "ignore" whereas the flat config format only allows `"off"` or `0`

e.g. This will still show as a warning both when running eslint and in the vscode ESlint plugin
```
rules : {
       "tsdoc/syntax": "warn",
       "tsdoc/tsdoc-reference-missing-hash": [ "off" ] 
}
```

e.g. This will NOT show as a warning in the vscode ESlint plugin but running eslint will error with the below
```
rules : {
       "tsdoc/syntax": "warn",
       "tsdoc/tsdoc-reference-missing-hash": [ "ignore" ] 
}
```

```
Configuration for rule "tsdoc/tsdoc-reference-missing-hash" is invalid. Expected severity of "off", 0, "warn", 1, "error", or 2.

You passed '"ignore"'.
```
