### ISSUE TITLE
`tsdoc.json` and `tsdoc-defaults.ts` out of sync

### ISSUE THREAD

**Issue by jkowalleck** [TypeStrong/typedoc#2623]
## Expected Behavior

`tsdoc.json` and `tsdoc-defaults.ts` are in sync.

## Actual Behavior

`tsdoc.json` and `tsdoc-defaults.ts` are in sync.

for example, the `@remarks` is not in `tsdoc.json`, but available in `tsdoc-defaults.ts`.

## Steps to reproduce the bug

compare 
- https://github.com/TypeStrong/typedoc/blob/v0.26.3/tsdoc.json
- https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/tsdoc-defaults.ts 

## Environment

-   Typedoc version: 0.26.3
-   TypeScript version: -
-   Node.js version: -
-   OS: -

**Comment by jkowalleck** [comment]
proposed solution:

1. I would add a test script, that checks whether the respective files are in sync, and add this script as part of CI/CT.
2. I would add a generator-script that crafts a `tsdoc.json` in reproducible manner.

**Comment by Gerrit0** [comment]
That test is here: https://github.com/TypeStrong/typedoc/blob/master/src/test/utils/options/tsdoc-defaults.test.ts

TypeDoc doesn't need to include `@remarks`, or any of the other tags defined by TSDoc because the file specifies `"noStandardTags": false,`, which instructs any TSDoc config parser to include those tags automatically. 

Copying from the tsdoc.json schema: [here](https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json)

```json
    "noStandardTags": {
      "description": "By default, the config file loader will predefine all of the standardized TSDoc tags.  To disable this and start with a completely empty configuration, set \"noStandardTags\"=true.",
      "type": "boolean"
    },
```

**Comment by jkowalleck** [comment]
> TypeDoc doesn't need to include `@remarks`, or any of the other tags defined by TSDoc [...]
is this so? then `eslint-plugin-tsdoc@0.3.0` might be bugged?

```
text
  32:4  error  tsdoc-undefined-tag: The TSDoc tag "@remark" is not defined in this configuration  tsdoc/syntax
  61:4  error  tsdoc-undefined-tag: The TSDoc tag "@remark" is not defined in this configuration  tsdoc/syntax
```

with `tsdoc.json`
```json5
{
  "$schema": "https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json",
  "extends": ["typedoc/tsdoc.json"],
  "tagDefinitions": [
    {
      "tagName": "@TODO",
      "syntaxKind": "block",
      "allowMultiple": true
    }
  ]
}
```

**Comment by Gerrit0** [comment]
That's because you have a typo, the tag is `@remarks`, not `@remark`

**Comment by jkowalleck** [comment]
> That's because you have a typo, the tag is `@remarks`, not `@remark`

oh, then, never mind. 

case closed.
