### ISSUE TITLE
Navigation does not remember scroll position

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#2626]
> Hello @Gerrit0,
> 
> I have encountered an issue related to the navigation and the changes made in [commit 9751e31](https://github.com/TypeStrong/typedoc/commit/9751e312789c9fae01a9b9f799a576ca5a07d372#diff-958325a2e382685c934a2542a4281a13e8eedc97f25b2c8882dd2b9c8c85fed6R95). Specifically, the navigation scrollbar keeps scrolling up on each page refresh. You can see a demonstration of this issue in Issue [#2624](https://github.com/TypeStrong/typedoc/issues/2624).
> 
> I saw you solved this issue, but I observed that the navigation scrolling happens only when the navigation is not visible, which seems to be due to the negation in the visibility check `!pageLink.checkVisibility()`.
> 
> Does this negation serve a specific purpose?

_Originally posted by @dom-rau in https://github.com/TypeStrong/typedoc/issues/2491#issuecomment-2211155238_

**Comment by Gerrit0** [comment]
#2624 is an entirely different issue, it is for TypeDoc's doc site which uses eleventy, not the API documentation generated by TypeDoc, (https://typedoc.org/guides/overview/, not https://typedoc.org/api/)

That negation was intended to only scroll the navigation if the page link wasn't already on the screen, which isn't the right way to check that... I incorrectly assumed that the method checked if the element was... visible...

**Comment by Khanon** [comment]
Was it solved? I'm using latest version of typedoc (0.26.7) and everytime I click on a link in the navigation bar, the scroll resets and goes to the top.

![scroll-top-issue](https://github.com/user-attachments/assets/5b05a341-8779-41fe-bbd0-c38132a6e5e2)
