### ISSUE TITLE
invalid link when referencing the same local images from multiple doc locations

### ISSUE THREAD

**Issue by obiot** [TypeStrong/typedoc#2627]
## Search terms

img src invalid link

## Expected Behavior

when referencing multiple time a "local" image from a repository, the generated typedoc should properly includes a link or a copy to the same image in all referenced documentation point.

## Actual Behavior

Typedoc will copy the image under the destination folder renaming the file to `imagename-[x]ext`, and properly setting the link to the copied image for one of the reference, but letting the original `imagename.ext` filename for the other one.

## Steps to reproduce the bug

here is an example where both use the same [source image](https://github.com/melonjs/melonJS/tree/master/src/video/images) :

- Properly display the image : [Generated page](https://melonjs.github.io/melonJS/classes/WebGLRenderer.html#setBlendMode) - [Page source](https://github.com/melonjs/melonJS/blob/c20b8225cbbfd8c2857cf34b2d69acf39fb2bff7/src/video/webgl/webgl_renderer.js#L730)
- Not displaying the image : [Generated page](https://melonjs.github.io/melonJS/classes/CanvasRenderer.html#setBlendMode) - [page source](https://github.com/melonjs/melonJS/blob/c20b8225cbbfd8c2857cf34b2d69acf39fb2bff7/src/video/canvas/canvas_renderer.js#L93)

Link to our repo : https://github.com/melonjs/melonJS
[tsconfig.json](https://github.com/user-attachments/files/16117794/tsconfig.json)
[tsconfig.base.json](https://github.com/user-attachments/files/16117797/tsconfig.base.json)

## Environment

-   Typedoc version: 0.26.3
-   TypeScript version: 5.5.2
-   Node.js version: 20.11.0
-   OS: MacOS 14.5

**Comment by Gerrit0** [comment]
Well that's rather embarrassing, I just flat missed checking the cache if I had already generated a name for an image...

**Comment by obiot** [comment]
thanks for the fix !
