### ISSUE TITLE
Line endings on windows break frontmatter in `projectDocuments` CLRF

### ISSUE THREAD

**Issue by bukowa** [TypeStrong/typedoc#2628]
I don't know how much time I have wasted on debugging line endings on Windows in many projects. It's funny, for example, in Docker where if you have entrypoint.sh with CLRF it will simply tell you that "entrypoint file not found". I found a similar error in the markdown plugin for typedoc, I always come across it wherever I go. `CLRF` - I will probably get this tattooed :D

## Search terms
Line endings on windows break frontmatter in `projectDocuments` CLRF

## Expected Behavior
It works.

## Actual Behavior
It's broken. `quick_start` has CLRF below:

![9f5e5e3d8933a885af58fce8cf46ea2c](https://github.com/TypeStrong/typedoc/assets/38087302/0d0d7500-e755-4504-ad3c-1e9ac3a13693)
![badbad](https://github.com/TypeStrong/typedoc/assets/38087302/0d75158f-85b8-4b63-a428-0e58edcdb166)

## Steps to reproduce the bug
I added files here: https://gist.github.com/bukowa/e9623517b7e73f2494369af98185a13f#file-quick-start-html-L54
If necessary I can probably build a full example.

## Environment

-   Typedoc version: `0.26.3`
-   TypeScript version: `5.5.3`
-   Node.js version: `v22.4.0`
-   OS: `Windows 10`

**Comment by Gerrit0** [comment]
Yep. That's it!

**Comment by Gerrit0** [comment]
Fixed with #2631
