### ISSUE TITLE
@link inline tags not working in project documents

### ISSUE THREAD

**Issue by yo35** [TypeStrong/typedoc#2629]
## Search terms

`@link`, inline, projectDocuments

## Expected Behavior

Inline links `{@link ...}` within markdown documents added with the `--projectDocuments` option should be resolved, as in the doc comments and as in the readme page.

## Actual Behavior

Inline links `{@link ...}` within markdown documents added with the `--projectDocuments` option are not resolved : in the generated HTML file, the `{@link ...}` tag itself is stripped off, but no HTML link is created. No error/warning is reported by TypeDoc in the console.

## Steps to reproduce the bug

In file https://github.com/yo35/kokopu/blob/4.11.1/doc_src/tutorials/01_getting_started.md?plain=1,
the tag `{@link Position}` on line 10 is not resolved: see the [generated file](https://kokopu.yo35.org/docs/4.11.1/documents/Tutorials.Getting_started.html).

On the contrary, for the readme Markdown file https://github.com/yo35/kokopu/blob/4.11.1/doc_src/home.md?plain=1, the same tag `{@link Positition}` on line 43 is properly resolved: see the [generated file](https://kokopu.yo35.org/docs/4.11.1/index.html).

Typedoc config file is https://github.com/yo35/kokopu/blob/4.11.1/typedoc.config.js.

## Environment

-   Typedoc version: 0.26.3
-   TypeScript version: 5.5.3
-   Node.js version: 20.15.0
-   OS: Linux Mint

**Comment by Gerrit0** [comment]
I have literally no idea how I didn't notice this was broken before release...

**Comment by yo35** [comment]
Thanks for the fix.
