### ISSUE TITLE
Abstract members

### ISSUE THREAD

**Issue by ntrrgc** [TypeStrong/typedoc#263]
At the moment as far as I can see abstract members are documented the same way than concrete members. There is no indication whatsoever in the resulting documentation on whether one member is concrete or abstract.

See for instance the TypeDoc API: http://typedoc.io/api/classes/td.models.type.html

In that page, `Type` is an abstract class. It has some abstract members, e.g. `clone()` and some concrete but overloadable members, like `equals()`, but the documentations shows both with the same icon as concrete members and with no hint of them being abstract. 

Classes are shown with the same icon too, even though a class being abstract makes a big difference in usage for the client.

**Comment by lynncyrin** [comment]
Updated path for the link above http://typedoc.org/api/classes/type.html !

(I'd also really like a different icon for abstract classes)

**Comment by Gerrit0** [comment]
This seems to have been partially fixed, we at least show an abstract tag for the member. We just need a separate icon now.

![image](https://user-images.githubusercontent.com/19329837/70880978-3c8b5900-1f88-11ea-99ef-b94935e19f07.png)
