### ISSUE TITLE
`@hidden` implementation of non-hidden overloads result in documentation that marks the function as hidden

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2634]
## Search terms

hidden, overload

## Actual Behavior

When the implementation of overloads is marked with `@hidden` while the overloads aren't, the generated documentation of the function is also marked marked with `Hidden`.

### Reproduction

Save the following file to `a.ts`.

```typescript
/**
 * @param a - Number param.
 */
export function f(a: number): void;

/**
 * @param a - String param.
 */
export function f(a: string): void;

/** @hidden */
export function f(a: string | number): void {
  console.log(a);
}
```

Run `typedoc a.ts`. Check out the output.

![image](https://github.com/TypeStrong/typedoc/assets/325476/c38b6356-d730-4b65-adcf-40d5ae325223)

## Expected Behavior

Function `f` above shouldn't be marked as `Hidden` in the generated doc.

## Environment

-   Typedoc version: 0.26.3
-   TypeScript version:  5.5.3
-   Node.js version: 22.4.1

**Comment by Gerrit0** [comment]
That should have entirely removed the function from the documentation... weird.

**Comment by xuhdev** [comment]
How should we exclude the implementation prototype from the doc then? They are often only used for implementation and not for users to read.

**Comment by xuhdev** [comment]
nvm, the implementation is undocumented by default.
