### ISSUE TITLE
githubPages option does not generate `.nojekyll` file

### ISSUE THREAD

**Issue by scottschreckengaust** [TypeStrong/typedoc#2635]
## Search terms

--githubPages, .nojekyll

## Expected Behavior

Expecting a `.nojekyll` file in the destination output folder.

The documentation states:

> --githubPages                                Generate a .nojekyll file to prevent 404 errors in GitHub Pages. Defaults to `true`

## Actual Behavior

There is no `.nojekyll` file generated, and if there is a `.nojekyll` file it is deleted.

## Steps to reproduce the bug

```
touch docs/.nojekyll
typedoc --plugin typedoc-plugin-markdown
```

The `.nojekyll` file will be deleted.

## Environment

-   Typedoc version: 0.26.3
-   TypeScript version: 5.5.3
-   Node.js version: 20.9.0
-   OS: macOS Sonoma 14.5 M2

**Comment by Gerrit0** [comment]
> typedoc-plugin-markdown

This plugin completely overwrites TypeDoc's renderer, so anything which uses renderer events, like this option, is disabled by it.

**Comment by scottschreckengaust** [comment]
Resolved.
