### ISSUE TITLE
`@param with name "foo", which was not used` When Parameter Name Matches Excluded Property Name From Parent Class

### ISSUE THREAD

**Issue by Lakuna** [TypeStrong/typedoc#2636]
## Search terms

`The signature Foo.constructor has an @param with name "bar", which was not used`

## Expected Behavior

The behavior from TypeDoc versions 0.26.1 and below is expected. The documentation should not exclude documented parameters, nor should it warn about unrelated properties.

## Actual Behavior

When a parent class (`A` in this example) has an excluded property (`a` in this example) with a name that matches the name of a child class' (`B` in this example) constructor parameter, a warning is given and the parameter is excluded from the documentation.

## Steps to reproduce the bug

1. Install TypeDoc version 2.6.2, 2.6.3, or 2.6.4.
2. Enable `excludeInternal` in your TypeDoc configuration.
3. Use a file with the following contents as an entrypoint.

    ```ts
    export abstract class A {
      protected constructor(a: number) {
        this.a = a;
      }

      /** @internal */
      public readonly a: number;
    }

    export class B extends A {
      /** @param a */
      public constructor(a: number) {
        super(a);
      }
    }
    ```

4. Execute `typedoc`.

The following warning messages will be displayed:

```
[warning] The signature B.constructor has an @param with name "a", which was not used
[info] Documentation generated at ./docs
[warning] Found 0 errors and 1 warnings
```

Additionally, the generated documentation will exclude `a` from the constructor of `B`:

![Screen Shot 2024-07-10 at 02 49 11](https://github.com/TypeStrong/typedoc/assets/31971465/0ae265b7-4d0c-4879-ab07-9ddb08523305)

## Environment

-   TypeDoc version: 2.6.4
-   TypeScript version: 5.4.5
-   Node.js version: 22.3.0
-   OS: Windows 11

**Comment by Gerrit0** [comment]
Wow, that's a weird one. Caused by 16b2694c270ae0bc3c3a092e0c9a1b2d383c1d3b.
