### ISSUE TITLE
Support for Tags used in documenting custom elements

### ISSUE THREAD

**Issue by fireflysemantics** [TypeStrong/typedoc#2637]
## Search Terms

It would be nice if Typedoc has support for the tags used to document custom element.  JSDoc has these.  More here: https://www.npmjs.com/package/web-component-analyzer

## Problem

If Typedoc had the corresponding JSDoc features it makes documenting web components more straight forward with Typedoc

## Suggested Solution

Implement corresponding JSDoc tags like `@element`, etc.

**Comment by Gerrit0** [comment]
Marking this wontfix. 

TypeDoc can be configured with support for custom tags already. If custom parsing/rendering is desired for a tag, this can be done by an external plugin. TypeDoc doesn't need to support it natively, and in the interest of reducing the maintenance burden, I do not plan on supporting additional sets of non-standard tags in the core without a *very* compelling reason.
