### ISSUE TITLE
Export the default blockTags to allow extending them

### ISSUE THREAD

**Issue by crycode-de** [TypeStrong/typedoc#2640]
## Search Terms

Allow extending of the `blockTags` (and maybe `inlineTags` and others too) array.

## Problem

Using [blockTags](https://typedoc.org/options/comments/#blocktags) config option it's already possible to *overwrite* the default blockTags definition. But extending them is currently not possible.

Of cause you could just copy&paste the default `blockTags` but it doesn't feel right and needs to be checked/updated on each TypeDoc update.

I'm using TypeDoc as node module by calling
```js
import TypeDoc from 'typedoc';
const typeDocApp = await TypeDoc.Application.bootstrapWithPlugins({
  // ...
  blockTags: [
    // ...
  ],
});
//...
```

The I saw that the default `blockTags` are defined in:
https://github.com/TypeStrong/typedoc/blob/c1fb5bd53ce0cca3a940ff3955ca2365ad3ebc67/src/lib/utils/options/tsdoc-defaults.ts#L16-L39

Trying to import them directly from the dist path fails with `ERR_PACKAGE_PATH_NOT_EXPORTED`:
```js
import { blockTags } from 'typedoc/dist/lib/utils/options/tsdoc-defaults.js';
// Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/utils/options/tsdoc-defaults.js' is not defined by "exports" in /home/[...]/node_modules/typedoc/package.json imported from /home/[...]/scripts/docs.ts
```

## Suggested Solution

Export the default `blockTags` (and maybe also the other default tags) to allow to import and extend them.

Example of possible use:
```js
import TypeDoc from 'typedoc';
const typeDocApp = await TypeDoc.Application.bootstrapWithPlugins({
  // ...
  blockTags: [
    ...TypeDoc.defaults.blockTags,
    '@myCustomTag',
  ],
});
//...
```

**Comment by Gerrit0** [comment]
Seems like a reasonable request :+1:
