### ISSUE TITLE
How to load Readme.md after update (includes removed)

### ISSUE THREAD

**Issue by goyertp** [TypeStrong/typedoc#2642]
Hey,

In the last change, you removed the `--includes` option, suggesting the use of the `@document` tag instead. This is unfortunate because maintaining the README.md and later including it with `includes` was simple and efficient.

Maintaining Markdown in the README.md is easy, straightforward, and a standard in many companies.

We loaded it like this:
```typescript
/** @packageDocumentation
 * [[include:aws-ses/README.md]]
 */
export * from "./ses-smtp-user";
```

The content of the file was directly viewable within the class/module and not on a separate page.
Can you somehow make this possible again?

Regards

Philipp

**Comment by Gerrit0** [comment]
I have no plans to include this in typedoc itself. It is easy to write a custom plugin which does this, see https://github.com/microsoft/tsdoc/issues/22#issuecomment-2211156557

**Comment by goyertp** [comment]
Thanks for your feedback.
