### ISSUE TITLE
Unexpected nav menu behaviour when combining projectDocuments with includeCategories

### ISSUE THREAD

**Issue by henrycatalinismith** [TypeStrong/typedoc#2646]
## Steps to reproduce

I've made a minor change to the example repo in a branch in my fork. The commit is https://github.com/henrycatalinismith/typedoc/commit/2f7a2d81759f4d22b0aaaeef9a36b78e92e7ccc6. A summary:

1. Set `includeCategories` to `true`.
2. Set `projectDocuments` to include a markdown file with a category value in its frontmatter.

## Expected Behavior

I was expecting the additional category to show up alongside the existing ones from the entrypoint, like this.

<img src="https://github.com/user-attachments/assets/6bcdf7db-14ce-4542-8980-514ef12d71e1" width="333">

## Actual Behavior

Instead, the existing categories from the entrypoint get cordoned off in a new `Other` category, and the `src` folder is now exposed as a module.

<img src="https://github.com/user-attachments/assets/61b71057-4935-496f-a797-d0daea2fc995" width="333">

**Comment by Gerrit0** [comment]
This is working as intended, and is caused by the alwaysCreateEntryPointModule option. <https://typedoc.org/options/input/#alwayscreateentrypointmodule>

If you set that to false, you'll see the behavior you were expecting.

**Comment by henrycatalinismith** [comment]
Hurray! Thank you!

![Screenshot 2024-07-23 at 07 36 47](https://github.com/user-attachments/assets/ce5c6ae1-006c-4a8a-a9c8-e35365a938b8)

https://github.com/henrycatalinismith/typedoc/commit/e03f78ede6a59b32436ca6310570d139da341d45

Sorry for miscategorising as a bug instead of a question! Tough to distinguish sometimes from an outside perspective! Thanks for the help though!
