### ISSUE TITLE
Left side navigation menu in typedoc documentation only shows "Loading..." instead of menus in mac, but same documentation works fine in windows

### ISSUE THREAD

**Issue by testuserfor** [TypeStrong/typedoc#2648]
## Search terms

#2596 

## Question

I have generated documentation using typedoc, working in mac (safari/firefox), documentation generated successfully.
All files are generated, but when I run it on browser, it always shows "Loading..." on left side menu instead of actual menus.
** The same documentation works fine in windows.

I am using following configration:
       "typedocOptions" : {
		"entryPoints" : [ "src" ],
		"entryPointStrategy" : "expand",
		"out" : "docs",
		"plugin" : [
			"@zamiell/typedoc-plugin-not-exported",
			"typedoc-github-theme",
			"typedoc-plugin-rename-defaults"
		],
		"theme" : "typedoc-github-theme",
		"name" : "Avertium"
	}

and 

{
    "react": "^18.3.1",
    "typescript": "^4.9.5",
    "typedoc": "^0.26.5",
}

Thanks

**Comment by Gerrit0** [comment]
I don't have a hope of debugging this without a Mac. My best guess is that there's some content blocker preventing the navigation script from loading. I'd recommend checking the developer console for errors

**Comment by Oblarg** [comment]
I'm on mac/safari and have not observed this with the most-recent typedoc.
