### ISSUE TITLE
ProjectDocument creates "index" in monorepo

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2649]
## Search terms

External, document, documentation, markdown, readme, changelog, index, projectDocuments

## Expected Behavior

I want to use `projectDocuments` to add my changelog for each of my projects in a monorepo.

Without `projectDocuments`:

![image](https://github.com/user-attachments/assets/c57338e0-2b35-4b79-8cdf-eaafc414adf1)

This following screenshot uses the inline tag in `index.ts` (without `projectDocumentation`):

```ts
/**
 * @document ../CHANGELOG.md
 */
```

![image](https://github.com/user-attachments/assets/e0dc04c2-ff66-4263-8d03-818ee1979071)

This second screenshot is exactly what I want, but I need to add this inline tag in each of my projects.

## Actual Behavior

With my code in `typedoc.json`, this is what happens:

```json
{
    "entryPointStrategy": "packages",
    "entryPoints": [
        "packages/*",
    ],
    "packageOptions": {
        "entryPoints": [
            "src/index.ts",
        ],
        "projectDocuments": [
            "./CHANGELOG.md",
        ],
        ...
    },
    ...
}
```

![image](https://github.com/user-attachments/assets/107cfcbd-0af8-4c0f-b729-2c3a4d502537)

As you can see, it puts everything (except for the changelog) under a subheading called `index`. I'm not sure why this is happening.

## Steps to reproduce the bug

- Create a monorepo like in https://github.com/Gerrit0/typedoc-packages-example
- Add markdown files all with the same name to each project
- Add the `projectDocuments` line to the main `typedoc.json`
- Run `typedoc` on the repo and observe results

## Environment

-   Typedoc version: 0.26.5
-   TypeScript version: 5.5.4
-   Node.js version: 20.11.1
-   OS: Kubuntu 22.04

**Comment by Gerrit0** [comment]
This is working as expected - https://typedoc.org/options/input/#alwayscreateentrypointmodule

**Comment by nicfv** [comment]
Ah, okay. It felt so intentional I figured there'd be an easy fix. This did the trick, thanks!

```json
{
    "entryPointStrategy": "packages",
    "entryPoints": [
        "packages/*",
    ],
    "packageOptions": {
        "alwaysCreateEntryPointModule": false,
        "entryPoints": [
            "src/index.ts",
        ],
        "projectDocuments": [
            "CHANGELOG.md",
        ],
        ...
    },
    ...
}
```

![image](https://github.com/user-attachments/assets/5c1623f6-582c-40c2-aec9-9beaef1471af)
