### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by MatthieuLebigre** [TypeStrong/typedoc#265]
Hi,

Do you plan to release a new version of typedoc with the latest fixes ?
I would love to have the fix #252.

Best regards

**Comment by felixfbecker** [comment]
ping

**Comment by blakeembrey** [comment]
https://github.com/TypeStrong/typedoc/releases/tag/v0.4.5

**Comment by jonnycornwell** [comment]
Great thanks!, really needed that default  theme fix :)
