### ISSUE TITLE
How to include custom js?

### ISSUE THREAD

**Issue by hesxenon** [TypeStrong/typedoc#2650]
## Search terms

include js, include script, custom script source

## Question

I'm developing a webcomponent library and I noticed that HTML that is inlined in the documentation is rendered. Would be quite nice to have the webcomponents render but for that I'd have to include the bundled script somehow. Is there a way to do that?

**Comment by Gerrit0** [comment]
Currently only via a plugin which uses a hook to add it to the page like  https://typedoc.org/api/documents/Renderer.Custom_Themes.html#md:hooks 

I've been meaning to add a `customJs` option which behaves like `customCss` does for a while, just haven't gotten around to it

**Comment by Aryakoste** [comment]
Hello @Gerrit0 I would like to work on this issue.

**Comment by Gerrit0** [comment]
Go for it!

**Comment by hesxenon** [comment]
@Aryakoste thanks for your work on this, but maybe it would be nice to have something like
```jsonc
"customJs": {
  src: "./dist/index.js",
  type: "module"
}
```

it seems the way this is currently implemented this only allows for non-esm scripts?

@Gerrit0 would you like me to open another issue for this or re-open this issue?

**Comment by Gerrit0** [comment]
I'm becoming really wary of adding too much behavior via options - TypeDoc already has *so* many...

This is also really easy to do with a plugin...

```ts
import { Application, JSX } from "typedoc";
import fs from "fs";
import path from "path";

/** @param {Application} app */
export function load(app) {
    app.renderer.hooks.on("head.end", (ctx) =>
        JSX.createElement("script", { src: ctx.relativeURL("./assets/custom.js"), type: "module" }),
    );

    app.renderer.on("beginRender", (event) => {
        fs.copyFileSync("path/to/custom.js", path.join(event.outputDirectory, "assets/custom.js"));
    });
}

```

**Comment by hesxenon** [comment]
absolutely, I get that. I mean I would probably re-use the lib.dom.ts declarations and do something like

```ts
customJs: Array<
  Partial<
    PickByValueType<HTMLScriptElement, string | number | boolean>
  > & {src: string}
>
```

so that consumers can specify any valid script attribute at the cost of being able to specify a string only.

But speaking of plugins: is there a guide to plugin development somewhere?

**Comment by Gerrit0** [comment]
Unfortunately that API would require a hardcoded special case in the options parser, which is not something I want to add. There are a number of similar options that it'd be convenient to have within objects, but the parser as is doesn't lend itself to it.

**Comment by Gerrit0** [comment]
For plugin docs, there is the internal-docs folder in this repository and <https://typedoc.org/guides/development/>
