### ISSUE TITLE
Missing space before external document in breadcrumbs

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2651]
## Search terms

space, breadcrumb, missing

## Expected Behavior

A space before the document name in the breadcrumbs, e.g:

```
Name / Package / Folder / Document
```

## Actual Behavior

No space before the document name in the breadcrumbs, e.g:

```
Name / Package / Folder/Document
```

## Live Example

Take a look here: https://npm.nicfv.com/documents/t6.examples_Assert_Boolean_Values.html

![image](https://github.com/user-attachments/assets/23803a82-ed8a-468d-af33-d4f90003ed8f)

## Environment

-   Typedoc version: 0.26.5
-   TypeScript version: 5.5.4
-   Node.js version: 20.11.1
-   OS: 22.04

**Comment by nicfv** [comment]
> If you had a document named "examples" which included child documents for each of the sub pages, typedoc would produce what you are expecting. You could also use the yaml front matter to set the document title to "examples / Assert Boolean Values"

Can you please point me in the direction how to do parent/child documents, as well as the yaml formatting?

**Comment by Gerrit0** [comment]
https://typedoc.org/guides/documents/ should have everything you need

**Comment by nicfv** [comment]
> https://typedoc.org/guides/documents/ should have everything you need

Thank you!

**Comment by nicfv** [comment]
Is it possible to just request there to be a space before and after that `/`? I think it would look nicer, but I know that's an opinion.

**Comment by Gerrit0** [comment]
Not including the space is the correct behavior -- perhaps it would be more clear if TypeDoc's UI used something besides `/` for separating pages in the breadcrumbs view...

TypeDoc is just displaying the document name here, I could *maybe* see an argument for splitting the document name on `/` and including non-linked entries similarly to how the page sidebar supports that magic, but just including spaces is definitely wrong.

![image](https://github.com/user-attachments/assets/2ed34e4f-e261-4b8d-94ff-95b0f33eaf68)
