### ISSUE TITLE
How to organize navigation (the left sidebar) by category without the remainder being placed in a default "Other" category? 

### ISSUE THREAD

**Issue by NkemdiAnyiam** [TypeStrong/typedoc#2656]
## Search terms

navigation, category, default category

## Question
I'm trying to use the "navigation" > "includeCategories" option in typedoc.json to organize the left nav bar. When I use the "@category" tag within my doc comments, the reflections are correctly placed under those categories in the navigation, but everything else is placed under a default category called "Other". How do I disable this default categorization and allow any uncategorized reflections to just remain where they are?

I'm not sure how clear my question is, so here is an example: Suppose I have a module named colors.ts which has 6 interfaces named `Red`, `Orange`, `Yellow`, `Green`, `Blue`, and `Purple` and 1 class named `Color`. By default, once the documentation is generated, all 7 would be listed straight under "colors". If I then applied "@category Warm" to the first 3 interfaces and "@category Cool" to the latter 3 interfaces in their doc comments, I _want_ the navigation layout to look something like this:

- colors
    - C Color
    - Warm
        - I Red
        - I Orange
        - I Yellow
    - Cool
        - I Green
        - I Blue
        - I Purple

Instead, it looks like this:
- colors
    - Other 
        - C Color
    - Warm
        - I Red
        - I Orange
        - I Yellow
    - Cool
        - I Green
        - I Blue
        - I Purple

**Comment by Gerrit0** [comment]
There is no way to do this today. TypeDoc's category plugin assumes that there are either no categories, and each reflection is placed directly within a group, or every symbol is placed within a category. This is important as traversing the groups/categories is how TypeDoc determines how to render both the left hand navigation and the list of reflections within the module's page.

I'm not opposed to allowing the [defaultCategory](https://typedoc.org/options/organization/#defaultcategory) option to be set to `none`, in which case TypeDoc renders the reflections without a category header...
