### ISSUE TITLE
Link doesn't work for names that match a parameter in the current function.

### ISSUE THREAD

**Issue by vitaly-t** [TypeStrong/typedoc#2657]
Link doesn't work when referencing a function with name that matches one of function parameters that we document.

In my case, I am documenting the following function:

```ts
export function delay(timeout: number);
```

And I also need to provide a reference to a separate function that happens to have the same name as the parameter `timeout`:

```ts
/**
@see
  - {@link timeout}
*/
```

Because of this sudden match, typedoc fails to produce a link for `timeout` function, it just outputs text instead. I know this, because just as I rename parameter `timeout` in function `delay` to something else, the link starts working, and produces the right reference.

But I do not want to rename the parameter. If this is somehow not a bug, then how can we work-around this issue?

---

I am using typedoc v0.26.5

**Comment by Gerrit0** [comment]
This is, unfortunately, working as expected. By default, [useTsLinkResolution](https://typedoc.org/options/comments/#usetslinkresolution) is turned on. In [your case](https://github.com/vitaly-t/iter-ops/blob/df2635717dde34894a5693a5525c0896f00aef03/src/ops/async/delay.ts#L38), the `timeout` function is not in scope, so TypeScript will check parameters, notice that `timeout` is an existing symbol, and assume you meant to link to that. When TypeDoc goes to parse the comment, TypeScript will tell it that the link goes to the parameter, which TypeDoc will respect.

In your case, TypeScript's link resolution is not desired, so we have to construct a link which TypeScript will fail to parse, allowing [TypeDoc's declaration reference resolution](https://typedoc.org/guides/declaration-references/) to take over.

The easiest way to do this is `{@link !timeout}`

**Comment by vitaly-t** [comment]
Thank you, changing the link to `{@link !timeout timeout}` did it!
