### ISSUE TITLE
Support for @augment tag

### ISSUE THREAD

**Issue by waynemwashuma** [TypeStrong/typedoc#2660]
## Search Terms

jsdoc, augment, extends

## Problem

The cli throws errors when `@augments` tag is used.
A related issue is #2659 

## Suggested Solution

The `@augments` tag can be added to the allow list.
Ill be able to create a pull request for this.

**Comment by Gerrit0** [comment]
I'm honestly kind of shocked that the usage of this tag (according to GitHub search) is as high as it is... PR welcome!
