### ISSUE TITLE
Not able to see comments added in document created - React Native

### ISSUE THREAD

**Issue by gilshaan** [TypeStrong/typedoc#2666]
## Code

```
 /**
   * Returns a test string.
   * @returns {string} The test string "testText".
   * @example const printText = (): string => { return 'testText';};
   */
  const printText = (): string => {
    return 'testText';
  };
```
```
  /**
   * Returns sum of numbers.
   * @returns {number} The sum of digits.
   */
  const add = (a: number, b: number): number => {
    return a + b;
  };
```

## Expected Behavior

To see the comments added and functions in document created

## Environment

-   Typedoc version: 0.26.5
-   TypeScript version: 5.0.4
-   Node.js version: 21.4.0
-   OS: MacOS 14.5 (23F79)

**Comment by harivkrish47** [comment]
> ## Code
> ```
>  /**
>    * Returns a test string.
>    * @returns {string} The test string "testText".
>    * @example const printText = (): string => { return 'testText';};
>    */
>   const printText = (): string => {
>     return 'testText';
>   };
> ```
> 
> ```
>   /**
>    * Returns sum of numbers.
>    * @returns {number} The sum of digits.
>    */
>   const add = (a: number, b: number): number => {
>     return a + b;
>   };
> ```
> 
> ## Expected Behavior
> To see the comments added and functions in document created
> 
> ## Environment
> * Typedoc version: 0.26.5
> * TypeScript version: 5.0.4
> * Node.js version: 21.4.0
> * OS: MacOS 14.5 (23F79)


Hi @gilshaan, Displaying comments directly within JSX elements is not natively supported in documentation tools like TypeDoc, which typically focus on comments outside of JSX only.

**Comment by Oblarg** [comment]
You should export the artifacts you want to render in your docs.

**Comment by gilshaan** [comment]
Hi @Oblarg 

I've been working on exporting all the necessary artifacts for TypeDoc, but I'm running into some issues where it's not rendering the details as expected, especially missing the comments before each function inside the code. I've ensured that TypeScript is generating the declaration files and that TypeDoc is configured properly.

Could you please let me know if there's a specific artifact that might be missing? Any insights or suggestions would be greatly appreciated.

Thank you!

**Comment by Gerrit0** [comment]
Without some runnable reproduction to look at, it's basically impossible to say what's going on with your project. In the snippets you provided, the functions aren't exported, so it makes sense that TypeDoc wouldn't include them.
