### ISSUE TITLE
Option to disable compact navigation structure when a category contains only one reflection

### ISSUE THREAD

**Issue by NkemdiAnyiam** [TypeStrong/typedoc#2667]
## Search Terms

compact, navigation, single reflection

## Problem
Given: The typedoc.json `navigation.includeCategories` option is set to `true`.

When there is only one reflection with a given @category tag, the rendered docs will not render the category as a dropdown. Instead, it will be displayed in a compact form, i.e., "(category name)/(reflection name)". This can be visually confusing (and aesthetically unpleasing), especially when there are other categories that are _not_ compacted.

For example, suppose I have a module named colors.ts which has 7 interfaces named `Red`, `Orange`, `Yellow`, `Green`, `Blue`, `Purple`, and `Gray` and 1 class named `Color`. And suppose I separated the interfaces into 3 categories: "Warm", "Cool", and "Neutral". The rendered navigation for the colors module would look like the following:
![image](https://github.com/user-attachments/assets/6e727369-236e-45d0-ba86-a4f88bc14f31)
I would like to be able to render it as a dropdown like the following despite `Gray` being the only reflection categorized under "Neutral":
![image](https://github.com/user-attachments/assets/4c468210-6c1f-4ef2-b187-40110929ef47)

## Suggested Solution

Add an additional boolean configuration option like `navigation.compactOrganization` or `navigation.compactStructure` (I'm not sure of the best name). It can default to `true` (in which case, nothing changes), but if set to `false`, categories (and groups) containing only a single reflection will still render a dropdown.

**Comment by Gerrit0** [comment]
With #2656 I believe this is unnecessary

**Comment by NkemdiAnyiam** [comment]
I think what I'm trying to describe is a little confusing, but I think showing an example of what VSCode does should clarify what I'm asking for. In VSCode, if a folder A contains only a folder B, the explorer just renders it as A/B, like this:
![image](https://github.com/user-attachments/assets/daea087d-d833-4e90-84b3-ea38c1fa2d9b)

But in the settings.json, if `explorer.compactFolders` is set to `false`, it renders A as a normal dropdown with B as a child (which is what I prefer) like this:.
![image](https://github.com/user-attachments/assets/b8b62376-208b-4f6a-ac98-17774a5071fb)

I would like a similar setting for typedoc.json (something like `navigation.compactOrganization`, `navigation.compactStructure`, `navigation.compactFolders`—whatever name fits the best). This way, categories or groups that only have a single reflection are still rendered as dropdowns instead of being compacted (as demonstrated by the screenshots of the example docs in my original post). The setting would look something like this:
![image](https://github.com/user-attachments/assets/ebfb7cf0-9449-4da3-a7e5-437db3d21c21)

**Comment by Gerrit0** [comment]
Gotcha, that makes sense!
