### ISSUE TITLE
TypeDoc won't ignore NOTICE Headers when trying to create @module or @packageDocumentation blocks

### ISSUE THREAD

**Issue by JustSamuel** [TypeStrong/typedoc#2669]
## Search terms
notice, @module, @packageDocumentation

## Question

[This might be relevant](https://github.com/TypeStrong/typedoc/issues/603#issuecomment-462616515)

As stated in the documentation of the [@module](https://typedoc.org/tags/module/) tag and the [@packageDocumentation](https://typedoc.org/tags/packageDocumentation/) tag: NOTE: A comment block where the @packageDocumentation tag is used must be the first comment in the file.

However, all our files contain a block comment GNU license in them as a header. Is it still possible to generate module comments? 

The following example will *not* generate a module description:
```
/**
 *  API service.
 *  Copyright (C) 2024
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
 
/**
 * Specify this is a module comment without renaming it:
 * @module
 */
```

**Comment by Gerrit0** [comment]
If you add `@license` to the license comment, typedoc will ignore it

**Comment by JustSamuel** [comment]
Thanks!
