### ISSUE TITLE
Add an option to ignore `this: void` parameter

### ISSUE THREAD

**Issue by xixixao** [TypeStrong/typedoc#2670]
## Search Terms

this paramater void

## Problem

`this: void` parameter is a way to tell TS that a function is not callable as a method.

## Suggested Solution

Would be nice to not show this param in the list of parameters.

**Comment by Gerrit0** [comment]
Arbitrary changes to types displayed in documentation is something I want to avoid in TypeDoc. This is easy to do with a plugin.

```bash
typedoc --plugin ./path/to/plugin.js
```

```js
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(td.Converter.EVENT_CREATE_SIGNATURE, (context, sig) => {
        const param = sig.parameters?.[0];
        if (param?.name === "this" && param.type?.toString() === "void") {
            context.project.removeReflection(param);
        }
    });
}
```

**Comment by xixixao** [comment]
Thanks for the workaround, appreciate it!
