### ISSUE TITLE
Possibility to always show re-exports in the main navigation?

### ISSUE THREAD

**Issue by KillyMXI** [TypeStrong/typedoc#2671]
## Search terms

re-export, rename, alias, module page, navigation, sidebar

## Question

TypeDoc 0.23.28 was always showing re-exports in the sidebar, among all other functions exported by a module.

With TypeDoc 0.26.5, I only see re-exports on the module page - in the grid and in "On this page" menu.
This new behavior is inconvenient - it makes re-exports less discoverable.

When aliases added not for code compatibility but for ease of use, I want to keep them equally discoverable.
Expected usage scenario: user jumps between individual function pages (there are a lot of them), not visiting the module page often.

Is there a way to restore previous behavior?
Looking through the documentation I couldn't find it.

**Comment by Gerrit0** [comment]
This changed in 0.26.4, the page navigation sidebar was never intended to include links to elements which don't have an individual page, so including the links broke the active page highlighting.

It's an easy enough change to fix the active page highlighting while still including re-exports... I should probably just revert the change to remove them.
