### ISSUE TITLE
Source order not honouring entry point

### ISSUE THREAD

**Issue by KDean-Dolphin** [TypeStrong/typedoc#2672]
## Search terms

sort source order index.js index.ts

## Question

My `typedoc.json` file is pretty basic:

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "sort": [
    "source-order"
  ],
  "entryPoints": [
    "src/index.ts"
  ]
}
```

My `index.ts` looks like this:

```typescript
export * from "./transformer.js";
export * from "./string.js";
export * from "./reg_exp.js";
export * from "./record.js";
export * from "./character_set.js";
```

I'm aware that `source-order` is defined as "sorts by file, then by position in file", but I was really hoping that would apply to `index.ts` as well; the organization of that file is in the order that makes the most sense from the reader's point of view (i.e., you can't understand what's in `string.js` until you understand what's in `transformer.js`).

Is there another option that I'm missing?

**Comment by Gerrit0** [comment]
I believe what you want is actually `"sort": []`, that is, do no sorting.

**Comment by KDean-Dolphin** [comment]
@Gerrit0 Brilliant, thank you!

(That should be in the documentation though...)
