### ISSUE TITLE
config type validation does not work properly

### ISSUE THREAD

**Issue by Zamiell** [TypeStrong/typedoc#2673]
## Expected Behavior

I have a file called "typedoc.config.mjs":

```js
/** @type {import('typedoc').TypeDocOptions} */
const config = {
  entryPoints: ["./src/index.ts", "./src/secondary-entry.ts"],
  out: "doc",
};

export default config;
```

However, it results in the following type error:

```
Type '{ entryPoints: string[]; out: string; }' is missing the following properties from type 'TypeDocOptions': options, tsconfig, compilerOptions, plugin, and 87 more.ts(2740)
```

I assume that this is a bug in TypeDoc, because it would be weird if end-users would have to specify 88 properties in their typedoc config files.

## More Info

I'm on version:

```
"typedoc": "^0.26.5",
```

**Comment by Gerrit0** [comment]
Ah, that example is wrong... it should be `Partial<import("typedoc").TypeDocOptions>`, that interface is intentionally non-partial.

**Comment by Zamiell** [comment]
closing in favor of https://github.com/TypeStrong/typedoc-site/pull/84
