### ISSUE TITLE
Can I append a comment right below frontmatter?

### ISSUE THREAD

**Issue by Balastrong** [TypeStrong/typedoc#2674]
## Search terms

comment frontmatter begin end

## Question

I'd like to add a comment on all pages to inform other developers that the file is autogenerated and shouldn't be manually edited, is it possible?

I'd expect an output similar to:

```md
---
title: my title
---

<!--- THIS FILE IS AUTOGENERATED -->

...rest of the file
```

**Comment by Gerrit0** [comment]
Sounds like this is a question for typedoc-plugin-markdown? TypeDoc doesn't emit those files, so can't do this.

**Comment by Balastrong** [comment]
The comment can also be on top of the generated HTML if the markdown plugin keeps it but I guess you're right, it's better to ask there.

Thanks!

**Comment by Gerrit0** [comment]
With the HTML output, this can be done with hooks today - https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md#hooks
