### ISSUE TITLE
Not recognizing link text before @link tag

### ISSUE THREAD

**Issue by KDean-Dolphin** [TypeStrong/typedoc#2678]
## Search terms

link

## Expected Behavior

Documentation written as `[descriptive text here]{@link TargetClass#targetMethod}` would be rendered similar to the way that `[descriptive text here](https://www.example.com)` is rendered.

See also https://jsdoc.app/tags-inline-link.

## Actual Behavior

Square brackets and enclosed text are rendered verbatim with the link to the right.

## Steps to reproduce the bug

What I write in code:

```
    /**
     * A description of some glorious function that will solve every programming problem in the world.
     *
     * Link: [descriptive text here]{@link TargetClass#targetMethod}
     *
     * Link code: [descriptive text here]{@linkcode TargetClass#targetMethod}
     *
     * Link plain: [descriptive text here]{@linkplain TargetClass#targetMethod}
     */
```

What I see in HTML:

> A description of some glorious function that will solve every programming problem in the world.
>
> Link: [descriptive text here][TargetClass#targetMethod](https://www.example.com)
>
> Link code: [descriptive text here][`TargetClass#targetMethod`](https://www.example.com)
>
> Link plain: [descriptive text here][TargetClass#targetMethod](https://www.example.com)

What I should see in HTML:

> A description of some glorious function that will solve every programming problem in the world.
>
> Link: [descriptive text here](https://www.example.com)
>
> Link code: [`descriptive text here`](https://www.example.com)
>
> Link plain: [descriptive text here](https://www.example.com)

## Environment

-   Typedoc version: 0.26.5
-   TypeScript version: 5.5.4
-   Node.js version: 21.7.3
-   OS: macOS Sonoma 14.6.1

**Comment by KDean-Dolphin** [comment]
Of course, no sooner do I submit the report than that little voice inside my head tells me to check the documentation again. What I'm looking for is, per the documentation, possible with `{@link TargetClass#targetMethod | descriptive text here}`.

I'm happy with that for documentation generation, though I've discovered that it's causing a minor problem in IntelliJ IDEA, which renders the vertical bar. So, off I go to submit a bug report over there.

Given that there is still a compatibility issue with JSDoc, I'm going to let the TypeDoc people decide whether to close this.

**Comment by Gerrit0** [comment]
Yeah, this is a wontfix. JSDoc's grammar is awful and this is one of the edge cases I have intentionally disregarded.
