### ISSUE TITLE
Add ability to open markdown links in new tab

### ISSUE THREAD

**Issue by KDean-Dolphin** [TypeStrong/typedoc#2679]
## Search Terms

markdown link target _blank

## Problem

The sourceLinkExternal option allows me to open links in a new tab when generating HTML. I would like to see a similar option for links in the markdown itself.

## Suggested Solution

Markdown links are, as designed, processed by markdown-it. However, it's possible to add a `target="_blank"` to all links through the use of a [custom renderer](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer). This should be enabled through an option in the generator.

**Comment by KDean-Dolphin** [comment]
To add to this, now that I've converted all my links to use `@link` instead, this ability would be nice for any `@link` that is a URL.

**Comment by Gerrit0** [comment]
TypeDoc renders `@link` to markdown before passing it to markdown-it, so the one option will pick up both cases
