### ISSUE TITLE
Getting errors when running typedoc programatically

### ISSUE THREAD

**Issue by joaogarin** [TypeStrong/typedoc#268]
Hello I am running typedoc to analyze some angular components. I get a bunch of errors altough it seems to analyze my components properly.

Using TypeScript 1.6.2 from /Library/WebServer/Documents/ng2-contacts/node_modules/typedoc/node_modules/typescript/lib
Error: node_modules/@angular/core/src/application_ref.d.ts(44)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/application_ref.d.ts(100)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/application_ref.d.ts(159)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(23)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(25)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/di/reflective_provider.d.ts(105)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/di/reflective_provider.d.ts(105)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/async.d.ts(26)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/async.d.ts(27)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(0)
 Cannot find name 'MapConstructor'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(1)
 Cannot find name 'SetConstructor'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(6)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(7)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(10)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(11)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(13)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(14)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(99)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(100)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(101)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(4)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(70)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(1)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(7)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(8)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(12)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/component_resolver.d.ts(8)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/component_resolver.d.ts(12)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(60)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(101)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(106)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(107)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(65)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(65)
 Cannot find name 'Promise'.

JSON written to /Library/WebServer/Documents/ng2-contacts/node_modules/carte-blanche-angular2/tmp/out.json

Using TypeScript 1.6.2 from /Library/WebServer/Documents/ng2-contacts/node_modules/typedoc/node_modules/typescript/lib
Error: node_modules/@angular/core/src/application_ref.d.ts(44)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/application_ref.d.ts(100)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/application_ref.d.ts(159)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(23)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(25)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/di/reflective_provider.d.ts(105)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/di/reflective_provider.d.ts(105)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/async.d.ts(26)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/async.d.ts(27)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(0)
 Cannot find name 'MapConstructor'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(1)
 Cannot find name 'SetConstructor'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(6)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(7)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(10)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(11)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(13)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(14)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(99)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(100)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(101)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(4)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(70)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(1)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(7)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(8)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(12)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/component_resolver.d.ts(8)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/component_resolver.d.ts(12)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(60)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(101)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(106)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(107)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(65)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(65)
 Cannot find name 'Promise'.

JSON written to /Library/WebServer/Documents/ng2-contacts/node_modules/carte-blanche-angular2/tmp/out.json

Using TypeScript 1.6.2 from /Library/WebServer/Documents/ng2-contacts/node_modules/typedoc/node_modules/typescript/lib
Error: node_modules/@angular/core/src/application_ref.d.ts(44)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/application_ref.d.ts(100)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/application_ref.d.ts(159)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(23)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(25)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/di/reflective_provider.d.ts(105)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/di/reflective_provider.d.ts(105)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/async.d.ts(26)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/async.d.ts(27)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(0)
 Cannot find name 'MapConstructor'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(1)
 Cannot find name 'SetConstructor'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(6)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(7)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(10)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(11)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(13)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(14)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(99)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(100)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/collection.d.ts(101)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(3)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(4)
 Cannot find name 'Set'.
Error: node_modules/@angular/core/src/facade/lang.d.ts(70)
 Cannot find name 'Map'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(1)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(7)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(8)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/facade/promise.d.ts(12)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/component_resolver.d.ts(8)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/component_resolver.d.ts(12)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(60)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(101)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(106)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(107)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(10)
 Cannot find name 'Promise'.
Error: node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18)
 Cannot find name 'Promise'.
Error: node_modules/carte-blanche-angular2/tmp/component.ts(5)
 Cannot find module './photo.component.ts'.
Error: node_modules/rxjs/Observable.d.ts(9)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(65)
 Cannot find name 'Promise'.
Error: node_modules/rxjs/Observable.d.ts(65)
 Cannot find name 'Promise'.

Sorry bout the long list:S

**Comment by joaogarin** [comment]
Worth mention that I am running typedoc in a ES6 babel compiled js file and not in a typescript file..is that a problem?

**Comment by aciccarello** [comment]
It looks like TypeScript cannot find the references for those ES6 classes (Map, Promise, Set). I wonder if TypeDoc needs a type definition file for those.

**Comment by joaogarin** [comment]
the weird thing is these errors are coming from definition files..

**Comment by felixfbecker** [comment]
If you have target ES5, you need to add typings for ES6 collections manually.

**Comment by joaogarin** [comment]
How do I add those manually? This is just running typedoc on the command line right..These are not showing up on any browser if that's what you are thinking. is there an option to include specific typings for example on typedoc? I tried using --includeDeclarations but it didnt change much

**Comment by joaogarin** [comment]
I guess I can target ES6, I have to say that option is not clear to me on what it does. All I want is the Json info out of the compiled typescript. So I tried now ES6 and that seems to be fine for me!

**Comment by felixfbecker** [comment]
When you do target: ES6, typescript will use lib.es6.d.ts, which includes all the typings for built-in Javascript objects, like Array or Promise. ES5 of course does not include Promise, so you have to install a shim with [the typings definition manager](https://github.com/typings/typings), like es6-promise, es6-collections or core-js. If it appears in the browser or not is irrelevant, TypeDoc needs to compile your code.

**Comment by joaogarin** [comment]
Yes I guess in this case the problem is I am using typedoc to analyze one single file and call generateJson on that file to get the Json array of the information in this file,I am not targetting an entire application. But in this case for me targeting ES6 is fine and that does fix the issue so I will close this, if I do need to target ES5 I guess its a matter of putting the def files together with this one file.

**Comment by joaogarin** [comment]
I am going to close this one..as for me I am using target as ES6.

**Comment by joshribakoff** [comment]
It was also analyzing my `node_modules` & complaining about issues I cannot control. IMO this was closed with the wrong solution. The solution for me was to use `--tsconfig` argument to specify my `tsconfig.lib.json` as by default it was looking at every file in the folder. (I am using the new "solution style" tsconfigs)
