### ISSUE TITLE
How to apply to annotations after adding members to this TranslatableStrings interface

### ISSUE THREAD

**Issue by 111yyh** [TypeStrong/typedoc#2682]
## Question
How to use members after adding members to TranslatableStrings interface?

**Comment by Gerrit0** [comment]
I have... no idea what you're asking. Plugins which add translatable strings also need to call [app.internationalization.addTranslations](https://typedoc.org/api/classes/Internationalization.Internationalization.html#addTranslations) to declare their defaults by adding entries to the `en` locale.

Translated text can be retrieved via `app.internationalization.translate("someKey", ...args)` or with `app.i18n.someKey(...args)`
