### ISSUE TITLE
The sorting strategy "alphabetical" should use localeCompare()

### ISSUE THREAD

**Issue by kozi** [TypeStrong/typedoc#2684]
The sorting strategy "alphabetical" should use localeCompare()

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

https://github.com/TypeStrong/typedoc/blob/ea0ea91d144a34295569113d3208beb1ee2efa03/src/lib/utils/sort.ts#L65
https://github.com/TypeStrong/typedoc/blob/ea0ea91d144a34295569113d3208beb1ee2efa03/src/lib/utils/sort.ts#L74

```javascript
a.name.localeCompare(b.name)
```

**Comment by Gerrit0** [comment]
PR welcome
