### ISSUE TITLE
Add option to choose whether to expose all re-exports in sidebar

### ISSUE THREAD

**Issue by ShaitanLyss** [TypeStrong/typedoc#2685]
## Search Terms

sidebar hierarchy re-exports

## Problem
My problem appeared in 0.26.6 due to the decision made in issue #2671.

I export a huge number of symbols at root level and I don't want my sidebar to be full of them with no hierarchy. As a workaround, I've been doing two export per module like so :
```
export * as Module from './module'
export * from './module'
```
In 0.26.5, this results in a clean readable hierarchy in the sidebar. 
In 0.26.6 however, all re-exports are added to the sidebar, making it cluttered and hard to read.

## Suggested Solution

It should be an option to add re-exports to the sidebar. Or if there's a better solution to my problem than doing two exports, please share it with me.

**Comment by Gerrit0** [comment]
The excludeReferences option will prevent typedoc from including them at all - https://typedoc.org/options/input/#excludereferences

Adding an option to exclude them from the sidebar seems reasonable if that's not what you're after.

**Comment by ShaitanLyss** [comment]
That's doesn't fit my use case, I'd still like to have the re-exports available in the main page (as they are the primary way to use the library), just not in the sidebar.
