### ISSUE TITLE
[question] ComplexGenericTypeAlias defined but never be used.

### ISSUE THREAD

**Issue by liaodalin19903** [TypeStrong/typedoc#2686]
## Search terms

type, type alias, generic

## Question

I find this type defined but never be used.
```
/** A complex generic type. */
export type ComplexGenericTypeAlias<T> =
    | T
    | T[]
    | Promise<T>
    | Promise<T[]>
    | Record<string, Promise<T>>;
```

Could you give a usage demo?

**Comment by Gerrit0** [comment]
That type exists in the example project purely to show how typedoc handles complex types like it, it does not have an intended use.
