### ISSUE TITLE
Relative links containing fragment trigger false-positive about missing files

### ISSUE THREAD

**Issue by cowwoc** [TypeStrong/typedoc#2687]
## Search terms

X is not a file and will not be copied to the output directory

## Expected Behavior

No warning

## Actual Behavior

Warning `docs/Features#diffs is not a file and will not be copied to the output directory`

## Steps to reproduce the bug

Run Typedoc on project containing README.md that contains this line:

`* [Diffs provided whenever possible](docs/Features.md#diffs-provided-whenever-possible)`

Typedoc will look for the literal file `docs/Features.md#diffs-provided-whenever-possible`, including the URL fragment. This file does not exist. If the fragment is removed, the file is found.

I am expecting Typedoc to support links to files with fragments. It should strip the fragments before checking if the file exists.

## Environment

-   Typedoc version: 0.26.6
-   TypeScript version: 5.5.4
-   Node.js version: 22.7.0
-   OS: Microsoft Windows [Version 10.0.19045.4780]

**Comment by Gerrit0** [comment]
Heh, I happened to run across that last weekend when experimenting with moving TypeDoc's site to just use TypeDoc. It is fixed on the beta branch with db67c4d8772ed9b7d75600c2e42c6032a926c961
