### ISSUE TITLE
[question] what's the meaning of ` handle links to models`? 

### ISSUE THREAD

**Issue by liaodalin19903** [TypeStrong/typedoc#2688]
## Search terms

models, reflections, links to models

## Question

Hi,

When I read the [document](https://typedoc.org/guides/development/#high-level)

> Resolve the models
> Necessary to handle links to models that might not have been created when the source model is generated.
> Output the models by serializing to HTML and/or JSON

How to understand:
1、what's the meaning of ` handle links to models`? 
2、what's the difference between `models` and `source model`?
3、why there using `serializing` word? is it mean serialize the ts object to text?

**Comment by Gerrit0** [comment]
1. TS comments can include `{@link}` tags. When initially converting, typedoc might not know where they go as what they link to might not have been converted yet, so their targets are figured out during the resolution step.
2. No difference, I used "source model" here to indicate the model containing the `@link` tag.
3. Yes, serializing is writing the converted reflection objects to disk. Currently this is done by converting the reflections to JSON or HTML (or markdown by typedoc-plugin-markdown), but there's no reason someone couldn't write a plugin to output a pdf if they wanted.

**Comment by liaodalin19903** [comment]
I still don't understand this:
> 1. TS comments can include {@link} tags. When initially converting, typedoc might not know where they go as what they link to might not have been converted yet, so their targets are figured out during the resolution step.

could you explain more?

**Comment by Gerrit0** [comment]
I'm not sure I can be more clear... perhaps this?

When converting a link tag, it gets a `target` attribute which says where it goes. This might be a reflection ID if it is pointing at a reflection, or it might be a ReflectionSymbolId, which is an unresolved reference. The resolution step figures out where that symbol ID resolves to.
