### ISSUE TITLE
[question] Why there say: `determine how the project model is generated and output to disk.`? is it means the Options is very important, participated in the whole execution process of TypeDoc?

### ISSUE THREAD

**Issue by liaodalin19903** [TypeStrong/typedoc#2689]
## Search terms

Options, type conversion

## Question

In the [document: options](https://typedoc.org/guides/development/#options)

> TypeDoc provides some 30 options which determine how the project model is generated and output to disk. The [Options](https://typedoc.org/api/classes/Configuration.Options.html) class consolidates application options into a single location and handles type conversion.

1. Is the Options means the input params of a function/ API ?
2. Why there say: `determine how the project model is generated and output to disk.`? is it means the Options is very important, participated in the whole execution process of TypeDoc?
3. What's the meaning of `Options class  consolidates application options into a single location `? 
4. What's the ` type conversion.`? is it refers to convert Int to String?

**Comment by Gerrit0** [comment]
1. Kind of, the options object contains all of TypeDoc's arguments that can be configured by a user via the command line or a config file.
2. It's important, but probably the least interesting piece of typedoc. It holds the `out` and `json` option values, so yes, it controls where stuff is written.
3. *All* available options are known by the options class. If a plugin declares more options, that class is used to do it, this lets it know how to generate a help message if `--help` is given, and whenever getting the value of an option, TypeDoc's code will go back to the options class. 
4. Conversion consists of converting a TS symbol/node/type into a reflection (typedoc model describing a documentation item) https://ts-ast-viewer.com is useful for seeing what symbols & nodes look like, and TypeDoc's json output closely mirrors the reflection structure.
