### ISSUE TITLE
HTML escaping codeblocks

### ISSUE THREAD

**Issue by pjordaan** [TypeStrong/typedoc#269]
What is the intention of codeblocks that contain HTML tags? I'm using this in combination with Angular2, so I have components that have a codeblock telling how to use it in a angular2 template.

When I render this to documentation the html examples are not escaped. Can't seem to find a setting or anything.

**Comment by pjordaan** [comment]
ok, I noticed I can workaround it by writing ``` around it because markdown runs over it.

**Comment by aciccarello** [comment]
Yeah, using ``` is probably what you want if you are putting HTML examples in your docs.

**Comment by aciccarello** [comment]
@pjordaan I'm closing this as the three backticks is the prefered way of adding code snippets.
