### ISSUE TITLE
[question] Why define enum by `[ts.SymbolFlags.RegularEnum]: convertEnum`?

### ISSUE THREAD

**Issue by liaodalin19903** [TypeStrong/typedoc#2691]
## Question

Hi, 
When I read [converter/symbols.ts](https://github.com/TypeStrong/typedoc/blob/v0.26.6/src/lib/converter/symbols.ts#L38) source code:

```
[ts.SymbolFlags.RegularEnum]: convertEnum,
```

this is define the Enum right? why there don't use the `enum` to define like below way:
```
enum Color {
  Red = 1,
  Green = 2,
  Blue = 3
}
```

**Comment by liaodalin19903** [comment]
1、I mean why use `ts.SymbolFlags` to contain the `RegularEnum`?
2、do you mean only can use `ts.SymbolFlags` to define a flag? and what's the relationship between `flag` and `TS compiler`?

**Comment by Gerrit0** [comment]
That question doesn't really make sense... `RegularEnum` is defined by TS, typedoc is just using it.
