### ISSUE TITLE
[question] How does TypeDoc obtain the Class Hierarchy data?

### ISSUE THREAD

**Issue by liaodalin19903** [TypeStrong/typedoc#2695]
## Search terms

Class Hierarchy , traverse

## Question

Hi, 
Typedoc  has the function of Class Hierarchy:

![QQ20240902-181549](https://github.com/user-attachments/assets/0e284d0e-9ca3-4fec-9184-cdb41dddd353)

which means the typedoc traverse the soruce files under the project directory,
but I didn't find where is the method for implement the `Class Hierarchy` data structure. 
only theme definition:
![QQ_1725272602817](https://github.com/user-attachments/assets/4249bfbe-466b-4147-aa4d-ab18a3257a14)

**Comment by Gerrit0** [comment]
https://github.com/TypeStrong/typedoc/blob/43f1dc20540b9bc6af1125db6cf0ed6deffccc00/src/lib/converter/plugins/TypePlugin.ts#L120
