### ISSUE TITLE
The @defaultValue tag can not transform to “zh_cn” language

### ISSUE THREAD

**Issue by Gengkaibo** [TypeStrong/typedoc#2702]
## Problem

The default theme does not attach special behavior to this tag, displaying its contents under a # Default Value header like other block tags.

I have read the document above, why can't '@ defaultValue' be translated into Chinese? Everything else has been translated, but this one doesn't look good without translation

## Suggested Solution

Please transform it when i set the locale with "zh"

**Comment by Gerrit0** [comment]
It can be, it just hasn't been translated, see near the bottom of - https://github.com/TypeStrong/typedoc/blob/master/src/lib/internationalization/locales/zh.cts

**Comment by Gerrit0** [comment]
Actually, this has been added now, I just haven't released it, will be this weekend: https://github.com/TypeStrong/typedoc/commit/93138bd57bed4beb15830ee071c6b8e4a9ad3ff7
