### ISSUE TITLE
Improve warning "Foo, defined in ./xxx, is referenced by foo but not included in the documentation"

### ISSUE THREAD

**Issue by ibc** [TypeStrong/typedoc#2703]
## Search Terms

"warnings"

## Problem

- I try to export function `foo()` which returns type `Foo`.
- Type `Foo` depends on type `Bar`.
- Function `foo()` and type `Foo` are properly "typedocumented" but type `Bar` is not.

Then a warning like this is shown:

```
[warning] Foo, defined in ./src/xxxx.ts, is referenced by foo but not included in the documentation
```

I figured out the problem by following all types that `Foo` depends on and checking whether they have proper inline doc or not. However...

## Suggested Solution

```
[warning] Foo, defined in ./src/xxxx.ts, is referenced by foo but references Bar which is not included in the documentation
```

Not sure if this is possible but would help a lot.

Aside of this, it could be great some new `@ignoreNotDocumented` tag for cases in which we want to mandate that all exported things are documented (`"treatWarningsAsErrors": true`) and just have some explicit exceptions. Note: I can open a separate and much better documented ticket for this thing.

**Comment by ibc** [comment]
> Aside of this, it could be great some new `@ignoreNotDocumented` tag for cases in which we want to mandate that all exported things are documented (`"treatWarningsAsErrors": true`) and just have some explicit exceptions. Note: I can open a separate and much better documented ticket for this thing.

I've opened a separate ticket for this:

https://github.com/TypeStrong/typedoc/issues/2704

**Comment by Gerrit0** [comment]
Your explanation doesn't make sense... I think you are conflating TypeDoc's not documented and not exported warnings.

That warning is saying that `Foo` is not exported, and that users might reasonably expect it to be as you *do* export `foo`, which references `Foo`.

`Bar` doesn't come into the equation at all, until, maybe, you decide to export `Foo`, and then you might get a warning that `Foo` references `Bar`, but `Bar` isn't exported.

**Comment by ibc** [comment]
I promise that what I saw yesterday is that typedoc complains because "`Foo` was not included in the documentation" but the real problem was that `Foo` depends on `Bar` which didn't have documentation.

Anyway and no idea how, I cannot reproduce it anymore and in fact now I see the proper and expected warning error if I try to replicate yesterday's code.

Sorry for the noise. I'll close this issue and comment on it if I see something similar and reproducible in the future.
