### ISSUE TITLE
Add tag @ignoreNotDocumented to explicitly exclude it from generated docs

### ISSUE THREAD

**Issue by ibc** [TypeStrong/typedoc#2704]
## Search Terms

"tags", "exclude", "ignore"

## Problem

This is pseudo-code since real code is way more complex but I hope I can simplify it:

I have some types for a custom `EnhancedEventEmitter` class. Basically I have a `FooEvents` that is the list of events (and their arguments) emitted by class `Foo`. And this is how it looks once documented by Typedoc:

```ts
FooEvents:
    | EventType<"started">
    | EventType<"stopped", [reason: string]>;
```

Here, `EventType` is internally defined as this:

```ts
export type EventType<Name extends string, Args extends any[] = []> = {
  name: Name;
  args: Args;
};
```

The application should basically do this:

```ts
foo.on('started', () => { ... });
foo.on('stopped', (reason) => { ... });
```

That's basically all. I don't need that the application has access and documentation about `EventType`. The application is **never** gonna need it. So I don't want to pollute the Typedoc generated documentation with the `EventType` definition. It's perfectly fine that in the `FooEvents` type generated by Typedoc, `EventType` is not clickable (which is how it would be if `treatWarningsAsErrors` is `false`).

However I want to use `treatWarningsAsErrors: true` to not miss anything (for example during GitHub CI check actions on PRs).

## Suggested Solution

Basically a new tag:

```ts
/**
 * @hidden
 * @ignoreNotDocumented
 */
export type EventType<Name extends string, Args extends any[] = []> = {
  name: Name;
  args: Args;
};
```

Meaning that such a tag is that Typedoc won't complain if it should generate documentation for this type but it doesn't have documentation (due to the `@hidden` tag). Instead, Typedoc should silently ignore this problem and just print this type in the generated documentation as plain text (instead of a link) and should not include `EventType` in the generated docs.

Another easier solution would be a `@excludeFromDocumentation` tag. But this is not the same as `@ignore` or `@hidden`. Its meaning would be something like "exclude this type from the generated documentation and do NOT complain if some other type (included in the generated documentation) depends on it".

**Comment by Gerrit0** [comment]
TypeDoc has the [intentionallyNotExported](https://typedoc.org/options/validation/#intentionallynotexported) option for this, though at the moment I'm leaning towards thinking that `@hidden` / `@ignore` should implicitly add their symbols to that list...

**Comment by ibc** [comment]
> TypeDoc has the [intentionallyNotExported](https://typedoc.org/options/validation/#intentionallynotexported) option for this, though at the moment I'm leaning towards thinking that `@hidden` / `@ignore` should implicitly add their symbols to that list...

Having to write symbols in `intentionallyNotExported` array is not comfortable at all honestly. And yes, my expectation was that if I add `@hidden` or `@ignore` in a type then Typedoc should not complain and should just silently exclude that symbol from the generated doc no matter there are other exported and documented types that depend on it.

**Comment by ibc** [comment]
Thanks for the fix/change. BTW is a new npm version planned?

**Comment by Gerrit0** [comment]
I'm hoping to put out the first 0.27 beta either this weekend or next weekend, which will include this.

**Comment by ibc** [comment]
I'm using typedoc 0.27.4 and I don't see this working.

In `enhancedEventEmitter.ts` file (note the `@ignore` tag which is supposed to do the trick in typedoc 0.27):

```ts
/**
 * @ignore
 */
export type EventType<Name extends string, Args extends any[] = []> = {
  name: Name;
  args: Args;
};
```

It fails:

```
[warning] EventType, defined in ./src/enhancedEventEmitter.ts, is referenced by index.types.MediaDeviceHandlerEvents but not included in the documentation
[warning] Found 0 errors and 1 warnings
```

The only way to silence that warning is by doing the same I did in previous versions of typedoc in its settings:

```json
intentionallyNotExported: [
  'src/enhancedEventEmitter.ts:EventType'
]
```

Meaning that AFAIS, typedoc 0.27 doesn't change the behavior.

**Comment by Gerrit0** [comment]
I cannot reproduce this. I tossed the following into a file, ran TypeDoc on it, and received no warnings.

```ts
/** Docs */
export interface GH2704 {
    /** Docs */
    FooEvents: EventType<"started"> | EventType<"stopped", [reason: string]>;
}

/**
 * @ignore
 */
export type EventType<Name extends string, Args extends any[] = []> = {
    name: Name;
    args: Args;
};
```

**Comment by ibc** [comment]
@Gerrit0 I've re-checked and I confirm that it doesn't work as expected. The code in your last comment works because `EventType` is **also** exported. But the thing here is that I don't want to export `EventType` publicly, so I remove the `export` keyword:

```ts
/** Docs */
export interface GH2704 {
    /** Docs */
    FooEvents: EventType<"started"> | EventType<"stopped", [reason: string]>;
}

/**
 * @ignore
 */
type EventType<Name extends string, Args extends any[] = []> = {
    name: Name;
    args: Args;
};
```

```
> typedoc --emit none

[warning] EventType, defined in ./src/publicTypes.ts, is referenced by index.types.GH2704.FooEvents but not included in the documentation
[warning] Found 0 errors and 1 warnings
```

So AFAIU the trick only works if the not documented type has `@ignore` and **it's publicly exported**. But what about if I don't want to export it? Then the only workaround I see is including it in `intentionallyNotExported` which is a bit cumbersome.

**Comment by Gerrit0** [comment]
Yes, that's correct, and a design limitation of how TypeDoc works. If the symbol isn't exported, TypeDoc never looks at it, so it doesn't ever see the `@ignore` annotation. Validation for missing exports happens after the TS program has been discarded, so typedoc also can't wait and check the symbol at that point.

You could technically make typedoc visit non-exported types with typedoc-plugin-missing-exports, but that feels like an awful hack.

**Comment by ibc** [comment]
Thanks, it's clear now.
