### ISSUE TITLE
How to translate the JSON output schema to Python

### ISSUE THREAD

**Issue by pawamoy** [TypeStrong/typedoc#2705]
## Search terms

json output schema python

## Question

What would be the best way to translate the JSON output schema into Python code? I'm trying to load back the JSON output into Python dataclasses. Is there an actual schema of the output somewhere, or just the documentation at https://typedoc.org/api/modules/JSONOutput.html? For now I've written classes rather manually, and now it's just trial and error, getting bug reports from awesome users that let me know when my models do not support fields appearing in the JSON output of typedoc. I wonder if I shouldn't start again from scratch and replicate all the models documented in https://typedoc.org/api/modules/JSONOutput.html, or I could somehow ask an LLM to translate a JSON schema into Python dataclasses.

**Comment by Gerrit0** [comment]
I'd probably toss a TS to json schema tool like https://github.com/vega/ts-json-schema-generator at the interface

**Comment by pawamoy** [comment]
Thanks @Gerrit0! I'll try that and report that. Feel free to close this in the mean time as there's nothing actionable for you here.

**Comment by pawamoy** [comment]
Not sure I'm using it right:

```console
% npx ts-json-schema-generator --path src/**/*.ts --type JSONOutput --no-type-check
error TSJ - 102: No root type "JSONOutput" found
```

**Comment by Gerrit0** [comment]
The root type should be ProjectReflection, and you'll probably need a type checker

**Comment by pawamoy** [comment]
Thanks! I wasn't able to find that out myself by just looking at the root index.ts (I'm not experienced with TypeScript :sweat_smile:). About the type checker, I'm getting lots of errors if I don't disable it. The output is longer than the buffer of my VSCode terminal, but here are the last three items:

```
  /media/data/dev/typedoc/src/lib/utils/tsconfig.ts:1:8
    1 import ts from "typescript";
             ~~
    Module '"/media/data/dev/typedoc/node_modules/typescript/lib/typescript"' can only be default-imported using the 'esModuleInterop' flag
  /media/data/dev/typedoc/src/lib/utils/tsutils.ts:13:19
    13         sym = sym.parent;
                         ~~~~~~
    Property 'parent' does not exist on type 'Symbol'.
  /media/data/dev/typedoc/src/lib/validation/exports.ts:45:49
    45             for (const [index, [file, name]] of processed.entries()) {
                                                       ~~~~~~~~~~~~~~~~~~~
    Type 'ArrayIterator<[number, [string, string]]>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
```

Anyway, it works with `--no-type-check` :slightly_smiling_face:

**Comment by pawamoy** [comment]
I got interesting results with https://github.com/koxudaxi/datamodel-code-generator :slightly_smiling_face:
