### ISSUE TITLE
[question] How do typedoc implement the plugin system? 

### ISSUE THREAD

**Issue by liaodalin19903** [TypeStrong/typedoc#2708]
## Search terms

plugins, plugin system

## Question

Hi, 
Under normal circumstances, a plugin system needs to be designed in advance, then implement plugins, register plugins. However, when I read the source code of Typedoc:

Only see:
1.【implemented】All implemented plugins are under `lib/converter/plugins/`.

2.【Export】
```
lib/converter/plugins/index -> lib/converter/index
```
There is nowhere to see where plugins are registered to the system.

3.I search for "TypePlugin" among them.
There is only export as well. There is nowhere to see where it is imported and used.
![image](https://github.com/user-attachments/assets/91e4ac42-dbdc-4f2f-b02e-04240bb1256e)

**Comment by Gerrit0** [comment]
The `@Component` decorator on that class will automatically construct it when the parent component (Converter in this case) is created.

This bit of magic is something that's going away in the next 0.x release.
