### ISSUE TITLE
Overridden methods incorrectly described as "overwriting"

### ISSUE THREAD

**Issue by ianhlavats** [TypeStrong/typedoc#271]
When a subclass overrides a method defined in a superclass, typedoc generates the text "Overwrites ParentClass.someMethod". 

It should generate "Overrides ParentClass.someMethod".

**Comment by aciccarello** [comment]
PR? :wink:

**Comment by Radagaisus** [comment]
Relevant PR: https://github.com/TypeStrong/typedoc-default-themes/pull/13.

**Comment by Radagaisus** [comment]
@aciccarello Relevant PR: https://github.com/TypeStrong/typedoc-default-themes/pull/13.

**Comment by Gerrit0** [comment]
Fixed in https://github.com/TypeStrong/typedoc-default-themes/commit/26bc6b783fdb4ad55c3a1fd3991d485d44414378
