### ISSUE TITLE
Is there a way to prevent type aliases and enums from being converted to the underlying type?

### ISSUE THREAD

**Issue by dev7355608** [TypeStrong/typedoc#2712]
## Search terms

enum, type alias

## Question

Is there a way to prevent type aliases and enums from being converted to the underlying type? In the example below I would like `Alias` and `Enum` to show up as `Alias` and `Enum` instead of `number`.

```js
/**
 * @typedef {number} Alias
 */

/**
 * @enum {number}
 */
export const Enum = { FOO: 0, BAR: 1 };

/**
 * @param {Alias} alias
 * @param {Enum} value
 */
export function test(alias, value) {}

/** Test */
export class Test {
  /** @type {Alias} */
  alias;
  /** @type {Enum} */
  value;
}
``` 

![image](https://github.com/user-attachments/assets/39ab20d4-bbc8-4a31-b875-1d389eb7c7a8) ![image](https://github.com/user-attachments/assets/f1f182cd-50a5-4bda-b986-cb497221c5ae)

**Comment by Gerrit0** [comment]
TypeScript (& therefore TypeDoc) will preserve type aliases if they aren't identical to the underlying type.

```ts
/**
 * @typedef {number & {}} Alias
 */
```

**Comment by dev7355608** [comment]
So is this intended behavior, or is this something TypeDoc doesn't have control over?

Thanks for `& {}` trick! It isn't particularly pretty that the `& {}` appears in type alias of the generated docs, but I can live with that. The `& {}` trick also works for enums, and it doesn't look like the `& {}` appears anywhere in the generated docs in the case of enums, which is nice.

**Comment by Gerrit0** [comment]
It's something that TypeDoc doesn't have control over, when TypeDoc gets the type of the parameter TypeScript just replies with `number`.

Technically TypeDoc *could* try to infer where this was intended by checking both the type and the type node, but this doesn't always work, and isn't always possible, so I've decided to not introduce entirely too much complexity to support that.

A plugin could also be used to rewrite type aliases which are `X & {}` to just be `X` pretty easily

**Comment by dev7355608** [comment]
A plugin that automatically strips the `& {}` from the output and treats enum types as if there was a `& {}` sounds nice. Is there an example plugin out there that does something similar to help me get started?

**Comment by Gerrit0** [comment]
> A plugin that automatically strips the `& {}` from the output

Easy enough:

```bash
npx typedoc --plugin ./plugin.js
```

```js
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, (context, decl) => {
        if (!decl.kindOf(td.ReflectionKind.TypeAlias) || decl.type?.type !== "intersection") {
            return;
        }

        const emptyObjIndex = decl.type.types.findIndex(
            (t) => t.type === "reflection" && !t.declaration.children && !t.declaration.signatures,
        );

        if (emptyObjIndex !== -1) {
            decl.type.types.splice(emptyObjIndex, 1);
        }
    });
}
```

> and treats enum types as if there was a `& {}`

Not possible, as that would require modifying the types, which isn't possible via TypeScript's API.

**Comment by dev7355608** [comment]
Thank you!
