### ISSUE TITLE
Why isn't the function signature of overridden functions showing up correctly?

### ISSUE THREAD

**Issue by dev7355608** [TypeStrong/typedoc#2713]
## Search terms

override, inheritDoc, function signature

## Question

It looks like instead of simply copying the function signature of the base function it tries to infer the signature from the source code of the function. In the example below `arg` has the type `any` instead of `number` and the return type is `1 | 2` instead of `number`. Is there something I'm doing wrong?

```js
/** A */
export class A {
    /**
     * This is the `foo` function.
     * @param {boolean} arg
     * @returns {number}
     */
    foo(arg) {
        return 0;
    }
}

/** B */
export class B extends A {
    /** @override */
    foo(arg) {
        return arg ? 1 : 2;
    }
}
```

Generated documentation of `B.foo` (left with `@override`; right with `@inheritDoc`):
![image](https://github.com/user-attachments/assets/2178e3b5-9065-4119-a05c-e90ce1dc4fb8) ![image](https://github.com/user-attachments/assets/5d4c1bdc-ca3f-4f0a-ac3b-4ef32c833e20)

**Comment by Gerrit0** [comment]
This behavior is determined by TypeScript, not TypeDoc. TypeDoc is just using the type reported by the compiler. As for why it is like this, I believe the team has tried to change this in the past, but hasn't been satisfied with the results... there's definitely an issue in the TS repo with more info.

**Comment by Gerrit0** [comment]
While TypeDoc *could* do that, it won't, because it would result in docs which lie to the users about what that class's types accept.

```ts
const x = new B();
x.foo("this is totally fine according to TS");
x.foo({ this: 2 });
```

Yes, the workaround is to repeat the param/returns tags. This is a disadvantage to writing JS vs TS, as the description then needs to be repeated, while in TS the types could just be repeated.

**Comment by dev7355608** [comment]
I see. Thanks again!
