### ISSUE TITLE
从另外一个声明文件中import进来的类型声明，在构建结果中找不到，请问是不支持，还是需要调整什么配置？

### ISSUE THREAD

**Issue by williampang2021** [TypeStrong/typedoc#2716]
## Question

// index.ts
import { type TestParam } from './types/TestParam';

/**
 * 测试aa
 * @param param - 参数对象的描述
 */
export const aa = (param: TestParam) => {
  if (param.age) {
    console.log('test');
  }
};

// TestParam.ts
export interface TestParam {
  name: string;
  age: number;
}

构建结果
<img width="675" alt="image" src="https://github.com/user-attachments/assets/caa7cc24-f6b8-469d-89fb-a9a62f194070">

# 版本
 "typedoc": "^0.26.7",
"typescript": "^5.3.3",

typedoc配置内容：
{
  cleanOutputDir: true,
  searchInComments: true,
  hideGenerator: true,
  includeVersion: true,
  entryPointStrategy: 'packages',
  entryPoints: ['packages/*'],
  out: 'typedocs',
  kindSortOrder: ['Function', 'Method', 'Property'],
  theme: 'default',
};

**Comment by Gerrit0** [comment]
我不懂中文

Given that it looks like you want to include documentation for members not exported, you probably want a pluign like this one: https://www.npmjs.com/package/typedoc-plugin-missing-exports

**Comment by williampang2021** [comment]
OK。It woks
