### ISSUE TITLE
Documents section missing from modules.html when there are no public exports

### ISSUE THREAD

**Issue by mrfigg** [TypeStrong/typedoc#2722]
## Search terms

packageDocumentation document index missing

## Expected Behavior

If a module includes a `@packageDocumentation` tag containing one or more `@document` tags and does not have any public exports, the 'Documents' section does not appear on the index page (modules.html).

## Actual Behavior

The 'Documents' section should appear on the index page (modules.html).

## Steps to reproduce the bug

src/index.ts:
```ts
/**
 * @packageDocumentation
 * Example
 *
 * @document ../CHANGELOG.md
 * @document ../LICENSE.md
 * @document ../README.md
 */

/** @private */
export function helloWorld() {
  return "Hello World";
}
```

typedoc.json:
```json
{
  "entryPoints": ["./src/index.ts"],
  "out": "./docs",
}
```

docs/modules.html screenshot:
![example](https://github.com/user-attachments/assets/fdd6ad57-56bc-4896-9270-07495ac7232c)

## Environment

-   Typedoc version: 0.26.7
-   TypeScript version: 5.6.2
-   Node.js version: 20.11.1
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Fixed with 77cf91777b2b900118cba2a0f91d10296e3e411d
