### ISSUE TITLE
Document page headings that are consistent with other pages

### ISSUE THREAD

**Issue by mrfigg** [TypeStrong/typedoc#2727]
I'm not sure if I should label this as a bug or feature request, but this one feels more like a feature request to me.

## Search Terms

documents headings

## Problem

Currently document page headings are missing, which is inconsistent with other pages.

## Suggested Solution

Option 1:
Include an h1 heading on document pages by default and add an `omitDocumentHeadings` boolean option.

Option 2:
Add an `includeDocumentHeadings` boolean option that when set adds an h1 heading to document pages.

Option 3 (preferred):
Include an h1 heading in document page titles, then check if documents start with a heading that matches the document name and remove it if found.

**Comment by Gerrit0** [comment]
Going to track this as a part of #2729, it doesn't need its own issue.
