### ISSUE TITLE
Breadcrumbs are missing on project page

### ISSUE THREAD

**Issue by mrfigg** [TypeStrong/typedoc#2728]
Not sure if I should label this as a bug or feature request, but this one feels more like a bug to me.

## Search terms

breadcrumbs headings modules index

## Expected Behavior

Expected page title breadcrumbs and heading to be consistent across all pages.

## Actual Behavior

Breadcrumbs are missing from the modules.html index page despite being on all other index pages (modules/*.html). Also the heading is an h2 instead of an h1.

## Steps to reproduce the bug

src/index.ts:
```ts
/**
 * @packageDocumentation
 * Example
 *
 * @document ../CHANGELOG.md
 * @document ../LICENSE.md
 * @document ../README.md
 */

/** @private */
export function helloWorld() {
  return "Hello World";
}
```

typedoc.json:
```json
{
  "entryPoints": ["./src/index.ts"],
  "out": "./docs"
}
```

docs/modules.html screenshot:
![example](https://github.com/user-attachments/assets/fca1ef24-85f0-4461-9ff4-fd18dc3648b9)

Compared to:

src/index.ts:
```ts
/**
 * @packageDocumentation
 * Example
 *
 * @document ../CHANGELOG.md
 * @document ../LICENSE.md
 */

/** @private */
export function helloWorld() {
  return "Hello World";
}
```

typedoc.json:
```json
{
  "entryPoints": ["./src/index.ts"],
  "out": "./docs",
  "projectDocuments": ["./README.md"]
}
```

docs/modules/index.html screenshot:
![example2](https://github.com/user-attachments/assets/2067c6e9-235a-4c72-a845-0763076c0b1c)

## Environment

-   Typedoc version: 0.26.8
-   TypeScript version: 5.6.2
-   Node.js version: 20.11.1
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Easy enough to change:

https://github.com/TypeStrong/typedoc/blob/1cefc011948fa06f798a0763ba5cc9d32f6ac04e/src/lib/output/themes/default/partials/header.tsx#L11
