### ISSUE TITLE
Category of DeclarationReflections not seen by plugin (and missing category description in output)

### ISSUE THREAD

**Issue by krisztianb** [TypeStrong/typedoc#2731]
## Search terms

category, categoryDescription, DeclarationReflections, output, plugin

## Question

First up: I asked about this on [Discord](https://discord.com/channels/508357248330760243/829307039447515176/1292050925107675137) so this is the same issue.

I'm the author of [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules). Recently somebody using the plugin mentioned that he is missing category descriptions (added using the `@categoryDescription` tag) in the generated documentation when using my plugin.

So I debugged into this and actually found that my plugin does nothing with categories at all because it doesn't even see them. The question is: Why?

I created a repo to reproduce here: https://github.com/krisztianb/typedoc-plugin-merge-modules/tree/GH-18-missing-category-descriptions

Things to do:

```bash
npm install
npm run build
npm test
```

The generated output looks like this:

![image](https://github.com/user-attachments/assets/ad8074f0-2afb-400e-aecb-ec23c82b66db)

Alpha and Beta are categories and as you can see Beta is missing [its description](https://github.com/krisztianb/typedoc-plugin-merge-modules/blob/GH-18-missing-category-descriptions/test/merge-module/input/b.ts#L4).

The TypeDoc output (with my added debug logs to the console) looks like this:

```bash
==================================== TEST MERGE MODULE =============================================
[info] Loaded plugin typedoc-plugin-merge-modules
=================================== MODULE =====================================
=================================== REFLECTION =====================================
CATEGORIES undefined
GROUPS undefined
=================================== MODULE =====================================
=================================== REFLECTION =====================================
CATEGORIES undefined
GROUPS undefined
=================================== MODULE =====================================
=================================== REFLECTION =====================================
CATEGORIES undefined
GROUPS undefined
[info] Documentation generated at ./output
```

As you can see there are no categories on the DeclarationReflections [output here](https://github.com/krisztianb/typedoc-plugin-merge-modules/blob/GH-18-missing-category-descriptions/src/merger/module_bundle.ts#L100).

The funny thing is that if I deactivate the plugin the category description of Beta is there in the generated output.

Any idea what the problem here could be?

**Comment by Gerrit0** [comment]
With a quick glance, it appears that this is because the plugin is listening with priority 0

https://github.com/krisztianb/typedoc-plugin-merge-modules/blob/33ffcfe92816dcfa6756a9757d72cfda6f55d478/src/plugin.ts#L65C1-L67

While the category plugin is listening with priority -200

https://github.com/TypeStrong/typedoc/blob/1cefc011948fa06f798a0763ba5cc9d32f6ac04e/src/lib/converter/plugins/CategoryPlugin.ts#L46

Higher priority listeners are called earlier, so categorization hasn't happened yet.

**Comment by krisztianb** [comment]
Thank you for looking into this.

What I see is that my plugin is hooking into `Converter.EVENT_RESOLVE_BEGIN` and not `Converter.EVENT_BEGIN`. It looks like `Converter.EVENT_RESOLVE_BEGIN` happens earlier and is used because the plugin manipulates the reflection collection within the project. If I use `Converter.EVENT_BEGIN` then the plugin doesn't work.

So the question for me is why would manipulating the reflection collection break the category descriptions?

**Comment by Gerrit0** [comment]
Sorry, I linked to the wrong line, I meant to link to line 47, though that happens at EVENT_RESOLVE_END, which is definitely after your plugin.

https://github.com/TypeStrong/typedoc/blob/1cefc011948fa06f798a0763ba5cc9d32f6ac04e/src/lib/converter/plugins/CategoryPlugin.ts#L47-L51

Descriptions come from the comment on the parent reflection's comment, and the comment is modified during that end listener, stripping out the category description.

Therefore, to fully merge the modules your plugin needs to copy the `@categoryDescription` (and `@groupDescription`) tags from the source module's comment to the target module's comment block tags array.
