### ISSUE TITLE
Ability to override `displayName` for `entryPoints`

### ISSUE THREAD

**Issue by hybridherbst** [TypeStrong/typedoc#2735]
## Search Terms

displayName, entryPoint

## Problem

When using entry points that don't end with "/index.<ext>", TypeDoc currently keeps that filename as part of the display name of the entry point. This leads to ugly URLs and ugly links – note the "_api" and "/api" parts where none should be:

![image](https://github.com/user-attachments/assets/c44a460d-6604-486c-a2ed-5e35e034070f)

## Suggested Solution

Some way to configure displayName when the entry points are not "/index.js". 
In our case, they are named "/api.js".

**Comment by Gerrit0** [comment]
You can do this today on a case by case basis with the [`@module`](https://typedoc.org/tags/module/) tag, or with a tiny plugin:

```bash
typedoc --plugin ./plugin.mjs
```

```js
import td from "typedoc";
/** @param {td.Application} app */
export function load(app) {
  app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, (context, refl) => {
    if (refl.name.endsWith("/api")) {
      refl.name = refl.name.replace("/api", "");
    }
  });
}
```

**Comment by hybridherbst** [comment]
Thanks – I tried this but it looks like createDeclaration is not called for module names, it's called for the individual Reflections. Am I missing something?

**Comment by Gerrit0** [comment]
It seems to work for me, `npx typedoc src/test/**/*.ts --plugin ./plugins/gh2735.js`

![image](https://github.com/user-attachments/assets/19f96517-e44d-416f-b9dc-9dda557b5827)

```
$ tree src/test
src/test
├── api.ts
├── someOtherTest
│   └── api.ts
└── someTest
    └── api.ts

3 directories, 3 files
```

It won't work if you're using packages mode for each of those as those aren't (initially) declaration reflections, but project reflections. Is that the case in your configuration?

**Comment by hybridherbst** [comment]
OK, got it to work! Thank you!
