### ISSUE TITLE
allow including undocumented symbols under stricter project settings

### ISSUE THREAD

**Issue by nbsp** [TypeStrong/typedoc#2737]
## Search terms

undocumented, include, exported

## Question

i've got a project that has `validation.notDocumented` and `treatValidationWarningsAsErrors` both set to `true`, to force all exported symbols to be documented as part of CI. however, i do have a couple of things that it would be unnecessary to document, and i've been trying to get them to show up on the generated page anyway.

everything i've tried either hides the symbol from documentation completely (`@ignore`), or keeps complaining about the symbol being undocumented (empty doc, `@public`, empty `@privateRemarks`, etc.)

is there a setting i missed somewhere?

**Comment by Gerrit0** [comment]
There is not a setting to ignore some undocumented members besides the [requiredToBeDocumented](https://typedoc.org/options/validation/#requiredtobedocumented) option which filters by kind.

TypeDoc determines that there is documentation based on the comment having any content in the summary section, or containing any block tags which aren't excluded. `@privateRemarks` is excluded, and `@public` is a modifier tag, so neither of those would work.

It seems somewhat wrong to me to introduce an intentionallyNotDocumented option which parallels the [intentionallyNotExported](https://typedoc.org/options/validation/#intentionallynotexported) option... the amount of time to open your typedoc config, find the intentionallyNotDocumented section, and add a symbol name is probably equal or even longer to adding a comment with even just 3 words of description...

**Comment by nbsp** [comment]
makes sense. thanks!
