### ISSUE TITLE
Document Content doesn't work for base `README.md` file

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2740]
## Search Terms

external, documentation, index, hierarchy, directory, base, readme

(Ref: #2651)

## Problem

Here is the README file in my package directory, with [document content](https://typedoc.org/guides/documents/#document-content):

```md
---
title: Examples
children:
    - ./examples/Linear Data Fitting.md
    - ./examples/Single Variable.md
    - ./examples/Multi Variable.md
---
## Getting Started

Here's the contents of my main README file...
```

Unfortunately it does not actually generate pages for `examples/example[1,2,3].md` even though the files exist.

> Note: This works for another file. If I create a "dummy" file called `examples.md` and paste the same code, it works exactly like I'd intend.

![image](https://github.com/user-attachments/assets/ac5219c6-73e9-48e6-8733-b9bb7b88c8b0)

## Suggested Solution

Allow document content in the base README file.

**Comment by Gerrit0** [comment]
This is because the readme file is not actually a real document. It is a carry-over from before typedoc had documents.

To specify additional documents for the project; use the projectDocuments option

**Comment by nicfv** [comment]
> To specify additional documents for the project; use the projectDocuments option

This would be ideal, but with the mono-repo style, I have varying names for my example markdown pages. I tried to do something like this:

```json
    "packageOptions": {
        "projectDocuments": [
            "*.md",
        ],
        ...
    },
```

...which does give me the changelog and examples, great. Unfortunately, it creates an extra README page:

![image](https://github.com/user-attachments/assets/d60ed65d-4c70-4cc7-9794-3271510be108)

(Readme can now be accessed through "datafit - v1.4.6" or "README" links)

When I replace `"*.md"` with `"examples/*.md"`, then I get the issue brought up in #2651 

> This is because the readme file is not actually a real document. It is a carry-over from before typedoc had documents.

Perhaps this issue raises the suggestion to treat `readme.md` as an actual document?

**Comment by Gerrit0** [comment]
There are a couple options there:

1. Set `"readme": "none"` in the packageOptions to keep the readme document, but leave out the project readme content
2. Use `!(README).md` as the glob for the project documents
3. Specify typedoc configuration in each package separately
