### ISSUE TITLE
Understanding/debugging why {@link } and other tags are not resolved correctly

### ISSUE THREAD

**Issue by hybridherbst** [TypeStrong/typedoc#2742]
## Search Terms

@link, tags, inline

## Problem

I have inline link tags. In some cases, they are resolved correctly, while in other cases, it just looks like this in the exported page: 

<img width="784" alt="image" src="https://github.com/user-attachments/assets/5c057fe4-49ef-4792-a645-6993297a245d">

TypeScript / VS Code finds the referenced code just fine when clicking on the link in VS Code.

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/579f036a-4833-4e13-a1de-8ef7133beda4">

Invalid link validation is true.

## Suggested Solution

Would be great to know how to 
1. see such errors (right now it's just random that I detect it on the built pages, there's no logs about it)
2. understand why they happen (why some work and others don't)
3. resolve the issues (without having to modify the actual code – in VSCode it works fine, just TypeDoc doesn't find the reference)

**Comment by Gerrit0** [comment]
In VSCode it works fine because VSCode doesn't know about inline code blocks. TypeDoc, on the other hand does, so it doesn't see a link tag, it sees a code block which cannot contain tags.

**Comment by Gerrit0** [comment]
If you want your link text to be styled as code, you have two options:

- ``{@link Foo | `Foo`}``
- `{@linkcode Foo}`

**Comment by hybridherbst** [comment]
I see, thanks – I didn't even notice the backticks around the bottom two links, makes sense.

Still, the first one – {@link Behaviour} – is not resolved correctly, is there a way to see errors for that / debug that? It's a bit annoying if it "just" ends up not being resolved without a chance to fix it / work around it.

**Comment by Gerrit0** [comment]
The behavior link *should* show up in warnings due to it not being resolved. Are you on the latest version? There was a bug prior to 0.27.6 which prevented those from being printed.

If you are, can you point me towards a project I can run?

**Comment by hybridherbst** [comment]
Sorry for the late response – I'm still trying to cleanly reproduce this. I'll reopen the issue if I find a good way.
