### ISSUE TITLE
Understanding how "entryPoints" and "modules" work together

### ISSUE THREAD

**Issue by hybridherbst** [TypeStrong/typedoc#2745]
## Search terms

entry points, modules, hierarchy, organization

## Question

It's not entirely clear to me how to organize code hierarchically with modules in TypeDoc.
It seems that "entryPoints" are always treated as separate modules. What's provided with the "name" property becomes the root module.

Can I nest modules further? Can I for example declare a specific index.js file inside one of the entryPoints as "sub-module"? I tried adding a comment with a tag `@module my-module` at the end as documented, but that neither results in a new module being created nor in that comment showing up somewhere.

**Comment by Gerrit0** [comment]
TypeDoc's procedure for documentation is:

```
Create project (using --name)
For each entry point:
    Convert the provided file as a module, add it as a child of project
```

The "Convert file" step, TypeDoc will follow exports. If those exports happen to be re-exports of other modules (e.g. `export * as ModName from "./module.js"`), then they will be documented as namespaces owned by that module.

If your library expects users to import from subpaths in your library, those paths should also be provided as entry points. If TypeDoc's [navigation.includeFolders](https://typedoc.org/options/output/#navigation) option is set (the default) and the module name includes `/` it will be placed within folders for each parent "folder" in the navigation. However, the module's name is still `parent/foo`. It isn't actually a child of `parent`, so the breadcrumbs on that module page will indicate that it is a direct child of the project reflection.
