### ISSUE TITLE
Inheritance between "groups" and "categories" works different than I'd expect

### ISSUE THREAD

**Issue by hybridherbst** [TypeStrong/typedoc#2746]
## Search terms

categories, groups, options

## Expected Behavior

I'm trying to structure code with both groups and categories.
However, it's not clear to me what has precedence when and when each of those is ignored. 

What I would like to achieve is a sorting where "Groups" come first - e.g. "Components" – and then, inside that, the categories. 

To me it looks like it might be an issue with inheritance – it looks like when _both_ category and group are specified, then I get the ordering that I expect; but when _group_ is specified on a parent class, that is only inherited by classes that do _not_ specify a category.

In other words: I would expect that in "Case E", "Category A" and "Category B" are nested under "Components", not under "Classes".

(Side note: the docs mention that ["categorizeByGroup" is true by default](https://typedoc.org/options/output/#navigationlinks), but it seems actually it's false by default)

### Code:

```ts
export function add(a, b) {}

/**
 * @group Components
 */
export function sum(a, b) {}

/**
 * @group Components
 */
export class MyClass {}

export class MyClass2 extends MyClass {}

/**
 * @category CategoryA
 */
export class MyClass3 extends MyClass {}

/**
 * @category CategoryB
 */
export class MyClass4 extends MyClass {}
```

### Results by config:

<table>
<tr><th>Case</th><th>Config</th><th>Result</th></tr>
<tr><td>A</td><td><pre><code>
  "navigation": {
    "includeFolders": false,
    "includeCategories": false,
    "includeGroups": true
  },
  "categorizeByGroup": false
</code></pre></td><td>
<img width="722" alt="image" src="https://github.com/user-attachments/assets/9ab17ee1-25ec-4a02-9c0f-5fd95320f490">

</td></tr>
<tr><td>B</td><td><pre><code>
  "navigation": {
    "includeFolders": false,
    "includeCategories": true,
    "includeGroups": true
  },
  "categorizeByGroup": false
</code></pre></td><td>
<img width="674" alt="image" src="https://github.com/user-attachments/assets/42a36d3c-b23a-4d0d-869f-2b940fb3a483">

</td></tr>
<tr><td>C</td><td><pre><code>
  "navigation": {
    "includeFolders": false,
    "includeCategories": true,
    "includeGroups": false
  },
  "categorizeByGroup": false
</code></pre></td><td>
<img width="694" alt="image" src="https://github.com/user-attachments/assets/8e774f76-e9b9-4be7-81da-f2b66ff5f92c">

</td></tr>
<tr><td>D</td><td><pre><code>
  "navigation": {
    "includeFolders": false,
    "includeCategories": false,
    "includeGroups": true
  },
  "categorizeByGroup": true
</code></pre></td><td>
<img width="726" alt="image" src="https://github.com/user-attachments/assets/dcc83133-ff50-432c-b316-c07c9d20a13c">

</td></tr>
<tr><td>E</td><td><pre><code>
  "navigation": {
    "includeFolders": false,
    "includeCategories": true,
    "includeGroups": true
  },
  "categorizeByGroup": true
</code></pre></td><td>
<img width="703" alt="image" src="https://github.com/user-attachments/assets/623e99a4-55b8-4724-881f-125933d78d2f">

</td></tr>
<tr><td>F</td><td><pre><code>
  "navigation": {
    "includeFolders": false,
    "includeCategories": true,
    "includeGroups": false
  },
  "categorizeByGroup": true
</code></pre></td><td>
<img width="688" alt="image" src="https://github.com/user-attachments/assets/ad321622-1087-4d4e-ac9d-97e8abc9df40">

</td></tr>
</table>

## Actual Behavior

This structure loses the group on `MyClass3`, `MyClass2` properly has the group:
```ts
/**
 * @group Components
 */
export class MyClass {}

export class MyClass2 extends MyClass {}

/**
 * @category CategoryA
 */
export class MyClass3 extends MyClass {}
```

This structure properly nests `MyClass` in `Component > Category`, which is inherited by `MyClass2`, but then `MyClass3` loses the group that it should inherit:
```ts
/**
 * @group Components
 * @category CategoryC
 */
export class MyClass {}

export class MyClass2 extends MyClass {}

/**
 * @category CategoryA
 */
export class MyClass3 extends MyClass {}
```

## Steps to reproduce the bug

Full repro: 
https://stackblitz.com/edit/vitejs-vite-yz5hhi?
Adjust settings in typedoc.json and src/index.ts as needed.

**Comment by hybridherbst** [comment]
Sorry, didn't see your response.

> The current rule of following regular comment inheritance is straightforward.

What is the current rule? "Inherit if no comment, don't inherit if any comment"?

**Comment by Gerrit0** [comment]
The current rule is "follow regular comment inheritance"

Comments are inherited if a member does not specify a comment, or that member uses the `@inheritDoc` tag
