### ISSUE TITLE
Everything exported as TypeObjectName

### ISSUE THREAD

**Issue by Code-Quake** [TypeStrong/typedoc#2750]
## Question
I have an object declared this way:

/**
 * A class for interacting with THS over WAMP. Use ThsClient.create() to create a new instance.
 *
 * @public
 */
export class MyClient {
  ...random code
}

TypeDoc generates this header in the documentation:

ClassMyClient

It does that for everything in the project; Namespaces, enums, interfaces. All of it.

How do I get it to generate MyClient instead of ClassMyClient

**Comment by Gerrit0** [comment]
There was a bug which caused kind names to be mashed up against the reflection name, #2748

You could do this by (ab)using TypeDoc's [locales option](https://typedoc.org/options/output/#locales) option to overwrite the `kind` translations ([these ones](https://github.com/TypeStrong/typedoc/blob/master/src/lib/internationalization/translatable.ts#L396-L419)) with empty strings.

The right way to do this is with a custom theme which overwrites the [header](https://typedoc.org/api/classes/DefaultThemeRenderContext.html#header) template to remove them, there is no option to remove the type from the header, though I guess the [headings](https://typedoc.org/options/output/#headings) option could be extended with a flag for that...
