### ISSUE TITLE
Sorting of union types is non-deterministic

### ISSUE THREAD

**Issue by imtuanpham** [TypeStrong/typedoc#2751]
This issue is related to https://github.com/TypeStrong/typedoc/issues/2502 but applies to non-literal types. Sorting of union types is non-deterministic.

## Steps to reproduce the bug

```
export type Type1 = 'type1';
export type Type2 = { prop1: string; prop2: boolean };

/**
 * Some Interface
 */
export interface SomeInterface {
  someUnionType: Type1 | Type2;
}
```

### Expected
<img width="478" alt="image" src="https://github.com/user-attachments/assets/00b03078-0821-4d6e-8983-cabde521476e">
 
### Actual
Most of the times it shows
<img width="490" alt="image" src="https://github.com/user-attachments/assets/aae10559-27d1-48da-961a-bae854d9e8cc">

But sometimes it shows
<img width="478" alt="image" src="https://github.com/user-attachments/assets/00b03078-0821-4d6e-8983-cabde521476e">

(This is causing our CI pipeline to fail as we have a job to ensure the API Doc changes are included in pull requests)

## Environment

-   Typedoc version: [v0.26.10](https://github.com/TypeStrong/typedoc/releases/tag/v0.26.10)

**Comment by Gerrit0** [comment]
I can't reproduce this. TypeDoc is using the the type as it is reported from TypeScript, which in the ~30 times I've run it, always puts `"type1"` second in the union.

![image](https://github.com/user-attachments/assets/999dae10-746c-4bc9-b957-f198649c1922)

**Comment by Gerrit0** [comment]
You can work around this by forcing `Type1` to introduce a new type:

```ts
export type Type1 = 'type1' & {};
```
