### ISSUE TITLE
Blank modules page at top level

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2753]
## Search terms

monorepo, blank, modules, html, page, link, index

## Question

Hi, when I visit my typedoc website, it works just fine, both `/` and `/index.html` will point to the project's readme page. I can get to this page by clicking the website name in the header bar at the top. However, if I click on the top-most level of the navigation tree on the left, I get a blank page at `/modules.html`. Why, doesn't it simply just show the modules contained within the repo instead?

![Screenshot_20241020_174405](https://github.com/user-attachments/assets/7572e286-a063-4604-9649-04772b28cdd3)

**Comment by Gerrit0** [comment]
It should... that's a bug.

**Comment by Gerrit0** [comment]
This is because of the change made for #2730. Previously, TypeDoc wouldn't include a modules page at all.

It doesn't work now for packages mode because the group/category plugins aren't run on deserialization, so the project doesn't have any context that the index will render.
