### ISSUE TITLE
Question: How to TypeDoc non module TypeScript project

### ISSUE THREAD

**Issue by bksglatz** [TypeStrong/typedoc#2754]
## Question

Hello there :)

I have a TypeScript project which is not based on a TypeScript module system. The whole project is organized in isolated modules (not a TypeScript module ;)). Every file has to be included in an html document in the right order.

There is a core system module and modules depending on that system module. Lets call them System module and Sub module. 
The code of the System module is stored in a System module directory with its own tsconfig files and own build process. The Sub modules are in Sub module directories next to the System module directory also with its own tsconfig files and build process.

The Sub modules incldue files (at least one) from the System module in their tsconfig to be able to build.

The code is organized in namespace modules and therefore we use  export statements and due to that TypeDoc seems to be able to create a documentation for the System module without further issues. As long as the documentation generation is started from within the System module directory.

But im not able to create a documentation for the Sub modules due to failures (Looks like ts build failures) because of missing Types from the System module.

The typedoc of the System module looks like this:
`{
    "$schema": "https://typedoc.org/schema.json",
    "name": "System module",
    "entryPoints": [ "Main.ts" ],
    "out": "Doc",
    "projectDocuments": [ "" ]
}`

But i did not yet find a way to give them Sub modules access to the Types from the System module. When i add the System module Main.ts as EntryPoint to the Sub module, the Sub module fails to interpret the System module files too. I guess because the System module is now not build from within its own directory.

Any advice would be appreciated :)

**Comment by bksglatz** [comment]
I guess im able to create a minimal example project which shows the behavior im struggeling with. I will link the project here when its done.

**Comment by bksglatz** [comment]
This example [https://github.com/bksglatz/typedoc-issue-example-1](https://github.com/bksglatz/typedoc-issue-example-1) shows the behavior i was talking about.

While creating the example i noticed that the project include from a different directory might not be the problem but the fact that the typedoc.json and therefore the directory from which i run `npx typedoc` is not the same directory which holds the tsconfig.json files. 

When i move the content from Project2/A to Project2 in my example and run  `npx typedoc` everything seems to work fine. 

So i may be able to workaround my issue (Or it may be the "official" way typedoc expects?) when i run typedoc for each tsconfig.json directory in Project2 isolated and merge the results later. But ill have to doublecheck this.

Would still a little bit inconvinient because in my real project this "module" is based on multiple isolated tsconfig.json files that are referenced from a root tsconfig.json by references. Maybe this is not (yet?) supported at all or this fails because the tsconfig.json on the root level is not named tsconfig.json but tsconfig.build.json and is called explicitly in our build environment.

**Comment by manticorp** [comment]
Hmm... this is an interesting one...

I'm able to do ```typedoc``` in the root directory, with the following typedoc.json:

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "name": "Test",
  "entryPoints": [ "Project1/Test1.ts", "Project2/A/A.ts", "Project2/B/B.ts" ],
  "exclude" : ["Doc/", "node_modules/"],
  "out": "Doc",
}
```

which generates something like this (after removing ```"projectDocuments": [ "" ]``` from the subfolders typedoc.json):

![image](https://github.com/user-attachments/assets/46796f17-a83a-47e1-b57c-b59c2e5b6ae5)

So...that works fine...I'm guessing when trying to build in the subfolders, it doesn't respect the "import" from the tsconfigs there.

Is there a reason you're not using plain imports?

By changing ```Project1/test1.ts``` to:

```ts
export namespace Test {
	export interface ITest {
		a: number;
		b: boolean;
	}
	export function func1(p: Test.ITest) {

	}
}
```

And ```Project2/A/A.ts``` to (and similar with B):

```ts
import { Test as Project1Test } from './../../Project1/Test1';

export namespace Test.A {
	export function func1(p: Project1Test.ITest) {

	}
}
```

The typedoc build works fine:

![image](https://github.com/user-attachments/assets/c2c088a5-4ed5-4ab9-9a4a-6707f1a16a80)

Of course this may or may not work depending on your exact scenario...

**Comment by manticorp** [comment]
Sorry I misunderstood the purpose of using includes - I now understand after reading your original issue message.

You're implementing these like this:

```html
<html>
<head>
  <script src="Project1/Project1.js"></script>
  <script src="Project2/A/A.js"></script>
  <script src="Project2/B/B.js"></script>
</head>
<body>
  <script>
    console.log(Test.A.func1({a: 1, b: true}));
  </script>
</body>
</html>
```

So Project2 should have knowledge of ```Project1/Test1.ts``` through the tsconfig files in ```Project2/A``` and ```Project2/B```....

😅

It does appear to be at that TypeDoc does not recognise the include option on nested typescript projects, as the projects themselves build fine...however, I'm not sure this is a bug with Typedoc.

For example, the following structure _does_ work fine:

```
typedoc-issue-example-1
  Project1
      - Test1.ts
      - tsconfig.json
      - typedoc.json
   Project3
      - C.ts
      - tsconfig.json
      - typedoc.json
```

and then

```cd Project3 && npx typedoc``

But the following does not:

```
typedoc-issue-example-1
   Project1
      - Test1.ts
      - tsconfig.json
      - typedoc.json
   Project2
      A
          - A.ts
          - tsconfig.json
      B
          - B.ts
          - tsconfig.json
      - typedoc.json
```

I think this is an issue because the Project2 folder does not have a ```tsconfig.json``` itself - adding one there seems to solve the build issue:

```
typedoc-issue-example-1
   Project1
      - Test1.ts
      - tsconfig.json
      - typedoc.json
   Project2
      A
          - A.ts
          - tsconfig.json
      B
          - B.ts
          - tsconfig.json
      - tsconfig.json
      - typedoc.json
```

Contents:

```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "files": [
    "A/A.ts"
    "B/B.ts"
  ],
  "include": [
    "../Project1/Test1.ts"
  ]
}
```

then running ```npx typedoc```:

![image](https://github.com/user-attachments/assets/cb8f15b9-53ee-4b53-997c-5fef09bd4823)

Does that help?

**Comment by bksglatz** [comment]
Thx for your reply. Yes we include the files the "classic" way in the html document. We can't build our components based on a module system for compatibility reasons. The project was started 10 years ago ;) It is a large api framework that runs extensions from our customers and this would be a breaking change. And even without that it would still be a lot of work because its not a small or medium size code base ;) 

That the missing tsconfig.json in Project2/ might be the problem was something i have thought about too.
In real there is always a tsconfig file in the ProjectXY/ directories referencing the deeper nested tsconfig.json files but its not called tsconfig.json but tsconfig.build.json. Because some projects contain a tsconfig.json for their top level too. I guess tsdoc does only look for "tsconfig.json"?

**Comment by bksglatz** [comment]
My next goal is to try to typedoc each tsconfig.json within a project isolated with json output and merge the results. If this is working this would at least be a way and would not be that much of a problem. Just a bit less convenient.

**Comment by manticorp** [comment]
Typedoc can be told where the tsconfig file is:

[https://typedoc.org/options/configuration/#tsconfig](https://typedoc.org/options/configuration/#tsconfig)

So you could specify explicitly ```tsconfig.build.json```

**Comment by bksglatz** [comment]
This looks interessting :) I had in mind to request a way to override the tsconfig name when my other plan does not work as a possible solution. Didn't know/find that it is already possible. I will doublecheck that first and let you know how it went.

**Comment by bksglatz** [comment]
The "missing" `"tsconfig": "tsconfig.build.json"` seemed to be my problem. Adding it solved the issue for me. Typedoc is now able to resolve all relations and documentation is generated fine. I can start with finetuning now :-) I will close the question (Not sure if im supposed to do it, but the question is answered ¯\_(ツ)_/¯)

@manticorp thx for your help

**Comment by manticorp** [comment]
No worries! Glad I could help and take some of the burden away from the Typedoc team themselves 😄

**Comment by manticorp** [comment]
Also, this may help:

[https://github.com/TypeStrong/typedoc?tab=readme-ov-file#monorepos--workspaces](https://github.com/TypeStrong/typedoc?tab=readme-ov-file#monorepos--workspaces)

[https://github.com/Gerrit0/typedoc-packages-example](https://github.com/Gerrit0/typedoc-packages-example)
