### ISSUE TITLE
Add or rename symbol

### ISSUE THREAD

**Issue by HLuizFilipe** [TypeStrong/typedoc#2757]
I'm in a project which we define entities (or business model, from Hexagonal Architecture) as Interface.

When exported/documented, shows up in the doc.

The trick part is we want to change the name of "Interfaces" by "Entities". 

Example:

```typescript
/**
 * @entity - This tag is something I found how to add/create
 */
interface MyLittleEntity {
    name: string
    country: country
}
```

And showing up like the screenshot below I've crafted

<img width="971" alt="image" src="https://github.com/user-attachments/assets/66b11d64-3007-442d-828f-3dba86fbae59">

----

I'm trying to reverse engineering some plugins and reading the documentation, but looks like "there is no way" to add a new Symbol, or I just didn't find yet.

Is there someone that can help me?

Thanks

## Search terms

symbol
plugin
reverse engineering

**Comment by manticorp** [comment]
Can you just use ```@group Entities``` ?

```ts
/**
 * @group Entities
 */
interface MyLittleEntity {
    name: string
    country: string
}
```

This generates the following:

![image](https://github.com/user-attachments/assets/bf8e6235-a792-4750-8759-07c12c4daa9b)

**Comment by HLuizFilipe** [comment]
@manticorp - Thank you so much!!

Would be nice to have a screenshot on the docs with an example like this, showing what would happen if a specific tag is been used.

I'll open a PR for that :)

**Comment by manticorp** [comment]
Awesome :) Care to close this issue?

I think it will be difficult to include screenshots because their appearance is determined by themes, and by other settings (see #2746).

I guess some screenshots of the default theme couldn't hurt, just bear in mind [the navigation options can change this as well](https://typedoc.org/options/output/#navigation).
