### ISSUE TITLE
typedoc fails on github action

### ISSUE THREAD

**Issue by wrnrlr** [TypeStrong/typedoc#2758]
For some reason typedoc keeps failing when I run it in a github action, while it works on my local enviroment.

This is the action failing: https://github.com/wrnrlr/prelude/actions/runs/11505262647/job/32026581306

I don't know how to reproduce the error on my machine.

**Comment by Gerrit0** [comment]
I blame deno. TypeDoc *does not* support runtimes other than Node. It looks like there are no lib files being included, which could happen due to not having node_modules or something... I don't use deno, so am not sure what the package system actually looks like there.

**Comment by wrnrlr** [comment]
It is probably a combination of Github Actions, Deno and Typedoc. Deno + Typedoc work ok on my local machine, although it is a bit slow and hard to organise the documentation of complex types.

**Comment by Gerrit0** [comment]
I don't have time to investigate issues which are definitely external to TypeDoc and especially ones that cannot be reproduced locally.

TypeDoc works just fine with a simple node based setup: https://github.com/Gerrit0/typedoc-packages-example/actions/runs/11632367251/job/32395312243
