### ISSUE TITLE
Hide a section

### ISSUE THREAD

**Issue by HLuizFilipe** [TypeStrong/typedoc#2762]
I have a very specific use case that I want to generate the link/docs for `Type Aliases`, but I want to hide from the navigation.

For example, I don't want to see `Type Aliases` on navigation and neither on `index`, but I want to be able to see its documentation its used referenced by a another symbol (aka interface for example).

Is there a way to do it via theme or a plugin, or even better, via `typedoc.json` ?

<img width="951" alt="image" src="https://github.com/user-attachments/assets/06042bc6-c45f-429e-9f50-6d9054640bba">

Thank you

**Comment by Gerrit0** [comment]
This can be done with a plugin. For your configuration, this should do the job:

```js
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(
        td.Converter.EVENT_RESOLVE_END,
        (context) => {
            for (const id in context.project.reflections) {
                const refl = context.project.reflections[id];
                removeTypeAliasGroup(refl);
            }
            removeTypeAliasGroup(context.project);
        },
        -300,
    );
}

/** @param {td.Reflection} refl */
function removeTypeAliasGroup(refl) {
    if (refl.isDeclaration() || refl.isProject()) {
        const aliases = refl.groups?.findIndex((g) => g.title === "Type Aliases");
        if (typeof aliases === "number" && aliases !== -1) {
            refl.groups.splice(aliases, 1);
        }
    }
}
```

**Comment by HLuizFilipe** [comment]
@Gerrit0 - Thank you so much for your help. 

I guess it should works fine if I do the following, right?

```ts
const elementsToHide = ["Type Aliases"]
const aliases = refl.groups?.findIndex((g) => elementsToHide.includes(g.title)); 
...
```

Anyway, I'm about to test that.

**Comment by Gerrit0** [comment]
Yeah, that ought to work. In a published plugin you might want to use `application.i18n` to get the translated string rather than including it directly.
