### ISSUE TITLE
Overloaded class properties should be printed as separate items.

### ISSUE THREAD

**Issue by Huxpro** [TypeStrong/typedoc#2767]
## Search terms

Overloaded class properties

## Expected Behavior

Overloaded class properties should be printed as separate items.
See the source code in the reproducible steps section below.

## Actual Behavior

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/89c029e1-50c0-44d4-b0b9-67f5a6b159ad">

## Steps to reproduce the bug

The source code for the above generated outputs are:

```ts
export interface Foo { 
  getJSModule<Module = unknown>(name: string): Module;
  getJSModule(name: "GlobalEventEmitter"): GlobalEventEmitter;
}
```

## Environment

-   Typedoc version: 0.26.11
-   TypeScript version:  5.0.4
-   Node.js version: 18
-   OS: macOS Sequoia 

I'm using <https://github.com/typedoc2md/typedoc-plugin-markdown> as well but it treated other overriding reflection kinds well so I don't feel like it's the problem of the plugin.

**Comment by Gerrit0** [comment]
How a member is rendered this is completely decided by your theme. TypeDoc's default theme renders this as:

![image](https://github.com/user-attachments/assets/a0eaf2b0-4d75-4370-afb7-fc1b17be35eb)

**Comment by Huxpro** [comment]
@Gerrit0 thanks for replying! I'll redirect this issue to typedoc-plugin-markdown then.
