### ISSUE TITLE
Bugs related to individual tag class names

### ISSUE THREAD

**Issue by XeroAlpha** [TypeStrong/typedoc#2771]
#2724 introduces two bugs about class names.

## Example
```typescript
/**
 * @example warning
 * 
 */
```

## Bugs

1. spaces in name variable

The example renders as:

```html
<div class="tsd-tag-Example: warning">

</div>
```

This results in the element having two classes: `tsd-tag-Example:` and `warning`, which makes this element looks weird.

2. i18n string

When `lang` is set to a different language, such as "zh-CN", the example renders as:

```html
<div class="tsd-tag-示例: warning">

</div>
```

Using i18n strings within class names is not advisable, as it can lead to inconsistencies and confusion.

## Solution

```diff
- <div class={`tsd-tag-${name}`}>
+ <div class={`tsd-tag-${item.tag} tsd-tag-${item.tag}-${item.name ?? ''}`}>
```

**Comment by Gerrit0** [comment]
I never intended for this to include anything but the tag name in the first place, it should have just been `tsd-tag-example`, PR welcome!
