### ISSUE TITLE
Duplication of the description of the `JSONOutput.DeclarationReflection.type` property

### ISSUE THREAD

**Issue by vanyauhalin** [TypeStrong/typedoc#2773]
Hi. I am not sure whether it is a bug within TypeDoc or TypeScript (or even VSCode). Please ignore the red underlines on the screenshot, as they are not relevant to this issue (I just forgot to remove them).

## Actual Behavior

<img width="930" alt="Screenshot 2024-11-13 at 11 44 11" src="https://github.com/user-attachments/assets/820a9806-16f2-4508-aaf5-cbe82808e7a8">

## Steps to reproduce the bug

```ts
import {type JSONOutput} from "typedoc"
const o: JSONOutput.DeclarationReflection = {}
o.type?.type
```

## Environment

-   Typedoc version: 0.26.11
-   TypeScript version: 5.4.5
-   Node.js version: 21.7.3
-   VSCode version: 1.95.2

**Comment by Gerrit0** [comment]
This isn't controlled by TypeDoc, but by TypeScript's language service. It looks like they have a bug where comment locations aren't deduplicated before rendering.
