### ISSUE TITLE
How to document a type?

### ISSUE THREAD

**Issue by vekexasia** [TypeStrong/typedoc#278]
I've a type used in a class

```
type MyType {
	haha: number,
	optional?: string
}
class MyClass{
	constructor(private config: MyType) {
	}
}
```

How to document  `MyType` to explain what `haha` and `optional` are used for?

**Comment by aciccarello** [comment]
I would use and interface for MyType and put JSDoc comments on the properties. Also, have you tried an `@param` jsdoc comment on the constructor?

```TypeScript
/** Description of MyType interface */
interface MyType {
    /** This property is ... */
    haha: number,
    /** Optional property useful for ... */
    optional?: string
}

/**
 * Description of what MyClass is
 */
class MyClass{
    /**
     * @param config Docs on config property.It is different than the interface docs
     */
    constructor(private config: MyType) {
    }
}

**Comment by vekexasia** [comment]
Thanks @aciccarello ... Would you please explain me what's the difference between a type and an interface?

**Comment by aciccarello** [comment]
I believe types were introduced later for some specific use cases. This SO questions has a good answer.

http://stackoverflow.com/q/37233735/4252741

**Comment by vekexasia** [comment]
Thank you :) @aciccarello

**Comment by giannif** [comment]
Anyone know if you can document a type like the original question asks? I have lots of types, and I'm interested in documenting them

**Comment by maksnester** [comment]
That still doesn't really have an answer. So it should be an issue because there are no docs for type properties.
It's possible to document an interface, but inline docs for properties won't work for types. The only option, for now, is to duplicate it with jsdoc like.

```ts
/**
 * @property foo Some docs.
 */
type MyFooType = {
  /** that comment is ignored */
  foo:? string;
}
```

**Comment by crhistianramirez** [comment]
@maksnester  is this still working for you? I'm trying your workaround and the name is being excluded. 

<img width="302" alt="image" src="https://user-images.githubusercontent.com/16483662/228352281-5af2e0ec-ca2d-4bb9-b2ad-b8ff20e93b20.png">

<img width="224" alt="image" src="https://user-images.githubusercontent.com/16483662/228352450-87a6438e-19be-4c98-a9f1-bf6169275f08.png">

**Comment by acao** [comment]
the vscode typescript extension honors this approach

```ts
export type HoverOptions = {
  /**
   * Provide a custom parser for the document
   * @default {JSON.parse}
   */
  parser?: (text: string) => any;
};
```

![Screenshot from 2023-07-20 12-34-03](https://github.com/TypeStrong/typedoc/assets/1368727/cb16e090-450c-4334-9043-70cbcebbbcca)

however typedoc no longer does (it used to iirc?)

![image](https://github.com/TypeStrong/typedoc/assets/1368727/deea3879-52d1-4fef-a5b0-938c95a516fa)
