### ISSUE TITLE
Support root projectDocuments in monorepos

### ISSUE THREAD

**Issue by johnameyer** [TypeStrong/typedoc#2780]
## Search Terms

projectDocuments root packages

## Problem

Today if one has a monorepo using entryPointStrategy packages, any projectDocuments linked there will not actually be included anywhere in the output documentation. Having root documents can give users a fast place to start and provide overall direction about how to use a set of packages rather than needing to have an overly long README or needing to tuck documentation into specific packages.

## Suggested Solution

Include projectDocuments in the root of the project hierarchy alongside index.html and other packages either directly or in a folder of their own.

**Comment by Gerrit0** [comment]
Incidentally, I actually already added support for this. In 0.27 TypeDoc will process project documents declared in the root config file and place them alongside the packages

Here's an example of what that looks like in the typedoc-packages-example repo, where the readme was disabled and then added as a project document.

![image](https://github.com/user-attachments/assets/95bcc843-664b-4cda-b05a-10635f86c6d1)

**Comment by johnameyer** [comment]
Fabulous, must've missed this in the beta notes!

Thanks for all your work on typedoc! 😄
