### ISSUE TITLE
Support TypeScript 5.7

### ISSUE THREAD

**Issue by chadwickellis** [TypeStrong/typedoc#2783]
## Search Terms

TypeScript 5.7

## Problem

TypeDoc currently does not support TypeScript 5.7. This causes issues when attempting to document projects that rely on TypeScript 5.7-specific features or syntax. It prevents proper generation of documentation and hinders developers using the latest TypeScript version.

## Suggested Solution

Add compatibility for TypeScript 5.7 in TypeDoc. Ensure that all new features and syntax introduced in TypeScript 5.7 are properly supported, and update the internal TypeScript peer dependency accordingly.

**Comment by Gerrit0** [comment]
#2763 - 0.27 supports TS 5.7, and is releasing tonight/tomorrow depending on how long it takes me to get through updating the remaining docs.
