### ISSUE TITLE
No file type validation for external documents? (Including mdx files)

### ISSUE THREAD

**Issue by phoneticallySAARTHaK** [TypeStrong/typedoc#2784]
## Search terms

external document file validation, markdown, mdx

## Expected Behavior

The local file (extension) being loaded should be constrained, unless there are plans to include arbitrary files. 

## Actual Behavior

No validation of file extension: https://github.com/TypeStrong/typedoc/blob/beta/src/lib/converter/converter.ts#L609

It will resolve files with any extension, and try to parse it as markdown

**Comment by phoneticallySAARTHaK** [comment]
Also, irrelevant to the issue, is it possible to override the parsed markdown?

Currently the `PARSE` event is triggered **after** the md is parsed, causing double computation over the text.

Should I make a separate issue for this?

**Comment by Gerrit0** [comment]
This is somewhat intentional -- While TypeDoc will always treat the input text as markdown, there are a *very large* number of extensions which I've seen markdown written in, from the common `.md`, `.markdown`, to the more uncommon `.grammarkdown`, and even arbitrary ones like `.def`. Limiting what extensions people can use seems like it would be a problem to me.

I guess an option could be introduced as an enhancement to list the extensions we expect to see, but is that actually something likely to be a problem in practice? Checking if the loaded file looks like binary data isn't an unreasonable thing to do.

---

Parsing occurs *during* the `PARSE` event. You can pass a priority level when listening to the event to attach an event listener which is called before (or after) TypeDoc passes it to markdown-it. There isn't currently any way to prevent the call to markdown-it.

**Comment by phoneticallySAARTHaK** [comment]
I see, you're right about the file extensions, it's better this way.

I wanted to make a plugin to include `mdx` files as well, which are also parsed as markdown. Could you suggest the best approach for it?

I can't use the approach the used by the closest plugin [include example](https://github.com/ferdodo/typedoc-plugin-include-example/blob/master/src/include-example.ts). Can I override the entire MarkedPlugin (overkill) or add new section on the relevant page itself?

**Comment by Gerrit0** [comment]
The approach will likely change depending on what interface you want to expose to users....

You could expose a `@mdx` tag to specify a file, and use a [comment.afterTags](https://typedoc.org/api/interfaces/RendererHooks.html#commentaftertags) hook to check for that tag, and add a block to the page after a comment... the simplest implementation would look something like:

```ts
// CC0
// @ts-check
import { resolve, dirname } from "path";
import td from "typedoc";

const MDX_TAG = "@mdx";

/** @param {td.Application} app */
export function load(app) {
    // Automatically add `@mdx` as a modifier tag so that the user of this
    // plugin doesn't have to. Do this with a low order so that if the user
    // sets the option anywhere, their choice will overwrite the default.
    app.options.addReader({
        name: "mdx-plugin",
        order: -1,
        supportsPackages: false,
        read(options) {
            options.setValue("blockTags", [...options.getValue("blockTags"), "@mdx"]);
        },
    });

    // or comment.beforeTags
    app.renderer.hooks.on("comment.afterTags", (context, comment) => {
        const mdxTag = comment.getTag(MDX_TAG);

        if (!mdxTag) return td.JSX.createElement(td.JSX.Fragment, null);

        // Tell TypeDoc not to render this tag
        mdxTag.skipRendering = true;

        const inputPath = td.Comment.combineDisplayParts(mdxTag.content);
        const resolvedPath = resolve(dirname(comment.sourcePath ?? "./a"), inputPath);

        // Compile content of resolvedPath...
        const compiled = `<div style="background: red">MDX Tag content for ${resolvedPath}</div>`;

        return td.JSX.createElement(td.JSX.Raw, { html: compiled });
    });
}
```

Though keep in mind that `comment.sourcePath` doesn't exist when rendering for packages mode. To support packages mode, you'd have to resolve this path earlier and either replace it within the comment, or store it on the reflection and provide serialize/deserialize methods to ensure TypeDoc preserves it. This would look something like:

```js
// CC0
// @ts-check
import { resolve, dirname, relative } from "path";
import td from "typedoc";

const MDX_TAG = "@mdx";

/** @param {td.Application} app */
export function load(app) {
    // Automatically add `@mdx` as a modifier tag so that the user of this
    // plugin doesn't have to. Do this with a low order so that if the user
    // sets the option anywhere, their choice will overwrite the default.
    app.options.addReader({
        name: "mdx-plugin",
        order: -1,
        supportsPackages: false,
        read(options) {
            options.setValue("blockTags", [...options.getValue("blockTags"), "@mdx"]);
        },
    });

    // During reflection resolution, save the resolved content path on the reflection.
    app.converter.on(td.Converter.EVENT_RESOLVE, (_context, refl) => {
        const comment = refl.comment;
        if (!comment?.sourcePath) return;

        const tag = comment.getTag(MDX_TAG);
        if (!tag) return;

        comment.removeTags(MDX_TAG);

        const inputPath = td.Comment.combineDisplayParts(tag.content);
        refl.mdxContentPath = resolve(dirname(comment.sourcePath), inputPath);
    });

    // When serializing to JSON (either for JSON output, or for packages mode)
    // save the resolved path.
    app.serializer.addSerializer({
        priority: 0,
        supports(item) {
            return item instanceof td.Reflection;
        },
        /** @param {td.Reflection} item */
        toObject(item, obj, ser) {
            // Save the path relative to the projectRoot to avoid including user paths
            // in the serialized JSON.
            if (item.mdxContentPath) {
                obj.mdxContentPath = relative(ser.projectRoot, item.mdxContentPath);
            }
            return obj;
        },
    });

    // When deserializing from JSON restore the resolved path
    app.deserializer.addDeserializer({
        priority: 0,
        supports(model, _obj) {
            return model instanceof td.Reflection;
        },
        fromObject(model, obj) {
            if (obj.mdxContentPath) {
                model.mdxContentPath = resolve(app.deserializer.projectRoot, obj.mdxContentPath);
            }
        },
    });

    // When rendering a comment for a reflection, check for a mdx path that should be rendered too
    // This could also be added to some other render hook if convenient as we no longer need the comment
    app.renderer.hooks.on("comment.afterTags", (_context, _comment, refl) => {
        const mdxPath = refl.mdxContentPath;

        if (!mdxPath) return td.JSX.createElement(td.JSX.Fragment, null);

        // Compile content of resolvedPath...
        const compiled = `<div style="background: red">MDX Tag content for ${mdxPath}</div>`;

        return td.JSX.createElement(td.JSX.Raw, { html: compiled });
    });
}
```

**Comment by phoneticallySAARTHaK** [comment]
Thanks a lot for this implementation!

Is there any way I can just override the parsing as of now? (since that would be much simpler, if easily possible)
