### ISSUE TITLE
How do I rename a module with the `@module` tag without removing the module from its folder in the navigation?

### ISSUE THREAD

**Issue by NkemdiAnyiam** [TypeStrong/typedoc#2785]
## Search terms

navigation, folders, module tag

## Question
I am working on organizing my files, folders, and TypeDoc output, and I started playing with the `@module` tag. However, when I tried using it (to rename one of my .ts files), the resulting TypeDoc output removed the file from its folder in the left-hand navigation. How do I prevent this? The before and after are shown below:

**BEFORE**
![image](https://github.com/user-attachments/assets/49f2d06f-adc2-4f19-8093-4b770cd9da28)

**`@MODULE` COMMENT**
```ts
/**
 * This is the doc comment for file1.ts
 *
 * Specify this is a module comment and rename it to my-module:
 * @module customEffectGeneration
 */
```

**AFTER**
![image](https://github.com/user-attachments/assets/c421b4ae-9849-49ac-922f-8976279eee37)

**Comment by Gerrit0** [comment]
Those folders are inferred from the names of the module, where typedoc splits the name on `/`, so `@module 2_animationEffects/customEffectGeneration` will likely work.
