### ISSUE TITLE
{@include} and {@includeCode} not working

### ISSUE THREAD

**Issue by jklosinski** [TypeStrong/typedoc#2786]
## Search terms

include, includeCode

## Expected Behavior

I am trying to use the `@include` and `@includeCode` tags defined [here](https://typedoc.org/documents/Tags.__include_.html).
But running typedoc gives warning `[warning] Encountered an unknown block tag @includeCode`.

I cannot find any information about these tags online anywhere, and nothing mentioned in changelogs.  Are they old tags that need to be removed from the documentation?

## Environment

-   Typedoc version: ^0.26.11
-   TypeScript version: 5.6
-   Node.js version: 20.12.2
-   OS: Windows 10

**Comment by Gerrit0** [comment]
No, those are new tags introduced in 0.27, apparently I somehow forgot to add them to the changelog.

**Comment by jklosinski** [comment]
@Gerrit0 Thanks for the quick reply.  I updated to 0.27 and tried them out and `@include` is working as intended.  `@includeCode`, however, doesn't seem to be working, at least not how it's shown on the docs page.

Here are the results from my testing.

```
/**
   * ... snip ...
   * @param options The options to use when cloning the record
   * @returns The results of the clone operation or null if the user declined
   * 
   * #includeMD works
   * {@include ./documents/includeTest.md} 
   * 
   * 
   * #include1 works but code shows up as text
   * {@include ./examples/quickStart.ts}
   * 
   * #includeCode1 close...renders as code but does not have "Example" header
   * {@includeCode ./examples/quickStart.ts}
   * 
   * #include2 code block renders tag literal and filename but does not pull in file contents  
   * ```typescript
   * {@include ./examples/quickStart.ts}
   * ```
   * #includeCode2 code block renders tag literal and filename but does not pull in file contents  
   * ```typescript
   * {@includeCode ./examples/quickStart.ts}
   * ```
   * 
   * 
   * 
   * @example
   * #include1Example code block renders tag literal and filename but does not pull in file contents  
   * {@include ./examples/quickStart.ts}
   * 
   * @example
   * #includeCode1Example code block renders tag literal and filename but does not pull in file contents  
   * {@includeCode ./examples/quickStart.ts}
   * 
   * 
   * 
   * @example
   * #include2Example code block renders but does not pull in file contents (just renders the tag as if it was code)
   * ```typescript
   * {@include ./examples/quickStart.ts}
   * ```
   * @example
   * #includeCode2Example code block renders but does not pull in file contents (just renders the tag as if it was code)
   * ```typescript
   * {@includeCode ./examples/quickStart.ts}
   * ```
   * 
   */
  export function promptToClone(
    options: Clone.Options
  ): Promise<Clone.OperationCompleteContext | null>;
```
Are the `@includeCode` variations above working as intended? 

Thanks for your time.

**Comment by Gerrit0** [comment]
Yes, those are all working as intended.

> include1 works but code shows up as text

As intended, `@include` means "copy paste the file contents here"

>  includeCode1 close...renders as code but does not have "Example" header

As intended, `@includeCode` is can be used for non-examples too. (For example, TypeDoc's site uses it to include the --help output, which isn't an example) https://typedoc.org/documents/Overview.html#command-line-interface

> include2 code block renders tag literal and filename but does not pull in file contents
> includeCode2 code block renders tag literal and filename but does not pull in file contents  

As intended, tags are not parsed within fenced code blocks.

> include1Example code block renders tag literal and filename but does not pull in file contents
> includeCode1Example code block renders tag literal and filename but does not pull in file contents
> include2Example code block renders but does not pull in file contents (just renders the tag as if it was code)
> includeCode2Example code block renders but does not pull in file contents (just renders the tag as if it was code)

As intended. TypeDoc treats `@example` / `@default` tag contents as code unless they include a code block. This is for compatibility with JSDoc, which unfortunately decided on this (IMO bad) behavior. TypeDoc's [`--jsdocCompatibility` option](https://typedoc.org/documents/Options.Comments.html#jsdoccompatibility) can be used to disable this behavior, leaving you with what you wanted.

**Comment by Gerrit0** [comment]
I just updated the docs to be more clear about the example tag, thanks for the report!
