### ISSUE TITLE
Description from @categoryDescription missing in docs since 0.27.0

### ISSUE THREAD

**Issue by blutorange** [TypeStrong/typedoc#2787]
## Search terms

category description missing

## Description

I was updating [typedoc-plugin-merge-modules](https://github.com/krisztianb/typedoc-plugin-merge-modules) (krisztianb/typedoc-plugin-merge-modules#21) to use ESM so that it can be used with TypeDoc 0.27 when I noticed some tests of that plugin were failing after the update. After taking a look and trying it without the plugin, TypeDoc's behavior regarding [@categoryDescription](https://typedoc.org/documents/Tags._category.html) seems to have that changed -- in that it does not seem to output the description anymore.

I found one note in the changelog regarding that tag, but it sounds like it should affect only plugin authors, but not people using the CLI?

```text
API: @group, @category, @groupDescription and @categoryDescription will no longer be removed from the reflections they are present on. They are skipped during rendering with the notRenderedTags option.
```

## Steps to reproduce the bug

Take the example from the documentation for [@categoryDescription](https://typedoc.org/documents/Tags._category.html):

```ts
// cat.ts
/**
 * @categoryDescription Advanced Use
 * These functions are available for...
 * @module
 */

/**
 * @category General Use
 */
export function runProcess(): void {}

/**
 * @category Advanced Use
 */
export function unref(): void {}

/**
 * @category Advanced Use
 */
export function ref(): void{}
```

And run `npx typedoc cat.ts --out docs`

## Expected Behavior

TypeDoc should output the category description in the docs.

## Actual Behavior

With TypeDoc 0.26.11:

![image](https://github.com/user-attachments/assets/6ffc27c4-4360-4238-8981-f684a3027f5f)

With TypeDoc 0.27.0:

![image](https://github.com/user-attachments/assets/06859df1-0843-498f-87f6-400537573377)

Also, even `grep -r docs -e 'These functions are available'` doesn't find anything, so it's definitely nowhere in the generated docs.

## Environment

-   Typedoc version: 0.26.11 / 0.27.0
-   TypeScript version: 5.6.3

**Comment by Gerrit0** [comment]
This is because modules are rendered in a custom way now, and I forgot to handle this and `@groupDescription` within them... easy fix.

**Comment by Gerrit0** [comment]
I forgot to include the issue number in the commit, fixed with c2c12894e07b6addaa282a90926115aa4dedc2bd

**Comment by blutorange** [comment]
Thanks, just to let you know, the tests for typedoc-plugin-merge-modules are now passing with the fix for this issue.

**Comment by thobson** [comment]
I'm still seeing this behaviour in 0.28.16

**Comment by Gerrit0** [comment]
Please open a new issue with a reproduction. This specific issue has been fixed.
