### ISSUE TITLE
[Question] Roadmap for TypeDoc 1.X.X release

### ISSUE THREAD

**Issue by PierBJX** [TypeStrong/typedoc#2788]
## Search terms

Stable release

## Question
Hi TypeDoc team,

Thank you for your amazing work on TypeDoc! I noticed that the project is still in the 0.X.Y version, which implies it is in beta. This raises some concerns for developers relying on TypeDoc in production projects, especially because semantic versioning rules prevent updates to minor versions when using the `^0.X.Y` notation (`npm update` only updates patch versions for version starting with `0.X.Y`).

Is there a roadmap or any planned timeline for a stable 1.X.X release?

Thanks in advance for your response!

**Comment by Gerrit0** [comment]
#2571
