### ISSUE TITLE
Module-less Category Descriptions / Class Summaries

### ISSUE THREAD

**Issue by johnameyer** [TypeStrong/typedoc#2793]
## Search Terms

`@categoryDescription` `@summary`

## Problem

When first coming to a documentation, users might want to get a "lay of the land" and understand what classes of things a package contains.

Many packages may organize their files within a package into directories while only exposing a single `index.js`. While users can manually group these files together using `@category` on the individual members, no summary / module page will be created and so there is no place to see the top line summary of that `categoryDescription` or `@summary` of the classes, which makes it hard to get that "lay of the land" perspective.

Check out [the core package of my docs](https://johnmeyer.dev/cards-ts) for examples of what I am trying to achieve with the Controllers and Game Builder categories.

## Suggested Solution

There's a few different ways to solve this generally as I see:

* Show `@categorySummary` / `@summary` / `useFirstParagraphOfCommentAsSummary` on the package README / index page
* Generate index / module pages for categories
* Allow for categorizing files with a single "module" `@category` in internal (i.e. non-entrypoint) index.js
* Allow for defining `@categoryDescription` in a non-module place (index.js?)
* Allow for specifying a README for a category like the package root

**Comment by Gerrit0** [comment]
TypeDoc sites always have at least one module page, even if you have a readme page, it can be reached by going to modules.html, which is linked in the navigation sidebar as the package name.

If you want that page to be the main page of the docs, you can do that by setting `--readme none`, optionally using the [`@include`](https://typedoc.org/documents/Tags.__include_.html) tag to reference the readme within the module comment for that file.

**Comment by Gerrit0** [comment]
I'm not sure I understand...

> Show `@categorySummary` / `@summary` / `useFirstParagraphOfCommentAsSummary` on the package README / index page

This is how TypeDoc works today for the package's module page:

![image](https://github.com/user-attachments/assets/85874702-5d2e-4e11-961f-11ca5dc2af81)

<details>

```diff
diff --git a/packages/core/src/index.ts b/packages/core/src/index.ts
index 6259d78..1b58960 100644
--- a/packages/core/src/index.ts
+++ b/packages/core/src/index.ts
@@ -1,3 +1,8 @@
+/**
+ * @module
+ * @categoryDescription Controller
+ * A controller is a class...
+ */
 export * from './browser-index.js';
 
 export { InquirerPresenter } from './intermediary/inquirer-presenter.js';
```

</details>

> Generate index / module pages for categories
> Allow for specifying a README for a category like the package root

Doing this raises a lot of questions... can you `@link` to those pages? What does the current module page look like then, does it contain duplicate information or links to the category pages, basically making it useless? What about groups, do they get their own pages? What if `categorizeByGroup` is true and the site includes both categories and groups, how does linking work then? Do you get a page per group and per category, or per group+category? Allowing this would require a major architecture change on the order of adding support for `@document` as TypeDoc expects pages to be generated according to reflection children, which this breaks entirely... not saying it can't happen, just that it isn't an easy change...

> Allow for categorizing files with a single "module" `@category` in internal (i.e. non-entrypoint) index.js

This goes contrary to TypeDoc's philosophy of following entrypoint exports to determine documentation, and definitely won't be implemented.

> Allow for defining `@categoryDescription` in a non-module place (index.js?)

I don't understand what this means... category descriptions are always owned by the parent of the categorized members so that there is an obvious single place of definition. Maybe I'm missing some reason here...?

**Comment by johnameyer** [comment]
> Show @categorySummary / @summary / useFirstParagraphOfCommentAsSummary on the package README / index page

Ah don't think I would've figured out that I can add all of my `@categorySummary` to the entrypoint file - nifty and thanks!

Based on the [documentation](https://typedoc.org/documents/Tags._summary.html) for `@summary`, I am a bit surprised the member summaries are not appearing on the module page though.

> Generate index / module pages for categories
Allow for specifying a README for a category like the package root

I don't think `@link` supports linking to files from what I've read in the docs and tried, but I just tried linking with a standard markdown link and that does seem to work. `{@include}` / `{@includeCode}` doesn't seem to work in category descriptions either.

I would think the module page would be more of an overview page and the group page would allow for more details / member summaries. If all the content would be included on the main module page then it could easily become long with a lot of included summaries or markdown documents...

You raise a lot of good questions otherwise... I think my comprehension of the differences between categories and groups isn't particularly strong enough so I'd rely on your judgement.

Would you have any other recommendations?

> Allow for categorizing files with a single "module" @category in internal (i.e. non-entrypoint) index.js

For my use case then, would it make more sense to point typedoc directly to the various internal `index.ts` packages? Manually specifying categories is a bit tedious and easy enough to forget. Or is there some other mechanism possible (e.g categorizing based on folder structure)?

> Allow for defining @categoryDescription in a non-module place (index.js?)

I think you helped clear this up for me with your response to the first point.

**Comment by Gerrit0** [comment]
> Based on the [documentation](https://typedoc.org/documents/Tags._summary.html) for `@summary`, I am a bit surprised the member summaries are not appearing on the module page though.

Not sure what you're seeing there, seems fine for me.

![image](https://github.com/user-attachments/assets/4d38ef73-9480-4c6b-b823-e140fd85fa20)

```diff
diff --git a/packages/core/src/controllers/controller.ts b/packages/core/src/controllers/controller.ts
index aa2a510..cf787e2 100644
--- a/packages/core/src/controllers/controller.ts
+++ b/packages/core/src/controllers/controller.ts
@@ -6,6 +6,7 @@ import { Serializable } from '../intermediary/serializable.js';
  * @typeParam WrappedControllers the controllers that this controller depends on
  * @typeParam HandlerData the data that this controller provides to handlers
  * @category Controller
+ * @summary Summary for AbstractController...
  */
 export abstract class AbstractController<State extends Serializable, WrappedControllers extends IndexedControllers, HandlerData extends Serializable = State> {
     constructor(protected state: State, protected controllers: WrappedControllers) {
```

> I don't think `@link` supports linking to files from what I've read in the docs and tried, but I just tried linking with a standard markdown link and that does seem to work

`@link` does, but it doesn't support file paths, [declaration references](https://typedoc.org/documents/Declaration_References.html) have to be used instead. Linking is probably one of the hardest pieces of typedoc to explain to people.  I'd recommend just using a markdown link for document links in general as they can also be resolved by VSCode.

> `{@include}` / `{@includeCode}` doesn't seem to work in category descriptions either.

Shoot, this specifically doesn't work on comments for modules with a single entry point. I created #2800 to track.

> I would think the module page would be more of an overview page and the group page would allow for more details / member summaries. If all the content would be included on the main module page then it could easily become long with a lot of included summaries or markdown documents...

Here's the crux of the issue -- for many packages, splitting that out into separate pages will result in objectively worse documentation as the pages are now less searchable! I'm very tempted to push this to a custom theme... What's best for your project is overkill for simpler ones....

> For my use case then, would it make more sense to point typedoc directly to the various internal `index.ts` packages? Manually specifying categories is a bit tedious and easy enough to forget. Or is there some other mechanism possible (e.g categorizing based on folder structure)?

This is probably what I'd lean towards doing in this case... A plugin to automatically add `@category` tags based on the directory would also work.

```js
// TypeDoc 0.27, CC0
import { Application, Converter, Comment, CommentTag } from "typedoc";
import { join, relative } from "path";

/** @type {[string, string][]} */
const dirsToCategory = [["core/src/controllers", "Controller"]];

const packagesDir = join(process.cwd(), "packages");

/** @param {Application} app */
export function load(app) {
  app.converter.on(Converter.EVENT_CREATE_DECLARATION, (context, decl) => {
    const symbol = context.project.getSymbolFromReflection(decl);
    if (!symbol) return;

    const path = symbol.declarations?.[0].getSourceFile().fileName;
    if (!path) return;

    const relativePath = relative(packagesDir, path);
    const category = dirsToCategory.find(([dir]) =>
      relativePath.startsWith(dir)
    );

    if (category) {
      decl.comment ||= new Comment();
      if (!decl.comment.getTag("@category")) {
        decl.comment.blockTags.push(
          new CommentTag("@category", [{ kind: "text", text: category[1] }])
        );
      }
    }
  });
}
```

**Comment by johnameyer** [comment]
> I am a bit surprised the member summaries are not appearing on the module page though.

I think there is some weirdness with `useFirstParagraphOfCommentAsSummary` where it needs to be in the root configuration and not in `packageOptions` / the config of a single package. Was running into issues with `@summary` but I'm unable to replicate now... was able to use `@summary` successfully.

> I'm very tempted to push this to a custom theme... 

Fair judgement! Reading over the documentation it does look like the theme should allow for this so might take a stab when I get a chance...

> A plugin to automatically add @category tags based on the directory would also work.

Nifty and short! Let me try this out as well...

**Comment by Gerrit0** [comment]
> I think there is some weirdness with `useFirstParagraphOfCommentAsSummary` where it needs to be in the root configuration and not in `packageOptions` / the config of a single package

Yes, this option is used during rendering, not during conversion, so needs to be set in the options used when rendering... I should probably go through the site and label each option with when it is used, as right now it just requires knowledge of typedoc's implementation...

> Fair judgement! Reading over the documentation it does look like the theme should allow for this so might take a stab when I get a chance...

It won't be as simple as it ought to be unfortunately. Hopefully easier in 0.28 once the router is more easily customizable...

**Comment by Gerrit0** [comment]
After thinking about it for a while, I'm going to push this functionality to a custom theme. My recommendation for those projects which need more structured organization is to split their code into modules -- `@group` / `@category` isn't intended as a replacement for modules.
