### ISSUE TITLE
Low contrast in light mode

### ISSUE THREAD

**Issue by personalizedrefrigerator** [TypeStrong/typedoc#2795]
## Search terms

Contrast, Accessibility

## Expected Behavior

Method names and get signatures rendered by TypeDoc should have sufficient contrast in light mode.

## Actual Behavior

At present, some content is difficult to read in light mode due to low contrast:

![screenshot: FireFox contrast checker shows 2.72:1 contrast](https://github.com/user-attachments/assets/6e2f921c-c8a8-4eb9-9c9f-7e614d886c3d)

For example, properties with color `--light-color-ts-method` have contrast 2.72:1 with the background in the default theme.

## Steps to reproduce the bug

To reproduce:
1. Generate documentation for a project.
2. Switch to TypeDoc's light theme (if not already enabled).
3. Inspect the color contrast for a method name.

An [example repository that reproduces the issue can be found here](https://github.com/personalizedrefrigerator/bug-report/tree/typedoc/bug-contrast).

> [!NOTE]
>
> This issue may be related to [this commit](https://github.com/TypeStrong/typedoc/commit/8d3742bdef2494925b00ea349f294e7628db618d#diff-9a60ff1ad658a0c4dec6ea96847009b7f01b3e103107040b4b0705de525d737aL33).

## Environment

-   Typedoc version: 0.27.2
-   TypeScript version: 5.7.2
-   Node.js version: 22.11.0
-   OS: Fedora 41

**Comment by Gerrit0** [comment]
... well that's annoying, when looking at the PR with that commit I thought it was copying the colors rather than referencing everything, not changing colors.
