### ISSUE TITLE
[0.27]: Seems like Shiki languages have changed; `bash` & `console` no longer valid.

### ISSUE THREAD

**Issue by typhonrt** [TypeStrong/typedoc#2798]
It seems like `shiki` was updated for `0.27` and `bash` and `console` are no longer [supported languages](<https://shiki.style/languages#bundled-languages>).

While it seems like they are still listed in the [default configuration internally](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/defaults.ts#L66-L78) in Typedoc if copying the default array as seen in [Typedoc docs](https://typedoc.org/documents/Options.Output.html#highlightlanguages) and setting this to `highlightLanguages` option this will trigger an error in the [option validator](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/sources/typedoc.ts#L353-L371).

Ahh... I can see this being a consequence of your rebundling of shiki [@gerrit0/mini-shiki](https://github.com/Gerrit0/mini-shiki)

If `bash` and `console` are no longer valid; easy suggestion is to remove them from Typedoc docs and internal default.

## Environment

-   Typedoc version: `0.27.2`

**Comment by Gerrit0** [comment]
This shouldn't have changed, mini-shiki is meant to be a complete drop in replacement.

**Comment by typhonrt** [comment]
This is when uses the same exact default options IE:

```json
{
    "highlightLanguages": [
        "bash",
        "console",
        "css",
        "html",
        "javascript",
        "json",
        "jsonc",
        "json5",
        "tsx",
        "typescript"
    ]
}
```

With `bash` / `console`:
![image](https://github.com/user-attachments/assets/0ff74475-e067-4ef4-abee-13d153e4edcc)


Without `bash` & `console` docs generate fine:
![image](https://github.com/user-attachments/assets/c879641b-5007-47d3-a3d8-99ef569b4a59)

---

Despite the error docs generate, but seemingly falls back to the internal default. I just happen to be adding `svelte` to the languages. This does work sans `bash` & `console`.

**Comment by Gerrit0** [comment]
If you were using TypeDoc's CLI, it would have exited without generating docs due to the configuration error. Options aren't set if they fail validation.

I'm not sure why I decided to only allow non-aliased languages when implementing this ages ago, I experimentally just allowed it and it all works as expected.... makes it an easy default.

**Comment by typhonrt** [comment]
Yeah this is programmatic usage / special case / complex docs project.
