### ISSUE TITLE
Certain modifier tags no longer included in json output since v0.25

### ISSUE THREAD

**Issue by ben-polinsky** [TypeStrong/typedoc#2802]
## Expected Behavior

`@alpha` tags (tested `@beta` and `@experimental` tags with the same result) used to document types should be available in the `modifierTags` array of the corresponding node in json output produced by TypeDoc. 

## Actual Behavior

Since version 0.25, the above behavior is no longer the case. 

## Steps to reproduce the bug

Consider the following:

```ts
/**
 * No issues here, correctly has `@alpha` in modifierTags
 * (behavior is the same with beta or experimental tags)
 * @alpha
 */
export type AlphaOk = number | string;

/**
 * Now, no `@alpha`
 * (behavior is the same with beta or experimental tags)
 * @alpha
 */
export type AlphaNoGo = (arg: number | string) => void;

```

Will produce the following output in versions <0.26:
[stackblitz link](https://stackblitz.com/edit/vitejs-vite-91rcpx?file=src%2Findex.ts) run `npm run docs`
```json
	"id": 2,
	"name": "AlphaNoGo",
	"variant": "declaration",
	"kind": 2097152,
	"flags": {},
	"comment": {
		"summary": [
			{
				"kind": "text",
				"text": "Now, no "
			},
			{
				"kind": "code",
				"text": "`@alpha`"
			},
			{
				"kind": "text",
				"text": "\n(behavior is the same with beta or experimental tags)"
			}
		],
		"modifierTags": [
			"@alpha"
		]
	},
```

But the following output in versions >=0.26
[stackblitz link](https://stackblitz.com/edit/vitejs-vite-lezl8v?file=src%2Findex.ts) run `npm run docs`
```json
   "id": 2,
  "name": "AlphaNoGo",
  "variant": "declaration",
  "kind": 2097152,
  "flags": {},
  "comment": {
  "summary": [
	  {
		  "kind": "text",
		  "text": "Now, no "
	  },
	  {
		  "kind": "code",
		  "text": "`@alpha`"
	  },
	  {
		  "kind": "text",
		  "text": "\n(behavior is the same with beta or experimental tags)"
	  }
  ]
  },
```

## Environment

-   Typedoc version: Tested failures with 0.26.0; 0.26.11; and 0.27.2
-   TypeScript version: various 5.x
-   Node.js version: 22; 20
-   OS: Mac; Ubuntu

**Comment by Gerrit0** [comment]
Those tags are all modifier tags, so shouldn't appear in the blockTags array. They appear in the under modifierTags property. https://typedoc.org/documents/Tags.html#modifier-tags

**Comment by ben-polinsky** [comment]
Apologies. But the tags are nowhere - they aren't in any `modifierTags` property as you can see from my example and reproduction.

**Comment by ben-polinsky** [comment]
The issue is with this [commit](https://github.com/TypeStrong/typedoc/commit/a060420dae017277ac9a36e2e96aba6afd33e7f9#diff-bf26d4bebc95d47c1a456e4f75adef90af7c5860f38327f789bf8c16dc4aa632R708) which adds "cascading" modifierTags. If I remove the default modifierTags and specify an empty array in config, then all is well.

I have a workaround, but this is a bug.

**Comment by Gerrit0** [comment]
Ah shoot, yes, this is a bug. Cascading tags shouldn't recurse into types, which is what's happening here.
