### ISSUE TITLE
Module-level summaries don't appear for all member kinds

### ISSUE THREAD

**Issue by pjeby** [TypeStrong/typedoc#2803]
## Search terms

`@summary`, `useFirstParagraphOfCommentAsSummary`

## Expected Behavior

As described in [the `@summary` docs](https://typedoc.org/documents/Tags._summary.html), when a function, type alias, or other module member has a `@summary`, or if `useFirstParagraphOfCommentAsSummary` is enabled, it should have a summary on the module page exporting that function.

## Actual Behavior

Summaries appear for classes and interfaces but not standard function declarations, even if an explicit `@summary` is given.  (They do appear for functions defined with `const fn = () => {}` however.)

## Steps to reproduce the bug

Entry point:

```ts
/**
 * Text A
 * @summary Text B
 */
export function test() {
}
```

Module page lists `test` function but neither `Text A` nor `Text B` appear below, whether  `useFirstParagraphOfCommentAsSummary` is used or not.

## Environment

-   Typedoc version: 0.27.3
-   TypeScript version: 5.2.2
-   Node.js version: 18.20.2
-   OS: Windows 10

**Comment by Gerrit0** [comment]
It's incredible how even after living with the special case nightmare that is functions for as long as I have, I still manage to consistently forget to handle it...
