### ISSUE TITLE
Rename "Type Aliases" to "Types"

### ISSUE THREAD

**Issue by pleek91** [TypeStrong/typedoc#2804]
## Search terms
"rename", "Type Aliases"

## Question
I'd like to rename "Type Aliases" to just "Types". Is that possible without using `@group` on all of my types to a custom group named "Types"? 

I did use `@group` to make some custom groups. But those items still have whatever their default group was in their url. For example a type grouped as "utilities" has the url `/api/type-aliases/myType` rather than `/api/utilities/myType`. Can I customize that as well?

**Comment by Gerrit0** [comment]
The locales option can be used for the first - see https://typedoc.org/documents/Options.Output.html#locales and https://github.com/TypeStrong/typedoc/blob/88b8f2bbf8206ab095938d7a97934a504e3a0965/src/lib/internationalization/locales/en.cts#L433

For the second, changing URLS requires a custom theme today. #2111 tracks supporting a custom output directory structure.

**Comment by pleek91** [comment]
@Gerrit0 thank you, I'll look into those
