### ISSUE TITLE
Nav: current location shown is incorrect when on ./index

### ISSUE THREAD

**Issue by bhj** [TypeStrong/typedoc#2805]
## Search terms

Navigation, index, module, current class

## Expected Behavior

`current` class either matches current location's nav item, or is not present

## Actual Behavior

When viewing `./index.html`, the `current` class is instead present on the entry for `./modules.html`

## Steps to reproduce the bug

Hey, thanks for all your work - I'm new to typedoc but it's immensely helpful. I have a pretty simple repo with a README and a single module. Essentially, in the screenshot below I am viewing the README (index) page, but the nav has the `current` class on the modules page instead.

<img width="318" alt="Screenshot 2024-12-08 at 11 59 28 AM" src="https://github.com/user-attachments/assets/2e185c26-1c66-430e-8363-396d47e5a7dd">

I think it would be better if the `current` class were not present in the nav in this case. Navigating to the modules page now shows different content, but the nav's current page indicator has not changed, which is confusing.

```
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": ["./src/index.ts"],
  "plugin": ["typedoc-plugin-merge-modules"],
  "defaultCategory": "General",
  "categoryOrder": ["General", "*"],
  "disableSources": true,
  "sort": ["kind", "source-order"],
  "visibilityFilters": {},
  "headings": {
      "readme": false,
      "document": true,
  },
}
```

I did try disabling `typedoc-plugin-merge-modules` (using `6.1.0`) without change.

## Environment

-   Typedoc version: 0.27.3
-   TypeScript version: 5.7.2

**Comment by Gerrit0** [comment]
I agree, easy fix!
