### ISSUE TITLE
Render links to`hostedBaseUrl` as internal links

### ISSUE THREAD

**Issue by aleksei-berezkin** [TypeStrong/typedoc#2809]
## Search Terms

external internal links hostedBaseUrl

## Problem

When generating a link to `hostedBaseUrl` (that is, to self), TypeDoc generates “external” links, that is, absolute links with `target="_blank"`, and with “external” icon.

Steps to reproduce:
* Check out test project https://github.com/aleksei-berezkin/typedoc-test-project
* run `npm run typedoc` to generate docs
* run `npm run serve`
* Open the link to `localhost` in the browser
* Check the “Test link” in README — it's rendered as an external link and opens in the new browser tab
* Check the “test link” in `TestInterface` — also rendered external

## Suggested Solution

Generate links pointing to `hostedBaseUrl` as “internal” links, i.e. relative (by default), without “external” icon, without `target="_blank"`.

**Comment by Gerrit0** [comment]
Seems like a reasonable thing to do
