### ISSUE TITLE
Cannot find name ... errors when using programmatically with declarations

### ISSUE THREAD

**Issue by felixfbecker** [TypeStrong/typedoc#281]
```
c:/Users/felix/git/Projekte/registerex/node_modules/typedoc/lib/converter/types/intrinsic.d.ts(5,105): error TS2305: Module 'ts' has no exported member 'IntrinsicType'.
c:/Users/felix/git/Projekte/registerex/node_modules/typedoc/lib/converter/types/intrinsic.d.ts(6,45): error TS2305: Module 'ts' has no exported member 'IntrinsicType'.
c:/Users/felix/git/Projekte/registerex/node_modules/typedoc/lib/converter/types/intrinsic.d.ts(7,44): error TS2305: Module 'ts' has no exported member 'IntrinsicType'.
c:/Users/felix/git/Projekte/registerex/node_modules/typedoc/lib/output/events.d.ts(20,15): error TS2304: Cannot find name 'HandlebarsTemplateDelegate'.
c:/Users/felix/git/Projekte/registerex/node_modules/typedoc/lib/output/utils/resources/templates.d.ts(4,20): error TS2304: Cannot find name 'HandlebarsTemplateDelegate'.
```
Seems like there are some dependencies typedoc can't live without - should the declarations be published on `typings/registry` instead?

**Comment by joaogarin** [comment]
Having simillar issue, where you able to fix this?

**Comment by felixfbecker** [comment]
Just ignoring it for now. @blakeembrey could you comment on this?

**Comment by joaogarin** [comment]
My issue is opened in https://github.com/TypeStrong/typedoc/issues/268

Also have been ignoring it as the app runs fine, but because I  am using with angular2 there is actually a big list of things I need to include, so its quite a list of warnings;P

**Comment by blakeembrey** [comment]
Most likely both are from global definitions. At least the Handlebars one is. It may be possible to switch to using Typings, or to `@types` when 2.0 is stable.

**Comment by felixfbecker** [comment]
@blakeembrey I tried installing the definitions with `typings`, but typedoc is still using tsd: https://github.com/TypeStrong/typedoc/blob/master/tsd.json. Would be nice if we could add a typings.json until `@types` is ready.

**Comment by blakeembrey** [comment]
I believe there's a PR for `@types`, finishing that up ASAP.

**Comment by christopherthielen** [comment]
These errors might go away if you 
```
npm install --save-dev @types/handlebars
```

**Comment by blakeembrey** [comment]
@christopherthielen It doesn't fix the private properties we have exposed from TypeScript though, which are the first three errors.

**Comment by christopherthielen** [comment]
oh, right, now I understand.  sorry for the noise!
