### ISSUE TITLE
@link to exported member with declaration reference links to top of module

### ISSUE THREAD

**Issue by aayla-secura** [TypeStrong/typedoc#2810]
## Search terms

link, declaration references

## Expected Behavior

I expect the link to point to the relevant object, class, etc regardless which resolution type is used.

## Actual Behavior

When I link to an exported in another module using the declaration reference syntax (because the linked member is not imported by the file for example), the link points to the top/root module and not to the exported member.

## Steps to reproduce the bug

For example, `moduleA` exports `someVar`, which in the doc has its own page.

If I import this into `moduleB` and use `{@link someVar}` it correctly links to it.

If I don't import it and use `{@link moduleA!~someVar}` it links to `moduleA`.

#### Relevant installed packages + versions

```
typedoc-plugin-merge-modules@6.1.0
typedoc@0.26.11
typescript@5.6.3
```

#### tsconfig.json

```
{
	"compilerOptions": {
		"target": "esnext",
		"module": "preserve",
		"moduleResolution": "node",
		"outDir": "./dist/types/",
		"declaration": true,
		"declarationMap": true,
		"emitDeclarationOnly": true,
		"isolatedModules": true,
		"forceConsistentCasingInFileNames": true,
		"strict": true,
		"noImplicitAny": true,
		"strictNullChecks": true,
		"strictFunctionTypes": true,
		"strictBindCallApply": true,
		"strictPropertyInitialization": true,
		"noImplicitThis": true,
		"useUnknownInCatchVariables": true,
		"alwaysStrict": true,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"skipDefaultLibCheck": false,
		"skipLibCheck": false
	},
	"include": ["src/ts/"],
	"typedocOptions": {
		"entryPoints": [
			"src/ts/"
		],
		"entryPointStrategy": "expand",
		"out": "docs/",
		"plugin": ["typedoc-plugin-merge-modules"],
		"mergeModulesMergeMode": "module" // added by plugin typedoc-plugin-merge-modules
	}
}
```

#### How you are running TypeDoc + any relevant configuration files

```
npx typedoc
```

## Environment

-   Typedoc version: 0.26.11
-   TypeScript version: 5.6.3
-   Node.js version: 20.18.0
-   OS: Ubuntu on WSL2 on Windows 11

**Comment by Gerrit0** [comment]
Going to ask for a reproduction that I can easily clone for this one. I don't want to spend time guessing what your setup actually looks at.

Also, please try to reproduce without the plugin. Plugins can do things which will break link resolution.

**Comment by aayla-secura** [comment]
Apologies, here is a minimal example that shows this: https://github.com/TypeStrong/typedoc-repros/pull/48

The first link in the doc for `index.bug` that uses declaration references points to `/modules/Module.html`, while the second one points to `/variables/Module.someVar.html`. Is my declaration reference syntax incorrect?

**Comment by Gerrit0** [comment]
That's... interesting. I apparently missed the `!~` case when implementing that parser some years ago. According to the [tsdoc spec](https://github.com/microsoft/tsdoc/blob/main/tsdoc/src/beta/DeclarationReference.grammarkdown#L144) that should be a reference to a local of the module, which isn't something which TypeDoc supports as it only supports exports. TypeDoc should really be emitting an error here.

`{@link Module!someVar}` works

**Comment by Gerrit0** [comment]
Looking at this a bit more... TypeDoc really ought to be entirely rejecting all usage of `~` in declaration references.

**Comment by Gerrit0** [comment]
... or maybe TypeDoc's docs should just be updated to describe how `~` actually works for it. Either way, this declaration reference doesn't parse correctly, so that's a bug.

https://github.com/TypeStrong/typedoc/blob/016e6a169fc0930afc5e031726c2d397b496133c/src/lib/converter/comments/declarationReferenceResolver.ts#L275-L283

**Comment by aayla-secura** [comment]
Oh, I see where my original mistake was: I was trying to link to a property of an object (which seems to be impossible as they don't have their own anchor or page). And that's why I thought `Module!object#prop` was not working. Thank you for explaining.

**Comment by Gerrit0** [comment]
TypeDoc does support one level of properties, though there was a bug prior to the most recent version where the links were resolved incorrectly.
