### ISSUE TITLE
Re-exported individual named modules don't show up

### ISSUE THREAD

**Issue by aayla-secura** [TypeStrong/typedoc#2811]
## Search terms

re-export

## Question
Not sure if that's a bug, or I'm misunderstanding something.

If a module re-exports everything from another using `export * from "some-module"`, then all of some-module's exports will show as re-exports in the doc for that module. However if I do `export { something } from "some-module"`, nothing shows up. Why is that? How can I include in the doc a particular named re-export?

**Comment by Gerrit0** [comment]
If that's the case, it sounds like a possible bug, however a quick attempt at reproducing it does not show this issue. https://github.com/TypeStrong/typedoc-repros/pull/46, `something` shows up in the docs.

If `some-module` is within node_modules, it is likely being picked up as external, and it might be hidden by default by the [visiblityFilters](https://typedoc.org/documents/Options.Output.html#visibilityfilters) checkboxes in settings.

**Comment by aayla-secura** [comment]
Ok, this was kind of hard to reproduce with a minimal example. It's quite bizarre. I created an example that shows this and a short explanation: https://github.com/TypeStrong/typedoc-repros/pull/47

I hope this helps. I think it should be marked as a bug.

**Comment by Gerrit0** [comment]
Perfect, thanks! That is a strange one.

What's happening here is that TypeDoc creates a reference in index which points to the reference in index-debug, which gets removed by `@hidden` so TypeDoc cleans up references to that reference. Easy enough fix, just have to make TypeDoc not make chains of references, and always point at the eventual target. Not sure why it didn't always work like this...
