### ISSUE TITLE
CONTRIBUTING.md references npm scripts that don't exist

### ISSUE THREAD

**Issue by shawninder** [TypeStrong/typedoc#2815]
## Search terms

test:visual, test:visual:accept, CONTRIBUTING.md

## Expected Behavior

I should be able to follow the directions in CONTRIBUTING.md and successfully run the commands it mentions.

## Actual Behavior

CONTRIBUTING.md mentions npm scripts that don't exist on the repo: `test:visual` and `test:visual:accept`. These are mentioned in 2 places:
- Under `#### Installation`, step 8
- Under `#### Testing`, near the end of paragraph 1

## Steps to reproduce the bug

- Follow instructions from CONTRIBUTING.md:
  - fork repo
  - clone fork
  - install dependencies
  - build
  - Set up a baseline for visual theme testing <-- THIS IS THE PROBLEMATIC STEP
    - EXPECT `npm run test:visual` to launch a test suite
    - OBSERVER npm erroring out saying `npm error Missing script: "test:visual"`
    - EXPECT `npm run test:visual:accept` to launch a test suite which accepts the produced visual artifacts
    - OBSERVER npm erroring out saying `npm error Missing script: "test:visual:accept"`

## Environment

-   Typedoc version: 0.27.5
-   TypeScript version: 5.7.2
-   Node.js version: 22.12.0
-   OS: macOS Monterey 12.7.6

**Comment by Gerrit0** [comment]
Thanks, updated
