### ISSUE TITLE
Cannot set output-specific options

### ISSUE THREAD

**Issue by OmarTawfik** [TypeStrong/typedoc#2818]
The following config allows setting options both globally (for all outputs?), and for each output. But currently it errors out. I tried it with both `cleanOutputDir` (for the `html` output), and `pretty` (for the `json` output). The options works globally, but fail on output-level with the below errors:

```js
const config = {
  entryPoints: [ "..." ],

  // options work when defined globally:
  cleanOutputDir: true,
  pretty: true,

  outputs: [
    {
      name: "html",
      path: "...",
      options: {
        // [error] Tried to modify an option (cleanOutputDir) value after options have been frozen.
        // cleanOutputDir: true,
      },
    },
    {
      name: "json",
      path: "...",
      options: {
        // [error] Tried to modify an option (pretty) value after options have been frozen.
        // pretty: true,
      },
    },
  ]
};
```

## Search terms

`output` `options` `pretty` `cleanOutputDir`

## Expected Behavior

Options would work when set on output-level.

## Actual Behavior

typedoc fails with the error above.

**Comment by Gerrit0** [comment]
Well, that's annoying... I guess I didn't see this because of how I was running TypeDoc when testing, options really shouldn't be frozen anymore, that method should just be removed.
