### ISSUE TITLE
cannot allow/skip unsupported highlighting languages

### ISSUE THREAD

**Issue by OmarTawfik** [TypeStrong/typedoc#2819]
Users can author code blocks in the docs, which might not be supported by typedoc. This is still a valid use case, because it can be used with `typedoc-plugin-markdown`, which will write the language-ID as-is to the markdown, to be highlighted by something other than `shiki` (for example `mkdocs`).

## Search terms

`highlight` `language` `add` `ignore`

## Expected Behavior

Perhaps adding an option like `ignoreLanguages` next to the existing `highlightLanguages`, to allow using these other languages. For `shiki`, it would remain unhighlighted.

## Actual Behavior

Without such flag, users are not able to set the correct language-ID, and are blocked from using other systems/markdown plugins.

**Comment by Gerrit0** [comment]
PR welcome

**Comment by Gerrit0** [comment]
I decided to call the option `ignoredHighlightLanguages` to more closely match `highlightLanguages`
