### ISSUE TITLE
Question: Where did `getAlias` go in the API / Reflection between `0.26.x` and `0.27.x`?

### ISSUE THREAD

**Issue by typhonrt** [TypeStrong/typedoc#2821]
Greets,

Just trying to find out where `Reflection.getAlias` moved to or related functionality to use in `0.27.x` when getting the URL from a reflection. While I understand the case of moving this to serializers the problem I'm facing is that I'm generating a JSON index of all pages to reflections such that this can be used potentially in a programmatic manner. I'm updating `ts-lib-docs` and it's used in the plugin I've created to map the MDN browser compat data to generated doc reflections. 

You can see the usage here: [MDNBuildReflectionMap#L67](https://github.com/typhonjs-typedoc/ts-lib-docs/blob/main/src/plugin/internal/typedoc/mdn-links/processing/MDNBuildReflectionMap.js#L67).

Thanks...

**Comment by Gerrit0** [comment]
I'm pretty sure you just want `reflection.url` which does all of that concatenation logic for you.

If `reflection.url` isn't set, then that reflection doesn't have an anchor in the page, so can't be linked to.

**Comment by typhonrt** [comment]
OK.. I'll take a look.. Ooomph... I Haven't dug into this particular bit of code in a minute and only try and generate `ts-lib-docs` once a year.. The September generation missed out on the `ES2024` built-in TS libs released with `5.7`. Will catch up soon on all of the DMT and such..

**Comment by typhonrt** [comment]
This particular bit of code was about creating the `#` hash references for all sub-symbols on a page / parent reflection. `getAlias` would just create that URL safe hash for leaf. IE here is a link to [AbortSignal.aborted](https://typhonjs-typedoc.github.io/ts-lib-docs/2024/dom/interfaces/AbortSignal-1.html#aborted) that is generated by that block of code mentioned; in this case it's the `aborted` part that `getAlias()` returned. So, I'm looking for a way to generate URL safe hashes for leaf reflections of a page that won't have the base reflection URL set, but has a parent reflection URL.

**Comment by typhonrt** [comment]
I just went with `this.name.replace(/\W/g, "_").toLowerCase()` for the hash anchors which seems to work. There were other issues w/ `ts-lib-docs` that popped up over the last year of TypeDoc upgrades and some new TS lib parsing aspects. I believe I got everything sorted. Just code I don't look at too often and even with some comments its a bit obtuse and a lot of data being processed.

You can chalk this up to another `who moved my cheese` incident. ;)

You did / are doing a great job with the `0.27.x` series.

**Comment by Gerrit0** [comment]
For what you're generating there, that will mostly work. It doesn't fully work. I changed your visit function to start with:

```ts
      const visit = (reflection) => {
         const url = reflection.url;
```

This way it will match the URLs generated by TypeDoc. There are a few differences, the `MathMLElementTagNameMap.annotation-xml` url is different.

```
  "MathMLElementTagNameMap.annotation-xml": {
    "doc_url": "interfaces/MathMLElementTagNameMap.html#annotation-xml",
    "kind": 1024
  },
```

XRInputSourceEvent.AT_TARGET has both a static and instance property and which one is linked to is different.
