### ISSUE TITLE
Add an option to render code blocks horizontally scrollable, without text wrapping

### ISSUE THREAD

**Issue by aleksei-berezkin** [TypeStrong/typedoc#2822]
## Search Terms

wrap, scroll, code

## Problem

Currently, TypeDoc renders code blocks to always fit the container, wrapping the text when necessary. However, many popular platforms, such as GitHub, ChatGPT, DEV.to, MDN, and Reddit, do not wrap lines. Instead, they make code blocks horizontally scrollable. There are exceptions, such as W3Schools, which do wrap lines.

## Suggested Solution

It would be nice to have an option to choose how code blocks are rendered: either wrap lines or enable horizontal scrolling.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the CSS to add a new class for horizontally scrollable code blocks and updated the existing code block styles to support both wrapping and scrolling options.

You can review changes in this commit: https://github.com/mark-addams001881/TypeStrong-typedoc-2822/commit/ca528e1a6e8684d3e78aa69406bedc650cc988b7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Gerrit0** [comment]
My policy for options which would require conditionally writing different CSS is to reject them -- maintaining a multitude of different options for rendering is unmanagable for the level of time I have to spend on typedoc.

This can be done easily with TypeDoc's [customCss](https://typedoc.org/documents/Options.Output.html#customcss) option.

```css
pre {
  white-space: pre;
  overflow-x: auto;
}
```

or

```css
pre {
  padding-bottom: 5px;
}
pre code {
  white-space: pre;
  overflow-x: auto;
  display: block;
  padding-bottom: 5px;
}
```

**Comment by aleksei-berezkin** [comment]
Thanks, this works for me for simple code snippets. For interface signatures, the following also needs to be added:

```css
.tsd-signature {
    overflow-x: scroll;
    white-space: pre;
}
```

This causes the content inside the signature to lack right-padding. To my knowledge, the only clean solution is to wrap the content in another block, similar to how pre code is handled. However, the lack of padding seems tolerable.

Please feel free to close the issue.
