### ISSUE TITLE
missing modernizr.js

### ISSUE THREAD

**Issue by zelein** [TypeStrong/typedoc#286]
Doing a fresh global install of typedoc and generating files for a project, I am getting a file not found error for modernizr.js.

It appears that modernizr is missing from/not being installed in "/assets/js".

**Comment by Radagaisus** [comment]
Relevant PR: https://github.com/TypeStrong/typedoc-default-themes/pull/17.

**Comment by aciccarello** [comment]
Closing due to the PR mentioned above.
