### ISSUE TITLE
Generic return type not recognized.

### ISSUE THREAD

**Issue by zelein** [TypeStrong/typedoc#288]
TypeDoc is not properly rendering my returned Promises. I've tried specifying an @returns as well as leaving it off, but neither seem to render properly.

![image](https://cloud.githubusercontent.com/assets/2420177/18366550/c3294958-75dc-11e6-9e59-c821012cb4ac.png)

![image](https://cloud.githubusercontent.com/assets/2420177/18366532/a9fbb484-75dc-11e6-8e57-907d77573478.png)

**Comment by landonpoch** [comment]
I see this issue as well.  The thing that is strange though is that generic return types are recognized for Array<T> but not for Promise<T>.   Very odd indeed.

**Comment by zelein** [comment]
This is one major thing that is holding my back from switching to TypeDoc from JSDoc.

**Comment by landonpoch** [comment]
Looks like the reason I was seeing this issue was because I had created an aliased ambient namespace for my promises.  As soon as I removed the alias, it all started working.

**Comment by zelein** [comment]
Can you elaborate on that a bit?

I'm using Bluebird for my promises and I'm just simply doing:
import * as Promise from "bluebird"

And I'm using the bluebird module type defs from typings.

**Comment by blakeembrey** [comment]
@zelein If you're using TypeScript, try to avoid using the JSDoc param syntax. TypeScript is parsing and normalising it, and I'm pretty sure it can't handle generics because that doesn't mean anything in JSDoc (could be wrong). See https://github.com/TypeStrong/typedoc/issues/232.

**Comment by landonpoch** [comment]
I was seeing the issue without any JSDoc comments at all.  @zelein I would also recommend just trying a standard `import bluebird = require('bluebird');` if you can.  That might get it working.  I think it might have something to do with the aliasing.

**Comment by zelein** [comment]
But Bluebird recommends you alias its library as Promise, since that is what it is doing. It's replacing the global Promise variable.

@blakeembrey How do you recommend adding descriptions to method parameters then? I've been able to minimize how much of the JSDoc syntax I use...but I haven't figured out a different way to further describe what each parameter is. I've also tried removing the returns Promise<string> entirely and letting TypeDoc generate it based on the typed return, but it still generates "Promise" instead of "Promise<string>"

**Comment by blakeembrey** [comment]
@zelein Ok, sounds like a bug then. I missed that you had tried that and was basing it on the previous feedback which looked like the same issue. You're welcome to make a PR if you find the issue.

**Comment by blakeembrey** [comment]
@zelein Also, you shouldn't be using `import *` and then using it as a function. That's a bug in TypeScript and incorrect usage. Does using `import x = require()` work here in instead?

**Comment by zelein** [comment]
@blakeembrey  `import * as Promise from "bluebird"` and `import Promise = require("bluebird")`
both compile down to `var Promise = require("bluebird")`

I've also tried `import Promise from "bluebird"` but TS says that it does not have a default export.
Regardless, I tried both ways and TypeDoc still fails to generate the generic type of the Promise.

Thanks for your help and insight. If I find the bug I will make a PR.

**Comment by blakeembrey** [comment]
@zelein They both compile down to the same, sure. But semantics are much different and you're abusing an undocumented bug or feature. Does using `import Bluebird = require()` work here?

**Comment by zelein** [comment]
I've successfully tested out `import Bluebird = require("bluebird")` and `import * as Bluebird from "bluebird"`
And the good news is Typdoc is able to successfully generate the generic value of "Bluebird\<string/>"!

So why does it only work if I have it aliased as Bluebird instead of Promise? Or Promises? Or Meow? Can you explain to me the difference?
