### ISSUE TITLE
Links on Guides is broken

### ISSUE THREAD

**Issue by satiekue** [TypeStrong/typedoc#294]
http://typedoc.org/guides/installation/
Links to api documentation and guides are giving 404's.

**Comment by ShadowManu** [comment]
The API docs were somehow lost when migrating to [typedoc-site](https://github.com/TypeStrong/typedoc-site), thing that was done when an old domain for the documentation was lost (now in hands of TypeStrong community). 

You can follow up the issue TypeStrong/typedoc-site#1 in there, to see how are we up in that. Sorry that @d-asensio and I are slow on that (each of us is full of work), but there is actual work this week. We will try to get them up as soon as our time allows.

PS: Consider this closed and follow up on the referenced issue?
