### ISSUE TITLE
Flag "excludePrivate" does not work.

### ISSUE THREAD

**Issue by lord-saumagen** [TypeStrong/typedoc#295]
I wanted to use the 'excludePrivate' flag but it appears that the flag is not recognized.
Please take a look at the output:
![excludeprivate](https://cloud.githubusercontent.com/assets/9468599/18724105/75cfbdf4-803b-11e6-981d-37e0d60aa2e4.png)

**Comment by aciccarello** [comment]
I don't think that is in the latest npm release. Are you installing from github master?

**Comment by blakeembrey** [comment]
As @aciccarello mentioned, this hasn't been released on NPM yet.

**Comment by lord-saumagen** [comment]
So if it isn't part of the NPM package, why does your project page claim to be the description of the NPM Package 0.4.5 and mention the flag?
If some of the options or functions described on the project parge are not available in the 0.4.5 release, you should at least mark them as "planned for future releases" or as "currently not available" or whatever.
How should one otherwise tell which of the functions can be used and which not. Except you run into an error message as I did. But to learn about your project that way is very frustrating.

That said, I wan't to thank you for your excellent work. As far as I can tell, the TypeDoc documentation generator is by far the most advanced documentation generator for TypeScript. It works like a charm. I look forward to your next release and hope you may also find some time to update your documentation.
Kind regards, Lord Saumagen.

**Comment by aciccarello** [comment]
@lord-saumagen The description on npm is pulled from the readme in this repo. The feature has been implemented but it has not yet been released. The confusion stems from the documentation displaying the latest version code while npm has it's own release process and is updated later. If you would like to use this feature you can [install from the git url](https://docs.npmjs.com/cli/install). I understand your confusion though I'm not sure how other projects manage this issue.

**Comment by blakeembrey** [comment]
As far as I know every project manages it's README like this. There's no other way of doing it. Perhaps you've never ended up trying using an unreleased feature from `master` before?
