### ISSUE TITLE
Support more tsconfig.json scenarios

### ISSUE THREAD

**Issue by brphelps** [TypeStrong/typedoc#301]
Right now, the tsconfig.json reader is somewhat limited -- it's only looking for "files" sections and doesn't take into account other significant parameters like "exclude" and "compilerOptions.rootDir". 

Since these are critical to being able to process a tsconfig.json the same way a TypeScript compiler would, support should be added.

**Comment by aciccarello** [comment]
I took a look at the status of Typescript 2.0 support. As a workaround, several options were temporarily ignored via #308 to allow builds to continue but people using the new features may not be able to compile. See #234 for the original discussion.

|feature|issues|PRs|status|
|--------|------|----|------|
|baseUrl|#340|#342|Awaiting #353|
|paths|#340|#342|Awaiting #353|
|include|#326| |Needs PR|
|lib|#315| |Needs PR|
|types|#311| |Needs PR|
|typeRoots|#305| |Needs PR|

**Comment by Gerrit0** [comment]
As far as I know - 0.20 respects all compiler options and behaves the same as tsc does.
