### ISSUE TITLE
Support @copydoc or enhance @inheritdoc

### ISSUE THREAD

**Issue by samchon** [TypeStrong/typedoc#304]
I want some features to be added.
## @copydoc

Copy definition from another one.

If I need to define same content on another object, then it's very annoying. Look at the below codes, then you may understand how I am suffering from duplicated definitions
- [ParallelSystemArray](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelSystemArray.ts#L16-L70)
  - [ParallelServerArray](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelServerArray.ts#L17-L63)
  - [ParallelClientArray](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelClientArray.ts#L17-L63)
  - [ParallelServerClientArray](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelServerClientArray.ts#L22-L68)
- [ParallelSystemArrayMediator](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelSystemArrayMediator.ts#L10-L84)
  - [ParallelServerArrayMediator](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelServerArrayMediator.ts#L17-L92)
  - [ParallelClientArrayMediator](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelClientArrayMediator.ts#L18-L84)
  - [ParallelServerClientArrayMediator](https://github.com/samchon/framework/blob/master/ts/src/samchon/templates/parallel/ParallelServerClientArrayMediator.ts#L22-L97)
## @inheritdoc

The **@inheritdoc** feature in TypeDoc copies definition from its parent class. However, it's standalone. It doesn't allow using the **@inheritdoc** as subsidiary one.

Overriding a method means some logics are changed and some explanation is required. I want to combine **@inheritdoc** with customized comments explaining what is changed.

``` typescript
/**
 * This is the parent class.
 * 
 * Blah blah blah...
 */
class ParentClass
{
    /**
     * Do something.
     */
    public domSomething(): void
    {
    }
}

/**
 * This is a child class derived from the {@link ParentClass}
 *
 * #### [Inherited] {@link ParentClass}
 * @copy8doc ParentClass
 */
class ChildClass
{
    /**
      * On top of its parent, {@link ChildClass.doSomething} do something more.
      * 
      * @inheritdoc
      */
    public doSomething(): void
    {
    }
}
```

**Comment by Gerrit0** [comment]
TypedDoc's [`@inheritDoc`](https://typedoc.org/tags/inheritDoc/) supports copying documentation from another arbitrary documented symbol as of 0.23.

I'm really wary to add additional copying methods which won't be recognized by VSCode, and will result in worse docs for people using the language service to read documentation (the majority of declaration file use, in my experience)

I'm open to doing something like this if enough people want it, but a proposal like it needs to describe how it will play with comment tags, where it's permitted, when it is resolved, etc... I don't want to add a feature that few people know exists, and fewer how to use properly, like several existing features...
