### ISSUE TITLE
support for typeRoots

### ISSUE THREAD

**Issue by m3l7** [TypeStrong/typedoc#305]
typedoc crashes if typeRoot option is set in tsconfig.json. Is there a way to avoid this?
here is my tsconfig.json:

```
  {
      "compilerOptions": {
          "target": "es5",
          "module": "commonjs",
          "sourceMap": true,
          "outDir": "src",
          "typeRoots": ["./typings/modules", "./typings/globals"]
      },
      "include":[
          "src/**/*"
      ]
  }
```

**Comment by aciccarello** [comment]
Related to #234. Someone is working on basic TS 2.0 support. You can try the version in #290 and see if that fixes this issue.

**Comment by m3l7** [comment]
I've updated from master and this issue seems to be solved.
