### ISSUE TITLE
Default the selected menu options on a generated doc site

### ISSUE THREAD

**Issue by christianacca** [TypeStrong/typedoc#307]
**Is it possible to specify which menu options are selected by default?**

I want to have the "Only exported" option selected by default whenever someone visits the generated doc site:

![image](https://cloud.githubusercontent.com/assets/886590/19408479/1af9b2da-92b6-11e6-9845-c00ecf0ce2d2.png)

**Alternatively, is there an build option to only generate docs for "exported" code?**

Thanks (and great job BTW).

Christian

**Comment by aqumus** [comment]
@Gerrit0  Is this issue been worked on by anyone, I could give it a try and raise a PR.
Any initial pointers?

**Comment by Gerrit0** [comment]
Nope, nobody's working on this today AFAIK. You'll need to add a new option (I generally start in declaration.ts in the options folder, then typedoc.ts in options/sources) and update the header template in... some tsx file.
