### ISSUE TITLE
Add alias for specific comment tag

### ISSUE THREAD

**Issue by iveetoo** [TypeStrong/typedoc#313]
Is there a way to register alias for specific comment tag?

I use the TypeScript compiler option `stripInternal: true` with the `@internal` tag to not emit declarations for some utility functions that are used internally. Also, I do not want to generate documentation for these utilities. I found the `@hidden` tag (https://github.com/TypeStrong/typedoc/issues/62) , that excludes the symbol from the generated documentation. Now, my .ts files has two comment tags:

``` javascript
/**
 * @internal
 * @hidden
 */
export function someUtility () { ... }
```

I would like to be able to register `internal` as alias for `hidden` tag. Thanks. 
Before I've found the `@hidden` tag, I was forced to generate the doc from the .d.ts file to exclude the utilities, but there is other issue (https://github.com/TypeStrong/typedoc/issues/186)

**Comment by aciccarello** [comment]
Closing in favor of #364 since it is more specific. I think handling this case specifically makes more sense than allowing user defined aliases.
