### ISSUE TITLE
TypeDoc doesn't support the lib option

### ISSUE THREAD

**Issue by kayahr** [TypeStrong/typedoc#315]
I use the new `lib` option in `tsconfig.json` to explicitly set the [built-in type definitions](http://www.typescriptlang.org/docs/release-notes/typescript-2.0.html#including-built-in-type-declarations-with---lib) I want to use in my project:

``` json
{
    "$schema": "http://json.schemastore.org/tsconfig",
    "compilerOptions": {
        "target": "es5",
        "lib": [ "es2015.promise", "es2015.core", "es2015.collection", "es5", "dom" ],
        "module": "commonjs",
        "rootDir": "src",
        "outDir": "lib",
        "noEmitOnError": true,
        "sourceMap": true,
        "declaration": true,
    },
    "exclude": [
        "node_modules",
        "lib"
    ]
}
```

Unfortunately typedoc doesn't support this:

``` bash
$ typedoc --out doc src
Error: Unknown option `lib.0`.
Error: Unknown option `lib.1`.
Error: Unknown option `lib.2`.
Error: Unknown option `lib.3`.
Error: Unknown option `lib.4`.
```

For now I reverted back to using external type definitions for the needed ES2015 features so I'm able to use TypeDoc but it would be nice if TypeDoc could support this useful new feature.

**Comment by aciccarello** [comment]
This is a remaining issues following #234. PR #308 ignored this option to allow TypeDoc to run but PRs to enable lib support are very welcome.

**Comment by unsafecode** [comment]
@aciccarello Any ETA on a fixing release? I cannot run typedoc anymore on TS 2.0

**Comment by aciccarello** [comment]
@unsafecode As far as I know no one is working on it. There is no active maintainer of this project so fixes/features are entirely community driven.

**Comment by jonaskello** [comment]
It seems the fix has been merged but there is no new release. I tried to install from master branch to get it:

`npm install -g https://github.com/TypeStrong/typedoc.git#master`

Installing works but running does not:

```
$ typedoc --mode modules  --out doc/ ./
module.js:457
    throw err;
    ^

Error: Cannot find module '../lib/cli.js'
    at Function.Module._resolveFilename (module.js:455:15)
```

**Comment by kayahr** [comment]
Since typedoc 0.5.1 the "lib" option is silently ignored and typedoc now complains about the missing type definitions. I found a simple but ugly workaround (No pull request for this) to fix this (At least for me). Insert these lines into `bin/typedoc` so the lib settings are converted to command line parameters (Directly referencing the .d.ts files of typescript):

```javascript
var path = require("path");
var tsconfigPath = path.resolve(process.cwd(), "tsconfig.json");
var tsconfig = require(tsconfigPath);
if (tsconfig.compilerOptions && tsconfig.compilerOptions.lib) {
    tsconfig.compilerOptions.lib.forEach(function(lib) {
        process.argv.push("node_modules/typescript/lib/lib." + lib + ".d.ts");
    });
}
```

As I said this is just an ugly "works for me" workaround and I just mention it in case it is useful for someone else waiting for a real fix for this issue.

**Comment by aciccarello** [comment]
Does anyone know if this was fixed in #359?

**Comment by nakedcity** [comment]
Any update on this one ??? lib is not taken in account yet

**Comment by bafolts** [comment]
You can also manually include the lib files in your include section of your typescript config file. A less hackier version than modifying the binary.

```
    "include": [
        "../node_modules/typedoc/node_modules/typescript/lib/lib.dom.d.ts",
        "../node_modules/typedoc/node_modules/typescript/lib/lib.es5.d.ts",
        "../node_modules/typedoc/node_modules/typescript/lib/lib.es2015.core.d.ts",
        "../node_modules/typedoc/node_modules/typescript/lib/lib.es2015.collection.d.ts",
        "../node_modules/typedoc/node_modules/typescript/lib/lib.es2015.reflect.d.ts",
        "../node_modules/typedoc/node_modules/typescript/lib/lib.es2015.iterable.d.ts",
        "../node_modules/typedoc/node_modules/typescript/lib/lib.es2015.promise.d.ts",
        "../node_modules/typedoc/node_modules/typescript/lib/lib.es2015.symbol.d.ts",
```

**Comment by yohei1126** [comment]
Thanks. I will try it later.

Yohei Onishi

2017-03-22 12:37 GMT+09:00 Blake Embrey <notifications@github.com>:

**Comment by brphelps** [comment]
@blakeembrey , @nicknisi  -- Is the lib option (specifically) supported via any command line args? Gulp-typedoc is basically a passthrough for command line options, and while I'm using lib in my tsconfig, I'm not sure if I can pipe that into that plugin anymore.

**Comment by nicknisi** [comment]
@brphelps It's not specifically supported via the command line currently, but it is something that should probably be supported. When set via command line args, it does pass through to TypeScript, but it doesn't get the conversion to the correct filename. Currently, `typedoc --lib dom,es2015` passes to TypeScript as `['dom', 'es2015']`, but it should be passed as `['lib.dom.d.ts, 'lib.es2015.d.ts']`.

**Comment by iburton** [comment]
FYI, this seems to work for my project, not sure if it is universal or not:
`lib: ["lib.dom.d.ts", "lib.es2015.d.ts"],`

**Comment by Gerrit0** [comment]
Passing TS options (like lib) through the command line should not be required in the vast majority of cases. We support reading a tsconfig.json file, which is where TS options should really be set.

I'm not worried about requiring the full declaration file name on the command line. In the 100 or so projects that I've looked at that use TypeDoc, none pass lib options through the CLI. I don't think the extra complexity in the option parsing code to handle shorthand names is worth it.
