### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by Thomas-Sparber** [TypeStrong/typedoc#316]
First of all: Thank you sooo much for the great Project!!
But as I am a german person and the german language uses some special characters such as ä, ö, ü or ß, I need to write the HTML version of those characters in my documentation: e.g. &auml; This is somehow annoying.
I also searched in the source code and found a solution. I inserted the following lines of code in the function `MarkedPlugin.prototype.parseMarkdown = function (text, context)` just at the beginning of the function:

```
text = text.replace(new RegExp('ä', 'g'), '&auml;');
text = text.replace(new RegExp('ö', 'g'), '&ouml;');
text = text.replace(new RegExp('ü', 'g'), '&uuml;');
text = text.replace(new RegExp('Ä', 'g'), '&Auml;');
text = text.replace(new RegExp('Ö', 'g'), '&Ouml;');
text = text.replace(new RegExp('Ü', 'g'), '&Uuml;');
text = text.replace(new RegExp('ß', 'g'), '&szlig;');
```

The file is located under lib/Output/plugins/MarkedPlugin.js

Best Regards
Thomas

**Comment by bradleyayers** [comment]
I'm curious why you need to write the HTML entity version of these characters? That shouldn't be needed, it sounds like instead the correct encoding is not being used or declared.

**Comment by Thomas-Sparber** [comment]
Yes that's probably true...
But as far as I know, most (or all) of the Webpages use These characters to Display Special characters.
How should I declare the correct Encoding?

**Comment by bradleyayers** [comment]
@Thomas-Sparber I expect you can just use a [meta tag](https://www.w3.org/International/questions/qa-html-encoding-declarations.en) to declare it

```html
<!DOCTYPE html>
<html lang="en"> 
<head>
<meta charset="utf-8"/>
...
```

**Comment by Gerrit0** [comment]
The default theme has a meta tag, so these characters should work as intended. We have a test case now for Cyrillic characters, which should also cover the characters above.
