### ISSUE TITLE
Support 2.0.6

### ISSUE THREAD

**Issue by Martinspire** [TypeStrong/typedoc#318]
The latest Typescript (2.0.6) isn't supported and it throws an unmet dependency warning when installing it.

Is there a specific reason where the package.json states typescript specifically to a certain version? The other dependencies all got a "greater or equal" caret next to their versions, but Typescript is stuck on a specific one. I don't think it should force a specific version of a dependency

**Comment by blakeembrey** [comment]
Please search and read other issues for why it's a dependency. Also, it's not this project warning about an unmet dependency - please check your warning, this project has no peer dependencies at all.

**Comment by Martinspire** [comment]
@blakeembrey I'm pretty sure it is.

Not only can i show you from the [package.json](https://github.com/TypeStrong/typedoc/blob/master/package.json), but also it has been changed recently:
https://github.com/TypeStrong/typedoc/commit/8f705318d91cff43e3e9ec8ed9938257f738bd5f

And yes if i put 2.0.6 in my own package .json then it will complain, but thats because this project is strictly setting the typescript dependency.

**Comment by aciccarello** [comment]
@Martinspire Could you include the exact error/warning message you are getting?

**Comment by blakeembrey** [comment]
@Martinspire That's just not how dependencies work in NPM, so perhaps you have a different issue. Please provide the warning you see. Or at least the NPM and node version you're using.

I'm 99.9% confident it can't be from this module because we don't have a peer dependency, we have a regular dependency. Unmet dependencies mean you have a module that specifies a peer dependency and TypeScript isn't fulfilling it.

**Comment by blakeembrey** [comment]
Also, the commit you say recently changed hasn't been released either.

**Comment by Martinspire** [comment]
The NPM log is as follows:

    npm WARN unmet dependency C:\ .... node_modules\typedoc requires typescript@'2.0.3' but will load
    npm WARN unmet dependency C:\ .... node_modules\typescript,
    npm WARN unmet dependency which is version 2.0.6

And this will probably be similar when the next version of typescript comes out since the 0.5.1 release of typedoc only specifies 2.0.6 now. 

My Node is somewhat older (4.x branch) as we have some internal error at the company, but that still doesn't change the fact that typedoc should not hardcode a specific version of typescript if there is no reason to do so.

The commit did happen but it wasn't (yet) part of the release. As far as i can see the new 0.5.1 contains this change

**Comment by blakeembrey** [comment]
It will always contain a hard dependency, TypeScript doesn't follow SemVer and this module requires a specific API interface to load. It wouldn't be a very useful system if we couldn't have a different dependency to someone else. Can you please share steps to reproduce this? Are you using specific NPM flags? I've never seen this issue before, so it suggests that perhaps it's your setup or an NPM bug.
