### ISSUE TITLE
Cannot find namespace 'NodeJS'.

### ISSUE THREAD

**Issue by drochgenius** [TypeStrong/typedoc#320]
I just updated my project to Typescript 2.0 and Typedoc@latest, and I get this error thrown from Typedoc.

```
 Cannot find namespace 'NodeJS'.
```

I had to change a type from `number` to `NodeJS.Timer`, because of a change in the type definition for setTimeout in Node type definitions.

Any idea how I can fix this issue?

**Comment by aciccarello** [comment]
Be aware that some of the newer TypeScript 2.0 features are not supported. This could affect how TypeDoc looks up the types for your project.

**Comment by aciccarello** [comment]
Are you using the `types` option in your tsconfig.json? See #311 for the state of that option.

**Comment by Fzum** [comment]
@drochgenius Got the same exact problem. also with number to Timer. Did you already find a solution? thanks

**Comment by Fzum** [comment]
If you also have tsconfig.app.json in your working directory, try to add the attribute node to the types field. Like: 
`{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es6",
    "baseUrl": "",
    "types": ["node"] --> ADD THIS
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}`

This was working for me..

**Comment by Murilo-Perrone** [comment]
For me ` "types": ["node"]` didn't work, but it worked by adding this directive:

```
{
  "compilerOptions":
  {
    ...
    "typeRoots": [
      "node_modules/@types"
    ]
  }
}
```
PS: I'm in an ionic 3 project running on Windows.

**Comment by aciccarello** [comment]
@Murilo-Perrone I thought TypeScript includes all `@types` definitions if `types` and `typeRoots` are not set.

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Comment by Gerrit0** [comment]
This seems to be working, I can't reproduce the issue without specifically configuring TypeDoc to break this.

Please open a new issue with a reproduction if you are still having the problem.

**Comment by zedmyls** [comment]
> If you also have tsconfig.app.json in your working directory, try to add the attribute node to the types field. Like: `{ "extends": "../tsconfig.json", "compilerOptions": { "outDir": "../out-tsc/app", "module": "es6", "baseUrl": "", "types": ["node"] --> ADD THIS }, "exclude": [ "test.ts", "**/*.spec.ts" ] }`
> 
> This was working for me..

works for me. thx
