### ISSUE TITLE
Add an option to prevent HTML from being generated

### ISSUE THREAD

**Issue by ericjim** [TypeStrong/typedoc#337]
In my current project, I am only relying on the outputted json file to generate documentation. Is there any way to prevent HTML from being generated? I do not use those files. This is somewhat related to https://github.com/TypeStrong/typedoc/issues/257

**Comment by aciccarello** [comment]
You should be able to do this by calling the [`generateJson` method](http://typedoc.org/api/classes/application.html#generatejson) on an `Application` instance.

It would be something along the lines of
```javascript

const src = Path.join(__dirname, 'src');
const out = Path.join(__dirname, 'docs.json');
const app = new TypeDoc.Application({
  mode: 'modules',
  out: 'docs',
  theme: 'minimal',
  tsconfig: './tsconfig.json',
});
app.generateJson(app.expandInputFiles([src]), out)
```

My initial reaction is that this doesn't need to be part of the CLI so I'll close the issue.
