### ISSUE TITLE
Is it possible to run typedoc via npm scripts?

### ISSUE THREAD

**Issue by fshchudlo** [TypeStrong/typedoc#341]
Hello. 
First of all, thanks for  your work on this great tool 👍 
Can you please help with such problem:
I try to run typedoc via npm scripts with next command: 
```
npm run typedoc -- --out ./docs/ ./src/
```
I see that typedoc is actually started, but I can't pass any additional arguments to it. 
For example, if I specify `--target` option like this:
```
npm run typedoc -- --out ./docs/ --target ES6 ./src/
```
typedoc raises 'Cannot find name 'Map'.' which indicates that it doesn't recognize `target` option.

I've also tried to use `--options` option which is mentioned in typedoc help and specify next json file
```
{
    "experimentalDecorators": true,
    "includeDeclarations": false,
    "help": true,
    "mode": "file",
    "module": "umd",
    "out": "docs",
    "readme": "none",
    "target": "es6"
}
```
but this doesn't work and I'm not sure that I use it correctly at all since this option is not described anywhere.

**Comment by dotcs** [comment]
Maybe I can help. I'm using typedoc for documentation of an Angular 2 project. I can successfully trigger the doc build via `npm run build-docs`.

package.json (relevant part only)
```json
{
  "scripts": {
     "build-docs": "rimraf docs && typedoc --options typedoc.json src/"
  }
}
```

```json
{
  "mode": "modules",
  "out": "docs",
  "name": "my-project-name",
  "theme": "default",
  "ignoreCompilerErrors": "true",
  "experimentalDecorators": "true",
  "emitDecoratorMetadata": "true",
  "target": "ES5",
  "moduleResolution": "node",
  "preserveConstEnums": "true",
  "stripInternal": "true",
  "suppressExcessPropertyErrors": "true",
  "suppressImplicitAnyIndexErrors": "true",
  "module": "commonjs"
}
```

**Comment by fshchudlo** [comment]
This works for me. Thanks a lot!
