### ISSUE TITLE
Getting error main.js:5 Uncaught TypeError: typedoc.Application is not a constructor

### ISSUE THREAD

**Issue by sidharthv** [TypeStrong/typedoc#343]
I created a very simple test.d.ts file with the following content:

```javascript
declare module MyModule {
    export interface SomeItem {
        type: string;
        timestamp: number;
        status: Date;
    }
}
```

Added a package.json file that specified devDependencies of only typedoc: 0.5.0

Ran the following command:
```
node_modules\.bin\typedoc --out OUTPUT test.d.ts --experimentalDecorators --target es5 --includeDeclarations --mode file --name 'Random'
```

It generated some html documentation and I was able to browse the content but I could not perform searches. I see the following error in the chrome console:
main.js:5 Uncaught TypeError: typedoc.Application is not a constructor
at typedoc (... main.js:5:4156)

**Comment by dotcs** [comment]
> TypeDoc 0.5.1
> Using TypeScript 2.0.6

+1, same problem here. Let me know more details are required.

**Comment by sebastiankvist** [comment]
> TypeDoc 0.5.1
> Using TypeScript 2.0.6

I too experience this.

**Comment by Narazaka** [comment]
It seems to be typedoc-default-themes@0.4.1 probrem because it has been fixed by
```json
{
"typedoc": "...",
"typedoc-default-themes": "0.4.0"
}
```

**Comment by zim32** [comment]
Still not fixed?

**Comment by timocov** [comment]
Fixed in https://github.com/TypeStrong/typedoc-default-themes/pull/29

**Comment by blakeembrey** [comment]
Closing as resolve according to the above comment.
