### ISSUE TITLE
TS 2.2dev doesn't output anything... :(

### ISSUE THREAD

**Issue by electricessence** [TypeStrong/typedoc#344]
I've tried with different versions and recently pulled directly from GitHub as Daniel R on Twitter posted an article about.

Firstly, with 2.0.2, and 2.0.8 I get a Node runtime error something about ```...declarations.forEach``` and it won't continue.

2.2dev seems to work just fine.  But no API shows up.  This used to work fine before.  Is there maybe a source parameter I'm missing?

**Comment by aciccarello** [comment]
Hello @electricessence, [support for Typescript 2.x](https://github.com/TypeStrong/typedoc/issues/234) is not at 100% yet. Members of the community have been submitting PRs to support newer features but more work needs to be done to support it completely.

Any further information to help the community figure out a fix would be greatly appreciated!

**Comment by electricessence** [comment]
@aciccarello The article I read presented a means for using 2.x so I thought it would be a good idea to double-check/verify if that's an actual thing.

**Comment by aciccarello** [comment]
@electricessence I'm going to assume that this was fixed in #448. Feel free to reopen if you are still encountering this problem.
