### ISSUE TITLE
@types in dependencies causing build failures

### ISSUE THREAD

**Issue by crazytoucan** [TypeStrong/typedoc#350]
Unfortunately, we just hit the `dependencies` vs `devDependencies` issue as discussed in https://github.com/TypeStrong/typedoc/pull/310#pullrequestreview-4978799. Specifically, our project:

- Uses a different version of Lodash / its own `@types/lodash`.
- Has a dev dependency on `typedoc`, which installs a separate version of `@types/lodash`

Both `@types/lodash` installations are being picked up by the typescript compiler, causing duplicate definition warnings. Per discussion in that thread, can we move those types back out to `devDependencies` to prevent the unnecessary downstream installation?

If any of the `@types/` modules are actually needed by the generated `typedoc.d.ts` (seems like `@types/handlebars` might fall into this category?), I propose we inline those typings (re-expose them manually) so that we don't cause any build inconsistencies for other folks that might be using a different version of handlebars.

Will you all accept a PR for this? Any concerns about the approach?

**Comment by DaSchTour** [comment]
I already made a PR for this #335 but it seams the project is close to death
Have to remove typedoc from my projects because this creates a lot of trouble 😡

**Comment by blakeembrey** [comment]
Answered in https://github.com/TypeStrong/typedoc/pull/335#issuecomment-268070899. The definition needs to be fixed in DefinitelyTyped - which it may already have been, because this was brought up to them a few weeks ago.

**Comment by blakeembrey** [comment]
If this seriously needs to be done for TypeScript to function, it's also a flaw in TypeScript that should be fixed. There's no reasonable expectation here for module authors to require duplication of dependencies to work.

**Comment by DaSchTour** [comment]
There is, because Typdoc add typings that are not needed for the project. Modules show up that are not available in the project and create conflicts with typings installed from other sources like typings. I don't see any case were typings are needed at runtime!
