### ISSUE TITLE
do we still need to install this lib via? npm install --save-dev https://github.com/DatenMetzgerX/typedoc/tarball/typescript-2-build

### ISSUE THREAD

**Issue by born2net** [TypeStrong/typedoc#351]
do we still need to install this lib via? npm install --save-dev https://github.com/DatenMetzgerX/typedoc/tarball/typescript-2-build

Regards,

Sean

**Comment by aciccarello** [comment]
@born2net I'm confused by your question. What alternative way of installing are you thinking of?

**Comment by born2net** [comment]
per this doc https://blog.cloudflare.com/generating-documentation-for-typescript-projects/
see:

If you’re using TypeScript 2.x, use the following command to install TypeDoc for your project:
npm install --save-dev https://github.com/DatenMetzgerX/typedoc/tarball/typescript-2-build ....

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by aciccarello** [comment]
Ah, I see. You are asking if you need to use DatenMetzgerX's branch. TypeDoc on npm has initial support for TypeScript 2.0 so you can simply `npm install typedoc --save-dev`. Be aware that this project still is missing support for some 2.0 features but the branch you are referring to doesn't seem to have any better support.

**Comment by born2net** [comment]
ok tx!

**Comment by born2net** [comment]
will this project support 2.0 soon?

**Comment by aciccarello** [comment]
It has partial support, but it is a community run project with no active maintainer. Support for features is primarily added via pull requests so no timeline.

**Comment by born2net** [comment]
got it tx
