### ISSUE TITLE
Support "readonly" as a parameter property.

### ISSUE THREAD

**Issue by lddubeau** [TypeStrong/typedoc#352]
### Versions

typedoc: 0.5.1
typescript: 2.0.10

### Steps to Reproduce

1. Create a project with this file named `test.ts`:

    ```
    class Foo {
        constructor(private a: string, readonly b: string) {
        }
    }

    const f: Foo = new Foo("1", "2");

    console.log(f.b);
    ```

2. Run `typedoc` on it.

### Expected Results

The documentation should list both `a` and `b` as properties of the class `Foo`.

### Actual Results

Only `a` is present as property of `Foo` but `b` is missing. (They both appear as parameters to the constructor, which is fine.)

**Comment by aciccarello** [comment]
Thanks @lddubeau. PRs are welcome.

**Comment by thopaw** [comment]
Is it possible to also use the doc added to the constructor property?

```
class A {
  constructor(
    /**
     * I want to see this comment in the documentation
     * /
     readonly property: string) {}
}
```

Is it possible to see the 

> I want to see this comment in the documentation

in the generated HTML?
