### ISSUE TITLE
Typedoc verbose mode?

### ISSUE THREAD

**Issue by seescode** [TypeStrong/typedoc#355]
This a great project.  I would love to see a verbose mode as one of the options.  It's sometimes difficult to tell what's going on whenever I try out different options.  

Maybe I can try and implement something.  I just need to get a sense of the requirements.  At a minimum I would like typedoc to tell me what files are being looked at.  For example having Converter.prototype.convert console.log out the filenames.  

Do you think this would be useful?

**Comment by aciccarello** [comment]
Yeah, I could see it being helpful to figure out what is being run. I know there is more information in the JSON output but a more user friendly interface for seeing how the application is being parsed would be helpful when configuring TypeDoc for a project.

PRs are always welcome even though it may take some time to get things merged.

**Comment by Gerrit0** [comment]
Frequently when debugging I wish we had this. I frequently switch to a linked version of TypeDoc and add a few well placed console.log statements to write out the configuration, what file is currently being processed... whatever seems relevant to what I'm searching for.

I'd like to add a builtin log level for verbosity, but it is hard to tell what is commonly useful (logging active config) vs specifically useful (`requirements` parameter to `TocPlugin#buildToc`)... I don't want verbose mode to turn out to be so much output that it is impossible to get useful info from it.

If we try to do this, I think starting with fairly minimal logging (config + current file being processed) is a good idea. We can add more logging as it becomes useful.
