### ISSUE TITLE
`getJsDocComments`  removed

### ISSUE THREAD

**Issue by basarat** [TypeStrong/typedoc#357]
So that contributions don't have to search like I did for alm

Function used as seen here : https://github.com/TypeStrong/typedoc/blob/0867cc2788eba6f4bcfd327d27151f13af6e8686/src/lib/ts-internal.ts#L82-L84

Removed from TypeScript master https://github.com/Microsoft/TypeScript/pull/12335/files

Sample fix https://github.com/alm-tools/alm/commit/62a53b776c7e7b7cf91fbdd235e790ef99a31d62#diff-782075da003b6eea6714a35fcd62a70f 

Thanks :rose:

**Comment by aciccarello** [comment]
Thanks for the heads up @basarat :rose:. If anyone wants to put together a PR I'm sure it'd be weclome :smile:

**Comment by ShiMeiWo** [comment]
@aciccarello I want the fixations. Would you include them into a PR? :)

**Comment by kamranayub** [comment]
I have this fix in my 2.1.4 branch (and soon PR)

**Comment by kamranayub** [comment]
@blakeembrey This can be closed, it's in master now. Thanks!
