### ISSUE TITLE
TypeDoc engin generates one readme file for the whole project. Is it possible to generate one readme file per directory | folder 

### ISSUE THREAD

**Issue by kanso-git** [TypeStrong/typedoc#358]
Problem description :  TypeDoc engin generates one Readme file for the whole project even if you have more than one readme files exis in the sub folders . Could you please provide a way to generate a readme file per folder ?

My current version of typedoc :"typedoc": "^0.5.1",

Many thanks in advance

**Comment by aciccarello** [comment]
Related to #63 and #247
