### ISSUE TITLE
Fenced code block breaking with @ decorator

### ISSUE THREAD

**Issue by etsuo** [TypeStrong/typedoc#361]
I have a function that is an ES7 style decorator (`@Module`). When I try to document its use in a fenced code block, typedoc renders it as an unknown tag, thus breaking the code block.

How do I include a code example like this:
```
/**
 * ### Example
 *
 * ```
 * import {Model} from '...'
 * @Model()
 * class User {
 * }
 * ```
 */
```

**Comment by aciccarello** [comment]
See #187
