### ISSUE TITLE
github.io compatible output filenames

### ISSUE THREAD

**Issue by mkloubert** [TypeStrong/typedoc#362]
I would like to publish the code documentation of my project [vs-deploy](https://github.com/mkloubert/vs-deploy) on github.io.

As you can see [here](https://mkloubert.github.io/vs-deploy/), this works fine for the index page.

But if you select a module like [contracts](https://mkloubert.github.io/vs-deploy/modules/_contracts_.html), GitHub reports an 404 error (maybe because of the `_contracts_.html` filename with surrounding `_` chars?).

Is there a way to fix that issue by defining a custom pattern for the output filenames, e.g.?

**Comment by WasabiFan** [comment]
You can create a file called `.nojekyll` in the root of your repository to prevent GitHub from attempting to use Jekyll (which handles names with underscores differently) and instead have it just serve your content as-is. Note that TypeDoc erases all files in the output directory by default, so you may need to use the `disable-output-check` flag as I do (which means that you will need to manually delete files that are no longer necessary) or add creation of that file to your build scripts.

**Comment by mkloubert** [comment]
Thanks a lot! 👍 

Works fine! :D

**Comment by userpixel** [comment]
I build the documentation every time a new version is released (but delete the old `docs` folder before generating new one). Given Github's popularity, it would be great to have an option to add that file to the output. Just a suggestion. :)

**Comment by thomashagstrom** [comment]
If you're publishing with `gh-pages` remember the `--dotfiles` parameter, e.g.

```bash
gh-pages --dotfiles -d docs
```
