### ISSUE TITLE
exporting internal definitions?

### ISSUE THREAD

**Issue by emmanueltouzery** [TypeStrong/typedoc#368]
[My understanding](http://stackoverflow.com/questions/41372014/publishing-a-typescript-library-on-npm-exported-symbols-modules#comment69954071_41374190) is that if I publish a `npm` library then only functions & types exported from `index.ts` will actually be accessible to users of the library.

As it is, `typedoc` also generates documentation for exported symbols from other files. To give an example. [parseView](https://github.com/emmanueltouzery/ng-typeview/blob/479f86450d6a7e6c824bcad85fa18771401e168d/src/view-parser.ts#L176) is for internal use only  -- but I do export it from view-parser.ts so that [ng-typeview](https://github.com/emmanueltouzery/ng-typeview/blob/479f86450d6a7e6c824bcad85fa18771401e168d/src/ng-typeview.ts#L7) can use it.

However if I create an index.ts NOT reexporting parseView, typedoc ignores that and documents parseView anyway. I can hide it with `@hidden`, but there should probably be a way to make this automatic?

Except if I misunderstood the system and these functions are actually available to users of my library?

**Comment by Shin-Ogata** [comment]
I have same problem.

My AMD project cannot compile because of duplicate "require" declaration from "node_modules/@typs/node/index.ts".

**Comment by Gerrit0** [comment]
Closing in favor of #639, where a new mode for only documenting exports from an entry point is described.

Regarding `npm` - just doing `require('somelib')` will give you access to whatever is exported from `index.js` (or an alternate file specified in `package.json`), but there is nothing to stop users from doing `require('somelib/private/parse-view.js')`
