### ISSUE TITLE
Use a local version of TypeScript?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [TypeStrong/typedoc#369]
Rather than wait for TypeDoc to support the latest TypeScript each time features are added, how about allow an optional config parameter to point to a local TypeScript version instead of the bundled?

For prior work, see [`gulp-typescript`](https://www.npmjs.com/package/gulp-typescript#typescript-version).

**Comment by blakeembrey** [comment]
I believe this has been answered before. Short answer: No, it's not possible to do because a version can break compatibility at any point. E.g. even 2.0 -> 2.1 broke `typedoc`.

**Comment by JoshuaKGoldberg** [comment]
@blakeembrey I couldn't find anything via issue search, could you please link to the discussions?

Not trying to be nitpicky, but is it that it's not possible to use a local version, or that using a local version is extremely prone to breakages? If it's the latter, how difficult is it to upgrade? Is there a guide somewhere?

**Comment by blakeembrey** [comment]
No, it's extremely simple to use a local version - we could use peer dependencies or not specify it at all and node will resolve it using the basic module resolution algorithm. However, `typedoc` is really only designed against a single version - e.g. a single minor up or down may break. Here's the PR for the latest version change by a community member: https://github.com/TypeStrong/typedoc/pull/365. I'm not sure where the discussion has occurred now, maybe something like https://github.com/TypeStrong/typedoc/issues/234?
