### ISSUE TITLE
Error with nested tsconfig extends

### ISSUE THREAD

**Issue by raveclassic** [TypeStrong/typedoc#380]
Hi!
Recent typescript supports configuration inheritance via "extends" in `tsconfig.json`. Everything's working until extended config tries to extend another itself.
Example:
```
//tsconfig.json
{
 "extends": "./tsconfig.a.json"
}

//tsconfig.a.json
{
 "extends": "./tsconfig.b.json",
}

//tsconfig.b.json
{
 "compilerOptions": {
 }
}
```

An error occures: `TypeError: Cannot convert undefined or null to object` at `typedoc\dist\lib\utils\options\readers\tsconfig.js:60` when trying to `delete compilerOptions[key];`.
Seems like `data.raw` does not contain `compilerOptions` at all.

```
ts: 2.1.5
typedoc: 0.5.5
```

**Comment by DennisJaamann** [comment]
+1, having the same issue:

- NodeJS 7.0.0
- TypeScript 2.2.0-dev.20161212
- TypeDoc 0.5.5

**Comment by lddubeau** [comment]
If I install 0.5.5, I can reproduce the problem without any use of "extends". I just need to have a `tsconfig.json` that contains `{}` and the error occurs.

I cannot reproduce the problem with typedoc 0.7.1. Consequently, this should be closed.

**Comment by aciccarello** [comment]
Reopening due to questions raised in #1089
