### ISSUE TITLE
Issues creating documentation for node.js (ts-node) app

### ISSUE THREAD

**Issue by BernhardBehrendt** [TypeStrong/typedoc#381]
Having a problem I can't solve actually when trying to document my code
which uses node specific typings.

Included `"@types/node": "^7.0.0"`

First doc generator crashes at `__dirname` ->  **Cannot find name '__dirname'.**

Then it also crashes at a `readFileSync`which is included this way 
`import {readFileSync} from 'fs';` -> **Cannot find module 'fs'.**

I don't know what's going wrong here because any other aspects around typings are working (run the app, runt mocha tests and coverage report).

Do I have to bind the typing differently or so?

**Comment by joelwross** [comment]
I am having similar problems. TypeScript (`v2.1.5`) is able to compile correctly and without errors simply by include `@types/node` in `node_modules` but running `typedoc` (on `v0.5.5`) will produce

```
Cannot find name 'process'.
```

Is there a specific step needed to ensure that TypeDoc's execution of the TypeScript compiler includes `@types` definitions?

**Comment by aciccarello** [comment]
These both seem like issues with arguments being passed to TypeScript. There were multiple changes made that may have fixed these.

I will close this issue, but if you are still encountering problems, please let us know how we can reproduce the issue. Thanks!
