### ISSUE TITLE
theme.js is broken

### ISSUE THREAD

**Issue by ajsantander** [TypeStrong/typedoc#382]
theme.js is not being called anymore, this is a feature that is currently not working:
https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/theme.ts#L47

Some themes require theme.js to be executed for proper functioning, and there are several themes out there than rely on this.

Eg.
https://github.com/kimamula/typedoc-markdown-theme
https://github.com/alg/typedoc-dash-theme

I can verify that theme.js was being used in typedoc v0.3.12 but not anymore shortly after that.

Is this feature still available?

**Comment by thepalebluedot** [comment]
For anyone interested, I found a workaround by using the typedoc API and warpping it in a node script: 
https://github.com/thepalebluedot/typedoc-md-theme

**Comment by cpriest** [comment]
@ajsantander  The link you have posted above is no longer any good, do you still have the workaround?  I'm also running into this issue.

**Comment by aciccarello** [comment]
Looks like this was caused by #252. PRs are welcome.

**Comment by blakeembrey** [comment]
@aciccarello That PR shouldn't have changed the behaviour, it was already commented out and both code paths are identical as a result. It seems this behaviour was changed before (maybe before I was involved) so I can't be sure why/when it was changed. Feel free to link me if there's something I've missed though.

**Comment by aciccarello** [comment]
@blakeembrey I believe you are correct. It appears that it was caused by prior changes that were the issue but that code was [commented out more than a year and a half ago](https://github.com/TypeStrong/typedoc/commit/fa7ebeb9ba3792a7083351a5a717e500d37f85d6#diff-63fbf19d888caafafd72e21f29cb1f4d). I dug up #246  and #237 which were prior to #252. But regardless of when it was removed we should align the features and the documentation.

**Comment by blakeembrey** [comment]
Thanks for the investigation work 😄 Is this the best way to enable the needed features or is there something people would prefer? I'm not really familiar with it, but since it was removed so long ago if there's a better fix maybe we can do that.

**Comment by aciccarello** [comment]
I'm trying to get a handle on the motivation for theme.js. Looking at the related issues:

- #246 found a work around by configuring handlebars
- @cpriest (per gitter conversation) is looking to change the results of `getNavigation()`
- #237 was focused on generating documentation in a single page (not sure how that's different than the minimal theme)

**Comment by bbugh** [comment]
This is still a problem. My `theme.js` is not being loaded. Is there some other way to add JavaScript and/or Handlebars helpers?

**Comment by Gerrit0** [comment]
For Handlebars helpers, see #154. I haven't even looked at the theme.js code, so I'll need to do a bit of research before I can answer that... it looks like #504 should have fixed this.
