### ISSUE TITLE
Typescript 2+ rootDirs unsupported

### ISSUE THREAD

**Issue by nakedcity** [TypeStrong/typedoc#386]
Error: Unknown option `rootDirs.0`.
Error: Unknown option `rootDirs.1`.
Error: Unknown option `rootDirs.2`.

**Comment by nakedcity** [comment]
Any update on this one??

**Comment by aciccarello** [comment]
@nakedcity This project is currently updated mainly through external PRs. If you would like to submit a fix I'm sure it would be greatly appreciated.

**Comment by Gerrit0** [comment]
This seems to be supported now, we don't ignore it when loading in the config. I think we can support any ts options.

The error previously was likely caused by TypeDoc being on an older version of TS that didn't support the rootDirs option.
