### ISSUE TITLE
entry point restricting class member documentation

### ISSUE THREAD

**Issue by datamadic** [TypeStrong/typedoc#388]
I believe this is similar to both [issue 186](https://github.com/TypeStrong/typedoc/issues/186) and [issue 172](https://github.com/TypeStrong/typedoc/issues/172) but it may warrant a ticket itself.

My goal is to generate docs for a library with a single entry point that documents the public methods and properties (from the root's perspective) while excluding modules that may be used internally. 

For example (in the snippet below) if `Main` is to be my entry point I would want `thing1` in the Properties section of `Main`'s generated documentation to be a link to the `Thing1` class. This is the case if I generate the docs without the `entryPoint` flag. The issue is that the unwanted `Thing2` is also documented (even with `--excludePrivate` it ends up in the `Externals` section). If I generate with with the `entryPoint` flag the `Thing1` link in the Properties section just becomes a link back to the main page. 

Is there some combo of flags / settings that I am overlooking that allows me to have docs generated from an entry point's perspective allowing links to properties without documenting all Externals? Apologies for taking your time if this is already possible! 

[An example repo](https://github.com/datamadic/typedoc-issue-example)

````ts
// main.ts
import Thing1 from "./thing1";
import Thing2 from "./thing2";

export default class Main {
    thing1: Thing1;

    constructor() {

        // used internally, no need to document this
        let other = new Thing2();

        // this is user facing, should be documented
        this.thing1 = new Thing1();
    }
}
````

````ts
// Thing1.ts
export default class Thing1 {
    pub() {
        console.log('thats public');
    }
    private prv() {
        console.log('thats private');
    }
}
````

````ts
// Thing2.ts
export default class Thing2 {
    fn() {
        console.log('so hidden');
    }
}
````

**Comment by aciccarello** [comment]
Would adding a comment with `@hidden` to the `Thing2` class and using the `--stripInternal` flag help? (see #62, #104, #198, and #364 for some info since I'm not sure where it's documented)

```Typescript
/**
 * @hidden
 */
export default class Thing2 {
    fn() {
        console.log('so hidden');
    }
}
```

**Comment by datamadic** [comment]
Thanks for following up!

After looking through the tickets and trying different combos of `@hidden`, `@internal`, and `--stripInternal` I have still not been able end up where the `thing1` link works without the `thing2` link showing up. I tried `@hidden` at both the module and instance level. It looks like the `@hidden` tag will keep `thing2` from being in the content section but not the menu section (again, unless I have just not used the correct flag configurations...) For example:

![screen shot 2017-01-19 at 2 21 30 pm](https://cloud.githubusercontent.com/assets/4810751/22121562/9995eaa4-de52-11e6-9175-62817369338f.png)

Notice that the content section is empty (the menu renders all the way to the left) Then when it correctly documents `thing1` all is well: 

![screen shot 2017-01-19 at 2 21 55 pm](https://cloud.githubusercontent.com/assets/4810751/22121754/2ddaa4a2-de53-11e6-88e6-3b3d338ba7b7.png)


These particular screen shots were form docs generated with the following (though I tried many combos with internal and in the Main module as well):
`typedoc  --out docs-all src --readme none  --mode modules --stripInternal --excludePrivate`
````ts
/**
  * @hidden
  */
export default class Thing2 {

    /**
     * @hidden
     */
    fn() {
        console.log('so hidden');
    }
}
````
Is there perhaps something that I am missing? 

Thanks again for taking a look!

**Comment by aciccarello** [comment]
Related to #250

**Comment by vekexasia** [comment]
would be nice to have such behavior :)

**Comment by Gerrit0** [comment]
Closing in favor of #639
