### ISSUE TITLE
Error: Invalid value for option "module".

### ISSUE THREAD

**Issue by ShiMeiWo** [TypeStrong/typedoc#390]
When I update typedoc to 0.5.5 and execute command-line:
```
typedoc --mode modules --module commonjs --target ES5 --out ./document ./src/scripts
```
Then, I got the messages:
```
Error: Invalid value for option "module".
Error: Invalid value for option "target".
```
I received no errors before I updated.
Would you mind to check this issue?

**Comment by aciccarello** [comment]
@ShiMeiWo, what version were you updating from?

**Comment by ShiMeiWo** [comment]
I don't remember the version for certain, v0.5.3 or v0.5.4, maybe.

**Comment by aciccarello** [comment]
I wonder if this is related to #373. Something about how those two options are being passed it does not like. Before v0.5.4 it ignored the command line options if they were in the tsconfig.json.

Do you have the `module` and `target` options set in a tsconfig.json? If so you don't need them in the command line.

**Comment by ShiMeiWo** [comment]
> Do you have the module and target options set in a tsconfig.json? If so you don't need them in the command line.

my tsconfig.json is:
```
{
  "compilerOptions": {
    "sourceMap": true, 
    "target": "ES5", 
    "outDir": "chunk", 
    "module": "commonjs",
    "lib": ["es6", "dom", "ES2015"],
    "baseUrl": ".",
    "paths": {
      "*": [
        "src/scripts/lib/*",
        "src/scripts/*"
      ]
    },
    "declaration": false,
    "locale": "ja-JP",
    "experimentalDecorators": true,
    "traceResolution": true,
    "noImplicitAny": false,
    "removeComments": false
  },
  "include": [
    "./src/scripts/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```
and I've tried just now:
`typedoc --mode file --out ./document ./src/scripts`
but I received same error messages:
```
Error: Invalid value for option "target".
Error: Invalid value for option "module".
```

**Comment by ShiMeiWo** [comment]
<self follow-up report>

I re-installed TypeScript some times, the issues seemed to be fixed few times. I wondered why and checked package.jsons in my workspace and /node_modules/typedoc. And I got some knowledges:

- When the version of TypeScript in /node_modules/typedoc/package.json is "2.1.5" and run typedoc, the issues never happen.
- When I update that version to "^2.2.0-devYYYYMMDD"(to use Fetch API), the issues happen.
- Even there is difference between my workspace's TypeScript version and TypeDoc's TypeScript version, it causes no critical issues.

So, I decided to not update TypeScript version in TypeDoc for the present.
And please note that updating TS 2.2 may cause similar issue.

Thanks a lot, @aciccarello !

**Comment by aciccarello** [comment]
Updating the version of TypeScript used by TypeDoc often causes problems because TypeDoc is dependent on TypeScript apis that may have breaking changes between minor versions.

As always, PRs to add support for new TypeScript versions are welcome!
