### ISSUE TITLE
Generating github links without git

### ISSUE THREAD

**Issue by jmlopez-rod** [TypeStrong/typedoc#394]
Is there a way to generate links to Github without having the repository? Say I download a zip file of the project and try to generate the documentation. We know the github url from the package.json

```
  "repository": {
    "type": "git",
    "url": "git://github.com/TypeStrong/TypeDoc.git"
  },
```

The generated docs may not be in sync since the code will not know what branch its supposed to look at. We could by default just make it point to master. Docs and code may be out of sync but that's a risk we are willing to take. To avoid this we could add another field to package.json specifying the branch name or commit to point it to or maybe an option in the command line.

Our internal doc generation involves using docker and we no longer have the repo when we make the docs and so all the links pointing to Github are not generated.

**Comment by aciccarello** [comment]
Related to (but different from) #129

**Comment by jmlopez-rod** [comment]
@aciccarello indeed, the other issue would solve this. Thanks.

**Comment by gdelmas** [comment]
i had the same issue and created a plugin [typedoc-plugin-sourcefile-url](https://github.com/gdelmas/typedoc-plugin-sourcefile-url)

the plugin allows to create custom URLs to source code files.

it can be simply installed with:

    npm install --save-dev typedoc-plugin-sourcefile-url
