### ISSUE TITLE
[BUG] properties being included in class in error due to same name for another class

### ISSUE THREAD

**Issue by zpydee** [TypeStrong/typedoc#397]
I'm currently working in an Angular 2 project and have experienced a situation where properties from a class in one module are being included in docs for a class in another module due to the classes having the same name.

note the two paths:
- `Defined in app/features/main/core-features/user-settings/reset-password/reset-password.component.ts:11`
- `Defined in app/features/auth/reset-password/reset-password.component.ts:48`

and a screenshot from docs:

<img width="954" alt="screen shot 2017-01-29 at 4 48 39 pm" src="https://cloud.githubusercontent.com/assets/6129162/22404926/57593436-e643-11e6-9042-07a84f18c006.png">

I'm busy working in `/app/features/auth/`. the properties `showForm` and `user` should not be included in docs for the class being documented...

**Comment by zpydee** [comment]
using version `0.5.5`

**Comment by zpydee** [comment]
SUGGESTION: typedoc should look at file path when determining distinct classes

**Comment by aciccarello** [comment]
@zpydee Please also include the configuration you are using to run typedoc. Classes are shown differently for different modes.

**Comment by Gerrit0** [comment]
It looks like you are using `--mode file`, in which case TypeDoc treats all files as global and will try to merge declarations with the same name. You should be using `--mode moduels`
