### ISSUE TITLE
Installing typedoc via npm installs @types/node

### ISSUE THREAD

**Issue by dieseldjango** [TypeStrong/typedoc#408]
Typedoc has a dependency on @types/fs-extra, which has a dependency on @types/node. Unfortunately, installing @types/node into node_modules in a react-native typescript project creates global type definition conflicts. This is preventing me from installing typedoc as a local package dependency.

**Comment by blakeembrey** [comment]
Yeah, it's shitty but nothing this repo can or should fix. Just correct your `tsconfig.json` file and search existing issues first.
