### ISSUE TITLE
typedoc is not recognizing defined modules from node_modules/@types

### ISSUE THREAD

**Issue by bdun94** [TypeStrong/typedoc#413]
I am currently using the following command:
 `typedoc --out doc --includeDeclarations --mode file node_modules/@types src` 

however when I run this command none of the declarations from `node_modules/@types` seem to be getting recognized and I fail the typescript compilation

**Comment by zanona** [comment]
I have a similar use case. I would like to generate documentation for some of the project modules like `firebase-functions` it would be nice to allow me reading it through in an easy to understand manner via the generated documentation.

By any chance is there any way to include one or more packages in the generated documentation?
`typedoc --out docs --include-modules firebase-functions firebase-admin moment`

Thanks in advance.
