### ISSUE TITLE
TypeScript 2.2 OptionDeclaration#type is now Map

### ISSUE THREAD

**Issue by shlomiassaf** [TypeStrong/typedoc#414]
TypeScript 2.2 use `Map` instead of `Object` in OptionDeclaration#type (and maybe other places)

I created this patch

https://github.com/shlomiassaf/typedoc/commit/d6557609eaeabb2522bc79c74e6a58c511a867b5

I can't PR it since I did it live on GitHub...
The `map` property in `OptionDeclaration` is public so it is probably used in other locations and it needs to be `Object | Map` or if taking the easy way `any`

i'm new to this project so I can't really decide on those, it looks like some sort of refactoring is needed.

**Comment by shlomiassaf** [comment]
I think a group issue should be opened for 2.2 migration, aggregate all open problems...

**Comment by aciccarello** [comment]
Hi @shlomiassaf. Thanks for the report and suggested fix. I created PR #417 from your patch branch so that your fix can be reviewed. I've also created a TypeScript 2.2 project for aggregating issues specific to that version.

**Comment by aciccarello** [comment]
I think this was supposed to be closed with #448
