### ISSUE TITLE
Moving @types from dependencies to dev dependencies

### ISSUE THREAD

**Issue by johnman** [TypeStrong/typedoc#418]
Hi,

Is it required to have @types in the dependencies of package.json?

Some npm servers do not support @types and this means that it prevents typedoc from being downloaded. As they seem to be types used by typedoc itself is it o.k. to move them to dev dependencies so the npm client doesn't try to down load them when installing typedoc?

Thanks,

John

**Comment by blakeembrey** [comment]
Please search existing issues before opening a new one.

**Comment by johnman** [comment]
Hi, was 413 the duplicate you mentioned? I checked through them all and that was the closest one although that was talking about an @types issue when trying to use typedoc, my one was a question related to trying to install typedoc and if the @types listed in the dependencies were just dev dependencies and if so would there be an issue moving them to the dev dependencies of package.json. If the move has no impact on the project but helps out enterprises (even if it is a small %) I thought it would be helpful to suggest it. Thanks

**Comment by blakeembrey** [comment]
It impacts the project because anyone using it from TypeScript would no longer be able to without manually going through the Typedoc dependency list and installing the `@types` dependencies themselves.

**Comment by blakeembrey** [comment]
To find duplicates, you should search through closed issues also. For instance, there's https://github.com/TypeStrong/typedoc/issues/408 which you can follow along.
