### ISSUE TITLE
Cannot find name 'require'.

### ISSUE THREAD

**Issue by IRus** [TypeStrong/typedoc#424]
Hi, I'm trying to use typedoc in my project, and i use `require` a lot, i have typedefs for require (`@types/webpack-env`) and this works perfectly, but typedoc for some reason doesn't see this defs, and i got errors:

```
 Cannot find name 'require
```

any tips? (i use both cli and webpack-plugin)

```
    "typedoc": "^0.5.5",
    "typedoc-webpack-plugin": "^1.1.3",
```

**Comment by jason0x43** [comment]
Make sure you're using at least typedoc 0.5.6; 0.5.5 had an issue that prevented it from automatically loading things in @types. If you're on 0.5.6 and still seeing the issue, try explicitly including the index.d.ts file from @types/webpack-env in your tsconfig (not ideal, but it might indicate that automatic type loading is still broken in some cases).

**Comment by IRus** [comment]
My bad, i updated to 0.5.6 and now issue gone, thanks!
