### ISSUE TITLE
Interface doesn't work with import or reference

### ISSUE THREAD

**Issue by WahlbergRu** [TypeStrong/typedoc#428]
Hello. I use 

`
import {ICallbackRow, IwidgetSettings, Iinvoke} from "./types";
`

or 

`
/// <reference path="./types.d.ts"/>
`

but this doesn't compile in documentation. 

But if I copy interface in file, then interface compile working. 

Where I have error?

**Comment by aciccarello** [comment]
Hello @WahlbergRu, what version of typedoc are you using?
