### ISSUE TITLE
Import aliases don't work

### ISSUE THREAD

**Issue by asakusuma** [TypeStrong/typedoc#435]
```JavaScript
import { Foo as MyType } from './foo';
export function bar(foo: MyType) {}
```

The docs don't recognize that `foo` is an instance of `Foo`. There is no link from `MyType` to `Foo`, and if you export the docs as JSON, the parameter `foo` is missing the reference id, unlike parameters who's types are not an alias.

**Comment by aciccarello** [comment]
Thanks for the report! I wonder if this is at all related to #393 since it involves renaming symbols.
