### ISSUE TITLE
Error: Option 'sourceRoot can only be used when either option '--inlineSourceMap' or option '--sourceMap' is provided

### ISSUE THREAD

**Issue by ChrisPearce** [TypeStrong/typedoc#438]
TypeDoc is displaying the following error:
Error: Option 'sourceRoot can only be used when either option '--inlineSourceMap' or option '--sourceMap' is provided.

The CLI command I'm using to execute TypeDoc is 
`typedoc --out ./typedoc-output ./`

My TypeScript project contains a tsconfig.json file in the root of the project containing the following:
{
    "compilerOptions": {
        "target": "es2015",
        "module": "commonjs",
        "sourceMap": true,
        "declaration": true,
        "strictNullChecks": true,
        "sourceRoot": "./"
    },

**Comment by borysn** [comment]
I'm confused about the status of this

**Comment by borysn** [comment]
also, is typedoc just broken? how do i get around this?

**Comment by dmdm** [comment]
As a workaround I have added 'sourceMap: true" 
```
        this.compilerOptions = {
            target: ts.ScriptTarget.ES3,
            module: ts.ModuleKind.None,
            sourceMap: true,
        };
```
in file node_modules/typedoc/dist/lib/utils/options/options.js

**Comment by dolanmiu** [comment]
What is the status of this bug?

I can reproduce this on `0.9.0` and can fix it with @dmdm's suggestion

But obviously this is not ideal

**Comment by dkent600** [comment]
The workaround is not acceptable. The bug is happening to me too.  Using TypeDoc version 0.10.0

**Comment by dkent600** [comment]
I find that if I pass `--ignoreCompilerErrors` then it ignores this compiler error.  But I'm not sure what other implications there might be.

**Comment by FibreFoX** [comment]
This bug still is present using TypeDoc `0.11.1` running on TypeScript `2.7.2` having this configuration inside my `tsconfig.json`:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es2017", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "sourceRoot": "src"
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

Executing with the `--ignoreCompilerErrors` argument (by just calling `typedoc --out .\doc --ignoreCompilerErrors`) created some output, but still prompted that warning-essage.

Is this bug anything important? Can this be ignored safely?

**Comment by jebarjonet** [comment]
This is still happening to me too in the exact same case
