### ISSUE TITLE
Fat arrow function as property param problem

### ISSUE THREAD

**Issue by Spiralis** [TypeStrong/typedoc#442]
First of all, thanks for a great project 👍.

I have a situation were I cannot seem to be able to figure out how to get the parameters for a fat arrow function to be reported correctly:

```
export class AuthenticationSettings {
    /**
     * A notifier method to call whenever the lookup results have been received.
     * @param authToken - The lookup results.
     */
    public cbSuccess: (authToken: string) => void = undefined;
    //...
}
```

The documentation generated is as follows:
![image](https://cloud.githubusercontent.com/assets/64342/23663233/474a765a-0352-11e7-8762-5b7d33b7d1cb.png)

As you can see the comment for the param is not written as a part of the type declaration, as expected. 

I have tried to create the type separately (outside the class):
```
/**
 * A notifier method to call whenever the lookup results have been received.
 * @param authToken - The lookup results.
 */
type CallbackSuccess = cbSuccess: (authToken: string) => void;
```
But, that did not help neither. The generated CallbackSuccess documentation has the same issue with non-matching params. 

I have searched the issues and docs and found no information on how to do this or whether there has been others who has had this problem earlier. 

Anyone know how to get this done?

I am using typedoc 0.5.7 btw.

**Comment by raveclassic** [comment]
Any considerations?

**Comment by Gerrit0** [comment]
In 0.21, this renders as:

![image](https://user-images.githubusercontent.com/19329837/122498906-2ad7a700-cfad-11eb-882e-bc94a30f60b1.png)
