### ISSUE TITLE
TypeDoc -v or --version does not output the version of TypeDoc

### ISSUE THREAD

**Issue by KevinFernandes** [TypeStrong/typedoc#443]
If I specify the -v or --version option I expect to see the version of TypeDoc, instead I see

TypeDoc {{ VERSION }}

My npm installed version of TypeDoc is 0.5.9

**Comment by aciccarello** [comment]
Related to #402

**Comment by blakeembrey** [comment]
I'm going to close it as a duplicate, it looks like it's the same issue. Will be fixed in the next release.
