### ISSUE TITLE
Problem handling `export = xyz;` in ambient declaration modules.

### ISSUE THREAD

**Issue by phreed** [TypeStrong/typedoc#447]
I am using `typedoc` to generate documentation using ambient declarations for a javascript project.
The specific entry looks like this...

    declare module "plugin/PluginBase" {
        export = GmePlugin.PluginBase;
    }

The documentation shows the module...
![image](https://cloud.githubusercontent.com/assets/211644/23815340/66a74412-05ad-11e7-93ae-5073e043f04b.png)
But it does not produce anything of interest...
![image](https://cloud.githubusercontent.com/assets/211644/23815386/9a15d8ea-05ad-11e7-89b6-e63581a6a92b.png)
The object of the `export =` does get generated properly...
![image](https://cloud.githubusercontent.com/assets/211644/23815444/deb7c5a8-05ad-11e7-8b4a-7d988db27db8.png)

**Comment by makepanic** [comment]
I can confirm that this is still an issue with `typedoc@0.8.0`.

If i `export default function(){}`, the function gets documented. 
If i `export = function(){}`, typedoc doesn't document the function.

[These kinds of exports](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) are useful for CommonJS and AMD projects
