### ISSUE TITLE
Expression of the method overloading is broken.

### ISSUE THREAD

**Issue by samchon** [TypeStrong/typedoc#453]
Since when, expression of the **method overriding** is broken like the below screenshot.

![method_overloading](https://cloud.githubusercontent.com/assets/13158709/24148986/5c1d2810-0e84-11e7-8f65-e5406d5810ad.png)

  - http://samchon.github.io/tstl/api/classes/std.treemap.html#extract
  - https://github.com/samchon/tstl/blob/master/src/std/base/UniqueMap.ts#L361-L394

**Comment by aciccarello** [comment]
Thanks for the bug report. This might be an issue with our theme rather than the docs parsing.

**Comment by mray19027** [comment]
Anyone find a fix for this?

**Comment by mray19027** [comment]
@samchon - PR submitted to fix this problem:
https://github.com/TypeStrong/typedoc-default-themes/pull/49
