### ISSUE TITLE
Add source-code inline

### ISSUE THREAD

**Issue by bryanrideshark** [TypeStrong/typedoc#46]
How much work would be required to add the source-code as optional output in the module? It would make the generated HTML a lot more beneficial for what we're doing in house...

If it's not too much work, I might try my hand at adding that support,

**Comment by sebastian-lenz** [comment]
Hi Bryan, nice to hear from you. TypeDoc uses the TypeScript compiler to extract documentation data from the source files, the compiler metadata also contains the position and length of declarations in the source files. I did a quick test and it seems pretty straight forward. However, this data is pretty "dirty", the compiler sees the beginning of a declaration right after the end of the previous one, the snippet often contains undesired brackets, newlines and comments.

We are currently working on version 0.2 of TypeDoc which will introduce support for TypeScript 1.1/1.3. I'll check back on this feature after 0.2 release.

**Comment by Chowarmaan** [comment]
:+1:

**Comment by aciccarello** [comment]
For github projects TypeDoc supports linking to source code. If you want additional code snippets in documentation, the simplest option is to use code fences.

```typescript
/**
 * The below will be a block of code
 * ```typescript
 * function toBeDocumented() {
 *   return Math.random();
 * }
 * ```
 */
function toBeDocumented() {
  return Math.random();
}
```

I don't anticipate this being added to TypeDoc anytime so l so I will close the issue. If someone is looking for this feature, I would suggest looking into creating a plugin. If you are successful, please share.

**Comment by Luca-spopo** [comment]
This would be very useful for (sort of) literate programming and writing specifications-as-tests

**Comment by tgreyuk** [comment]
FYI https://www.npmjs.com/package/typedoc-plugin-inline-sources
