### ISSUE TITLE
typedoc.io domain resolves to parked page.

### ISSUE THREAD

**Issue by jj4th** [TypeStrong/typedoc#460]
http://typedoc.org/api/ Refers to: http://typedoc.io/themes/default as a theme preview, however the typedoc.io domain appears to target a domain parked page.

**Comment by aciccarello** [comment]
Oops. Looks like we missed that in #270 

This is related to TypeStrong/typedoc-site#1

**Comment by aciccarello** [comment]
The api docs have been regenerated so there should be no more references to typedoc.io
