### ISSUE TITLE
How to exclude multiple patterns

### ISSUE THREAD

**Issue by taffeldt** [TypeStrong/typedoc#477]
I use Typedoc for my Angular 2 project.
I am trying to prevent Typedoc from reading out the folder dist/ where I store my compiled .js files (as well as some other stuff that makes Typescript crash) but I would also like to exclude the folder e2e/ as well as all files that end on .spec.ts
I understand the flag --exclude is being used for that and that it makes use of the Glob pattern.
My pattern would be ./dist/** ./e2e/** and */**.spec.ts
I tried `--exclude {./dist/*/**,./e2e/**,./client/test.ts,*/**.spec.ts}`
as well as `--exclude ./dist/** --exclude ./e2e/** --exclude  */**.spec.ts`
In case 1 the program doesn't exclude anything, in case 2 only one of them.

So I am wondering how I am supposed to do this and would highly appreciate some help.
I think #475 might be related (as in it was supposed because the author had the same problem).

**Comment by aciccarello** [comment]
There are some comments on #170 that should be helpful. TypeDoc uses minmatch globs. PRs to improve the docs are always appreciated.

**Comment by mend3** [comment]
exclude "sql" and "utils" under dir "packages/libs/"
`typedoc --exclude './packages/libs/[(sql|utils)]*'`

with monorepo
all BUT "sql" and "utils"
`typedoc --entryPointStrategy packages './packages/libs/[!(mssql|utils)]*'`

working fine for me

![image](https://user-images.githubusercontent.com/1450229/143616694-9bf39e52-e5ac-40f1-bbad-70ec5f6a0c08.png)
