### ISSUE TITLE
Support typedoc.json "extends"

### ISSUE THREAD

**Issue by DennisJaamann** [TypeStrong/typedoc#493]
Add support for creating extended typedoc.json files. 

This functionality already exists for:
- TypeScript configs
- TsLint configs

So why not do the same for typedoc when we want for example a company wide configuration for typedocs with the same theme etc preconfigured.

Example:

_**node_modules/@somecompany/somelib/typedoc.json**_
```
{
  "mode": "file",
  "module": "commonjs",
  "theme": "default",
  "out": "docs",
  "target": "ES5",
  "moduleResolution": "node",
  "includeDeclarations":"false",
  "ignoreCompilerErrors": "true",
  "experimentalDecorators": "true",
  "externalPattern":"**/*.d.ts",
  "excludeExternals":"true",
  "emitDecoratorMetadata": "true",
  "preserveConstEnums": "true",
  "stripInternal": "true",
  "suppressExcessPropertyErrors": "true",
  "suppressImplicitAnyIndexErrors": "true"
}
```

**_someprojectusingsomelib/typedoc.json_**
```
{
  "extends": "@somecompany/somelib/typedoc.json"
}
```
**_Currently, there is a way of achieving this but it feels rather cumbersome / not community standard in comparison with tools such as typescript or tslint._**

```
 "scripts": {
    "docs": "npm run typedoc -- --options node_modules/@somecompany/somelib/typedoc.json ./src/",
    "typedoc": "typedoc"
  },
```

**Comment by aciccarello** [comment]
Cool idea. PRs welcome.
