### ISSUE TITLE
Error: [object Object]

### ISSUE THREAD

**Issue by StephanBijzitter** [TypeStrong/typedoc#495]
```
Stephans-MacBook-Pro:{company project redacted} stephanbijzitter$ typedoc --mode modules --out typedoc/ source/canvas/api/

TypeDoc 0.6.0
Using TypeScript 2.2.2 from /Users/stephanbijzitter/.config/yarn/global/node_modules/typescript/lib
Error: [object Object]
Error: [object Object]
```
Wish I could give you more information, but this is not really allowing me to give you more information.

**Comment by aciccarello** [comment]
@StephanBijzitter Do you have a github repo that reproduces the issue?

**Comment by StephanBijzitter** [comment]
Part of a company codebase, but I can probably whip something up tomorrow

**Comment by StephanBijzitter** [comment]
Took a bit longer to find the time, but I don't think a github repo will be needed.

```bash
mkdir test
mkdir typedoc
touch test/IColorable.ts
```
Make sure the file has the following content:
```typescript
export interface IColorable {

    getColor(): string;
    setColor(color: string): void;
}
```
Then run the following:
```bash
typedoc --mode modules --target es6 --out ./typedoc ./test
```
Tested with different targets (or no target) and with different waysof providing the paths, to no avail.

**Comment by StephanBijzitter** [comment]
Right, found out what is going on.

Somewhere else in a subdirectory of the same parent directory, I have a file which is plain javascript, but used by the typescript code. The compiler tries to compile the .js file and emits an error saying it cannot compile a .js file because it would override the input .js file.

When running typedoc, it seems the error from the typescript compiler propagates correctly but is not logged correctly and gets mangled to the error you see in the opening post. 

Changing that .js file into a .ts file fixed it all for me.

**Comment by flaviut** [comment]
I think this should be re-opened—even if you've figured out the problem. Printing something like `Error: [object Object]` is definitely a bug.

**Comment by StephanBijzitter** [comment]
Yeah that makes sense.

**Comment by aciccarello** [comment]
@flaviut That's true. PRs are certainly welcome.

**Comment by AJStacy** [comment]
I'm having this issue as well.

**Comment by flaviut** [comment]
I'm currently unable to reproduce with @StephanBijzitter's example with 0.8.0 (and I forgot how I ran across this issue), but at some point I grabbed a stack trace. I'm having trouble making use of it, but here it is:

    at ConsoleLogger.log (/home/user/dev/myproject/node_modules/typedoc/dist/lib/utils/loggers.js:124:11)
    at ConsoleLogger.Logger.diagnostic (/home/user/dev/myproject/node_modules/typedoc/dist/lib/utils/loggers.js:99:22)
    at /home/user/dev/myproject/node_modules/typedoc/dist/lib/utils/loggers.js:84:19
    at Array.forEach (native)
    at ConsoleLogger.Logger.diagnostics (/home/user/dev/myproject/node_modules/typedoc/dist/lib/utils/loggers.js:83:21)
    at CliApplication.Application.convert (/home/user/dev/myproject/node_modules/typedoc/dist/lib/application.js:80:25)
    at CliApplication.bootstrap (/home/user/dev/myproject/node_modules/typedoc/dist/lib/cli.js:59:32)
    at CliApplication.Application [as constructor] (/home/user/dev/myproject/node_modules/typedoc/dist/lib/application.js:39:15)
    at new CliApplication (/home/user/dev/myproject/node_modules/typedoc/dist/lib/cli.js:35:42)
    at Object.<anonymous> (/home/user/dev/myproject/node_modules/typedoc/bin/typedoc:4:1)

@AJStacy Are you still able to reproduce this bug?

**Comment by arusahni** [comment]
I'm still seeing this error - with the same cause @StephanBijzitter found (a JS file being processed by the TS compiler). Filing a PR with a fix now.
