### ISSUE TITLE
check illegal or empty comments

### ISSUE THREAD

**Issue by kaibadash** [TypeStrong/typedoc#50]
Can we check illegal or empty comments?
thank you.

**Comment by sebastian-lenz** [comment]
Hi kaibadash. Can you please clarify your problem or provide some example code?

**Comment by kaibadash** [comment]
```typescript
module Module {
    /** 
     * Sample Code 
     */
    export class Calc {
        // Sample1: empty comment.
        public mul(n1: number, n2: number): number {
            return n1 * n2;
        }

        /**
         * Sample2: lack of param and return.
         * @param n1 number 1
         */
        public sum(n1: number, n2: number): number {
            return n1 + n2;
        }

        /**
         * Sample3: illegal params.
         * @param hoge1 hoge1
         * @param hoge2 hoge2
         * @param hoge3 hoge3
         * @return result
         */
        public div(n1: number, n2: number): number {
            return n1 / n2;
        }
    }
}
```

Here is example code.
I want to recieve warnings.

**Comment by kamranayub** [comment]
Warnings for mismatched parameters would be excellent (w/option to fail)--so we can fix spelling issues. *Maybe* TSLint could be used to do this, not sure. Another style-check would be the option to force comments for public members.

**Comment by fforjan** [comment]
I've started to have some code for this feature (nothing committed at the moment)
From my hack and checking Calc sample from @kaibadash, I've got a plugin which can easily detect empty comments. Missing return statement should be too. 
Invalid params is a bit more difficult.

**Comment by fforjan** [comment]
My code is here for the moment, https://github.com/fforjan/typedoc/blob/CommentChecker/src/td/output/plugins/CommentCheckerPlugin.ts

And this is the result from @kaibadash sample:

Warning: kaibadash-github.ts(1,14) : Element 'Module' does not have comment.
Warning: kaibadash-github.ts(26,19) :Parameter 'n1' does not have comment.
Warning: kaibadash-github.ts(26,19) : Parameter 'n2' does not have comment.
Warning: kaibadash-github.ts(7,19) : Element 'mul' does not have comment.
Warning: kaibadash-github.ts(15,19) : Parameter 'n2' does not have comment.

I have no idea at the moment why my code is not catching the div related issues

**Comment by sebastian-lenz** [comment]
That's a great starting point!

You are currently listening to the renderer, I think it would make more sense to attach your events to the converter. The converter offers the resolve event which will be dispatched for every reflection of the project, see http://typedoc.io/api/classes/td.converter.converter.html#event_resolve.

I've created a basic example for a plugin, see https://github.com/sebastian-lenz/typedoc-plugin-template. As we are in the process of moving to TypeScript 1.5, the template already requires the latest version of TypeScript.

You can create a fork of the template on your user's namespace or if you like to I can create a repository within the TypeDoc namespace and invite you.

**Comment by fforjan** [comment]
I will create a fork of the template and move my code into it ;)
I might need to push for minor changes to your main branch - Logger should be also counting warnings as some of the messages are warnings and my code is counting them for testing purpose - not the best at the moment but I don't think there is any harm in that change :)
I will try to send individual push request for those little modifications so you can accept it (or not!).

BTW, I'm off to Japan for a week (business trip) leaving this Saturday so do not expect activity from me for the next 10 days.
