### ISSUE TITLE
How to not generate source file links?

### ISSUE THREAD

**Issue by jumpinjackie** [TypeStrong/typedoc#501]
Is there a setting to not have typedoc generate source file links (ie. The "Defined in `URL_to_source
_and_line_number`")?

I have no need for this feature and it results in very noisy commits whenever I run typedoc and put the output into `/docs` on `master` branch because blob URLs for referenced sources changes every time

**Comment by jonchardy** [comment]
You can do this by modifying the theme if you'd like. That's the route we took.

In the theme project, you'll want to update src/default/partials/member.declaration.hbs and src/default/partials/member.signature.body.hbs. See the following commit: [Don't include source information](https://github.com/jonchardy/typedoc-default-themes/commit/0859be1f0e1e424905ac79765fceb9fcd9d9ad87).

**Comment by Gerrit0** [comment]
Closing in favor of #808 as it seems to have more visibility.

**Comment by crhistianramirez** [comment]
A middleground option that allows you to keep defined in bug generates a less noisy output is to just the filename and line in `src/default/partials/member.declaration.hbs`

```html
<li>Defined in {{fileName}}:{{line}}</li>
```

It would be even nicer if there was a feature that generated the link from the master branch *instead* of from the unique commit. That way it would only generate changes if the file structure changed and unless you were keeping multiple versions of documentation it would just work.

**Comment by Gerrit0** [comment]
You can specify `--gitRevision` to tell TypeDoc what to use instead of the current ish.
