### ISSUE TITLE
@private does not respect --excludePrivate

### ISSUE THREAD

**Issue by crazyfx1** [TypeStrong/typedoc#506]
If you use @ private, the member is still visible even though --excludePrivate was set to true. The member was only marked as private in the documentation.

**Comment by aciccarello** [comment]
Related to #62 and #25. Since we don't have good docs on those features I'd have to experiment with it to know exactly what the `@private` and `@hidden` tags are supposed to do.

**Comment by wbhob** [comment]
They are supposed to fully exclude the property/function/thing from the docs to be invisible to the consumer.

**Comment by dupski** [comment]
For anyone else that stumbles across this with the same problem, the `--excludePrivate` flag currently only works for **private class members**. It does not work for anything else decorated with `/** @private */`.

The simplest way I've found to hide them, short of using a custom fork, is to simply add the following css:

```css
.tsd-is-private {
    display: none;
}
```

TypeDoc is awesome, but is really hard to work on. The codebase could do with a bit of sanitization (remove grunt, use ts-node to run the tests without having to build them...). I'll have a think and raise a seperate issue / PR for that.

**Comment by Gerrit0** [comment]
Fixed with 5d41a2e03a4cefa29ae84e7f9ef409d976d4ac56
