### ISSUE TITLE
Wrong handling of function declarations in TypeDoc

### ISSUE THREAD

**Issue by lord-saumagen** [TypeStrong/typedoc#508]
# Wrong handling of function declarations in TypeDoc

Pleas take a look at the following code segments:

### Class: 'ClassWithMethodDeclaration'
```TypeScript
namespace Test
{
  export class ClassWithMethodDeclaration
  {
    /**
    * @description A declaration of the 'next()' function which gets initialized during construction.
    *
    * @returns {Array<number>}
    */
    public next: () => Array<number>;

    /**
     * @constructor
    *
    * @description The default constructor of the  'Test.ClassWithMethodDeclaration' class.
     */
    constructor()
    {

      this.next = () => 
      {
        return [1, 2, 3, 4, 5];
      }

    }
  }
}
```

### Class: 'ClassWithMethodDefinition'
```TypeScript
namespace Test
{
  export class ClassWithMethodDefinition
  {
    /**
    * @constructor
    *
    * @description The default constructor of the  'Test.ClassWithMethodDefinition' class.
    */
    constructor()
    {

    }

    /**
    * @description The definition of the 'next()' function.
    *
    * @returns {Array<number>}
    */
    public next(): Array<number>
    {
      return [1, 2, 3, 4, 5]
    }
  }
}
```

Both classes are totally valid TypeScript classes and they are functional equivalent.   
The first class **'ClassWithMethodDeclaration'** has a function declaration   
```TypeScript
public next: () => Array<number>;
```
as a member. The function gets initialized in the constructor. That is a common pattern   
for functions which have dependencies to other member variables or external dependencies   
which gets supported during the constructor call. (For the sake of brevity the constructor   
in this examples doesn't support any parameters and the function is not really dependent   
on internal or external references. But it's also not important to demonstrate the problem.)   
The second class **'ClassWithMethodDefinition'** has the same function as member, but in   
this case the function gets defined in the class body.
```TypeScript
    public next(): Array<number>
    {
      return [1, 2, 3, 4, 5]
    }
```
That means, declaration an initialization are one unit.   
From an outside view those implementation details are transparent. Someone who creates   
one of these classes must not know how the **next()** function is implemented because    
it's totally irrelevant.

For that reason the documentation for the **next()** function in both classes should be   
equal. They have the same accessibility, the same call signature and return the same   
result. The only difference is that they belong to different classes.

Unfortunately there is a huge difference in the documentation which gets generated for   
this functions. The documentation for the **next()** function in the    **'ClassWithMethodDeclaration'** class looks like this:

![classwithmethoddeclaration](https://cloud.githubusercontent.com/assets/9468599/26167636/d29b3008-3b26-11e7-9881-22da5a194141.png)

* The method is declared as property
* There is a **'returns'** artefact which is normally not visible
* There is a **'Type declaration'** which is not part of the class in any way.
* The reported type is anonymous (and for that reason totally useless) and has an icon assigned which has no explanation in the legend.   

For somebody who reads that documentation it's hard or even impossible to figure out   
how the **next** member is supposed to be used.

The documentation for the **next** member of the **'ClassWithMethodDefinition'** class   
on the other hand looks the way it should look.

![classwithmethoddefinition](https://cloud.githubusercontent.com/assets/9468599/26167668/eb78ed18-3b26-11e7-92d3-47bb72a4c934.png)

* The member is declared as method
* There is no **'returns'** artefact but a proper return type declaration.
* There is no mysterious type declaration of any type.

Every programmer should be able to understand that documentation.

Since a member of a class which is declared as function before initialization is still   
a function member of the class like every other function member, the generated   
documentation shouldn't differ from other function members. Even it that's impossible   
for any reason, the documentation should at least make any sense.

The documentation was generated using   
**TypeDoc version 0.6.0** and   
**TypeScript version 2.2.2**.

You will find the whole test project attached as '*.zip' file for your convenience.
[Typedoc__Render_Error_Function_Declaration.zip](https://github.com/TypeStrong/typedoc/files/1008584/Typedoc__Render_Error_Function_Declaration.zip)

The test project was created with **'Visual Studio Community 2017 Version 15.2'**

I want to thank everybody who worked on the TypeDoc project for the excellent product. I'm looking   
forward to see the described problem resolved in one of the future releases.

Kind regards, Lord Saumagen.

**Comment by aciccarello** [comment]
Thanks for the great report @lord-saumagen. I believe that this is the same issue noted in #442.

PRs are always welcome :wink:
