### ISSUE TITLE
--entryPoint is broken for .d.ts files

### ISSUE THREAD

**Issue by mad-gooze** [TypeStrong/typedoc#511]
Hello! 

I am trying to use typedoc to generate documentation for .d.ts declaration file. I specify this file as an entry point via `--entryPoint '\"api.d\"'` like I found in [this discussion](https://github.com/TypeStrong/typedoc/issues/172#issuecomment-269879664).
I am getting this error:
```Warning: The entry point `"api.d"` could not be found.```
and `--entryPoint` option is ignored.
I've researched the sources and it looks like that `.d` suffix gets omitted here:
https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/reflections/abstract.ts#L511

Are there any fixes for my issue?

**Comment by samvv** [comment]
Did you try with `--includeDeclarations`? I've managed to get it working once before, while using this flag.

**Comment by mootari** [comment]
I managed to get it working by passing an `entryPoint` as array:
```javascript
const app = new td.Application({
  // ...
  theme: 'default',
  includeDeclarations: true,
  entryPoint: ['babylon.d.ts']
});
app.generateDocs(['babylon.d.ts'], config.target);
```

**Comment by bd82** [comment]
I think I managed to get it working use "--mode file" instead of --entryPoint
