### ISSUE TITLE
Document imported types

### ISSUE THREAD

**Issue by Gozala** [TypeStrong/typedoc#516]
Right now if I have code like this:

```ts
import {Maybe} from "maybe.ts"

export const toMaybe =
  <x, a>(result: Result<x, a>): Maybe<a> =>
    result.isOk ? result.value : null

export type Result<x, a> = ...
```

typedoc generates docs such that `Maybe<a>` is completely undocumented.

<img width="498" alt="screen shot 2017-05-25 at 12 05 55 pm" src="https://cloud.githubusercontent.com/assets/21236/26466281/0a9d1350-4143-11e7-8dc2-b9c178de98a9.png">

It would be great to have an option to either generate docs for imports as well or alternatively have a way to provide external links.

**Comment by vekexasia** [comment]
:+1: for this

**Comment by Gerrit0** [comment]
In 0.20, TypeDoc will document whatever you export. Changing the code to:

```ts
import {Maybe} from "maybe.ts"

export * as MaybeTS from "maybe.ts"

export const toMaybe =
  <x, a>(result: Result<x, a>): Maybe<a> =>
    result.isOk ? result.value : null
export type Result<x, a> = { isOk: true, value: a } | { isOk: false, err: x }
```

Will result in documentation like this, with links going where you would expect:

![image](https://user-images.githubusercontent.com/19329837/100523572-afc4b580-316e-11eb-9e3f-f6fe3c37a306.png)
