### ISSUE TITLE
Generated documentation doesn't display the content of array of objects

### ISSUE THREAD

**Issue by SofiaP** [TypeStrong/typedoc#520]
I have this example:

```typescript
interface example {
  obj: {
    property: string
  }[];
}
```

And the output of the content of 'obj' is:

![image](https://cloud.githubusercontent.com/assets/4086015/26643998/35b15cd0-462b-11e7-8151-60436c677299.png)

Is it possible to make it display the inner contents of the object array?

**Comment by aciccarello** [comment]
@SofiaP What do you imagine the output looking like? I tend to think it would be better to define the interface of that object separately so that it can be referenced independently.

**Comment by SofiaP** [comment]
If I define the obj like an interface this would work, but in some cases I don't need to reference the interface multiple times, and it would be nice to view the content of the object. If I do not use an array I will see the object, I don't understand why when I use an array of objects I can't see the object rendered,

I would expect to view the property rendered like:

obj: { property: string }[]

**Comment by kal93** [comment]
Has there been any solution or workaround for this?

**Comment by aciccarello** [comment]
@kal93 A workaround would be to define the object interface

```TypeScript
interface example {
  obj: ObjectDefinition[];
}

interface ObjectDefinition {
  property: string;
}
```

**Comment by apsheni** [comment]
It looks like something goes wrong in new releases. This example parsed by TypeDoc 0.5.10 appears like this:

**Properties**
obj: _object_ []
**Type declaration**
* property: _string_

**Comment by Gerrit0** [comment]
In recent versions of TypeDoc, we render objects more reasonably:

![image](https://user-images.githubusercontent.com/19329837/100523485-109fbe00-316e-11eb-9d72-ea023b2cd9ca.png)
