### ISSUE TITLE
Adding documentation for destructured arguments in a fat arrow function

### ISSUE THREAD

**Issue by nahushf** [TypeStrong/typedoc#522]
How do I add documentation for destructured parameters in a fat arrow function?
I have tried the following:
```
/** 
 * Some description
 * @param param1 First parameter
 * @param param2 Second parameter 
 */
export const myFunction = ({param1, param2}: {param1: string, param2: number}) => {}
```
and
```
/** 
 * Some description
 * @param __namedParameters Object description
 * @param param1 First parameter
 * @param param2 Second parameter 
 */
export const myFunction = ({param1, param2}: {param1: string, param2: number}) => {}
```
and 
```
/** 
 * Some description
 * @param __namedParameters Object description
 * @param __namedParameters.param1 First parameter
 * @param __namedParameters.param2 Second parameter 
 */
export const myFunction = ({param1, param2}: {param1: string, param2: number}) => {}
```
None of these seem to work. If the above was an ordinary function, shouldn't the first approach work according to [this](https://github.com/TypeStrong/typedoc/blob/master/examples/basic/src/typescript-1.5.ts#L22) example?

**Comment by xAlien95** [comment]
As a temporary work-around, destructured parameters in arrow functions can be documented as follows:

```ts
/** Some description */
export const myFunction = ({
  /** First parameter */
  param1,
  /** Second parameter */
  param2,
}: {
  param1: string,
  param2: number,
}) => {}
```

**Comment by rjdestigter** [comment]
This doesn't work for destructured array parameters.

**Comment by Gerrit0** [comment]
In 0.20, the first code block in the OP works as expected. producing the following:

![image](https://user-images.githubusercontent.com/19329837/103258057-ef8ae280-4950-11eb-9736-861919819a59.png)
