### ISSUE TITLE
Empty type declarations

### ISSUE THREAD

**Issue by Mikhus** [TypeStrong/typedoc#524]
Imaging I have the following type declaration

~~~typescript
/**
 * Database connection configuration data structure for a single
 * environment.
 */
export type DbEnvConfig = {
    url: string;
    dialect: string;
};
~~~

As result I get this representation in generated documentation:

~~~
DbEnvConfig
DbEnvConfig: object
Defined in index.ts:12
Database connection configuration data structure for a single environment.

Type declaration
~~~

If I will add indexes to type:

~~~typescript
/**
 * Database connection configuration data structure for a single
 * environment.
 */
export type DbEnvConfig = {
    [name: string]: string;
    url: string;
    dialect: string;
};
~~~

I would see this:

~~~
DbEnvConfig
DbEnvConfig: object
Defined in index.ts:12
Database connection configuration data structure for a single environment.

Type declaration

 - [name: string]: string
~~~

So I missing all the properties defined for a type. For me it looks like a critical bug (I dunno if is suggested to be expected behavior). In such a case documentation itself loses its meaning, as the most critical information is missing from it. Better to look on the source code then...

**Comment by aciccarello** [comment]
I suspect that it is due to missing support of `type` definitions. I assume defining this as an interface would be simple workaround until this feature is fixed.

```TypeScript
/**
 * Database connection configuration data structure for a single
 * environment.
 */
export interface DbEnvConfig {
    [name: string]: string;
    url: string;
    dialect: string;
}
```

**Comment by vekexasia** [comment]
Probably related but I get similar behavior for this:

```typescript
 putDelegates(data: { a: string, b: string, c: string[], d?: string }, callback?: cback<any>): Promise<any> {
}
```
The generated doc shows "data" as "object" not providing any hint on the allowed elements.

I could create an interface but I've hundreds of methods with different inputs. Wouldn't really be a use case for interfaces.

**Comment by aciccarello** [comment]
@vekexasia I think that is a separate issue. Per #497 it should be giving some basic info by default. If you want more details you should use an interface.

**Comment by miedmondson** [comment]
Similar experience when using `"excludeNotExported": true`:

```
export type Avatar = {
  name: string,
  hairColor: string,
  eyeColor: string,
}
```

Typedoc output:

![Type declaration with properties](https://www.dropbox.com/s/n4iso83vj47ufjn/Screenshot%202019-08-01%2017.46.10.png?dl=0)

Typedoc output with `"excludeNotExported": true`:

![Empty "Type declaration"](https://www.dropbox.com/s/jkxby4kmdps0osq/Screenshot%202019-08-01%2017.46.37.png?dl=0)

**Comment by Gerrit0** [comment]
#1103 should fix this.

**Comment by Gerrit0** [comment]
In 0.20 the alias with the index signature renders as:

![image](https://user-images.githubusercontent.com/19329837/100523425-b7378f00-316d-11eb-946a-3bfcf5d9b753.png)

This isn't entirely correct, as it's missing the index signature, but it is closer to the desired output.
