### ISSUE TITLE
'typedoc -help' output is overwhelming

### ISSUE THREAD

**Issue by BurtHarris** [TypeStrong/typedoc#526]
With all the options available, getting started can be complicated.   The help output is now so long it's not very helpful.   The vast majority of the `tsc` options seem second-priority, particularly as I handle them with a `tsconfig.json` file in most projects.    

I really don't know the tool well enough to offer a PR on this, but the current situation seems like an adoption blocker.   Perhaps instead of dumping all the options, it could launch a browser pointing to a set of wiki pages.

**Comment by samvv** [comment]
Personally, I don't think the user will like it when the browser gets kicked off, but indeed, the options could use some simplification. Problem is right now they are hard-coded everywhere in the code.

**Comment by BurtHarris** [comment]
I really like command-line spawns browser approach.   `npm help install` for example gives me just the sort of information I'm looking for.   `npm docs <packagename>` gives similar behavior.

**Comment by aciccarello** [comment]
I created a PR to reduce the number of options given in the output. If the online docs get better someone could create a separate issue to launch the browser from the CLI
