### ISSUE TITLE
What's wrong with my command line?

### ISSUE THREAD

**Issue by BurtHarris** [TypeStrong/typedoc#527]
I'm trying `typedoc --mode modules --out doc .\src\antlr4ts.ts` 

The command parser seems to be treating this as if I haven't specified any input files, but obviously I have.  **.\src\antlr4ts.ts**

**Comment by BurtHarris** [comment]
I think I've answered my own question, there must have been something wrong in my `tsconfig.json`.   I tried deleting it and got some output...

**Comment by aciccarello** [comment]
Hi @BurtHarris, we may need to look into support of the `include` option.

**Comment by mnpenner** [comment]
When I run this,

    typedoc --out docs --mode modules --module commonjs --readme none --target es6 --name jtilz ./dist/node/I_DONT_EXIST

It doesn't error out. Just completely ignores the source files I give it.

Is it overriding it in favour of my `tsconfig.json`? I'd really prefer that it didn't.

**Comment by fr0** [comment]
Is there any way to tell typedoc to only generate documentation for a specific subfolder of my project? No matter what options I give it, it seems to want to document the entire folder.

**Comment by natevoci** [comment]
I have a separate tsconfig.json file for running typedoc where I specify the folders I want included in the documentation in the include block.

```
typedoc ... --tsconfig tsconfig.docs.json
```

```
{
  "compilerOptions": {
    ...
  },
  "include": [
    "main/folder/**/*",
    "path/to/another/folder/**/*"
  ]
}
```

This works for me, but I only use the json output option. I have not tried the the html generated docs to see if it does the same thing.
