### ISSUE TITLE
--ignoreCompilerErrors is not documented in readme

### ISSUE THREAD

**Issue by ORESoftware** [TypeStrong/typedoc#531]
The option --ignoreCompilerErrors is not documented in readme, would be nice to have it. I can't remember where I discovered that option...it may have been gulp-typedoc...not sure.

**Comment by samvv** [comment]
It is documented in the CLI, when running `typedoc --help`. Maybe that's where you got it from? Still, it might be worthwhile to add all flags to the README.

**Comment by blakeembrey** [comment]
Feel free to submit a PR.
