### ISSUE TITLE
Search results can't be clicked

### ISSUE THREAD

**Issue by jonchardy** [TypeStrong/typedoc#534]
This actually happens to be a theme issue, but I figure it will get more attention here.

When using the search feature, it's possible to navigate between results and hit enter and be taken to that page. Also, on mobile devices, it's possible to touch a result and be taken to that page. Clicking a result, however, doesn't take the user to the page, which is a big problem.

I imagine this is some sort of issue with jQuery intercepting the click event before the anchor can be processed, but my knowledge in that realm is limited. Does anyone know how to fix this?

EDIT: Even more interesting, a normal-speed click doesn't work, but if the mouseup occurs the instant after mousedown (click very quickly), it correctly navigates to the search result.

The file that handles this is https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/assets/js/src/typedoc/components/Search.ts.

**Comment by pirix-gh** [comment]
@jonchardy I've fixed it in https://github.com/pirix-gh/eledoc

**Comment by aciccarello** [comment]
I believe this should be fixed on the latest version of typedoc-default-themes
