### ISSUE TITLE
using different project file other than tsconfig.json

### ISSUE THREAD

**Issue by oity** [TypeStrong/typedoc#539]
I have a project that comes with many flavour, I use different tsconfig file, es: tsconfigMobile.jsons tsconfig.Desktop and compile them with tsc and -p option.
Seem that Typedoc do not use -p switch, and try to use tsconfig.json in local directory.

**Comment by aciccarello** [comment]
Interesting, the project flag has been around since TS 1.8 so I'm surprised this hasn't been mentioned before. If you run `typedoc --help` it does list the TypeScript project option but I haven't tried it.

**Comment by oity** [comment]
Yep if you run typedoc --help it show all tsc options, despite seems unable to correctly use the -p
if I copy my tsconfig$somename$.json as tsconfig.json and launch typedoc (without -p switch) it works like a charm.

but if I try to run typedoc -p tsconfig$somename$.json he just print the help screen.
mv tsconfig.json tsconfig_temp.json
typedoc --out /tmp/test -p tsconfig_temp.json
Usage:
 typedoc --mode modules --out path/to/documentation path/to/sourcefiles
[omiss]

mv tsconfig_temp.json tsconfig.json
typedoc --out /tmp/test 

Using TypeScript 2.3.2 from ...
Rendering [========================================] 100%

Documentation generated at /tmp/test

if I use -p switch with a nonexistent .json he still work if tsconfig.json is provided
ls -al my_little_fairy.json
ls: cannot access 'my_little_fairy.json': No such file or directory
ls -al tsconfig.json 
-rw-r--r-- 1 test test 2036 giu 26 11:37 tsconfig.json

typedoc --out /tmp/test -p my_little_fairy.json
Using TypeScript 2.3.2 from ...
Rendering [========================================] 100%

Documentation generated at /tmp/test

**Comment by Gerrit0** [comment]
Fixed by #588
