### ISSUE TITLE
Add screenshots or samples

### ISSUE THREAD

**Issue by tbillington** [TypeStrong/typedoc#540]
Hi, just curious if there are samples/screenshots anywhere on the website or repo? I'd like to see what the generated docs will look like. Themes are also mentioned in the guide on the website but there are no screenshots there either.

**Comment by aciccarello** [comment]
Hello, the TypeDoc website includes an example of the generated output (though the website hasn't been updated in awhile).

http://typedoc.org/api/

**Comment by tbillington** [comment]
Ah, I should have realised that the docs were the example, silly me 🤣  thanks
