### ISSUE TITLE
Test various typedoc configs

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#542]
There are a lot of issues where users are seeing a different output than expected. Also, a lot of PRs have no way to test the new feature. We should make it easier to write simple tests to test the output for various configurations.

## Test model
Broken up by directory:

- TypeScript file
- (optional) JSON file defining typedoc config
- expected converter model.

## Concerns
- Exactly comparing converter models is somewhat brittle because one change could break all tests
- Need to keep tests fast (some are currently timing out)
- Knowledge of current test runner is limited

**Comment by samvv** [comment]
Why not use [ava](https://github.com/avajs/ava) for speeding up the tests? It's a really great testing framework, one I stumbled upon myself a while back. It spawn several separate node processes so that tests run incredibly fast.

**Comment by blakeembrey** [comment]
The specific testing framework shouldn't be too relevant to actually going through and building out the tests structure for something like this. I'd suggest sticking to whichever works, then we can open a separate issue if we manage to make it this far 😄 

We should definitely go for snapshots as much as possible to. We kind of do it already, but this project is super heavy on "looks right" that we should mostly focus on that.

**Comment by Gerrit0** [comment]
Another 👍  for `ava` here. The fact that is runs each test file in it's own process really helps keep tests fast. 

It also has an incredibly useful `snapshot` test assertion that can essentially replace the manual snapshots that the project uses now. 

- [Example project](https://github.com/avajs/ava-snapshot-example)
- [Docs](https://github.com/avajs/ava/blob/master/readme.md#snapshot-testing)

**Comment by Gerrit0** [comment]
We kind of do this now, there are several toggles for options that get serialized to different snapshot files.

With a recent improvement to the tests, they all run in under 10 seconds on my machine now, I'm not concerned about the speed so much anymore.
