### ISSUE TITLE
README.md comments

### ISSUE THREAD

**Issue by lmckeen** [TypeStrong/typedoc#543]
when creating a README.md file and using it with typedoc, you can get a really nice looking how to up and running quite easily, but if you write some comments in the README.md file and have too many keywords inside your comment as examples below

`// This event does not need to be added to object because it `
`// is not being listened for and has only dispatched` 

it will end up using the regex class for the element instead of the comment class to style it, without this comment class added the comments will not show up as highlighted in green like its expected.

**Comment by aciccarello** [comment]
Hello @lmckeen, Could you include a screenshot of the output you are seeing? Also, is that a valid [comment in markdown](https://stackoverflow.com/questions/4823468/comments-in-markdown)?

**Comment by lmckeen** [comment]
if you view the above output in markdown it will look like this 

<img width="542" alt="screen shot 2017-06-29 at 3 33 09 pm" src="https://user-images.githubusercontent.com/11928027/27704329-ac0cd85c-5ce0-11e7-9c06-a330fe2c5ae4.png"> 

but if you remove the keywords it will highlight correctly like this
 
<img width="547" alt="screen shot 2017-06-29 at 3 34 19 pm" src="https://user-images.githubusercontent.com/11928027/27704352-c0ae3ada-5ce0-11e7-81e1-13c8b43c1c93.png">

**Comment by Gerrit0** [comment]
This is due to automatic language detection, which is error prone in the first place and not handled by TypeDoc. If you specify the language this won't happen.

    ```ts
    // This event does not need to be added to object because it
    // is not being listened for and has only dispatched
    ```
