### ISSUE TITLE
Add npm package version to the documentation

### ISSUE THREAD

**Issue by madoar** [TypeStrong/typedoc#544]
I would like to add the version of the library which I'm writing to its documentation, so that an user can easily see if the documentation, that he's currently viewing belongs to the version of the library he's currently using.

Therefore the question: Is it currently possible to add the version of the library, for which you're creating a documentation, to the documentation itself?
If yes, how can this be done? Otherwise is it planned to add such a feature?

**Comment by aciccarello** [comment]
@madoar To my knowledge there is no current feature for this but it sounds like a great idea. As always, PRs are welcome.

**Comment by madoar** [comment]
I'm not really into the typedoc codebase.
Can you point me in the right direction, what would need to be done to show the version number, of the library of the documentation, inside the documentation?

**Comment by domske** [comment]
Any updates on this? (Maybe stale issue.) A workaround could be to require the package.json in the config.js of typedoc. This requires the config file as JavaScript instead of JSON.

**Comment by Gerrit0** [comment]
This hasn't been worked yet, it seems like a good idea though. It seems reasonable to me to change the default name to include the version from package.json, users can always pass in a static name to remove the version if it isn't desired.

**Comment by Gerrit0** [comment]
Released in v0.15.6 - TypeDoc now defaults to using the package name and version to construct the name displayed in the documentation. If you just want the package name, you can pass `--name <name>` when generating the docs.
