### ISSUE TITLE
[question] Does typedoc supports something like jsdoc tutorials?

### ISSUE THREAD

**Issue by makepanic** [TypeStrong/typedoc#550]
Hi,
I'm wondering if typedoc supports something like [jsdoc tutorials](http://usejsdoc.org/about-tutorials.html).
I generated typedoc for one project but haven't found anything related to that.

Tutorials in jsdoc allow a user to add markdown pages that aren't bound to code. It's useful if one wants to add a guide or some examples that don't fit in the README.

thanks

**Comment by aciccarello** [comment]
HI @makepanic, currently typedoc does not have a feature exactly like this. See #247 and #63 for related discussions.

**Comment by makepanic** [comment]
Thanks, i'll close this issue
