### ISSUE TITLE
All files of project in Globals?

### ISSUE THREAD

**Issue by allanegidio** [TypeStrong/typedoc#551]
I generated code using typedoc.
But it generated without a summary.
Why were all the files stored in Globals?

**Comment by aciccarello** [comment]
Hello @allanegidio do you have a readme.md in your root directory? Listing all of the files in globals is the way typedoc currently outputs documentation. Originally typedoc was designed around the old modules/namespaces system. The output for the files option is therefore a bit messy. See #68 and #242 for more information.

**Comment by allanegidio** [comment]
Hello @aciccarello, thanks for answer.
Yes i have. I will check these issues and fix it.
 :D
