### ISSUE TITLE
Feature request: Display the source code of interfaces and enums

### ISSUE THREAD

**Issue by vguzev** [TypeStrong/typedoc#553]
We're using typedoc to generate documentation for our REST services at the backend. 
Some of the common interfaces and enums must be reused at the frontend. It would be great if it was possible to copy interface/enum declaration directly from the documentation, generated by typedoc.
Could you please add this feature? 

P.S. This could be implemented for example as two tabs: "Properties" and "Source Code".

**Comment by jedahu** [comment]
This would be great for type aliases. Their auto-generated documentation is somewhat lacking at the moment.
