### ISSUE TITLE
fix: remove specific version of typescript from dependencies

### ISSUE THREAD

**Issue by Hotell** [TypeStrong/typedoc#556]
Suddenly all my builds started to fail https://github.com/Hotell/typescript-lib-starter/pulls

The culprit here is typedoc becuase it has specific version of typescript as direct project `dependencies` which overrides local `node_modules/.bin/tsc` symlink to use this TS instead of TS that is used by the project.

This is a big deal.

![image](https://user-images.githubusercontent.com/1223799/28239622-b15df8bc-6970-11e7-8d29-202cf259d416.png)

**How to fix this:**

- move typescript to peerDependencies ( best solution ) ( this would be a breaking change for your library from perspective of semver )
- change typescript version in your `depencies` to `^2.3.4`

I can submit PR if you're willing to go through it and merge it eventually after LGTM :)

cheers

**Comment by aciccarello** [comment]
We have a PR #549 open to update TypeScript to 2.4 but work does need to be done to make the TypeScript dependency less brittle.

**Comment by aciccarello** [comment]
For reference, this has been discussed mainly in #145 (though also noted in #369).

There is also some relevant discussion in #310

**Comment by Hotell** [comment]
all right, so I found out in the end that the culprit is `yarn` !!! wooot :(

sorry for bugging you folks.

https://github.com/yarnpkg/yarn/issues/3983

**Comment by blakeembrey** [comment]
I'm going to close this for now. If you have it in your own dependencies it certainly shouldn't replace it. That's the reason we use `dependencies` - we have a specific version requirement for TypeScript and we can't just use any version today. As a result, we can not use `peerDependencies` or have it automatically use later versions.
