### ISSUE TITLE
Possible bug removing type converters in converter.ts

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#559]
I was reviewing the code and came across the [`removeTypeConverter` method](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/converter.ts#L237-L247). This method seems to be looking up an item's position in an array and removing it. However, the method looks up the item's position in the `typeNodeConverters` array twice which leads me to think that the first check should be checking the `typeTypeConverters` array.

Does anyone else think this is wrong? Is this causing bugs other than a memory leak?

**Comment by blakeembrey** [comment]
Looks like a typo. It definitely splices from the correct things, just doesn't use `indexOf` correctly. I'd suggest a PR to fix this, plus try to avoid re-using the `index` variable to make it clearer.
