### ISSUE TITLE
Typedoc hangs in Linux

### ISSUE THREAD

**Issue by akrepon** [TypeStrong/typedoc#560]
Hi,

I am currently using typedoc 0.7.1. It's working great on my dev machine(windows 7) but on the linux server it just hangs and does nothing. The server I am using has SUSE installed:

SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 1

It just outputs this message and does nothing furher.

 Using TypeScript 2.3.2 from /data/devops/jenkins/workspace/cia-pipeline/node_modules/typedoc/node_modules/typescript/lib

What could be the reason for this?

Thanks.

**Comment by Roaders** [comment]
I get this on windows (but it does occasionally work) but on linux (our CI jenkins server) it seems fine

**Comment by Roaders** [comment]
The issue for me seems to be that the github plugin takes over 2 seconds per file and fails each time (this is running in a corporate environment where we have no access to github. I assume that some request timesout each time so for over 1000 files this appears to hang.

How can I disable the GithubPlugin?

**Comment by Gerrit0** [comment]
That explanation doesn't make sense to me, I just took a look at the GitHub plugin and all it does is run a few `git` commands, none of which try to reach github.com. I also disconnected all internet access and was able to run TypeDoc without an issue.

I don't believe it's currently possible to disable built in plugins with configuration (looks like #254 can be used to track this), but you can remove the component if you are working with a script:

```js
// @ts-check

const td = require('typedoc');
const app = new td.Application({
    tsconfig: 'tsconfig.json'
});

const converter = /** @type {import('typedoc/dist/lib/utils/component').ChildableComponent<any>} */ (app.getComponent('converter'));
converter.removeComponent('git-hub');

app.generateDocs(app.expandInputFiles(['src']), 'docs');
```

**Comment by Roaders** [comment]
ON further investigation I have found that it is the `git rev-parse --show-toplevel` call that the github extension does. As detailed [here](https://stackoverflow.com/questions/53396610/why-does-git-rev-parse-show-toplevel-return-different-casing-than-actual-path/) it seems that for me an incorrectly typed path is returned from this call so that when the github plugin is comparing the cached repository paths with the path returned from this git call they do not match. It then looks up the repo path for every single file.

I will submit a PR to fix this.

**Comment by aciccarello** [comment]
@Roaders, can this be closed? Can you try checking against master?

**Comment by Roaders** [comment]
Just seen that or had been merged to master. Thanks for that.

Unfortunately the machine that had the issue had no access to GitHub. When the changes are released I will have to request that the new version is made available internally (which should be quick) before I can test it.

I will let you know once I have tested 🙂

**Comment by Gerrit0** [comment]
@Roaders 0.14.x has been out for a while with your merged changes. Has it fixed your issue?

---

The OPs issue is too vague for us to really do anything about. TypeDoc certainly has some performance issues with large projects taking a few minutes to document (under investigation, haven't found the solution yet) but this is being tracked in other issues.

**Comment by Roaders** [comment]
It was only ever an intermittent problem but since updating I have not seen the issue. I think it's safe to assume that it is fixed.
