### ISSUE TITLE
How do you use the `--excludeExternal` flag ? and what do mean by "Prevent externally resolved files"

### ISSUE THREAD

**Issue by andreGarvin** [TypeStrong/typedoc#561]
I am working on a project that has some internal functions that I do not want to include in the documentation. I am fully aware of the `@hidden` doc string namespace but every time I return back to the global.html page I still see the function on the documentation page after running the command. I even tried `--excludeExternals ` not including `@hidden` the function and its documentation still show have been trying to not include certain files from my src folder

**Comment by aciccarello** [comment]
I think `--excludeExternals` was designed to prevent certain files from being included in the documentation (see `--externalPattern`). I'm not sure why `@hidden` wouldn't work. Do you have an example repo?

**Comment by andreGarvin** [comment]
Nevermind I created a script that removes them from the docs after they are done being generated for the problem
