### ISSUE TITLE
Add @category tag

### ISSUE THREAD

**Issue by wbhob** [TypeStrong/typedoc#564]
Sometimes globally-scoped things can get pretty cluttered, so I was wondering if you all can add a `@category` tag to sort documented objects into groups.

**Comment by jonchardy** [comment]
I actually did this as part of our TypeDoc implementation. If you're curious, see https://github.com/jonchardy/typedoc/commit/c12381beb66eda7f415f6d8673f4b355d8e91c73. Alongside these changes, I updated our theme to sort our index page by category.

Excuse the organization, I usually push things to GitHub in batches.

The relevant changes are:
https://github.com/jonchardy/typedoc/commit/c12381beb66eda7f415f6d8673f4b355d8e91c73#diff-0d149f9b1469c3c2f367a941af1b0945
https://github.com/jonchardy/typedoc/commit/c12381beb66eda7f415f6d8673f4b355d8e91c73#diff-bd337a93cb6b55ec5c687ea8a327720e
https://github.com/jonchardy/typedoc/commit/c12381beb66eda7f415f6d8673f4b355d8e91c73#diff-739b66d6abaf9c587a31ae9909a64903
https://github.com/jonchardy/typedoc/commit/c12381beb66eda7f415f6d8673f4b355d8e91c73#diff-ebc8b0bc65bb184ea94b7734503a15f3
https://github.com/jonchardy/typedoc/commit/c12381beb66eda7f415f6d8673f4b355d8e91c73#diff-09c50b8d3de6159296d213ab8664a22a
https://github.com/jonchardy/typedoc/commit/c12381beb66eda7f415f6d8673f4b355d8e91c73#diff-431f5355945bc08849278b194d39a0df

**Comment by wbhob** [comment]
Pr? @jonchardy

**Comment by jonchardy** [comment]
Created PR #566. Feel free to take a look, discuss, and make any changes you feel will improve it.

**Comment by aciccarello** [comment]
Closed by #566

**Comment by emmanueltouzery** [comment]
Regarding closing this bug: I didn't try the changes yet, but my understanding is that the PR which was pulled, according to its author "won't really do much without some accompanying changes to a theme". So I'm not sure this feature is really complete now. Is changing the theme documented?

**Comment by aciccarello** [comment]
@emmanueltouzery I think you are right. I'll reopen this. PRs are welcome to update the [themes](https://github.com/TypeStrong/typedoc-default-themes).

**Comment by mootari** [comment]
I would also love to see multiple `@category` tags handled. The current implementation only keeps the first tag value around. Example:
```
    /**
     * @category Foo
     * @category Bar
     */
```
```
  "tags": [
    {
      "tag": "category",
      "text": "Foo"
    },
    {
      "tag": "category",
      "text": "Bar\n"
    }
  ]
```
becomes:
```
  "categories": [
    {
      "title": "Foo",
      "children": [
        371
      ]
    }
  ]

**Comment by mootari** [comment]
On a related note: I don't think it's a good idea to reformat the original category name. If need be this can be handled in the theme.
https://github.com/TypeStrong/typedoc/blob/32bf5289fc7742c6c2e80b786b298987e5336aaa/src/lib/converter/plugins/CategoryPlugin.ts#L123-L128

**Comment by Gerrit0** [comment]
I opened #1158 to track multiple categories, closing this as there is base functionality for categories already, and the themes have been updated.
