### ISSUE TITLE
Comment are not rendered when brackets are around an optional parameter

### ISSUE THREAD

**Issue by krenor** [TypeStrong/typedoc#567]
Using [JSDoc Syntax](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values)

```@param {string} [key] An optional but fancy key```

![With brackets](https://user-images.githubusercontent.com/13726968/28626597-be17ca44-721f-11e7-90d8-c5869608f134.png)

```@param {string} key An optional but fancy key```

![Without brackets](https://user-images.githubusercontent.com/13726968/28626627-cee4c5c0-721f-11e7-83c6-de36b0bb4221.png)

**Comment by aciccarello** [comment]
Hi @krenor, TypeDoc does not completely follow the JSDoc syntax but I think this is something that should be supported. PRs are welcome.

**Comment by microshine** [comment]
I've got the same problem.
I use [Document This plugin](https://marketplace.visualstudio.com/items?itemName=joelday.docthis) for VisualStudio Code which uses correct JSDOC annotations ([JSDOC Optional parameters and default values](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values)).

**Comment by ST-DDT** [comment]
Linking to the PR with a proposed fix for better visibility:
https://github.com/TypeStrong/typedoc/pull/1810
