### ISSUE TITLE
Inherited properties of custom Error incorrectly reported as static.

### ISSUE THREAD

**Issue by tomc974** [TypeStrong/typedoc#572]
Hi!

I just noticed that if you create a custom `Error`, the inherited properties `message`, `name` and `stack` are reported by TypeDoc as being `static` while the TypeScript compiler correctly consider them as instance properties.

```typescript
class CustomError extends Error {
}
```

**Comment by aciccarello** [comment]
@tomc974, I'll need to check to see that TypeDoc is listening to TypeScript correctly.

You'll probably want to look at this information on [Extending built-ins](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work) for suggestions on how to correctly extend the `Error` object.

**Comment by aciccarello** [comment]
I've confirmed that TypeDoc is handling this differently than TypeScript.

```TypeScript

function useError() {
  CustomError.stack; // [ts] Property 'stack' does not exist on type 'typeof CustomError'.  

  let errorInst = new CustomError();
  errorInst.stack; // ok
}
```

![image](https://user-images.githubusercontent.com/11273838/28723727-e96cf470-7374-11e7-805a-80a57f10aa54.png)
