### ISSUE TITLE
Error: Cannot find type definition file for depedencies 

### ISSUE THREAD

**Issue by bogdanlozyak** [TypeStrong/typedoc#574]
Hello everyone,
I've upgraded to the last version of typedoc whick contains the last version of Typescript 2.4.1
```
C:\Users\lozya\Desktop\Materiale Stage\davebackend>npm cache clean --force & npm uninstall -g typedoc & npm install -g typedoc
npm WARN using --force I sure hope you know what you are doing.
removed 60 packages in 2.608s
C:\Users\lozya\AppData\Roaming\npm\typedoc -> C:\Users\lozya\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc
+ typedoc@0.8.0
added 60 packages in 10.151s

C:\Users\lozya\Desktop\Materiale Stage\davebackend>typedoc -v

TypeDoc 0.8.0
Using TypeScript 2.4.1 from C:\Users\lozya\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\lib
```
When i'm trying to build my project documentation, I get this error
```
C:\Users\lozya\Desktop\Materiale Stage\davebackend>typedoc --out docs/typedoc/ --module node --target ES5 --mode file ./app/

Using TypeScript 2.4.1 from C:\Users\lozya\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\lib
Error: Cannot find type definition file for 'fs-extra'.
Error: Cannot find type definition file for 'glob'.
Error: Cannot find type definition file for 'handlebars'.
Error: Cannot find type definition file for 'highlight.js'.
Error: Cannot find type definition file for 'lodash'.
Error: Cannot find type definition file for 'marked'.
Error: Cannot find type definition file for 'minimatch'.
Error: Cannot find type definition file for 'node'.
Error: Cannot find type definition file for 'shelljs'.
```

Some advice to solve this?
Thanks for your time

**Comment by AmirTugi** [comment]
Running into the same issue as well

**Comment by aciccarello** [comment]
Could you provide more information about how to reproduce this issue? My guess would be that you need to provide arguments to the typescript compiler.

**Comment by Floppy012** [comment]
Maybe worth noting: Today I ran into the same problem but only with one of my own projects. I'm having a project directly included as TS dependency (not transpiled).

- The project is not in the `@types` directory (I have additional type-roots set in tsconfig)
- As the module is not transpiled the globals file is called `globals.ts`
- `globals.ts` is not located in the root directory of the dependency 

This is a shortened tree of the dependency:

```
./node_modules/@private/base
├── dist
│   ├── api
│   │   ├── globals.ts
│   ├── config
│   ├── index.ts
│   ├── logging
│   ├── main
│   ├── module
│   └── util
├── package.json
└── README.md
```
TSC compiles the project without any errors.

TypeDoc spits out this error: `Error: Cannot find type definition file for 'base'.` 

My current workaround is the `ignoreCompilerErrors` switch. Docs are being built fine.
