### ISSUE TITLE
Only export by default

### ISSUE THREAD

**Issue by nicolasgere** [TypeStrong/typedoc#580]
Hello, i want to use your package for create documentation for a library i have.
Is is possible to set export only by default? Or just generate export stuff only.
Thanks for the job and have a good day

**Comment by aciccarello** [comment]
Hello @nicolasgere, can you explain what you mean by "set export only by default"?

**Comment by nicolasgere** [comment]
@aciccarello i dont want to provide a docs for the internal stuff of the library, just the exported one

**Comment by Maximkaaa** [comment]
@nicolasgere I beleive --excludeNotExported option is what you are looking for. I could not find any mentioning about it in the typedoc docs though so probably this is a documentation issue.

**Comment by ManAnRuck** [comment]
<img width="308" alt="Bildschirmfoto 2019-07-26 um 11 44 32" src="https://user-images.githubusercontent.com/2183135/61942977-c10a1a80-af9a-11e9-9a04-bc1eb0eb5bed.png">
a parameter which not exclude not exported stuff, but check this checkbox by default would be also very helpful

**Comment by aciccarello** [comment]
It seems like several things are being discussed in this issue:
- The OP is probably interested in the idea of adding a "library" mode which is discussed in #639 
- If there are issues with the `--excludeNotExported` option, a new issue should be opened to identify that issue
- The easiest way to set that checkbox by default would be to create a custom theme
