### ISSUE TITLE
tags and descriptions not lining up in class comments

### ISSUE THREAD

**Issue by Rhonun** [TypeStrong/typedoc#583]
![screen shot 2017-08-21 at 4 02 06 pm](https://user-images.githubusercontent.com/3461296/29535997-1aec2dc2-868a-11e7-8427-c66e1e3022a0.png)
![screen shot 2017-08-21 at 4 00 56 pm](https://user-images.githubusercontent.com/3461296/29535988-0f019c68-868a-11e7-932a-f7fb380687d2.png)

**Comment by damianb** [comment]
Additionally, tags are overlapping other content like code blocks from examples - see the following screenshot:

![image](https://user-images.githubusercontent.com/121707/31674209-d9eee886-b326-11e7-9a4d-d765b39e7a4d.png)

**Comment by damianb** [comment]
Issue seems to be the empty `<dd>` elements.

Bootstrap also encountered this problem (reported at https://github.com/twbs/bootstrap/issues/4062), and fixed it with this commit: https://github.com/twbs/bootstrap/commit/37f4a25be436e8b25004d22541809032d8354600

**Comment by aciccarello** [comment]
Fixed via TypeStrong/typedoc-default-themes#54
