### ISSUE TITLE
TypeDoc renders main entry point containing only exports default and reexport declarations as empty

### ISSUE THREAD

**Issue by octatone** [TypeStrong/typedoc#596]
I have an entry point `index.ts` for my library that contains only an export default and export declarations:

```js
import Main from './Main'
export default Main

export { default as State } from './state'
export { default as ThingModel } from './state/Thing/Model'
export { default as ThingCollection } from './state/Thing/Collection'

// etc ...
```

When I generate docs via TypeDoc it is an empty file.  I would expect it to list what is exported from this module:

<img width="833" alt="empty" src="https://user-images.githubusercontent.com/492289/30753256-0fe00392-9fbf-11e7-98e2-948a1dca62f5.PNG">

**Comment by aciccarello** [comment]
Hi @octatone, how are you calling/what are you using for your typedoc configuration.

**Comment by octatone** [comment]
via shell:
`typedoc --options ./config/typedoc.js --out ./docs ./src`

typedoc.js
```js
module.exports = {
  mode: "modules",
  module: "umd",
  target: "ES5",
  externalPattern: "node_modules",
  excludeExternals: true,
  excludePrivate: true
}
```

`index.ts` lives at `./src/index.ts`

I get the same empty output regardless of options or no options (default options).

**Comment by chrisprice** [comment]
From a quick poke around, am I right in thinking this behavior is because [typedoc only supports](https://github.com/TypeStrong/typedoc/blob/5eb104b69ea8f58f08057eefaf58b076153214e1/src/lib/converter/nodes/export.ts#L12) [`ts.SyntaxKind.ExportAssignment`](https://github.com/Microsoft/TypeScript/blob/9af21eb00eb957240159745c181077e21df9da17/src/compiler/transformers/utilities.ts#L79) and the export syntax in use is [`ts.SyntaxKind.ExportDeclaration`](https://github.com/Microsoft/TypeScript/blob/9af21eb00eb957240159745c181077e21df9da17/src/compiler/transformers/utilities.ts#L46)?

**Comment by pluma** [comment]
I'm guessing this isn't going to be fixed anytime soon?

**Comment by pabloFuente** [comment]
And how can the export syntax be changed from ExportDeclaration to ExportAssignment? Any idea?

**Comment by Gerrit0** [comment]
This will be fixed by #801

**Comment by pluma** [comment]
#801 was closed and replaced by #1157, which has been merged. I can't seem to get reexports to show up with the latest release, though.

**Comment by Gerrit0** [comment]
Could you set up an example repo showing this problem? The tests for it are passing... seems to be working for me.

**Comment by pluma** [comment]
Here's my setup:

https://github.com/arangodb/arangojs/blob/feb46dbe1628d906500440af77d9c87804d0ec49/src/index.ts
https://github.com/arangodb/arangojs/blob/feb46dbe1628d906500440af77d9c87804d0ec49/typedoc.json

Only the default export shows up in the documentation.

**Comment by pluma** [comment]
Ah, nevermind, explicitly changing it to `export {...} from` syntax fixes this. Re-exporting the imports doesn't work though.

**Comment by Gerrit0** [comment]
Ah, that makes some sense. Yet another reason coming back to why we need to use the type checker to get this information instead of walking the node tree and trying to figure it out ourselves... Glad you found a workaround for now.
