### ISSUE TITLE
Top level module level comments don't show if imports exist

### ISSUE THREAD

**Issue by nickzelei** [TypeStrong/typedoc#603]
It seems that top level module level comments don't appear if the module also has imports.

```
/**
* @copyright <our copyright here>
*/

import * as _ from "lodash";
```

I have tested this in files that do have imports vs files that don't. The top level module comment only appears in modules that do not have any external imports.

**Comment by aciccarello** [comment]
I'm curious if it thinks the comment is for the import.

Does the module comment appear if you do the following?

```TypeScript
/**
* @copyright <our copyright here>
*/

/** ignore this comment */
import * as _ from "lodash";
```

**Comment by zelein** [comment]
Yes, that did make it appear.

**Comment by zelein** [comment]
It only appeared when using the multi-line notation. It did not change when using single line.

**Comment by chriskrycho** [comment]
At least for me, it works if using a single-line comment in front of the imports.

**Comment by christopherthielen** [comment]
I'm not sure what the intention is behind the code, but this is due to these lines: https://github.com/TypeStrong/typedoc/blob/v0.9.0/src/lib/converter/factories/comment.ts#L90-L93

**Comment by zelein** [comment]
That looks like the culprit. Single-line comments are not ideal since (at least for us) they are used as file headers..so they are naturally multi-line.

**Comment by demurgos** [comment]
I am encountering the same issue. I also use the workaround described above (using a dummy doc comment).
It would be nice if the lines highlighted by @christopherthielen were either removed or explained.

**Comment by ShawnTalbert** [comment]
I'm trying out TypeDoc and can't seem to get a top level module description to render. 

The top of my module file looks like so:

```
/**
 * Document all the things
 */


//imports
import {Result} from "N/search"
```

Any ideas? I think this is a great project but if I can't have introductory text at the top of a module if feels rather raw.

**Comment by Gerrit0** [comment]
`//imports` won't be caught as a documentation comment. Change it to `/** imports */` and you should be golden.

**Comment by ShawnTalbert** [comment]
Thanks @Gerrit0 switching to that style of comment (specifically with two prefix asterisks) worked. This is a very annoying bug.

**Comment by Gerrit0** [comment]
It is not a bug. TypeScript doesn't have the concept of a "module" documentation comment, and will take the concatenation of all doc comments before a declaration.

Given the following file:

```ts
/** Module */

/** Function */
export function test () {}
```

TypeScript will give "Module Function" as the documentation for `test`.

![image](https://user-images.githubusercontent.com/19329837/52600483-07b6ee80-2e19-11e9-9a0d-cf551d3a4e7b.png)

TypeDoc follows the JSDoc behavior of only treating the last comment as the documentation, so only "Function" would be included in the documentation. This makes it possible for a module comment to exist - if it is separated from any node by another documentation comment. This behavior is documented [on the site](https://typedoc.org/guides/doccomments/#files).

While we could introduce a bunch of checks to say that some node types "can't" be documented, this would open the door to more breaking changes in the future, and I don't think it's a good idea right now.

**Comment by aciccarello** [comment]
@Gerrit0 Thanks for pointing out the TypeScript parsing.

This is a difficult problem to solve without breaking changes. There are many different cases we would need to handle if we were trying not to be too restrictive. The simplest semantics I can think of is that file documentation would need to be at the very beginning of the file and be followed by a empty line. Another option would be to require something like a `@file` comment tag, though I don't love that idea.

I'd like to see some clarification on Microsoft/tsdoc#6 before making a breaking change.

### File with imports
```typescript
/**
 * This clearly is at the top of the file. Imports are never documented.
 */
import foo from 'foo';

export function bar() {
  foo();
}
```

### File comment that isn't first line
```typescript
/*
 * Corporate header
 * @copyright Foo Inc.
 */
/**
 * I'm not sure how important this use case is but it may be worth recognizing.
 */

export function bar() {
  foo();
}
```

### File without imports
```typescript
/**
 * The only indication that this is a file level comment is the empty line.
 */

export function foo() {
  return 'foo';
}

export function bar() {
  return 'bar';
}
```

### Commented out lines
```typescript
/**
 * This clearly is at the top of the file. Imports are never documented.
 */
// import foo from 'foo';

export function bar() {
  // foo();
}
```


```typescript
/**
 * This could have been a comment for the following line that was commented out.
 */
// const foo = () => 'foo';

export function bar() {
  foo();
}
```

**Comment by ShawnTalbert** [comment]
I sympathize with limitations of TS under the covers. However a full featured API documentation tool like TypeDoc should consider top level module documentation as a first-class feature one way or another.

I've seen far too many APIs documented that just dump you into a haphazard collection of exported symbols. The top-level documentation provides context to tie it all together and helps the reader make sense of what follows.

If I can be of any assistance I'm happy to help.

**Comment by Gerrit0** [comment]
With 0.15.6 (should be out later today) TypeDoc supports the `@packageDocumentation` tag to mark a comment as documentation for the file. This is consistent with TSDoc's effort to standardize blocks.

The legacy behavior of using a dummy comment still works, but using `@packageDocumentation` is preferred.

**Comment by Rigii** [comment]
For me still an actual issue.
TypeDoc totally ignores top-level comments in my functional component index file. Same story if comment in a component file, and doc generates directly for it. I just started to use TypeDoc for my React project, could somebody explain what's wrong?
index.ts

` /**
 * @module LogoSafeComponent
 * # This is a comment!!!
 * ## This is a comment 2!!!
 * ## This is a comment 3!!!
 * @param classNameCustom - custom styling class name
 * @param isSmall - img size
 * @module
 */

export * from "./LogoSafe";`

modules.md output

`
[safe-app](README.md) / Exports

# some-app

## Table of contents

### Functions

- [LogoSafeComponent](modules.md#logosafecomponent)

## Functions

### LogoSafeComponent

▸ **LogoSafeComponent**(`__namedParameters`): `ReactElement`<`any`, `string` \| `JSXElementConstructor`<`any`\>\>

#### Parameters

| Name                                 | Type      |
| :----------------------------------- | :-------- |
| `__namedParameters`                  | `Object`  |
| `__namedParameters.classNameCustom?` | `string`  |
| `__namedParameters.isSmall?`         | `boolean` |

#### Returns

`ReactElement`<`any`, `string` \| `JSXElementConstructor`<`any`\>\>

#### Defined in

[LogoSafe.tsx:13](https://github.com/SomeAppOfficial/chrome-extension/blob/efc774c/src/components/LogoSafe/LogoSafe.tsx#L13)
`

If I highlit my component in code, the documentation looks as expected. Actually, I expect the same data in my .md output:

<img width="580" alt="Screenshot 2022-07-13 at 18 36 43" src="https://user-images.githubusercontent.com/23354048/178788994-10cf414c-eef2-43aa-a7b7-755d45f43833.png">

**Comment by Gerrit0** [comment]
Please open a new issue rather than bumping a (at this point very old) one

**Comment by heyakyra** [comment]
For people who end up here via search…

The module-level comment will only work if the first declaration also has a TSDoc comment. 
https://github.com/microsoft/FluidFramework/wiki/TSDoc-Guidelines#documenting-modules

There is a conflict between TypeDoc and TSDoc: https://github.com/matrix-org/matrix-js-sdk/issues/3243#issuecomment-1684411422

And adding support for an `@module` tag would be good https://github.com/microsoft/tsdoc/issues/296#issuecomment-898566841
