### ISSUE TITLE
ability to group functions in the documentation

### ISSUE THREAD

**Issue by emmanueltouzery** [TypeStrong/typedoc#608]
I'm writing a typescript library and I'm using typedoc to document it. I have a series of standalone functions in the library (toplevel `export function`, not part of a class or an interface, callable directly). That's problematic in typedoc for me, because all the functions are grouped together in a 'Functions' section at the bottom of the documentation. I'd like to group them by category. 

I do not understand typescript namespaces/internal modules or external modules as well as I would like to, but as far as I can see, typedoc only documents external modules (`export module`), not `namespace` and not `module`. And I guess that's correct for a library.

So the only way I can see right now to group my standalone functions with typedoc is to use external modules. Then the documentation looks great, exactly what I want, but I don't want to use external modules in my library, because that forces many things for the users of the library: to begin with, external modules get compiled differently according to my setup in my tsconfig, which may not be the one that suits users of the library, and second users of the library may wish to avoid external modules (for instance I see advices to avoid mixing external & internal modules and I don't want to alienate users using internal modules).

So I'd like to keep exporting standalone functions and at the same time I'd like to achieve a display in typedoc similar to the one achieved when grouping them through external modules.

I imagine annotations like:

```typescript
/**
 * @functiongroup DiskIO
 */
export function writeToFile(...) ...

/**
 * @functiongroup NetworkIO
 */
 export function connectToHost(...) ...
```

Does that make sense? If I provide a PR to that effect, does it have any chance to get merged?

**Comment by aciccarello** [comment]
Hello, would #564 provide the functionality you are looking for?

**Comment by emmanueltouzery** [comment]
yes bug #564 is exactly what I want, closing this bug as a duplicate. I see a PR was merged, but not released yet and it seems I'll need to do some manual work on the theme, but i'm happy to see that something may happen related to that :-)
