### ISSUE TITLE
Strategy for Documenting TypeDoc

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#609]
The documentation for TypeDoc could use some improvements. The latest few documentation updates have all been to the readme but in my opinion, the [typedoc.org guides](http://typedoc.org/guides/installation/) should be the main source for documentation. In #595, @shlomiassaf suggested moving to more of a monorepo strategy for managing the project. I think the docs could also gain some visibility by this strategy and updating the API docs could become part of the release process.

I know from #270 that @d-asensio did some of the work getting the website back up and @blakeembrey has access to the [typedoc-site](https://github.com/TypeStrong/typedoc-site) project. Would it be possible & beneficial to host typedoc.org [from a /docs folder](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)? If not, there should be clear instructions on how to contribute to the docs.

## My Suggestions:

1. Emphasize the website as the focus of documentation (over the readme)
2. Move [TypeStrong/typedoc-site](https://github.com/TypeStrong/typedoc-site) into this project (for easier visibility/contributions & easier API doc updates)
3. Figure out a good process for updating the API docs
4. Explicitly encourage contributions to docs (and point people in the right direction)

P.S. I've been trying to put together a list of possible improvements to the documentation under the [documentation project](https://github.com/TypeStrong/typedoc/projects/3). If anyone wants to pitch in, PRs are always welcome :wink:

**Comment by aciccarello** [comment]
As an alternative to hosting the website from master under a `docs` directory, we could use the `gh-pages` branch. We could still have a `docs` directory for the markdown files and simply copy them into the `_guides` directory of the `gh-pages` branch.

The advantage to this is that it keeps the master branch clean of any website related things but keeps everything under one repo. Having a `docs` directory of just markdown files would also make contributions easier and make it easier for people who don't look at the website to find answers.

See the `Teradata/covalent` project [release script](https://github.com/Teradata/covalent/blob/797e1fa7ab2bb26a745562320c8c1a3be88d1967/scripts/ghpages-deploy).

**Comment by cancerberoSgx** [comment]
Hello. I'm writing some Getting starter with typedoc documentation for my colleages. I've started some work [here](https://cancerberosgx.github.io/javascript-documentation-examples/examples/typedoc-tutorial-basic/docs/docco/src/index.html). I wonder if something like this coul dbe included in TypeDoc ? I think it could be of great help speccially for those that doesn't have prior experience with jsdoc/javadoc like tools. Sincerely, typedoc is a  great tool but it has very poor documentation and something like this could improve things a lot. What do you think ? (if you think it's OK I can make a PR with this or please feel free to use it as you like) Thanks! and keep it up!

**Comment by aciccarello** [comment]
@cancerberoSgx Wow, that's great. Currently the documentation is held in the [typedoc-site guides folder](https://github.com/TypeStrong/typedoc-site/tree/gh-pages/_guides) as markdown. Is there any chance we could get a Markdown version of that?

**Comment by cancerberoSgx** [comment]
of course, I designed with the hope you integrate it as markdown some day :) give me a sec...
