### ISSUE TITLE
To Display only the typescript class names instead of entire file path in the generated document

### ISSUE THREAD

**Issue by yash8989** [TypeStrong/typedoc#619]
![typedoc_scrrenshot](https://user-images.githubusercontent.com/8244708/31442043-bb87158a-aeb2-11e7-83e8-18193b351b48.png)
The document that is generated displays the entire file path,  is there a way by which we can display only the typescript class names in the links shown in the screenshot?..

**Comment by pwagener** [comment]
I've been using [typedoc-plugin-external-module-name](https://github.com/christopherthielen/typedoc-plugin-external-module-name) to some effect here.  Not certain it fits your use case @yash8989, but is worth investigation.

**Comment by kal93** [comment]
Setting `mode:'file'` worked for me.
