### ISSUE TITLE
Use Typescript 2.5.3

### ISSUE THREAD

**Issue by avikalpa** [TypeStrong/typedoc#624]
I have a typescript project that uses the latest version of typescript(2.5.3)

It would be great if typedoc could have a 'peer-dependency' of typescript.
If not, please update typescript dependency to 2.5.3 instead of 2.4.1

Thanks.

- tags: enhancement

**Comment by aciccarello** [comment]
Hello @avikalpa, because TypeDoc is tightly coupled to specific TypeScript versions, using peer-dependencies is not a viable option. It would be good to update though. PR #573 is open to address this.

**Comment by sabberworm** [comment]
@aciccarello 

> TypeDoc is tightly coupled to specific TypeScript versions

Are you sure that’s completely true?

I used installed TypeDoc 0.9.0, removed `./node_modules/typedoc/node_modules/typescript` and it worked perfectly:

```
➔ ./node_modules/.bin/typedoc --tsconfig . --out build/tsdoc js/main/src

Using TypeScript 2.6.2 from /path/to/node_modules/typescript/lib
Rendering [========================================] 100%

Documentation generated at /path/to/build/tsdoc
```

Maybe some things don’t work but if it’s good enough for my use-case, why not let me use it this way? You can still require specific versions of typescript with `peerDependencies` and npm will warn us if the versions are seemingly incompatible…
