### ISSUE TITLE
Searching before indexes are prepared results in a 404

### ISSUE THREAD

**Issue by fm-adam** [TypeStrong/typedoc#627]
Hi,

We use TypeDoc to generate documentation from TypeScript source. We've recently noticed that when we search the generated documentation there is a period of time where "Preparing search index..." is displayed in the search box. If you happen to type something into the search box while the index is being prepared and then hit enter you will be redirected to a 404 page.

Is this a known issue? We could not find any mention of it in the open issues. Is there a fix? Is there a way to cache the search index that gets generated so that it does not get rebuilt every time the page reloads?

Please let me know, and thank you.

Adam

**Comment by Gerrit0** [comment]
I can't seem to reproduce this in 0.20, it works well here: https://typedoc.org/api/index.html
