### ISSUE TITLE
Using declared modules rather than treating files as modules.

### ISSUE THREAD

**Issue by AdamHarte** [TypeStrong/typedoc#628]
I have a library of modules that I want to generate documentation for using typedoc. Each module definition is in it's own .d.ts file.

Here is an example of what one of my module files might look like:

```javascript
/**
 * @module duration-units
 */

/**  */
declare module "duration-units" {
	/** Constants for all the unit types. */
	export enum UnitType {
		SECONDS,
		MINUTES,
		HOURS
	}
	
	export class Unit {
		/**
		 * Create a Unit that can be converted easily to other units.
		 */
		constructor(value:number, type:UnitType);
		
		/** The type of units to use. */
		units:UnitType;
		
		/**
		 * Convert hours to seconds.
		 * @param hours The number of hours to convert to seconds.
		 */
		toSeconds(hours:number):number;
	}
	
	interface UnitActions {
		/**
		 * Add a list of units together.
		 * @param units The array of Units to add together.
		 */
		addUnits(units:Unit[]):number
	}
	
	/** Perform various actions on your units. */
	export var actions:UnitActions;
}
```

This is how I currently have my definition file setup. As well as generating the documentation, the file is also used for IntelliSense completion in VS Code.

You can probably see I am using the `External Module Name` plugin with the `@module` declaration at the top. This helped get rid of the `.d` at the end of my module names.

However, my main problem is that the generated documentation has one level of hierarchy more than I want. My index page seems to list all the modules based on the files (using the `@module` name as their name), then if I click on a module, I am taken to a `External module duration-units` page, with one entry for `"duration-units"` (with the quotes) under a Modules heading. When I click on this module, I am taken to the actual docs for the module.

Really I would like the list on the index page to be the declared modules from inside each of my files. Is there a way to do this? Or do I need to modify my modules to be formatted differently?

Cheers.

**Comment by Gerrit0** [comment]
Since the module you are describing is global and doesn't depend on the file, you can pass `--mode file` to TypeDoc which will remove all of the external modules and put their content directly under globals, this will also remove the need for the external module name plugin.
