### ISSUE TITLE
Question: How to generate documents and serve?

### ISSUE THREAD

**Issue by petrovic-ivan** [TypeStrong/typedoc#629]
I installed package like this: `npm install typedoc --global`.

Then I did `typedoc --out docs src` from my root folder.

After that I receive error:

>  Cannot use imports, exports, or module augmentations when '--module' is 'none'.

What I am missing?

**Comment by aciccarello** [comment]
I'd have to mess around with some options. Try adding the `--module commonjs` or `--mode file` options.

If either of those don't work, can you post your tsconfig.json file?

**Comment by s-weigand** [comment]
Had the same problem and adding 
```
  "typedocOptions": {
    "module": "commonjs"
  },
```
to my `tsconfig.json` fixed it.

Posting this just in case someone else finds this issue, by searching for that problem.
