### ISSUE TITLE
typedocOptions does not support extends

### ISSUE THREAD

**Issue by paulsouche** [TypeStrong/typedoc#630]
Hi,

Since `0.9.0` `typedoc.json` is deprecated and we can add a `typedocOptions` in our `tsconfig.json` but it is not supported when we extend our tsconfg.json

Steps to reproduce

You can use [my repo](https://github.com/paulsouche/typedoc-630)

Or

main `tsconfig.json` in /

```json
{
  "typedocOptions": {
    "mode": "modules",
    "out": "docs",
    "exclude": "test",
    "theme": "default",
    "ignoreCompilerErrors": true,
    "excludePrivate": true,
    "excludeNotExported": true,
    "target": "es5",
    "moduleResolution": "node",
    "preserveConstEnums": true,
    "stripInternal": true,
    "suppressExcessPropertyErrors": true,
    "suppressImplicitAnyIndexErrors": true,
    "module": "commonjs"
  }
}
```

child `tsconfig.json` in /child

```json
{
  "extends": "../tsconfig.json"
}
```

run `typedoc index.ts` in /child

Thanks anyway for the great job

**Comment by Gerrit0** [comment]
With 07fb1ce879bfcbea0c3d75e2b1a1dee8575c15ae (release later today) TypeDoc will resolve `"extends"` in `typedoc.json`, to include more options.

Just a note - typedoc.json is not deprecated.
