### ISSUE TITLE
Using TypeDoc with projects that include JavaScript?

### ISSUE THREAD

**Issue by dtgriscom** [TypeStrong/typedoc#643]
I'm working on a project where the shell is standard JavaScript, but most of the core code is written using TypeScript. Will TypeDoc work in such a situation? 

I guess there are a number of levels of "working":

1) TypeDoc will tolerate JavaScript files that it encounters, but won't generate documentation for them

2) TypeDoc will parse JavaDoc comments in JavaScript files and add them to the documentation tree

3) TypeDoc will read JavaScript files, parse JavaDoc comments, and in addition figure out what it can from the symbols and argument lists, and add it all to the documentation tree

Will TypeDoc do any of this?

Thanks,
Dan

**Comment by aciccarello** [comment]
@dtgriscom TypeDoc gets the type information from the TypeScript compiler so the things that the compiler understands will get passed to TypeDoc. That said, I haven't tried parsing JavaScript myself so I'm not sure what level of support exists. Let us know how things work for you!

**Comment by dtgriscom** [comment]
No go:

`Error: File '/Users/griscom/Documents/Work/25-seven/Intercom/webgui/arguments.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.`


Such is life...
Dan

**Comment by dtinth** [comment]
It works fine but you need to configure the TypeScript compiler:

```
typedoc --allowJs --ignoreCompilerErrors --module commonjs --out /tmp/bms-js-docs ~/Bemuse/bms-js/index.js
```

- `--allowJs` Makes TypeScript not bail when it found `.js` file extension.
- `--ignoreCompilerErrors` Is needed because compiling JS file as TypeScript will likely cause the compiler to complain.
- `--module commonjs` Is needed if you want TypeDoc to parse `require()` calls.

**Comment by Manleen** [comment]
I'm using the above command still it doesn't generates documentation for *.js files. 
Any idea why --allowJs is not working?

**Comment by aciccarello** [comment]
@Manleen Can you link to a repo where we could see your code and error?

**Comment by Manleen** [comment]
I don't see any error. I have both .ts and .js files in the source code. When I use typedoc to generate the documentation, it just generates docs for ts files. The repo is private so I can't link it.

**Comment by EternalPhane** [comment]
@Manleen You should define typedoc options in tsconfig.json and use `--tsconfig` option to load the file. Here's an example:

tsconfig.json
```json
{
    "compilerOptions": {
        "allowJs": true,
        "module": "es2015",
        "target": "es6"
    },
    "include": [
        "src/**/*.js"
    ],
    "typedocOptions": {
        "ignoreCompilerErrors": true,
        "mode": "modules",
        "out": "./docs"
    }
}
```

cli
```
> typedoc --tsconfig tsconfig.json
```
