### ISSUE TITLE
Excessive file search up to the system root

### ISSUE THREAD

**Issue by gretchenfitze** [TypeStrong/typedoc#645]
Hello,

https://github.com/TypeStrong/typedoc/blob/a24e61e2968bdc503d4fd4c733deba53a5e1b642/src/lib/converter/plugins/PackagePlugin.ts#L95-L114

This while loop is supposed to find package.json and readme.md in the project, so I expect that it will stop when `this.packageFile` and `this.readmeFile` are not undefined, but it still looking for it up to the system root directory.
It causes permission errors when you have limited access to the build server.

**Comment by pro-src** [comment]
Wow, this is so easy to fix that I didn't think there would be an _old_ issue... I opened a PR for this: https://github.com/TypeStrong/typedoc/pull/772
