### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by taoqf** [TypeStrong/typedoc#648]
I came to a problem with the double quote, modules/*.html file generated will have a _ prefix, and I will get a 404 when I put these files on my website on github. It seems github will hide these files. Is there a way I could generate files without _?

**Comment by aciccarello** [comment]
@taoqf Thanks for reporting but there is already a closed issue for this. The solution is to include a `.nojekyll `file at the document root. I would like to eventually see the underscores removed from external modules though.

Closing as duplicate of #149

**Comment by taoqf** [comment]
Thanks
