### ISSUE TITLE
Search function searches from the start of a word

### ISSUE THREAD

**Issue by janetfi** [TypeStrong/typedoc#649]
The Search field at the top of generated pages only searches from the beginning of API member names.  So, for example, if you search for "Screen" and hope to see "SplashScreen" in the search results, you won't.
Is there a way to fix that, or will it cause the Search function to take forever?
Is the code for the search functionality in main.js?  (My code editor removed all line endings, so I'm having trouble reading main.js.)
(This project rocks!)

**Comment by Gerrit0** [comment]
The search field in the default theme uses [Lunr](https://lunrjs.com/) to search, so you are supposedly able to use `*` as a wildcard, however this doesn't seem to work for me (Maybe the library is just outdated?)

I believe you will want to take a look at [Search.ts](https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/assets/js/src/typedoc/components/Search.ts), everything here should also be in main.js, Search.ts is the source.

**Comment by aciccarello** [comment]
This will be available in the next release of typdoc-default-themes
