### ISSUE TITLE
Type error for enums with string values

### ISSUE THREAD

**Issue by patrickhrastnik** [TypeStrong/typedoc#651]
Since TypeScript 2.4 enums can have string literal values.
[https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html](TypeScript changelog)
But Typedoc fires the following message:

```
[11:52:16] c:/Projekte/HolterOnline/TypeScript/src/enums/DokumentTyp.ts(9)
 Type '"promotion"' is not assignable to type 'DokumentTyp'.
```

Content of DokumentTyp.ts is as follows:

```
export enum DokumentTyp {
    Aktion = "promotion",
    Katalog = "catalog",
    Preisliste = "pricelist",
    Ersatzteile = "spareparts",
    Prospekt = "flyer",
    Handbuch = "manual",
    Datenblatt = "datasheet",
    Zertifikat = "certificate",
    Werkszeugnis = "factory_certificate",
    Sicherheitsdatenblatt = "material_safety_data_sheet",
    Anleitung = "instruction",
    Leistungserklärung = "declaration_of_performance",
    Präsentation = "presentation",
    Sonstiges = "other"
}
```

TypeScript compiles without errors, but Typedoc cannot generate the documentation.
Am I doing something wrong, or is this some missing feature in Typedoc?

I'm running Typedoc in gulp via gulp-typedoc.

**Comment by aciccarello** [comment]
Related to #599

**Comment by Gerrit0** [comment]
This seems to work correctly in `0.9.0` for me, what version are you using?

**Comment by patrickhrastnik** [comment]
Currently 0.7.2
I'm gonna update immediately

**Comment by patrickhrastnik** [comment]
Thank you, in 0.9.0 this issue doesn't exist.
Sorry for wasting your time. Have a nice day 👍
