### ISSUE TITLE
 Cannot find name 'Set',  'Map',  'Promise' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by bhavinsa** [TypeStrong/typedoc#652]
![image](https://user-images.githubusercontent.com/19814178/33380888-7904b116-d542-11e7-8640-539c30e8d882.png)

Version : 
TypeScript 2.4.1
Angular - 4.0.0
NodeJS - v6.11.4

I have used this command to generate the document -
typedoc --experimentalDecorators --target 'es5' --module 'commonjs' --out /doc /src/app

But is gives me error like - 
 Cannot find name 'Set',  'Map',  'Promise' only refers to a type, but is being used as a value here.

looking for help.

**Comment by bhavinsa** [comment]
@aciccarello 

I have changed to es6, but now error for it give error - Cannot find module '@angular/core'.

typedoc --experimentalDecorators --target ES6 --module 'commonjs' --out /doc /src/app


![image](https://user-images.githubusercontent.com/19814178/33383436-4b49e582-d549-11e7-9e78-736e867059a7.png)

**Comment by aciccarello** [comment]
This seems like a configuration problem so I'm going to close this issue. Feel free to leave additional comments. Also make sure you are passing in the file or directory that you want to document. I'm wondering if it is trying to document the `node_modules` directory.
