### ISSUE TITLE
Upgrade TS version

### ISSUE THREAD

**Issue by chriskrycho** [TypeStrong/typedoc#655]
Since TypeDoc hooks into the TS version, it can be quite frustrating to use when it's behind by several versions.

I have it running as a pre-commit hook via [husky](https://github.com/typicode/husky), and it's currently failing because I have intentionally (for the sake of the shape of my exports in the `index.ts`) imported some unused items. In TS 2.6 I can ignore those unused items by doing `// @ts-ignore` on the preceding line; but TypeDoc being only at 2.4 can't do that.

Related: is the underlying API being used so unstable that TypeDoc can't treat TS as a peer dependency rather than a direct dependency? It would be great if it was a peer dep with a version requirement for >= whatever the minimum version it needs is.

**Comment by aciccarello** [comment]
@chriskrycho, PR #654 should update the TS version in master. Once that is merged and a release is made the `// @ts-ignore` issue should be resolved.

As to why we can't use peer dependencies, TypeDoc currently relies on some internal TS APIs so it is very unstable. It'd be great if the project could move away from those but that seems like a significant undertaking.

Related #369

**Comment by chriskrycho** [comment]
Makes sense. Thanks!
