### ISSUE TITLE
Promise<object> incorrectly renders as Promise<any>

### ISSUE THREAD

**Issue by tomc974** [TypeStrong/typedoc#656]
For example, if you define a type alias like this `type T = Promise<object>`, TypeScript (in VS Code) correctly displays the type of T as `Promise<object>` but TypeDoc will render it as `Promise<any>`.

TypeScript version: 2.6.1
TypeDoc: 0.9.0

**Comment by aciccarello** [comment]
May be related to #571 and #572

**Comment by NaridaL** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/27608.

**Comment by aciccarello** [comment]
Great! I'll leave this open until we can confirm on a typescript nightly.

**Comment by aciccarello** [comment]
Confirmed that this was fixed upstream in #881.
