### ISSUE TITLE
How can I generate a list of classes?

### ISSUE THREAD

**Issue by dtgriscom** [TypeStrong/typedoc#657]
I'm using Typedoc in a Typescript project where there's a large number of source files in a hierarchy, with each file having one main class (along perhaps one or two supporting classes). Unfortunately, in the resulting HTML tree the only way I can find to get to a class is through the "Globals" list of "modules" (each being one file), then choose a file, then choose the class. I can't find any way of seeing just a pure list of classes. (I've tried both the "default" and "minimal" themes.)

Am I missing something? Generated a list of classes for an object-oriented language seems like such a basic need that I'm surprised it doesn't happen by default.

Thanks,
Dan

**Comment by dtgriscom** [comment]
And, I figured it out. The default "mode" value is "modules"; by changing this to "file" the index page generated a list of all the classes.

(I'll close this, but consider it as a request for better documentation.)

**Comment by gp187** [comment]
Is there any way to group them? I saw `@categories` notation in the docs by it doesn't seem to group anything
