### ISSUE TITLE
Allow specifying typedoc options in tsconfig.json

### ISSUE THREAD

**Issue by dtgriscom** [TypeStrong/typedoc#658]
When I'm working on a given project with tools, I'd rather not have to specify command line arguments for the tool. It makes my work quicker, as well as making it easier for other developers to do the same work. So, I put as many `typedoc` configuration items as possible into the `tsconfig.json` in the project's root directory.

Problem: tsconfig requires that you specify the project to be analyzed on the command line. Yes, it isn't a big deal to type `typedoc .`, but given that `typedoc` happily looks for a `tsconfig.json` in the current directory, it would be great for it to either allow specifying the project in the `tsconfig.json` file, or just assume that if no directory is specified then the current directory is to be analyzed.

**Comment by aciccarello** [comment]
Hello @dtgriscom. This should already be available via an (undocumented) `typedocOptions` object in your `tsconfig.json`. There is also an option to have a separate project configuration file, though this needs some work. See the discussion in #604 for more information.

I'll leave this open until the documentation issue is resolved.

**Comment by christophehurpeau** [comment]
You can use the option `--tsconfig` for a specific tsconfig file:

```bash
typedoc --out docs --tsconfig tsconfig.doc.json
```

> tsconfig.doc.json

```
{
  "extends": "./tsconfig.json",

  "exclude": [
    "src/**/*.test.ts",
  ]
}

```
