### ISSUE TITLE
@inheritdoc also for classes?

### ISSUE THREAD

**Issue by emmanueltouzery** [TypeStrong/typedoc#660]
currently as far as I can tell, if you have an interface and a class implementing it, and if you want not to have to copy-paste the apidoc between both, you can put the apidoc on the interface, then put:

```
/**
 * @inheritdoc
 */
```

on each relevant method in the class.

that's useful, but it seems to work only for interfaces, not for abstract classes for instance. I think that would be useful also in these other contexts.

**Comment by kraenhansen** [comment]
I have successfully changed the tslint.json to accept

```
/**
 * @inheritdoc
 */
```

as a valid way of completing the docs for a method.

See https://palantir.github.io/tslint/rules/completed-docs/ - but use `existence` instead of `exists` (the docs have been fixed but not published yet). This is a part of my tslint.json:

```
        "completed-docs": [
            true,
            {
                "classes": { "visibilities": ["exported"] },
                "enums": { "visibilities": ["exported"] },
                "enum-members": { "visibilities": ["exported"] },
                "functions": { "visibilities": ["exported"] },
                "interfaces": { "visibilities": ["exported"] },
                "properties": { "privacies": ["public", "protected"] },
                "methods": { "privacies": ["public", "protected"], "tags": { "content": {}, "existence": ["inheritdoc"] } },
                "types": { "visibilities": ["exported"] },
                "variables": { "visibilities": ["exported"] }
            }
        ]
```

**Comment by Gerrit0** [comment]
In TypeDoc 0.21.1 (and likely for a while, haven't touched this code in a good bit), if you do not specify a comment, TypeDoc will automatically inherit doc comments if you add no comment to the class. I think this meets the need in this issue:

```ts
export interface Foo {
    /** docs for prop */
    prop: string;
}

export class FooImpl implements Foo {
    prop = 'prop' // docs from the interface will show up here too
}
```
