### ISSUE TITLE
Generated readme.md does not format the first line of the file if it is a header

### ISSUE THREAD

**Issue by JasonKaz** [TypeStrong/typedoc#662]
Using Typedoc 0.9, Typescript 2.4.1.

I tried to use an H1 header on the first line of the readme file but it did not seem to format it into a proper header:

![image](https://user-images.githubusercontent.com/959848/34003344-0a6a85d2-e0c3-11e7-9939-eb33944e7a50.png)

Putting a newline first does allow it to render though:
![image](https://user-images.githubusercontent.com/959848/34003385-29f03bb8-e0c3-11e7-9c30-e913fd1bcba6.png)

Seems to happen with all header weights.

However other formatting does seem to apply:
![image](https://user-images.githubusercontent.com/959848/34003556-92cecd16-e0c3-11e7-9174-ee9f44b543dc.png)

**Comment by aciccarello** [comment]
Sorry, I couldn't reproduce this so I'm going to close. Can you try checking the latest version of TypeDoc? If still doesn't work we can reopen the issue.
