### ISSUE TITLE
Add content to globals.html page?

### ISSUE THREAD

**Issue by fr0** [TypeStrong/typedoc#665]
I'd like to add markdown or HTML content to the rendered `globals.html` page (see attached screenshot). Is this possible?

![screen shot 2017-12-20 at 10 29 29 am-edited](https://user-images.githubusercontent.com/435418/34215050-36675fee-e572-11e7-95a8-08fc8b2b6db3.png)

Thanks for the awesome work so far!

**Comment by aciccarello** [comment]
@fr0 The usual place for adding content is the documentation home page which takes a markdown file. What would be your use case to add content to the globals listing?

**Comment by fr0** [comment]
Thanks for the response.
There are two reasons why I want this:

1. The globals page seems to be linked to everywhere (see screenshot), so when I'm navigating around, that is where I return to most of the time. There's only one way to get back to the home page, and that's the link at the very top.

![screen shot 2017-12-20 at 12 54 33 pm-edited](https://user-images.githubusercontent.com/435418/34221191-21cde090-e585-11e7-868c-cc89a495731c.png)

2. How can I add links in my readme markdown file to classes in my library? If I just link to `/docs/classes/foo.html`, then those end up as dead links when my `README.md` is viewed from GitHub, which is no good. Is there a way to add content to the home page dynamically, only when viewed from TypeDoc?

**Comment by aciccarello** [comment]
Seems like it would be helpful if it was easier to go to the home page. So currently it is just the link at the top of the page that gets you back to the homepage but I wouldn't be opposed to putting it in the list of links to the right.

As far as the issue with links in your readme, there are two options. One is that you make your links absolute urls (e.g. http://mywebsite.com/docs/classes/foo.html) or have a separate docs specific readme that you pass to TypeDoc using the `--readme` option.

Do those two solutions cover your use cases adequately?

**Comment by fr0** [comment]
I wasn't aware of the `--readme` feature -  it definitely helps to cover my case. If you made it easier to get back to the home page, I'd consider this problem 100% solved.

Thanks for the help!

**Comment by aciccarello** [comment]
Great! I've created a separate issue for making the homepage easier to access so I'll close this one.
