### ISSUE TITLE
Make readme/homepage as easy to access as Globals

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#667]
The globals page is linked in the breadcrumbs and in the right nav. The readme is only linked to at the very top of the page. It should be easier to get to the home page. One simple solution would be to add a link in the right nav.

This issue is extracted from #665

**Comment by Gerrit0** [comment]
I believe this has been resolved via the introduction of the [titleLink](https://typedoc.org/guides/options/#titlelink), [navigationLink](https://typedoc.org/guides/options/#navigationlinks), and [sidebarLinks](https://typedoc.org/guides/options/#sidebarlinks) options.
