### ISSUE TITLE
Either update or remove http://typedoc.org/api/

### ISSUE THREAD

**Issue by mootari** [TypeStrong/typedoc#668]
The generated API documentation for TypeDoc hasn't been updated in over a year. In addition it doesn't seem to be linked anywhere, which makes it only discoverable through Google.

Please either regenerate the API docs for the current source or remove them completely, because outdated docs tend to do more harm than good.

**Comment by aciccarello** [comment]
Yep, I'm hoping I'll be able to do some of this over the Christmas break.

Closing in favor of TypeStrong/typedoc-site#2

**Comment by mootari** [comment]
API pages have been updated (#460).
