### ISSUE TITLE
Clarify reason for casting to ts.Node in FunctionConverter.convert()

### ISSUE THREAD

**Issue by mootari** [TypeStrong/typedoc#669]
I'm currently compiling information about all TypeDoc events and noticed that in [FunctionConverter.convert](https://github.com/TypeStrong/typedoc/blob/v0.9.0/src/lib/converter/nodes/function.ts#L41) the passed node gets cast to `ts.Node`. I can see no reason why the node isn't passed through as is (`ts.FunctionDeclaration` or `ts.MethodDeclaration`), because [ConstructorConverter](https://github.com/TypeStrong/typedoc/blob/v0.9.0/src/lib/converter/nodes/constructor.ts#L49) already passes a `ts.ConstructorDeclaration` node.

Is this casting still required?

**Comment by Gerrit0** [comment]
There's no reason to cast here, we should probably turn on https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/, as there are extra type assertions in quite a few places.
