### ISSUE TITLE
Why is some of my own code "external"?

### ISSUE THREAD

**Issue by deap82** [TypeStrong/typedoc#673]
I have a few *.d.ts files in my project that I wanted to include in my docs, so I added the `includeDeclarations` flag in my typedoc config.

That caused all definition files in node_modules to also be included, which is undesired. So I added the `excludeExternals` flag.

It removed the stuff from node_modules, as wanted, but caused some of my very own classes in the project not to be included.

One such case was a file that had two classes. I split them to two separate files which caused one but not the other to be part of my docs site.

I have also tried different combinations using the `exclude` and `externalPattern` settings but can't get it right.

I have also tried `typedoc-plugin-internal-external` (https://github.com/christopherthielen/typedoc-plugin-internal-external) to actively mark affected class as internal, but it's not making any difference. (And it would be nice to avoid having to do that.)

**Why is my own code considered external by typedoc?** When I remove `excludeExternals` from config these classes are still considered external when toggling the checkbox in the generated site.

This is one very simple class that has the problem (the file has no imports):
```
export class LoadingbarEvents {
    public static Start: string = "vk:loadingbar:start";
    public static Stop: string = "vk:loadingbar:stop";
}
```
This is my current typedoc config:

```
var typedocConfig = {
    theme: "dev-docs/ts/theme-composed",
    disableOutputCheck: true,
    readme: "dev-docs/ts/INDEX.md",
    name: "My project name",
    excludePrivate: true,
    exclude: '**/node_modules/**',
    includeDeclarations: true,
    excludeExternals: true,
    mode: 'file',
    out: "dev-docs/sites/ts",
    verbose: true
};
```

I'm using gulp-typedoc to run typedoc.

**Comment by deap82** [comment]
I decided to do some digging around in the typedoc code base and here is what I found:

The `isExternal` flag is set like this:
https://github.com/TypeStrong/typedoc/blob/32bf5289fc7742c6c2e80b786b298987e5336aaa/src/lib/converter/context.ts#L220

At that point in the code I found that the paths in `this.fileNames` are all absolute paths, while *some* of the `node.fileName` values are not. This matched the code items not included in my docs site.

After some more digging around I found that the node.fileName originates from this piece of code in converter.ts;
https://github.com/TypeStrong/typedoc/blob/32bf5289fc7742c6c2e80b786b298987e5336aaa/src/lib/converter/converter.ts#L357-L359

`sourceFile` is `node` in the previous snippet.

The `program` constant is assigned in the same file:
https://github.com/TypeStrong/typedoc/blob/32bf5289fc7742c6c2e80b786b298987e5336aaa/src/lib/converter/converter.ts#L274

The `fileNames` list sent to `ts.createProgram` are all absolute paths. So something happens in the typescript package because in the return from `getSourceFiles()` some of the paths are not absolute any more.

I tried my best at digging around also in the typescript source code as well, but then resorted to try to fix it within typedoc instead. 

See my changes here: https://github.com/deap82/typedoc/commit/c420f132f6ca3baeb008587443e0bcb57db9446a

I'm not entirely sure it's PR ready, I'd need some insight into how this might affect other config options than the ones I have or alternatively some help with digging around more in the typescript package and raise an issue there.

**Comment by mootari** [comment]
@deap82 Perhaps you can tweak `baseUrl` or `paths` in the `compilerOptions` passed to typedoc?

**Comment by deap82** [comment]
@mootari,
Thank you for your input, **but I'm not sure what you mean I should try**.

My `baseUrl` is currently `.` and I don't use the `paths` setting. The `baseUrl` as `.` is required to be able to combine node module resolution while imports of my own files still can start at app level (OR be relative). (Without baseUrl all imports of my own files would have to be relative, which complicates refactoring and moving around files).

For some of my affected files I tried to define paths like this, but it didn't help (and seems redundant):
```
		"paths": {
			"app/services/app-service": ["app/services/app-service"]
		},
```

Even if this worked in some way (even with sending separate compilerOption config to typedoc then what I have for my ts build) it seems tedious and will lead to me and my team forgetting to document stuff because it's not part of the docs site.

I also tried to find some common denominator between the files that the typescript package "changes" the path on, but I can't seem to find one.

- Some of the files are never imported in another file (Aurelia custom elements that are instead referenced as global resources in main.ts file).
- Some of the files are imported in other files with a path relative to the baseUrl.
- Some of the files are imported in other files with a path relative to the current file.
- Some of the files contains classes with only static members.
- Some of the files has no export, some has a single export and some has multiple exports.

A few of these cases I tried to "flip around", but typedoc still gets the relative path from typescripts `program.getSourceFiles()`.

I tried looking into making a typedoc-plugin out of this instead, but it seems to me there is no appropriate event where I could manipulate the path at the right time, like I'm doing in my fork.

Maybe I should extend my fork to include a new config flag (`ensureAbsolutePaths` [boolean]) for this path manipulation to take place (so it doesnt cause unexpexted behaviour for others)?
**Would that approach lead to an acceptable PR?** 

I also thought of removing the dependency on `compilerHost.currentDirectory` and instead compare the paths with the original `fileNames` list, where all paths are absolute. I.e; If a path is found to be a substring of a path in `fileNames` then use the path from `fileNames`.

It would be interesting if other users of TypeDoc could check if they actually have internal files/code items that are hidden when they untick the external checkbox in their docs site. It seems strange if I'm the only one with this issue... O:-)

**Comment by mootari** [comment]
> Thank you for your input, but I'm not sure what you mean I should try.

I'm just grasping at straws, because I read in a TS issue that the behavior changed in the last few versions.  Unfortunately I'm not actually using Typescript directly, so my experience is limited.

For what it's worth, I did the following to have a d.ts as main entry point:
```javascript
const config = {
  source: 'babylon.d.ts',
  target: 'build',
};
const app = new Application({
  // ...
  includeDeclarations: true,
  excludeExternals: true,
  mode: 'modules',
  entryPoint: [path.basename(config.source), 'BABYLON']
});
app.generateDocs([config.source], config.target);
```

**Comment by deap82** [comment]
Hmm... I’m not using this `entryPoint` setting at all. I’m using gulp to pipe all *.ts files under a certain folder level to typedoc... within that folder structure there are some *.d.ts files I want to include, which I achieve with the `includeDeclarations` flag.

What do you mean with not using typescript directly? Can you use typedoc without typescript?

**Comment by mootari** [comment]
> What do you mean with not using typescript directly? Can you use typedoc without typescript?

Yup, I'm only using the [npm package](https://www.npmjs.com/package/typedoc) to generate documentation for [babylon.d.ts](https://github.com/BabylonJS/Babylon.js/blob/master/dist/babylon.d.ts). I never write any actual typescript.

**Comment by deap82** [comment]
I've created a plugin to workaround this issue for now. https://github.com/deap82/typedoc-plugin-ensure-internal

**Comment by Gerrit0** [comment]
In 0.20, the "external" distinction is determined purely by the location of the symbol being documented, instead of being a somewhat magical combination of what was provided as input files and the external pattern.
