### ISSUE TITLE
Potential security vulnerabilities in your dependencies

### ISSUE THREAD

**Issue by nidsharm** [TypeStrong/typedoc#676]
Hi, 

My team works on [AWS Amplify](https://github.com/aws/aws-amplify) and typedoc is a dev dependency that we consume for our packages. 

We got a notification about a security vulnerability in one of your dependencies -> marked package which requires an update from version 0.3.5 to 0.3.9. I have forked your package currently to update the dependency. 

Is there an ETA as to when the update will be done on the package or can we submit a pull request for the same? 

Thanks,
Nidhi

**Comment by edsilv** [comment]
I've got the same issue, removing typedoc from my project until fixed.

**Comment by Gerrit0** [comment]
Related: #675

**Comment by Gerrit0** [comment]
Resolved with 6cfeec0bd26049afb6f42b89dcc6ca2dbac146ff
