### ISSUE TITLE
Add interface for Application options

### ISSUE THREAD

**Issue by demurgos** [TypeStrong/typedoc#677]
Hi,
I am trying to use the Node API of Typedoc. My issue is that the options for the constructor of the `Application` class are not documented as a Typescript interface but just as `Object`. This makes it harder to use.
Could you add an interface for the application options?

This is the corresponding line:
https://github.com/TypeStrong/typedoc/blob/32bf5289fc7742c6c2e80b786b298987e5336aaa/src/lib/application.ts#L96

**Comment by mootari** [comment]
The options are for the most part provided by plugins. You can find an overview here: https://gist.github.com/mootari/d39895574c8deacc57d0fc04eb0d21ca#file-options-md

**Comment by demurgos** [comment]
Thanks for the link, but I still think that this is a valid issue. Your link lists options that are not mentioned in the readme (`listInvalidSymbolLinks`, `disableOutputCheck`) and I couldn't find any link to this Gist from the official repo or website.
When I was checking the source code, I got the feeling that you were using some custom way to define the options. This may not be a high priority issue, but why not use Typescript's standard features to declare the options?
With the various type operators, you could still have something expressive supporting the plugin-based organization of your code (`export type Options = ConverterOptions & RendererOptions & ...` for example).

**Comment by mootari** [comment]
> Thanks for the link, but I still think that this is a valid issue.

I didn't mean to declare this issue invalid, I just wanted to give you something to start with.

>  Your link lists options that are not mentioned in the readme (listInvalidSymbolLinks, disableOutputCheck) and I couldn't find any link to this Gist from the official repo or website.

The typedoc docs are currently out of date. I went through the typedoc sources and compiled the gist to get an overview of the typedoc internals for myself. I'm neither an author nor member of typedoc.

**Comment by demurgos** [comment]
Ok, thanks and sorry for the confusion.

**Comment by Gerrit0** [comment]
In 0.16, there is now an interface for TypeDoc's options. The interface is technically stricter than what TypeDoc will accept and convert to the real option type, but it supports best practices.

https://github.com/TypeStrong/typedoc/blob/67987ad23bbb8bfaefbc0ed8cc237f9c5c30d9c2/src/lib/utils/options/declaration.ts#L37-L81
