### ISSUE TITLE
Options Exclude and Verbose do not work properly ?

### ISSUE THREAD

**Issue by AlexDmr** [TypeStrong/typedoc#695]
Hi and thanks a lot for this software which is VERY useful !
I encounter two problems :
1) The --verbose option seems to be unavailable.
      ```
> typedoc --verbose
Error: Unknown option: verbose
```

2) But the most annoying for me is that the exclude option does not filter any file.
I try to generate documentation for a sub-part of my project. Directories are like that :
projectRoot
  - ts
    |- nf
    |- ui
  -node_modules

I generate documentation for projectRoot with
typedoc --mode file --out ./documentation --exclude ./ts/nf/Z*    ./ts/nf
or
typedoc --mode file --out ./documentation --exclude Z*    ./ts/nf

But in both cases file Z* are included in the documentation (and the definitions in them of course). Maybe I am wrong with how to specify exclude parameter ?

My system is windows 10
typedoc --version
TypeDoc 0.9.0

**Comment by aciccarello** [comment]
What  `--verbose` flag are you trying to use? I'm not aware of any TypeDoc or TypeScript flags like that.

For the exclude issues, try adding quotes around your minimatch glob to make sure your shell isn't expanding the glob automatically. I don't think that is usually a problem on windows but I'd like to rule it out.

**Comment by AlexDmr** [comment]
Well for the verbose option I took it from : http://typedoc.org/guides/usage/   at the end of the page.
About the quotes I tried :
typedoc --mode file --out ./documentation --exclude "./ts/nf/Z*"    ./ts/nf
or
typedoc --mode file --out ./documentation --exclude "Z*"    ./ts/nf

both do still includes the files.

**Comment by aciccarello** [comment]
Ah, yeah. The verbose option was removed in bcbf54f. The exclude option can be a bit difficult and the documentation could definitely be improved. I'll have to experiment with it a little to try to figure out what your problem might be. If you have a public repo I could see that would be very helpful.

I've created TypeStrong/typedoc-site#6 to remove the documentation for `--verbose`

**Comment by EliteXXL** [comment]
Hi, I've got a similar problem. I have the path excluded in the tsconfig.json, but it still includes the files. I have a public repository where test it: https://github.com/EliteXXL/advanced-router

**Comment by AlexDmr** [comment]
Hi, I did put a minimal example here :
https://github.com/AlexDmr/minimalTypedocCounterExample

I added an issue so you can see what I tried.
Thanks for your help !

**Comment by aciccarello** [comment]
Thanks for the repos. I'll try to take a look this week.

**Comment by aciccarello** [comment]
Thanks for the comments. I'm going to close this in favor of #839 and TypeStrong/typedoc-site#6 since these are two separate issues.
