### ISSUE TITLE
mathjax support

### ISSUE THREAD

**Issue by lab4quant** [TypeStrong/typedoc#697]
Hello, I would like to comment using [mathjax](https://www.mathjax.org/), so generated document could be displaying math equations properly

How can I do this with `typedoc`?

e.g.
```
/**
 *  $\sum_{i=0}^n i^2 = \frac{(n^2+n)(2n+1)}{6}$
 */
```
thanks!

**Comment by aciccarello** [comment]
Hello, a specialized use case like that sounds like a good place to use a custom plugin. There isn't much documentation but you could look at some of the plugins listed in the readme for inspiration.

**Comment by lab4quant** [comment]
@aciccarello , thanks for your update, i might need to do something on generated html file

**Comment by terrible-coder** [comment]
I am looking to write maths equations in the comments too. I tried looking up the currently available plugins for typedoc but I did not find one for mathjax or latex style maths equations. Did someone find a solution/work around?
