### ISSUE TITLE
Flow Support Question

### ISSUE THREAD

**Issue by moronzinc** [TypeStrong/typedoc#698]
Hi Folks,

I used Typedoc to generate documentation at my old job but my current company only supports Flow.  I was wondering if anyone could give me a good sense if it's possible to modify Typedoc to support Flow types and how much work it would take to do this. I really like the layout of the documentation that Typedoc generates along with the hierarchies so I'd love to scope this out.

Thanks!

**Comment by aciccarello** [comment]
Hello @moronzinc, TypeDoc uses the TypeScript compiler to parse documentation. If you would like to use it to generate docs for your project you need to be able to compile your project with TypeScript. You can use the `ignoreCompilerErrors` flag to avoid fixing every compilation error, but this isn't guaranteed to work.

You might want to look into tools that can migrate Flow code to TypeScript, even if just for the documentation step. Alternatively, you might want to use JSDoc, either with a Flow plugin or by stripping types with `flow-remove-types`.

- [flow-to-typescript](https://github.com/bcherny/flow-to-typescript) (alpha)
- [flow-jsdoc](https://github.com/Kegsay/flow-jsdoc)
- [flow-remove-types](https://flow.org/en/docs/tools/flow-remove-types/)
- [documentation.js](https://github.com/documentationjs/documentation)
