### ISSUE TITLE
show type parameters

### ISSUE THREAD

**Issue by KiaraGrouwstra** [TypeStrong/typedoc#702]
I was trying to use `typedoc` to make documentation for type parameters.
It appears for generic functions (`function f<T extends string>(): T`) info on type parameters shows up automatically.
For generic types (`type F<T extends string> = T`) however, it appears they do not show up, while `@param` tags are also lost in the docs.
I wouldn't mind doing a PR for this, but I'm not sure where to look just yet. Might anyone here know?

**Comment by pirix-gh** [comment]
Bump. Any news?

If it can help. This works (workaround):
``` ts
/** Type description
 * @typeparam <A1> **A1** Description is carried over, it works
 */
export type Type<A1, A2> =
    A1 extends A2
    ? A1
    : A2
```

**Comment by Gerrit0** [comment]
Millsp's solution is the intended way of documenting type parameters, I don't fully understand what problem is being reported in the OP...
