### ISSUE TITLE
Search.js get's weird characters added to it.

### ISSUE THREAD

**Issue by jeroen1602** [TypeStrong/typedoc#708]
When generating documentation for the search.js file will have weird characters appended in front of it.

# Debug results
Manually removing the weird characters does make the js-file readable again for webbrowsers.

# Steps to reproduce
 -  Execute `$ typedoc --target ES6 --out ./docs/ ./src` 
 -  Look in the assets/js/search.js file

# Expected Behavior
It should generate a correct search.js file that a webbrowser can read.

# Actual Behavior  
The file that the command creates has these characters appended to it  
`ï»¿var typedoc = typedoc || {};`

# System details
 - OS: Windows 10 64-bit
 - `$ node -v ` v9.2.1
 - `$ npm -v` 5.6.0
 - `$ typedoc -v` TypeDoc 0.10.0 Using TypeScript 2.7.1

**Comment by aciccarello** [comment]
Thanks for the report. Should be fixed by #705 when merged.
