### ISSUE TITLE
Typedoc not exporting lazy-loaded modules

### ISSUE THREAD

**Issue by mboughaba** [TypeStrong/typedoc#709]
Hello guys,

I really like this plugin for its simplicity and powerful features. Thank you for putting it all together  ❤️  

I noticed a small problem which I am not sure how to tackle.

When module is lazy loaded, Typedoc will not generate its documentation. 
Any idea how can I solve this, should we create a new Typedoc plugin to support that? Please do not hesitate to provide some tips on how I could work on this and eventually make a PR.

for minimal reproducer check:
https://stackblitz.com/edit/angular-gitter-ya7thg

*Code has to be run locally with Typedoc*

Here is my configuration in `tsconfig.json`
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "typedocOptions": {
    "exclude": "**/*.spec.ts",
    "ignoreCompilerErrors": true,
    "mode": "file",
    "module": "commonjs",
    "moduleResolution": "node",
    "out": "doc",
    "preserveConstEnums": true,
    "suppressExcessPropertyErrors": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "ES5",
    "theme": "default"
  }
}
```

documentation task in `package.json`
```json
    "docs": "npm run typedoc src/main.ts",
    "typedoc": "typedoc"

```

**Comment by aciccarello** [comment]
Hello @mboughaba, this is expected. The way TypeDoc works is that it takes the files that TypeScript parses. Angular's lazy loading uses a string to indicate where a module is without importing it so TypeScript does not parse those files.

If you want to document a lazy loaded module, either point TypeDoc to it directly or create a file which imports the main and lazy loaded modules.

```TypeScript
// next to main.ts
import './main';
import './app/lazy/lazy.module';
```

**Comment by mboughaba** [comment]
Hi @aciccarello Thanks a lot, it works as expected!
Do you think this is something I can document in the README in a faq or troubleshooting section?

**Comment by aciccarello** [comment]
I've marked this issue as a question. It is good that you brought it up because I can imagine other people could run into it. But hopefully they'll search the issues and find this.

I'm trying to think of what would actually be documented. It really just comes down to how TypeScript parses a project.
