### ISSUE TITLE
@ts-ignore not work for typedoc

### ISSUE THREAD

**Issue by iSpring** [TypeStrong/typedoc#717]
My project uses TypeScript. And I compile the project with `"webpack": "^3.3.0"`, `"typescript": "^2.6.1"` and ` "awesome-typescript-loader": "^3.4.1"`. 

In some cases, I need to use `__DEV__` to write conditional code. Like the following code snippet.
```
let activeInfo = this._uniformActiveInfosMap[name];
if (!activeInfo) {
    // @ts-ignore
    if (__DEV__) {
        // https://stackoverflow.com/questions/21911836/opengl-shaders-uniform-variables-count-incorrect
        let warningMessage = `uniform ${name} is not active for program ${this.type}`;
        if (!this._warningMessagMap[warningMessage]) {
            this._warningMessagMap[warningMessage] = true;
            console.warn(`uniform ${name} is not active for program ${this.type}`);
        }
    }
}
```

The value of `__DEV__` is defined by `webpack.DefinePlugin` in webpack.config.js.

vscode will show `Cannot find name __DEV__` error, so I add the comment `// @ts-ignore` and vscode doesn't show this error any more.

Unfortunately, when I use typedoc, the error `Cannot find name __DEV__` appears. It seems `// @ts-ignore` doesn't work for typedoc.

Here is the npm script of typedoc.
```
"doc:api": "typedoc --out _site src/"
```

typedoc vertion is `"typedoc": "^0.9.0"`

I know typedoc supports option `--ignoreCompilerErrors ` and it does work for my case. But I don't want to use this option because it will ignore all compile errors.

So, my question is how to make @ts-ignore works for typedoc.

Any comments are appreciated.

**Comment by aciccarello** [comment]
Hello @iSpring, TypeDoc uses it's own version of TypeScript due to tight bundling. I believe typedoc v0.9.0 was using TypeScript v2.5. Can you try again with the latest version of TypeDoc?

**Comment by iSpring** [comment]
Hi @aciccarello , thanks for your hint. typedoc 0.11.0 does honor `@ts-ignore`. Close this issue.
