### ISSUE TITLE
Requires upgrade of dependency; TypeScript v2.7.2

### ISSUE THREAD

**Issue by samchon** [TypeStrong/typedoc#718]
Current `TypeDoc` requires `TypeScript v2.7.1`. However, the `v2.7.1` has some critical errors and they're fixed in `v2.7.2`.
  - https://github.com/Microsoft/TypeScript/releases/tag/v2.7.2
  - https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+milestone%3A%22TypeScript+2.7.2%22+label%3A%22fixed%22+

**Comment by giladgray** [comment]
@aciccarello any update on this? the fixes in 2.7.2 are critical.

**Comment by aciccarello** [comment]
@giladgray Sorry, I'm a bit swamped right now but I'll try to get out a release before next week.

**Comment by aciccarello** [comment]
Released in 0.11.1
