### ISSUE TITLE
Typedoc does not play well with alias type arguments

### ISSUE THREAD

**Issue by guilhermevrs** [TypeStrong/typedoc#729]
Hi

I was playing with the parsing capabilities from typedoc on my codebase and I found a possible issue.
How do I use:

```
const app = new Application(typedocOptions)
app.convert(listOfFilePaths);
```

Consider the following case:

in package _core_
```
export interface IContextInput {
  [key: string]: any;
};

export type IContext<T extends IContextInput, U extends IContextInput = {}> = {[P in keyof T]: T[P]} & {[C in keyof U]: U[C]};
```

in package _main_
```
import {IContext, IContextInput} from "core";

interface TestInput extends IContextInput {
     param: boolean;
}

interface TestContext extends IContext<TestInput> {}
```

I can't get the information I want for extendedTypes, like "this interface extends IContext with type argument TestInput"

I have tried to debug a little bit the code and got to ``Converter.convertType`` method. The type object contains the information I want:

![image](https://user-images.githubusercontent.com/1570567/37969478-23c28dfe-31d1-11e8-9045-29fe09829299.png)

And it gets into the ``UnionIntersectionConverter`` (because the union in ``IContext``).

So extendedTypes get:

![image](https://user-images.githubusercontent.com/1570567/37970423-bccafe44-31d3-11e8-87f4-4ee4a1f6b9b9.png)

**Comment by Gerrit0** [comment]
0.20 has improved support for this, along with a large number of other things. Rendering the example in the OP, I see:

![image](https://user-images.githubusercontent.com/19329837/103248718-23eaa880-4929-11eb-803b-a6601f4bd568.png)
