### ISSUE TITLE
Keep different versions of documentations

### ISSUE THREAD

**Issue by vinz243** [TypeStrong/typedoc#737]
HI, It would be great if we could keep differents versions (either only majors or minors) of documentations in the same folder, and developers would be able to select the version they are using

Thanks

**Comment by aciccarello** [comment]
@vinz243 This would be a great feature! How would you expect TypeDoc to know what versions to show/generate?

**Comment by vinz243** [comment]
I guess it could use tags to detect which version to generate docs for. However this would also means that the version would first need to be tagged, so this would not work except if the docs are on another branch (like gh-pages). Another solution would be like, tagging the newly generated docs as 'current', and the previous one using tags maybe? There could be a CLI option too like `--targetVersion 4.2.0` to select a version (then `current` and `4.2.0` would have same docs)

**Comment by balupton** [comment]
We have https://github.com/bevry/awesome-travis/blob/master/scripts/surge.bash which deploys the repo for each commit, branch, and tag.

For instance, for https://github.com/bevry/editions you can see the docs for master at http://master.editions.bevry.surge.sh/docs/ or the docs for v1.3.4 at http://v1.3.4.editions.bevry.surge.sh/docs/

I made a scaffolding tool to do all the setup automatically at https://github.com/bevry/boundation - which today I added typescript and typedoc support.

**Comment by Gerrit0** [comment]
Benjamin's solution is the best one here, while TypeDoc could theoretically support merging docs for different versions, it is a large amount of complexity for a fairly small benefit. Keeping separate versions yourself also provides the flexibility to decide when documentation should be updated.

**Comment by thislooksfun** [comment]
I just (mostly) solved this issue in my own workflow as documented [here](https://github.com/thislooksfun/snoots/issues/9#issuecomment-799034893), complete with automatic symlinks to the latest versions. It's semi-specific to my use-case right now, but I could easily abstract it out to its own action if people would be interested.
