### ISSUE TITLE
Reference link is lost when merging namespace

### ISSUE THREAD

**Issue by fvoronin** [TypeStrong/typedoc#738]
For example, we have two simple modules:

**ObjectEditor.ts**
```typescript
import "Options";

class ObjectEditor  {
    static defaultOptions: ObjectEditorNs.Options = {
        title: undefined,
        type: undefined,
    }

    constructor(options?: ObjectEditorNs.Options) {
    }
}

export = ObjectEditor;
```

**Options.ts**
```typescript
declare namespace ObjectEditorNs {
    export interface Options {
        title?: string;
        type?: string;
    }
}
```

And Typedoc's out:

![class objecteditor](https://user-images.githubusercontent.com/1442281/38304613-7ba9b526-3823-11e8-8ae8-1cb8a975f8e8.png)

Constructor parametr has **link** to `Option` interface.

Lets add extension to `Option` interface

**ObjectEditorExt.ts**
```typescript
declare namespace ObjectEditorNs {
	interface Options {
		skip?: boolean;
	}
}
```

And now Typedoc lose link to `Option`:

![class objecteditor no link to options](https://user-images.githubusercontent.com/1442281/38304953-8bd8f3de-3824-11e8-8652-a8a94b8e6966.png)

**Comment by aciccarello** [comment]
Yes, namespace merging does not work very well. This probably won't work with your project, but is a link created when using `--mode modules`? In file mode where would you expect the link to go to?

**Comment by fvoronin** [comment]
Yes, we use `--mode modules` for our project. And I use it for that example.
In `file` mode Typedoc generate link for constructor `Options` parameter in first case of the example. In second case, for extended `Options`, Typedoc miss again reference to `Options` interface description. But if we look at the Module `ObjectEditorNs` we saw `Options` interface

![image](https://user-images.githubusercontent.com/1442281/38324283-433d264c-3859-11e8-8d18-5c39bf325715.png)

Thats has **3** properties, defined in 2 different files:

![image](https://user-images.githubusercontent.com/1442281/38324448-c859dc44-3859-11e8-98b4-eec83b17c483.png)

And it's look better than in `modules` mode result, where we have **2** separate `Options` description pages.
