### ISSUE TITLE
Deconstructing arguments missing defaults in the generated docs.

### ISSUE THREAD

**Issue by Mike96Angelo** [TypeStrong/typedoc#740]
Example:
=======
```
function myFunc({
    a = 'test', 
    b = 42
}: {
    a?: string
    b?: number
}) {
    // some code
}
```
Generates this documentation:
=======================

**myFunc(__namedParameters: object): void**
*Parameters*

 - __namedParameters: object
   - a?: string
   - b?: number

*Returns* void

When it should generates this documentation:
==================================

**myFunc(__namedParameters: object): void**
*Parameters*

 - __namedParameters: object
   - a?: string = 'test'
   - b?: number = 42

*Returns* void

**Comment by Gerrit0** [comment]
Marking this as a wontfix. Recursing into objects to find defaults has the potential to be entirely too complicated. Parameters can have defaults, but options within that having defaults is really an implementation detail. I should be able to change the default from a number to a `unique symbol` if I need to determine if it was set in the method body, without requiring a change to the signature. If it needs to be documented, it should be described in the function's comment.

```ts
export function foo({ x: { y: { z = 2 } } });
// I should be able to change to this with no doc output change
export function foo({ x: { y: { z = someSymbol } } });
```
