### ISSUE TITLE
Typedoc generates broken links to Type Aliases

### ISSUE THREAD

**Issue by dkent600** [TypeStrong/typedoc#748]
Typedoc generates broken links to Type Aliases. For example, Type Aliases documents end up in: "api/README/#[typename]" but the links are generated to: "api/interfaces/README/#[typename]"

**Comment by aciccarello** [comment]
@dkent600 Thanks for the report. Do you have an example so we can reproduce this? I'm confused why `README` is in your URL.

**Comment by dkent600** [comment]
Hi @aciccarello Any luck reproducing this?

**Comment by Gerrit0** [comment]
Closing this as I can't repro - the linked project appears to have been deprecated for a while and all the links are broken.
