### ISSUE TITLE
Error compiling d.ts: An error occurred while creating reflections for the current project

### ISSUE THREAD

**Issue by SergioMorchon** [TypeStrong/typedoc#75]
| <error>
 |   at <error>
 |   at visitFunctionDeclaration (C:\Program Files\nodejs\node_modules\typedoc\b
in\typedoc.js:2582:36)
 |   at visit (C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2246:
32)
 |   at C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2317:21
 |   at <error>
 |   at visitBlock (C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:
2316:28)
 |   at visit (C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2258:
32)
 |   at C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2362:21
 |   at <error>
 |   at visitModuleDeclaration (C:\Program Files\nodejs\node_modules\typedoc\bin
\typedoc.js:2356:21)

Error: An error occurred while creating reflections for the current project.
 | Please report this error at https://github.com/sebastian-lenz/typedoc/issues
 | including the following details:
 |
 | The error occurred while converting `WFL.Dialog.choose` in `wfl-1.d.ts` aroun
d line 1380:
 |  >          _/
 |  @         function choose<T>(message: string | Resources.Strings.IStringReso
urce, options: T[]): JQueryPromise<T[]>;
 |  >         /_*
 |  >          \* Abre un di├ílogo de selecci├│n de opciones.
 |  >          \* @param options Opciones del di├ílogo.
 |  >          \* @returns Promesa con la selecci├│n del usuario.
 |  >          */
 |  >         function choose<T>(options: Choose.IOptions<T>): JQueryPromise<T[]

> ;
>  |  >         module Query {
>  |  >             interface IOptions {
>  |  >                 /**
>  |  >                  \* Mensaje del di├ílogo.
>  |  >                  _/
>  |  >                 message: string | Resources.Strings.IStringResource;
>  |  >                 /_*
>  |  >                  \* Contenido inicial del valor del di├ílogo.
>  |  >                  _/
>  |  >                 content?: string;
>  |  >                 /_*
>  |  >                  \* Si el di├ílogo ser├í o no multil├¡nea.
>  |  >                  _/
>  |  >                 multiline?: boolean;
>  |  >                 /_*
>  |  >                  \* Indica si el contenido es v├ílido o no.
>  |  >                  */
>  |  >                 valid?: (value: string) => boolean;
>  |  >             }
>  |  >         }

**Comment by SergioMorchon** [comment]
Ps.: great debug system, I hope it is helpful for the typedoc project!

**Comment by sebastian-lenz** [comment]
Hi Sergio, thanks for reporting this. I guess you've split the error message, the stack trace belongs to an error before the code snippet I guess. Could you check the output again and paste the first error? It should consist of a code snippet followed by a stack trace.

Yes, I hope the new error output will help to find errors more quickly, as we see I should adjust the output to be more compatible with GitHub.

**Comment by SergioMorchon** [comment]
It first stops here:

Error: An error occurred while creating reflections for the current project.
 | Please report this error at https://github.com/sebastian-lenz/typedoc/issues
 | including the following details:
 |
 | The error occurred while converting `wfl-1.d.ts` around line 1236:
 |  >     }
 |  @     module Dialog {
 |  >         /**
 |  >          * Estado del di├ílogo.
 |  >          */
 |  >         enum EnumState {
 |  >             /**
 |  >              * El di├ílogo se encuentra desplegado.
 |  >              */
 |  >             Collapsed = 0,
 |  >             /**
 |  >              * El di├ílogo est├í minimizado.
 |  >              */
 |  >             Expanded = 1,
 |  >         }
 |  >         /**
 |  >          * Representa una acci├│n de di├ílogo.
 |  >          */
 |  >         class Action extends Disposable {
 |  >             /**
 |  >              * Texto de la acci├│n.
 |  >              */
 |  >             text: Resources.Strings.IStringResource;
 |  >             /**
 |  >              * Comando de la acci├│n.
 |  >              */
 |  >             command: ICommand;
 |  >             /**
 |
 | <error>
 |   at visit (C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2296:
29)
 |   at C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2310:25
 |   at Array.forEach (native)
 |   at visitBlock (C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:
2308:33)
 |   at visit (C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2258:
32)
 |   at C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.js:2362:21
 |   at Context.withScope (C:\Program Files\nodejs\node_modules\typedoc\bin\type
doc.js:1787:17)
 |   at visitModuleDeclaration (C:\Program Files\nodejs\node_modules\typedoc\bin
\typedoc.js:2356:21)
 |   at Object.visit (C:\Program Files\nodejs\node_modules\typedoc\bin\typedoc.j
s:2230:32)
 |   at Context.inherit (C:\Program Files\nodejs\node_modules\typedoc\bin\typedo
c.js:1824:28)

**Comment by sebastian-lenz** [comment]
Okay, I have no clue what's going on here. Could you send me a longer code snippet that I can test?

**Comment by SergioMorchon** [comment]
Hi!

Y re-executed the new version (npm 0.3.3) on the same d.ts file, and got:
>>> BEGIN OF ERROR DESCRIPTION

The error occurred while converting `wfl-1.d.ts` around line 1246:

```
      }
@     module Dialog {
          /**
           * Estado del di├ílogo.
           */
          enum EnumState {
              /**
               * El di├ílogo se encuentra desplegado.
               */
              Collapsed = 0,
              /**
               * El di├ílogo est├í minimizado.
               */
              Expanded = 1,
          }
          /**
           * Representa una acci├│n de di├ílogo.
           */
          class Action extends Disposable {
              /**
               * Texto de la acci├│n.
               */
              text: Resources.Strings.IStringResource;
              /**
               * Comando de la acci├│n.
               */
              command: ICommand;
              /**
```

```

```

<<< END OF ERROR DESCRIPTION

Maybe a carácter encoding issue?

The original file is UTF-8, and the code block is:
    module Dialog {
        /**
         * Estado del diálogo.
         */
        enum EnumState {
            /**
             * El diálogo se encuentra desplegado.
             */
            Collapsed = 0,
            /**
             * El diálogo está minimizado.
             */
            Expanded = 1,
        }
        /**
         * Representa una acción de diálogo.
         */
        class Action extends Disposable {
            /**
             * Texto de la acción.
             */
            text: Resources.Strings.IStringResource;
            /**
             * Comando de la acción.
             */
            command: ICommand;
            /**

**Comment by sebastian-lenz** [comment]
Hi Sergio, thank you for testing it again. Still no error stack trace, I think I have to remove the error output as it seems to produce more problems than helping us finding the error. Which node version are you using?

**Comment by SergioMorchon** [comment]
I'm with v0.10.32.

**Comment by jounii** [comment]
Getting similar issue with parsing phaser js phaser.d.ts file. Marked it as external, so no problem, however getting other crashes. Need to narrow down which files..

**Comment by sebastian-lenz** [comment]
Hi Sergio, the new TypeDoc version on npm now does not try to format the error output. Could you check if you receive a readable error message/stack trace?

**Comment by sebastian-lenz** [comment]
Version 0.3.6 is now on NPM, does this issue still exist? The new version reintroduces the <code>--verbose</code> option causing TypeDoc to output details of the reflection process, maybe this could help in narrowing down the problem.
