### ISSUE TITLE
Allow to pass github user/project from options

### ISSUE THREAD

**Issue by egoist** [TypeStrong/typedoc#753]
Currently it's using the output of:

https://github.com/TypeStrong/typedoc/blob/eff16996c653c3fbe960f9c25a76b0210f50801e/src/lib/converter/plugins/GitHubPlugin.ts#L51

However it might be not defined in a continuous deployment environment like netlify.com so the *link to source file* isn't working.

A flag like `--gitRemote https://github.com/user/project` would help.

**Comment by egoist** [comment]
Here's a workaround if you're using Netlify, run following command first in your build command:

```bash
git remote add origin git@github.com:$user/$repo.git
```

**Comment by aciccarello** [comment]
Sounds like a good suggestion. PRs are welcome. Should be able to add an option in that GitHubPlugin file.

**Comment by artentica** [comment]
Seems to already been implemented => https://github.com/TypeStrong/typedoc/pull/843
@aciccarello

**Comment by aciccarello** [comment]
@artentica That adds support for different github host names. I don't believe it supports different user logins though.

**Comment by artentica** [comment]
In seing the title i undestand it correspond to this: https://github.com/TypeStrong/typedoc/blob/eff16996c653c3fbe960f9c25a76b0210f50801e/src/lib/converter/plugins/GitHubPlugin.ts#L34
Wich is only few month old

**Comment by aciccarello** [comment]
True, I misunderstood this issue. I think the remaining issue is that that is pulled from `git ls-remote --get-url`. However, looking at the workaround @egoist posted, I do think that we should be able to close this.

**Comment by domoritz** [comment]
I don't think setting the remote is always enough. The issue is that different users may have different setups.
