### ISSUE TITLE
Output all references to a symbol in that symbol's entry?

### ISSUE THREAD

**Issue by tamethecomplex** [TypeStrong/typedoc#755]
Would it be feasible to use "find references" type functionality to output, along with a symbol (e.g. function, interface), every location that symbol is referenced within the codebase?

Similar question asked here: https://github.com/sverweij/dependency-cruiser/issues/46.  The purpose of this would be to enable cruising of a fine-grained symbol-wise dependency graph for better insight into how a symbol is used in a codebase.

**Comment by aciccarello** [comment]
Hello @tamethecomplex, that seems like a cool idea but it is probably outside the scope of this project.  That seems like information an IDE would be better equipt to provide.
