### ISSUE TITLE
@ignore doesn't work - only @hidden

### ISSUE THREAD

**Issue by cancerberoSgx** [TypeStrong/typedoc#761]
[here](http://typedoc.org/guides/doccomments/) it says 

> @hidden and @ignore  Keeps the subsequent code from being documented.

But only @hidden seems to work, I couldn't make @ignore work at all. 

If the solution is fixing the documentation I would do a PR but if it is fixing the implementation I'm not sure.

**Comment by aciccarello** [comment]
Thanks, the docs are actually ahead of the current release. `@hidden` will be added with the next release.

**Comment by joshua7v** [comment]
@aciccarello `@hidden` seems work, you mean `@ignore` will be added in next release right? So in next release, it could be possible to prevent some specific files being documented, am i right? Because there are some files (external modules) I don't want them to be exposed in the doc generated.

And, do you have time estimation on next release?

**Comment by aciccarello** [comment]
Yes, sorry. I had them backwards :grinning: But the two do the same thing. I believe it works on a symbol level so you can ignore a class or method or variable from being documented.

I'm not sure when I can make another release but I was able to get some work done this week.

**Comment by joshua7v** [comment]
@aciccarello Yeah, I know it's already work on symbol level. Just wonder if there's a way to ignore a file. For now, I have to add `@hidden` to every symbol in a file if I don't want it to be documented. And although nothing in a module is documented, the file itself will still show up in the document site.

So, in my case, all I want is to ignore the file, and make it don't show up in the generated site. Maybe I can customize a theme to achieve this, like filter out files if no doc is under this file?

**Comment by aciccarello** [comment]
@joshua7v  Try the [`--exclude` option](http://typedoc.org/guides/usage/). I'm not 100% sure this is what you are looking for but it could work.
