### ISSUE TITLE
@event tag does not work with `--json` option

### ISSUE THREAD

**Issue by huangyingjie** [TypeStrong/typedoc#763]
I run this command
````ts
typedoc --theme node_modules/typedoc-clarity-theme/bin --json _site/docjson src
````
and my tag is
````ts
    /**
     * some constructor
     * @param options
     * @event mapLoaded
     */
    constructor(options: Options) {
````
Then I cannot find string `mapLoaded` in _site/docjson.

typedoc version: 
TypeDoc 0.11.1，Using TypeScript 2.7.2

-----------
I have found example from typedoc's source code
````ts
    /**
     * Triggered before the renderer starts rendering a project.
     * @event
     */
    static BEGIN = 'beginRender';
````
Then another question comes, if `beginRender`'s callback has a parameter, how can I set its type?

**Comment by aciccarello** [comment]
Seems like an issue with serialization

**Comment by Gerrit0** [comment]
This seems to work correctly in 0.20, there are some `@event` tags in the tests which result in the expected change to the json output
