### ISSUE TITLE
Typedoc does not support the pnpm structure of node_modules

### ISSUE THREAD

**Issue by ghost** [TypeStrong/typedoc#776]
Since `pnpm` does not pollute the `node_modules` folder with peer dependencies this causes an issue when running `typedoc` with `pnpm`. In my case I get the following issue:
```
Using TypeScript 2.7.2 from /Users/near/Source/test/node_modules/.registry.npmjs.org/typescript/2.7.2/node_modules/typescript/lib
Error: /Users/near/Source/test/node_modules/@types/glob/index.d.ts(10)
 Cannot find module 'minimatch'.
```
I don't know whether this is a TypeScript issue or `typedoc` issue. If it's the latter than I'd appreciate if you can adapt your parsing of import statements to take into consideration that not all peer dependencies are straight in the `node_modules` folder. They are all in `node_modules/.registry.npmjs.org` assuming they are fetched from the generic npm registry. Each package has either soft or hard links inside its own `node_modules` folder which point to the correct package folder.

**Comment by aciccarello** [comment]
That looks like an issue with the glob types not typedoc

Related but I don't think it is the same DefinitelyTyped/DefinitelyTyped#11932

**Comment by aciccarello** [comment]
@cortopy Thanks for letting us know. Any tips on how to reproduce?

**Comment by cortopy** [comment]
@aciccarello thank for reopening the issue and your prompt reply!

I've [forked](https://github.com/cortopy/typedoc/tree/test-pnpm/examples/basic) an example to replicate:


## Steps to replicate
```
1. npm i -g pnpm
2. git clone git@github.com:cortopy/typedoc.git
3. cd typedoc/examples/basic
4. git checkout test-pnpm
5. pnpm i
6. npx typedoc --module commonjs --includes inc/ --media media/ --target ES5 --json json.json --out doc/ src/
```

You can find the `failing-fle.ts` in the `src` folder. It's using external packages. Basically those are the ones that were creating some issues for me

Although I should also point out that if you run `tsc` in that folder, the whole project build ok, no issues found

**Comment by Gerrit0** [comment]
This appears to been fixed, I just set up a project using pnpm and was unable to reproduce
