### ISSUE TITLE
Typedoc export 

### ISSUE THREAD

**Issue by oleksandr-dakal** [TypeStrong/typedoc#784]
There is the interfaces & classes that can't be imported from index.ts and can be very helpful:

- Component
- PageEvent
- RendererEvent

Can assist in preparing PR

**Comment by aciccarello** [comment]
Hi @oleksandr-dakal there isn't a good strategy for which classes and interfaces are exposed right now. I'd like to discuss this further before committing to making them publicly facing.

**Comment by Gerrit0** [comment]
Much, much, *much* later than I wanted to do this, but 0.22.0-beta.4 exports nearly everything even indirectly exposed in the API.

The not exported values that I expect to stick around for a bit are:

https://github.com/TypeStrong/typedoc/blob/20149bbda7eaf7395070441cb9ecdc31e2c4e00a/.config/typedoc.json#L3-L14
