### ISSUE TITLE
Type definitions for JSON serialization

### ISSUE THREAD

**Issue by GerkinDev** [TypeStrong/typedoc#789]
Hi,

I'm trying to use the documentation in JSON format to generate my documentation. I'm looking for the type definitions to type the imported JSON file. Where can I find them ?

Thank you !

**Comment by GerkinDev** [comment]
Oops, I'm feeling dumb right now, I didn't see this repo in the dependencies: https://github.com/TypeStrong/typedoc-default-themes

**Comment by aciccarello** [comment]
Unfortunately, there isn't a type definition at the moment. I'd suggest looking at the spec files for examples.

**Comment by GerkinDev** [comment]
Hi
What do you mean by *spec file*? Where can I find some?
Thank you

**Comment by aciccarello** [comment]
See the src/test/converter/_____/spec.json files in this repo

**Comment by GerkinDev** [comment]
Great ! Would it be possible to put those definitions into Typedoc itself, so users could import those types from the Typedoc node module?

Cheers !

**Comment by Gerrit0** [comment]
Closing in favor of #605, I'm working on a change that would integrate types for the JSON output & should close that issue as well.
