### ISSUE TITLE
@inheritDoc does not find method in implemented interface when method signature is different

### ISSUE THREAD

**Issue by kayahr** [TypeStrong/typedoc#793]
When annotating a method implementation with `@inheritDoc` then it only works when the method signature exactly matches the one in the implemented interface. It does not work when widening the signature with optional parameters or union types or using generic types.

**Example:**

```typescript
// test.ts
interface Base<T> {
    /**
     * Some method doc.
     */
    someMethod(a: T): void;
}

class Implementation implements Base<string> {
    /** @inheritDoc */
    someMethod(a: string): void {}
}
```
```
$ typedoc --out doc test.ts
```

**Version:** TypeDoc 0.11.1

**Expected behavior:**
Generated documentation must show that `someMethod` is an implementation of the interface and it must copy the documentation from the interface to the implementation.

**Actual behavior:**
TypeDoc doesn't recognize the interface method and therefor doesn't link the interface and doesn't copy the documentation.

**Analysis:**
The reason for this problem is that TypeDoc does a very simple check to find the super method. It compares the array of parameter types with an `equal` check. So `string` does not match a typed parameter restricted to `string`.

This could be solved by implementing a more complicated `isAssignableFrom` check instead of simply comparing the types with `equals`.

**Comment by noahwillcrow** [comment]
This is still an issue.

**Comment by Gerrit0** [comment]
TypeDoc 0.22 fixes this:

![image](https://user-images.githubusercontent.com/19329837/132113321-266b25fd-030b-4bb0-9dec-549b55bcf6dc.png)

**Comment by birkskyum** [comment]
This still appear to be a problem in verison 0.24.8
