### ISSUE TITLE
Full local paths included when inheriting from Node types

### ISSUE THREAD

**Issue by jameswilddev** [TypeStrong/typedoc#800]
Define the following types:

```typescript
/**
 * Defines types which can be round-tripped by `JSON.parse` and
 * `JSON.stringify`.
 */
export type Json = string | number | boolean | JsonObject | JsonArray | null;

/**
 * This is a helper type required by [[Json]].
 */
export interface JsonObject {
  /**
   * The properties defined.
   */
  readonly [x: string]: Json;
}

/**
 * This is a helper type required by [[Json]].
 */
export interface JsonArray extends ReadonlyArray<Json> { }

```

The documentation for JsonArray will include everything defined in ReadonlyArray (this is correct), with the full path to the user's local install of TypeScript (this is not expected), as below:

![c](https://user-images.githubusercontent.com/3138458/41580978-e38a863c-7394-11e8-9033-32bad13a9d60.png)

This may have been reported previously in #169 but whether this is the same problem is not clear.

**Comment by notwaldorf** [comment]
@jameswilddev have you found a workaround for this yet, by any chance? I can repro this with classes that extend `Error` to, eg:
```
export class SomeException extends Error {
  ...
}
```

**Comment by jameswilddev** [comment]
I've not been using TypeDoc; like the idea but it doesn't support a lot of the TypeScript features I use often.  I believe TypeScript's developers are doing something in-house.

**Comment by chapterjason** [comment]
Facing the same issue... :disappointed: Shouldn't the `excludeExternals` exlude these references? Wouldn't be better to place there something like (if I take your example above) `typescript/lib/lib.d.ts:1002`. Specify an external map would also be great. Something to reference to the other documentation.

**Comment by DanTheMan827** [comment]
it's not just node modules but others too
```
Inherited from Error.message

Defined in X:/Users/Daniel/Documents/GitHub/node-fel/node_modules/typedoc/node_modules/typescript/lib/lib.es5.d.ts:964
```

**Comment by BastienAr** [comment]
Any news on that issue ? Facing the same problem here

**Comment by psichma** [comment]
Yup, I'm also getting this problem. Tried every kind of combination of the exclude parameters, but nothing seems to work.
For me its not the inheritance of typescript specific stuff, but in general of other node modules.
I really don't want to release a documentation with my local paths.

**Comment by Gerrit0** [comment]
Closing this in favor of #642, will be fixed in the next version anyways.
