### ISSUE TITLE
The json output of typedoc is inconsistent with html output

### ISSUE THREAD

**Issue by angelwen08** [TypeStrong/typedoc#810]
I want to output a json file for azure-event-hub package and only output those types or classes export form index.d.ts.
So I use this command, but none of those  types/classes is generated.
Typedoc   <path to azure-event-hubs>\typings\lib\index.d.ts --json api.json --ignoreCompilerErrors --includeDeclarations 

If I use the following command to generate html output, it works as what I want
Typedoc   <path to azure-event-hubs>\typings\lib\index.d.ts --out <outDir> --ignoreCompilerErrors –includeDeclarations

Could you check why the output of json and html are inconsistent?

**Comment by aciccarello** [comment]
Thanks for the bug report. The json output could use improvement. It would be helpful if there was a small project where we could reproduce this.

**Comment by angelwen08** [comment]
Please just use npm package azure-event-hub to reproduce it.  
1. npm install azure-event-hub
2. under the package azure-event-hub, execute typedoc  by specifying source  \typings\lib\index.d.ts
Thank you!
