### ISSUE TITLE
How to stop automatic search when type a letter

### ISSUE THREAD

**Issue by ajmujaa** [TypeStrong/typedoc#812]
Hi

I'm using the typedoc to generate documentation for the stencil js project to showcase the web components. The document is generated very well. I want to prevent the automatic search function when I type a letter as I have some other editor plugged to the page. Is there a way to prevent automatic search in typedoc?

Thanks

**Comment by jonchardy** [comment]
This is part of the theme. If you clone the theme repository, you can remove [this section](https://github.com/TypeStrong/typedoc-default-themes/blob/c71e7dcbe8aa53d028646d3cc0219c16bd404835/src/default/assets/js/src/typedoc/components/Search.ts#L289) to get rid of keydown on the body element.
