### ISSUE TITLE
How do I suppress documentation for inherited symbols from being displayed in the page for an interface?

### ISSUE THREAD

**Issue by ashleydavis** [TypeStrong/typedoc#813]
I  have an interface IOrderedDataFrame that extends IDataFrame.

Typedoc by default seems to copy all the documentation from IDataFrame to IOrderedDataFrame which means that the two functions added by IOrderedDataFrame are lost in the noise. 

I'd like to be able to disable the inheritance of documentation so it's clear the functions that IOrderedDataFrame adds to DataFrame. Is this possible?

Please see screenshot.

![typedoc issue](https://user-images.githubusercontent.com/625126/42607481-78952cc6-85c6-11e8-9d9b-1d3f569e90d4.png)

**Comment by zbigg** [comment]
Just wanted to point that these inherited docs get very noisy when using external libraries like `react`. Your class documentation is just flooded with stuff inherited from say `React.component` that is usually of no use for anyone using the component.

**Comment by hvariant** [comment]
Would like to know about this as well.

**Comment by hvariant** [comment]
If you use the default theme you can filter methods at the top of the page using the three checkboxes 'Inherited', 'External' and 'Only Exported', like [this](https://i.imgur.com/acBf00S.png).

**Comment by arthurevans** [comment]
Has anyone found an answer for this?

It would be really helpful to be able to suppress the inherited members from a specified list of classes, for example, or things inherited from external libraries.

When defining a custom element class, for example, you need to extend HTMLElement. If you have defined your own superclass based on HTMLElement and subclasses, you really *want* to see the inherited stuff from your own library, without the six pages of DOM APIs.

**Comment by arthurevans** [comment]
@Gerrit0 Thanks! It turns out that plugin doesn't fix my problem, but it might point me in the direction of solving it for myself.

**Comment by jonchardy** [comment]
@Gerrit0 @aciccarello 

Hey guys, while working on the plugin, I've found that the way Typedoc identifies inherited declarations might not be right.

```
export class CustomError extends Error {
  public test: string;
}
```

If you generate docs for this class, then toggle the Inherited checkbox, the static Error declaration still exists, despite coming from the super class. See https://github.com/jonchardy/typedoc-plugin-no-inherit/issues/8.

**Comment by Gerrit0** [comment]
That does seem like a Typedoc bug, it looks like it's been reported before and just hasn't been resolved yet. #572

**Comment by vdegenne** [comment]
Why can you make a plugin for typedoc to spot an inherited class for exclusion but can't provide a general option for typedoc to automatically exclude all inherited class (from the keyword `extends`) ?

**Comment by peterflynn** [comment]
This was closed as completed in April 2020 – does that mean there's an option in Typedoc to exclude inherited symbols now?  I'm having trouble finding anything in this list that solves this: https://typedoc.org/options/

**Comment by motla** [comment]
> This was closed as completed in April 2020 – does that mean there's an option in Typedoc to exclude inherited symbols now? I'm having trouble finding anything in this list that solves this: https://typedoc.org/options/

`"excludeExternals": true` should do.
