### ISSUE TITLE
Option to exclude certain doc tags

### ISSUE THREAD

**Issue by Simon-Laux** [TypeStrong/typedoc#815]
I use [apiDoc](http://apidocjs.com/) in my Code to document my API, but typeDoc also parses those comments, what I don't want:
![screenshot 1531430789](https://user-images.githubusercontent.com/18725968/42662908-a7d5dde2-8633-11e8-9086-5bab90365a40.png)

So I'm now asking for an option to define a blacklist of doc tags that should not be included in the typedoc.
If there is already an option for this, that I just overlooked, please point me in the right direction.

**Comment by Gerrit0** [comment]
Released in 0.16.10 :)

You can use `--excludeTags` to remove tags from the generated documentation.
