### ISSUE TITLE
typescript change to export declare type breaks typedoc

### ISSUE THREAD

**Issue by miker99** [TypeStrong/typedoc#817]
Sorry of this is a duplicate.  I checked issues and didn't see it.

typescript used to generate .d.ts like so:

export declare const DEFAULT_FOOTPRINT_OPTIONS: 
   textAlign: "left" | "right" | "center" | "start" | "end";

it now generates something like:
export declare const DEFAULT_FOOTPRINT_OPTIONS: 
    textAlign: import("./features").TextAlign;

typedoc error:
Error: /home/users/.../... ...t.ds
 ';' expected.

**Comment by aciccarello** [comment]
@yarkovaleksei thanks for confirming the duplicate. I'll close this in favor of #820.
