### ISSUE TITLE
V8 Compilation Error when running typedoc

### ISSUE THREAD

**Issue by ev1stensberg** [TypeStrong/typedoc#818]
Hi! I tried implementing typedoc at [webpack-cli](https://github.com/webpack/webpack-cli/) but we got a v8 runtime error. Is this a known bug, or do you need additional details? 

Cheers,

Even

**Comment by aciccarello** [comment]
Hi @ev1stensberg I'm not aware of any issues. I doubt that this is a typedoc issue but feel free to add more details. Until then I'll leave this closed.
