### ISSUE TITLE
question: is there any way to document unit test?

### ISSUE THREAD

**Issue by lab4quant** [TypeStrong/typedoc#821]
Hello, is there anyway to document unit test?

like this:

```typescript
/**
 * ### Test1
 * test1 description
 */
describe('Test1', () => {

  /**
   * #### Case1
   * case 1 description
   */
  it('case 1', () => {

  });

  /**
   * #### Case2
   * case2 description
   */
  it('case 2', () => {

  });
```

thanks!

**Comment by aciccarello** [comment]
Typedoc only looks at the symbols in a file (variables, classes, function, declarations etc.) So it doesn't look at the it blocks. You might be able to rewrite the file to allow it. What is the use case for generating documentation on tests?
