### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by zdrawku** [TypeStrong/typedoc#823]
I tried to find documentation for supporting multiple languages with no success. Is localization supported for documentation generation?

**Comment by aciccarello** [comment]
Sorry, currently localization is not supported. I think this is out of scope for the time being so I'll close this issue but feel free to continue discussing your ideas here.

**Comment by zdrawku** [comment]
[This ](https://github.com/IgniteUI/typedoc-plugin-localization) is the solution to my question. We have created a typedoc plugin which is:

1. Merging all code comments (classes, methods, properties, enumerations etc.) that needs localization in a couple of json files.
2. Translate them by hand and save your changes.
3. Use the updated files to build a documentation for an entire project in the desired language.


In the [Readme.md](https://github.com/IgniteUI/typedoc-plugin-localization/blob/master/README.md) you can find more detailed explanation of the steps that you should take to use the plugin.

**Comment by aciccarello** [comment]
Very cool! Do you want to add that to the typedoc readme?

**Comment by zdrawku** [comment]
That would be great! If there is something that we need to consider as a plugin requirement or repository configuration, just let me know.

**Comment by zdrawku** [comment]
Sharing with the community steps and a video representation of the localization plugin usage:

```
npm install typedoc-plugin-localization

npx typedoc projects\igniteui-angular\src\public_api.ts --generate-json exports

npx typedoc .\projects\igniteui-angular\src\public_api.ts --generate-from-json .\exports\ --out localized

```
For more information, have a look at the [readme.md](https://github.com/IgniteUI/typedoc-plugin-localization/blob/master/README.md) file.

![localizationplugin](https://user-images.githubusercontent.com/11193764/44771691-6ee72c00-ab74-11e8-99fb-d6c03937ea2e.gif)

**Comment by antawad** [comment]
@zdrawku thanks for sharing. I have a question, are you able to do a merge somehow? i.e. say we follow these steps:
1. Merging all code comments (classes, methods, properties, enumerations etc.) that needs localization in a couple of json files.
2. Translate them by hand and save your changes.
3. Use the updated files to build a documentation for an entire project in the desired language.

Works great for version 1 of the class.

Say now we have version 2 of the class with some properties added, is there a way to do a merge with the translations from version 1? Or does it have to be done by hand? 

Cheers.

**Comment by Aleksandyr** [comment]
@antawad What kind of a merge you would like to apply?
Just on your translations? If that is the case you can do it by hand by copy/pasting the current translation and then merge it with the second version of the class.

If you are asking whether the plugin could do it on its own. It is not possible, because the plugin just extracts the comments, and then based on the same hierarchy it applies the translations.

**Comment by antawad** [comment]
Thank you @Aleksandyr for the info. 

I was wondering if there is an automated way to use the 
"typedoc-plugin-localization" to merge translations of the same class. Manually merging / amending the translation file should be fine as a start. 

As an idea, I wonder if it would make sense to add a tag in the class comments something like this:
```
/**
 * MyClass Comments
 */
export class MyClass {
    /**
     * @translate
     * This is my awesome prop.
     */
    myNewProp: string;
}
```
and we can have the localization strings in a .json file. e.g.:
**en.json**
```
{
    "MyClass":{
        "myNewProp":"This is my awesome prop."
    }
}
```
**fr.json**
```
{
    "MyClass":{
        "myNewProp":"FR - This is my awesome property in French"
    }
}
```
and when using the command to generate the documentation we can use set the localization language --localize "fr/en" and it will look up the string translations in the files above.

**Comment by Aleksandyr** [comment]
@antawad of course you can do that.
As you can see from that [igniteui-angular-api-i18n](https://github.com/IgniteUI/igniteui-angular-api-i18n/tree/master/typedoc) repository. That is exactly what we are doing here. We are keeping two identical versions of **en** and **jp** langs by keeping the same hierarchy. You can add **french** for example if that is needed. Afterward you just have to tell the plugin from which directory it should take the translations via **[--generate-from-json](https://github.com/IgniteUI/typedoc-plugin-localization#arguments)** option.

In the [additional information](https://github.com/IgniteUI/typedoc-plugin-localization#additional-information) section of the plugin, you can find how you could apply additional translations to the [theme](https://github.com/IgniteUI/ig-typedoc-theme) as well. By creating a JSON file in your project and localize all the strings you need. As an example, you can see it in the [igniteui-angular](https://github.com/IgniteUI/igniteui-angular/blob/master/extras/template/strings/shell-strings.json) repository.

**Comment by antawad** [comment]
@Aleksandyr Do you have an example of how you guys are handling same name properties? For example say we have a ClassA with a property `price` and classB with a property `price`. Are we able to nest properties? The en.json file for localization currently looks something like this: 
```json
{
    "en": {
        "price": "This is the price for ClassA",
    }
}
```
Can we have something similar to this:
```json
{
    "en": {
        "ClassA": {
            "price": "This is the price for ClassA"
        },
        "ClassB":{
            "price": "This is the price for ClassB"
        }
    }
}
```
