### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by webmaster128** [TypeStrong/typedoc#826]
typedoc is great and a lot of people love using it. And as far as my quick search goes, there is no real alternative to it. This is the result of a lot of hard work in the past, that I honor a lot. Thanks for bringing this to the community.

However, right now the projects seems abandoned. There are may issues that could easily be closed, such as updating TypeScript or bumping the min nodejs version to 6 that would help a lot of users.

Many contributors took their time to craft pull requests that are on hold for no clear reason. In fact only two PRs have been merged since April, 2018.

Is @aciccarello the only one maintaining this project? Or is it everyone from the TypeStrong organization? Anyway, the importance of this project for the TypeScript community, I think there should be a handful of maintainers working together. I don't know how this can be managed but I am sure it would be possible to find people that volunteer and maybe proved themselves by good quality contributions in the past.

Keep up the good work – we need this project!

**Comment by blink1073** [comment]
I am one of the maintainers of [jupyterlab](https://github.com/jupyterlab/jupyterlab), a large TypeScript project that depends on this library.  I would be happy to help maintain this library, if only to review/merge PRs and keep the up with the TypeScript version.  We have been forced several times to wait to adopt TypeScript language features because TypeDoc was using an older version.

**Comment by blink1073** [comment]
@blakeembrey ^^

**Comment by blink1073** [comment]
Blake, you may remember we collaborated on `simulate-event`.

**Comment by sebastian-lenz** [comment]
There has been decreased activity in this project over the last months, it would be great if some people with fresh energy become engaged. @aciccarello has been very active over the last years but I can totally relate to him that at some point a project like this becomes very exhausting.

As I'm not actively working on this project I would like the current maintainers to handle this decission. I personally think it would be a good idea to add @blink1073 as a maintainer.

**Comment by blink1073** [comment]
Thanks, @sebastian-lenz!  And thank you for all your efforts in creating and maintaining this project.

**Comment by aciccarello** [comment]
@webmaster128 Thanks for reaching out. I am the only (semi) active maintainer at the moment but it has been a busy time for me. I still intend to keep working on typedoc but I would support adding another maintainer. I'm glad to hear @blink1073 willing to help out.

#256 and the typedoc gitter channel are probably the best places to talk about strategies. I also am working towards getting a TS 3.0 release out soon.
