### ISSUE TITLE
Multiple build

### ISSUE THREAD

**Issue by presto41** [TypeStrong/typedoc#829]
I want to generate a few separated documentations from one project but I don't know what should I build my config file. It should be array of biulds? Something like that?

```
typedoc: {
    build: [{
            build 1
    },
    {
            build 2
    }]
}
```

**Comment by presto41** [comment]
Ok, I solved my problem. There I should to build config file like that:

```
typedoc: {
    build1: {
            build 1
    },
    build2: {
            build 2
    }
}
```

and call as typedoc:build1 or typedoc:build2

**Comment by aciccarello** [comment]
Thanks for posting your fix for others! I :+1:'d your SO question.

FYI, this may be more specific to [gulp-typedoc](https://github.com/rogierschouten/gulp-typedoc) than the typedoc proper.
