### ISSUE TITLE
Properties don't render default values

### ISSUE THREAD

**Issue by kamranayub** [TypeStrong/typedoc#83]
Given:

```
public letterSpacing: number = 0;
```

The output does not show what the default value is. Is this intended?

**Comment by sebastian-lenz** [comment]
Yes, the default value is only shown for function parameters. Variables and properties will only reflect function assignments and object literals.

**Comment by kamranayub** [comment]
Is this a restriction of the compiler or TypeDoc? If TypeDoc, could there be an option to include them? We use auto-properties a ton.

**Comment by sebastian-lenz** [comment]
The compiler represents the default value as an expression node. TypeDoc also reflects the default value of properties [right here](https://github.com/sebastian-lenz/typedoc/blob/master/src/td/converter/converters/convertNode.ts#L387) so it's available on the generated models and in the generated json output.

However, the included template does not render the default value of properties. It shouldn't be a big deal to add a parameter to include them optionally.

**Comment by kamranayub** [comment]
That would be excellent! It would clean up a lot of comments where we say (`default: true`, etc.)

**Comment by aindlq** [comment]
+1. The way defaults are handled in JSDoc is quite nice, see http://usejsdoc.org/tags-default.html

**Comment by solfolango** [comment]
I inspected the json output and the default value is indeed there "defaultValue". Knowing nothing about Handlebars and the like, I tried to edit the default template in 'partials\type.hbs' and included an 

`{{#if defaultValue}}
   &nbsp;= {{defaultValue}}
{{/if}}`

but - as I expected - it did absolutely nothing. Can you give me some pointers on how to access the default value in the template? It would be quite a bit of help for my project. I don't need an option, just a pointer where to edit the template manually. Thanks!

**Comment by jeffreymeng** [comment]
I understand it's been almost two years, has there been any progress on this?

When I define method signatures for classes, I can't set an initialization value, so a default tag in the comments would be very nice.

**Comment by Gerrit0** [comment]
For a while now, TypeDoc will render initializers for properties:

![image](https://user-images.githubusercontent.com/19329837/103250078-70d17d80-492f-11eb-9a27-335dd698d177.png)
