### ISSUE TITLE
Review ts-internal

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#830]
TypeDoc uses functions which the TypeScript team considers internal and exposes the types in [ts-internal.ts](https://github.com/TypeStrong/typedoc/blob/f75f378f8fe7cddd91e044933ced8d547e26bc3c/src/lib/ts-internal.ts).

We should review these methods to see if:

1. The methods are still considered private (marked `@internal`) by the TypeScript team
2. There is an alternative method (hopefully public) that should be used instead
3. We could engage the TypeScript team about exposing an api publicly so we are less likely to have breaking changes

**Comment by Gerrit0** [comment]
0.20 does a pretty good job of cleaning this up. There are only two things left in it, one of them has an issue that I expect will be accepted to be made public. The other... is deeply integrated into how typedoc works, isn't going to be exposed by the TS team, and will just have to be lived with for a while.

https://github.com/TypeStrong/typedoc/blob/33c2bc69bd7da205fee0157b1087b4873b9a3ba8/src/lib/ts-internal.ts#L1-L19
