### ISSUE TITLE
Ternary conditionals not supported in typescript 2.8

### ISSUE THREAD

**Issue by justinkchen** [TypeStrong/typedoc#831]
Can we upgrade the typescript version so that there arent any errors during compilation for newer types?

**Comment by aciccarello** [comment]
I'm working on updating typescript now so that will be resolved separately. I'm not sure if ternary conditionals will work by default though.

PRs to add a ternary conditional test case would be helpful

**Comment by Gerrit0** [comment]
Released in v0.15.6
