### ISSUE TITLE
Migrate off of grunt

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#836]
I imagine that build and configuration will be clearer/easier using npm scripts and js task files. Tests could also be executed using ts-node.

**Comment by demurgos** [comment]
I had good experience using the Typescript, Mocha and ts-node, especially with Typescript 3 and project references.

Looking at your grunt file, you still have some use cases that may be hard to implement manually: text replacement in a watch task, some manual file updates, and some file copies. These are harder to migrate, but possible.
I still think it's good to have a proper task manager for more complex projects. In practice I find Gulp easier to configure so it may be worth a try (disclaimer: I'm a Gulp maintainer). The main issue I had with Grunt is that you lack flexibility if you cannot express your needs declaratively in their config object.

**Comment by blink1073** [comment]
nb about TypeScript 3 project references, there is currently no output in [watch mode](https://github.com/Microsoft/TypeScript/issues/26147).
