### ISSUE TITLE
Add contrubuting.md file

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#837]
## Add basic info on how to contribute

- [x] Checking out git repo (basic git instructions)
- [x] How to build/test the code
- [x] update spec script (`npm run grunt -- update-specs`)
- [ ] rebase instructions

## Note some coding guidelines
- [x] Code should align with tslint rules
- [x] Build should pass
- [x] Don't bump the project version number

## Other
- [x] Info about this being a community run project
- [x] Add link to contributing.md to readme (and update specs)
- [x] Recommend gitter group for discussions about implementation

**Comment by blink1073** [comment]
In JupyterLab we run [prettier](https://github.com/prettier/prettier) as a [precommit](https://github.com/jupyterlab/jupyterlab/blob/master/package.json#L26) hook, and it has taken away a large part of the maintenance burden of reviewing PRs.  As a developer, it is also nice to think less about the formatting of the code you are writing and more about the content.

**Comment by webmaster128** [comment]
I also recommend prettier but as part of the build step (scripts.prebuild in package.json). I think and author should always explicitly see what he or she checks-in. If you push unlinted content, the CI should reject that.

**Comment by blink1073** [comment]
Another option is as a pre-commit hook using [husky](https://github.com/typicode/husky).

**Comment by aciccarello** [comment]
tslint should be failing the CI if there is a problem already. Autofixes are nice though. I haven't had great experiences with precommit hooks in the past but I'd be open to it or anything else that improved the contribution experience.

This issue is mostly focused on the contribution docs though :smile:

**Comment by Gerrit0** [comment]
I've taken an initial crack at this in #841 - feedback welcome! I really wasn't sure how far to go when describing installation & setup. I don't think someone brand new to coding could/should pick up TypeDoc as their first project, but someone might prove me wrong.

**Comment by Gerrit0** [comment]
Looking through the checklist in the original comment here, it looks like everything is complete, except perhaps the "rebase instructions" - The contributing.md file does include [updating your branch](https://github.com/TypeStrong/typedoc/blob/master/CONTRIBUTING.md#updating-your-branch) instructions, but doesn't use `git rebase`. Is this something that should be resolved before this issue can be marked as done?

**Comment by aciccarello** [comment]
That should be sufficient. The [official GitHub guide](https://help.github.com/articles/syncing-a-fork/) recommends doing a merge. With GitHub's PR squashing it's less important for contributors to know how to rebase.
