### ISSUE TITLE
Remove Typescript 2.7.2 dependency

### ISSUE THREAD

**Issue by jimjaeger** [TypeStrong/typedoc#838]
Hello,

regardless which typescript version is configured in the node project, typedoc currently use a hardcoded version 2.7.2 that is be installed right into the module folder.

You can see it in the first line:
Using TypeScript 2.7.2 from <project>\node_modules\typedoc\node_modules\typescript\lib

As result it breaks for typescript feature higher than 2.7.2: 
for example Error: <project>/node_modules/@types/bluebird/index.d.ts(318)
 '>' expected.

Can you remove the hard version dependency and use the version that is provided by the project?

**Comment by aciccarello** [comment]
This has already been completed. Just need to cut a new release.
