### ISSUE TITLE
Ignore a whole module in the generated doc

### ISSUE THREAD

**Issue by amaurymartiny** [TypeStrong/typedoc#842]
Here's myModule.ts:
```javascript
/**
 * @hidden
 * @ignore
 * @internal
 */

/**
 * Some comment.
 *
 * @ignore
 */
const myFunction = () => {};
```

When I run typedoc on it, I still see `myModule` in the list of modules on the right.

My typedoc.js:
```
module.exports = {
  exclude: ['**/*spec.ts', '**/index.ts'],
  excludeExternals: true,
  excludeNotExported: true,
  excludePrivate: true,
  hideGenerator: true,
  includes: './src',
  out: 'docs',
  module: 'commonjs',
  stripInternal: 'true'
};

```

**Comment by BenDevelopment** [comment]
I'm looking for the same behavior. Did you find a solution @amaurymartiny ?

**Comment by igncp** [comment]
I've tried to replicate this issue today with this setup but haven't been able. Both `@internal` and `@hidden`  tags (individually or combined) on top of the file would hide it from the globals menu. Using the same `typedoc.js` file as the initial comment. Tried with the latest version and `0.12.0`.

Would any of you have more info about the environment (OS, `typedoc` version, dir structure, ...) or a repo where this is happening? I could take a look

**Comment by amaurymartiny** [comment]
@igncp Look at the `am-docs` branch of https://github.com/maxogden/menubar/tree/am-docs/.

Specifically:
- `yarn docs` generates docs (typedoc 0.14.2), outputs into the `docs/` folder
- [here](https://github.com/maxogden/menubar/tree/am-docs/docs#external-modules) we see `"util/cleanOptions"`, and its docs are generated
- while I insistingly tried to hide them [here](https://github.com/maxogden/menubar/blob/am-docs/src/util/cleanOptions.ts#L1-L5)

**Comment by SimonFarrugia** [comment]
@amaurymartiny Same issue here. Just add another comment block after it, and it works fine.

**Comment by Gerrit0** [comment]
I suspect this was fixed in some commit to TypeDoc after the original report but the issue didn't get closed alongside it.

Since if you are not familiar with TypeDoc's behavior it won't make much sense, I've opened #1080 to track adding a warning for the case of a module documentation comment used with import statements.

**Comment by Dzenly** [comment]
Is there a way to ignore the whole module without adding `@ignore` to all exported stuff?

**Comment by Gerrit0** [comment]
As discussed above, you should be able to just add `@ignore` to the doc comment for the module. If this doesn't work for you, please open an issue.

**Comment by Dzenly** [comment]
Done: https://github.com/TypeStrong/typedoc/issues/1113

**Comment by pirix-gh** [comment]
Just to recap what worked for me. If you want to exclude a whole file (from the menu, search...), at the top of your file:

```ts
/** @ignore *//** */
```
It is hacky and I'd love to see this fixed. Unfortunately, it does not work for me without `/** */` (on typedoc@0.15.4, ubuntu 18.04, nodejs 12.13.1).

(like @SimonFarrugia suggested above)
