### ISSUE TITLE
Error if declarationMap is enabled in tsconfig.json

### ISSUE THREAD

**Issue by felixfbecker** [TypeStrong/typedoc#844]
If `declarationMap` is set to `true` in tsconfig.json, typedoc fails with this error:
```
Error: Option 'declarationMap' cannot be specified without specifying option 'declaration'.
```
It seems like `declaration` is _unset_ by typedoc, but `declarationMap` is not.

**Comment by FedeBev** [comment]
Same here, any news?

**Comment by iamcco** [comment]
same here
