### ISSUE TITLE
Add option to follow symlinks

### ISSUE THREAD

**Issue by duclet** [TypeStrong/typedoc#849]
Can we add an option to follow the symlinks of files are that imported?

**Comment by mike-d-davydov** [comment]
Since typedoc does NOT follow links, it doesn't work with @microsoft/rushjs and pnpm. For us it is a grave problem

**Comment by Gerrit0** [comment]
Which version are you on? I expect this should be fixed now that #949 has been merged. The `@next` (v0.15.0-0) or my mirror (`@gerrit0/typedoc`) both have this change included.

**Comment by mike-d-davydov** [comment]
Looks like after switching to 15-0-0 it's gone... Need to double-check

**Comment by aciccarello** [comment]
I'll close this since it should be fixed in the upcoming release.
