### ISSUE TITLE
[Feature Request] Keep @example from indenting text

### ISSUE THREAD

**Issue by oleersoy** [TypeStrong/typedoc#852]
Hello - Thanks for making Typedoc.  It's really awesome!

[For this repository](https://github.com/fireflysemantics/collections) I have `@example` annotations for each API method.  Here's a snippet:

```
   @example
<pre>
   const original = ['a', 'b'];
   const result = ['a', 'b', 'c', 'd'];          
   expect(push(original, 'c', 'd')).to.eql(result);
</pre>
```

The generated `@example` pill indents the first line `const original=...` so that it ends up not being aligned with the rest of the code, even though it's all wrapped in a `pre` tag.  Here's a link to the typedoc:

https://fireflysemantics.github.io/collections/doc/modules/_index_.html

I looked at the CSS for the pill and it looks like it is using clearfix and float.  Flexbox is supported universally by all browsers now essentially so switching to that for the layout is probably a good idea.

## Fragments Support 

Also it would be awesome to have support for fragments, so we could do things like link to specific API methods in the same way the github links to specific parts of a conversation.  For example:

```
https://fireflysemantics.github.io/collections/doc/modules/_index_.html#post
```

**Comment by aciccarello** [comment]
Thanks for the clear report @oleersoy. This has actually already been fixed in TypeStrong/typedoc-default-themes#54 but has not been released yet because I do not have npm publish rights to that repo. I'll try to reach out again and see I can get that fixed.

**Comment by oleersoy** [comment]
@aciccarello awesome!  Great to hear that.  Do you now by chance if fragment support is on the way as well?

**Comment by Gerrit0** [comment]
It looks like the mentioned PR has been merged, so that's fixed. There has been support for fragments for.. a while. I'm not sure when exactly, but your provided link works - https://fireflysemantics.github.io/collections/doc/modules/_index_.html#post
