### ISSUE TITLE
Don't use the project readme when testing the renderer

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#853]
The current renderer end-to-end test generates an index.html file based on the project readme. While we want to check that the renderer converts markdown to HTML, it is problematic to use the project readme. Any contributions to improve the readme will fail the CI because they also require updating the specs.

The typedoc application config in the render.ts spec file should be updated to point to a static dummy readme that does not change as frequently as the project readme.

## Steps
- Add dummy readme that has some basic markdown to convert
- Update application config in src/test/renderer.ts to point to readme
- Update specs

**Comment by Towerism** [comment]
I'll take this
