### ISSUE TITLE
How can I get rid of the double quotes in module mode?

### ISSUE THREAD

**Issue by tetsuo** [TypeStrong/typedoc#854]
Hello, thanks for the Typedoc! Can you remove the double quotes that surround the module names?

They look ugly and doesn't add anything at all to the generated documentation for me. I'm sure they are there to prevent something, but you can also add an icon to indicate that and or allow users to disable them in some way.

**Comment by aciccarello** [comment]
Yep, closing as a duplicate

**Comment by EmmaGoodliffe** [comment]
Recommend https://www.npmjs.com/package/typedoc-plugin-external-module-name for anyone having this issue.
