### ISSUE TITLE
Supporting nested events

### ISSUE THREAD

**Issue by mmacfadden** [TypeStrong/typedoc#855]
We have several classes that emit events. We would like to clearly articulate in the API what the valid event constants are. The classes also have several other non event related static constants. As a result we put the Events under an object named "Events". The classes look something like this:

```Typescript
export class Foo {
  public static readonly OTHER_CONSTANT = "other";

  public static readonly Events = {
    /**
     * @event
     */
    OPENED: "opened",

    /**
     * @event
     */
    CLOSED: "closed"
  }

  constructor() { 
  }
  
  public someMethod(): void {
  }
}
```

The issue is that, there does not seem to be a way to have the events show up as events in the API documentation. When looking at the typescript definitions generated by the build, it is pretty obvious what the events are, so we get good autocompletion in editors, but we don't get the nice "Events" section in the API docs generated by Typedoc.

We have chosen to not put the constants on the class itself, because then they get mixed in with the other constants that are not related to events, which makes code completion less useful.

Any ideas on the best way to accomplish this? Is this a feature that could be added or something we could write a plugin for?

Thanks for Typedoc!

**Comment by Gerrit0** [comment]
A plugin *could* listen to the `Converter.EVENT_RESOLVE_END` event and mutate the `groups` property to create/add to an events group... this feels like it would be confusing to users to me since everything else in the index only shows top level properties.
