### ISSUE TITLE
Class Property Directive for Documenting Property Name & Type Only

### ISSUE THREAD

**Issue by ppator1** [TypeStrong/typedoc#856]
### Feature Request
**Actual Behavior**
TypeDoc generates documentation for class properties as they are defined in code
**Expected Behavior**
TypeDoc generates documentation for class properties using options to only include property name and type in generated docs

Currently, TypeDoc does not seem to have a way to create documentation for class properties in a clean manner. You can see what I'm talking about here [TypeDoc VariableConverter Class Documentation](http://typedoc.org/api/classes/variableconverter.html). If you scroll down to look at the "supports" property of the "VariableConverter" class you can see that not only does it include the name of the property and its type, but it also includes its set value (the = along with the value that comes after the =). This makes for unsightly documentation, and is currently an undesirable effect of generating documentation for a project we are working on.

**Comment by Gerrit0** [comment]
As of 0.20.1, properties will include their initializer only if deemed to be "simple" (a numeric or string literal)
