### ISSUE TITLE
Function exported as variable despite @function tag

### ISSUE THREAD

**Issue by jerylvaz** [TypeStrong/typedoc#858]
v**2.7.2**

```
/**
 * Promisified version of fs.writeFile().
 * @function writeFileAsync
 */
export const writeFileAsync: Function = util.promisify(fs.writeFile);
```

![typedoc](https://user-images.githubusercontent.com/12097710/45752092-aea1b080-bc14-11e8-9cf1-79ae467776e1.png)

CLI options: 
`--readme ./README.md --mode file --includeDeclarations --excludePrivate --excludeExternals`

**Comment by aciccarello** [comment]
Hello @jerylvaz, in general, TypeDoc does not override type information from jsdoc tags. The `@function` tag is not officially supported. Since the variable is defined as a `const` TypeScript considers it a variable with a function signature. I wonder if it would make sense to tag callable variables as functions.

**Comment by justinfagnani** [comment]
> I wonder if it would make sense to tag callable variables as functions.

This is definitely what I'd want.

**Comment by Ixonal** [comment]
I'm running into this too. The documentation generated shows the whole function implementation when I set up memoization...

```typescript
/**
 * Determines whether or not the given string can be considered a url
 */
export const isUrl = memoize(
  function isUrl(str: string): boolean {
    urlParser.href = str;
    return !!(urlParser.host && urlParser.host !== window.location.host);
  }
);
```

It may be of benefit to officially support the `@function` annotation for this specific situation...

**Comment by Gerrit0** [comment]
In 0.20, TypeDoc renders the OP's code block as the following:

![image](https://user-images.githubusercontent.com/19329837/103160195-1b5e6a80-478f-11eb-9d4c-4b049fb10945.png)

Removing the (bad) type annotation `: Function`, results in rendering this:

![image](https://user-images.githubusercontent.com/19329837/103160209-3a5cfc80-478f-11eb-9669-c1d1d8a68216.png)
