### ISSUE TITLE
Please support @template alias for @typeparam

### ISSUE THREAD

**Issue by soul-codes** [TypeStrong/typedoc#860]
First off, thank you so much for TypeDoc. I can imagine how bewildering TypeScript doc generation can be especially in the light of the recent advanced types. I really hope that this is a project that will get continual support.

VSCode supports `@template` to annotate TypeScript generic parameter. Not only it gets properly highlighted in the IDE, VSCode lets you also refactor the generic parameter name with their F2 command and both the name on the comment and the in-code references change.

Seeing that VSCode is Microsoft's and so is TypeScript, it would be good if TypeDoc would follow suit and support `@template` in addition to `@typeparam`, so that we can benefit both from VSCode's refactor capabilities and consistent document generation from TypeDoc.

**Comment by aciccarello** [comment]
Thanks for reporting @soul-codes. This is a good idea, however I would like to wait for Microsoft to provide a little more direction before moving forward on this. 👍

**Comment by Koviko** [comment]
While this issue remains open, what is the correct way to document generics?

**Comment by Gerrit0** [comment]
For now, the `@typeparam` tag is the way to go as it is recognized by TypeDoc. TypeScript still uses `@template`, so we should probably support that as an alias. We should also probably support `@typeParam` for compatibility with Api-Extractor.

**Comment by Gerrit0** [comment]
TSDoc has decided to officially support tag synonyms, so TypeDoc should also support them, PR welcome to add support for `@template`

**Comment by Gerrit0** [comment]
Support for `@template` will be included in 0.17.
