### ISSUE TITLE
Disable output (--out)

### ISSUE THREAD

**Issue by GerkinDev** [TypeStrong/typedoc#861]
Hi there!

I'm generating documentation for a lib using typedoc, and I use this documentation in an angular application that uses only the json output. Thus, I'd like to know if this is possible to totally disable all output (html...) other than json

Cheers!

**Comment by Gerrit0** [comment]
Just don't use `--out`, only use the `--json` option and Typedoc should only render the JSON output.

**Comment by GerkinDev** [comment]
.... Okay i'm feeling really dumb: my IDE did not showed me files changes, and I didn't see that it actually worked.
