### ISSUE TITLE
Suggestion: exclude `@internal`

### ISSUE THREAD

**Issue by rbuckton** [TypeStrong/typedoc#867]
TypeScript supports `--stripInternal` as an advanced compiler flag, in which declarations that have an `@internal` tag in their comments are stripped from output declaration files. Ideally, TypeDoc should exclude declarations from documentation marked with `/** @internal */`, similar to the logic here: https://github.com/rbuckton/iterable-query/blob/refactor/src/typedoc-plugin-custom/plugin.ts#L381.

This may need to be configurable, as the `typedoc-plugin-internal-external` package also uses `@internal` by default.

**Comment by aciccarello** [comment]
Thanks for your feedback @rbuckton. There already is some discussion of this in #364 

You bring up a good point about the effect ignoring it would have on plugin users. Maybe @christopherthielen could provide some feedback. His while plugin allows using another tag name I imagine many use the default of `@internal`.
