### ISSUE TITLE
Suggestion: Resolve names for declarations exported using export specifiers.

### ISSUE THREAD

**Issue by rbuckton** [TypeStrong/typedoc#868]
Currently, if `excludeNotExported` is set, declarations like the following are also excluded:

```ts
function foo() {}
export { foo as bar }
```

Not only should `foo` be considered exported, in the documentation it should be given the name `bar`. Also, ideally you should also support additional names for the same reflection:

```ts
function foo() {}
export { foo, foo as bar }
```

Should export (and have documentation entries) both `foo` and `bar`.

**Comment by NaridaL** [comment]
I think adding an `aliases` key in those cases makes more sense:

```json
{
  kindString: "Function",
  name: "foo",
  aliases: ["bar"],
  ...
}
```

That could be mirrored in the output:

### function foo
*This function is also accessible through the name(s) `bar`*

**Comment by rbuckton** [comment]
In my case, I have a function named `_break` that I export as `break`. I don't want the non-exported function name in my documentation.

**Comment by rbuckton** [comment]
I've been tinkering with this more in a plugin:

- If `excludeNotExported` is enabled and the export alias points to a non-exported declaration, rename the non-exported reflection as the first export alias and mark it as exported.
- For all other aliases (or if the target declaration is already exported), copy the signatures/types/etc. to the alias and point to the target declaration in sources.hbs:
  ![selectmany](https://user-images.githubusercontent.com/3902892/46586658-8b5d6a80-ca36-11e8-8deb-d6c2334ea3bc.png)
- If re-exporting a module namespace object (i.e. from `import * as x`), add a new `ReflectionKind.Export`
and a new declaration template:
  ![fn](https://user-images.githubusercontent.com/3902892/46586708-f149f200-ca36-11e8-808a-badb6d851d32.png)

**Comment by Gerrit0** [comment]
In 0.20 (currently `typedoc@beta`) typedoc asks the compiler for exported symbols + names, so the first example results in a single exported function named `bar`, and the second a function `foo` and a reference `bar` which is tied to `foo`
