### ISSUE TITLE
Interface that merges with Namespace (nee. Module) is labled as Module in output.

### ISSUE THREAD

**Issue by rbuckton** [TypeStrong/typedoc#879]
If you have the following declarations:

```ts
interface Foo<T> {
  foo: T;
}
namespace Foo {
  export function createFoo(): Foo { … }
}
```

TypeDoc generates documentation that reads:

> Module Foo&lt;T&gt;

And classifies this as a module, rather than an interface (or a combination of the two).

Note that in VS Code, whenever there are merged declarations they appear in quick info like this:

```ts
interface Foo<T>
namespace Foo
```

**Comment by aciccarello** [comment]
Related to #472
