### ISSUE TITLE
typedoc not using project typescript version

### ISSUE THREAD

**Issue by TitaneBoy** [TypeStrong/typedoc#884]
Hi...Since the last release of typedoc (0.13.0), I'm facing an error when using typedoc. My project is an Angular project and since the last release of Angular, it does not work yet with Typescript 3.x, So I cannot use typescript 3.x. But it looks that typedoc is using typescript 3.1.x.

How can we resolve this issue ? Should typedoc use the typescript version described in the package.json of the current project instead of the last version of typescript  ?

Thanks in advance for your answer and help.

PS: Typedoc@0.12.0 works perfectly in my project. But I don't understand why exactly because in the package.json of typedoc@0.12.0, it use typescript@3.0.x. I'm not sure if it works because of this issue #838

**Comment by aciccarello** [comment]
Hello @TitaneBoy, for the foreseeable future, TypeDoc will be tied to a specific TypeScript version to avoid compatibility issues. Therefore you will need to either add TypeScript 13.1 support or downgrade to TypeDoc versions. Sorry for the inconvenience. It sounds like Angular 7 will bring improved TypeScript support.
