### ISSUE TITLE
Interface is displayed twice when both child and base classes implement it.

### ISSUE THREAD

**Issue by hanastasov** [TypeStrong/typedoc#893]
Is there a way to avoid generating duplicate node for an Interface when visiting the generated doc for a child class ?

Example:
export class A implements Foo {}

export class B extends A implements Foo {}

Steps to reproduce:
1) npm install
2) typedoc --out docs /src

Visiting the generated page for class B shows the following:

![image](https://user-images.githubusercontent.com/14248932/55399736-9eb84100-5554-11e9-998c-fb62e0af960d.png)

[typedoc example.zip](https://github.com/TypeStrong/typedoc/files/3033671/typedoc.example.zip)

Is there a way to avoid this duplication ?

**Comment by hanastasov** [comment]
Do you have any trouble reproducing it ? Do you need me to attach a project with an npm run command that will result in the html, or just attaching the produced html is just fine ?

**Comment by aciccarello** [comment]
Sorry, I haven't had a chance to try reproducing this yet. Any information about your configuration would be helpful (e.g. what mode are you using).

**Comment by hanastasov** [comment]
I am attaching the most basic configuration and project possible. 

Run 1) npm install, 2) typedoc --out docs /src
and open the generated docs at /docs folder, see the documentation for class B:

![image](https://user-images.githubusercontent.com/14248932/55399648-5862e200-5554-11e9-9d7d-a08bb0f5df00.png)
![image](https://user-images.githubusercontent.com/14248932/55399659-63b60d80-5554-11e9-8716-092ce5bc84ba.png)

[typedoc example.zip](https://github.com/TypeStrong/typedoc/files/3033669/typedoc.example.zip)

**Comment by aciccarello** [comment]
thanks

**Comment by LinYunMo** [comment]
Is there any conclusion on this issue? @aciccarello

**Comment by Gerrit0** [comment]
Nobody's sent in a PR with a fix, so it's still an issue. Feel free to make a PR if this is getting in your way. I think it should be relatively straightforward.

**Comment by Gerrit0** [comment]
This works as expected in 0.20

![image](https://user-images.githubusercontent.com/19329837/103244769-470e5b80-491b-11eb-9329-405132b5af79.png)
