### ISSUE TITLE
Provide an option to link standard classes to MDN

### ISSUE THREAD

**Issue by FranklinYu** [TypeStrong/typedoc#895]
For example, if my function returns `Promise<string>`, I would like TypeDoc to render it as [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)&lt;[string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)&gt;. MDN is almost the official documentation of JavaScript (easier to read than [the standard](https://www.ecma-international.org/ecma-262/9.0/)), but user may also want to link to other sources like [Node.js](https://nodejs.org/dist/latest-v10.x/docs/api/). I imagine the API be like

```bash
typedoc --link MDN --link nodejs-v10.x ./src/
```

**Comment by aciccarello** [comment]
Thanks for sharing the idea. This likely won't be added to the core project anytime soon. I believe this would be a good use case for a plugin.
