### ISSUE TITLE
Refactor to use array include

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#898]
Minor change to make the code more readable. `Array.includes` is available in Node 6+ and can be used to replace the less-readable `[].indexOf !== -1` or `[].indexOf > -1`.

In general, `Array.includes` is a drop in replacement but there are some slight differences in edge cases (most notably when searching for `undefined`).

https://dev.to/adroitcoder/includes-vs-indexof-in-javascript

**Comment by bendtherules** [comment]
Hi,
I would like to take this up.

**Comment by aciccarello** [comment]
Great! Let me know if you have any questions about contributing. [Gitter](https://gitter.im/TypeStrong/typedoc) is also a good place for discussion.
