### ISSUE TITLE
Allow different markdown flavors

### ISSUE THREAD

**Issue by ItalyPaleAle** [TypeStrong/typedoc#899]
When rendering Markdown files that contain tables (in the GitHub syntax), they are not rendered as HTML by TypeDoc

**Comment by aciccarello** [comment]
Thanks for the suggestion. It looks like this would be easy to fix. There is a table option in the [Marked.js config](https://marked.js.org/#/USING_ADVANCED.md). That would then need to be applied to the `MarkedPlugin`.

https://github.com/TypeStrong/typedoc/blob/6d5b21bf196f8349be4e1157d0a6268d2dd12b3f/src/lib/output/plugins/MarkedPlugin.ts#L89-L91

I'd also like to see a table added to the doc comments in a test. PRs welcome!

**Comment by aciccarello** [comment]
Thanks for the PR but you bring up a potential problem. Markdown parsers have a lot of edge cases. Additionally, Microsoft is trying to standardize doc comments with a tsdoc spec which [will use CommonMark](https://github.com/Microsoft/tsdoc#what-are-the-goals) as the standard.

I think a better solution would be a way to override the Marked.js options. That way some could use a non-standard MD flavor if they would like to.

**Comment by ItalyPaleAle** [comment]
Ok, I think you should implement that!

**Comment by Gerrit0** [comment]
Overriding marked options is tracked by #1395
