### ISSUE TITLE
Feature Request: Instead of showing links to types/aliases/interfaces, show their information instead

### ISSUE THREAD

**Issue by balupton** [TypeStrong/typedoc#902]
I am converting a fairly large package to typescript today, and got typedoc generations docs. However the documentation requires a lot more clicking around to get the information that the jsdoc solution had previously.

Here is the declarations:
https://github.com/bevry/safeps/blob/4c9497e2b9eb53903ba12598e192c5ce1b931af5/source/index.ts#L25-L98

As you can see, there is a lot of shared properties between the interfaces. For three of them, I've already made what typedoc calls type aliases for them, which have the jsdoc descriptions.

However, when I navigate the documenation, I must click through several steps before I get the information. Each screenshot/visual-box is an additional click with typedoc:

<img width="932" alt="screen shot 2018-11-16 at 11 52 37 pm" src="https://user-images.githubusercontent.com/61148/48622515-24e74700-e9fb-11e8-9a1c-f973a38896f8.png">
<img width="919" alt="screen shot 2018-11-16 at 11 52 55 pm" src="https://user-images.githubusercontent.com/61148/48622517-26b10a80-e9fb-11e8-93c5-94ebca18cd1d.png">
<img width="926" alt="screen shot 2018-11-16 at 11 53 02 pm" src="https://user-images.githubusercontent.com/61148/48622521-29abfb00-e9fb-11e8-8a18-fe828a716857.png">
<img width="933" alt="screen shot 2018-11-16 at 11 53 12 pm" src="https://user-images.githubusercontent.com/61148/48622526-2d3f8200-e9fb-11e8-836d-db229baa7f51.png">
<img width="940" alt="screen shot 2018-11-16 at 11 53 16 pm" src="https://user-images.githubusercontent.com/61148/48622528-2fa1dc00-e9fb-11e8-9c23-dea912631b31.png">
<img width="935" alt="screen shot 2018-11-16 at 11 53 20 pm" src="https://user-images.githubusercontent.com/61148/48622535-329ccc80-e9fb-11e8-9a5d-15c89be58505.png">

I really like the way JSDoc embeds documentation, like it has done here for a different project: http://master.editions.bevry.surge.sh/docs/global.html#Edition

Or here via documentation.js for an earlier version of that project http://master.safeps.bevry.surge.sh/docs/#.safeps.exec

**Comment by aciccarello** [comment]
@balupton I agree that there are often too many clicks needed to view docs.  It sounds like you want a way to inline types into their usage. For simple cases with one type or interface it wouldn't be too hard to inline the docs. How would you expect more complex union types to be handled. I'm not sure if there is a way to inline this functionality.

I think this should be tried as a plugin before we attempt implementing this in typedoc proper. Maybe an `@inlineDoc` annotation on the type/interface would be a good trigger.

**Comment by balupton** [comment]
>@balupton I agree that there are often too many clicks needed to view docs.  It sounds like you want a way to inline types into their usage. For simple cases with one type or interface it wouldn't be too hard to inline the docs. How would you expect more complex union types to be handled. I'm not sure if there is a way to inline this functionality. ...

@aciccarello thanks for the quick reply

Essentially I think that right now the documentation is focused on package author implementation details, rather than end user consumption details.

For instance, an end user doesn't care at all about intermediary types, only the types they will be writing and plugging into the calls.

So my expectation is for the documentation to cater towards the consumers / end users of the package, rather than the people who wrote the package.

To accomplish this, I'd imagine in the first screenshot, there is a table below "opts", with the union of the two types it mentions, and the childmost leafs of the types, so a table of the name, type, and description of each param that interface provides. If people want to get details on the implementation they can click through the existing line above the new table to follow through the details.

These consumption detail tables should be implemented for each interface.

Having a annotation would mean I would end up annotating everything, a CLI flag would make more sense imho.

If this because common, it would be great for docs, as it means people can describe their types in the declaration files, and those descriptions make their way into documentation of packages that consume them. For instance, if the node.js declaration file exported /** comments along the types, then my interfaces that extend or union the builtin node.js types, would have descriptions on the builtin properties without every consumer having to describe them again, or not bothering.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gerrit0** [comment]
Closing this in favor of #1021.
