### ISSUE TITLE
All Files marked as external

### ISSUE THREAD

**Issue by Roaders** [TypeStrong/typedoc#903]
Hi All

I am trying to create docs for all of my projects in one place. I have copied the npm imports from all these projects into a `projects` folder and I then run typedoc passing it all the files pointed to by the `types` property in the package.json:

Files structure:
```
tsconfig.json
package.json
node_modules
    ...imports
projects
    project-one
    project_two
```

Code:
```
const tsDocOptions = {
    excludePrivate: true,
    excludeNotExported: true,
    excludeExternals: false,
    moduleResolution: "node",
    includeDeclarations: true,
    mode: "module",
    tsconfig: "tsconfig.json"
}

new Application(tsDocOptions).generateDocs([
"projectOne/main/index.d.ts",
"projectTwo/main/index.d.ts
], "docs")
```

This does work - I get a list of all my classes and interfaces but they are ALL marked as external and they are mixed in with all the angular, rxjs and other actual external files. They are also not searchable using the search bar at the top of the page.

I have tried playing with the `externalPattern` option but it has not made any difference. Can anyone tell me why all of these fiels are marked as external?

**Comment by Roaders** [comment]
ok, is there a way of passing a whole folder to the Application.generateDocs function as you do from the command line? I think that's the issue.

**Comment by aciccarello** [comment]
Yeah, there is an `expandInputFiles` function which can help with that.

```javascript
const TypeDoc = require('typedoc'); const app = new TypeDoc.Application({ mode: 'Modules', logger: 'none', target: 'ES5', module: 'CommonJS', experimentalDecorators: true }); const project = app.convert(app.expandInputFiles(['src'])); if (project) { // Project may not have converted correctly const outputDir = 'docs'; // Rendered docs app.generateDocs(project, outputDir); // Alternatively generate JSON output app.generateJson(project, outputDir + '/documentation.json'); }
```

**Comment by Roaders** [comment]
Many thanks, I'll give that a go.
