### ISSUE TITLE
@category not working for functions within modules

### ISSUE THREAD

**Issue by geethika18** [TypeStrong/typedoc#904]
**Requirement**
Within a module, there should be a way to classify/categorize the functions - ex: content creation functions, content editing functions etc.

Tried out something similar to what was mentioned in https://github.com/TypeStrong/typedoc/pull/566

But @category tag was taking effect only on classes.

**Comment by geethika18** [comment]
Hi @aciccarello,

I have a ts file defined as below

namespace ABC{

/**
* @category abc.1
*/
export function1() {
}

/**
* @category abc.2
*/
export function2() {
}
...
}

My requirement is to have these categories produce different pages or even different sections within the same page. Please help me out with the same.

**Comment by geethika18** [comment]
Can I get some help here?

**Comment by Gerrit0** [comment]
I don't believe this is supported with the default theme yet, #866 might resolve this.

**Comment by jonchardy** [comment]
Yes, see #866. I'm willing to help make some changes here, but need some input on desired behavior.

**Comment by geethika18** [comment]
Hi @jonchardy ,

Any luck with this? Please let me know. Thanks.

**Comment by geethika18** [comment]
Output generated 

![image](https://user-images.githubusercontent.com/13620937/50688220-76e73900-104a-11e9-8680-658f5112f9c3.png)

Expected output 

![image](https://user-images.githubusercontent.com/13620937/50688238-89617280-104a-11e9-8c6d-7d200f821b86.png)


The theme used is same, but in 2nd case I had to duplicate my input file which is basically a weird work-around. Please suggest me the right approach.

**Comment by jonchardy** [comment]
See https://github.com/TypeStrong/typedoc/pull/938

**Comment by geethika18** [comment]
Hi @jonchardy ,

What is the ETA for releasing this change?

**Comment by jonchardy** [comment]
I don't know, I'm just a contributor. @aciccarello

**Comment by aciccarello** [comment]
Sorry, there is no ETA at the moment. The PR will need to be reviewed. Additionally there are some issues with releasing themes at the moment.

**Comment by geethika18** [comment]
Hi @aciccarello ,

Could you please share the ETA for releasing this change? I see that the change is merged. Thank you.
