### ISSUE TITLE
Support multiple --exclude arguments

### ISSUE THREAD

**Issue by balupton** [TypeStrong/typedoc#905]
Via the API, exclude supports an array https://github.com/TypeStrong/typedoc/issues/170#issuecomment-388607358

However, via the CLI, it only supports a single usage instead of multiple. It would be nice if the CLI concatenated multiple `--exclude` values into an array, so we can do:

```
typedoc --exclude '**/*test*' --exclude '**/node_modules/** --exclude '**/test/**
```

as unfortunately, this workaround does not work for the above:

```
typedoc --exclude '**/{*test*,{node_modules|test}/**}'
```

**Comment by aciccarello** [comment]
Thanks for the suggestion! I agree this would be a helpful. If anyone would like to implement this, please reach out for discussion!

**Comment by balupton** [comment]
I took a look to try and find where this is defined, but seems more complicated than a first glance offers.

Perhaps it would make sense to use https://www.npmjs.com/package/cac (personal favourite out all the alternatives) instead of what appears to be a custom built solution.

**Comment by 9oelM** [comment]
Perhaps we need to set up a simple test against that to verify.

**Comment by aciccarello** [comment]
Yeah, we should test that. I seem to recall bracket syntax didn't work well.

**Comment by 9oelM** [comment]
May be relevant. Just taking notes for reference

### [`/src/lib/application.ts`](https://github.com/TypeStrong/typedoc/blob/dbdbfcaa39783072540df242957a8bcd91d82204/src/lib/application.ts#L252-L282)
```ts
        inputFiles.forEach((file) => {
            file = Path.resolve(file);
            if (FS.statSync(file).isDirectory()) {
                add(file);
            } else if (!isExcluded(file)) {
                files.push(file);
            }
        });

```

### [`src/lib/converter/converter`](https://github.com/TypeStrong/typedoc/blob/1c4c5151cec938ef03cae79c33c12be8d587ea74/src/lib/converter/converter.ts#L385-L397)
```ts
    private compile(context: Context): ReadonlyArray<ts.Diagnostic> {
        const program = context.program;

        const exclude = createMinimatch(this.application.exclude || []);
        const isExcluded = (file: ts.SourceFile) => exclude.some(mm => mm.match(file.fileName));

        const includedSourceFiles = program.getSourceFiles()
            .filter(file => !isExcluded(file));
        const isRelevantError = ({ file }: ts.Diagnostic) => !file || includedSourceFiles.includes(file);

        includedSourceFiles.forEach((sourceFile) => {
            this.convertNode(context, sourceFile);
        });
```

**Comment by Downchuck** [comment]
@aciccarello That glob syntax has strange semantics -- I can't tell what it's actually doing -- if I remove the first *test* clause, it no longer filters node_modules. If I change test to spec, it's not actually filtering out spec files.

**Comment by Gerrit0** [comment]
@Downchuck that's because TypeDoc currently splits the glob on `,` before matching it (I know, I know...) once resolved, it should behave as expected.

**Comment by Downchuck** [comment]
@Gerrit0 No idea how to math that in my brain pan - but this is working ```'{**/*spec*,**/*.spec.ts,**/node_modules/**,**/*spec.ts}'``` though no idea why. As you said, something to do with the comma - as when I take out the first or last item my spec or node_modules are no longer filtered.

**Comment by Gerrit0** [comment]
As of 0.16, this is supported.
