### ISSUE TITLE
Document inputFiles option

### ISSUE THREAD

**Issue by yordis** [TypeStrong/typedoc#908]
Hey folks, right now I am trying now I am working on some CLI that wraps `typedoc` command line.

I am trying to figure out what I am doing wrong and after a couple of hours I am getting nowhere.

I have the following code

```javascript
const { CliApplication } = require('typedoc');
const { resolveApp } = require('../paths');
const { setupEnv } = require('../env');

async function run(toolbox) {
  const { parameters } = toolbox;
  setupEnv('development');

  const config = {
    out: resolveApp('docs'),
    inputFiles: resolveApp('src'),
    includeDeclarations: true,
    readme: resolveApp('README.md'),
    ...parameters.options,
  };

  console.log(config);

  // eslint-disable-next-line no-new
  new CliApplication(config);
}
```

As you can see I am doing `console.log` which will output something like

```javascript
{ out:
   '/Users/yordisprieto/Developer/straw-hat/javascript/fetcher/docs',
  inputFiles:
   '/Users/yordisprieto/Developer/straw-hat/javascript/fetcher/src',
  includeDeclarations: true,
  readme:
   '/Users/yordisprieto/Developer/straw-hat/javascript/fetcher/README.md' }
```

I added a `console.log` around here https://github.com/TypeStrong/typedoc/blob/955c388eee386372fd5fa88302423083b7813110/src/lib/cli.ts#L56

So I am getting this output

```javascript
{ hasErrors: false, inputFiles: [ 'docs' ] }
```

But I dont think this is actually working.

When I use `typedoc --out ./docs ./src` command directly I get this output on the same line

```javascript
{ hasErrors: false, inputFiles: [ './src' ] }
```

Which as you can see it `docs` is not there, which is what I am expecting.

One, I am assuming that passing `inputFiles` in the config of `new CliApplication(config);` but I am not actually sure about it.

I need your support on figuring this out 😢

**Comment by Gerrit0** [comment]
That is certainly some odd behavior... I really can't say what's going on without more digging. However, I think I might have a good guess.

How are you calling your code? If you do something like `node file.js ./docs`, and use `CliApplication` then when the argument reader is called it will [check](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/readers/arguments.ts#L15) if this is called from the CLI and will parse `process.argv` as if you were running `typedoc ./docs`... which will set `./docs` to the input files.

If you are writing your own CLI, you should use the `Application` class instead. The [`CliApplication.bootstrap`](https://github.com/TypeStrong/typedoc/blob/master/src/lib/cli.ts#L51) method should show how you can use it.

I'm not actually sure why `CliApplication` is exported. It seems like it shouldn't be as it really can't be used by external code due to this behavior.

**Comment by yordis** [comment]
@Gerrit0 this is what I was trying to do https://github.com/straw-hat-team/straw-hat-cli/blob/master/src/common/commands/docs.js

I commented everything out since I got nowhere with it.

The reason I was using `CliApplication` is that of this line https://github.com/TypeStrong/typedoc/blob/7424d9705dae528e4ec111a176e3c3d91364f8e5/src/lib/cli.ts#L68

Somehow you get the `inputFiles` which I thought it was a regex or something like that but it is actually an array of files (correct me if I am wrong)

Since the `CliApplication` automatically somehow figure out that list I just used the class.

Even if I use `Application` I think I will be in the same position since the there is no documentation for `options` and I keep getting this weird behavior.


Ideally I would love to call the function with some `inputFiles` regex or array (I would prefer regex) and figure out the list for me.

**Comment by yordis** [comment]
@Gerrit0 so do you know how I could get the `inputFiles` back without having to code that part using `Application`?

**Comment by Gerrit0** [comment]
I think I might have misunderstood your goal, the `result.inputFIles` that the CLI class uses is a result of parsing the command line options to find entry files / directories. When using TypeDoc programatically, it's expected that you provide these.

In the case of `typedoc --out ./docs ./src`, `result.inputFiles` would just be `['./src']` and the `expandInputFiles` function will be used to get all the ts files within that directory.

Assuming I understood `resolveApp` correctly, your commented out code looks like it should work, though I haven't actually run it.

**Comment by yordis** [comment]
> result.inputFiles would just be ['./src'] and the expandInputFiles

Oh so I could bypass `bootstrap` function call since I could just call `expandInputFiles` with my config.

Niiice I was misunderstanding who was doing what and how.

THANKS  A LOT, will try out tomorrow and let you know

**Comment by yordis** [comment]
@Gerrit0 that works! 👏 👏 👏 👏 👏 👏 👏 👏 👏
