### ISSUE TITLE
Feature request: Support jsdoc style typescript comments in js files

### ISSUE THREAD

**Issue by bendtherules** [TypeStrong/typedoc#911]
Typescript supports a way to add jsdoc-style comments (that indicate type information) within js files (https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript). This is quite a valid way to use Typescript without moving to ts files.

But these files don't seem to get picked up or processed by typedoc to generate relevant documentation. Is it possible to support this?
(TS compiler api should already have ways to understand this comments, the way VSCode does)

**Comment by aciccarello** [comment]
@bendtherules TypeDoc should already support this? Are you passing the `allowJS` compiler option? If so, please let us know how we can reproduce your issue. Thanks!

**Comment by bendtherules** [comment]
Repro repo: https://github.com/bendtherules/repro-typedoc-issue-jsdoc/tree/without-ext-types

Trying to run: `npx typedoc --tsconfig ./tsconfig.json --out ./docs ./src/`

But it doesn't have any methods of Calculations in the output.
In master branch, the ,js files import stuff from other .ts files, whose types do show up in output (but not from js files).

**Comment by bendtherules** [comment]
Hi, just checking back.

Is this problem reproducible on someone else's end? 
If this doesn't work, is there any simplified example which is known to work?

**Comment by aciccarello** [comment]
I was able to get it to work with some slight modifications.

I changed the input file to explicitly be the js file. The TS compiler was complaining about overriding the file so I added an `outDir` to the `tsconfig.json`. With this configuration TypeDoc was able to generate the `Calculations` docs.

```bash
npx typedoc --tsconfig ./tsconfig.json --out ./docs ./src/index.js
```

![_users_aciccarello_documents_code_typedoc_issues_repro-typedoc-issue-jsdoc_docs_modules__sip_ html ipad](https://user-images.githubusercontent.com/11273838/49700787-2f2ed800-fb98-11e8-80cd-fa355969c72f.png)

**Comment by bendtherules** [comment]
Thanks, this works. Forgot to test it out earlier.

Should I keep it open as it should automatically pick that up? Or is it outside typedocs's scope (and something that typescript should do itself) ?

**Comment by bendtherules** [comment]
`outDir` is not the solution, just something needed to make TS not throw an error. It is not used for any actual output.

None of the variations of providing folder name like `./src/` works. (It creates empty index, doesn't catch inner files).

**Comment by bendtherules** [comment]
Ideally though, files should be automatically picked up using include/exclude provided in tsconfig.json.

Providing it in CLI shouldn't be required for js, as it's not required for ts.

**Comment by Gerrit0** [comment]
Well, it was fairly easy to track down why js files weren't included when specifying a directory - `expandInputFiles` doesn't check for the `.js` extension.

This will fix your original command, but I'm not sure if the input files will be picked up automatically as ts files apparently are (never realized this...)
