### ISSUE TITLE
Extended properties of abstract classes are wrong

### ISSUE THREAD

**Issue by krlwlfrt** [TypeStrong/typedoc#912]
In our project, we have an abstract class that is extended by some classes where the properties of the abstract parent class are overriden. These overriden values are not visible in the generated Typedoc documentation and instead the values of the extended properties are shown.

* [Documentation of abstract parent class `SCAbstractRoute`](https://openstapps.gitlab.io/core/classes/_lib_index_d_.scabstractroute.html#errornames)
* [Code of abstract parent class `SCAbstractRoute`](https://gitlab.com/openstapps/core/blob/master/src/core/Route.ts#L83)
* [Documentation of extending class `SCIndexRoute`](https://openstapps.gitlab.io/core/classes/_lib_index_d_.scindexroute.html#errornames)
* [Code of extending class `SCIndexRoute`](https://gitlab.com/openstapps/core/blob/master/src/core/protocol/routes/INDEX/IndexRequest.ts#L29)

I'd expect the generated documentation for `SCIndexRoute` for its property `errorNames` to show the values of the extending class.

**Comment by krlwlfrt** [comment]
See #83.

**Comment by Gerrit0** [comment]
The linked project structure has changed, so this isn't easily reproducible. I suspect it has been fixed with the 0.20 beta. If still having issues, please open a new issue.
