### ISSUE TITLE
typedoc examples in the wild ? 

### ISSUE THREAD

**Issue by orenmizr** [TypeStrong/typedoc#918]
who uses typedoc today ? where are the links ? (huge selling point)

**Comment by orenmizr** [comment]
thanks for the response. i wanted to see how known companies are using typedoc. it speaks to its capablities and adoption. there is a lot of information in the default template, so i wanted to see how others customize it to their own needs.

**Comment by aciccarello** [comment]
Some that I've seen

- [UI Router](https://ui-router.github.io/ng1/docs/1.0.0-rc.1/)
- [Morphism](https://morphism.now.sh/)
- [Babylon](https://doc.babylonjs.com/api/)
- [OpenVidu](https://openvidu.io/api/openvidu-browser/index.html)

There are also some tools that use the JSON model outputted by TypeDoc to generate their own documentation

- [DocFx](https://dotnet.github.io/docfx/tutorial/universalreference/gen_doc_for_ts.html)
