### ISSUE TITLE
using --includeDeclarations  when there are no .d.ts declaration files causes typedoc to silently hang forever

### ISSUE THREAD

**Issue by 9oelM** [TypeStrong/typedoc#919]
# The problem
Yes I have looked at #913 and the comment by @aciccarello also. But I still find that `--includeDeclarations` option would make typedoc hang like forever without any warnings **if there are no d.ts declaration files**. 

## Context
I was planning to add `d.ts` files later on but I did not want to edit typedoc config later too, so I just added `includeDeclarations` option to the config (`typedoc.js`). But the problem was `typedoc` would hang somewhere in its process, probably looking for `.d.ts` files. 

I tested this problem each time with the option specified on cli (by specifying `--includeDeclarations`) and in `typedoc.js` in rootdir.

## Reproducing the problem
You can test directly from `c9.io` [here](https://ide.c9.io/j031/typedoc-test):
(on c9 cli)
```
typedoc --out docs test.ts
```

or git clone this repo to test it out:
```
git clone https://github.com/9oelM/typedoc-test.git
cd typedoc-test
npm install
typedoc --out docs test.ts
```

this is going to show something like
```                                                                                                                 
Using TypeScript 3.1.6 from /home/ubuntu/workspace/node_modules/typedoc/node_modules/typescript/lib
```
and hang forever. 

This is the content of the config file used:
`typedoc.js`
```js
module.exports = {
  module: "commonjs",
  mode: "modules",
  target: "es5",
  out: "docs/",
  name: "justTesting",
  exclude: ["node_modules/**", "**/"],
  includeDeclarations: true,
}
```

I waited for several minutes but it won't work. It is even clearer that `includeDeclarations` option is the problem when you test it out without it (just exclude the last line from the above config):

```
$ typedoc --out docs test.ts 

Using TypeScript 3.1.6 from /home/ubuntu/workspace/node_modules/typedoc/node_modules/typescript/lib
Rendering [========================================] 100%

Documentation generated at /home/ubuntu/workspace/docs
```
It would work without `includeDeclarations` specified.

# So..
I just hope there would be some kind of safety measures in case users put `includeDeclarations` option in advance of creating `d.ts` files, or by any other ignorance because it is `typedoc` is going to hang forever and not going to tell you the problem!

**Comment by aciccarello** [comment]
Thanks for the detailed report, I've merged this with #913
