### ISSUE TITLE
Support Typescript last version or support choosing local typescript bin

### ISSUE THREAD

**Issue by bios21** [TypeStrong/typedoc#924]
Currently, when executing the `typedoc`binary, it tries to compile Typescript with shipped version of Typescript (3.1.x now) ;
When developing with new Typescript's features like generic object spread (https://github.com/Microsoft/TypeScript/pull/28234) ; the shipped compiler is not able to handle those new functionalities.

Is it possible to, in a first time, ship the latest version of Typescript ?
In a second time, be able to use the local version of Typescript of a project ?

**Comment by aciccarello** [comment]
1 should be closed by #922
2 will hopefully be added in a 1.0 release

**Comment by taoqf** [comment]
It really do not need typescript as a dependence, I prefer move typescript into devDependencies, what do you think? @aciccarello

**Comment by bios21** [comment]
I don't talk about dependency. I talk about configuration needs. Or even peerDependencies

**Comment by Gerrit0** [comment]
1. [v0.14.0](https://github.com/TypeStrong/typedoc/releases/tag/v0.14.0) has been released, with the latest compiler version. 
2. Is being tracked in #880, we still rely on a lot of internal APIs, so it isn't feasible yet.

As 1 has been addressed and 2 is being tracked in another issue, closing.
