### ISSUE TITLE
Option to exclude only unused externals

### ISSUE THREAD

**Issue by rochdev** [TypeStrong/typedoc#926]
Right now, when setting the `excludeExternals` option to true, all externals are excluded, even the ones that are actually used (i.e. subclassed). When setting it to false, all externals are included, regardless of if they are used or not.

There should be an option to exclude only externals that are not actually used. In my opinion this should even be the default, since I think in most cases it's the expected behavior.

**Comment by aciccarello** [comment]
This is a good idea but there are some complications. It would need to be coupled with larger improvements to the Internal/External distinction. I've opened #927 to track tasks for larger improvements.

The complicated part of this is knowing how to trim the dependency tree. Additionally, an imported external could import a whole tree of types even if they aren't used directly. So in many cases the externals listed would still be much longer than expected. I think the easiest way to handle large amounts of externals is to make sure that the externals aren't listed in the generated docs but you can still link to them if needed. Other suggestions are welcome too.

**Comment by rochdev** [comment]
Maybe an option to include specific externals then? For my use case it's only a single external that I need to include.

**Comment by Gerrit0** [comment]
You might be able to use [typedoc-plugin-internal-external](https://www.npmjs.com/package/typedoc-plugin-internal-external) to mark that external as internal.

(Not sure this will work, but if it is in an `@types` package, try declaration merging and adding the `@internal` marker there)

**Comment by rochdev** [comment]
Thanks for the suggestion @Gerrit0! Unfortunately, I'm using the "file" mode and when converting the external to an internal the classes get mixed up with the real internal ones. I'll try to do some more testing with "modules" mode, but so far only "file" mode gave me the correct result for internals.

**Comment by metaa** [comment]
Any new insights here?
I'd like TypeDoc to include externals like `PathLike` that I do use, but exclude those thousands of other declarations I don't rely on.

**Comment by Gerrit0** [comment]
Unfortunately there is way more work to be done here than anyone has time. I don't think anyone's touched this issue recently. Feel free to give solving it a shot if you have the time.
