### ISSUE TITLE
Exclude Internal API from documentation

### ISSUE THREAD

**Issue by yordis** [TypeStrong/typedoc#929]
As a user, I should be able to exclude internal code from the generated documentation.

Internal code is the code that it is not exported in the files. If the user didn't export specific code snippet, like variables, or functions, probably means that it is not part of the public API so I would like to exclude those from the documentation.

Currently, I have to be putting `@hidden` everywhere in my source code, which makes the source code a little bit ugly.

Maybe introduce a flag that will allow me to do this.

**Comment by aciccarello** [comment]
Thanks for the input. This would be covered by #639 so I'll close this as a duplicate.
