### ISSUE TITLE
Turn off autogenerate

### ISSUE THREAD

**Issue by KayHS** [TypeStrong/typedoc#937]
Hi,

Is there a way to prevent typedoc from autogenerating documentation that you have no explicitly set doc strings for.

For example i only want it to generate documentation if i have something like the following above a fucntion call.

```
   /**
     * Represents a book.
     * @constructor
     * @req {string} title - The title of the book.
     * @res {string} author - The author of the book.
     */
```

I don't want it to autogenerate based on my code, but only when i explicitly define these comments.

**Comment by aciccarello** [comment]
Hello @KayHS, TypeDoc does not currently support this use case. This should be possible with a plugin, however unfortunately we don't have documentation on how to create plugins at the moment. You might be able to learn from an [existing plugin](https://github.com/TypeStrong/typedoc#plugins).

**Comment by aciccarello** [comment]
I'm going to close this as I don't anticipate adding this feature. You may want to use the [`@ignore` tag](hidden-and-ignore) to avoid generating documentation on specific comments. Feel free to comment and ask questions.
