### ISSUE TITLE
Adding a Code of Conduct

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#939]
Following the work on #928, it would be worthwhile to consider adding a Code of Conduct. Some good information on CoCs can be found on the [Open Source Guide website](https://opensource.guide/code-of-conduct/).

A suggested option which I would support is the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct). The only problem I see it that the TypeDoc project does not currently have an email address for those who would like to report a CoC violation.

Any thoughts?

**Comment by 9oelM** [comment]
1. Does the email address have to be official? i.e. typedoc@gmail.com (X) report@typedoc.org (O)
2. Who would be in charge of taking care of the emails if we have an email address?

**Comment by Gerrit0** [comment]
We have one of these now - it points people to my email dedicated to this project. This is an improvement, but not perfect. If someone has a problem with me... there's nobody to contact since there isn't another active maintainer of TypeDoc.
