### ISSUE TITLE
0.13 supported config paths do not work in 0.14.0

### ISSUE THREAD

**Issue by Roaders** [TypeStrong/typedoc#942]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
My `--options` path is:

`node_modules/my-config-project/config/typedoc.config.json`

in 0.13 this worked fine

## Actual Behavior

In 0.14 this no longer loads the config, This makes 0.14 a breaking change despite not being marked as such and has broken 60+ projects...

## Environment
  - Typedoc version: 0.14
  - Node.js version: 8.11.1
  - OS: windows

**Comment by aciccarello** [comment]
What CLI string are you using to invoke TypeDoc? Are you specifying the input files in a file or just the `--options` argument?

I think this may be the same as [#604 (comment)](https://github.com/TypeStrong/typedoc/issues/604#issuecomment-452552348). I closed that issue but as I think about it more that case should be working. We'll take a look at the argument parsing and we should be able to fix this in a patch release.

**Comment by macbric** [comment]
Same behavior with _--tsconfig_. An error is thrown since version 0.14. Version 0.13 is working.
> Error: The tsconfig file  does not exist.

**Comment by aciccarello** [comment]
Fix released in v0.14.1
