### ISSUE TITLE
Typedoc website SSL Cert is for localhost

### ISSUE THREAD

**Issue by jwulf** [TypeStrong/typedoc#950]
![screenshot from 2019-01-17 11-25-05](https://user-images.githubusercontent.com/406975/51289080-9d45a500-1a4a-11e9-88e8-c012687f169b.png)
![screenshot from 2019-01-17 11-25-14](https://user-images.githubusercontent.com/406975/51289088-9fa7ff00-1a4a-11e9-953e-227e29a89b9c.png)

**Comment by Gerrit0** [comment]
`typedoc.io` isn't the website for TypeDoc, we have https://typedoc.org/

**Comment by aciccarello** [comment]
Yeah, sorry. TypeDoc used to have `typedoc.io` but at  some point we lost the domain. I'm not sure why we couldn't get it (I wasn't involved in that decision), but everything was migrated to `typedoc.org`.

Is there a bad link somewhere that we can correct?
