### ISSUE TITLE
feat: Add tag like @throws to document possible errors thrown by the following method

### ISSUE THREAD

**Issue by diosney** [TypeStrong/typedoc#952]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

Currently there is no apparent way to documents thrown errors, like `@throws` do in JSDoc.

## Suggested Solution

Add support for a tag similar to `@throws` where the error can be stated, along with a brief description of it.

**Comment by diosney** [comment]
Well, it does output a `throws` block like the `remarks` one, so it seems that it does support it.

(I should check it before adding the issue, sorry for that).

Where can I find a typedoc cheatsheet with its supported tags and format? (besides @microsoft/tsdoc ones I mean.)

**Comment by diosney** [comment]
For the next ones like me searching for this, I solved it by doing something like:

If `InitializationError` and `SomeOtherErrorClass` are defined as classes extending `Error`, which is very common in custom code, you just can do the following, and they will be hiperlinked:

```
     * @throws [[InitializationError]] Some description here.
     * @throws [[SomeOtherErrorClass]] Another description here.
```
If not, maybe something like:

```
     * @throws InitializationError Some description here.
     * @throws SomeOtherErrorClass Another description here.
```
or

```
     * @throws *InitializationError* Some description here.
     * @throws *SomeOtherErrorClass* Another description here.
```

**Comment by Gerrit0** [comment]
TypeDoc's default theme will render any tag that it doesn't recognize, so you could even use `@myCustomTag some text` and it would show up.

I believe there are only a few tags which are explicitly supported:

- public
- private
- protected
- event
- hidden / ignore
- typeparam
- param
- preferred
- returns

(There is also a `resolve` tag, which I still don't know what it does, and it isn't documented anywhere)

**Comment by diosney** [comment]
Wow! Thanks!
