### ISSUE TITLE
Use SSL in "Generated by" links

### ISSUE THREAD

**Issue by dusekdan** [TypeStrong/typedoc#955]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

When links crediting the TypeDoc for generating documentation are created, the `<a>`  tag points to _http_ address, while it would certainly be better off pointing towards existing _https_ version, like so.

```
<p>Generated using <a href="http://typedoc.org/" target="_blank">TypeDoc</a></p>
```

Please consider the fact that it is possible to visit _http_ version of the address due to missing redirection and the lack of [strict-transport-security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) header. Judging by you having the https version of your website, you do understand the benefits of it and so I will not elaborate more.

## Suggested Solution

- [ ] Start uniformly using the https links (you have valid certificate) in both code and documentation ([see all the references to http only link](https://github.com/TypeStrong/typedoc/search?q=http%3A%2F%2Ftypedoc.org&unscoped_q=http%3A%2F%2Ftypedoc.org))
- [ ] (Ideally) Implement strict-transport-security and redirection to protect requests on http links of your domain.

Thank you for your time and looking into this.

**Comment by Gerrit0** [comment]
Related, #814, this would be a good change to make.

**Comment by aciccarello** [comment]
I'm not aware of a way to add the Strict-Transport-Security header via github pages but the https redirect has been enabled. Only remaining task then would be to fix the links our source.
