### ISSUE TITLE
Cannot find documentation of the option file format

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#962]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

TypeDoc does allow to specify an option file using the `--options` command line parameter but I cannot seem to find the documentation of the option file format.

## Suggested Solution

There is either no documentation of the option file format or it is relatively hard to find and a link to it next to the explanation of the command line argument would be most helpful.

**Comment by aciccarello** [comment]
Sorry that it is not better documented. I started working on some website improvements that should help with this but got stalled.

**Comment by diosney** [comment]
@doberkofler 

In the meantime, you can use something like:

- in `package.json`:

```
"docs": "npx typedoc --options typedoc.config.json",
```
- in the `typedoc.config.json`:

```
{
  "name"              : "SDK",
  "out"                  : "./docs",
  "mode"              : "file",
  "src"                  : "./src",
  "exclude"           : "./src/demo/**/*",
  "theme"             : "default",
  "readme"           : "./README.md"
}

```

**Comment by aciccarello** [comment]
@doberkofler The [website](https://typedoc.org/guides/installation/#json-configuration) has been updated.

I would like to see something similar to the `--help` option to collect and print all the available options in JSON format with their correct types.

**Comment by chharvey** [comment]
Please also include **default values**. For example, does `--mode` default to `"file"` or `"modules"`?

**Comment by Gerrit0** [comment]
Docs with all TypeDoc options + their defaults now exist - https://typedoc.org/guides/options/

The JSON format accepts the same keys. For backwards compatibility, `src` in `typedoc.json` will be aliased to `inputFiles` for a release or two, getting a warning next release and being removed later.
