### ISSUE TITLE
Recognize more comment styles

### ISSUE THREAD

**Issue by adrianheine** [TypeStrong/typedoc#963]
Currently, since typedoc uses `getJSDocCommentRanges` for retrieving comments, line comments and block comments that don't start with `/**` are not recognized:

```ts
class X {
  /**
   * works
   */
  x() {
  }

  /*
   * doesn't work
   */
  x2() {
  }

  // doesn't work
  x3() {
  }
}
```

It should be fairly easy to remove this limitation by copying [getJSDocCommentRanges](https://github.com/Microsoft/TypeScript/blob/v2.1.4/src/compiler/utilities.ts#L631) without the filtering at the end.

**Comment by adrianheine** [comment]
If you're worried about that, this could still be an option.

**Comment by aciccarello** [comment]
Thanks for the suggestion, however I agree with @Gerrit0 that we should only document comments explicitly designated with `/**`. Microsoft's tsdoc project follows a similar convention.

I'm going to close this for now but feel free to continue commenting.

**Comment by adrianheine** [comment]
Hm, that's a pretty arbitrary limitation you want to keep there.

**Comment by aciccarello** [comment]
The convention is supposed to give control over what comments show up in documentation. I consider it a fairly standard convention to use `/**` to mean "I want this documented".

For example, there may be situations like the following where you would want to leave a comment but not have that documented.
```typescript
class Foo extends Bar {
  someProp: string;

  // Override parent props
  inheritedVal1 = true;
  inheritedVal2 = true;
}
```

Could you explain the use case for documenting other comments?

**Comment by adrianheine** [comment]
Yes, and I'm just asking for an option that supports all comment styles, disabled by default. My use case is https://github.com/codemirror/codemirror.next, in which we use line comments.

**Comment by aciccarello** [comment]
True, I agree that this would likely be disabled by default. However, I'm not sure that it is worth the extra complexity. Could you explain why you want to document line comments?

**Comment by adrianheine** [comment]
Because that's our comment style for all kinds of comments.

**Comment by svicalifornia** [comment]
I second this request.

**Comment by adrianheine** [comment]
btw, we've written https://github.com/adrianheine/gettypes/ and use that together with https://github.com/marijnh/builddocs. It's highly opinionated, though.
