### ISSUE TITLE
A way to document "export from" types?

### ISSUE THREAD

**Issue by gwynjudd** [TypeStrong/typedoc#964]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
I've got something like this:

[picklist/index.ts]
```ts
/**
 * @module picklist
 */

export * from './controller';
export * from './shims';
export * from './view-item';
export * from './view';
```

```ts
import * as Picklist from 'picklist/index';

export interface Foo {
  Picklist: typeof Picklist;
}
```

The question is, how to document [Foo.Picklist]? Currently it is coming out like this in the docs:

![image](https://user-images.githubusercontent.com/314188/52096777-002f6280-262d-11e9-8f16-0799aa1f2557.png)

There is no documentation generated for the Picklist type.

By comparison, types that are generated without using the "export from" syntax don't have this problem.

## Suggested Solution

Don't really know to be honest. Seems like it could be related to #516.

**Comment by Gerrit0** [comment]
In 0.17.0 Picklist is shows as `typeof Picklist` (it doesn't have a link, but that's a separate issue that I'm looking into and not specific to this use, quite a few reference types seem to be broken)

![image](https://user-images.githubusercontent.com/19329837/76720067-5e1fec00-6701-11ea-9d0d-e562464321e8.png)

The support for export declarations was greatly improved in 0.16, and slightly extended in 0.17
