### ISSUE TITLE
License of Assets

### ISSUE THREAD

**Issue by anttipirila** [TypeStrong/typedoc#969]
When apidoc is generated assets are copied next to the generated documents. These assets seems to be licensed under Apache Lisence. The license file and appropriate copyright statement for assets should be included to the assets directory.

**Comment by Gerrit0** [comment]
So, this always seemed rather weird to me - putting a license in the assets folder would be confusing as some user data, which is not owned by typedoc, is also copied into the assets folder. I recently did some searching and found the following.

https://github.com/swagger-api/swagger-codegen/issues/2963#issuecomment-258559506

Which makes sense for the generated files, certainly, but doesn't really say anything about the assets... practically, I'm not sure that forcing all of typedoc's consumers to copy an extra file around is worthwhile. Other documentation generators also do not do this extra copying. We haven't had any instances of abuse that I'm aware of in the history of the project, and making every generated site larger in an attempt to preempt this seems like a bad idea. The Creative Commons foundation has a snippet on their website which I think supports this:

>  Creative Commons licenses are copyright licenses, enforceable by law. However, enforcement of the licenses should be a way of making sure that creators are treated fairly, not a scheme to trap well-meaning reusers who would be willing to correct errors. If users are afraid to use CC-licensed material because the cost of error is unfairly high, CC’s goals are not met. - [CC](https://creativecommons.org/license-enforcement/)

With this in mind, I'm going to close this as a won't implement. If some lawyer comes in and tells me I'm wrong, well, will deal with that in the event that it happens.
