### ISSUE TITLE
Add minimal theme example to the website

### ISSUE THREAD

**Issue by aciccarello** [TypeStrong/typedoc#971]
_Migrated from TypeStrong/typedoc-site#5_

The website used to demonstrate both the default theme and the minimal theme. See https://github.com/TypeDoc/themes

Demonstrating the minimal theme would help users see that the output is flexible.

**Comment by ZbigniewRA** [comment]
http://typedoc.io/themes shows only `404 Not Found`.

**Comment by Gerrit0** [comment]
typedoc.io is no longer used by this project. https://typedoc.org is what we use.
