### ISSUE TITLE
Add links to headers

### ISSUE THREAD

**Issue by Gerrit0** [TypeStrong/typedoc#972]
It is possible to link to a specific part of the page using anchors, for example: https://typedoc.org/guides/doccomments/#files

However, getting the link requires either guessing at the anchor, or viewing the source to grab the header's ID. It would be great if anchors were clickable like in the [ts-morph](https://dsherret.github.io/ts-morph/) documentation

**Comment by igncp** [comment]
Hi, I would like to take over this issue if ok 🙂 

I have it working here: https://github.com/TypeStrong/typedoc/compare/master...igncp:feat/add-links-in-rendered-content?expand=1

But still needs some styling, testing and polishing. Cheers

**Comment by Gerrit0** [comment]
Looking good! I'm kind of surprised that works, I thought the header had to have an ID to be linked to in the page.

**Comment by igncp** [comment]
Correct, using ID seems to be the recommended way to do this. Updated it, working but still not ready for PR. Thanks for the info.
