### ISSUE TITLE
Typedoc file discovery is different from TSC

### ISSUE THREAD

**Issue by rix0rrr** [TypeStrong/typedoc#974]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

When running TypeDoc, I expect it to find the same files that a run of `tsc` would.

## Actual Behavior

TypeDoc reimplements its own file discovery (even though TSC's can just be invoked as a library), and reimplements it poorly.

* When trying to exclude `node_modules` to avoid a giant tree crawl, TypeDoc is going to recurse into all directories, afterwards discarding all files that were found:

https://github.com/TypeStrong/typedoc/blob/master/src/lib/application.ts#L267

(The `isExcluded()` check could/should happen BEFORE recursing into subdirectories)

* TypeDoc *could* simply be calling `ts.parseJsonConfigFileContent()` to have JS return all filenames that are in scope of the current build, respecting `includes`/`excludes` that are already in the `tsconfig.json`.

Example: https://github.com/awslabs/jsii/blob/master/packages/jsii/lib/compiler.ts#L263

## Steps to reproduce the bug

For one, run in a directory with a mix of `.ts` and `.d.ts` files. TSC would know to only look at the `.ts` files, but TypeDoc doesn't.

Run in a directory with `{ "exclude": ["node_modules"] }` in the `tsconfig.json`. The directory is not ignored.

## Environment
  - Typedoc version: `HEAD`
  - Node.js version:
  - OS:

**Comment by aciccarello** [comment]
Thanks for the feedback. I would like to see TypeDoc align more with the typescript compiler and how tsc reads projects. Until then you will have to pass arguments like "exclude" to typedoc as well as TypeScript.

Could you explain the specific issue you are seeing with `.d.ts` files? Is the problem that your file links are pointing to the wrong source flies? It would be helpful if you could include how to reproduce this with the typedoc/typescript configuration you are encountering this with.

**Comment by Gerrit0** [comment]
Note: if you specify a tsconfig file with --tsconfig (and don't specify input files in the command) then TypeDoc will use the TS api to find source files

**Comment by jerry153fish** [comment]
Hi @aciccarello I can reproduce this one on

```
tsc version: 3.5.5
typedoc: 0.15.0
```

when specify with tsconfig file

#### tsconfig files 
```
    "extends": "./base-tsconfig.json",
    "references": [
        // prepend the common projects
        { "path": "../../WebCommon/typescript/util", "prepend": "true" }
     ]
```

tsc runs OK.
Typedoc fails to find the references all fails on 
` Cannot find namespace 'Util'.`

**Comment by Gerrit0** [comment]
I'm willing to bet we need to do something special (or at least different from when TypeDoc was mostly written years ago) in order to support the `references` key, and currently we aren't.
