### ISSUE TITLE
20x slowdown compared to 0.11.x

### ISSUE THREAD

**Issue by alexdima** [TypeStrong/typedoc#975]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
Typedoc works as before, and takes reasonable time to execute.

## Actual Behavior
Typedoc is super super slow, going from 2.5s (v0.11.1) to 49s (v0.14.2).

## Steps to reproduce the bug

- save as `monaco.d.ts` - [monaco.d.ts.txt](https://github.com/TypeStrong/typedoc/files/2879629/monaco.d.ts.txt)
- run in PowerShell:
```
 Measure-Command {..\typedoc-0.11.1\node_modules\.bin\typedoc --mode file --out out --includeDeclarations --entryPoint monaco monaco.d.ts}
TotalMilliseconds : 2499.9106

Measure-Command {..\typedoc-0.13.0\node_modules\.bin\typedoc --mode file --out out --includeDeclarations --entryPoint monaco monaco.d.ts}
TotalMilliseconds : 44939.4815

Measure-Command {..\typedoc-0.14.2\node_modules\.bin\typedoc --mode file --out out --includeDeclarations --entryPoint monaco monaco.d.ts}
TotalMilliseconds : 48930.0364
```

## Environment
  - Typedoc version: 0.14.2
  - Node.js version: 0.15.1
  - OS: Windows

**Comment by aciccarello** [comment]
Thanks for the report. I wonder if this is a windows focused issue.

Related to #960

**Comment by Gerrit0** [comment]
I think this must be a windows issue, I haven't run into it. Thanks for the reproduction! Time to pull out `git bisect` and see what went wrong.

**Comment by Gerrit0** [comment]
`git bisect` says d4b2f56ca799cab3f3670c8301b51df34339e420 is the first bad commit, I haven't had time to look into what exactly the issue is.

**Comment by Gerrit0** [comment]
Finally getting back to this, and I still have absolutely no clue why updating to TS 3.x causes this major slowdown when compilation speed remains essentially constant.

The Chrome devtools simply can't handle TypeDoc when trying to parse the above file. I get a hard crash as soon as the profiling is complete, which is making this more difficult than it ought to be.

Even the built in profiler with `--prof` has issues, when trying to generate useful output from the log file with `node --prof-process --preprocess -j .\isolate-000002C68C42A0C0-v8.log | flamebearer` I get a ton of `Code move event for unknown code: 0x1ba..` errors. 

Despite this, I have managed to discover a few performance issues which let me reduce the runtime of the 20x slower code to 15x slower... which obviously isn't great. I'm still missing the core issue. Hopefully I'll be able to discover what exactly is happening with more investigation.

**Comment by Gerrit0** [comment]
Well, whatever the issue was... we're back to being pretty fast.

```
C:\Users\gtbir\Desktop\library-tests> measure-command { npx typedoc .\src\monaco.d.ts }
Rendering [========================================] 100%

...
TotalMilliseconds : 4750.1524
```
