### ISSUE TITLE
Installation failing using npm

### ISSUE THREAD

**Issue by rajasekharmekala** [TypeStrong/typedoc#976]
I am trying to install typedoc and i am getting the following error. Please suggest me how to fix it.

npm ERR! path \node_modules\highlight.js\tools\build.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '\node_modules\highlight.js\tools\build.js'

**Comment by sbrunner** [comment]
For us it's a blocking issue ...

**Comment by almadigabor** [comment]
Same here on 0.14.2

npm ERR! path \node_modules\typedoc\node_modules\highlight.js\tools\build.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '\node_modules\typedoc\node_modules\highlight.js\tools\build.js'
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by faeb187** [comment]
same here:
node 10.15.1
npm 6.8.0

**Comment by WindWu** [comment]
Same here on version 0.14.2. 
It looks the highlight.js 1.15.1 breaks the backward compatibility. My workaround is to install the highlight.js to specific version "9.13.1", which is same as the one used by typedoc

**Comment by shhider** [comment]
Same!

I installed `highlight.js@9.13.1` manually just now, and re-install again. It works for me, you can try it.

**Comment by dolezel** [comment]
https://github.com/highlightjs/highlight.js/issues/1984

**Comment by slowpokex** [comment]
I have the same issue, but I can't good solution for resolving

**Comment by PaulShestakov** [comment]
Same issue

**Comment by chesminsky** [comment]
SAME

**Comment by aciccarello** [comment]
It seems like this is mainly an issue if you have another dependency which depends on highlight.js@1.15.1. One workaround would be to use some of the [new features](https://twitter.com/maybekatz/status/1098378194745344000) in npm@6.8 and use the time machine.

I plan on updating all dependencies when I push the next release.

**Comment by vamship** [comment]
> It seems like this is mainly an issue if you have another dependency which depends on highlight.js@1.15.1. One workaround would be to use some of the [new features](https://twitter.com/maybekatz/status/1098378194745344000) in npm@6.8 and use the time machine.
> 
> I plan on updating all dependencies when I push the next release.

I get the same error when I try `npm install typedoc` in a brand new directory, with no other dependencies.

I'm using npm version 6.8.0. Here is the actual result:
```
npm install typedoc
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN enoent ENOENT: no such file or directory, open '/.../package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

npm ERR! path /.../node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/.../node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /.../_logs/2019-02-25T15_19_56_137Z-debug.log
```

**Comment by vamship** [comment]
Also, it appears that the new features that @aciccarello is referring to are in the next release of npm (which is currently in pre-release).

https://npm.community/t/release-npm-6-9-0-next-0/5553?u=zkat

For the short term, publishing a new version of typedoc with updated dependencies will help us a lot!

**Comment by chharvey** [comment]
#977 should temporarily work around this issue until highlightjs/highlight.js#1984 is fixed. Could project maintainers take a look and make additional commits as necessary?

**Comment by aciccarello** [comment]
Highlight.js v9.15.5 has been released so this issue should be resolved.
