### ISSUE TITLE
[Question] How to change code highlighting syntax theme?

### ISSUE THREAD

**Issue by rockmandash** [TypeStrong/typedoc#980]
### Hello, thank you for this amazing and wonderful tool!!
Please see the image below.
![image](https://user-images.githubusercontent.com/7580792/53786614-30815e00-3f57-11e9-9ca6-d09446de5f67.png)
I have create a method and export it, I use jest test to tell my user how to use it.
I know that `typedoc` use [highlight.js](https://highlightjs.org/) to highlight the syntax, and I know that [highlight.js](https://highlightjs.org/) support several  code syntax highlighting theme like `monokai` or `dracula`, etc...
#### How can I change my generated doc to use different syntax highlighting theme?
Thank you very much!!

**Comment by Gerrit0** [comment]
There isn't any functionality for this in the default theme yet, it seems like a reasonable request. PR welcome :)

**Comment by aciccarello** [comment]
I'm thinking about what's the best way to support this and I think allowing arbitrary CSS to be added is the easiest approach. The highlight js theme isn't very big so the cost of overriding the styles would be small.

The problem I'm struggling with is "how configurable should the theme be?". The theme is easy to fork (if you know how to point typedoc to it) so I don't want to add too many flags for theming.

**Comment by rockmandash** [comment]
Maybe no theme at all, let `typedoc` generate a `JSON` that `represent the whole website`.

So the people who wants totally different theme can do whatever they want in the `front-end`.

**Comment by Gerrit0** [comment]
>Maybe no theme at all, let `typedoc` generate a `JSON` that `represent the whole website`.

You should already be able to do this by outputting JSON, is there something missing that prevents this workflow?

**Comment by rockmandash** [comment]
@Gerrit0 OMG, that's a hidden feature! Thank you!

**Comment by Gerrit0** [comment]
This is possible now with `--highlightTheme`, run `typedoc --help` to get a list of available Shiki themes.

**Comment by bjorn** [comment]
For those wondering where the `--highlightTheme` option went, it was split into `--lightHighlightTheme` and `--darkHighlightTheme` in typedoc 0.22.
