### ISSUE TITLE
Support custom comments for function type literals

### ISSUE THREAD

**Issue by jasongerbes** [TypeStrong/typedoc#983]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

Typedoc should properly interpret comments for the parameters and return type of function type literals.

## Actual Behavior

Typedoc displays the parameters and return type for the function type literal, but the comments provided are incorrectly placed.

## Steps to reproduce the bug

Given the following function type literal:
```ts
export type Validator = (value: any) => boolean;
```

Typedoc automatically generates the following documentation:

![image](https://user-images.githubusercontent.com/13686180/53990962-55abe180-418e-11e9-9dde-c94d033df37b.png)

Adding comments to the type declaration:

```ts
/**
 * A validator function.
 * @param value The value to be validated.
 * @returns `true` if the value is valid.
 * @returns `false` if the value is invalid.
 */
export type Validator = (value: any) => boolean;
```

Results in the following incorrect documentation:

![image](https://user-images.githubusercontent.com/13686180/53991270-15009800-418f-11e9-853e-7ddd57e1fc85.png)

## Environment
  - Typedoc version: v0.14.2
  - Node.js version: v10.15.0
  - OS: Windows 10

**Comment by fenyiwudian** [comment]
Hey man, I have the same needs,after many attempts, I finally commented like this and succeeded
```typescript
/**
 * commments for MyFunType
 */
type MyFunType = 
/**
 * @param title commonets for the title param
 * @param id comments for the id param
 * @returns comments for return value
 */
(title: string, id: number) => number;
```

The generated docs:
![image](https://user-images.githubusercontent.com/12799388/66534109-c9103a00-eb47-11e9-8cdc-c53feebb7a4b.png)

**Comment by DanielSWolf** [comment]
The syntax found by @fenyiwudian works great! But it took me some time and perseverance to find this issue. It would be great if this syntax was documented [in the TypeDoc documentation](https://typedoc.org/guides/doccomments).

**Comment by Gerrit0** [comment]
In 0.21.0, the OP's type alias renders as:

![image](https://user-images.githubusercontent.com/19329837/122498840-0c71ab80-cfad-11eb-9464-539c16064e35.png)
