### ISSUE TITLE
New line mangled in type signatures

### ISSUE THREAD

**Issue by Downchuck** [TypeStrong/typedoc#984]
Currently a new line is erased instead of either maintained or converted to a space in documentation; e.g.:
```
obj = {attr: {example: `Line one
Line two`}};
```

This shows up in documentation with the line space stripped:
```
{example: `Line oneLine two`}}
```

**Comment by yangxisosong** [comment]
Is there a solution to this problem now?

**Comment by Gerrit0** [comment]
Nope, nobody has picked it up to fix it yet. If you want to give fixing it a shot feel free!

**Comment by Gerrit0** [comment]
In 0.20.1, initializers are only printed if determined to be "simple" - which indirectly solved this issue since we don't consider template literals to be "simple"
