### ISSUE TITLE
@param and @return comments not coming up in documentation in the code

### ISSUE THREAD

**Issue by rohitghy5** [TypeStrong/typedoc#989]
On using @param and @return the comments are coming up in typedoc but not coming up in the 
code. Also the comments below it are also not displayed on using @
![Issue](https://user-images.githubusercontent.com/47653390/54576989-16984e80-4a20-11e9-88e8-a1c8b7c8fd73.JPG)
ll

**Comment by Gerrit0** [comment]
This isn't an issue with Typedoc - it's a problem with whatever editor / language service plugin you are using. Typedoc doesn't manage the intelligence you see in your editor, it just analyses your code to create documentation.

**Comment by rohitghy5** [comment]
thanks, seems issue with netbeans editor
