### ISSUE TITLE
@category not rendered properly

### ISSUE THREAD

**Issue by wangjie-agora** [TypeStrong/typedoc#991]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

Just tried the latest category tag, and the interfaces/functions/methods can be grouped on the index, but the @category tags and the category names still appear in the descriptions of each interface/function/method.

![image](https://user-images.githubusercontent.com/40165471/54742403-469c4900-4bfc-11e9-911e-1bf3cbd141de.png)

### The ts code

```
    /**
     * The Client object returned by the {@link createClient} method provides access to much of the core AgoraRTC functionality.
     * @category Core
     */
    interface Client
```

### Typedoc config

   ```
 "typedocOptions": {
        "mode": "file",
        "hideGenerator": true,
        "defaultCategory": "Miscellaneous",
        "categorizeByGroup": true,
        "includes": "types",
        "excludeExternals": true,
        "includeDeclarations": true,
        "target": "ES6",
}
```

## Environment
  - Typedoc version: 0.14.2
  - Node.js version: 11.12.0
  - OS: macOS Mojave

**Comment by Gerrit0** [comment]
> Typedoc version: 0.14.2

The category changes merged to master 2 days ago have not yet been released. Are you running on master or from npm?

**Comment by wangjie-agora** [comment]
> > Typedoc version: 0.14.2
> 
> The category changes merged to master 2 days ago have not yet been released. Are you running on master or from npm?

Running on master. I can get the index in the categories I set.

**Comment by Gerrit0** [comment]
Oh, gotcha, I misread the initial report. Yea, this is a bug. It should be a fairly simple fix, we just have to add `category` to the list of tags that won't be rendered.

**Comment by jonchardy** [comment]
Included a fix for this in https://github.com/TypeStrong/typedoc/pull/1008. It will remove the comment tag when the category is resolved.
