### ISSUE TITLE
Functions declared in ternary statement don't work properly

### ISSUE THREAD

**Issue by kbjr** [TypeStrong/typedoc#998]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

When defining a function in a ternary statement, I would expect the resulting documentation to show that there is a function. For example

```typescript
export const minOrMax = Math.random() < 0.5
  ? (a: number, b: number) : number => Math.max(a, b)
  : (a: number, b: number) : number => Math.min(a, b);
```

`minOrMax` here can be multiple things, but they are both functions and they both have the same signature, I would expect the docs to show a function called `minOrMax` with the signature `(a: number, b: number) : number`.

## Actual Behavior

The actual output shows the defined function as a variable with the whole source of the ternary as its "value". For an example, here was a function I tried to make to shim `Object.values()` in this way.

![image](https://user-images.githubusercontent.com/195127/55189995-43eda680-515c-11e9-9eda-1618078c44b0.png)

The source for the above is:

```typescript
export const objectValues: {<T>(object: Object<T>): T[]} = Object.values
	? <T>(object: Object<T>): T[] => Object.values(object)
	: <T>(object: Object<T>): T[] => {
		const keys = Object.keys(object);
		const values = new Array(keys.length);

		for (let i = 0; i < keys.length; i++) {
			values[i] = object[keys[i]];
		}

		return values;
	};
```

**Comment by Gerrit0** [comment]
In 0.20 the source under "expected behavior" produces:

![image](https://user-images.githubusercontent.com/19329837/103160109-5e6c0e00-478e-11eb-9b30-cb3826d02310.png)

The second example, modified slightly since I don't have an `Object<T>` type:

```ts
export const objectValues: {<T>(object: Object<T>): T[]} = Object.values
	? <T>(object: Object<T>): T[] => Object.values(object)
	: <T>(object: Object<T>): T[] => {
		const keys = Object.keys(object);
		const values = new Array(keys.length);

		for (let i = 0; i < keys.length; i++) {
			values[i] = object[keys[i]];
		}

		return values;
	};
```

Renders as:

![image](https://user-images.githubusercontent.com/19329837/103160157-d20e1b00-478e-11eb-8220-d2deb61b2133.png)
