### ISSUE TITLE
Way to hide "defined in"

### ISSUE THREAD

**Issue by fc** [TypeStrong/typedoc#999]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
Currently it will generate a link to the source code. Here it is where it is in the templates:
https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/partials/member.sources.hbs

I'm generating documentation for end users of a module but it's not necessary for them to have links back to our GitHub repos.

## Suggested Solution
Add an option to `typedoc` like `--hideSources` that will hide it.

Currently it is possible create a fork of the template to hide it if it's really needed.

**Comment by aciccarello** [comment]
I wonder if you can use this plugin to unset the URL. The template is able to handle missing URLs.

https://github.com/gdelmas/typedoc-plugin-sourcefile-url

**Comment by fc** [comment]
Thank you!

While it still has the link, it at least removes the URL to the GitHub repos.  It's an imperfect solution but without wanting to maintain a fork of a template it is acceptable for right now.  It may also be possible to achieve it by submitting a PR to that plugin.

This is the sourcefile-map.json I use (the replace value must be a string).
```
[
  {
    "pattern": "^",
    "replace": ""
  }
]
```

**Comment by domske** [comment]
Please reopen and add a official option to hide `defined in <link>`.

**Comment by rhuitl** [comment]
Yes please do... we have to customize the theme only for this reason, and now found that we got broken search because we forgot to update the theme when updating Typedoc...
